### ISSUE TITLE
OMPI host program using a shared object with OMPI instructions

### ISSUE THREAD

**Issue by saulocpp** [open-mpi/ompi#10032]
I have a main C++ program that includes some classes with MPI code and it works as it should. Then I decided to split these classes to a shared object and load it in runtime from the host program, which is only a testbed for what I do in the library.

The problem is that, when calling an imported function, `/usr/local/ucx/lib/libucs.so.0` complains about  `address not mapped to object at address (nil)` when running a scatterv or gatherv operating between host RAM and host pinned memory (CUDA).

The main program is:

```
#include <iostream>
#include <cstdint>
#include <dlfcn.h>
#include <mpi.h>

using namespace std;

int main(int argc, char **argv)
	{
	const uint32_t	SAMPLES	= 1010,
			VX	= 100,
			VY	= 201,
			VXY	= VX * VY;

	void *lib_handle = dlopen("./MPI_CUDA.so", RTLD_NOW | RTLD_GLOBAL);
	if(lib_handle == NULL)
		{
    		cerr << "Unable to load " << "./MPI_CUDA.so" << endl;
		return -1;
		}
	int (*User_Func)(const uint32_t, const uint32_t) = (int (*)(const uint32_t, const uint32_t)) dlsym(lib_handle, "User_Func");

	MPI_Init(&argc,&argv);
	
	User_Func(SAMPLES, VXY);

	MPI_Finalize();

	dlclose(lib_handle);

	return 0;
	}
```
It was compiled with: `nvcc --compiler-bindir /usr/local/bin/mpic++ -Xcompiler -Wall -o MPI_CUDA MPI_CUDA.cpp -ldl`
The library was compiled with `-fPIC` and `-ldl` in case this information is relevant.
The program defines a few constants, opens the shared object and imports one function that takes 2 uint32_t arguments. The MPI is then initialized, attempts to run the function, finishes MPI and closes the lib.

I am wondering what could be missing now that the MPI computation is in a shared object and no longer in the main program's space.

Any ideas are welcome.

**Comment by ggouaillardet** [comment]
I have no answer, but here are a couple of things to double check:
- does you `MPI_CUDA.so` depend on `libmpi.so`?
- do you observe the same behavior instead of `dlopen("MPI_CUDA.so"...)`, you make your `MPI_CUDA` binary depend on `MPI_CUDA.so`?

**Comment by saulocpp** [comment]
Good morning, Gilles, and thanks for your time looking into this.

Yes, both the .so and the executable depend on libmpi.so.
I will try what you suggest and also move the MPI initialization/finalization to the referred function being imported, instead of doing from the host program, just to see what happens and then report back.

**Comment by bwbarrett** [comment]
@saulocpp is this still an issue, or can we close this issue?

**Comment by saulocpp** [comment]
Brian, apologies for not providing a proper update.
Yes, it can be closed as I got a tip from Gilles over SO.
Thanks a lot.

**Comment by bwbarrett** [comment]
No problem; thanks for the quick response.  I hate closing tickets without confirmed resolution...
