### ISSUE TITLE
Running Docker container conflicts with OpenMPI?

### ISSUE THREAD

**Issue by gwiesenekker** [open-mpi/ompi#10041]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

The OpenMPI version is 4.1.2.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

I compiled it from a downloaded source/distribution tarball and installed it using ./configure followed by ./make install.

### Please describe the system on which you are running

* Operating system/version: 
Zorin OS 16
Linux amd1950x 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Computer hardware:
AMD 1950X 
* Network type: 
Wired
-----------------------------

## Details of the problem

I do not use mpi_run, my C-program launches the tasks using MPI_Comm_spawn which allows me to specify the number of tasks mpi_nslaves on the command-line. When the docker container (the latest tensorflow:latest-gpu-jupyter image) is not running I can launch up to 16 slaves as expected, but when the docker container is running on port 8888 (it is idle, so just waiting for input) I can only launch up to 7 slaves, when I try to launch 8 slaves the processes are starting but hang somewhere (exactly where would require some more troubleshooting). Any reason why a running docker container would conflict with OpenMPI?

Regards,
GW

**Comment by jsquyres** [comment]
I can't think of a reason offhand, but we would need more information to be able to help troubleshoot.

**Comment by ggouaillardet** [comment]
Are you running your C program inside or outside the container?
Are you sure there is no other services running in your container (for example, TensorBoard on port 6006)?

When the container is started, are some `iptables` automagically created and could they impact `mpirun`?

**Comment by gwiesenekker** [comment]
Hi,

I am running my C program outside the container. The container only exposes port 8888. The diff between netstat -an before and after starting the container is:
`
$ diff netstat-before-docker-sorted.out netstat-after-docker-sorted.out 
8a9
> tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN     
36a38
> tcp6       0      0 :::8888                 :::*                    LISTEN     
68a71
> unix  2      [ ACC ]     STREAM     LISTENING     424451   /run/containerd/s/3248803e55b5c6a269136e8e3b2a543cbbc48cc98abe43e44fed805e7c64a9eb
358a362,363
> unix  3      [ ]         STREAM     CONNECTED     415399   
> unix  3      [ ]         STREAM     CONNECTED     415402   /run/containerd/s/3248803e55b5c6a269136e8e3b2a543cbbc48cc98abe43e44fed805e7c64a9eb
361a367
> unix  3      [ ]         STREAM     CONNECTED     418361   
378a385,386
> unix  3      [ ]         STREAM     CONNECTED     430455   
> unix  3      [ ]         STREAM     CONNECTED     431685   /run/docker.sock
379a388,392
> unix  3      [ ]         STREAM     CONNECTED     436003   /run/docker.sock
> unix  3      [ ]         STREAM     CONNECTED     436005   /run/docker.sock
> unix  3      [ ]         STREAM     CONNECTED     438419   /run/containerd/containerd.sock.ttrpc
> unix  3      [ ]         STREAM     CONNECTED     440210   
> unix  3      [ ]         STREAM     CONNECTED     440211   
`
The diff between netstat -an before and after starting my c-program s:
`
gwies@amd1950x:~$ diff netstat-before-c-sorted.out netstat-after-c-sorted.out
5a6,22
> tcp        0      0 0.0.0.0:1024            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1025            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1026            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1027            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1028            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1029            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1030            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1031            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1032            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1033            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1034            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1035            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1036            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1037            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1038            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1039            0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:1040            0.0.0.0:*               LISTEN     
6a24
> tcp        0      0 0.0.0.0:56937           0.0.0.0:*               LISTEN     
10a29,63
> tcp        0      0 127.0.0.1:53776         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53778         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53780         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53782         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53784         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53786         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53788         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53790         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53792         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53796         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53798         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53800         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53802         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53804         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53806         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53808         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:53810         127.0.0.1:55555         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         0.0.0.0:*               LISTEN     
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53776         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53778         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53780         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53782         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53784         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53786         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53788         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53790         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53792         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53796         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53798         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53800         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53802         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53804         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53806         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53808         ESTABLISHED
> tcp        0      0 127.0.0.1:55555         127.0.0.1:53810         ESTABLISHED
14a68,87
> tcp        0      0 127.0.1.1:6818          127.0.0.1:58882         TIME_WAIT  
> tcp        0      0 172.17.0.1:1030         192.168.123.23:59109    TIME_WAIT  
> tcp        0      0 192.168.123.23:1024     192.168.123.23:34877    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:36373    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:36657    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:41235    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:42583    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:43097    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:44055    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:45325    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:46297    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:46835    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:48411    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:49579    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:52093    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:53215    ESTABLISHED
> tcp        0      0 192.168.123.23:1024     192.168.123.23:58435    ESTABLISHED
> tcp        0      0 192.168.123.23:1027     192.168.123.23:34613    ESTABLISHED
> tcp        0      0 192.168.123.23:34613    192.168.123.23:1027     ESTABLISHED
> tcp        0      0 192.168.123.23:34877    192.168.123.23:1024     ESTABLISHED
16a90,100
> tcp        0      0 192.168.123.23:36373    192.168.123.23:1024     ESTABLISHED
> tcp        0      0 192.168.123.23:36657    192.168.123.23:1024     ESTABLISHED
> tcp        0      0 192.168.123.23:41235    192.168.123.23:1024     ESTABLISHED
> tcp        0      0 192.168.123.23:42583    192.168.123.23:1024     ESTABLISHED
> tcp        0      0 192.168.123.23:43097    192.168.123.23:1024     ESTABLISHED
> tcp        0      0 192.168.123.23:44055    192.168.123.23:1024     ESTABLISHED
> tcp        0      0 192.168.123.23:45325    192.168.123.23:1024     ESTABLISHED
> tcp        0      0 192.168.123.23:46297    192.168.123.23:1024     ESTABLISHED
> tcp        0      0 192.168.123.23:46835    192.168.123.23:1024     ESTABLISHED
> tcp        0      0 192.168.123.23:47615    192.168.123.23:1024     TIME_WAIT  
> tcp        0      0 192.168.123.23:48411    192.168.123.23:1024     ESTABLISHED
17a102
> tcp        0      0 192.168.123.23:49579    192.168.123.23:1024     ESTABLISHED
18a104,105
> tcp        0      0 192.168.123.23:52093    192.168.123.23:1024     ESTABLISHED
> tcp        0      0 192.168.123.23:53215    192.168.123.23:1024     ESTABLISHED
19a107
> tcp        0      0 192.168.123.23:58435    192.168.123.23:1024     ESTABLISHED
375a464,465
> unix  3      [ ]         STREAM     CONNECTED     431073   
> unix  3      [ ]         STREAM     CONNECTED     431074   
388a479,486
> unix  3      [ ]         STREAM     CONNECTED     438750   
> unix  3      [ ]         STREAM     CONNECTED     438751   
> unix  3      [ ]         STREAM     CONNECTED     438833   
> unix  3      [ ]         STREAM     CONNECTED     438834   
> unix  3      [ ]         STREAM     CONNECTED     438835   
> unix  3      [ ]         STREAM     CONNECTED     438836   
> unix  3      [ ]         STREAM     CONNECTED     438837   
> unix  3      [ ]         STREAM     CONNECTED     438838   
395a494,499
> unix  3      [ ]         STREAM     CONNECTED     441928   
> unix  3      [ ]         STREAM     CONNECTED     441929   
> unix  3      [ ]         STREAM     CONNECTED     441930   
> unix  3      [ ]         STREAM     CONNECTED     441931   
> unix  3      [ ]         STREAM     CONNECTED     441932   
> unix  3      [ ]         STREAM     CONNECTED     441933   
403a508,515
> unix  3      [ ]         STREAM     CONNECTED     444831   
> unix  3      [ ]         STREAM     CONNECTED     444832   
> unix  3      [ ]         STREAM     CONNECTED     444833   
> unix  3      [ ]         STREAM     CONNECTED     444834   
> unix  3      [ ]         STREAM     CONNECTED     446401   
> unix  3      [ ]         STREAM     CONNECTED     446402   
> unix  3      [ ]         STREAM     CONNECTED     446403   
> unix  3      [ ]         STREAM     CONNECTED     446404   
412a525,546
> unix  3      [ ]         STREAM     CONNECTED     449221   
> unix  3      [ ]         STREAM     CONNECTED     449222   
> unix  3      [ ]         STREAM     CONNECTED     449223   
> unix  3      [ ]         STREAM     CONNECTED     449224   
> unix  3      [ ]         STREAM     CONNECTED     449225   
> unix  3      [ ]         STREAM     CONNECTED     449226   
> unix  3      [ ]         STREAM     CONNECTED     449233   
> unix  3      [ ]         STREAM     CONNECTED     449234   
> unix  3      [ ]         STREAM     CONNECTED     452198   
> unix  3      [ ]         STREAM     CONNECTED     452199   
> unix  3      [ ]         STREAM     CONNECTED     452200   
> unix  3      [ ]         STREAM     CONNECTED     452201   
> unix  3      [ ]         STREAM     CONNECTED     452202   
> unix  3      [ ]         STREAM     CONNECTED     452203   
> unix  3      [ ]         STREAM     CONNECTED     452204   
> unix  3      [ ]         STREAM     CONNECTED     452205   
> unix  3      [ ]         STREAM     CONNECTED     452206   
> unix  3      [ ]         STREAM     CONNECTED     452207   
> unix  3      [ ]         STREAM     CONNECTED     452208   
> unix  3      [ ]         STREAM     CONNECTED     452209   
> unix  3      [ ]         STREAM     CONNECTED     452215   
> unix  3      [ ]         STREAM     CONNECTED     452216   
413a548,607
> unix  3      [ ]         STREAM     CONNECTED     454454   
> unix  3      [ ]         STREAM     CONNECTED     454455   
> unix  3      [ ]         STREAM     CONNECTED     454456   
> unix  3      [ ]         STREAM     CONNECTED     454457   
> unix  3      [ ]         STREAM     CONNECTED     454458   
> unix  3      [ ]         STREAM     CONNECTED     454459   
> unix  3      [ ]         STREAM     CONNECTED     454460   
> unix  3      [ ]         STREAM     CONNECTED     454461   
> unix  3      [ ]         STREAM     CONNECTED     454462   
> unix  3      [ ]         STREAM     CONNECTED     454463   
> unix  3      [ ]         STREAM     CONNECTED     454464   
> unix  3      [ ]         STREAM     CONNECTED     454465   
> unix  3      [ ]         STREAM     CONNECTED     455402   
> unix  3      [ ]         STREAM     CONNECTED     455403   
> unix  3      [ ]         STREAM     CONNECTED     455404   
> unix  3      [ ]         STREAM     CONNECTED     455405   
> unix  3      [ ]         STREAM     CONNECTED     455406   
> unix  3      [ ]         STREAM     CONNECTED     455407   
> unix  3      [ ]         STREAM     CONNECTED     455411   
> unix  3      [ ]         STREAM     CONNECTED     455412   
> unix  3      [ ]         STREAM     CONNECTED     455413   
> unix  3      [ ]         STREAM     CONNECTED     455414   
> unix  3      [ ]         STREAM     CONNECTED     455415   
> unix  3      [ ]         STREAM     CONNECTED     455416   
> unix  3      [ ]         STREAM     CONNECTED     455420   
> unix  3      [ ]         STREAM     CONNECTED     455421   
> unix  3      [ ]         STREAM     CONNECTED     455422   
> unix  3      [ ]         STREAM     CONNECTED     455423   
> unix  3      [ ]         STREAM     CONNECTED     455686   
> unix  3      [ ]         STREAM     CONNECTED     455687   
> unix  3      [ ]         STREAM     CONNECTED     457962   
> unix  3      [ ]         STREAM     CONNECTED     457963   
> unix  3      [ ]         STREAM     CONNECTED     457964   
> unix  3      [ ]         STREAM     CONNECTED     457965   
> unix  3      [ ]         STREAM     CONNECTED     457966   
> unix  3      [ ]         STREAM     CONNECTED     457967   
> unix  3      [ ]         STREAM     CONNECTED     458044   
> unix  3      [ ]         STREAM     CONNECTED     458045   
> unix  3      [ ]         STREAM     CONNECTED     458046   
> unix  3      [ ]         STREAM     CONNECTED     458047   
> unix  3      [ ]         STREAM     CONNECTED     458048   
> unix  3      [ ]         STREAM     CONNECTED     458049   
> unix  3      [ ]         STREAM     CONNECTED     458053   
> unix  3      [ ]         STREAM     CONNECTED     458054   
> unix  3      [ ]         STREAM     CONNECTED     458055   
> unix  3      [ ]         STREAM     CONNECTED     458056   
> unix  3      [ ]         STREAM     CONNECTED     458057   
> unix  3      [ ]         STREAM     CONNECTED     458058   
> unix  3      [ ]         STREAM     CONNECTED     460821   
> unix  3      [ ]         STREAM     CONNECTED     460822   
> unix  3      [ ]         STREAM     CONNECTED     460823   
> unix  3      [ ]         STREAM     CONNECTED     460824   
> unix  3      [ ]         STREAM     CONNECTED     460825   
> unix  3      [ ]         STREAM     CONNECTED     460826   
> unix  3      [ ]         STREAM     CONNECTED     460832   
> unix  3      [ ]         STREAM     CONNECTED     460833   
> unix  3      [ ]         STREAM     CONNECTED     460834   
> unix  3      [ ]         STREAM     CONNECTED     460835   
> unix  3      [ ]         STREAM     CONNECTED     460836   
> unix  3      [ ]         STREAM     CONNECTED     460837  
`
The firewall (ufw) is disabled. Also note that I can launch up to 7 slaves, I cannot launch more slaves. 

Regards,
GW

**Comment by ggouaillardet** [comment]
is `192.168.123.23` an address on your host?
is it configured even when `docker` is not running?
if the `192.168.123.0/24` network (I guessed the net mask) is for Docker only, can you try to
`mpirun --mca btl_tcp_if_exclude 192.168.123.0/24 ...` and see if it helps?

a more reliable method to assess whether a firewall is running or not is to run `potables -L` and confirm there are no rules.

**Comment by gwiesenekker** [comment]
192.168.123.23 is the IP-address of my server, so it is configured even if docker is not running. The docker networks are:

`
$ docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
92a9bb0d869e   bridge    bridge    local
82806583b0d0   host      host      local
48f981befc0d   none      null      local
$ docker network inspect 92a9bb0d869e
[
    {
        "Name": "bridge",
        "Id": "92a9bb0d869e37141646dbc4c4516b7f9525ca2230957e2bd42b9ea5251af571",
        "Created": "2022-03-06T09:20:11.196923865+01:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
$ docker network inspect 82806583b0d0
[
    {
        "Name": "host",
        "Id": "82806583b0d0df84c39ff41aace870cb3ac789ef5149bff1eff9c776adc3fa08",
        "Created": "2022-02-07T08:14:38.724854764+01:00",
        "Scope": "local",
        "Driver": "host",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
$ docker network inspect 48f981befc0d
[
    {
        "Name": "none",
        "Id": "48f981befc0d2829bc81d14f5e5fd50daac871deac9881e27fea0e9a8179354f",
        "Created": "2022-02-07T08:14:38.68024219+01:00",
        "Scope": "local",
        "Driver": "null",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
`

I double checked, but the firewall is disabled. Also note that I am changing nothing in the firewall and network configuration when running more and more slaves, and it works until 7 slaves, after which the program just hangs. 
If I exclude 192.168.123.23/24 the program errors out (I guess expected because I excluded the host) with the error:

`
Open MPI detected an inbound MPI TCP connection request from a peer
that appears to be part of this MPI job (i.e., it identified itself as
part of this Open MPI job), but it is from an IP address that is
unexpected.  This is highly unusual.

The inbound connection has been dropped, and the peer should simply
try again with a different IP interface (i.e., the job should
hopefully be able to continue).

  Local host:          <HOSTNAME>
  Local PID:           299805
  Peer hostname:       <HOSTNAME> ([[17206,1],0])
  Source IP of socket: 192.168.123.23
  Known IPs of peer:   
	127.0.0.1
	172.17.0.1
--------------------------------------------------------------------------
`

I have done some more troubleshooting, and it looks like the processes hang in the first call to MPI_Barrier. I launch the processes myself from main(), I cannot use mpi_run because Mathematica that calls the C program does not support mpi_run. The launch code looks like:

`
  MPI_Init(&narg, &argv);

  mpi_nslaves = options.nslaves;

  int mpi_nworld;

  MPI_Comm_size(MPI_COMM_WORLD, &mpi_nworld);

  if (mpi_nworld < 1)
  {
    fprintf(stderr, "mpi_nworld < 1\n");
    exit(EXIT_FAILURE);
  }

  MPI_Comm mpi_comm_parent;

  MPI_Comm_get_parent(&mpi_comm_parent);

  if (mpi_comm_parent == MPI_COMM_NULL)
  {
    if (mpi_nworld > 1)
    {
      fprintf(stderr, "do not use mpirun but use --nslaves=\n");
      exit(EXIT_FAILURE);
    }
    if (mpi_nslaves > 0)
    {
      if (RUNNING_ON_VALGRIND)
      {
        MPI_Comm_spawn("valgrind", argv, mpi_nslaves,
          MPI_INFO_NULL, 0, MPI_COMM_SELF,
          &mpi_comm_slaves, MPI_ERRCODES_IGNORE);
      }
      else
      {
        MPI_Comm_spawn(argv[0], argv + 1, mpi_nslaves,
          MPI_INFO_NULL, 0, MPI_COMM_SELF,
          &mpi_comm_slaves, MPI_ERRCODES_IGNORE);
      }
      MPI_Intercomm_merge(mpi_comm_slaves, FALSE, &mpi_comm_global);
    }
    else
    {
      mpi_comm_global = MPI_COMM_WORLD;
      mpi_comm_slaves = MPI_COMM_NULL;
    }
    mpi_id_slave = INVALID;
  }
  else 
  {
    MPI_Intercomm_merge(mpi_comm_parent, TRUE, &mpi_comm_global);

    mpi_comm_slaves = MPI_COMM_WORLD;

    MPI_Comm_rank(mpi_comm_slaves, &mpi_id_slave);
  }

  MPI_Comm_size(mpi_comm_global, &mpi_nglobal);

  BUG(mpi_nglobal > MPI_NGLOBAL_MAX)

  BUG(mpi_nglobal != (mpi_nslaves + 1))

  MPI_Comm_rank(mpi_comm_global, &mpi_id_global);

  if (mpi_comm_parent == MPI_COMM_NULL)
  {
    BUG(mpi_id_slave != INVALID)
    BUG(mpi_id_global != 0)
  }
  else
  {
    BUG(mpi_id_slave == INVALID)
    BUG(mpi_id_global == 0)
  }

  //MPI_Barrier(mpi_comm_global);

PRINTF("before MPI_Barrier\n");
  MPI_Barrier(mpi_comm_global);
PRINTF("after MPI_Barrier\n");
`

options.nslaves is set from the command-line (--nslaves = 16). I create two communicators: mpi_comm_global (17) and mpi_comm_slaves (16), the *_global and *_slave IDs track the IDs within those communicators. PRINTF is a wrapper for printf that logs (and flushes) stdout to a unique log-file. The output shows:

`
$ grep before stdout*
stdout:0:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:10:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:11:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:1:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:12:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:13:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:14:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:15:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:16:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:2:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:3:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:4:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:5:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:6:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:7:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:8:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
stdout:9:17.txt:08:46:53-07/03/2022@ before MPI_Barrier
$ grep after stdout*
stdout:10:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:11:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:1:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:12:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:13:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:14:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:15:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:2:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:3:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:4:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:5:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:6:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:7:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:8:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
stdout:9:17.txt:08:46:53-07/03/2022@ after MPI_Barrier
`

So MPI_Barrier hangs for global IDs 0 and 16. Is there a way to further troubleshoot MPI_Barrier?

Regards,
GW

**Comment by ggouaillardet** [comment]
OK, try the other way around then
```
mpirun --mca btl_tcp_if_include 192.168.123.0/24 --mca oob_tcp_if_include 192.168.123.0/24 ...
```

**Comment by gwiesenekker** [comment]
I am getting the same error:

$ env | grep OMPI
OMPI_MCA_oob_tcp_if_include=192.168.123.0/24
OMPI_MCA_btl_tcp_if_exclude=192.168.123.0/24
$ a.out --nslaves=16 gen_pos 1000000
before MPI_Barrier
--------------------------------------------------------------------------
Open MPI detected an inbound MPI TCP connection request from a peer
that appears to be part of this MPI job (i.e., it identified itself as
part of this Open MPI job), but it is from an IP address that is
unexpected.  This is highly unusual.

The inbound connection has been dropped, and the peer should simply
try again with a different IP interface (i.e., the job should
hopefully be able to continue).

  Local host:          <HOSTNAME>
  Local PID:           308544
  Peer hostname:       <HOSTNAME> ([[25856,1],0])
  Source IP of socket: 192.168.123.23
  Known IPs of peer:   
	127.0.0.1
	172.17.0.1
--------------------------------------------------------------------------

Regards,
GW

**Comment by ggouaillardet** [comment]
You should **include** the subnet on both `oob` and `tcp:

```
export OMPI_MCA_btl_tcp_if_include=192.168.123.0/24
```

**Comment by gwiesenekker** [comment]
Hi,

That solved the issue and it is reproducible: unsetting these environment variables: MPI_Barrier hangs (when the Docker container is running); setting these environment variables: the program continues. So, what do these settings achieve to resolve the conflict with Docker?

Regards,
GW

**Comment by ggouaillardet** [comment]
Open MPI (the `btl/tcp` component to be more specific) (tries to) use several socket pairs between processes when several interfaces are available. My guess is that docker sets up some network that are tried by Open MPI but are not usable (typically, the communications would hang because of docker firewall).
So I guess restricting IP traffic to a subnet that is known to always work avoid the hang.

**Comment by gwiesenekker** [comment]
Hi,

Your guess is absolutely right: the netstat -an output shows exactly that:

tcp        0      0 172.17.0.1:1030         192.168.123.23:59109    TIME_WAIT 

The 172.17.0.1 address belongs to the Docker bridge network.

Regards,
GW

**Comment by jsquyres** [comment]
FWIW, Open MPI has both "include" and "exclude" MCA params (which you're setting via env vars).  You could either exclude the Docker-only network or include the desired comma-delimited list of network(s) -- either way will work (but not both simultaneously -- it only makes sense to use "include" *or* "exclude" -- not both).

Sounds like this issue is resolved; I'll close the issue.  Feel free to re-open if you have additional questions on this topic.
