### ISSUE TITLE
mca_base_component_repository_open: unable to open mca_shmem_sysv/mmap/posix

### ISSUE THREAD

**Issue by kenorb** [open-mpi/ompi#10049]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

`v4.1.2`

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

```
git checkout v4.1.2
./configure
make
```

### Please describe the system on which you are running

* Operating system/version: Ubuntu 21.10
* Computer hardware: PC
* Network type: local

-----------------------------

## Details of the problem

```
$ mpirun -n 1 ./myprog
[Ubuntu:201160] mca_base_component_repository_open: unable to open mca_shmem_sysv: dynamic loader not available (using dldummy) (ignored)
[Ubuntu:201160] mca_base_component_repository_open: unable to open mca_shmem_mmap: dynamic loader not available (using dldummy) (ignored)
[Ubuntu:201160] mca_base_component_repository_open: unable to open mca_shmem_posix: dynamic loader not available (using dldummy) (ignored)
--------------------------------------------------------------------------
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_shmem_base_select failed
  --> Returned value -1 instead of OPAL_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_init failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Error" (-1) instead of "Success" (0)

*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[Ubuntu:201160] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

Code in brief:

```
#include <mpi.h>

int main(int argc, char **argv) {
  int rank;
  int size;
  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  MPI_Comm_size(MPI_COMM_WORLD, &size);
  MPI_File ifile;
...
  MPI_File_read_at_all(*in, start, chunk, localsize, MPI_CHAR, MPI_STATUS_IGNORE);
...
  MPI_File_close(&ifile);
  MPI_Finalize();
}
```

**Comment by jsquyres** [comment]
If you got a git clone of the Open MPI repository and checked out the v4.1.2 branch, I'm guessing you also ran `autogen.pl` before invoking `configure`, right?

Can you send the full configure and build logs?  I haven't seen `dynamic loader not available (using dldummy)` as an error before; it suggests that someone compiled something like https://github.com/ryancdotorg/brainflayer/blob/master/dldummy.c as part of your application, or somehow got introduced into the build/link/install process of Open MPI.

**Comment by kenorb** [comment]
```
$ git status
HEAD detached at v4.1.2
nothing to commit, working tree clean
$ ./autogen.pl
...
Open MPI autogen: completed successfully.  w00t!
$ ./configure
...
(no errors)
$ make
$ sudo make install
(successful install)
```

- `config.log file` attached: [`config.log.gz`](https://github.com/open-mpi/ompi/files/8191285/config.log.gz)

**Comment by kenorb** [comment]
> It suggests that someone compiled something like brainflayer

Yes, I've forked brainflayer with branch which has MPI integration somebody did and I'm trying to fix it (for the purpose of comparing speed with non-MPI version, reproducing setup described in the following [blog post](https://web.archive.org/web/20150817221111/https://www.juliu5.com/brainflayer-parallelized/) which it worked there and continuation of the work). But the run fails and I'm not familiar with MPI.

```
$ git clone --branch dev-mpi --recursive https://github.com/kenorb-contrib/brainflayer brainflayer-mpi
$ cd brainflayer-mpi
$ make
$ ./hex2blf example.hex example.blf
$ ./brainflayer -v -I 0000000000000000000000000000000000000000000000000000000000000001 -b example.blf
...
  opal_shmem_base_select failed
  --> Returned value -1 instead of OPAL_SUCCESS
...
  opal_init failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
...
  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Error" (-1) instead of "Success" (0)
...
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

Do you've any other code example which I can try to compile and run?

**Comment by ggouaillardet** [comment]
By default, Open MPI uses `dlopen()` and friends to handle components (aka plugins).
In your case, Open MPI ends up invoking the dummy `dlopen()` instead of the real one, and hence causing the error.

Unless you can get rid of `dldummy`, you need (at the very least) to
`configure --disable-dlopen ...`
and rebuild Open MPI

**Comment by jsquyres** [comment]
@kenorb Yes, @ggouaillardet is spot-on: you're using a library that deliberately disables system-level functionality that Open MPI uses by default (the `dlopen()` function and friends).  

You can ditch that "dldummy" functionality in brainflayer (e.g., just remove `dldummy.o` from brainflayer's `Makefile`), or you can do what @ggouaillardet suggested: re-configure Open MPI with the `--disable-dlopen` CLI option, and then re-build / re-install Open MPI.  See https://www.open-mpi.org/faq/?category=building#avoid-dso for details.

**Comment by jsquyres** [comment]
BTW, just re-reading your above post and cloning that brainflayer fork/dev-mpi branch out of curiosity...

It looks like the main use of MPI in there is to use the MPI_File APIs to read some sort of input file.  That's a somewhat odd way to do it, but workable.  I think it does presume that you're going to run more than one brainflayer process, though.  I.e., if you just compile/link brainflayer against Open MPI and then run `./brainflayer ...`, you won't get any speedup (I may be telling you something you already know -- e.g., if you just posted a simple case to show it not working, above).  You'll likely want to use `mpirun` to launch multiple copies of `brainflayer` -- perhaps one per core on your machine? -- so that it will actually split up the work across the different `brainflayer` processes.

Good luck.

**Comment by kenorb** [comment]
> do what @ggouaillardet suggested: re-configure Open MPI with the `--disable-dlopen` CLI option, and then re-build / re-install Open MPI. See https://www.open-mpi.org/faq/?category=building#avoid-dso for details.

I've reconfigured `v4.1.2` with `--disable-dlopen` and after install, the binary with provided command runs without errors, so it's a good start.
Thank you.
