### ISSUE TITLE
Missing ELEMENTAL in declaration of ompi_request_op_ne in mpi_f08 module? 

### ISSUE THREAD

**Issue by sfilippone** [open-mpi/ompi#10057]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
openmpi-4.1.0-5.fc34.x86_64  

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Fedora 34 package

### Please describe the system on which you are running

* Operating system/version: 
* Computer hardware: 
* Network type: 
Linux laptop 
-----------------------------

## Details of the problem
When using the MPI module  mpi_f08 I am getting the following error. 
```
psi_dswapdata.F90:248:16:

  248 |         if (any(y%comid .ne. mpi_request_null)) then
      |                1
Error: Operands of comparison operator ‘.ne.’ at (1) are TYPE(mpi_request)/TYPE(mpi_request)
```
The ```y%comid``` variable is an array. 
In mpi-types.F90 (am not sure how the various includes work with the f08 version) I see
```
 logical function ompi_request_op_ne(a, b)
    type(MPI_Request), intent(in) :: a, b
    ompi_request_op_ne = (a%MPI_VAL .NE. b%MPI_VAL)
  end function ompi_request_op_ne
```
Now, the error message above shold be fixed by declaring the function to be ELEMENTAL so that the array comparison is treated properly (and similarly for all the other defined equality/inequality operators) 
```
 elemental  function ompi_request_op_ne(a, b) result(res)
   logical :: res 
    type(MPI_Request), intent(in) :: a, b
    res = (a%MPI_VAL .NE. b%MPI_VAL)
  end function ompi_request_op_ne
```

**Comment by jsquyres** [comment]
Forgive my ignorance -- what does it mean to compare an array to a scalar?

**Comment by jsquyres** [comment]
Interesting.  Ok.  I have some followup questions:

1. Does using `ELEMENTAL` violate the MPI spec?  I don't *think* so -- it doesn't look like the MPI 4.0 spec says anything about `ELEMENTAL` at all.  Indeed, MPI-4.0 section 19.1.2, "Fortran Support Through the mpi_f08 Module", only says the following about the operator functions (p793, 22:23):

> Overload the operators .EQ. and .NE. to allow the comparison of these MPI handles with .EQ., .NE., == and /=.

2. What will adding `ELEMENTAL` to the `mpi_f08` bindings in the middle of a release series (e.g., in 4.1.2) mean towards ABI guarantees for the v4.x series?  E.g., will that change the back-end symbol created for the function by the Fortran compiler?

I note that MPICH doesn't seem to use `ELEMENTAL` for its handle operator functions, either.  If we make this change, we should probably encourage MPICH to make the change, too (for application portability).

**Comment by jsquyres** [comment]
FWIW: I just asked this question to the MPI Forum Fortran working group (which hasn't needed to be active much lately, but they still respond to questions) to get some advice, too: https://lists.mpi-forum.org/pipermail/mpiwg-fortran/2022-March/003613.html.

**Comment by sfilippone** [comment]
ELEMENTAL means that the Fortran compiler is allowed to apply that function
element-by-element  (in the context of an array expression).
That is what the compiler does with the "normal"  .EQ. and .NE. operators;
given that these functions are very simple and can be declared ELEMENTAL, I
would go for the behaviour that generates the least surprise.

I do not know whether ELEMENTAL changes the ABI; as far as I can tell, the
symbol generated by GNU Fortran is the same.
As for MPICH, I sent a bug report to the discuss mailing list with the same
contents.
Cheers
S.

**Comment by jsquyres** [comment]
Let's link up all 3 discussions (this Open MPI github issue, the MPICH discuss thread, and the Forum Fortran working group discussion) so that we don't have to have the same Q&A 3 times.

Where's the MPICH discuss thread?  I don't see it in the archives: https://lists.mpich.org/pipermail/discuss/  Has the March archive simply not been created yet, perchance?

**Comment by jsquyres** [comment]
If your mail to discuss@mpich.org was set to moderation as a first-time poster, perhaps it would be better to cancel that message and file a github issue at https://github.com/pmodels/mpich/issues, and link to this issue and the Forum Fortran WG thread...?

**Comment by sfilippone** [comment]
> If your mail to [discuss@mpich.org](mailto:discuss@mpich.org) was set to moderation as a first-time poster, perhaps it would be better to cancel that message and file a github issue at https://github.com/pmodels/mpich/issues, and link to this issue and the Forum Fortran WG thread...?

Ok, will do.

**Comment by sfilippone** [comment]
> Interesting. Ok. I have some followup questions:
> 
>     1. Does using `ELEMENTAL` violate the MPI spec?  I don't _think_ so -- it doesn't look like the MPI 4.0 spec says anything about `ELEMENTAL` at all.  Indeed, MPI-4.0 section 19.1.2, "Fortran Support Through the mpi_f08 Module", only says the following about the operator functions (p793, 22:23):
> 
> 
> > Overload the operators .EQ. and .NE. to allow the comparison of these MPI handles with .EQ., .NE., == and /=.
> 
>     2. What will adding `ELEMENTAL` to the `mpi_f08` bindings in the middle of a release series (e.g., in 4.1.2) mean towards ABI guarantees for the v4.x series?  E.g., will that change the back-end symbol created for the function by the Fortran compiler?
> 
> 
> I note that MPICH doesn't seem to use `ELEMENTAL` for its handle operator functions, either. If we make this change, we should probably encourage MPICH to make the change, too (for application portability).

Some additional background: 
1. The issue surfaced when moving from MPI_MOD/integer handles to MPI_F08/type(mpi_request), and the code stopped working, whereas the expectation would be that moving from an intrinsic comparison to a defined operator should not cause an error; 
2. The ELEMENTAL declaration carries with it some restriction, all of them are easily satisfied by the operators' code
3. Adding ELEMENTAL would allow some additional cases to be handled, but would not in any way break existing source code, it would still compile just fine;
4. As you correctly pointed out, the ABI might be a different matter; I think  this is not going to be an issue, but I guess someone more familiar with compiler internals would need to confirm 
5. Binary operators on arrays in Fortran are interpreted as element-by-element and require the arrays to have the same shape, except that scalars are always conformant to any arrays and are treated as if they were replicated as many times as necessary; compare this with the "dotted" operators in Matlab (the Matlab array language is almost the same as the Fortran array language)

**Comment by hzhou** [comment]
> 4. As you correctly pointed out, the ABI might be a different matter;

From my limited knowledge, Fortran doesn't have a well-defined ABI to start with. For example, the interface (where the keyword `elemental` is being discussed) is all compiler-specific and may well be just a gzip-ed source code.

**Comment by jsquyres** [comment]
@hzhou I was referring to Open MPI's ABI guarantees.  I.e., if Open MPI v4.1.0 was build with fortran compiler X and compiler options Y and configure options Z, then an MPI application -- even an application that uses `mpi_f08` -- should work without recompilation with Open MPI v4.1.x.

Hence, if `ELEMENTAL` changes something in terms of the back-end symbol(s) that the compiler generates, that will complicate things.  I have not had the cycles to check this.

**Comment by sfilippone** [comment]
Il Mer 2 Mar 2022, 17:56 Hui Zhou ***@***.***> ha scritto:

> Our implementation kind of works with arrays since we just reduce it to
> intrinsic operators.
>
> Sorry, I take that back. Our implementation only works with scalars and
> thus, according to my reading of Fortran's text, we are supposed to declare
> it as elemental. Without it, it can't work with arrays in any way.
>
Exactly, with ELEMENTAL  the compiler can apply the fuction to arrays even
if it is defined  on scalars, otherwise you would need some other machinery
(which I have no time to go into right now)
Salvatore

**Comment by hppritcha** [comment]
@jsquyres reading through the comments here and what my fortran book says about elemental functions, I think we should add the elemental prefix to our ```ompi_request_op_ne``` and friends to make it easier for applications that prefer to operate on arrays of MPI handles.

Metcalf, Michael; Reid, John; Cohen, Malcolm. Modern Fortran Explained (Numerical Mathematics and Scientific Computation) gives an example of an elemental procedure on page 127.    The procedure is written using scalar arguments, but because its declared elemental, can be used with arrays as long as the shape of the input args and output (the lhs here) match.

**Comment by jsquyres** [comment]
@hppritcha Can you check if it has an effect on the symbol that the compiler produces?

**Comment by hppritcha** [comment]
oh that's a good point.  I'll check that!

**Comment by hppritcha** [comment]
of course the behavior is likely compiler dependent.

**Comment by hppritcha** [comment]
Using gcc 9.4.0 the symbol names are the same
```
install_elemental_master/lib> (master *)nm libmpi_usempif08.so | grep -i ompi_request_op_ne
0000000000032b85 T __mpi_types_MOD_ompi_request_op_ne
install_master/lib> (master *)nm libmpi_usempif08.so | grep -i ompi_request_op_ne
0000000000032b75 T __mpi_types_MOD_ompi_request_op_ne
```

**Comment by jsquyres** [comment]
@hppritcha and I talked on the phone today; he's going to cook up a small non-MPI example to test what happens when:

* have a module+library that doesn't use ELEMENTAL
* compile an application (that does not expect ELEMENTAL) against that interface so that the executable is dependent upon the library
* change the interface to now use ELEMENTAL
* recompile the module+library
* does the application still work correctly against the new library?
* recompile the application against the new module+library
* does the application still work correctly against the old library and new library?
* change the application to use ELEMENTAL
* recompile the application against the new module+library
* does the application still work correctly against the old library and new library?

**Comment by sfilippone** [comment]
> @hppritcha and I talked on the phone today; he's going to cook up a small non-MPI example to test what happens when:
> 
>     * have a module+library that doesn't use ELEMENTAL
> 
>     * compile an application (that does not expect ELEMENTAL) against that interface so that the executable is dependent upon the library
> 
>     * change the interface to now use ELEMENTAL
> 
>     * recompile the module+library
> 
>     * does the application still work correctly against the new library?
> 
>     * recompile the application against the new module+library
> 
>     * does the application still work correctly against the old library and new library?
> 
>     * change the application to use ELEMENTAL
> 
>     * recompile the application against the new module+library
> 
>     * does the application still work correctly against the old library and new library?

Yes, the application will still work correctly in both  (old application +  new module/library, new application + new module/library). 
If it doesn't, it's a compiler bug.

**Comment by hppritcha** [comment]
Okay I did some playing around with the following files:
```
hpp@cn2024:~/elemental_sandbox>cat interval_types.f90
module interval_types
type interval
    real(kind=8):: lower
    real(kind=8):: upper
end type interval
contains
    function add_intervals(a,b)
      type(interval) :: add_intervals
      type(interval), intent(in) :: a,b
      add_intervals%lower = a%lower + b%lower
      add_intervals%upper = a%upper + b%upper
    end function add_intervals

    subroutine print_interval(a)
      type(interval), intent(in) :: a
      print *,"lower = ", a%lower
      print *,"upper = ", a%upper
    end subroutine print_interval

end module interval_types
```
and
```
hpp@cn2024:~/elemental_sandbox>cat interval_types_elem.f90
module interval_types
type interval
    real(kind=8):: lower
    real(kind=8):: upper
end type interval
contains
    elemental function add_intervals(a,b)
      type(interval) :: add_intervals
      type(interval), intent(in) :: a,b
      add_intervals%lower = a%lower + b%lower
      add_intervals%upper = a%upper + b%upper
    end function add_intervals

    impure elemental subroutine print_interval(a)
      type(interval), intent(in) :: a
      print *,"lower = ", a%lower
      print *,"upper = ", a%upper
    end subroutine print_interval

end module interval_types
```
and two tests:
```
program mytest_scalar
use interval_types
type(interval) :: a, b, sum
a%lower = 1.0
a%upper = 2.0
b%lower = 2.0
b%upper = 3.0

sum = add_intervals(a,b)
call print_interval(sum)

end program mytest_scalar
```
and 
```
program mytest_vec
use interval_types
type(interval) :: a(4), b(4), sum(4)
a%lower = 1.0
a%upper = 2.0
b%lower = 2.0
b%upper = 3.0

sum = add_intervals(a,b)
call print_interval(sum)

end program mytest_vec
```
and checked compiling the mytest_scalar using either of the modules files generated from interval_type (and the elemental variant) and linking first with object file produced compiling interval_types.f90 and interval_types_elem.f90 and did not find a problem with gfortran, Cray fortran, IBM fortran in any cases.  The mytest_vec could only be compiled using the object file and mod file resulting from compilation of interval_types_elem.f90.  These results seem to indicate that at least for these three fortran compilers, its okay to link against a library containing the ```elemental``` definition of ```add_intervals``` even though the module file used to compile the binary did not have an elemental definition of ```add_intervals```.

**Comment by cniethammer** [comment]
@hppritcha I just took your example codes from above and tried with Intel 19.1.0, AOCC.LLVM.2.1.0 (flang), and PGI 20.4.
Examples compile fine and symbol names are the same. However, call addresses seem to change in case of AOCC/LLVM and PGI:
```
+ flang mytest_scalar.f90 -I scal/ scal/interval_types.o -o mytest_scal_scal
+ flang mytest_scalar.f90 -I elem/ elem/interval_types_elem.o -o mytest_scal_elem
+ nm mytest_scal_scal
+ nm mytest_scal_elem
+ diff mytest_scal_scal.nm mytest_scal_elem.nm
45c45
< 00000000002008f4 r .C306_interval_types_print_interval_
---
> 00000000002008f8 r .C306_interval_types_print_interval_
```

**Comment by jsquyres** [comment]
Everything is merged in all branches; ELEMENTAL support will debug in Open MPI v4.1.3, which, if all goes well, will be released late next week.
