### ISSUE TITLE
use opal atomics to modify ompi initialize/finalize related variables

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#1006]
By using opal atomics to modify/read the following ompi initialize/finalize related variables:
```
ompi_mpi_init_started
ompi_mpi_initialized
ompi_mpi_finalized 
ompi_rte_initialized
ompi_mpi_finalize_started
```
would help in bringing some MPI query functions into compliance with the MPI-3 specification.

See issue #493.

**Comment by jsquyres** [comment]
Per #1007, I'm not sure that this a correct premise any more (i.e., using a mutex was easier than using atomics).  Regardless, I think that this ticket is subsumed by #1007, so I'll close this one.
