### ISSUE TITLE
PMIx compilation failed when using pmi headers via --with-pmi

### ISSUE THREAD

**Issue by Isaac-a95** [open-mpi/ompi#10076]
## Background information

I'm configuring Open MPI in a system which already have pmi.h in a custom location.
I give the correct path but still pmi.h is not correctly included when compiling the internal version of PMIx.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.1.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Dowloaded the tarball

### Please describe the system on which you are running

* Operating system/version: SUSE Linux Enterprise Server 12
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem

I have the PMI headers files located at a custom location , and when running configure they are correctly located.
```shell
$ ls /usr/include/slurm
pmi2.h  pmi.h  slurmdb.h  slurm_errno.h  slurm.h  smd_ns.h  spank.h
```
and the configure output:
```shell
$ ./configure --prefix=$OMPI_DIR --with-pmi=/usr/include/slurm --with-pmi-libdir=/usr/lib64
[...]
checking for pmi.h in /usr/include/slurm... found
checking pmi.h usability... yes
checking pmi.h presence... yes
checking for pmi.h... yes
checking for libpmi in /usr/lib64... found
checking for PMI_Init in -lpmi... yes
checking for pmi2.h in /usr/include/slurm... found
checking pmi2.h usability... yes
checking pmi2.h presence... yes
checking for pmi2.h... yes
checking for libpmi2 in /usr/lib64... found
checking for PMI2_Init in -lpmi2... yes
checking for pmix.h in /usr/include/slurm... not found
checking for pmix.h in /usr/include/slurm/include... not found
[...]
PMIx support: Internal
[...]
```

However, when compiling, I get:
```
Making all in mca/pmix/s1
make[2]: Entering directory '/tmp/ompi/openmpi-4.1.2/opal/mca/pmix/s1'
  CC       mca_pmix_s1_la-pmix_s1_component.lo
  CC       mca_pmix_s1_la-pmix_s1.lo
pmix_s1.c:29:10: fatal error: pmi.h: No such file or directory
 #include <pmi.h>
          ^~~~~~~
compilation ended
Makefile:1907: recipe for target 'mca_pmix_s1_la-pmix_s1.lo' failed
```

This is simply solved by configuring as:
```shell
$ CPPFLAGS=-I/usr/include/slurm ./configure --prefix=$OMPI_DIR --with-pmi=/usr/include/slurm [...]
```
But I guess that this is not intended and the path to the PMI header file is lost somewhere, btw, I'm using GCC 7.2.0

Thanks!

**Comment by bwbarrett** [comment]
The PMI-1/PMI-2 checks are written a little oddly.  My SLURM install is in /opt/slurm instead of /usr/, but I was able to replicate your failure with ` ./configure --prefix=/home/ec2-user/install --with-pmi=/opt/slurm/include/slurm --with-pmi-libdir=/opt/slurm/lib`.  Configure passed with identical messages, but the build failed.

Digging a little, it's because of a convoluted series of tests for PMI and looking for SLURM-specific bits.  However, if you instead use the configure options (again, swap /opt/slurm with /usr):
```
./configure --prefix=/home/ec2-user/install --with-pmi=/opt/slurm/ --with-pmi-libdir=/opt/slurm/lib
```
The configure will look a bit different, but still successful:
```
checking if user requested PMI support... yes
checking for pmi.h in /opt/slurm/... not found
checking for pmi.h in /opt/slurm//include... not found
checking for pmi.h in /opt/slurm//include/slurm... found
checking pmi.h usability... yes
checking pmi.h presence... yes
checking for pmi.h... yes
checking for libpmi in /opt/slurm/lib... found
checking for PMI_Init in -lpmi... yes
checking for pmi2.h in /opt/slurm/... not found
checking for pmi2.h in /opt/slurm//include... not found
checking for pmi2.h in /opt/slurm//include/slurm... found
checking pmi2.h usability... yes
checking pmi2.h presence... yes
checking for pmi2.h... yes
checking for libpmi2 in /opt/slurm/lib... found
checking for PMI2_Init in -lpmi2... yes
checking for pmix.h in /opt/slurm/... not found
checking for pmix.h in /opt/slurm//include... not found
checking can PMI support be built... yes
checking if user requested internal PMIx support()... no
checking for pmix.h in /usr... not found
checking for pmix.h in /usr/include... not found
```

However, it now properly adds the right CPPFLAGS to find pmi.h and Make completes successfully.

So can you try configuring with
```
./configure --prefix=$OMPI_DIR --with-pmi=/usr --with-pmi-libdir=/usr/lib64
```
and confirm this fixes your issue?

**Comment by Isaac-a95** [comment]
Configuring as as you proposed fixed the issue.

```
checking if user requested PMI support... yes
checking for pmi.h in /usr... not found
checking for pmi.h in /usr/include... not found
checking for pmi.h in /usr/include/slurm... found
checking pmi.h usability... yes
checking pmi.h presence... yes
checking for pmi.h... yes
checking for libpmi in /usr/lib64... found
checking for PMI_Init in -lpmi... yes
checking for pmi2.h in /usr... not found
checking for pmi2.h in /usr/include... not found
checking for pmi2.h in /usr/include/slurm... found
checking pmi2.h usability... yes
checking pmi2.h presence... yes
checking for pmi2.h... yes
checking for libpmi2 in /usr/lib64... found
checking for PMI2_Init in -lpmi2... yes
checking for pmix.h in /usr... not found
checking for pmix.h in /usr/include... not found
```

And then correctly compiles, thanks!

**Comment by jsquyres** [comment]
Thanks for the confirmation!
