### ISSUE TITLE
configure option `--runstatedir=DIR` not in OMPI v5.0.0rc3.tar.gz

### ISSUE THREAD

**Issue by gpaulsen** [open-mpi/ompi#10103]
When I compare the output of `configure --help` from the v5.0.0rc3 tarball with the output of `configure --help` from a gitclone of the tag `v5.0.0rc3` after running autogen.pl on my mac (using autoconf v2.71 and automake v1.16.5) I see that the output from the gitclone includes an additional option:
```
diff /Users/gpaulsen/Downloads/ompi-v5.0.0rc3-configure--help.txt configure--help.txt
1c1
< `configure' configures Open MPI 5.0.0rc3 to adapt to many kinds of systems.
---
> `configure' configures Open MPI gitclone to adapt to many kinds of systems.
40a41
>   --runstatedir=DIR       modifiable per-process data [LOCALSTATEDIR/run]
683d683
<   CPP         C preprocessor
690a691
>   CPP         C preprocessor
```

I would expect these two paths to be identical.

**Comment by bwbarrett** [comment]
`runstatedir` is automatically added by newer versions of Autoconf (2.70 or later).  We don't use it in Open MPI, so it doesn't matter, but dist tarballs (and nightly tarballs) are always built with the autotools versions specified in the make_dist_tarball script that is in the branch being built.  5.0.x specifies AC 2.69, which didn't auto-add that option.
