### ISSUE TITLE
ompi/v5.0.x : mpirun --version doesn't works!

### ISSUE THREAD

**Issue by ericch1** [open-mpi/ompi#10149]
Hi,

since March 2, it seems that `mpirun --version` argument doesn't works as expected.  It returns:
```
mpirun --version
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    version
from the file:
    help-schizo-ompi.txt
But I couldn't find that topic in the file.  Sorry!
--------------------------------------------------------------------------
```

Here are all the configuration informations:

http://www.giref.ulaval.ca/~cmpgiref/ompi_5.x/2022.03.02.22h04m44s_ompi_config.log

http://www.giref.ulaval.ca/~cmpgiref/ompi_5.x/2022.03.02.22h04m44s_ompi_ompi_info_all.txt

Thanks,

Eric

**Comment by awlauria** [comment]
Thanks for the report. This is actually a dup of https://github.com/open-mpi/ompi/issues/10096, and should be fixed for rc3.
