### ISSUE TITLE
Command line MCA parameter does not take precedence over env var (?)

### ISSUE THREAD

**Issue by gkatev** [open-mpi/ompi#10159]
Hi, I'm seeing an issue where a `--mca` argument to mpirun does not override the value given to the same MCA parameter via an env var (I believe it is supposed to?).

I'm on v5.0.x (#9a070fc), building from git clone.
How I'm building Open MPI:
```
$ git submodule update --init --recursive
./autogen.pl
./configure --enable-mca-dso=coll --prefix=/home/vm-x86/openmpi-5.0.x --enable-debug --with-pmix=internal \
  --disable-mpi-fortran --with-ucx=/home/vm-x86/ucx --with-ucc=/home/vm-x86/ucc \
  --with-libfabric=/home/vm-x86/libfabric --with-xpmem=/home/vm-x86/xpmem \
  --with-knem=/home/vm-x86/knem |& tee config.out
make -sj16
make -s install
```
Configure output: [config.out](https://github.com/open-mpi/ompi/files/8340720/config.out.txt)
```
$ git submodule status
 b59e49feac071a622b64008115c590561d7f2e43 3rd-party/openpmix (v4.1.2-12-gb59e49fe)
 8c09625b4a9b92f31f00522fa721b7e8612daab4 3rd-party/prrte (v2.0.2-25-g8c09625b4a)
```
For example, running this results in a failure:
```
$ OMPI_MCA_coll=invalid mpirun --mca coll basic,libnbc osu_bcast
...
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      x86-64-1
Framework: coll
Component: invalid
--------------------------------------------------------------------------
```
(I've also observed it happen with various other MCA parameters)

Is this indeed unexpected? Can someone else reproduce it? -- otherwise I could also look into it, with some indication where in the source code to dig.

**Comment by ggouaillardet** [comment]
@gkatev this is indeed very surprising!

I will try to reproduce it.

Can you please run the following command and post the output?

```
OMPI_MCA_coll=invalid mpirun --mca coll basic,libnbc env | grep ^OMPI_MCA_coll
```

**Comment by gkatev** [comment]
@ggouaillardet 
```
$ OMPI_MCA_coll=invalid mpirun --mca coll basic,libnbc env | grep ^OMPI_MCA_coll
OMPI_MCA_coll=invalid
OMPI_MCA_coll=invalid
OMPI_MCA_coll=invalid
OMPI_MCA_coll=invalid
```

**Comment by jsquyres** [comment]
I've marked this as a blocker for v5.0.x -- as described, it sounds like a regression.

**Comment by ggouaillardet** [comment]
Thanks @gkatev 
unfortunately all I can say is: this is not good :-(

**Comment by gkatev** [comment]
@ggouaillardet so you could not reproduce it, right?

FYI I built a version of 4.1.2 with the same config line ([config.out](https://github.com/open-mpi/ompi/files/8342745/config.out.txt)) and it worked correctly.

**Comment by ggouaillardet** [comment]
FWIW, I was able to fix this by patching the embedded PMIx

```patch
diff --git a/src/mca/pmdl/ompi/pmdl_ompi_component.c b/src/mca/pmdl/ompi/pmdl_ompi_component.c
index f2e19d47..70ec5e51 100644
--- a/src/mca/pmdl/ompi/pmdl_ompi_component.c
+++ b/src/mca/pmdl/ompi/pmdl_ompi_component.c
@@ -76,7 +76,7 @@ static pmix_status_t component_register(void)
         mca_pmdl_ompi_component.include = pmix_argv_split(mca_pmdl_ompi_component.incparms, ',');
     }
 
-    mca_pmdl_ompi_component.excparms = NULL;
+    mca_pmdl_ompi_component.excparms = "OMPI_MCA_*";
     (void) pmix_mca_base_component_var_register(
         component, "exclude_envars",
         "Comma-delimited list of envars to exclude (\'*\' and \'?\' supported)",
```

@rhc54 could you please check if this is the right fix?

**Comment by awlauria** [comment]
@ggouaillardet can you post this patch to openpmix? He won't see mentions here.

**Comment by ggouaillardet** [comment]
I am AFK now
I can do that tomorrow unless someone else takes care of it in the mean
time.

**Comment by awlauria** [comment]
Testing your patch, @ggouaillardet I am not sure it is completely correct.

While it does force the command line to take precedence over what the user has in the environment, if the user only uses the environment and not the command line, it is no longer propagated across node. IE:

```
OMPI_MCA_osc=foo mpirun --host "hostA:1,hostB:1" -mca pml ob1 -np 2 env | grep MCA_osc
```
Will only show OMPI_MCA_osc for the local node.

**Comment by ggouaillardet** [comment]
@awlauria thanks for testing my patch.
Indeed, that was not a good one ...

I just opened openpmix/openpmix#2548 with a new tentative fix.

**Comment by awlauria** [comment]
v5.0.x: https://github.com/open-mpi/ompi/pull/10179. Included in rc3.

main still requires a submodule update.

**Comment by gkatev** [comment]
```
$ OMPI_MCA_coll=invalid mpirun --np 10 --mca coll basic,libnbc env | grep -i MCA_coll
OMPI_MCA_coll=invalid
 if [ "${_mOMPI_MCA_coll=invalid
 if [ "${_mOMPI_MCA_coll=invalid
 if [ "${_mOMPI_MCA_coll=invalid
 if [ "${_mOMPI_MCA_coll=invalid
 if [ "${_mOMPI_MCA_coll=invalid
 if [ "${_mOMPI_MCA_coll=invalid
OMPI_MCA_coll=invalid
OMPI_MCA_coll=invalid
 if [ "${_mOMPI_MCA_coll=invalid
```
```
$ OMPI_MCA_coll=invalid mpirun --np 10 env | grep -i MCA_coll
OMPI_MCA_coll=invalid
 if [ "${_mOMPI_MCA_coll=invalid
 if [ "${_mOMPI_MCA_coll=invalid
 if [ "${_mOMPI_MCA_coll=invalid
 if [ "${_mOMPI_MCA_coll=invalid
OMPI_MCA_coll=invalid
OMPI_MCA_coll=invalid
OMPI_MCA_coll=invalid
OMPI_MCA_coll=invalid
OMPI_MCA_coll=invalid

**Comment by awlauria** [comment]
prrte pr: https://github.com/openpmix/prrte/pull/1351

@gkatev specifically, the fix is here: https://github.com/openpmix/prrte/commit/d9d7312af41aeed342028bd79322b1f60e45dbcb#diff-2a67d675dd2b7dd4075c0d9a1bbe98cb2b8498d2e591490fea2fd1dd20dd4b30L96

Would you be able to checkout that prrte branch and verify it works for you?

**Comment by gkatev** [comment]
Indeed @awlauria, I can confirm it now works for me. Thanks!

**Comment by awlauria** [comment]
Thanks for verifying, closing.
