### ISSUE TITLE
5.0.0rc3: ./autogen.pl --force fails

### ISSUE THREAD

**Issue by mkurnosov** [open-mpi/ompi#10155]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
5.0.0rc3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
[openmpi-5.0.0rc3.tar.bz2](https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.0rc3.tar.bz2)

### Please describe the system on which you are running

* Operating system/version: GNU/Linux
* Computer hardware: 
* Network type: IB
-----------------------------
## Details of the problem

`./autogen.pl --force` fails
`Not at the root directory of an OMPI source tree at ./autogen.pl line 106.`

It checks for the `config/opal_try_assemble.m4`, but there is no such file in 5.0.0rc3 distribution tarball.

**Comment by ggouaillardet** [comment]
Thanks for the report!

indeed, in `autogen.pl`

```
# Verify that we're in the OMPI root directorty by checking for a token file.

my_die "Not at the root directory of an OMPI source tree"
    if (! -f "config/opal_try_assemble.m4");
```

the issue here is the macros defined in `config/opal_try_assemble.m4` are not used anywhere and this file does not get included in the tarball.

Meanwhile, you can either remove the mentionned lines or choose an other `m4` file from the `config` directory.

**Comment by mkurnosov** [comment]
@ggouaillardet thank you

**Comment by jsquyres** [comment]
This is definitely a blocker bug for v5.0.0.  Thankfully, it's easy to fix.

**Comment by awlauria** [comment]
This is fixed in main by: https://github.com/open-mpi/ompi/pull/10167

**Comment by awlauria** [comment]
v5.0.x: https://github.com/open-mpi/ompi/pull/10227
