### ISSUE TITLE
Suggestion: add OpenMPI tag to project

### ISSUE THREAD

**Issue by h1z1** [open-mpi/ompi#10193]
Not sure where to post this, Github's "search" is severely degenerate but when you search for "OpenMPI" on GITHUB, 99.9% of the results are anything but this repo.  Though it technically wouldn't be able to match on the project name, nor the repository itself.

One suggestion thus is add various tags related to it - "OpenMPI", "openmp" etc along with the "mpi"  topic tags?  Another would be create a shell repo called OpenMPI with a simple readme pointing to this one.

* Template removed, didn't seem appropriate for issues related to the GIthub repo itself.

**Comment by bwbarrett** [comment]
Thank you for the filing the issue.  Surprisingly, none of us had noticed the search issue before.  We've added a tag and that seems to have already changed the search ordering some.

**Comment by h1z1** [comment]
Can confirm this repo is listed as #1 now :)
