### ISSUE TITLE
BLCR CRS component should use restart API when available

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#102]
Recent versions of BLCR have a restart API that alleviates the need to `exec()` the `cr_restart` binary from `opal-restart`. We should check for the existance of this API, and use it when available.

Per a conversation on the users list:

[http://www.open-mpi.org/community/lists/users/2010/03/12228.php]

**Comment by jjhursey** [comment]
C/R support is not longer supported. Closing as won't fix.
