### ISSUE TITLE
OFI MTL help message issues

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1020]
The help message checked turned up the following:

```
*** WARNING: Possibly unused help topic
  Help file: ./mca/mtl/ofi/help-mtl-ofi.txt
  Help topic: debug level
*** WARNING: Possibly unused help topic
  Help file: ./mca/mtl/ofi/help-mtl-ofi.txt
  Help topic: ofi init
*** WARNING: Possibly unused help file (no topics used from this file)
  Help file: ./mca/mtl/ofi/help-mtl-ofi.txt
```

**Comment by yburette** [comment]
Good catch, I'll clean that up.

**Comment by jsquyres** [comment]
Thanks!

**Comment by yburette** [comment]
@jsquyres @rhc54 Do you want me to create a pull request for v1.10.1?

**Comment by jsquyres** [comment]
v1.10.1 is likely to go out in the immediate future.  I wouldn't worry about it -- if it's fixed in master/v2.x, I think we're good.

**Comment by hppritcha** [comment]
@yburette It looks like 8bf1c95 needs to be PR'd over to ompi-release?

**Comment by yburette** [comment]
@hppritcha You're right. Do you want me to create PRs for both v1.10 and v2.x?

**Comment by hppritcha** [comment]
Yes please do.  Thanks.

**Comment by yburette** [comment]
OK, I created the PRs for both branches.

open-mpi/ompi-release#801
open-mpi/ompi-release#802

**Comment by hppritcha** [comment]
fixed with cited PRs.  closing.
