### ISSUE TITLE
PSM2 MTL needs to use new PSM2 symbols

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1021]
It just occurred to me that we don't have a Github issue to track this: per the discussion at http://www.open-mpi.org/community/lists/devel/2015/09/17919.php, the PSM2 MTL needs to not use the same symbols as the PSM MTL (this is really more of an issue with the PSM and PSM2 dependent libraries, but the PSM2 MTL needs to be updated to match).

@matcabral is already working on this, but we need a blocker issue here to ensure that we don't release 2.0.0 before this work is done.

**Comment by matcabral** [comment]
Jeff,
Would you please share a high level timeline for v2.0.0? 
Thanks,

**Comment by jsquyres** [comment]
rc before Supercomputing (mid-Nov).  Given that the rest of November and December are super short (with the holidays and whatnot), it's unlikely that we'll release v2.0.0 before January.
