### ISSUE TITLE
Installation stops at configure step 

### ISSUE THREAD

**Issue by ece8264** [open-mpi/ompi#10225]
OpenMPI version: 4.1.3

I tried to install OpenMPI according to the following steps: 

$ mkdir $HOME/openmpi
$ cd $HOME/openmpi
3. Copy the .tar.gz file into this directory:
$ cp $HOME/Downloads/openmpi-1.8.7.tar.gz $HOME/openmpi
4. Extract the package and go into the extracted directory:
$ tar -xzvf openmpi-1.8.7.tar.gz
$ cd openmpi-1.8.7
5. Configure and compile (this step may take about 5-10 minutes):
$ ./configure --prefix=$HOME/openmpi
$ make all
6. Finally install using the following command:
$ make install

**But  during configuration an error interrupts the step and subsequently the whole process, these are the last lines on the terminal :** 

**checking KIND value of Fortran C_SIGNED_CHAR... no ISO_C_BINDING -- fallback
checking Fortran value of selected_int_kind(4)... no
configure: WARNING: Could not determine KIND value of C_SIGNED_CHAR
configure: WARNING: See config.log for more details
configure: error: Cannot continue**
 
Anyone familiar ? Thank you very much for your time !

**Comment by bwbarrett** [comment]
It would be most helpful if you could attach the config.log generated by that run of configure.

**Comment by ece8264** [comment]
Of course thank you in advance btw it's an immense file I don't know if it's possible to find something there 
[config.log](https://github.com/open-mpi/ompi/files/8429536/config.log)

**Comment by bwbarrett** [comment]
Well, this is confusing.  My guess is that there's something wrong with your fortran compiler/runtime install, but I have no idea what.  The Fortran compiler was able to compile and run a number of simple programs, but appears to cause a runtime exception when the Fortran open function is called.  This is one of the tests that fails to run:

```Fortran
       program main

         open(8, file="conftest.out")
         write(8, fmt="(I5)") selected_int_kind(4)
         close(8)

       end
```

I believe that this is a valid Fortran program (if a bit useless in a general context), but that's the one that failed.  Raw notes from config.log:

```
configure:45867: checking for corresponding KIND value of CHARACTER
configure:45890: result: C_SIGNED_CHAR
configure:45908: checking KIND value of Fortran C_SIGNED_CHAR
configure:45936: gfortran -o conftest  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/fresco/anaconda3/lib -Wl,-rpath-link,/home/fresco/anaconda3/lib -L/home/fresco/anaconda3/lib  conftest.f90  -lz >&5
configure:45936: $? = 0
configure:45936: ./conftest
At line 4 of file conftest.f90 (unit = 7)
Fortran runtime error: Cannot open file '': No such file or directory

Error termination. Backtrace:
#0  0x7fd67af57613 in already_open
     at /home/builder/ktietz/cos6/ci_cos6/ctng-compilers_1622658800915/work/.build/x86_64-conda-linux-gnu/src/gcc/libgfortran/io/open.c:712
#1  0x557221bad201 in ???
#2  0x557221bad2da in ???
#3  0x7fd67ac7e0b2 in ???
#4  0x557221bad0dd in ???
#5  0xffffffffffffffff in ???
configure:45936: $? = 2
configure: program exited with status 2
configure: failed program was:
|       program main
|
|         use, intrinsic :: ISO_C_BINDING
|         open(unit = 7, file = "conftest.out")
|         write(7, *) C_SIGNED_CHAR
|         close(7)
|
|       end
configure:45952: result: no ISO_C_BINDING -- fallback
configure:45956: checking Fortran value of selected_int_kind(4)
configure:45983: gfortran -o conftest  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/fresco/anaconda3/lib -Wl,-rpath-link,/home/fresco/anaconda3/lib -L/home/fresco/anaconda3/lib  conftest.f90  -lz >&5
configure:45983: $? = 0
configure:45983: ./conftest
At line 3 of file conftest.f90 (unit = 8)
Fortran runtime error: Cannot open file '': No such file or directory

Error termination. Backtrace:
#0  0x7f8c53597613 in already_open
     at /home/builder/ktietz/cos6/ci_cos6/ctng-compilers_1622658800915/work/.build/x86_64-conda-linux-gnu/src/gcc/libgfortran/io/open.c:712
#1  0x56173757c201 in ???
#2  0x56173757c2f3 in ???
#3  0x7f8c532be0b2 in ???
#4  0x56173757c0dd in ???
#5  0xffffffffffffffff in ???
configure:45983: $? = 2
configure: program exited with status 2
configure: failed program was:
|       program main
|
|         open(8, file="conftest.out")
|         write(8, fmt="(I5)") selected_int_kind(4)
|         close(8)
|
|       end
configure:46005: result: no
configure:46016: WARNING: Could not determine KIND value of C_SIGNED_CHAR
configure:46018: WARNING: See config.log for more details
configure:46020: error: Cannot continue
```

**Comment by bwbarrett** [comment]
@ggouaillardet, @jsquyres or one of the other Fortran folks, any ideas?

I don't think they're the problem, but you have a number of binary hardening LDFLAGS set (likely as part of your anaconda environment).  Those are not flags that the Open MPI team regularly builds with.  I don't think any of them would cause this behavior, but it might be worth trying to not set all of the things in your LDFLAGS environment and see if that changes the behavior of the Fortran runtime.

**Comment by ece8264** [comment]
PROBLEM SOLVED !
Once again thank you for diving that deep and proposing a concrete solution to such an obscure issue.
Due to my lack of experience with handling LDFLAGS and many more ... I preferred to simply remove every anaconda3 directory as well as associated hidden files and its directory on the PATH environment variable that probably was the reason that caused configuration step to stop with an error

**Comment by snsmssss** [comment]
Thank you @bwbarrett bwbarrett
I had the same issues as @ece8264 

I followed your instructions and I could overcome ./configure error
I have Anaconda env conflicting
