### ISSUE TITLE
PLATFORM_COMPILER_GNU not defined on macos

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#10233]
Getting a zillion of these when compiling main/HEAD on macos:

```
1704   CC       base/if_base_components.lo
1705 In file included from base/if_base_components.c:17:
1706 In file included from ../../../opal/mca/if/base/base.h:16:
1707 In file included from ../../../opal/mca/base/mca_base_framework.h:18:
1708 In file included from ../../../opal/class/opal_list.h:71:
1709 In file included from ../../../opal/class/opal_object.h:126:
1710 In file included from ../../../opal/mca/threads/thread_usage.h:33:
1711 In file included from ../../../opal/include/opal/sys/atomic.h:420:
1712 ../../../opal/include/opal/sys/atomic_stdc.h:53:42: warning: 'PLATFORM_COMPILER_GNU' is not defined, evaluates to 0 [-Wundef]
1713 #    if defined(PLATFORM_ARCH_X86_64) && PLATFORM_COMPILER_GNU && __GNUC__ < 8
1714                                          ^
```

I have not checked, but I presume that this is also an issue on v5.0.0.

I don't have time to investigate at the moment; wanted to file this to make sure it wasn't lost.

**Comment by jsquyres** [comment]
Hey @devreal -- looks like this came from 935ee76461f, which was your commit.  Any idea what's happening here?

**Comment by gpaulsen** [comment]
I'd hit this last week, but somehow it went away.  My solution was to change the `#if` to a `#if defined()`, but I didn't PR it since after a MAC OS update/brew update (something) it seemed to go away.  Let me try to reproduce again today.

**Comment by gpaulsen** [comment]
I rebased and pushed my potential PR to my fork here: https://github.com/gpaulsen/ompi/tree/topic/main/fix_annoying_mac_warning

**Comment by jsquyres** [comment]
@gpaulsen Do you have another issue or PR open already?

**Comment by gpaulsen** [comment]
no.

**Comment by gpaulsen** [comment]
I confirmed this is still an issue for me as well.  Testing my branch now, and will PR if it looks good.
