### ISSUE TITLE
clang not happy building Open MPI when UCX present

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#10243]
I'm noticing that with the AMD AOCC compilers (clang) based, that the linker is pickier than gnu with respect to undefined symbols in share libraries:

```
1 warning generated.
  CCLD     opal_wrapper
ld.lld: error: ../../../opal/.libs/libopen-pal.so: undefined reference to ucm_set_external_event [--no-allow-shlib-undefined]
ld.lld: error: ../../../opal/.libs/libopen-pal.so: undefined reference to ucm_test_events [--no-allow-shlib-undefined]
ld.lld: error: ../../../opal/.libs/libopen-pal.so: undefined reference to ucm_test_external_events [--no-allow-shlib-undefined]
ld.lld: error: ../../../opal/.libs/libopen-pal.so: undefined reference to ucm_vm_munmap [--no-allow-shlib-undefined]
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

The problem is not in Open MPI but in the contents of the ucx.pc file.  Opening here in case other's hit this problem and are googling.

This problem was observed with ucx 1.11.0

A workaround till the ucx.pc file is fixed is to add LDFLAGS="-Wl,--allow-shlib-undefined" to the configure arguments.

**Comment by bwbarrett** [comment]
That doesn't seem like the right fix.  The right fix should be to add something to LIBS.

**Comment by hppritcha** [comment]
That doesn't make sense to me.  I'd want my package to have a correct contents.  It appears this was revamped in ucx master branch.

For ucx master
```
pkg-config --libs ucx
```
returns 
```
-L<path to ucx install>/lib -lucp -luct -lucs -lucm 
```
unfortunately this doesn't appear in 1.12.1.

**Comment by bwbarrett** [comment]
Sorry, poor phrasing.  The right fix is for UCX's pkg-config module to return the libraries that contain public APIs (and if we call things that aren't ipublic APIs, shame on us).

I meant that the workaround doesn't sound right.  We shouldn't set `LDFLAGS="-Wl,--allow-shlib-undefined"`, but we should set something like `LIBS=-lucm` (plus whatever other libraries are missing).

**Comment by hoopoepg** [comment]
hi
could you run ```make V=1``` command to get linker arguments and provide output? it seems something wrong in libs sequence in linker...

**Comment by hppritcha** [comment]
the issue is in what’s returned from

pkg-config –libs ucx

That’s how Open MPI is determining which UCX libs to add to the link line.

 It appears that at some point someone added in functions into opal/mca/common/ucx that requires the ucm lib.  Also, there seems to be pickiness with clang’s linker selection that brings out this problem.  I don’t see this with the gnu compilers I’m using.

My workaround will be what @bwbarrett  suggested above.

What will fix the issue is for the pkg config file changes that are in ucx master to be cherry-picked back to the 1.11 and 1.12 branches so we pick up the fix in the next UCX release.    I'd prefer not to use ucx master for the nightly testing that brought this problem to my attention.

I was going to open a PR against UCX with a patched ucx.pc.in but noticed on master there was a significant refactor of ucx's pkgconfig files.

**Comment by hppritcha** [comment]
closing as fixed via UCX updates.
