### ISSUE TITLE
Error occours when compiling parallel HDF5 with openmpi-4.1.1

### ISSUE THREAD

**Issue by xiaowang119** [open-mpi/ompi#10263]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

openmpi-4.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

from a source

### Please describe the system on which you are running

* Operating system/version:  Ubuntu 20.04.4 LTS

-----------------------------

## Details of the problem

The "configure" operation as follow is all right.
```shell
shell$ CC=/usr/local/openmpi/bin/mpicc CXX=/usr/local/openmpi/bin/mpicxx ./configure --prefix=/usr/local/wyj-hdf5 --enable-parallel --enable-hl --enable-shared --enable-static
```
But a error occours when I "make" it.

[errorLog.txt](https://github.com/open-mpi/ompi/files/8474023/errorLog.txt)

**Comment by xiaowang119** [comment]
So sorry for my negligence, the full log is as follow
[out.txt](https://github.com/open-mpi/ompi/files/8474123/out.txt)
.

**Comment by jsquyres** [comment]
This looks like an HDF error, not an Open MPI error.

I see tons of warnings in the output, but only one actual error:

```
h5tools_dump.c:635:9: error: C++ style comments are not allowed in ISO C90
  635 |         //HGOTO_ERROR(dimension_break, H5E_tools_min_id_g, "Could not allocate buffer for ptdata");
      |         ^
h5tools_dump.c:635:9: note: (this will be reported only once per input file)
```

You should contact the HDF maintainers about this, not Open MPI.

**Comment by xiaowang119** [comment]
Thank you so much for your patient reply. I'll close this issue!
