### ISSUE TITLE
Incorrect behavior with MPI_Allreduce + MPI_MAX for unsigned long datatype

### ISSUE THREAD

**Issue by keadyk** [open-mpi/ompi#10276]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.1.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Spack / sysadmin installed

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

N/A

### Please describe the system on which you are running

* Operating system/version: CentOS 8 / RHEL 8.5
* Computer hardware: Intel Xeon (multiple variants)
* Network type: 

-----------------------------

## Details of the problem

I am seeing incorrect behavior from MPI_Allreduce with MPI_MAX in v4.1.2, exclusively for the unsigned long datatype. I can reproduce the incorrect behavior across two machines with different hardware, and across several compilers (intel-classic and a few gcc's). 

Reproducer here:

[main.cpp.txt](https://github.com/open-mpi/ompi/files/8491256/main.cpp.txt)

Compiled with `mpicxx`, no other flags.

Output with gcc-11.2 + v4.1.2 and `mpirun -n 2 ./a.out` (incorrect! Global max should be non-zero):
```
We live in a sane and rational universe. 
(18446744073709551615 > 9223372036854775807)

=================================
ATTEMPT 1: Works?
GLOBAL MAX is: 9223372036854775806
=================================


=================================
ATTEMPT 2: Bug?
GLOBAL MAX is: 0
=================================
```

Output with gcc-9.3 + v4.1.1 and `mpirun -n 2 ./a.out` (works correctly):

```
We live in a sane and rational universe. 
(18446744073709551615 > 9223372036854775807)

=================================
ATTEMPT 1: Works?
GLOBAL MAX is: 9223372036854775806
=================================


=================================
ATTEMPT 2: Bug?
GLOBAL MAX is: 9223372036854775808
=================================
```

I suspect that unsigned longs are somehow being treated as signed longs "under the hood" within v4.1.2, so the comparison overflows for large unsigned longs. I did diff the v4.1.1 and v4.1.2 two tags of your repo, and noticed the following addition to `ompi/datatype/ompi_datatype_module.c` in 4.1.2: 

```
    [OMPI_DATATYPE_MPI_LONG] = &ompi_mpi_long.dt,
    [OMPI_DATATYPE_MPI_UNSIGNED_LONG] = &ompi_mpi_long.dt,
```

Maybe this is a red herring, but it does seem like the second line should have `ompi_mpi_unsigned_long.dt` in it. 

Please let me know if there's anything else I can provide! Thanks for your help :)

**Comment by bosilca** [comment]
Thanks @keadyk for the report, the reproducer and the proposed fix. With this patch all seem to work fine.
