### ISSUE TITLE
openmpi-5.0.0rc6 build failing on  -ludev

### ISSUE THREAD

**Issue by naughtont3** [open-mpi/ompi#10291]
Building the openmpi-5.0.0rc6 tarball fails during link due to a missing `-ludev`.  

Not sure where the udev comes from and why it changed between rc5 and rc6.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

 - openmpi-5.0.0rc6
 - gcc 9.1.0
 - ucx 1.11.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Build from source tarball.  Same configure options/setting worked with openmpi-5.0.0rc5.

### Please describe the system on which you are running

* Operating system/version: linux
* Computer hardware: ppc64
* Network type: infiniband

-----------------------------

## Details of the problem

```shell
  $ ./configure \
        --enable-python-bindings \
       --enable-mpirun-prefix-by-default \
       --prefix=/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/openmpi-5.0.0rc6 \
      --disable-vt \
      --enable-mpi1-compatibility \
     --with-memory-manager=none \
     --with-ucx=/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/ucx-1.11.2 \
     --with-cuda=/sw/summit/cuda/11.0.3 \
    --with-knem=/opt/knem-1.1.3.90mlnx1 \
 && make && make install

...<snip>...

  CC       mpiext/mpiext.lo
  CC       patterns/net/netpatterns_base.lo
  CC       patterns/net/netpatterns_multinomial_tree.lo
  CC       patterns/net/netpatterns_nary_tree.lo
  CC       patterns/net/netpatterns_knomial_tree.lo
  CC       patterns/comm/allreduce.lo
  CC       patterns/comm/allgather.lo
  CC       patterns/comm/bcast.lo
  CC       instance/instance.lo
  CCLD     libmpi.la
/usr/bin/ld: cannot find -ludev
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2469: libmpi.la] Error 1
make[2]: Leaving directory '/autofs/nccs-svm1_sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/build/openmpi-5.0.0rc6/ompi'
make[1]: *** [Makefile:2702: all-recursive] Error 1
make[1]: Leaving directory '/autofs/nccs-svm1_sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/build/openmpi-5.0.0rc6/ompi'
make: *** [Makefile:1484: all-recursive] Error 1
```

**Comment by awlauria** [comment]
I actually hit this last week. Is your build picking up hcoll? That is how I hit it. Can you check your `config.log` for building the mca/coll/hcoll component?

We were able to work-around this by installing `systemd-devel` on the node.

**Comment by naughtont3** [comment]
Yes, looks like that is it.  I won't be able to install `systemd-devel`, but will just disable.

**Comment by janjust** [comment]
@naughtont3 , which hcoll version is this? MOFED 4.4? I'm guessing, since I see summit login node.

**Comment by awlauria** [comment]
I hit it on `hcoll-4.4.2968-1.49411.ppc64le`

**Comment by janjust** [comment]
I don't see this dependency in our current release, v4.7, checking v4.5

**Comment by janjust** [comment]
Closing this, this hcoll version is no longer supported and not part of lts releases.
