### ISSUE TITLE
main/v5.0.x branch random timeout with ompi-tests/ibm/topology/distgraph1

### ISSUE THREAD

**Issue by wzamazon** [open-mpi/ompi#10295]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

main branch

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

built from source
```
./configure --prefix=/xxx --with-sge --without-verbs --disable-builtin-atomics --with-libfabric=/xxx --enable-debug
``
### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

 6692c28a4daed5e99443eb724231d7300287fb2c 3rd-party/openpmix (v1.1.3-3495-g6692c28a)
 7ae2c083189db0881d2eff29d71bd507be02bad3 3rd-party/prrte (psrvr-v2.0.0rc1-4340-g7ae2c08318)

### Please describe the system on which you are running

* Operating system/version:  Amazon Linux 2
* Computer hardware:  Intel 
* Network type: EFA and TCP has same issue.
-----------------------------

## Details of the problem

when running the test cases in `ompi-tests/ibm`, I noticed that the `topology/distgraph1` test would randomly hang.

I used the following command to run the test
```
/path/to/mpirun \
                -np 8 -N 4 \
                --hostfile 2instances \
               /xxx/ompi-tests/ibm/topology/distgraph1
```

When the hang happens, the following  is the output:

```
using graph layout 'deterministic complete graph'
testing MPI_Dist_graph_create_adjacent
testing MPI_Dist_graph_create w/ outgoing only
testing MPI_Dist_graph_create w/ incoming only
testing MPI_Dist_graph_create w/ rank 0 specifies only
....
```

**Comment by wzamazon** [comment]
I did some debug, and I can see the hang happens inside function `ompi_comm_nextcid`.
The function called `ompi_comm_nextcid_nb`, which submitted a `comm_request`.

It then wait for the request to complete, but the request never completed.

**Comment by awlauria** [comment]
This PR seems related - might be worth trying with this fix: https://github.com/open-mpi/ompi/pull/10308

**Comment by wenduwan** [comment]
Possibly related https://github.com/open-mpi/ompi/issues/10969

**Comment by wenduwan** [comment]
The test is now passing.
