### ISSUE TITLE
`mpirun` symlink breakage on Linux+Conda environments (newest patch)

### ISSUE THREAD

**Issue by mrmundt** [open-mpi/ompi#10300]
Thank you for taking the time to submit an issue!

## Background information

We have a suite of MPI tests for our package Pyomo which utilize a Linux + Conda environment. Two days ago, a new version of `openmpi` was uploaded to Anaconda, and we are now experiencing what appears to be a symlink breakage.

Previously passing test: https://github.com/Pyomo/pyomo/runs/6032066405?check_suite_focus=true
Currently failing test (because `mpirun` command cannot be found): https://github.com/Pyomo/pyomo/runs/6098156452?check_suite_focus=true 

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Newest version available on Anaconda: linux-64/openmpi-4.1.3-hbea3300_101.tar.bz2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Through Anaconda: `conda install openmpi`

### Please describe the system on which you are running

The system on which we are running is the `ubuntu-latest` GitHub Actions runner. Full details can be found here: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md

* Operating system/version:  Ubuntu 20.04.4 LTS
* Computer hardware: VM

-----------------------------

## Details of the problem

We have previously run `conda install openmpi` and been able to run `mpirun` with no issues in our test suite (linked above). This is the expected behavior - that `openmpi` out of the box with enable `mpirun` to be found. Since the most recent update, however, we now get the error `mpirun: command not found`

**Comment by mrmundt** [comment]
UPDATE: We have been digging more into this on our end, and this is actually a particularly strange corner case it seems. When we run `conda install openmpi`, we are getting the version `4.0.2` from the default conda channel. However, later, we install `cyipopt` that flags `openmpi` as a dependency and then installs `4.1.3` from the `conda-forge` channel, and somehow in that update, the `bin` gets blown away. See below:

```
% conda create -n mpi
% conda activate mpi
% conda install -c conda-forge openmpi
% ls /home/miniconda3/envs/mpi
bin/ conda-meta/ etc/ include/ lib/ share/
% conda install -c conda-forge openmpi
% ls /home/miniconda3/envs/mpi/
conda-meta/ include/ lib/ share/  # NO MORE BIN
```
This behavior of over-writing `openmpi` was not apparent before (and there have been no updates to `cyipopt`), so not sure why this is happening now.

Previous behaviour: https://github.com/Pyomo/pyomo/runs/6032066405?check_suite_focus=true#step:14:562
Current behaviour: https://github.com/Pyomo/pyomo/runs/6098156452?check_suite_focus=true#step:14:561

**Comment by mrmundt** [comment]
UPDATE: With the release of 4.1.4, this issue still exists.

**Comment by edgargabriel** [comment]
Apologies for my lack of knowledge, but do you have any information (or any way to find out)  who created the conda openmpi package? I am not aware of the Open MPI community doing this, at least I don't recall the topic coming up on any of the conference calls. mpirun still exists in all Open MPI versions. So whoever created the package probably made a mistake and introduced the problem. Would it make sense to post this issue to the conda community or similar (assuming there is one)?

**Comment by mrmundt** [comment]
@edgargabriel - I linked the ticket we have open there, too. When we found this issue, we didn't know if it was from the build or the package.
