### ISSUE TITLE
PML selection issues

### ISSUE THREAD

**Issue by yburette** [open-mpi/ompi#1035]
We are observing two issues with the way the PML is selected:

1) on Truescale, when mpirun is used without any argument, the openib BTL (ob1 PML) gets selected over the PSM MTL (cm PML). This is a problem because users would like to get the best performance (with the PSM MTL) out-of-the-box. Instead, they have to add --mca pml  cm.

2) currently, whichever of the ob1 or the cm PML gets initialized/loaded first wins! Unfortunately, the components are not always loaded in the same order...

**Comment by yburette** [comment]
ob1 PML has a default priority of 20.
cm PML has a default priority of 10.

if ob1 is initialized first, then cm_init() sees that its priority is lower and thus returns NULL.
---> openib BTL is selected

if cm is initialized first, then it looks at which MTL can be selected. If a MTL is usable, cm's priority is bumped to 30. ob1_init() then sees that its priority is lower and thus returns NULL.
---> PSM MTL is selected

**Comment by yburette** [comment]
https://github.com/open-mpi/ompi-release/blob/v1.10/ompi/mca/pml/ob1/pml_ob1_component.c#L251
```
if((*priority) > mca_pml_ob1.priority) { 
    *priority = mca_pml_ob1.priority;
    return NULL;
}
```

https://github.com/open-mpi/ompi-release/blob/v1.10/ompi/mca/pml/cm/pml_cm_component.c#L146
```
if((*priority) > ompi_pml_cm.default_priority) { 
    *priority = ompi_pml_cm.default_priority;
    return NULL;
}
```

**Comment by yburette** [comment]
A simple fix which works for Truescale is to increase the cm PML's default priority to 20 so that it can compete with ob1.
However, this might not work for the other components (e.g. MXM, portals).

@jsquyres @hppritcha @rhc54 What do you guys think?

**Comment by hjelmn** [comment]
I would think it would be safe to remove the extra check against ob1. I will take a look and see if I can determine why cm's author did that.

**Comment by rhc54** [comment]
Can we get this resolved soon?

**Comment by jsquyres** [comment]
@yburette I'm not sure I understand the proposed solution: if you increase the default cm priority to 20, what happens?  Does CM then always increase its priority to 30 (assuming the PSM/PSM2 MTL is available)?  If so, I think we need to check with @regrant and @tkordenbrock to see what this will do for the Portals BTL / MTL combo...?

(I agree we need a solution, though (ASAP) -- what you described with the openib BTL/PSM MTL being selected according to the order in which they were loaded is Bad)

**Comment by hjelmn** [comment]
@jsquyres I agree, which is why I propose #1039 to fix this issue.

**Comment by hjelmn** [comment]
I can make similar changes to ob1.

**Comment by jsquyres** [comment]
Hah -- I just commented on the same thing (do we need the same changes in ob1?) on #1039. Our emails crossed in the ether, I guess.  :smile:

**Comment by yburette** [comment]
@jsquyres @hjelmn 
Good point and this is exactly what I lack knowledge of. For PSM/PSM2, Intel would like to have the MTL selected by default. What is the expected behavior for Portals and MXM?

I think we could increase the priority to 30 only for the desired MTLs and leave it at 20 (or even lower it back down to 10) for the others.

If we remove the conditional check from ob1, I believe we can increase cm's priority for the desired MTLs only.

All BTLs get ob1's priority (20), right?

**Comment by hjelmn** [comment]
ob1 has a priority, BTLs do not. cm works a little differently as the underlying mtl implements all the pt2pt semantics. This means that ideally the mtls should have a priority and the priority of the selected mtl should become cm's priority. I will write a quick PR to do this.

**Comment by rhc54** [comment]
let's use this issue to track getting this into 1.10.1 so I know the release is blocked until that happens

**Comment by yburette** [comment]
I think we can increase the OFI MTL's priority without impacting ob1.
By default, the OFI MTL won't run with the sockets and MXM providers.

Please see PR #1058

**Comment by regrant** [comment]
@rhc54 we've checked the new behaviour with the Portal MTL/BTL combo and things are fine with this change, so we're good to go.
