### ISSUE TITLE
some oshmem files missing from tarball when configuring with --disable-oshmem

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#1036]
This is the norm when built on a mac. If I try to build and install the tarball on another machine it fails when it get to installing the oshmem man pages. Looking at oshmem/shmem/man/man3 I see:

```
tt-fey1:/scratch1/hjelmn/openmpi-gitclone/oshmem/shmem/man/man3 hjelmn$ ls
Makefile.extra
```

This started with the fix that prevents oshmem man pages from being installed when oshmem is disabled. They should still be included in the tarball generated by make dist. Maybe add the files to EXTRA_DIST?

**Comment by hjelmn** [comment]
@miked-mellanox Please assign to the appropriate person. To reproduce configure with --disable-oshmem and the make dist.

**Comment by miked-mellanox** [comment]
@igor-ivanov - please take a look. thanks

**Comment by ggouaillardet** [comment]
imho, this is a much more general issue

for example, if you ```configure``` with ```--disable-mpi``` there are no source file in the ```/ompi``` directory (!)

**Comment by miked-mellanox** [comment]
@igor-ivanov - could you please PR it to v2.x as well
thanks
