### ISSUE TITLE
MPI-4: Bogus typedef and missing definitions and routines related to `MPI_Session`

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#10388]
I'm using branch v5.0.x from git. The [changelog](https://docs.open-mpi.org/en/v5.0.x/news/news-v5.0.x.html) claims support for `MPI_Session`, however I found the following issues:

* The installed `mpi.h` header file contains the following line:
```c
typedef int (MPI_Session_delete_attr_function)(MPI_Session, int, void *, void *);
```
To the best of my knowledge, such typedef is not defined in the MPI-4 standard document. If this typedef comes from an errata or some planned extension, then I apologize for the noise, although I should note it is a bit surprising not seeing a companion `MPI_Session_copy_attr_function` typedef.

* The following routines are missing:

  1. `MPI_Session_set_errhandler`
  2. `MPI_Session_get_errhandler`
  3. `MPI_Session_call_errhandler`

  Note however that `MPI_Session_create_errhandler` is available.

* The `MPI_ERR_SESSION` error class is missing (MPI-4, pp. 472, ln. 28). It should be used for in all of the `MPI_Session_XXX` routines to signal an invalid `MPI_Session` argument.

* The `MPI_Info_create_env` routine is missing.
  Although not strictly related to the `MPI_Session` type, the `MPI_Info_create_env` routine is the way to get something equivalent to `MPI_INFO_ENV` when using the Session model (MPI-4, pp. 484, ln. 35)

**Comment by hppritcha** [comment]
related to https://github.com/open-mpi/ompi/issues/7993

**Comment by dalcinl** [comment]
This issue should be labeled as `MPI-4.0`.

**Comment by awlauria** [comment]
merged to main and v5.0.x, closing. Thanks @hppritcha

**Comment by jsquyres** [comment]
@awlauria Do you want to re-open this?

The `MPI_ERR_SESSION` issue is being tracked at #10588

**Comment by jsquyres** [comment]
Oh, I can re-open it.  Duh.  😄

**Comment by dalcinl** [comment]
> Oh, I can re-open it. Duh.

As there is another issue tracking the leftover, you can re-close this one.
