### ISSUE TITLE
MPI-4: Missing `MPI_F_XXX` C constants

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#10391]
I'm using branch v5.0.x to assess MPI-4 support.

There are 4 trivial constants (C only) that are missing and should be trivial to add (MPI-4, pp. 844, ln. 5):

* `MPI_F_STATUS_SIZE`
* `MPI_F_SOURCE`
* `MPI_F_TAG`
* `MPI_F_ERROR`

Adding something the following lines to `mpi.h` should be enough:

```c
#define MPI_F_STATUS_SIZE OMPI_FORTRAN_STATUS_SIZE
#define MPI_F_SOURCE 0
#define MPI_F_TAG 1
#define MPI_F_ERROR 2
```

**Comment by dalcinl** [comment]
@awlauria Could you please ad the `MPI-4.0` label ?

**Comment by jjhursey** [comment]
@drwootton said that he would try to get to this next week.

**Comment by jjhursey** [comment]
PR https://github.com/open-mpi/ompi/pull/10491 has been merged. The changes will be cherry-picked to the v5.0.x, v4.1.x, and v4.0.x branches.

**Comment by jjhursey** [comment]
For reference, this has been merged into the relevant release branches.
  - main: https://github.com/open-mpi/ompi/pull/10491
  - v5.0.x: https://github.com/open-mpi/ompi/pull/10530
  - v4.1.x: https://github.com/open-mpi/ompi/pull/10534
  - v4.0.x: https://github.com/open-mpi/ompi/pull/10533
