### ISSUE TITLE
ompi 4.1.3: segmentation fault at launch on Fedora 36

### ISSUE THREAD

**Issue by tonycurtis** [open-mpi/ompi#10415]
Thank you for taking the time to submit an issue!

## Background information

4.1.3 does what's described below at launch.  4.1.2 is fine.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.1.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

source

### Please describe the system on which you are running

* Operating system/version: Fedora 36
* Computer hardware: aarch64
* Network type: tcp

-----------------------------

## Details of the problem

```
$ mpirun -n 1 ./helloworld
[arm-fedora:468901] *** Process received signal ***
[arm-fedora:468901] Signal: Segmentation fault (11)
[arm-fedora:468901] Signal code: Invalid permissions (2)
[arm-fedora:468901] Failing at address: 0x2650f540
[arm-fedora:468901] [ 0] linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xffff9da0b7dc]
[arm-fedora:468901] [ 1] [0x2650f540]
[arm-fedora:468901] *** End of error message ***
Segmentation fault (core dumped)
```

**Comment by tonycurtis** [comment]
Just rebuilt with pmix/libevent/hwloc set to =internal and all works now

**Comment by jsquyres** [comment]
Can you specify what version of PMIx you were using before you built with the Open MPI-bundled PMIx?

**Comment by tonycurtis** [comment]
`pmix-4.1.1-0.2.rc6.fc36.aarch64`

**Comment by jsquyres** [comment]
@tonycurtis I just re-discovered this issue.  😢  Do you know if this is still an issue for v4.1.4 or the upcoming v4.1.5?

**Comment by tonycurtis** [comment]
Haven't seen anything recently related to this

**Comment by jsquyres** [comment]
Ok.  Is it safe to close this issue?

**Comment by tonycurtis** [comment]
Yes, I think so
