### ISSUE TITLE
PRRTE/PMIx release schedule impact?

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#10431]
I've sometimes gotten the impression that PRRTE/PMIx are holding up OMPI v5.0 release. Yet then I look at your issue tracker and see tons of problems in the MPI/OPAL layers in v5.0, which makes me think that PRRTE/PMIx are _not_ the critical path.

So I'm not sure where you stand. We have a few "blockers" over there, and so far nobody has shown any inclination to work on them. They therefore are waiting on me, which means they will be resolved but slowly. I currently "guesstimate" PMIx v4.2 release in June (assuming I can resolve sufficient valgrind issues by then), and PRRTE v2.1 in late summer.

If that isn't soon enough, I'd suggest that people come look at the PRRTE/PMIx blockers and consider lending a hand. Otherwise, it will be on an "as-available" basis for this old retired dude.

**Comment by jsquyres** [comment]
Yo @rhc54!

Yes, you're right.  We've been trying to bang on the drum over here to get people to help with PMIx and PRTE.  We've definitely ratcheted up the pleading; I don't know if it's had much of an effect yet.

**Comment by jsquyres** [comment]
I think that this github issue was mostly a "heads up" notice from @rhc54 to us; I'm going to close it because we're tracking the need for PMIx / PRTE stuff elsewhere (i.e., the need for people to jump in and contribute to PMIx / PRTE!).
