### ISSUE TITLE
ibm/dynamic/spawn segv with openib in 2.x and master

### ISSUE THREAD

**Issue by rolfv** [open-mpi/ompi#1043]
It seems that openib is the key to things not working with spawn. I see them same errors with intercomm_create and spawn_multiple. I see this on 2.x and master but not 1.10. A few examples:
```
[rvandevaart@drossetti-ivy4 dynamic]$ mpirun -np 2 --mca btl self,sm,openib spawn
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node drossetti-ivy4 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
[rvandevaart@drossetti-ivy4 dynamic]$ 
```
```
(gdb) where
#0  0x00007f290c81a1d0 in ?? ()
#1  <signal handler called>
#2  0x00007f29130fe910 in opal_memory_ptmalloc2_free (mem=0x7f2913f4ca08)
    at ../../../../../opal/mca/memory/linux/malloc.c:3502
#3  0x00007f29130fd679 in opal_memory_linux_free_hook (__ptr=0x7f2913f4ca08, caller=0x7f2913c341bc)
    at ../../../../../opal/mca/memory/linux/hooks.c:708
#4  0x00007f2913c341bc in ompi_proc_destruct (proc=0x1cfe0f0) at ../../ompi/proc/proc.c:85
#5  0x00007f2913c33a65 in opal_obj_run_destructors (object=0x1cfe0f0) at ../../opal/class/opal_object.h:455
#6  0x00007f2913c35571 in ompi_proc_finalize () at ../../ompi/proc/proc.c:391
#7  0x00007f2913c3b0cc in ompi_mpi_finalize () at ../../ompi/runtime/ompi_mpi_finalize.c:429
#8  0x00007f2913c64195 in PMPI_Finalize () at pfinalize.c:44
#9  0x000000000040157b in main (argc=1, argv=0x7fffcbb5ab88) at spawn.c:57
(gdb) 
```
Works with TCP
```
[rvandevaart@drossetti-ivy4 dynamic]$ mpirun -np 2 -mca btl self,sm,tcp spawn
[rvandevaart@drossetti-ivy4 dynamic]$ echo $?
0
[rvandevaart@drossetti-ivy4 dynamic]$ mpirun -np 4 -mca btl self,sm,tcp spawn
[rvandevaart@drossetti-ivy4 dynamic]$ echo $?
0
[rvandevaart@drossetti-ivy4 dynamic]$ 
```

------

**EDIT:** The reentrant message below is also reported in #1081, and is therefore not being considered part of this bug.

And different when we go to np=4.
```
rvandevaart@drossetti-ivy4 dynamic]$ mpirun -np 4 -mca btl self,sm,openib spawn
[warn] opal_libevent2022_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
[warn] opal_libevent2022_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
[warn] opal_libevent2022_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
[warn] opal_libevent2022_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
[warn] opal_libevent2022_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
etc....
```

**Comment by hppritcha** [comment]
wonderful, I'm also seeing this ```reentrant invocation``` stuff - but bizillions of copies of it, when running pretty much any multi-threaded test using ```MPI_THREAD_MULTIPLE``` - at least on master.

**Comment by hppritcha** [comment]
I'd say this is a blocker. 
For ```MPI_THREAD_MULTIPLE``` we also need to get rid of this libevent message.

**Comment by rhc54** [comment]
Are you seeing it only with openib? Or with other transports as well?

**Comment by hppritcha** [comment]
Oh its with vader, ugni, tcp, etc. etc. if I'm running a multi-threaded
test.

2015-10-20 16:45 GMT-06:00 rhc54 <notifications@github.com>:

**Comment by hjelmn** [comment]
Yeah, I have seen this a lot. Took a crack at fixing this but didn't have time to finish. It might be sufficient to remove the warning in non-debug builds.

**Comment by jsquyres** [comment]
Looks like the 2nd problem (the libevent messages) is also reported in #1081.  I.e., the libevent issue is not specific to the openib spawn segv problem.

**Comment by rolfv** [comment]
I just reran a bunch of tests and I no longer see the SEGV that I noted at the beginning of this bug. The plan was to run valgrind to figure out why we were getting that SEGV, but since I no longer see that issue, that does not seem very useful. However, I still see some different issues so I am going to close this bug and open a new one with more accurate details..
