### ISSUE TITLE
Document why we still have the smcuda BTL in v5.0.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#10469]
NVIDIA has indicated that they still want to keep the `smcuda` BTL for the v5.0.x release.

We need to explain why it is still there / what+when it is used (and when it should be explicitly disabled).

FYI: @bosilca

**Comment by janjust** [comment]
We don't anymore, and I think we have lowered the `smcuda `priority, if not we will @edgargabriel. And the plan is to drop it in subsequent major version. I'm going to close this issue.
