### ISSUE TITLE
Is there a way to disable traffic striping in openmpi?

### ISSUE THREAD

**Issue by dfaraj** [open-mpi/ompi#10471]
Thank you for taking the time to submit an issue!

## Background information
on nodes with two high speed network interfaces, one on each CPU socket, it seems openmpi by default stripes the data between the two interfaces.  Is there a way to disable that? meaning, cores on first socket use attached NIC and cores on second socket use the other NIC.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
v4-1.4
and using ofi mtl

**Comment by jsquyres** [comment]
FYI @open-mpi/ofi

**Comment by bwbarrett** [comment]
If you are using the OFI MTL, each rank will chose exactly one NIC to use (of providers of the same name that are available).  There is no way to turn this behavior off, other than setting environment variables inside Libfabric to have each process only see one available provider.  You would have to check with your provider's documentation for how to best accomplish this.

**Comment by dfaraj** [comment]
Thanx @bwbarrett 
I can actually just write a wrapper script around the binary to set the X number of avail NICs per rank.
