### ISSUE TITLE
MPI_Finalize hangs

### ISSUE THREAD

**Issue by frizwi** [open-mpi/ompi#10475]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
v4.1.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Compiled from release source - with UCX

### Please describe the system on which you are running
* Operating system/version: Rocky Linux 8
* Computer hardware: Gadi supercomputer, 48 cores per node See here for more details: https://nci.org.au/our-systems/hpc-systems
* Network type: IB

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

My application completes normally, but gets stuck in MPI_Finalize()

On the master process (rank == 0)
```
#0  ompi_osc_ucx_free (win=<optimized out>) at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/mca/osc/ucx/osc_ucx_component.c:867
#1  0x0000150b17cf27d7 in ompi_win_free (win=win@entry=0x5d092e0) at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/win/win.c:362
#2  0x0000150b17cf29c6 in ompi_win_finalize () at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/win/win.c:130
#3  0x0000150b17d049c5 in ompi_mpi_finalize () at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/runtime/ompi_mpi_finalize.c:320
#4  ompi_mpi_finalize () at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/runtime/ompi_mpi_finalize.c:104
#5  0x00000000004374fc in main (argc=<optimized out>, argv=<optimized out>) at control/main.c:718

```

All other worker processes:

```
#0  0x00001537cde91a71 in poll () from /lib64/libc.so.6
#1  0x00001537cae395c5 in poll_dispatch (base=0x1d31b40, tv=0x7ffd5eaa2ba0) at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/opal/mca/event/libevent2022/libevent/poll.c:165
#2  0x00001537cae41eb5 in opal_libevent2022_event_base_loop (base=0x1d31b40, flags=<optimized out>) at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/opal/mca/event/libevent2022/libevent/event.c:1630
#3  0x00001537caeaea7b in opal_progress_events () at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/opal/runtime/opal_progress.c:191
#4  opal_progress_events () at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/opal/runtime/opal_progress.c:172
#5  0x00001537caeaeb33 in opal_progress () at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/opal/runtime/opal_progress.c:247
#6  0x00001537cf60aa25 in ompi_request_wait_completion (req=0x236f198) at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/request/request.h:440
#7  ompi_request_default_wait (req_ptr=0x7ffd5eaa2d28, status=0x7ffd5eaa2d30) at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/request/req_wait.c:42
#8  0x00001537cf5891e2 in ompi_coll_base_sendrecv_zero (stag=-16, rtag=-16, comm=0x1fb0f40, source=2, dest=2) at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/mca/coll/base/coll_base_barrier.c:213
#9  ompi_coll_base_barrier_intra_recursivedoubling (comm=0x1fb0f40, module=<optimized out>) at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/mca/coll/base/coll_base_barrier.c:219
#10 0x00001537cf4aa633 in ompi_osc_ucx_free (win=<optimized out>) at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/mca/osc/ucx/osc_ucx_component.c:875
#11 0x00001537cf5f67d7 in ompi_win_free (win=win@entry=0x2b76830) at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/win/win.c:362
#12 0x00001537cf5f69c6 in ompi_win_finalize () at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/win/win.c:130
#13 0x00001537cf6089c5 in ompi_mpi_finalize () at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/runtime/ompi_mpi_finalize.c:320
#14 ompi_mpi_finalize () at /jobfs/35197837.gadi-pbs/0/openmpi/4.1.2/source/openmpi-4.1.2/ompi/runtime/ompi_mpi_finalize.c:104
#15 0x00000000004374fc in main (argc=<optimized out>, argv=<optimized out>) at control/main.c:718
(gdb) 

```
How can I find out what they're waiting for?

**Comment by jsquyres** [comment]
Can you send a small C or Fortran example program that shows the problem?

FYI @open-mpi/ucx

**Comment by janjust** [comment]
Looks like an osc issue, a small example would help.

**Comment by janjust** [comment]
How many ranks? Nodes? Are there any that are still active? It looks like the hang is in the finalize barrier one rank waiting on others.

**Comment by hoopoepg** [comment]
according call stack it waits for completions of remote access operation

**Comment by frizwi** [comment]
Single node, 48 cores, All processes still active. FYI, I used to have a Barrier just before before the Finalize, but it still only gets stuck in Finalize. Not sure If I am able to come up with a smaller example but @hoopoepg I'll have a look more closely at any RMA calls.

I'm getting a 404 trying to access open-mpi/ucx

**Comment by jsquyres** [comment]
@open-mpi/ucx is a group of people here on Github.  My "FYI @open-mpi/ucx" notation was a github notification that alerted the UCX team / made them aware of this issue.

@bosilca had good comments in your other issue about MPI one-sided operations: https://github.com/open-mpi/ompi/issues/10474#issuecomment-1158055699

Your call stack implies that you have windows that still exist at Finalize.  I tend to stay away from MPI one-sided operations, but I thought that a technically-correct MPI application had to free its MPI handles before Finalize.  Try freeing your windows before Finalize.

**Comment by frizwi** [comment]
Thanks @jsquyres and @hoopoepg  Turns out there were some locked Windows - calling MPI_Win_unlock fixes my issues.

**Comment by jsquyres** [comment]
Ok, great!  I'll close this issue, then.
