### ISSUE TITLE
ompi/5.0.x: mpiexec -V return value is 243 instead of "0"

### ISSUE THREAD

**Issue by ericch1** [open-mpi/ompi#10486]
Hi,

just noticed that when I execute "mpiexec -V" with ompi/5.0.x branch, the return value is "243".

All other versions of MPI used to return "0" I think...

Screenshot:

```
(17:18:49) [zorg]:Test.MEF++> /opt/openmpi-5.x_debug/bin/mpiexec -V; echo $?
mpiexec (Open MPI) 5.0.0rc7

Report bugs to https://www.open-mpi.org/community/help/
213


(17:18:55) [zorg]:Test.MEF++> /opt/openmpi-4.1.2/bin/mpiexec -V; echo $?
mpiexec (OpenRTE) 4.1.2

Report bugs to http://www.open-mpi.org/community/help/
0


(17:19:02) [zorg]:Test.MEF++> /opt/openmpi-3.x_debug/bin/mpiexec -V; echo $?
mpiexec (OpenRTE) 4.1.2

Report bugs to http://www.open-mpi.org/community/help/
0

```

Is this a wanted behaviour change?

Thanks,
Eric

**Comment by jsquyres** [comment]
This feels like a bug.

**Comment by rhc54** [comment]
Yes it is - I have fixed it in https://github.com/openpmix/openpmix/pull/2628 and https://github.com/openpmix/prrte/pull/1380. Will backport those to their respective release branches when done.

**Comment by jsquyres** [comment]
Looks like this was fixed long ago.
