### ISSUE TITLE
Documentation: run-time changes v4.1.x --> v5.0.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#10480]
Originally taken from the "to-do" section in the Open MPI docs:

- [ ] #11730
    - Eliminiated all -foo options
    - Modernized some of the examples
    - Much more work needs to be done to update it for all the PRTE changes since Open MPI v4.1.x.
- [ ] #11731
- [ ] Add that we do support “single dash” `mpirun` options, but we don’t want people to do that.
- [ ] #11732
    - See https://github.com/open-mpi/ompi/issues/10222
- [ ] #11733
- [ ] https://github.com/open-mpi/ompi/issues/7668 (ORTE –> PRRTE user-visible changes)
- [ ] #11734
- [ ] #11735
    * This is an old link to section 10.8.21 -- it may or may not be correct [https://ompi–8329.org.readthedocs.build/en/8329/faq/running-mpi-apps.html](https://ompi--8329.org.readthedocs.build/en/8329/faq/running-mpi-apps.html)
    * Is "aggressive" mode really determined by the slot count provided by PRRTE? Or is it determined by a query to hwloc with a reference to the number of processes per node. It just surprises me that this part of OMPI is controlled by PRRTE instead of something more generic that might work with, say, Slurm direct launch via `srun`.
- [ ] From Ralph's comment on #11097:
    * https://github.com/open-mpi/ompi/issues/11097#issuecomment-1332337392

**Comment by qkoziol** [comment]
Working on this

**Comment by qkoziol** [comment]
Is there a definition for all of these keywords anywhere?

"* ``--map-by <object>``: Map to the specified object, defaults to
  ``package``. Supported options include ``slot``, ``hwthread``, ``core``,
  ``L1cache``, ``L2cache``, ``L3cache``, ``package``, ``numa``,
  ``node``, ``seq``, ``rankfile``, ``pe-list=#``, and ``ppr``.
  Any object can include modifiers by adding a ``:`` and any combination
  of the following:
"

**Comment by rhc54** [comment]
> Does the "don't use single dash" command-line options apply to using '-n' in the examples in the man page? i.e. should I replace them with '--n' (or '--np') ?

No - the `-n` is mandated in the MPI standard, as is `-np`

> Is there a definition for all of these keywords anywhere?

I doubt it - you might look to see if there is a "terminology" section as that would be the most likely place to find it.

**Comment by qkoziol** [comment]
On review, I see that the mpirun man page (https://docs.open-mpi.org/en/main/man-openmpi/man1/mpirun.1.html ) covers exit status behavior in section 19.1.2.6.19 and return value in section 19.1.2.8.   These seem like they should be merged into one section (probably into 19.1.2.8, since it already has the more significant heading in the manpage.  Thoughts?

**Comment by qkoziol** [comment]
There's too many diverse actions in this meta-issue and it's going to create a terrible PR (eventually).  I'm going to break them into separate issues so that they can be tackled in smaller bites.   I'll apply the same tags (to start) and assign the one(s) I've been working on to myself.

**Comment by qkoziol** [comment]
Closing this, in favor of the smaller, more focused that track individual items.
