### ISSUE TITLE
MPI_Win_lock with MPI_MODE_NOCHECK

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1049]
Per thread starting here http://www.open-mpi.org/community/lists/users/2015/10/27900.php, Sebastian Rettenberger (@rettenbs) reports:

> There seems to be a bug in MPI_Win_lock/MPI_Win_unlock in OpenMPI 1.10. The same code runs fine with OpenMPI 1.8.7 and Intel MPI.
> 
> This happens when using MPI_Win_lock with MPI_MODE_CHECK. I could reproduce this with the attached code with one rank and MPI_LOCK_EXCLUSIVE as well as MPI_LOCK_SHARED. OpenMPI is compiled with "--enable-mpi-thread-multiple" (not sure if this is important).

Sebastian's test program is here: https://gist.github.com/jsquyres/8db59c06933b0ead4921

In a later email, Sebastian said he can reproduce the issue with a single thread, too.

@hjelmn Can you have a look?  I'm tentatively labeling this a 1.10.2 issue so that it doesn't hold up 1.10.1.

**Comment by rivis** [comment]
This issue is same as #840.
Merging 2a8cc5e637844d985143aedd25b240e1c7a94482 to v1.10 will fix it.

**Comment by hjelmn** [comment]
Ok, I will PR.

**Comment by hjelmn** [comment]
Closes with open-mpi/ompi-release#700
