### ISSUE TITLE
TCP BTL and OOB need to reject non-OMPI connections

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#105]
As reported by Ake, there are real-world cases where the TCP BTL and/or OOB are accepting random incoming TCP connections (e.g., port scanners).  At best, this causes OMPI to crash, and at worst, it causes undefined behavior.  Ouch!

    http://www.open-mpi.org/community/lists/users/2010/04/12635.php

I have some fixes for the TCP BTL as part of https://svn.open-mpi.org/trac/ompi/ticket/2045 (e.g., a magic string exchange during TCP connect/accept to verify validity/compatibility of peers), but I haven't finished debugging / hardening up that mercurial branch to bring into the SVN trunk.  It seems like at least a similar magic key exchange as part of the OOB TCP would also be helpful here.

**Comment by jsquyres** [comment]
Looks like this was done forever ago.
