### ISSUE TITLE
darray and subarray issues related to type_resize

### ISSUE THREAD

**Issue by bosilca** [open-mpi/ompi#1063]
open-mpi/ompi#965 and open-mpi/ompi#1003 are describing the issue and proposing a patch for the two darray and subarray functions. However, the real problem is somewhere deeper, supposedly in the type_resize, and should be fixed there.

**Comment by bosilca** [comment]
Thanks to a hint from @ggouaillardet in the #965 ticket, I found what the problem was. In the construction of the subarray and darray types we need to move the final type in the correct position. This is not changing the upper or lower bound (which is the only result of the resize function), but instead shift the entire data map by a known displacement. The corresponding PR is #1072.

**Comment by jsquyres** [comment]
@bosilca Since #1072 has been merged to master, should we close this issue?  Or is there more work to do?
