### ISSUE TITLE
Add external component to opal/pmix framework

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#1064]
Need an external component to allow packages to link against external libpmix

**Comment by hppritcha** [comment]
Is this an enhancement or a bug?  Why should an enhancement be a blocker for 2.0 release?

**Comment by rhc54** [comment]
@hppritcha The upstream packagers require it before they will include OMPI 2.0 in their packages.

**Comment by hppritcha** [comment]
Okay, so they don't want to use the pmix1xx, but rather a version of the standalone pmix?

**Comment by rhc54** [comment]
Yeah, they don't like embedded packages. This is why we now have support for external libevent and hwloc as well. Basically, any package that is also available on its own has to be externally linked even if we have an internal version as well.

**Comment by hppritcha** [comment]
@rhc54 is this something you can get to in the next week or two?  Or would it be okay for this to wait till a post rc1 for 2.0.0?

**Comment by rhc54** [comment]
@hppritcha I think @igor-ivanov et al have got this in reasonable shape, but we are still wrestling with the libevent duplicate symbol question. So I'd say push to post rc1 is fine

**Comment by hppritcha** [comment]
changing milestone to v2.x
