### ISSUE TITLE
v4.1.x: --do-not-launch throws misleading error

### ISSUE THREAD

**Issue by jjhursey** [open-mpi/ompi#10643]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Open MPI v4.1.x branch

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

`git clone -b v4.1.x git@github.com:open-mpi/ompi.git` at commit 88bb62711a3a9a01027096b47ea31f7bb175170a

### Please describe the system on which you are running

* Operating system/version: RHEL 8.4
* Computer hardware: ppc64le
* Network type: Ethernet

-----------------------------

## Details of the problem

```shell
shell$  mpirun --host f5n17:2 --do-not-launch hostname
 Data for JOB [17227,1] offset 0 Total slots allocated 2

 ========================   JOB MAP   ========================

 Data for node: f5n17	Num slots: 2	Max slots: 0	Num procs: 2
 	Process OMPI jobid: [17227,1] App: 0 Process rank: 0 Bound: N/A
 	Process OMPI jobid: [17227,1] App: 0 Process rank: 1 Bound: N/A

 =============================================================
[f5n18:3126629] LAUNCH MSG RAW SIZE: 783
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[17227,0],0] FORCE-TERMINATE AT (null):0 - error base/plm_base_launch_support.c(595)

This is something that should be reported to the developers.
--------------------------------------------------------------------------
```

The "An internal error has occurred in ORTE" is incorrect since ORTE is just terminating without launching - which is what the user asked for.

We need to suppress the error message in this case.

**Comment by jjhursey** [comment]
For reference, below is what Open MPI `main` branch displays with PRRTE:
```shell
shell$ mpirun --np 2 --map-by :donotlaunch hostname
[f5n18:3115678] LAUNCH MSG RAW SIZE: 1039
```

**Comment by jjhursey** [comment]
PRs:
 * `v4.0.x`: https://github.com/open-mpi/ompi/pull/10645
 * `v4.1.x`: https://github.com/open-mpi/ompi/pull/10644
 * `v5.0.x` and `main` are not impacted

**Comment by jsquyres** [comment]
Fixed in both branches; closing.
