### ISSUE TITLE
Request for submodule update on v5.0.x branch

### ISSUE THREAD

**Issue by kent-cheung-arm** [open-mpi/ompi#10664]
Would it be possible to update the openpmix and prrte submodule references in time for the next v5.0.x RC release please? There is a specific fix on the openpmix v4.2 branch which is required to resolve an issue found in our testing.

Thanks.

**Comment by gpaulsen** [comment]
Hello.  Thanks for posting the issue.  We (The v5.0.x RMs) are working on doing just that in this PR: https://github.com/open-mpi/ompi/pull/10612, however there is a blocker introduced in prrte in this update that we're waiting on to merge.  See: https://github.com/open-mpi/ompi/issues/10641

**Comment by awlauria** [comment]
Closing since  #10612 was merged, which completes this ticket. @kent-cheung-arm 

That said I will shortly post another submodule update for the v5.0.0 branch today, and there will likely be one at least once per week up to the v5.0.0 release.

**Comment by awlauria** [comment]
Latest submodule PR: https://github.com/open-mpi/ompi/pull/10715

**Comment by kent-cheung-arm** [comment]
Thanks!
