### ISSUE TITLE
[5.0.x] Issues with some mpirun arguments (map-by, output-filename, indentation)

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#10669]
- Specifying the `--map-by` argument leads to an error:
```
$ mpirun -N 1 -n 2 --rank-by core  --map-by node hostname
--------------------------------------------------------------------------
When resolving deprecated command line options, the result generated
too many directives for the target option:

  Command line option: map-by
  Initial value: ��,
  Deprecated option: N ppr:1:node

Please correct the command line and try again.
--------------------------------------------------------------------------
```
Note that the `Initial value` shows a corrupted string. Overall, the error message does not provide any useful information and I don't see why `--map-by node` should not work.

- The `--output-filename` seems to work (with some heavy extension of the filename) but doesn't appear in the help output.

- There is also a bunch of indentation missing, e.g.:

```
   --default-hostfile <arg0>         Provide a default hostfile
-H|--host <arg0>                     List of hosts to invoke processes on
```

**Comment by rhc54** [comment]
Just FYI: `-N 1` resolves to a `--map-by ppr:1:node` directive. Thus, you wind up with two invocations of the `--map-by` cmd line option, and that's the error.

**Comment by awlauria** [comment]
@devreal is this resolved in your eyes? Can you try with the latest main (we did a prte/pmix submodule update this morning).

**Comment by gpaulsen** [comment]
Closing due to inaction.  Please reopen if this is still an issue with latest v5.0.x
