### ISSUE TITLE
[Q] Installation of configuration file share/openmpi/mca-btl-openib-device-params.ini

### ISSUE THREAD

**Issue by Flamefire** [open-mpi/ompi#10665]
To make it short: We install various versions of OpenMPI with easybuild and the file `share/openmpi/mca-btl-openib-device-params.ini` seems to randomly get installed or not.
We need it because we apply the following patch on our system to me it support or IB card:
```
@@ -165,7 +165,7 @@
 
 [Mellanox ConnectIB]
 vendor_id = 0x2c9,0x5ad,0x66a,0x8f1,0x1708,0x03ba,0x15b3,0x119f
-vendor_part_id = 4113
+vendor_part_id = 4113,7059,7060,7043
 use_eager_rdma = 1
 mtu = 4096
 max_inline_data = 256
```

The file was referenced at https://github.com/open-mpi/ompi/blob/v4.1.4/opal/mca/btl/openib/Makefile.am#L38 but I couldn't follow how/when it gets installed.

Can anyone provide guidance on how that file was supposed to get installed and why it may not always be there?

**Comment by jsquyres** [comment]
This file does not exist in the upcoming v5.0.x series (because the entire openib BTL has been retired in v5.0.x), but it should be present in previous versions.

**Comment by Flamefire** [comment]
Ok issue was actually caused by different `--with-verbs`/`--without-verbs` configure settings. Thanks for bringing me on the right track!
