### ISSUE TITLE
mpirun cmd line option "changes"

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#10689]
I heard today that there is some frustration/concern in the OMPI community about PRRTE cmd line option changes. I think these concerns are somewhat misplaced. It is true that cmd line options inside PRRTE have changed in recent months, specifically in the `--rank-by` area.

HOWEVER, the entire purpose of the `schizo/ompi` component is to define the _external_ user-facing cmd line options, and then _translate_ those to the _internal_ PRRTE options. This could easily have been done so that no changes were apparent to the OMPI community. The problem is that nobody is maintaining the OMPI community's schizo component, thus causing any changes in the internal options to be exposed directly to the user.

I respectively suggest, therefore, that - rather than being frustrated with the actions of the PRRTE developers - one focus on establishing a method and staffing for maintaining your PRRTE personality component. It is the responsibility of the OMPI community to do so - someone needs to step up and do it.

**Comment by jsquyres** [comment]
FWIW, in any conversation I've had about this topic, it's always been in the recognition that we -- the OMPI community -- need to go update the PRTE schitzo/ompi component.  I didn't think that there was any blame to be placed on the PRTE community.

Indeed, about a week ago, 2 OMPI community members (@awlauria and @gpaulsen) finally started looking at the current state of PRTE's schitzo/ompi component to try to reconcile it to what needs to be done in terms of updating, bug fixes, documentation, etc.  I don't know exactly where they are in that process, but I think the deadlines for PRTE v3.0 were made quite clear.  As the end of August 2022 approaches, this is going to be a problem.

**Comment by rhc54** [comment]
Thanks for the clarification - much appreciated!
