### ISSUE TITLE
OPAL_CONFIG_SUBDIR breaks with "./configure CPPFLAGS=..."

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1069]
I've noticed on master that if I do:

```sh
$ ./configure CPPFLAGS=-I...whatever...
```

Then the build eventually fails with pmix1xx not being able to find the libevent header file.

The reason is because the pmix1xx configure.m4 file does the following:

* Saves the original CPPFLAGS
* Sets CPPFLAGS to point to relevant places (including the libevent header location)
* Exports CPPFLAGS
* Calls OPAL_CONFIG_SUBDIR

But then OPAL_CONFIG_SUBDIR undoes this careful CPPFLAGS by passing $* to the sub-configure script, which dutifully passes the user-CLI-specified `CPPFLAGS=-I...whatever...` token to the sub-configure script.  This overrides the exported CPPFLAGS.

Chaos ensues in the build.

Somehow we need to remove the CPPFLAGS from the CLI options passed to the sub-configure script.

I mark this as a "blocker" bug because there are definitely users who configure this way (i.e., passing CPPFLAGS on the configure command line), and it's definitely a valid thing to do.  So we need to figure this out before we release v2.0.0.

**Comment by rhc54** [comment]
@jsquyres Gilles has had a patch sitting on this for quite some time, assigned to you for review. See 

https://github.com/open-mpi/ompi/pull/1028
