### ISSUE TITLE
Parent job should get a callback when comm_spawned job completes

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#107]
We currently rely on communicator disconnect for informing a parent that a comm_spawned job is done. ORTE knows when the child terminates, either normally or not, but has no way to communicate that back to the parent job.

Jeff and I talked very briefly about it and suggest:
- check to ensure this is the current case
- provide a mechanism for ORTE to call a provided callback fn to alert the parent job of child job termination and exit status

**Comment by rhc54** [comment]
This has been done via PMIx
