### ISSUE TITLE
[Question] How to use --report-child-jobs-separately flag?

### ISSUE THREAD

**Issue by afonari** [open-mpi/ompi#10737]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
v 3.1.5

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

OpenMPI from the nvidia HPC sdk.

When I run a program, I get:
```
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
```

I thought if I add `--report-child-jobs-separately` the job should exit with 0 erorr code. But it doesn't. Can someone enlighten me please.

**Comment by jsquyres** [comment]
@open-mpi/ucx This seems to be an NVIDIA HPC SDK question.  Can you answer?

**Comment by rhc54** [comment]
Nah, it's an ORTE question. It sounds like you have a job that doesn't call comm_spawn, and so there is only the one job. The message is telling you that all the procs in the job terminated "normally", meaning that none of the procs terminated by signal (e.g., a segfault). However, at least one process returned a non-zero exit, which we treat as an error, and so we return that status.

The `--report-child-jobs-separately` flag controls what we report if your job _does_ call comm_spawn. In that case, we report the comm_spawn'd jobs separate from the primary job. You aren't seeing that report, which tells me your app doesn't call comm_spawn.

**Comment by afonari** [comment]
Gotcha, thanks for the explanation @rhc54, closing.
