### ISSUE TITLE
OMPI main cannot build with internal PRRTE and PMIx?

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#10755]
I'm trying to build OMPI's main branch with the internal PMIx and PRRTE submodules. However, PRRTE configure fails every time complaining that it cannot find the PMIx devel headers. This makes perfect sense as those headers aren't installed until PMIx gets built, but I cannot help but wonder how others are getting around this problem?

I can use the external alternatives - just wondering why the default build is failing out-of-the-box. This is on Mac Monterey, this morning's head of OMPI main.

**Comment by awlauria** [comment]
It might be mac specific issue. MTT ran clean last night, and CI is completing successfully. Can someone else with a mac confirm?

**Comment by rhc54** [comment]
Seems to be something being left behind that causes the problem. If I build from a fresh clone, it works. However, if I take a clone and build it against external support, and then try to reconfigure for internal support, it is borked.

Probably not worth chasing down. I honestly don't build the code very much any more, but just wondered if I was missing something.

**Comment by awlauria** [comment]
You may have needed to do a `make distclean` before rebuilding in that case.

**Comment by rhc54** [comment]
Quite possible - just very unexpected and consumed a fair amount of time trying to figure out what to do about it.

🤷‍♂️  Like I said, I don't build it very often at all - I think this is the first time in at least 6 months - so not worth worrying about.
