### ISSUE TITLE
compat open-mpi for redhat 8.5

### ISSUE THREAD

**Issue by JMSnyder1980** [open-mpi/ompi#10773]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
 mpi version 4.11

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

I installed it using yum installl

### Please describe the system on which you are running

* Operating system/version:   redhat 8.5.1

-----------------------------

## Details of the problem

How do I install compat open mpi on redhat 8.5.1?
```

**Comment by jjhursey** [comment]
This is more of a question for the RHEL package maintainers. Looking at my RHEL 8.6 box I only see an `openmpi` and `openmpi-devel` pair of packages.

I did find [this old RHEL ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1158864#c11) talking about changes to the `compat-openmpi` package between RHEL 6 and 7. My best guess is that they dropped it in RHEL 8.

**Comment by jjhursey** [comment]
I will close this since it looks like a RHEL packaging issue. I have used Open MPI (installed from the tarball, and from `yum openmpi` -- just not with the `compat-openmpi` target) on RHEL 8.6.
