### ISSUE TITLE
MAN PAGES: may need to update the ERRORS section for MPI 4.0 

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#10783]
Currently there's a pretty generic ERRORS section in 308 of our man3 man pages with wording like this:
```
Before the error value is returned, the current MPI error handler is
called. By default, this error handler aborts the MPI job, except for
I/O function errors. The error handler may be changed with
:ref:`MPI_Comm_set_errhandler`; the predefined error handler MPI_ERRORS_RETURN
may be used to cause error values to be returned. Note that MPI does not
guarantee that an MPI program can continue past an error.
```

In some places MPI_File_set_errhandler, etc. is used for calls with explicit win, file, or sesssion.

There is no mention of the initial error handler introduced as part of the MPI 4.0 standard.
This quasi-generic blurb should probably be updated to reflect changes with default error handling semantics as defined in MPI 4.0.   Note Open MPI main does comply (modulo bugs) with the MPI 4.0 standard.

**Comment by jjhursey** [comment]
`main` PR: https://github.com/open-mpi/ompi/pull/11015

**Comment by jjhursey** [comment]
This issue can be closed as completed:
 * `main` https://github.com/open-mpi/ompi/pull/11015 and https://github.com/open-mpi/ompi/pull/11077
 * `v5.0.x` https://github.com/open-mpi/ompi/pull/11079 (includes both of the PRs above)
