### ISSUE TITLE
mpirun all of ranks are zero, but mpiexec is work

### ISSUE THREAD

**Issue by Ttw0626** [open-mpi/ompi#10799]
### Background

the MPICH could work in my PC, however, I am going to build the Openmpi on my PC and remove totally the MPICH.
However, before the remove, the mpirun of Openmpi will show that all of ranks are zero,
after the remove of MPICH, the case is same.

What's more, the speed of execution is too too slow compared to mpirun of MPICH.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Version := v4.1.4 from tar.gz source

what's more, I already attempted many times to install the openmpi from apt-get. the case is same.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

from a source/distribution tarball
from an operating system distribution package,

### Please describe the system on which you are running

* Operating system/version: Kubuntu 22.04.1 LTS x86_64
* Computer hardware: 12th Gen Intel i9-12900K (24) @ 5.200GHz; NVIDIA GeForce GTX 1070.....
* Network type: LAN

-----------------------------

## Details of the problem

until now, the mpiexec of Openmpi cannot work again. i will show the simple test in below.

## Openmpi
```shell
shell$ mpiexec -np 8 ./PETSc_test
```
```shell
 hello, DAMASK from rank            0
 hello, DAMASK from rank            0
 hello, DAMASK from rank            0
 hello, DAMASK from rank            0
 hello, DAMASK from rank            0
 hello, DAMASK from rank            0
 hello, DAMASK from rank            0
 hello, DAMASK from rank            0
```
## Mpich
it will good.

## Thanks
could someone give me any help!!

**Comment by rhc54** [comment]
Did you recompile the program using OMPI? The two MPI implementations are not binary compatible. This is usually one of the signs.

**Comment by ggouaillardet** [comment]
you can 
```
$ type mpiexec
$ mpiexec --version
$ ldd PETSc_test
```

and see if you can spot some inconstancy.

**Comment by jsquyres** [comment]
> Did you recompile the program using OMPI? The two MPI implementations are not binary compatible. This is usually one of the signs.

That, or using the `mpiexec` from Open MPI with an MPICH-compiled binary, or using the `mpiexec` from MPICH with an Open MPI-compiled binary.

To be 100% clear:

- To use Open MPI, you must compile your app with Open MPI's wrapper compilers and use Open MPI's `mpiexec` (or `mpirun` -- `mpirun` and `mpiexec` are exactly identical/equivalent in Open MPI)
- To use MPICH, you must compile your app with MPICH's wrapper compilers and use MPICH's `mpiexec.

**Comment by Ttw0626** [comment]
Thanks!!!! 

Until now, I thought I already fixed it.

I re-install the OS. hahahha. i can't find another way.

Thanks all.

**Comment by jsquyres** [comment]
Sounds like the issue is resolved.  Great!

Open a new issue if something else comes up.
