### ISSUE TITLE
OAC submodule pulled from my own fork

### ISSUE THREAD

**Issue by abouteiller** [open-mpi/ompi#10816]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

main / ee324be1 

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Forked Open MPI, pulled from my own repo

## Details of the problem

`git submodule update --init --recursive` fails because it tries to obtain the git repo `abouteiller/oac`, which does not exist (if it existed, it may not contain the wanted hash, as it may become outdated w.r.t. the origin/upstream).

## Proposed resolution

Change `../oac` to `../../open-mpi/oac` in `.gitmodules`

**Comment by bwbarrett** [comment]
happy to take a pull request...
