### ISSUE TITLE
[FR] Color coding for ompi_info

### ISSUE THREAD

**Issue by gkatev** [open-mpi/ompi#10813]
Hello, I'd like to throw in a low-importance quality-of-life improvement: add colors to the output of ompi_info. I'm mostly thinking of this for MCA parameters, to help navigate long outputs.

I've prototyped an example of what something like this might look like:

![tuned_both](https://user-images.githubusercontent.com/31203804/191004649-371df6f5-de87-4d97-8e92-3b3872beba94.png)

**Comment by bosilca** [comment]
Nice. One suggestion: enable colors only when the terminal has ANSI capabilities and we are not dumping the MCA as parsable.

**Comment by jsquyres** [comment]
That is super awesome - I love it!  🎉  Can you make a PR?

I do echo @bosilca's suggestion, though -- only use colors if it's a TTY (e.g., if you pipe the output of `ompi_info` through `less` or `more` or something, we don't want ANSI sequences in there.

**Comment by gkatev** [comment]
Perfect! Yea, I will look around and see where to implement it.

**Comment by gkatev** [comment]
I created #10820 (draft), and will gradually update it in the next days.
