### ISSUE TITLE
MPI_Parrived has wrong signature in mpi.h

### ISSUE THREAD

**Issue by jprotze** [open-mpi/ompi#10826]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v5.0.0rc7 and git/main

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Independent of installation. The problem is in the public API header

### Please describe the system on which you are running

Independent of system. The problem is in the public API header

-----------------------------

## Details of the problem

The mpi.h header defines MPI_Parrived with `MPI_Count partition`:
https://github.com/open-mpi/ompi/blob/main/ompi/include/mpi.h.in#L1857

The MPI standard and also OpenMPI doc defines MPI_Parrived with `int partition`:
https://docs.open-mpi.org/en/v5.0.x/man-openmpi/man3/MPI_Parrived.3.html

**Comment by jsquyres** [comment]
Excellent catch; thank you!

I've filed #10831 to fix `main`; will cherry-pick it to `v5.0.x` when that PR is merged.

**Comment by jjhursey** [comment]
PRs have been merged:
 * `main` https://github.com/open-mpi/ompi/pull/10831
 * `v5.0.x` https://github.com/open-mpi/ompi/pull/10839
