### ISSUE TITLE
NEWS doesn't mention ABI incompatibility for 1.10

### ISSUE THREAD

**Issue by loveshack** [open-mpi/ompi#1083]
It seems particularly relevant when NEWS says it's based on the 1.8 series, and rather suggests compatibility.

**Comment by rhc54** [comment]
Fair point - the numbering change indicates an ABI break, but the fact that we say it is based on v1.8 might have mistakenly given that impression. I've corrected the NEWS to make clarify the situation.

Thanks!

**Comment by jsquyres** [comment]
Just to cross ref this (already-closed) issue:

* Here's the commit on master: 186c18be0ecbf113a3fab2cfaf1d9951bdf868dd
* Here's the PR for v2.x: open-mpi/ompi-release#733

**Comment by rhc54** [comment]
I believe it also went into 1.10.1, didn't it? I meant to have it do so...

**Comment by jsquyres** [comment]
Yes, it looks like it did.
