### ISSUE TITLE
MPI_Group_from_session_pset should use PMIX_QUERY_PSET_MEMBERSHIP

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#10862]
The current implementation of MPI_Group_from_session_pset will only work for process sets defined as part of the job launch mechanism.  PMIx allows for a more general approach for querying for the list of pmix_proc's in a pset.  We should use this query function to support use cases involving more flexible generation of pset names going forward.

**Comment by rhc54** [comment]
FWIW: IIRC, I added the ability for PMIx to dynamically define process sets. I can check and ensure PRRTE supports it as well. Not sure if that is relevant to what you are denoting here, but thought I'd pass it slong just in case.

**Comment by rhc54** [comment]
Also FWIW - you are correct about using the query function. Only the initial process set definitions are available to all procs in the job info. Dynamically created ones are known to their participants - others need to query for them. I'll ensure PRRTE supports that query.

**Comment by hppritcha** [comment]
bot:aws:retest

**Comment by hppritcha** [comment]
fixed via multiple commits both in openmpi and prrte
