### ISSUE TITLE
Poor message on binding failures

### ISSUE THREAD

**Issue by loveshack** [open-mpi/ompi#1087]
help-orte-rmaps-base.txt talks about libnumactl and libnumactl-devel, but shouldn't.  The equivalent library probably only exists on GNU/Linux systems and has a distribution-specific name.  The -dev/-devel package is irrelevant at runtime (and even at build time if you you use system hwloc).  What is relevant is a working hwloc, which is system-independent.

The useless github system will doubtless mangle this suggested patch, but I can mail it if someone wants to apply it as-is.

```diff
diff --git a/orte/mca/rmaps/base/help-orte-rmaps-base.txt b/orte/mca/rmaps/base/help-orte-rmaps-base.txt
index ac89d7e..3333a41 100644
--- a/orte/mca/rmaps/base/help-orte-rmaps-base.txt
+++ b/orte/mca/rmaps/base/help-orte-rmaps-base.txt
@@ -159,8 +159,7 @@ A request was made to bind a process, but at least one node does NOT
 support binding processes to cpus.
 
   Node:  %s
-This usually is due to not having libnumactl and libnumactl-devel
-installed on the node.
+This usually is due to not having a working libhwloc on the node.
 #
 [rmaps:membind-not-supported]
 WARNING: a request was made to bind a process. While the system
@@ -169,9 +168,8 @@ support binding memory to the process location.
 
   Node:  %s
 
-This usually is due to not having the required NUMA support installed
-on the node. In some Linux distributions, the required support is
-contained in the libnumactl and libnumactl-devel packages.
+This usually is due to not having the required NUMA support supplied
+by a working libhwloc on the node.
 This is a warning only; your job will continue, though performance may be degraded.
 #
 [rmaps:membind-not-supported-fatal]
@@ -181,10 +179,8 @@ support binding memory to the process location.
 
   Node:  %s
 
-This usually is due to not having the required NUMA support installed
-on the node. In some Linux distributions, the required support is
-contained in the libnumactl and libnumactl-devel packages.
-The provided memory binding policy requires that we abort the job at this time.
+This usually is due to not having the required NUMA support supplied
+by a working libhwloc on the node.
 #
 [rmaps:no-bindable-objects]
 No bindable objects of the specified type were available
```

EDIT: Added diff syntax hilighting

**Comment by jsquyres** [comment]
@loveshack FWIW, if you put a patch inside triple-single-quotes followed by the "diff" token, it'll both put it in fixed-width font, but it'll also syntax highlight it.  I took the liberty of editing your initial description to add that.

Per your help messages.  Mmmm.  I see what you're doing there.  I agree that the current messages could be improved, but at least let me tell you the rationale: we didn't mention hwloc because it's (usually) hidden from the user.  I.e., the internal hwloc is used.  So from the OMPI-installer point of view, it's libnuma that matters, not hwloc.

But your points still stand:

* The -dev[el] packages aren't necessary on the run nodes; only when OMPI is installed.
* libnuma is Linux-specific

I don't have a better suggestion at the moment -- I have to run.  I'm open to suggestions...

**Comment by ggouaillardet** [comment]
at first, we could we have two distinct error messages
1. internal hwloc was built without libnumactl headers (so that cannot work unless ompi is rebuilt)
2. that could/should work, but it does not (and we just mention libnumactl and not its headers) so we avoid confusion (e.g. devel headers are not required on compute nodes)
makes sense ?

**Comment by loveshack** [comment]
Jeff Squyres <notifications@github.com> writes:

> Per your help messages.  Mmmm.  I see what you're doing there.  I
> agree that the current messages could be improved, but at least let me
> tell you the rationale: we didn't mention hwloc because it's (usually)
> hidden from the user.

Probably not with any packaged version, though they may not be "usual",
unfortunately.

> I.e., the internal hwloc is used.  So from the
> OMPI-installer point of view, it's libnuma that matters, not hwloc.

I don't know why hwloc is bundled -- and bundling is at least part of
the problem -- but presumably you'd solve this issue by also bundling
libnuma and then checking that built hwloc components work (assuming
you're not cross-building, or do it in installation).

> But your points still stand:
>
> * The -dev[el] packages aren't necessary on the run nodes; only when
> OMPI is installed.

s/installed/built/ ?
and then only with the bundled hwloc.

> * libnuma is Linux-specific

It's also distribution- (library name-wise) and architecture-specific.
Even on Linux, it's absent at least from arm and s390, amongst the
official Debian architectures.

**Comment by loveshack** [comment]
Gilles Gouaillardet <notifications@github.com> writes:

> at first, we could we have two distinct error messages
> 1. internal hwloc was built without libnumactl headers (so that cannot
> work unless ompi is rebuilt)
> 2. that could/should work, but it does not (and we just mention
> libnumactl and not its headers) so we avoid confusion (e.g. devel
> headers are not required on compute nodes)
> makes sense ?

Afraid not.  The fundamental issue is whether you have a working hwloc,
whatever the system-specific support under that needs to be.  If there
isn't a useful MCA flag to debug the problem, as it seems, probably
there should be one.

**Comment by jsquyres** [comment]
New suggestion (this would be the basis for all 3 messages):

> A request was made to bind a process, but at least one node does NOT support binding processes to cpus.
>
>   Node:  %s
>
> Open MPI uses the "hwloc" library to perform process and memory binding.  This error message means that hwloc has indicated that processor binding support is not available on this machine.
>
> On OS X, processor and memory binding is not available at all (i.e., the OS does not expose this functionality).
>
> On Linux, lack of the functionality can mean that you are on a platform where processor and memory affinity is not supported in Linux itself, or that hwloc was built without NUMA and/or processor affinity support.  When building hwloc (which, depending on your Open MPI installation, may be embedded in Open MPI itself), it is important to have the libnuma header and library files available.  Different linux distributions package these files under different names; look for packages with the word "numa" in them.  You may also need a developer version of the package  (e.g., with "dev" or "devel" in the name) to obtain the relevant header files.
> 
> If you are getting this message on a non-OS X, non-Linux platform, then hwloc does not support processor / memory affinity on this platform.  If the OS/platform does actually support processor / memory affinity, then you should contact the hwloc maintainers: https://github.com/open-mpi/hwloc.

**Comment by loveshack** [comment]
> New suggestion (this would be the basis for all 3 messages):

Looks good to me.  The only suggestion would be to mention if there's
any means of debugging failures.  I'd have hoped there'd be some
..._verbose MCA-ism that would at least show if the component failed due
to dynamic linkage (e.g. not being able to load libnuma) or some other
reason.

That's a general issue, though.  I've wished for a means of
debugging/checking .so's of other components that might fail for want of
the correct dynamic linkage, whether it's missing objects or wrong
versions with missing symbols.

**Comment by ggouaillardet** [comment]
@bgoglin

does hwloc links with or dlopen libnumactl ?
is there an api to query whether hwloc was built with libnumactl ?

Thanks,

Ｇｉｌｌｅｓ

**Comment by bgoglin** [comment]
hwloc needs libnuma for memory-binding syscalls (most are not in libc, for instance mbind et set_mempolicy), so yes it links with it.
There's no direct API to query libnuma, but there's a query for binding abilities:
```.c
#include <hwloc.h>
#include <stdio.h>

int main()
{
  hwloc_topology_t topo;
  const struct hwloc_topology_support *support;
  hwloc_topology_init(&topo);
  hwloc_topology_load(topo);
  support = hwloc_topology_get_support(topo);
  printf("set_area_membind support = %d\n", (int)support->membind->set_area_membind
  printf("set_thisthread_membind support = %d\n", (int)support->membind->set_thread_membind
  hwloc_topology_destroy(topo);
  return 0;
}
```
When built with libnuma:
```
set_area_membind support = 1
set_thisthread_membind support = 1
```
When built without libnuma, you get 0 instead of 1.

There are other membind features that you could check as well. But at least these two ones use syscalls that require libnuma.

**Comment by jsquyres** [comment]
Yeah, `support->membind->set_area_membind` is what we already check in OMPI.

I'll update the warning message to what I showed above (https://github.com/open-mpi/ompi/issues/1087#issuecomment-153442269), but I won't be able to get to this until after SC / the US Thanksgiving holiday.
