### ISSUE TITLE
need ability to not use --enable-new-dtags option in linker scripts.

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#1089]
It turns out the --enable-new-dtags linker option in the Open MPI compiler scripts is causing issues for some users:

Here's what a sysadmin reported:

Many of our users want to encode an RPATH to the MPI library in their executable at link time.  In fact,   they like to encode paths to all of their other libraries this way.  On Linux, RPATH overrides anything a user sets in LD_LIBRARY_PATH, which provides one way for our app developers to ensure that thier users are getting the correct set of libraries (they can't mess things up with a wrong LD_LIBRARY_PATH setting).  The --enable-new-dtags flag changes things so that LD_LIBRARY_PATH settings now override any RPATH setting, which breaks our apps.

MVAPICH recently added the --enable-new-dtags flag to their wrappers starting with MV2-2.1, which broke many of our applications.  At that point, I also looked into Open MPI and found that this option was added somewhere by the time 1.8.3 was released.  Apparently, this particular set of users wasn't using Open MPI, and so we didn't notice the change in Open MPI until now.

I asked MVAPICH to add a configure flag to avoid the --enable-new-dtags option.  I now configure MV2-2.1 to drop this flag in the wrappers.  I was looking to see if there's a similar fix already in Open MPI that we could use, and if not, if something could be added.
-Adam

@adammoody

**Comment by jsquyres** [comment]
@adammoody Does `--disable-wrapper-rpath` not work for you?

**Comment by payerle** [comment]
Please allow an option to disable adding the --enable-new-dtags flag.  
We are running into issues with it for openmpi/1.10.2 built with intel/2016.3.210 compiler suite; the
compiler environmental setup scripts sets LD_LIBRARY_PATH to include the path to Intel MPI libraries,
which are being preferred to the OpenMPI libraries set in rpath (because if DT_RUNPATH is set, DT_RPATH is ignored, so LD_LIBRARY_PATH takes precedence over both).  

I can hack the configure scripts, etc. to mimic an loader which does not support --enable-new-dtags,
but it would be nice to have a configure option.  Please add an option to disable this.

**Comment by adammoody** [comment]
@hppritcha we recently stumbled into this issue again.  Any update here?

For now, I'm planning to hack configure to remove the --enable-new-dtags, but that's my ugly solution.

I'm hoping we could get a --disable-new-dtags configure option added to config/opal_setup_wrappers.m4 to do the same.  Basically, the idea would be to skip running OPAL_SETUP_RUNPATH if --disable-new-dtags is thrown.  I could post a PR for this.  Just let me know.  Thanks!

**Comment by hppritcha** [comment]
@adammoody let me know if the patch works

**Comment by hppritcha** [comment]
reopening issue because some sites are wanting this back ported to 3.x.y releases.

**Comment by icdragn** [comment]
Isn't this already in 3.1.x? At least, the configure option is there...

**Comment by jsquyres** [comment]
@hppritcha I think @icdragn is right:

```
$ pwd
/home/jsquyres/openmpi-releases/openmpi-3.0.3
$ ./configure --help |& grep rpath
  --enable-wrapper-rpath  enable rpath/runpath support in the wrapper

$ cd ../openmpi-3.1.3
$ ./configure --help |& grep rpath
  --enable-wrapper-rpath  enable rpath/runpath support in the wrapper
                          supports it (default: enabled, unless wrapper-rpath
```

Are you talking about something else?

**Comment by dshrader** [comment]
Actually, I think the configure parameter that @hppritcha is looking for is `--enable-wrapper-runpath`:

```
$ tar xjf openmpi-3.1.3.tar.bz2 
$ cd openmpi-3.1.3/
$ ./configure -h | grep -A 2 runpath
  --enable-wrapper-rpath  enable rpath/runpath support in the wrapper
                          compilers (default=yes)
  --enable-wrapper-runpath
                          enable runpath in the wrapper compilers if linker
                          supports it (default: enabled, unless wrapper-rpath
                          is disabled).
```

**Comment by hppritcha** [comment]
@jsquyres you're right.  the admin is wanting to install 3.0.x which apparently didn't get this patch

**Comment by jsquyres** [comment]
@hppritcha We're gearing up for v3.0.x and v3.1.x releases.

I confirm that this fix is in v3.0.x, but it is ***NOT*** in v3.1.x.

Did you want this in v3.1.x?  If so, please file a PR ASAP.

**Comment by hppritcha** [comment]
@jsquyres i'll see into opening a pr for 3.1.x

**Comment by hppritcha** [comment]
won't fix.   not planning to release 3.0.x update unless there's something critical.  and this issue doesn't fall into that category.

**Comment by cponder** [comment]
The flag showed up with compiling OpenACC 5.0.5 on an ARM system running Rocky Linux release 9.3 (Blue Onyx) using the NVHPC 24.9 compiler:
```
nvfortran-Error-Unknown switch: --enable-new-dtags
```
I set these to bypass it
```
export  FCFLAGS=" -noswitcherror ..."
export  LDFLAGS=" -noswitcherror ..."
```
but it didn't show up in the failing phase. Is there some other place I need to put it, like `-Wlink,-noswitcherror` or something?
If i set `--disable-wrapper-rpath` I get this error
```
configure: error: --enable-wrapper-runpath cannot be selected with --disable-wrapper-rpath
```
though I'm not setting `-enable-wrapper-runpath` anywhere.

**Comment by cponder** [comment]
Passing it as part of the compiler invocation worked:
```
export F90="nvfortran -noswitcherror"
export FC="nvfortran -noswitcherror"
```
Is there a variable that would do it, though? I tried LDFLAGS but it didn't show up in the linkage-line.
