### ISSUE TITLE
mpi4py: Getting PMIX ERROR: BAD-PARAM with branch v5.0.x

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#10902]
This is with branch v5.0.x running mpi4py test suite on GitHub Actions.

I'm seeing the following output in the logs:

```
PMIX ERROR: BAD-PARAM in file client/pmix_client_connect.c at line 377
```

Full logs [here](https://github.com/mpi4py/mpi4py-testing/actions/runs/3200864393/jobs/5228254114)

**Comment by dalcinl** [comment]
I forgot to clarify: All tests are successful. But the message is suspicious and unexpected. So I'm reporting it.

**Comment by awlauria** [comment]
Looks like these are happening in spawn tests.

**Comment by awlauria** [comment]
@dalcinl have you seen this happen in main?

**Comment by dalcinl** [comment]
@awlauria A build of main that ran 3 days ago is clean [[logs]](https://github.com/mpi4py/mpi4pytesting/actions/runs/3208534158/jobs/5244481729), no error messages at all.

**Comment by dalcinl** [comment]
@awlauria @jsquyres I don't recall whether any of you guys took any explicit action on this issue. FWIW, I'm no longer seeing these messages when running mpi4py testsuite on GitHub Actions using `open-mpi/ompi@v5.0x`. Therefore, I believe you can close this issue.

**Comment by awlauria** [comment]
Thanks - it was probably fixed in a submodule pointer update. Closing.
