### ISSUE TITLE
Memory pool and registration cache rewrite

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#1094]
The current memory pool interface includes quite a bit of "registration cache" functionality. I am working on a rewrite of both frameworks to move this functionality down to rcache. It would be best if this goes into 2.0.0. Master PR coming shortly.

**Comment by hppritcha** [comment]
this has been deemed not a blocker by the v2.0.0 RMs

**Comment by jsquyres** [comment]
@hjelmn Can you make a strong argument for this for v2.0.0?  @hppritcha's and my gut feeling is that we should be closing the door on major new features for v2.0.0 and push this one off to v2.1.0.

**Comment by hjelmn** [comment]
Depends. What is the timeframe for v2.1.0? If it is guaranteed to be before we June I see no problem with pushing this off the v2.1.0. If not I think this should be in v2.0.0 since right now the mpool and rcache design is completely broken by the btl move. The old mpool=blah info key stuff is broken (works in v1.10).

The only issue with this PR is I haven't been able to reproduce the Mellanox failure. Looks like something is stomping on memory but its impossible to tell what from the backtrace.

**Comment by jsquyres** [comment]
I don't think we can *guarantee* before June, but I would certainly hope it is before June.

**Comment by jsquyres** [comment]
I should clarify/soften my previous comment: I only say "I don't think we can *guarantee* [v2.1] before June..." simply because I can't predict the future.  I'm unaware of any specific issues that would prevent a v2.1 before June -- I just don't want to commit/promise it this far out.

**Comment by hjelmn** [comment]
This is complete.
