### ISSUE TITLE
Accelerator framework caused IMB MPI1 Gather regression on EFA fabric

### ISSUE THREAD

**Issue by wenduwan** [open-mpi/ompi#10965]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
https://github.com/open-mpi/ompi/commit/7bcbc7a9ca78817e81c100c5dac5785efa74444a

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

```
git clone --recursive https://github.com/open-mpi/ompi.git
cd ompi
git checkout <commit id>
git submodule update --init --recursive
./autogen.pl
./configure --prefix=/home/ec2-user/ompi/install --without-verbs --with-libfabric=/opt/amazon/efa --disable-man-pages --with-libevent=external --with-hwloc=external --disable-builtin-atomics
make -j32
make install
```

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

```
$git submodule status
 1f0b53f482a659e3a19e20983fc1b0637b52bb14 3rd-party/openpmix (v1.1.3-3617-g1f0b53f4)
 30b32226af6b87efab1d2267d0bb30f59c6c6de6 3rd-party/prrte (psrvr-v2.0.0rc1-4433-g30b32226af)
 5c8de3d97b763bf8981fb49cbedd36e201b8fc0a config/oac (5c8de3d)
```

### Please describe the system on which you are running

* Operating system/version: AmazonLinux2
* Computer hardware: EC2 c5n.18xlarge * 16 nodes
* Network type: EFA

-----------------------------

## Details of the problem

We observed that this commit caused a 12% regression in avg latency (1939.89 us vs 1726.18 us) of 256kb IMB (v2021.3) MPI1 Gather benchmark.

**Comment by shijin-aws** [comment]
AWS is actively working on this issue.

**Comment by wckzhang** [comment]
I'm pretty sure this is a libfabric/EFA bug and not an OMPI bug. Resolving.

**Comment by wckzhang** [comment]
To shine a little light on the issue, the issue arises from calling fi_getinfo with FI_HMEM capability hint (which fails) before calling fi_getinfo without FI_HMEM capability hint (which succeeds). If you just call fi_getinfo without the FI_HMEM capability hint, there is no performance issue. This indicates that there is some performance impact from calling fi_getinfo.
