### ISSUE TITLE
5.0.0rc8 oshmem segfault in exit handler

### ISSUE THREAD

**Issue by david-edwards-arm** [open-mpi/ompi#10978]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
5.0.0rc8 with Open UCX 1.13.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
tarball

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04
* Computer hardware: x86_64

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

The following program (built with oshcc) segfaults in the exit handler:
```
#include <shmem.h>

int main()
{
    start_pes(0);
    return 0;
}
```

The issue appears to be dereferencing a null pointer: `mca_memheap_base_alloc_exit()` calls both `mca_sshmem_segment_detach()` and `mca_sshmem_unlink()`, the first of which sets the `map_segment_t` context to NULL (in `shmem_ds_reset()`), however it is deferenced without a null check in the second (in `segment_unlink()`).

**Comment by MamziB** [comment]
@david-edwards-arm Can you please share more info about build and command line you are using?
I am using the latest ucx branch/ latest v5.0.x and nothing fails. I ran it like below on one node.
```
./oshrun -np 4  ./a.out
````

**Comment by janjust** [comment]
@david-edwards-arm , quick reminded on this issue - we're not able to reproduce it - does it still reproduce for you? I'm not sure if anything went into > rc8 that fixes the issue? Please let us know, I'd like to close this issue if it's not reproduced anymore

**Comment by david-edwards-arm** [comment]
@janjust @MamziB I've looked further into this and the issue has since been fixed in commit https://github.com/open-mpi/ompi/commit/6ec559d1fae8082f5ae48449c1926ad3856d727f on 2022-11-23:

> **oshmem: Fix segment reset**
Do not clear pointer to segment context in shmem_ds_reset, as it can be
used by the following segment_unlink call

Close as duplicate.
