### ISSUE TITLE
[mpi4py] GitHub Actions, `mca_sharedfp_sm_component_file_query` warning, singleton init mode

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#10971]
This is with `v5.0.x` and `main`, and it is probably not a new issue, it has been happening for at least a month. I'm a bit late reporting, sorry about that.

When running mpi4py testsuite on GitHub Actions, I have a step that runs on singleton mode. In that step, I get the following warnings:
```
[fv-az395-738:129846] mca_sharedfp_sm_component_file_query: Error, unable to open file for mmap: /tmp/ompi.fv-az395-738.1001/jf.0/1534787584/mpi4py-0qcrl3_pv_cid--1-0.sm
[fv-az395-738:129846] mca_sharedfp_sm_component_file_query: Error, unable to open file for mmap: /tmp/ompi.fv-az395-738.1001/jf.0/1534787584/mpi4py-epzxgk44_cid--1-0.sm
[fv-az395-738:129846] mca_sharedfp_sm_component_file_query: Error, unable to open file for mmap: /tmp/ompi.fv-az395-738.1001/jf.0/1534787584/mpi4py_dcj2mn4_cid--1-0.sm
```
See [here](https://github.com/mpi4py/mpi4py-testing/actions/runs/3301361631/jobs/5446742769#step:17:1) for full logs.

The following steps run tests under `mpiexec`, no warnings are printed.

**Comment by edgargabriel** [comment]
@dalcinl thank you for reporting this, I will have a look.

**Comment by edgargabriel** [comment]
@dalcini, would you mind testing pr https://github.com/open-mpi/ompi/pull/10976 to see whether it resolves the issue?

**Comment by dalcinl** [comment]
@edgargabriel Thanks for your prompt action. Your branch fixes the issue [[logs]](https://github.com/mpi4py/mpi4py-testing/actions/runs/3336968437/jobs/5522741117#step:17:1).

**Comment by dalcinl** [comment]
@edgargabriel @jsquyres I believe this issue can be closed.
