### ISSUE TITLE
Use of btl ofi in EFA environment results in low bandwidth utilization.

### ISSUE THREAD

**Issue by LeoGoTi** [open-mpi/ompi#11005]
I'm currently working in some AWS c5n.9xlarge instances.
I have tried some call paths to conduct openmpi tasks, and the results bring me into confusion.

- When using `--mca pml cm --mca mtl ofi --mca mtl_ofi_provider_include efa`, the performance is fine (with > 96% bw util).
- With `--mca pml ob1 --mca btl ofi --mca btl_ofi_provider_include efa`, I haven't achieved >50% bw util ever.

I understand that btl is optimized for one-sided communication (hence this call path is not set as default), but I tried to increase `pml_ob1_sedf/recv_pipeline_depth` to lift up the pipeline level, only to get lower latency instead of better bw.

Here is the command line I used for BTL ofi test:
`mpirun --pernode --hostfile hostfile  --mca pml ob1 --mca btl ofi --mca btl_ofi_provider_include efa --mca pml_ob1_send_pipeline_depth 100 --mca pml_ob1_recv_pipeline_depth 101 --mca btl_ofi_mode 1 osu_bw -m 4:16777216`
Other commands differs mainly in binary specification.

Is there any misunderstanding about ob1 protocols and btl implementation?

**Comment by wzamazon** [comment]
Hi, indeed, using btl/ofi for two side operation is not something we test regularly. The default path is to use mtl/ofi.

Is there any reason that you must use btl/ofi for two side operation?

**Comment by bwbarrett** [comment]
To add some more color to what Wei said, the way the EFA provider in Libfabric is designed is really optimized for the MTL use case (where memory management and bounce buffering is largely left to Libfabric).  With the OFI BTL, Open MPI takes responsibility for much of that, but for the send/recv interface, the EFA provider doesn't give that up today.  So you end up in a situation where Libfabric is copying data from a communication buffer into what it thinks is the final buffer, but in reality, that second buffer is a bounce buffer in the OB1 PML, where it gets copied a second time.  These copies are the driving performance limiter in a single-threaded MPI process with EFA, so using the BTL will almost definitionally lower benchmark performance.

**Comment by LeoGoTi** [comment]
@wzamazon @bwbarrett 
Thanks for the replies. 
Actually, there is no need for an end user to stick to the lower-performance call path. The reason lies in that I wondered what caused the deterioration, to eliminate potential misuse.
@bwbarrett I think that completely answered the question. I thought when facing such a result, for NO reason I should stop at my perceptual knowledge that "dedicated implementation is better than general-purpose implementation". 

Thanks again, sincerely.
