### ISSUE TITLE
process binding failure - 5.0.0rc9 and 4.1.4

### ISSUE THREAD

**Issue by thomasgillis** [open-mpi/ompi#11029]
## Background information

I have an issue with process binding but unsure if it's a configuration/user issue or a bug.
I get two nodes from the job scheduler (`cobalt` on `jlse`) and request one process on each of those nodes.
With `mpich` the binding is done using `mpiexec -n 2 -ppn 1` and everything goes through.

When trying to do the same with `ompi` I use `mpiexec -n 2 --npernode 1` and it fails with
```text
--------------------------------------------------------------------------
Your job has requested more processes than the ppr for
this topology can support:

  App: ./c/mpi/pt2pt/osu_bw
  Number of procs:  2
  PPR: 1:node

Please revise the conflict and try again.
--------------------------------------------------------------------------
``` 

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

I have the issue with both version `5.0.0rc9` and `4.1.4`.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

from the tarballs
```
Configure command line: '--prefix=/home/tgillis/lib-OMPI-4.1.4-UCX-1.13.1'
                          '--without-verbs'
                          '--enable-mpirun-prefix-by-default'
                          '--with-cuda=no' '--with-pmix=internal'
                          '--with-hwloc=internal'
                          '--with-ucx=/home/tgillis/lib-OMPI-4.1.4-UCX-1.13.1'
```

### Please describe the system on which you are running

it's `jlse-skylake` at ANL

-----------------------------

## Details of the problem

As mentioned earlier I am not sure if it's a configuration issue or a problem in process binding. As it works out of the box with `mpich` I guess it might be an issue specific to `ompi`.

Also as a side note I would be interested to get the non-deprecated options flags as well, especially on how to combine multiple `--map-by` requirements (like `x` ranks per node, `y` cores per rank).

I have tried `--map-by ppr:x:node --map-by core:PE=y` but it complains on the options

**Comment by rhc54** [comment]
Another possibility is that OMPI isn't understanding your scheduler's allocation description. What scheduler is involved here (PBS, Slurm, ...)? You could also try creating a hostfile with the host names in it and then passing that to OMPI with `mpiexec --hostfile <file> ...`

**Comment by thomasgillis** [comment]
@rhc54 thanks for the quick reply.
Hostfile works but it looks like `ompi` doesn't understand that I have two nodes and not just the one where the allocation starts.
The job scheduler is this weird [`cobalt` project](https://git.cels.anl.gov/aig-public/cobalt).
Is there anything I can do (expect a `hostfile`) to have `mpiexec` get the correct information?

thanks for the command line

**Comment by rhc54** [comment]
Ah, indeed - that's what I kinda expected. @hppritcha Do you have any advice and/or ETA on Cobalt integration?

**Comment by rhc54** [comment]
@thomasgillis Can you check to see if the pbs support has been built? It should build and IIRC cobalt provides a PBS environment. Look in your `config.log` for lines like the following:
```shell
configure:3521: --- MCA component ras:pbs (m4 configuration macro)
configure:56368: checking for MCA component ras:pbs compile mode
configure:56370: result: static
configure:56519: checking if MCA component ras:pbs can compile
configure:56521: result: yes
```
Second, once you have an allocation, can you do a `printenv` on the node where you are trying to execute `mpiexec` and see if there are `PBS_xxx` variables? Can you please report them here?

**Comment by thomasgillis** [comment]
@rhc54 no mca - pbs has been built: 

```
configure:204744: checking for pbs-config
configure:204754: result: not found
```

and regarding the env there is no `PBS` variables in my env.

**Comment by rhc54** [comment]
Hmmm...the `ras:pbs` should not be looking for `pbs-config`. It is supposed to build by default in linux environments, and so it doesn't look for any PBS libraries. Perhaps you missed it? Otherwise, something is definitely wrong with the configure.

Oh wait - are you looking at OMPI v4.1.4?? That definitely won't work - please look at your other OMPI v5 install.

No PBS envars in the env is a killer. Can you post the output of `printenv`?

**Comment by thomasgillis** [comment]
oh sorry let me try the `5.0.0rc9` then.
here is the env:
[env.txt](https://github.com/open-mpi/ompi/files/9939991/env.txt)

**Comment by rhc54** [comment]
Ah, I see what they have done - they renamed everything `PBS_xxx` to `COBALT_xxx`. Can you please post the contents of the `COBALT_NODEFILE`?

**Comment by thomasgillis** [comment]
sure here we go:
```
skylake07
skylake06
```

also no reference of `pbs` or `ras` in the config.log for `5.0.0rc9`.
Thanks for your time :-)

**Comment by rhc54** [comment]
oh yeah - it's in the `3rdparty-prrte` directory - sorry about that. PRRTE is a submodule of the overall code base.

Looks like the nodefile hasn't changed, so it is likely just a minor code change to the PBS components to also look for their COBALT equivalents. I can provide a quick patch for you to try if willing?

**Comment by rhc54** [comment]
Here is the patch - it goes in the 3rdparty-prrte directory
```diff
diff --git a/src/mca/ras/pbs/ras_pbs_component.c b/src/mca/ras/pbs/ras_pbs_component.c
index cac5b01..b40a61a 100644
--- a/src/mca/ras/pbs/ras_pbs_component.c
+++ b/src/mca/ras/pbs/ras_pbs_component.c
@@ -99,8 +99,12 @@ static int prte_mca_ras_pbs_component_query(pmix_mca_base_module_t **module, int
         *priority = param_priority;
         *module = (pmix_mca_base_module_t *) &prte_ras_pbs_module;
         return PRTE_SUCCESS;
+    } else if (NULL != getenv("COBALT_JOBID")) {
+        /* we are running under Argonne's Cobalt variant */
+        *priority = param_priority;
+        *module = (pmix_mca_base_module_t *) &prte_ras_pbs_module;
+        return PRTE_SUCCESS;
     }
-
     /* Sadly, no */
     *module = NULL;
     return PRTE_ERROR;
diff --git a/src/mca/ras/pbs/ras_pbs_module.c b/src/mca/ras/pbs/ras_pbs_module.c
index e124c19..ae8b4a1 100644
--- a/src/mca/ras/pbs/ras_pbs_module.c
+++ b/src/mca/ras/pbs/ras_pbs_module.c
@@ -56,7 +56,10 @@ static char *filename;
 /*
  * Global variable
  */
-prte_ras_base_module_t prte_ras_pbs_module = {NULL, allocate, NULL, finalize};
+prte_ras_base_module_t prte_ras_pbs_module = {
+    .allocate = allocate,
+    .finalize = finalize
+};
 
 /**
  * Discover available (pre-allocated) nodes and report
@@ -71,8 +74,11 @@ static int allocate(prte_job_t *jdata, pmix_list_t *nodes)
 
     /* get our PBS jobid from the environment */
     if (NULL == (pbs_jobid = getenv("PBS_JOBID"))) {
-        PRTE_ERROR_LOG(PRTE_ERR_NOT_FOUND);
-        return PRTE_ERR_NOT_FOUND;
+        /* see if we are in Argonne's Cobalt variant */
+        if (NULL == (pbs_jobid = getenv("COBALT_JOBID"))) {
+            PRTE_ERROR_LOG(PRTE_ERR_NOT_FOUND);
+            return PRTE_ERR_NOT_FOUND;
+        }
     }
 
     /* save that value in the global job ident string for
@@ -156,8 +162,12 @@ static int discover(pmix_list_t *nodelist, char *pbs_jobid)
     /* setup the full path to the PBS file */
     filename = getenv("PBS_NODEFILE");
     if (NULL == filename) {
-        pmix_show_help("help-ras-pbs.txt", "no-nodefile", true);
-        return PRTE_ERR_NOT_FOUND;
+        /* try the Cobalt variant */
+        filename = getenv("COBALT_NODEFILE");
+        if (NULL == filename) {
+            pmix_show_help("help-ras-pbs.txt", "no-nodefile", true);
+            return PRTE_ERR_NOT_FOUND;
+        }
     }
     fp = fopen(filename, "r");
     if (NULL == fp) {
```

**Comment by thomasgillis** [comment]
will do, thx @rhc54 
I might take some time though because I need to hack the installation system (currently based on the `tar`)

**Comment by rhc54** [comment]
You can't just do `patch -p1 <file-containing-patch>` with the file version of the above in the `3rdparty/prrte` directory? You then just do a `make install` and it should be done. The patch should apply fine to the expanded tarball.

**Comment by rhc54** [comment]
Just a poke - any progress on this? If this isn't a good time, I may just leave it out of PRRTE v3.0 and pickup Cobalt at some later point so we can release.

**Comment by thomasgillis** [comment]
sorry it got delayed over the weekend :-) I will try it today.

**Comment by thomasgillis** [comment]
So I have rebuilt the whole `ompi` with the patch (also I have checked it has been applied correctly) and it seems like it works on my end :-)

```
mpiexec -n 2 --npernode 1 --report-bindings true
[skylake08:26012] Rank 0 bound to package[0][core:0]
[skylake06:65672] Rank 1 bound to package[0][core:0]
```

**Comment by rhc54** [comment]
Very cool! I will update PRRTE with the patch. Yes, PRRTE v3.0 is baseline for OMPI v5.0.0.

**Comment by rhc54** [comment]
@jsquyres This can be closed - updates completed
