### ISSUE TITLE
How to set up different allreduce algorithms (may ring or binary tree，etc) 

### ISSUE THREAD

**Issue by Han-Huaqiao** [open-mpi/ompi#11042]
How to set up different allreduce algorithms? Now, I need to ask ompi to run a certain allreduce algorithm bu function MPI_Allreduce (c/c++). In ompi-4.1.4, how to specify these parameters?

**Comment by bosilca** [comment]
I'm sure we answered similar questions many times on our mailing list. The process is going through 2 steps:
1. list all available algorithms for a collective communication. Use `ompi_info --param coll tuned --level 9` to see all available collective communication algorithms. Grep through the output to find the collective of intertest (allreduce in this context), and check the output to see the available algorithms 
```
MCA coll tuned: parameter "coll_tuned_allreduce_algorithm" (current
                          value: "ignore", data source: default, level: 5
                          tuner/detail, type: int)
                          Which allreduce algorithm is used. Can be locked
                          down to any of: 0 ignore, 1 basic linear, 2
                          nonoverlapping (tuned reduce + tuned bcast), 3
                          recursive doubling, 4 ring, 5 segmented ring. Only
                          relevant if coll_tuned_use_dynamic_rules is true.
                          Valid values: 0:"ignore", 1:"basic_linear",
                          2:"nonoverlapping", 3:"recursive_doubling",
                          4:"ring", 5:"segmented_ring", 6:"rabenseifner"
```
2.  Now run mpirun with the following MCA arguments to change the behavior. Here I select the recursive doubling (aka 3) as the default allreduce algorithms, using a tree fanout of 4 and a segment size of 4k.
```
--mca coll_tuned_use_dynamic_rules 1 \
--mca coll_tuned_allreduce_algorithm 3 \
--mca coll_tuned_allreduce_algorithm_segmentsize 4096 \
--mca coll_tuned_allreduce_algorithm_tree_fanout 4
```

**Comment by jsquyres** [comment]
I think @bosilca answered this question, so unless you have followup questions, I'm going to close it.
