### ISSUE TITLE
map by l3cache is not working

### ISSUE THREAD

**Issue by arunedarath** [open-mpi/ompi#11062]
Hi,

a) With openpi 4.1.4 I map by l3cache is working as expected.

$ mpirun -np 2 --display-map --map-by l3cache --bind-to core  whoami
 Data for JOB [16717,1] offset 0 Total slots allocated 32

 ========================   JOB MAP   ========================

 Data for node: lib-ssp-04      Num slots: 32   Max slots: 0    Num procs: 2
        Process OMPI jobid: [16717,1] App: 0 Process rank: 0 Bound: socket 0[core 0[hwt 0]]:[B/././././././././././././././.][./././././././././././././././.]
        Process OMPI jobid: [16717,1] App: 0 Process rank: 1 Bound: socket 0[core 2[hwt 0]]:[././B/././././././././././././.][./././././././././././././././.]

 =============================================================
arun
arun

b) But with v5.0.0rc9 the mapping seems to be broken

mpirun -np 2 --display-map --map-by l3cache --bind-to core  whoami

========================   JOB MAP   ========================
Data for JOB prterun-lib-ssp-04-1006170@1 offset 0 Total slots allocated 32
    Mapping policy: BYL3CACHE:NOOVERSUBSCRIBE  Ranking policy: SLOT Binding policy: CORE
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE

Data for node: lib-ssp-04       Num slots: 32   Max slots: 0    Num procs: 2
        Process jobid: prterun-lib-ssp-04-1006170@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-lib-ssp-04-1006170@1 App: 0 Process rank: 1 Bound: package[0][core:1] ---> binding to core 1

=============================================================
arun
arun

The topology & ompi_info is attached. Is it broken or am I missing something?

--Arun
[ompi_info.txt](https://github.com/open-mpi/ompi/files/9994483/ompi_info.txt)
[topology.txt](https://github.com/open-mpi/ompi/files/9994484/topology.txt)

**Comment by arunedarath** [comment]
same issue with map-by numa & socket also

a) openmpi4.1.4
mpirun -np 2 --display-map --map-by numa --bind-to core  whoami
 Data for JOB [31960,1] offset 0 Total slots allocated 32

 ========================   JOB MAP   ========================

 Data for node: lib-ssp-04      Num slots: 32   Max slots: 0    Num procs: 2
        Process OMPI jobid: [31960,1] App: 0 Process rank: 0 Bound: socket 0[core 0[hwt 0]]:[B/././././././././././././././.][./././././././././././././././.]
        Process OMPI jobid: [31960,1] App: 0 Process rank: 1 Bound: socket 0[core 4[hwt 0]]:[././././B/././././././././././.][./././././././././././././././.]

 =============================================================
arun
arun

mpirun -np 2 --display-map --map-by socket --bind-to core  whoami
 Data for JOB [31778,1] offset 0 Total slots allocated 32

 ========================   JOB MAP   ========================

 Data for node: lib-ssp-04      Num slots: 32   Max slots: 0    Num procs: 2
        Process OMPI jobid: [31778,1] App: 0 Process rank: 0 Bound: socket 0[core 0[hwt 0]]:[B/././././././././././././././.][./././././././././././././././.]
        Process OMPI jobid: [31778,1] App: 0 Process rank: 1 Bound: socket 1[core 16[hwt 0]]:[./././././././././././././././.][B/././././././././././././././.]

 =============================================================
arun
arun


b) openmpi5_rc9
mpirun -np 2 --display-map --map-by numa --bind-to core  whoami                                                                                                                                                                   

========================   JOB MAP   ========================
Data for JOB prterun-lib-ssp-04-1008987@1 offset 0 Total slots allocated 32
    Mapping policy: BYNUMA:NOOVERSUBSCRIBE  Ranking policy: SLOT Binding policy: CORE
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE


Data for node: lib-ssp-04       Num slots: 32   Max slots: 0    Num procs: 2
        Process jobid: prterun-lib-ssp-04-1008987@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-lib-ssp-04-1008987@1 App: 0 Process rank: 1 Bound: package[0][core:1]

=============================================================

arun
arun

$ mpirun -np 2 --display-map --map-by socket --bind-to core  whoami                                                                                                                                                                 

========================   JOB MAP   ========================
Data for JOB prterun-lib-ssp-04-1009022@1 offset 0 Total slots allocated 32
    Mapping policy: BYPACKAGE:NOOVERSUBSCRIBE  Ranking policy: SLOT Binding policy: CORE
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE


Data for node: lib-ssp-04       Num slots: 32   Max slots: 0    Num procs: 2
        Process jobid: prterun-lib-ssp-04-1009022@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-lib-ssp-04-1009022@1 App: 0 Process rank: 1 Bound: package[0][core:1]

=============================================================
arun
arun


--Arun

**Comment by rhc54** [comment]
Hmmm...well, it seems to be working fine for me, albeit I don't have your topology:
```shell
$ mpirun --prtemca hwloc_use_topo_file summit.xml --map-by package:core --bind-to core -n 2 --display map
========================   JOB MAP   ========================
Data for JOB prterun-Ralphs-iMac-2-68644@1 offset 0 Total slots allocated 42
    Mapping policy: BYPACKAGE:NOOVERSUBSCRIBE  Ranking policy: FILL Binding policy: CORE
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE


Data for node: Ralphs-iMac-2	Num slots: 42	Max slots: 0	Num procs: 2
        Process jobid: prterun-Ralphs-iMac-2-68644@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-Ralphs-iMac-2-68644@1 App: 0 Process rank: 1 Bound: package[1][core:21]

=============================================================

$ mpirun --prtemca hwloc_use_topo_file summit.xml --map-by l3:core --bind-to core -n 2 --display map
========================   JOB MAP   ========================
Data for JOB prterun-Ralphs-iMac-2-69105@1 offset 0 Total slots allocated 42
    Mapping policy: BYL3CACHE:NOOVERSUBSCRIBE  Ranking policy: FILL Binding policy: CORE
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE


Data for node: Ralphs-iMac-2	Num slots: 42	Max slots: 0	Num procs: 2
        Process jobid: prterun-Ralphs-iMac-2-69105@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-Ralphs-iMac-2-69105@1 App: 0 Process rank: 1 Bound: package[0][core:2]

```
One thing I notice is that you are defaulting to a different ranking policy - not sure why, but I suspect you may be using an older hash on the OMPI v5 branch (I'm using the head of the PRRTE v3.0 branch - the OMPI v5 branch should be _close_ to the same level, but perhaps not fully updated yet).

Could you post the xml output from lstopo so I can ensure this isn't a topology issue?

**Comment by arunedarath** [comment]
[topology_xml.txt](https://github.com/open-mpi/ompi/files/9995449/topology_xml.txt)

Please see the topology attached.

I tried different ranking policies but the result is the same. How the default ranking policy is chosen? Is it a build-time option?

`arun@lib-ssp-04 ~ $ mpirun  --map-by package:core --bind-to core --rank-by slot -n 2 --display map whoami
                                                             
========================   JOB MAP   ========================
Data for JOB prterun-lib-ssp-04-1034635@1 offset 0 Total slots allocated 32
    Mapping policy: BYPACKAGE:NOOVERSUBSCRIBE  Ranking policy: SLOT Binding policy: CORE                 
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE
                                                             
                                                                           
Data for node: lib-ssp-04       Num slots: 32   Max slots: 0    Num procs: 2            
        Process jobid: prterun-lib-ssp-04-1034635@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-lib-ssp-04-1034635@1 App: 0 Process rank: 1 Bound: package[0][core:1]

=============================================================               
arun                                                                                                
arun                                                                                                
arun@lib-ssp-04 ~ $ mpirun  --map-by package:core --bind-to core --rank-by fill -n 2 --display map whoami
                                                             
========================   JOB MAP   ========================
Data for JOB prterun-lib-ssp-04-1034641@1 offset 0 Total slots allocated 32
    Mapping policy: BYPACKAGE:NOOVERSUBSCRIBE  Ranking policy: FILL Binding policy: CORE                 
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE
                                                             
                                                                           
Data for node: lib-ssp-04       Num slots: 32   Max slots: 0    Num procs: 2            
        Process jobid: prterun-lib-ssp-04-1034641@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-lib-ssp-04-1034641@1 App: 0 Process rank: 1 Bound: package[0][core:1]

=============================================================               
arun                                                                                                
arun
arun@lib-ssp-04 ~ $ mpirun  --map-by package:core --bind-to core --rank-by span -n 2 --display map whoami
                                                             
========================   JOB MAP   ========================
Data for JOB prterun-lib-ssp-04-1034647@1 offset 0 Total slots allocated 32
    Mapping policy: BYPACKAGE:NOOVERSUBSCRIBE  Ranking policy: SPAN Binding policy: CORE
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE


Data for node: lib-ssp-04       Num slots: 32   Max slots: 0    Num procs: 2
        Process jobid: prterun-lib-ssp-04-1034647@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-lib-ssp-04-1034647@1 App: 0 Process rank: 1 Bound: package[0][core:1]

=============================================================
arun
arun
arun@lib-ssp-04 ~ $ mpirun  --map-by package:core --bind-to core --rank-by node -n 2 --display map whoami

========================   JOB MAP   ========================
Data for JOB prterun-lib-ssp-04-1034653@1 offset 0 Total slots allocated 32
    Mapping policy: BYPACKAGE:NOOVERSUBSCRIBE  Ranking policy: NODE Binding policy: CORE
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE


Data for node: lib-ssp-04       Num slots: 32   Max slots: 0    Num procs: 2
        Process jobid: prterun-lib-ssp-04-1034653@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-lib-ssp-04-1034653@1 App: 0 Process rank: 1 Bound: package[0][core:1]

=============================================================
arun
arun
                                                                                            
`

For the main directory, HEAD is at

arun@lib-ssp-04 ompi $ git show
commit faca8318eeed9a0af128eaf07eac9d0076ff1655 (HEAD -> my_v5.0.0rc9, tag: v5.0.0rc9)
Merge: d4efccd7d3 3b748fdf42
Author: Austen Lauria <awlauria@us.ibm.com>
Date:   Fri Oct 21 16:07:10 2022 -0400

    Merge pull request #10968 from awlauria/news_v5.0.x_rc9_
    
    v5.0.xrc9 prep work

PRRTE is at (Does not seems to be too old to me)
arun@lib-ssp-04 prrte $ cd -
/home/arun/ompi
arun@lib-ssp-04 ompi $ cd 3rd-party/prrte/; git log -1
commit 7a17d22d5c94dde6e59e008443ed8ffc17af9396 (HEAD)
Author: Josh Hursey <jhursey@us.ibm.com>
Date:   Wed Oct 26 17:08:03 2022 -0400

    Rankfile slots fix and LSF support fix for LSB_AFFINITY_HOSTFILE
    
--Arun

**Comment by rhc54** [comment]
Certainly seems like it should be current enough - yet it works fine for me, even with your topology:
```shell
$ mpirun --prtemca hwloc_use_topo_file /Users/rhc/pmix/topologies/issue11062.xml --map-by package:core --bind-to core -n 2 --display map hostname

========================   JOB MAP   ========================
Data for JOB prterun-Ralphs-iMac-2-81971@1 offset 0 Total slots allocated 32
    Mapping policy: BYPACKAGE:NOOVERSUBSCRIBE  Ranking policy: FILL Binding policy: CORE
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE


Data for node: Ralphs-iMac-2	Num slots: 32	Max slots: 0	Num procs: 2
        Process jobid: prterun-Ralphs-iMac-2-81971@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-Ralphs-iMac-2-81971@1 App: 0 Process rank: 1 Bound: package[1][core:16]
```
That commit you cite actually is quite old and pre-dates fixes to things like the default ranking policy setting. I suspect that is the problem you are seeing - the branch just needs an update.

**Comment by arunedarath** [comment]
With the latest PRRTE and openpmix it is working as expected. Thank you.


arun@lib-ssp-04 ~ $ mpirun  --map-by core --bind-to core  -n 2 --display map whoami                                                                                                                                                                   

========================   JOB MAP   ========================
Data for JOB prterun-lib-ssp-04-1323373@1 offset 0 Total slots allocated 32
    Mapping policy: BYCORE:NOOVERSUBSCRIBE  Ranking policy: FILL Binding policy: CORE
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE


Data for node: lib-ssp-04       Num slots: 32   Max slots: 0    Num procs: 2
        Process jobid: prterun-lib-ssp-04-1323373@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-lib-ssp-04-1323373@1 App: 0 Process rank: 1 Bound: package[0][core:1]

=============================================================
arun
arun
arun@lib-ssp-04 ~ $ mpirun  --map-by l3cache --bind-to core  -n 2 --display map whoami                                                                                                                                                                

========================   JOB MAP   ========================
Data for JOB prterun-lib-ssp-04-1323387@1 offset 0 Total slots allocated 32
    Mapping policy: BYL3CACHE:NOOVERSUBSCRIBE  Ranking policy: FILL Binding policy: CORE
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE


Data for node: lib-ssp-04       Num slots: 32   Max slots: 0    Num procs: 2
        Process jobid: prterun-lib-ssp-04-1323387@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-lib-ssp-04-1323387@1 App: 0 Process rank: 1 Bound: package[0][core:2]

=============================================================
arun
arun
arun@lib-ssp-04 ~ $ mpirun  --map-by numa --bind-to core  -n 2 --display map whoami                                                                                                                                                                   

========================   JOB MAP   ========================
Data for JOB prterun-lib-ssp-04-1323393@1 offset 0 Total slots allocated 32
    Mapping policy: BYNUMA:NOOVERSUBSCRIBE  Ranking policy: FILL Binding policy: CORE
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE


Data for node: lib-ssp-04       Num slots: 32   Max slots: 0    Num procs: 2
        Process jobid: prterun-lib-ssp-04-1323393@1 App: 0 Process rank: 0 Bound: package[0][core:0]
        Process jobid: prterun-lib-ssp-04-1323393@1 App: 0 Process rank: 1 Bound: package[0][core:4]

=============================================================
arun
arun

--Arun

**Comment by jsquyres** [comment]
> With the latest PRRTE and openpmix it is working as expected. Thank you.

Is your issue resolved / should we close this issue?

**Comment by arunedarath** [comment]
sure. Please close.
