### ISSUE TITLE
Cuda rcache behavior conflicts with libfabric's mr cache

### ISSUE THREAD

**Issue by wckzhang** [open-mpi/ompi#11125]
Summary of the issue:

The way Open MPI (and libfabric) invalidate registrations for cuda memory is without a hook mechanism. Instead, on a subsequent registration, if the memory address is the same but the cuda buffer id is different, the region is invalidated and kicked out of the cache.

This works except when layered on top of another cache as with libfabric's mr cache. When libfabric invalidates a cuda entry in the cache, Open MPI is still holding onto the registration which results in a reference count greater than 0 which prevents the entry from being removed from libfabric's cache.

Other than adding hooking invalidation behavior, I think it is more appropriate to only have one cache layer at a time.

This currently only applies to the OFI BTL and only for one sided operations. I'm not sure whether we would want to pass a flag to disable libfabric's cache or simply not use the rcache in the OFI BTL. Please provide some thoughts in this issue if you have interest in the OFI BTL.

**Comment by wckzhang** [comment]
@bwbarrett @hppritcha @wzamazon

**Comment by wzamazon** [comment]
>This works except when layered on top of another cache as with libfabric's mr cache. When libfabric invalidates a cuda entry in the cache, Open MPI is still holding onto the registration which results in a reference count greater than 0 which prevents the entry from being removed from libfabric's cache.

I am not sure I understand the sequence of event here. Can you elaborate?

On the other hand, because btl/ofi has its own registration cache, it should specify FI_MR_LOCAL mr mode, which means btl/ofi will manage its own registration and always pass a descriptor (which I believe btl/ofi does).

When FI_MR_LOCAL is specified, libfabric should turn off its cache.

**Comment by wckzhang** [comment]
Sequence with cuda buffer:

1. OMPI calls Rcache register on cuda buffer
2. Rcache detects no existing registration, calls fi_mr_regattr on cuda buffer
3. fi_mr_regattr calls mr cache register on cuda buffer
4. mr cache detects no existing registration, calls add region (true registration) on cuda buffer
5. Key doesn't exist so it is added to mr map
6. Application frees cuda buffer
7. Ompi calls rcache register on host buffer
8. Rcache register detects no existing registration, calls fi_mr_regattr on host buffer
9. fi_mr_regattr calls mr cache register on host buffer
10. mr cache detects no existing registration, calls add region (true registration) on host buffer
11. mr map detects key reuse from prior cuda buffer registration and attempts to invalidate it by notifying mr cache
12. mr cache notify detects use count is 1 (ompi has not called fi_close on the registration yet) and cannot kick it out of the cache
13. mr map fails to remove from map as entry is still in the mr cache

This is one possible sequence of events. There are other sequences that can happen.

**Comment by wzamazon** [comment]
I think at step 8:
```
8. Rcache register detects no existing registration, calls fi_mr_regattr on host buffer
```
 
Rcache should have called `fi_close` when it found buffer ID mismatch.

**Comment by wckzhang** [comment]
@wzamazon No there is no buffer id mismatch, this is a host buffer.

**Comment by hppritcha** [comment]
Could we use the rcache MCA_RCACHE_FLAGS_CACHE_BYPASS flag bit to bypass the OMPI cache for providers that we know are doing their own MR cache management?  I'm thinking of ways to minimize changes to the existing ofi/btl code.
I am thinking just bypassing OMPI cache for such providers would be the simplest solution.

**Comment by wckzhang** [comment]
I took a brief glimpse and I think that BYPASS flag would stop the ompi cache from applying. That sounds like a feasible solution. I don't know if the bypass cache has been tested with cuda buffers though, it seems like there are some code blocks being executed without checking for bypass cache:

such as
```

    if (flags & MCA_RCACHE_FLAGS_ACCELERATOR_MEM) {
        size_t psize;
        int res = opal_accelerator.get_address_range(MCA_ACCELERATOR_NO_DEVICE_ID, addr, (void **)&base, &psize);
        if (OPAL_SUCCESS != res) {
            abort();
        }
        bound = base + psize - 1;
        /* Check to see if this memory is in the cache and if it has been freed. If so,
         * this call will boot it out of the cache. */
        check_for_accelerator_freed_memory(rcache, base, psize);
    }

    do_unregistration_gc(rcache);
```

I don't know if we can completely bypass the rcache as ```OB1 uses an rcache lookup to determine whether or not the buffer is pinned, meaning whether or not it should use the pipeline protocol vs. the read/write protocols.``` - for someone using the ofi btl + ob1 for pt2pt, I think you'll want the rcache.

**Comment by wckzhang** [comment]
Actually surprisingly enough, adding the bypass flag seems to work fine without any changes to cuda. I'm guessing it's because while the cuda section does unnecessary stuff, check for accelerator freed memory is not really harmful

**Comment by wckzhang** [comment]
This is merged, resolving
