### ISSUE TITLE
cannot find cuda library in openmpi-5.0.0rc9

### ISSUE THREAD

**Issue by kc9qey** [open-mpi/ompi#11138]
configure:86569: checking for cuda header at /sw/external/nvhpc/22.11/Linux_x86_64/22.11/cuda/11.0/targets/x86_64-linux/include
configure:86574: result: found
configure:86609: checking for cuda library (cuda) in /sw/external/nvhpc/22.11/Linux_x86_64/22.11/cuda/11.0/targets/x86_64-linux
configure:86626: result: not found

Configure line:
./configure --prefix=/sw/external/openmpi-5.0_beta/ompi_for_nvhpc22.11  --with-ucx=`pwd`/ucx_deploy  --with-knem=/opt/knem-1.1.4.90mlnx1 --with-pmix=internal CC=pgcc CXX=pgc++ FC=pgfortran --enable-mpi-ext=cuda  --with-cuda=/sw/external/nvhpc/22.11/Linux_x86_64/22.11/cuda/11.0/targets/x86_64-linux

compiler: nvhpc 22.11

**Comment by kc9qey** [comment]
[svcdeltaswmgt@dt-login03 openmpi-5.0.0rc9]$ ls /sw/external/nvhpc/22.11/Linux_x86_64/22.11/cuda/11.0/targets/x86_64-linux
include  lib
[svcdeltaswmgt@dt-login03 openmpi-5.0.0rc9]$ ls /sw/external/nvhpc/22.11/Linux_x86_64/22.11/cuda/11.0/targets/x86_64-linux/lib
libaccinj64.so           libcudart_static.a      libcurand.so.10.2.1.245  libnppial.so.11          libnppidei.so             libnppif_static.a       libnppim.so.11.1.0.245   libnppisu.so.11          libnpps.so               libnvjpeg_static.a             libnvToolsExt.so        stubs
libaccinj64.so.11.0      libcuinj64.so           libcurand_static.a       libnppial.so.11.1.0.245  libnppidei.so.11          libnppig.so             libnppim_static.a        libnppisu.so.11.1.0.245  libnpps.so.11            libnvrtc-builtins.so           libnvToolsExt.so.1
libaccinj64.so.11.0.221  libcuinj64.so.11.0      libnppc.so               libnppial_static.a       libnppidei.so.11.1.0.245  libnppig.so.11          libnppist.so             libnppisu_static.a       libnpps.so.11.1.0.245    libnvrtc-builtins.so.11.0      libnvToolsExt.so.1.0.0
libcudadevrt.a           libcuinj64.so.11.0.221  libnppc.so.11            libnppicc.so             libnppidei_static.a       libnppig.so.11.1.0.245  libnppist.so.11          libnppitc.so             libnpps_static.a         libnvrtc-builtins.so.11.0.221  libOpenCL.so
libcudart.so             libculibos.a            libnppc.so.11.1.0.245    libnppicc.so.11          libnppif.so               libnppig_static.a       libnppist.so.11.1.0.245  libnppitc.so.11          libnvjpeg.so             libnvrtc.so                    libOpenCL.so.1
libcudart.so.11.0        libcurand.so            libnppc_static.a         libnppicc.so.11.1.0.245  libnppif.so.11            libnppim.so             libnppist_static.a       libnppitc.so.11.1.0.245  libnvjpeg.so.11          libnvrtc.so.11.0               libOpenCL.so.1.0
libcudart.so.11.0.221    libcurand.so.10         libnppial.so             libnppicc_static.a       libnppif.so.11.1.0.245    libnppim.so.11          libnppisu.so             libnppitc_static.a       libnvjpeg.so.11.1.1.245  libnvrtc.so.11.0.221           libOpenCL.so.1.0.0
[svcdeltaswmgt@dt-login03 openmpi-5.0.0rc9]$ ls /sw/external/nvhpc/22.11/Linux_x86_64/22.11/cuda/11.0/targets/x86_64-linux/include/cuda.h
/sw/external/nvhpc/22.11/Linux_x86_64/22.11/cuda/11.0/targets/x86_64-linux/include/cuda.h
[svcdeltaswmgt@dt-login03 openmpi-5.0.0rc9]$

**Comment by kc9qey** [comment]
...am on a login node of the cluster with no gpu or cuda driver.  Do I need to borrow the libcuda.so from /usr/lib64/ on a gpu node to finish this configure ?

**Comment by jsquyres** [comment]
I was just noticing that there is no `libcuda.*` in your directory list, and that's why it looks like configure said that the library could not be found.

@wckzhang You touched this section of `config/opal_check_cuda.m4` last 😄 -- can you comment here?  Feel free to pull in relevant NVIDIA people, if needed, to discuss the resulting desired behavior.

**Comment by kc9qey** [comment]
Accelerators
-----------------------
CUDA support: yes
ROCm support: no
 
OMPIO File Systems
-----------------------
DDN Infinite Memory Engine: no
Generic Unix FS: yes
IBM Spectrum Scale/GPFS: no (not found)
Lustre: yes (pkg-config: default search paths)
PVFS2/OrangeFS: no

# worked around it by cp  /usr/lib/lib64/libcuda.*   into  CUDA_HOME/lib   , spack installs don't run into this and will build openmpi on a login node without a cuda driver, what's spack doing there that i cannot from the manual configure ?  Anyway, i have a workaround for this.

**Comment by wckzhang** [comment]
So if your libcuda.so is not in a standard path you have to provide ```--with-cuda-libdir=<path-to-libcuda.so>``` as well. This is standard practice for Open MPI but is new behavior for cuda since previously we did dynamic library detection during runtime and now we do not. This is all detailed in the OMPI cuda docs - https://docs.open-mpi.org/en/v5.0.x/networking/cuda.html

**Comment by edbennett** [comment]
Can the FAQ at https://www.open-mpi.org/faq/?category=buildcuda please be adjusted to reflect this?

Since that already says to use `--with-cuda=${PATH_TO_CUDA_INSTALLATION}`, I naturally assumed that it would look in `${PATH_TO_CUDA_INSTALLATION}/lib` for the libraries, as it did with the `/include` subdirectory for headers.
