### ISSUE TITLE
OpenMPI Does not configure with Intel ICX Compilers, ICC planned obselete 2023Q3

### ISSUE THREAD

**Issue by lrbison** [open-mpi/ompi#11142]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

mainline Dec 1st, 4dae1421f1c19fed941eca42cac8756debca3b7b

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
```
[ec2-user@ip-10-0-0-52 ompi]$ git submodule status
+29bacec619f2ed0f7ce0db067bea520dc4f45859 3rd-party/openpmix (v4.2.2)
+884527149d1cb28266e72f441a3ad80ac090237c 3rd-party/prrte (v3.0.0rc3-9-g884527149d)
 5c8de3d97b763bf8981fb49cbedd36e201b8fc0a config/oac (5c8de3d)
```

### Please describe the system on which you are running

* Operating system/version: Amazon Linux 2
* Computer hardware: N/A
* Network type: N/A

-----------------------------

## Details of the problem

Intel is moving to icx and icpx as their new compiler (https://www.intel.com/content/www/us/en/developer/articles/guide/porting-guide-for-icc-users-to-dpcpp-or-icx.html)

Buf if we build from source with the new ICX compilers:
```
./configure CC=icx CXX=icpx F77=ifort FC=ifort
```

The configure step fails.  Output is
```
checking if C and C++ are link compatible... no
**********************************************************************
* It appears that your C++ compiler is unable to link against object
* files created by your C compiler.  This generally indicates either
* a conflict between the options specified in CFLAGS and CXXFLAGS
* or a problem with the local compiler installation.  More
* information (including exactly what command was given to the
* compilers and what error resulted when the commands were executed) is
* available in the config.log file in this directory.
**********************************************************************
```

offending test from config.log is:
```
configure:19321: checking if C and C++ are link compatible
configure:19343: icx -c -O3 -DNDEBUG  -Wundef -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -Wshadow -Werror-implicit-function-declaration -pedantic -Wall -finline-functions  conftest_c.c
configure:19346: $? = 0
configure:19373: icpx -o conftest -DNDEBUG    conftest.cpp conftest_c.o  >&5
/usr/bin/ld: cannot find -lstdc++
icpx: error: linker command failed with exit code 1 (use -v to see invocation)
```

Try again, build from source with the classic compilers:
```
./configure CC=icc CXX=icpc F77=ifort FC=ifort
```
Configure and build pass, but build is strewn with warnings:
```
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
```
so we may want to recommend that diag-disable in CFLAGS, and we need ICX-compatible build in under 12 months.

**Comment by lrbison** [comment]
Both icx and icpx report version 2022.2.1.20221020
Both icc and icpc report 2021.7.1.20221019, but were packaged with the 2022.2.1 compiler download.

**Comment by jsquyres** [comment]
Is there something wrong with that configure test?  It's been pretty reliable for 15+ years.  It is doing exactly what it says it is doing: it makes a C `.o` file and then tries to link it with a C++ `.cpp` file.  If that doesn't work, something's wrong.

**Comment by lrbison** [comment]
I've not used the intel C compilers much, and I didn't know ICX even existed before this morning, so I'm the wrong person to ask!

I did reproduce it:

```
[ec2-user@ip-10-0-0-52 tmp]$ make
icx -c conftest_c.c -o conftest_c.o
icpx -o conftest conftest.cpp conftest_c.o
/usr/bin/ld: cannot find -lstdc++
icpx: error: linker command failed with exit code 1 (use -v to see invocation)
```

but gcc/g++ work just fine.  Running icpx with -v provides the link line:

> ```"/usr/bin/ld" --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o conftest /usr/lib/gcc/x86_64-redhat-linux/10/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/10/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/10/crtbegin.o -L/home/ec2-user/intel/oneapi/compiler/2022.2.1/linux/bin-llvm/../compiler/lib/intel64_lin -L/home/ec2-user/intel/oneapi/compiler/2022.2.1/linux/bin-llvm/../lib -L/home/ec2-user/intel/oneapi/compiler/2022.2.1/linux/bin-llvm/../compiler/lib/intel64_lin -L/usr/lib/gcc/x86_64-redhat-linux/10 -L/usr/lib/gcc/x86_64-redhat-linux/10/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/10/../../.. -L/lib -L/usr/lib -L/home/ec2-user/intel/oneapi/compiler/2022.2.1/linux/compiler/lib/intel64_lin -L/home/ec2-user/intel/oneapi/compiler/2022.2.1/linux/lib /tmp/conftest-e8390b.o conftest_c.o -Bstatic -lsvml -Bdynamic -Bstatic -lirng -Bdynamic -lstdc++ -Bstatic -limf -Bdynamic -lm -lgcc_s -lgcc -Bstatic -lirc -Bdynamic -ldl -lgcc_s -lgcc -lc -lgcc_s -lgcc -Bstatic -lirc_s -Bdynamic /usr/lib/gcc/x86_64-redhat-linux/10/crtend.o /usr/lib/gcc/x86_64-redhat-linux/10/../../../../lib64/crtn.o```

I did manage to get icpx to compile a working executable as long as it doesn't have to link against any other .o file, but once a .o file appears, it fails with the same error.  The compiler (or my environment) very much seems broken to me.  My environment was a fresh shell just sourced the intel compiler vars.sh.

It would be good if someone with more intel compiler knowledge could take a look.

**Comment by hppritcha** [comment]
Hmm I think something is wrong with your compiler installation.  I do a nightly check of building open mpi main and 5.0.x via spack using latest Intel engineering releases and haven’t gotten this error.  The compiler (or more likely clang llvm) have gotten really picky and sometimes can’t build prrte or pmix submodules but I’ve not seen a config error like you are seeing.  I am relying on system admins to do correct install of the compiler toolchain and experience Leads me to believe they are experts in that area.

**Comment by lrbison** [comment]
Do you know if the build is happening using icc or icx?

I'm happy to close as ID-10T error if someone with a working icx has better luck than me.

**Comment by jsquyres** [comment]
@MamziB just cited in https://github.com/open-mpi/ompi/issues/11133#issuecomment-1335827850 that he used `icx` and `icpx` and his build worked (totally different scenario / different issue).

You might want to check with your sys admin to see if your env has some kind of problem...?

**Comment by MamziB** [comment]
@lrbison FYI here are my configs:

````
/global/scratch/users/mbayatpour/workspace4/ompi-git-repo/ompi/configure -C --prefix=/global/scratch/users/mbayatpour/build-x86/ompi-fork-no-debug-intel-experimental --with-ucx=/global/scratch/users/mbayatpour/build-x86/ucx-no-debug-intel --with-verbs --enable-mpi1-compatibility --without-xpmem --with-libevent=/usr --with-slurm --with-pmix=internal --with-hwloc=internal CC=icx CXX=icpx F77=ifx FC=ifx


Currently Loaded Modulefiles:
 1) intel/2022.1.2   2) tbb/2021.6.0   3) compiler-rt/2022.1.0   4) compiler/2022.1.0   5) mkl/2022.0.2
 
  icx --version
Intel(R) oneAPI DPC++/C++ Compiler 2022.1.0 (2022.1.0.20220316)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /global/software/centos-8.x86_64/modules/langs/intel/2022.1.2/compiler/2022.1.0/linux/bin-llvm

**Comment by lrbison** [comment]
Thanks, I'll try these.  Looks like this is a false alarm.
