### ISSUE TITLE
Fault Tolerance (ULFM) not working since 5.0.0rc8

### ISSUE THREAD

**Issue by rcoacci** [open-mpi/ompi#11169]
## Background information

I'm currently investigating fault tolerance for my Master's degree, and while trying some examples from https://github.com/ICLDisco/ulfm-testing/ couldn't make UFLM work with most current versions.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
v5.0.0rc8
v5.0.0rc9
main branch (#4424938)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Installed using tarballs for the rc releases and git for main. 
I've attached dockerfiles describing exactly how it's being build.

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
For main:
 250004266bc046c6303c8531ababdff4e1237525 3rd-party/openpmix (2500042)
 ca2bf3aeab38261ae7c88cea64bc782c949bd76e 3rd-party/prrte (ca2bf3a)
 5c8de3d97b763bf8981fb49cbedd36e201b8fc0a config/oac (5c8de3d)

Also see the attached dockerfiles.

### Please describe the system on which you are running

* Operating system/version: Ubuntu 20.04 (docker) / Ubuntu 22.10 (host)
* Computer hardware: docker on personal desktop (single machine)
* Network type: TCP 

-----------------------------

## Details of the problem

When running 02.err_handler.c from (https://github.com/ICLDisco/ulfm-testing), I either get an PMIx Error when running from git main branch:

```shell
Rank 2 / 5: bye bye!
Rank 4 / 5: bye bye!
[5633ad98da90:00000] *** An error occurred in PMIx Event Notification
[5633ad98da90:00000] *** reported by process [3956277249,3]
[5633ad98da90:00000] *** on a NULL communicator
[5633ad98da90:00000] *** Unknown error (this should not happen!)
[5633ad98da90:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[5633ad98da90:00000] ***    and MPI will try to terminate your MPI job as well)
```

Or the application blocks indefinetely (probably stuck on MPI_Barrier) with high processor usage (over 90%), when running with rc8-rc9:
```shell
Rank 2 / 5: bye bye!
Rank 4 / 5: bye bye!
[eee248ca9223:00001] [prterun-eee248ca9223-1@0,0] errmgr:dvm:sending notification PROC-ABORTED-BY-SIG affected proc [prterun-eee248ca9223-1@1,2]
[eee248ca9223:00001] [prterun-eee248ca9223-1@0,0] errmgr:dvm:sending notification PROC-ABORTED-BY-SIG affected proc [prterun-eee248ca9223-1@1,4]
```
And I have to forcebly terminate it (CTRL-C or kill).

When running with rc7 and earlier it works as expected:

```shell
Rank 2 / 5: bye bye!
Rank 4 / 5: bye bye!
Rank 3 / 5: Notified of error MPI_ERR_PROC_FAILED: Process Failure. 2 found dead: { 2 4 }
Rank 0 / 5: Notified of error MPI_ERR_PROC_FAILED: Process Failure. 2 found dead: { 2 4 }
Rank 1 / 5: Notified of error MPI_ERR_PROC_FAILED: Process Failure. 2 found dead: { 2 4 }
Rank 3 / 5: Notified of error MPI_ERR_PROC_FAILED: Process Failure. 2 found dead: { 2 4 }
Rank 0 / 5: Notified of error MPI_ERR_PROC_FAILED: Process Failure. 2 found dead: { 2 4 }
Rank 1 / 5: Notified of error MPI_ERR_PROC_FAILED: Process Failure. 2 found dead: { 2 4 }
```

All tests were done with the following script:
```shell
VERSION="$1"
docker run -v $PWD:/sandbox ompi5:$VERSION make clean err_handler
docker run -v $PWD:/sandbox ompi5:$VERSION mpirun --with-ft ulfm -n 5 err_handler
```
The actual compilation is:

```shell
mpicc -Wall -Wextra -std=c11 -O2 -D_POSIX_C_SOURCE -c err_handler.c -o err_handler.c.o
mpicc -Wall -Wextra -std=c11 -O2 -D_POSIX_C_SOURCE  err_handler.c.o  -o err_handler
```

Docker file for rc versions: [ompi5rc_docker.txt](https://github.com/open-mpi/ompi/files/10177027/ompi5rc_docker.txt)
Docker file for git versions: [ompi5_docker.txt](https://github.com/open-mpi/ompi/files/10177028/ompi5_docker.txt)

**Comment by rhc54** [comment]
From what I can tell, the problem is that OMPI is only looking for the "proc_failed" event, but PRRTE is providing finer grained events to indicate the cause of the failure. All that needs to be done is for OMPI to expand the events they register to receive.

That said, it appears from a quick grep of the code base that OMPI is no longer registering to recv _any_ failure events. I suspect that is the root of the problem.

**Comment by abouteiller** [comment]
Same issue as https://github.com/open-mpi/ompi/issues/11153

**Comment by rcoacci** [comment]
I can confirm that #11173  fixes the issue for me.
On a side note, the pull request branch doesn't merge cleanly to v5.0.x branch, only to main branch (I might be doing something wrong here).
