### ISSUE TITLE
/mpi/openmpi/4.1.4-gnu-10.2/lib64/libopen-pal.so: undefined reference to fi_open@FABRIC_1.5'`

### ISSUE THREAD

**Issue by Joseph-0123** [open-mpi/ompi#11167]
Dear developers and users,

I am using the [MOOSE framework](https://mooseframework.inl.gov/index.html) on our [uni cluster](https://www.scc.kit.edu/dienste/bwUniCluster_2.0.php) for numerical simulations. Initially, the MOOSE Framework ran well using mpi/openmpi/4.0. After the current maintenance of UniCluster, my MOOSE framework cannot be used due to the [MPI compiler problem](https://github.com/idaholab/moose/discussions/22720). So I use the mpi/openmpi/4.1 to replace the mpi/openmpi/4.0 and update and rebuild MOOSE following their [guidance](https://mooseframework.inl.gov/getting_started/installation/hpc_install_moose.html) and tips on [mpich buliding](https://mooseframework.inl.gov/getting_started/installation/manual_installation_llvm.html).

I have the following errors when I run ./scripts/update_and_rebuild_libmesh.sh at the ending step of the rebuilding MOOSE.

**/opt/bwhpc/common/mpi/openmpi/4.1.4-gnu-10.2/lib64/libopen-pal.so: undefined reference to fi_open@FABRIC_1.5'`**

Could you please help me? Thanks a lot. 

Best regards,

Joseph

**Comment by ggouaillardet** [comment]
It seems your sysadmin upgraded `libfabric` (or moved it to an other location) and Open MPI is not happy about it.

Your best bet is to ask your sysadmin to rebuild and reinstall Open MPI with the updated `libfabric`.
Meanwhile, you can rebuild Open MPI into your home directory.

**Comment by jsquyres** [comment]
It's hard to be sure from just that one errors message, but you may also have the "wrong" Libfabric in your `LD_LIBRARY_PATH`.

E.g., Open MPI was built with Libfabric version X, but you have Libfabric version Y in your environment -- either manually put in your `LD_LIBRARY_PATH`, or via some automated mechanism such as environment modules.

**Comment by Joseph-0123** [comment]
> It seems your sysadmin upgraded `libfabric` (or moved it to an other location) and Open MPI is not happy about it.
> 
> Your best bet is to ask your sysadmin to rebuild and reinstall Open MPI with the updated `libfabric`. Meanwhile, you can rebuild Open MPI into your home directory.

Thanks for your suggestions. I will try it.

**Comment by Joseph-0123** [comment]
> It's hard to be sure from just that one error message, but you may also have the "wrong" Libfabric in your `LD_LIBRARY_PATH`.
> 
> E.g., Open MPI was built with Libfabric version X, but you have Libfabric version Y in your environment -- either manually put in your `LD_LIBRARY_PATH`, or via some automated mechanism such as environment modules.

Yes. I will contact our sysadmin to check this. Thanks.

**Comment by ztf5566** [comment]
Hi Joseph-0123,

I am also the MOOSE user using the same bwUniCluster_2.0. I have exactly the same issue as you after the maintenance of UniCluster. Did you solve this issue?  Many thanks if you could share the experience that how to fix it.

Thanks  and best,
ztf5566

**Comment by Joseph-0123** [comment]
> Hi Joseph-0123,
> 
> I am also the MOOSE user using the same bwUniCluster_2.0. I have exactly the same issue as you after the maintenance of UniCluster. Did you solve this issue? Many thanks if you could share the experience that how to fix it.
> 
> Thanks and best, ztf5566

Hello ztf5566, 
Yes, I did it. Please build the mpi/openmpi by yourself and do not use the bwUniCluster_2.0's mpi.

The discussion (https://github.com/idaholab/moose/discussions/22720 ) which I raised in the MOOSE github may give you some help.

**Comment by ztf5566** [comment]
Hi Joseph-0123,

Thanks a lot. Now I am able to use MOOSE on  bwUniCluster_2.0 after following your great suggestion.

Best,
ztf5566

**Comment by Joseph-0123** [comment]
> Hi Joseph-0123,
> 
> Thanks a lot. Now I am able to use MOOSE on bwUniCluster_2.0 after following your great suggestion.
> 
> Best, ztf5566

Good news.
