### ISSUE TITLE
Allow BTL add_procs to fail

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#112]
Per lengthy discussion the devel list (starting here: http://www.open-mpi.org/community/lists/devel/2010/05/7988.php) and on the OMPI teleconf:

 * Allow BTL add_procs() to return a "something Really Bad happened; please abort the job" error code.  This is intended for dire circumstances, such as when malloc() fails.  It is '''not''' intended for cases where the BTL fails, but the job could otherwise continue.
 * Allow BTL add_procs() to return a "this BTL has failed; please ignore it for the rest of the run" error code.  This is intended for when a specific BTL initially stated that it could run during BTL selection, but then later figures out that it lied and needs to reneg and be ignored for the duration of the process.  The local BML/PML will then ignore this BTL.  Peer processes will need to use the fail-to-connect failover methodology that (supposedly) already works for the TCP and MX BTLs.
 * Add an MCA parameter to customize behavior of what happens when a BTL fails add_procs().  For example, if openib fails in add_procs(), should the BML/PML silently ignore it, or should it abort the job?  (arguably: we might already have enough of a mechanism here in the "btl" MCA param itself -- this bullet is just a reminder to re-examine and see if it's worthwhile to have a separate/additional MCA parameter).

I'm thinking that this should be 1.5 and beyond functionality -- not 1.4.x.  Thoughts?

**Comment by jsquyres** [comment]
This might be relevant to some updating that we're doing to add_procs() stuff.  Assigning to @hjelmn.

**Comment by jsquyres** [comment]
@hjelmn You just modified add_procs a bunch -- did this get resolved as a side-effect?

**Comment by jsquyres** [comment]
According to @hjelmn this behavior is possible in Open MPI v2.0.0.  Resolving.
