### ISSUE TITLE
[4.1.4] On Rocky Linux 9/RHEL9 rpmbuild generates binaries with missing `RPATH`/shared libraries

### ISSUE THREAD

**Issue by wenduwan** [open-mpi/ompi#11215]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.4.tar.bz2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

This is a minimal reproducer script
```bash
#!/usr/bin/env bash

set -euxo pipefail

wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.4.tar.bz2

tar xf openmpi-4.1.4.tar.bz2 --wildcards '*/openmpi.spec' --strip-components 4

sed -i "/^Provides/s/openmpi/openmpi-test-build/" openmpi.spec
sed -i "s/\$VERSION/4.1.4/g" openmpi.spec
sed -i "s/\$EXTENSION/bz2/g" openmpi.spec

mkdir -p ompi_build/SOURCES
cp openmpi-4.1.4.tar.bz2 ompi_build/SOURCES

rpmbuild -bb openmpi.spec --define '_topdir '"${PWD}"'/ompi_build' \
    --define 'mflags -j8' \
    --define '_source_filedigest_algorithm md5' \
    --define '_binary_filedigest_algorithm md5' \
    --define '_name openmi-test' \
    --define '_prefix /opt/openmpi' \
    --define '_mandir /opt/openmpi/share/man' \
    --define 'install_modulefile 1' \
    --define 'modulefile_subdir openmpi' \
    --define 'configure_options --with-sge --without-verbs --disable-builtin-atomics --enable-orterun-prefix-by-default'

sudo dnf install -y ompi_build/RPMS/x86_64/*.rpm

ldd /opt/openmpi/bin/mpirun
# Example output
#$ ldd /opt/openmpi/bin/mpirun
#	linux-vdso.so.1 (0x00007ffd3fb89000)
#	libopen-rte.so.40 => not found
#	libopen-pal.so.40 => not found
#	libevent_core-2.1.so.7 => /lib64/libevent_core-2.1.so.7 (0x00007f10b1987000)
#	libc.so.6 => /lib64/libc.so.6 (0x00007f10b177e000)
#	/lib64/ld-linux-x86-64.so.2 (0x00007f10b19d1000)

objdump -x /opt/openmpi/bin/mpirun | grep RPATH # No RPATH found

ldd /opt/openmpi/lib64/pmix/mca_gds_ds21.so

# Example output
#$ ldd /opt/openmpi/lib64/pmix/mca_gds_ds21.so
#	linux-vdso.so.1 (0x00007ffeb6bc1000)
#	libmca_common_dstore.so.1 => not found
#	libm.so.6 => /lib64/libm.so.6 (0x00007f6ed04fa000)
#	libz.so.1 => /lib64/libz.so.1 (0x00007f6ed04e0000)
#	libc.so.6 => /lib64/libc.so.6 (0x00007f6ed02d7000)
#	/lib64/ld-linux-x86-64.so.2 (0x00007f6ed05e8000)

objdump -x /opt/openmpi/lib64/pmix/mca_gds_ds21.so | grep RPATH # No RPATH found

```

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
N/A

### Please describe the system on which you are running

* Operating system/version: Rocky Linux 9.1
* Computer hardware: AWS EC2
* Network type: N/A

### Software versions
[installed_software.txt](https://github.com/open-mpi/ompi/files/10241483/installed_software.txt)

-----------------------------

## Details of the problem

We encountered an odd rpmbuild issue on Rocky Linux 9. Following the above procedures we ended up with binaries with missing RPATH/shared libraries. We understand 4.1.4 has been released a while ago so it might not support RL9/RHEL9 when it came out. Please note that we also tested on Rocky Linux 8.x which worked just fine, i.e. binaries are linked properly.

We have attempted to fix this by  `export LDFLAGS="Wl,-rpath,$$ORIGIN,..."`(with `$` character escaping) in `openmpi.spec` right before `%configure ...` - which partially worked for `bin/mpirun` etc., but not `lib64/pmix/*.so`.

For pmix, upon inspecting the build log, we discovered string escape issues around `$$ORIGIN`. We tried multiple levels of escaping, e.g. `\\\\\$\\\\\$ORIGIN`, none of which helped - `$$` was always evaluated instead. This is not unique to Rocky Linux 9, and it's also present in CentOS 7, RHEL8/RL8. It can be verified by `objdump -x <binary> | grep RPATH` - with `Wl,-rpath,$$ORIGIN` flag you will likely find e.g. `1234ORIGIN` in the rpath of the binary (1234 alike is the result of evaluating `$$`).

At this point we suspect that the current rpm build logic has a latent bug that forcefully evaluates escaped shell variables in `Wl,...` flag. And the rpm build process conflicts with Rocky Linux 9 in some way that causes the missing linkage.

Opinions, questions and suggestion are welcome! Thanks!

**Comment by rhc54** [comment]
For PMIx (and for PRRTE, once you get to OMPI v5), I am not an rpm person and cannot help you there. We have had contributors modify the spec file to work with different Linux variants and welcome patches for that purpose. So if you find some change to the rpm.spec that resolves your issue(s) for either of those projects, please open a PR against them!

**Comment by wzamazon** [comment]
Looks like rpmbuild set LT_SYS_LIBRARY_PATH to `{prefix}/lib64`, which caused this.

The error can be reproduced

```
tar -xf openmpi-4.1.4.tar.bz2 
cd openmpi-4.1.4
export LT_SYS_LIBRARY_PATH=$PWD/install/lib
./configure --prefix=$PWD/install >& config.log
make -j 36 >& make.log
make install >& install.log
ldd install/bin/mpirun 
ldd install/lib/pmix/mca_gds_ds12.so
```
