### ISSUE TITLE
mpi4py: Regression in singleton spawn tests

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#11216]
**Spawn** tests form mpi4py testsuite when running in **singleton MPI init** mode are currently failing. These tests are run weekly, so I guess the regression comes from changes in `open-mpi/ompi@master` during the last 7 days.

https://github.com/mpi4py/mpi4py-testing/actions/runs/3717580374/jobs/6305078153

Right now I do not have convenient access to my everyday development environment, therefore, I'm not able able to try things out locally and bisect the issue.

**Comment by dalcinl** [comment]
@hppritcha Maybe the issue comes form 15becc3b5729b6567bb8efa9ef347a7243699ca2?

**Comment by dalcinl** [comment]
@hppritcha After running the two builds [[bad]](https://github.com/mpi4py/mpi4py-testing/actions/runs/3720082445/jobs/6309339683) [[good]](https://github.com/mpi4py/mpi4py-testing/actions/runs/3720086806/jobs/6309346613), looks like the regression was introduced by #11183.

**Comment by hppritcha** [comment]
thanks for catching this @dalcinl .  looks like spawning from a singleton is broken.  i'll investigate this coming week.

**Comment by rhc54** [comment]
I have it - basic problem is fixed, but there was something more that I'm also addressing. Should be done tomorrow.
