### ISSUE TITLE
orte-submit connection failures

### ISSUE THREAD

**Issue by marksantcroos** [open-mpi/ompi#1123]
As mentioned in #1116 I see frequent startup failures from orte-submit where it returns -1.

The complete output from a failed orte-submit is:
```
[nid06819:20547] mca: base: components_register: registering framework oob components
[nid06819:20547] mca: base: components_register: found loaded component alps
[nid06819:20547] mca: base: components_register: component alps has no register or open function
[nid06819:20547] mca: base: components_register: found loaded component tcp
[nid06819:20547] mca: base: components_register: component tcp register function successful
[nid06819:20547] mca: base: components_register: found loaded component ud
[nid06819:20547] mca: base: components_register: component ud register function successful
[nid06819:20547] mca: base: components_open: opening oob components
[nid06819:20547] mca: base: components_open: found loaded component alps
[nid06819:20547] mca: base: components_open: component alps open function successful
[nid06819:20547] mca: base: components_open: found loaded component tcp
[nid06819:20547] mca: base: components_open: component tcp open function successful
[nid06819:20547] mca: base: components_open: found loaded component ud
[nid06819:20547] mca: base: components_open: component ud open function successful
[nid06819:20547] mca:oob:select: checking available component alps
[nid06819:20547] mca:oob:select: Querying component [alps]
[nid06819:20547] mca:oob:select: Skipping component [alps] - no available interfaces
[nid06819:20547] mca:oob:select: checking available component tcp
[nid06819:20547] mca:oob:select: Querying component [tcp]
[nid06819:20547] oob:tcp: component_available called
[nid06819:20547] WORKING INTERFACE 1 KERNEL INDEX 1 FAMILY: V4
[nid06819:20547] [[45981,0],0] oob:tcp:init rejecting loopback interface lo
[nid06819:20547] WORKING INTERFACE 2 KERNEL INDEX 2 FAMILY: V4
[nid06819:20547] [[45981,0],0] oob:tcp:init adding 10.128.26.216 to our list of V4 connections
[nid06819:20547] [[45981,0],0] TCP STARTUP
[nid06819:20547] mca:oob:select: Adding component to end
[nid06819:20547] mca:oob:select: checking available component ud
[nid06819:20547] mca:oob:select: Querying component [ud]
[nid06819:20547] oob:ud: component_available called
[nid06819:20547] mca:oob:select: Skipping component [ud] - failed to startup
[nid06819:20547] mca:oob:select: Found 1 active transports
[nid06819:20547] mca: base: components_register: registering framework rml components
[nid06819:20547] mca: base: components_register: found loaded component oob
[nid06819:20547] mca: base: components_register: component oob has no register or open function
[nid06819:20547] mca: base: components_open: opening rml components
[nid06819:20547] mca: base: components_open: found loaded component oob
[nid06819:20547] mca: base: components_open: component oob open function successful
[nid06819:20547] orte_rml_base_select: initializing rml component oob
[nid06819:20547] [[45981,0],0] rml_recv_buffer_nb for peer [[WILDCARD],WILDCARD] tag 54
[nid06819:20547] [[45981,0],0] rml_recv_buffer_nb for peer [[WILDCARD],WILDCARD] tag 57
[nid06819:20547] [[45981,0],0] rml_recv_buffer_nb for peer [[WILDCARD],WILDCARD] tag 56
[nid06819:20547] [[45981,0],0] rml_recv_buffer_nb for peer [[WILDCARD],WILDCARD] tag 9
[nid06819:20547] [[45981,0],0] rml_recv_buffer_nb for peer [[WILDCARD],WILDCARD] tag 3
[nid06819:20547] [[45981,0],0] rml_recv_buffer_nb for peer [[WILDCARD],WILDCARD] tag 26
[nid06819:20547] [[45981,0],0] rml_recv_buffer_nb for peer [[WILDCARD],WILDCARD] tag 53
[nid06819:20547] [[45981,0],0] rml_send_buffer to peer [[56498,0],0] at tag 1
[nid06819:20547] [[45981,0],0] posting recv
[nid06819:20547] [[45981,0],0] posting persistent recv on tag 54 for peer [[WILDCARD],WILDCARD]
[nid06819:20547] [[45981,0],0] posting recv
[nid06819:20547] [[45981,0],0] posting persistent recv on tag 57 for peer [[WILDCARD],WILDCARD]
[nid06819:20547] [[45981,0],0] posting recv
[nid06819:20547] [[45981,0],0] posting persistent recv on tag 56 for peer [[WILDCARD],WILDCARD]
[nid06819:20547] [[45981,0],0] posting recv
[nid06819:20547] [[45981,0],0] posting persistent recv on tag 9 for peer [[WILDCARD],WILDCARD]
[nid06819:20547] [[45981,0],0] posting recv
[nid06819:20547] [[45981,0],0] posting persistent recv on tag 3 for peer [[WILDCARD],WILDCARD]
[nid06819:20547] [[45981,0],0]: set_addr to uri 3702652928.0;tcp://10.128.36.168,160.91.205.203:47320
[nid06819:20547] [[45981,0],0]:set_addr checking if peer [[56498,0],0] is reachable via component tcp
[nid06819:20547] [[45981,0],0] oob:tcp: working peer [[56498,0],0] address tcp://10.128.36.168,160.91.205.203:47320
[nid06819:20547] [[45981,0],0] PASSING ADDR 10.128.36.168 TO MODULE
[nid06819:20547] [[45981,0],0]:tcp set addr for peer [[56498,0],0]
[nid06819:20547] [[45981,0],0] PASSING ADDR 160.91.205.203 TO MODULE
[nid06819:20547] [[45981,0],0]:tcp set addr for peer [[56498,0],0]
[nid06819:20547] [[45981,0],0]: peer [[56498,0],0] is reachable via component tcp
[nid06819:20547] [[45981,0],0] posting recv
[nid06819:20547] [[45981,0],0] posting persistent recv on tag 26 for peer [[WILDCARD],WILDCARD]
[nid06819:20547] [[45981,0],0] posting recv
[nid06819:20547] [[45981,0],0] posting persistent recv on tag 53 for peer [[WILDCARD],WILDCARD]
[nid06819:20547] [[45981,0],0] rml_send_msg to peer [[56498,0],0] at tag 1
[nid06819:20547] [[45981,0],0] OOB_SEND: ../../../../../orte/mca/rml/oob/rml_oob_send.c:210
[nid06819:20547] [[45981,0],0]:tcp:processing set_peer cmd
[nid06819:20547] [[45981,0],0] SET_PEER ADDING PEER [[56498,0],0]
[nid06819:20547] [[45981,0],0] set_peer: peer [[56498,0],0] is listening on net 10.128.36.168 port 47320
[nid06819:20547] [[45981,0],0]:tcp:processing set_peer cmd
[nid06819:20547] [[45981,0],0] set_peer: peer [[56498,0],0] is listening on net 160.91.205.203 port 47320
[nid06819:20547] [[45981,0],0] oob:base:send to target [[56498,0],0]
[nid06819:20547] [[45981,0],0] oob:tcp:send_nb to peer [[56498,0],0]:1 to channel=-1 seq = -1
[nid06819:20547] [[45981,0],0] tcp:send_nb to peer [[56498,0],0]
[nid06819:20547] [[45981,0],0]:[../../../../../orte/mca/oob/tcp/oob_tcp.c:466] post send to [[56498,0],0]
[nid06819:20547] [[45981,0],0]:[../../../../../orte/mca/oob/tcp/oob_tcp.c:403] processing send to peer [[56498,0],0]:1 to channel =-1 seq_num = -1
[nid06819:20547] [[45981,0],0]:[../../../../../orte/mca/oob/tcp/oob_tcp.c:437] queue pending to [[56498,0],0]
[nid06819:20547] [[45981,0],0] tcp:send_nb: initiating connection to [[56498,0],0]
[nid06819:20547] [[45981,0],0]:[../../../../../orte/mca/oob/tcp/oob_tcp.c:451] connect to [[56498,0],0]
[nid06819:20547] [[45981,0],0] orte_tcp_peer_try_connect: attempting to connect to proc [[56498,0],0]
[nid06819:20547] [[45981,0],0] oob:tcp:peer creating socket to [[56498,0],0]
[nid06819:20547] [[45981,0],0] orte_tcp_peer_try_connect: attempting to connect to proc [[56498,0],0] on socket 7
[nid06819:20547] [[45981,0],0] orte_tcp_peer_try_connect: attempting to connect to proc [[56498,0],0] on 10.128.36.168:47320 - 0 retries
[nid06819:20547] [[45981,0],0] waiting for connect completion to [[56498,0],0] - activating send event
[nid06819:20547] [[45981,0],0] tcp:send_handler called to send to peer [[56498,0],0]
[nid06819:20547] [[45981,0],0] tcp:send_handler CONNECTING
[nid06819:20547] [[45981,0],0]:tcp:complete_connect called for peer [[56498,0],0] on socket 7
[nid06819:20547] [[45981,0],0] tcp_peer_complete_connect: sending ack to [[56498,0],0]
[nid06819:20547] [[45981,0],0] SEND CONNECT ACK
[nid06819:20547] [[45981,0],0] SENDING CREDENTIAL OF SIZE 45
[nid06819:20547] [[45981,0],0] send blocking of 89 bytes to socket 7
[nid06819:20547] [[45981,0],0] blocking send complete to socket 7
[nid06819:20547] [[45981,0],0] tcp_peer_complete_connect: setting read event on connection to [[56498,0],0]
[nid06819:20547] [[45981,0],0]:tcp:recv:handler called for peer [[56498,0],0]
[nid06819:20547] [[45981,0],0] RECV CONNECT ACK FROM [[56498,0],0] ON SOCKET 7
[nid06819:20547] [[45981,0],0] waiting for connect ack from [[56498,0],0]
[nid06819:20547] [[45981,0],0]-[[56498,0],0] tcp_peer_recv_blocking: peer closed connection: peer state 4
[nid06819:20547] [[45981,0],0] tcp_peer_close for [[56498,0],0] sd 7 state ACK
[nid06819:20547] [[45981,0],0] unable to complete recv of connect-ack from [[56498,0],0] ON SOCKET 7
[nid06819:20547] [[45981,0],0] SIMUL CONNECTION WITH [[56498,0],0]
[nid06819:20547] [[45981,0],0] tcp:lost connection called for peer [[56498,0],0]
```

And the excerpt from the orte-dvm log:
```
2015-11-11 04:25:49,418: agent_0.bootstrap_3 : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-batch2:26122] [[56498,0],0] message received from [[45981,0],0] for tag 1 on channel=-1
2015-11-11 04:25:49,419: agent_0.bootstrap_3 : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-batch2:26122] [[56498,0],0] rml_send_buffer to peer [[45981,0],0] at tag 53
2015-11-11 04:25:49,419: agent_0.bootstrap_3 : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-batch2:26122] [[56498,0],0] message received  bytes from [[45981,0],0] for tag 1 on channel=-1 called callback
2015-11-11 04:25:49,530: agent_0.bootstrap_3 : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-batch2:26122] [[56498,0],0] rml_send_msg to peer [[45981,0],0] at tag 53
2015-11-11 04:25:49,564: agent_0.bootstrap_3 : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-batch2:26122] [[56498,0],0]-[[45981,0],0] Send message complete at ../../../../../orte/mca/oob/tcp/oob_tcp_sendrecv.c:232
```

[for my own bookkeeping: rp.session.titan-ext7.marksant1.016750.0001-pilot.0000]

**Comment by rhc54** [comment]
Hmmm...looks to me like the two procs are getting out of sync on validating the connection, and so both drop it. I'll have to poke into it after Thanksgiving, I fear. If you are feeling brave, you are welcome to look at the connection handshake. I suspect there is a lingering race condition there somewhere.

**Comment by marksantcroos** [comment]
So, I took the dive :)

However, it looks like it is not a single problem, or at least it doesn't show up as a single issue, as after instrumenting the code I hit different error scenarios.

I'm also not sure if the fix would be easy, as it seems to boil down to socket/tcp system limits on the orte-dvm side.

Would this issue be enough of an excuse to pick up the discussion we had about a single/persistent/direct link between our code and the dvm?

**Comment by rhc54** [comment]
Hmmmm....it's been awhile, so let's quickly review the situation. You have a workflow orchestrator that is launching lots and lots of orte-submit jobs in parallel, yes? When that happens, you start hitting socket limits on the orte-dvm.

If that is true, then the question becomes: can the orchestrator open the socket to the dvm and just submit lots of parallel execution requests? The answer is of course "yes" IF the orchestrator is a C-program and not a script, but can you first confirm that I've correctly described the situation?

**Comment by marksantcroos** [comment]
> Hmmmm....it's been awhile, so let's quickly review the situation. You have a workflow orchestrator that is launching lots and lots of orte-submit jobs in parallel, yes? When that happens, you start hitting socket limits on the orte-dvm.

ACK. In an ideal world we would have a couple of those orchestrators for load balancing purposes, but still a (couple of) order(s) of magnitude less than we have orte-submits now.

> If that is true, then the question becomes: can the orchestrator open the socket to the dvm and just submit lots of parallel execution requests? The answer is of course "yes" IF the orchestrator is a C-program and not a script, but can you first confirm that I've correctly described the situation?

Right. Although the code base is python, we would like to get rid of this central "exec()" per orte-submit.
Consequently, I'm willing to take the complexity overhead of using some wrapper mechanism to be able to call C code as mature mechanisms for that exists.

We discussed some of this back in June and you suggested (rephrasing) that we could either expose the orte-submit functionality as a library call, or even go directly to PMIx_Spawn.

**Comment by rhc54** [comment]
Okay, that helps a lot - thanks! Going to PMIx_Spawn is possible provided the orchestrator is on the same node as the orte-dvm process, so that might be a possibility. It would require a slight mod to PMIx as right now it only allows connection from one of its own children.

I suppose one possibility would be to have orte-dvm fork/exec your orchestrator when it starts up. This would resolve the problem right away as PMIx_Spawn would then just work.

The other possibility is to wrap the orte_plm.spawn command so you could access it from the orchestrator. You would have to wrap a bunch of things, though, as you have to assemble the orte_job_t object to pass to it - might be more pain than it's worth.

We'd have the same issue with PMIx, though - you'd have to wrap at least the Spawn API, and figure out how to create all the structs that need to be passed to it. I forget the equivalent in Python to the C "struct" - would that be a big deal to do?

**Comment by marksantcroos** [comment]
> Going to PMIx_Spawn is possible provided the orchestrator is on the same node as the orte-dvm process, so that might be a possibility.

That will generally not be the case in practice, so that would rule that path out.

> The other possibility is to wrap the orte_plm.spawn command so you could access it from the orchestrator.

This is the scenario earlier labeled as a direct library call, right? Or is this yet another scenario?

> You would have to wrap a bunch of things, though, as you have to assemble the orte_job_t object to pass to it - might be more pain than it's worth.

Assuming I would have all the information to do so, that looks like an acceptable compromise.
Getting rid of the many TCP connections and all the exec()'s is a worthy goal.

> We'd have the same issue with PMIx, though - you'd have to wrap at least the Spawn API, and figure out how to create all the structs that need to be passed to it.

Ok, so from that perspective not using PMIx directly is not much of a loss.

> I forget the equivalent in Python to the C "struct" - would that be a big deal to do?

Python doesn't have a struct, the closest is "dict" probably. But the language bridge solutions like swig, ctypes, etc. have mechanisms to map the data structures.

**Comment by rhc54** [comment]
Okay, sounds like the direct library call to orte_plm.spawn is the way to go. This is actually all that orte-submit does - if you look at orte/tools/orte-submit/orte-submit.c, you'll see that all it does is parse the cmd line to create the orte_job_t (which contains the full description of the app you want launched) and then it calls orte_plm.spawn.

So I could give you two options:

* you could implement the construction of the job object and call spawn

* we could package orte-submit as a library call where you pass in a cmd line string, and we package it up and call spawn

I would assume you'd prefer the latter?

**Comment by marksantcroos** [comment]
> So I could give you two options:
> 
> you could implement the construction of the job object and call spawn
> 
> we could package orte-submit as a library call where you pass in a cmd line string, and we package it up and call spawn

I also need some control over node placement, core count and environment, but I guess that could still be exposed on the orte-submit library call. The more that is done on the C level the better, from both simplicity and performance.

How involved is it to separate the TCP level and the plm level code?

**Comment by rhc54** [comment]
It would be pretty hard to separate the two without making you wrap an awful lot of code. Node placement and core count are already exposed on the orte-submit cmd line, so nothing different would need be done there. We could add a param that would allow passing of the environment - perhaps something like this:

```c
int orte_submit(char *cmd_line, char *environment)
```
where the cmd line looks just like the orte-submit cmd line, and the environment is a colon-separated list of environmental variables in <var>=<value> form.

Make sense?

**Comment by rhc54** [comment]
Crud - they ate my brackets. The envar param is var=value:var2=value2 form

**Comment by rhc54** [comment]
I guess we'd also need a way for me to tell you when that application had completed - we normally use a callback function, but that might be hard to wrap. Do you want to do this threaded, and have the orte_submit function block until the application completes? Or do you have some other mechanism in mind?

**Comment by marksantcroos** [comment]
> int orte_submit(char *cmd_line, char *environment)

That sounds ok. I assume you propose this as the cmd_line is parsed at the other side anyway?

> It would be pretty hard to separate the two without making you wrap an awful lot of code.

Hmm, I'm not sure if we are talking about the same thing now. My question was more how much work this would be in general, apart from the python discussion.

I'm assuming we will have to separate the TCP and plm stuff, otherwise we still end up with a TCP connection per task, or am I missing something now?

> I guess we'd also need a way for me to tell you when that application had completed - we normally use a callback function,

Callbacks would be my preferred option too. We already make use of that extensively in our code.
I agree that we have to see how that works from a wrapping perspective, but a quick internet search seems to tell me that its possible.

**Comment by rhc54** [comment]
Let me clarify. The cmd line is currently parsed by the orte-submit tool and the results of that parsing are put in an orte_job_t object. This object is then passed to orte_plm.spawn(orte_job_t*), which opens a socket to orte-dvm and sends the object across. The DVM then executes it and sends back a message when the app is complete.

What I'm proposing is that your orchestrator call orte_submit with the same cmd line it constructs now when calling "system(cmd_line)" to run orte-submit. However, instead of using system to run the cmd, the orte_submit() function will construct the object and call orte_plm.spawn for you.

This way, there will be only one socket opened between your orchestrator and orte-dvm. We will simply reuse it to keep sending new orte_job_t objects across to be executed. You won't be launching any orte-submit processes, thus avoiding all this connection stuff.

Does that clarify things?

**Comment by marksantcroos** [comment]
> This way, there will be only one socket opened between your orchestrator and orte-dvm. We will simply reuse it to keep sending new orte_job_t objects across to be executed.

Right, my question was about how easy it is to re-use the socket.

**Comment by marksantcroos** [comment]
So how would this practically work? Would there only be an orte-submit() function that sets up the socket things the first time it gets called and creates some kind of singleton? All consecutive orte-submit() calls would then reuse that? Or will we first setup the connection and pass those details to orte-submit()?

Does general OMPI architecture dictate any form over the other? Is this already in place?

**Comment by rhc54** [comment]
I have to create the orte_submit() function, but the rest of it is already in place. The first call to orte_submit would cause a call to orte_init to setup the communication system and connect to orte-dvm. After that, it would just keep sending job objects to orte-dvm.

So you would only need to wrap the orte_submit() function, and handle the callback. Everything else would be taken care of under the covers.

**Comment by marksantcroos** [comment]
Ok, that sounds good.

And possibly also less work than debugging the TCP issues. And more future-proof for sure!

**Comment by marksantcroos** [comment]
Closing this as the many-connection model is not the way forward anyway.
