### ISSUE TITLE
Unexplainable Hang

### ISSUE THREAD

**Issue by ImanHosseini** [open-mpi/ompi#11251]
Thank you for taking the time to submit an issue!

## Background information
I am using OpenMPI 4.0.3 (installed through apt)

## Please describe the system on which you are running
Running in Ubuntu (WSL2)

## Details of the problem
The issue: program would hang. My guess was connection issue, but it was weird because I had checked and ssh _was_ working. So I straced to see what's going on and I was shocked to see the results! :
```shell
iman@WSLPC:~/projs/pois$ strace -f -e execve -- mpirun -host val ./poisson
execve("/usr/bin/mpirun", ["mpirun", "-host", "val", "./poisson"], 0x7ffea619bc58 /* 41 vars */) = 0
strace: Process 18341 attached
[pid 18341] execve("/usr/bin/nvidia-modprobe", ["/usr/bin/nvidia-modprobe"], 0x7ffcbc60ecc8 /* 0 vars */) = 0
[pid 18341] +++ exited with 1 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=18341, si_uid=1000, si_status=1, si_utime=0, si_stime=1} ---
strace: Process 18342 attached
[pid 18342] execve("/usr/bin/nvidia-modprobe", ["/usr/bin/nvidia-modprobe"], 0x7ffcbc60ec98 /* 0 vars */) = 0
[pid 18342] +++ exited with 1 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=18342, si_uid=1000, si_status=1, si_utime=0, si_stime=0} ---
strace: Process 18343 attached
[pid 18343] execve("/usr/bin/nvidia-modprobe", ["/usr/bin/nvidia-modprobe"], 0x7ffcbc60ec98 /* 0 vars */) = 0
[pid 18343] +++ exited with 1 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=18343, si_uid=1000, si_status=1, si_utime=0, si_stime=2} ---
strace: Process 18344 attached
[pid 18344] execve("/usr/bin/nvidia-modprobe", ["/usr/bin/nvidia-modprobe"], 0x7ffcbc60ec98 /* 0 vars */) = 0
[pid 18344] +++ exited with 1 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=18344, si_uid=1000, si_status=1, si_utime=0, si_stime=2} ---
strace: Process 18345 attached
[pid 18345] execve("/usr/bin/nvidia-modprobe", ["/usr/bin/nvidia-modprobe"], 0x7ffcbc60ec98 /* 0 vars */) = 0
[pid 18345] +++ exited with 1 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=18345, si_uid=1000, si_status=1, si_utime=0, si_stime=1} ---
strace: Process 18346 attached
[pid 18346] execve("/usr/bin/nvidia-modprobe", ["/usr/bin/nvidia-modprobe"], 0x7ffcbc60ec98 /* 0 vars */) = 0
[pid 18346] +++ exited with 1 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=18346, si_uid=1000, si_status=1, si_utime=0, si_stime=2} ---
strace: Process 18347 attached
[pid 18347] execve("/usr/bin/nvidia-modprobe", ["/usr/bin/nvidia-modprobe"], 0x7ffcbc60ec98 /* 0 vars */) = 0
[pid 18347] +++ exited with 1 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=18347, si_uid=1000, si_status=1, si_utime=0, si_stime=1} ---
strace: Process 18348 attached
[pid 18348] execve("/usr/bin/nvidia-modprobe", ["/usr/bin/nvidia-modprobe"], 0x7ffcbc60ec98 /* 0 vars */) = 0
[pid 18348] +++ exited with 1 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=18348, si_uid=1000, si_status=1, si_utime=0, si_stime=1} ---
```
This is inexplicable! Why is there no ssh, and why is this weird unrelated modprobe thing being called? Any hints on what might be happening here?

**Comment by ggouaillardet** [comment]
Iman,

The first step is to

mpirun -host val hostname

to make sure the wire-up is correct.


I guess nvidia-modprobe is indirectly called by CUDA related detection.

Anyway, this is a setuid root binary, which means it cannot be strace'd as
expected unless you are running as root.
one option is to run strace mpirun ... as root (not you will need to pass
the --allow-run-as-root option).

an other option is to forgets strace and your OpenMPI built in traces:

mpirun --mca plm_base_verbose 10 ...
it should print the ssh command line (assuming you are not running under a
batch manager)
if it does not, you might have to rebuild OpenMPI and pass --enable-debug
to your command line


Cheers,

Gilles

**Comment by ImanHosseini** [comment]
Thanks, this is from "mpirun --mca plm_base_verbose":
```
[DESKTOP-OVPGS75:03131] [[1143,0],0] plm:rsh: final template argv:
        /usr/bin/ssh <template>  orted -mca ess "env" -mca ess_base_jobid "74907648" -mca ess_base_vpid "<template>" -mca ess_base_num_procs "2" -mca orte_node_regex "DESKTOP-OVPGS[2:75],val@0(2)" -mca orte_hnp_uri "74907648.0;tcp://172.27.198.230,172.27.198.230,192.168.67.3:56301" --mca plm_base_verbose "10" -mca plm "rsh" --tree-spawn -mca routed "radix" -mca orte_parent_uri "74907648.0;tcp://172.27.198.230,172.27.198.230,192.168.67.3:56301" -mca pmix "^s1,s2,cray,isolated"
```
1] "-mca orte_node_regex "DESKTOP-OVPGS[2:75],val@0(2)"" -> this is unrelated, but weird! The machine name is OVPGS75, but there is no multitude of them, its just 1 machine with that name there is no 'OVPGS2' or any other number. Does it just guess they exist based on the name ending in a number?

2] I think I can see what's happening here. So my setup is: I have a windows laptop, on which I run WSL2, and a laptop which has native linux. So how can I SSH to the WSL2 machine? [this](https://www.hanselman.com/blog/how-to-ssh-into-wsl2-on-windows-10-from-an-external-machine), TLDR: part of it is I have setup port forwarding so that windows forwards port 22 to WSL at port 22 -> so SSH works but it seems this does not work because it uses other port numbers. Am I right? And if I am, what is a workaround for this issue? 
[windows](https://learn.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy) has no way for me to forward packets coming from that IP on _all_ the ports. Is there a way to make openmpi use specific ports, so I can hardcode those 2 ports into the port-forwarding?

**Comment by ggouaillardet** [comment]
Open MPI requires much more connectivity:
 - passwordless SSH is the bare minimum in order to spawn a remote `orted` daemon
 - `mpirun` and `orted` daemons must be able to communicate with each other via adhoc TCP sockets (via the `oob/tcp` component)
 - MPI instances (e.g. ranks) must be able to communicate with each other via adhoc TCP sockets (via the `btl/tcp` component)
 
This generally does not fly well with port forwarding.

your best option is probably to use a full blown virtual machine (for example VirtualBox) on your windows laptop and make sure it is assigned its own IP on the same network than your native Linux laptop.
