### ISSUE TITLE
An error occurred in MPI_Allreduce: the reduction operation MPI_LAND is not defined on the MPI_INTEGER datatype

### ISSUE THREAD

**Issue by jeffhammond** [open-mpi/ompi#11270]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.1.4

```
mpicc -show
clang -I/opt/homebrew/Cellar/open-mpi/4.1.4_2/include \
      -L/opt/homebrew/Cellar/open-mpi/4.1.4_2/lib \
      -L/opt/homebrew/opt/libevent/lib -lmpi
```

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Homebrew

### Please describe the system on which you are running

* Operating system/version: MacOS
* Computer hardware: Apple M1
* Network type: N/A

-----------------------------

## Details of the problem

```sh
mpicc -g -O2 -Wall -std=c99 land_integer.c -o land_integer.x
mpirun -n 1 ./land_integer.x
*** An error occurred in MPI_Allreduce: the reduction operation MPI_LAND is not defined on the MPI_INTEGER datatype
*** reported by process [1420558337,0]
*** on communicator MPI_COMM_WORLD
*** MPI_ERR_OP: invalid reduce operation
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
```

### land_integer.c

```c
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>

int main(void)
{
    MPI_Init(NULL,NULL);

    int me, np;
    MPI_Comm_rank(MPI_COMM_WORLD,&me);
    MPI_Comm_size(MPI_COMM_WORLD,&np);

    MPI_Fint i = me;
    MPI_Allreduce(MPI_IN_PLACE, &i, 1, MPI_INTEGER, MPI_LAND, MPI_COMM_WORLD);

    return MPI_Finalize();
}
```

**Comment by ggouaillardet** [comment]
This is imho a correct interpretation of the standard.

According to MPI 4.0, chapter 6.9 pages 227, allowed types for `MPI_LAND` are C integer and Logical.

**Comment by jeffhammond** [comment]
You're right.  Sorry for the trouble.
