### ISSUE TITLE
Write up a documentation page on MCA subsystem(s) for v5.0.0

### ISSUE THREAD

**Issue by gpaulsen** [open-mpi/ompi#11286]
I'm working to write up a documentation page on how the Open MPI MCA subsystems work for the Open MPI v5.0.0 release.
This will include:
o High level description of MCA framework
o MCA framework specific options
o various ways to specify MCA parameters (env, commandline, param file, <defaults in code>)
o Description on how to use the `*_info` commands to query MCA at runtime.
o Description of other MCA subsystems inside of Open MPI (ompi/pmix/prte) and links to those projects/documentation.

This task is NOT intended to document the mca options for the Open MPI components.

Please use this issue to discuss until I have the PR ready.

**Comment by wckzhang** [comment]
All these topics are already covered, I'm going to resolve this issue
