### ISSUE TITLE
Support RHEL 7 out of the box libfabric

### ISSUE THREAD

**Issue by wckzhang** [open-mpi/ompi#11289]
With a recent change we upgraded the dependency of libfabric to be 1.9 whereas in RHEL 7, the OS package is 1.7. Need to add changes to the ofi mtl and ofi btl code to if/def the changes requiring 1.9 and reduce the dependency version.

**Comment by wckzhang** [comment]
Howard said he had a patch ready already and will PR today

**Comment by hppritcha** [comment]
this is effectively a dup of https://github.com/open-mpi/ompi/issues/10954

**Comment by jsquyres** [comment]
> this is effectively a dup of #10954

Agreed; closing as a dup.
