### ISSUE TITLE
Error during MPI_Cancel with OFI MTL

### ISSUE THREAD

**Issue by lrbison** [open-mpi/ompi#11306]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

main (57ca47ab)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
```
 5bd97056ccd994c711fde4ac19aded8e4eac8285 3rd-party/openpmix (v1.1.3-3726-g5bd97056)
 e0076a116884c9a8bcd5fffe20be84f3564446c3 3rd-party/prrte (psrvr-v2.0.0rc1-4537-ge0076a1168)
 237ceff1a8ed996d855d69f372be9aaea44919ea config/oac (heads/main)
```

### Please describe the system on which you are running

* Operating system/version: Amazon Linux AL2
* Computer hardware: p4d
* Network type: EFA

-----------------------------

## Details of the problem

Testing mpi4py's internal tests (9cbc39a1 of https://github.com/mpi4py/mpi4py), I found crashes and/or errors during `testCancel (test_p2p_obj.TestP2PObjSelf)` in `test_p2p_obj.py`

## Reproducer:
`python test/runtests.py -v -i test_p2p_obj.py -f`

Crashes occur in `ompi/mca/mtl/ofi/mtl_ofi.h: ompi_mtl_ofi_cancel`.  Initially `ofi_req->comm->c_index` was segfaulting because ofi_req->comm was `0x1` or `0x0` and the after moving that reference to the OMPI_MTL_OFI_RECV case, I find that `ofi_req->type`  ~~is garbage (`401`)~~  Actually it is 4: OMPI_MTL_OFI_PROBE.

**Comment by lrbison** [comment]
I've reproduced on both v5.0.x and main.

ofi_req->type is actually OMPI_MTL_OFI_PROBE (4) so it's not garbage.

Something funny is happening with cancelling the request in general, because if we comment out the `#req.cancel()` line, we still hang in the one-line loop `while not flag: flag = req.get_status()`.

The test passes if we don't use the OFI BTL.

**Comment by wckzhang** [comment]
> The test passes if we don't use the OFI BTL.

Did you mean OFI MTL?

**Comment by lrbison** [comment]
This is a two part problem.

The first problem is addressed by https://github.com/open-mpi/ompi/pull/11324 where cancellation of ISend and IProbe could segfault, and cancellation of IProbe if it didn't segfault would return error.

The second part is that mpi4py's recv call might actually call IProbe followed by MRecv, and the MRecv function didn't generate ACK's as required by our SSend implementation.  This should be addressed by https://github.com/open-mpi/ompi/pull/11327

**Comment by lrbison** [comment]
> Did you mean OFI MTL?

Yes

**Comment by lrbison** [comment]
This crash also happens in 4.1.x, although backporting isn't seamless.
