### ISSUE TITLE
[4.1.x] mpirun abort after receiving 10 SIGPIPE signal

### ISSUE THREAD

**Issue by wzamazon** [open-mpi/ompi#11322]
Thank you for taking the time to submit an issue!

## Background information

I noticed that `mpirun` from 4.1.x branch would abort itself, when receiving 10th SIGPIPE event.
The code is at:

https://github.com/open-mpi/ompi/blob/v4.1.x/orte/mca/ess/hnp/ess_hnp_module.c#L1001

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.1.x branch

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

built from source

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

N/A

### Please describe the system on which you are running

* Operating system/version: Amazon linux 2
* Computer hardware: AMD EPYC 7R13
* Network type: EFA (though should not matter

-----------------------------

## Details of the problem

I am investigating a random `mpirun` failure on a system user typically launch 96 processes (1 process per core).

What I found is that `mpirun` is working as PMIx server, and send response to a client try to connect with it.

Sometimes, server will fail to send repsonse to client due to "broken pipe" error. (I have not determined why it will happen)

For each send error, `mpirun` will also get a SIGPIPE signal. What is interesting to me is that `mpirun` will abort itself when it receives the 10th SIGPIPE

Code is:
https://github.com/open-mpi/ompi/blob/91ac1d7e22f9da04ffc25d5c587683ecdb150da0/orte/mca/ess/hnp/ess_hnp_module.c#L1001

I wonder why do not just ignore SIGPIPE? After all, client can close connection before  it got  response, which will result server (mpirun) to get a SIGPIPE signal.

**Comment by wzamazon** [comment]
I did some research, and found this behavior (abort at 10th SIGPIPE) was introduced in this commit  30c635fd4dca343b03ec40ea7c2ceb3f7d1e79d0.


```
Author: Ralph Castain <rhc@open-mpi.org>
Date:   Thu Nov 25 15:25:24 2010 +0000

    Don't endlessly output sigpipe errors. Count the number of times we trap it, and abort if we get more than 10 of them.
```
But it did not provide a motivation for doing so.

@rhc54 Your thoughts on this would be greatly appreciated.

**Comment by wzamazon** [comment]
Thank you!

I am looking into the origin of the SIGPIPE error. Currently, it looks like the client encountered  "a brief series of failures". It was able to recover from it.

Regarding the experimentation the determined 10 as reasonable cutoff, were the experiments done on a multi-client on server situation? If so, how much clients were used?

My point is: with newer CPU that has more cores, user tend to launch more clients for one server, should we increase the threshold accordingly?

**Comment by wckzhang** [comment]
Is it possible to have this number dynamically tuned based on number of cores?

**Comment by rhc54** [comment]
> My point is: with newer CPU that has more cores, user tend to launch more clients for one server, should we increase the threshold accordingly?

No idea - suppose you could make it an MCA param if you like. I don't remember how many clients were involved - I think the key is trying to identify the source of the errors and fixing those. Otherwise, you really are just playing with fire trying to guess how many failures are "okay".

**Comment by rhc54** [comment]
> Is it possible to have this number dynamically tuned based on number of cores?

Anything is possible - like I said, though, whatever number you pick will either be too low (and you'll abort "too soon") or too high (leading to lots of time spent cycling across errors before giving up).

**Comment by wzamazon** [comment]
Thank you!

I will focus on the root cause of the SIGPIPE then.

On that I have a question:

can you point me to code that client send connection request to the server?

I meant the request that will cause server to call the function "connection_handler"

https://github.com/open-mpi/ompi/blob/91ac1d7e22f9da04ffc25d5c587683ecdb150da0/opal/mca/pmix/pmix3x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c#L1099

**Comment by rhc54** [comment]
I haven't looked at the PMIx v3.x code in a very long time. The client starts its connection in
```c
pmix_status_t pmix_ptl_base_connect(struct sockaddr_storage *addr,
                                    pmix_socklen_t addrlen, int *fd)
```
which is in the `src/mca/ptl/base/ptl_base_connect.c` file. This is called from
```c
static pmix_status_t try_connect(char *uri, int *sd, pmix_info_t iptr[], size_t niptr)
```
in `src/mca/ptl/tcp/ptl_tcp.c`. I'd start there.

**Comment by wzamazon** [comment]
Thank you for the pointer!

Closing for now.

**Comment by wzamazon** [comment]
@rhc54

With your pointer, I was able to identify the reason why client closed the connection in this case.

It happened inside `try_connect()`

around 
https://github.com/open-mpi/ompi/blob/91ac1d7e22f9da04ffc25d5c587683ecdb150da0/opal/mca/pmix/pmix3x/pmix/src/mca/ptl/tcp/ptl_tcp.c#L983

`try_connect()` call `recv_connect_ack()` to recv some data. When `recv_connect_ack()` failed, `try_connect` will close the socket.

`recv_connect_ack()` call `pmix_ptl_base_recv_blocking()`, which call `recv()` to receive data.

 I noticed that `pmix_ptl_base_recv_blocking()` will return error, when `recv()` encountered EAGAIN,

https://github.com/open-mpi/ompi/blob/91ac1d7e22f9da04ffc25d5c587683ecdb150da0/opal/mca/pmix/pmix3x/pmix/src/mca/ptl/base/ptl_base_connect.c#L150

(Although the comment in the function says it will retry.)

This error caused the socket to be closed, which in turn caused server to get the SIGPIPE signal, and 10 such events caused
server to be aborted.

**Comment by rhc54** [comment]
Sounds like it is worth a try

**Comment by wzamazon** [comment]
I tried this fix and I can confirm this fixed the issue.

I opened a PR https://github.com/open-mpi/ompi/pull/11330.

For some reason I cannot invite you as reviewer.

**Comment by wzamazon** [comment]
PR has been merged.
