### ISSUE TITLE
v5.0.x: Nightly Snapshot missing ROMIO support

### ISSUE THREAD

**Issue by jjhursey** [open-mpi/ompi#11364]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Open MPI v5.0.x nightly tarball (Jan 28):
 * https://www.open-mpi.org/nightly/v5.0.x/

According to MTT [link](https://mtt.open-mpi.org/index.php?limit=&wrap=&trial=&enable_drilldowns=&yaxis_scale=&xaxis_scale=&hide_subtitle=&split_graphs=&remote_go=&do_cookies=&phase=all_phases&text_start_timestamp=past+3+weeks&text_platform_hardware=all&show_platform_hardware=show&text_os_name=all&show_os_name=show&text_mpi_name=%5Eompi-nightly-v5.0.x%24&show_mpi_name=show&text_mpi_version=all&show_mpi_version=show&text_http_username=ibm&show_http_username=show&text_local_username=all&show_local_username=hide&text_platform_name=all&show_platform_name=show&click=Summary&phase=all_phases&text_compute_cluster_id=&text_os_version=&show_os_version=&text_platform_type=&show_platform_type=&text_submit_id=&text_hostname=&show_hostname=&text_mpi_get_id=&text_mpi_install_compiler_id=&text_mpi_install_configure_id=&text_mpi_install_id=&text_compiler_name=&show_compiler_name=&text_compiler_version=&show_compiler_version=&text_vpath_mode=&show_vpath_mode=&text_endian=&show_endian=&text_bitness=&show_bitness=&text_configure_arguments=&text_exit_value=&show_exit_value=&text_exit_signal=&show_exit_signal=&text_duration=&show_duration=&text_client_serial=&show_client_serial=&text_result_message=&text_result_stdout=&text_result_stderr=&text_environment=&text_description=&lastgo=summary):
 * Last Success: `v5.0.x-202301070345-1b10b9b`
 * First Failure: `v5.0.x-202301110343-9643281`

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

1. Download the nightly snapshot for v5.0.x
2. Configure with: `./configure --enable-io-romio`

### Please describe the system on which you are running

* Operating system/version: RHEL 8.4
* Computer hardware: ppc64le
* Network type: N/A

-----------------------------

## Details of the problem

```shell
shell$ ./configure --enable-io-romio
...
--- MCA component io:romio341 (m4 configuration macro)
checking for MCA component io:romio341 compile mode... static
checking if want ROMIO component... yes
checking if MPI profiling is enabled... yes

*** Configuring ROMIO distribution
configure: error: ROMIO distribution did not configure successfully
```

If I re-run autogen then it throws this error:
```shell
shell$ ./autogen.pl --force
...
=== Processing subdir: 3rd-party/romio341
Could not change to 3rd-party/romio341
```

I'm guessing that's the problem, but I don't know how to fix.

**Comment by jjhursey** [comment]
@bwbarrett and @jsquyres, you two probably know where to look to fix this. Maybe something in 'make dist'? I just don't know the nightly snapshot mechanism to know where to look. This only happens with `v5.0.x`. All other branches seem fine including `main`.

**Comment by jjhursey** [comment]
I had a couple of moments to kick off a `make distcheck` in the background (assuming that is what is used for nightly tarballs. And the generated tarball included the `3rd-party/romio341/` directory when building from the `v5.0.x` branch. So I must be missing something with the nightly tarball generation to get it to reproduce for me locally.

Steps I used:
```
cd /tmp
git clone --recurse-submodules -b v5.0.x https://github.com/open-mpi/ompi.git ompi-v5
cd ompi-v5
./autogen.pl
./configure --enable-sphinx
make distcheck

mkdir -p /tmp/check-tar
cd /tmp/check-tar
tar -zxf /tmp/ompi-v5/openmpi-gitclone.tar.gz
ls openmpi-gitclone/3rd-party/romio341/
```

**Comment by bwbarrett** [comment]
probably stupid on my end, but I didn't keep the full logs for successful builds, and the dist run looks to have succeeded.  I think a good first step is to make "make dist" fail when ROMIO isn't included.  My guess is that it isn't included because configure didn't succeed for some reason.  I don't have time to look at it this week, but I think the patch below (on main) should work for making "make dist" fail when ROMIO doesn't configure properly.  This will then result in us saving the full build logs so we can understand what went wrong (and is a good failsafe anyway).  We should do something like the patch below regardless, just like we do for PMIx and PRRTE (the other two packages that are shipped as expanded source code instead of tarballs).

@awlauria I think there was a patch on main about ROMIO not properly configuring; might be worth looking at the history between main and v5.0.x and see if you can find something.

```
diff --git a/ompi/mca/io/romio341/configure.m4 b/ompi/mca/io/romio341/configure.m4
index 4396d62c83..2ec19ec20c 100644
--- a/ompi/mca/io/romio341/configure.m4
+++ b/ompi/mca/io/romio341/configure.m4
@@ -114,6 +114,7 @@ AC_DEFUN([MCA_ompi_io_romio341_CONFIG],[
 
                    AS_IF([test "$io_romio341_happy" = "1"],
                          [$1],
-                         [$2])])])
+                         [OPAL_MAKEDIST_DISABLE="$OPAL_MAKEDIST_DISABLE ROMIO"
+                          $2])])])
     OPAL_VAR_SCOPE_POP
 ])
```

**Comment by jjhursey** [comment]
A commit was added to break the distribution build if ROMIO was not included. This is intended to help isolate where things are breaking in the release process so it can be repaired.
 * `main` PR #11424
 * `v5.0.x` PR #11425

**Comment by bwbarrett** [comment]
The merged PRs to break the build did, in fact, break the build.  The data for the failed build is in a [tarball](download.open-mpi.org/nightly/open-mpi/failed-builds/openmpi-v5.0.x-202302210346-failed.tar.gz).
The ROMIO configure is failing with:

```
checking for clock_gettime... yes
checking for clock_getres... yes
checking for gethrtime... no
checking for mach_absolute_time... no
checking for gettimeofday... yes
./configure: line 11641: syntax error near unexpected token `else'
./configure: line 11641: `else $as_nop'
configure: error: MPL configure failed
configure: /bin/bash './configure' *failed* for 3rd-party/romio341
configure: WARNING: ROMIO distribution did not configure successfully
checking if MCA component io:romio341 can compile... no
```

**Comment by jsquyres** [comment]
This issue seems to depend on the version of Autoconf and/or Automake (I'm not sure which, and have run out of time to investigate further today).  Specifically:

* It does *not* happen with Autoconf 2.69 + Automake 1.15.
* It *does* happen with Autoconf 2.71 + Automake 1.16.5.

**Comment by jsquyres** [comment]
# Checking branches

1. The nightly tarball for `v5.0.x` is failing to get built.
    * As I noted above, it works with Autoconf 2.69 + Automake 1.15, but fails with Autoconf 2.71 + Automake 1.16.5.
3. Oddly, the nightly tarball to `main` is *not* failing to get built.
    * However, I notice that the behavior is the same as on the `v5.0.x` branch: it works with Autoconf 2.69 + Automake 1.15, but fails with Autoconf 2.71 + Automake 1.16.5.
    * This makes me wonder if the `main` nightly snapshot is using the wrong autotools env module to build itself.  I see on `aws.open-mpi.org` that we have the following autotools modules:
       ```
       ip-172-31-9-163# pwd        
       /home/mpiteam/modules/autotools
       ip-172-31-9-163# ls -1 ompi*
       ompi-master
       ompi-v1.10
       ompi-v2.0.x
       ompi-v2.x
       ompi-v3.0.x
       ompi-v3.1.x
       ompi-v3.x
       ompi-v4.0.x
       ompi-v4.1.x
       ompi-v5.0.x
       ```
      Notice the `ompi-master`, not `ompi-main`.  Is it working for the `main` nightly snapshot because we are missing an `ompi-main` module (sym link), and therefore the build for `main` is defaulting to the OS-default Autotools (i.e., AC 2.69 + AM 1.16.1)?  I didn't want to make an `ompi-main` module (sym link) without checking with @bwbarrett first.

# Fixing the ROMIO configury issue

I think that this is weirdness because of the changes that were introduced in Autoconf 2.71 (or 2.70? I don't remember).  Indeed, Open MPI had to make a bunch of changes to our configury to handle the upgrade to AC 2.7.1, so I wondered if MPICH/ROMIO did the same.

Looking at MPICH's git repo, it appears that this is the case.

Nominally, just replacing https://github.com/open-mpi/ompi/blob/main/3rd-party/romio341/mpl/configure.ac#L433-L498 with https://github.com/pmodels/mpich/blob/38552cfab7ac139754066e09f2a85e8b5a7d3df7/src/mpl/configure.ac#L451-L513 fixes the problem.  Essentially, it replaces `AC_TRY_RUN` and `AC_TRY_COMPILE` with `AC_RUN_IFELSE` and `AC_COMPILE_IFELSE` (along with associated m4 quoting changes, using`AC_LANG_SOURCE` and `AC_LANG_PROGRAM`, and indenting/whitespace changes).

There are still a ton of other AC warnings emitted by the ROMIO code at `autogen.sh` time -- I'm sure we *could* update a bunch of other ROMIO configury (but let's not -- unless we upgrade *all* of ROMIO, which I am **not** advocating that we do at this point). But this hunk appears to be the only place -- with our tuple of Autotools, at least -- that is *problematic*.

@bwbarrett What do we want to do here?  Should we replace that hunk in `3rd-party/romio314/mpl/configure.ac` with the corrected hunk from MPICH upstream?  Here's an ignore-whitespace comparison between the two so that you can see what I'm talking about:

```patch
diff --git a/3rd-party/romio341/mpl/configure.ac b/3rd-party/romio341/mpl/configure.ac
index 6c16286259..338eead7f8 100644
--- a/3rd-party/romio341/mpl/configure.ac
+++ b/3rd-party/romio341/mpl/configure.ac
@@ -426,13 +426,12 @@ pac_cv_posix_clock_realtime=no)
 
     linux86_cycle|linux86_cycle_2)
 
-# The following AC_TRY_RUN statements are needed because x86_64 compilers
+# The following AC_RUN_IFELSE statements are needed because x86_64 compilers
 # usually know about rdtscp but the cpu may or may not actually implement the
 # feature.  This is not cross-compile safe, unfortunately.  In the long run we
 # should allow the user to override this with a configure flag.
-    AC_CACHE_CHECK([that linux86 cycle counter is available],
-        pac_cv_linux86_cycle,
-            AC_TRY_RUN([
+    AC_CACHE_CHECK([that linux86 cycle counter is available], pac_cv_linux86_cycle, [
+        AC_RUN_IFELSE([AC_LANG_SOURCE([[
             int main()
             {
                 /* rdtscp */
@@ -440,8 +439,8 @@ int main()
                 __asm__ __volatile__("rdtscp; shl \$32, %%rdx; or %%rdx, %%rax" : "=a" (*var_ptr) : : "ecx", "rdx");
                 return 0;
             }
-            ],pac_cv_linux86_cycle=rdtscp,
-                AC_TRY_RUN([[
+            ]])],pac_cv_linux86_cycle=rdtscp,[
+        AC_RUN_IFELSE([AC_LANG_SOURCE([[
             int main()
             {
                 /* cpuid 64 */
@@ -449,8 +448,8 @@ int main()
                 __asm__ __volatile__("push %%rbx ; cpuid ; rdtsc ; pop %%rbx ; shl $32, %%rdx; or %%rdx, %%rax" : "=a" (*var_ptr) : : "ecx", "rdx");
                 return 0;
             }
-                ]],pac_cv_linux86_cycle=cpuid_rdtsc64,
-                    AC_TRY_RUN([[[
+            ]])],pac_cv_linux86_cycle=cpuid_rdtsc64,[
+        AC_RUN_IFELSE([AC_LANG_SOURCE([[
             int main()
             {
                 /* cpuid 32 */
@@ -458,8 +457,8 @@ int main()
                 __asm__ __volatile__("push %%ebx ; cpuid ; rdtsc ; pop %%ebx" : "=A" (*var_ptr) : : "ecx");
                 return 0;
             }
-                    ]]],pac_cv_linux86_cycle=cpuid_rdtsc32,
-                        AC_TRY_RUN([[[[
+            ]])],pac_cv_linux86_cycle=cpuid_rdtsc32,[
+        AC_RUN_IFELSE([AC_LANG_SOURCE([[
             int main()
             {
                 /* simple */
@@ -467,35 +466,33 @@ int main()
                 __asm__ __volatile__("rdtsc" : "=A" (*var_ptr));
                 return 0;
             }
-                        ]]]],pac_cv_linux86_cycle=rdtsc,
+            ]])],pac_cv_linux86_cycle=rdtsc,
             pac_cv_linux86_cycle=no)
-                    )
-                ),
-dnl The if-cross-compiling clause from the first AC_TRY_RUN.  Hope that if the
+        ])])], dnl closing the last 3 AC_RUN_IFELSE
+        [
+        dnl The if-cross-compiling clause from the first AC_RUN_IFELSE.  Hope that if the
         dnl compiler knows about the instruction then it's supported by the target
         dnl platform.
-                AC_TRY_COMPILE(,[[
+        AC_COMPILE_IFELSE([AC_LANG_PROGRAM([],[[
             long long var, *var_ptr=&var;
             __asm__ __volatile__("rdtscp; shl \$32, %%rdx; or %%rdx, %%rax" : "=a" (*var_ptr) : : "ecx", "rdx");
-                ]],pac_cv_linux86_cycle=rdtscp,
-                    AC_TRY_COMPILE(,[[[
+            ]])],pac_cv_linux86_cycle=rdtscp,[
+        AC_COMPILE_IFELSE([AC_LANG_PROGRAM([],[[
             long long var, *var_ptr=&var;
             __asm__ __volatile__("push %%rbx ; cpuid ; rdtsc ; pop %%rbx ; shl $32, %%rdx; or %%rdx, %%rax" : "=a" (*var_ptr) : : "ecx", "rdx");
-                    ]]],pac_cv_linux86_cycle=cpuid_rdtsc64,
-                        AC_TRY_COMPILE(,[[[[
+            ]])],pac_cv_linux86_cycle=cpuid_rdtsc64,[
+        AC_COMPILE_IFELSE([AC_LANG_PROGRAM([],[[
             long long var, *var_ptr=&var;
             __asm__ __volatile__("push %%ebx ; cpuid ; rdtsc ; pop %%ebx" : "=A" (*var_ptr) : : "ecx");
-                        ]]]],pac_cv_linux86_cycle=cpuid_rdtsc32,
-                            AC_TRY_COMPILE(,[[[[[
+            ]])],pac_cv_linux86_cycle=cpuid_rdtsc32,[
+        AC_COMPILE_IFELSE([AC_LANG_PROGRAM([],[[
             long long var, *var_ptr=&var;
             __asm__ __volatile__("rdtsc" : "=A" (*var_ptr));
-                            ]]]]],pac_cv_linux86_cycle=rdtsc,
-                            pac_cv_linux86_cycle=no)
-                        )
-                    )
-                )
-            )
-    )
+            ]])],pac_cv_linux86_cycle=rdtsc,
+            pac_cv_linux86_cycle=no
+        )])])]) dnl closing the 4 AC_COMPILE_IFELSE
+        ]) dnl end of first AC_RUN_IFELSE
+    ]) dnl end of AC_CACHE_CHECK
 
     case "$pac_cv_linux86_cycle" in
         "rdtscp")
```

**Comment by jjhursey** [comment]
@jsquyres Thanks for tracking down the fix.
 * `main` PR https://github.com/open-mpi/ompi/pull/11449
 * `v5.0.x` PR https://github.com/open-mpi/ompi/pull/11453

**Comment by awlauria** [comment]
Thanks @jsquyres !
