### ISSUE TITLE
Restoring 32-bit support

### ISSUE THREAD

**Issue by barracuda156** [open-mpi/ompi#11409]
Referring to: https://github.com/open-mpi/ompi/issues/11248#issuecomment-1376341965

@jsquyres @awlauria
Yes, I am interested to maintain 32-bit compatibility. Could you please advise me on what is needed?

Context: we want `ppc` platforms to be supported in Macports, and those are predominantly `ppc32`.

**Comment by jsquyres** [comment]
@barracuda156 Thanks for responding.

Did you see the conversation about this topic that occurred at https://github.com/open-mpi/ompi/pull/11282#issuecomment-1416364660?  It might be worth reading -- it's someone in a similar situation as you: Debian.  They support a bunch of 32-bit platforms, and have MPI libraries and applications on those platforms.

There is also a second conversation that occurred at nearly the same time on the Open MPI "devel" mailing list: https://www.mail-archive.com/devel@lists.open-mpi.org/msg21447.html.  It's not entirely clear yet whether Yatindra (the volunteer from the devel list) is going to submit their 32-bit work / maintain it over time.  That being said, it would be good to have multiple 32-bit maintainers.

To be clear: we (the Open MPI community) are not opposed to continuing 32-bit support, but:

* For reasons I described in the PR #11282 discussion, none of the other Open MPI community members have any customers or users who actually use MPI or run HPC applications in 32-bit environments.  Hence, we don't have any use cases to support it.
* Only you and Yatindra have volunteered to maintain it.
* Debian has also expressed an interest in 32-bit support, but after some discussion, it was determined that they have no known users who run MPI in 32 bit environments.  Instead, their rationale is the inertia of existing Debian libraries and apps that are supported in 32-bit environments; many of them are MPI-only, but at least a bunch of them can optionally support MPI.  It would be a bunch of work to selectively disable MPI for 32-bit environments in those packages.

Out of curiosity: do you have any known users who run MPI in 32-bit environments?

**Comment by barracuda156** [comment]
@jsquyres I will read through the references, thank you.

> Out of curiosity: do you have any known users who run MPI in 32-bit environments?

We have a number of ports that depend on MPI, some of those require MPI (perhaps akin to Debian case?). For some of those ports – in math and science – I am the maintainer, so yes, at least 1 user is known for sure :)

P. S. For unrelated technical reasons we do not have reliable statistics for ports usage on older macOS (system `curl` is too old, and to make `mpstats` work with new `curl` a manual setup of Macports is needed, which most users are either unaware of – or otherwise find it burdensome).

**Comment by barracuda156** [comment]
> @barracuda156 Are you going to provide a PR to restore 32 bit support?  v5.0.0 is getting quite close; time is running out.

Sorry for a delay, I get back to this in very beginning of April. Out of station at the moment, and I need my PPC machines – it is not a kind of task I would work on in Rosetta emulation.

**Comment by thesamesam** [comment]
@barracuda156 Did you get anywhere with it in the end?

**Comment by jsquyres** [comment]
@thesamesam v5.0.0 was released without 32 bit support.  Let's go ahead and close this issue; if someone wants to open a PR to re-introduce -- and more importantly, **maintain over time** -- 32 bit support, we'd love to see it.  Thanks!

**Comment by barracuda156** [comment]
@thesamesam @jsquyres There are several issues at the moment, and from the outlook it seems quite broken. Initial build failures I got were trivial to fix, however several components of OpenMPI may be rather troublesome.
I did not give up on the idea in principle, however it is not very high on priority list.
Life would have been easier if 32-bit support was considered when writing the code to begin with, but we are where we are.

I may have mentioned earlier, but I am not really sure that even 4.x versions worked correctly. (Though my testing was rather basic and it could be the case that my setup was not correct which affected results.)

If I have time and mood, I may give this another go. If it happens to be broken beyond repair, well, there is MPICH which works decently so far.

**Comment by rhc54** [comment]
> Life would have been easier if 32-bit support was considered when writing the code to begin with...well, there is MPICH

In the FWIW category: on at least one of the problematic subsystems, Argonne's MPICH team was directly involved in the design - and had no interest in 32-bit support.  🤷‍♂️

**Comment by barracuda156** [comment]
@rhc54 I did not claim otherwise, I am not involved with MPICH upstream and have no stakes there :) 
What I know is that it does build and work on 32-bit though (because some of my Fortran ports use it). Not perfectly, I guess, but also not broken at the build stage.

**Comment by jsquyres** [comment]
> Life would have been easier if 32-bit support was considered when writing the code to begin with, but we are where we are.

Just to be clear, Open MPI was originally written to fully support 32 and 64 bit.  However, over the years, 32 bit support became less important in real-world HPC, and therefore people stopped caring about it.  It is likely that parts of the code (and/or entire features) we developed over time that didn't really consider 32 bit.

All this being said, not much has changed since https://github.com/open-mpi/ompi/issues/11409#issuecomment-1429949719.
