### ISSUE TITLE
mpirun without any parameters confuses application parameter for its own

### ISSUE THREAD

**Issue by gkatev** [open-mpi/ompi#11402]
Hi, on the almost-latest main @ 7a5e9c5 (prrte is @ dc6ccf6), I'm seeing mpirun confusing application parameters for its own, when it itself does not have any. Please see the examples:

```
$ mpirun echo
/* all good */

$ mpirun echo -e
--------------------------------------------------------------------------
An unrecognized option was included on the mpirun command line:

	Option: -e

Please use the "mpirun --help" command to obtain a list of all
supported options.
--------------------------------------------------------------------------

$ mpirun -n 1 echo -e
/* all good */

$ mpirun --mca a a echo -e
/* all good */
```

**Comment by jsquyres** [comment]
@gkatev Does this also happen on v5.0.x?

I'm guessing you can run with `mpirun -- echo -e`, but we probably shouldn't require the `--` for a command line as simple as that.

**Comment by rhc54** [comment]
Fixed in referenced PR

**Comment by jsquyres** [comment]
Thanks @rhc54!

@awlauria Do we have any pending PMIX submodule-pointer-update PRs?  If not, can a new one be created when this PMIx PR is merged?

**Comment by rhc54** [comment]
This one (https://github.com/open-mpi/ompi/pull/11379) has been hanging around for a while - just updated it again

**Comment by awlauria** [comment]
Thanks!

@rhc54 what commit fixes this specifically, and do we need to port that to v5?

**Comment by rhc54** [comment]
The one I referenced: [22dabb8e471fb110ca75a5fd3d5f12d8d6a984a3](https://github.com/openpmix/openpmix/commit/22dabb8e471fb110ca75a5fd3d5f12d8d6a984a3)

I'm backporting it to the v4.2 branch today

**Comment by rhc54** [comment]
OMPI v5 submodule pointer updates is here: https://github.com/open-mpi/ompi/pull/11403
