### ISSUE TITLE
v4.1.1 build error

### ISSUE THREAD

**Issue by vasslavich** [open-mpi/ompi#11417]
Hi!
My target is:

- Ubuntu 20.04
- i7-9700

I'm using OpenMPI 4.1.4 and got the error:
`In file included from ../../../../../../../../../../opal/mca/pmix/pmix3x/pmix/src/mca/ptl/tcp/ptl_tcp.c:51:
/usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: error: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror=cpp]
   21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
      |  ^~~~~~~
cc1: all warnings being treated as errors
make[5]: *** [Makefile:743: ptl_tcp.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory '/home/devzone/OMPI-EXT-4.1.4/openmpi-4.1.4/build-debug/opal/mca/pmix/pmix3x/pmix/src/mca/ptl/tcp'
make[4]: *** [Makefile:1915: all-recursive] Error 1
make[4]: Leaving directory '/home/devzone/OMPI-EXT-4.1.4/openmpi-4.1.4/build-debug/opal/mca/pmix/pmix3x/pmix/src'
make[3]: *** [Makefile:787: all-recursive] Error 1
make[3]: Leaving directory '/home/devzone/OMPI-EXT-4.1.4/openmpi-4.1.4/build-debug/opal/mca/pmix/pmix3x/pmix'
make[2]: *** [Makefile:2090: all-recursive] Error 1
make[2]: Leaving directory '/home/devzone/OMPI-EXT-4.1.4/openmpi-4.1.4/build-debug/opal/mca/pmix/pmix3x'
make[1]: *** [Makefile:2394: all-recursive] Error 1
make[1]: Leaving directory '/home/devzone/OMPI-EXT-4.1.4/openmpi-4.1.4/build-debug/opal'
make: *** [Makefile:1912: all-recursive] Error 1`

Can anyone tell me how to stop this warning as error?
Thanks!

**Comment by jsquyres** [comment]
I am unable to replicate your error when building on Ubuntu 20.04.

Can you please provide all the details that were requested in the initial github issue bug report template?

**Comment by ggouaillardet** [comment]
it seems two conditions are met here:
 - <sys/sysctl.h> issues a warning (related to ubuntu 20.04 ?)
 - `-Werror` is used (`--enable-picky` ?)

**Comment by jsquyres** [comment]
@ggouaillardet Understood.  I tried building the Open MPI v4.1.4 tarball in Ubu 20, and it worked fine for me.  So at least for a default Ubu 20 install, I was unable to re-create the problem.  This is why I asked for more details.

IIRC, PMIx compiles by default with `-Werror` (it does in Open MPI `main`/`v5.0.x` branches -- I did not check, but I am *assuming* that it does back in the `v4.1.x` branch as well).

**Comment by rhc54** [comment]
At least for PMIx v4.x, we only do `-Werror` (and get really picky about things) by default for git clone builds - we shouldn't be doing it for tarballs. I didn't backport that behavior to the v3 series, but I don't remember the default settings for that series.

**Comment by vasslavich** [comment]
I've add `CFLAGS=-Wno-cpp --disable-werror` to a configure. It's workround for me, now buliding is ok. I suggest to close the issue.
Thank you!
