### ISSUE TITLE
OpenMPI "no oversubscribe" does not work when using MPI_Comm_spawn

### ISSUE THREAD

**Issue by siserte** [open-mpi/ompi#11421]
## Background information
OpenMPI version 4.1.2
Operating System: SUSE Linux Enterprise Server 12 SP2
Kernel: Linux 4.4.120-92.70-default
Architecture: x86-64

```
$cat hostfile
node00
node01
node02
node03
```
-----------------------------

## Details of the problem

I have a simple ```MPI_Comm_spawn```-based code that spawns 4 processes:

```
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>
int main(int argc, char* argv[]){
	MPI_Init(&argc, &argv);
	MPI_Comm intercomm;
	int final_nranks = 4, len;
    char name[MPI_MAX_PROCESSOR_NAME];
    MPI_Get_processor_name(name, &len);
	MPI_Comm_get_parent(&intercomm);
	if(intercomm == MPI_COMM_NULL){
		MPI_Info info;
                MPI_Info_create(&info);
		MPI_Info_set(info, "hostfile", "hostfile");
		MPI_Info_set(info, "map_by", "ppr:1:node");
		MPI_Comm_spawn(argv[0], MPI_ARGV_NULL, final_nranks, info, 0, MPI_COMM_WORLD, &intercomm, MPI_ERRCODES_IGNORE);
		printf("PARENT %s\n", name);
	} else {
		printf("CHILD %s\n", name);
	}
	MPI_Finalize();
	return 0;
}
```

When I run the code with 
```
$ mpirun  -np 2 --hostfile hostfile --map-by node ./a.out
```
I would expect something like:
```
PARENT node00
PARENT node01
CHILD node00
CHILD node01
CHILD node02
CHILD node03
```
I want that each process runs in a different node.
Since by default OpenMPI does not oversubscribe slots, I would expect that *child* processes were spawned in different nodes. But it is not the case. Instead, I get:
```
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  PML add procs failed
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
[node00:50113] *** An error occurred in MPI_Init
[node00:50113] *** reported by process [3761700866,2]
[node00:50113] *** on a NULL communicator
[node00:50113] *** Unknown error
[node00:50113] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[node00:50113] ***    and potentially your MPI job)
[node00:200682] 3 more processes have sent help message help-mpi-runtime.txt / mpi_init:startup:internal-failure
[node00:200682] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[node00:200682] 3 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal unknown handle
```

If I remove ```MPI_Info_set(info, "map_by", "ppr:1:node");``` from the code, the run does not crash but *child* processes are spawned in the same host:
```
PARENT node00
PARENT node01
CHILD node00
CHILD node00
CHILD node00
CHILD node00
```

**Comment by siserte** [comment]
I've upgraded to the last OpenMPI version 5.0.0rc10 and I get a weird behavior since sometimes it works with some errors:
```
[node00:281361] PMIX ERROR: ERROR in file prted/pmix/pmix_server_dyn.c at line 1034
[node00:281361] PMIX ERROR: OUT-OF-RESOURCE in file base/bfrop_base_unpack.c at line 1839
PARENT node00
CHILD node00
PARENT node01
CHILD node01
CHILD node02
CHILD node03
```

but in others execution I get:

```
[node00:281468] PMIX ERROR: ERROR in file prted/pmix/pmix_server_dyn.c at line 1034
[node00:281468] PMIX ERROR: OUT-OF-RESOURCE in file base/bfrop_base_unpack.c at line 1839
--------------------------------------------------------------------------
PRTE has lost communication with a remote daemon.

  HNP daemon   : [prterun-node00-281468@0,0] on node node00
  Remote daemon: [prterun-node00-281468@0,2] on node node01

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
[node00:00000] *** An error occurred in Socket closed
[node00:00000] *** reported by process [3933011970,0]
[node00:00000] *** on a NULL communicator
[node00:00000] *** Unknown error
[node00:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[node00:00000] ***    and MPI will try to terminate your MPI job as well)
```

**Comment by siserte** [comment]
Hi, is it possible to have some feedback on this?

Since I imagine that the team is involved in higher priority tasks I would like to have some hints or ideas to see if it is possible to reach a solution.

Thank you.

**Comment by siserte** [comment]
***Update
With the version in tarball `openmpi-5.0.0rc11.tar.gz` I always get:

```
[node00:281361] PMIX ERROR: ERROR in file prted/pmix/pmix_server_dyn.c at line 1034
[node00:281361] PMIX ERROR: OUT-OF-RESOURCE in file base/bfrop_base_unpack.c at line 1839
PARENT node00
CHILD node00
PARENT node01
CHILD node01
CHILD node02
CHILD node03
```

So, I have not seen the `PRTE has lost communication with a remote daemon.` error in any case.

**Comment by rhc54** [comment]
> If I remove MPI_Info_set(info, "pernode", "true"); from the code, the run does not crash but child processes are spawned in the same host

Looking at your posted code, I cannot find any such line. Can you please clarify?

**Comment by siserte** [comment]
You are right.
My bad.
I meant ```MPI_Info_set(info, "map_by", "ppr:1:node");'''. I've just edited the original post correcting it.

**Comment by rhc54** [comment]
Afraid those line numbers for the PMIx error logs don't match anything in the current code. Suspect that is because the OMPI rc11 is lagging behind. You might try the head of their v5 branch to see if the problem has already been fixed.

**Comment by rhc54** [comment]
I tried your example with the HEAD of today's OMPI v5 branch, and it worked fine:
```shell
$ mpirun -n 2 --map-by node ./a.out
CHILD rhc-node01
CHILD rhc-node02
PARENT rhc-node01
CHILD rhc-node03
CHILD rhc-node04
PARENT rhc-node02
$
```
So I think the problem has been solved.

**Comment by siserte** [comment]
I've just pulled the last commit of the branch v5.0.x (907350a1c8485ee74aefa607d19fbd7127c2e396) and I get the same.
I'll try to update PRTE and PMIX just in case it works for you because of that.

**Comment by rhc54** [comment]
I didn't do anything special - just checked out the head of the branch at 907350a1c8485ee74aefa607d19fbd7127c2e396 (using the default options plus `--enable-debug`), and built it. You might check that you are really using the mpirun you intended to use.

**Comment by siserte** [comment]
It didn't show the error when I compiled with UCX1.13.
I tested that option since the configure raise a warning regarding an old UCX version.

**Comment by rhc54** [comment]
Odd - UCX has nothing to do with the mapping code 🤷‍♂️  I don't use UCX, so I can't offer any advice there.

**Comment by siserte** [comment]
Well, in that case, could it be to use GCC9 instead of GCC7?
I loaded GCC9 for the UCX upgrade warning.

**Comment by rhc54** [comment]
Can't imagine why - I would instead suspect that something wasn't being refreshed when built. Rerunning configure for the new UCX version probably triggered a full rebuild and that "fixed" it.
