### ISSUE TITLE
Where can i find a report paper for analyzing MPI complexity???

### ISSUE THREAD

**Issue by astrung** [open-mpi/ompi#1142]
When i tried to find some papers for analyzing MPI complexity, i get only some papers about one of collective algorithms(About only All-to-all,etc,...)But i want to find some paper which report all of collective algorithms.Where can i find some papers like that??

**Comment by astrung** [comment]
Can someone give any hints for me???

**Comment by ggouaillardet** [comment]
feel free to browse the mailing list, that was answered not so long ago.
ompi_info --all | grep algo
should list the available algorithms.
the ultimate source of information is the code itself ompi/mca/coll/tuned with the v1.10 series.
generally speaking, you are much more likely to get a quick reply if you post to the users mailing list.

**Comment by astrung** [comment]
@ggouaillardet I have known about for available algorithms,but i need a report paper for complexity of available algorithms-not about using it

**Comment by bosilca** [comment]
As @ggouaillardet indicated we had a similar discussion on the [Open MPI mailing list](http://www.open-mpi.org/community/lists/users/2015/09/27719.php) end of September. In addition to the following links, I strongly suggest to dig for more answers on [Google Scholar](https://scholar.google.com/).
1. http://dl.acm.org/citation.cfm?doid=2751205.2751216 
2. http://icl.cs.utk.edu/projectsfiles/rib/pubs/Pjesivac-Grbovic_PMEO-PDS05.pdf 
3. https://www.cs.utexas.edu/~echan/vpapers/CCPE2007.pdf

**Comment by astrung** [comment]
And which tools we can use for analyze for MPI performance??@bosilca,@ggouaillardet
