### ISSUE TITLE
getting stuck when using openmpi on multi nodes

### ISSUE THREAD

**Issue by 1117z** [open-mpi/ompi#11437]
Thank you for taking the time to submit an issue!

## Background information

openmpi v4.1.4

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
I built it from source with configure command `./configure --prefix=${openmpi-install-path} --with-pmix=internal --without-verbs `

### Please describe the system on which you are running

* Operating system/version: openeuler 22.03 LTS
* Computer hardware: arm
* Network type:

-----------------------------

## Details of the problem

I tried to run a benchmark in 4 nodes.  It is unresponsive and the utilization of cpu is full.  It seems like a deadlock occurred during communication.  So, I ran the example `ring_c` to exclude this cause.

And something weird happened, the message was transmitted 2 rounds, and then it stuck without outputting any error. The output is as follow:
```
Process 0 sending 10 to 1, tag 201 (512 processes in ring)
Process 0 sent to 1                                       
Process 0 decremented value: 9                            
Process 0 decremented value: 8
```
And this bug won't occur when using 2 or less nodes.

**Comment by jsquyres** [comment]
When you say "stocked", do you mean that the application stopped emitting output, but the individual MPI processes were still running?  Or did the entire application stop (without error) and return to the shell prompt?

What type of networking are you using?

**Comment by 1117z** [comment]
I mean that the application stopped emitting output, but the individual MPI processes were still running
the networking is IB

**Comment by jsquyres** [comment]
Are you using the UCX PML or the openib BTL?

**Comment by 1117z** [comment]
Because the cluster is homogeneous cluster, and I ran it with default configuration, maybe it's UCX PML?


I need to check my openmpi configuration tomorrow.

**Comment by 1117z** [comment]
I found these in my openmpi configure output:
```
checking UCX version... bad (1.8.x)                                                                           
configure: WARNING: UCX support skipped because version 1.8.x was found, which has a known catastrophic issue.
configure: WARNING: Please upgrade to UCX version 1.9 or higher.                                              
......
--- MCA component btl:openib (m4 configuration macro)
checking for MCA component btl:openib compile mode... dso
checking rdma/rdma_cma.h usability... yes
checking rdma/rdma_cma.h presence... yes
checking for rdma/rdma_cma.h... yes
checking for rdma_create_id in -lrdmacm... yes
checking for rdma_get_peer_addr... yes
checking if UD CM is enabled... yes
checking if OpenFabrics RDMACM support is enabled... yes
checking whether expanded verbs are available... no
checking whether IBV_EXP_ATOMIC_HCA_REPLY_BE is declared... no
checking whether IBV_EXP_QP_CREATE_ATOMIC_BE_REPLY is declared... no
checking whether ibv_exp_create_qp is declared... no
checking whether ibv_exp_query_device is declared... no
checking whether IBV_EXP_QP_INIT_ATTR_ATOMICS_ARG is declared... no
checking for struct ibv_exp_device_attr.ext_atom... no
checking for struct ibv_exp_device_attr.exp_atomic_cap... no
checking for ibv_fork_init... yes
checking which openib btl cpcs will be built... oob rdmacm udcm
checking if MCA component btl:openib can compile... yes
```
It seems like I'm using openib BTL.

**Comment by 1117z** [comment]
I install ucx-v1.9.0 and rebuild open-mpi with that successfully. But `ring_c` still stuck.

**Comment by 1117z** [comment]
I installed UCX-v1.9.x and then rebuilt openmpi with it. And it works now. Thanks for your help sincerely! @jsquyres

**Comment by jsquyres** [comment]
Glad you got it working.  FWIW: the UCX BTL is the officially supported way to use IB these days; while the `openib` BTL was relevant when v4.1.0 was releases, it has since been deprecated (and is removed in the upcoming v5.0.x release).
