### ISSUE TITLE
OpenMPI flagging UCX on Omnipath Systems

### ISSUE THREAD

**Issue by ebolandrtx** [open-mpi/ompi#11458]
Hi 

We are seeing the following error messages:

 By default, for Open MPI 4.0 and later, infiniband ports on a device
  are not used by default.  The intent is to use UCX for these devices.
  You can override this policy by setting the btl_openib_allow_ib MCA parameter
  to true.

On our omnipath systems. We have the following environment variables set:

setenv      OMPI_MCA_PML            cm
setenv      OMPI_MCA_BTL            self,^tcp,^openib
setenv      OMPI_MCA_MTL            psm2,^ucx

Since i am explicitly telling open-mpi to use psm2 rather than ucx i was surprised to see the above error message, as i would presume it is only relevant for infiniband systems. Is this behaving as intended? Can i set btl_openib_allow_ib to ignore?

Thanks!

Erin

**Comment by ebolandrtx** [comment]
Or do we get this just because verbs support is compiled into openmpi?

**Comment by hppritcha** [comment]
short answer to your question is yes.  If you are doing your own Open MPI config/install just add

--with-verbs=no

to the configure line.

**Comment by ebolandrtx** [comment]
Howard, 

Thanks for the clarification. Just wanted to make sure that it was working the way it was supposed to on OmniPath.!

Erin

**Comment by jsquyres** [comment]
Sounds like @hppritcha's solution worked, so I'll close this issue.

**Comment by ebolandrtx** [comment]
Oh interesting - there were notes on the web about the include/exclude behavior that indicate they can be mixed. Thanks for clarifying!

**Comment by jsquyres** [comment]
@ebolandrtx If you can point me to where you found notes on the web that say you can mix them, I'd like to get those corrected.
