### ISSUE TITLE
Error message about ucx_p2p during run with 4.1.5 using XPMEM

### ISSUE THREAD

**Issue by tonycurtis** [open-mpi/ompi#11469]
Thank you for taking the time to submit an issue!

## Background information

Just started testing ompi 4.1.5.  Using XPMEM through UCX has started showing error messages that I've not seen before (although the programs seem to be running fine).  v.i.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.1.5

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

tarball

### Please describe the system on which you are running

* Operating system/version: Rocky 8.4
* Computer hardware: aarch64 / a64fx
* Network type: IB

-----------------------------

## Details of the problem

E.g. on a single node using the OSU MPI osu_bibw benchmark

```
$ UCX_TLS=xpmem mpiexec -n 2 ./a.out
[LOG_CAT_ML] component ucx_p2p is not available but requested in hierarchy: ucx_p2p:p2p
[LOG_CAT_ML] ml_discover_hierarchy exited with error
...
...
```

**Comment by janjust** [comment]
@tonycurtis HCOLL issue, can you run with -mca coll ^hcoll

**Comment by tonycurtis** [comment]
That gets rid of the messages

**Comment by janjust** [comment]
Could be an hcoll issue - can you check which version you're using? `/opt/mellanox/hcoll/bin/hcoll_info -v ?`

**Comment by tonycurtis** [comment]
Version: v4.7.3208 (1512342)

**Comment by janjust** [comment]
Yeah that's the latest. Hmm need to see about reproducing it. The error message comes from HCOLL basically failing to init because it cannot open up its ucx component for whatever reason.
I'm assuming -pml ucx -mca coll ^hcoll works?

**Comment by tonycurtis** [comment]
Assuming that's meant to be `--mca pml ...` I get:

```
$ UCX_TLS=xpmem salloc --partition='short' --ntasks=2 mpirun  --mca pml ucx -mca coll ^hcoll  ./a.out
No components were able to be opened in the pml framework.

This typically means that either no components of this type were
installed, or none of the installed components can be loaded.
Sometimes this means that shared libraries required by these
components are unable to be found/loaded.

  Host:      fj069
  Framework: pml
```

**Comment by janjust** [comment]
weird - ok - does ucx_info -d show the xpmem device as available? looks like an ucx issue afterall
I'm guessing the ucx your using is from mofed?

**Comment by tonycurtis** [comment]
`-d` shows xpmem.  Own build (1.13.1).  Ahhh, looks like I was mixing UCX versions

**Comment by janjust** [comment]
ok - is that the issue? If so, let's close the issue.

**Comment by tonycurtis** [comment]
Yeah, looks like it's working as expected.  I was just dumb and mixed up UCX versions.
