### ISSUE TITLE
[v5.0.x] MPI_Allreduce using MPI_IN_PLACE will segfault

### ISSUE THREAD

**Issue by wzamazon** [open-mpi/ompi#11473]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v5.0.x branch

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
built from source

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

```
7f6f8db13b42916b27b690b8a3f9e2757ec1417f ../3rd-party/openpmix (v4.2.3-8-g7f6f8db1)
 c7b2c715f92495637c298249deb5493e86864ac8 ../3rd-party/prrte (v3.0.1rc1-36-gc7b2c715f9)
 237ceff1a8ed996d855d69f372be9aaea44919ea ../config/oac (237ceff)
```

### Please describe the system on which you are running

* Operating system/version: Amazon Linux 2
* Computer hardware: Intel CPU
* Network type: EFA

-----------------------------

## Details of the problem

Reported from mtt, `ibm/collective/allreduce_in_place` is failing with segfault .

[link](https://mtt.open-mpi.org/index.php?limit=&wrap=&trial=&enable_drilldowns=&yaxis_scale=&xaxis_scale=&hide_subtitle=&split_graphs=&remote_go=&do_cookies=&phase=test_run&text_start_timestamp=2023-03-07+19%3A12%3A31+-+2023-03-08+19%3A12%3A31&text_platform_hardware=%5Ex86_64%24&show_platform_hardware=show&text_os_name=%5ELinux%24&show_os_name=show&text_mpi_name=%5Eompi-nightly-v5.0.x%24&show_mpi_name=show&text_mpi_version=%5Ev5.0.x-202303080242-c5fe4aa%24&show_mpi_version=show&text_suite_name=all&show_suite_name=show&text_test_name=allreduce_in_place&show_test_name=hide&text_np=all&show_np=show&text_full_command=&show_full_command=show&text_http_username=%5Eamazon%24&show_http_username=show&text_local_username=all&show_local_username=hide&text_platform_name=%5Eaws-amazonlinux-slurm-efa-installer%24&show_platform_name=show&click=Detail&phase=test_run&test_result=_run_f&text_compute_cluster_id=&text_os_version=&show_os_version=&text_platform_type=&show_platform_type=&text_submit_id=&text_hostname=&show_hostname=&text_mpi_get_id=&text_mpi_install_compiler_id=&text_mpi_install_configure_id=&text_mpi_install_id=&text_compiler_name=&show_compiler_name=&text_compiler_version=&show_compiler_version=&text_vpath_mode=&show_vpath_mode=&text_endian=&show_endian=&text_bitness=&show_bitness=&text_configure_arguments=&text_exit_value=&show_exit_value=&text_exit_signal=&show_exit_signal=&text_duration=&show_duration=&text_client_serial=&show_client_serial=&text_result_message=&text_result_stdout=&text_result_stderr=&text_environment=&text_description=&text_test_build_id=&text_test_build_compiler_id=&text_test_run_id=&text_test_name_id=&text_test_run_command_id=&text_test_suite_id=&text_performance_id=&text_launcher=&show_launcher=&text_resource_mgr=&show_resource_mgr=&text_network=&show_network=&text_parameters=&show_parameters=&lastgo=summary)

**Comment by wzamazon** [comment]
From code inspection, it is because `coll_han_allreduce` did not handle the case that sendbuf is MPI_IN_PLACE

as in the following code:

https://github.com/open-mpi/ompi/blob/cc9883dac1bdee99d9b5b4d6cf35177b028bb35e/ompi/mca/coll/han/coll_han_allreduce.c#L265

`mca_coll_han_allreduce_t1_task` keep increasing `sbuf` even if it is MPI_IN_PLACE

**Comment by bosilca** [comment]
I'm diggin around that code path right now. I'll take a look.

**Comment by a-szegel** [comment]
https://github.com/open-mpi/ompi/issues/11480

opened a clone of this issue:

**Comment by wzamazon** [comment]
Opened PR https://github.com/open-mpi/ompi/pull/11488 as a fix

**Comment by wzamazon** [comment]
PR was merged. opened https://github.com/open-mpi/ompi/pull/11523 to backport
