### ISSUE TITLE
mlx5 atomics not supported

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#1148]
mlx5 HCAs return their atomic results in network byte order. Because of this Mellanox disables atomics when using OFA verbs. It is possible to re-enable the atomics if Mellanox verbs extensions are in use.

#1147 makes the necessary changes. It will enable atomics on mlx5 if the verbs extensions are detected and will disable atomic support otherwise.

@hppritcha Will have the 2.0.0 PR open once this passes the Mellanox smoke-test. I am making this a blocker since the atomics detection gets the wrong result without #1147.

**Comment by hppritcha** [comment]
@hjelmn  can this be closed now that open-mpi/ompi-release#783 has been merged?

**Comment by hjelmn** [comment]
yup
