### ISSUE TITLE
Mapping/binding regression with PBS from 5.0.0rc9 to 5.0.0rc10

### ISSUE THREAD

**Issue by albandil** [open-mpi/ompi#11503]
I struggle with launching simple parallel jobs under PBS 19.0.0 on Debian 11 after upgrade to Open MPI 5.0.0rc10, even though 5.0.0rc9 seemed to worked according to (my) expectations. I build the software from the official prerelease source tarballs like this:
```
$ ../configure --prefix=$HOME/software/bullseye/openmpi-5.0.0rc9 --with-pbs --with-tm=$HOME/software/pbspro-19.0.0
$ ../configure --prefix=$HOME/software/bullseye/openmpi-5.0.0rc10 --with-pbs --with-tm=$HOME/software/pbspro-19.0.0
```
Then I launch an interactive PBS session
```
$ qsub -I -l select=1:ncpus=64:mpiprocs=8:ompthreads=8:mem=64gb:cluster=luna
```
to get a dual-socket AMD EPYC 7513 node. I first start with the older release candidate. With 5.0.0rc9, a program executed via `mpiexec` correctly uses 8 processes, albeit not bound to anything:
```
$ ~/software/bullseye/openmpi-5.0.0rc9/bin/mpiexec --display allocation,map true

======================   ALLOCATED NODES   ======================
    luna202: slots=8 max_slots=0 slots_inuse=0 state=UP
        Flags: DAEMON_LAUNCHED:LOCATION_VERIFIED:SLOTS_GIVEN
        aliases: luna202.fzu.cz,luna202
=================================================================

========================   JOB MAP   ========================
Data for JOB prterun-luna202-959280@1 offset 0 Total slots allocated 8
    Mapping policy: BYCORE:NOOVERSUBSCRIBE  Ranking policy: SLOT Binding policy: NONE
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE


Data for node: luna202  Num slots: 8    Max slots: 0    Num procs: 8
        Process jobid: prterun-luna202-959280@1 App: 0 Process rank: 0 Bound: N/A
        Process jobid: prterun-luna202-959280@1 App: 0 Process rank: 1 Bound: N/A
        Process jobid: prterun-luna202-959280@1 App: 0 Process rank: 2 Bound: N/A
        Process jobid: prterun-luna202-959280@1 App: 0 Process rank: 3 Bound: N/A
        Process jobid: prterun-luna202-959280@1 App: 0 Process rank: 4 Bound: N/A
        Process jobid: prterun-luna202-959280@1 App: 0 Process rank: 5 Bound: N/A
        Process jobid: prterun-luna202-959280@1 App: 0 Process rank: 6 Bound: N/A
        Process jobid: prterun-luna202-959280@1 App: 0 Process rank: 7 Bound: N/A

=============================================================
```
With addition of `-n 8 --map-by :hwtcpus:pe=8` I used to be able to also get the binding working
```
$ ~/software/bullseye/openmpi-5.0.0rc9/bin/mpiexec -n 8 --map-by :hwtcpus:pe=8 --display allocation,map true

======================   ALLOCATED NODES   ======================
    luna202: slots=64 max_slots=0 slots_inuse=0 state=UP
        Flags: DAEMON_LAUNCHED:LOCATION_VERIFIED:SLOTS_GIVEN
        aliases: luna202.fzu.cz,luna202
=================================================================

========================   JOB MAP   ========================
Data for JOB prterun-luna202-970446@1 offset 0 Total slots allocated 64
    Mapping policy: BYSLOT:NOOVERSUBSCRIBE  Ranking policy: SLOT Binding policy: HWTHREAD:IF-SUPPORTED
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: 8  Cpu Type: HWT


Data for node: luna202  Num slots: 64   Max slots: 0    Num procs: 8
        Process jobid: prterun-luna202-970446@1 App: 0 Process rank: 0 Bound: package[0][hwt:0-7]
        Process jobid: prterun-luna202-970446@1 App: 0 Process rank: 1 Bound: package[0][hwt:8-15]
        Process jobid: prterun-luna202-970446@1 App: 0 Process rank: 2 Bound: package[0][hwt:16-23]
        Process jobid: prterun-luna202-970446@1 App: 0 Process rank: 3 Bound: package[0][hwt:24-31]
        Process jobid: prterun-luna202-970446@1 App: 0 Process rank: 4 Bound: package[1][hwt:32-39]
        Process jobid: prterun-luna202-970446@1 App: 0 Process rank: 5 Bound: package[1][hwt:40-47]
        Process jobid: prterun-luna202-970446@1 App: 0 Process rank: 6 Bound: package[1][hwt:48-55]
        Process jobid: prterun-luna202-970446@1 App: 0 Process rank: 7 Bound: package[1][hwt:56-63]

=============================================================
```
However, neither the plain command, nor any other attempts with further explicit directives seem to work with 5.0.0rc10 anymore and I get an error:
```
$ ~/software/bullseye/openmpi-5.0.0rc10/bin/mpiexec --display allocation,map true

======================   ALLOCATED NODES   ======================
    luna202: slots=8 max_slots=0 slots_inuse=0 state=UP
        Flags: DAEMON_LAUNCHED:LOCATION_VERIFIED:SLOTS_GIVEN
        aliases: luna202.fzu.cz,luna202
=================================================================
--------------------------------------------------------------------------
A request was made to bind to that would result in binding more
processes than cpus available in your allocation:

   Application:     hostname
   #processes:      8
   Binding policy:  CORE

You can override this protection by adding the "overload-allowed"
option to your binding directive.
--------------------------------------------------------------------------
```
**Is it because the node has been set up in a wrong way in PBS all the time and 5.0.0rc9 and earlier worked only by accident, or is this an actual regression in Open MPI 5.0.0rc10?**

When I am not within a PBS job, but still on the same node, Open MPI is perfectly flexible, e.g.,
```
$ ~/software/bullseye/openmpi-5.0.0rc10/bin/mpiexec -n 8 --map-by l3cache:pe=8 --display allocation,map true

======================   ALLOCATED NODES   ======================
    luna202: slots=64 max_slots=0 slots_inuse=0 state=UP
        Flags: DAEMON_LAUNCHED:LOCATION_VERIFIED:SLOTS_GIVEN
        aliases: luna202.fzu.cz,luna202
=================================================================

========================   JOB MAP   ========================
Data for JOB prterun-luna202-969785@1 offset 0 Total slots allocated 64
    Mapping policy: BYL3CACHE:NOOVERSUBSCRIBE  Ranking policy: FILL Binding policy: CORE:IF-SUPPORTED
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: 8  Cpu Type: CORE


Data for node: luna202  Num slots: 64   Max slots: 0    Num procs: 8
        Process jobid: prterun-luna202-969785@1 App: 0 Process rank: 0 Bound: package[0][core:0-7]
        Process jobid: prterun-luna202-969785@1 App: 0 Process rank: 1 Bound: package[0][core:8-15]
        Process jobid: prterun-luna202-969785@1 App: 0 Process rank: 2 Bound: package[0][core:16-23]
        Process jobid: prterun-luna202-969785@1 App: 0 Process rank: 3 Bound: package[0][core:24-31]
        Process jobid: prterun-luna202-969785@1 App: 0 Process rank: 4 Bound: package[1][core:32-39]
        Process jobid: prterun-luna202-969785@1 App: 0 Process rank: 5 Bound: package[1][core:40-47]
        Process jobid: prterun-luna202-969785@1 App: 0 Process rank: 6 Bound: package[1][core:48-55]
        Process jobid: prterun-luna202-969785@1 App: 0 Process rank: 7 Bound: package[1][core:56-63]

=============================================================
```

Attached is the output from lstopo when running under PBS: [lscpu+lstopo.txt](https://github.com/open-mpi/ompi/files/11011326/lscpu%2Blstopo.txt) [lstopo.xml.txt](https://github.com/open-mpi/ompi/files/11011328/lstopo.xml.txt).

Interestingly, the output is different when I log into the node outside of a PBS session, which might be related to the issue: [lscpu+lstopo.noPBS.txt](https://github.com/open-mpi/ompi/files/11011331/lscpu%2Blstopo.noPBS.txt) [lstopo.xml.noPBS.txt](https://github.com/open-mpi/ompi/files/11011334/lstopo.xml.noPBS.txt)

Additional information:

 - still the case in version 5.0.0rc11

**Comment by awlauria** [comment]
Some fixes have gone into prrte since rc11 that looks like it might be related - might be worth trying with our next rc12, or the head of the v5.0.x branch.

**Comment by albandil** [comment]
Still the same, both with the head of `v5.0.x` (bff342ce21900509e761b0429c4327c6da2dc4e1) as well as with the current `main` (42e577f1d7e39207359146594b37264a5a7a5709). Here is a compact summary of several my tests:

|                      | 5.0.0rc9     | v5.0.x                                     | main                                       |
| --- | --- | --- | --- |
| no explicit bind/map | OK, but unbound | fail, "...would result in binding more..." | fail, "...would result in binding more..." |
| `--bind-to hwthread --map-by numa:hwtcpus:pe=8 -n 8` | OK, bound to hwt:0-7 etc | OK, bound to hwt:0-7 etc | OK, bound to hwt:0-7 etc |
| `--bind-to hwthread --map-by :hwtcpus:pe=8 -n 8` | OK, bound to hwt:0-7 etc | fail, "...would...bound to...more than one package..." | fail, "...would...bound to...more than one package..." |
| `--bind-to hwthread --map-by hwthread:hwtcpus:pe=8 -n 8` | segmentation fault | fail, "...map to an object level...less cpus...requested" | fail, "...map to an object level...less cpus...requested" |

**Comment by rhc54** [comment]
This looks familiar - didn't we have this exact same issue opened a while ago, and found that the problem was the way the PBS allocation was being requested? Something like it resulted in a topology that lacked what the user expected, and now that we actually account at the cpu level, the topology won't support these directives.

**Comment by albandil** [comment]
> ... a topology that lacked what the user expected ...

I think this is a good description. This PBS seems to be set up in such a way that it simply hides half of the hardware threads. The default mapping/binding approach of Open MPI 5.0.0rc10+ then struggles. However, since it is still possible to force user expectations manually (e.g. by `-n 16 --map-by package:hwtcpus:pe=8 --bind-to hwthread`), I think this issue can be closed.
