### ISSUE TITLE
OMPI 5.0.x issues running with applications compiled against ompi 4.1.x

### ISSUE THREAD

**Issue by wckzhang** [open-mpi/ompi#11509]
When I attempted to run (after disabling psec munge and gds shmem components), I encountered an issue in which the test reported:

```
[ec2-user@ip-10-0-0-64 ~]$ ~/install/bin/mpirun -np 2 -N 2  ~/osu4/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency
This test requires exactly two processes
This test requires exactly two processes
```
I have seen this issue before and it had to do with a topology issue I believe. I assume there's a similar topology issue going on. Putting this here for now until I know what the issue is exactly

**Comment by hppritcha** [comment]
Is the mpirun from OMPI 5 or from OMPI 4.1.x?

**Comment by jsquyres** [comment]
Can you try this with an MPI application that prints its COMM_WORLD rank and size?

It might be useful to ensure that when running with both the old OMPI and new OMPI that both processes think that they have a COMM_WORLD size of 2 and that they have a unique rank.  If they both think that COMM_WORLD is of size 1, that might imply that there's some runtime data transfer not occurring correctly between old OMPI and new OMPI.

**Comment by wckzhang** [comment]
The mpirun is from OMPI 5, let me modify the code to print out comm worlds

**Comment by wckzhang** [comment]
```
[ec2-user@c5n-dy-c5n18xlarge-1 osu-micro-benchmarks-5.6.2]$ ~/install/bin/mpirun -np 2 -N 1  --hostfile ~/hostfile  ~/osu4/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency
Warning: Permanently added 'c5n-dy-c5n18xlarge-2,10.0.24.164' (ECDSA) to the list of known hosts.
This test requires exactly two processes
Rank: 0, Comm size world: 1
This test requires exactly two processes
Rank: 0, Comm size world: 1
--------------------------------------------------------------------------
prterun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [prterun-c5n-dy-c5n18xlarge-1-12429@1,0]
  Exit code:    1
--------------------------------------------------------------------------
[ec2-user@c5n-dy-c5n18xlarge-1 osu-micro-benchmarks-5.6.2]$ /opt/amazon/openmpi/bin/mpirun -np 2 -N 1  --hostfile ~/hostfile  ~/osu4/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency
Warning: Permanently added 'c5n-dy-c5n18xlarge-2,10.0.24.164' (ECDSA) to the list of known hosts.
Rank: 1, Comm size world: 2
Rank: 0, Comm size world: 2
```
The first run is using OMPI 5 mpirun, the second is 4.1.x. Definitely looks to be a problem.

**Comment by wckzhang** [comment]
Ran the problematic job with rmaps verbosity:
```
[c5n-dy-c5n18xlarge-1:12902] AVAILABLE NODES FOR MAPPING:
[c5n-dy-c5n18xlarge-1:12902]     node: c5n-dy-c5n18xlarge-1 daemon: 0 slots_available: 36
[c5n-dy-c5n18xlarge-1:12902] mca:rmaps:rr:byobj mapping by Core for job prterun-c5n-dy-c5n18xlarge-1-12902@1 slots 36 num_procs 2
[c5n-dy-c5n18xlarge-1:12902] mca:rmaps:rr: found 36 Core objects on node c5n-dy-c5n18xlarge-1
[c5n-dy-c5n18xlarge-1:12902] mca:rmaps:rr: assigning proc to object 0
[c5n-dy-c5n18xlarge-1:12902] [prterun-c5n-dy-c5n18xlarge-1-12902@0,0] get_avail_ncpus: node c5n-dy-c5n18xlarge-1 has 0 procs on it
[c5n-dy-c5n18xlarge-1:12902] mca:rmaps: compute bindings for job prterun-c5n-dy-c5n18xlarge-1-12902@1 with policy CORE:IF-SUPPORTED[1007]
[c5n-dy-c5n18xlarge-1:12902] mca:rmaps: bind [prterun-c5n-dy-c5n18xlarge-1-12902@1,INVALID] with policy CORE:IF-SUPPORTED
[c5n-dy-c5n18xlarge-1:12902] [prterun-c5n-dy-c5n18xlarge-1-12902@0,0] BOUND PROC [prterun-c5n-dy-c5n18xlarge-1-12902@1,INVALID][c5n-dy-c5n18xlarge-1] TO package[0][core:0]
[c5n-dy-c5n18xlarge-1:12902] mca:rmaps:rr: assigning proc to object 1
[c5n-dy-c5n18xlarge-1:12902] [prterun-c5n-dy-c5n18xlarge-1-12902@0,0] get_avail_ncpus: node c5n-dy-c5n18xlarge-1 has 1 procs on it
[c5n-dy-c5n18xlarge-1:12902] mca:rmaps: compute bindings for job prterun-c5n-dy-c5n18xlarge-1-12902@1 with policy CORE:IF-SUPPORTED[1007]
[c5n-dy-c5n18xlarge-1:12902] mca:rmaps: bind [prterun-c5n-dy-c5n18xlarge-1-12902@1,INVALID] with policy CORE:IF-SUPPORTED
[c5n-dy-c5n18xlarge-1:12902] [prterun-c5n-dy-c5n18xlarge-1-12902@0,0] BOUND PROC [prterun-c5n-dy-c5n18xlarge-1-12902@1,INVALID][c5n-dy-c5n18xlarge-1] TO package[0][core:1]
```

**Comment by jsquyres** [comment]
Just to be 100% sure: when you run, you are 100% sure that the `mpirun` and run-time libraries are from the Open MPI install that you are testing, right?  I.e., there's no accidental cross-pollination of the Open MPI v4.x and Open MPI v5.x installs, right?

**Comment by wckzhang** [comment]
There shouldn't be an interaction between the 4.1.x and 5.0.x installs, they are in completely separate repos (The 4.1.x is the built-in installation for our latest installer while the 5.0.x was built manually)

**Comment by jsquyres** [comment]
> There shouldn't be an interaction between the 4.1.x and 5.0.x installs, they are in completely separate directories (The 4.1.x is the built-in installation for our latest installer while the 5.0.x was built manually)

Understood.  Have you updated your `PATH` and `LD_LIBRARY_PATH`, and ensured that when you run `ldd` on `mpirun` and the MPI executable, that only the shared libraries from the target Open MPI install are being used?

When I test ABI stuff, I usually like to do something like this:

1. Install Open MPI v4.x into `/tmp/directory-to-test`
2. Build MPI apps with that install
3. Run the MPI apps to make sure they work
4. `rm -rf /tmp/directory-to-test`
5. Install Open MPI v5.x into the same `/tmp/directory-to-test`
6. Re-run the MPI apps (without recompiling them) to make sure they work

That way, there's only a single Open MPI install at any given time, and you're guaranteed not to accidentally mix-n-match stuff between the two OMPI versions.

That being said, having two different OMPI versions installed on the same machine simultaneously should also work (and should also be tested), but it's trickier to ensure that you have all the `PATH` and `LD_LIBRARY_PATH` stuff is set properly.

**Comment by rhc54** [comment]
> Ran the problematic job with rmaps verbosity:
> 
> ```
> [c5n-dy-c5n18xlarge-1:12902] AVAILABLE NODES FOR MAPPING:
> [c5n-dy-c5n18xlarge-1:12902]     node: c5n-dy-c5n18xlarge-1 daemon: 0 slots_available: 36
> [c5n-dy-c5n18xlarge-1:12902] mca:rmaps:rr:byobj mapping by Core for job prterun-c5n-dy-c5n18xlarge-1-12902@1 slots 36 num_procs 2
> [c5n-dy-c5n18xlarge-1:12902] mca:rmaps:rr: found 36 Core objects on node c5n-dy-c5n18xlarge-1
> [c5n-dy-c5n18xlarge-1:12902] mca:rmaps:rr: assigning proc to object 0
> [c5n-dy-c5n18xlarge-1:12902] [prterun-c5n-dy-c5n18xlarge-1-12902@0,0] get_avail_ncpus: node c5n-dy-c5n18xlarge-1 has 0 procs on it
> [c5n-dy-c5n18xlarge-1:12902] mca:rmaps: compute bindings for job prterun-c5n-dy-c5n18xlarge-1-12902@1 with policy CORE:IF-SUPPORTED[1007]
> [c5n-dy-c5n18xlarge-1:12902] mca:rmaps: bind [prterun-c5n-dy-c5n18xlarge-1-12902@1,INVALID] with policy CORE:IF-SUPPORTED
> [c5n-dy-c5n18xlarge-1:12902] [prterun-c5n-dy-c5n18xlarge-1-12902@0,0] BOUND PROC [prterun-c5n-dy-c5n18xlarge-1-12902@1,INVALID][c5n-dy-c5n18xlarge-1] TO package[0][core:0]
> [c5n-dy-c5n18xlarge-1:12902] mca:rmaps:rr: assigning proc to object 1
> [c5n-dy-c5n18xlarge-1:12902] [prterun-c5n-dy-c5n18xlarge-1-12902@0,0] get_avail_ncpus: node c5n-dy-c5n18xlarge-1 has 1 procs on it
> [c5n-dy-c5n18xlarge-1:12902] mca:rmaps: compute bindings for job prterun-c5n-dy-c5n18xlarge-1-12902@1 with policy CORE:IF-SUPPORTED[1007]
> [c5n-dy-c5n18xlarge-1:12902] mca:rmaps: bind [prterun-c5n-dy-c5n18xlarge-1-12902@1,INVALID] with policy CORE:IF-SUPPORTED
> [c5n-dy-c5n18xlarge-1:12902] [prterun-c5n-dy-c5n18xlarge-1-12902@0,0] BOUND PROC [prterun-c5n-dy-c5n18xlarge-1-12902@1,INVALID][c5n-dy-c5n18xlarge-1] TO package[0][core:1]
> ```

FWIW: that looks correct.

**Comment by wckzhang** [comment]
I think this may be another SO versioning issue:
libmpi.so.0.0.0 <-- my 5.0.x installation version is 0.0.0
I also just realized that my 5.0.x installation is built off of main, not 5.0.x, let me recompile

**Comment by wckzhang** [comment]
Ok yeah this issue seems to be because OMPI Main versioning was reset to 0.0.0:
```
[ec2-user@c5n-dy-c5n18xlarge-1 ~]$ ~/50install/bin/mpirun -np 2 ~/osu4/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency
# OSU MPI Latency Test v5.6.2
# Size          Latency (us)
0                       1.46
1                       1.41
2                       1.39
4                       1.37
8                       1.38
16                      1.39
32                      1.38
64                      1.45
128                     1.47
256                     1.51
512                     1.54
1024                    1.73
2048                    1.98
4096                    2.85
8192                    5.17
16384                   6.58
32768                   8.92
65536                  14.97
131072                 27.02
262144                 51.10
524288                100.01
1048576               204.86
2097152               416.34
4194304               875.26
```
Did not have an issue running with it after I rebuilt
