### ISSUE TITLE
Open MPI failed to TCP connect to a peer MPI process when the data scale is increased.

### ISSUE THREAD

**Issue by Fragile-azalea** [open-mpi/ompi#11508]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
v.4.0.7
### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
```
tar -xvzf openmpi-4.0.7.tar.gz openmpi-4.0.7/
./configure  --prefix=/home/pxl/openmpi
make && make install
````
### Please describe the system on which you are running

* Operating system/version: Linux ubuntu 4.15.0-186-generic 216-Ubuntu SMP Wed Jul 1 05:34:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Computer hardware: Qemu-Kvm
* Network type: libvirt

-----------------------------

## Details of the problem

I want to simulate 16 machines with a 2d-torus network, so I start 16 virtual machines and 32 virtual gateways by Qemu-Kvm. I use zebra and ospfd to route.
I test my virtual connection with ring_c code. It works well.
Then I test my virtual connection with allreduce code.
 
<details>
<summary>Here is my allreduce code</summary>

```
#include "mpi.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char *argv[]) {
    int rank, size, next, prev, message, tag = 201;

    /* Start up MPI */

    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    char *length_str = getenv("LENGTH");
    int   length_len = strlen(length_str);
    int   length     = 0;
    for (int i = 0; i < length_len; ++i) {
        length = length * 10 + length_str[i] - 48;
    }
    printf("%d", length);
    int *send_buffer = (int *)malloc(length * sizeof(int));
    int *recv_buffer = (int *)malloc(length * sizeof(int));

    MPI_Allreduce(send_buffer, recv_buffer, length, MPI_INT, MPI_SUM,
                  MPI_COMM_WORLD);

    MPI_Finalize();
    free(send_buffer);
    free(recv_buffer);
    printf("ok");
    return 0;
}

```

</details>

Here is my command line:

```
mpirun --prefix /home/pxl/openmpi --allow-run-as-root --mca oob_tcp_if_include ens17,ens18,ens19,ens20 --mca btl_tcp_if_include ens17,ens18,ens19,ens20 -np 16 -H 192.168.100.100:1,192.168.101.101:1,192.168.102.102:1,192.168.103.103:1,192.168.104.104:1,192.168.105.105:1,192.168.106.106:1,192.168.107.107:1,192.168.108.108:1,192.168.109.109:1,192.168.110.110:1,192.168.111.111:1,192.168.162.112:1,192.168.163.113:1,192.168.164.114:1,192.168.115.115:1 -bind-to none -map-by slot --mca orte_base_help_aggregate 0 --mca btl_base_verbose 100 -x LD_LIBRARY_PATH -x PATH -x LENGTH=256000 /home/pxl/openmpi-4.0.7/examples/allreduce.o
```

It seems to work well until now.

Then I scale up length to 512000.

To my surprise, it raises many problems:
```
--------------------------------------------------------------------------
WARNING: Open MPI failed to TCP connect to a peer MPI process.  This
should not happen.

Your Open MPI job may now hang or fail.

  Local host: xinglin-g0
  PID:        1915
  Message:    connect() to 192.168.110.111:1024 failed
  Error:      Operation now in progress (115)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: Open MPI failed to TCP connect to a peer MPI process.  This
should not happen.

Your Open MPI job may now hang or fail.

  Local host: gpu15
  PID:        1523
  Message:    connect() to 192.168.214.114:1024 failed
  Error:      Operation now in progress (115)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: Open MPI failed to TCP connect to a peer MPI process.  This
should not happen.

Your Open MPI job may now hang or fail.

  Local host: gpu15
  PID:        1523
  Message:    connect() to 192.168.100.100:1024 failed
  Error:      Transport endpoint is not connected (107)
--------------------------------------------------------------------------
```
I feel very confused about it and would greatly appreciate some help from experts in the field.

<details>
<summary>Here is 2d-torus diagram</summary>

![图片1](https://user-images.githubusercontent.com/17422499/226366624-fd90e075-ffc8-4c62-baf0-1bc9c313b9ee.png)
</details>

**Comment by bosilca** [comment]
These messages indicate some connectivity issues between your VMs. If you get the same message (aka. connectivity issues between the same instances) then you should manually check their connectivity (with ssh from one instance to another as an example). If the peers with connectivity issues change between calls it could indicate a deeper issue, in which case you might want to increase the connect/accept timeout and/or the number of retries.

**Comment by Fragile-azalea** [comment]
I get the same message when I try again.
For g15-192.168.100.100, I try to check it by following methods:
1. ssh 192.168.100.100  It works well.
2. traceroute 192.168.100.100
Here is my log:
```
traceroute to 192.168.100.100 (192.168.100.100), 30 hops max, 60 byte packets
 1  192.168.215.103 (192.168.215.103)  0.410 ms  0.363 ms  0.319 ms
 2  192.168.100.100 (192.168.100.100)  0.583 ms  0.598 ms  0.557 ms
``` 

3. nc -l -v -n -p 1234 and  nc 192.168.100.100 1234
Here is my log:

```
Listening on [0.0.0.0] (family 0, port 1234)
Connection from 192.168.215.115 58390 received!
``` 

Do you know if I use the right way to check their connectivity?

**Comment by bosilca** [comment]
This is the right way. It appears the problem is not the connectivity but how it is handled either by the OS or by OMPI. I looked at the code and I don't understand how this error happen. Some of the error messages are talking about error 115 which is EINPROGRESS (the connect is not yet completed). But right before we print the error message we filter for EINPROGRESS, because that is not technically an error, it simply indicates the connection was not yet completed.

How many of these virtual instances are running on the same physical node ?

**Comment by Fragile-azalea** [comment]
All 16 virtual instances are running on the same physical node.

**Comment by bosilca** [comment]
would it be possible that your node is overwhelmed, triggering timeouts during the connections wave ? What if you reduce the number of instances to 8 ? Are you still seeing these connection issues ?

**Comment by Fragile-azalea** [comment]
I reduced the number of instances to 9, creating a 3*3 2D-torus network. This configuration allows me to scale the data length up to the memory limit without experiencing any connection problems.

**Comment by bosilca** [comment]
ok, so we were able to pinpoint the source of the problem, timeouts outside OMPI control. I am not familiar with the configuration of virtual machines, but I would suggest you increase the number of retries and the connection timeout on your virtual machines.

**Comment by Fragile-azalea** [comment]
I will close this issue because it is not a problem caused by OMPI. I will update this issue once I succeed in running the allreduce with a 4x4 2D-torus network. Thank you for your quick and helpful answer!
