### ISSUE TITLE
[5.0.x] MTT receiving bad answers (data corruption) for allgather/scatter gap collectives (only with han enabled)

### ISSUE THREAD

**Issue by wckzhang** [open-mpi/ompi#11510]
This is my minimum reproducer.
```
[ec2-user@c5n-dy-c5n18xlarge-1 ~]$ mpirun --np 4 -N 2 --hostfile ~/hostfile ~/ompi-tests/ibm/collective/allgather_gap
Warning: Permanently added 'c5n-dy-c5n18xlarge-2,10.0.26.144' (ECDSA) to the list of known hosts.
[**ERROR**]: MPI_COMM_WORLD rank 1, file allgather_gap.c:84:
bad answer (0) at index 1 of 4 (should be 1)
[**ERROR**]: MPI_COMM_WORLD rank 3, file allgather_gap.c:84:
bad answer (0) at index 1 of 4 (should be 1)
```

I will try to trace the error down.

**Comment by wckzhang** [comment]
Note, I don't hit this issue when I specify --mca coll ^han. So maybe @bosilca may know what's going on

**Comment by janjust** [comment]
@bosilca @devreal Could either of you look into this issue?

**Comment by wckzhang** [comment]
I've been looking at it but my progress has been limited. I found this bad answer to happen with ```--mca coll basic,libnbc``` as well as default behavior. Haven't figured out if this is an issue with han or with its lower level modules since they use basic + libnbc as well.

**Comment by wckzhang** [comment]
I suspect this issue may be caused by the CM PML or MTL dropping the offset somewhere. Since the run with --mca coll basic,libnbc fails with --mca pml cm and passes with --mca pml ob1.

The libnbc + basic run does a simple gather then broadcast, so far I've traced the data in gather seems to be appropriate set, haven't finished checking the broadcast data.

**Comment by wckzhang** [comment]
So from what I can tell, it looks like mca_pml_cm_isend looks incorrect since it never uses the convertor.

**Comment by wckzhang** [comment]
Found the issue, this is the same offset bug that was happening in mca_pml_send, creating PR now

**Comment by wckzhang** [comment]
See - https://github.com/open-mpi/ompi/pull/11528

**Comment by wckzhang** [comment]
I'm guessing that with --mca coll ^han this issue didn't show up because it hit a happy path using blocking sends instead of nonblocking sends.

**Comment by awlauria** [comment]
main: #11528
v5.0.x: #11530

PR's merged - closing. Thanks!
