### ISSUE TITLE
MPI_Testsome returning `MPI_UNDEFINED` not documented

### ISSUE THREAD

**Issue by eschnett** [open-mpi/ompi#1152]
I am using OpenMPI 1.10.1 on OS X, installed via Macports. The man page of `MPI_Waitsome` documents that `outcount` can be `MPI_UNDEFINED`, but the man page of `MPI_Testsome` does not document this.

**Comment by bosilca** [comment]
This issue has been addressed by @jsquyres in 11c571b5.
