### ISSUE TITLE
Framework: psec warning

### ISSUE THREAD

**Issue by ahkumar** [open-mpi/ompi#11557]
Dear all,  

Setup: 
I ran into the below warnings on an install, where I have slurm compiled against both pmix v3.2.2 & v4.2.3. 
I am using: OpenMPI: 4.1.4 & slurm 22.05.08; 

Issue: I don't see this warning if I chose to use --mpi=pmix_v3. 

Question: 

a) Any idea why do I see this?
b) Wondering if there is a way I can silence this warning?

Thank you!!

`# srun --mpi=pmix_v4 -n1 ./mpi_hello.slurm
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
PMIx stopped checking at the first component that it did not find.

Host:      c001
Framework: psec
Component: munge
--------------------------------------------------------------------------

--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
PMIx stopped checking at the first component that it did not find.

Host:      c001
Framework: psec
Component: munge
--------------------------------------------------------------------------

Hello world from processor c001, rank 0 out of 1 processors`

**Comment by rhc54** [comment]
Slurm normally requires the `munge` library to make the client-server connections. In this case, Slurm and PMIx saw the `munge` library when built, but the library appears to be missing from the compute nodes where your process is running. You can tell PMIx to ignore that component by adding `PMIX_MCA_psec=^munge` to your environment.

**Comment by ahkumar** [comment]
@rhc54 Perfect, that works. thank you so much!!
