### ISSUE TITLE
Authorization required, but no authorization protocol specified

### ISSUE THREAD

**Issue by heroyang6263** [open-mpi/ompi#11553]
When I run the example cpi `mpirun -np 2 ./cpi`, the teminal print:
`Authorization required, but no authorization protocol specified`
`Authorization required, but no authorization protocol specified`
`Process 0 of 2 is on manager`
`Process 1 of 2 is on manager`
`pi is approximately 3.1415926544231318, Error is 0.0000000008333387`
`wall clock time = 0.000045`

What is the reason?

**Comment by bosilca** [comment]
Are you running things as root instead of a normal user ?

**Comment by heroyang6263** [comment]
> Are you running things as root instead of a normal user ?

No, I running things as normal user, and this user is newly created by me.

**Comment by ggouaillardet** [comment]
can you try

```
export HWLOC_PLUGINS_BLACKLIST="gl,nvml"
```
before invoking `mpirun` ?

**Comment by heroyang6263** [comment]
> can you try
> 
> ```
> export HWLOC_PLUGINS_BLACKLIST="gl,nvml"
> ```
> 
> before invoking `mpirun` ?

It still doesn't work

**Comment by himmelmaus** [comment]
Hi, I am encountering the same issue with mpirun version 4.1.2 on Ubuntu 22.04.3 LTS, definitely not logged in as root - I was wondering if a fix had been found?

**Comment by rhc54** [comment]
The problem lies in your X11 server and has nothing to do with OMPI - see https://unix.stackexchange.com/questions/209746/how-to-resolve-no-protocol-specified-for-su-user/417233#417233 for suggested solutions.

**Comment by joaander** [comment]
The problem may also lie in hwloc's gl component. See #7701, specifically https://github.com/open-mpi/ompi/issues/7701#issuecomment-932587086.

**Comment by ThatIsMyUsername** [comment]
> 当我运行示例 cpi 时`mpirun -np 2 ./cpi`，终端打印： `Authorization required, but no authorization protocol specified` `Authorization required, but no authorization protocol specified` `Process 0 of 2 is on manager` `Process 1 of 2 is on manager` `pi is approximately 3.1415926544231318, Error is 0.0000000008333387` `wall clock time = 0.000045`
> 
> 原因何在？

Hello, have you solved this problem? How was it resolved? thank you.

**Comment by vanishingideal** [comment]
> > 当我运行示例 cpi 时`mpirun -np 2 ./cpi`，终端打印： `Authorization required, but no authorization protocol specified` `Authorization required, but no authorization protocol specified` `Process 0 of 2 is on manager` `Process 1 of 2 is on manager` `pi is approximately 3.1415926544231318, Error is 0.0000000008333387` `wall clock time = 0.000045`
> > 原因何在？
> 
> Hello, have you solved this problem? How was it resolved? thank you.

Have you tried creating a persistent `~/.Xauthority` if one isn't present? You can do something like:

```
export XAUTHORITY=$HOME/.config/x11/xauthority
xauth generate :0 . trusted
```
