### ISSUE TITLE
404 error for link to release notes on download webpage for 5.0 series

### ISSUE THREAD

**Issue by BenWibking** [open-mpi/ompi#11572]
## Background information

N/A

-----------------------------

## Details of the problem

On the download page for 5.0 releases (https://www.open-mpi.org/software/ompi/v5.0/), the link to the release notes / NEWS file leads to a 404 error:

```
<a href="https://github.com/open-mpi/ompi/raw/v5.0.x/NEWS">This file</a> contains a list of changes between the releases in the Open MPI in the v5.0 series.
```

This link is broken: https://github.com/open-mpi/ompi/raw/v5.0.x/NEWS

**Comment by jsquyres** [comment]
Thanks @BenWibking!  Fixed in https://github.com/open-mpi/ompi-www/pull/447.
