### ISSUE TITLE
incorrect results with pml ucx using Intel compiler - patch included

### ISSUE THREAD

**Issue by QuesarVII** [open-mpi/ompi#11583]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
4.1.5

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
From source, tested both manual and rpm build.
Issue occurs with new Intel icx / icpx compilers, or with -xHost on an EPYC CPU with the older icc / icpc compilers.

### Please describe the system on which you are running

* Operating system/version: Rocky 9
* Computer hardware: Ice lake Xeon
* Network type:   Mellanox 25G ethernet, ConnectX 5

-----------------------------

## Details of the problem

A basic cpi test program is giving very incorrect results from OpenMPI 4.1.5 when built with the new Intel icx / icpc compilers:

mpirun -np 3 --machinefile /etc/nodes --map-by node ./cpi-ompi-icx
Process 0 of 3 on head
Process 1 of 3 on node1
Process 2 of 3 on node2
pi is approximately 12724618342851800481927554599091198382907596267512571318150207784014489777680827923043313851491993216935585702327599004511234715064043132103988701805113029085079382905059122903542421635729424889862590766352365068224106548558034894848.0000000000000000, Error is 12724618342851800481927554599091198382907596267512571318150207784014489777680827923043313851491993216935585702327599004511234715064043132103988701805113029085079382905059122903542421635729424889862590766352365068224106548558034894848.0000000000000000
wall clock time = 0.010114

Running with "--mca pml ^ucx" gives correct results.  We encountered this same issue previously under a very specific use case, that being an EPYC CPU and compiling with icc (classic compiler, did not try icx at that time) with the "-xHost" optimization flag.

Changing the line:
pml_datatype->size_shift = (int)(log(size) / log(2.0)); /* log2(size) */
in ompi/mca/pml/ucx/pml_ucx_datatype.c to use log2(size) instead of log(size) / log(2.0) resolves the issue for both problems.  

I'm including a patch that resolves the behavior in both cases.  This seems like it might be a compiler bug, but I'm not sure.  The patch to OpenMPI resolves the issue regardless, and is only applied if the Intel compilers are detected.

Thanks,
Rick Warner

**Comment by QuesarVII** [comment]
[openmpi-4--icc-xHost--and-icx-fix-log-to-log2.txt](https://github.com/open-mpi/ompi/files/11203864/openmpi-4--icc-xHost--and-icx-fix-log-to-log2.txt)

**Comment by devreal** [comment]
Wow. I wonder why we don't use `log2(size)` everywhere?

**Comment by QuesarVII** [comment]
I was unsure as well.  That's why I only changed it with ifdefs to only mod it for use with the Intel compiler. I'm guessing log(size) / log(2.0) is somehow more efficient when it works.

**Comment by QuesarVII** [comment]
I tested the new patch you made successfully.  Thanks!
