### ISSUE TITLE
Failure in MPI launch depending on machine ordering in hostfile with OpenMPI 5.0.x

### ISSUE THREAD

**Issue by amadhuka1** [open-mpi/ompi#11619]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v5.0.0rc9

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Installed from source tarball

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

N/A

### Please describe the system on which you are running

* Operating system/version: Ubuntu 20.04
* Computer hardware: Intel Xeon Platinum 8260 CPU; Intel Xeon Gold 6342 CPU
* Network type: TCP

-----------------------------

## Details of the problem

I am running a problem across 3 machines in a cluster (named `aa, bb, cc`) using a persistent prte DVM and am experiencing inconsistent behavior based on the ordering of hosts in the DVM hostfile. 

For background, all machines share the same operating system and network configuration. The nodes `aa` and `cc` have very similar machine configurations, both running the Intel Xeon Gold 6342 CPU while the node `bb` has a Intel Xeon Platinum 8260 CPU.

\
I am first launching the persistent prte DVM using the command:
```
$ prte --hostfile dvmHostfile.txt --report-uri dvmURI.txt
```
where the hostfile  `dvmHostfile.txt` has the following contents:
```
aa slots=10
bb slots=10
cc slots=10
```
\
I then use the following mpirun command with the `--rankfile` option to ensure 1 rank is launched per node in the above hostfile:
```
$ mpirun --dvm=file:dvmURI.txt --mca btl self,vader,tcp --display MAP-DEVEL --map-by rankfile:file=myRankFile.txt -np 3 my_app
```
where the simplified rankfile `myRankFile.txt` has the following contents:
```
rank 0=aa slot=0
rank 1=bb slot=0
rank 2=cc slot=0
```

\
The job fails to start with the following error message:
```
--------------------------------------------------------------------------
The rankfile that was used claimed that a host was either not
allocated or oversubscribed its slots.  Please review your rank-slot
assignments and your host allocation to ensure a proper match.  Also,
some systems may require using full hostnames, such as
"host1.example.com" (instead of just plain "host1").

  Host: bb
--------------------------------------------------------------------------
```

\
However, if I simply re-order the hosts in the `dvmHostfile.txt` as follows, the job launches and runs correctly:
```
aa slots=10
cc slots=10
bb slots=10
```

\
The pertinent debug logs using the parameters `PRTE_MCA_rmaps_base_verbose=10` and `PRTE_MCA_plm_base_verbose=10` produce the following for the incorrect hostfile:
<pre>
[prte-aa-1123352@0,0] plm:base:orted_report_launch from daemon [prte-aa-1123352@0,2]
[prte-aa-1123352@0,0] plm:base:orted_report_launch from daemon [prte-aa-1123352@0,2] on node cc
[aa:1123352] ALIASES FOR NODE cc (cc)
[aa:1123352]  ALIAS: xx.x.xx.xxx
[prte-aa-1123352@0,0] RECEIVED TOPOLOGY SIG 2N:2S:2L3:48L2:48L1:48C:96H:0-95::x86_64:le FROM NODE cc
[prte-aa-1123352@0,0] TOPOLOGY SIGNATURE ALREADY RECORDED IN POSN 0
[prte-aa-1123352@0,0] plm:base:orted_report_launch completed for daemon [prte-aa-1123352@0,2] at contact prte-aa-1123352@0.0;tcp://xx.x.xx.xxx:xxxxx:xx
[prte-aa-1123352@0,0] plm:base:orted_report_launch job prte-aa-1123352@0 recvd 2 of 3 reported daemons
[prte-aa-1123352@0,0] plm:base:orted_report_launch from daemon [prte-aa-1123352@0,1]
[prte-aa-1123352@0,0] plm:base:orted_report_launch from daemon [prte-aa-1123352@0,1] on node bb
[aa:1123352] ALIASES FOR NODE bb (bb)
[aa:1123352]  ALIAS: xx.x.xx.xxx
[prte-aa-1123352@0,0] RECEIVED TOPOLOGY SIG 4N:2S:2L3:48L2:48L1:48C:48H:0-47::x86_64:le FROM NODE bb
[prte-aa-1123352@0,0] NEW TOPOLOGY - ADDING SIGNATURE
[prte-aa-1123352@0,0] plm:base:orted_report_launch completed for daemon [prte-aa-1123352@0,1] at contact prte-aa-1123352@0.0;tcp://xx.x.xx.xxx:xxxxx:xx
[prte-aa-1123352@0,0] plm:base:orted_report_launch job prte-aa-1123352@0 recvd 3 of 3 reported daemons
DVM ready

.
. 
* after running the mpirun command*
.
.

[aa:1123352] mca:rmaps: mapping job prte-aa-1123352@1
[aa:1123352] mca:rmaps: setting mapping policies for job prte-aa-1123352@1 inherit TRUE hwtcpus FALSE
[aa:1123352] mca:rmaps:ppr: job prte-aa-1123352@1 not using ppr mapper PPR NULL policy PPR NOTSET
[aa:1123352] [prte-aa-1123352@0,0] rmaps:seq called on job prte-aa-1123352@1
[aa:1123352] mca:rmaps:seq: job prte-aa-1123352@1 not using seq mapper
[aa:1123352] mca:rmaps:rr: job prte-aa-1123352@1 not using rr mapper
[aa:1123352] mca:rmaps:rank_file: mapping job prte-aa-1123352@1
[aa:1123352] [prte-aa-1123352@0,0] using known nodes
[aa:1123352] [prte-aa-1123352@0,0] Starting with 3 nodes in list
[aa:1123352] [prte-aa-1123352@0,0] Filtering thru apps
[aa:1123352] [prte-aa-1123352@0,0] Retained 3 nodes in list
[aa:1123352] [prte-aa-1123352@0,0] node aa has 10 slots available
<b>[aa:1123352] [prte-aa-1123352@0,0] node bb lacks topology</b>
[aa:1123352] [prte-aa-1123352@0,0] node cc has 10 slots available
[aa:1123352] AVAILABLE NODES FOR MAPPING:
[aa:1123352]     node: aa daemon: 0 slots_available: 10
[aa:1123352]     node: cc daemon: 2 slots_available: 10
[aa:1123352] [prte-aa-1123352@0,0] get_avail_ncpus: node aa has 0 procs on it
[aa:1123352] mca:rmaps: compute bindings for job prte-aa-1123352@1 with policy NONE[1]
[aa:1123352] [prte-aa-1123352@0,0] logging info
[aa:1123352] [prte-aa-1123352@0,0] plm:base:orted_cmd sending kill_local_procs cmds
[aa:1123352] [prte-aa-1123352@0,0] PRTE Notification received from [prte-aa-1123352@0,0]
[aa:1123352] [prte-aa-1123352@0,0] NOTIFYING PMIX SERVER OF STATUS JOB ENDED SOURCE prte-aa-1123352@1 RANGE AVAIL TO PROCESSES IN SAME ALLOCATION ONLY
</pre>
I noticed that the topology for node `bb` is missing when mpirun attempts to map to it. 

\
Similarly, the corresponding debug log for the corrected hostfile is as follows:
<pre>
[aa:1131984] [prte-aa-1131984@0,0] plm:base:orted_report_launch from daemon [prte-aa-1131984@0,1]
[aa:1131984] [prte-aa-1131984@0,0] plm:base:orted_report_launch from daemon [prte-aa-1131984@0,1] on node cc
[aa:1131984] ALIASES FOR NODE cc (cc)
[aa:1131984]  ALIAS: xx.x.xx.xxx
[aa:1131984] [prte-aa-1131984@0,0] RECEIVED TOPOLOGY SIG 2N:2S:2L3:48L2:48L1:48C:96H:0-95::x86_64:le FROM NODE cc
[aa:1131984] [prte-aa-1131984@0,0] TOPOLOGY SIGNATURE ALREADY RECORDED IN POSN 0
[aa:1131984] [prte-aa-1131984@0,0] plm:base:orted_report_launch completed for daemon [prte-aa-1131984@0,1] at contact prte-aa-1131984@0.0;tcp://xx.x.xx.xxx:xxxxx:xx
[aa:1131984] [prte-aa-1131984@0,0] plm:base:orted_report_launch job prte-aa-1131984@0 recvd 2 of 3 reported daemons
[aa:1131984] [prte-aa-1131984@0,0] plm:base:orted_report_launch from daemon [prte-aa-1131984@0,2]
[aa:1131984] [prte-aa-1131984@0,0] plm:base:orted_report_launch from daemon [prte-aa-1131984@0,2] on node bb
[aa:1131984] ALIASES FOR NODE bb (bb)
[aa:1131984]  ALIAS: xx.x.xx.xxx
[aa:1131984] [prte-aa-1131984@0,0] RECEIVED TOPOLOGY SIG 4N:2S:2L3:48L2:48L1:48C:48H:0-47::x86_64:le FROM NODE bb
[aa:1131984] [prte-aa-1131984@0,0] NEW TOPOLOGY - ADDING SIGNATURE
[aa:1131984] [prte-aa-1131984@0,0] REQUESTING TOPOLOGY FROM [prte-aa-1131984@0,2] FOR SIG 4N:2S:2L3:48L2:48L1:48C:48H:0-47::x86_64:le
[aa:1131984] [prte-aa-1131984@0,0] plm:base:daemon_topology recvd for daemon [prte-aa-1131984@0,2]
[aa:1131984] [prte-aa-1131984@0,0] plm:base:orted:report_topo launch completed for daemon [prte-aa-1131984@0,2]
[aa:1131984] [prte-aa-1131984@0,0] plm:base:orted_report_launch recvd 3 of 3 reported daemons
DVM ready

.
. 
* after running the mpirun command*
.
.

[aa:1131984] mca:rmaps: mapping job prte-aa-1131984@1
[aa:1131984] mca:rmaps: setting mapping policies for job prte-aa-1131984@1 inherit TRUE hwtcpus FALSE
[aa:1131984] mca:rmaps:ppr: job prte-aa-1131984@1 not using ppr mapper PPR NULL policy PPR NOTSET
[aa:1131984] [prte-aa-1131984@0,0] rmaps:seq called on job prte-aa-1131984@1
[aa:1131984] mca:rmaps:seq: job prte-aa-1131984@1 not using seq mapper
[aa:1131984] mca:rmaps:rr: job prte-aa-1131984@1 not using rr mapper
[aa:1131984] mca:rmaps:rank_file: mapping job prte-aa-1131984@1
[aa:1131984] [prte-aa-1131984@0,0] using known nodes
[aa:1131984] [prte-aa-1131984@0,0] Starting with 3 nodes in list
[aa:1131984] [prte-aa-1131984@0,0] Filtering thru apps
[aa:1131984] [prte-aa-1131984@0,0] Retained 3 nodes in list
[aa:1131984] [prte-aa-1131984@0,0] node aa has 10 slots available
[aa:1131984] [prte-aa-1131984@0,0] node cc has 10 slots available
[aa:1131984] [prte-aa-1131984@0,0] node bb has 10 slots available
[aa:1131984] AVAILABLE NODES FOR MAPPING:
[aa:1131984]     node: aa daemon: 0 slots_available: 10
[aa:1131984]     node: cc daemon: 1 slots_available: 10
[aa:1131984]     node: bb daemon: 2 slots_available: 10
.
.
.
</pre>

\
After some investigation, it appears that if the machine `bb` (which has a different configuration than `aa` and `cc`) appears as the second machine in the hosfile, the error is present. Looking at the file `3rd-party/prrte/src/mca/plm/base/plm_base_launch_support.c` here: 
https://github.com/openpmix/prrte/blob/aa498b9b410445aac83b4fefbab4fd981f989b79/src/mca/plm/base/plm_base_launch_support.c#L1730
I notice that there is special handling for the daemon rank=1. The request for the topology from the remote daemon is skipped when rank=1. Instead, according to this: 
https://github.com/openpmix/prrte/blob/aa498b9b410445aac83b4fefbab4fd981f989b79/src/mca/plm/base/plm_base_launch_support.c#L1469
we always receive the topology from the rank 1 daemon so there is no need to explicitly request it. In that if-statement even though we unpack the topology information - unless I am mistaken - I don't see where we set the rank 1 daemon topology to the received topology. If I manually set the rank 1 daemon topology, then both rankfiles produce working results. Does this have something to do with the issue I am experiencing?

\
Please let me know if there is more information I can provide. Thanks!

**Comment by rhc54** [comment]
Sounds like you are using the `prte` from inside the OMPI code, yes? I have no idea what state that code is in as the v5.0 release branch often trails development by quite a bit. I would suggest installing PRRTE master from the git project repo instead and see if the problem persists. I suspect this was fixed long ago.

**Comment by awlauria** [comment]
The current v5 branch is near the head of prrte/pmix v3.0. 

Would you be able to try the latest v5.0.x branch to see if it still happens? rc9 is a bit old (Oct 2022)
