### ISSUE TITLE
Behavior of MPI_COMM_DISCONNECT with inactive persistent request handles

### ISSUE THREAD

**Issue by raffenet** [open-mpi/ompi#11644]
## Background information

We had a lengthy discussion about how MPI_COMM_DISCONNECT should behave during the MPI Forum meeting today. Specifically, what MPI should do if there are outstanding inactive persistent request handles associated with a communicator which is passed to MPI_COMM_DISCONNECT. I wrote a test program to confirm my suspicion that it would hang with MPICH, since the references to the communicator held by the persistent requests would not be freed. Some in the Forum suggested this was a bug in MPICH, but I am not yet convinced.

When I built the program using Open MPI, it did not hang. My question is - is that expected?

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.1.4

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Built from tarball.

### Please describe the system on which you are running

* Operating system/version: macOS 12.6.4
* Computer hardware: Apple M1 Pro
* Network type: n/a

-----------------------------

## Details of the problem

Not only does MPI_COMM_DISCONNECT not hang when there are outstanding persistent request handles, I found that they are still usable after disconnect. See test program and output:

```c
#include <stdlib.h>
#include <stdio.h>
#include <mpi.h>

int main(void) {
    MPI_Init(NULL, NULL);

    MPI_Comm comm;
    MPI_Comm_dup(MPI_COMM_SELF, &comm);

    int a=42, b=0;
    MPI_Request requests[2];
    MPI_Send_init(&a, 1, MPI_INT, 0, 0, comm, &requests[0]);
    MPI_Recv_init(&b, 1, MPI_INT, 0, 0, comm, &requests[1]);

    MPI_Comm_disconnect(&comm);

    MPI_Startall(2, requests);
    MPI_Waitall(2, requests, MPI_STATUSES_IGNORE);

    printf("b = %d\n", b);

    MPI_Finalize();
    return 0;
}
```
```sh
raffenet@glitch:~/ $ ./a.out
b = 42
```

**Comment by raffenet** [comment]
That is the behavior I would expect from MPI_COMM_FREE. However, the spec says that MPI_COMM_DISCONNECT
```
...waits for all pending communication on comm to complete internally,
deallocates the communicator object, and sets the handle to MPI_COMM_NULL. It is a
collective operation.
```
Do you think the program should also hang with Open MPI then?

Ultimately, I think the question from the Forum discussion is - are inactive persistent requests "pending communication"? If so, MPI cannot really wait for them to complete, since they are inactive. Some asserted that MPI should actually free those requests during MPI_COMM_DISCONNECT, but I am skeptical of this view.

**Comment by bosilca** [comment]
Our implementation does everything described in the standard, but the internal communicator still has 2 pending refcounts, and the user still has two, assumingly valid, requests handle that she can use later on. Thus, the implementation cannot release the requests internal resources, and this includes the refcounts to the communicator.

The best we can do is to mark the communicator as user freed, and prevent future start on the persistent requests, but this does not solve the root problem nor provide a way to dissociate the requests from the communicator to be disconnected. I join you on the skeptical side, MPI implementations shall not be required to keep track of dependencies between different MPI objects, this will lead to non-scalable software.

**Comment by raffenet** [comment]
I would quibble that not deallocating the internal communicator before returning from MPI_COMM_DISCONNECT might be violating the spec as written. But we are finding that the spec as written has multiple interpretations 😄. I do agree that keeping additional comm->request associations so MPI_COMM_DISCONNECT can free the inactive ones is undesirable. I'll post this issue to the MPI Forum Slack so others can chime in.

**Comment by raffenet** [comment]
Related MPI Forum issue: https://github.com/mpi-forum/mpi-issues/issues/676

**Comment by raffenet** [comment]
Upon further thought, until there is consensus about the spec, I don't think we need to have implementation-level issues. We can hash it out in those other threads for now. Thanks for the responses @bosilca.
