### ISSUE TITLE
PRTE has lost communication with a remote daemon. caused by plm_ssh_module.c(316) updating exit status to 213

### ISSUE THREAD

**Issue by tom8382** [open-mpi/ompi#11663]
[root@controller ompi-5.0.x]#
[root@controller ompi-5.0.x]#
[root@controller ompi-5.0.x]# mpirun -v --allow-run-as-root -np 4 --mca plm_base_verbose 10 --prefix /home/wzhl/ompi_workspace -host 10.233.165.100 --mca routed binomial --debug-daemons -mca btl_tcp_if_include en_i350_1  hostname
[controller:72192] mca: base: component_find: searching NULL for plm components
[controller:72192] mca: base: find_dyn_components: checking NULL for plm components
[controller:72192] pmix:mca: base: components_register: registering framework plm components
[controller:72192] pmix:mca: base: components_register: found loaded component slurm
[controller:72192] pmix:mca: base: components_register: component slurm register function successful
[controller:72192] pmix:mca: base: components_register: found loaded component ssh
[controller:72192] pmix:mca: base: components_register: component ssh register function successful
[controller:72192] mca: base: components_open: opening plm components
[controller:72192] mca: base: components_open: found loaded component slurm
[controller:72192] mca: base: components_open: component slurm open function successful
[controller:72192] mca: base: components_open: found loaded component ssh
[controller:72192] mca: base: components_open: component ssh open function successful
[controller:72192] mca:base:select: Auto-selecting plm components
[controller:72192] mca:base:select:(  plm) Querying component [slurm]
[controller:72192] mca:base:select:(  plm) Querying component [ssh]
[controller:72192] [[INVALID],0] plm:ssh_lookup on agent ssh : rsh path NULL
[controller:72192] mca:base:select:(  plm) Query of component [ssh] set priority to 10
[controller:72192] mca:base:select:(  plm) Selected component [ssh]
[controller:72192] mca: base: close: component slurm closed
[controller:72192] mca: base: close: unloading component slurm
[controller:72192] [prterun-controller-72192@0,0] plm:ssh_setup on agent ssh : rsh path NULL
[controller:72192] [prterun-controller-72192@0,0] plm:base:receive start comm
[controller:72192] [prterun-controller-72192@0,0] plm:base:setup_vm
[controller:72192] [prterun-controller-72192@0,0] plm:base:setup_vm creating map
[controller:72192] [prterun-controller-72192@0,0] setup:vm: working unmanaged allocation
[controller:72192] [prterun-controller-72192@0,0] using dash_host
[controller:72192] [prterun-controller-72192@0,0] checking node 10.233.165.100
[controller:72192] [prterun-controller-72192@0,0] plm:base:setup_vm add new daemon [prterun-controller-72192@0,1]
[controller:72192] [prterun-controller-72192@0,0] plm:base:setup_vm assigning new daemon [prterun-controller-72192@0,1] to node 10.233.165.100
[controller:72192] [prterun-controller-72192@0,0] plm:ssh: launching vm
[controller:72192] [prterun-controller-72192@0,0] plm:ssh: local shell: 0 (bash)
[controller:72192] [prterun-controller-72192@0,0] plm:ssh: assuming same remote shell as local shell
[controller:72192] [prterun-controller-72192@0,0] plm:ssh: remote shell: 0 (bash)
[controller:72192] [prterun-controller-72192@0,0] plm:ssh: final template argv:
        /usr/bin/ssh <template> PRTE_PREFIX=/home/wzhl/ompi_workspace;export PRTE_PREFIX;LD_LIBRARY_PATH=/home/wzhl/ompi_workspace/lib:/home/wzhl/ompi_workspace/lib:$LD_LIBRARY_PATH;export LD_LIBRARY_PATH;DYLD_LIBRARY_PATH=/home/wzhl/ompi_workspace/lib:/home/wzhl/ompi_workspace/lib:$DYLD_LIBRARY_PATH;export DYLD_LIBRARY_PATH;/home/wzhl/ompi_workspace/bin/prted --debug-daemons --allow-run-as-root --prtemca ess "env" --prtemca ess_base_nspace "prterun-controller-72192@0" --prtemca ess_base_vpid "<template>" --prtemca ess_base_num_procs "2" --prtemca prte_hnp_uri "prterun-controller-72192@0.0;tcp://10.233.165.127,192.168.2.1:59019:24,24" --prtemca plm_base_verbose "10" --prtemca routed "binomial" --prtemca pmix_session_server "1" --prtemca plm "ssh" --tree-spawn --prtemca prte_parent_uri "prterun-controller-72192@0.0;tcp://10.233.165.127,192.168.2.1:59019:24,24"
[controller:72192] [prterun-controller-72192@0,0] plm:ssh:launch daemon 0 not a child of mine
[controller:72192] [prterun-controller-72192@0,0] plm:ssh: adding node 10.233.165.100 to launch list
[controller:72192] [prterun-controller-72192@0,0] plm:ssh: activating launch event
[controller:72192] [prterun-controller-72192@0,0] plm:ssh: recording launch of daemon [prterun-controller-72192@0,1]
[controller:72192] [prterun-controller-72192@0,0] plm:ssh: executing: (/usr/bin/ssh) [/usr/bin/ssh 10.233.165.100 PRTE_PREFIX=/home/wzhl/ompi_workspace;export PRTE_PREFIX;LD_LIBRARY_PATH=/home/wzhl/ompi_workspace/lib:/home/wzhl/ompi_workspace/lib:$LD_LIBRARY_PATH;export LD_LIBRARY_PATH;DYLD_LIBRARY_PATH=/home/wzhl/ompi_workspace/lib:/home/wzhl/ompi_workspace/lib:$DYLD_LIBRARY_PATH;export DYLD_LIBRARY_PATH;/home/wzhl/ompi_workspace/bin/prted --debug-daemons --allow-run-as-root --prtemca ess "env" --prtemca ess_base_nspace "prterun-controller-72192@0" --prtemca ess_base_vpid 1 --prtemca ess_base_num_procs "2" --prtemca prte_hnp_uri "prterun-controller-72192@0.0;tcp://10.233.165.127,192.168.2.1:59019:24,24" --prtemca plm_base_verbose "10" --prtemca routed "binomial" --prtemca pmix_session_server "1" --prtemca plm "ssh" --tree-spawn --prtemca prte_parent_uri "prterun-controller-72192@0.0;tcp://10.233.165.127,192.168.2.1:59019:24,24"]
--------------------------------------------------------------------------
An unrecognized option was included on the prted command line:

  Option: --allow-run-as-root

Please use the "prted --help" command to obtain a list of all
supported options.
--------------------------------------------------------------------------
[controller:72192] [prterun-controller-72192@0,0] daemon 1 failed with status 213
[controller:72192] [prterun-controller-72192@0,0]:../../../../../../../3rd-party/prrte/src/mca/plm/ssh/plm_ssh_module.c(316) updating exit status to 213
[controller:72192] [prterun-controller-72192@0,0] plm:base:receive stop comm
[controller:72192] mca: base: close: component ssh closed
[controller:72192] mca: base: close: unloading component ssh
--------------------------------------------------------------------------
PRTE has lost communication with a remote daemon.

  HNP daemon   : [prterun-controller-72192@0,0] on node controller
  Remote daemon: [prterun-controller-72192@0,1] on node 10.233.165.100

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
[root@controller ompi-5.0.x]#

**Comment by tom8382** [comment]
hi, i have got a ssh fail here, i can do "ssh remotehost hostname" success. but cannot do mpirun. anybody can give me some suggestion?

**Comment by tom8382** [comment]
after change user root to a none-root user, i get some new error! It shows that has already launch to remotehost, but has this error
**"
PMIX ERROR: UNPACK-PAST-END in file ../../../../../3rd-party/prrte/src/util/nidmap.c at line 233
[xcr1.lns.cw.net:906647] PRTE ERROR: Authentication failed in file ../../../../../../3rd-party/prrte/src/tools/prted/prted.c at line 941
"**


all log here:
[wangzhonglei@controller ompi-5.0.x]$ mpirun -np 4 --mca plm_base_verbose 10 -host 10.233.165.100 --debug-daemons hostname
[controller:225428] mca: base: component_find: searching NULL for plm components
[controller:225428] mca: base: find_dyn_components: checking NULL for plm components
[controller:225428] pmix:mca: base: components_register: registering framework plm components
[controller:225428] pmix:mca: base: components_register: found loaded component slurm
[controller:225428] pmix:mca: base: components_register: component slurm register function successful
[controller:225428] pmix:mca: base: components_register: found loaded component ssh
[controller:225428] pmix:mca: base: components_register: component ssh register function successful
[controller:225428] mca: base: components_open: opening plm components
[controller:225428] mca: base: components_open: found loaded component slurm
[controller:225428] mca: base: components_open: component slurm open function successful
[controller:225428] mca: base: components_open: found loaded component ssh
[controller:225428] mca: base: components_open: component ssh open function successful
[controller:225428] mca:base:select: Auto-selecting plm components
[controller:225428] mca:base:select:(  plm) Querying component [slurm]
[controller:225428] mca:base:select:(  plm) Querying component [ssh]
[controller:225428] [[INVALID],0] plm:ssh_lookup on agent ssh : rsh path NULL
[controller:225428] mca:base:select:(  plm) Query of component [ssh] set priority to 10
[controller:225428] mca:base:select:(  plm) Selected component [ssh]
[controller:225428] mca: base: close: component slurm closed
[controller:225428] mca: base: close: unloading component slurm
[controller:225428] [prterun-controller-225428@0,0] plm:ssh_setup on agent ssh : rsh path NULL
[controller:225428] [prterun-controller-225428@0,0] plm:base:receive start comm
[controller:225428] [prterun-controller-225428@0,0] plm:base:setup_vm
[controller:225428] [prterun-controller-225428@0,0] plm:base:setup_vm creating map
[controller:225428] [prterun-controller-225428@0,0] setup:vm: working unmanaged allocation
[controller:225428] [prterun-controller-225428@0,0] using dash_host
[controller:225428] [prterun-controller-225428@0,0] checking node 10.233.165.100
[controller:225428] [prterun-controller-225428@0,0] plm:base:setup_vm add new daemon [prterun-controller-225428@0,1]
[controller:225428] [prterun-controller-225428@0,0] plm:base:setup_vm assigning new daemon [prterun-controller-225428@0,1] to node 10.233.165.100
[controller:225428] [prterun-controller-225428@0,0] plm:ssh: launching vm
[controller:225428] [prterun-controller-225428@0,0] plm:ssh: local shell: 0 (bash)
[controller:225428] [prterun-controller-225428@0,0] plm:ssh: assuming same remote shell as local shell
[controller:225428] [prterun-controller-225428@0,0] plm:ssh: remote shell: 0 (bash)
[controller:225428] [prterun-controller-225428@0,0] plm:ssh: final template argv:
        /usr/bin/ssh <template> PRTE_PREFIX=/home/wzhl/ompi_workspace;export PRTE_PREFIX;LD_LIBRARY_PATH=/home/wzhl/ompi_workspace/lib:/home/wzhl/ompi_workspace/lib:$LD_LIBRARY_PATH;export LD_LIBRARY_PATH;DYLD_LIBRARY_PATH=/home/wzhl/ompi_workspace/lib:/home/wzhl/ompi_workspace/lib:$DYLD_LIBRARY_PATH;export DYLD_LIBRARY_PATH;/home/wzhl/ompi_workspace/bin/prted --debug-daemons --prtemca ess "env" --prtemca ess_base_nspace "prterun-controller-225428@0" --prtemca ess_base_vpid "<template>" --prtemca ess_base_num_procs "2" --prtemca prte_hnp_uri "prterun-controller-225428@0.0;tcp://10.233.165.127,192.168.2.1:42105:24,24" --prtemca plm_base_verbose "10" --prtemca pmix_session_server "1" --prtemca plm "ssh" --tree-spawn --prtemca prte_parent_uri "prterun-controller-225428@0.0;tcp://10.233.165.127,192.168.2.1:42105:24,24"
[controller:225428] [prterun-controller-225428@0,0] plm:ssh:launch daemon 0 not a child of mine
[controller:225428] [prterun-controller-225428@0,0] plm:ssh: adding node 10.233.165.100 to launch list
[controller:225428] [prterun-controller-225428@0,0] plm:ssh: activating launch event
[controller:225428] [prterun-controller-225428@0,0] plm:ssh: recording launch of daemon [prterun-controller-225428@0,1]
[controller:225428] [prterun-controller-225428@0,0] plm:ssh: executing: (/usr/bin/ssh) [/usr/bin/ssh 10.233.165.100 PRTE_PREFIX=/home/wzhl/ompi_workspace;export PRTE_PREFIX;LD_LIBRARY_PATH=/home/wzhl/ompi_workspace/lib:/home/wzhl/ompi_workspace/lib:$LD_LIBRARY_PATH;export LD_LIBRARY_PATH;DYLD_LIBRARY_PATH=/home/wzhl/ompi_workspace/lib:/home/wzhl/ompi_workspace/lib:$DYLD_LIBRARY_PATH;export DYLD_LIBRARY_PATH;/home/wzhl/ompi_workspace/bin/prted --debug-daemons --prtemca ess "env" --prtemca ess_base_nspace "prterun-controller-225428@0" --prtemca ess_base_vpid 1 --prtemca ess_base_num_procs "2" --prtemca prte_hnp_uri "prterun-controller-225428@0.0;tcp://10.233.165.127,192.168.2.1:42105:24,24" --prtemca plm_base_verbose "10" --prtemca pmix_session_server "1" --prtemca plm "ssh" --tree-spawn --prtemca prte_parent_uri "prterun-controller-225428@0.0;tcp://10.233.165.127,192.168.2.1:42105:24,24"]
Daemon was launched on xcr1 - beginning to initialize
[xcr1.lns.cw.net:906647] mca: base: component_find: searching NULL for plm components
[xcr1.lns.cw.net:906647] mca: base: find_dyn_components: checking NULL for plm components
[xcr1.lns.cw.net:906647] pmix:mca: base: components_register: registering framework plm components
[xcr1.lns.cw.net:906647] pmix:mca: base: components_register: found loaded component ssh
[xcr1.lns.cw.net:906647] pmix:mca: base: components_register: component ssh register function successful
[xcr1.lns.cw.net:906647] mca: base: components_open: opening plm components
[xcr1.lns.cw.net:906647] mca: base: components_open: found loaded component ssh
[xcr1.lns.cw.net:906647] mca: base: components_open: component ssh open function successful
[xcr1.lns.cw.net:906647] mca:base:select: Auto-selecting plm components
[xcr1.lns.cw.net:906647] mca:base:select:(  plm) Querying component [ssh]
[xcr1.lns.cw.net:906647] [prterun-controller-225428@0,1] plm:ssh_lookup on agent ssh : rsh path NULL
[xcr1.lns.cw.net:906647] mca:base:select:(  plm) Query of component [ssh] set priority to 10
[xcr1.lns.cw.net:906647] mca:base:select:(  plm) Selected component [ssh]
[xcr1.lns.cw.net:906647] [prterun-controller-225428@0,1] plm:ssh_setup on agent ssh : rsh path NULL
[xcr1.lns.cw.net:906647] [prterun-controller-225428@0,1] plm:base:receive start comm
[xcr1.lns.cw.net:906647] PMIX ERROR: UNPACK-PAST-END in file ../../../../../3rd-party/prrte/src/util/nidmap.c at line 233
[xcr1.lns.cw.net:906647] PRTE ERROR: Authentication failed in file ../../../../../../3rd-party/prrte/src/tools/prted/prted.c at line 941
^C[controller:225428] [prterun-controller-225428@0,0]:../../../../../../3rd-party/prrte/src/tools/prte/prte.c(1209) updating exit status to 1
[controller:225428] [prterun-controller-225428@0,0] plm:base:prted_cmd sending prted_exit commands
[controller:225428] [prterun-controller-225428@0,0] prted:comm:process_commands() Processing Command: PRTE_DAEMON_HALT_VM_CMD
[controller:225428] [prterun-controller-225428@0,0] prted_cmd: received halt_vm cmd
[xcr1.lns.cw.net:906647] PMIX ERROR: UNPACK-PAST-END in file ../../../../../../../3rd-party/prrte/src/mca/grpcomm/direct/grpcomm_direct.c at line 509
[xcr1.lns.cw.net:906647] [prterun-controller-225428@0,1] plm:base:receive stop comm
[xcr1.lns.cw.net:906647] mca: base: close: component ssh closed
[xcr1.lns.cw.net:906647] mca: base: close: unloading component ssh
[controller:225428] [prterun-controller-225428@0,0] plm:base:receive stop comm
[controller:225428] mca: base: close: component ssh closed
[controller:225428] mca: base: close: unloading component ssh
[wangzhonglei@controller ompi-5.0.x]$

**Comment by tom8382** [comment]
solved，local mpi is debug mode. remote mpi is release mode.

**Comment by xjgjin** [comment]
Please tell me how to change the remote MPI to release mode. Can you send your parameter configuration?

**Comment by jsquyres** [comment]
@xjgjin If you have a specific question, please open a new issue with all the details requested in the template.  Thanks!
