### ISSUE TITLE
make dist failed in v5.0.0rc11

### ISSUE THREAD

**Issue by artemry-nv** [open-mpi/ompi#11676]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using?
v5.0.0rc11
Not reproducible with v5.0.0rc10

### Describe how Open MPI was installed
./autogen.sh
./configure
make dist

### Please describe the system on which you are running

* Operating system/version: rhel7.2

-----------------------------

## Details of the problem

```
make dist
make -j2  dist-bzip2 dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory `/build-result/src/hpcx-v2.16-gcc-MLNX_OFED_LINUX-5-redhat7-cuda12-gdrcopy2-nccl2.17-x86_64/ompi-775d0aa17bb0ed5b9da2e0a543ebbac819feea52'
/usr/bin/perl "./contrib/dist/make-authors.pl" --skip-ok --quiet --srcdir="."
New AUTHORS file written.
if test -d "openmpi-gitclone"; then find "openmpi-gitclone" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "openmpi-gitclone" || { sleep 5 && rm -rf "openmpi-gitclone"; }; else :; fi
test -d "openmpi-gitclone" || mkdir "openmpi-gitclone"
 (cd config && make -j2  top_distdir=../openmpi-gitclone distdir=../openmpi-gitclone/config \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: warning: -jN forced in submake: disabling jobserver mode.
make[2]: Entering directory `/build-result/src/hpcx-v2.16-gcc-MLNX_OFED_LINUX-5-redhat7-cuda12-gdrcopy2-nccl2.17-x86_64/ompi-775d0aa17bb0ed5b9da2e0a543ebbac819feea52/config'
make -j2  \
  top_distdir="../openmpi-gitclone" distdir="../openmpi-gitclone/config" \
  dist-hook
make[3]: warning: -jN forced in submake: disabling jobserver mode.
make[3]: Entering directory `/build-result/src/hpcx-v2.16-gcc-MLNX_OFED_LINUX-5-redhat7-cuda12-gdrcopy2-nccl2.17-x86_64/ompi-775d0aa17bb0ed5b9da2e0a543ebbac819feea52/config'
#########################################################################
#
# make dist is disabled due to the following packages: ROMIO
#
#########################################################################
make[3]: *** [dist-hook] Error 1
make[3]: Leaving directory `/build-result/src/hpcx-v2.16-gcc-MLNX_OFED_LINUX-5-redhat7-cuda12-gdrcopy2-nccl2.17-x86_64/ompi-775d0aa17bb0ed5b9da2e0a543ebbac819feea52/config'
make[2]: *** [distdir] Error 2
make[2]: Leaving directory `/build-result/src/hpcx-v2.16-gcc-MLNX_OFED_LINUX-5-redhat7-cuda12-gdrcopy2-nccl2.17-x86_64/ompi-775d0aa17bb0ed5b9da2e0a543ebbac819feea52/config'
make[1]: *** [distdir] Error 1
make[1]: Leaving directory `/build-result/src/hpcx-v2.16-gcc-MLNX_OFED_LINUX-5-redhat7-cuda12-gdrcopy2-nccl2.17-x86_64/ompi-775d0aa17bb0ed5b9da2e0a543ebbac819feea52'
make: *** [dist] Error 2
```

**Comment by janjust** [comment]
Just to clarify, this is an internal HPCX build based on v5.0.0.rc11 - just wanted to clarify since hpcx-v2.16 is not publicly available.

**Comment by janjust** [comment]
interestingly for it failed because of a different component:
```
make  \
  top_distdir="../openmpi-gitclone" distdir="../openmpi-gitclone/config" \
  dist-hook
make[5]: Entering directory '/global/scratch/users/tomislavj/ompi-dev/ompi-build-v5.0.x/config'
#########################################################################
#
# make dist is disabled due to the following packages: Sphinx/Documentation
#
#########################################################################
make[5]: *** [Makefile:1520: dist-hook] Error 1
make[5]: Leaving directory '/global/scratch/users/tomislavj/ompi-dev/ompi-build-v5.0.x/config'
make[4]: *** [Makefile:1365: distdir-am] Error 2
make[4]: Leaving directory '/global/scratch/users/tomislavj/ompi-dev/ompi-build-v5.0.x/config'
make[3]: *** [Makefile:1361: distdir] Error 2
make[3]: Leaving directory '/global/scratch/users/tomislavj/ompi-dev/ompi-build-v5.0.x/config'
make[2]: *** [Makefile:1632: distdir-am] Error 1
make[2]: Leaving directory '/global/scratch/users/tomislavj/ompi-dev/ompi-build-v5.0.x'
make[1]: *** [Makefile:1626: distdir] Error 2
make[1]: Leaving directory '/global/scratch/users/tomislavj/ompi-dev/ompi-build-v5.0.x'
make: *** [Makefile:1730: dist] Error 2
```

**Comment by jsquyres** [comment]
Is `./autogen.sh ; ./configure; make dist` from a distribution tarball one of your tests or something?

@artemry-nv For more information on what is failing, you'll need to supply all the information that is asked for in the github issue template (e.g., configure stdout/stderr, config.log, etc.).  Per the message that you showed, ROMIO didn't configure properly, so Open MPI (correctly) didn't let you make a distribution tarball.  ROMIO's `configure` output probably has more detail about why it failed to configure properly (potentially missing header files or something...?).

@janjust Similarly, per the error message you showed, Open MPI (correctly) disallowed you from running `make dist` because Sphinx was unable to be configured properly.  See the docs for how to setup Sphinx -- https://docs.open-mpi.org/en/v5.0.x/developers/sphinx.html.

To be clear: these are specific, intentional decisions: `make dist` will fail if ROMIO or Sphinx are unable to be configured properly, because without both of these components, you cannot make a distribution tarball correctly.

**Comment by janjust** [comment]
@jsquyres yes indeed, after I built sphinx and set the path it built correctly for me.

**Comment by jsquyres** [comment]
@artemry-nv @janjust Should this issue be closed?

**Comment by artemry-nv** [comment]
> @artemry-nv @janjust Should this issue be closed?

Are there any new ROMIO requirements/dependencies introduced in v5.0.0rc11 (since v5.0.0rc10)?

**Comment by jsquyres** [comment]
I don't know offhand.  It would be easiest if you could either examine or post the config.log and configure stdout/stderr, which will show exactly what failed during the ROMIO configuration.

**Comment by janjust** [comment]
@jsquyres I'll keep a track of this, but let us first look into why it failed for @artemry-nv but not me, I'll close it if it's a non-issue (which I suspect)

**Comment by jsquyres** [comment]
Looks like this got fixed.

**Comment by artemry-nv** [comment]
Just for the record, the reason of the failure was missing ROMIO because of:
```
[2024-01-11T04:49:56.475Z] checking stdatomic.h usability... no
[2024-01-11T04:49:56.475Z] checking stdatomic.h presence... no
[2024-01-11T04:49:56.475Z] checking for stdatomic.h... no
[2024-01-11T04:49:56.475Z] configure: WARNING: 3rd party ROMIO cannot be built, disqualifying the io/romio341 component
```
We built on a RHEL7 host where C++11 stdatomic.h is absent due to old GCC by default. 
Everything was built fine on RHEL8 system.
