### ISSUE TITLE
Struggling with install on Ubuntu 18.04

### ISSUE THREAD

**Issue by dovhochsztein** [open-mpi/ompi#11674]
Hi, I am trying to install openMPI and hitting a strange bug I can't diagnose and can't find similar on the forums/FAQ.
I have downloaded the tar ball from [here](https://www.open-mpi.org/software/ompi/v4.1/) (though, for the record, I have tried versions 4.1.5, 4.1.0 and 2.1.1).
I have followed the instructions in the install/readmes:
`tar xf openmpi-4.1.5.tar.gz`
`cd openmpi-4.1.5`
`mkdir build`
`cd build`
`../configure --prefix=/usr/local/openmpi`

And I have gotten a long trace with the bottom showing:
`configure: WARNING: See config.log for details
configure: error: Cannot continue`
attached are the full trace, and the config file:
[openmpi trace.txt](https://github.com/open-mpi/ompi/files/11465256/openmpi.trace.txt)
[config.log](https://github.com/open-mpi/ompi/files/11465249/config.log)

Any ideas?
Thanks

**Comment by edgargabriel** [comment]
The error in configure is due to an issue with your Fortran compiler

```
checking if Fortran compiler supports CHARACTER... yes
checking size of Fortran CHARACTER... configure: WARNING: Could not determine size of CHARACTER
configure: WARNING: See config.log 
```

If you don't really need Fortran for your application, you could add ```--disable-mpi-fortran``` to your configure line
(I am not a Fortran expert, not sure I can provide any help beyond this)

**Comment by dovhochsztein** [comment]
That definitely solved that error, thanks!
