### ISSUE TITLE
5.0.x: broken link in documentation (to mpir-to-pmix-guide)

### ISSUE THREAD

**Issue by tonycurtis** [open-mpi/ompi#11699]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

main @ b22a4debc8eb6088768b6a870150972fc27e50d5

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

N/A

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

N/A

### Please describe the system on which you are running

* Operating system/version: N/A
* Computer hardware: N/A
* Network type: N/A

-----------------------------

## Details of the problem

There's a link to

[https://github.com/openpmix/mpir-to-pmix-guide](https://github.com/openpmix/mpir-to-pmix-guide)

in

[https://github.com/open-mpi/ompi/blob/main/docs/news/news-v5.0.x.rst](https://github.com/open-mpi/ompi/blob/main/docs/news/news-v5.0.x.rst)

but that document isn't there.

**Comment by jsquyres** [comment]
Hey @hppritcha -- I know we moved this guide somewhere, but I don't remember where it got moved to, offhand.

**Comment by hppritcha** [comment]
https://github.com/hpc/mpir-to-pmix-guide

**Comment by jsquyres** [comment]
Fixed in main and v5.0.x branch; closing this issue.
