### ISSUE TITLE
PGI compiler issues

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#117]
Larry Baker posted a bunch of PGI compiler issues:
- http://www.open-mpi.org/community/lists/devel/2010/08/8297.php
- http://www.open-mpi.org/community/lists/devel/2010/08/8298.php
- http://www.open-mpi.org/community/lists/devel/2010/08/8299.php
- http://www.open-mpi.org/community/lists/devel/2010/08/8300.php
- http://www.open-mpi.org/community/lists/devel/2010/08/8301.php

Some of them are Libtool issues, but some of them are OMPI issues.  None appear to be drastic correctness issues (nor are they regressions), so they shouldn't hold up 1.5.0.  But we should fix them nonetheless (and submit upstream to Libtool where appropriate).

**Comment by gpaulsen** [comment]
Closing as "Too Old"
