### ISSUE TITLE
Remove OSHMEM Java bindings

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1170]
Per https://github.com/open-mpi/ompi-release/pull/787, remove the OSHMEM Java bindings (no one appears to be using them, and no one is interested in maintaining them -- case in point: they're already drifting out of sync with the C and Fortran OSHMEM bindings).

@miked-mellanox @igor-ivanov

**Comment by igor-ivanov** [comment]
@jsquyres just to check: remove from master and v2.x?

**Comment by jsquyres** [comment]
@igor-ivanov I think so.  Definitely from v2.x so that no users see them in v2.0.0.  And since no one is interested in them at all, we might as well remove them from master.  Do you agree?

**Comment by igor-ivanov** [comment]
@jsquyres agree, will remove from master and v2.x

**Comment by jsquyres** [comment]
@igor-ivanov Sweet; many thanks.

**Comment by igor-ivanov** [comment]
@jsquyres 
v1.10.x does not have oshmem:JAVA
v2.x https://github.com/open-mpi/ompi-release/pull/787
master: https://github.com/open-mpi/ompi/pull/1176

**Comment by hppritcha** [comment]
This was closed by open-mpi/ompi-release#787.
