### ISSUE TITLE
5.0.x: broken link to ULFM reference (https://github.com/open-mpi/ompi/blob/main/docs/news/news-v5.0.x.rst again)

### ISSUE THREAD

**Issue by tonycurtis** [open-mpi/ompi#11701]
Thank you for taking the time to submit an issue!

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

main @ HEAD

### Please describe the system on which you are running

* Operating system/version:
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem

```
New Features:
ULFM Fault Tolerance support has been added. See [:ref:`the ULFM section <ulfm-label>`](https://github.com/open-mpi/ompi/blob/main/docs/news/news-v5.0.x.rst#id1)
```

link does nothing.

**Comment by jsquyres** [comment]
@tonycurtis I'm looking at https://docs.open-mpi.org/en/v5.0.x/news/news-v5.0.x.html; the link there correctly takes me to https://docs.open-mpi.org/en/v5.0.x/features/ulfm.html#ulfm-label.

Is that link not working for you for some reason?

**Comment by tonycurtis** [comment]
It's pointing to itself (same github page)

**Comment by jsquyres** [comment]
Hmm.  I am not seeing that.  This is the tooltip that appears in my web browser when I hover over that link in  https://docs.open-mpi.org/en/v5.0.x/news/news-v5.0.x.html:

![Screenshot 2023-05-20 at 9 54 12 AM](https://github.com/open-mpi/ompi/assets/617316/6b08c778-1a9b-48bb-81e6-94c094013447)

If I click on it, I am taken to https://docs.open-mpi.org/en/v5.0.x/features/ulfm.html#ulfm-label.

**Comment by tonycurtis** [comment]
If I hover over the link, the destination is exactly the same as in the browser's location bar at the top.  (Tested in brave, safari.)

**Comment by tonycurtis** [comment]
I'm also seeing the markdown in the text (:ref: bit etc)

**Comment by jsquyres** [comment]
Oh, it just clicked: you're viewing these docs on github.com, not on docs.open-mpi.org.

**Short version:** you should be reading these docs on https://docs.open-mpi.org; they're much prettier and better linked over there.  Every time we merge a PR, docs.open-mpi.org is updated (vs. only being updated when we release a new version of Open MPI).  Meaning: docs.open-mpi.org is just as current as the source on github.com.

More detail...

These files are not Markdown -- they are ReStructured Text (RST).  Github *sorta* renders RST correctly, but not entirely.  Case in point: Github is apparently not rendering the `:ref:` RST directive properly.  But if you view that same RST file in docs.open-mpi.org (where it was rendered correctly), the link to the ULFM section works properly.

Check out:

* https://github.com/open-mpi/ompi/blob/main/docs/news/news-v5.0.x.rst (i.e., the GitHub-sorta-rendered RST code)

  vs.
  
* https://docs.open-mpi.org/en/v5.0.x/news/news-v5.0.x.html (the properly rendered RST code)

**Comment by tonycurtis** [comment]
Aaaahhhh.  I'll use the docs content, then.
