### ISSUE TITLE
Add NEWS bullets for v2.0.0

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1172]

**Comment by hppritcha** [comment]
How verbose do we want to be here:

```git shortlog --no-merges v2.x --not v1.10```

returns 6274 lines of output.

**Comment by jsquyres** [comment]
I usually look at the git logs and pull out the user-visible changes.  If the commits are not visible to the user, we don't bother listing them in NEWS.  Admittedly, this is sometimes subjective.
