### ISSUE TITLE
Add docs about mpirun launch vs. direct launch.

### ISSUE THREAD

**Issue by qkoziol** [open-mpi/ompi#11734]
Add docs about mpirun launch vs. direct launch.

**Comment by qkoziol** [comment]
Split out from https://github.com/open-mpi/ompi/issues/10480

**Comment by qkoziol** [comment]
I reworked the "quickstart" info for mpirun, etc. as part of the earlier work to retire the FAQ:  https://docs.open-mpi.org/en/v5.0.x/launching-apps/quickstart.html

I think it addresses this issue adequately, but more input would be welcome. 

 @jsquyres @gpaulsen @awlauria @janjust - I'm inclined to close this as completed.  Any objections?

**Comment by janjust** [comment]
:+1 looks good to me

**Comment by lrbison** [comment]
👍 looks good

**Comment by awlauria** [comment]
Looks great - thanks.
