### ISSUE TITLE
Add a section about debugging and removal of MPIR

### ISSUE THREAD

**Issue by qkoziol** [open-mpi/ompi#11733]
Add a section about debugging and removal of MPIR, yadda yadda yadda (at least some of this can come from the “parallel debugging” FAQ section).

**Comment by qkoziol** [comment]
Split out from https://github.com/open-mpi/ompi/issues/10480

**Comment by qkoziol** [comment]
@jsquyres - I'm assuming that this is in the main Open MPI documentation.  Please add a comment to the issue if you were thinking something else.

**Comment by hppritcha** [comment]
some of the verbiage in the README for https://github.com/hpc/mpir-to-pmix-guide may be helpful

**Comment by gpaulsen** [comment]
I'll take a stab at this tomorrow.

**Comment by qkoziol** [comment]
@gpaulsen - Any update about this?

**Comment by gpaulsen** [comment]
Yes, I'm working on... I'm a bit rusty on building the docs, but hope to PR this afternoon.

**Comment by gpaulsen** [comment]
I reviewed https://docs.open-mpi.org/en/v5.0.x/app-debug/mpir-tools.html# that our IBM contractor Dave Wootton wrote and updated.  It looks very complete.

The links are all good, and have been updated to point to new locations of other documents.  I'm not certain what else can or should be said about MPIR.

Closing and complete.
