### ISSUE TITLE
Rank reorder in MPI_Dist_graph_create

### ISSUE THREAD

**Issue by MarcelKoch** [open-mpi/ompi#11756]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
openMPI v4.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
- system package in openSUSE 15.4
- from source

### Please describe the system on which you are running

* Operating system/version: openSUSE 15.4
* Computer hardware: AMD Ryzen 9 5900x
* Network type: Within one socket

-----------------------------

## Details of the problem

I've created a communicator with a graph topology with the `MPI_Dist_graph_create` function. I've set the `reorder` parameter to `true` and in some cases I can observe that the rank numbering of the new communicator actually differs from the original one. But, in that case, the wrong values are communicated during a `MPI_Ineighbor_alltoallv` call. More specifically, each rank communicates with the wrong neighbors. 

I've tried to debug openMPI a bit, and indeed the all-to-all seems to use the neighbor ranks wrt to the original (not permuted) ordering. It relies on `MPI_Dist_graph_neighbors` which returns the ranks for in- and out-neighbors in terms of the original ordering. But the ranks are not mapped to the permuted ordering before individual send/recv calls are placed. 

Sidenote: IMO the standard is not very clear if the out-parameters of `MPI_Dist_graph_neighbors` use the ranks of the new (possible reordered) communicator, or of the communicator used to create the new one. I would appreciate if anyone has more insight on that.

**Comment by cniethammer** [comment]
Concerning the side note: 

To my understanding the returned rank values in the out-parameters of `MPI_Dist_graph_neighbors` must be ranks of the new (possible reordered) communicator. There is no way to obtain the original communicator from the new communicator - so ranks from the original communicator would be totally useless.
The descriptions of the neighborhood collectives uses `MPI_Dist_graph_neighbors` to clarify their outcome, which should support this (see, e.g., MPI 4.0 p. 419).

However, for me, the text around `MPI_Dist_graph_neighbors` is confusing, too. The output is defined via the creation calls instead of the topology information attached to the communicator. I will check how this can be improved in the MPI Topology chapter and will come up with a suggestion in the WG/Forum.

**Comment by bosilca** [comment]
@cniethammer is correct, users have no access to the parent communicator therefore it makes no sense for `MPI_Dist_graph_neighbors` to return information related to it.

There is a totally valid reason to define the returned values based on the calls and not on the locally provided topology information: the topology information is distributed, which means the locally provided edges and weights is only a part of what will be returned.

Last, but not least, I confirm we have a bug, we do not translate ranks if we reorder the ranks in the new communicators.

**Comment by bosilca** [comment]
@MarcelKoch please try this:
```diff
diff --git a/ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c b/ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
index f96def2ddf..bacda703b6 100644
--- a/ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
+++ b/ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
@@ -956,6 +956,17 @@ int mca_topo_treematch_dist_graph_create(mca_topo_base_module_t* topo_module,
         free(lrank_to_grank);
     } /* distributed reordering end */
 
+    /* Translate the ranks provided by the user to account for the reordered communicator.
+     * Note that this operation is safe to be done in place, directly into the in/out arrays.
+     */
+    ompi_group_translate_ranks(comm_old->c_remote_group, n,
+                               topo->in,
+                               (*newcomm)->c_remote_group,
+                               topo->in);
+    ompi_group_translate_ranks(comm_old->c_remote_group, n,
+                               topo->out,
+                               (*newcomm)->c_remote_group,
+                               topo->out);
   release_and_return:
     if (NULL != reqs ) free(reqs);
     if (NULL != tracker) free(tracker);
```

**Comment by jsquyres** [comment]
@MarcelKoch Did the above patch work for you?

**Comment by MarcelKoch** [comment]
Sorry for the delayed reply. I think the patch has an error and it should be 
```diff
diff --git a/ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c b/ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
index f96def2ddf..bacda703b6 100644
--- a/ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
+++ b/ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
@@ -956,6 +956,17 @@ int mca_topo_treematch_dist_graph_create(mca_topo_base_module_t* topo_module,
         free(lrank_to_grank);
     } /* distributed reordering end */
 
+    /* Translate the ranks provided by the user to account for the reordered communicator.
+     * Note that this operation is safe to be done in place, directly into the in/out arrays.
+     */
+    ompi_group_translate_ranks(comm_old->c_remote_group, topo->indegree,
+                               topo->in,
+                               (*newcomm)->c_remote_group,
+                               topo->in);
+    ompi_group_translate_ranks(comm_old->c_remote_group, topo->outdegree,
+                               topo->out,
+                               (*newcomm)->c_remote_group,
+                               topo->out);
   release_and_return:
     if (NULL != reqs ) free(reqs);
     if (NULL != tracker) free(tracker);
```
In the previous patch, not all new ranks were set correctly, because the size of the in/out array was assumed to be `n`, while it should be `indegree`/`outdegree` resp.

**Comment by bosilca** [comment]
Correct, I should have used the degree as defined in the topology instead of n. Thanks for the fix, I will prepare a PR later today.
