### ISSUE TITLE
Can't launch with MPMD on different architectures: x86 and aarch64

### ISSUE THREAD

**Issue by lykke-li** [open-mpi/ompi#11781]
## Background information

I am trying to use OpenMPI with MPMD to running a program across different architectures: x86 and aarch64. But I can't launch it successfully with keeping modifying my command and configurations.

### What version of Open MPI are you using?

Open MPI 4.1.5rc2

### Describe how Open MPI was installed 

From `module load` on a cluster

### Please describe the system on which you are running

* Operating system/version: both of them are Rocky Linux 8.7
* Computer hardware: x86 - Intel; aarch64 - ARM; they share the same file system
* Network type: InfiniBand with ConnectX-6

## Details of the problem

The command I use to launch `mpirun -np 2 hostname` with MPMD (on the x86 architecture): 

1. Checking the current OpenMPI version can support MPMD on single architecture:

```shell
mpirun -np 1 hostname : -np 1 hostname
```

It works, and can print the x86's hostname twice.

2. On two different architectures:

```shell
$ mpirun -np 1 --hostfile hostfile1 hostname : -np 1 --hostfile hostfile2 uptime
--------------------------------------------------------------------------
An ORTE daemon has unexpectedly failed after launch and before
communicating back to mpirun. This could be caused by a number
of factors, including an inability to create a connection back
to mpirun due to a lack of common network interfaces and/or no
route found between them. Please check network connectivity
(including firewalls and network routing requirements).
--------------------------------------------------------------------------
```

Where the content of `hostfile1` and `hostfile2` is the corresponding hostname of x86 node and aarch64 node.

I also tried different approach to launch MPMD:

```bash
mpirun --app test-mpmd.conf
bash: /path/to/x86/ompi/bin/orted: cannot execute binary file: Exec format error
--------------------------------------------------------------------------
```

Where `test-mpmd.conf`:

```
-np 1 -host x86_node ./show_hostname.sh
-np 1 -host aarch64_node ./show_hostname.sh
```

Where `show_hostname.sh`:

```
#!/bin/bash
HOST=`uname -m`
case "$HOST" in
    x86_64)
        exec hostname "$@"
        ;;
    aarch64)
        exec hostname "$@"
        ;;
    *)
        echo "Unknown architecture"
        exit 1
        ;;
esac
```

I'm wondering if I didn't correctly setup the MPMD command or any suggestion about this issue?

Appreciate with any help or suggestion. Thanks!

**Comment by jsquyres** [comment]
Setting up to run on multiple different architectures is tricky.

Question before I answer you: any reason you're using Open MPI v4.1.5rc2?  Open MPI v4.1.5 has been out for quite a while now -- no need to use an rc.

You'll need to have 2 entirely different builds/installs of Open MPI: one for x86, and the other for aarch64.  For example, you can install the same version of Open MPI into `/usr/local` on both machines, where `/usr/local` is a local filesystem -- not a network-shared filesystem.  This will have the Open MPI executables compiled for each architecture.  Then you add `/usr/local/bin` to `PATH` on each node, and `/usr/local/lib` to your `LD_LIBRARY_PATH` in each node's non-interactive shell startup files (e.g., `$HOME/.bashrc`).

Then you'll be able to do something like this:

```
shell$ cat hosts
my-x86-host
my-aarch64 host
shell$ mpirun --hostfile hosts hostname
my-x86-host
my-aarch64-host
```

The key is that Open MPI has to be able to find binaries native to the system on which it is running.  And note that `hostname` is already local to each machine, and native to the machine on which it is installed.

When you compile MPI applications (e.g., the hello world or ring example programs), you'll also need to compile them twice: once for each architecture.  If your MPI executable is named `hello_c`, for example, you can play whatever PATH tricks you want to have ` hello_c` compiled for x86 on your x86 machine and a different `hello_c` compiled for aarch64 on your aarch64 machine.  E.g., you could have another pair of local directories named `/usr/local/mpi` (on each machine -- *not* a networked filesystem) and put the respective `hello_c` files in each.

Or you could name the executables `hello_c.x86` and `hello_c.aarch64`, respectively, and have them both in the same directory on a networked filesystem.  Then you'd have to use the MPMD launcher functionality, perhaps something like this:

```
shell$ mpirun -np 1 --host my-x86-host hello_c.x86 : -np 1 --host my-aarch64-host hello_c.aarch64
```

**Comment by ggouaillardet** [comment]
note you might have to configure Open MPI with `--enable-heterogeneous`.
keep in mind this option is very lightly tested.

two tricks you might find useful:

```
mpirun --mca orte_lauch_agent <orte_agent> --mca orte_fork_agent <fork_agent> ... a.out
```

- `orte_agent` is a program you can write (for example a shell script on a shared directory
that will exec the right `orted` depending on the architecture
- `mpirun` and `orted` daemon will fork&exec `fork_agent a.out` instead of `a.out`,
so you can also implement your own `fork_agent` to pick the right `a.out` depending on the architecture.

**Comment by lykke-li** [comment]
Hi @jsquyres , appreciate your help! 

The reason I use rc version is just because it is the default one from module load. But now I followed your suggestion and installed the v4.1.5 manually for further tests.

Instead of installing them under the local filesystem `/tmp/`, I just create symbolic links under `tmp` and link to the corresponding installed openmpi on x86 and aarch64 architecture, and add the `/tmp/bin` and `/tmp/lib` into the environment path as in `.bashrc`. 

[**WORK**]: Now I can get the printed hostname of both x86-host and aarch64-host by running `mpirun -np 1 --host x86-node:1 hostname :  -np 1 --host aarch64-node:1 hostname` command on x86 node.

However, when I move to test `hello_c` program (just the simple MPI hello world C code), I met some problem:

[**NOT WORK**]: When I run `mpirun -np 1 --host x86-node hello.x86 : -np 1 --host aarch64-node hello.aarch64` on x86 node, there is only one output I can see: `hello from aarch64-node, rank 1 out of 2 processors`, and then the program will hang without exit. Which means the process on x86 node is hanging and print nothing.

[**WORK**]: But both of the `mpirun --host x86-node:2 -np 1 hello.x86 : -np 1 hello.x86` and `mpirun --host aarch64-node:2 -np 1 hello.aarch64 : -np 1 hello.aarch64` called from x86 node can print the expected output -- two hello from x86 or aarch64 node with the corresponding rank id. I think this test can let me make sure I didn't make mistake on compiling.

Could you give me more suggestions or clues for the not working one?
