### ISSUE TITLE
communicator: add errhandler_type back and debugger GAP issue

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#11819]
This is an issue corresponding to PR #11818.  Filing this as an issue just so that we can track it on the project board.

It affects main and v5.0.x.

**Comment by wzamazon** [comment]
https://github.com/open-mpi/ompi/pull/11818 was merged.

I opened a PR to backport to v5.0.x branch: https://github.com/open-mpi/ompi/pull/11821

**Comment by wzamazon** [comment]
backport merged.
