### ISSUE TITLE
[question] Are MPI implementations (openmpi/mpich) API/ABI compatible?

### ISSUE THREAD

**Issue by yurivict** [open-mpi/ompi#11813]
Are MPI implementations (openmpi/mpich) API/ABI compatible?

If some library uses MPI, but doesn't wish to link to a specific MPI implementation - can it only use MPI headers and not link with MPI libraries, and let the application that uses this library to decide what MPI implementation to use?

**Comment by jsquyres** [comment]
They are API compatible, meaning that if your program includes `mpi.h` and calls MPI functions, it can be compiled against either Open MPI or MPICH (or any of the MPI's that are derived from them).

However, Open MPI and MPICH are not ABI compatible, meaning that if you compile your MPI application against Open MPI, it will not automatically run-time link against MPICH's shared libraries and function properly.

**Comment by yurivict** [comment]
@jsquyres 
I am curious, what causes such ABI incompatibility?

**Comment by jsquyres** [comment]
They are totally different implementations written by different people.

An oft-cited difference between Open MPI and MPICH is that in Open MPI, the pre-defined MPI handles (e.g., `MPI_COMM_WORLD`) are pointers, but in MPICH, they are integers.

**Comment by devreal** [comment]
@yurivict there are wrappers that try to provide ABI compatibility (e.g., [1]) and some traction behind defining a common ABI in the MPI Forum for a future release of the standard. The wrappers are probably your best bet right now.

[1] https://github.com/cea-hpc/wi4mpi

**Comment by yurivict** [comment]
@jsquyres @devreal 
Thank you for this information. It is very useful.

I will try to port [wi4mpi](https://github.com/cea-hpc/wi4mpi) to FreeBSD and see if can be used as a proxy for MPI interface.

The problem that we have now is that many ports have MPICH and OPENMPI options. These option choices should be matched between depending packages, so that same MPI choices are made in the application and libraries that it uses, for example.

This is a very error-prone situation because these choices can be easily mismatched. I am wondering if wi4mpi can solve this, if we would link all libraries and applications to it and only the application would have a choice of what MPI to use.
