### ISSUE TITLE
Wrong size of predefined datatype MPI_BYTE

### ISSUE THREAD

**Issue by FlorentGermain-Bull** [open-mpi/ompi#11815]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
main branch

-----------------------------

## Details of the problem

Hi,
Reading the predefined datatypes definition, I found something confusing: OMPI_DATATYPE_MPI_BYTE could be defined larger than a 1Byte when C char size is largen than 1Byte, which seems to be erroneous.

The 4.0 version of the MPI standard states: `A value of type MPI_BYTE consists of a byte (8 binary digits). A byte is uninterpreted and is different from a character.` (https://www.mpi-forum.org/docs/mpi-4.0/mpi40-report.pdf bottom of page 33).

Is there any reason to keep MPI_BYTE = MPI_UNSIGNED_CHAR, even if it is not compliant with the standard (when sizeof(char) != 1)?

**Comment by bosilca** [comment]
In which case is the standard C `unsigned char` larger than 1 byte ?

**Comment by FlorentGermain-Bull** [comment]
I don't know in which context or platform this could occur, but ompi/datatype/ompi_datatype_internal.h checks it
`
#if SIZEOF_CHAR == 1
#define OMPI_DATATYPE_MPI_CHAR                    OMPI_DATATYPE_MPI_INT8_T
#define OMPI_DATATYPE_MPI_SIGNED_CHAR             OMPI_DATATYPE_MPI_INT8_T
#define OMPI_DATATYPE_MPI_UNSIGNED_CHAR           OMPI_DATATYPE_MPI_UINT8_T
#define OMPI_DATATYPE_MPI_BYTE                    OMPI_DATATYPE_MPI_UINT8_T
#elif SIZEOF_CHAR == 2
#define OMPI_DATATYPE_MPI_CHAR                    OMPI_DATATYPE_MPI_INT16_T
#define OMPI_DATATYPE_MPI_SIGNED_CHAR             OMPI_DATATYPE_MPI_INT16_T
#define OMPI_DATATYPE_MPI_UNSIGNED_CHAR           OMPI_DATATYPE_MPI_UINT16_T
#define OMPI_DATATYPE_MPI_BYTE                    OMPI_DATATYPE_MPI_UINT16_T
#elif SIZEOF_CHAR == 4
#define OMPI_DATATYPE_MPI_CHAR                    OMPI_DATATYPE_MPI_INT32_T
#define OMPI_DATATYPE_MPI_SIGNED_CHAR             OMPI_DATATYPE_MPI_INT32_T
#define OMPI_DATATYPE_MPI_UNSIGNED_CHAR           OMPI_DATATYPE_MPI_UINT32_T
#define OMPI_DATATYPE_MPI_BYTE                    OMPI_DATATYPE_MPI_UINT32_T
#elif SIZEOF_CHAR == 8
#define OMPI_DATATYPE_MPI_CHAR                    OMPI_DATATYPE_MPI_INT64_T
#define OMPI_DATATYPE_MPI_SIGNED_CHAR             OMPI_DATATYPE_MPI_INT64_T
#define OMPI_DATATYPE_MPI_UNSIGNED_CHAR           OMPI_DATATYPE_MPI_UINT64_T
#define OMPI_DATATYPE_MPI_BYTE                    OMPI_DATATYPE_MPI_UINT64_T
#endif
`

**Comment by devreal** [comment]
Looking at the [C standard](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf), my reading of 6.2.6 is that `char` must be of size 1 byte:

> 4. Values stored in non-bit-field objects of any other object type consist of n × CHAR_BIT bits, where n is the size of an object of that type, in bytes.

And 5.2.4.2.1 says:

> - number of bits for smallest object that is not a bit-field (byte)
>    CHAR_BIT 8

So `MPI_BYTE` can safely be mapped to `MPI_CHAR`.

**Comment by jsquyres** [comment]
> it looks like an overly paranoid test. We can safely remove it and replace it with an assert that `SIZEOF_CHAR == 1`.

Is it there for some crazy Intel compiler command line switch?  I know there's CLI options for changing the size of `int` -- are there Intel compiler CLI options for changing the size of `char`?  Or perhaps were we worried about (older?) Cray platforms that could have `char` be more than 1 byte...?

**Comment by Draal8** [comment]
I didn't find any such compiler options on [intel c++ developer guide](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-9/alphabetical-option-list.html) so i guess we're safe on that side.

**Comment by jsquyres** [comment]
@FlorentGermain-Bull Could you file a PR with @bosilca's suggestion?

> it looks like an overly paranoid test. We can safely remove it and replace it with an assert that `SIZEOF_CHAR == 1`.

**Comment by jsquyres** [comment]
PR merged to main.
