### ISSUE TITLE
v4.1.x: Unable to find relevant files during the make install step

### ISSUE THREAD

**Issue by Yahoo-90** [open-mpi/ompi#11822]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
v4.1.5

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
from a source/distribution tarball

### Please describe the system on which you are running

* Operating system/version:Ubuntu20.04
* Computer hardware:
* Network type:soft-roce

-----------------------------

## Details of the problem

I had already installed rdma core and ucx before installing ompi, but during the “make install” step of installing ompi, I encountered an error shows that I couldn't find the libverbs and lrdmacm  . The specific error is shown in the following error_info file, but I think these files already exist on my computer, but their names are libibverbs and librdmacm :
![image](https://github.com/open-mpi/ompi/assets/65900256/2253930a-a42e-477b-bd2a-15f1bf4bdb08)
What is the reason for this and how can I solve this problem?
[error_info.txt](https://github.com/open-mpi/ompi/files/12038496/error_info.txt)

**Comment by yosefe** [comment]
Seems OpenMPI is being build with btl/openib support, and the error comes from there.
What is the configure command and full output?
Where is rdma-core installed? Seems openmpi cannot find librdmacm.so and libibverbs.so, i'd guess it's installed in non-default location?
