### ISSUE TITLE
Deadlock on request.Wait()

### ISSUE THREAD

**Issue by YarShev** [open-mpi/ompi#11824]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

```bash
$ mpiexec --version
mpiexec (OpenRTE) 4.1.5

Report bugs to http://www.open-mpi.org/community/help/
```

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

```bash
conda install -c conda-forge mpi4py openmpi
```

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

-

### Please describe the system on which you are running

* Operating system/version: `Ubuntu 22.04.2 LTS`
* Computer hardware: two `i3en.24xlarge` instances on AWS
* Network type: `Ethernet`

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```bash
$ mpiexec -n 2 --host host1:1,host2:1 --prefix <PATH_TO_CONDA_ENV> python foo.py
```

```python
# foo.py
from mpi4py import MPI
from mpi4py.util import pkl5
import time
import socket

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

hostname = socket.gethostname()
host = socket.gethostbyname(hostname)
with open('out.txt', 'w') as f:
    print(f"host ={host}" , f"rank ={rank}", file=f)

N = 100000
msgpack_buffer = bytearray(N)
msgpack_buffer1=bytearray(N)

tag=1
if rank == 0:
    with pkl5._bigmpi as bigmpi:
        h1 = comm.Isend(bigmpi(msgpack_buffer), dest=1)
        h2 = comm.Isend(bigmpi(msgpack_buffer1), dest=1)

    h1.Wait()
    time.sleep(1)
    h2.Wait() # deadlock is here
elif rank == 1:
    with pkl5._bigmpi as bigmpi:
        comm.Recv(bigmpi(msgpack_buffer), source=0)

if not MPI.Is_finalized():
    MPI.Finalize()
```

There is an issue when `N=>100000`, but the issue is gone when `N<=10000`.

There is no an issue on Intel MPI and MPICH.

**Comment by devreal** [comment]
@YarShev I don't think your code is correct. Process 0 sends two messages to process 1, which only receives one message. The call to `h2.Wait` will deadlock because there is no receiver for the message. For smaller messages you might get away with that (because of the way messages are handled internally) but that does not mean that your program is a correct MPI program.

**Comment by YarShev** [comment]
@devreal, thanks for the explanation, that is probably the case. Closing the issue.
