### ISSUE TITLE
The submodule pmix automatically pass -Werror and generate lots of errors

### ISSUE THREAD

**Issue by JiakunYan** [open-mpi/ompi#11838]
## Background information
I am trying to compile OpenMPI from the github clone (Actually, the OpenMPI with the continuation extension, though I do not think this issue is related to the changes made by that fork.).

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

github repo: https://github.com/devreal/ompi.git
hash: c8c04371c3cb0ab79ce71a0b5b5980af5867d41a 

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
From a git clone.
```
./autogen.pl
./configure --with-ucx
make install
```

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
```
 90c091c7b2342da546f6f12647e020d569f66ec7 3rd-party/openpmix (v1.1.3-3655-g90c091c7)
 f99fe3ff03b6169175155389777b71dec01c2044 3rd-party/prrte (psrvr-v2.0.0rc1-4515-gf99fe3ff03)
 5c8de3d97b763bf8981fb49cbedd36e201b8fc0a config/oac (5c8de3d)
```

### Please describe the system on which you are running

* Operating system/version: openSUSE Leap 15.4
* Computer hardware: AMD EPYC 7532
* Network type: infiniband

-----------------------------

## Details of the problem

I encountered this error
```shell/home/jyan/workspace/install_scripts_source/openmpi-cont/3rd-party/openpmix/src/util/pmix_if.c: In function ‘pmix_ifnametoaddr’:
/home/jyan/workspace/install_scripts_source/openmpi-cont/3rd-party/openpmix/src/util/pmix_if.c:93:13: error: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Werror=stringop-overread]
   93 |         if (strcmp(intf->if_name, if_name) == 0) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: note: source object is likely at address zero
/home/jyan/workspace/install_scripts_source/openmpi-cont/3rd-party/openpmix/src/util/pmix_if.c: In function ‘pmix_ifnametoindex’:
/home/jyan/workspace/install_scripts_source/openmpi-cont/3rd-party/openpmix/src/util/pmix_if.c:113:13: error: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Werror=stringop-overread]
  113 |         if (strcmp(intf->if_name, if_name) == 0) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: note: source object is likely at address zero
/home/jyan/workspace/install_scripts_source/openmpi-cont/3rd-party/openpmix/src/util/pmix_if.c: In function ‘pmix_ifnametokindex’:
/home/jyan/workspace/install_scripts_source/openmpi-cont/3rd-party/openpmix/src/util/pmix_if.c:132:13: error: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Werror=stringop-overread]
  132 |         if (strcmp(intf->if_name, if_name) == 0) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: note: source object is likely at address zero
```

Further investigation leads me to this line:
https://github.com/openpmix/openpmix/blob/90c091c7b2342da546f6f12647e020d569f66ec7/config/pmix.m4#L1050

If building from github repo, pmix will automatically pass `-Werror`.

Passing `--enable-devel-check=no` fixes this error, but it would be better if OpenMPI could always pass it for users.

**Comment by rhc54** [comment]
What compiler is this? PMIx has been distributed on most systems without any reports of problems, so it would be worth knowing the compiler so we can silence it's issue.

**Comment by JiakunYan** [comment]
@rhc54  gcc 13.1.0. Maybe it is too new.

**Comment by rhc54** [comment]
Yeah, we have had problems with some of the newest gcc releases - seems like they got a little _too_ picky and sometimes erroneously generate "warnings" where none is merited, and then have to go back and fix the compiler.

I can try to take a look and see if there is anything we can do. Might just need to wait for a bug-fix release from those guys. Meantime, you might try backing down to something less bleeding edge and see if the problem disappears.

**Comment by devreal** [comment]
I incidentally ran into the same issue last week with GCC 13.1.0. The pmix used here is rather old (November 2022) and newer versions do compile.

@JiakunYan You can run `git submodule update --init --recusrive` to get the latest versions...

Having said that, I will reiterate what I said in private already: PMIx should not make the minor problem of a few (compiler warnings that are harmless and caused by a handful of developers) a major problem for everyone else (potentially dozens of OMPI developers that rely on PMIx to build, albeit with warnings) by defaulting to `-Werror`. Setting up everyone's built to potentially fail after a compiler upgrade is bad. PMIx is now foundational to Open MPI and most people compiling do not care about its warnings.

**Comment by JiakunYan** [comment]
@rhc54 @devreal Thanks! I tried GCC 12.2.0 and it worked. I think this issue is good to close.
