### ISSUE TITLE
 MPI_Comm_f2c() function was called before MPI_INIT was invoked

### ISSUE THREAD

**Issue by sudarsan3010** [open-mpi/ompi#11844]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Mpich 3.4
Openmpi 4.1.2

### Describe how Open MPI was installed:

Downloaded directly from the website 
https://www.mpich.org/static/downloads/3.4/mpich-3.4.tar.gz
https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.2.tar.gz

### Please describe the system on which you are running

* Operating system/version: x86_64-redhat-linux-gnu
* Computer hardware: HPC
* GNU compiler collection version: 9.3.0
* GNU Make - 3.81
-----------------------------

## Details of the problem

**1.** I have compiled LISF (https://lis.gsfc.nasa.gov/sites/default/files/LIS/public_7_4_releases/LISF_installation_guide.14-jun-2022.pdf) using mpich & openmpi (above mentioned versions). Even the required libraries for LISF has been compiled using same mpich.

The execution statement is as follows,
mpirun -np 4 ./LDT ldt.config

The error I am getting is,
```
*** The MPI_Comm_f2c() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[node1.local:04095] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

I searched for this error message in all the directories and found it in some directory of openmpi.

**2.** I am now trying to reduce the version (install minimal required versions of LISF) 
mpich 3.3 & Openmpi -4.0.0

Mpich 3.3 has been installed successfully, while installing OpenMPI I am getting following error while executing 'make'.

```
make[2]: Entering directory `/home/user6/library_packages/openmpi-4.0.0/ompi/tools/ompi_info'
  CC       ompi_info.o
  CC       param.o
  CCLD     ompi_info
/home/user6/library_packages/openmpi-4.0.0/opal/.libs/libopen-pal.so: undefined reference to `dlsym'
/home/user6/library_packages/openmpi-4.0.0/opal/.libs/libopen-pal.so: undefined reference to `dlerror'
/home/user6/library_packages/openmpi-4.0.0/opal/.libs/libopen-pal.so: undefined reference to `openpty'
/home/user6/library_packages/openmpi-4.0.0/opal/.libs/libopen-pal.so: undefined reference to `dlopen'
/home/user6/library_packages/openmpi-4.0.0/opal/.libs/libopen-pal.so: undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make[2]: *** [ompi_info] Error 1
make[2]: Leaving directory `/home/user6/library_packages/openmpi-4.0.0/ompi/tools/ompi_info'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user6/library_packages/openmpi-4.0.0/ompi'
make: *** [all-recursive] Error 1
```

**Comment by ggouaillardet** [comment]
The error message is self explanatory: LISF cannot call `MPI_Comm_f2c()` before `MPI_Init()` (or after `MPI_Finalize()` fwiw). This is either an application issue, or it might happen if you are mixing libraries (some depend on Open MPI and other depend on MPICH)

I would stick with your already installed Open MPI 4.1.2, make sure all the dependencies have been built with Open MPI 4.1.2, and use a debugger to get a stack trace when `MPI_Comm_f2c()` is invoked, so you can double confirm this occurs before `MPI_Init()`.

**Comment by jsquyres** [comment]
I'm a little confused by this issue: is this an application question, or an installation question?

I think @ggouaillardet provided a good answer to the application question.  Note that we can not answer questions about LISF or MPICH -- those are not our code bases, and we can't answer questions about them.  This github repo is for Open MPI.

For your installation question, it's unclear as to whether you're trying to install Open MPI v4.1.2 or v4.0.0.

There's a lot of different data points here -- can you clarify your question please?

**Comment by sudarsan3010** [comment]
Glad to see immediate responses.

@ggouaillardet Okay I will use debugger and let know here.

@jsquyres No. 1 is an application issue and No. 2 is an installation issue.

Version 4.1.2 has been installed and it causes the above mentioned error (Serial number 1).

So, I am trying to install a lower version 4.0.0, which gives some error during installation (Serial number 2).

**Comment by jsquyres** [comment]
It is highly unlikely that Open MPI v4.0.0 vs. v4.1.2 will give you a different result with this error.

**Comment by sudarsan3010** [comment]
@ggouaillardet I have debugged mpirun alone. Attached below

(base) [user6@satellite examples]$ gdb mpirun
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-60.el6_4.1)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This GDB was configured as "x86_64-redhat-linux-gnu".

Reading symbols from /home/user6/mpich_3.4/bin/mpirun...done.
(gdb) run
Starting program: /home/user6/mpich_3.4/bin/mpirun
[Thread debugging using libthread_db enabled]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000420c25 in HYDU_create_proxy_list ()
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.7.x86_64 libxml2-2.7.6-21.el6_8.1.x86_64
(gdb) backtrace
#0  0x0000000000420c25 in HYDU_create_proxy_list ()
#1  0x0000000000404658 in main () at ui/mpich/mpiexec.c:262
(gdb)

**Comment by bosilca** [comment]
@sudarsan3010 we need the stacktrace of the MPI processes themselves not the `mpirun` command. For a small number of processes, you can enable X forwarding in your ssh and then (in the same terminal) start your parallel application with `mpirun -np 2 xterm -e gdb --args ...`. Then, in the xterm that will open, set a breakpoint to `MPI_Comm_f2c` and `MPI_Init`, to see when they are called. Once one of these breakpoints are hit, you should print the `backtrace`.

That being said let me remind you that you are on the Open MPI github and are providing traces from MPICH. Our knowledge of that code is limited, not sure how much we will be able to help. Thus, running with OMPI while continuing this discussion would be preferable.

**Comment by jsquyres** [comment]
@sudarsan3010 Do you have any further information, such as the stack traces from the individual MPI processes?

**Comment by sudarsan3010** [comment]
The error has been resolved. The mpich and openmpi has been installed in the same directory, that was causing this issue.
