### ISSUE TITLE
4.1.5 defines MPI_F_STATUS_SIZE to undefined OMPI_FORTRAN_STATUS_SIZE

### ISSUE THREAD

**Issue by jprotze** [open-mpi/ompi#11843]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.1.5

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Manually compiled from release tarball

-----------------------------

## Details of the problem

Compilation of code that tests for MPI_F_STATUS_SIZE to be available for a c compiler fails, because the symbol is defined, but is defined to an undefined symbol (`OMPI_FORTRAN_STATUS_SIZE`) which presumably should be replaced by configure:
 

https://github.com/open-mpi/ompi/blob/v4.1.x/ompi/include/mpi.h.in#L544
vs.
https://github.com/open-mpi/ompi/blob/v4.1.x/ompi/include/mpif-config.h.in#L51

**Comment by jprotze** [comment]
It looks like the definition & configure change introduced in https://github.com/open-mpi/ompi/commit/7fce2f3057d6baaba688c99ad5602407df21128d was missed when cherry-picking in #10491

**Comment by jsquyres** [comment]
@jprotze Thanks for tracking that down!  I did some testing and it looks like we only want part of 7fce2f30.  I filed a PR to fix the issue in #11862.
