### ISSUE TITLE
MPICH p2p failures

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#1185]
I see MTT failures for the following tests:
* **bsend2**
* **bsendalign**
* **bsend5**
* **cancelrecv** (addressed in Issue https://github.com/open-mpi/ompi/issues/1175)
* **icsend** (addressed in PR https://github.com/open-mpi/ompi/pull/1184)

The rest of the tests seems to have same problem: **hang**. It can be observed with **pml/ob1**, **btl/[tcp,openib]**, if I use **pml/yalla** (mxm) I see no problems with those tests. All problems can be reproduced even on one node, but you must make sure that you don't include any sm BTLs:  `-mca btl self,[tcp,openib]`. In all cases rank0 that receives the data remains blocked in `MPI_Recv()` while all senders reach `MPI_Finalize()` and *think* that the data was sent correctly.
Here is some additional information on each of them:
* **bsend2** and **bsendalign** are similar from this problems point of view problem, they can be reproduced with just 2 processes.
* **bsend5** needs 4 processes to hang.

**Comment by hjelmn** [comment]
Weird. I will take a look and see why buffered sends are not working correctly.

**Comment by hjelmn** [comment]
Can't get either bsend2 or bsendalign to hang on my mac. bsend5 does hang however.

**Comment by hjelmn** [comment]
Scratch that. I can reproduce on a different mac with bsend2. Looking at it now.

**Comment by hjelmn** [comment]
Ok, was a problem with my firewall. All those tests pass with -mca btl self,tcp

**Comment by hjelmn** [comment]
Hah, well. I was running with a single change. Can you try with this patch?

```
diff --git a/ompi/mca/pml/ob1/pml_ob1_isend.c b/ompi/mca/pml/ob1/pml_ob1_isend.c
index dba3c22..893e6ce 100644
--- a/ompi/mca/pml/ob1/pml_ob1_isend.c
+++ b/ompi/mca/pml/ob1/pml_ob1_isend.c
@@ -198,7 +198,7 @@ int mca_pml_ob1_send(const void *buf,
             return rc;
         }
 
-        /* free the request and return. don't care if it completes now */
+        ompi_request_wait_completion (brequest);
         ompi_request_free (&brequest);
         return OMPI_SUCCESS;
     }
```

**Comment by artpol84** [comment]
@hjelmn With this patch all those tests works well. Thank you.

**Comment by hjelmn** [comment]
Not sure how MTT missed this. Seems to only trigger under specific circumstances. Thanks for reporting this. Will patch 1.10.2 and 2.x.

**Comment by artpol84** [comment]
I've caught this with MTT and it was 100% reproducible. Master MTT must be
revisited.

вторник, 8 декабря 2015 г. пользователь Nathan Hjelm написал:

> Not sure how MTT missed this. Seems to only trigger under specific
> circumstances. Thanks for reporting this. Will patch 1.10.2 and 2.x.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-mpi/ompi/issues/1185#issuecomment-162771672>.
>


-- 
-----
Best regards, Artem Polyakov
(Mobile mail)

**Comment by rhc54** [comment]
I believe the reason is simply that the current MTT's being run each night are using the IBM and Intel test suites, and not the MPICH test suite - which is what @artpol84 is using.
