### ISSUE TITLE
windows 11 install openmpi 4.1.4  with java binding meet error

### ISSUE THREAD

**Issue by mullerhai** [open-mpi/ompi#11852]
Hi, I want to install openmpi 4.1.4   on windows11, but after exec  ./configure --enable-mpi-java ,meet error 

* Operating system/version: win 11
* Computer hardware:  cpu i7  ,mem 64Gb disk 4tb
* Network type: wifi
```
*** Java MPI bindings
checking for Java in OS X/macOS locations... not found
checking for Java in Linux locations... not found
checking for Java in Solaris locations... not found
checking if Java support available... no
configure: WARNING: Java support requested but not found.
configure: error: Cannot continue
```

**Comment by mullerhai** [comment]
but after I add some param also meet error
```
./configure --enable-mpi-java --with-jdk-bindir="/usr/lib/jvm/java-1.8.0/bin" --with-jdk-headers="/usr/lib/jvm/java-1.8.0/include" --prefix="/opt/openmpi-4.1.4"
```

**Comment by mullerhai** [comment]
is jdk version to high cause this ?

**Comment by mullerhai** [comment]
but after when I try jdk 8 and 11，also same error
···
*** Java MPI bindings
checking --with-jdk-bindir value... sanity check ok (/c/Java/bin)
checking --with-jdk-headers value... sanity check ok (/c/Java/include)
checking for javac... /c/Java/bin/javac
checking for jar... /c/Java/bin/jar
checking for javadoc... /c/Java/bin/javadoc
checking for javah... /c/Java/bin/javah
checking javac -h... yes
checking jni.h usability... no
checking jni.h presence... no
checking for jni.h... no
checking if Java support available... no
configure: WARNING: Java support requested but not found.
configure: error: Cannot continue

···

**Comment by mullerhai** [comment]
if not use java binding ，also meet error
···
== Library and Function tests
============================================================================
checking for library containing openpty... no
checking for library containing gethostbyname... no
checking for library containing socket... no
checking for library containing sched_yield... none required
checking for library containing dirname... none required
checking for library containing ceil... none required
checking for library containing clock_gettime... none required
checking for asprintf... yes
checking for snprintf... yes
checking for vasprintf... yes
checking for vsnprintf... yes
checking for openpty... no
checking for isatty... yes
checking for getpwuid... no
checking for fork... no
checking for waitpid... no
checking for execve... yes
checking for pipe... no
checking for ptsname... no
checking for setsid... no
checking for mmap... no
checking for tcgetpgrp... no
checking for posix_memalign... no
checking for strsignal... no
checking for sysconf... no
checking for syslog... no
checking for vsyslog... no
checking for regcmp... no
checking for regexec... no
checking for regfree... no
checking for _NSGetEnviron... no
checking for socketpair... no
checking for strncpy_s... yes
checking for usleep... yes
checking for mkfifo... no
checking for dbopen... no
checking for dbm_open... no
checking for statfs... no
checking for statvfs... no
checking for setpgid... no
checking for setenv... no
checking for __malloc_initialize_hook... no
checking for __clear_cache... yes
configure: WARNING: neither statfs() and statvfs() were found
configure: error: Cannot continue

···

**Comment by jsquyres** [comment]
I'm not surprised that there may be glitches here; Open MPI doesn't really get much native testing on Windows.  

Have you tried https://cygwin.com/cgi-bin2/package-grep.cgi?grep=openmpi?  Or building Open MPI under WSL?

**Comment by mullerhai** [comment]
> I'm not surprised that there may be glitches here; Open MPI doesn't really get much native testing on Windows.
> 
> Have you tried https://cygwin.com/cgi-bin2/package-grep.cgi?grep=openmpi? Or building Open MPI under WSL?

wsl  both centos and Ubuntu I install openmpi successfully，but windows11 local now failed ，I use java develop with IDEA ide IN  Windows 11，How  I use windows11 to connect with local wsl openmpi ？

https://cygwin.com/cgi-bin2/package-grep.cgi?grep=openmpi I will try，but I not sure if use source code build openmpi is ok with cygwin ? thanks

**Comment by mullerhai** [comment]
> I'm not surprised that there may be glitches here; Open MPI doesn't really get much native testing on Windows.
> 
> Have you tried https://cygwin.com/cgi-bin2/package-grep.cgi?grep=openmpi? Or building Open MPI under WSL?

Most important ，openmpi java binding on windows11 just I need to use for java develop，please consider  make  support openmpi  on windows11， thanks

**Comment by jsquyres** [comment]
> please consider make support openmpi on windows11， thanks

I'm sorry, the Open MPI community just doesn't have the resources to develop the needed support for Microsoft Windows. There's so little demand for it that when we *did* nominally support Windows (years ago), we ultimately removed all that code because no one was using it, and it fell into disrepair.

Even today, we've had reports that Open MPI works on WSL, but to my knowledge, no one in the Open MPI dev community develops, tests, or supports such environments.

Sorry!

**Comment by mullerhai** [comment]
> > please consider make support openmpi on windows11， thanks
> 
> I'm sorry, the Open MPI community just doesn't have the resources to develop the needed support for Microsoft Windows. There's so little demand for it that when we _did_ nominally support Windows (years ago), we ultimately removed all that code because no one was using it, and it fell into disrepair.
> 
> Even today, we've had reports that Open MPI works on WSL, but to my knowledge, no one in the Open MPI dev community develops, tests, or supports such environments.
> 
> Sorry!

I understand you,  thanks, I will try another way to build mpi on Windows 11
