### ISSUE TITLE
MPI 4.0.5 hangs 

### ISSUE THREAD

**Issue by TerryInFab** [open-mpi/ompi#11853]
Hi,

I've installed mpi 4.0.5 on my KylinOS-x86, the info of "uname -a" is:
Linux iZ2zee1iwih8aq4osgv4z6Z 4.19.90-24.4.v2101.ky10.x86_64 #1 SMP Mon May 24 12:14:55 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

and when I run:  mpirun  --allow-run-as-root --bind-to none -n 3 -host 101.200.199.85:3 ls /tmp,    it will hang for half an hour and then successfully connect to that remote host with the result of "ls /tmp".

Attached is the output of : strace mpirun  --allow-run-as-root --bind-to none -n 3 -host 101.200.199.85:3 ls /tmp

Could you see if there is any way to solve this? Thanks in advance.

--------------
[logs_of_strace.txt](https://github.com/open-mpi/ompi/files/12335169/logs_of_strace.txt)

**Comment by jsquyres** [comment]
@TerryInFab If you need further help, please send the information described here: https://docs.open-mpi.org/en/v5.0.x/getting-help.html#for-problems-launching-mpi-or-openshmem-applications

Technically, that's a help page for v5.0.x; you need to change one thing for the v4.0.x/v4.1.x series: in the commands shown, change `--prtemca` to `--mca`.
