### ISSUE TITLE
Signal: Segmentation fault (11)

### ISSUE THREAD

**Issue by YarShev** [open-mpi/ompi#11867]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

```bash
$ mpiexec --version
mpiexec (OpenRTE) 4.1.5

Report bugs to http://www.open-mpi.org/community/help/
```

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

```bash
$ conda install -c conda-forge mpi4py openmpi
```

### Please describe the system on which you are running

* Operating system/version: Ubuntu 20.04.4 LTS
* Computer hardware: Intel(R) Xeon(R) Platinum 8276L CPU @ 2.20GHz
* Network type: Ethernet

-----------------------------

## Details of the problem

```bash
mpiexec -n 2 python foo.py
```

```python
# foo.py
from mpi4py import MPI
import numpy

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

if rank == 0:
    data = numpy.arange(1000000, dtype='i')
    r = comm.Isend([data, MPI.INT], dest=1, tag=77)
    r.Wait()
elif rank == 1:
    data = numpy.empty(1000000, dtype='i')
    r = comm.Irecv([data, MPI.INT], source=0, tag=77)
    r.Free()
    print(data)
```

```bash
mpiexec noticed that process rank 1 with PID 0 on node FOO exited on signal 11 (Segmentation fault)
```

The issue is probably similar to https://github.com/pmodels/mpich/issues/6584, which mpich has fixed recently.

**Comment by devreal** [comment]
The code will not produce what you expect:
```
r = comm.Irecv([data, MPI.INT], source=0, tag=77)
r.Free()
print(data)
```

Assuming that `r.Free()` simply calls `MPI_Request_free` it does not wait for the operation to complete. The print may or may not print the data you expect, depending on whether the receive has completed already. Not sure that this is the cause for the Segfault but can you try to wait for the request first?

**Comment by YarShev** [comment]
If I wait for the request, everything works well. However, let's assume that I don't need data on the receiver side and just want to free a request and issue another irecv. Even removing print(data) in the original example above raises the error.

**Comment by devreal** [comment]
The code you posted ends without either calling `MPI_Finalize` or waiting for the communication to complete, i.e., the communication is dangling until the implicit finalization occurs. I can only speculate here but it could well be that the numpy array gets destroyed before all data is written to it. You have no control over the order in which the finalization/destruction happens. What happens if you add a call to `MPI.Finalize` at the end? If that doesn't help, a stack trace would be helpful to learn where things go wrong.

**Comment by YarShev** [comment]
If I add `MPI.Finalize`, there is no any error. When printing `data` I get the output `data = [0 0 0 ... 0 0 0]` and this is probably the expected behavior so the issue can be closed. Thanks.
