### ISSUE TITLE
Module plm:tm ignored with --disable-dlopen

### ISSUE THREAD

**Issue by albandil** [open-mpi/ompi#11886]
**In brief**: `--disable-dlopen` seems to prevent use of `plm:tm` in PRRTE, even though the output from configure confirms that the component is built, and a shared library(!) with this plugin is actually created:

    (...)
    PBS: yes (scheduler)
    Slurm: yes
    ssh/rsh: yes
    Torque: yes (/storage/praha1/home/jacob/software/pbspro-19.0.0)
    (...)

**In detail**: When the configure option `--disable-dlopen` is used with Open MPI 5.0.x (currently at 70d0906a3d22bef70a10845b22e8233b70fd4fb2), it is correctly interpreted by the bundled libraries hwloc and openpmix, resulting in absence of their dynamically linked plugins. However, the flag is not respected by PRRTE for some reason. As a result, the PBS task manager module `plm:tm` is built as DSO (obviously, only if PBS tm library is available):

    $ ./configure --disable-dlopen --with-pbs --with-tm=<path>
    (...)
    checking for MCA component plm:tm compile mode... dso
    (...)

Because Open PMIx is built without DSO support in this case (`PMIX_HAVE_PDL_SUPPORT=0`), and because PRRTE uses the component loading interface provided by Open PMIx, the shared library with the `plm:tm` plugin is not loaded during PRRTE component initialization (within or without a PBS session).

Example of execution of Open MPI configured with `--disable-dlopen`:

    $ mpiexec --map-by node --prtemca plm_base_verbose 10 true
    (...)
    [luna74.fzu.cz:987004] mca:base:select: Auto-selecting plm components
    [luna74.fzu.cz:987004] mca:base:select:(  plm) Querying component [slurm]
    [luna74.fzu.cz:987004] mca:base:select:(  plm) Querying component [ssh]
    [luna74.fzu.cz:987004] [[INVALID],0] plm:ssh_lookup on agent ssh : rsh path NULL
    [luna74.fzu.cz:987004] mca:base:select:(  plm) Query of component [ssh] set priority to 10
    [luna74.fzu.cz:987004] mca:base:select:(  plm) Selected component [ssh]
    (...)

... and without `--disable-dlopen`:

    $ mpiexec --map-by node --prtemca plm_base_verbose 10 true
    (...)
    [luna71.fzu.cz:25217] mca:base:select: Auto-selecting plm components
    [luna71.fzu.cz:25217] mca:base:select:(  plm) Querying component [slurm]
    [luna71.fzu.cz:25217] mca:base:select:(  plm) Querying component [ssh]
    [luna71.fzu.cz:25217] [[INVALID],0] plm:ssh_lookup on agent ssh : rsh path NULL
    [luna71.fzu.cz:25217] mca:base:select:(  plm) Query of component [ssh] set priority to 10
    [luna71.fzu.cz:25217] mca:base:select:(  plm) Querying component [tm]
    [luna71.fzu.cz:25217] mca:base:select:(  plm) Query of component [tm] set priority to 75
    [luna71.fzu.cz:25217] mca:base:select:(  plm) Selected component [tm]
    (...)

The help text in the top-level *configure* mentions also another option `--disable-prtedlopen`, but using this in addition to the previous one does not improve the situation, only produces a discouraging warning:

    $ ./configure --disable-dlopen --disable-prtedlopen --with-pbs --with-tm=<path>
    configure: WARNING: unrecognized options: --disable-prtedlopen
    (...)
    checking for MCA component plm:tm compile mode... dso
    (...)

I also unsuccessfully tried `--enable-dlopen=no`.

I think that if it is impossible to compile `plm:tm` statically (or make it work in any other way) with `--disable-dlopen`, then *configure* should clearly state the incompatibility and/or prevent such compilation. Otherwise is it very puzzling that a PBS/TM-enabled Open MPI does not work properly under PBS.

**System**: Cluster of dual-socket AMD Epyc 7551 nodes with Debian 11 and PBS Pro 19.0.

**Comment by rhc54** [comment]
Obviously, the intent is for the option to work. Looking at the PRRTE code, it appears some confusion entered the configure logic at some point - probably relating to whether or not to allow users to separately determine `dlopen` behavior for an embedded PRRTE. Allowing that behavior would probably only create additional confusion, so better to just eliminate it.

Give https://github.com/openpmix/prrte/pull/1782 a try (using `--disable-dlopen`) and see if that fixes the problem.

**Comment by rhc54** [comment]
This is now fixed on PRRTE master - will backport it shortly. Requires bumping submodules over here to see the change.

**Comment by albandil** [comment]
I can confirm that this works for me now in 5.0.x when I update the submodules to their current main branches https://github.com/openpmix/openpmix/commit/552f5afe85c7d81b153331c5718ec6b01b857fcc and https://github.com/openpmix/prrte/commit/f4c9fdd56351505ec7275f462ee1d25f95ae62ca.

**Comment by rhc54** [comment]
This is complete and can be closed.
