### ISSUE TITLE
mpi_leave_pinned=0 erroneously turns off all large message RDMA protocols

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#119]
When we run with --mca mpi_leave_pinned=0, the MPI library currently does no large message RDMA at all.  The way the code is written, we will always revert to the send/receive protocol.  Presumably, this is not the intent.  

This issue was discussed a while ago on the developer's list, but no action was taken.  Here are two email trails from the archive.

http://www.open-mpi.org/community/lists/devel/2009/10/6925.php

http://www.open-mpi.org/community/lists/devel/2009/10/6931.php

As the email pointed out, the issue is this code snippet from pml_ob1_rdma.c at line 64.  (from the trunk)

```
        if( NULL != btl_mpool ) {
            if(!mca_pml_ob1.leave_pinned) {
                /* look through existing registrations */
                btl_mpool->mpool_find(btl_mpool, base, size, &reg);
            } else {
                /* register the memory */
                btl_mpool->mpool_register(btl_mpool, base, size, 0, &reg);
            }

            if(NULL == reg)
                continue;
        }
```

When we run with mca_pml_ob1.leave_pinned==0, then we always make a call into the mpool_find function.  The find function attempts to find memory that was already registered.  Well, since we only ever try to find the memory, but do not ever register it, this function will always return a NULL value in the reg parameter.  This means that the num_btls_used value remains a 0, and the function returns indicating that there are no btls that support large message RDMA.  The PML reverts to doing just sends and receives.

It would appear that one way to fix this is to just get rid of the mpool_find function, and go right to the registering.  The underlying code also has checks all over the place for whether we are running with leave_pinned, so I think the right thing will just happen.  I am currently experimenting.

**Comment by jsquyres** [comment]
@rolfv Is this issue going anywhere?

**Comment by jsquyres** [comment]
@rolfv @bosilca @hjelmn Did this issue get resolved?

**Comment by jsquyres** [comment]
@hjelmn Says that this is now resolved -- that whole section of code was re-written (it was a non-issue to begin with).
