### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for the ompi

### ISSUE THREAD

**Issue by wangyuliu** [open-mpi/ompi#11908]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. As part of my dataset, I have collected the ompi project. **I would like to gather community opinions to support my assessment.** I appreciate your help and response! Based on scanning tools, the porting complexity is determined to be moderate leaning towards simple, with a small amount of code related to the CPU architecture in the project. (referring to the overall workload from adapting the project to a specific architecture to achieving full functionality on that architecture). Is this assessment accurate? I look forward to your help and response.
各位网友大家好啊~~~~我正在实施一个工具，以评估CPU架构移植的复杂性。它主要关注RISC-V体系结构的移植。作为我的数据集的一部分，我收集了ompi项目。我希望收集社会人士的意见，以支持我的评估。我很感谢你的帮助和回应！基于扫描工具，移植的复杂性被确定为中等偏简单，与项目中的CPU架构相关的代码量不大。（指的是从使项目适应特定架构到在该架构上实现全部功能的总体工作量）。这样的评价准确吗？我期待着你的帮助和回应。

**Comment by jsquyres** [comment]
Open MPI does have quite a bit of architecture-independent code; it was carefully architected, written, and maintained over the years to be as portable as possible.  That being said, there are definitely parts that require code that is specific to a given architecture.  Wherever possible, we have tried to separate these bits of code out either by formal components or by configure tests / preprocessor macros.

Open MPI is a large code base.  Even though most of it is likely architecture-independent, and while we do encourage porting Open MPI to new operating systems and new architectures, it isn't necessarily a small task to do so.  Even if you write most of the obvious code for the architecture-specific places in Open MPI, you'll still need quite a bit of iterative testing to find the not-so-obvious places.

My point is that overall, Open MPI is pretty friendly to porting to new environments.  But that doesn't mean that it's an easy task.

**Comment by janjust** [comment]
I would also agree with @jsquyres , Open MPI was already written to be architecture independent, thus the _moderate to simple_ difficulty is accurate. Having said that, it's a large code base and porting to new architectures and operating systems would require quite a lot of work and most importantly testing.

**Comment by jsquyres** [comment]
@wangyuliu If you have any further questions, please feel free to open a new issue.  Additionally, if you'd like to submit some contributions to Open MPI (e.g., if there are things needed for explicit RISC-V support), we'd love to see some pull requests.  Be sure to have a look at https://docs.open-mpi.org/en/v5.0.x/developers/index.html and https://docs.open-mpi.org/en/v5.0.x/contributing.html.

Thank you!
