### ISSUE TITLE
PMIx and PRRTE: CI status

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#11914]
I know folks in this project rely a lot on CI, and your reliance on PMIx and now PRRTE is strong. So I'm opening this issue to ensure that you are aware of the current status of CI on PMIx and PRRTE.

Put simply - it no longer exists on PRRTE and exists only at a limited level on PMIx.

Set aside the reasons why this may be happening - probably too reliant on a single organization, things change, etc. My point is only that you be aware of the risk window OMPI faces.

I test PRRTE master during development of whatever I am working on, but that leaves the question of unintended breakage. I only generally check that the PRRTE release branches still compile after backporting changes to them as there are limits to my time.

Same holds true for PMIx. We do still have Mellanox CI running on it, as well as the cross-version checks, so it isn't totally running free. However, we have had issues in the past with different compilers (XL) and cpu architectures (PowerPC) - and those aren't covered any more.

Nothing I can do about it. So if you care, some one or org over there is going to have to do something about it. Or just rely on picking up problems in your CI when updating submodule pointers - and hope that I'm willing/able to take some time to backtrack them down (no promises - not highly likely if things have moved too far. I have a lot of personal things on my plate).

Totally up to you 🤷‍♂️

**Comment by rhc54** [comment]
Quick update: Jeff created some GitHub actions that I have moved to the various release branches. So we now at least test build PMIx and PRRTE on Mac and Ubuntu for a couple of configurations (vpath/not, sphinx/not). Not much coverage, but better than zero 🤷‍♂️

**Comment by jsquyres** [comment]
Agreed; this is an issue that we need to continually monitor and do our best to maintain.  In times of limited budgets and manpower, automation can be a help.  But it does require proper care and feeding!
