### ISSUE TITLE
Updated ompi now orte is mad and cannot create daemons

### ISSUE THREAD

**Issue by victarionmagne** [open-mpi/ompi#11936]
Thank you for taking the time to submit an issue!

### Please describe the system on which you are running

* Operating system/version: Linux 6.5.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:40 +0000 x86_64 GNU/Linux
* Computer hardware: CPU's Xeon x86   E5-1620     |   AMD Phenom II x86  | Xeon W3520 x86
* All intel 1Gb pcie cards
* 4 Z400* series HP desktops 1 AMD node that has been isolated and reinsterted which isnt the problem
* 8 GB ram on all systems

* Network type: Ipv4 dhcp, over tcp
* all nodes conected to single switch, connected to single router(opfsense) 

-----------------------------

## Details of the problem
runnning mpirun with any program gives the same error 
"ORTE does not know how to route a message to the specified daemon
located on the indicated node:"
and does fix by using recommended commandline flag "--mca routed=directed"

I have checked all nodes have passwordless ssh into each other,
all nodes have access to the program, and it is mounted correctly
All nodes can run the program sepperately
all nodes have ssh-copy-id'd the same password
all nodes have the same user
all nodes shown and can be accessed via ssh login
and all have been updated to the newest arch as of Thu Sep 21 15:12:57 CEST 2023

*code
#include <mpi.h>
#include <stdio.h>

int main(int argc, char** argv) {

        MPI_Init(NULL, NULL);      // initialize MPI environment
        int world_size; // number of processes
        MPI_Comm_size(MPI_COMM_WORLD, &world_size);

        int world_rank; // the rank of the process
        MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

        char processor_name[MPI_MAX_PROCESSOR_NAME]; // gets the name of the processor
        int name_len;
        MPI_Get_processor_name(processor_name, &name_len);

        printf("Hello world from processor %s, rank %d out of %d processors\n",
                processor_name, world_rank, world_size);

        MPI_Finalize(); // finish MPI environment
}
*

```shell
shell$ mpirun --mca routed direct -np 16 --hostfile ~/hosts mnt/programs/MPI_sample.h --use-hwthread-cpus
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   magne1700
  target node:  magne1701

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   magne1700
  target node:  magne1702

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   magne1700
  target node:  magne1705

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
--------------------------------------------------------------------------

```

**Comment by rhc54** [comment]
Hmmm...something isn't correct in this report. You state that setting the `routed` method to `direct` fixed the problem. Yet your posted example indicates just the opposite:
```shell
$ mpirun --mca routed direct ....
```
yields an error:
```shell
ORTE was unable to reliably start one or more daemons.
```
The rest of that error output is just a reflection of the primary problem of not being able to start one or more daemons. You cannot route a message to a daemon that failed to start.

So the question is: why can't you start the daemons? You could try something like this:
```shell
$ mpirun --mca routed direct --mca plm_base_verbose 10 --leave-session-attached ...
```
and see what it indicates.

**Comment by victarionmagne** [comment]
``
[magne@magne1700 ~]$ mpirun --mca routed direct --mca plm_base_verbose 10 --leave-session-attached -np 16 --hostfile ~/Host2 mnt/programs/Get_processors.h
[magne1700:01167] mca: base: components_register: registering framework plm components
[magne1700:01167] mca: base: components_register: found loaded component rsh
[magne1700:01167] mca: base: components_register: component rsh register function successful
[magne1700:01167] mca: base: components_register: found loaded component slurm
[magne1700:01167] mca: base: components_register: component slurm register function successful
[magne1700:01167] mca: base: components_register: found loaded component isolated
[magne1700:01167] mca: base: components_register: component isolated has no register or open function
[magne1700:01167] mca: base: components_open: opening plm components
[magne1700:01167] mca: base: components_open: found loaded component rsh
[magne1700:01167] mca: base: components_open: component rsh open function successful
[magne1700:01167] mca: base: components_open: found loaded component slurm
[magne1700:01167] mca: base: components_open: component slurm open function successful
[magne1700:01167] mca: base: components_open: found loaded component isolated
[magne1700:01167] mca: base: components_open: component isolated open function successful
[magne1700:01167] mca:base:select: Auto-selecting plm components
[magne1700:01167] mca:base:select:(  plm) Querying component [rsh]
[magne1700:01167] mca:base:select:(  plm) Query of component [rsh] set priority to 10
[magne1700:01167] mca:base:select:(  plm) Querying component [slurm]
[magne1700:01167] mca:base:select:(  plm) Querying component [isolated]
[magne1700:01167] mca:base:select:(  plm) Query of component [isolated] set priority to 0
[magne1700:01167] mca:base:select:(  plm) Selected component [rsh]
[magne1700:01167] mca: base: close: component slurm closed
[magne1700:01167] mca: base: close: unloading component slurm
[magne1700:01167] mca: base: close: component isolated closed
[magne1700:01167] mca: base: close: unloading component isolated
[magne1700:01167] [[26381,0],0] plm:rsh: final template argv:
        /usr/bin/ssh <template>  orted -mca orte_leave_session_attached "1" -mca ess "env" -mca ess_base_jobid "1728905216" -mca ess_base_vpid "<template>" -mca ess_base_num_procs "2" -mca orte_node_regex "magne[4:1700,1705]@0(2)" -mca orte_hnp_uri "1728905216.0;tcp://192.168.87.23,10.1.1.2:50405" --mca plm_base_verbose "10" -mca plm "rsh" --tree-spawn -mca routed "direct" -mca orte_parent_uri "1728905216.0;tcp://192.168.87.23,10.1.1.2:50405" -mca pmix "^s1,s2,cray,isolated"
[magne1705:01504] mca: base: components_register: registering framework plm components
[magne1705:01504] mca: base: components_register: found loaded component rsh
[magne1705:01504] mca: base: components_register: component rsh register function successful
[magne1705:01504] mca: base: components_open: opening plm components
[magne1705:01504] mca: base: components_open: found loaded component rsh
[magne1705:01504] mca: base: components_open: component rsh open function successful
[magne1705:01504] mca:base:select: Auto-selecting plm components
[magne1705:01504] mca:base:select:(  plm) Querying component [rsh]
[magne1705:01504] mca:base:select:(  plm) Query of component [rsh] set priority to 10
[magne1705:01504] mca:base:select:(  plm) Selected component [rsh]
[magne1705:01504] mca: base: close: component rsh closed
[magne1705:01504] mca: base: close: unloading component rsh
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------


this is what i get

**Comment by victarionmagne** [comment]
```
'[magne@magne1700 ~]$ mpirun --mca routed direct --mca plm_base_verbose 10 --leave-session-attached -np 16 --hostfile ~/Host2 mnt/programs/Get_processors.h
[magne1700:01167] mca: base: components_register: registering framework plm components
[magne1700:01167] mca: base: components_register: found loaded component rsh
[magne1700:01167] mca: base: components_register: component rsh register function successful
[magne1700:01167] mca: base: components_register: found loaded component slurm
[magne1700:01167] mca: base: components_register: component slurm register function successful
[magne1700:01167] mca: base: components_register: found loaded component isolated
[magne1700:01167] mca: base: components_register: component isolated has no register or open function
[magne1700:01167] mca: base: components_open: opening plm components
[magne1700:01167] mca: base: components_open: found loaded component rsh
[magne1700:01167] mca: base: components_open: component rsh open function successful
[magne1700:01167] mca: base: components_open: found loaded component slurm
[magne1700:01167] mca: base: components_open: component slurm open function successful
[magne1700:01167] mca: base: components_open: found loaded component isolated
[magne1700:01167] mca: base: components_open: component isolated open function successful
[magne1700:01167] mca:base:select: Auto-selecting plm components
[magne1700:01167] mca:base:select:(  plm) Querying component [rsh]
[magne1700:01167] mca:base:select:(  plm) Query of component [rsh] set priority to 10
[magne1700:01167] mca:base:select:(  plm) Querying component [slurm]
[magne1700:01167] mca:base:select:(  plm) Querying component [isolated]
[magne1700:01167] mca:base:select:(  plm) Query of component [isolated] set priority to 0
[magne1700:01167] mca:base:select:(  plm) Selected component [rsh]
[magne1700:01167] mca: base: close: component slurm closed
[magne1700:01167] mca: base: close: unloading component slurm
[magne1700:01167] mca: base: close: component isolated closed
[magne1700:01167] mca: base: close: unloading component isolated
[magne1700:01167] [[26381,0],0] plm:rsh: final template argv:
        /usr/bin/ssh <template>  orted -mca orte_leave_session_attached "1" -mca ess "env" -mca ess_base_jobid "1728905216" -mca ess_base_vpid "<template>" -mca ess_base_num_procs "2" -mca orte_node_regex "magne[4:1700,1705]@0(2)" -mca orte_hnp_uri "1728905216.0;tcp://192.168.87.23,10.1.1.2:50405" --mca plm_base_verbose "10" -mca plm "rsh" --tree-spawn -mca routed "direct" -mca orte_parent_uri "1728905216.0;tcp://192.168.87.23,10.1.1.2:50405" -mca pmix "^s1,s2,cray,isolated"
[magne1705:01504] mca: base: components_register: registering framework plm components
[magne1705:01504] mca: base: components_register: found loaded component rsh
[magne1705:01504] mca: base: components_register: component rsh register function successful
[magne1705:01504] mca: base: components_open: opening plm components
[magne1705:01504] mca: base: components_open: found loaded component rsh
[magne1705:01504] mca: base: components_open: component rsh open function successful
[magne1705:01504] mca:base:select: Auto-selecting plm components
[magne1705:01504] mca:base:select:(  plm) Querying component [rsh]
[magne1705:01504] mca:base:select:(  plm) Query of component [rsh] set priority to 10
[magne1705:01504] mca:base:select:(  plm) Selected component [rsh]
[magne1705:01504] mca: base: close: component rsh closed
[magne1705:01504] mca: base: close: unloading component rsh
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
'
```

**Comment by victarionmagne** [comment]
Sorry for bad grammar
It was ment to say
"The recommend fix" is rather than "does fix"

**Comment by rhc54** [comment]
Interesting - ORTE doesn't think anything requires launch of a daemon. Well, probably should add some more debug output.
```shell
$ mpirun --mca routed direct --mca plm_base_verbose 10 --leave-session-attached --mca state_base_verbose 5 --mca ras_base_verbose 10 ...
```

**Comment by rhc54** [comment]
Occurred to me that the lack of output might actually indicate that you didn't configure OMPI in debug mode - please be sure to configure OMPI `--enable-debug` so all of the debug output is available.

**Comment by jsquyres** [comment]
Also, did you check the items that were listed in the error message?

* not finding the required libraries and/or binaries on one or more nodes. Please check your PATH and LD_LIBRARY_PATH settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes. Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base). Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required (e.g., on Cray). Please check your configure cmd line and consider using one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a lack of common network interfaces and/or no route found between them. Please check network connectivity (including firewalls and network routing requirements).

Also, double check that the version of Open MPI that is found in your environment for non-interactive logins is the same version across all nodes.  In simple environments, you might be able to do this by ensuring that all nodes only have a single Open MPI installation, and that it is the same version.

**Comment by Xiang-cd** [comment]
same issue here, build with spack version 4.1.5, all tips the error message hints tested but doesn't work

**Comment by jsquyres** [comment]
@Xiang-cd Just to clarify: you got the same "ORTE was unable to reliably start one or more daemons." message as shown above?

**Comment by Xiang-cd** [comment]
> @Xiang-cd Just to clarify: you got the same "ORTE was unable to reliably start one or more daemons." message as shown above?

yes， I finally solved using version 4.1.6, everything works well, very strange.

**Comment by jsquyres** [comment]
@Xiang-cd Yes, that is strange.

@victarionmagne Have you been able to check the things that the help message directed?

**Comment by victarionmagne** [comment]
Yes sorry for being absent, i currently have the system down, but i shall set it up quickly try the solution above and see if it fixes the problem

**Comment by victarionmagne** [comment]
After running with rhc54's suggestion i get this output
`mpirun --mca routed direct --mca plm_base_verbose 10 --leave-session-attached --mca state_base_verbose 5 --mca ras_base_verbose 10 ...
[magne1700:27631] mca: base: components_register: registering framework plm components
[magne1700:27631] mca: base: components_register: found loaded component rsh
[magne1700:27631] mca: base: components_register: component rsh register function successful
[magne1700:27631] mca: base: components_register: found loaded component slurm
[magne1700:27631] mca: base: components_register: component slurm register function successful
[magne1700:27631] mca: base: components_register: found loaded component isolated
[magne1700:27631] mca: base: components_register: component isolated has no register or open function
[magne1700:27631] mca: base: components_open: opening plm components
[magne1700:27631] mca: base: components_open: found loaded component rsh
[magne1700:27631] mca: base: components_open: component rsh open function successful
[magne1700:27631] mca: base: components_open: found loaded component slurm
[magne1700:27631] mca: base: components_open: component slurm open function successful
[magne1700:27631] mca: base: components_open: found loaded component isolated
[magne1700:27631] mca: base: components_open: component isolated open function successful
[magne1700:27631] mca:base:select: Auto-selecting plm components
[magne1700:27631] mca:base:select:(  plm) Querying component [rsh]
[magne1700:27631] mca:base:select:(  plm) Query of component [rsh] set priority to 10
[magne1700:27631] mca:base:select:(  plm) Querying component [slurm]
[magne1700:27631] mca:base:select:(  plm) Querying component [isolated]
[magne1700:27631] mca:base:select:(  plm) Query of component [isolated] set priority to 0
[magne1700:27631] mca:base:select:(  plm) Selected component [rsh]
[magne1700:27631] mca: base: close: component slurm closed
[magne1700:27631] mca: base: close: unloading component slurm
[magne1700:27631] mca: base: close: component isolated closed
[magne1700:27631] mca: base: close: unloading component isolated
[magne1700:27631] mca: base: components_register: registering framework ras components
[magne1700:27631] mca: base: components_register: found loaded component slurm
[magne1700:27631] mca: base: components_register: component slurm register function successful
[magne1700:27631] mca: base: components_register: found loaded component simulator
[magne1700:27631] mca: base: components_register: component simulator register function successful
[magne1700:27631] mca: base: components_open: opening ras components
[magne1700:27631] mca: base: components_open: found loaded component slurm
[magne1700:27631] mca: base: components_open: component slurm open function successful
[magne1700:27631] mca: base: components_open: found loaded component simulator
[magne1700:27631] mca:base:select: Auto-selecting ras components
[magne1700:27631] mca:base:select:(  ras) Querying component [slurm]
[magne1700:27631] mca:base:select:(  ras) Querying component [simulator]
[magne1700:27631] mca:base:select:(  ras) No component selected!
[magne1700:27631] [[2157,0],0] ACTIVATE JOB [INVALID] STATE PENDING INIT AT plm_rsh_module.c:974
[magne1700:27631] [[2157,0],0] ACTIVATE JOB [2157,1] STATE INIT_COMPLETE AT base/plm_base_launch_support.c:376
[magne1700:27631] [[2157,0],0] ACTIVATE JOB [2157,1] STATE PENDING ALLOCATION AT base/plm_base_launch_support.c:389

======================   ALLOCATED NODES   ======================
        magne1700: flags=0x01 slots=1 max_slots=0 slots_inuse=0 state=UP
=================================================================
[magne1700:27631] [[2157,0],0] ACTIVATE JOB [2157,1] STATE ALLOCATION COMPLETE AT base/ras_base_allocate.c:473
[magne1700:27631] [[2157,0],0] ACTIVATE JOB [2157,1] STATE PENDING DAEMON LAUNCH AT base/plm_base_launch_support.c:204
[magne1700:27631] [[2157,0],0] ACTIVATE JOB [2157,1] STATE ALL DAEMONS REPORTED AT plm_rsh_module.c:1129
[magne1700:27631] [[2157,0],0] ACTIVATE JOB [2157,1] STATE VM READY AT base/plm_base_launch_support.c:183
[magne1700:27631] [[2157,0],0] ACTIVATE JOB [2157,1] STATE PENDING MAPPING AT base/plm_base_launch_support.c:232
[magne1700:27631] [[2157,0],0] ACTIVATE JOB [2157,1] STATE MAP COMPLETE AT base/rmaps_base_map_job.c:507
[magne1700:27631] [[2157,0],0] ACTIVATE JOB [2157,1] STATE PENDING FINAL SYSTEM PREP AT base/plm_base_launch_support.c:262
[magne1700:27631] [[2157,0],0] complete_setup on job [2157,1]
[magne1700:27631] [[2157,0],0] ACTIVATE JOB [2157,1] STATE PENDING APP LAUNCH AT base/plm_base_launch_support.c:489
[magne1700:27631] [[2157,0],0] ACTIVATE JOB [2157,1] STATE SENDING LAUNCH MSG AT base/odls_base_default_fns.c:440
--------------------------------------------------------------------------
Open MPI tried to fork a new process via the "execve" system call but
failed.  Open MPI checks many things before attempting to launch a
child process, but nothing is perfect. This error may be indicative
of another problem on the target host, or even something as silly as
having specified a directory for your application. Your job will now
abort.

  Local host:        magne1700
  Working dir:       /home/magne
  Application name:  ../..
  Error:             Permission denied
--------------------------------------------------------------------------
[magne1700:27631] [[2157,0],0] ACTIVATE PROC [[2157,1],0] STATE FAILED TO START AT base/odls_base_default_fns.c:1059
[magne1700:27631] [[2157,0],0] ACTIVATE PROC [[2157,1],1] STATE FAILED TO START AT base/odls_base_default_fns.c:1059
[magne1700:27631] [[2157,0],0] ACTIVATE PROC [[2157,1],2] STATE FAILED TO START AT base/odls_base_default_fns.c:1059
[magne1700:27631] [[2157,0],0] ACTIVATE PROC [[2157,1],3] STATE FAILED TO START AT base/odls_base_default_fns.c:1059
[magne1700:27631] [[2157,0],0] ACTIVATE JOB NULL STATE DAEMONS TERMINATED AT errmgr_default_hnp.c:502
[magne1700:27631] [[2157,0],0] ACTIVATE PROC [[2157,1],0] STATE IOF COMPLETE AT iof_hnp_read.c:306
[magne1700:27631] [[2157,0],0] ACTIVATE PROC [[2157,1],1] STATE IOF COMPLETE AT iof_hnp_read.c:306
[magne1700:27631] [[2157,0],0] ACTIVATE PROC [[2157,1],2] STATE IOF COMPLETE AT iof_hnp_read.c:306
[magne1700:27631] [[2157,0],0] ACTIVATE JOB NULL STATE DAEMONS TERMINATED AT orted/orted_comm.c:382
[magne1700:27631] [[2157,0],0] ACTIVATE PROC [[2157,1],0] STATE EXITED WITH NON-ZERO STATUS AT base/odls_base_default_fns.c:1738
[magne1700:27631] [[2157,0],0] ACTIVATE JOB NULL STATE DAEMONS TERMINATED AT errmgr_default_hnp.c:502
[magne1700:27631] [[2157,0],0] ACTIVATE PROC [[2157,1],1] STATE EXITED WITH NON-ZERO STATUS AT base/odls_base_default_fns.c:1738
[magne1700:27631] [[2157,0],0] ACTIVATE JOB NULL STATE DAEMONS TERMINATED AT errmgr_default_hnp.c:502
[magne1700:27631] [[2157,0],0] ACTIVATE PROC [[2157,1],2] STATE EXITED WITH NON-ZERO STATUS AT base/odls_base_default_fns.c:1738
[magne1700:27631] [[2157,0],0] ACTIVATE JOB NULL STATE DAEMONS TERMINATED AT errmgr_default_hnp.c:502
--------------------------------------------------------------------------
mpirun was unable to start the specified application as it encountered an
error:

Error code: 1
Error name: (null)
Node: magne1700

when attempting to start process rank 0.
--------------------------------------------------------------------------
4 total processes failed to start
[magne1700:27631] 3 more processes have sent help message help-orte-odls-default.txt / execve error
[magne1700:27631] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[magne1700:27631] mca: base: close: component rsh closed
[magne1700:27631] mca: base: close: unloading component rsh
❯ mpirun --mca routed direct --mca plm_base_verbose 10 --leave-session-attached --mca state_base_verbose 5 --mca ras_base_verbose 10 ... >> log.txt
[magne1700:27641] mca: base: components_register: registering framework plm components
[magne1700:27641] mca: base: components_register: found loaded component rsh
[magne1700:27641] mca: base: components_register: component rsh register function successful
[magne1700:27641] mca: base: components_register: found loaded component slurm
[magne1700:27641] mca: base: components_register: component slurm register function successful
[magne1700:27641] mca: base: components_register: found loaded component isolated
[magne1700:27641] mca: base: components_register: component isolated has no register or open function
[magne1700:27641] mca: base: components_open: opening plm components
[magne1700:27641] mca: base: components_open: found loaded component rsh
[magne1700:27641] mca: base: components_open: component rsh open function successful
[magne1700:27641] mca: base: components_open: found loaded component slurm
[magne1700:27641] mca: base: components_open: component slurm open function successful
[magne1700:27641] mca: base: components_open: found loaded component isolated
[magne1700:27641] mca: base: components_open: component isolated open function successful
[magne1700:27641] mca:base:select: Auto-selecting plm components
[magne1700:27641] mca:base:select:(  plm) Querying component [rsh]
[magne1700:27641] mca:base:select:(  plm) Query of component [rsh] set priority to 10
[magne1700:27641] mca:base:select:(  plm) Querying component [slurm]
[magne1700:27641] mca:base:select:(  plm) Querying component [isolated]
[magne1700:27641] mca:base:select:(  plm) Query of component [isolated] set priority to 0
[magne1700:27641] mca:base:select:(  plm) Selected component [rsh]
[magne1700:27641] mca: base: close: component slurm closed
[magne1700:27641] mca: base: close: unloading component slurm
[magne1700:27641] mca: base: close: component isolated closed
[magne1700:27641] mca: base: close: unloading component isolated
[magne1700:27641] mca: base: components_register: registering framework ras components
[magne1700:27641] mca: base: components_register: found loaded component slurm
[magne1700:27641] mca: base: components_register: component slurm register function successful
[magne1700:27641] mca: base: components_register: found loaded component simulator
[magne1700:27641] mca: base: components_register: component simulator register function successful
[magne1700:27641] mca: base: components_open: opening ras components
[magne1700:27641] mca: base: components_open: found loaded component slurm
[magne1700:27641] mca: base: components_open: component slurm open function successful
[magne1700:27641] mca: base: components_open: found loaded component simulator
[magne1700:27641] mca:base:select: Auto-selecting ras components
[magne1700:27641] mca:base:select:(  ras) Querying component [slurm]
[magne1700:27641] mca:base:select:(  ras) Querying component [simulator]
[magne1700:27641] mca:base:select:(  ras) No component selected!
[magne1700:27641] [[2171,0],0] ACTIVATE JOB [INVALID] STATE PENDING INIT AT plm_rsh_module.c:974
[magne1700:27641] [[2171,0],0] ACTIVATE JOB [2171,1] STATE INIT_COMPLETE AT base/plm_base_launch_support.c:376
[magne1700:27641] [[2171,0],0] ACTIVATE JOB [2171,1] STATE PENDING ALLOCATION AT base/plm_base_launch_support.c:389
[magne1700:27641] [[2171,0],0] ACTIVATE JOB [2171,1] STATE ALLOCATION COMPLETE AT base/ras_base_allocate.c:473
[magne1700:27641] [[2171,0],0] ACTIVATE JOB [2171,1] STATE PENDING DAEMON LAUNCH AT base/plm_base_launch_support.c:204
[magne1700:27641] [[2171,0],0] ACTIVATE JOB [2171,1] STATE ALL DAEMONS REPORTED AT plm_rsh_module.c:1129
[magne1700:27641] [[2171,0],0] ACTIVATE JOB [2171,1] STATE VM READY AT base/plm_base_launch_support.c:183
[magne1700:27641] [[2171,0],0] ACTIVATE JOB [2171,1] STATE PENDING MAPPING AT base/plm_base_launch_support.c:232
[magne1700:27641] [[2171,0],0] ACTIVATE JOB [2171,1] STATE MAP COMPLETE AT base/rmaps_base_map_job.c:507
[magne1700:27641] [[2171,0],0] ACTIVATE JOB [2171,1] STATE PENDING FINAL SYSTEM PREP AT base/plm_base_launch_support.c:262
[magne1700:27641] [[2171,0],0] complete_setup on job [2171,1]
[magne1700:27641] [[2171,0],0] ACTIVATE JOB [2171,1] STATE PENDING APP LAUNCH AT base/plm_base_launch_support.c:489
[magne1700:27641] [[2171,0],0] ACTIVATE JOB [2171,1] STATE SENDING LAUNCH MSG AT base/odls_base_default_fns.c:440
--------------------------------------------------------------------------
Open MPI tried to fork a new process via the "execve" system call but
failed.  Open MPI checks many things before attempting to launch a
child process, but nothing is perfect. This error may be indicative
of another problem on the target host, or even something as silly as
having specified a directory for your application. Your job will now
abort.

  Local host:        magne1700
  Working dir:       /home/magne
  Application name:  ../..
  Error:             Permission denied
--------------------------------------------------------------------------
[magne1700:27641] [[2171,0],0] ACTIVATE PROC [[2171,1],0] STATE FAILED TO START AT base/odls_base_default_fns.c:1059
[magne1700:27641] [[2171,0],0] ACTIVATE PROC [[2171,1],1] STATE FAILED TO START AT base/odls_base_default_fns.c:1059
[magne1700:27641] [[2171,0],0] ACTIVATE PROC [[2171,1],2] STATE FAILED TO START AT base/odls_base_default_fns.c:1059
[magne1700:27641] [[2171,0],0] ACTIVATE PROC [[2171,1],3] STATE FAILED TO START AT base/odls_base_default_fns.c:1059
[magne1700:27641] [[2171,0],0] ACTIVATE JOB NULL STATE DAEMONS TERMINATED AT errmgr_default_hnp.c:502
[magne1700:27641] [[2171,0],0] ACTIVATE PROC [[2171,1],0] STATE IOF COMPLETE AT iof_hnp_read.c:306
[magne1700:27641] [[2171,0],0] ACTIVATE PROC [[2171,1],1] STATE IOF COMPLETE AT iof_hnp_read.c:306
[magne1700:27641] [[2171,0],0] ACTIVATE PROC [[2171,1],2] STATE IOF COMPLETE AT iof_hnp_read.c:306
[magne1700:27641] [[2171,0],0] ACTIVATE JOB NULL STATE DAEMONS TERMINATED AT orted/orted_comm.c:382
[magne1700:27641] [[2171,0],0] ACTIVATE PROC [[2171,1],0] STATE EXITED WITH NON-ZERO STATUS AT base/odls_base_default_fns.c:1738
[magne1700:27641] [[2171,0],0] ACTIVATE JOB NULL STATE DAEMONS TERMINATED AT errmgr_default_hnp.c:502
[magne1700:27641] [[2171,0],0] ACTIVATE PROC [[2171,1],1] STATE EXITED WITH NON-ZERO STATUS AT base/odls_base_default_fns.c:1738
[magne1700:27641] [[2171,0],0] ACTIVATE JOB NULL STATE DAEMONS TERMINATED AT errmgr_default_hnp.c:502
[magne1700:27641] [[2171,0],0] ACTIVATE PROC [[2171,1],2] STATE EXITED WITH NON-ZERO STATUS AT base/odls_base_default_fns.c:1738
[magne1700:27641] [[2171,0],0] ACTIVATE JOB NULL STATE DAEMONS TERMINATED AT errmgr_default_hnp.c:502
--------------------------------------------------------------------------
mpirun was unable to start the specified application as it encountered an
error:

Error code: 1
Error name: (null)
Node: magne1700

when attempting to start process rank 0.
--------------------------------------------------------------------------
[magne1700:27641] 3 more processes have sent help message help-orte-odls-default.txt / execve error
[magne1700:27641] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[magne1700:27641] mca: base: close: component rsh closed
[magne1700:27641] mca: base: close: unloading component rsh`

**Comment by victarionmagne** [comment]
running openmpi 4.1.5
i shall try update now to see if the problem is fixed

**Comment by rhc54** [comment]
If you look at that output, you'll see that OMPI was unable to perform an `execve` to start your application process. Sounds like something is borked in the system or (as the error message indicates) you gave us a directory instead of an app to run as that system call should not fail.

**Comment by jsquyres** [comment]
@victarionmagne Were you ever able to get running?

**Comment by victarionmagne** [comment]
Sorry i was never able to get back on this.
I reorganised my entire system.
Thus i dont have the configuration for the one beforehand.

Im sorry for the inconvenience,
And hope you have a great day.

**Comment by jsquyres** [comment]
Ok.  I'll close this issue; feel free to open a new one if you have problems in the future.
