### ISSUE TITLE
Hang when running Open MPI 4.1.4 from inside a SLURM 23.02 srun session.

### ISSUE THREAD

**Issue by mwheinz** [open-mpi/ompi#11946]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.1.4.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Via an IEFS install.

### Please describe the system on which you are running

* Operating system/version: RHEL 8.6
* Computer hardware: Xeon
* Network type: Ethernet

-----------------------------

## Details of the problem

Need some advice. The problem appears to be related to issue #8378 - jobs run via salloc and ssh run fine, jobs run via srun silently hang.  If I use srun then unset all SLURM environment variables, the job runs so it's pretty clearly an issue with open mpi calling srun. Issue #8378 indicates that a fix was pending in 2021, but we're using version 23.02. 

Any suggestions?

**Comment by rhc54** [comment]
Just to be clear - are you trying to `srun mpirun ...`? If so, that cannot work and never would unless you explicitly tell `mpirun` to use `ssh`. Otherwise, `mpirun` tries to use `srun` under the covers, and you cannot layer the two.

**Comment by mwheinz** [comment]
> Just to be clear - are you trying to `srun mpirun ...`? 

Thanks for the quick reply, Ralph. Yeah, the users of this particular cluster were apparently taught to use "srun <args> --pty /bin/bash" to start an interactive session and then run mpirun. 

Interestingly, they've been doing this for years but it only seems to have become a problem after I upgraded them from SLURM 2019 to SLURM 2023.

I'll inform them that they need to explicitly use ssh.

**Comment by rhc54** [comment]
"srun --pty /bin/bash" is different than what I had stated. This cmd starts an interactive bash shell, so there is no conflict as the Slurm control variables are not present.

If that is failing, then I suspect SchedMD inadvertently re-created the original bug they had to fix before - probably something that needs to be reported to them.

**Comment by mwheinz** [comment]
> "srun --pty /bin/bash" is different than what I had stated. This cmd starts an interactive bash shell, so there is no conflict as the Slurm control variables are not present.
> 

Oh, the SLURM environment variables are definitely present, dozens of them, and it's definitely trying to use srun to launch jobs on remote nodes.

**Comment by rhc54** [comment]
Understood - definitely sounds like SchedMD reintroduced the bug.

**Comment by mwheinz** [comment]
@rhc54 , FYI - the problem appears to only impact Open MPI. If I run the same job with Intel MPI it also uses srun but it does not hang.

**Comment by rhc54** [comment]
> Intel MPI it also uses srun

Hmmm...I don't believe that is true - or at least, it certainly didn't used to be true.

Regardless, it isn't much worth my time to chase this down again. Did it before, SchedMD fixed the problem - but sounds like it has reappeared. 🤷‍♂️ 

It's a rather obscure way to run `salloc`, so I doubt many people would encounter it. May be that SchedMD doesn't find it of enough concern to pursue? Has it been reported to them?

Either way, I don't see much chance that I'll worry about it. Just have them go the normal `salloc` route until Slurm fixes it.

**Comment by mwheinz** [comment]
> > Intel MPI it also uses srun
> 
> Hmmm...I don't believe that is true - or at least, it certainly didn't used to be true.

I actually tested it by running a lengthy MPI job and using ps -ef to look at the processes (I won't bother pasting the output here unless you want me to).
> 
> Regardless, it isn't much worth my time to chase this down again. Did it before, SchedMD fixed the problem - but sounds like it has reappeared. 🤷‍♂️

Agreed.

> Either way, I don't see much chance that I'll worry about it. Just have them go the normal `salloc` route until Slurm fixes it.

No worries.

**Comment by jsquyres** [comment]
@mwheinz Is this issue resolved?

**Comment by mwheinz** [comment]
> @mwheinz Is this issue resolved?

We resolved the issue by teaching the users to use salloc. I don't think there's any action that OpenMPI needs to take at this time.

**Comment by mwheinz** [comment]
Closing.
