### ISSUE TITLE
Cannot configure/build with AppleClang 15.0

### ISSUE THREAD

**Issue by scivision** [open-mpi/ompi#11955]
AppleClang 15.0 compiler was recently released for macOS. I am suddenly unable to configure/build OpenMPI with this new Apple compiler "clang".

The reason I was trying to build OpenMPI is that with AppleClang 15.0, `mpif90 -show` emits `-Wl,-commons` that causes warnings/errors with AppleClang 15.0. But before I could diagnose that separate issue, I have to be able to build OpenMPI.

## Background information

OpenMPI v4.1.5 from a source/distribution tarball with macOS AppleClang 15.0

Since AppleClang 15.0, I am unable to even configure the build for OpenMPI. Before AppleClang 15.0, I have build OpenMPI many different times.

```sh
./configure --prefix=/tmp/openmpi-4.1.5 CC=clang CXX=clang++ FC=gfortran --with-hwloc=internal --disable-shared --enable-static
```

error in
[config-openmpi.log](https://github.com/open-mpi/ompi/files/12772302/config-openmpi.log)

> configure: error: Could not determine global symbol label prefix

### Please describe the system on which you are running

* Operating system/version: macOS 14.0 Sonoma
* Computer hardware: M2 CPU
* Network type: Ethernet

**Comment by jsquyres** [comment]
This has been fixed and will be included in the forthcoming 4.1.6 release.

For the time being, you can get the latest 4.1.6rc (which has the fix) from here: https://www.open-mpi.org/software/ompi/v4.1/
