### ISSUE TITLE
OpenMPI built from source not working on a raspberry pi + mac cluster

### ISSUE THREAD

**Issue by ghltshubh** [open-mpi/ompi#11958]
(Open MPI) 4.1.5 installed from source on raspberry pies and homebrew on macbook m1. 

* Operating system/version: 
  

Macbook M1:

     ProductName:		macOS
     ProductVersion:		14.0
     BuildVersion:		23A344

Raspberry Pi:

     Distributor ID:	Debian
     Description:	Debian GNU/Linux 10 (buster)
     Release:	        10
     Codename:	        buster

* Computer hardware:

     Macbook Air M1 
     Raspberry Pi 4

* Network type: LAN (Raspberries connected via switch that's connected to home router, Macbook m1 connected via wifi to the home router)

-----------------------------

## Details of the problem

I am trying to use macbook m1 as the master in a cluster of 4 raspberry pies (workers, connected to each other with a switch which is connected to my home router to which the mac is connected via wifi). I built OpenMPI (4.1.5) from source for both raspberry pi 4 and the macbook and have configured everything correctly with hosts and hostnames and saved public keys in each raspberry for direct login from the master.

However, when I run

`mpiexec -machinefile machinefile -n 5 python mpi_run.py`

machinefile

```
MacBook-Air.attlocal.net
rpi1
rpi2
rpi3
rpi4
```
mpi_run.py file

```
from mpi4py import MPI
import sys

size = MPI.COMM_WORLD.Get_size()
rank = MPI.COMM_WORLD.Get_rank()
name = MPI.Get_processor_name()

sys.stdout.write(
    "Hello, World! I am process %d of %d on %s.\n"
    % (rank, size, name))
```
a test example it just doesn't output anything. The working animation in the top right of the terminal runs for a few seconds and then nothing happens, no output or error. The mpiexec does run individually on each machine.

**Comment by ggouaillardet** [comment]
First make sure you can SSH passwordless between your M1 and the Raspberry Pi.
You should also disable any firewall running on/between the nodes.

Then try something easier:
```
mpirun --host rpi1 -np 1 hostname
```

you might have to force the network to be used, for example
```
mpirun --mca oob_tcp_if_include 192.168.0.0/24 --mca btl_tcp_if_include 192.168.0.0/24 --host rpi1 -np 1 hostname
```

and see how it goes.

If it hangs, try
```
mpirun --mca plm_base_verbose 100 --mca oob_base_verbose 100 --host rpi1 -np 1 hostname
```

and compress and upload the logs.

**Comment by ghltshubh** [comment]
@ggouaillardet I can ssh passwordless from mac (master) into every Raspberry Pi. I have disabled the macbook firewall as well. Even then 

```
mpirun --host rpi1 -np 1 hostname
```

gets stuck without any output or error. 

Following is the output of 
```
mpirun --mca plm_base_verbose 100 --mca oob_base_verbose 100 --host rpi1 -np 1 hostname
```

```
[MacBook-Air.attlocal.net:12119] mca: base: components_register: registering framework plm components
[MacBook-Air.attlocal.net:12119] mca: base: components_register: found loaded component rsh
[MacBook-Air.attlocal.net:12119] mca: base: components_register: component rsh register function successful
[MacBook-Air.attlocal.net:12119] mca: base: components_register: found loaded component slurm
[MacBook-Air.attlocal.net:12119] mca: base: components_register: component slurm register function successful
[MacBook-Air.attlocal.net:12119] mca: base: components_register: found loaded component isolated
[MacBook-Air.attlocal.net:12119] mca: base: components_register: component isolated has no register or open function
[MacBook-Air.attlocal.net:12119] mca: base: components_open: opening plm components
[MacBook-Air.attlocal.net:12119] mca: base: components_open: found loaded component rsh
[MacBook-Air.attlocal.net:12119] mca: base: components_open: component rsh open function successful
[MacBook-Air.attlocal.net:12119] mca: base: components_open: found loaded component slurm
[MacBook-Air.attlocal.net:12119] mca: base: components_open: component slurm open function successful
[MacBook-Air.attlocal.net:12119] mca: base: components_open: found loaded component isolated
[MacBook-Air.attlocal.net:12119] mca: base: components_open: component isolated open function successful
[MacBook-Air.attlocal.net:12119] mca:base:select: Auto-selecting plm components
[MacBook-Air.attlocal.net:12119] mca:base:select:(  plm) Querying component [rsh]
[MacBook-Air.attlocal.net:12119] mca:base:select:(  plm) Query of component [rsh] set priority to 10
[MacBook-Air.attlocal.net:12119] mca:base:select:(  plm) Querying component [slurm]
[MacBook-Air.attlocal.net:12119] mca:base:select:(  plm) Querying component [isolated]
[MacBook-Air.attlocal.net:12119] mca:base:select:(  plm) Query of component [isolated] set priority to 0
[MacBook-Air.attlocal.net:12119] mca:base:select:(  plm) Selected component [rsh]
[MacBook-Air.attlocal.net:12119] mca: base: close: component slurm closed
[MacBook-Air.attlocal.net:12119] mca: base: close: unloading component slurm
[MacBook-Air.attlocal.net:12119] mca: base: close: component isolated closed
[MacBook-Air.attlocal.net:12119] mca: base: close: unloading component isolated
[MacBook-Air.attlocal.net:12119] mca: base: components_register: registering framework oob components
[MacBook-Air.attlocal.net:12119] mca: base: components_register: found loaded component tcp
[MacBook-Air.attlocal.net:12119] mca: base: components_register: component tcp register function successful
[MacBook-Air.attlocal.net:12119] mca: base: components_open: opening oob components
[MacBook-Air.attlocal.net:12119] mca: base: components_open: found loaded component tcp
[MacBook-Air.attlocal.net:12119] mca: base: components_open: component tcp open function successful
[MacBook-Air.attlocal.net:12119] mca:oob:select: checking available component tcp
[MacBook-Air.attlocal.net:12119] mca:oob:select: Querying component [tcp]
[MacBook-Air.attlocal.net:12119] oob:tcp: component_available called
[MacBook-Air.attlocal.net:12119] WORKING INTERFACE 1 KERNEL INDEX 13 FAMILY: V6
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:tcp:init adding 2600:1700:7b9e:e830:1452:4102:b029:73fd to our list of V6 connections
[MacBook-Air.attlocal.net:12119] WORKING INTERFACE 2 KERNEL INDEX 13 FAMILY: V6
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:tcp:init adding 2600:1700:7b9e:e830:61ad:7e0f:2d4b:e4b5 to our list of V6 connections
[MacBook-Air.attlocal.net:12119] WORKING INTERFACE 3 KERNEL INDEX 13 FAMILY: V6
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:tcp:init adding 2600:1700:7b9e:e830::16 to our list of V6 connections
[MacBook-Air.attlocal.net:12119] WORKING INTERFACE 4 KERNEL INDEX 4 FAMILY: V4
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:tcp:init rejecting loopback interface lo0
[MacBook-Air.attlocal.net:12119] WORKING INTERFACE 5 KERNEL INDEX 5 FAMILY: V4
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:tcp:init adding 192.168.1.66 to our list of V4 connections
[MacBook-Air.attlocal.net:12119] [[31676,0],0] TCP STARTUP
[MacBook-Air.attlocal.net:12119] [[31676,0],0] attempting to bind to IPv4 port 0
[MacBook-Air.attlocal.net:12119] [[31676,0],0] assigned IPv4 port 54907
[MacBook-Air.attlocal.net:12119] [[31676,0],0] attempting to bind to IPv6 port 0
[MacBook-Air.attlocal.net:12119] [[31676,0],0] assigned IPv6 port 54908
[MacBook-Air.attlocal.net:12119] mca:oob:select: Adding component to end
[MacBook-Air.attlocal.net:12119] mca:oob:select: Found 1 active transports
[MacBook-Air.attlocal.net:12119] [[31676,0],0]: get transports
[MacBook-Air.attlocal.net:12119] [[31676,0],0]:get transports for component tcp
[MacBook-Air.attlocal.net:12119] [[31676,0],0] plm:rsh: final template argv:
	/usr/bin/ssh <template>  orted -mca ess "env" -mca ess_base_jobid "2075918336" -mca ess_base_vpid "<template>" -mca ess_base_num_procs "2" -mca orte_node_regex "MacBook-Air,rpi[1:1]@0(2)" -mca orte_hnp_uri "2075918336.0;tcp://192.168.1.66:54907;tcp6://[2600:1700:7b9e:e830:1452:4102:b029:73fd,2600:1700:7b9e:e830:61ad:7e0f:2d4b:e4b5,2600:1700:7b9e:e830::16]:54908" --mca plm_base_verbose "100" --mca oob_base_verbose "100" -mca plm "rsh" --tree-spawn -mca routed "radix" -mca orte_parent_uri "2075918336.0;tcp://192.168.1.66:54907;tcp6://[2600:1700:7b9e:e830:1452:4102:b029:73fd,2600:1700:7b9e:e830:61ad:7e0f:2d4b:e4b5,2600:1700:7b9e:e830::16]:54908" -mca pmix "^s1,s2,cray,isolated"
```

After killing the process

```
^C[MacBook-Air.attlocal.net:12119] [[31676,0],0] OOB_SEND: rml_oob_send.c:265
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:base:send to target [[31676,0],1] - attempt 0
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:base:send unknown peer [[31676,0],1]
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:tcp:send_nb to peer [[31676,0],1]:15 seq = -1
[MacBook-Air.attlocal.net:12119] [[31676,0],0]:[oob_tcp.c:188] processing send to peer [[31676,0],1]:15 seq_num = -1 hop [[31676,0],1] unknown
[MacBook-Air.attlocal.net:12119] [[31676,0],0]:[oob_tcp.c:191] post no route to [[31676,0],1]
[MacBook-Air.attlocal.net:12119] [[31676,0],0] tcp:no route called for peer [[31676,0],1]
[MacBook-Air.attlocal.net:12119] [[31676,0],0] OOB_SEND: oob_tcp_component.c:1123
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:base:send to target [[31676,0],1] - attempt 1
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:base:send unknown peer [[31676,0],1]
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:tcp:send_nb to peer [[31676,0],1]:15 seq = -1
[MacBook-Air.attlocal.net:12119] [[31676,0],0]:[oob_tcp.c:188] processing send to peer [[31676,0],1]:15 seq_num = -1 hop [[31676,0],1] unknown
[MacBook-Air.attlocal.net:12119] [[31676,0],0]:[oob_tcp.c:191] post no route to [[31676,0],1]
[MacBook-Air.attlocal.net:12119] [[31676,0],0] tcp:no route called for peer [[31676,0],1]
[MacBook-Air.attlocal.net:12119] [[31676,0],0] OOB_SEND: oob_tcp_component.c:1123
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:base:send to target [[31676,0],1] - attempt 2
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:base:send unknown peer [[31676,0],1]
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:tcp:send_nb to peer [[31676,0],1]:15 seq = -1
[MacBook-Air.attlocal.net:12119] [[31676,0],0]:[oob_tcp.c:188] processing send to peer [[31676,0],1]:15 seq_num = -1 hop [[31676,0],1] unknown
[MacBook-Air.attlocal.net:12119] [[31676,0],0]:[oob_tcp.c:191] post no route to [[31676,0],1]
[MacBook-Air.attlocal.net:12119] [[31676,0],0] tcp:no route called for peer [[31676,0],1]
[MacBook-Air.attlocal.net:12119] [[31676,0],0] OOB_SEND: oob_tcp_component.c:1123
[MacBook-Air.attlocal.net:12119] [[31676,0],0] oob:base:send to target [[31676,0],1] - attempt 3
[MacBook-Air.attlocal.net:12119] mca: base: close: component rsh closed
[MacBook-Air.attlocal.net:12119] mca: base: close: unloading component rsh
[MacBook-Air.attlocal.net:12119] [[31676,0],0] TCP SHUTDOWN
[MacBook-Air.attlocal.net:12119] [[31676,0],0] TCP SHUTDOWN done
[MacBook-Air.attlocal.net:12119] mca: base: close: component tcp closed
[MacBook-Air.attlocal.net:12119] mca: base: close: unloading component tcp
```

**Comment by ggouaillardet** [comment]
You will also need to disable firewalls running on the rpi if any.

Can you confirm the five machines are in the `192.168.1.0/24` network?

if so, what if you

```
mpirun --mca oob_tcp_if_include 192.168.1.0/24 --host rpi1 -np 1 hostname
```

**Comment by ghltshubh** [comment]
@ggouaillardet Yes, all the 5 machines are in that network. `(192.168.1.66,192.168.1.{73-76})`

I disabled the iptables even though the iptables-service wasn't installed on `rpi1` and tried to connect it but ran into the same issue. The command 
`mpirun --mca oob_tcp_if_include 192.168.1.0/24 --host rpi1 -np 1 hostname` gets stuck without any error or output.

**Comment by ggouaillardet** [comment]
I still suspect there is some firewall, either on your machines or router...

Assuming
`netcat` is installed on your systems, you can

```
nc -l 54907
```
on your M1, and then

```
echo hello | nc 192.168.1.66 54907
```
on `rpi1`. If the connection can be successfully established, both commands will return and `hello` will be output on your M1`

I also noted there are no logs from `rpi` which is suspicious

What if you
```
ssh rpi1 orted
```  
from your M1? it should start but fail shortly.

**Comment by ghltshubh** [comment]
@ggouaillardet I tried netcat and got 
`(UNKNOWN) [192.168.1.66] 54907 (?) : Connection refused`

Earlier I was getting `orted` command not found error. But I found that the shell wasn't able to find the right MPI path in RPis because the `.bashrc` file had a condition that skipped the file to read if the shell was non-interactive. I fixed it and now I am getting 

```
[rpi1:07699] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 135
[rpi1:07699] [[INVALID],INVALID] ORTE_ERROR_LOG: Bad parameter in file util/session_dir.c at line 107
[rpi1:07699] [[INVALID],INVALID] ORTE_ERROR_LOG: Bad parameter in file util/session_dir.c at line 346
[rpi1:07699] [[INVALID],INVALID] ORTE_ERROR_LOG: Bad parameter in file base/ess_base_std_orted.c at line 264
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_session_dir failed
  --> Returned value Bad parameter (-5) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
```

**Comment by ggouaillardet** [comment]
Did you retry `mpirun` after fixing your `.bashrc` ?

let me double check this:
 - `192.168.1.66` is the IP of your M1, right?
 - you did run `echo hello | nc 192.168.1.66 54907` on you `rpi1` while `nc -l 54907` was running in an other window on your M1?

if so, this suggests there are firewall(s) running somewhere on/between your machines.

**Comment by ghltshubh** [comment]
@ggouaillardet Yes I did. Still the same issue.

- Yes, `192.168.1.66` is the macbook ip.
- Correct, I ran `echo hello | nc 192.168.1.66 54907` on rpi1 which I ssh'd into from my macbook while `nc -l 54907` was running in another window on my macbook.

I am not sure what and where to look for firewall. I already disabled iptables.

**Comment by ggouaillardet** [comment]
you can try the same thing between `rpi1` and `rpi2` (after you update the IP) and see how it goes.

If it also fails, that would suggest there is a firewall on your router.
If not, make sure the builtin firewall on your M1 is really disabled and no "antivirus" is running.

**Comment by ghltshubh** [comment]
@ggouaillardet I tried the `netcat` between RPi1 and RPi2.
I did `nc -l 54907` on rpi2 and `echo hello | nc 192.168.1.75 54907` on rpi1. It didn't give any error or refused connection as it was with macbook but it hangs indefinitely without any output or error.

**Comment by ggouaillardet** [comment]
Most home "routers" have the option to assign fix IP addresses to given mac addresses. I recommend you do that so you will never have to update your /etc/hosts (nor DNS, if any). That being said, this is unlikely related to this issue.

double check again there is no firewall on your rpi (`sudo iptables -L` should return no rules)
I suspect your router provides some kind of "isolation" between the systems connected to it (e.g. M1 and rpi), but this is not something I can help you with.

**Comment by ghltshubh** [comment]
@ggouaillardet Thanks for all your help. I will try it however I am little confused because in the openmpi documentation [here](https://docs.open-mpi.org/en/v5.0.0rc7/running-apps/ssh.html#launching-with-ssh) it says that you should be able to login password less from each host to every other host. But the online tutorials that I saw only did password less login from master to every worker node.

**Comment by ghltshubh** [comment]
@ggouaillardet Also sometimes I get this pop up which lasts for a very short time and goes away. I am not sure if this could be causing an issue. 
![image](https://github.com/open-mpi/ompi/assets/16928813/5fb293f2-fb96-47e7-9453-d79ad44f6745)

**Comment by ghltshubh** [comment]
I tried making rpi1 as the master and then doing `mpirun --host rpi1,rpi2,rpi3,rpi4 hostname` and it works fine. I think macbook is blocking the connection somehow but I can't figure it out.

**Comment by ggouaillardet** [comment]
The popup strongly suggests a firewall is running on your mac !

**Comment by ghltshubh** [comment]
@ggouaillardet Yeah seem so but I don't know where the additional firewall could be. I already disabled the default firewall.

**Comment by jsquyres** [comment]
Since you have built/installed Open MPI on all the RPi's, you might want to test the functionality just between the RPi's, and leave your Mac out of it.  That would eliminate the Mac firewalling as an issue.

I don't recall if this was mentioned above, but make sure that all nodes can ssh to each other non-interactively (i.e., `ssh othernode hostname` runs without any password/passphase/etc. prompting).  For a small, 4-node cluster Open MPI should probably run an ssh from the first node to each of the other nodes, but there is a crossover point such that Open MPI will do a tree-based SSH.  I have found that it's easier to just setup ssh-to-all-nodes-non-interactively at the beginning.

**Comment by ghltshubh** [comment]
It worked perfectly with the raspberry pi cluster with one of the raspberry pi as the master but not with the macbook m1 as the master. I am closing the issue for now. Thanks @jsquyres @ggouaillardet

**Comment by jsquyres** [comment]
@ghltshubh FWIW: you might have an endian difference between your Mac and the Pi's...?  You *might* be able to use `--enable-heterogeneous` to get the Mac+Pi run to work.  However, this feature is known to have fallen in to disrepair, and is currently broken: https://docs.open-mpi.org/en/v5.0.x/installing-open-mpi/configure-cli-options/misc.html#miscellaneous-functionality and https://docs.open-mpi.org/en/v5.0.x/tuning-apps/heterogeneity.html (that doc is for the upcoming 5.0.x release, but I'm pretty sure that the note about `--enable-heterogeneous` also applies to the v4.1.x series).
