### ISSUE TITLE
internal_Bcast(107): MPI_Bcast(buffer=0x55abdc081240, count=80, MPI_DATATYPE_NULL, 0, comm=0x84000002) failed

### ISSUE THREAD

**Issue by zly5** [open-mpi/ompi#11969]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

2.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

a source/distribution tarball

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

command：

root@autodl-container-a34a11a952-af0f241d:~/awp_src202309/run_dir# mpirun -n 2 ./pmcl3d \
>  -X 200 -Y 200 -Z 160 -x 1 -y 2 \
>  --TMAX 15.0   --DH 200.0 --DT 0.01 \
>  --NSRC 1 --NST 80  \
> --IFAULT 1 --MEDIASTART 2 --READ_STEP 80 --WRITE_STEP 1500 \
> --NSKPX 1 --NSKPY 1   --NTISKP 1   -c output_ckp/ckp   -o output_sfc   --INSRC input/source_frechetkernel   --INVEL input/mesh_frechetkernel

running result：

rank=0) RS=80, RSG=80, NST=80, IF=1

0 = (0,0)) NX,NY,NZ=200,200,160
nxt,nyt,nzt=200,100,160
rec_N=(200,200,1)
rec_nxt,=200,100,1
NBGX,SKP,END=(1:1:200),(1:1:200),(1:1:1)
rec_nbg,ed=(0,199),(0,99),(0,0)
disp=0

rank=1) RS=80, RSG=80, NST=80, IF=1

1 = (0,1)) NX,NY,NZ=200,200,160
nxt,nyt,nzt=200,100,160
rec_N=(200,200,1)
rec_nxt,=200,100,1
NBGX,SKP,END=(1:1:200),(1:1:200),(1:1:1)
rec_nbg,ed=(0,199),(0,99),(0,0)
disp=80000
filetype size (supposedly=rec_nxt*nyt*nzt*WS*4=120000000) =120000000
rank=0, x_rank_L=-1, x_rank_R=-1, y_rank_F=-1, y_rank_B=1
Before inisource
rank=1, x_rank_L=-1, x_rank_R=-1, y_rank_F=0, y_rank_B=-1
Abort(135343107) on node 0 (rank 0 in comm 0): Fatal error in internal_Bcast: Invalid datatype, error stack:
internal_Bcast(107): MPI_Bcast(buffer=0x55abdc081240, count=80, MPI_DATATYPE_NULL, 0, comm=0x84000002) failed
internal_Bcast(67).: Datatype for argument datatype is a null datatype
Abort(135343107) on node 1 (rank 1 in comm 0): Fatal error in internal_Bcast: Invalid datatype, error stack:
internal_Bcast(107): MPI_Bcast(buffer=0x55796ffb0240, count=80, MPI_DATATYPE_NULL, 0, comm=0x84000001) failed
internal_Bcast(67).: Datatype for argument datatype is a null datatype
root@autodl-container-a34a11a952-af0f241d:~/awp_src202309/run_dir#

**Comment by bosilca** [comment]
1. according to historical documents OMPI 2.1.1 was release in May 2017, a whopping 5 years ago, the end-of-life for the 2 series long passed.
2. OMPI never had an `internal_Bcast` function, can't really help debug that
3. In any case passing `MPI_DATATYPE_NULL` with `count != 0` is illegal, which seems to indicate that the application is doing something that it should not.

**Comment by jsquyres** [comment]
It looks like this might be a bug report against MPICH, and it looks like the example is invalid.

I'm going to close this issue; please re-open if my conclusions are incorrect.
