### ISSUE TITLE
Multi-thread wait can result in an assert failure

### ISSUE THREAD

**Issue by FlorentGermain-Bull** [open-mpi/ompi#11965]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
4.1.5, main (commit 0922d1512dc569f09c02aec4247162503931514c)
MPI_Wait code is similar from OpenMPI 2.x to 5.x on this part

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Built from source, fork based on 4.1.5

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
$ git submodule status
+22fe51cb7a961b6060fc5c48e659237cbe162566 3rd-party/openpmix (v1.1.3-3872-g22fe51cb)
+ece4f3c45a07a069e5b8f9c5e641613dfcaeffc3 3rd-party/prrte (psrvr-v2.0.0rc1-4638-gece4f3c45a)
 c1cfc910d92af43f8c27807a9a84c9c13f4fbc65 config/oac (heads/main)

### Please describe the system on which you are running

* Operating system/version:
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem

```shell
shell$ mpicc -o mt mt.c
shell$ mpirun -n 2 ./mt
```

When multiple threads are waiting on the same request, only the first one is blocked and the other threads fails on an assertion:
mt: ../../ompi/request/request.h:486: ompi_request_wait_completion: Assertion `REQUEST_COMPLETE(req)' failed.

**Comment by FlorentGermain-Bull** [comment]
I probably missed the "add file" button
mt.c:
`
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>
#include <assert.h>
#include <pthread.h>
#include <semaphore.h>
#include <unistd.h>

#define REPEATS 5000
#define WAITERS 64

#define MSG_SIZE 65536

typedef struct {
    MPI_Request req;
    sem_t w2m, m2w, barrier;
} comm_struct;

void * waiter(void *arg)
{
    comm_struct *link = (comm_struct*) arg;

    for (int repeat = 0; repeat < REPEATS; repeat++) {
        /* Wait for master to fill request */
        sem_wait(&link->m2w);

        /* Wait on barrier to prevent threads to pass multiple loop steps at once */
        sem_wait(&link->barrier);

        /* Wait on request */
        MPI_Wait(&link->req, MPI_STATUS_IGNORE);

        /* Signal master that this threads has returned from MPI_Wait */
        sem_post(&link->w2m);
    }

    return arg;
}

void master(comm_struct *link)
{
    int rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    int peer = 1-rank;

    char sbuf[MSG_SIZE];
    char rbuf[MSG_SIZE];

    for (int repeat = 0; repeat < REPEATS; repeat++) {
        /* Post isend, fill request */
        MPI_Isend(sbuf, MSG_SIZE, MPI_CHAR, peer, 0, MPI_COMM_WORLD, &link->req);

        /* Signal threads that request is filled */
        for (int i = 0; i < WAITERS; i++) {
            sem_post(&link->m2w);
        }

        /* Wait until threads are awaken */
        int val;
        do {
            sem_getvalue(&link->m2w, &val);
        } while (val > 0);

        /* Barrier to prevent threads to pass multiple loop steps at once */
        for (int i = 0; i < WAITERS; i++) {
            sem_post(&link->barrier);
        }

        /* Post matching recv */
        MPI_Recv(rbuf, MSG_SIZE, MPI_CHAR, peer, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);

        /* Wait on send request */
        MPI_Wait(&link->req, MPI_STATUS_IGNORE);

        /* Wait for threads to return from MPI_Wait */
        for (int i = 0; i < WAITERS; i++) {
            sem_wait(&link->w2m);
        }
    }
}

int main(int argc, char **argv)
{
    /* THREAD_MULTIPLE init */
    int provided;
    MPI_Init_thread(&argc, &argv, MPI_THREAD_MULTIPLE, &provided);
    assert (provided == MPI_THREAD_MULTIPLE);

    int size;
    MPI_Comm_size(MPI_COMM_WORLD, &size);
    assert (size == 2);

    pthread_t threads[WAITERS];
    comm_struct link;

    /* Init semaphores */
    sem_init(&link.w2m, 0, 0);
    sem_init(&link.m2w, 0, 0);
    sem_init(&link.barrier, 0, 0);

    /* Start threads */
    for (int i = 0; i < WAITERS; i++) {
        pthread_create(&threads[i], NULL, waiter, (void*) &link);
    }

    master(&link);

    /* Wait threads */
    for (int i = 0; i < WAITERS; i++) {
        pthread_join(threads[i], NULL);
    }

    /* Cleanup */
    sem_destroy(&link.w2m);
    sem_destroy(&link.m2w);
    sem_destroy(&link.barrier);

    MPI_Finalize();

    return 0;
}
`

**Comment by jsquyres** [comment]
@FlorentGermain-Bull I'm a little confused by your initial report -- you mention it's Open MPI v4.1.x, but you also report submodules.  There's no git submodules on the v4.1.x. branch.  Can you clarify?

Also, does this happen on the `main` or `v5.0.x` branches?

**Comment by bosilca** [comment]
Concurrent wait from multiple threads on the same request is illegal in the MPI standard.

**Comment by FlorentGermain-Bull** [comment]
> @FlorentGermain-Bull I'm a little confused by your initial report -- you mention it's Open MPI v4.1.x, but you also report submodules. There's no git submodules on the v4.1.x. branch. Can you clarify?
> 
> Also, does this happen on the `main` or `v5.0.x` branches?

The bug was initially observed on 4.1.5 version but I reproduced it with the main branch

**Comment by FlorentGermain-Bull** [comment]
> Concurrent wait from multiple threads on the same request is illegal in the MPI standard.

You are right, 11.6.2 says that concurrent wait is illegal, I missed that one.
