### ISSUE TITLE
Open MPI v5.0.0 RC13 generates PMIX warning

### ISSUE THREAD

**Issue by edgargabriel** [open-mpi/ompi#11964]
Thank you for taking the time to submit an issue!

## Background information

Running a multi-node job with Open MPI 5.0.0RC13 creates PMIX warnings 

```
mpirun --hostfile hostf --map-by package --report-bindings --mca pml ucx -np 2 ./osu_bw
[node018:09897] Rank 0 bound to package[0][core:0]
[node019:08200] Rank 1 bound to package[0][core:0]
[node018:09897] PMIX ERROR: PMIX_ERR_UNPACK_READ_PAST_END_OF_BUFFER in file base/gds_base_fns.c at line 133
[node018:09897] PMIX ERROR: PMIX_ERR_UNPACK_READ_PAST_END_OF_BUFFER in file base/gds_base_fns.c at line 133
[node018:09897] PMIX ERROR: PMIX_ERR_UNPACK_READ_PAST_END_OF_BUFFER in file base/gds_base_fns.c at line 133
[node018:09897] PMIX ERROR: PMIX_ERR_UNPACK_READ_PAST_END_OF_BUFFER in file base/gds_base_fns.c at line 133
...
```
This does not seem to prevent the job from finishing correctly.  It also only seems to happen if the hostfile has more than one entry, i.e. a hostfile with just a single line does not generate this warning (independent of whether the hosts are remote or local).

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

5.0.0 RC13

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
node018:~/edgar/ompi$ git submodule status
 f20e0d5dc6b4028bd1edd469980c5f6ff71014ad 3rd-party/openpmix (v4.2.6)
 63370ca00771a7a6004d6b638476ca794b04e4c1 3rd-party/prrte (v3.0.1)
 c1cfc910d92af43f8c27807a9a84c9c13f4fbc65 config/oac (heads/main)

Maybe as additional information that might relevant: this system does not have a shared file systems across the compute nodes.

**Comment by rhc54** [comment]
> --mca map-by package

New one on me - what is this expected to do??

**Comment by edgargabriel** [comment]
> > --mca map-by package
> 
> New one on me - what is this expected to do??

that is a typo, I played around with so many options. Will fix the output

**Comment by awlauria** [comment]
Does this reproduce on current main?

**Comment by rhc54** [comment]
Not sure why it would have something to do with lack of a shared filesystem, but the root cause is that no modex information was exchanged. There is what looks like a spurious error log in the code - not sure why that is present, but probably some leftover debug from some earlier time.

Anyway, I can remove it. It doesn't exist on the `master` branch, so no problems there.

**Comment by rhc54** [comment]
Also, FWIW: I cannot reproduce this error on my container-based "cluster".

**Comment by rhc54** [comment]
Fix committed to the PMIx v4.2 branch.

**Comment by jsquyres** [comment]
Sweet -- thanks Ralph!  (I was literally going to just go and try to reproduce the issue to try to get more data)

**Comment by lrbison** [comment]
@edgargabriel  Can you clarify which PMIx was being used, was it internal PMIx in rc13 release?

**Comment by edgargabriel** [comment]
it was the internal

**Comment by rhc54** [comment]
If someone wants to update the submodules (you'll have to change to head of their respective release branches), it should be fixed.

**Comment by awlauria** [comment]
For the v5.0.0 release branch we are now pointing to release tags of Pmix and prrte. On main we can submit an update for the hash.

**Comment by rhc54** [comment]
Understood - but obviously, you are going to need to move those release tags before doing your release, yes? Or are you going to ignore all bug fixes from your last rc and just release anyway?

**Comment by rhc54** [comment]
Not for awhile - we just _did_ a release for you guys 😄 

I'm waiting (on both PMIx and PRRTE) to see if we get any more issues raised.

**Comment by awlauria** [comment]
Understood, but this is a bit of an issue for ompi in that successful mpiruns shouldn't have error output :(

@janjust how long could we wait for a new drop?

**Comment by rhc54** [comment]
I don't understand - you don't need a new drop for testing. Just update the submodule pointer to the HEAD of the PMIx v4.2 branch.

**Comment by awlauria** [comment]
Yes we can do that for now. @janjust

**Comment by awlauria** [comment]
@rhc54 to be clear we'll want to point to a released tag of pmix/prrte for ompi final release. We don't put want to push the pointers and revert later if a new release with these fixes can't be done.

**Comment by rhc54** [comment]
Never said a new release can't be done - only that I cannot justify dropping releases at a high frequency. The downstream packagers would be rather distraught with that practice. I'd rather wait to see what other issues emerge and then do _one_ final release, ideally when you are actually ready and committed to releasing.

If the relative timing doesn't work out ideally, remember you will almost certainly have to do a 5.0.1 in a relatively short time - we always do as errors don't show until the general community starts to use it. So you could sweep up any PMIx/PRRTE fixes at that time as well.

@edgargabriel seems to have a unique system that creates this problem - it isn't being seen/reported elsewhere that I have heard about. As I said at the Tues meeting, my patch didn't "fix" any bug - it just silenced the message as the problem wasn't fatal. So I'm not convinced this is a blocking problem for you - certainly not something meriting an emergency release of PMIx.

**Comment by awlauria** [comment]
I agree, sounds good. Thanks @rhc54

**Comment by edgargabriel** [comment]
I can confirm that the warnings are gone with RC14
