### ISSUE TITLE
[5.0.0rc13] ROCm dependency leaks into libmpi.so even with "--enable-mca-dso=yes"

### ISSUE THREAD

**Issue by mkre** [open-mpi/ompi#11971]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

5.0.0rc13

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Compiled from source

## Details of the problem

I am experimenting with 5.0.0rc13. I am trying to build _all_ MCA components as DSOs using `--enable-mca-dso=yes` and enable ROCm support using `--with-rocm`. As expected, I end up with a `mca_accelerator_rocm.so` file in my `lib/openmpi` directory. However, at the same time my top-level `libmpi.so` is having a dependency on `libamdhip64.so.5`. I cannot guarantee that this library will always be available at run time (hence building ROCm support as a DSO), so how can I avoid this link dependency?

**Comment by edgargabriel** [comment]
@mkre would you have a chance to test the fix in https://github.com/edgargabriel/ompi/tree/topic/rocm-ldflags-libs ?  I *think* it resolves the problem, but would like you to confirm it if possible. The current fix is for main, but I would backport it to 5.0 if it fixes the issue (not sure whether it would make it in 5.0.0 or 5.0.1 though)

**Comment by mkre** [comment]
@edgargabriel, with your fix applied, the dependency from `libmpi.so` to `libamdhip64.so` is gone. Thanks!

**Comment by wenduwan** [comment]
@edgargabriel Is this still targeted for the next 5.0 release?

**Comment by edgargabriel** [comment]
@wenduwan yes, the fix is already in master, and the pr to 5.0 has been also filed and approved (but not yet merged)

**Comment by janjust** [comment]
closing, fixed with #12047
