### ISSUE TITLE
MPI-4.0: Missing MPI_ERR_VALUE_TOO_LARGE

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#11973]
As per my recollection, the only thing (besides large count routines) that Open MPI is currently missing from MPI-4.0 is the error class `MPI_ERR_VALUE_TOO_LARGE`. Although this new error class is related to the large-count usage and therefore upcoming Open MPI v5.0.0 will not have a use for it, maybe it for the sake of API completeness it would be good to make it available in next 5.0.0 release?

@jsquyres IIRC, you know very well where and what to touch to implement this addition. Would you please consider doing it?

**Comment by jsquyres** [comment]
@bosilca beat me to it!
