### ISSUE TITLE
main/v5.0: bad Fortran bindings for MPI_PSEND|RECV_INIT

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#11982]
Per https://github.com/open-mpi/ompi/issues/11967#issuecomment-1749118092, regarding the MPI_PSEND_INIT / MPI_PRECV_INIT routines:

* The `mpi_f08` binding has the `count` argument as type `INTEGER` 
    * According to MPI-4.0, this should be `INTEGER(KIND=MPI_COUNT_KIND)`
* The other Fortran bindings has the `count` argument as type `INTEGER`
    * According to MPI-4.0, this should be `INTEGER(KIND=MPI_COUNT_KIND)`

**Comment by lrbison** [comment]
I think this can be closed?
