### ISSUE TITLE
Cannot launch from head node on Big Red due to oob issues

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#12]
Filing this mainly so we don't forget about it...

On Big Red we cannot always launch jobs from the head node to the remote nodes. This seems to be due to the oob not finding the right communication paths.

The networking on Big Red is a bit confusing. There are 3 networks:[[BR]]

1. A Myrinet network which is global to all compute nodes[[BR]]

2. A GigE network which is global[[BR]]

3. A GigE network which is local to each cabinet.

If the compute nodes are in the same cabinet as the head node, we use the cabinet GigE network and are fine. If we launch on a backend node, we find and use the myrinet network (or force it to use the global GigE network) and are fine.

However, if we launch from the head node to nodes which are not in the same cabinet, we do not automatically find the correct network and simply hang. I can get it to launch correctly if I pass "-mca oob_tcp_include eth3,eth1" (the global GigE interfaces on the head node and the compute nodes, respectively).

This doesn't seem to be an issue for others, and since one normally isn't supposed to launch jobs from the head node of Big Red, I'm putting this to 1.3.

**Comment by jsquyres** [comment]
The Big Red machine no longer exists.
