### ISSUE TITLE
Add TCP btl bandwidth detection

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#120]
Per http://www.open-mpi.org/community/lists/devel/2010/09/8461.php, at least on some flavors of Linux, we can get the available TCP bandwidth from /sys/class/net/ethX/speed.  It seems like this would be a useful way to accurately set the btl_bandwidth value, when possible.

**Comment by kmroz** [comment]
In Linux, we can get this via an ioctl(..., SIOCETHTOOL, ...) + ethtool_cmd_speed(). However, this wouldn't work on the BSDs, etc.

@jsquyres - Does OMPI come with some #defines for specific OSs? We could do the ioctl() if Linux, otherwise default to the current 100 Mbit/sec that's being set?

**Comment by jsquyres** [comment]
No, we tend to stay away from OS/version #defines and instead test for desired behavior in configure.  For example, in this case, we could just check to see if `SIOCETHTOOL` exists.  And if so, it's probably a safe enough assumption that it can be used for this `ioctl()`.

Want to make a PR to do that?

**Comment by kmroz** [comment]
Ahh, I see... like you do with ```#ifdef HAVE_SYS_TYPES_H``` etc.

Yes, I will put something together for this.
