### ISSUE TITLE
Open MPI 5.0.0 with PBS Pro support

### ISSUE THREAD

**Issue by kristijan-385** [open-mpi/ompi#12062]
I'm trying to build Open MPI 5.0.0 with PBS Pro support.

I was building versions 4.1.X with `--with-tm="${PBS_ROOT}"` successfully, however, since version 5.0.0, I'm having trouble with the same configure setup. Environment variables such as `CPATH`, `LIBRARY_PATH` and `LD_LIBRARY_PATH` are set within loaded modulefiles beforehand. Also, the errors are the same whether I define the default option `--with-pbs` or not. Also, I'm having trouble differentiating `--with-pbs` (_Build PBS scheduler component_) and `--with-tm` (Build TM (_Torque, PBSPro, and compatible) support_).

I'm using this configure setup:

```
./configure \
  CC="gcc" \
  CXX="g++" \
  FC="gfortran" \
  --prefix="${ID}" \
  --enable-shared \
  --enable-static \
  --with-pbs \
  --with-tm="${PBS_ROOT}"
  --with-tm-libdir="${PBS_ROOT}/lib"
  --with-libfabric="/opt/cray/libfabric/1.15.2.0" \
  --with-libfabric-libdir="/opt/cray/libfabric/1.15.2.0/lib64"
```

The error is:

```
--- MCA component ess:tm (m4 configuration macro)
checking for MCA component ess:tm compile mode... static
checking for pbs-config path... /opt/pbs/bin/pbs-config
checking if pbs-config works... no
checking for tm pkg-config name... /opt/pbs/lib/pkgconfig/tm.pc
checking if tm pkg-config module exists... no
checking for tm header at /opt/pbs/include... found
checking for tm library (pbs) in /opt/pbs/lib... found
checking for tm cppflags... -I/opt/pbs/include
checking for tm ldflags... -L/opt/pbs/lib
checking for tm libs... -lpbs -lcrypto -lz
checking for tm static libs... -lpbs -lcrypto -lz
checking for tm.h... yes
checking for tm_init... no
checking for tm pkg-config name... (cached) /opt/pbs/lib/pkgconfig/tm.pc
checking if tm pkg-config module exists... (cached) no
checking for tm header at /opt/pbs/include... found
checking for tm library (pbs) in /opt/pbs/lib... found
checking for tm cppflags... -I/opt/pbs/include
checking for tm ldflags... -L/opt/pbs/lib
checking for tm libs... -lpbs -lcrypto -lz
checking for tm static libs... -lpbs -lcrypto -lz
checking for tm.h... (cached) yes
checking for tm_init... (cached) no
checking for tm pkg-config name... (cached) /opt/pbs/lib/pkgconfig/tm.pc
checking if tm pkg-config module exists... (cached) no
checking for tm header at /opt/pbs/include... found
checking for tm library (torque) in /opt/pbs/lib... not found
configure: error: TM support requested but not found.  Aborting
configure: ===== done with 3rd-party/prrte configure =====
configure: error: PRRTE configuration failed.  Cannot continue.
```
It seems to me as if `--with-tm` is searching **explicitly** for Torque libraries, but the option states _Torque, PBSPro, and compatible support_.

**Comment by rhc54** [comment]
The option comment should be updated - the `--with-tm` option is explicitly for Torque, not PBS. Altair separated the two out so that you can build to discover the PBS allocation (since PBS is the scheduler) separate from using the Torque launcher. So `--with-pbs` enables discovery of PBS allocations, and `--with-tm` means "use Torque to launch the daemons".  If you haven't installed Torque (which it looks like you didn't), then omit `--with-tm` and we will just use the `ssh` launcher instead.

**Comment by kristijan-385** [comment]
Great, thanks.

**Comment by kristijan-385** [comment]
It seems that PBS integration is working, however, I noticed that environment variables have to be exported via `-x` option. Somewhere else I also found the quote:

`If Open MPI was compiled with native Torque/TM support, the LD_LIBRARY_PATH (and the rest of the environment) should be propagated out to all the nodes in the allocation automatically. If Open MPI wasn't built with the native Torque support, then I'm guessing you're using rsh/ssh to launch, in which case the "-x LD_LIBRARY_PATH" clause is necessary. I'd actually advise re-building OMPI with Torque/TM support; it's better than rsh/ssh support for multiple reasons.`

Since TM option is now separated from PBS, is there an elegant way to export all of the variables?

**Comment by rhc54** [comment]
Set `PRTE_MCA_prte_fwd_environment=true` in your environment and it should do the trick. If you want it to happen on a global basis (i.e., for all users), then you can add `prte_fwd_environment = true` to the PRRTE default param file.

**Comment by kristijan-385** [comment]
> Set `PRTE_MCA_prte_fwd_environment=true` in your environment and it should do the trick. If you want it to happen on a global basis (i.e., for all users), then you can add `prte_fwd_environment = true` to the PRRTE default param file.

That did the trick. 👍
