### ISSUE TITLE
PMIx was unable to find a usable compression library on the system

### ISSUE THREAD

**Issue by fancyerii** [open-mpi/ompi#12070]
I installed openmpi 5.0.0 in ubuntu 20.04. When I run with mpirun, it prints:

```
PMIx was unable to find a usable compression library
on the system. We will therefore be unable to compress
large data streams. This may result in longer-than-normal
startup times and larger memory footprints. We will
continue, but strongly recommend installing zlib or
a comparable compression library for better user experience.

You can suppress this warning by adding "pcompress_base_silence_warning=1"
to your PMIx MCA default parameter file, or by adding
"PMIX_MCA_pcompress_base_silence_warning=1" to your environment.
```

I have installed zlib by:
```
sudo apt install zlib1g-dev
```
and I can find zlib.h in "/usr/include/zlib.h". I also find configure command has found zlib:
```
External Packages
-----------------------
Curl: no (explicitly disabled)
Jansson: no (explicitly disabled)
munge: no (not found)
ZLIB: yes (pkg-config: default search paths)
```
```

**Comment by rhc54** [comment]
You installed the `dev` package, which includes the headers so that the `zlib` support can build. However, you also must install the runtime package that contains the actual `zlib` library so we can use it. Afraid I don't know how ubuntu has named that package - usually it would just be `zlib` as opposed to `zlib-devel`.

**Comment by jsquyres** [comment]
In addition to what @rhc54 said, ensure to install the zlib library on all the nodes where you are running your job, too.

**Comment by fancyerii** [comment]
@jsquyres I have installed zlib with:
```
sudo apt install zlib1g
```
And I can find it by:

```
$ dpkg -L zlib1g
/.
/lib
/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu/libz.so.1.2.11
/usr
/usr/share
/usr/share/doc
/usr/share/doc/zlib1g
/usr/share/doc/zlib1g/changelog.Debian.gz
/usr/share/doc/zlib1g/copyright
/lib/x86_64-linux-gnu/libz.so.1
```
But it still complain no zlib.

**Comment by jsquyres** [comment]
@fancyerii Can you supply all the information requested in the github issue template?

https://github.com/open-mpi/ompi/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by jsquyres** [comment]
In addition to what is asked for in the template, can you also provide:

1. The stdout/stderr from running `configure` (e.g., `./configure ...all your params... |& tee configure.out`)
2. The stdout/stderr from running `make` (e.g., `make |& tee make.out`)
3. The output from running `pmix_info`

Thanks!

**Comment by fancyerii** [comment]
## Background information

### What version of Open MPI are you using? 
I downloaded it from [[openmpi-5.0.0.tar.gz](https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.0.tar.gz)](https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.0.tar.gz)



### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
```
./configure
make
sudo make install
```
you can fined configure output [here](https://gist.github.com/fancyerii/842b1f2700865e464ae33157acc4d2d7),[make output](https://gist.github.com/fancyerii/bb8266d78d215b10e9a2016b8622e68d), [pmix_info result](https://gist.github.com/fancyerii/6dd3fa5ab5c1ab7cf3d36d4e363f3295)

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.



### Please describe the system on which you are running

* Operating system/version: Ubuntu 20.04.6 LTS
* Computer hardware: AMD EPYC 7K62 48-Core Processor 
* Network type: Ethernet controller [0200]: Red Hat, Inc. Virtio network device [1af4:1000

-----------------------------

## Details of the problem
 
```
$ mpirun -np 2 myapp 
--------------------------------------------------------------------------
PMIx was unable to find a usable compression library
on the system. We will therefore be unable to compress
large data streams. This may result in longer-than-normal
startup times and larger memory footprints. We will
continue, but strongly recommend installing zlib or
a comparable compression library for better user experience.

You can suppress this warning by adding "pcompress_base_silence_warning=1"
to your PMIx MCA default parameter file, or by adding
"PMIX_MCA_pcompress_base_silence_warning=1" to your environment.
--------------------------------------------------------------------------
```

**Comment by wenduwan** [comment]
I happen to have a Ubuntu 20.04 machine handy.

I followed @fancyerii installation steps
```
$ wget https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.0.tar.gz
$ tar xf openmpi-5.0.0.tar.gz
$ cd openmpi-5.0.0
$ ./configure
$ sudo make -j install
```

In my case I get pmix error
```
$ mpirun --version
mpirun: error while loading shared libraries: libpmix.so.2: cannot open shared object file: No such file or directory
```

@fancyerii  I'm curious what is the pmix used by mpi, i.e. what is the output of `$ ldd /usr/local/lib/libmpi.so`

**Comment by fancyerii** [comment]
@wenduwan 
```
$ ldd /usr/local/lib/libmpi.so
	linux-vdso.so.1 (0x00007fff5b34a000)
	libopen-pal.so.80 => /usr/local/lib/libopen-pal.so.80 (0x00007fb755280000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb75524a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb755240000)
	libpmix.so.2 => /usr/local/lib/libpmix.so.2 (0x00007fb755037000)
	libhwloc.so.15 => /usr/local/lib/libhwloc.so.15 (0x00007fb754fda000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb754e8b000)
	libevent_core-2.1.so.7 => /usr/local/lib/libevent_core-2.1.so.7 (0x00007fb754e4d000)
	libevent_pthreads-2.1.so.7 => /usr/local/lib/libevent_pthreads-2.1.so.7 (0x00007fb754e48000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb754c56000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb7556fd000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fb754c51000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb754c4b000)
```

**Comment by wenduwan** [comment]
@fancyerii Thanks!

I had to `export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`

Tried a simple launch to verify prrte/pmix
```
$ mpirun --version
mpirun (Open MPI) 5.0.0

Report bugs to https://www.open-mpi.org/community/help/
$ mpirun -n 2 lscpu | grep 'Model name'
Model name:                         AMD EPYC 7R13 Processor
Model name:                         AMD EPYC 7R13 Processor
```

So what does your `LD_LIBRARY_PATH` look like?

**Comment by wenduwan** [comment]
FYI my zlib installation
```
$ sudo apt list --installed | grep zlib

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

zlib1g-dev/focal-updates,focal-security,now 1:1.2.11.dfsg-2ubuntu1.5 amd64 [installed]
zlib1g/focal-updates,focal-security,now 1:1.2.11.dfsg-2ubuntu1.5 amd64 [installed,automatic]
```

**Comment by fancyerii** [comment]
@wenduwan add LD_LIBRARY_PATH do not help
```
$ echo $LD_LIBRARY_PATH 
/usr/local/cuda/lib64
$ export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
$ mpirun --version
mpirun (Open MPI) 5.0.0

Report bugs to https://www.open-mpi.org/community/help/
(failed reverse-i-search)`mpi r': ^Cirun --version
$ mpirun -np 2 myapp 
--------------------------------------------------------------------------
PMIx was unable to find a usable compression library
on the system. We will therefore be unable to compress
large data streams. This may result in longer-than-normal
startup times and larger memory footprints. We will
continue, but strongly recommend installing zlib or
a comparable compression library for better user experience.

You can suppress this warning by adding "pcompress_base_silence_warning=1"
to your PMIx MCA default parameter file, or by adding
"PMIX_MCA_pcompress_base_silence_warning=1" to your environment.
```

**Comment by fancyerii** [comment]
> sudo apt list --installed | grep zlib

```
$ sudo apt list --installed | grep zlib

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

zlib1g-dev/focal-security,focal-updates,now 1:1.2.11.dfsg-2ubuntu1.5 amd64 [installed]
zlib1g/focal-security,focal-updates,now 1:1.2.11.dfsg-2ubuntu1.5 amd64 [installed]
zlibc/focal,now 0.9k-4.3 amd64 [installed]
```

**Comment by fancyerii** [comment]
> $ mpirun -n 2 lscpu | grep 'Model name'

```
$ mpirun -n 2 lscpu | grep 'Model name'
--------------------------------------------------------------------------
PMIx was unable to find a usable compression library
on the system. We will therefore be unable to compress
large data streams. This may result in longer-than-normal
startup times and larger memory footprints. We will
continue, but strongly recommend installing zlib or
a comparable compression library for better user experience.

You can suppress this warning by adding "pcompress_base_silence_warning=1"
to your PMIx MCA default parameter file, or by adding
"PMIX_MCA_pcompress_base_silence_warning=1" to your environment.
--------------------------------------------------------------------------
Model name:                         AMD EPYC 7K62 48-Core Processor
Model name:                         AMD EPYC 7K62 48-Core Processor
```

**Comment by jsquyres** [comment]
> In addition to what is asked for in the template, can you also provide:
> 
> 1. The stdout/stderr from running `configure` (e.g., `./configure ...all your params... |& tee configure.out`)
> 2. The stdout/stderr from running `make` (e.g., `make |& tee make.out`)
> 3. The output from running `pmix_info`
> 
> Thanks!

**Comment by wenduwan** [comment]
@fancyerii From the provided information I don't see anything wrong with the installation(log shows libz was found). I wonder if you have special environment settings?

I checked my system
```
$ mpirun -n 2 --mca pcompress_base_verbose 10 /sbin/ldconfig  -v | grep libz
[ip-172-31-23-179:212923] mca: base: component_find: searching NULL for pcompress components
[ip-172-31-23-179:212923] mca: base: find_dyn_components: checking NULL for pcompress components
[ip-172-31-23-179:212923] pmix:mca: base: components_register: registering framework pcompress components
[ip-172-31-23-179:212923] pmix:mca: base: components_register: found loaded component zlib
[ip-172-31-23-179:212923] pmix:mca: base: components_register: component zlib has no register or open function
[ip-172-31-23-179:212923] mca: base: components_open: opening pcompress components
[ip-172-31-23-179:212923] mca: base: components_open: found loaded component zlib
[ip-172-31-23-179:212923] mca:base:select: Auto-selecting pcompress components
[ip-172-31-23-179:212923] mca:base:select:(pcompress) Querying component [zlib]
[ip-172-31-23-179:212923] mca:base:select:(pcompress) Query of component [zlib] set priority to 50
[ip-172-31-23-179:212923] mca:base:select:(pcompress) Selected component [zlib]
/sbin/ldconfig.real: Path `/usr/local/cuda-12/targets/x86_64-linux/lib' given more than once
/sbin/ldconfig.real: Path `/usr/local/cuda-12.3/targets/x86_64-linux/lib' given more than once
/sbin/ldconfig.real: Path `/usr/local/cuda-12/targets/x86_64-linux/lib' given more than once
/sbin/ldconfig.real: Path `/usr/local/cuda-12.3/targets/x86_64-linux/lib' given more than once
/sbin/ldconfig.real: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib' given more than once
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib' given more than once
/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.31.so is the dynamic linker, ignoring

/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.31.so is the dynamic linker, ignoring

	libzstd.so.1 -> libzstd.so.1.4.4
	libzstd.so.1 -> libzstd.so.1.4.4
	libz.so.1 -> libz.so.1.2.11
	libz.so.1 -> libz.so.1.2.11
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
``` 

The logging should provide more hints.

**Comment by jsquyres** [comment]
And @wenduwan pointed out that you linked the information I asked for, and I totally missed it.  Oops!

**Comment by jsquyres** [comment]
@fancyerii  I looked at this with @wenduwan this morning.  Here's what we found:

* You're building Open MPI against an already-installed PMIx (what we call an "external" PMIx).
    * Specifically: Open MPI is ignoring the copy of the PMIx that is bundled ("internal") to the Open MPI source tree, and is just using the external PMIx.
* It looks like this external PMIx is in `/usr/local`.
* The PMIx that is installed there does not support the zlib compression.  This is why you are getting this warning message.
    * I'm guessing that the PMIx that is already installed in `/usr/local` was built+installed before you had the zlib headers installed.  Hence, it built itself without zlib support.

You have a few choices:

1. The warning message tells you how to disable the warning message.  If you're only launching at small scale (e.g., 16 or less nodes), compression probably does not matter, and disabling the warning is probably a "good enough" solution.
2. You can remove the PMIx from `/usr/local` and let Open MPI build with its own ("internal") PMIx.  Since the zlib headers are now present, the internal PMIx will build with zlib support, and the warning message will disappear.
3. You can re-build / re-install the PMIx in `/usr/local` with zlib support.  Since the zlib headers are available, just doing a default build again will likely include zlib support, and the warning message will disappear.

Does that make sense?

**Comment by fancyerii** [comment]
@jsquyres I can find "/usr/local/lib/libpmix.so". I think I can ignore this for now. I don't know much of PMIx and it's not installed by me. I find some information here(https://packages.ubuntu.com/source/focal/pmix).It seems that libpmix is installed by ubuntu's package mananger. If it's true, apt install will automatically install dependency like zlib1g-dev.

**Comment by jsquyres** [comment]
> It seems that libpmix was installed by ubuntu's package mananger. If it's true, apt install will automatically install dependency like zlib1g-dev.

Sort of.

First off, if you want to know what PMIx is / why Open MPI uses it, see https://docs.open-mpi.org/en/v5.0.x/installing-open-mpi/required-support-libraries.html.

If Apt installed something that needs PMIx, then it will install PMIx and whatever PMix requires to *run*.  It does not necessarily install what PMIx -- or things that use PMIx, like OMPI -- need to *compile*.

More specifically: if you're installing the Ubuntu binary package for PMIx, if that Ubuntu PMIx package has support for zlib, then it will likely require the corresponding Ubuntu zlib package, but it will *not* require the zlib-dev package (because that package is only needed for *building* PMIx, not *running* PMIx).  That's a big "if", though -- I don't know if the Ubuntu PMIx binary package includes zlib support or not.
