### ISSUE TITLE
Build error on macOS (`PATH_MAX` undeclared)

### ISSUE THREAD

**Issue by eschnett** [open-mpi/ompi#12108]
I am building OpenMPI 5.0.0 on macOS with a MacPorts-installed GCC 13.2.

My configure options are
```
$ ./configure --prefix=$HOME/openmpi-5.0.0 --with-libevent=internal CC=gcc CXX=g++ FC=gfortran
```

This fails with the error message
```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/stdio.h:409,
                 from ./include/mpl_base.h:14,
                 from ./include/mpl.h:9,
                 from src/str/mpl_str.c:6:
src/str/mpl_str.c: In function 'MPL_create_pathname':
src/str/mpl_str.c:413:37: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'AF_MAX'?
  413 |         MPL_snprintf(dest_filename, PATH_MAX, "%s/%s.%u.%u%c", dirname, prefix,
      |                                     ^~~~~~~~
```

This refers to the file `3rd-party/romio341/mpl/src/str/mpl_str.c` (I wish that was reported directly in the error message). Adding the line `#include <sys/syslimits.h>` to the beginning of this file resolves the error.

**Comment by bosilca** [comment]
According to [POSIX](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/limits.h.html), `PATH_MAX` might be omitted from `<limits.h>` if 
> the corresponding value is equal to or greater than the stated minimum, but where the value can vary depending on the file to which it is applied.

Anyway, PR on the way.
