### ISSUE TITLE
Mismatched double-quote in preprocessor error message

### ISSUE THREAD

**Issue by tonycurtis** [open-mpi/ompi#12116]
Thank you for taking the time to submit an issue!

## Background information

Compiler message indicates mismatched quote.  Compile doesn't fall over since the reported feature supported.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

main @ 3862c748a2b9761fe280fcc541cca7187407929f

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

clone

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

```
 9095457b2c5b2370178a9a0ffaff7a6918af632e 3rd-party/openpmix (v1.1.3-3932-g9095457b)
 066b56055c4f9017a581dc472864c9e2d8c189cc 3rd-party/prrte (psrvr-v2.0.0rc1-4706-g066b56055c)
 c1cfc910d92af43f8c27807a9a84c9c13f4fbc65 config/oac (heads/main)
```

### Please describe the system on which you are running

* Operating system/version: Rocky 9.2
* Computer hardware: x86_64
* Network type: IBV

-----------------------------

## Details of the problem

```
ompi/instance/instance.c:70:#error "No support for recursive mutexes available on this platform.
```

**Comment by hppritcha** [comment]
@jsquyres can this issue be closed?

**Comment by jsquyres** [comment]
> @jsquyres can this issue be closed?

Yes -- thanks for noticing @hppritcha
