### ISSUE TITLE
Nonconforming MPI_APPNUM with mpiexec

### ISSUE THREAD

**Issue by jedbrown** [open-mpi/ompi#12127]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.1.5

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Arch Linux package manager

### Please describe the system on which you are running

* Operating system/version: Arch Linux
* Computer hardware: x86-64
* Network type: N/A

-----------------------------

## Details of the problem

MPI-4.1 (similar wording since at least MPI-2.1) states that `mpiexec spec0 : spec1 : spec2` sets distinct values for the `MPI_APPNUM` attribute.

<details>

![image](https://github.com/open-mpi/ompi/assets/3303/aebebdb2-49a1-46ef-8077-c1833bcc3b5b)
</details>

 The following demonstrates that OMPI's implementation of `MPI_APPNUM` is nonconforming:

```c
#include <assert.h>
#include <mpi.h>
#include <stdio.h>

int main(int argc, char **argv) {
  MPI_Init(&argc, &argv);
  MPI_Comm comm = MPI_COMM_WORLD;
  int rank, size, found, *appnum;
  MPI_Comm_size(comm, &size);
  MPI_Comm_rank(comm, &rank);
  MPI_Comm_get_attr(comm, MPI_APPNUM, &appnum, &found);
  assert(found == 1);
  printf("[%d/%d] appnum %d\n", rank, size, *appnum);
  MPI_Finalize();
}
```
and build/run with
```console
$ mpicc appnum.c -o appnum
$ mpiexec -n 1 ./appnum : -n 2 ./appnum : -n 1 ./appnum
[0/4] appnum 0
[1/4] appnum 0
[2/4] appnum 0
[3/4] appnum 0
```

The MPICH implementation is conforming
```console
$ /opt/mpich/bin/mpiexec -n 1 ./appnum : -n 2 ./appnum : -n 1 ./appnum
[0/4] appnum 0
[1/4] appnum 1
[2/4] appnum 1
[3/4] appnum 2
```

I noticed this while unit testing my Rust implementation with `MPI_Comm_spawn_multiple`. I believe OMPI's `MPI_APPNUM` is also nonconforming with that starting procedure, but I didn't bother creating a stand-alone C reproducer.

**Comment by ggouaillardet** [comment]
FWIW, it works for me on a Mac with Open MPI 4.1.4 provived by `homebrew`:

```
$ mpiexec -V
mpiexec (OpenRTE) 4.1.5

Report bugs to http://www.open-mpi.org/community/help/
$ mpiexec -n 1 ./appnum : -n 2 ./appnum : -n 1 ./appnum
[0/4] appnum 0
[1/4] appnum 1
[2/4] appnum 1
[3/4] appnum 2
```

I will double check on archlinux.

**Comment by ggouaillardet** [comment]
I was able to reproduce the issue on `archlinux`.

That could be related to the fact `archlinux` is using an external `PMIx 4.2.6` when `homebrew` is using the builtin `PMIx 3.2.4`

**Comment by ggouaillardet** [comment]
So here is the status on `archlinux`:
 - default: `4.1.5` with external `PMIx 4.2.6`: KO
 - rebuild: `4.1.5` with internal `PMIx`: OK
 - rebuild: `4.1.6` with external `PMIx 4.2.6`: OK

At this stage, I would simply wait for the fine folks at `archlinux` update Open MPI to the latest `4.1.6` or `5.0.0`

**Comment by jedbrown** [comment]
Fascinating. I built 4.1.6 and indeed, the issue goes away with both `mpiexec` and `MPI_Comm_spawn_multiple`. Thanks.
