### ISSUE TITLE
Concerning warnings in OSC rdma

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#12130]
In `main` and `v5.0.x`, the following concerning compiler warnings are emitted for the `rdma` OSC component:

```
  CC       osc_rdma_accumulate.lo
osc_rdma_accumulate.c:179:22: warning: assigning to 'void *' from 'const void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        compare_copy = compare_addr;
                     ^ ~~~~~~~~~~~~
osc_rdma_accumulate.c:865:41: warning: passing 'const void *' to parameter of type 'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                                        compare_copy, compare_addr, len, MCA_ACCELERATOR_TRANSFER_DTOH);
                                        ^~~~~~~~~~~~
osc_rdma_accumulate.c:878:14: warning: passing 'const void *' to parameter of type 'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        free(compare_copy);
             ^~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/malloc/_malloc.h:47:18: note: passing argument to parameter here
void  free(void *);
                 ^
3 warnings generated.
```

I generated these warnings with clang 15 on macOS Sonoma 14.1.1, but I'm betting that similar warnings will be emitted on other OSs / compilers / versions.

Note that I did fix some *other* compiler warnings in the `rdma` OSC component in https://github.com/open-mpi/ompi/pull/12129; hence, the warnings above are what are *left* after fixing those other warnings.

These warnings seem serious, but I don't grok the code well enough to properly assess and/or fix them.  I tried a few simple things, but that led down a rabbit hole of `const`-related side issues.  It will probably be better for someone who already understands what this code is meant to be doing to have a look at these warnings.

Can someone have a look?

**Comment by devreal** [comment]
I had posted a PR that fixes this a while back and totally forgot about it: https://github.com/open-mpi/ompi/pull/11500

**Comment by devreal** [comment]
Oh wait, never mind. That's  different set of warnings that I had not seen before. I will take a look.

**Comment by janjust** [comment]
@devreal just curious if you had any chance to look into this.
