### ISSUE TITLE
How to exit process gracefully when get signal SIGTERM？

### ISSUE THREAD

**Issue by pineleen** [open-mpi/ompi#12149]
### What version of Open MPI are you using? 
4.1.5a1

### Describe how Open MPI was installed 
Ubuntu 20.04  distribution package

### Please describe the system on which you are running
Ubuntu 20.04, intel x86_64 cpu

-----------------------------

## Details of the problem
In my code, I need to wait about 1min after get sigterm for graceful process exit.  but mpirun just "waiting a small number of seconds, then sending all processes in the job a SIGKILL." described in https://docs.open-mpi.org/en/v5.0.x/man-openmpi/man1/mpirun.1.html#signal-propagation .  

And I can't find the option to set the number of seconds. 

So, how can I exit my process gracefully?

```
#include <mpi.h>
#include <chrono>
#include <thread>
#include <iostream>
#include <csignal>

volatile bool g_stop = false;
void signalHandler(int signum) {
    std::cout << "get signal: " << signum  << std::endl;
    if (signum == SIGTERM) {
        g_stop = true;
    }
}

int main(int argc, char* argv[])
{
    MPI_Init(&argc, &argv);
    std::signal(SIGTERM, signalHandler);

    int rank = 0;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    while(!g_stop){
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
    
    for (int i=0; i<60; i++){
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
        std::cout << rank << ", graceful exiting: " << i << std::endl;
    }

    MPI_Finalize();
    std::cout << rank << ", main finish!" << std::endl;
    return 0;
}
```

```shell
shell$ mpic++ main.cc -o main -g
shell$ mpirun -n 2 ./main
shell$ kill -15 pid_of_mpirun
```

the logs:
```
get signal: 15
1, graceful exiting: 0
1, graceful exiting: 1
1, graceful exiting: 2
1, graceful exiting: 3
1, graceful exiting: 4
1, graceful exiting: 5
1, graceful exiting: 6
1, graceful exiting: 7
1, graceful exiting: 8
get signal: 15
0, graceful exiting: 0
0, graceful exiting: 1
0, graceful exiting: 2
0, graceful exiting: 3
0, graceful exiting: 4
0, graceful exiting: 5
0, graceful exiting: 6
0, graceful exiting: 7
0, graceful exiting: 8
```

I appreciate if you could please help me fix the issue.

**Comment by rhc54** [comment]
Add `--mca odls_base_sigkill_timeout 60` or however many seconds you want to wait.

**Comment by pineleen** [comment]
> Add `--mca odls_base_sigkill_timeout 60` or however many seconds you want to wait to the `mpirun` cmd line
It does work. Thanks for your reply.
