### ISSUE TITLE
prrte submodule pointer bump broke --report-bindings

### ISSUE THREAD

**Issue by wenduwan** [open-mpi/ompi#12143]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

main and v5.0.x

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Build from source

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

```
 9095457b2c5b2370178a9a0ffaff7a6918af632e 3rd-party/openpmix (v1.1.3-3932-g9095457b)
 066b56055c4f9017a581dc472864c9e2d8c189cc 3rd-party/prrte (psrvr-v2.0.0rc1-4706-g066b56055c)
 c1cfc910d92af43f8c27807a9a84c9c13f4fbc65 config/oac (heads/main)
```

### Please describe the system on which you are running

* Operating system/version: Amazon Linux 2
* Computer hardware: EC2
* Network type: EFA

-----------------------------

## Details of the problem

We recently bumped prrte submodule pointer in main and v5.0.x branch. After this, `mpirun --report-bindings ...` segfaults

- main branch: https://github.com/open-mpi/ompi/commit/2f9cabf741bd2d3c75e607a53d06466af0ec134d
- v5.0.x branch: https://github.com/open-mpi/ompi/commit/15bfea8adefdb4deb3d1f328c9807b128720e27b

**Comment by wenduwan** [comment]
The issue is fixed in https://github.com/openpmix/prrte/pull/1878

Now we need to bump prrte pointer in both main and v5.0.x

I'm ok with doing that on main, but v5.0.0x needs a release tag soon(like on 12/8).

**Comment by wenduwan** [comment]
Hey @rhc54,  we are about to start 5.0.1 RC process - we would like to ingest a new prrte release or RC with the known bugfixes. Could you provide an ETA for that?

**Comment by rhc54** [comment]
Should be done this evening.

**Comment by rhc54** [comment]
Here you go...

https://github.com/openpmix/openpmix/releases/tag/v4.2.8rc1

https://github.com/openpmix/prrte/releases/tag/v3.0.3rc1

**Comment by wenduwan** [comment]
@rhc54 Thank you very much!
