### ISSUE TITLE
cuda support

### ISSUE THREAD

**Issue by fxz08** [open-mpi/ompi#12148]
Please submit all the information below so that we can understand the working environment that is the context for your question.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
5.1.0a1
### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

from a git clone

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

9095457b2c5b2370178a9a0ffaff7a6918af632e 3rd-party/openpmix (v1.1.3-3932-g9095457b)
 4676a3cb8f7eabde919f19bf70b1d211a79c2b6d 3rd-party/prrte (psrvr-v2.0.0rc1-4715-g4676a3cb8f)
 c1cfc910d92af43f8c27807a9a84c9c13f4fbc65 config/oac (heads/main)

### Please describe the system on which you are running

* Operating system/version:    ubuntu/20.04
* Computer hardware:    nvidia tesla p100
* Network type:

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

I use './configure --prefix=/usr/local/openmpi --with-ucx=/usr/local/ucx  --with-cuda=/usr/local/cuda-11.2' to install ,but cuda support is no.

CUDA support: no
Intel ZE support: no
ROCm support: no

**Comment by bosilca** [comment]
I guess it is because libcuda.so is not installed in `/usr/local/cuda-11.2/lib64`. I have a similar issue on some clusters and I solved it by explicitly pointing to the CUDA stubs using `--with-cuda-libdir`. In my environment this is `--with-cuda-libdir=/usr/local/cuda-11.2/lib64/stubs`.

**Comment by fxz08** [comment]
Thank you for your advice,  In my environment libcuda.so is also installed in '/usr/local/cuda-11.2/lib64/stubs',  I have solved it by --with-cuda-libdir.
