### ISSUE TITLE
Build issue with internal libevent on macOS with Apple clang + gfortran-12

### ISSUE THREAD

**Issue by mathomp4** [open-mpi/ompi#12168]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Open MPI 5.0.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

I tried installing Open MPI two ways:

1. `../configure CC=clang CXX=clang++ FC=gfortran-12 --prefix=$HOME/installed/Compiler/clang-gfortran-12/openmpi/5.0.0 |& tee configure.clang-gfortran-12.log`
2. `../configure CC=clang CXX=clang++ FC=gfortran-12 --withlibevent=internal --with-pmix=internal --prefix=$HOME/installed/Compiler/clang-gfortran-12/openmpi/5.0.0 |& tee configure.clang-gfortran-12.log`

### Please describe the system on which you are running

* Operating system/version: macOS 13.6.3
* Computer hardware: Apple M1 Max
* Network type: Internal (desktop)

* C compiler: Apple clang version 15.0.0
* C++ compiler: Apple clang version 15.0.0
* Fortran compiler: GNU Fortran (Homebrew GCC 12.3.0) 12.3.0

-----------------------------

## Details of the problem

I am having a build-time issue with Open MPI 5.0.0. Note, that I *didn't* have this issue with Open MPI 5.0.0rc12 in the past, but I seem to now.

To wit, I first tried configuring with the first `configure` line above:
```
../configure CC=clang CXX=clang++ FC=gfortran-12 --prefix=$HOME/installed/Compiler/clang-gfortran-12/openmpi/5.0.0 |& tee configure.clang-gfortran-12.log
```
but got:
```
...
checking will libev support be built... no
configure: WARNING: Either libevent or libev support is required, but neither
configure: WARNING: was found. Please use the configure options to point us
configure: WARNING: to where we can find one or the other library
configure: error: Cannot continue
configure: ===== done with 3rd-party/openpmix configure =====
configure: error: Could not find viable pmix build.
```
So, okay, I then added `--with-pmix=internal --with-libevent=internal` to try and get around this, and doing so, `configure` completed. But when I try to `make` I get:
```
make -j6 |& tee make.clang-gfortran-12.log
...
  CCLD     libevent_pthreads.la
ld: Undefined symbols:
  _event_mm_free_, referenced from:
      _evthread_posix_lock_alloc in evthread_pthread.o
      _evthread_posix_lock_free in evthread_pthread.o
      _evthread_posix_cond_alloc in evthread_pthread.o
      _evthread_posix_cond_free in evthread_pthread.o
  _event_mm_malloc_, referenced from:
      _evthread_posix_lock_alloc in evthread_pthread.o
      _evthread_posix_cond_alloc in evthread_pthread.o
  _evthread_set_condition_callbacks, referenced from:
      _evthread_use_pthreads in evthread_pthread.o
  _evthread_set_id_callback, referenced from:
      _evthread_use_pthreads in evthread_pthread.o
  _evthread_set_lock_callbacks, referenced from:
      _evthread_use_pthreads in evthread_pthread.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libevent_pthreads.la] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

As far as I can tell, these are all from libevent and I'm using the *internal* version. Is there perhaps some library I need from Brew to get this to work?

**Comment by mathomp4** [comment]
As a test, I tried building with all gcc (`CC=gcc-12`, `CXX=g++-12`, and `FC=gfortran-12`) and that worked.

So, on a whim I decided to try adding ye olde `LDFLAGS='-Wl,-ld_classic'` to the clang-gfortran build, but...no go. Same error. ☹️

**Comment by jsquyres** [comment]
@mathomp4 Can you try with the 5.0.1rc?  https://www.open-mpi.org/software/ompi/v5.0/

**Comment by mathomp4** [comment]
@jsquyres I just grabbed it (didn't know it was out!) and sadly, no go. I'm attaching the `make V=1` I get once it's at the crash.

[make.serial.log](https://github.com/open-mpi/ompi/files/13719611/make.serial.log)

**Comment by mathomp4** [comment]
Ohhhh. I have a thought! I have been able to build Open MPI 5.0.0 on my M2 Mac but not on this M1. I just took a look and the modulefile and they are slightly different! One moment please...

**Comment by mathomp4** [comment]
Well, that is fun. So it turns out the issue is with this code in my modulefile:

```lua
-- We used to do this in zshrc 
--   #export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion)
-- but that interfered with...something. So we do it here. Note
-- that we need to chomp the newline from the subprocess call.
local sw_vers = subprocess("sw_vers -productVersion"):gsub("\n$","")
setenv("MACOSX_DEPLOYMENT_TARGET",sw_vers)
```

The annoying thing is that when I committed that code all I put in the commit message was `Readd MACOSX_DEPLOYMENT_TARGET`. I want to say it was to suppress a zillion warnings when I run CMake on a model of ours? 

Well, simple fix, but any idea why setting `MACOSX_DEPLOYMENT_TARGET` would foobar up libevent?

**Comment by jsquyres** [comment]
> any idea why setting `MACOSX_DEPLOYMENT_TARGET` would foobar up libevent?

Nope. ☹️

**Comment by mathomp4** [comment]
> > any idea why setting `MACOSX_DEPLOYMENT_TARGET` would foobar up libevent?
> 
> Nope. ☹️

That sounds about right with my experience with that variable. I mean, I do see it in the libevent tarball's `configure`:
```
    case $host_os in
    rhapsody* | darwin1.[012])
      _lt_dar_allow_undefined='$wl-undefined ${wl}suppress' ;;
    darwin1.*)
      _lt_dar_allow_undefined='$wl-flat_namespace $wl-undefined ${wl}suppress' ;;
    darwin*) # darwin 5.x on
      # if running on 10.5 or later, the deployment target defaults
      # to the OS version, if on x86, and 10.4, the deployment
      # target defaults to 10.4. Don't you love it?
      case ${MACOSX_DEPLOYMENT_TARGET-10.0},$host in
        10.0,*86*-darwin8*|10.0,*-darwin[91]*)
          _lt_dar_allow_undefined='$wl-undefined ${wl}dynamic_lookup' ;;
        10.[012][,.]*)
          _lt_dar_allow_undefined='$wl-flat_namespace $wl-undefined ${wl}suppress' ;;
        10.*)
          _lt_dar_allow_undefined='$wl-undefined ${wl}dynamic_lookup' ;;
      esac
    ;;
```
and that is different than the one in prrte:
```
    darwin*)
      # Open MPI patched for Darwin / MacOS Big Sur.  See
      # http://lists.gnu.org/archive/html/bug-libtool/2015-07/msg00001.html
      case ${MACOSX_DEPLOYMENT_TARGET},$host in
      10.[012],*|,*powerpc*)
          _lt_dar_allow_undefined='${wl}-flat_namespace ${wl}-undefined ${wl}suppress' ;;
      *)
          _lt_dar_allow_undefined='$wl-undefined ${wl}dynamic_lookup' ;;
      esac
```
Mine resolves to `13.6.3` (of course), so maybe the problem is libevent doesn't have the `*` case? 🤷🏼

**Comment by rhc54** [comment]
This is the internal libevent? That's version 2.1.12, which was released in July 2020. Apple first moved away from versioning OSX as `10.x` in June 2020 with the release of BigSur. So no surprise that libevent doesn't know anything about OSX versions other than those starting with `10.x`.

I don't see any activity since that release, so I'm guessing this won't be fixed anytime soon.

**Comment by mathomp4** [comment]
Or, perhaps, already has been? I just cloned the master of libevent and a grep of its source shows no reference to `MACOSX_DEPLOYMENT_TARGET`! And there is at least a 2.2.1-alpha tag, so maybe in X years, all will be happy again.

For now, I'll close this as I have a workaround!

**Comment by jsquyres** [comment]
Just out of sheer curiosity, I poked around a bit in libevent's github and I see that there's a relatively new issue entitled "Libevent 2.2 stable release" (https://github.com/libevent/libevent/issues/1512).  So perhaps there will be another release in the not-distant future...?  🤷‍♂️ 

My curiosity did not extend enough to see if their `configure` now checks for macOS properly.  😄
