### ISSUE TITLE
Discarding mremap's fifth argument

### ISSUE THREAD

**Issue by thomas3494** [open-mpi/ompi#12180]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Open MPI 4.1.4

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

RHEL package

### Please describe the system on which you are running

It is [Snellius](https://servicedesk.surf.nl/wiki/display/WIKI/Snellius+hardware), rome partition. Relevant hardware:

* Operating system/version: RHEL 8.6
* Computer hardware: AMD Rome 7H12 (2x)
* Network type:    1x HDR100 ConnectX-6 single port
                                 2x 25GbE SFP28 OCP
                                 based on Infiniband HDR100 (100Gbps), fat tree topology

-----------------------------

## Details of the problem

I compiled the following program with mpicc, and ran it using mpirun.  Expected results would be something like

original: 0x7f7dbc94d000 (5)
shadow: 0x7f7dbc94b000 (13)
mremap(0x7f7dbc94b000, 4096, 4096, MREMAP_MAYMOVE | MREMAP_FIXED,
0x7f7dbc94d000);
original: 0x7f7dbc94d000 (13)

but the program gives an EPERM error. Running under strace shows that the last argument in the C-call is replaced by a NULL for the syscall.

```
#define _GNU_SOURCE
#include <stdlib.h>
#include <stdio.h>
#include <mpi.h>
#include <sys/mman.h>
#include <gnu/libc-version.h>

int main(int argc, char **argv)
{
        MPI_Init(&argc, &argv);

        printf("Running GLIBC %d.%d\n", __GLIBC__, __GLIBC_MINOR__);

        int *original = mmap(NULL, 8192, PROT_WRITE,
                                MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);
        if (original == MAP_FAILED || original == NULL) {
                perror("original mmap failed");
                return -1;
        }
        original[0] = 5;
        printf("original: %p (%d)\n", original, original[0]);

        int *shadow = mmap(NULL, 8192, PROT_WRITE,
                        MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);
        if (shadow == MAP_FAILED || shadow == NULL) {
                perror("shadow mmap failed");
                MPI_Finalize();
        }
        shadow[0] = 13;
        printf("shadow: %p (%d)\n", shadow, shadow[0]);

        printf("mremap(%p, 4096, 4096, MREMAP_MAYMOVE | MREMAP_FIXED, %p);\n",
                        shadow, original);
        void *result = mremap(shadow, 4096, 4096,
                        MREMAP_MAYMOVE | MREMAP_FIXED, original);
        if (result == MAP_FAILED) {
                perror("mremap failed");
                MPI_Finalize();
        }
        printf("original: %p (%d)\n", original, original[0]);

        MPI_Finalize();
}
```

**Comment by edgargabriel** [comment]
I am slightly confused, this does not look like an Open MPI issue. Do you get a different behavior if you do not compile/link it with MPI, i.e. a standalone sequential C code?

**Comment by thomas3494** [comment]
@edgargabriel Yes, removing the MPI calls and compiling with gcc (12.3.0) it gives the expected behaviour, so something like


```
original: 0x7f7dbc94d000 (5)
shadow: 0x7f7dbc94b000 (13)
mremap(0x7f7dbc94b000, 4096, 4096, MREMAP_MAYMOVE | MREMAP_FIXED,
0x7f7dbc94d000);
original: 0x7f7dbc94d000 (13)
```

**Comment by devreal** [comment]
I tried this on one of the clusters I have access to but couldn't reproduce the problem. Glancing at the code I see that OMPI does replace the last argument with `NULL` if `MREMAP_FIXED` is not provided in `flags`: https://github.com/open-mpi/ompi/blob/main/opal/mca/memory/patcher/memory_patcher_component.c#L245 

Since you do set this flag I wonder whether the values of `MREMAP_FIXED` do not match. It might be worth stepping through `_intercept_mremap` in a debug build to see what happens.

**Comment by jsquyres** [comment]
Does this happen with Open MPI v4.1.6?

**Comment by thomas3494** [comment]
@jsquyres It does

**Comment by thomas3494** [comment]
I tried the test on a different machine, using GCC 11.3.0, GLIBC 2.35, OpenMPI 4.1.6, and got the expected output. Snellius uses the same GCC and OpenMPI version, but GLIBC 2.28.

**Comment by thomas3494** [comment]
From the UCX repository

```
commit 28747c908a6b23060d193f9b0affa540c2a8c00c
Merge: e5b55922f 5a9565dec
Author: Yossi Itigin <yosefe@mellanox.com>
Date:   Fri Jan 20 20:40:11 2023 +0200

    Merge pull request #8822 from yosefe/topic/ucm-test-fix-mremap-override-pass-new
    
    UCM/TEST: Fix mremap() override - pass new_address
```

For both systems `ompi_info` shows `--with-ucx` . Is there a way to query the exact version of UCX that has been used to compile OpenMPI? On the system where the bug does not occur, I cannot find UCX. Does that mean that at runtime a different backend is used, or is UCX compiled in statically?

**Comment by yosefe** [comment]
@thomas3494 the UCX version on the system can be checked by `ucx_info -v` command.

**Comment by thomas3494** [comment]
@yosefe One system has multiple versions of UCX (can be loaded through `Lmod`), and the other `ucx_info` does not exist. Is `ucx` baked into `libmpi.so` or will it fallback to a different backend on the second system? If it is the latter, that would explain the issue.

**Comment by yosefe** [comment]
UCX is not part of libmpi, so it will be loaded according to LD_LIBRARY_PATH

**Comment by thomas3494** [comment]
Okay, thanks, then we can close this.
