### ISSUE TITLE
Add uninstall option to make

### ISSUE THREAD

**Issue by malcolmroberts** [open-mpi/ompi#12191]
**Is your feature request related to a problem? Please describe.**
I'd like to clean up after installing.

**Describe the solution you'd like**
`make install` can also have a `make uninstall` option.

**Describe alternatives you've considered**
If the installation prefix is its own directory, then it could be just deleted, but this doesn't work for directories with other things in it.

**Comment by jsquyres** [comment]
I'm not sure what you're asking for.  Are you saying that `make uninstall` doesn't work for you?

**Comment by malcolmroberts** [comment]
ah - looks like it's actually there, but I hadn't noticed that my build didn't work, so I guess that the uninstall option wasn't available until a build had succeeded.  My mistake; closing.  Thanks for the quick response!
