### ISSUE TITLE
OMPI 5.0.0 mpirun --quiet option not recognized

### ISSUE THREAD

**Issue by tmandrus** [open-mpi/ompi#12216]
Please submit all the information below so that we can understand the working environment that is the context for your question.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
OpenMPI version is v5.0.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Built and installed from in a local directory as a non-root user. These are my config options:
```shell
openMpiDependencies=/path/to/dependencies
${openMpiRoot}/configure \
        --prefix=/path/to/install \
        CC=/path/to/gcc \
        CXX=/path/to/g++ \
        CFLAGS=-O3 \
        CXXFLAGS=-O3 \
        --with-ofi=$openMpiDependencies/libfabric-1.19.0/install \
        --with-ofi-libdir=$openMpiDependencies/libfabric-1.19.0/install/lib \
        --with-ucx=$openMpiDependencies/ucx-1.15.0/install \
        --with-ucx-libdir=$openMpiDependencies/ucx-1.15.0/install/lib \
        --with-hwloc=$openMpiDependencies/hwloc-2.10.0 \
        --with-hwloc_libdir=$openMpiDependencies/hwloc-2.10.0/install/lib \
        --enable-sparse-groups \
        --enable-oshmem \
        --enable-show-load-errors-by-default \
        --with-libevent=internal \
        --with-pmix=internal \
        --with-prrte=internal \
        --enable-mca-dso \
        --enable-shared \
        --disable-io-romio \
```

### Please describe the system on which you are running

* Operating system/version: CentOS Linux release 7.9.2009 (Core)
* Computer hardware: x86 Intel Xeon E7-8867 CPUs, 500 GB RAM
* Network type: Internet-enabled

-----------------------------

## Details of the problem
When I run `mpirun` with the `-q` or `--quiet` options, I get a warning that these options are not recognized. 

```shell
shell$ ./mpirun -q -n 2 hostname
--------------------------------------------------------------------------
An unrecognized option was included on the mpirun command line:

  Option: -q

Please use the "mpirun --help" command to obtain a list of all
supported options.
--------------------------------------------------------------------------

$./mpirun -n 2 hostname
localMachineName
localMachineName

```
Otherwise, `mpirun` appears to be running as expected. I just included a basic example above but I've also tested with simple and complex MPI programs. Wondering if this is reproducible or something specific to my installation, and how to possible resolve this issue? Thanks!

**Comment by rhc54** [comment]
Well, "quiet" never actually did much, so it doesn't appear to be around any more on the cmd line. However, you can add `--prtemca prte_execute_quiet 1` to the `mpirun` cmd line to get the same effect.

**Comment by tmandrus** [comment]
Thanks addressing this! I see the --quiet flag falls under "old content" slated for auditing and this is pretty minor. The --prtemca flag is a suitable option moving forward and I am happy to close this issue.
