### ISSUE TITLE
error when install openmpi 4.1.5

### ISSUE THREAD

**Issue by jianxing33** [open-mpi/ompi#12244]
So I came across this error when install the openmpi 4.15

Making all in mca/common/ucx
make[2]: Entering directory `/nas/longleaf/home/jianxing/COAWSTv3.7_gnu_package/openmpi-4.1.5/opal/mca/common/ucx'
  CC       libmca_common_ucx_la-common_ucx.lo
In file included from common_ucx.c:20:
common_ucx.h: In function ‘opal_common_ucx_wait_request’:
common_ucx.h:154:52: warning: implicit declaration of function ‘ucp_request_free’; did you mean ‘ucp_request_test’? [-Wimplicit-function-declaration]
  154 |     MCA_COMMON_UCX_WAIT_LOOP(request, worker, msg, ucp_request_free(request));
      |                                                    ^~~~~~~~~~~~~~~~
common_ucx.h:72:17: note: in definition of macro ‘MCA_COMMON_UCX_WAIT_LOOP’
   72 |                 _completed;                                                              \
      |                 ^~~~~~~~~~
In file included from common_ucx.c:28:
/opt/ucx/include/ucm/api/ucm.h: At top level:
/opt/ucx/include/ucm/api/ucm.h:11:10: fatal error: ucs/sys/compiler.h: No such file or directory
   11 | #include <ucs/sys/compiler.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [libmca_common_ucx_la-common_ucx.lo] Error 1
make[2]: Leaving directory `/nas/longleaf/home/jianxing/COAWSTv3.7_gnu_package/openmpi-4.1.5/opal/mca/common/ucx'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/nas/longleaf/home/jianxing/COAWSTv3.7_gnu_package/openmpi-4.1.5/opal'
make: *** [all-recursive] Error 1

**Comment by jsquyres** [comment]
This isn't really enough information for us.  Can you please supply all the information that was asked for by the github issue template?

https://github.com/open-mpi/ompi/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
