### ISSUE TITLE
One method of debugger attach broken

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1225]
In master and v2.x, debugger attach for TotalView is currently broken.  The problem is that when we upgraded to PMIx, we removed the OOB support from apps as it was no longer necessary. However, we currently send a message from mpirun to rank0 indicating that the debugger is ready, and therefore releasing rank0 to complete a barrier.

There are several ways of fixing this; there's ongoing discussion to pick the best one.

Just to summarize:

* stat: works (anything based on LaunchMon works)
* DDT: works
* TotalView: doesn't work

**Comment by hppritcha** [comment]
@rhc54 have you had a chance to look at this?

**Comment by rhc54** [comment]
I've looked at it and have been working on a fix, but no ETA for committing it.

**Comment by jsquyres** [comment]
Discussion from today's call...

There was a webex discussing this issue, and what to do about it.  Two main options emerged:

1. Restore OOB functionality (including usock component).
1. Use PMIX notification system.

Restoring the OOB functionality for this one message seems like a lot of work, and it also seems like a step backwards.

The consensus seems to be to move forward and use the PMIx notification system (which means: finish implementing the PMIx notification system).  @rhc54 is working on it.  This will likely take a little time to finish and test.  @gpaulsen thinks that IBM may be able to contribute some resources to help.

Note, too, that the PMIx notification stuff will be part of PMIx v1.2.  Meaning: if we want TotalView attach to work in Open MPI v2.0.0 (as of today: we do), we'll need to update the v2.x branch with PMIx v1.

**Comment by gpaulsen** [comment]
From Telcon Call:  https://github.com/open-mpi/ompi/wiki/WeeklyTelcon_20160112
Decided this is NOT a blocker for 2.0.0, but want fixed in next release.

**Comment by jsquyres** [comment]
When this issue is fixed, please also revert the change (on v2.x) from open-mpi/ompi-release#905.

**Comment by jsquyres** [comment]
Per discussion on 24 Feb 2016, moving this milestone back to v2.0.1.  Rationale: it's a bug fix, and it does not affect our backwards compatibility promises for the 2.x series.

**Comment by rhc54** [comment]
@jsquyres @hppritcha @hjelmn Just an FYI: I noticed that something is broken on the pmix120 component - I'm getting hangs during regular init (i.e., no debugger) on my Mac. Not sure what may have broken, but I'll fix in on Fri.

**Comment by gpaulsen** [comment]
Any update?  Is this a 2.0 blocker?

**Comment by jsquyres** [comment]
We're iterating with Totalview.  The first version we sent to them didn't work; we sent them another one last night.
