### ISSUE TITLE
Question: Are Fortran TYPE MPI_COMM MPI_INFO BIND(C) compatible/interoperable

### ISSUE THREAD

**Issue by brtnfld** [open-mpi/ompi#12274]
## Background information

I'm working on passing from Fortran the communicator and information of TYPE MPI_COMM and MPI_INFO to C, but when I try to access the communicator, for example, in C, I get:

[cog:00000] *** An error occurred in MPI_Comm_size
[cog:00000] *** reported by process [536018945,1]
[cog:00000] *** on communicator MPI_COMM_WORLD
[cog:00000] *** MPI_ERR_COMM: invalid communicator

Meanwhile, with MPICH, these types are BIND(C) compatible and work. I thought the benefit of having a type(MPI_COMM) was that I no longer needed to call a C-stub to use MPI_Comm_f2c. What is the benefit of using type(MPI_COMM)?

Am I correct that I must return to using MPI_Comm_f2c for openmpi use cases?

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

This is was with v5.0.0

**Comment by ggouaillardet** [comment]
I do not think you should expect this trick to work with all MPI implementations, but feel free to ask the MPI Forum if Open MPI implentation is incorrect with that respect.

As far as I am concerned, the (only) benefit of `type(MPI_Comm)` is type checking.
For example the compiler will error if `MPI_INT` and `MPI_COMM_WORLD` arguments are swapped when calling a MPI subroutine.

**Comment by jsquyres** [comment]
> As far as I am concerned, the (only) benefit of `type(MPI_Comm)` is type checking.

@ggouaillardet is correct: the major "win" for the distinct types for Fortran handles is the type checking by the compiler.

For your use case, you absolutely still need to call `MPI_Comm_f2c()` in a correct MPI application.  That is both correct and required by the MPI standard.  In MPICH, it may be a no-op (and -- in practice -- you can get away with not calling it), but it's not a no-op in Open MPI.

**Comment by lrbison** [comment]
> I thought the benefit of having a type(MPI_COMM) was that I no longer needed to call a C-stub to use MPI_Comm_f2c

I agree with Gilles, the primary advantage to me is type checking.

> Am I correct that I must return to using MPI_Comm_f2c for openmpi use cases?

From MPI Standard 4.1, section 19.3.4

> Handles are passed between Fortran and C by using an explicit C wrapper to convert Fortran
handles to C handles. There is no direct access to C handles in Fortran.

So yes, to be standards compliant, you must use the transfer functions

**Comment by brtnfld** [comment]
Thank you for the valuable insights. I'll revert to using the f2c APIs. I appreciate your input.

**Comment by brtnfld** [comment]
I assume that the reason why MPI_Comm_f2c  expects an integer is that MPI_Comm is not interoperable with C. So, most APIs will pass the %mpi_val to the c-stub. However, despite the compiler warnings, passing MPI_Comm seems to work, but this is likely a happy coincidence. Is there meant to be an F08-compatible version of MPI_Comm_f2c?
