### ISSUE TITLE
Possible bug/issue in autoconf when configuring  --with-prrte=internal

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#12306]
I'm running `configure --with-prrte=internal ...` out of source, and getting the following output:

```
configure: ===== done with 3rd-party/prrte configure =====
checking for internal PRRTE RST files... not found
checking for prte.h... no
../ompi/configure: line 66906: test: -eq: unary operator expected
```

After checking my GitHub Actions logs, I noticed the same output in both main and v5.0.x branches.
https://github.com/mpi4py/mpi4py-testing/actions/runs/7770441998/job/21190639527#step:6:3478
https://github.com/mpi4py/mpi4py-testing/actions/runs/7770441998/job/21190639618#step:6:3362

**Comment by janjust** [comment]
Looks like a doc issue
