### ISSUE TITLE
Accumulate failing when ranks exceed number of processors

### ISSUE THREAD

**Issue by nrgraham23** [open-mpi/ompi#1231]
The accumulate function is failing when run with more ranks than processors.

CAccumulate.java in the ompi-java-test repo (https://github.com/open-mpi/ompi-java-test/blob/master/onesided/CAccumulate.java) is a reproducer.  The values received differ from the expected values, and the values that are received vary from run to run.  The fail also appears to be more likely the more the ranks exceed the number of processors (i.e. if you have 4 processors, a run with 5 ranks will pass more often than a run with 8 processors).

@hppritcha

**Comment by hppritcha** [comment]
Adding Java bindings label although this may actually be a problem in osc

**Comment by nrgraham23** [comment]
This problem appears to have been fixed when ompi was changed to not allow you to run more ranks that you have cores.  Closing this issue.
