### ISSUE TITLE
Makefile for openmpi-4.1.1

### ISSUE THREAD

**Issue by parsonb** [open-mpi/ompi#12330]
I'm using open MPI v4.1.1, which I installed from openmpi-4.1.1.tar.gz.
  I'm running Mac OS 14.1.1 (Sonoma) on an Apple Studio M1 Ultra.
  $configure seemed to run successfully, and installed two makefiles called Makefile.am and Makefile.in.  However $make -f Makefile.in and $make -f Makefile.am  both fail with an error statement of the following form:   "Makefile.in:15: *** missing separator.  Stop."
  Is another makefile available for v4.1.1? (Installing openMPI v.5 generated a Makefile that worked on the same computer. I need v4.1.1 because other software I'm installing is linked only to it.)
  Thanks very much.
  Bill Parson

**Comment by jsquyres** [comment]
Not sure why you are running `make -f Makefile.in` -- that will almost certainly fail.

After you run `configure`, there should be a regular `Makefile` which should work fine.  If you're not seeing `Makefile`, then please submit all the information asked for in the Github Issue template: https://github.com/open-mpi/ompi/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

That being said, 4.1.1 is ancient.  You should at least be using v4.1.6; it should be binary compatible with v4.1.1.

**Comment by parsonb** [comment]
Thanks, Jeff. I think the problem was that I executed configure simply by double-clicking on it. That seemed to run all the routines, but it did not create a regular Makefile. If I ran configure with the command ./configure --prefix=/Users/bill/mpi/ it created a regular Makefile in addition to Makefile.in and Makefile.am.

**Comment by jsquyres** [comment]
Ok, sounds like the issue is resolved then.  Glad it's working!
