### ISSUE TITLE
Should the plm rsh module really error out if there is no ssh/rsh even before it knows if it needs to use it?

### ISSUE THREAD

**Issue by akesandgren** [open-mpi/ompi#12386]
When doing mpirun in an environment (container) that does not have ssh/rsh installed the plm rsh module errors out early.
Even when it does not need ssh/rsh to do startup.
Is this really necessary?

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)
v4.x

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Installed with EasyBuild 4.9.0

I.e. it doesn't really make sense to me that this errors out (hw is a simple hello world):
```
Apptainer> type ssh
bash: type: ssh: not found
Apptainer> typ rsh
bash: typ: command not found
Apptainer> mpirun -n 1 ./hw
--------------------------------------------------------------------------
The value of the MCA parameter "plm_rsh_agent" was set to a path
that could not be found:

  plm_rsh_agent: ssh : rsh

Please either unset the parameter, or check that the path is correct
--------------------------------------------------------------------------
[b-cn1603.hpc2n.umu.se:473887] [[INVALID],INVALID] FORCE-TERMINATE AT Not found:-13 - error plm_rsh_component.c(335)
```

it doesn't need ssh/rsh to startup a single task on the current node.

I know I can set OMPI_MCA_plm=^rsh but there shouldn't really be a need to in this case.

**Comment by rhc54** [comment]
Is there an allocation - e.g., a default hostfile?

**Comment by akesandgren** [comment]
In the above case no there is no hostfile, or to be specific the openmpi-default-hostfile is empty (only contains comments)

**Comment by rhc54** [comment]
Hmmm...well, we won't do anything about it for the OMPI v4 series, but I can take a look at providing a local-only component for OMPI v5. Have to ponder a bit as to the best way to avoid creating a larger number of users complaining about not being able to launch their job as expected (because of missing rsh), but getting no error - just a bunch of procs on the local node. We have encountered that before, which is the reason for the current behavior.

**Comment by akesandgren** [comment]
So there is no way currently to make it bailout if it's missing only when it would really need it?

**Comment by rhc54** [comment]
Well, yes there is - by doing exactly what you did with the MCA param. Otherwise, it checks to ensure there is some method for launching daemons and errors out if not so we avoid the unexpected "everything on the local node" problem. Given that running on multiple nodes is by far the most common use-case, and the volume of complaints when we didn't ensure we could do it, that seems like a reasonable solution.

What I can do is look for an allocation, and if one isn't found, then we could accept not having a launcher. Like I said, have to ponder that a bit to ensure we don't recreate the prior problem.

**Comment by akesandgren** [comment]
Ok, thanks for the explanation. I was just hit by that during a container build/test  setup and thought I should ask about it...

**Comment by rhc54** [comment]
Just FWIW: I took a look and this has already been fixed in OMPI v5. Looks like I fixed it in PRRTE back before OMPI v5 started, and so OMPI simply picked it up when they started using PRRTE for the runtime.

**Comment by akesandgren** [comment]
Perfect, so let's close this...

**Comment by minrk** [comment]
FWIW, it is still the case that openmpi 5.0.3 does not start if ssh is not present.

Running in a container, the error is:

```
$ mpiexec -n 1 echo 'hi'
--------------------------------------------------------------------------
It looks like "prte_init()" failed for some reason. There are many
reasons that can cause PRRTE to fail during "prte_init()", some of
which are due to configuration or environment problems.  This failure
appears to be an internal failure — here's some additional information
(which may only be relevant to a PRRTE developer):

   prte_plm_base_select failed
   --> Returned value  (-46) instead of PRTE_SUCCESS
--------------------------------------------------------------------------
```

and with

```
export OMPI_MCA_plm_ssh_agent=false
```

eveyrthing runs fine.

This seems like a bit of a step backward from openmpi 4, since there is no longer any indication from the error that the problem is related to ssh/rsh.

**Comment by rhc54** [comment]
Huh - well, I'll add it to the list of things to look at, but it is a very low priority and unlikely to be addressed this year.

**Comment by minrk** [comment]
Sure! Not a high priority and probably affects mainly containers and CI and easy to work around with `OMPI_MCA_plm_ssh_agent=false`. I mostly wanted to add a comment because the discussion above could be interpreted as suggesting that openmpi 5 works without ssh present by default, which isn't accurate. It's unclear if this is intended to be the case or not.

**Comment by rhc54** [comment]
Well, FWIW - just checked this with head of PRRTE master branch and it worked fine:
```shell
$ prterun -n 1 --prtemca plm_base_verbose 10 hostname
[rhc-node01:61518] mca: base: component_find: searching NULL for plm components
[rhc-node01:61518] mca: base: find_dyn_components: checking NULL for plm components
[rhc-node01:61518] pmix:mca: base: components_register: registering framework plm components
[rhc-node01:61518] pmix:mca: base: components_register: found loaded component slurm
[rhc-node01:61518] pmix:mca: base: components_register: component slurm register function successful
[rhc-node01:61518] pmix:mca: base: components_register: found loaded component ssh
[rhc-node01:61518] pmix:mca: base: components_register: component ssh register function successful
[rhc-node01:61518] mca: base: components_open: opening plm components
[rhc-node01:61518] mca: base: components_open: found loaded component slurm
[rhc-node01:61518] mca: base: components_open: component slurm open function successful
[rhc-node01:61518] mca: base: components_open: found loaded component ssh
[rhc-node01:61518] mca: base: components_open: component ssh open function successful
[rhc-node01:61518] mca:base:select: Auto-selecting plm components
[rhc-node01:61518] mca:base:select:(  plm) Querying component [slurm]
[rhc-node01:61518] mca:base:select:(  plm) Querying component [ssh]
[rhc-node01:61518] [[INVALID],UNDEFINED] plm:ssh_lookup on agent ssh : rsh path NULL
[rhc-node01:61518] [[INVALID],UNDEFINED] plm:ssh: unable to be used: cannot find path for launching agent "ssh : rsh"
[rhc-node01:61518] mca:base:select:(  plm) No component selected!
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:receive start comm
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:setup_vm
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:setup_vm creating map
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] setup:vm: working unmanaged allocation
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] using default hostfile /opt/hpc/etc/hostfile.txt
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] checking node 10.0.4.2
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] ignoring myself
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:setup_vm only HNP in allocation
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:receive processing msg
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:receive job launch command from [prterun-rhc-node01-61518@0,0]
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:receive adding hosts
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:receive calling spawn
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:receive done processing commands
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:setup_job
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:setup_vm
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:setup_vm no new daemons required
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] complete_setup on job prterun-rhc-node01-61518@1
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:launch_apps for job prterun-rhc-node01-61518@1
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:send launch msg for job prterun-rhc-node01-61518@1
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:launch wiring up iof for job prterun-rhc-node01-61518@1
rhc-node01
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:prted_cmd sending prted_exit commands
[rhc-node01:61518] [prterun-rhc-node01-61518@0,0] plm:base:receive stop comm
$
```
So I think it is correct that this has been closed as "fixed". PLM framework in head of PRRTE v3.0 branch is identical to PRRTE master branch, so I suspect this will be fixed in next OMPI release.
