### ISSUE TITLE
How can `MPI_Intercomm_merge` achieve best performance?

### ISSUE THREAD

**Issue by cruiseliu** [open-mpi/ompi#12418]
# Background information

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)
v4.1.6

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
conda-forge

### Please describe the system on which you are running

* Operating system/version: Ubuntu 20.04 (inside docker)
* Computer hardware: Xeon E5-2673 v3 *2
* Network type: Microsoft Hyper-V Network Adapter

-----------------------------

## Details of the problem

I launched 8 processes separately with `mpirun -n 1 --ompi-server URI`  (on one single node), and merged the `intercomm`s into an `intracomm` with `MPI_Intercomm_merge()`.
A simple benchmark shows that this communicator is about 1x slower than a communicator created with `mpirun -n 8`.

The communicators are created and merged in the following order:

  - rank 0's COMM_WORLD accept, rank 1's COMM_WORLD connect
  - merge the newcomm into intracomm
  - the new intracomm accept, rank 2's COMM_WORLD connect
  - merge the newcomm into intracomm
  - the new intracomm accept, rank 3's COMM_WORLD connect
  - ......

Is that I'm using a suboptimal merge order or there is some other reason?

**Comment by bosilca** [comment]
OMPI 4.x cannot use shared memory communications between processes on different jobs. As a result, your processes will communicate over pipes instead of shared memory, putting the latency up and the bandwidth down. Not going to get fixed in the 4.x, but you might have a better luck with the 5.0.

**Comment by cruiseliu** [comment]
> OMPI 4.x cannot use shared memory communications between processes on different jobs. As a result, your processes will communicate over pipes instead of shared memory, putting the latency up and the bandwidth down. Not going to get fixed in the 4.x, but you might have a better luck with the 5.0.

Got it. Thanks for your help.

Could you please explain a bit more about how 5.0 implements shared memory between different jobs? Or is there a link to design documentations?
In fact we are trying to launch worker processes without mpirun and setup the ompi environment inside the processes, because of our platform's limitation. So I want to learn about the launcher's implementation.

**Comment by bosilca** [comment]
OMPI uses [PMIX](https://pmix.github.io/) for job launching, you might want to go and read the docs related to process launching there.

I looked into the code again, and I was wrong, OMPI 5.x still has the limitation on shared memory between different job, so you will not be able to take advantage of shared memory communications between processes in different jobs. Sorry.

**Comment by cruiseliu** [comment]
Thanks for your info.
