### ISSUE TITLE
Ubuntu does not have a maintainer for OpenMPI

### ISSUE THREAD

**Issue by eschnett** [open-mpi/ompi#1242]
It seems that Ubuntu and Debian do not have maintainers for their OpenMPI package. For the past two years, they have been shipping version 1.6.5, and according to their issue tracker <https://bugs.launchpad.net/ubuntu/+source/openmpi/+bug/1365152>, this is still the current state.

I am bringing this up here in the hope that this reaches someone with sufficient interest in both OpenMPI and Ubuntu, and with sufficient time and expertise.

**Comment by rhc54** [comment]
We are working on this, and hope to have a solution soon. A couple of people have volunteered to step forward and take this on for Debian/Ubuntu.

**Comment by amckinstry** [comment]
I'm now maintaining OpenMPI for Debian (having uploaded 1.10.2, currently undergoing transition), and hence in practice for Ubuntu. 
Best regards
Alastair McKinstry (mckinstry@debian.org)

**Comment by eschnett** [comment]
@amckinstry Thank you!

**Comment by jsquyres** [comment]
@amckinstry Sweet; thanks. Let us know if there's anything you need from us.  We like to have an open dialogue with our downstream packagers.

**Comment by jsquyres** [comment]
Bug is now closed at the Ubuntu launchpad -- closing the bug here, too.

**Comment by rhc54** [comment]
@amckinstry Very glad to hear that you are taking this over! Just as an FYI: beginning with the 2.0 release (due out soon), there will be another external package (PMIx) that needs to be present along with OpenMPI (it is currently embedded in OMPI, but I know the distros prefer it to be separate). I filed a Debian ticket noting that a new PMIx package needs to be added to the distro, but I haven't done anything further about it.
