### ISSUE TITLE
MTT MPI_Gatherv_c/MPI_Scatterv_c failure

### ISSUE THREAD

**Issue by wenduwan** [open-mpi/ompi#12438]
### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

main branch

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Nightly tarball

### Please describe the system on which you are running

* Operating system/version: Amazon Linux 2
* Computer hardware: c6gn.16xlarge
* Network type: EFA

-----------------------------

## Details of the problem

https://mtt.open-mpi.org/index.php?limit=&wrap=&trial=&enable_drilldowns=&yaxis_scale=&xaxis_scale=&hide_subtitle=&split_graphs=&remote_go=&do_cookies=&phase=test_run&text_start_timestamp=2024-03-12+23%3A31%3A10+-+2024-03-26+23%3A31%3A10&text_platform_hardware=%5Eaarch64%24&show_platform_hardware=show&text_os_name=%5ELinux%24&show_os_name=show&text_mpi_name=%5Eompi-nightly-main%24&show_mpi_name=show&text_mpi_version=%5Emain-202403230241-984944d%24&show_mpi_version=show&text_suite_name=%5ETestBuild%3AIntelInstalled%24&show_suite_name=show&text_test_name=all&text_np=%5E256%24&show_np=show&text_full_command=&show_full_command=show&text_http_username=%5Eamazon%24&show_http_username=show&text_local_username=all&show_local_username=hide&text_platform_name=%5Eaws-amazonlinux-slurm-efa-installer%24&show_platform_name=show&click=Detail&phase=test_run&test_result=_run_f&text_compute_cluster_id=&text_os_version=&show_os_version=&text_platform_type=&show_platform_type=&text_submit_id=&text_hostname=&show_hostname=&text_mpi_get_id=&text_mpi_install_compiler_id=&text_mpi_install_configure_id=&text_mpi_install_id=&text_compiler_name=&show_compiler_name=&text_compiler_version=&show_compiler_version=&text_vpath_mode=&show_vpath_mode=&text_endian=&show_endian=&text_bitness=&show_bitness=&text_configure_arguments=&text_exit_value=&show_exit_value=&text_exit_signal=&show_exit_signal=&text_duration=&show_duration=&text_client_serial=&show_client_serial=&text_result_message=&text_result_stdout=&text_result_stderr=&text_environment=&text_description=&text_test_build_id=&text_test_build_compiler_id=&text_test_run_id=&text_test_name_id=&text_test_run_command_id=&text_test_suite_id=&text_performance_id=&text_launcher=&show_launcher=&text_resource_mgr=&show_resource_mgr=&text_network=&show_network=&text_parameters=&show_parameters=&lastgo=detail

This is caused by #12376

**Comment by bosilca** [comment]
#12434 seems to be related to `MPI_Reduce`. How is this related to gather/scatter ?

**Comment by wenduwan** [comment]
Sorry updated link.

The intel-tests MPI_Gatherv_c and MPI_Scattev_c failed for derived datatypes with gaps. This happened in the new HAN Gatherv/Scatterv algorithm.

I will upstream a fix shortly.
