### ISSUE TITLE
mpirun does not work inside a docker container

### ISSUE THREAD

**Issue by chemwolf6922** [open-mpi/ompi#12431]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)
v5.0.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Built and installed from the release tarball. 

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
N/A

### Please describe the system on which you are running

For the physical machine
* Operating system/version:  ubuntu server 22.04, Linux 5.15.0-101-generic "#"111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
* Computer hardware: ryzen 5700x
* Network type: Ethernet
For the docker image
* "Operating system/version": ubuntu 22.04
* Network type: the default docker bridge

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

Openmpi built and installed on the physical machine runs fine, for example:
```shell
mpirun -np 2 echo 1
1
1
```
However, openmpi built and installed inside the docker container reports the following bug:
```shell
mpirun -np 2 echo 1
--------------------------------------------------------------------------
It looks like "prte_init()" failed for some reason. There are many
reasons that can cause PRRTE to fail during "prte_init()", some of
which are due to configuration or environment problems.  This failure
appears to be an internal failure — here's some additional information
(which may only be relevant to a PRRTE developer):

   prte_plm_base_select failed
   --> Returned value  (-46) instead of PRTE_SUCCESS
--------------------------------------------------------------------------
```

**Comment by ggouaillardet** [comment]
Try installing ssh in the container.

**Comment by chemwolf6922** [comment]
> Try installing ssh in the container.

Thanks, it worked, but why😂
