### ISSUE TITLE
Testing for ROCm-aware MPI.

### ISSUE THREAD

**Issue by Knight-WP** [open-mpi/ompi#12444]
Hello, do you have any specific unit tests for  ROCm aware OpenMPI?

**Comment by edgargabriel** [comment]
We have a ROCm aware MPI testsuite at AMD, but that one is unfortunately not (yet) open source. If you want to run some tests, you could try the osu benchmarks, they support ROCm devices and can be used to test a wide range of point-to-point and collective operations. See this website here with some instructions on compiling/running OSU benchmarks with Open MPI + ROCm.

https://rocm.docs.amd.com/en/latest/how-to/gpu-enabled-mpi.html#rocm-enabled-osu-benchmarks

**Comment by Knight-WP** [comment]
I'm sorry for not replying promptly due to my vacation. Thank you very much for your answer.
