### ISSUE TITLE
mpirun fails to bind a singleton

### ISSUE THREAD

**Issue by aminiussi** [open-mpi/ompi#12463]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)
v5.0.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Installed from sources with the configuration command:
```
configure --prefix=/trinity/shared/apps/tr17.10/x86_64/openmpi-gcc132-5.0.2 --with-slurm --with-cuda=/trinity/shared/apps/tr17.10/x86_64/cuda-11.6/
```

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

N/A

### Please describe the system on which you are running

* Operating system/version: CentOS Linux release 7.9.2009 (Core)
* Computer hardware: SkyLake
* Network type: Not sure, but the issue appears on a single node

-----------------------------

## Details of the problem

Deep inside my slurm script, I launch a job with
```shell
mpirun --np 1 --report-binding --map-by package:PE=32 ./testGhosts 111
```
I'm getting the following output:
```
19: A request was made to bind to that would result in binding more
19: processes than cpus available in your allocation:
19:
19:    Application:     ./testGhosts
19:    #processes:      1
19:    Binding policy:  CORE
19:
19: You can override this protection by adding the "overload-allowed"
19: option to your binding directive.
```
I do not understand how I can bin more processes than cpus if there is only 1 process ?

Maybe the mpirun command does not make sense, but then the message is confusing.

Thanks

**Comment by rhc54** [comment]
I take it your `hello_worldmpirun` actually calls `mpirun` inside it? Otherwise, that cmd line indeed makes no sense.

We have never allowed nested calls to `mpirun` as the passing of envars between the two instances causes too much confusion.

**Comment by rhc54** [comment]
Still not sure I understand the reference to a "singleton" in this issue's title - that term has a specific meaning in MPI, but I'm guessing that isn't what you are referring to here.

`--map-by package:PE=32` is telling us to bind your process to 32 cores, all of which must be inside a single package. Are there 32 cores in a package on your machine? Did your `salloc` request provide enough for that directive?


> The same script with 2 MPI process instead of one passes ok.

Was your `salloc` the same? Did you ask for `PE=32` in that instance? If both are yes, then I find that result difficult to understand - not sure how that would happen.

**Comment by aminiussi** [comment]
The problem shows up when launching a MPI program with a single task (which is what is qualified as a singleton by srun).

> --map-by package:PE=32 is telling us to bind your process to 32 cores, all of which must be inside a single package. Are there 32 cores in a package on your machine?

Ok, so that's probably the problem. Since I used <nb core on node>/<nb task> to compute that one and there are 2 sockets on those node.

Still, the message goes "more processes than cpus available" while there is only one process and at least one cpu.

> Was your salloc the same? Did you ask for PE=32 in that instance? 

PE is 16 in the second one. 

The problem is that I'm asking more core than available in the package in the first case.

**Comment by aminiussi** [comment]
I have enough information to fix my issue.

Sorry for the inconvenience.

**Comment by rhc54** [comment]
> the message goes "more processes than cpus available" while there is only one process and at least one cpu.

Yeah, it's hard to come up with a concise message that covers every possible scenario. Probably should change it to say "you requested more cpus for your processes than are available". Glad you can proceed!
