### ISSUE TITLE
BLD: autogen stage fails with v5.0.3

### ISSUE THREAD

**Issue by tylerjereddy** [open-mpi/ompi#12483]
My submodules all look updated, etc., and I seem to consistently see `./autogen.pl` failing with:

```
<snip>
=== Found pmix framework: src/mca/ptl
--- Found pmix / ptl / client component: src/mca/ptl/client
--- Found pmix / ptl / server component: src/mca/ptl/server
--- Found pmix / ptl / tool component: src/mca/ptl/tool
Missing src/mca/common/Makefile.am at ./autogen.pl line 96, <IN> line 3.
Command failed: ./autogen.pl
```

If I switch to `v5.0.2` and update submodules again, a clean `autogen` will succeed. Working on fairly standard Linux env (`SUSE Linux Enterprise Server 15 SP4`) on one of our supercomputers at LANL.

**Comment by ggouaillardet** [comment]
That typically occurs when a directory had been deleted but there are some leftover files.
Confirm there should not be a 3rd-party/openpmix/src/mca/common directory, delete it and try again.

**Comment by tylerjereddy** [comment]
Fair enough, thanks, I usually expect `git clean -xfd` to give me a clean build state, but it looks like this project needs at least `git submodule foreach git clean -xfd` in addition.

I wonder if any of my recent `pmix` issues have been caused by residual artifacts when swapping between hashes, yikes.
