### ISSUE TITLE
Trying to run MPI 3.0.6 on docker

### ISSUE THREAD

**Issue by niltonlqjr** [open-mpi/ompi#12527]
## Background information

I'm trying to run MPI 3.0.6 on docker (i need this version because the application that i need to run cant compile with newer versions). 

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

I've used Open MPI 3.0.6 downloaded in the link https://www.open-mpi.org/software/ompi/v3.0/
checksums:
MD5: 2048643fcbcfc999a8f6c82e67031231
SHA1: 6c9f901cc63902e2d6b938fbaff82c67877ccab0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Installed with ./configure && make && make install in the dockerfile.
extracted from source code

### Please describe the system on which you are running

* Operating system/version: Host running ubuntu 22.04 and docker image beeing built from an ubuntu 20:04
* Computer hardware: one Core i5 6200u and one core i7-3770
* Network type: Ethernet Gigabit

-----------------------------

## Details of the problem
I've set up my Dockerfile to enable passwordless SSH and performed port redirection to Docker using the 'docker run -p' argument. Now, I can execute SSH and SCP commands without any issues, using both public and private keys. Additionally, I've modified the '/usr/local/etc/openmpi-mca-params.conf' file (within the Docker image) to include the following lines:

```shell
btl_tcp_port_min_v4=52001
btl_tcp_port_range_v4=30
btl=tcp,self
btl_tcp_if_include=eth0
oob_tcp_if_include=eth0
oob_tcp_dynamic_ipv4_ports=53001:53031
orte_fwd_mpirun_port=1
```

When attempting to run a simple application, such as 'hello world', on localhost alone, it executes without any problem. However, when attempting to run the application across multiple hosts, I encounter the following message:

```text
--------------------------------------------------------------------------
Both static and dynamic port ranges were specified for the
out-of-band (OOB) communication subsystem:

Static ports:   53001
Dynamic ports:  53001:53031

Only one can be specified. Please choose either static or
dynamic ports and try again.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
No network interfaces were found for out-of-band communications. We require
at least one available network for out-of-band messaging.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_oob_base_select failed
  --> Returned value (null) (-43) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
```
It's noticeable that I haven't configured static ports by default in the MCA configuration file.

I also attempted to run the same application with the following configuration file:

```shell
btl_tcp_port_min_v4=52001
btl_tcp_port_range_v4=30
btl=tcp,self
btl_tcp_if_include=eth0
oob_tcp_if_include=eth0
oob_tcp_dynamic_ipv4_ports=53001:53031
```

When attempting to run with this second configuration file, I encountered the following error:

```text
[87c5d7eb0d99:00092] [[40279,0],1] tcp_peer_recv_connect_ack: received unexpected process identifier [[40279,0],1] from [[40279,0],0]
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
```

Any ideas on what I can do?

If it helps, the following GitHub repository contains all configuration files:
https://github.com/niltonlqjr/docker-disccofan

Thank you!

**Comment by rhc54** [comment]
Pretty sure the problem is here:
```shell
oob_tcp_dynamic_ipv4_ports=53001:53031
```
That ':' is supposed to be a `-`. The OOB has no idea what to do with that option string as written.

**Comment by niltonlqjr** [comment]
> It's unfortunate that you can't update to use a newer Open MPI. How hard would it be to update your application to be MPI conformant?
> 
> As a bit of a shot in the dark, what happens if you set `oob_tcp_static_ipv4_ports` and/or `oob_tcp_static_ipv6_ports` to `-1`?




> Pretty sure the problem is here:
> 
> ```shell
> oob_tcp_dynamic_ipv4_ports=53001:53031
> ```
> 
> That ':' is supposed to be a `-`. The OOB has no idea what to do with that option string as written.

I attempted replacing `:` with `-`, yet the error persists. I've also set `oob_tcp_static_ipv4_ports` and `oob_tcp_static_ipv6_ports`, but the error remains unchanged.

**Comment by niltonlqjr** [comment]
Ok, now i got a new error:
I tryed to set open mpi mca params for the machine that i invoke mpirun and for the machines that will just be on hostfile.
The machine that invokes the mpi run has the following on `/usr/local/etc/openmpi-mca-params.conf`:

```shell
orte_fwd_mpirun_port = 1
btl=tcp,self
btl_tcp_port_min_v4 = 52001
btl_tcp_port_range_v4 = 30
btl_tcp_if_include = eth0
oob_tcp_if_include = eth0
oob_tcp_dynamic_ipv4_ports = 52101-52131
```

and the machine that does not invoke has the following configuration:
```shell
btl=tcp,self
btl_tcp_port_min_v4 = 52001
btl_tcp_port_range_v4 = 30
btl_tcp_if_include = eth0
oob_tcp_if_include = eth0
```

using it i got the following error message:

```
[3dd8502af237:00078] [[45183,0],1] ORTE_ERROR_LOG: Not found in file util/nidmap.c at line 165
[3dd8502af237:00078] [[45183,0],1] ORTE_ERROR_LOG: Not found in file base/ess_base_std_orted.c at line 550
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  construct daemon map from static ports failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
```

**Comment by niltonlqjr** [comment]
Looking quickly at the source code it looks like a fail on `gethostbyname` call.
IDK if it is related to the fact that docker container name is not displayed in network.

**Comment by niltonlqjr** [comment]
It's finally up and running!!!!!!

If anyone encounters a similar situation in the future, here's how I resolved it:
- Disabled the SSH service on the host machine.
- Utilized `docker run --network=host ...` to execute my container.
- Within the container, I configured the desired network interface using parameters `btl_tcp_if_include` and `oob_tcp_if_include` (I employed [this script](https://github.com/niltonlqjr/docker-disccofan/blob/main/scripts/init_container.sh) for this task).

With these adjustments, it's now running.

You can access the Git project [here](https://github.com/niltonlqjr/docker-disccofan) (this project also installs some dependencies required by the application. If you don't need these dependencies, you should modify the Dockerfile.host according to your requirements).
