### ISSUE TITLE
OpenMPI/5.0.3 with PMIx/4.2.7 compilation error

### ISSUE THREAD

**Issue by rgayatri23** [open-mpi/ompi#12537]
### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

Using v5.0.3 (observe the same with v5.0.2 too)

### System - Perlmutter

* Operating system/version:
```bash
 uname -srm
Linux 5.14.21-150400.24.81_12.0.87-cray_shasta_c x86_64
```
* Computer hardware: AMD EPYC CPU and NVIDIA A100 GPU 
* Network type: libfabric
* compilers tested: gcc/12.3 , nvhpc/23.9, llvm/18.1.0

-----------------------------

## Details of the problem
When trying to install the mentioned open-mpi/5.0.3, I get the following compile error:
```bash
base/ess_base_bootstrap.c:72:14: error: static declaration of ‘pmix_getline’ follows non-static declaration
```
Every call that touches the following code path encounters the same error:
```bash
#if PMIX_NUMERIC_VERSION < 0x00040208
static char *pmix_getline(FILE *fp)
...
#endif
``` 

The `ifdef` looks like it is for pmix versions lower than 4.2.8. We have pmix/4.2.7 but the function definition seems to not contain `static` in it. 
```bash
rgayatri@perlmutter:login:.../openmpi> pmix_info
                 Package: PMIx root@runner-vzcz-kjx-project-87-concurrent-0
                          Distribution
                    PMIX: 4.2.7
```
I was able to successfully build and test by editing the source code to comment out the `ifdef` block.

**Comment by rhc54** [comment]
Yes, this is a known typo in PRRTE that has been corrected - should be:
```c
#if PMIX_NUMERIC_VERSION < 0x00040205
```
It occurs in a couple of places, but commenting it out when encountered is just fine.

**Comment by rgayatri23** [comment]
Oh great, thanks. I just raised it in case it wasn't known. I will close this issue in this case.

**Comment by nyetsche** [comment]
FYI this is fixed in https://github.com/openpmix/prrte/pull/1957 but not in a tagged release or branch, so I'm unsure when it will be combined into OpenMPI.

**Comment by rhc54** [comment]
FWIW: it is in a release branch, just not yet in a tagged release. OMPI is in the process of updating PRRTE for their next release, so I imagine it will come soon.
