### ISSUE TITLE
problem with MPI_Comm_Create_Group

### ISSUE THREAD

**Issue by Bellahra** [open-mpi/ompi#12530]
## Background information
I am writing a MPI Fortran code. In my work, i need to use the MPI_Comm_Create_Group(comm, group, tag, newcomm, ierror) subroutine to realize operations like one-to-many but not one-to-all. 

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

4.0.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

it was installed with the source package.

### Please describe the system on which you are running

* Operating system/version: Ubuntu 20.04 LTS
* Computer hardware: Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz
* Network type: wifi

-----------------------------
## Details of the problem

When I call the subroutine as follows,

```Fortran
if(rank>1) then
      call MPI_Comm_create_group(MPI_COMM_WORLD, MPI_GROUP_EMPTY, 52, newcomm, ierr)
      print*,ierr,rank
   end if
    call MPI_Comm_size(newcomm,n1_ranks,ierr)
    !CALL MPI_COMM_GROUP(newcomm,group)
    !call MPI_group_rank(group, rank1)
    print*,n1_ranks,rank1
 ```

and when i run the code with 5 CPU cores, the output is
        
>            0           2
>            0           4
>            5           0
>            0           3
> [bellpc:77423] *** An error occurred in MPI_Comm_size
> [bellpc:77423] *** reported by process [3189899265,2]
> [bellpc:77423] *** on communicator MPI_COMM_WORLD
> [bellpc:77423] *** MPI_ERR_COMM: invalid communicator
> [bellpc:77423] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
> [bellpc:77423] ***    and potentially your MPI job)
>            5           0
> [bellpc:77417] 2 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal
> [bellpc:77417] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

It seems that the group has been created successfully, cause ranks 2,3,4 with ierr=0 were printed. But if the group is created and the new communicator called 'newcomm' containing ranks 2,3,4 exists, why I can not get the size of the new group? The first question is that why does this problem occur? My guess is wrong usage of the create_group subroutine. 

Further, I changed the subroutine to obtain the information of the new group, this is one piece of my code, 

```Fortran
    if(rank>1) then
    call MPI_Comm_create_group(MPI_COMM_WORLD, MPI_GROUP_EMPTY, 52, newcomm, ierr)
    print*,ierr,rank
    end if
    call MPI_Comm_size(newcomm,n1_ranks,ierr)
    CALL MPI_COMM_GROUP(newcomm,group)
    call MPI_group_rank(group, rank1)
    print*,n1_ranks,rank1
```
But the code even can not be compiled successfully,

  

>  16 |     CALL MPI_COMM_GROUP(newcomm,group)
>       |                                      1
> Error: There is no specific subroutine for the generic ‘mpi_comm_group’ at (1)
> test6.f90:17:37:
> 
>    17 |     call MPI_group_rank(group, rank1)
>       |                                     1
> Error: There is no specific subroutine for the generic ‘mpi_group_rank’ at (1)
> 

I think in the above process, MPI_Comm_Group connects the newcomm with the 'group', and hence i could get the rank of 'group', but it also doesn't work. 

Can anyone help me with this? Thanks in advance.

Below is the full testing code of mine
``` Fortran
program test6
use mpi
    integer rank, n_ranks, ierr,n1_ranks
    integer status(MPI_STATUS_SIZE)
    integer:: group
    INTEGER:: rank1
    integer :: newcomm
    call MPI_Init(ierr)
    call MPI_Comm_size(MPI_COMM_WORLD, n_ranks, ierr) 
    call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierr)
    if(rank>1) then
        call MPI_Comm_create_group(MPI_COMM_WORLD, MPI_GROUP_EMPTY, 52, newcomm, ierr)
        print*,ierr,rank
    end if
    call MPI_Comm_size(newcomm,n1_ranks,ierr)
    CALL MPI_COMM_GROUP(newcomm,group)
    call MPI_group_rank(group, rank1)
    print*,n1_ranks,rank1
    call MPI_Finalize(ierr)
end program
```

**Comment by ggouaillardet** [comment]
Please format your code and do copy/paste the outputs instead of posting pictures.

`ierr` should pretty much always be `MPI_SUCCESS`, but `newcomm` might be `MPI_COMM_NULL`.
`MPI_Comm_size(MPI_COMM_NULL, ...)` is illegal w.r.t. the MPI standard.

**Comment by wenduwan** [comment]
@Bellahra Thanks for reporting the issue. Could you please edit the post using this template?

https://github.com/open-mpi/ompi/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by Bellahra** [comment]
> @Bellahra Thanks for reporting the issue. Could you please edit the post using this template?
> 
> https://github.com/open-mpi/ompi/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by Bellahra** [comment]
> Please format your code and do copy/paste the outputs instead of posting pictures.
> 
> `ierr` should pretty much always be `MPI_SUCCESS`, but `newcomm` might be `MPI_COMM_NULL`. `MPI_Comm_size(MPI_COMM_NULL, ...)` is illegal w.r.t. the MPI standard.

Ok, thank you. The question has been complemented and formatted.

**Comment by bosilca** [comment]
There are multiple issues with this code.

1. As @ggouaillardet indicated calling `MPI_Comm_create_group` with `MPI_GROUP_EMPTY` returns `MPI_COMM_NULL`, and it is illegal to call `MPI_Comm_size` on `MPI_COMM_NULL`.
2. On rank 0 (which is the rank that does not call `MPI_Comm_create_group`) the `newcomm` variable is not initialized, and that leads to badness in `MPI_Comm_size`.
3. Based on your question, I don't think this code does what you expect it to do. There is no group create by this code, ever. The reason is simple, you create the comm from `MPI_GROUP_EMPTY` so it will always result in `MPI_COMM_NULL`. If I understand what you are trying to do, I don't think using `MPI_Comm_create_group` is the right way to go, but instead you should take a look at `MPI_Comm_split`.

**Comment by Bellahra** [comment]
> There are multiple issues with this code.
> 
> 1. As @ggouaillardet indicated calling `MPI_Comm_create_group` with `MPI_GROUP_EMPTY` returns `MPI_COMM_NULL`, and it is illegal to call `MPI_Comm_size` on `MPI_COMM_NULL`.
> 2. On rank 0 (which is the rank that does not call `MPI_Comm_create_group`) the `newcomm` variable is not initialized, and that leads to badness in `MPI_Comm_size`.
> 3. Based on your question, I don't think this code does what you expect it to do. There is no group create by this code, ever. The reason is simple, you create the comm from `MPI_GROUP_EMPTY` so it will always result in `MPI_COMM_NULL`. If I understand what you are trying to do, I don't think using `MPI_Comm_create_group` is the right way to go, but instead you should take a look at `MPI_Comm_split`.

Thank you for your reply. I have tried your solution, and below is my code
```Fortran
program test7
    use mpi
    implicit none
    integer :: rank, n_ranks, ierr, n1_ranks, rank1
    integer :: group, newcomm
    call MPI_Init(ierr)
    call MPI_Comm_size(MPI_COMM_WORLD, n_ranks, ierr) 
    call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierr)
    if (rank > 1) then
    print*,'1'
        call MPI_Comm_create(MPI_COMM_WORLD, MPI_GROUP_EMPTY, newcomm, ierr)
    else
        newcomm = MPI_COMM_NULL
    end if
    if (newcomm /= MPI_COMM_NULL) then
    print*,'begin'
        CALL MPI_Comm_group(newcomm, group, ierr)
        call MPI_Group_rank(group, rank1, ierr)
        call MPI_Group_size(group, n1_ranks, ierr)
        print*, "Rank ", rank, " belongs to the new group with size ", n1_ranks
    endif
    call MPI_Finalize(ierr)
end program test7
```
where I replaced the MPI_Comm_Split with its equivalent one, MPI_Comm_Create. I run the code with 5 CPU cores, but it takes tens of minutes to run, and now only one '1' was printed. So I am not sure whether it can function correctly.  Why does creating a new group consume so much time?

**Comment by bosilca** [comment]
I'm afraid you missed quite a bit of the underlying nature of the communicator creation. At the highest level the communicator creation functions are **collective**, aka. all processes involved must call them. Now, depending on the MPI functions you use, the definition of **involved** differs, but overall it falls into one of the following two categories:
1. All participants in the original communicator: This applies to `MPI_Comm_create` and to `MPI_Comm_split`;
2. All participants in the group involved: This applies to : `MPI_Comm_create_group`.
For each of the communicator creation function this is well defined in the standard.

Now, let's go back to your new example, the one using `MPI_Comm_create`. This function is collective across all ranks in the original communicator, in your case `MPI_COMM_WORLD`. As you only make ranks > 1 go into this function, it is not collective and thus will eventually block.

Here is a working example:
```fortran
program test7
    use mpi
    implicit none
    integer :: rank, n_ranks, ierr, n1_ranks, rank1
    integer :: group, newcomm, color
    call MPI_Init(ierr)
    call MPI_Comm_size(MPI_COMM_WORLD, n_ranks, ierr)
    call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierr)
    color = 1 ! for now all ranks participate
    if (rank == 0) then ! let's exclude 1 from the resulting communicator
       color = MPI_UNDEFINED
    endif
    call MPI_Comm_split(MPI_COMM_WORLD, color, rank, newcomm, ierr)

    if (newcomm /= MPI_COMM_NULL) then
        print*,'begin'
        CALL MPI_Comm_group(newcomm, group, ierr)
        call MPI_Group_rank(group, rank1, ierr)
        call MPI_Group_size(group, n1_ranks, ierr)
        print*, "Rank ", rank, "in MPI_COMM_WORLD belongs to the new group with size ", n1_ranks, " as rank ", rank1
     else
        print*, "Rank ", rank, "in MPI_COMM_WORLD does not belongs to the new group"
    endif
    call MPI_Finalize(ierr)
end program test7
```

**Comment by Bellahra** [comment]
@bosilca Thank you most sincerely. Your explanation is very clear and helped me with exactly what I have misunderstood.

**Comment by wenduwan** [comment]
@Bellahra Please let us know if you have followup questions. Or this issue will be closed automatically.
