### ISSUE TITLE
Failed to build RPM from SRPM because of large UID and old tar command

### ISSUE THREAD

**Issue by acgoldma** [open-mpi/ompi#12540]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

Any version of Open MPI may have this issue (have seen it with SRPMs from 4.1.5 and 5.0.2)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Open MPI was built from SRPM

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

N/A

### Please describe the system on which you are running

* Operating system/version: RHEL 9.2
* Computer hardware: Intel x86_64 SKX CPU
* Network type: N/A

-----------------------------

## Details of the problem

The default tar format does not support UIDs larger than 20 bits (tar-ustar).
Should switch to tar-pax to use current POSIX tar which has more support. 
https://www.gnu.org/software/tar/manual/html_node/Formats.html#Formats

pax has been the POISX standard since 2001 (ustar is the POSIX.1-1988). 

https://github.com/open-mpi/ompi/blob/8ecda5225b378fea25943039f36897225ce34026/configure.ac#L106

Should be a simple fix, but needs to be validated on more nodes then I can. 
```diff
  # Init automake
  #
- AM_INIT_AUTOMAKE([foreign dist-bzip2 subdir-objects no-define 1.13.4 tar-ustar])
+ AM_INIT_AUTOMAKE([foreign dist-bzip2 subdir-objects no-define 1.13.4 tar-pax])

```

May need to be replicated to 3rd-party libs.

**Comment by wenduwan** [comment]
Thanks for reporting the issue and providing the fix. The issue will be fixed in 5.0.4 release.

**Comment by acgoldma** [comment]
If there are future 4.x releases can this be backported?

**Comment by jsquyres** [comment]
@acgoldma Yes, there will likely be at least one more v4.1.x release.  https://github.com/open-mpi/ompi/pull/12558
