### ISSUE TITLE
Issues running OpenMPI 5.0.3

### ISSUE THREAD

**Issue by mikekatana** [open-mpi/ompi#12553]
I am getting following message when running Open MPI 5.0.3 - latest PMIX and PRRTE is installed. LD_LIBRARY_PATH is set correctly 

~/openmpi-5.0.3$ mpiexec --version
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_preg_compress has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_psec_native has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_gds_ds12 has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_preg_native has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_bfrops_v12 has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_bfrops_v21 has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_psensor_heartbeat has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_bfrops_v20 has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_gds_hash has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_psec_none has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_psensor_file has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_ptl_tcp has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_plog_syslog has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_psquash_flex128 has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_pshmem_mmap has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_psquash_native has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_ptl_usock has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_plog_default has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_bfrops_v3 has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_plog_stdfd has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_gds_ds21 has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
[fbhost07:557711] mca:base:process_repository_item filename /usr/local/lib/pmix/mca_pcompress_zlib has bad prefix - expected:
        pmix_mca_
or
        libpmix_mca_
mpiexec (Open MPI) 5.0.3

* Ubuntu 22.04
* x86
* tcp

-----------------------------

## Details of the problem

See meesage above
```

**Comment by rhc54** [comment]
Looks like you have an old PMIx installed in the same location - you need to get rid of it.

**Comment by mikekatana** [comment]
Removed all PMIX fragments from Ubuntu 22.04 and re-installed 5.0.3 by using the --with-pmix=internal switch. Then 5.0.3 works.
