### ISSUE TITLE
--hostfile option not working as expected

### ISSUE THREAD

**Issue by rhl-bthr** [open-mpi/ompi#12574]
Running `mpirun --hostfile hosts -np 2 hostname`, both the processes are executed on the same host, and none on the other. I did verify that the hostfile is being detected (mpirun crashed when I deleted the file).

My `hosts` file looks like,
```
10.4.0.1
10.4.0.2
```

Weirdly enough, if I add duplicate the 2 entries in the host file, making the total of 4, then running `mpirun -np 4` runs 2 processes per host.

I'm running Ubuntu 22.04 on both machines, and they're accessible to each other via ssh (without any credentials).

**Comment by rhc54** [comment]
Yes, that is exactly as it should do. I'd suggest reading the hostfile documentation - it explains all this and provides examples.

**Comment by rhc54** [comment]
> Sorry, maybe I should have been clearer. Running mpi with 2 hosts in the hostfile, and setting `-np 2`, still runs both processes on the _same_ one host, and none on the other. My expectation was that it would run one process per host.

No, that expectation is not correct. You really should read the hostfile doc - we spent quite a bit of time on it to ensure it clearly explained all this.

> If so, is there a way I can use -hostfile but still enforce the behavior that runs one process per host, which is what I'm getting when I run mpi with the setting mpirun -host 10.4.0.1,10.4.0.2 -np 2 hostname

Sure - but the precise syntax depends on which OMPI version you are using (which you haven't told us). You might want to try `mpirun --help` or check the `mpirun` documentation for placement options.
