### ISSUE TITLE
Slurm "run" is failing to find "munge" component when run with "container-name"

### ISSUE THREAD

**Issue by RamHPC** [open-mpi/ompi#12571]
Slurm "srun" is failing to find "munge" component when run with "--container-name" option. There are no issues with running (srun) MPI applications. I can clearly see in the debug log, munge component is found, opened, init and creating credentials etc. I am trying to run simple NVIDIA benchmarking application called "image segmentation".

* If you have a problem building or installing Open MPI, [be sure to read this](https://docs.open-mpi.org/en/main/getting-help.html#for-problems-building-or-installing-open-mpi).
* If you have a problem launching MPI or OpenSHMEM applications, [be sure to read this](https://docs.open-mpi.org/en/main/getting-help.html#for-problems-launching-mpi-or-openshmem-applications).
* If you have a problem running MPI or OpenSHMEM applications (i.e., after launching them), [be sure to read this](https://docs.open-mpi.org/en/main/getting-help.html#for-problems-running-mpi-or-openshmem-applications).

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)
Slurm - 23.11.5
OpenMPI - 5.0.3
Pmix - 5.0.2
Enroot - 3.4.1-1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
From Source.
RHEL 8.5

### Please describe the system on which you are running

* Operating system/version: RHEL 8.5
* Computer hardware: HPE Server with A100
* Network type: Mellanox IB

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.
```shell
$ srun --mpi=pmix --container-name=image_segmentation_105400 bash -c "all_reduce_perf_mpi -b 62M -e 62M -d half"
```
[gpu1:921435] psquash: flex128 init
[gpu1:921435] psquash: native init
[gpu1:921435] psquash: flex128 init
srun: error: gpu1: task 0: Exited with exit code 1
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened. This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded). Note that
PMIX stopped checking at the first component that it did not find.

Host: gpu1
Framework: psec
Component: munge
It looks like pmix_init failed for some reason; your parallel process is
likely to abort. There are many reasons that a parallel process can
fail during pmix_init; some of which are due to configuration or
environment problems. This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
PMIX developer):

pmix_psec_base_open failed
--> Returned value -46 instead of PMIX_SUCCESS
[gpu1:926665] PMIX ERROR: NOT-FOUND in file client/pmix_client.c at line 562
[gpu1:926665] OPAL ERROR: Not found in file pmix3x_client.c at line 112
The application appears to have been direct launched using "srun",
but OMPI was not built with SLURM's PMI support and therefore cannot
execute. There are several options for building PMI support under
SLURM, depending upon the SLURM version you are using:

version 16.05 or later: you can use SLURM's PMIx support. This
requires that you configure and build SLURM --with-pmix.

Versions earlier than 16.05: you must use either SLURM's PMI-1 or
PMI-2 support. SLURM builds PMI-1 by default, or you can manually
install PMI-2. You must then build Open MPI using --with-pmi pointing
to the SLURM PMI library location.

Please configure as appropriate and try again.
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
*** and potentially your MPI job)
[gpu1:926665] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
srun: error: gpu1: task 0: Exited with exit code 1
---------------
If I run a simple MPI application 
```shell
shell$srun --ntasks=6 --nodes=1 slurm_mpi_app ${job}
```
I don't see any problem with PMIX and psec finding munge component. With the container I don't get PMIX debug messages also.

PMIX Debug messages:
[gpu1:910061] mca: base: component_find(pmix): searching NULL for psec components
[gpu1:910061] mca: base: find_dyn_components(pmix): checking NULL for psec components
[gpu1:910061] mca: base: component_find_check(pmix): checking for munge component
[gpu1:910061] mca: base: component_find_check(pmix): checking for native component
[gpu1:910061] pmix:mca: base: components_register: registering framework psec components
[gpu1:910061] pmix:mca: base: components_register: found loaded component native
[gpu1:910061] pmix:mca: base: components_register: component native has no register or open function
[gpu1:910065] mca: base: component_find_check(pmix): checking for native component
[gpu1:910065] mca: base: components_open: opening psec components
[gpu1:910065] mca: base: components_open: found loaded component native
[gpu1:910065] mca: base: components_open: component native open function successful
[gpu1:910065] mca: base: components_open: found loaded component munge
[gpu1:910065] mca: base: components_open: component munge open function successful
[gpu1:910065] mca:psec:select: checking available component native
[gpu1:910065] mca:psec:select: Querying component [native]
[gpu1:910065] psec: native init
[gpu1:910065] mca:psec:select: checking available component munge
[gpu1:910065] mca:psec:select: Querying component [munge]
[gpu1:910065] psec: munge init
[gpu1:910066] mca:psec:select: checking available component munge
[gpu1:910066] mca:psec:select: Querying component [munge]
[gpu1:910066] psec: munge init
[gpu1:910061] pmix:mca: base: components_register: found loaded component munge
[gpu1:910061] pmix:mca: base: components_register: component munge has no register or open function
[gpu1:910061] mca: base: component_find_check(pmix): checking for munge component
[gpu1:910061] mca: base: component_find_check(pmix): checking for native component
[gpu1:910061] mca: base: components_open: opening psec components
[gpu1:910061] mca: base: components_open: found loaded component native
[gpu1:910061] mca: base: components_open: component native open function successful
[gpu1:910061] mca: base: components_open: found loaded component munge
[gpu1:910061] mca: base: components_open: component munge open function successful
[gpu1:910061] mca:psec:select: checking available component native
[gpu1:910061] mca:psec:select: Querying component [native]
[gpu1:910061] psec: native init
[gpu1:910061] mca:psec:select: checking available component munge
[gpu1:910061] mca:psec:select: Querying component [munge]
[gpu1:910061] psec: munge init
[gpu1:910065] Final psec priorities
[gpu1:910065]   psec: munge Priority: 80
[gpu1:910065]   psec: native Priority: 10
[gpu1:910066] Final psec priorities
[gpu1:910066]   psec: munge Priority: 80
[gpu1:910066]   psec: native Priority: 10
[gpu1:910061] Final psec priorities
[gpu1:910061]   psec: munge Priority: 80
[gpu1:910061]   psec: native Priority: 10
[gpu1:910065] ptl:tcp: connecting to server

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:

**Comment by rhc54** [comment]
Couple of possibilities:

1. the PMIx inside the container was not built with munge support
2. the container itself lacks the munge library

Slurm requires that the munge support be present, or else you will get those errors.

**Comment by RamHPC** [comment]
Yes. OpenMPI, PMIx and all other libraries are not part of the container. My expectation with Enroot/Pyxis is that it will utilize the installation from the host machine. Please suggest if that understanding is wrong. Slurm is working fine on the cluster which uses munge. I am not interested to build the container with all these packages like slurm, openmpi, pmix, ucx etc.

**Comment by rhc54** [comment]
I'm not sure I understand how you are intending the app inside the container to load all those libraries and their dependencies. What kind of container is this? Are you mounting the location where munge can be found, and is it mounted to the same path where PMIx expects to find it?

**Comment by RamHPC** [comment]
This looks like a problem in enroot or providing configurations to enroot. The PATH and LD_LIBRARY_PATH need to be exported to enroot for the container to find the correct libraries. Thank you for your earlier suggestion which provided a clue that the local "env" is not getting exported to enroot -> container. I am closing the issue here and follow up with Enroot/Pyxis project.
