### ISSUE TITLE
Connections to nodes are closed after 30 minutes.

### ISSUE THREAD

**Issue by yuangcao** [open-mpi/ompi#12576]
Hi,

### What version of Open MPI are you using?

v4.0.3

### Describe how Open MPI was installed

I installed it from a source tarball.
```bash
wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.3.tar.gz
tar zxvf openmpi-4.0.3.tar.gz
cd openmpi-4.0.3.tar.gz
./configure --prefix=/usr/local/
make all
sudo make install
```

### Please describe the system on which you are running

* Operating system/version: CentOS Linux release 7.6.1810 (Core)
* Computer hardware: x86_64
* Network type: Ethernet

-----------------------------

## Details of the problem

I use `mpirun` to run `mdtest` on three nodes (physical servers):
```shell
mpirun --allow-run-as-root -np 96 --hostfile ~/hostfile.me --map-by node mdtest -d ~/testdir -n 3300000 -i 1 -F -C -z 0 -u
```

`~/hostfile.me`:
```
localhost max_slots=40
node5 max_slots=40
node6 max_slots=40
```

My problem is that if the program running time is longer than 30 minutes, the two servers (node4, node5) will close the connection. The output is as follows:
```
No OpenFabrics connection schemes reported that they were able to be
used on a specific port.  As such, the openib BTL (OpenFabrics
support) will be disabled for this port.

  Local host:           node4
  Local device:         mlx5_bond_0
  Local port:           1
  CPCs attempted:       rdmacm, udcm
--------------------------------------------------------------------------
-- started at 05/27/2024 12:47:10 --

mdtest-4.1.0+dev was launched with 96 total task(s) on 3 node(s)
Command line used: /usr/local/bin/mdtest '-d' '/home/cya/testdir' '-n' '3300000
' '-i' '1' '-F' '-C' '-z' '0' '-u'
Nodemap: 100100100100100100100100100100100100100100100100100100100100100100100100100100100100100100100100
Path                : /home/cya/testdir
FS                  : 10.0 GiB   Used FS: 0.0%   Inodes: 0.0 Mi   Used Inodes: 3.7%
96 tasks, 316800000 files
[node4:811607] 31 more processes have sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
[node4:811607] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
       Connection to 10.52.140.26 closed by remote host.
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
Connection to 10.52.134.218 closed by remote host.
```

ip address:
- node5: 10.52.140.26
- node6: 10.52.134.218

If the running time is less than 30 minutes, the program can finish successfully. If it running more than 30 minutes, the error will occur.

I ran `mpirun --allow-run-as-root -np 96 --hostfile ~/hostfile.me --map-by node sleep 40m` and after 30 minutes the program exit with the same error as above. Besides, the ssh connection between these servers will close after being idle for 30 minutes.

I changed the value in `/proc/sys/net/ipv4/tcp_keepalive_time` from 300 to 7200, and the problem still exists.

I think it is a network problem. The system closes the TCP connection idle for 30 minutes. But I don't know how to solve it after 3 hours search, so I come here to look for help.

Thanks for your time.

**Comment by yuangcao** [comment]
The problem disappeared after adding `ServerAliveInterval 60`. Thanks a lot!

But I wonder why. I think `mpirun` connects nodes using TCP, but the `ServerAliveInterval` works for ssh. Why does this ssh parameter influence the behavior of TCP connections?

**Comment by bosilca** [comment]
OMPI redirects all output through our own channels, so your ssh connections will drop, killing the processes on the corresponding nodes. OMPI then interpret this as not being able to connect to some processes and bails out.

**Comment by ggouaillardet** [comment]
FWIW, I noted the error message is misleading:
```
ORTE was unable to reliably start one or more daemons.
```
Everything suggests the daemons were correctly started, but they died unexpectedly after that.
If `prrte` has a similar issue, this is something we could investigate and improve.

**Comment by yuangcao** [comment]
OMPI spawns `orted` daemon through `ssh`. In my case, the ssh connection working for communicating between localhost `mpirun` and remote host `orted` was closed due to a long time idle, and that is the reason of the problem I met. Am I correct?

**Comment by ggouaillardet** [comment]
The successful workaround suggests this is what happened.

**Comment by yuangcao** [comment]
Okey. Thank you.
