### ISSUE TITLE
Error while building from source openmpi 5.0.3

### ISSUE THREAD

**Issue by intelligi123** [open-mpi/ompi#12598]
Please submit all the information below so that we can understand the working environment that is the context for your question.

* If you have a problem building or installing Open MPI, [be sure to read this](https://docs.open-mpi.org/en/main/getting-help.html#for-problems-building-or-installing-open-mpi).
* If you have a problem launching MPI or OpenSHMEM applications, [be sure to read this](https://docs.open-mpi.org/en/main/getting-help.html#for-problems-launching-mpi-or-openshmem-applications).
* If you have a problem running MPI or OpenSHMEM applications (i.e., after launching them), [be sure to read this](https://docs.open-mpi.org/en/main/getting-help.html#for-problems-running-mpi-or-openshmem-applications).

## Background information

Building openmpi

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)
v5.0.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
I am trying to install by building openmpi from source tarball

### Please describe the system on which you are running

* Operating system/version: ubuntu 23.10
* Computer hardware: Intel Xeon Gold 6330*2
* Network type: VMWare ESXi

-----------------------------

## Details of the problem

This is the error I am facing when run `sudo make` command

```
base/schizo_base_stubs.c:364:41: error: ‘pmix_framework_names’ undeclared here (not in a function); did you mean ‘prte_framework_names’?
  364 | static char **pmix_frameworks_tocheck = pmix_framework_names;
      |                                         ^~~~~~~~~~~~~~~~~~~~
      |                                         prte_framework_names
base/schizo_base_stubs.c: In function ‘prte_schizo_base_parse_prte’:
base/schizo_base_stubs.c:287:17: warning: ignoring return value of ‘asprintf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  287 |                 asprintf(&param, "PRTE_MCA_%s", p1);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
base/schizo_base_stubs.c:341:21: warning: ignoring return value of ‘asprintf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  341 |                     asprintf(&param, "PRTE_MCA_%s", p1);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
base/schizo_base_stubs.c: In function ‘prte_schizo_base_parse_pmix’:
base/schizo_base_stubs.c:432:17: warning: ignoring return value of ‘asprintf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  432 |                 asprintf(&param, "PMIX_MCA_%s", p1);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
base/schizo_base_stubs.c:466:21: warning: ignoring return value of ‘asprintf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  466 |                     asprintf(&param, "PMIX_MCA_%s", p1);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
base/schizo_base_stubs.c:471:21: warning: ignoring return value of ‘asprintf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  471 |                     asprintf(&param, "OMPI_MCA_%s", p1);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
base/schizo_base_stubs.c:512:21: warning: ignoring return value of ‘asprintf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  512 |                     asprintf(&param, "PMIX_MCA_%s", p1);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[4]: *** [Makefile:787: base/schizo_base_stubs.lo] Error 1
make[4]: Leaving directory '/home/ubuntu-6/Downloads/openmpi-5.0.3/3rd-party/prrte/src/mca/schizo'
make[3]: *** [Makefile:1705: all-recursive] Error 1
make[3]: Leaving directory '/home/ubuntu-6/Downloads/openmpi-5.0.3/3rd-party/prrte/src'
make[2]: *** [Makefile:801: all-recursive] Error 1
make[2]: Leaving directory '/home/ubuntu-6/Downloads/openmpi-5.0.3/3rd-party/prrte'
make[1]: *** [Makefile:1406: all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu-6/Downloads/openmpi-5.0.3/3rd-party'
make: *** [Makefile:1533: all-recursive] Error 1
```

**Comment by wenduwan** [comment]
@intelligi123 The issue appears to be related to a certain pmix version on your system. What is the installed pmix version on your system, e.g. `apt list --installed | grep pmix`?
