### ISSUE TITLE
Strange error messages from BCAST when inconsistent counts used

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#126]
Jeremiah Willcock reported on the users list:

```
http://www.open-mpi.org/community/lists/users/2011/02/15544.php
```

When an inconsistent count value is supplied to MPI_BCAST, we give a strange error message in v1.4:

```
*** An error occurred in MPI_Bcast 
*** on communicator MPI COMMUNICATOR 3 SPLIT FROM 0 
*** MPI_ERR_IN_STATUS: error code in status 
*** MPI_ERRORS_ARE_FATAL (your MPI job will now abort) 
```

which is strange because there is no status in a broadcast.  In v1.5, we apparently return MPI_ERR_TRUNCATE.  So this problem has already been fixed -- directly or indirectly.

Jeremiah posted a small reproducer program for v1.4:

```

#include <mpi.h> 
int arr[1142]; 
int main(int argc, char** argv) { 
   int rank, my_size; 
   MPI_Init(&argc, &argv); 
   MPI_Comm_rank(MPI_COMM_WORLD, &rank); 
   my_size = (rank == 1) ? 1142 : 1088; 
   MPI_Bcast(arr, my_size, MPI_INT, 0, MPI_COMM_WORLD); 
   MPI_Finalize(); 
   return 0; 
} 
```

He ran this with 3 or 4 MPI processes using the TCP BTL.

On the one hand, this program is clearly erroneous.  But OTOH, we should try to provide reasonable / correct error messages.

I leave it up to the v1.4 RMs as to whether they want to investigate this or not.

**Comment by awlauria** [comment]
Re-checking this on v5.0.x, it seems to work correctly by reporting an `MPI_ERR_TRUCATED` error message.

Since this was reported on an ancient version (v1.4), closing as it is no longer an issue.

```
[awlauria@f10n18 v5.0.x_08_03]$ ./exports/bin/mpirun --np 4 ./a.out 
[f10n18:00000] *** An error occurred in MPI_Bcast
[f10n18:00000] *** reported by process [4273799169,3]
[f10n18:00000] *** on communicator MPI_COMM_WORLD
[f10n18:00000] *** MPI_ERR_TRUNCATE: message truncated
[f10n18:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[f10n18:00000] ***    and MPI will try to terminate your MPI job as well)
```
