### ISSUE TITLE
Wrong configure check for cuMemFree

### ISSUE THREAD

**Issue by lahwaacz** [open-mpi/ompi#12661]
The `configure` script from OpenMPI 5.0.3 checks for the `cuMemFree` function using the following test program:

```c
extern void cuMemFree (void);
int main(int argc, char *argv[]) {
    cuMemFree ();
    return 0;
}
```

However, the *real* `cuMemFree` function is declared [as follows](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1g89b3f154e17cc89b6eea277dbdf5c93a):

    CUresult cuMemFree ( CUdeviceptr dptr )

Because of the missing parameter in the test program, compilation with nvcc 12.5 fails:

```
$ nvcc test.cu
/usr/bin/ld: /tmp/tmpxft_001b2dee_00000000-11_test.o: in function `main':
tmpxft_001b2dee_00000000-6_test.cudafe1.cpp:(.text+0x26): undefined reference to `cuMemFree()'
collect2: error: ld returned 1 exit status
```

**Comment by bosilca** [comment]
This error is during linking, where the correctness of the calls is not checked. This test is correctly identifying that no CUDA related libraries has been given on the command `nvcc test.cu`, so the check should fail. You need to specify `--with-cuda=...` and in some versions `--with-cuda-libdir=...` to build a CUDA-aware library.
