### ISSUE TITLE
io/ompio: mca parameters are not recognized in some instances

### ISSUE THREAD

**Issue by edgargabriel** [open-mpi/ompi#12682]
Thank you for taking the time to submit an issue!

## Background information

The mca parameters of the io/ompio component (and probably io/romio as well) are currently accidentally converted to PRTE parameters in ompi 5.0.x (with x <=4) and ompi main. Hence, setting e.g. 

```
mpirun --mca io_ompio_cycle_buffer_size 1024 -np 64 ./exec
```
will not yield the expected results.

The problem has been identified, and a fix is planned for ompi 5.0.6. Until then, the recommendation is to use environment variables to set mca parameters of io/ompio, e.g

```
export OMPI_MCA_io_ompio_cycle_buffer_size=1024
mpirun -x OMPI_MCA_io_ompio_cycle_buffer_size -np 64 ./exec
```

instead of runtime parameters of mpirun or settings in the `mca-parameters.conf` file.

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

5.0.x  or current main

**Comment by rhc54** [comment]
You'll need the combination of the two references PRs to fix this problem. I'll generate an OMPI-level PR to test that the combination passes CI, but someone will have to (a) pull the PRRTE changes over into the OMPI fork, and then (b) update the submodule pointers for OMPI main.

I'll be pulling the changes into the respective PMIx/PRRTE release branches, and then someone can pull the submodule pointers for OMPI v5. Will reference those changes here as well so you can know when to do it.

**Comment by edgargabriel** [comment]
sorry wrong ticket :-(

**Comment by janjust** [comment]
Can this be closed? @rhc54 @edgargabriel

**Comment by edgargabriel** [comment]
@janjust  I plan to test this today, will update the issue

**Comment by edgargabriel** [comment]
I can confirm it works with the current 5.0.x branch of ompi.
