### ISSUE TITLE
Current status of the communication resources instance optimization

### ISSUE THREAD

**Issue by JiakunYan** [open-mpi/ompi#12680]
Greetings,

I am very interested in the multi-CRI optimization described in this paper [Give MPI Threading a Fair Chance: A Study of Multithreaded MPI Designs](https://ieeexplore.ieee.org/abstract/document/8891015?casa_token=7E7t8D1xtnIAAAAA:41-j-u8qhV0pamdZlECL-AoZGt9wMrYQ8scDXHQcv3Pjogp9cuR4Jy2SxkHZfYP0-xPeXccPDxWX) (Section 3B). However, a search of "cri" or "Communication Resources Instance" in the current code base did not give me anything. Has it been merged into the OpenMPI master branch? If so, how can I enable it? (I imagine there should be a way to specify how many CRIs I want to use.) 

Probe @bosilca

**Comment by bosilca** [comment]
That was the nametag for the paper. In real life it was a much more traditional name: btl_uct_num_contexts_per_module. However, in order to get it you need to use the UCT BTL and and PML OB1, it will not work with the UCX PML.

**Comment by wenduwan** [comment]
Hi @JiakunYan was your question answered?

**Comment by JiakunYan** [comment]
Thanks! I will take a look at it later. Close this issue for now.
