### ISSUE TITLE
OOB Send locks if no ORTE thread (C/R related)

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#127]
rml_oob_send.c:154 relies on the opal_condition_wait to make progress (literally by calling opal_progress) if it does not have an active peer thread. However, when threads are enabled, opal_condition_wait() on line 79 uses the thread library provided condition wait which does not call opal_progress(). So this quickly leads to deadlock if you enable thread support by doing something like 'opal_set_using_threads(true);'.

The C/R thread calls `opal_set_using_threads(true)` since it is setting up a new thread and a mutex lock. By enabling the C/R thread we cause things to lock up due to the problem above.

So the hack is to not enable threads when enabling the C/R thread and hope for the best. This is not a good solution, obviously, so I am filing this ticket so that I don't lose track of the issue.

**Comment by jjhursey** [comment]
The C/R code has been removed from the current master and all current releases. I'm going to close this bug for now.
