### ISSUE TITLE
Configure can't continue during Open MPI install

### ISSUE THREAD

**Issue by Cecepoi** [open-mpi/ompi#12708]
Hi,

I am trying to install openmpi-5.0.1 on a x86_64 GNU/Linux system. However, when I run the configure command (./configure --prefix=/usr/local/openmpi ), it stops with this warning:

checking size of Fortran CHARACTER... configure: WARNING: Could not determine size of CHARACTER
configure: WARNING: See config.log for details
configure: error: Cannot continue

I checked Fortran and it is able to compile
[config.log](https://github.com/user-attachments/files/16365368/config.log)
. I have no experience with all these stuff before. Bellow is the configure log. 

Thank you!

**Comment by ggouaillardet** [comment]
This is the culprit:

```
configure:30461: checking size of Fortran CHARACTER
configure:30527: gcc -O3 -DNDEBUG  -finline-functions -mcx16 -I. -c conftest.c
configure:30530: $? = 0
configure:30534: gfortran   conftestf.f90 conftest.o -o conftest
/usr/bin/ld: conftest.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
configure:30537: $? = 1
```

with `conftestf.f90`
```
program fsize

   external size
   CHARACTER :: x(2)
   call size(x(1),x(2))
end program
```
and `conftest.c`
```
#include <stdio.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif
void size_(char *a, char *b)
{
    int diff = (int) (b - a);
    FILE *f=fopen("conftestval", "w");
    if (!f) exit(1);
    fprintf(f, "%d\n", diff);
}
#ifdef __cplusplus
}
#endif
```

I noted you are mixing your own `gcc 9.3.0` compiler with the distro `gfortran 7.5.0`, so that could be an issue.
Options are to build `gfortran 9.3.0` or try using the workaround suggested by the error message (e.g. use `-fPIC` with `gcc` and/or `gfortran` and see if you can build the test, and if so, pass these flagc to `configure`)

**Comment by Cecepoi** [comment]
Thank you so much, problem solved!
