### ISSUE TITLE
Non-compliant C90 comments at mpi.h file leads to compilation failure for codes compiled with gcc -ansi or -std=c90 flags

### ISSUE THREAD

**Issue by bcmundim** [open-mpi/ompi#12710]
### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

v5.0.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From a source/distribution tarball

### Please describe the system on which you are running

* Operating system/version: Linux CentOS/7.9
* Computer hardware: Lenovo SR630 server
* Network type: Infiniband

-----------------------------

## Details of the problem

While trying to compile one of [Visit](https://www.visitusers.org) software dependencies, [IceT](https://www.sandia.gov/ccr/software/icet/), the compilation was interrupted with an error while parsing OpenMPI mpi.h file included in one of their files. I tracked the problem down to non C90 compliant comments in the mpi.h. IceT uses the gcc -ansi flag and that triggers this bug. You can easily reproduce it by trying to compile the hello_c example you ship with the OpenMPI source code:

```bash
me@somewhere:~/src/openmpi/openmpi-5.0.5/examples$ CFLAGS=-ansi make hello_c
mpicc -ansi -g  hello_c.c  -o hello_c
In file included from /path/to/software/2022a/opt/gcc-11.3.0/openmpi/5.0.2+ucx-1.15.0/include/mpi.h:285,
                 from hello_c.c:11:
/path/to/software/2022a/opt/gcc-11.3.0/openmpi/5.0.2+ucx-1.15.0/include/mpi_portable_platform.h:294:30: error: operator '/' has no right operand
  294 | #elif defined(__NVCOMPILER) // Must occur prior to PGI and CLANG
      |                              ^
make: *** [hello_c] Error 1
```

This could be tracked down further at two comments on the header file ./opal/include/opal/opal_portable_platform_real.h at lines 294 and 593. I am not sure if there are other places that eventually will end up in the public facing mpi.h file though. Would it be possible to replace those comments with the C90 ones? At least on the public facing header files such as mpi.h?

Thanks!

**Comment by jsquyres** [comment]
@bcmundim Sorry for the delay; this question slipped by me.

Open MPI has required a C99 compiler for many years.  It's a bit surprising that a IceT is requiring a 30+ year old C standard, especially if it requires `mpi.h`.  Can IceT really not be compiled with a C99 or newer C compiler (i.e., something that is only 25+ years old)?  If so, that seems like the real issue.

**Comment by devreal** [comment]
The MPI standard is silent about specific C versions and we intentionally have not used any post-C90 features so it could be argued that the header `mpi.h` should work with any C standard (Open MPI required C99 for compiling its code, which is different from application codes).

**Comment by jsquyres** [comment]
@devreal True, but the MPI standard is silent about compiler support, too -- and Open MPI only supports a specific set of compilers.  

FWIW: It looks like the portable_platform file was last imported from Gasnet in 2021.  I won't object if someone wants to post a PR to update these things, but it seems like codes that require compiling with `-ansi` (i.e., C89) are making choices that potentially limit their applicability.

**Comment by jsquyres** [comment]
More specifically: since we import that portable_platform.h from Gasnet, we would really like to see the fix put upstream so that we can pull it down here again (including the fix).  Otherwise, we'll have to keep track of local edits the next time we pull this down (i.e., we'll forget).

**Comment by bcmundim** [comment]
@jsquyres What is gasnet? Why is  this issue being abandoned when the fix is really simple? If there is no plan to change this could you please at least announce the lack of openmpi support for C90 compiler options? Unfortunately I don't have control over IceT. My workaround was to use mpich instead of openmpi. But I would like to avoid that workaround as much as possible. Thanks.

**Comment by devreal** [comment]
@bcmundim Please see https://github.com/open-mpi/ompi/pull/12811 for a PR changing the header. I don't think we pull this is from gasnet regularly so we can patch it ourselves.

**Comment by jsquyres** [comment]
I notice that we accidentally closed this issue before resolving it.

I worked with the gasnet team and got the changes put in upstream.  I then made #12829 as an alternative to @devreal's PR.  Let's figure out which of our 2 PR's we should merge here (and cherry pick over to the v5.0.x series).

**Comment by jsquyres** [comment]
v5.0.x PR is pending.

Probably won't bring this back to v4.1.x -- I did a cherry-pick and it didn't immediately apply.  I didn't look into the conflict details, but since this issue was about v5.0.x, unless there's a specific reason to bring it to v4.1.x, I think bringing the update to main and v5.0.x is probably good enough.
