### ISSUE TITLE
test typos

### ISSUE THREAD

**Issue by spaette** [open-mpi/ompi#12738]
@luzpaz

You've made previous commits pertaining to typo fixes

So perhaps you could make an assessment if these warrant fixes and whether to modify copyrighted files.

I'm disinclined to open pulls in the Organization's repos owing to contact information being searchable in .mailmap files.

grep output

```
$ grep -nr Completet ompi/test
ompi/test/simple/intercomm1.c:16:    printf("%d Completet\n", rank);
$ grep -nr declered ompi/test
ompi/test/carto/carto-file:24:# (Reserve word)          (declered   (declered        (declered
$ grep -nr exepcted ompi/test
ompi/test/simple/concurrent_spawn.c:61:            printf("ERROR: child did not receive exepcted argv!\n");
$ grep -nr firiing ompi/test
ompi/test/simple/hello_show_help.c:32:               "sleep statements to ensure that the timer is firiing properly\nin the HNP and "
$ grep -nr opertations ompi/test
ompi/test/monitoring/check_monitoring.c:506:       MPI_COMM_WORLD with RMA opertations */
$ grep -nr sentinal ompi/test
ompi/test/util/opal_error.c:53:        1,                 /* sentinal */
$ 
```

**Comment by luzpaz** [comment]
@spaette let me see if I understand, is the code you are referencing 3rd party upstream code?

**Comment by spaette** [comment]
From the `grep` output these specific repo files have copyrights.

The first listed file you modified in a commit merged on Aug 15, 2022.

If content from this ticket is of some use then maybe I'll look at some other subdirectories.

```
$ sed 11q ompi/test/monitoring/check_monitoring.c
/*
 * Copyright (c) 2016-2017 Inria.  All rights reserved.
 * Copyright (c) 2017      The University of Tennessee and The University
 *                         of Tennessee Research Foundation.  All rights
 *                         reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */
$ sed 19q ompi/test/class/opal_pointer_array.c
/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*
 * Copyright (c) 2004-2005 The Trustees of Indiana University and Indiana
 *                         University Research and Technology
 *                         Corporation.  All rights reserved.
 * Copyright (c) 2004-2017 The University of Tennessee and The University
 *                         of Tennessee Research Foundation.  All rights
 *                         reserved.
 * Copyright (c) 2004-2005 High Performance Computing Center Stuttgart,
 *                         University of Stuttgart.  All rights reserved.
 * Copyright (c) 2004-2005 The Regents of the University of California.
 *                         All rights reserved.
 * Copyright (c) 2010      Cisco Systems, Inc.  All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */
$ sed 17q ompi/test/util/opal_error.c
/*
 * Copyright (c) 2004-2005 The Trustees of Indiana University and Indiana
 *                         University Research and Technology
 *                         Corporation.  All rights reserved.
 * Copyright (c) 2004-2005 The University of Tennessee and The University
 *                         of Tennessee Research Foundation.  All rights
 *                         reserved.
 * Copyright (c) 2004-2005 High Performance Computing Center Stuttgart,
 *                         University of Stuttgart.  All rights reserved.
 * Copyright (c) 2004-2005 The Regents of the University of California.
 *                         All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */
$ 
```

**Comment by luzpaz** [comment]
Are these upstream projects hosted on github perchance ? I'd submit typo changes to them in that case. If not, feel free to revert any changes made to their source.

**Comment by spaette** [comment]
> Are these upstream projects hosted on github perchance ? 

_cf_: LICENCE

The text "organizations who have edited" seems to indicate this repository is the upstream project. That being said perhaps it would be appropriate for a Member to review any PR modifying the cited files. As earlier indicated I won't be submitting any PRs, as I don't want my contact information accessible via search engines' indexing of .mailmap files.

```
$ sed 6q ompi/LICENSE
Most files in this release are marked with the copyrights of the
organizations who have edited them.  The copyrights below are in no
particular order and generally reflect members of the Open MPI core
team who have contributed code to this release.  The copyrights for
code used under license from other parties are included in the
corresponding files.
$ 
```

**Comment by jsquyres** [comment]
@luzpaz All of these files are in the Open MPI repository.  It's a little confusing because they're in a subdirectory named `ompi/`, but they're all here in `open-mpi/ompi`.

**Comment by rhc54** [comment]
Just to clarify a bit. The "signed-off-by" requirement has a _very_ long legal history in the open source software world. As a result, you'll find virtually every project requiring it. Basically, it protects the project from people who make a contribution that violates their employer's intellectual property agreement - i.e., the employer owns the person's work product and hasn't approved "giving it away" to the open source project.

Even students are generally covered by such agreements - colleges pretty much universally require they be signed, and even high schools have implemented them (at least, around here they have). Those agreements specify what IP you own and can contribute where/when you like, and what IP the employer owns and requires you gain permission prior to giving away - you need to know what it says.

It also protects the contributor by (hopefully) reminding them to _check_ for an IP agreement and make sure they understand it prior to submitting a contribution. People often forget they signed such a thing - and employers can (and do) hold the employee responsible for "lost IP value".

The copyright is a separate matter. It allows the employer (or contributor, if they own their own IP) to flag that they have the right to use the modified code regardless of what anyone else does with it. If you and/or your employer don't care, then don't modify the copyright text. It has no value/impact for the project.

We do have bot "do not search" flags on things like mailmap, but of course those rely on the bot paying attention to them. What some of us do is simply create a new email (e.g. "anon@gmail.com") specifically for contributing to open source projects. We can then just ignore that email should someone harvest it. Just don't use it for your GitHub account!

**Comment by spaette** [comment]
recursive `grep` for readd removed from earlier shell output and moved here

```
$ grep -nr readd ompi/test
ompi/test/class/opal_pointer_array.c:161:                test_failure("Add/Remove: failure during the readd ");
$ 
```

GNU sed commands (via script)

```
$ cat typos.sh
#!/bin/sh

sed -i "s/Completet/Complete/g" ompi/test/simple/intercomm1.c
sed -i "s/declered/declared/g" ompi/test/carto/carto-file
sed -i "s/exepcted/expected/g" ompi/test/simple/concurrent_spawn.c
sed -i "s/firiing/firing/g" ompi/test/simple/hello_show_help.c
sed -i "s/opertations/operations/g" ompi/test/monitoring/check_monitoring.c
sed -i "s/sentinal/sentinel/g" ompi/test/util/opal_error.c
$
```

**Comment by spaette** [comment]
_dealing with dumped strings_

@bosilca
committed Apr 18, 2017

I presume `readd` was the committer's intention.

```
$ sed -n '158,165p' ompi/test/class/opal_pointer_array.c
    for (i = 0; i < 4; i++) {
        if (!opal_pointer_array_add(array, (void *) (uintptr_t)(i + 1))) {
            if (i != 2) {
                test_failure("Add/Remove: failure during the readd ");
                break;
            }
        }
    }
$ 
```

<hr>

_for my own records_

These files affected by this ticket's associated commits have had their copyrights updated.

test/monitoring/check_monitoring.c
test/util/opal_error.c

**Comment by spaette** [comment]
@rhc54

Is the GH username sufficient?

`https://docs.open-mpi.org/en/main/contributing.html#contributing-contributors-declaration-label`

Each proposed contribution to
the Open MPI code base must include the text Signed-off-by: followed by the contributor’s name
and email address.


**Pro tip**

You can use the `-s` flag to the git commit command (i.e., `git commit -s ...`) to automatically
add the appropriate `Signed-off-by: `line to your commit message.

**Comment by rhc54** [comment]
Up to the OMPI folks for the OMPI portions. For my repos (PMIx/PRRTE), I would tend not to accept it. This is a legal statement declaring that you have the right to make the contribution. I'd rather not tie that to some moniker that can disappear. If you are that concerned about your info, then I'd suggest just leaving things alone - while contributions are appreciated, corrections for minor typos probably don't warrant you dealing with the angst.

**Comment by rhc54** [comment]
Like I said - for me, the GH moniker isn't sufficient. I don't really feel a lot of concern about minor typos in comments - nice to clean them up, but nobody will suffer if they aren't (regardless of how many lines are impacted). If the issue of meeting the legal requirements is an obstacle to you, then I'd suggest simply letting things go.
