### ISSUE TITLE
clarify how to report bugs

### ISSUE THREAD

**Issue by loveshack** [open-mpi/ompi#1273]
I reported a couple of bugs I found in the v2 pre-release in the tracker for the repo it's from, and was told I should have put them here.  I can't see anything to tell me that, and on checking the README, I find it says the best way is to post them to the mail ilsts.

Could you clarify somewhere prominent how to report bugs and, if possible, do something to prevent people wasting time by reporting them against repos where you don't want them?  If the README is right, it would probably be useful to explicitly deprecate the issue trackers there.

**Comment by ggouaillardet** [comment]
@loveshack as far as I am concerned, the best way to report a bug is via the mailing list (users or devel)

though it might seem counter-intuitive, mailing lists are actively monitored by ompi developers, whereas github issues are not.

**Comment by ggouaillardet** [comment]
@jsquyres @hppritcha @rhc54 

what about disabling issues for the ompi-release repo ?
see https://help.github.com/articles/disabling-issues/

**Comment by rhc54** [comment]
Good suggestion - done!

FWIW: we do actually receive email from every issue filed against the OMPI master repository, so reporting bugs there is just fine. The README is reporting the historical method for reporting bugs that predates our use of GitHub - we should discuss on the telecon whether or not to change it.

**Comment by hppritcha** [comment]
I think this can be closed now due to our how-to-report-an-issue template.
