### ISSUE TITLE
Which tools can use to measure Hockney model parameters with OpenMPI?

### ISSUE THREAD

**Issue by astrung** [open-mpi/ompi#1274]
Now, i am using Hockney model to analyze communication performance,and i need a tools (or some methods,ways,..) to calculate Latency and Bandwidth of the network(Hockney model parameters).So does OpenMPI provide some tools to caculate,or some tools which can use with OpenMPI to do it???

**Comment by jsquyres** [comment]
I'm afraid not.  If there are generic MPI programs out there that can calculate these parameters for you, they should work with Open MPI, but Open MPI doesn't provide such tools as part of its distribution.

If you're looking for simple point-to-point latency and bandwidth measurements between a pair of peers, there's a bunch of simple latency and bandwidth MPI benchmarks available.  The OSU benchmarks come to mind, as well as the Intel MPI benchmarks, and Skampi (although that might not be maintained any more...?), and/or NetPIPE (which I think is in the middle of being resurrected).  You can Google around for more.
