### ISSUE TITLE
Getting "free(): corrupted unsorted chunks" error while running mpirun

### ISSUE THREAD

**Issue by NancyAgarwal013** [open-mpi/ompi#12744]
Hi Team,

I was trying to run openMPI in one of my GPU Node for distributed testing but getting below error

![image](https://github.com/user-attachments/assets/198048f1-8425-4d64-8050-dd97ebb90f6c)

Can anyone let me know what can be possible reason here, I downloaded HPCx inside my node and from there I was trying to run mpi.

**Comment by nancyagarwal1301** [comment]
While debugging more I can see this negative size error. But from where is it picking it up and how to resolve this?

![image](https://github.com/user-attachments/assets/8fb86ed1-4cf5-4187-87ab-1ca6740488ff)

**Comment by devreal** [comment]
@NancyAgarwal013 can you please post the full stack trace (and not as screenshots) so we can see how we got to the UCP callsite of `memset`?

**Comment by jsquyres** [comment]
@NancyAgarwal013 Also, can you post all the information asked for in the bug template?

https://github.com/open-mpi/ompi/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
