### ISSUE TITLE
An error while building OpenMPI

### ISSUE THREAD

**Issue by zxy1119** [open-mpi/ompi#12780]
An error while building OpenMPI , please tell my why

![image](https://github.com/user-attachments/assets/c0b405b8-6438-474f-b75f-4a8e680d872a)

**Comment by ggouaillardet** [comment]
Because you either messed up the timestamps, or you screwed up somewhere else.

**Comment by zxy1119** [comment]
May I ask how I can solve or troubleshoot the problem

**Comment by jsquyres** [comment]
@zxy1119 For us to help you troubleshoot the problem, we need all the information from the github issue template -- a screenshot showing a single error is not enough.  Can you provide all that information?

https://github.com/open-mpi/ompi/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
