### ISSUE TITLE
When use "from mpi4py import MPI" in docker container, I meet an error as follows

### ISSUE THREAD

**Issue by gyxu-cycle** [open-mpi/ompi#12786]
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1665)..............: 
MPIDI_OFI_mpi_init_hook(1586): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1665)..............: 
MPIDI_OFI_mpi_init_hook(1586): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor

**Comment by jsquyres** [comment]
I'm sorry, this is not using Open MPI; it's using MPICH.  Open MPI and MPICH are completely different implementations of the MPI specification; they are entirely different code bases and communities of developers.  You will need to ask your question over in the MPICH community.
