### ISSUE TITLE
.

### ISSUE THREAD

**Issue by atanuchaudhury** [open-mpi/ompi#12790]

**Comment by AstroSuro** [comment]
Please provide the user name and pwd both for your desktop and server. 
Also provide the path where the scripts are located.

**Comment by rhc54** [comment]
> Please provide the user name and pwd both for your desktop and server. Also provide the path where the scripts are located.

PLEASE do not post that info on this public site!!!

**Comment by AstroSuro** [comment]
> > Please provide the user name and pwd both for your desktop and server. Also provide the path where the scripts are located.
> 
> PLEASE do not post that info on this public site!!!

Sorry.. My bad. I typed in wrong issue..

**Comment by atanuchaudhury** [comment]
desktop
id: desktop-aa6kout\yd
pass: UmichMTE / ***@***.***

server
ssh ***@***.***
Pass:acmt2024

path: /home/achaudhury/olb-1.7r0/examples/laminar/cylinder3d
