### ISSUE TITLE
C/R Performance Bug with non-blocking communication

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#128]
It was reported on the Open MPI users mailing list that there may be a performance bug in the C/R coordination protocol implementation regarding non-blocking send/recv calls.

This was reported by Nguyen Toan in the following thread.
- [http://www.open-mpi.org/community/lists/users/2011/02/15525.php]

The attached tarball is a repeater benchmark from Nguyen Toan to help highlight the problem for further debugging.

**Comment by jjhursey** [comment]
The C/R code has been removed from the current `master` and all current releases. I'm going to close this bug for now.
