### ISSUE TITLE
Building OPenMpi with LSF

### ISSUE THREAD

**Issue by fabiosanger** [open-mpi/ompi#12804]
Thank you for taking the time to submit an issue!

## Background information
I am trying to build openmpi with lsf support using --with-lsf

`sudo ./configure --with-lsf=/usr/local/lsf/10.1 --with-lsf-libdir="${LSF_LIBDIR}" --with-cuda=/usr/local/cuda --enable-mca-dso=btl-smcuda,rcache-rgpusm,rcache-gpusm,accelerator-cuda --prefix=/software/openmpi-5.0.3`

### What version of Open MPI are you using?

v5.0.3, v5.0.4, v5.0.5

### Describe how Open MPI was installed 

distribution tarball

### Please describe the system on which you are running

* Operating system/version: Linux Jelly 22.04
* Computer hardware: HPC
* Network type: TCP

-----------------------------

## Details of the problem

> --- MCA component ess:lsf (m4 configuration macro)
> checking for MCA component ess:lsf compile mode... static
> checking for library containing yp_all... -lnsl
> checking for library containing shm_open... none required
> checking for lsf pkg-config name... /software/lsf-isg-test-cluster-22/10.1/linux3.10-glibc2.17-x86_64/lib/pkgconfig/lsf.pc
> checking if lsf pkg-config module exists... no
> checking for lsf header at /usr/local/lsf/10.1/include... found
> checking for lsf library (lsf) in /software/lsf-isg-test-cluster-22/10.1/linux3.10-glibc2.17-x86_64/lib... found
> checking for lsf cppflags... -I/usr/local/lsf/10.1/include
> checking for lsf ldflags... -L/software/lsf-isg-test-cluster-22/10.1/linux3.10-glibc2.17-x86_64/lib
> checking for lsf libs... -llsf -lnsl
> checking for lsf static libs... -llsf -lnsl
> checking for lsf/lsf.h... yes
> checking for ls_info... no
> checking for libevent conflict... No conflict found. -levent is not being explicitly used.
> configure: WARNING: LSF support requested (via --with-lsf) but not found.
> configure: error: Aborting.
> configure: ===== done with 3rd-party/prrte configure =====
> configure: error: PRRTE configuration failed.  Cannot continue.

**Comment by fabiosanger** [comment]
I will try that tomorrow in the mean time

[config.log](https://github.com/user-attachments/files/16935347/config.log)

**Comment by fabiosanger** [comment]
modified configure as

`sudo ./configure --with-lsf=/usr/local/lsf/10.1 --with-lsf-libdir="${LSF_LIBDIR}" --with-cuda=/usr/local/cuda --enable-mca-dso=btl-smcuda,rcache-rgpusm,rcache-gpusm,accelerator-cuda LIBS="-lnsl -levent" LDFLAGS="-L/usr/lib/x86_64-linux-gnu" --prefix=/software/openmpi-5.0.3`

error message
```
[--- MCA component ess:lsf (m4 configuration macro)
checking for MCA component ess:lsf compile mode... static
checking for library containing yp_all... none required
checking for library containing shm_open... none required
checking for lsf pkg-config name... /software/lsf-isg-test-cluster-22/10.1/linux3.10-glibc2.17-x86_64/lib/pkgconfig/lsf.pc
checking if lsf pkg-config module exists... no
checking for lsf header at /usr/local/lsf/10.1/include... found
checking for lsf library (lsf) in /software/lsf-isg-test-cluster-22/10.1/linux3.10-glibc2.17-x86_64/lib... found
checking for lsf cppflags... -I/usr/local/lsf/10.1/include
checking for lsf ldflags... -L/software/lsf-isg-test-cluster-22/10.1/linux3.10-glibc2.17-x86_64/lib
checking for lsf libs... -llsf
checking for lsf static libs... -llsf
checking for lsf/lsf.h... yes
checking for ls_info... no
checking for evthread_set_condition_callbacks in -levent... yes
checking for libevent conflict... No conflict found. The correct libevent.so was linked.
configure: WARNING: LSF support requested (via --with-lsf) but not found.
configure: error: Aborting.
configure: ===== done with 3rd-party/prrte configure =====
configure: error: PRRTE configuration failed.  Cannot continue.
```

[config.log](https://github.com/user-attachments/files/16935463/config.log)

**Comment by rhc54** [comment]
I suspect this is the problem:
```shell
checking for ls_info... no
```
You might be missing a required LSF package?

**Comment by fabiosanger** [comment]
I think i found the issue

> Supported LTO compression algorithms: zlib zstd
> gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
> ... rest of stderr output deleted ...
> configure:4817: $? = 0
> configure:4806: gcc -V >&5
> gcc: error: unrecognized command-line option '-V'
> gcc: fatal error: no input files
> compilation terminated.
> configure:4817: $? = 1
> configure:4806: gcc -qversion >&5
> gcc: error: unrecognized command-line option '-qversion'; did you mean '--version'?
> gcc: fatal error: no input files
> compilation terminated.

I imported the gcc module and i can configure

**Comment by wenduwan** [comment]
@fabiosanger I'm marking this issue ready to close.

Please comment in the thread to keep it open if you have more questions.
