### ISSUE TITLE
Need suggestion regarding open system

### ISSUE THREAD

**Issue by atanuchaudhury** [open-mpi/ompi#12820]
Hello,
I want to make the cylinder3d model an open system or an unbounded flow system. For this should i use “setSlipBoundary” condition or “setZeroDistributionBoundary”? Please reply

Thank you

**Comment by edgargabriel** [comment]
You are asking this on the wrong site, Open MPI is an implementation of the MPI specification (https://www.mpi-forum.org/docs/), so the terms that you mention in the issue are not part of the MPI specificaiton.
