### ISSUE TITLE
Migration of some environment variables from openmpi 4 to openmpi 5

### ISSUE THREAD

**Issue by francesco-ballarin** [open-mpi/ompi#12873]
### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

5.0.5

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From Debian's package https://tracker.debian.org/pkg/openmpi

### Please describe the system on which you are running

Not relevant

-----------------------------

## Details of the problem

Hi,
I am updating several scripts related to debian packaging to openmpi 5.

I have changed `OMPI_MCA_rmaps_base_oversubscribe` to `PRTE_MCA_rmaps_default_mapping_policy` already, as discussed in https://docs.open-mpi.org/en/v5.0.x/mca.html

However, the scripts also use the following environment variables

- `OMPI_MCA_btl_base_warn_component_unused`
- `OMPI_MCA_plm_rsh_agent`
- `OMPI_MCA_orte_rsh_agent`

but I can't find them on that webpage.

Can you tell me what is the corresponding name in openmpi 5?
Is it as easy as replacing `OMPI` with `PRTE`? I'd rather ask and be extra sure before doing a massive search and replace in a lot of files ;)

Thanks,
Francesco

**Comment by rhc54** [comment]
> OMPI_MCA_btl_base_warn_component_unused

Unchanged

> OMPI_MCA_plm_rsh_agent

Should still be recognized (auto updated to the new form), but you can also change it to `PRTE_MCA_plm_ssh_agent`

> OMPI_MCA_orte_rsh_agent

This has disappeared, I'm afraid

**Comment by francesco-ballarin** [comment]
Thanks very much for the quick reply, I'll replace the environment variables as suggested.
