### ISSUE TITLE
v5.x failure beyond 94 nodes

### ISSUE THREAD

**Issue by tonycurtis** [open-mpi/ompi#12872]
Thank you for taking the time to submit an issue!

## Background information

Running installation tests on cluster, v5 (release or from github) works up to <= 94 nodes, then fails instantly.  v4 works fine.  N.B. this is running a job from a login node via SLURM (salloc + mpiexec).

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

main @ 448c3ba2d1b8dced090e5aefb7ccb07588613bcd

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

source / git

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

```
 e32e0179bc6bd1637f92690511ce6091719fa046 3rd-party/openpmix (v1.1.3-4036-ge32e0179)
 0f0a90006cbc880d499b2356d6076e785e7868ba 3rd-party/prrte (psrvr-v2.0.0rc1-4819-g0f0a90006c)
 dfff67569fb72dbf8d73a1dcf74d091dad93f71b config/oac (heads/main-1-gdfff675)
```

### Please describe the system on which you are running

* Operating system/version:  Rocky 8.4
* Computer hardware: aarch64
* Network type: IB

-----------------------------

## Details of the problem

Beyond 94 nodes

```
--------------------------------------------------------------------------
PRTE has lost communication with a remote daemon.

  HNP daemon   : [prterun-login2-2232463@0,0] on node login2
  Remote daemon: [prterun-login2-2232463@0,28] on node fj094

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
```

**Comment by hppritcha** [comment]
Could you try running
```
mpirun --debug-daemons -np 95 -N 1 hostname
```
that may help provide some more info for triaging.

**Comment by tonycurtis** [comment]
Er, Howard, do you mean run 95 ranks on 1 node?  Or run hostname on 1 rank on 95 nodes?

**Comment by rhc54** [comment]
The mpirun cmd line will execute one instance of `hostname` on each of 95 nodes. The `--debug-daemons` flag will hold the stdout/stderr connections open between the daemons so you can see any error messages. I'm not sure if that `salloc` command will do the same thing, but will take a gander at the output.

**Comment by rhc54** [comment]
Looks like the daemons are unable to send a message back to `mpirun` - maybe there is an issue with their choice of transport? You might need to specify the network they should use.

**Comment by tonycurtis** [comment]
Well it's an mpirun inside a salloc.  Note this means mpirun is running on the launch (in this case, login) node, not inside the job per se.  I.e. interactive test, not batch.  Tried using UCX_TLS=rc,self explicitly but same result.  4.1.6 has no issues.

If I run an interactive job and then mpirun from inside a compute node. it works with v5.

**Comment by rhc54** [comment]
UCX has nothing to do with it - not used by the runtime. Might be a difference in how we select transports between OMPI v4 and v5, but I can't say for sure. I'll have to ponder what might be going on - not hearing of scaling issues elsewhere.

**Comment by tonycurtis** [comment]
Well, I didn't think it was UCX related, but did due diligence.  I'm pretty sure I have reported this same issue either for ompi or pmix in the past.

**Comment by tonycurtis** [comment]
I'll give the if_include etc a go to see if that identifies the issue.  Seems possible.

**Comment by tonycurtis** [comment]
Yeah, that seems to be it.  Excluded the external interface, program runs

**Comment by tonycurtis** [comment]
All submodules are up to date, BTW

**Comment by rhc54** [comment]
Hooray!! Glad it solved the problem!

**Comment by tonycurtis** [comment]
This is one of those "obviously an interface choice" in hindsight things.  Testing same procedure with 5.0.5 release.

**Comment by rhc54** [comment]
I'm afraid that won't work - the "if_include/exclude" patch isn't in any OMPI release yet.

**Comment by tonycurtis** [comment]
Ah.  Well.  Fortunately I/we have kept our ompi release / default version for users at 4.1.6.  So this isn't going to cause issues for 99.9% of them.  I'll let things percolate through and catch up before moving the cluster install of ompi to v5.

thanks!

**Comment by tonycurtis** [comment]
I'll close this issue, then.
