### ISSUE TITLE
Open-MPI 4.1.7 "read more" announcement is a broken link

### ISSUE THREAD

**Issue by tonycurtis** [open-mpi/ompi#12904]
Thank you for taking the time to submit an issue!

## Background information

As subject, on www.open-mpi.org

**Comment by jsquyres** [comment]
We got a little ahead of ourselves and posted 4.1.7 before sending the announcement email.  😳 

As soon as we send out the email, the announcement link should become valid.

**Comment by tonycurtis** [comment]
should have put a barrier in, then ;)
