### ISSUE TITLE
Understanding intra-node communication: message queues vs shared memory

### ISSUE THREAD

**Issue by goelayu** [open-mpi/ompi#12912]
(If this is not the right place for this question, please point me in the right direction)

What underlying software/hardware primitive does Open MPI use to communicate between two process on the same node? Some online discussions seem to indicate that this is done on top of shared memory? I assumed shared memory **could** be one of the ways Open MPI allows two processes (on the same node) to communicate, but not the de facto. 
Are any message queues (POSIX message queue) used for such communications? 

Any pointers to relevant documentation/source-code would be greatly appreciated.

**Comment by bosilca** [comment]
It depends on the location of the source and destination memory and the type of support available. By default we are using shared memory, aka. memory mapped on both processes. However, if available, for large data transfers we can use CMA, XPMEM, KNEM, one-sided memory copy mechanism. Finally, if the memory is mapped onto accelerators we are using CUDA IPC to move data across.

In no instance we are using POSIX message queues. There is no documentation other than the code. I would look at the [SMSC components](https://github.com/open-mpi/ompi/tree/main/opal/mca/smsc) for the one-sided memory copies, the [SM BTL](https://github.com/open-mpi/ompi/tree/main/opal/mca/btl/sm) for the shared memory and then finally [SMCUDA BTL](https://github.com/open-mpi/ompi/tree/main/opal/mca/btl/smcuda) for accelerator support.
