### ISSUE TITLE
Add support for node order by Infiniband fat-tree order dump file

### ISSUE THREAD

**Issue by yosefe** [open-mpi/ompi#1293]
Infiniband SM can produce GUID order file (opensm-ftree-ca-order.dump) for fat-tree topologies which gives the optimal order for All-to-All communication.
We need a way to push this file directly to OpenMPI command line, e.g
`-mca ca_order_file <filename>`
This will re-order the nodes on which the job is running according to the order in this file (but should **not** affect local process topolgy, e.g bynode/byslot/dist...)

@miked-mellanox

**Comment by miked-mellanox** [comment]
@yosefe - basically should it generate hostfile out of ca file?

**Comment by yosefe** [comment]
@miked-mellanox it may be enough, but need to make sure.

**Comment by jsquyres** [comment]
@yosefe Are you thinking about this for v2.1.0 or so?  (v2.0.0 is feature complete)

**Comment by yosefe** [comment]
after rethinking this, it should go into the collective algorithm and not MPI rank order.
