### ISSUE TITLE
MPI_Wtime initialization can be faulty and lead to 0.0 being returned during one second

### ISSUE THREAD

**Issue by adegomme** [open-mpi/ompi#12953]
### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)
latest

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
compiled directly from latest sources

-----------------------------

## Details of the problem

In https://github.com/open-mpi/ompi/commit/9bced03213eac35250f64e9ed58dd091f7dabf1c a change to the handling of MPI_Wtime was performed, to set the origin of time at the first call, return a time of 0.0 for this one and then return values relative it later.

This improves precision, but there is a small catch/bug we found when running some simulations recently.

The issue is that the test to check if the value has already been initialized is performed by simply checking that the amount of seconds in the stored value is 0, which is the default value
See line : https://github.com/open-mpi/ompi/blob/e5cc709aaecc3e9f36a332e4db0f5767a5888150/ompi/mpi/c/wtime.c#L65

In most of the cases the first call to clock_gettime or others will return time since boot or epoch, and this value will be more than 0 second, which works. But in our particular case boot is "superfast", and we enter MPI before the 1s mark on our platform timers. This means that all calls to MPI_Wtime before the 1s mark will consider the timers as uninitialized, reinitialize it and return 0.0 in the process. Which lead to some odd timing and bandwidth results.

Fix options are either to mark things explicitely as uninitialized/initialized properly through a dedicated boolean (tested, works), or to set a really impossible uninitialized value (-1 or else), or to check nanoseconds as well. 

Even if this only triggers on a particular emulated platform, another aspect is that this seems to be non-reentrant, and even if I don't see a case where we would suffer from having several threads setting almost the same value as the default one, it might be a good idea to make it reentrant in the process.

**Comment by ggouaillardet** [comment]
Thanks for the report.

Since invoking `MPI_Wtime()` before `MPI_Init()` is an undefined behavior, the initialization could occur here too.
@bosilca @jsquyres any thoughts?

**Comment by ggouaillardet** [comment]
I got that Jeff.
Your fix works for me.
My point was that if we do the initialisation at MPI_Init() we could remove the if() branch in MPI_Wtime().
That could also be considered as good enough for MPI_WTIME_IS_GLOBAL.

**Comment by bosilca** [comment]
I like to have the timer relative the `MPI_Init`. Please check the above PR as a potential solution to this issue.

**Comment by adegomme** [comment]
If I read this correctly, every MPI_Wtime call before MPI_Init would now return the raw opal_clock_gettime value. I know standard says it's undefined to call this before MPI_Init, but the change might have side effects with some non compliant codes.

MPI_Wtime
MPI_Init 
MPI_Wtime

would suddenly return a big negative value, for example.

**Comment by bosilca** [comment]
Sure, users can do non-standard calls but it does not mean they have to work properly. However, the code
```
MPI_Init
t1=MPI_Wtime
```
will now return in `t1` the duration of the `MPI_Init` call. Potentially useful but not required by the standard.

**Comment by jsquyres** [comment]
@adegomme Does your code call `MPI_Wtime` before `MPI_Init`?

**Comment by adegomme** [comment]
no, I'm just thinking of potential annoying side effects of the fix on other codes.

**Comment by jsquyres** [comment]
> no, I'm just thinking of potential annoying side effects of the fix on other codes. On my side both proposals would work.

Fair enough; thanks for asking the question.

We generally don't go out of our way to accommodate apps that don't adhere to the MPI spec.  So I think we'll be ok making this change (i.e., that you have to initialize MPI before calling MPI_Wtime).

**Comment by ggouaillardet** [comment]
A simple way to accommodate those apps that do not adhere to the MPI standard could be to do the initialization in the `libmpi.so` library constructor. Then have`MPI_Init()`, only initializes if it has not been previously done (e.g. static library).
I am not convinced this is something desirable though.

**Comment by jsquyres** [comment]
@ggouaillardet Agreed; that's possible.  I think that might get a little confusing, though -- that it some cases, Wtime works before Init (when linked against libmpi.so) but in other cases, it does not (when linked against libmpi.a).

That being said, I just checked with MPICH: they don't allow using Wtime before Init.  My $0.02 is that this means that we don't need to care about this case.
