### ISSUE TITLE
Simplify and enhance performance of opal_hwloc_base_get_npus() used by orte's rmaps

### ISSUE THREAD

**Issue by timattox** [open-mpi/ompi#1298]
The opal_hwloc_base_get_npus() function needs to count the number of bits turned on in a cpuset.
This patch replaces a linear bit counting loop with a call to an already existing efficient population count routine: hwloc_bitmap_weight()
which effectively counts the bits a word at a time.
I did not test the performance gain, but as per-node core counts keep going up, this can't hurt.
See pull request https://github.com/open-mpi/ompi/pull/1297

**Comment by rhc54** [comment]
Fixed with commit of #1297
