### ISSUE TITLE
ORTE/OOB/UD set CQE size without querying the MAX supported size

### ISSUE THREAD

**Issue by shamisp** [open-mpi/ompi#1301]
https://github.com/open-mpi/ompi/blob/master/orte/mca/oob/ud/oob_ud_qp.c#L53

You can't use static values since it may not work on a certain platforms. You have to query the size first and then use it.

(Link to the original report: https://github.com/openucx/ucx/issues/551#issuecomment-171326250)

**Comment by jsquyres** [comment]
Per 16 Jan 2016 teleconf, @jladd-mlnx will assign this to someone in Mellanox.

**Comment by jladd-mlnx** [comment]
@artpol84 could you, please, address this.

**Comment by jladd-mlnx** [comment]
Assigning this to @igor-ivanov instead. Igor, please address this ASAP.

**Comment by jladd-mlnx** [comment]
Fixed via https://github.com/open-mpi/ompi/issues/1301
