### ISSUE TITLE
ompi_datatype_get_pack_description not thread safe

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#1317]
Opened a PR to fix. See #1316.

**Comment by jsquyres** [comment]
#1316 was merged to master.

@hjelmn Does this need to be PRed to v2.x?

**Comment by hjelmn** [comment]
You just merged it. open-mpi/ompi-release#909

**Comment by jsquyres** [comment]
My mistake -- this has been merged to v2.x already.

Pro tip: put "closes open-mpi/ompi#1317" in the commit message to auto-close this issue when the PR is merged.  :smile:
