### ISSUE TITLE
Improve Support for C/R in Torque Environments

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#132]
The BLCR team has done some great work integrating !Torque/Open MPI/BLCR. They posted to the devel mailing list their code which includes a list of problem areas with Open MPI.
   http://www.open-mpi.org/community/lists/devel/2011/07/9562.php

The tarball from that email is attached to this ticket. We should look into addressing this problem areas to improve the integration of these system services.

**Comment by rhc54** [comment]
We no longer support c/r
