### ISSUE TITLE
Can't compile Fortran application with -std=f2008 using mpi_f08 module

### ISSUE THREAD

**Issue by paulromano** [open-mpi/ompi#1323]
I have a Fortran application that uses MPI (via mpi_f08) and is normally compiled with `gfortran -std=f2008`. When trying to compile against OpenMPI 1.10.2, I get the following build errors:
```
/home/romano/openmc/src/message_passing.F90:5:6:

   use mpi_f08
      1
Error: GNU Extension: LOGICAL dummy argument ‘flag’ at (1) with non-C_Bool kind in BIND(C) procedure ‘mpi_comm_copy_attr_function’
/home/romano/openmc/src/message_passing.F90:5:6:

   use mpi_f08
      1
Error: GNU Extension: LOGICAL dummy argument ‘flag’ at (1) with non-C_Bool kind in BIND(C) procedure ‘mpi_type_copy_attr_function’
/home/romano/openmc/src/message_passing.F90:5:6:

   use mpi_f08
      1
Error: GNU Extension: LOGICAL dummy argument ‘flag’ at (1) with non-C_Bool kind in BIND(C) procedure ‘mpi_win_copy_attr_function’
/home/romano/openmc/src/message_passing.F90:5:6:

   use mpi_f08
      1
Error: GNU Extension: LOGICAL dummy argument ‘flag’ at (1) with non-C_Bool kind in BIND(C) procedure ‘mpi_comm_copy_attr_function’
/home/romano/openmc/src/message_passing.F90:5:6:

   use mpi_f08
      1
Error: GNU Extension: LOGICAL dummy argument ‘flag’ at (1) with non-C_Bool kind in BIND(C) procedure ‘mpi_type_copy_attr_function’
/home/romano/openmc/src/message_passing.F90:5:6:

   use mpi_f08
      1
Error: GNU Extension: LOGICAL dummy argument ‘flag’ at (1) with non-C_Bool kind in BIND(C) procedure ‘mpi_win_copy_attr_function’
/home/romano/openmc/src/message_passing.F90:5:6:

   use mpi_f08
      1
Error: GNU Extension: LOGICAL dummy argument ‘flag’ at (1) with non-C_Bool kind in BIND(C) procedure ‘mpi_comm_dup_fn’
/home/romano/openmc/src/message_passing.F90:5:6:

   use mpi_f08
      1
Error: GNU Extension: LOGICAL dummy argument ‘flag’ at (1) with non-C_Bool kind in BIND(C) procedure ‘mpi_comm_null_copy_fn’
/home/romano/openmc/src/message_passing.F90:5:6:

   use mpi_f08
      1
Error: GNU Extension: LOGICAL dummy argument ‘flag’ at (1) with non-C_Bool kind in BIND(C) procedure ‘mpi_type_dup_fn’
/home/romano/openmc/src/message_passing.F90:5:6:

   use mpi_f08
      1
Error: GNU Extension: LOGICAL dummy argument ‘flag’ at (1) with non-C_Bool kind in BIND(C) procedure ‘mpi_type_null_copy_fn’
/home/romano/openmc/src/message_passing.F90:5:6:

   use mpi_f08
      1
Error: GNU Extension: LOGICAL dummy argument ‘flag’ at (1) with non-C_Bool kind in BIND(C) procedure ‘mpi_win_dup_fn’
/home/romano/openmc/src/message_passing.F90:5:6:

   use mpi_f08
      1
Error: GNU Extension: LOGICAL dummy argument ‘flag’ at (1) with non-C_Bool kind in BIND(C) procedure ‘mpi_win_null_copy_fn’
```

I should note that the errors still persist with -std=f2008ts as well. I'm on Ubuntu 15.10 with gfortran 5.2.1 which I used to build OpenMPI from source. Not sure if there is a solution for this given the problems with logicals and C interoperability...

**Comment by ggouaillardet** [comment]
@paulromano thanks for the report
so gfortran 5.2.1 is more strict than previous versions when compiling with ```-std=f2008```

at first glance, there is no __need__ for C/Fortran interoperability here (though it is simple and convenient). i ll try to find a solution for that.

**Comment by jsquyres** [comment]
@ggouaillardet Looks like this is the fault of https://github.com/open-mpi/ompi-release/pull/851 -- that PR introduced some BIND(C)'s to subroutines with LOGICAL parameters, which is not allowed.

**Comment by jsquyres** [comment]
PR to fix this issue: #1327

**Comment by jsquyres** [comment]
@paulromano Just curious: is there a reason you have to use the `-std=f2008ts` flag?

**Comment by paulromano** [comment]
@jsquyres No reason that I *have* to, per se. It's just part of the [style guide](http://openmc.readthedocs.org/en/latest/devguide/styleguide.html#fortran) for my code that any new additions should be F2008 compliant. When I get a pull request from someone with a change to the code, having -std=f2008 gives added assurance that no compiler-specific extensions have been used.

**Comment by jsquyres** [comment]
@paulromano I realized I never ACKed your response -- oops!  Ok, thanks for the info.  I don't think Github sends mails for the related PRs and issues opened on this ticket, but we've split the solution into 2 parts: 1) fix the accidental LOGICAL pollution of BIND(C) stuff, and 2) re-implement the MPI default attribute handling callbacks in the referenced Github PRs.

**Comment by paulromano** [comment]
@jsquyres @ggouaillardet Thanks for the quick action on this issue; look forward to the next version!
