### ISSUE TITLE
osc/rdma segmentation fault when using IB atomics (c_post_start)

### ISSUE THREAD

**Issue by sjeaugey** [open-mpi/ompi#1329]
The MTT test ibm/onesided/c_post_start still fails with segmentation fault when using new IB atomics.

Setting btl_openib_flags to 12599 makes the bug disappear.

The core I get is corrupted so I don't have a stack trace yet - will post it as soon as I get it.

**Comment by sjeaugey** [comment]
Here is the stack trace (sorry no line number). The crash happens with only 2 ranks on rank 1.

#0  0x00007f439a74f5d0 in ?? ()
#1  <signal handler called>
#2  0x00007f4399d36386 in ompi_osc_rdma_complete_atomic () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-1/installs/DIFa/install/lib/openmpi/mca_osc_rdma.so
#3  0x00007f43a2f86fe6 in PMPI_Win_complete () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-1/installs/ompi-master--gcc_master--dev-3397-g70787d1/install/lib/libmpi.so.0
#4  0x0000000000401089 in main ()

**Comment by jsquyres** [comment]
**EDIT:** Added triple-single-ticks to the verbatim section to make it easier to read.

**Comment by sjeaugey** [comment]
Thanks Jeff.

Nathan, the crash does not always happen on rank 1, sometimes it is on rank 0 also.

**Comment by hjelmn** [comment]
My MTT was out of date on our clusters. Updated and now I see this issue. Will fix now.

**Comment by hjelmn** [comment]
Simple enough. There was a typo in the osc/rdma MPI_Win_start implementation. Fixed in the referencing PR.
