### ISSUE TITLE
win_dup_fn test causes gfortran failures

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1332]
@ggouaillardet The new win_dup_fn fortran tests cause failures on old compilers.  For example: http://mtt.open-mpi.org/index.php?do_redir=2265.  I'm not sure what the exact issue is; perhaps that older gfortran doesn't like `POINTER`...?

Can you please update the test to avoid this issue?

**Comment by ggouaillardet** [comment]
ok, will do

**Comment by jsquyres** [comment]
Fixed!
