### ISSUE TITLE
@ in opal.pc pkg-config file

### ISSUE THREAD

**Issue by marksantcroos** [open-mpi/ompi#1343]
The `@{libdir}` that is used "internally" by OpenMPI also ends up in the pkg-config file. There is some conversion code in `opal_setup_wrappers.m4`, but shouldnt that be used before it ends up in the .pc file?

An innocent external consumer of the pkg-config information (like myself) now falls over the unsupported `@`.

**Comment by ggouaillardet** [comment]
@marksantcroos i cannot see any ```@``` in my ```.pc``` files.
which ompi version are you using and what is your ```configure``` command line ?

**Comment by marksantcroos** [comment]
This is with ~HEAD. I encounter it on multiple systems, but not all of them.
Both for dynamic and static builds, and all configured basically like:
```
../configure --enable-orterun-prefix-by-default --prefix=$PREFIX --with-devel-headers --enable-debug
```

**Comment by ggouaillardet** [comment]
You meant latest master, right ?
Can you please give the details of a system on which .pc are broken ?
(Distro and compiler version ?)

**Comment by marksantcroos** [comment]
Yes, latest master, but it isn't a recent thing.

E.g. Comet @ SDSC:
- CentOS release 6.6
- gcc version 4.9.2
- pkg-config version 0.23
- automake (GNU automake) 1.13.3
- autoconf (GNU Autoconf) 2.69
- m4 (GNU M4) 1.4.16

**Comment by jsquyres** [comment]
@marksantcroos Can you show exactly what you're seeing?

When I install from the git master, this is the ompi.pc file that I see:

```
# Copyright (c) 2010 Cisco Systems, Inc.  All rights reserved.
#
Name: Open MPI
Description: Portable high-performance MPI implementation
Version: 3.0.0a1
URL: http://www.open-mpi.org/
#
prefix=/home/jsquyres/bogus
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib
#
# Note that -lopen-pal and all the EXTRA_LIBS are only necessary when
# static linking (they're pulled in by libopen-rte.so's implicit
# dependencies), so only list these in Libs.private.
#
Libs: -L${libdir}     -Wl,-rpath -Wl,${libdir} -Wl,--enable-new-dtags -lmpi
Libs.private: -lm -lnuma -lpciaccess -ldl -lutil -lrt 
#
Cflags: -I${includedir}     -pthread 
```

And if I use it:

```sh
$ PKG_CONFIG_PATH=$bogus/lib/pkgconfig pkg-config ompi --libs
-L/home/jsquyres/bogus/lib -Wl,-rpath -Wl,/home/jsquyres/bogus/lib -Wl,--enable-new-dtags -lmpi 
```

which looks ok to me.

The other .pc files in the $libdir/pkgconfig dir look similar.

**Comment by marksantcroos** [comment]
```
Libs: -L${libdir}     -Wl,-rpath -Wl,@{libdir} -Wl,--enable-new-dtags -lopen-pal
```
Note that I only see it in the opal.pc, not in the orte.pc.

**Comment by jsquyres** [comment]
Got it.  Easy typo to fix; thanks!

**Comment by marksantcroos** [comment]
Thanks!
