### ISSUE TITLE
Misleading openib Warning message for default subnet GID

### ISSUE THREAD

**Issue by matcabral** [open-mpi/ompi#1352]
While testing on a node with 4 HFI (Intel OmniPath devices) using openib btl we saw that a Warning message is shown when the default subent GID is used to warn the user of possible miss behaviors. This is described in detail here: https://www.open-mpi.org/faq/?category=openfabrics#ofa-default-subnet-gid

However, found that the text does not represent what the code is actually testing/finding. The text says that two ports have the default subnet GID. When, instead the code is testing if there is at least one "openib btl" available and the CURRENT subnet ID is the default one and the warning message is not masked, then print the Warning. See:   
"ompi/mca/btl/openib/btl_openib_component.c" line 750 in ompi-release branch v1.10: 

```c
    if(mca_btl_openib_component.ib_num_btls > 0 &&
            IB_DEFAULT_GID_PREFIX == subnet_id &&
            mca_btl_openib_component.warn_default_gid_prefix) {
        opal_show_help("help-mpi-btl-openib.txt", "default subnet prefix",
                true, ompi_process_info.nodename);
    }
```

In my setup, as I mentioned, I have 4 ports and only hfi1_1 with the default subnet GID. Each time that port is "evaluated" the warning message is shown. Playing with  "- x OMPI_MCA_btl_openib_if_include=hfi1_x,hfi1_y "  (being x and y numbers different than 1 and smaller than 4) the warning message is not shown. 
Therefore, there are two ways to fix this: 
   a) update the error message (and the FAQ) entry describing the behavior. 
   b) update the code to compare all subnet GIDs.

**Comment by jsquyres** [comment]
@matcabral Pro Github tip: if you do the following, it'll syntax highlight the C code block in your github markdown:
1. Put a line with three single ticks and a "c" before the code block (which tells the syntax highlighter how to highlight the code block -- as C code)
1. Put a line with three single ticks after the code block

I edited your original comment to put the single ticks in there.

**Comment by jsquyres** [comment]
@rhc54 Shouldn't this be assigned to Steve Wise?  I thought Chelsio volunteered to do the upkeep for the openib BTL.

**Comment by rhc54** [comment]
@jsquyres Steve hasn't been able to do so for some time now - it has mostly been a combination of @hjelmn @artpol84 and @ggouaillardet

**Comment by matcabral** [comment]
@jsquyres thanks, look nicer with colors :)

**Comment by ggouaillardet** [comment]
I can have a look at it
for the time bring, you can
```mpirun --mca btl_openib_warn_default_gid_prefix 0 ...```
in order not to display this warning.

**Comment by ggouaillardet** [comment]
@matcabral i made #1362 to fix that.
could you please give it a try ?
/* i have no such hardware to test that */

if you are using the v1.10 series, the patch is available at https://github.com/ggouaillardet/ompi-release/commit/66b5f8f4d93712ccb03d1578d73f27818720e320.patch

**Comment by matcabral** [comment]
Tested the patch and confirmed it works as expected. (OMPI 1.10.2)
