### ISSUE TITLE
Failure calling MPI_Type_set_attr(datatype, keyval, NULL)

### ISSUE THREAD

**Issue by bosilca** [open-mpi/ompi#1359]
Despite working for communicators and windows, setting a NULL attribute value in datatypes fails with MPI_ERR_ARG.

**Comment by jsquyres** [comment]
@bosilca I think you need to say "Fixes #xxx" in the commit message to auto-close github issues (vs. "Provides a fix for #xxx".

Also, thanks to @dalcinl for reporting the issue.
