### ISSUE TITLE
halo_1sided_put_alloc_mem_usempi race condition on IB

### ISSUE THREAD

**Issue by sjeaugey** [open-mpi/ompi#1366]
From MTT tests, running halo_1sided_put_alloc_mem_usempi between two nodes produces errors :

```
 message size   transfertime    duplex bandwidth per process and neigbor
            5 : j=            1  i=            0  -->  snd_buf_right( 
            1            1            4 )=    1000047.        1000047.     
    1000048.      in left process
            5 :     is not identical to rcv_buf_left(            1            1
             4 )=    1010047.        1010047.        1010048.    Warning: ieee_inexact is signaling
FORTRAN STOP--------------------------------------------------------------------------
mpirun has exited due to process rank 5 with PID 0 on
node drossetti-ivy5 exiting improperly.
```

It doesn't seem to fail intra-node.

It is actually not related to IB, since it also fails with TCP.

Note : this failure is not new, just showed up because some "stop" were added to MTT tests in case of errors.

**Comment by hjelmn** [comment]
Ah, this test. I added a barrier to osc/pt2pt that should have fixed this with tcp. Can you retest with the latest master and -mca osc pt2pt,sm?

**Comment by sjeaugey** [comment]
Oh, I didn't see you asked me to test again master -- and I failed to mention explicitely that it works on v2.x and on master.

So, this is a v1.10 problem only. I'm not saying we should fix this, we will just continue seeing 2 errors in MTT in v1.10. Or maybe there is a way to acknowledge that error and not report it in MTT.

**Comment by hjelmn** [comment]
Ah, hmmm. Guess I will go ahead and fix this for 1.10.3. No reason no to.

**Comment by sjeaugey** [comment]
If you know how to fix it and you don't need to bring the whole new code into v1.10, then yes, there is no reason not to do it.

I was just afraid that could be a big change and it was not a regression in the first place, just an error that started to show up because we fixed the test.

**Comment by hjelmn** [comment]
Nah. Its just the barrier in MPI_Win_fence that helps this. I don't like it but I see why it might be needed for this test.

**Comment by rhc54** [comment]
@hjelmn Has this now been fixed?

**Comment by hjelmn** [comment]
Yup. Fixed

**Comment by rhc54** [comment]
@hjelmn So can this be closed? If so, please do so.

**Comment by jsquyres** [comment]
I'm going to assume this can be closed.
