### ISSUE TITLE
MCA parameter file parsing of env vars is broken

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#1375]
Specifying environment variables using the:

-x FOO=bar

syntax in MCA files is currently broken in master and v2.x. Specifying a line like above can lead to memory corruption, incorrect behavior, or just cause mpirun to abort.

I have opened #1374 to fix the issue on master but it will also need to be fixed on 2.x.

**Comment by rhc54** [comment]
As noted, has been fixed but won't be backported.
