### ISSUE TITLE
Fix usage of AC_CACHE_CHECK([number of arguments to ibv_create_cq])

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#138]
As reported by Paul H. Hargrove" PHHargrove@lbl.gov:

> From: "Paul H. Hargrove" PHHargrove@lbl.gov
> Date: February 14, 2012 7:23:43 PM EST
> To: Open MPI Developers devel@open-mpi.org
> Subject: [OMPI devel] the dangers of configure probing argument counts
> Reply-To: Open MPI Developers devel@open-mpi.org
> 
> There was recently a fair amount of work done in hwloc to get configure to work correctly for a probe that was intended to determine how many arguments appear in a specific function prototype.  The "issue" was that the C spec doesn't require that the C compiler issue an error for either too-many or too-few arguments.  While gcc and most other compilers make both cases an error, there are two compilers of non-trivial importance which do NOT:
> -  By default the IBM (xlc) C compiler warns for the case of too many argument.
> -  By default the Intel (icc) C compiler warns for the case of too few arguments.
> 
> This renders configure-time tests that want to check argument counts unreliable unless one takes special care to add something "special" to CFLAGS.  While hacking on hwloc we determined that is was NOT safe for configure to add to CFLAGS in general, nor to ask the user to do so.  It was only safe to /temporarily/ add to CFLAGS for the duration of the argument count probe.
> 
> So, WHY am I tell you all this?
> Because of the following in openmpi-1.7a1r25865/ompi/config/ompi_check_openib.m4:
> 
> > ```
> >      [AC_CACHE_CHECK(
> >          [number of arguments to ibv_create_cq],
> > ```
> > 
> > which performs exactly the sort of test I am warning against.
> 
> So, I would encourage somebody to make the effort to reuse the configure logic Jeff and I developed for hwloc.
> In particular look for setting and use of HWLOC_STRICT_ARGS_CFLAGS in config/hwloc.m4
> 
> -Paul

**Comment by jsquyres** [comment]
This issue is now moot -- the configury in question no longer exists (and we do not have any specific checks for `ibv_create_cq` any more).
