### ISSUE TITLE
ompi_info -a should show all built components

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#1396]
ompi_info -a should show all components regardless of whether or not they have parameters.  This provides users a relatively easy way to determine whether or not a given component is available for the Open MPI they are trying to use.

**Comment by kmroz** [comment]
Hopefully taken care of by https://github.com/open-mpi/ompi/issues/1515.

**Comment by jsquyres** [comment]
Looks like this was fixed in #1515.
