### ISSUE TITLE
Add public symbol verification list

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1405]
Per discussion in the Dallas Feb 2016 meeting, add some "nm" types of tests (during `make check`?) to make sure that we're only exporting the symbols that we mean to export.  We really only want to export the MPI API, and possibly a few other symbols -- i.e., we'll likely need some kind of whitelist.

@gpaulsen said that they do this kind of stuff in Platform MPI and would be willing to contribute this kind of functionality.

**Comment by jsquyres** [comment]
Per F2F Jan 2017 discussion, @hppritcha and @jsquyres are ok if this comes in v2.1.x, even if x>0.

**Comment by gpaulsen** [comment]
Created internal IBM work item 140614 to track and prioritize.

**Comment by jsquyres** [comment]
@gpaulsen Looks like this will miss v2.1.0.  Do you want to re-milestone it to v2.1.1, or v3.0.0?

**Comment by gpaulsen** [comment]
Lets just close it and when it comes in, it'll be happy days.  The test case we have really is just running 'nm' on the library and then using some grep patterns, to ensure we don't accidentally export non-MPI symbols.
