### ISSUE TITLE
Fix TCP BTL THREAD_MULTIPLE deadlock

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1406]
Discussed at Feb 2016 Dallas meeting.  @bosilca says he knows what the problem is and will fix it.

**Comment by jsquyres** [comment]
@hjelmn @bosilca Did this get fixed yet, perchance?

**Comment by jsquyres** [comment]
@bosilca Says that he has large modifications to the TCP BTL (it's a giant change).  Not clear yet on how we want to handle this...

**Comment by hppritcha** [comment]
@bosilca is there a chance we can have a narrowly focused fix to the existing TCP BTL?

**Comment by jsquyres** [comment]
@bosilca If we can't get a focused fix, how about this:

* Have the old TCP BTL code selected on non-THREAD_MULTIPLE
* Have your new TCP BTL code selected on THREAD_MULTIPLE

This would allow us to have somewhat newer/less-tested code in the THREAD_MULTIPLE path (and therefore make solid advances in the THREAD_MULTIPLE category, modulo bug fixes), but have solid/reliable/time-tested code in the non-THREAD_MULTIPLE case (i.e., the majority of the world).

As the new code gets more testing and we get higher confidence in it, we can remove this division / remove the old code, and just have the new code.

What do you think?

**Comment by jsquyres** [comment]
@bosilca Any comment?

**Comment by bosilca** [comment]
#1491

**Comment by jsquyres** [comment]
Fixed via #1491.
