### ISSUE TITLE
Fix vader MPI_THREAD_MULTIPLE deadlock.

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1408]
Discussed at Feb 2016 Dallas meeting.  @bosilca says he runs into it periodically; he will get with @hjelmn and help identify where the problem is.

**Comment by jsquyres** [comment]
@bosilca Can you share this test?  I'd like to add it to the Cisco MTT runs.

**Comment by bosilca** [comment]
It is a modified version of the osu_mbw_mr benchmark. The only real difference is that we are initializing the MPI library in MPI_THREAD_MULTIPLE mode.
