### ISSUE TITLE
Cannot bind to individual PU's (hyperthreads) on Power7 platforms

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#141]
hwloc on Power7 platforms views only sockets and PU's, but not cores.  And actually it is confused about the true topology in that what it views as sockets are really cores.  The issue is in the linux kernel for Power7 and not really hwloc's problem.  But, we still need a way to bind at the logical CPU level (PU's) and at the core/socket level.

**Comment by rhc54** [comment]
Yes we can
