### ISSUE TITLE
Portals4 OSC multiple lock/unlock support

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#142]
The Portals4 OSC component currently doesn't support a rank locking more than one rank simultaneously (which is allowed in MPI-3).

**Comment by jsquyres** [comment]
@regrant @tkordenbrock Is this issue still relevant?  Will it be fixed for v2.0.0?  Or sometime in the 2.x series?  Please update the milestone as appropriate, or close this issue.  Thanks!

**Comment by jsquyres** [comment]
@regrant @tkordenbrock Is this issue still relevant?

**Comment by tkordenbrock** [comment]
@jsquyres Yes, it is still relevant but there are higher priority bugs and enhancements for v2.0.0.  I have changed the milestone to v2.x.

**Comment by hppritcha** [comment]
@tkordenbrock can this anciet issue be closed?

**Comment by tkordenbrock** [comment]
Yes, this was fixed ages ago.  Closing.
