### ISSUE TITLE
Portals4 OSC long/non-contiguous operation support

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#143]
The Portals4 OSC component does not support operations which must be broken up into smaller communication operations.  This includes non-contiguous operations and operations whose lengths are greater than the waw/war ordered sizes.

**Comment by hppritcha** [comment]
can this be closed?
@regrant

**Comment by jsquyres** [comment]
@regrant @tkordenbrock Is this issue still relevant?  Will it be fixed for v2.0.0?  Or sometime in the 2.x series?  Please update the milestone as appropriate, or close this issue.  Thanks!

**Comment by jsquyres** [comment]
@regrant @tkordenbrock Is this issue still relevant?

**Comment by tkordenbrock** [comment]
@jsquyres Yes, it is still relevant but there are higher priority bugs and enhancements for v2.0.0.  I have changed the milestone to v2.x.

**Comment by hppritcha** [comment]
@tkordenbrock where are we with this issue?

**Comment by tkordenbrock** [comment]
This code is nearly complete.  I will be pushing a PR this week.

**Comment by regrant** [comment]
This has been fixed by PRs #2999 and #2986
