### ISSUE TITLE
Giving btl_tcp_if_include of an interface that does not exist results in SEGV

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1435]
Reported on master -- didn't try 2.x.

**Comment by kmroz** [comment]
Tried reproducing this on latest ompi/master and ompi-release/v2.x. Both show no such problem:

    % mpirun --mca btl_tcp_if_include foo -np 2 ./hello_c
    MPI_INIT: argc 1
    MPI_INIT: argc 1
    [elm][[3219,1],1][btl_tcp_component.c:706:mca_btl_tcp_component_create_instances] invalid     
    interface "foo"
    [elm][[3219,1],0][btl_tcp_component.c:706:mca_btl_tcp_component_create_instances] invalid  
    interface "foo"
    Hello, world, I am 0 of 2, (Open MPI v3.0.0a1, package: Open MPI kilo@elm Distribution, ident:   
    3.0.0a1, repo rev: dev-3764-g9efd7f1, Unreleased developer copy, 131)
    Hello, world, I am 1 of 2, (Open MPI v3.0.0a1, package: Open MPI kilo@elm Distribution, ident: 
    3.0.0a1, repo rev: dev-3764-g9efd7f1, Unreleased developer copy, 131)
    MPI_FINALIZE[1]
    MPI_FINALIZE[0]

The check responsible for this looks sane:

    btl_tcp_component.c:static int mca_btl_tcp_component_create_instances(void)
        [...]
        /* if the user specified an interface list - use these exclusively */
        argv = include = split_and_resolve(&mca_btl_tcp_component.tcp_if_include,
                                       "include", true);
        [...]
            char* if_name = *argv;
            int if_index = opal_ifnametokindex(if_name);
            if(if_index < 0) {
                BTL_ERROR(("invalid interface \"%s\"", if_name));
                ret = OPAL_ERR_NOT_FOUND;
                goto cleanup;
            }
        [...]

And I certainly don't have an interface on my system called "foo" :smile:

**Comment by kmroz** [comment]
I also dropped a small debug into opal/mca/btl/base/btl_base_select.c:mca_btl_base_select() as I was not 100% sure if hello_c.c would be enough to properly test TCP BTL instantiation (and I couldn't figure out how to make the opal_output_verbose() happen :smile:).

I can confirm that we hit the below condition:

    mca_btl_base_select():
    ....
         OPAL_LIST_FOREACH_SAFE(...)
         ....
             modules = component->btl_init(&num_btls, enable_progress_threads,
                                          enable_mpi_threads);
         ....
             if (NULL == modules) {
                printf("KM: component->btl_version.mca_component_name: %s\n",
                        component->btl_version.mca_component_name);
                opal_output_verbose(10, opal_btl_base_framework.framework_output,
                                    "select: init of component %s returned failure",
                                    component->btl_version.mca_component_name);
         ....
    ....

So the failure happens _gracefully_.

**Comment by kmroz** [comment]
@jsquyres - Have you been able to reproduce this on your end at all since your last update?

**Comment by jsquyres** [comment]
Agreed -- this is no longer an issue on master.  Also tested v2.x -- not happening there, either.  Yay!
