### ISSUE TITLE
mpicc link shouldn't add -ldl and -lhwloc

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#145]
See https://bugzilla.redhat.com/show_bug.cgi?id=814798

```
$ mpicc -showme:link
-pthread -m64 -L/usr/lib64/openmpi/lib -lmpi -ldl -lhwloc
```

-ldl and -lhwloc should not be listed.  The user should only link against libraries that they are using directly, namely -lmpi, and they should explicitly add -ldl and -lhwloc if their code directly uses those libraries. There does not appear to be any references to libdl or libhwloc symbols in the openmpi headers which is the other place it could come in.

configure appears to add them to opal_WRAPPER_EXTRA_LIBS which then makes its way into this list.

We are now stripping these out of the link settings for the Fedora packages.

**Comment by rhc54** [comment]
Fixed long, long ago
