### ISSUE TITLE
Move configure summary commits to v2.x branch

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1450]
For v2.1.0 (or beyond), make a PR to move the following commits to the v2.x branch:
- d2f5fca: configure: add a summary section at the end of configure output (generates several conflicts)
- 48c650c47a24: configury: minor updates to config summary output
- https://github.com/open-mpi/ompi/commit/7bd12dc1a4238b598cb2f7118cd07ef5d0aa019c: config: Fix wrong variable name

@hjelmn

**Comment by hjelmn** [comment]
one more: a93b849f13b12a7b1c1cdde71a9e491ddc220e17

**Comment by hjelmn** [comment]
also: 7bd12dc1a4238b598cb2f7118cd07ef5d0aa019c

**Comment by jsquyres** [comment]
This is already done.
