### ISSUE TITLE
OMPI v1.6 running out of registered memory

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#148]
Over the past week or two, I've had users report -- both on and off list -- that OMPI 1.6.x is running out of openib registered memory where OMPI 1.4.x is not.

LANL reported on-list here: http://www.open-mpi.org/community/lists/users/2012/06/19489.php

U. Michigan also reported this to me in an off-list email.  

It's been reported to me that newer Mellanox HCA hardware defaults to only allowing a small amount of registered memory and that value needs to be tuned up (per http://www.ibm.com/developerworks/wikis/display/hpccentral/Using+RDMA+with+pagepool+larger+than+8GB).

But still, the issue is that OMPI worked with 1.4.x but not with 1.6.x.  What changed?

How do we make OMPI 1.6 work out of the box?

**Comment by rhc54** [comment]
Per Mellanox, this can be closed. Any further work will be done on a separate new ticket.
