### ISSUE TITLE
Build fail on CentOS 5.11: Absoft (ASM symbols missing)

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1487]
MTT link from last night showing the problem: https://mtt.open-mpi.org/index.php?do_redir=2279

```
../../../opal/.libs/libopen-pal.so: undefined reference to `__sync_sub_and_fetch_4'
./../../opal/.libs/libopen-pal.so: undefined reference to `__sync_bool_compare_and_swap_4'
libopen-pal.so: undefined reference to `__sync_add_and_fetch_4'
: undefined reference to `__sync_add_and_fetch_8'
```

@hjelmn Can you have a look?

**Comment by hjelmn** [comment]
Thats weird. I don't have an absoft compiler. They only make a fortran compiler, correct?

**Comment by hjelmn** [comment]
gcc 4.1.2 is the c compiler. It should have the sync builtin atomics (configure found them).

**Comment by jsquyres** [comment]
Correct: Absoft makes a Fortran compiler.  But to test Open MPI with their Fortran compiler, they have to test with whatever C compiler is on the system, too.  In this case, it's not their Fortran compiler that's causing the problem -- it's something else, because the error occurs when trying to link `opal_wrapper`.

**Comment by jsquyres** [comment]
@cagoelz sent us some output from that failed MTT run:

* [absoft-config.log.txt](https://github.com/open-mpi/ompi/files/186186/absoft-config.log.txt)
* [absoft-make-V=1.log.txt](https://github.com/open-mpi/ompi/files/186188/absoft-make-V.1.log.txt)

**Comment by bosilca** [comment]
From the [gcc](https://gcc.gnu.org/onlinedocs/gcc-4.1.2/gcc/Atomic-Builtins.html) documentation of 

> Not all operations are supported by all target processors. If a particular operation cannot be implemented on the target processor, a warning will be generated and a call an external function will be generated. The external function will carry the same name as the builtin, with an additional suffix `_n' where n is the size of the data type.

Based on this documentation, the error message above, aka. missing __sync_add_and_fetch_4, suggests that the compiler does not have intrinsic support for these atomics operations and relies on external functions. Our configure reached a different conclusion because of a bug.

Here is what I gather from the log file:

1. Looking for __sync:
configure:31100: gcc -std=gnu99 -c -g -pipe -Wall -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -pedantic -Werror-implicit-function-declaration -finline-functions -fno-strict-aliasing  conftest.c >&5

2. Looking for __sync 128:
gcc -std=gnu99 -o conftest -g -pipe -Wall -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -pedantic -Werror-implicit-function-declaration -finline-functions -fno-strict-aliasing   conftest.c  >&5

We look for the __sync primitive by simply compiling the .c configure file into a .o, while we generate an executable when we look for the 128 bits __sync primitives. We should generate the executable for both and then our configure will correctly detect that the available gcc does not have support for __sync intrinsics.

**Comment by hjelmn** [comment]
That makes sense. Just change them to a AC_LINK_IFELSE.

**Comment by jsquyres** [comment]
@hjelmn This is still happening: https://mtt.open-mpi.org/index.php?do_redir=2281

**Comment by jsquyres** [comment]
@hjelmn Unfortunately, this did not fix the issue -- it happened again in MTT last night: https://mtt.open-mpi.org/index.php?do_redir=2284

I note that the platform on which Absoft is building is ia32.  Does that have something to do with this error?

@cagoelz Could you send us (or attach to this issue) the `config.log` and `opal/include/opal_config.h` file from the MTT build cited above?

**Comment by cagoelz** [comment]
Files attached. 
[config.log.txt](https://github.com/open-mpi/ompi/files/195487/config.log.txt)
[opal_config.h.txt](https://github.com/open-mpi/ompi/files/195486/opal_config.h.txt)

**Comment by jsquyres** [comment]
@cagoelz Thanks!

@hjelmn OIC what happened -- #1508 was merged in after the snapshot tarballs were made last night (i.e., the MTT from last night didn't include the fix from #1508).

I actually kicked off a new snapshot tarball generation a little while ago because there was a compile error in the new TCP BTL changes that came in yesterday.  The change from #1508 will be included in this new snapshot.  I'll close this issue again on the assumption that the issue is fixed (I'll re-open it if necessary).

**Comment by jsquyres** [comment]
Sorry @hjelmn, your fix didn't fix this issue -- I have to re-open it again.  :-(

[Last night's MTT](https://mtt.open-mpi.org/index.php?do_redir=2285) showed the same compile/link failure.  I assume @cagoelz's attachments from yesterday are still relevant to last night's failure -- can you have a look and see what's going on?

**Comment by jsquyres** [comment]
Er... @rhc54 that was an amusing cross-repository ticket closing.  :stuck_out_tongue_winking_eye:

**Comment by rhc54** [comment]
???? how the heck did that work?

**Comment by rhc54** [comment]
WOW - that seems like a real "hole" in the system! All I did was "git pull" from OMPI, and then update the SCON repo.

**Comment by jsquyres** [comment]
@hjelmn This problem is still occurring on master.  Can you please have a look?  https://mtt.open-mpi.org/index.php?do_redir=2288

Absoft's build system is a 32-bit platform, GCC: 4.1.2, Absoft: Absoft 32-bit Pro Fortran 16, CentOS5.11.

```
$ ./configure FC=af90 FCFLAGS=-Z790 "CFLAGS=-g -pipe" --enable-picky --enable-debug --enable-mpirun-prefix-by-default
```

The error is:

```
../../../opal/.libs/libopen-pal.so: undefined reference to `__sync_sub_and_fetch_4'
./opal/.libs/libopen-pal.so: undefined reference to `__sync_bool_compare_and_swap_4'
reference to `__sync_add_and_fetch_4'
./../opal/.libs/libopen-pal.so: undefined reference to `__sync_add_and_fetch_8'
```

**Comment by hjelmn** [comment]
Need the latest config.log to track this down. Last one if from before the change that should have fixed this.

**Comment by jsquyres** [comment]
@hjelmn Tony provided the config.log in an earlier comment: https://github.com/open-mpi/ompi/issues/1487#issuecomment-203412942

**Comment by cagoelz** [comment]
Do you need the config.log from the 4/12 testing?

**Comment by hjelmn** [comment]
That log was from before the fix. Yes, I need the latest one.

**Comment by cagoelz** [comment]
Here it is. 
[config.log.txt](https://github.com/open-mpi/ompi/files/215276/config.log.txt)

**Comment by hjelmn** [comment]
I think I see the problem. The configure test is succeeding but it is just checking for __sync_synchronize(). I am improving the check to add compare-and-swap and fetch-and-add.
