### ISSUE TITLE
Re-examine openib BTL MCA param default values

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#149]
Nathan would like to re-examine the openib BTL MCA default param values.  For example:
- receive queues: go to all SRQ?
- receive queues: increase the default eager limit? (perhaps on a per-CPU-type / per HCA basis?)
- receive queues: add a queue for tiny messages (e.g., 128 bytes), to mainly be used by PML control messages? (i.e., avoid wasting an entire eager_limit sized buffer for a 68 byte PML control message)
- limit the free list size to 8K or 16K entries (does it really need to be unlimited?).  This might also help the unbalanced registration issues on #3131 and #3134.
- ...?

There's a bunch of MCA params that should probably just be hidden so that users don't have to see them.  We probably don't want to ''delete'' them, because there's probably some obscure user out there who is using them, but at least we can hide them so most users won't have to see an ompi_info a mile long with openib BTL params.

**Comment by jsquyres** [comment]
@hjelmn Did you ever do this, perchance?  Or should we close it?

**Comment by awlauria** [comment]
Openib btl is removed. Closing.
