### ISSUE TITLE
Merge new TCP BTL code to v2.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1505]
#1491 fixed some TCP BTL MPI_THREAD_MULTIPLE issues.  After letting it soak on master for a little bit, we need to PR it over to the v2.x branch.

Commits to include:

* 32277db6aba4e0a794a0c9814a23f6d2930f4170
* 92062492b9ad4ce6b362e0243c3d481d0492c632
* f69eba1bc42634d6194ceadca9f537f7c91200a9
* d0165818b393b54a2455abea5d58609f252d636d
* f70c5c495bf1dae9da8fe430205973bb46678915
* e852d85cc1b6dbaaec5417499de41bb7fc620cea
* 7eca2f96504f4bc10eae82a0559b70145a775a9c

**Comment by hppritcha** [comment]
There may be some other commits that need to be picked up.

**Comment by jsquyres** [comment]
This is now done.
