### ISSUE TITLE
aprun launched jobs hang in MPI_Finalize

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#1527]
On master aprun launched jobs now hang in `orte_rml_base_close`.  Processes are hung in the
`ORTE_WAIT_FOR_COMPLETION` macro.

**Comment by rhc54** [comment]
@hppritcha Do your apps not start an async progress thread? Or are they shutting it down early? It looks to me like apps launched by aprun shouldn't be doing anything different, but those are the only two reasons why you wouldn't get thru that wait.

**Comment by hppritcha** [comment]
No particular async thread is being started related to alps specific components.  The hang is not observed in v2.x nor when using srun/master, so in those cases something is progessing libevent to allow ```orte_rml_base_close``` to complete.

**Comment by hppritcha** [comment]
I suspect that the fact the usock oob component doesn't startup when using aprun might be the cause.

**Comment by rhc54** [comment]
I believe this has been fixed - at least, it works for me
