### ISSUE TITLE
MPI Errhandler causes segfault on receipt of signal

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#1530]
In trying to track down an apparent "hang" on the 1.10.3 branch, I discovered that the job wasn't actually hanging. Instead, the job was taking a long time to complete because nearly every proc was segfaulting and writing out a core dump - and it was taking so long to write out all those core dumps that MTT thought we had hung.

The test is Intel MPI_Errhandler_fatal1_f (a few others show the same symptom - this is just the one I was working with). Everything starts correctly, and then rank=0 calls MPI_Abort. ORTE correctly identifies the situation and issues "kill" signals to the other procs, starting with SIGCONT followed by SIGTERM, and then SIGKILL.

The output results look okay:

```shell
$ mpirun -n 16 ./MPI_Errhandler_fatal1_f
 MPITEST_INFO (         0): Starting test MPI_Errhandler_fatal     
 MPITEST_INFO (         0): This test should abort after printing the results
 MPITEST_INFO (         0): message, otherwise a f.a.i.l.u.r.e is noted
MPITEST_results: MPI_Errhandler_fatal all tests PASSED (        16)
[bend001:21445] *** An error occurred in MPI_Send
[bend001:21445] *** reported by process [139981018365953,21474836480]
[bend001:21445] *** on communicator MPI COMMUNICATOR 3 DUP FROM 0
[bend001:21445] *** MPI_ERR_RANK: invalid rank
[bend001:21445] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[bend001:21445] ***    and potentially your MPI job)
```

However, the writing out of the core files takes a long time, and the shell prompt doesn't return until that dump is completed. Thus, MTT thinks the job timed out and tries to kill it - and fails, because the mpirun is actually already dead.

I have no idea why this test is segfaulting upon receipt of a signal. Can someone please investigate?

@ggouaillardet @bosilca @hjelmn @jsquyres 

Not sure which of you might have time and knowledge to dig this one out.

**Comment by rhc54** [comment]
Should have provided this - here is the MTT complaint:

```shell
>> Command: mpirun     --hostfile /home/common/hosts -np 16 --prefix /home/common/openmpi/build/ompi-release/ src/MPI_Errhandler_fatal1_f 
   Elapsed:       00:00:10 0.00u 0.01s
*** WARNING: Test: MPI_Errhandler_fatal1_f, np=16, variant=1: TIMED OUT
    (failed)
*** Past timeout of 2 seconds by 1 seconds
*** Killing mpirun with SIGTERM
** Kill TERM (after 5 seconds) didn't work!
*** Killing mpirun with SIGINT
** Kill INT (after 5 seconds) didn't work!
*** Now I'm mad.  Killing mpirun with SIGKILL
** Kill KILL didn't work!  Sleeping and trying again...
*** Past drain timeout; quitting
```

**Comment by rhc54** [comment]
Final tidbit - when I gdb the core dump, all I can see is that the proc was sitting in a signal handler, and that the rest of the stack was corrupted.

**Comment by ggouaillardet** [comment]
@rhc54 i was able to reproduce it on one system, and the problem went away with

```
export IPATH_NO_BACKTRACE=1
```

could you please give it a try ?

```libpsm_infinipath.so``` sets its own signal handler when ```mca_mtl_psm.so``` is dlopen'ed, and it overwrites the OpenMPI signal handler.
if you built with ```--disable-dlopen``` i am not sure which signal handler is set first, nor whether this is a consistent behavior across all systems.

this issue was already discussed at https://www.open-mpi.org/community/lists/devel/2015/08/17838.php (loooong thread) and at that time, it was noticed only when using Java

**Comment by jsquyres** [comment]
When I run this, I end up in `opal/mca/pmix/pmix120/pmix/src/client/pmix_client.c` in `PMIx_Abort`.

It calls `PMIX_ACTIVATE_SEND_RECV` on line 549, and then returns.  This seems to be a race condition, because the `orted` will kill the process "right away" -- but perhaps not before the call to `PMIx_Abort` returns and unwinds the stack into areas that are not expecting a return.

Shouldn't `PMIx_Abort` guarantee to not return?

**Comment by rhc54** [comment]
@jsquyres I'm scratching my head over your comment and failing to grok it. One process calls "abort", and we correctly handle that call and it cleanly exits. The other processes (that registered errhandlers) are the ones that are segfaulting. Are you saying that those procs are also calling "abort" upon receiving a signal? If so, then that would indeed be a problem.

**Comment by jsquyres** [comment]
@rhc54 and I talked about this on the phone:

1. ORTE's abort is catching the return from PMIx_Abort() and is calling exit().  So we're good there.
1. I looped over calling `MPI_Errhandler_fatal1_f` and am unable to replicate the error.  :frowning: 

@rhc54 is going to keep investigating...

**Comment by ggouaillardet** [comment]
@rhc54 did you confirm this issue is not related to ```libpsm_infinipath.so``` that sets its signal handler when dlopen-ed and is then unmapped because there is no PSM hardware ?

**Comment by rhc54** [comment]
I don't have psm support on my system, nor are any of those components built. I can't swear that isn't the problem - maybe some other component is opening something that can cause the problem. For example, I do have libfabric installed, and the usnic btl is opening it, so perhaps this problem is creeping in that way?

**Comment by ggouaillardet** [comment]
iirc, i ran the application as a singleton under gdb, set a breakpoint in ```signal``` and ```sigaction``` in order to find who sets signal handlers.
a simpler solution would have been to call ```sigaction``` and then use ```dladdr``` after ```MPI_Init``` but i could not figure out how to get ```dladdr``` work ...

**Comment by jsquyres** [comment]
usnic doesn't set any signal handlers.

Does your libfabric had libpsm(2) support?  You should be able to run `fi_info --list` to see what providers your libfabric has.

**Comment by hiliev** [comment]
Same problem here. `libpsm_infinipath.so` is setting a signal handler for `SIGINT` while the `psm` MTL is `dlopen()`-ed and then not restoring the previous handler on `dlclose()`. Ctrl-C then results in a call right into the middle of an unmapped memory region. It took me quite some staring at the stack trace before I realised what is going on and my initial assumption was that the stack frame was somehow getting corrupted. We don't have any InfiniPath hardware on our cluster, but the library is installed anyway and the build system picks it up and builds the MTL. Our solution was to disable the `psm` MTL.

**Comment by matcabral** [comment]
@rhc54 is saying he's build does not have PSM support. Please confirm. 
If  PSM is actually in, as @ggouaillardet mentioned, using IPATH_NO_BACKTRACE=1 will disable libpsm_infinipath.so playing with sighandlers.  There was an issue related to psm hijacking sighandlers and JVM. This was fixed in PSM_VERNO    0x0110. Please look at:

https://github.com/01org/psm/commit/225bbc9ab2609868dfbc62f652f5f38f54f68485

I've been thinking on adding a sanity check on the psm mtl to warn or fail when psm version is older than 0x0110.

**Comment by rhc54** [comment]
I can confirm that I do _not_ have the PSM support built on my machine. However, I _do_ have the OFI MTL component built, and have libfabric on the machine. Thus, even though I lack the hardware and have not built the PSM MTL, I fear that the libraries may be getting opened via the libfabric provider.

If that is true, then this problem could hit everyone who installs libfabric, even if they don't have supporting hardware for it, as the OFI MTL will always build if that library is present.

**Comment by ggouaillardet** [comment]
@matcabral in the case of psm mtl, i do not think the error occurs when configure'd with --disable-dlopen, or when static libraries are built in.

**Comment by matcabral** [comment]
@rhc54 I think the key question would be to know how the libfabric that you have was built. 
@ggouaillardet I haven't looked deeper into psm code, but I the signal handler registration only happen at load time.

**Comment by ggouaillardet** [comment]
@matcabral if OpenMPI uses dynamic components, and there is no infinipath hardware, then the ```libpsm_infinipath.so``` is dlopen'ed and then dlclose'd shortly after in ```MPI_Init()```. in previous releases, that means some signal handlers use unmmap'ed (e.g. invalid) addresses, and hence the issue.

my point is that if OpenMPI was configure'd with ```--disable-dlopen```, the ```libpsm_infinipath.so``` library is loaded at init time, and is unloaded when the application exits, so there is virtually no way to use an invalid address, so there is no need for issuing a warning.
that being said, if Java is used, it might be necessary/easier to abort.

**Comment by matcabral** [comment]
@ggouaillardet (thanks for the clarification) . Regarding the warning, to make it simple, I would make the psm mtl fail when using "older unsafe version" and not invest in knowing java is around (or depending on if ```--disable-dlopen``` was used) (btw, we may be diverging from bug's title :O )

Back to main issue: hypothesis: Is it possible that libfabric was built with psm support so it is dlopening an old (unsafe) libpsm_infinipath.so and then closing it before execution? reproducing what  @ggouaillardet  is describing.

**Comment by rhc54** [comment]
I would expect that is indeed the case. I simply downloaded the libfabric (v1.1.0) rpm and installed it via "yum" on CentOS-7, and I'm sure they would have built it for the most general case.

**Comment by rhc54** [comment]
Solution lies outside of our scope, so I'm going to close this one.
