### ISSUE TITLE
Make XRC/XOOB be the default connection scheme (if available)

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#154]
In an effort to reduce the consumption of registered memory, if XRC is available (both at compile time and in the hardware at run-time), make XOOB be the default connection scheme in the openib BTL.

  '''NOTE:''' This is all predicated on the effort to reduce the use of registered memory because we may actually run out, and it's not a completely solvable problem on the v1.6 series because the async RDMA CM runs in a separate thread.  Meaning: it can request new registered memory at any time in a separate/async thread, and our mpool code is not thread safe (and won't be fixed in 1.6.x).  Hence, this is not a ''completely'' solvable problem in the v1.6 series.  So we're just doing our best to reduce the use of registered memory.

Mellanox advises waiting to do this until 1.6.2 because as of July 2012, there's some bug in the Mellanox XRC driver that XRC accidentally consumes ''more'' memory than non-XRC.  Hence, this is not a useful default change to make in OMPI until Mellanox fixes this bug.

Filing this ticket as a placeholder for the future.

**Comment by rhc54** [comment]
Closed due to staleness - we don't even have an OOB method any more
