### ISSUE TITLE
Missing help file `help-rcache-base.txt`

### ISSUE THREAD

**Issue by jjhursey** [open-mpi/ompi#1545]
I looks like there is a missing help file in the master branch:
```text
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    leave pinned failed
But I couldn't open the help file:
    /path-to-my-install/openmpi/help-rcache-base.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
```

That help file is referenced in two places:
  * [opal/mca/rcache/base/rcache_base_create.c](https://github.com/open-mpi/ompi/blob/master/opal/mca/rcache/base/rcache_base_create.c)
  * [opal/mca/rcache/base/rcache_base_mem_cb.c](https://github.com/open-mpi/ompi/blob/master/opal/mca/rcache/base/rcache_base_mem_cb.c)

I could not easily find this file in the history. @hjelmn I think you were the last one working down here, maybe you have an idea about where this file is and how to restore it?

**Comment by hjelmn** [comment]
The file was probably originally opal/mca/mpool/base/help-mpool-base.txt. I will see what happened. I probably forgot to move|copy the file.

**Comment by hjelmn** [comment]
hah. forgot to checkin the file. fixing now.
