### ISSUE TITLE
Datatype warning on master

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1547]
@bosilca I'm getting the following compilation warning on master:

```
opal_datatype_pack.c: In function 'opal_pack_general_checksum': 
opal_datatype_pack.c:567:13: warning: label 'update_loop_description' defined but not used [-Wunused-label] 
             update_loop_description:  /* update the current state */ 
             ^ 
```

It looks like the only use of the `update_loop_description` label is in some code that is `#if 0`'ed out with some kind of comment about heterogeneity.

[Can you re-examine the code?](https://github.com/open-mpi/ompi/blob/master/opal/datatype/opal_datatype_pack.c#L550-L572)  See if that `#if 0` code (and the label) should be removed, and/or if the label should be `#if 0`'ed as well.  Thanks.

**Comment by bosilca** [comment]
Fixed in d379e23
