### ISSUE TITLE
"Not enough slots" failure in dev-3885-g5892020 master tarball (2016-04-20)

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1571]
@rhc54 This is a weird one.  All of Absoft's "trivial" runs last night failed on a specific platform (Centos 5.11), complaining about not having enough slots, and worked properly on another (RHEL 6.7).  The only thing I can think that would be different between the two would be some kind of hwloc update...?  But we haven't done that in a while -- right?

* [MTT run on Centos 5.11 showing the failures](https://mtt.open-mpi.org/index.php?do_redir=2290)
* [MTT run on RHEL 6.7 showing success](https://mtt.open-mpi.org/index.php?do_redir=2291) (with the same version of master tarball)

Here's the command line and error message from the failed runs:

```sh
$ mpirun -np 4 --mca btl sm,tcp,self ./c_hello 
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 4 slots
that were requested by the application:
  ./c_hello

Either request fewer slots for your application, or make more slots available
for use.
```

@cagoelz Can you confirm that nothing changed in your Centos 5.11 platform over the last week or so?  I.e., are there actually (at least) 4 processors (as recognized by Linux) to use on that machine?

**Comment by rhc54** [comment]
We haven't updated hwloc in roughly a year, so that can't be the problem. I'd guess that somehow we aren't seeing 4 available processors on that machine.

**Comment by jsquyres** [comment]
Let's see what @cagoelz says...

**Comment by cagoelz** [comment]
Hardware has not changed and Linux reports 2 processors as it has for all the time we've been running the tests on this machine.

**Comment by rhc54** [comment]
Ah, then the error is indeed correct. Do you have a hostfile that you are using for these tests? We did change the handling of oversubscribe, and I suspect you are hitting that change

**Comment by jsquyres** [comment]
@cagoelz The easy solution might be to change the np value to 2 in your MTT ini file.

**Comment by cagoelz** [comment]
np appears to be coming from "-np &test_np() " in our ini file. I do see "hostlist = localhost:4" at the top, are they related?

**Comment by jsquyres** [comment]
Yes.  Change it to `localhost:2` and let's see if that fixes the problem.  Thank you!

**Comment by cagoelz** [comment]
I will do that.  Question, is it still useful to you guys for us to run the tests on this system given that it is 32 bit and Centos 5.11 is eol March, 31 2017?

**Comment by jsquyres** [comment]
Yes.  32 bit builds are most helpful because we have a handful of customers who use 32 bit, but none of us have 32 bit machines on which to test.  😄

**Comment by cagoelz** [comment]
We will continue testing on that system then, I have updated our ini file with "hostlist = localhost:2" and started a fresh run.

**Comment by adrianreber** [comment]
Interesting, I have the same error on ppc64 but not on x86_64 with more or less the same configuration:  https://mtt.open-mpi.org/index.php?do_redir=2293

```
There are not enough slots available in the system to satisfy the 3 slots
that were requested by the application.
```

The system has 4 cores:

```
$ cat /proc/cpuinfo 
processor	: 0
cpu		: PPC970MP, altivec supported
clock		: 2500.000000MHz
revision	: 1.1 (pvr 0044 0101)

processor	: 1
cpu		: PPC970MP, altivec supported
clock		: 2500.000000MHz
revision	: 1.1 (pvr 0044 0101)

processor	: 2
cpu		: PPC970MP, altivec supported
clock		: 2500.000000MHz
revision	: 1.1 (pvr 0044 0101)

processor	: 3
cpu		: PPC970MP, altivec supported
clock		: 2500.000000MHz
revision	: 1.1 (pvr 0044 0101)

timebase	: 14318378
platform	: Maple
model		: TSS,7047-191
```

**Comment by jsquyres** [comment]
That's with the spawn test. The resulting number of procs may be more than the number of cores...?

Sent from my phone. No type good.

**Comment by cagoelz** [comment]
The test run after chaning np to 2 produced similar bad results:

"There are not enough slots available in the system to satisfy the 2 slots
that were requested by the application:
  ./c_hello"

https://mtt.open-mpi.org/index.php?do_redir=2294

**Comment by jsquyres** [comment]
@cagoelz Mmm... somehow it still ran with `-np 4`.  Can you send me your .ini file in email?  I'll have a closer look.

**Comment by cagoelz** [comment]
I will send you the ini file tomorrow but I think my skills generating links out of the test reporter may be misleading you. When I scroll about half way down in the linked report to test 19, I see:

****************************************
19
Date range	2016-04-21 18:35:49
Org	absoft
Platform name	Fortran_16.0_32_CentOS5.11
Hardware	 ia32
OS	Linux
MPI name	ompi-nightly-master
MPI version	dev-3885-g5892020
Suite	trivial
Test	ring_mpifh
np	2
Command	mpirun -np 2 --mca btl sm,self ./ring_mpifh 
Launcher	mpirun
Resource Manager	none
Runtime Parameters	Network	
loopback,shmem
Description	Absoft MPI test compilations
Exit value	1
Signal	-1
Duration	00:00:01
Client serial	1543113
Result message	Failed; exit status: 1
Stdout	
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 2 slots
that were requested by the application:
  ./ring_mpifh

Either request fewer slots for your application, or make more slots available
*****************************

**Comment by jsquyres** [comment]
Ah yes, if I scroll down to 19, I see that, too: `-np 2`, and the same error.

Can you run `lstopo` on the machine in question and verify that it's actually showing up with 2 cores?

**Comment by cagoelz** [comment]
[cag@ltljoe3 ~]$ lstopo
Machine (2026MB)
  Socket L#0 + L2 L#0 (2048KB) + L1d L#0 (16KB) + Core L#0
    PU L#0 (P#0)
    PU L#1 (P#1)
  HostBridge L#0
    PCIBridge
      PCIBridge
        PCI 1000:0030
          Block L#0 "sdb"
          Block L#1 "sda"
    PCIBridge
      PCIBridge
        PCI 8086:1076
          Net L#2 "eth0"
      PCIBridge
        PCI 8086:1076
          Net L#3 "eth1"
    PCIBridge
      PCI 1002:5159
    PCI 8086:24db
      Block L#4 "hda"

**Comment by rhc54** [comment]
Is this some kind of VM? It shows only a single core, two HTs. So you could run 2 procs if you add -use-hwthread-cpus, or add "-oversubscribe" to the cmd line. If you do the latter, you can run as many procs as you like, so that is probably the simplest solution.

**Comment by cagoelz** [comment]
It's just an old 32 bit server with a single hyperthreaded Intel something something. I've added
-use-hwthread-cpus and left np at 2.

**Comment by jsquyres** [comment]
Perfect; thanks.
