### ISSUE TITLE
--enable-sparse-groups causes assert failures in intel and ibm tests

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1593]
v2.x results https://mtt.open-mpi.org/index.php?do_redir=2306 shows that `--enable-sparse-groups` is returning in assertion failures in:

* Intel MPI_Comm_split3_c
* Intel MPI_Comm_split3_f 
* Intel MPI_Comm_split4_c 
* Intel MPI_Comm_split4_f 

And v2.x results https://mtt.open-mpi.org/index.php?do_redir=2309 shows an `--enable-sparse-groups` fail in

* IBM group/compare
* Similar failures occurred in IBM communicator/create_group_* (Fortran) in different MTT results

There's a bunch of similar failures in master results: https://mtt.open-mpi.org/index.php?do_redir=2310

@edgargabriel Can you have a look?

**Comment by edgargabriel** [comment]
Honestly, I suspect that these failures have to do something with the addproc changes, since the sparse group code has not changes since ~2008

**Comment by rhc54** [comment]
Is this on the master, or 2.x? I thought we had fixed such things on the master, and so this might just be something that hasn't come across.

**Comment by jsquyres** [comment]
This is on v2.x.  But I see the same failure signature on master.

**Comment by jsquyres** [comment]
Looks like there's more failures of the same type on master (i.e., more fails on master than there are on v2.x).  I added an MTT link for master fails to the initial description.

**Comment by edgargabriel** [comment]
I can have a look, but it will take me a couple of days to get to it

**Comment by jsquyres** [comment]
@edgargabriel Many thanks.  There's no immediate rush, but given all the progress we've made in terms of scalability for the 2.x series, having sparse groups continue to work is probably a Good Thing.  Doesn't need to be v2.0.0, though.

**Comment by rhc54** [comment]
FWIW: I believe @ggouaillardet was looking at this and (IIRC) had a patch for it that is pending for master

**Comment by jsquyres** [comment]
Also FWIW: I don't see an obvious PR pending about sparse groups.  Shrug.  @hjelmn thinks it may be a missing OBJ_RETAIN or OBJ_RELEASE.

**Comment by hjelmn** [comment]
I couldn't find an existing PR so I opened #1595 to fix this. Tested and the failure is gone and I do not see any procs being leaked.
