### ISSUE TITLE
USNIC breaks build if external hwloc is detected

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#1596]
I continue to hit this problem on the 2.x release branch. If an external version of hwloc is present in my path, then the usnic/btl will fail to build with an error that "hwloc.h: not built with verbs support".

Yes, my external hwloc version wasn't built with verbs support - because I don't have IB on my machine!

We fixed this on master, but somehow that fix has been left out of 2.x. Can you please find it and bring it across?

**Comment by jsquyres** [comment]
@rhc54 On https://github.com/open-mpi/ompi-release/pull/1051, you said this could wait until v2.0.1.  Do you now need it for v2.0.0?

**Comment by rhc54** [comment]
I commented on #1051 - we can close this one here
