### ISSUE TITLE
Not checking OF device attributes when making QP's, etc.

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#16]
Galen noticed in a code review of the openib BTL that there are a few places where we are creating WQE's and other items without checking the attributes on the device to see how many it can actually handle.  So we may attempt to exceed the limits unintentionally, and then get a generic error back from the creation function.  These types of errors should either be avoidable or be able to give better warning/error messages because we can detect exactly what the problem is if we're a little more thorough / defensive in the setup.

I'm temporarily assigning this ticket to Galen so that he can cite some specifics.  Who actually fixes them is a different issue.  :-)

**Comment by awlauria** [comment]
openib btl is gone..Closing.
