### ISSUE TITLE
ENOSYS used incorrectly in openib BTL

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1607]
As mentioned in http://www.open-mpi.org/community/lists/devel/2016/04/18839.php, the openib BTL should probably be minorly updated to handle `EOPNOTSUPP`.

See the mail for more details.

**Comment by hppritcha** [comment]
@jsquyres @bturrubiates any progress on this issue?  Should the milestone be changed ?

**Comment by jsquyres** [comment]
I think that this should fall to the openib BTL maintainer: @bharatpotnuri

**Comment by bharatpotnuri** [comment]
@jsquyres Shall work on it.

**Comment by jsquyres** [comment]
Using XOR here seems unnecessarily complicated.  I had to stare at that for a few minutes before I grokked the code.  😄 

Can you make it simpler?

This is just a response to Linus' update a while ago: https://github.com/torvalds/linux/commit/e15f431fe2d53cd4673510736da7d4fa1090e096

Do you think it's necessary, e.g., to future-proof?  Or is that unnecessary?

**Comment by jsquyres** [comment]
@bharatpotnuri That looks great.  Can you file a PR?

**Comment by bwbarrett** [comment]
@bharatpotnuri, #3881 looks ready to merge into master.  Can you do so and then file PRs to merge the change to whichever branches make sense (I assume at least 3.0.0, since the issue is tagged as such)?  Thanks!

**Comment by bharatpotnuri** [comment]
@bwbarrett I submitted PRs for 3.0.x, 3.x, 2.x, 2.0.x. I am not sure if 2.x branches still accept trivial changes. This one anyway is harmless.
Thanks!

**Comment by jsquyres** [comment]
Now merged on all branches.  Closing this issue.
