### ISSUE TITLE
Cannot find /usr/lib64/libpmix.so

### ISSUE THREAD

**Issue by opoplawski** [open-mpi/ompi#1609]
On Fedora, pmix is installed to /usr/lib64/libpmix.so on 64-bit.  openmpi 2.0.0rc2 fails to find it because it only looks in /usr/lib:
~~~~~
checking if user requested PMIx support... yes
checking --with-external-pmix value... sanity check ok (/usr/include)
checking --with-external-libpmix value... not found
configure: WARNING: Expected file /usr/lib/libpmix.* not found
configure: error: Cannot continue
~~~~~

**Comment by rhc54** [comment]
Working this now - hope to have a patch for you to test in the morning.

Out of curiosity: what version of PMIx are you using? We are getting ready to release 1.1.4, and if that is what you would package, then I'll make sure we test that combination.

**Comment by ggouaillardet** [comment]
@opoplawski do you configure with
--with-external-pmix
or
--with-external-pmix=/usr
iirc, we have a macro that search library in lib64 if the dir is /usr

**Comment by rhc54** [comment]
@ggouaillardet Actually, we don't use that macro, and so we aren't currently looking at lib64. I have a patch to correct this now.

**Comment by opoplawski** [comment]
We currently have pmix 1.1.3 packaged.  I'm not specifying =/usr, but it finds the header in /usr/include, it's just not looking in /usr/lib64 as Ralph has confirmed.  I did a quick hack to make a build for testing so there is no big rush.  Thanks.

**Comment by jsquyres** [comment]
PR filed for v2.x: https://github.com/open-mpi/ompi-release/pull/1125
