### ISSUE TITLE
create zero-length MPI derived datatypes

### ISSUE THREAD

**Issue by wkliao** [open-mpi/ompi#1611]
A PnetCDF user reported the following error messages when using OpenMPI to build PnetCDF.
*** An error occurred in MPI_Type_create_hindexed
*** reported by process [230463504385,227633266688]
*** on communicator MPI_COMM_WORLD
*** MPI_ERR_ARG: invalid argument of some other kind
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)

The root cause comes from two MPI datatype constructors below that try create a zero-length datatype.
    MPI_Type_create_hindexed(0, NULL, NULL, MPI_BYTE, &newtype);
and
    MPI_Type_indexed(0, NULL, NULL, MPI_BYTE, &fnewtype);

My understanding is MPI standard considers creating zero-length datatypes a normal practice. 
The same calls do not cause errors when using MPICH.

**Comment by rhc54** [comment]
Could you please tell us what version of OMPI you are referring to?

**Comment by wkliao** [comment]
OpenMPI 1.10.2 and 1.8.5.

Wei-keng

**Comment by bosilca** [comment]
In some of the datatype creation functions we were extremely strict on the arguments (we require a allocated pointer even if the array was not needed). I made (6e6ed62a3) all our datatypes consistent, they all now accept NULL if the count (or the dimensions) is 0.

**Comment by jsquyres** [comment]
Fixed via 6e6ed62.
