### ISSUE TITLE
Only short hostname is accepted in rank file in case of affinity support

### ISSUE THREAD

**Issue by fengliplatform** [open-mpi/ompi#1614]
OpenMPI 1.10.1

When the rank file is like following with long name, Got error.

```
li@fengli-16-120: cat ./hostrankfile0
rank 0=fengli-17.gss.platformlab.ibm.com slot=0
rank 1=fengli-17.gss.platformlab.ibm.com slot=1
rank 2=fengli-17.gss.platformlab.ibm.com slot=2
rank 3=fengli-17.gss.platformlab.ibm.com slot=3
rank 4=fengli-16.gss.platformlab.ibm.com slot=0
rank 5=fengli-16.gss.platformlab.ibm.com slot=1
rank 6=fengli-16.gss.platformlab.ibm.com slot=2
rank 7=fengli-16.gss.platformlab.ibm.com slot=3

li@fengli-16-119: mpirun -rf ./hostrankfile0 ./hello2
--------------------------------------------------------------------------
The rankfile that was used claimed that a host was either not
allocated or oversubscribed its slots.  Please review your rank-slot
assignments and your host allocation to ensure a proper match.  Also,
some systems may require using full hostnames, such as
"host1.example.com" (instead of just plain "host1").

  Host: fengli-16
--------------------------------------------------------------------------
```
When the rank file is like following with short name, it works all right.

```
 li@fengli-16-125: cat ./hostrankfile1
rank 0=fengli-17 slot=0
rank 1=fengli-17 slot=1
rank 2=fengli-17 slot=2
rank 3=fengli-17 slot=3
rank 4=fengli-16 slot=0
rank 5=fengli-16 slot=1
rank 6=fengli-16 slot=2
rank 7=fengli-16 slot=3

li@fengli-16-124: mpirun -rf ./hostrankfile1 ./hello2
Hello world from processor fengli-16, rank 5 out of 8 processors
Hello world from processor fengli-16, rank 6 out of 8 processors
Hello world from processor fengli-16, rank 7 out of 8 processors
Hello world from processor fengli-16, rank 4 out of 8 processors
Hello world from processor fengli-17, rank 2 out of 8 processors
Hello world from processor fengli-17, rank 3 out of 8 processors
Hello world from processor fengli-17, rank 0 out of 8 processors
Hello world from processor fengli-17, rank 1 out of 8 processors
```

Note: this long hostname rank file has been tested successfully with OpenMPI 1.6.5.

***EDIT: Reformatted verbatim text***

**Comment by jsquyres** [comment]
What happens with v2.0.0rc2?

**Comment by jsquyres** [comment]
@fengliplatform Ping.

**Comment by fengliplatform** [comment]
Super busy...sorry for the delay...

So first shot so far...
1. To long name rank file: the same issue.
 li@fengli-16.gss.platformlab.ibm.com-72: cat ./hostrankfile0
rank 0=fengli-17.gss.platformlab.ibm.com slot=0
rank 1=fengli-17.gss.platformlab.ibm.com slot=1
rank 2=fengli-17.gss.platformlab.ibm.com slot=2
rank 3=fengli-17.gss.platformlab.ibm.com slot=3
rank 4=fengli-16.gss.platformlab.ibm.com slot=0
rank 5=fengli-16.gss.platformlab.ibm.com slot=1
rank 6=fengli-16.gss.platformlab.ibm.com slot=2
rank 7=fengli-16.gss.platformlab.ibm.com slot=3
 li@fengli-16.gss.platformlab.ibm.com-73: which mpirun
/usr/local/openmpi-2.0-rc2/bin/mpirun
 li@fengli-16.gss.platformlab.ibm.com-74: mpirun -rf ./hostrankfile0 ./hello2
--------------------------------------------------------------------------
The rankfile that was used claimed that a host was either not
allocated or oversubscribed its slots.  Please review your rank-slot
assignments and your host allocation to ensure a proper match.  Also,
some systems may require using full hostnames, such as
"host1.example.com" (instead of just plain "host1").

  Host: fengli-16
--------------------------------------------------------------------------

**Comment by fengliplatform** [comment]
2. To short name rank file:

 li@fengli-16.gss.platformlab.ibm.com-75: cat ./hostrankfile1
rank 0=fengli-17 slot=0
rank 1=fengli-17 slot=1
rank 2=fengli-17 slot=2
rank 3=fengli-17 slot=3
rank 4=fengli-16 slot=0
rank 5=fengli-16 slot=1
rank 6=fengli-16 slot=2
rank 7=fengli-16 slot=3

 li@fengli-16.gss.platformlab.ibm.com-76: which mpirun
/usr/local/openmpi-2.0-rc2/bin/mpirun
 li@fengli-16.gss.platformlab.ibm.com-79:
 li@fengli-16.gss.platformlab.ibm.com-79: mpirun -rf ./hostrankfile1 ./hello2 > output

//// in standard output/////
.....
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      fengli-16.gss.platformlab.ibm.com
Framework: ess
Component: pmi
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_base_open failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      fengli-17.gss.platformlab.ibm.com
Framework: ess
Component: pmi
--------------------------------------------------------------------------
--------------------------------------------------------------------------
.....


///////// in standard error ///////////
 li@fengli-16.gss.platformlab.ibm.com-79: mpirun -rf ./hostrankfile1 ./hello2 > output
[fengli-16.gss.platformlab.ibm.com:06849] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file runtime/orte_init.c at line 129
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[fengli-16.gss.platformlab.ibm.com:6849] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[fengli-17.gss.platformlab.ibm.com:18005] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[fengli-16.gss.platformlab.ibm.com:06850] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file runtime/orte_init.c at line 129
[fengli-17.gss.platformlab.ibm.com:18005] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file runtime/orte_init.c at line 129
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[fengli-16.gss.platformlab.ibm.com:6850] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init
*** on a NULL communicator
.....

**Comment by fengliplatform** [comment]
Looks not good...but not much time now to look into...Please verify

**Comment by fengliplatform** [comment]
Some other info from my env:

 li@fengli-16.gss.platformlab.ibm.com-86: mpirun -h
mpirun (Open MPI) 2.0.0rc2

Usage: mpirun [OPTION]...  [PROGRAM]...
Start the given program using Open RTE

 li@fengli-16.gss.platformlab.ibm.com-87: ompi_info
                 Package: Open MPI root@fengli-16.gss.platformlab.ibm.com
                          Distribution
                Open MPI: 2.0.0rc2
  Open MPI repo revision: v2.x-dev-1360-geb07690
   Open MPI release date: Apr 28, 2016
                Open RTE: 2.0.0rc2
  Open RTE repo revision: v2.x-dev-1360-geb07690
   Open RTE release date: Apr 28, 2016
                    OPAL: 2.0.0rc2
      OPAL repo revision: v2.x-dev-1360-geb07690
       OPAL release date: Apr 28, 2016
                 MPI API: 3.1.0
            Ident string: 2.0.0rc2
                  Prefix: /usr/local/openmpi-2.0-rc2
 Configured architecture: x86_64-unknown-linux-gnu
          Configure host: fengli-16.gss.platformlab.ibm.com
           Configured by: root
           Configured on: Fri May  6 10:56:27 EDT 2016
          Configure host: fengli-16.gss.platformlab.ibm.com
                Built by: root
                Built on: Fri May  6 11:15:43 EDT 2016
              Built host: fengli-16.gss.platformlab.ibm.com
              C bindings: yes
            C++ bindings: no
             Fort mpif.h: yes (all)
            Fort use mpi: yes (limited: overloading)
       Fort use mpi size: deprecated-ompi-info-value
        Fort use mpi_f08: no
 Fort mpi_f08 compliance: The mpi_f08 module was not built
  Fort mpi_f08 subarrays: no
           Java bindings: no
  Wrapper compiler rpath: runpath
              C compiler: gcc
     C compiler absolute: /usr/bin/gcc
  C compiler family name: GNU
      C compiler version: 4.4.7
            C++ compiler: g++
   C++ compiler absolute: /usr/bin/g++
           Fort compiler: gfortran
       Fort compiler abs: /usr/bin/gfortran
         Fort ignore TKR: no
   Fort 08 assumed shape: no
      Fort optional args: no
          Fort INTERFACE: yes
    Fort ISO_FORTRAN_ENV: no
       Fort STORAGE_SIZE: no
      Fort BIND(C) (all): no
      Fort ISO_C_BINDING: yes
 Fort SUBROUTINE BIND(C): no
       Fort TYPE,BIND(C): no
 Fort T,BIND(C,name="a"): no
            Fort PRIVATE: no
          Fort PROTECTED: no
           Fort ABSTRACT: no
       Fort ASYNCHRONOUS: no
          Fort PROCEDURE: no
         Fort USE...ONLY: no
           Fort C_FUNLOC: no
 Fort f08 using wrappers: no
         Fort MPI_SIZEOF: no
             C profiling: yes
           C++ profiling: no
   Fort mpif.h profiling: yes
  Fort use mpi profiling: yes
   Fort use mpi_f08 prof: no
          C++ exceptions: no
          Thread support: posix (MPI_THREAD_MULTIPLE: no, OPAL support: yes,
                          OMPI progress: no, ORTE progress: yes, Event lib:
                          yes)
           Sparse Groups: no
  Internal debug support: no
  MPI interface warnings: yes
     MPI parameter check: runtime
Memory profiling support: no
Memory debugging support: no
              dl support: yes
   Heterogeneous support: no
 mpirun default --prefix: no
         MPI I/O support: yes
       MPI_WTIME support: native
     Symbol vis. support: yes
   Host topology support: yes
          MPI extensions: affinity, cuda
  MPI_MAX_PROCESSOR_NAME: 256
    MPI_MAX_ERROR_STRING: 256
     MPI_MAX_OBJECT_NAME: 64
        MPI_MAX_INFO_KEY: 36
        MPI_MAX_INFO_VAL: 256
       MPI_MAX_PORT_NAME: 1024
  MPI_MAX_DATAREP_STRING: 128
           MCA allocator: basic (MCA v2.1.0, API v2.0.0, Component v2.0.0)
           MCA allocator: bucket (MCA v2.1.0, API v2.0.0, Component v2.0.0)
           MCA backtrace: execinfo (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA btl: vader (MCA v2.1.0, API v3.0.0, Component v2.0.0)
                 MCA btl: sm (MCA v2.1.0, API v3.0.0, Component v2.0.0)
                 MCA btl: self (MCA v2.1.0, API v3.0.0, Component v2.0.0)
                 MCA btl: tcp (MCA v2.1.0, API v3.0.0, Component v2.0.0)
                  MCA dl: dlopen (MCA v2.1.0, API v1.0.0, Component v2.0.0)
               MCA event: libevent2022 (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
               MCA hwloc: hwloc1112 (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
                  MCA if: posix_ipv4 (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
                  MCA if: linux_ipv6 (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
         MCA installdirs: env (MCA v2.1.0, API v2.0.0, Component v2.0.0)
         MCA installdirs: config (MCA v2.1.0, API v2.0.0, Component v2.0.0)
              MCA memory: patcher (MCA v2.1.0, API v2.0.0, Component v2.0.0)
               MCA mpool: sm (MCA v2.1.0, API v2.0.0, Component v2.0.0)
               MCA mpool: grdma (MCA v2.1.0, API v2.0.0, Component v2.0.0)
             MCA patcher: overwrite (MCA v2.1.0, API v1.0.0, Component
                          v2.0.0)
             MCA patcher: linux (MCA v2.1.0, API v1.0.0, Component v2.0.0)
                MCA pmix: pmix112 (MCA v2.1.0, API v2.0.0, Component v2.0.0)
               MCA pstat: linux (MCA v2.1.0, API v2.0.0, Component v2.0.0)
              MCA rcache: vma (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA sec: basic (MCA v2.1.0, API v1.0.0, Component v2.0.0)
               MCA shmem: mmap (MCA v2.1.0, API v2.0.0, Component v2.0.0)
               MCA shmem: sysv (MCA v2.1.0, API v2.0.0, Component v2.0.0)
               MCA shmem: posix (MCA v2.1.0, API v2.0.0, Component v2.0.0)
               MCA timer: linux (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA dfs: orted (MCA v2.1.0, API v1.0.0, Component v2.0.0)
                 MCA dfs: app (MCA v2.1.0, API v1.0.0, Component v2.0.0)
                 MCA dfs: test (MCA v2.1.0, API v1.0.0, Component v2.0.0)
              MCA errmgr: default_orted (MCA v2.1.0, API v3.0.0, Component
                          v2.0.0)
              MCA errmgr: default_hnp (MCA v2.1.0, API v3.0.0, Component
                          v2.0.0)
              MCA errmgr: default_app (MCA v2.1.0, API v3.0.0, Component
                          v2.0.0)
              MCA errmgr: default_tool (MCA v2.1.0, API v3.0.0, Component
                          v2.0.0)
                 MCA ess: tool (MCA v2.1.0, API v3.0.0, Component v2.0.0)
                 MCA ess: pmi (MCA v2.1.0, API v3.0.0, Component v2.0.0)
                 MCA ess: env (MCA v2.1.0, API v3.0.0, Component v2.0.0)
                 MCA ess: singleton (MCA v2.1.0, API v3.0.0, Component
                          v2.0.0)
                 MCA ess: slurm (MCA v2.1.0, API v3.0.0, Component v2.0.0)
                 MCA ess: hnp (MCA v2.1.0, API v3.0.0, Component v2.0.0)
               MCA filem: raw (MCA v2.1.0, API v2.0.0, Component v2.0.0)
             MCA grpcomm: direct (MCA v2.1.0, API v3.0.0, Component v2.0.0)
                 MCA iof: hnp (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA iof: mr_hnp (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA iof: mr_orted (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA iof: orted (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA iof: tool (MCA v2.1.0, API v2.0.0, Component v2.0.0)
            MCA notifier: syslog (MCA v2.1.0, API v1.0.0, Component v2.0.0)
                MCA odls: default (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA oob: usock (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA oob: tcp (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA plm: rsh (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA plm: slurm (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA plm: isolated (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA ras: loadleveler (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
                 MCA ras: slurm (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA ras: simulator (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
               MCA rmaps: mindist (MCA v2.1.0, API v2.0.0, Component v2.0.0)
               MCA rmaps: round_robin (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
               MCA rmaps: rank_file (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
               MCA rmaps: staged (MCA v2.1.0, API v2.0.0, Component v2.0.0)
               MCA rmaps: resilient (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
               MCA rmaps: ppr (MCA v2.1.0, API v2.0.0, Component v2.0.0)
               MCA rmaps: seq (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA rml: oob (MCA v2.1.0, API v2.0.0, Component v2.0.0)
              MCA routed: direct (MCA v2.1.0, API v2.0.0, Component v2.0.0)
              MCA routed: radix (MCA v2.1.0, API v2.0.0, Component v2.0.0)
              MCA routed: debruijn (MCA v2.1.0, API v2.0.0, Component v2.0.0)
              MCA routed: binomial (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA rtc: freq (MCA v2.1.0, API v1.0.0, Component v2.0.0)
                 MCA rtc: hwloc (MCA v2.1.0, API v1.0.0, Component v2.0.0)
              MCA schizo: ompi (MCA v2.1.0, API v1.0.0, Component v2.0.0)
               MCA state: staged_hnp (MCA v2.1.0, API v1.0.0, Component
                          v2.0.0)
               MCA state: app (MCA v2.1.0, API v1.0.0, Component v2.0.0)
               MCA state: dvm (MCA v2.1.0, API v1.0.0, Component v2.0.0)
               MCA state: orted (MCA v2.1.0, API v1.0.0, Component v2.0.0)
               MCA state: hnp (MCA v2.1.0, API v1.0.0, Component v2.0.0)
               MCA state: tool (MCA v2.1.0, API v1.0.0, Component v2.0.0)
               MCA state: staged_orted (MCA v2.1.0, API v1.0.0, Component
                          v2.0.0)
               MCA state: novm (MCA v2.1.0, API v1.0.0, Component v2.0.0)
                 MCA bml: r2 (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                MCA coll: self (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                MCA coll: basic (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                MCA coll: libnbc (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                MCA coll: inter (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                MCA coll: tuned (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                MCA coll: sm (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                MCA fbtl: posix (MCA v2.1.0, API v2.0.0, Component v2.0.0)
               MCA fcoll: static (MCA v2.1.0, API v2.0.0, Component v2.0.0)
               MCA fcoll: dynamic (MCA v2.1.0, API v2.0.0, Component v2.0.0)
               MCA fcoll: individual (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
               MCA fcoll: two_phase (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
                  MCA fs: ufs (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                  MCA io: ompio (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                  MCA io: romio314 (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA osc: sm (MCA v2.1.0, API v3.0.0, Component v2.0.0)
                 MCA osc: rdma (MCA v2.1.0, API v3.0.0, Component v2.0.0)
                 MCA osc: pt2pt (MCA v2.1.0, API v3.0.0, Component v2.0.0)
                 MCA pml: v (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA pml: ob1 (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA pml: cm (MCA v2.1.0, API v2.0.0, Component v2.0.0)
                 MCA rte: orte (MCA v2.1.0, API v2.0.0, Component v2.0.0)
            MCA sharedfp: lockedfile (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
            MCA sharedfp: sm (MCA v2.1.0, API v2.0.0, Component v2.0.0)
            MCA sharedfp: individual (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
                MCA topo: basic (MCA v2.1.0, API v2.2.0, Component v2.0.0)
           MCA vprotocol: pessimist (MCA v2.1.0, API v2.0.0, Component
                          v2.0.0)
 li@fengli-16.gss.platformlab.ibm.com-88:

**Comment by jjhursey** [comment]
Thanks for trying that release.

I'm assigning myself to this issue, but might not have time to look at it for a few more weeks. If someone has cycles before then feel free to pick it up. Otherwise I'll update once I start work.

**Comment by jsquyres** [comment]
@fengliplatform Github pro tip: enclose blocks of verbatim output in three triple ticks (i.e., ` ` ` without the spaces).  This makes sure that the text renders in the wiki format without markup interpretation and in a fixed-width font.  It's significantly easier to read.

Here's a full description of the Github wiki markdown format that you can use in Github issues, pull requests, and wiki pages: https://help.github.com/articles/basic-writing-and-formatting-syntax/

**Comment by rhc54** [comment]
@fengliplatform Sorry to be so far behind, but have you tried setting the ``orte_keep_fqdn_hostnames`` MCA param? I believe that is all that is required here - we default to stripping the domain name from the host.

**Comment by fengliplatform** [comment]
Thank you @rhc54 for the message. Will try this when get a chance... but can we make both long and short name rank file understood by MCA by default? I would think that would be a better behavior instead of having to set parameter.

**Comment by rhc54** [comment]
It leads to ambiguity, I'm afraid. We've had that problem in the past - someone refers to both a short and long name, and the two were for different machines. Hence the requirement for the parameter.

**Comment by fengliplatform** [comment]
In that case, someone needs to fix their network configuration - that is not proper environment and error prone to all aspects (not only to OpenMPI)... from my point of view. OpenMPI don't have to sacrifice ...

**Comment by rhc54** [comment]
well, we can certainly argue the point, but i'm not inclined to do so here. IMHO, there is no right/wrong, just people doing things in different ways. Since we previously focused on short names, adding a parameter to support the alternative method seemed the best solution and has been accepted for nearly 10 years now. In fact, this is the first concern I've heard about it in at least 5 years, so it clearly isn't a burning issue out there 😄

**Comment by fengliplatform** [comment]
sure,...we appreciate all the effort from community to let this happen :-) BTW, when adding this parameter, is both long and short rank file supported? or only long name supported? Thanks,

**Comment by rhc54** [comment]
The hostnames have to match - so if you have short names in the hostfile, then you need to use short names everywhere else. If you have long names in the hostfile, then you need to use long names everywhere else.

It all hinges on what is being provided in the allocation.

**Comment by jjhursey** [comment]
@fengliplatform Did you have a chance to try the `-mca orte_keep_fqdn_hostnames 1` option?

I did a test using the v2.x series and this option allowed your example to work correctly.

```shell
shell$ cat my-rankfile 
rank 0=node01.mycluster.com slot=0
rank 1=node01.mycluster.com slot=1
rank 2=node02.mycluster.com slot=0
rank 3=node02.mycluster.com slot=1
```

```shell
shell$ mpirun -rf ./my-rankfile ./hello_c 5
--------------------------------------------------------------------------
The rankfile that was used claimed that a host was either not
allocated or oversubscribed its slots.  Please review your rank-slot
assignments and your host allocation to ensure a proper match.  Also,
some systems may require using full hostnames, such as
"host1.example.com" (instead of just plain "host1").

  Host: node01
--------------------------------------------------------------------------
```
```shell
shell$ mpirun -rf ./my-rankfile -mca orte_keep_fqdn_hostnames 1 ./hello_c 5
  0/  4) [node01.mycluster.com] Hello, world!
  0/  4) [node01.mycluster.com] --> Sleep (5)
  1/  4) [node01.mycluster.com] Hello, world!
  1/  4) [node01.mycluster.com] --> Sleep (5)
  2/  4) [node02.mycluster.com] Hello, world!
  2/  4) [node02.mycluster.com] --> Sleep (5)
  3/  4) [node02.mycluster.com] Hello, world!
  3/  4) [node02.mycluster.com] --> Sleep (5)
```

**Comment by fengliplatform** [comment]
Thanks, Josh. Yes , the problem has been resolved. 

To make programmer's life easier, I'd like to see a transparent solution in future that long , short names are covered automatically without having to have a parameter...

Have a nice day

**Comment by jjhursey** [comment]
I'll think a bit more about how to make that transparent to the user. That might require some discussion about expected behavior and the principle of least astonishment.

Thanks for confirming the issue is resolved.
