### ISSUE TITLE
2.0.0rc2: Regression in MPI_File_get_byte_offset()

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#1631]
According to the MPI standard: *The default view is a linear byte stream (displacement is zero, etype and filetype equal to MPI_BYTE).* In the snipped below, I'm expecting to see output of the form ``(i, i)`` for i=0..3, however ``MPI_File_get_byte_offset()`` is returning displacement 0 for any input offset value.

```python
from mpi4py import MPI
comm = MPI.COMM_SELF
mode = MPI.MODE_RDWR | MPI.MODE_CREATE
info = MPI.INFO_NULL
fh = MPI.File.Open(comm, "/tmp/datafile", mode, info)
for offset in range(4):
    print(offset, fh.Get_byte_offset(offset)) 
```
```shell
$ python test-ompi-2.py 
(0, 0)
(1, 0)
(2, 0)
(3, 0)
```

**Comment by edgargabriel** [comment]
I am not sure I understand neither your example nor the argument. If you do not write or read data from the file at all, your file pointer is at the beginning of the file, therefore the offset is zero. *every* process has the initial offset of zero.

**Comment by edgargabriel** [comment]
ok, I see now your point. Let me check, Its not about the position of the file pointer, its about what would it be if you pass in *offset* etypes. I'll double check.

**Comment by dalcinl** [comment]
This is the first of many regressions. I'm double checking all of them and reporting separate issues.
https://bitbucket.org/mpi4py/mpi4py/issues/40/test-failures-with-openmpi-200rc2

**Comment by edgargabriel** [comment]
will create a fix for that, I can confirm that this is a bug.

**Comment by ggouaillardet** [comment]
@dalcinl keep in mind that the default io module is ompio from v2.x, it was previously romio.
what if you
mpirun --mca io romio314 ...

from an end user point of view, I agree this is being seen as a regression.
but from a developer point of view, that might be a bug that has always been around and undetected.

**Comment by dalcinl** [comment]
@ggouaillardet I agree, name it as you see fit and feel free to change the issue title. I'm just reporting issues before 2.0.0 is released, otherwise people will flood my own issue tracker with bugs that are not related to my code, my continuous integration builds start failing after upgrading Open MPI, packagers from Linux distros have to patch my code to skip tests, etc.

**Comment by edgargabriel** [comment]
this is btw. the one issue that will take me a little time to implement. WE have the logic available to perform these calculations, but I need to extract the logic such that we do not move the file pointer at the same time. All other issues that you reported should be resolved by tomorrow. (latest). Its then the release managers duty to decide whether we schedule them for 2.0.0 or 2.0.1

**Comment by jsquyres** [comment]
@edgargabriel Where are we on this?

**Comment by edgargabriel** [comment]
That will take me a couple of more days. I would suggest to push this one to 2.0.1

**Comment by jsquyres** [comment]
Will do; thanks.
