### ISSUE TITLE
2.0.0rc2: Regression in MPI_File_get_size() after two call to MPI_File_preallocate()

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#1633]
```python
from mpi4py import MPI
comm = MPI.COMM_SELF
mode = MPI.MODE_RDWR | MPI.MODE_CREATE
info = MPI.INFO_NULL
fh = MPI.File.Open(comm, "/tmp/datafile", mode, info)
fh.Set_size(0)
assert fh.Get_size() == 0
fh.Preallocate(1)
assert fh.Get_size() == 1
fh.Preallocate(100)
assert fh.Get_size() == 100
```
```shell
$ python test-ompi-4.py 
Traceback (most recent call last):
  File "test-ompi-4.py", line 11, in <module>
    assert fh.Get_size() == 100
AssertionError
```

**Comment by edgargabriel** [comment]
will provide a fix for this, I *think* it is fairly straight forward.

**Comment by edgargabriel** [comment]
just as an FYI, the solution is already available in my private repo, just waiting to finish the fix to file the joint pull request.

**Comment by jsquyres** [comment]
Sweet.  I added the tests so that we can make sure these don't regress again.

**Comment by edgargabriel** [comment]
Cool. The get_byte_offset will take me a bit longer however.

**Comment by dalcinl** [comment]
@edgargabriel @jsquyres There are still issues with `MPI_File_preallocate()`. The following extended example calls preallocate with a size less than the current file size. According to the MPI standard (page 498, lines 23-25), the file size should not change

```python
from mpi4py import MPI
comm = MPI.COMM_SELF
mode = MPI.MODE_RDWR | MPI.MODE_CREATE
info = MPI.INFO_NULL
fh = MPI.File.Open(comm, "/tmp/datafile", mode, info)
fh.Preallocate(0)
assert fh.Get_size() == 0
fh.Preallocate(1)
assert fh.Get_size() == 1
fh.Preallocate(100)
assert fh.Get_size() == 100
fh.Preallocate(10)
assert fh.Get_size() == 100
fh.Preallocate(200)
assert fh.Get_size() == 200
```

```shell
$ mpiexec -n 1 python test-ompi-issue-1633.py 
Traceback (most recent call last):
  File "test-ompi-issue-1633.py", line 13, in <module>
    assert fh.Get_size() == 100
AssertionError
```

**Comment by edgargabriel** [comment]
I'll have a look

**Comment by jsquyres** [comment]
@edgargabriel How's it going on this one -- has it been resolved?

**Comment by edgargabriel** [comment]
It is fixed on master, but I need to file the pr to 2.x.

**Comment by jsquyres** [comment]
Could you do so today?  We're really, really trying to get v2.0.0 out... 😄 

Thanks!

**Comment by edgargabriel** [comment]
ok, I just figured that since the fix to the file_get_byte_offset issue was delayed to 2.0.1, the same will happen to this. I will also need somebody to review this.

**Comment by jsquyres** [comment]
Just talking this over with @hppritcha right now... can you get https://github.com/open-mpi/ompi-release/pull/1212 and the fix for this reviewed in the immediate future, perchance?

**Comment by jsquyres** [comment]
Sorry -- I hit submit too soon: if you can get both of these reviewed in the immediate future, we can put them both in for v2.0.0.  Thanks!

**Comment by edgargabriel** [comment]
Jeff, you want me to push the fix for the preallocate problem into the pr for the get_byte_offset ?

**Comment by edgargabriel** [comment]
I just did that, will keep the efforts low for everybody involved

**Comment by jsquyres** [comment]
Perfect; many thanks, @edgargabriel

**Comment by edgargabriel** [comment]
Jeff, does @vvenkates27 have access to the ompi-tests repository? If not, could you please give him access?

**Comment by jsquyres** [comment]
Done.

**Comment by edgargabriel** [comment]
Thanks!

**Comment by vvenkates27** [comment]
Thanks for providing access.

**Comment by jsquyres** [comment]
Fixed via https://github.com/open-mpi/ompi-release/pull/1212.
