### ISSUE TITLE
Open MPI + Scalasca :Can not run mpirun command with option --prefix

### ISSUE THREAD

**Issue by astrung** [open-mpi/ompi#1658]
I have installed scalasca(scorep,cube,..)with Open MPI for peformance measurement . When i add an option : " --prefix = /my-path" to mpirun, "scalasca - analyze" can not be executed ( Aborted ) .
My command :
_scalasca -analyze mpirun -np 1 --host localhost --prefix /home/as/lib /home/as/Documents/a.out_
"/home/as/lib" is the installed Open MPI directory.
And error :
_S=C=A=N: Abort: Target executable/home/as/lib' is a directory!_
If without "--prefix" , it runs normally .But i need "-- prefix" option to run it on a cluster.
So how to fix it???
Or do we have an other ways to run Open MPI on cluster without --prefix option to specific Open MPI installed directory ???
I have installed Open MPI on all of cluster machines with same path (/home/as/lib)

**Comment by rhc54** [comment]
Configure OMPI --enable-orterun-prefix-by-default and then you won't have to add the prefix option.

BTW: you should let the scorep folks know they have a bug in their program so they can fix it.

**Comment by ggouaillardet** [comment]
you can also try to replace mpirun with `which mpirun` and remove the --prefix option
or you can try
scalasca -analyze -- mpirun --prefix ... 
(not sure how scalasca will handle these though...)

**Comment by astrung** [comment]
I fixed it by " --prefix /my/path ".
But i get an other error:
Do we have any limits on MPI_Send or MPI_Recv - or limits by computer ??? When i try to send large data, it can not completed.
This is my code : 



[All_gather.zip](https://github.com/open-mpi/ompi/files/262883/All_gather.zip)

**Comment by jsquyres** [comment]
Closing this because the question about `--prefix` has been answered (for simplicity, let's keep issues to a single issue -- and you opened #1669 to discuss the other issue).
