### ISSUE TITLE
ibv_resize_cq call on dual-port ConnectX device makes the HCA unusable until reboot

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#166]
Hello,

running a MPI program on our test cluster results in a crash and necessary reboot of the compute nodes, if both ports of the ConnectX HCA are active and used by MPI.
## The error output is:

The OpenFabrics (openib) BTL failed to initialize while trying to
create an internal queue.  This typically indicates a failed
OpenFabrics installation, faulty hardware, or that Open MPI is
attempting to use a feature that is not supported on your hardware
(i.e., is a shared receive queue specified in the
btl_openib_receive_queues MCA parameter with a device that does not
support it?).  The failure occured here:

  Local host:  rc008
  OMPI source: btl_openib.c:190
  Function:    ibv_create_cq()
  Error:       Device or resource busy (errno=16)
  Device:      mlx4_0

You may need to consult with your system administrator to get this
## problem fixed.

[rc008][[5397,1],43][btl_openib.c:222:adjust_cq] cannot resize completion queue, error: 16
[rc008][[5397,1],79][btl_openib.c:222:adjust_cq] cannot resize completion queue, error: 16
....
[rc000][[5397,1],72][btl_openib_component.c:3547:poll_device] error polling HP CQ with -2 errno says Device or resource busy
[rc016][[5397,1],87][btl_openib_component.c:3547:poll_device] error polling HP CQ with -2 errno says Device or resource busy
[rc009][[5397,1],98][btl_openib_component.c:3547:poll_device] error polling LP CQ with -2 errno says Device or resource busy
[rc013][[5397,1],48][btl_openib_component.c:3547:poll_device] error polling LP CQ with -2 errno says Device or resource busy
## ....

Afterwards, the HCAs do not respond to any command, the MPI processes become zombie processes and a reboot of the compute nodes is necessary.

The configuration:
 a) HCAs: Mellanox Technologies MT25418 [ConnectX VPI PCIe 2.0 2.5GT/s - IB DDR / 10GigE]; or Voltaire (ibv_devinfo shows board_id: VLT0130010001, fw_ver: 2.3.000)
 b) both HCA ports are attached to different switches
 c) each port of the HCA belongs to a different IB subnet (2 OpenSM running)
 b) OFED 3.5 rc2
 c) kernel 2.6.32-220.13.1.el6.x86_64

I found the following hint in the source code of ompi/mca/btl/openib/btl_openib.c:
"For ConnectX the resize CQ is not implemented and verbs returns -ENOSYS but should return ENOSYS. So it is reason for abs"

But it looks like the ibv_resize_cq() call does somehow "deadlock" the HCA. The only workaround I found is to set HAVE_IBV_RESIZE_CQ to 0, so that this call isn't executed during the initialization phase.

Please let me know if you have questions or need more information.

Regards,
Jens

PS: the ompi trunk is also affected (but the line number of the error output is different)

**Comment by awlauria** [comment]
Openib btl is removed. Closing.
