### ISSUE TITLE
Limits with MPI_Send or MPI_Recv ??

### ISSUE THREAD

**Issue by astrung** [open-mpi/ompi#1669]
Do we have any limits about message size on MPI_Send or MPI_Recv - or limits by computer ??? When i try to send large data, it can not completed.
This is my code : 

[All_gather.zip](https://github.com/open-mpi/ompi/files/262883/All_gather.zip)
It stopped when i try to run with a buffer about 80000 bytes(40000 integer)

**Comment by jsquyres** [comment]
The attached code does not compile:

```
$ mpicc All_gather.c
All_gather.c:48:1: error: expected identifier or ‘(’ before ‘}’ token
 }
 ^
```

Additionally, it looks like this code is not correct: you are assuming that MPI_Sends can complete before their respective MPI_Recvs have been posted.  This is usually referred to as assuming that MPI has implicit buffering.  See the MPI-3.1 document, page 43, example 3.9 -- your code seems to be making the same mistake.

**Comment by astrung** [comment]
Should i use MPI_ISend or use MPI_Sendrecv ???

**Comment by jsquyres** [comment]
It depends on your application.  In the example you sent, probably either would be fine.

**Comment by astrung** [comment]
But for peformance, which method can be the best solution ???( MPI_Send , ISend , Sendrecv )

**Comment by jsquyres** [comment]
Keep in mind that you have to get your application correct first, and then worry about optimization.

All the various MPI send / receive mechanisms have various benefits and tradeoffs.  And it very much depends on what exactly your real application is doing.  Your best bet may well be to try each of the different mechanisms and see which work best for your particular application.

**Comment by astrung** [comment]
Using MPI_Isend after MPI_Irecv immediately, could we lost data by sending before received node is ready ??
My code:
`for`
`MPI_Irecv` 
`MPI_Isend`
`MPI_Wait_all`

**Comment by jsquyres** [comment]
No.  MPI's communication is defined to be reliable / lossless (even if the receiver isn't ready when the data is sent).
