### ISSUE TITLE
orte_ras_base_node_insert():  loss of slots on HNP

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#167]
For RAS modules that produce multiple orte_node_t records matching the HNP, the HNP record will be overridden with ONLY the slot count of the final orte_node_t record in the "nodes" list produced by the RAS module.  E.g. this came up when Grid Engine produced the following PE_HOSTFILE:

```
node01-53 6 all.q@node01-53 <NULL>
node01-53 10 distrib.q@node01-53 <NULL>
```

where node01-53 is the HNP for the job and Grid Engine's allocation across multiple queues on node01-53 is the cause for two lines instead of just one.  As far back as Open MPI 1.4.2 this issue exists in orte_ras_base_node_insert(); in the 1.6.1 source see orte/mca/ras/base/ras_base_node.c:99.

Since all RAS modules can effectively produce multiple orte_node_t records with the same node name, it seems logical to fix this in orte_ras_base_node_insert().

**Comment by rhc54** [comment]
Fixed long ago
