### ISSUE TITLE
About  mpiCC/mpic++/mpicxx 

### ISSUE THREAD

**Issue by Zhiming-Wang** [open-mpi/ompi#1686]
As far as I know; the C++ MPI bindings is disabled by default at v2.0. 
// "configure" file at openmpi-2.0.0rc2.tar.bz2
145   --enable-mpi-cxx        enable C++ MPI bindings (default: disabled)

I installed openmpi-2.0.0rc2 without manually add "enable-mpi-cxx", but mpiCC/mpic++/mpicxx exist and do not work. I think they should be removed to avoid confusion the user, if "enable-mpi-cxx" is not specified.

**Comment by jsquyres** [comment]
Can you clarify what you mean by "they do not work"?

AFAIK, they still work just fine -- you can compile C++-based MPI applications, and use the MPI C++ bindings (that were, indeed, removed in MPI-3.0, but at still allowed to be in MPI implementations).

**Comment by Zhiming-Wang** [comment]
Sorry, I forget that user can access the C bindings from C++. The mpiCC/mpic++/mpicxx are needed.
I closed the issue. Thanks @jsquyres
