### ISSUE TITLE
Heterogeneous builds broken (master and v2.x)

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1694]
From https://mtt.open-mpi.org/index.php?do_redir=2324 (master, but v2.x is the same):

```
--- make check  result_stdout/result_stderr ---
unpack_ooo.c:35:1: warning: missing braces around initializer [-Wmissing-braces]
 } foo = {0}, *bar = NULL;
 ^
unpack_ooo.c:35:1: warning: (near initialization for ‘foo.i’)
[-Wmissing-braces]unpack_ooo.c:40:1: warning: missing braces around initializer [-Wmissing-braces]
 } pfoo = {0}, *pbar = NULL;
 ^unpack_ooo.c:40:1: warning: (near initialization for ‘pfoo.i’) [-Wmissing-braces]
  CCLD     unpack_ooo
```

@bosilca @ggouaillardet

**Comment by bosilca** [comment]
These are harmless warnings (a more picky compiler than usual). The real culprit seems to be the ddt_pack test, which aborted. Can you provide a stack trace ?

**Comment by jsquyres** [comment]
Here's the bt:

```
(gdb) bt
#0  0x0000003491632925 in raise () from /lib64/libc.so.6
#1  0x0000003491634105 in abort () from /lib64/libc.so.6
#2  0x000000349162ba4e in __assert_fail_base () from /lib64/libc.so.6
#3  0x000000349162bb10 in __assert_fail () from /lib64/libc.so.6
#4  0x00002aaaaab3dd46 in ompi_datatype_get_pack_description (
    datatype=0x604e30, packed_buffer=0x7fffffffc808)
    at ompi_datatype_args.c:506
#5  0x00002aaaaab3de39 in ompi_datatype_pack_description_length (
    datatype=0x604e30) at ompi_datatype_args.c:544
#6  0x0000000000401dba in main (argc=1, argv=0x7fffffffcb48) at ddt_pack.c:366
```

**Comment by ggouaillardet** [comment]
This is related to the issue that was initially reported at http://www.open-mpi.org/community/lists/users/2016/05/29260.php

@bosilca found an issue and fixed it in open-mpi/ompi@16d9f71d01cc and that was backported into v2.x and v1.10.

i also identified an other issue (that unlikely affected the user at that time) which is yet to be solved.
(basically, we do not ```malloc``` enough space for the datatype description when alignment is mandatory and does require some extra space)

i initially posted the two patches below patches

these are simple heuristics that are good enough for this case.
a correct (and heavier) fix would be to make a "dry" ```ompi_datatype_get_pack_description``` to get the exact description length, and then do the real ```ompi_datatype_get_pack_description``` to get the description (or to ```realloc``` when needed)

fwiw, George added an ```assert()``` to trap this error, so the bug was always here, and we were just lucky the test did not fail until now


for master

```patch
diff --git a/ompi/datatype/ompi_datatype_args.c b/ompi/datatype/ompi_datatype_args.c
index 5a62ac5..d73d044 100644
--- a/ompi/datatype/ompi_datatype_args.c
+++ b/ompi/datatype/ompi_datatype_args.c
@@ -100,8 +100,8 @@ typedef struct __dt_args {
         if( pArgs->ci == 0 ) pArgs->i = NULL;                           \
         else pArgs->i = (int*)buf;                                      \
         pArgs->ref_count = 1;                                           \
-        pArgs->total_pack_size = (4 + (IC)) * sizeof(int) +             \
-            (AC) * sizeof(OPAL_PTRDIFF_TYPE);                           \
+        pArgs->total_pack_size = (4 + (IC) - (DC)) * sizeof(int) +      \
+            ((AC) + (DC)) * sizeof(OPAL_PTRDIFF_TYPE);                  \
         (PDATA)->args = (void*)pArgs;                                   \
         (PDATA)->packed_description = NULL;                             \
     } while(0)
```

for v1.10
```patch
diff --git a/ompi/datatype/ompi_datatype_args.c b/ompi/datatype/ompi_datatype_args.c
index d6a33b3..0b5e01c 100644
--- a/ompi/datatype/ompi_datatype_args.c
+++ b/ompi/datatype/ompi_datatype_args.c
@@ -100,8 +100,8 @@ typedef struct __dt_args {
         if( pArgs->ci == 0 ) pArgs->i = NULL;                           \
         else pArgs->i = (int*)buf;                                      \
         pArgs->ref_count = 1;                                           \
-        pArgs->total_pack_size = (4 + (IC)) * sizeof(int) +             \
-            (AC) * sizeof(OPAL_PTRDIFF_TYPE);                           \
+        pArgs->total_pack_size = (4 + (IC) - (DC)) * sizeof(int) +      \
+            ((AC) + (DC)) * sizeof(OPAL_PTRDIFF_TYPE);                  \
         (PDATA)->args = (void*)pArgs;                                   \
         (PDATA)->packed_description = NULL;                             \
     } while(0)
```

**Comment by bosilca** [comment]
I think open-mpi/ompi@2b868c4 should solve the problem. I was miscounting (OK ignoring) the space for storing the datatype ID. Now we will overcompute the length of the packed description, but the only impact will be on the local allocation. When the data is packed to be moved to another node (such as one-sided), we are using the length returned by the packing function, value that is correct.

**Comment by jsquyres** [comment]
@ggouaillardet @bosilca Is this now resolved?

**Comment by jsquyres** [comment]
@ggouaillardet @bosilca Is this now resolved?

**Comment by jsquyres** [comment]
I see open-mpi/ompi-release@82c479a0935efda8b1856cc43a461c4c7630f1f5 which is apparently the cherry pick of  open-mpi/ompi@2b868c4.

Looks like this issue is closed.
