### ISSUE TITLE
Improve ARM support

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#170]
Per discussion on the devel list:

```
http://www.open-mpi.org/community/lists/devel/2013/01/11955.php
```

Lief would like to revert r27882 and implement it differently (see first mail in this thread).  r27882 was not accepted into v1.6; a different (simpler) workaround was used as a stopgap.

Lief -- do you have a timeline for this implementation?  Can it be done in the near enough future to include in the v1.7 series?  Should be revert r27882 in the immediate future?

**Comment by bosilca** [comment]
Several issues with compiling on a RasberryPi2 (armv7-a) have been reported on the mailing list. The patch proposed in the original [svn r27882](https://svn.open-mpi.org/trac/ompi/changeset/27882) provides an ugly but functional solution. I propose we reintegrate the original patch in master.

**Comment by jsquyres** [comment]
@bosilca Sounds good.  Can you commit to master?

**Comment by bosilca** [comment]
I just got a rpi2. Give me few days to check the status of this.

**Comment by jsquyres** [comment]
Move this to the Future milestone -- I think 2.x is the earliest this will happen.

**Comment by jsquyres** [comment]
@shamisp Just saw this in the old issues -- can you look to see if it is still relevant?  If not, feel free to close it.  Thanks.

**Comment by hppritcha** [comment]
Moving to 3.x milestone

**Comment by hppritcha** [comment]
@shamisp if you want anything for ARM in 3.0.0 needs to be in the pipeline this week.  We're planning on forking this week and only what's on #3107 (modulo bug fixes) will get in.

**Comment by jsquyres** [comment]
I believe that ARMv8 is now well-supported.
