### ISSUE TITLE
rcache/grdma : build broken for CUDA GDR

### ISSUE THREAD

**Issue by sjeaugey** [open-mpi/ompi#1702]
As reported by MTT. Build fails at rcache_grdma_module.c:486 ('base' undeclared).

**Comment by hjelmn** [comment]
Not in a release so removing blocker flag.

**Comment by hjelmn** [comment]
Will be fixed once jenkins finishes on #1703.

**Comment by sjeaugey** [comment]
Thanks for the fix. I was not sure indeed if flags were relevant outside of releases.

**Comment by hjelmn** [comment]
No problem. The flags tend to be used for releases since there is no blocking master :).

**Comment by sjeaugey** [comment]
:+1: I confirm that fixed the build issue. Should be reflected in two days in MTT.

**Comment by sjeaugey** [comment]
This issue shows up in v2.x now.

**Comment by hjelmn** [comment]
Ah yes. Will backport the change.

**Comment by sjeaugey** [comment]
Not fixed on v2.x

**Comment by sjeaugey** [comment]
Build is fixed in v2.x.
Closing this one.
