### ISSUE TITLE
RFC: Remove (broken) heterogeneous support

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#171]
Per http://www.open-mpi.org/community/lists/devel/2013/01/12060.php:

WHAT: Remove the configure command line option to enable heterogeneous support 

WHY: The heterogeneous conversion code isn't working, very few people use this feature 

WHERE: README and config/opal_configure_options.m4. See attached patch. 

TIMEOUT: Next Tuesday teleconf, 5 Feb, 2013 

MORE DETAIL: 

The heterogeneous code has been broken for a while. The assumption is that this is a minor bug that can fairly easily be fixed, but a) no one has taken the time to do so, b) very few people use this functionality, and c) many OMPI developers don't even have hardware where to test this scenario (e.g., big and little endian systems). 

As such, a suggestion was made to remove the --enable-heterogeneous configure CLI switch so that users don't try to enable it. It someone ever fixes the heterogeneous code, the configure CLI switch can be put back.

**Comment by rhc54** [comment]
This seems to work in some releases and not in others - closing due to lack of interest
