### ISSUE TITLE
--with-valgrind=/path builds broken on master

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1732]
The addition of the new hwloc component (v1.11.3) appears to have broken external valgrind builds.

Specifically, early in configure, hwloc1113 checks for `<valgrind/valgrind.h>` and fails to find it.  Note that this is fine for hwloc -- it doesn't need Valgrind support.

However, if OMPI was configured with `--with-valgrind=/location`, then later in configure, then `opal/mca/memchecker/valgrind/configure.m4` adds `-I/location/include` to `$CPPFLAGS` and then checks for `<valgrind/valgrind.h>`.  However, Autoconf thinks it has already done this test -- and uses the cached result (i.e., that `<valgrind/valgrind.h>` wasn't found).  I.e., the new `$CPPFLAGS` value is ignored.

I'm not sure what the correct fix is here.

**Comment by rhc54** [comment]
If hwloc doesn't need valgrind, then why does it include that header and check for it??

**Comment by jsquyres** [comment]
hwloc *can* use Valgrind, but it doesn't *need* it.

**Comment by bgoglin** [comment]
I committed your code with reworded comments and commit message. Thanks.
