### ISSUE TITLE
MPI_Abort(0) in srun/pmi2 aborts only current process

### ISSUE THREAD

**Issue by plesn** [open-mpi/ompi#1744]
The `PMI2_Abort()` function aborts all processes when the flag is
non-zero, otherwise it exits only current process. The MPI spec for
`MPI_Abort()` says it should abort all tasks (on a best effort basis)
and return the error code. So strictly speaking we may be ok even
though we don't abort.

If user calls MPI_Abort with 0, should we rather abort all processes
at the cost of changing the error code to non-zero ?

**Comment by rhc54** [comment]
Since slurm specifically documents their behavior, it seems to me that we would be causing considerable confusion if we changed it under-the-covers.
