### ISSUE TITLE
MPI_Waitall optimization

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#176]
The current MPI_Waitall() has O2 complexity
can do better.
very important for pps benchmarks

When using MPI_ISend + MPI_Waitall() is worse than using MPI_Send

**Comment by jsquyres** [comment]
This issue (improving WAIT/TEST) has come up a few times (e.g., in the face-to-face dev meeting in Jan and June 2015).  @bosilca is working on it.

**Comment by jsquyres** [comment]
@bosilca Did you ever make any progress on this TEST/WAIT optimization stuff?

**Comment by bosilca** [comment]
Yes. It is in paper submission stage ...

**Comment by miked-mellanox** [comment]
out of curiosity, could you please share offline the conclusions and results?

**Comment by bosilca** [comment]
This issue is now stale, all future discussion will go in #1820 ,
