### ISSUE TITLE
support for auto-discovery MTU in ompi/mca/btl/openib/mca-btl-openib-device-params.ini

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#177]
Hi,
Today ompi/mca/btl/openib/mca-btl-openib-device-params.ini files contains static MTU definition per card.

When MTU is changed in the fabric, card is not aware of this change and the only way to notify OMPI is to pass "-mca btl_openib_ib_mtu 4096" parameter to mpirun command line

Jeff suggested:
Maybe there should be a new sentinel value in the file that means "use whatever the network MTU is"?  That would give you the ability to force a specific MTU via MCA param / INI file, or have OMPI just use whatever the network admin set.

**Comment by jsquyres** [comment]
I highly doubt this will ever be fixed.
