### ISSUE TITLE
pmix use of strnlen is not portable

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1771]
As reported by @siegmargross http://www.open-mpi.org/community/lists/users/2016/06/29405.php, Solaris 10 does not have `strnlen`.  It is used in the pmix 114 component:

```
$ ack strnlen
ompi/mca/io/romio314/romio/mpi-io/register_datarep.c
68:    /* check datarep name (use strlen instead of strnlen because
69:       strnlen is not portable) */

opal/mca/pmix/pmix114/pmix/src/server/pmix_server_listener.c
318:    if ((int)strnlen (msg, len) < len) {
332:    if ((int)strnlen (msg, len) < len) {
339:    if ((int)strnlen (msg, len) < len)
```

@rhc54 Can you add a quick configure test to PMIx and use an alternate when `strnlen` is not available?

**Comment by rhc54** [comment]
I'm afraid you are a little late for the PMIx 1.1.4 release, but I can do something for inside OMPI and add it to PMIx for a future release. It means that we won't support Solaris 10 based on distro packages, but that is probably too big of a problem - any such users will just have to build OMPI themselves using the internal PMIx support.

**Comment by rhc54** [comment]
Someone with access to a machine that does not have strnlen might want to check this to ensure I got it right
