### ISSUE TITLE
OpenMPI puts `-L/usr/lib` into `libmpi.la`

### ISSUE THREAD

**Issue by eschnett** [open-mpi/ompi#1776]
OpenMPI 1.10 (and 1.8) put the system library directory `/usr/lib` into the library search path. This leads to the following problem:
- I have installed OpenMPI myself
- I am now building HDF5 with MPI support (using `CC=/my/openmpi/location/bin/mpicc` etc.)
- HDF5 examines the linker flags that OpenMPI needs, and then uses `-L/usr/lib` in its `LDFLAGS`
- The system already has (a different version of) OpenMPI installed in `/usr/lib`
- With `/usr/lib` in the library search path, the compiler picks up a mixture of the system OpenMPI and the OpenMPI I installed, leading to build problems; HDF5's configure then aborts

See <https://github.com/LLNL/spack/issues/1038> for details where this was discussed.

I don't think `/usr/lib` or `/usr/local/lib` should ever be explicitly put into the library search path. These directories contain many libraries, and should thus searched last; all explicitly specified directories need to be search first. Otherwise, it is impossible to use a self-built library instead of a system library.

I think OpenMPI needs to filter out `/usr/lib` and `/usr/local/lib` (and likewise `/usr/include` and `/usr/local/include`) from its library and include search paths that are stored e.g. in `libmpi.la` or in the `pkgconfig` directory.

**Comment by rhc54** [comment]
We don't typically do that, so it is either a bug or due to something we picked up. Can you please create a gist and give us your configure cmd line, the output of configure, and the config.log?

**Comment by eschnett** [comment]
I believe this was caused by the option `--with-verbs=/usr`. I'm now using `--with-verbs` instead. Thanks for the quick reply!
