### ISSUE TITLE
Fix error code propagation for persistent requests

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1780]
Per @bosilca's comment (https://github.com/open-mpi/ompi-release/pull/1199#issuecomment-224670918), error codes are not being propagated properly for persistent requests (after the recent request code revamp).

**Comment by bwbarrett** [comment]
@jsquyres / @bosilca, do you remember context and what we need to do?  It's labelled as a 3.0.x issue, but I'm not sure I follow why...

**Comment by bosilca** [comment]
No recollection. Let's just close it for now.

**Comment by jsquyres** [comment]
@bosilca You said that error codes were not being propagated properly for persistent requests.

Do you know that that now works?

**Comment by bosilca** [comment]
I remember what I said, I don't remember why. I checked the error path in the request management code, and I do not see any inconsistencies between persistent and non-persistent requests. If I find more info about this I will reopen the issue.
