### ISSUE TITLE
OPAL_ENABLE_THREAD_MULTI usage on v2.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1796]
@hjelmn @bosilca There is a use of `OPAL_ENABLE_THREAD_MULTI` in bml/r2 on v2.x that is causing a compiler warning (because it isn't defined).  This macro is not used in bml/r2 on master.  With all the thread changes on master recently, I don't know whether it is safe to just delete this `#if` or not.

Master:

```c
    /* do it last, for the lazy initialization check in bml_base_get* */
    opal_atomic_wmb();
    proc->proc_endpoints[OMPI_PROC_ENDPOINT_TAG_BML] = bml_endpoint;
```

v2.x:

```c
    /* do it last, for the lazy initialization check in bml_base_get* */
#if OPAL_ENABLE_THREAD_MULTI
    opal_atomic_wmb();
#endif /* OPAL_ENABLE_THREAD_MULTI */
    proc->proc_endpoints[OMPI_PROC_ENDPOINT_TAG_BML] = bml_endpoint;
```

Please investigate.

**Comment by hjelmn** [comment]
Just delete it. It hasn't existed for a long time.

**Comment by jsquyres** [comment]
Closed via https://github.com/open-mpi/ompi-release/pull/1234

**Comment by jsquyres** [comment]
Closed via https://github.com/open-mpi/ompi-release/pull/1236
