### ISSUE TITLE
IBV_EVENT_PORT_ERR generated when second port of Mellanox VPI adapter loses link

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#180]
On a system with a Mellanox ConnectX-3 VPI adapter running the first port in Infiniband mode and the second port in Ethernet mode, an IBV_EVENT_PORT_ERR message is generated if the second port loses link even though IMB-MPI1 is running over the first port only.

Mellanox development investigated and concluded that the asynchronous event handler in openmpi does not check the port.

This problem has been observed under multiple versions of OpenMPI including 1.6.5, and under multiple versions of RH (6.2, 6.3, 6.4) and SLES (11.2 & 11.3).

**Comment by rhc54** [comment]
Per Mellanox, this can be closed. Any further work will be done on a separate new ticket.

**Comment by masteele** [comment]
What was Mellanox's reason for closing this?
