### ISSUE TITLE
RFE: support for "--map-by nic"

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#181]
I am sitting in a talk by Jeff on the LAMA work.

I made the observation that his slide showing hwloc's map of a server shows 2 NICs, and then asked how one would go about mapping or binding "by NIC".  His response was to request this Trac ticket.

Only the case that a server has a 1-to-1 correspondence between NICs and an existing token (e.g. board, numa or socket) can this currently by done using the existing options, and even then the user needs to KNOW the correspondence.

So, this is an RFE to add "nic" to the mapping and binding options.

The first "trick" is that this particular level will sit at a different "depth" in the hierarchy on different servers.
The 2nd "trick" is that the btl (etc.) may need to also cooperate (bind to single nic rather than striping) - but that might be an ADDITIONAL set of explicit MCA params rather than implicitly requested via the --bind-by.

**Comment by rhc54** [comment]
I think we've concluded that we just don't know how to do this.
