### ISSUE TITLE
[feature suggestion] Please add the .cmake file for cmake-based projects to be able to configure ompi better

### ISSUE THREAD

**Issue by yurivict** [open-mpi/ompi#1819]

**Comment by jsquyres** [comment]
I'm not sure what you're asking for -- are you looking for a zero-length `.cmake` file at the top of the Open MPI tree?

If you're asking for full cmake support, it is unfortunately unlikely that we will add that.  Open MPI is a GNU Autotools-based system.  We have discussed adding cmake support a few times over the years, but every time we have more than one build system, the multiple systems end up drifting out of sync with each other and it ends up being a bit of a mess.  😦

**Comment by jsquyres** [comment]
I'm going to assume you're asking for full cmake support and close this issue.  If you intended something else, please reply to this ticket and we can re-open if necessary.  Thanks.
