### ISSUE TITLE
MPI_Status_set_elements

### ISSUE THREAD

**Issue by jjhursey** [open-mpi/ompi#1825]
Test case in this Gist: https://gist.github.com/jjhursey/95b6c8a26bf100a7076a69c6e2983eed

In `MPI_Status_set_elements`, if a datatype is defined by the user, then setting the elements in status is incorrect.

Fails at the macro call on [Line 222](https://gist.github.com/jjhursey/95b6c8a26bf100a7076a69c6e2983eed#file-large-count-c-L222) in large-count.c (see Gist)

[Line 198](https://gist.github.com/jjhursey/95b6c8a26bf100a7076a69c6e2983eed#file-large-count-c-L198) in large-count.c makes a call to `MPI_Status_set_elements` with a user defined datatype, the description of the datatype is shown below:
```c
    198             MPI_Status_set_elements(&status, (type_), 1);         \
    199             MPI_Get_elements(&status, (type_), &elements);        \
    200             MPI_Get_elements_x(&status, (type_), &elements_x);    \
    201             MPI_Get_count(&status, (type_), &count);              \
    202             check(elements == (elts_));                           \
    203             check(elements_x == (elts_));                         \
    204             check(count == 1);                                    \
```

The datatype being passed in is `imax_contig` with the state below before calling the `check_set_elements` macro
```
(gdb) p *imax_contig 
$2 = {
  super = {
    super = {
      obj_magic_id = 16046253926196952813, 
      obj_class = 0x3fff8be85308 <ompi_datatype_t_class>, 
      obj_reference_count = 1, 
      cls_init_file_name = 0x3fff8be56350 "../../../../opensrc/ompi/ompi/datatype/ompi_datatype_create.c", 
      cls_init_lineno = 68
    }, 
    flags = 308, 
    id = 0, 
    bdt_used = 16, 
    size = 2147483647, 
    true_lb = 0, 
    true_ub = 2147483647, 
    lb = 0, 
    ub = 2147483647, 
    nbElems = 2147483647, 
    align = 1, 
    name = '\000' <repeats 63 times>, 
    desc = {
      length = 4, 
      used = 1, 
      desc = 0x1000a869d70
    }, 
    opt_desc = {
      length = 3, 
      used = 1, 
      desc = 0x1000a8b6c10
    }, 
    btypes = {0, 0, 0, 0, 2147483647, 0 <repeats 42 times>}
  }, 
  id = 73, 
  d_f_to_c_index = 73, 
  d_keyhash = 0x0, 
  args = 0x1000a8b30a0, 
  packed_description = 0x0, 
  pml_data = 0, 
---Type <return> to continue, or q <return> to quit---
  name = "\000\000\000\000\000\000\000\000\277\\\205\n\000\001\000\000\312\\\205\n\000\001\000\000\n\000\000\000\000\000\000\000\017\000\000\000\000\000\000\000\250i\213\n\000\001\000\000\001\000\000\000\000\000\000\000\350k\213\n\000\001\000"
}
```

In `MPI_Status_set_elements()`, the setting of `_ucount` is based on the size of the datatype passed in which is then passed to `ompi_datatype_set_element_count()` (then `opal_datatype_set_element_count`) to obtain the size of the datatype.  Here the size for the datatype  returned from `opal_datatype_set_element_count()` is 1 which is set as `_ucount` of the status. (see [Line 80 of `status_set_elements.c`](https://github.com/open-mpi/ompi/blob/master/ompi/mpi/c/status_set_elements.c#L82) )

```shell
shell$ mpirun -np 1 large-count-dbg
check failed: (elements == (2147483647)), line 222
check failed: (elements_x == (2147483647)), line 222
check failed: (count == 1), line 222
check failed: (elements == (2147483647)), line 222
check failed: (elements_x == (2147483647)), line 222
check failed: (count == 1), line 222
check failed: (elements == (4)), line 223
check failed: (elements_x == (4)), line 223
check failed: (count == 1), line 223
found 18 errors
```

Here the actual values (for the failure at line 222):
```
(gdb) p elements
$1 = 1
(gdb) p elements_x 
$2 = 1
(gdb) p count
$3 = -32766
```
Instead of the expected values noted in the `check failed` message above.

**Comment by ggouaillardet** [comment]
@jjhursey @bosilca and i previously discussed a similar case.
per the MPI 3.1 standard (p483) about ```MPI_STATUS_SET_ELEMENTS[_X]```
```
These functions modify the opaque part of status so that a call to
MPI_GET_ELEMENTS or MPI_GET_ELEMENTS_X will return count. MPI_GET_COUNT
will return a compatible value.
Rationale. The number of elements is set instead of the count because the former
can deal with a nonintegral number of datatypes. (End of rationale.)
```

so bottom line, the test is wrong (and so is mpich by the way ...)
if you
```
MPI_Status_set_elements(&status, (type_), 1);
MPI_Get_elements(&status, (type_), &elements);
MPI_Get_elements_x(&status, (type_), &elements_x);
MPI_Get_count(&status, (type_), &count);
```
then the checks should be
```
check(elements == 1);
check(elements_x == 1);
```
the count check is type dependent, for ```four_ints``` and ```imax_contig``` for example, that should be
```
check(count == 0);
```


an other way to see things is to simply
```
MPI_Status_set_elements(&status, (type_), (elts_));
```

then the test works fine under OpenMPI (but fails with mpich fwiw)

**Comment by ggouaillardet** [comment]
i wrote a fixed and extended version of the test, it is available at https://gist.github.com/ggouaillardet/f3ec4611a3c880206cd9b6a5ca89df55

**Comment by jjhursey** [comment]
@ggouaillardet Thanks for the response. That sounds reasonable to me. Let me talk it over internally with the folks that asked me to report the issue before we close it as invalid.

**Comment by jjhursey** [comment]
After discussing this a bit internally, I think we are coming to the same consensus opinion. I'm going to close this issue as invalid. Thanks!
