### ISSUE TITLE
configuring OMPI with the latest PMIx master

### ISSUE THREAD

**Issue by karasevb** [open-mpi/ompi#1827]
Hello, it seems that `./configure` test for the pmix v2.x/2.0 has problems. Here is the excerpt from the configure log on my machine when trying to configure with PMIx/master:

```
configure:139819: checking for library containing PMIx_Register_event_handler
configure:139850: gcc -std=gnu99 -o conftest -I/sandbox/hwloc/include -O3 -DNDEBUG 
    -Wall -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes 
    -Wcomment -pedantic -Werror-implicit-function-declaration -finline-functions -fno-strict-aliasing 
    -mcx16 -pthread    -I/sandbox/hwloc/include  -I/home/user/pmix/libevent-2.0.22-stable/install/include -I/sandbox/pmix/include     
    -L/sandbox/hwloc/lib  -L/home/user/pmix/libevent-2.0.22-stable/install/lib 
    -L/sandbox/pmix/lib conftest.c  -lm -lutil   -lhwloc  -lm -lutil   -lhwloc  -levent 
    -levent_pthreads >&5
conftest.c:601:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 char PMIx_Register_event_handler ();
 ^
conftest.c:603:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 main ()
 ^
/tmp/ccMI5mKr.o: In function `main':
conftest.c:(.text.startup+0x7): undefined reference to `PMIx_Register_event_handler'
collect2: error: ld returned 1 exit status
configure:139850: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Open MPI"
| #define PACKAGE_TARNAME "openmpi"
| #define PACKAGE_VERSION "gitclone"
. . .
| #define HAVE_SYS_AUXV_H 1
| #define HAVE_PMIX_H 1
| /* end confdefs.h.  */
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char PMIx_Register_event_handler ();
| int
| main ()
| {
| return PMIx_Register_event_handler ();
|   ;
|   return 0;
| }
```

If I grab `conftest.c` and compile it with PMIx library - all is OK. The problem seems to be in the original compilation command: I don't see `-lpmix` there:
```
gcc -std=gnu99 -o conftest -I/sandbox/hwloc/include -O3 <snip>  -L/sandbox/hwloc/lib  
    -L/home/user/pmix/libevent-2.0.22-stable/install/lib -L/sandbox/pmix/lib conftest.c 
    -lm -lutil   -lhwloc  -lm -lutil   -lhwloc  -levent -levent_pthreads >&5
```

**Comment by karasevb** [comment]
Sorry, that was a false alarm. Confusion came from several facts:
* First, originally I was configuring against the stale master that was lacking of `PMIx_Register_event_handler()` and thus OMPI wasn't treat it as pmix/ext2.0.
* Second when today I started configuring against latest master the config.log was confusing because of the way `./configure` checks for the libraries:
```
+ for ac_lib in ''\'''\''' pmix
+ test -z ''
+ ac_res='none required'
+ ac_fn_c_try_link 139850

... snippet ...

+ for ac_lib in ''\'''\''' pmix
+ test -z pmix
```

As you can see 2 libraries are actually checked: a) the empty lib; b) the pmix lib.

So I saw the empty lib check and fired the false alarm

**Comment by artpol84** [comment]
@jsquyres do you know why calling
```
OPAL_CHECK_PACKAGE([opal_pmix_ext20],
                              [pmix.h],
                              [pmix],
                              [PMIx_Register_event_handler],
                              [-lpmix],
                              [$pmix_ext_install_dir],
                              [$pmix_ext_install_dir/lib],
                              [AC_MSG_RESULT([yes])
                               opal_pmix_ext20_happy=yes],
                              [AC_MSG_RESULT([no])
                               opal_pmix_ext20_happy=no])
```

leads to checking of "" and "pmix" instead of just "pmix"?

**Comment by jsquyres** [comment]
OPAL_CHECK_PACKAGE uses [AC_SEARCH_LIBS](https://www.gnu.org/software/autoconf/manual/autoconf.html#index-AC_005fSEARCH_005fLIBS-344).

I assume from the discussion above that this issue should be closed; feel free to re-open it, if incorrect.

**Comment by artpol84** [comment]
Yeah I know it uses it, but it doesn't explain to me why we check
empty-string as lib.

среда, 29 июня 2016 г. пользователь Jeff Squyres написал:

> OPAL_CHECK_PACKAGE uses AC_SEARCH_LIBS
> <https://www.gnu.org/software/autoconf/manual/autoconf.html#index-AC_005fSEARCH_005fLIBS-344>
> .
>
> I assume from the discussion above that this issue should be closed; feel
> free to re-open it, if incorrect.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/open-mpi/ompi/issues/1827#issuecomment-229400130>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHL5PkkYoUKJNYOtZtdk3rDwAZ5C96k_ks5qQpRdgaJpZM4JAy3C>
> .
>


-- 
-----
Best regards, Artem Polyakov
(Mobile mail)

**Comment by jsquyres** [comment]
Check the Autoconf docs I linked to.

**Comment by artpol84** [comment]
Thanks!
I saw that manual today but looks like wasnt carefully reading :).

среда, 29 июня 2016 г. пользователь Jeff Squyres написал:

> Check the Autoconf docs I linked to.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/open-mpi/ompi/issues/1827#issuecomment-229406906>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHL5Ptjz2o75hIR3Heq5IcDmQsffNvx0ks5qQpmMgaJpZM4JAy3C>
> .
>


-- 
-----
Best regards, Artem Polyakov
(Mobile mail)

**Comment by jsquyres** [comment]
😄  IIRC, the rationale for testing without the library is to see if it's a system-default-linked library.  I.e., you don't need to specify `-lfoo` because the system does it for you automatically (kinda like `-lc`).

**Comment by artpol84** [comment]
I figured that yout, yes. Thank's once again!

2016-06-29 22:57 GMT+06:00 Jeff Squyres <notifications@github.com>:

> 😄 IIRC, the rationale for testing without the library is to see if it's
> a system-default-linked library. I.e., you don't need to specify -lfoo
> because the system does it for you automatically (kinda like -lc).
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/open-mpi/ompi/issues/1827#issuecomment-229419682>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHL5PntEnDyhbqBBmED0uA2L89o59qqCks5qQqPmgaJpZM4JAy3C>
> .
>



-- 
С Уважением, Поляков Артем Юрьевич
Best regards, Artem Y. Polyakov
