### ISSUE TITLE
Update LAMA mapper to handle inverted topologies

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#183]
(In [30086]) Init variable to avoid infinite loop issues with PGI compilers

Thanks to Tetsuya Mishima for identifying the problem and providing the patch!

cmr=v1.7.4:reviewer=jsquyres:subject=Fix LAMA mapper for PGI compilers

jsquyres, please review this CMR. Thanks.

**Comment by rhc54** [comment]
Removed due to staleness
