### ISSUE TITLE
Incorrect XRC atomic setup

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1839]
Per http://www.open-mpi.org/community/lists/devel/2016/07/19144.php, Håkon Bugge notes:

> To me, it looks like Open MPI in xoob_send_qp_connect() attempts to set the max_dest_rd_atomic attribute in the transition from INIT to RTR, even for XRC_INI QPs. This is illegal, according to the ib_modify_qp_is_ok() function in ib_core. In particular, IBV_QP_MAX_DEST_RD_ATOMIC is not part of either the required nor optional set of attributes for this transition for XRC_INI QPs.

Can someone with knowledge of the openib BTL and/or XRC please check this?  Thanks.

**Comment by artpol84** [comment]
@jsquyres I don't think we will find the resources to address this as we are focusing on UCX.
I recall that there was a talk about removing openib. Can we close it?

**Comment by jsquyres** [comment]
Yes, go ahead and apply the wontfix label and close this.
