### ISSUE TITLE
Make rdmacm CPC disqualify itself if MPI_THREAD_MULTIPLE

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1848]
As discussed on today's webex, the rdmacm CPC in the openib BTL is not thread safe (it never has been).  The rdmacm CPC should disqualify itself (instead of failing in random ways) if MPI_THREAD_MULTIPLE is the thread level.

@jladd-mlnx @artpol84 @larrystevenwise @bharatpotnuri Could one of you do this?  I'm assuming that this is easier / faster than actually making the rdmacm CPC thread safe.

Thanks!

**Comment by jsquyres** [comment]
BTW, this is different than #1841, which is about fixing the rdmacm CPC to be thread safe -- I filed this issue as a quick workaround so that we already get orderly failures/aborts rather than undefined behavior.

**Comment by larrystevenwise** [comment]
@jsquyres - should the openib/rdmacm CPC use global var 'ompi_mpi_thread_multiple' to decide if it will participate in connections?

**Comment by jsquyres** [comment]
Yes, `ompi_mpi_thread_multiple` will only be `true` if MPI_INIT[_THREAD] was setup with MPI_THREAD_MULTIPLE.

**Comment by larrystevenwise** [comment]
Something like this (untested)?

<pre>
diff --git a/opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c b/opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c
index b675748..3d47708 100644
--- a/opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c
+++ b/opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c
@@ -2000,6 +2000,11 @@ static int rdmacm_component_query(mca_btl_openib_module_t *openib_btl, opal_btl_
     struct sockaddr_in sin;
 #endif

+    if (ompi_mpi_thread_multiple) {
+       rc = OPAL_ERR_NOT_SUPPORTED;
+       goto out;
+    }
+
     /* RDMACM is not supported if we have any XRC QPs */
     if (mca_btl_openib_component.num_xrc_qps > 0) {
         BTL_VERBOSE(("rdmacm CPC not supported with XRC receive queues, please try xoob CPC; skipped on %s:%d",
</pre>

**Comment by jsquyres** [comment]
Github pro tip: you can add "patch" after the triple-single-ticks in the Github markdown so that github knows to syntax hilight that verbatim code as a diff.  😄   (github understands lots of tokens to tell it how to syntax hilight verbatim blocks, like "c", "sh", "fortran", ...etc.).

Yes, probably something like that...?  I haven't looked at that code in years, though, and don't know offhand what the caller will do with ERR_NOT_SUPPORTED.  It *may* be useful to add a `BTL_VERBOSE` explaining why it won't be used, similar to the XRC stuff below it.

**Comment by larrystevenwise** [comment]
```patch
diff --git a/opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c b/opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c
index b675748..4c79415 100644
--- a/opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c
+++ b/opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c
@@ -2000,6 +2000,14 @@ static int rdmacm_component_query(mca_btl_openib_module_t *openib_btl, opal_btl_
     struct sockaddr_in sin;
 #endif

+    if (ompi_mpi_thread_multiple) {
+        BTL_VERBOSE(("rdmacm CPC not supported ompi_mpi_thread_multiple; skipped on %s:%d",
+                     ibv_get_device_name(openib_btl->device->ib_dev),
+                     openib_btl->port_num));
+       rc = OPAL_ERR_NOT_SUPPORTED;
+       goto out;
+    }
+
     /* RDMACM is not supported if we have any XRC QPs */
     if (mca_btl_openib_component.num_xrc_qps > 0) {
         BTL_VERBOSE(("rdmacm CPC not supported with XRC receive queues, please try xoob CPC; skipped on %s:%d",

**Comment by larrystevenwise** [comment]
This compiles.  @bharatpotnuri, can you please verify this works and provide a PR for it?
```patch
diff --git a/opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c b/opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c
index b675748..652cd45 100644
--- a/opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c
+++ b/opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c
@@ -63,6 +63,8 @@
 #include "btl_openib_ip.h"
 #include "btl_openib_ini.h"

+#include "ompi/runtime/mpiruntime.h"
+
 #if BTL_OPENIB_RDMACM_IB_ADDR
 #include <stdio.h>
 #include <netinet/in.h>
@@ -2000,6 +2002,14 @@ static int rdmacm_component_query(mca_btl_openib_module_t *openib_btl, opal_btl_
     struct sockaddr_in sin;
 #endif

+    if (ompi_mpi_thread_multiple) {
+        BTL_VERBOSE(("rdmacm CPC not supported with MPI_THREAD_MULTIPLE; skipped on %s:%d",
+                     ibv_get_device_name(openib_btl->device->ib_dev),
+                     openib_btl->port_num));
+        rc = OPAL_ERR_NOT_SUPPORTED;
+        goto out;
+    }
+
     /* RDMACM is not supported if we have any XRC QPs */
     if (mca_btl_openib_component.num_xrc_qps > 0) {
         BTL_VERBOSE(("rdmacm CPC not supported with XRC receive queues, please try xoob CPC; skipped on %s:%d",

**Comment by larrystevenwise** [comment]
@jsquyres - dumb question:  How does one enable or disable MPI_THREAD_MULTIPLE thread level?  I thought it was a 'configure' option, but I don't see it.  I see env var OMPI_MPI_THREAD_LEVEL though. Is that the proper way? thanks!

**Comment by jsquyres** [comment]
@larrystevenwise The env variable is an easy way (and is OMPI-specific, obviously).  The normal way is to call MPI_INIT_THREAD (instead of MPI_INIT) to initialize MPI in your program.  MPI_INIT doesn't take thread-level arguments, but MPI_INIT_THREAD does.

You probably want to use one of the explicitly threaded tests, though.  The issue isn't just running a single-threaded program when run with OMPI_MPI_THREAD_LEVEL set to use MPI_THREAD_MULTIPLE (that'll just initialize all the locks and whatnot in the code paths, but it doesn't magically make multiple threads / asynchronous progress).  Instead, you want a test that initializes itself to MPI_THREAD_MULTIPLE and then has multiple threads invoking MPI calls simultaneously.

You might want to run the latency_th test or overlap test in the ompi-tests/thread-tests-1.1 dir.  Run it with, say, 8 threads per proc.  Make sure you `--bind-to none` (per https://github.com/open-mpi/ompi/pull/1840#issuecomment-230838961).  Run this a bazillion times and see if you can get the rdmacm CPC to fail.

...come to think of it, the problems we've been seeing in Jenkins *might* be due to the issues I cited on that comment...?  Either way, the rdmacm CPC has not been really tested / stressed in a true multi-threaded scenario, so it would be good to a) verify if it works or not, and b) if not, fix it.

Did that all make sense?

**Comment by larrystevenwise** [comment]
@jsquyres - Yes. This makes sense.  I was concerned that single-threaded mpi applications would not run by default with ompi-2.x over iwarp because the rdmacm cpc would be skipped.  But that isn't the case.  Good! :)

**Comment by bharatpotnuri** [comment]
I am able to reproduce the issue with osu_latency_mt test for rdmacm CPC.
Here is the command and failure:
```
[root@maneybhanjang ~]# /usr/mpi/gcc/openmpi-master/bin/mpirun --allow-run-as-root --hostfile /root/mpd.hosts --np 2 --prefix /usr/mpi/gcc/openmpi-master/ --map-by node --bind-to none --mca btl_openib_cpc_include rdmacm --mca btl openib,sm,self /usr/mpi/gcc/openmpi-master/tests/OSU/osu_latency_mt
--------------------------------------------------------------------------
No OpenFabrics connection schemes reported that they were able to be
used on a specific port.  As such, the openib BTL (OpenFabrics
support) will be disabled for this port.

  Local host:           maneybhanjang
  Local device:         mlx4_0
  Local port:           1
  CPCs attempted:       rdmacm
--------------------------------------------------------------------------
# OSU MPI Multi-threaded Latency Test v5.0
# Size          Latency (us)
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[57678,1],0]) is on host: maneybhanjang
  Process 2 ([[57678,1],1]) is on host: 10.193.184.162
  BTLs attempted: self

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
[maneybhanjang:26657] *** An error occurred in MPI_Barrier
[maneybhanjang:26657] *** reported by process [47325729652737,47321949667328]
[maneybhanjang:26657] *** on communicator MPI_COMM_WORLD
[maneybhanjang:26657] *** MPI_ERR_INTERN: internal error
[maneybhanjang:26657] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[maneybhanjang:26657] ***    and potentially your MPI job)
[maneybhanjang.blr.asicdesigners.com:26618] 1 more process has sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
[maneybhanjang.blr.asicdesigners.com:26618] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```
Like @jsquyres said, osu_latency_mt.c uses MPI_INIT_THREAD to MPI to initialize. Will update with more details.

**Comment by bharatpotnuri** [comment]
Added PR https://github.com/open-mpi/ompi/pull/1861 for disqualifying rdmacm for MPI_THREAD_MULTIPLE.

**Comment by hjelmn** [comment]
@bharatpotnuri That error is due to not having a per-peer QP. You need to add one for rdmacm to function.

**Comment by bharatpotnuri** [comment]
@hjelmn I tried the test with Chelsio adapter too and the error is same. Here is the error trace when run with `--mca btl_openib_receive_queues P,65536,256,192,128`:
*For iwarp the current HW does not support SRQ, Hence used only per-peer QP.

```
[root@maneybhanjang ~]# /usr/mpi/gcc/openmpi-master/bin/mpirun --allow-run-as-root --hostfile /root/mpd.hosts --np 2 --prefix /usr/mpi/gcc/openmpi-master/ --map-by node --bind-to none --mca btl_openib_cpc_include rdmacm --report-state-on-timeout --get-stack-traces -mca btl_openib_receive_queues P,65536,256,192,128 --timeout 600 --mca btl openib,sm,self /usr/mpi/gcc/openmpi-master/tests/OSU/osu_latency_mt
# OSU MPI Multi-threaded Latency Test v5.0
# Size          Latency (us)
opal_mutex_lock(): Resource deadlock avoided
[maneybhanjang:17504] *** Process received signal ***
[maneybhanjang:17504] Signal: Aborted (6)
[maneybhanjang:17504] Signal code:  (-6)
[maneybhanjang:17504] [ 0] /lib64/libpthread.so.0[0x3aea40f710]
[maneybhanjang:17504] [ 1] /lib64/libc.so.6(gsignal+0x35)[0x3aea032625]
[maneybhanjang:17504] [ 2] /lib64/libc.so.6(abort+0x175)[0x3aea033e05]
[maneybhanjang:17504] [ 3] /usr/mpi/gcc/openmpi-master/lib/openmpi/mca_btl_openib.so(+0x10306)[0x2b51ca8dd306]
[maneybhanjang:17504] [ 4] /usr/mpi/gcc/openmpi-master/lib/openmpi/mca_btl_openib.so(+0x12f29)[0x2b51ca8dff29]
[maneybhanjang:17504] [ 5] /usr/mpi/gcc/openmpi-master/lib/openmpi/mca_btl_openib.so(+0x1a8e8)[0x2b51ca8e78e8]
[maneybhanjang:17504] [ 6] /usr/mpi/gcc/openmpi-master/lib/openmpi/mca_btl_openib.so(+0x1b6a1)[0x2b51ca8e86a1]
[maneybhanjang:17504] [ 7] /usr/mpi/gcc/openmpi-master/lib/openmpi/mca_btl_openib.so(+0x1bcb6)[0x2b51ca8e8cb6]
[maneybhanjang:17504] [ 8] /usr/mpi/gcc/openmpi-master/lib/openmpi/mca_btl_openib.so(+0x1c16a)[0x2b51ca8e916a]
[maneybhanjang:17504] [ 9] /usr/mpi/gcc/openmpi-master/lib/openmpi/mca_btl_openib.so(+0x1c209)[0x2b51ca8e9209]
[maneybhanjang:17504] [10] /usr/mpi/gcc/openmpi-master/lib/libopen-pal.so.0(opal_progress+0xac)[0x2b51be5f0726]
[maneybhanjang:17504] [11] /usr/mpi/gcc/openmpi-master/lib/libopen-pal.so.0(sync_wait_mt+0x152)[0x2b51be5f8d3e]
[maneybhanjang:17504] [12] /usr/mpi/gcc/openmpi-master/lib/openmpi/mca_pml_ob1.so(+0xf35a)[0x2b51cc69035a]
[maneybhanjang:17504] [13] /usr/mpi/gcc/openmpi-master/lib/openmpi/mca_pml_ob1.so(mca_pml_ob1_send+0x58d)[0x2b51cc6925f3]
[maneybhanjang:17504] [14] /usr/mpi/gcc/openmpi-master/lib/libmpi.so.0(+0x10005d)[0x2b51bdfee05d]
[maneybhanjang:17504] [15] /usr/mpi/gcc/openmpi-master/lib/libmpi.so.0(ompi_coll_base_barrier_intra_two_procs+0x81)[0x2b51bdfee790]
[maneybhanjang:17504] [16] /usr/mpi/gcc/openmpi-master/lib/openmpi/mca_coll_tuned.so(ompi_coll_tuned_barrier_intra_dec_fixed+0x57)[0x2b51ce262ef0]
[maneybhanjang:17504] [17] /usr/mpi/gcc/openmpi-master/lib/libmpi.so.0(MPI_Barrier+0x103)[0x2b51bdf69f2d]
[maneybhanjang:17504] [18] /usr/mpi/gcc/openmpi-master/tests/OSU/osu_latency_mt[0x4010ec]
[maneybhanjang:17504] [19] /lib64/libpthread.so.0[0x3aea4079d1]
[maneybhanjang:17504] [20] /lib64/libc.so.6(clone+0x6d)[0x3aea0e89dd]
[maneybhanjang:17504] *** End of error message ***
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node maneybhanjang exited on signal 6 (Aborted).
--------------------------------------------------------------------------

```

**Comment by hjelmn** [comment]
@bharatpotnuri I fixed the deadlock on master. Are you testing an older hash? See: 01d6da31af4345e752d836c41af82012f8b6c3c9 and 960fcd292c2fc9a05acb9dd003ba9dfc27e8c1eb.

**Comment by bharatpotnuri** [comment]
@hjelmn I am using the latest code pulled from master. Commits  01d6da3 and 960fcd2 exist in my repo.
Apparently this could be another deadlock issue with multi thread(issue only seen with multi thread tests). When run with gdb I see the test proceeding for a little extent(runs successfully once in a while) and then hits a deadlock.  I did not get much useful info when run under gdb. Will update with findings.

**Comment by jsquyres** [comment]
@bharatpotnuri Any updates?

**Comment by larrystevenwise** [comment]
@bharatpotnuri is out until tomorrow.

**Comment by jsquyres** [comment]
@larrystevenwise We're likely to push this to v2.0.2 unless some kind of conclusion can be reached in the immanent future.

**Comment by larrystevenwise** [comment]
@jsquyres please push this to v2.0.2.  I'll talk with Bharat tomorrow to see where we are at, but don't hold up the release.  Thanks.

**Comment by jsquyres** [comment]
Cool; thanks.

**Comment by bharatpotnuri** [comment]
@jsquyres Sorry, I was stuck with someother work, couldn't look into this one until now. Will soon update the pull request #1861 by the release.

**Comment by bharatpotnuri** [comment]
With commit 9a08fb7, PR #1861 tests good for disqualifying rdmacm for MPI_THREAD_MULTIPLE.

**Comment by jsquyres** [comment]
Re-opening to track this for v2.0.2 and v2.1.0.

**Comment by jsquyres** [comment]
This is now done.
