### ISSUE TITLE
autogen.pl --no-ompi is broken

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1884]
Looks like dc5adc5a91b4682a8e0de492350745eb01fa37d0 broke `./autogen.pl --no-ompi` (see http://www.open-mpi.org/community/lists/devel/2016/07/19243.php).

@ggouaillardet This was your commit -- can you have a look?  I'm guessing that this will also affect the v2.0.1 PR https://github.com/open-mpi/ompi-release/pull/1215.

**Comment by rhc54** [comment]
thanks!!

**Comment by ggouaillardet** [comment]
@rhc54 you are welcome :-)

@jsquyres what about extending Cisco mtt so it
```./autogen.sh --no-oshmem```
```./autogen.sh --no-ompi```
```./autogen.sh --no-orte```
and build/install (i am not sure test can be run if only opal is built)

this is not the first time this kind of error is detected quite some time after ompi was broken.

**Comment by rhc54** [comment]
@ggouaillardet I apologize - I had to revert this commit in order to finish some work on master. Please resubmit when the problem has been fixed.

**Comment by ggouaillardet** [comment]
my bad, i will test that thouroughly on #1887
