### ISSUE TITLE
opal_fifo test failing on master at IBM / MTT

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1893]
The `opal_fifo`test is failing in IBM's MTT on master: https://mtt.open-mpi.org/index.php?do_redir=2335

The compiler appears to be gcc 4.8.2 on an Ubuntu-based 32 bit platform (I don't know if it's x86 or POWER).

@jjhursey Can you provide more detail (e.g., the output log and/or stack trace)?

**Comment by hjelmn** [comment]
This might be related to the new builtin atomics work. Be interesting to know if it fails with --disable-builtin-atomis

**Comment by jjhursey** [comment]
Issue #2966 has more detail and a valid MTT link. So I'm going to close this one and move the discussion over there.
