### ISSUE TITLE
Allow alternate IOF wireup strategies via orterun

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#19]
Currently, the urm RMGR component has the following IOF setup
hard-coded in it:
- vpid 0 gets stdin forwarded from orterun
- orterun's stdout/stderr receives the stdout/stderr from all processes

orterun should grow some options to allow alternate IOF wireup
schemes.  Some potentially worthwhile schemes include:
- Replicating stdin to all processes in the job
- Display stdout and/or stderr only from selected processes

To avoid scalability problems, this wireup scheme should be encoded in
the app context or some other data that is xcast out to all the
orteds (and yes, this is fine that this is orted-specific
functionality) so that acting on the IOF wirteup strategy does not
require any additional control messages in IOF -- if all processes in
the job ''know'' what the wireup strategy is, they can just setup
local data structures to reflect that and be done (assuming that
everyone else is also doing the same).

This would also allow fixing a minor code discrepancy in the ODLS
default component.  Currently, it publishes stdin (if relevant),
stdout, and stderr.  But it only ''unpublishes'' stdin.  The reason
for this is scalibility issues: since stdin is only sent to one
process, publishing and unpublishing it only requires one IOF control
message (each).  Publishing SOURCE stdout/stderr is actually a no-op
because the proxy ''always'' sends all SOURCE fragments to the svc, so
publishing it is not required.  Unpublishing SOURCE endpoints ''does''
require an IOF control message, however, but since the HNP is either
about to or in the process of shutting down when we would have
unpublished, the resource leak that we cause by not unpublishing is
short-lived, and therefore it isn't done (to avoid sending N*2
unpublish requests to the SVC).

**Comment by rhc54** [comment]
We can safely say that all that will be done, has been done
