### ISSUE TITLE
Make ROMIO work with PVFS2 in the 1.6 series

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#191]
this patch fixes a compilation problem with ROMIO on PVFS2 for OpenMPI, and resets two function pointers to ensure correctness of the data. Patch is attached.

**Comment by rhc54** [comment]
@edgargabriel Is this still true?? Can we close it?

**Comment by edgargabriel** [comment]
yes. I honestly don't remember whether it was fixed in 1.6, but it is working now.
