### ISSUE TITLE
bug in XRC that leads to hang of heavy collective operations like Alltoall

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#192]
The attached test isend_txrc.c demonstrates the problem. The bug is intermittent so run_loop.sh scripts may be used.

We reproduced the hang on Alltoall with large core count. The test isend_txrc.c uses low number of XRC buffers to catch this error.

The problem appears on progress of no_wqe_pending frags because sd_wqe is common for several endpoints (that relates to same node for lcl_qp) and sd_wqe may be updated not for the same endpoint as no_wqe_pending_frags belongs to.

The solution is to move no_wqe_pending_frags field from struct mca_btl_openib_endpoint_qp_t to struct mca_btl_openib_qp_t :

```c
typedef struct mca_btl_openib_qp_t {
    struct ibv_qp *lcl_qp;
    uint32_t lcl_psn;
    int32_t  sd_wqe;      /**< number of available send wqe entries */
    int32_t  sd_wqe_inflight;
    int wqe_count;
    int users;

#if 1
    opal_list_t no_wqe_pending_frags[2]; /**< put fragments here if there is no wqe available  */

#endif

    opal_mutex_t lock;
} mca_btl_openib_qp_t;


typedef struct mca_btl_openib_endpoint_qp_t  {
    mca_btl_openib_qp_t *qp;
    opal_list_t no_credits_pending_frags[2]; /**< put fragment here if there is no credits
                                     available */

#if 0
    opal_list_t no_wqe_pending_frags[2]; /**< put fragments here if there is no wqe available  */
#endif 

    int32_t  rd_credit_send_lock;  /**< Lock credit send fragment */
    mca_btl_openib_send_control_frag_t *credit_frag;
    size_t ib_inline_max;          /**< max size of inline send*/
    union {
        mca_btl_openib_endpoint_srq_qp_t srq_qp;
        mca_btl_openib_endpoint_pp_qp_t pp_qp;
    } u;
} mca_btl_openib_endpoint_qp_t;
```

And revise OpenIB BTL code that have references to no_wqe_pending_frags lists.

**Comment by jsquyres** [comment]
Who will look at this?

**Comment by rhc54** [comment]
Per Mellanox, this can be closed. Any further work will be done on a separate new ticket.
