### ISSUE TITLE
Symbol versioning for OpenMPI

### ISSUE THREAD

**Issue by amckinstry** [open-mpi/ompi#1956]
Hi,
I've implemented an initial patch for symbol versioning in OpenMPI as discussed originally in #1906.

**Comment by amckinstry** [comment]
Document describing use of symbol versioning:

[versioning-in-openmpi.docx](https://github.com/open-mpi/ompi/files/415532/versioning-in-openmpi.docx)

**Comment by jsquyres** [comment]
Cross reference: the corresponding PR is #1955.

**Comment by hppritcha** [comment]
Kick down the road to 3.x

**Comment by bwbarrett** [comment]
The PR was closed with no follow up, so I'm going to close this issue.  Please re-open if you think there's more action we can take.
