### ISSUE TITLE
Update ROMIO?

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1970]
I got a comment from a user:

> Regarding ROMIO support, I downloaded the latest OpenMPI version (v2.0.1), and it appears to be based on an older version of ROMIO (from MPICH 3.1.4).
> 
> The more recent version of ROMIO in MPICH 3.2 (circa summer 2015) has support for newer file systems -- in particular newer versions of Panfs (with support for a RAID6 variant) that are showing up on users' systems.
> 
> Are there any near-term plans to upgrade ROMIO in OpenMPI v2.x?

I know our primary support for IO is OMPIO in v2.x.  Is it worth upgrading ROMIO?  Or does OMPI support the new Panfs + RAID6 stuff that the user mentions?

@edgargabriel @ggouaillardet

**Comment by edgargabriel** [comment]
RAID 6 is below the file system level and typically not exposed to the user, but a characteristic of the internal storage architecture. It should not be something that the user / MPI I/O has to worry about. Support for new PanFS versions might be different. I know that ROMO has a panfs adio component, but since I do not have access  to a panasas storage system, I have absolutely no experience with that.

That being said, as with virtually all POSIX compliant file systems, the generic posix./ufs components should work, they just might not be able to take advantage of certain file system specific optimizations.

**Comment by ggouaillardet** [comment]
@edgargabriel i haven't been using panasas for a while.
iirc, they can do RAID at the file level (vs the block level) so i am (just) guessing "RAID6 variant" support means "file level RAID can be set by MPI-IO via hints"
if there is some interest, i can try to upgrade to romio from mpich 3.2 but not in the near term.
iirc, it could support non blocking operations ... assuming we can plug this to Open MPI Grequest.

**Comment by ggouaillardet** [comment]
fwiw, i started that with mpich 3.2b1 and then stopped because we decided it would not be part of v2.x anyway. my branch is still available at https://github.com/ggouaillardet/ompi/commits/refresh/romio32b1

that should be pretty easy to do it again with 3.2

**Comment by jsquyres** [comment]
@hppritcha Do you have thoughts on this?  My $0.02: if we do it, it would probably be a candidate for Open MPI v2.2.

**Comment by edgargabriel** [comment]
another option might be to try to bring in just an update for the panfs adio, not entirely sure whether that's feasible though.

**Comment by ggouaillardet** [comment]
@edgargabriel the changes look miminal (the open callback has been rewritten for the new panfs interface)

i made a patch that can be downloaded at https://github.com/ggouaillardet/ompi/commit/a7cfe9f0bab9625aff31f5151c1b4d5c9d984879.patch and i have no way to test it (so i am not even sure it compiles)

@jsquyres would you mind asking your user to give it a try ?

**Comment by hppritcha** [comment]
Moving this to v3.x milestone.

**Comment by jjhursey** [comment]
It's not a full update, but I filed a PR to work around 4 known missing MPI operations in ROMIO 3.1.4 (they are fully implemented in the 3.2 and later series).
 *    https://github.com/open-mpi/ompi/pull/3688

**Comment by hppritcha** [comment]
closed via #4520
