### ISSUE TITLE
Hargrove-inspired fixes:

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2000]
1. Update README to no longer support OS X 10.6 and 10.7
2. Update README to clarify Oracle Studio versions (perhaps 12.5 only?)
3. @rhc54 to update PMIx to fix a pair of issues:
  * https://www.mail-archive.com/devel@lists.open-mpi.org/msg19376.html: This is technically an OS X 10.6 problem, and we therefore don't care, but it's fixed in the pending PMIx update
  * https://www.mail-archive.com/devel@lists.open-mpi.org/msg19378.html: Solaris fix
4. https://www.mail-archive.com/devel@lists.open-mpi.org/msg19382.html: @hjelmn is looking into the dlopen test failure with XLC -- we think it may represent a larger patcher failure (and was reported in https://github.com/open-mpi/ompi/issues/1854).

Thanks to @PHHargrove for reporting the issues.

**Comment by PHHargrove** [comment]
> Update README to no longer support OS X 10.6 and 10.7

Did I miss something?
Why are these being dropped and why am I credited with "inspiring" this?

> https://www.mail-archive.com/devel@lists.open-mpi.org/msg19376.html: This is technically an OS X 10.6 problem, and we therefore don't care, but it's fixed in the pending PMIx update

"Technically" it is a problem for any non-glibc platform which predates the 2008 revision of POSIX.1 in which strnlen() was first specified. That likely includes Solaris 10 and older releases of the BSD OSes (I only test the latest).

**Comment by jsquyres** [comment]
OS X 10.6 and 10.7 are ancient.  OS X support is largely for developers on laptops, and on the webex today, we decided that it is likely not that important to support such old versions of OS X.

You're credited because you are The Hargrove!  😄   You inspired the discussion on the webex today because you raised these issues.

Technically: ok.  It's getting fixed anyway.

**Comment by jsquyres** [comment]
1 through 3 are in for v2.0.1.  4 is going in to v2.0.2 (no PR yet).
