### ISSUE TITLE
Libevent warnings

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#2004]
If a process abnormally terminates, we get a warning out of libevent (the file descriptor varies):

```
[warn] Epoll ADD(1) on fd xx failed. Old events were 0; read change was 1 (add); write change was 0 (none): Operation not permitted. 
```

Similar report was filed a long time ago: https://github.com/open-mpi/ompi/issues/341

Don't know if they are related, but worth noting. I'm told we also get this message sometimes when normally terminating as well, so it's possibly a race condition.

@jladd-mlnx @hjelmn @ggouaillardet Just setting this up to track the problem until someone has time to investigate.

**Comment by jjhursey** [comment]
@rhc54 this was fixed in PR #2223, right? Did it get PR'ed to v2.x?

**Comment by rhc54** [comment]
I see that the branch was already committed to v2.0.x, but apparently not to v2.x - will do so now

**Comment by rhc54** [comment]
Filed as https://github.com/open-mpi/ompi/pull/2321 - assigned to you to review
