### ISSUE TITLE
--disable-mpi-io broken on master

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2009]
@edgargabriel It looks like some recent OMPIO changes on master broke `--disable-mpi-io`.  Can you have a look?

https://mtt.open-mpi.org/index.php?do_redir=2344

**Comment by edgargabriel** [comment]
I thought I fixed that a while back, but there seems to be an issue when using --disable-dlopen. Will look into that. Can confirm and reproduce the problem.
