### ISSUE TITLE
Problem with MPI dynamic window support

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#2012]
Per discussion in an email thread on the users group, 
there appears to be a regression in master/2.x release with
handling of MPI dynamic windows.

The reproducer is in the email.

The error goes away if the OSC rdma component is not used.
@hjelmn 

https://mail-archive.com/users@lists.open-mpi.org/msg29851.html

**Comment by hjelmn** [comment]
Will take a look.

**Comment by hjelmn** [comment]
I can reproduce the issue. Looks like the insertion code is messing up. Should have a fix shortly.
