### ISSUE TITLE
btl/scif : MPI_Comm_spawn hangs

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#203]
from the ibm test suite :

```mpirun -np 2 --mca btl tcp,scif,self dynamic/intercomm_create```

hangs in MPI_Comm_spawn()

if the scif btl is removed, then it does not hang.

is the scif btl supposed to work ?
if no, should it discard itself ?

/* for example the sm btl does not seem to support this :

```mpirun -np 2 --mca btl sm,self dynamic/intercomm_create```

fails with an error message :

```At least one pair of MPI processes are unable to reach each other for MPI communications [...]```
*/

**Comment by jsquyres** [comment]
@hjelmn Do you think you'll be able to fix this for 1.8.5?

**Comment by hppritcha** [comment]
I suggest this be closed as wont fix.
