### ISSUE TITLE
v2.0.x: Open BSD 6.0 and patcher problems

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#2049]
As reported by Paul H., Open BSD 6.0 disallows the patcher code's `mprotect` call.

See https://mail-archive.com/devel@lists.open-mpi.org/msg19527.html

This impacts master and v2.x

**Comment by PHHargrove** [comment]
FYI:

I have confirmed w/ the released 2.0.1 tarball that configuring with `--enable-mca-no-build=patcher` is sufficient to avoid the problem  I can pass `make check` and run `ring_c`, on both i386 and amd64 systems running OpenBSD-6.0

I suggest that a *possible* solution is to have the configure probe for the patcher framework attempt an `mprotect()` call with `prot = PROT_EXEC|PROT_READ|PROT_WRITE`.  Then the problematic code would be automatically disqualified not only on OpenBSD-6, but also on any future OSes (including Linux and Mac OS X) with strong "W^X" policies.
 
-Paul

**Comment by jsquyres** [comment]
Per the call today, @artpol84 is going to check to see if Mellanox cares about Open BSD.

**Comment by hppritcha** [comment]
Mellanox does not care about Open BSD - per discussion devel telecon

**Comment by jsquyres** [comment]
@hjelmn Will add some kind of disabling for the patcher on Open BSF 6.0 systems.

**Comment by jsquyres** [comment]
@hjelmn says he can work on this next week.

**Comment by hppritcha** [comment]
we'd like this fixed in 2.0.2 but not a blocker.

**Comment by PHHargrove** [comment]
Current (2.0.2rc3) it is not possible to run on OpenBSD-6 unless one configures with `--enable-mca-no-build=patcher`.
Would it be appropriate to document this in README for v2.0.2?

**Comment by hppritcha** [comment]
done, PR #2687
