### ISSUE TITLE
iallgather using coll ml is giving wrong answers

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#205]
I have noticed on the trunk that the ibm/collective iallgather and iallgather_in_place are getting wrong answers.  I pointed this out on the mailing list as well.

http://www.open-mpi.org/community/lists/devel/2014/06/14989.php

If we turn on off the allgather support in coll ml, then the test passes.  I do not see any problems with Open MPI 1.8.  This is only in the trunk.

[rvandevaart@drossetti-ivy2 collective]$ mpirun --mca coll ml,basic,libnbc,inter --mca btl self,sm,tcp -np 3 -host drossetti-ivy2,drossetti-ivy3  iallgather
[**ERROR**]: MPI_COMM_WORLD rank 0, file iallgather.c:77:
bad answer (0) at index 1 of 3 (should be 1)
[**ERROR**]: MPI_COMM_WORLD rank 1, file iallgather.c:77:
bad answer (0) at index 1 of 3 (should be 1)
[**ERROR**]: MPI_COMM_WORLD rank 2, file iallgather.c:77:
## bad answer (0) at index 1 of 3 (should be 1)

MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
## exactly when Open MPI kills them.

[rvandevaart@drossetti-ivy2 collective]$ mpirun --mca coll_ml_disable_allgather 1 --mca coll ml,basic,libnbc,inter --mca btl self,sm,tcp -np 3 -host drossetti-ivy2,drossetti-ivy3  iallgather
[rvandevaart@drossetti-ivy2 collective]$

**Comment by jsquyres** [comment]
As of June 2015, coll ml is disabled by default in v1.8, v1.10, v2.x.  @shamisp and @manjugv say that they are actively working on coll ml again (per email on 23 June 2015), so we'll mark this one for the v2.x series.

**Comment by hppritcha** [comment]
@hjelmn can this be closed?

**Comment by hppritcha** [comment]
Hmmm remembered we don't support coll ML currently.  Closing.
