### ISSUE TITLE
pkgincludedir not defined in .pc files

### ISSUE THREAD

**Issue by amckinstry** [open-mpi/ompi#2069]
There is a regression in 2.0* packages; the variable ${pkgincludedir} is used in some .pc files (mpi-fort specifically), leading to failures:

$ pkg-config mpi-fort --libs
Variable 'pkgincludedir' not defined in '/usr/lib/pkgconfig/mpi-fort.pc'

Removing the clauses from Cflags that have -I${pkgincludedir}/.. and it works.

**Comment by ggouaillardet** [comment]
@amckinstry as fas ar i am concerned, the pc file is called ```ompi-fort.pc``` and __not__ ```mpi-fort.pc```

can you please double check ```/usr/lib/pkgconfig/mpi-fort.pc``` is an Open MPI file ?
if yes, can you please post your ```mpi-fort.pc``` of both ```v1.10``` and ```v2.x``` and you ```configure``` command line ?

**Comment by amckinstry** [comment]
@ggouaillardet You are correct; on Debian mpi-fort.pc is an alias to ompi-fort.pc (a similar symlink is used for mpich if it is installed instead).

The underlying file is ompi-fort.pc which has the issue. 

./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --with-libfabric --enable-mpi-thread-multiple --disable-silent-rules --enable-mpi-cxx --with-hwloc=/usr/ --with-libltdl=/usr/ --with-devel-headers --with-slurm --with-sge --without-tm --enable-heterogeneous --disable-vt --sysconfdir=/etc/openmpi --libdir=${prefix}/lib/openmpi/lib --includedir=${prefix}/lib/openmpi/include

and ompi-fort.pc:

# Copyright (c) 2010 Cisco Systems, Inc.  All rights reserved.
#
Name: Open MPI
Description: Portable high-performance MPI implementation
Version: 2.0.1
URL: http://www.open-mpi.org/
#
prefix=/usr
exec_prefix=${prefix}
includedir=${prefix}/lib/openmpi/include
libdir=${prefix}/lib/openmpi/lib
#
# Note that -lopen-pal and all the EXTRA_LIBS are only necessary when
# static linking (they're pulled in by libopen-rte.so's implicit
# dependencies), so only list these in Libs.private.
#
Libs: -L${libdir} -L/usr//lib    -Wl,-rpath -Wl,/usr//lib -Wl,-rpath -Wl,${libdir} -Wl,--enable-new-dtags -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi
Libs.private: -lhwloc -lutil -lm
Cflags: -I${includedir} -I${includedir}/openmpi -I/usr//include -I${pkgincludedir}/opal/mca/event/libevent2022/libevent -I${pkgincludedir}/opal/mca/event/libevent2022/libevent/include   -pthread  -I${libdir}

**Comment by ggouaillardet** [comment]
i see

fwiw, that would have been hidden you had configure'd without the ```--with-devel-headers``` option
i will look at it from now

in the meantime, can you replace ```${pkgincludedir}``` with ```${{{includedir}}}``` ?
i think this is what went wrong in the first place

**Comment by amckinstry** [comment]
Thanks. I'm not sure which of our users or packages avail of these devel headers; from the logs, we've enabled this option in Debian since the beginning.

I have a workaround doing so with sed in the current release, thanks

**Comment by ggouaillardet** [comment]
that was not quite right, for the time being, it can be replaced with ```${{{includedir}}}/openmpi```

**Comment by jsquyres** [comment]
FWIW, there's some oddness going on in there, too -- I see it adding `-I/usr//include`, which is a Bad Idea.  Perhaps our path sanitization is not being applied correctly (or at all?) to the `*.pc` files...?

I'm also unable to replicate the error, even if I use `--with-devel-headers`.

**Comment by ggouaillardet** [comment]
open-mpi/ompi@628c730196d8fb566c142bf4e09f8f38c2406fb7 fixes the ```pkg-config``` error

```/usr//include``` and ```/usr//lib``` are in the path, please do note the double slash.

from the configure command line
```--with-hwloc=/usr/ --with-libltdl=/usr/```
please do also note the trailing slash in ```/usr/```

@amckinstry is there any reason not to simply use ```/usr``` here ?
if you use ```/usr```, do you still have ```-I/usr/include``` in the ```*.pc``` files ?

@jsquyres sanitization might correctly handle ```/usr/include``` but not ```/usr//include```, i will quickly double check this from now

**Comment by ggouaillardet** [comment]
@amckinstry a full fix for v2.x is available at https://patch-diff.githubusercontent.com/raw/open-mpi/ompi-release/pull/1372.patch

you do not need to update your Open MPI configure command line
e.g. keep  ```--with-hwloc=/usr/ --with-libltdl=/usr/```) so you can confirm there is no more
reference to ```/usr//include``` nor ```/usr//lib``` in the ```*.pc``` files

as a side notes, 
- since ```hwloc``` and ```libltdl``` are in /usr, you have the option to configure with ```--with-hwloc=external --with-libltdl=external```
- you also have the option to configure Open MPI with external ```libevent``` and ```pmix``` with
```--with-libevent=external --with-pmix=external``` (building an external ```pmix``` does require external ```hwloc``` and ```libevent```, and you might probably want to do that (i heard we received some requests from major distros to stop using embedded ```libevent```, ```hwloc``` and ```pmix``` since in some cases embedded and external libs can conflict)

**Comment by amckinstry** [comment]
@ggouaillardet We use prefix=/usr but includedir, libdir are different.
-L/usr//lib and -L/usr//lib (and -rpath) show up redundantly in the Libs and Includes.

prefix=/usr
exec_prefix=${prefix}
includedir=${prefix}/lib/openmpi/include
libdir=${prefix}/lib/openmpi/lib

Libs: -L${libdir} -L/usr//lib    -Wl,-rpath -Wl,/usr//lib -Wl,-rpath -Wl,${libdir} -Wl,--enable-new-dtags -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi
Libs.private: -lhwloc -lutil -lm
Cflags: -I${includedir} -I${includedir}/openmpi -I/usr//include   -pthread  -I${libdir}


I will test patch 1372 and external libevent, pmix but right now I'm busy with the transition to get openmpi2 into 'testing' for the next Debian release (openmpi and related release-critical errors are on the critical path; hence the (small) influx of openmpi bugs)

**Comment by ggouaillardet** [comment]
according to @jsquyres there should not be any /usr/include nor /usr/lib.
that happened because configury did not treat /usr/ like /usr, and this is fixed in the patch.
(or you can use /usr instead of /usr/ in your configure command line, so current configure handle it correctly)

if you use /opt instead, that might appear more than once, and even if this is harmless, that is unelegant. i will also double check that part.
