### ISSUE TITLE
Need PMIX1.2.1 for v2.1 release

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#2072]
This issue tracks getting PMIX2 in the v2.1 release.  The shared memory dstore is an important feature when trying to support 100's of MPI processes on a single node.

**Comment by hppritcha** [comment]
per discussion in Dallas this is being marked as a blocker.

**Comment by ggouaillardet** [comment]
btw, is this feature working on master now ?
It was disabled because it broke MPI_Comm_spawn, and i do not recall that has been fixed

**Comment by jsquyres** [comment]
Per discussion with @rhc54 this morning, there is still some development work occurring for PMIx 2.0.  After that is complete and merged to master, then it can be ported to v2.1.0.

**Comment by jjhursey** [comment]
@rhc54 Which branch of PMIx is tracking the PMIx 2.0 effort? I found three references to v2.x in the PMIx set of repos:
 * https://github.com/pmix/master/tree/v2.x
 * https://github.com/pmix/releases/tree/v2.x
 * https://github.com/pmix/releases/tree/release/v2.x

I would be interested in helping test.

**Comment by rhc54** [comment]
I've been shifting the release tree over to the master repo, just as we did for ompi. However, I can't say for certain that I have it fully up-to-date. I'll get things squared away tomorrow

**Comment by rhc54** [comment]
@jjhursey I have consolidated the PMIx release branches into the pmix/master repo, and all branches over there are now up-to-date.

**Comment by jjhursey** [comment]
Ref https://github.com/pmix/master/pull/141

Timeline (rough - certainly up for discussion):
 * Get that PR into PMIx `master`
 * Update Open MPI `master` **internal PMIx component**
 * Test via MTT
 * Once clean in MTT, then cherry-pick PR into PMIx `v2.x` branch
 * Roll a `v2.0rc1` release
 * Test the `v2.0.rc1` in Open MPI `master` with the **external PMIx component**
 * Iterate on any new issues that come up via MTT testing.
 * Once _stable_ then start working on a new internal v2.0 PMIx component on the Open MPI v2.1 branch
 * Test the v2.1 integration

**Comment by jjhursey** [comment]
I've opened PR #2286 to bring PMIx v1.2 into Open MPI v2.x. Once merged, that PR will fix this issue.

**Comment by jjhursey** [comment]
PR #2286 was merged in, but we are waiting for PMIx v1.2.1 release which includes some scalability improvements. See Issue #2744 for more details (maybe close this as a dup?)

**Comment by jsquyres** [comment]
This is now done.
