### ISSUE TITLE
Move r31982 to 1.8.3: MPI_Request_free and errors reporting

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#208]
Per discussion on the MPI Forum, if a request is released by the user using MPI_Request_free, and in the unlikely case there is an error on the corresponding communication, the error is supposed to became FATAL. For more information please look at  MPI Forum Ticket 143 .

Unfortunately, in Open MPI, we are unable to follow this requirement. We always trigger the error on request completion, so if there is no request ... there is no way to trigger the error.

**Comment by jsquyres** [comment]
r31982 corresponds to open-mpi/ompi@fd0e1b7261a3aa9cbe8e3568c1c6ba8faf57154a

**Comment by jsquyres** [comment]
This is already on the v1.8 branch.
