### ISSUE TITLE
CReqops.java test failing on master

### ISSUE THREAD

**Issue by nrgraham23** [open-mpi/ompi#2081]
The java test CReqops.java is currently failing on master.  The issue was reported by @gundramleifert on the ompi-users mailing list: https://www.mail-archive.com/users@lists.open-mpi.org/msg29988.html

**Comment by nrgraham23** [comment]
This issue was referenced incorrectly, re-opening it.

**Comment by hjelmn** [comment]
Thought I had fixed that, sorry!

**Comment by hjelmn** [comment]
Hah, fixed in the commit but merging the PR caused it to close! Good to know.

**Comment by nrgraham23** [comment]
No problem.  The issue was with the test, not the Java bindings.  The window size was being set as the number of processes, but it needs to be at least size 4 in parts of the test.  As soon as I bend git to my will I'll have a PR up to fix this.
