### ISSUE TITLE
PGI 16.9-beta ASM error (ppc64le)

### ISSUE THREAD

**Issue by jjhursey** [open-mpi/ompi#2086]
Build fails when using the PGI 16.9-beta compiler on ppc64le:
```shell
shell$ uname -m
ppc64le
shell$ pgcc --version

pgcc 16.9-beta linuxpower target on Linuxpower 
The Portland Group - PGI Compilers and Tools
Copyright (c) 2016, NVIDIA CORPORATION.  All rights reserved.
shell$ ./configure --without-x CC=pgcc CXX=pgc++ FC=pgfortran
...
shell$ make
...
make[2]: Entering directory `/tmp/ompi/opal/mca/mpool'
  CC       base/mpool_base_frame.lo
  CC       base/mpool_base_lookup.lo
  CC       base/mpool_base_alloc.lo
  CC       base/mpool_base_tree.lo
LLVM ERROR: Unsupported asm: input constraint with a matching output constraint of incompatible type!
make[2]: *** [base/mpool_base_tree.lo] Error 1
make[2]: Leaving directory `/tmp/ompi/opal/mca/mpool'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/ompi/opal'
make: *** [all-recursive] Error 1
```

PG 16.7-beta does not have this problem.

I suspect our ASM might need an adjustment.
Might be related to #2044

**Comment by hjelmn** [comment]
This is a nastly little bug. I used "+m" (*v) to indicate that the location pointed to by v is both read and written by the asm. This should be valid. For some reason with PGI 16.9 it doesn't like the "+m" constraint. It does, however, work with "=m" which is a little weaker. I think we are covered on the input constraint via "r" (v). I am not entirely sure but the 32-bit atomics just use "=m" anyway.
