### ISSUE TITLE
OSHMEM has no C++ wrapper compilers

### ISSUE THREAD

**Issue by bertwesarg** [open-mpi/ompi#2097]
Because of the missing `oshCC` wrapper I tried to compile a C++ SHMEM program with the `oshcc` wrapper, but this failed. I converted the `./examples/hello_oshmem_c.c` to C++:

``` c++
/*
 * Copyright (c) 2014      Mellanox Technologies, Inc.
 *                         All rights reserved.
 * Copyright (c) 2015 Cisco Systems, Inc.  All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

#include <iostream>
#include "shmem.h"

#if !defined(OSHMEM_SPEC_VERSION) || OSHMEM_SPEC_VERSION < 10200
#error This application uses API 1.2 and up
#endif

int main(int argc, char* argv[])
{
    int proc, nproc;
    char name[SHMEM_MAX_NAME_LEN];
    int major, minor;

    shmem_init();
    nproc = shmem_n_pes();
    proc = shmem_my_pe();
    shmem_info_get_name(name);
    shmem_info_get_version(&major, &minor);

    std::cout << "Hello, world, I am " << proc << " of " << nproc << ": " << name
              << " (version: " << major << "." << minor << ")" << std::endl;

    shmem_finalize();

    return 0;
}
```

Running with `oshcc` gives me:

``` shell
$ oshcc hello_oshmem_cxx.cc -o hello_oshmem_cxx
cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
/tmp/ccwM40NE.o: In function `main':
hello_oshmem_cxx.cc:(.text+0x80): undefined reference to `std::cout'
hello_oshmem_cxx.cc:(.text+0x85): undefined reference to `std::basic_ostream<char, 
...
collect2: error: ld returned 1 exit status
$ oshcc -showme:command hello_oshmem_cxx.cc -o hello_oshmem_cxx
gcc -std=gnu99 hello_oshmem_cxx.cc -o hello_oshmem_cxx
```

Please note that you advertise `oshCC` in your `README`.

**Comment by ggouaillardet** [comment]
Thanks for the report, i will take a crack at it

**Comment by jsquyres** [comment]
I think the fact that a wrapper for the C compiler can't compile a C++ program is not surprising.

I think you're really reporting the lack of an OSHMEM wrapper for the C++ compiler, right?

**Comment by ggouaillardet** [comment]
yep, we need ```{shmem,osh}{c++,cxx,CC}``` wrappers
there is no c++ bindings for oshmem, but we need a wrapper that invokes the C++ compiler

**Comment by ggouaillardet** [comment]
i made #2102 , still need to be finalised, but at least, i could compile the example with ```oshc++```

**Comment by bertwesarg** [comment]
Thanks. I suggest to add the C++ shmem example.

**Comment by bertwesarg** [comment]
I don't know if this changes anything, but Open MPI already utilized `std::complex` when compiled with a C++ compiler. Though because of the missing C++ wrapper, this could not be utilized by the user.

**Comment by ggouaillardet** [comment]
@bertwesarg I am not sure I understand, but I do not understand much of c++ anyway

mpic++ 
1. Use a c++ compiler (e.g. g++)
2. Links with the c++ MPI library (e.g. libmpicxx.so) that contains the C++ bindings

Though oshmem has no c++ bindings (e.g. no libosmemecxx.so), a c++ compiler must be use to compile c++ source files, hence the need for a new wrapper.

Strictly speaking, you only need the C++ library if you are using the (deprecated) MPI C++ bindings.
An other way to put it is that you only need a C++ compiler if you use boostMPI or similar stuff.

Meanwhile,
OPAL_CC=g++ oshcc foo.cpp
might do the trick (I am afk and cannot check right now)

**Comment by bertwesarg** [comment]
The C++ wrapper is needed to use the correct compiler diver to do the linking. Thus your trick with `OPAL_CC=g++ oshcc` should work.

My intention with this comment was more, that Open MPI already has more _C++ support_ in SHMEM, than only the mention of `oshCC` in the README. As there are the `shmem_complexf_*_to_all` functions, which use `std::complex` as there arguments. So this may be an indication, that its not only the `README`, which is _effected__ by the bug @jsquyres mentioned.

**Comment by ggouaillardet** [comment]
Got it, thanks

I will double check that as well

**Comment by ggouaillardet** [comment]
At first glance, that looks like a hack to trick C++ applications 
No C++ compiler is used to build oshmem and ```std::complex``` is hence never used in ```liboshmem.so```

As a side note, we should probably cleanup ```oshmem_info```
(e.g. remove reference to C++ bindings and Fortran ```usempi``` and ```usempif08``` flavors)

**Comment by hppritcha** [comment]
assigning to @nrgraham23 to see about integrating into ompi/oshmem.

**Comment by hppritcha** [comment]
decided to have @ggouaillardet  do this afterall

**Comment by hppritcha** [comment]
We are interested in seeing this go in to 2.1.x

**Comment by ggouaillardet** [comment]
i rebased #2102 so @jsquyres can review it, then i will PR only open-mpi/ompi@4bc0f37f48dc8cc6e1ee8972059628e46d99034c into the ```v2.x``` branch

**Comment by jsquyres** [comment]
This is going to have to be re-milestoned to v3.0.0.
