### ISSUE TITLE
v2.1.0: OSHMEM v1.3 API updates

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2109]
Just filing a blocker issue for tracking.

There's PRs on ompi-release that do what is needed -- they need to be re-opened on the ompi repo (and potentially rebased):

* https://github.com/open-mpi/ompi-release/pull/1041
* https://github.com/open-mpi/ompi-release/pull/1329
* https://github.com/open-mpi/ompi-release/pull/1330

I don't know if https://github.com/open-mpi/ompi/pull/2103 is intended for v2.1.0 or not.

**Comment by artpol84** [comment]
open-mpi/ompi-release#1329 is backed up by #2127

**Comment by artpol84** [comment]
open-mpi/ompi-release#1041 is backed up by #2095

**Comment by artpol84** [comment]
open-mpi/ompi-release#1330 is backed up by 2128

**Comment by jsquyres** [comment]
@artpol84 Thanks for the tracking!

**Comment by jladd-mlnx** [comment]
This can be closed.
