### ISSUE TITLE
Abort if --enable-mpi-fortran=usempif08 is specified but we can't build F08 bindings

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#211]
As noted by Paul Hargrove in http://www.open-mpi.org/community/lists/devel/2014/07/15347.php, if you

  --enable-mpi-fortran=usempif08

and configure determines that we can't build the F08 bindings, it doesn't abort.

r32354 was an attempt to fix this, but it wasn't quite right.

**Comment by jsquyres** [comment]
I'm going to close this issue since PR #228 is open for it.
