### ISSUE TITLE
Add support for local addresses to the TCP BTL

### ISSUE THREAD

**Issue by bosilca** [open-mpi/ompi#2114]
Cherrypick 93fa94f9 in 2.0.

**Comment by hppritcha** [comment]
@jsquyres do we still want to take this for v2.0.x/v2.x?  93fa94f doesn't apply cleanly.

**Comment by jsquyres** [comment]
Since v3.0.0 is around the corner (and included this enhancement), and since 93fa94f96fe901ed9f8842bcbfca78a04d77ba34 doesn't apply cleanly, we might as well close this issue.
