### ISSUE TITLE
Add support for local addresses in BTL TCP

### ISSUE THREAD

**Issue by bosilca** [open-mpi/ompi#2115]
Cherrypick 93fa94f9.

**Comment by jsquyres** [comment]
@hppritcha Will do in the next day or so.

**Comment by hppritcha** [comment]
just a heads up that this commit does not apply cleanly to v2.0.x

**Comment by hppritcha** [comment]
this is a mess.  it looks like we also need commit from #2054, maybe more.

**Comment by jsquyres** [comment]
@hppritcha @bosilca Might I suggest that we simply defer this to v3.0.0 -- would that be ok?

**Comment by bosilca** [comment]
👍

**Comment by bwbarrett** [comment]
This patch is in 3.0.x and 3.1.x, so not sure why we left this issue open.  Closing.
