### ISSUE TITLE
Java MPI.Finalize() seems to be periodically failing.

### ISSUE THREAD

**Issue by nrgraham23** [open-mpi/ompi#2116]
A number of the Java tests are failing periodically when run with 8 ranks.  They seem to work fine with 2 ranks (or perhaps the issue is less likely to surface with fewer ranks).

Thanks to  @gundramleifert for finding and reporting the issue.

**Comment by nrgraham23** [comment]
@hppritcha and I looked at this today and the error seems to be that MPI.Finalize() fails from time to time.  We saw a seg fault with as few as 2 ranks, and in multiple different tests (not just the one sided ones).

**Comment by gundramleifert** [comment]
@nrgraham23 what is the status of this issue?

**Comment by nrgraham23** [comment]
@gundramleifert 

You may need to update your psm install from the latest version found at: https://github.com/01org/psm.

I was running into issues with signal highjacking, discussed at: https://github.com/open-mpi/ompi/pull/1781 until I updated my version of psm.

However, after updating psm, I started getting different crashes and hangs from psm.

This appears to be an issue with psm, not ompi.  I spoke with @matcabral who has forwarded the issue to the correct team at Intel to look into this.

**Comment by matcabral** [comment]
I do not confirm the issue is in psm. Moreover, after the IPATH_NO_BACKTRACE (and HFI_NO_BACKTRACE) fix in opal_init.c. There should be no issues with signals handling. However, I do say that more research is needed.

**Comment by nrgraham23** [comment]
Right.  The issue I was seeing after updating psm definitely looked different than the errors I was getting related to signal handling.

**Comment by nrgraham23** [comment]
This problem was traced to PSM/PSM2 and is documented in the Java bindings section of the OMPI FAQ.  Closing this issue.
