### ISSUE TITLE
OMPI/v2.x is missing pmix2x component

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#2129]
As far as I recall there was an agreement that OMPI v2.1.0 will have PMIx v2.0.
However not this is not a case:
https://github.com/open-mpi/ompi/tree/v2.x/opal/mca/pmix

We need to identify proper commits and port them from master.

**Comment by artpol84** [comment]
@rhc54 @jladd-mlnx @jsquyres @hppritcha

**Comment by jladd-mlnx** [comment]
Closing this. Duplicates https://github.com/open-mpi/ompi/issues/2072
