### ISSUE TITLE
rcache/gpusm compile error on v2.x

### ISSUE THREAD

**Issue by sjeaugey** [open-mpi/ompi#2141]
MTT build error on v2.x :
https://mtt.open-mpi.org/index.php?do_redir=2359

It seems includes are missing but the changes are so big it's not clear to me how this should be fixed.

`In file included from rcache_gpusm_module.c:41:0:
../../../../opal/mca/rcache/base/base.h:44:22: error: unknown type name ‘mca_base_framework_t’
 OPAL_DECLSPEC extern mca_base_framework_t opal_rcache_base_framework;`

**Comment by hjelmn** [comment]
Not surprised. We merged hoping MTT would catch these and it did :). Will take a look and see if this is a missing commit or merge error.

**Comment by sjeaugey** [comment]
@hjelmn Thanks. I could try to add the missing headers to make it compile, but since I don't know what the original rework intent was, I may do it wrong and create more problems in the future.

**Comment by jsquyres** [comment]
@sjeaugey Is this issue still relevant, or should it be closed?

**Comment by sjeaugey** [comment]
Can be closed.
