### ISSUE TITLE
openmpi 2.0 breaks when run as root

### ISSUE THREAD

**Issue by amckinstry** [open-mpi/ompi#2147]
OMPI 2.0 breaks if run as root, failing in PMIX.
This is a regression compared to 1.10.3 ; is it expected bahaviour?

This breaks test suites for us, as by default they are run as "fakeroot".

|(unstable-amd64-sbuild)mba@hartree:/$ OMPI_MCA_orte_rsh_agent=/bin/false
|fakeroot pw.x
|[hartree:10002] PMIX ERROR: INVALID-CREDENTIAL in file
|src/server/pmix_server_listener.c at line 540
|[hartree:10001] PMIX ERROR: UNREACHABLE in file src/client/pmix_client.c
|at line 983
|[hartree:10001] PMIX ERROR: UNREACHABLE in file src/client/pmix_client.c
|at line 199
|--------------------------------------------------------------------------
|It looks like orte_init failed for some reason; your parallel process is
|likely to abort.  There are many reasons that a parallel process can
|fail during orte_init; some of which are due to configuration or
|environment problems.  This failure appears to be an internal failure;
|here's some additional information (which may only be relevant to an
|Open MPI developer):
|
|  init pmix failed
|  --> Returned value Unreachable (-12) instead of ORTE_SUCCESS
|--------------------------------------------------------------------------
|--------------------------------------------------------------------------
|It looks like orte_init failed for some reason; your parallel process is
|likely to abort.  There are many reasons that a parallel process can
|fail during orte_init; some of which are due to configuration or
|environment problems.  This failure appears to be an internal failure;
|here's some additional information (which may only be relevant to an
|Open MPI developer):
|
|  orte_ess_init failed
|  --> Returned value Unreachable (-12) instead of ORTE_SUCCESS
|--------------------------------------------------------------------------
|--------------------------------------------------------------------------
|It looks like MPI_INIT failed for some reason; your parallel process is
|likely to abort.  There are many reasons that a parallel process can
|fail during MPI_INIT; some of which are due to configuration or
|environment
|problems.  This failure appears to be an internal failure; here's some
|additional information (which may only be relevant to an Open MPI
|developer):
|
|  ompi_mpi_init: ompi_rte_init failed
|  --> Returned "Unreachable" (-12) instead of "Success" (0)
|--------------------------------------------------------------------------
|**\* An error occurred in MPI_Init
|**\* on a NULL communicator
|**\* MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
|**\*    and potentially your MPI job)
|[hartree:10001] Local abort before MPI_INIT completed completed
|successfully, but am not able to aggregate error messages, and not able
|to guarantee that all other processes were killed!
|(unstable-amd64-sbuild)mba@hartree:/$ libfakeroot, when sending message:
|Invalid argument
|libfakeroot, when sending message: Invalid argument
|libfakeroot, when sending message: Invalid argument
|semop(1): encountered an error: Invalid argument

pw.x (from quantum-espresso) is linked to the fortran MPI library as
well, not sure if that matters:

|(unstable-amd64-sbuild)mba@hartree:/$ ldd /usr/bin/pw.x | grep mpi
|        libscalapack-openmpi.so.1 => /usr//lib/libscalapack-openmpi.so.1 (0x00007fded925f000)
|        libblacs-openmpi.so.1 => /usr//lib/libblacs-openmpi.so.1 (0x00007fded902a000)
|        libblacsF77init-openmpi.so.1 => /usr//lib/libblacsF77init-openmpi.so.1 (0x00007fded8e28000)
|        libmpi_usempif08.so.20 => /usr//lib/libmpi_usempif08.so.20 (0x00007fded7d85000)
|        libmpi_usempi_ignore_tkr.so.20 => /usr//lib/libmpi_usempi_ignore_tkr.so.20 (0x00007fded7b7f000)
|        libmpi_mpifh.so.20 => /usr//lib/libmpi_mpifh.so.20 (0x00007fded7928000)
|        libmpi.so.20 => /usr//lib/libmpi.so.20 (0x00007fded7636000)
|        libblacsCinit-openmpi.so.1 => /usr//lib/libblacsCinit-openmpi.so.1 (0x00007fded6073000)

**Comment by ggouaillardet** [comment]
@amckinstry the issue is (so to speak) ```fakeroot```

from ```validate_cred``` in  ```opal/mca/pmix/pmix112/pmix/src/sec/pmix_native.c```

```getsockopt (peer->sd, SOL_SOCKET, SO_PEERCRED, &ucred, &crlen);```

my understanding is that ```fakeroot``` tricks the processes into believing they are ran as ```root```,
as such,  ```orted``` expects a connection from ```root``` (e.g. ```ucred.uid``` is ```0```)
/* in singleton mode, an ```orted``` is fork&exec'ed under the hood */

but ```fakeroot``` cannot trick ```getsockopt```, which returns the user (non zero) ```uid```

is it critical for you to be able to run Open MPI under ```fakeroot``` ?

**Comment by ndattani** [comment]
I am running a program on a compute cluster. It works fine when I use mpiexec but only allow 1 core. If I allow more than 1 core I get errors like: 

```
PMIX ERROR: INVALID-CREDENTIAL in file src/server/pmix_server_listener.c at line 540
OPAL ERROR: Unreachable in file pmix3x_client.c at line 112
```

Do you know what the problem is?

**Comment by rhc54** [comment]
@ndattani Your reported error message is from OMPI 4.x, not OMPI 2.0 as is being used by @amckinstry in his original issue. It would appear you have a completely different issue and should be reported separately.

It would also help to have a lot more info - e.g., what cmd line did you use to get that result? What system are we talking about? How was OMPI configured?

**Comment by jsquyres** [comment]
This issue is very old and stale; I don't think it was resolved, but we're very far beyond the v2.x series these days.  I'm going to close this issue.
