### ISSUE TITLE
v2.1.0: Fix OOS issues in vader BTL with single-threaded scenarios

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2160]
Per #2067, the Vader BTL has some cases where out-of-sequence messages can occur, even in single-threaded scenarios.  This affects master, v2.0.x, v2.1.x, and, if anyone cares, v1.10.x (note that _this_ issue is on the v2.1.0 milestone).

(note that this issue specifically does _not_ address the OOS issues in multi-threaded scenarios -- that is a much larger issue, and is covered by #2159)

**Comment by hppritcha** [comment]
@bosilca says this can be closed so closing it.
