### ISSUE TITLE
Open MPI 2.0.x crashes on ppc64le

### ISSUE THREAD

**Issue by cparrott73** [open-mpi/ompi#2167]
Posted here at the request of @jsquyres, who also requested I tag @hjelmn and @gpaulsen:

I was reading with some interest the recent reports of issues involving Open MPI 2.0 with PGI on ppc64le on the Open MPI devel mailing list:

https://mail-archive.com/devel@lists.open-mpi.org/msg19514.html

We have encountered similar issues here at PGI.  We did work around this issue by patching ./configure to change the following line to the following line:

```
    if test "$opal_cv_c_compiler_vendor" = "portland group" ; then
        # PGI seems to have some issues with our inline assembly.
        # Disable for now.
        #asm_result="no (Portland Group)"
        asm_result="yes"
```

A variant of this issue also affects Open MPI 1.10.x on ppc64le with PGI as well.

However, we have run into another problem with Open MPI 2.0.1 on ppc64le with PGI.  We can produce a build of Open MPI 2.0.1 on ppc64le with PGI 16.9-beta, but when we compile simple MPI test programs (e.g. cpi.c) they crash:

```
cparrott@tuleta3 ~ $ mpicc -o cpi cpi.c
cparrott@tuleta3 ~ $ ./cpi
[tuleta3:44801] *** Process received signal ***
[tuleta3:44801] Signal: Segmentation fault (11)
[tuleta3:44801] Signal code: Address not mapped (1)
[tuleta3:44801] Failing at address: 0x100000996328
[tuleta3:44801] [ 0] [0x100000040478]
[tuleta3:44801] [ 1] /var/tmp/openmpi/lib/libopen-pal.so.20(+0x128888)[0x100000318888]
[tuleta3:44801] [ 2] /lib64/ld64.so.2(+0xecd4)[0x10000000ecd4]
[tuleta3:44801] [ 3] /lib/powerpc64le-linux-gnu/libc.so.6(__sbrk+0x64)[0x1000008612d4]
[tuleta3:44801] [ 4] /lib/powerpc64le-linux-gnu/libc.so.6(__default_morecore+0x18)[0x1000007ebd78]
[tuleta3:44801] [ 5] /lib/powerpc64le-linux-gnu/libc.so.6(+0x944ec)[0x1000007e44ec]
[tuleta3:44801] [ 6] /lib/powerpc64le-linux-gnu/libc.so.6(__libc_malloc+0x84)[0x1000007e6af4]
[tuleta3:44801] [ 7] /lib/powerpc64le-linux-gnu/libc.so.6(__strdup+0x34)[0x1000007eef34]
[tuleta3:44801] [ 8] /var/tmp/openmpi/lib/libopen-pal.so.20(opal_hwloc1112_hwloc__add_info+0x98)[0x10000030d870]
[tuleta3:44801] [ 9] /var/tmp/openmpi/lib/libopen-pal.so.20(+0x1087c8)[0x1000002f87c8]
[tuleta3:44801] [10] /var/tmp/openmpi/lib/libopen-pal.so.20(+0x10efe4)[0x1000002fefe4]
[tuleta3:44801] [11] /var/tmp/openmpi/lib/libopen-pal.so.20(+0x108a34)[0x1000002f8a34]
[tuleta3:44801] [12] /var/tmp/openmpi/lib/libopen-pal.so.20(+0x121a60)[0x100000311a60]
[tuleta3:44801] [13] /var/tmp/openmpi/lib/libopen-pal.so.20(opal_hwloc1112_hwloc_topology_load+0x188)[0x10000030fcc0]
[tuleta3:44801] [14] /var/tmp/openmpi/lib/libopen-pal.so.20(opal_hwloc_base_get_topology+0x88)[0x1000002e40c0]
[tuleta3:44801] [15] /var/tmp/openmpi/lib/libopen-rte.so.20(+0x7ec2c)[0x1000000eec2c]
[tuleta3:44801] [16] /var/tmp/openmpi/lib/libopen-rte.so.20(orte_init+0x2e0)[0x1000000a05b8]
[tuleta3:44801] [17] /var/tmp/openmpi/lib/libopen-rte.so.20(orte_daemon+0x2d8)[0x1000000c4380]
[tuleta3:44801] [18] orted[0x10000a24]
[tuleta3:44801] [19] /lib/powerpc64le-linux-gnu/libc.so.6(+0x24d00)[0x100000774d00]
[tuleta3:44801] [20] /lib/powerpc64le-linux-gnu/libc.so.6(__libc_start_main+0xc8)[0x100000774ef8]
[tuleta3:44801] *** End of error message ***
[tuleta3:44800] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ../../../../../orte/mca/ess/singleton/ess_singleton_module.c at line 573
[tuleta3:44800] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ../../../../../orte/mca/ess/singleton/ess_singleton_module.c at line 163
[tuleta3:44800] *** Process received signal ***
[tuleta3:44800] Signal: Segmentation fault (11)
[tuleta3:44800] Signal code: Address not mapped (1)
[tuleta3:44800] Failing at address: (nil)
[tuleta3:44800] [ 0] [0x100000040478]
[tuleta3:44800] [ 1] /var/tmp/openmpi/lib/libopen-pal.so.20(+0x12888c)[0x10000095888c]
[tuleta3:44800] [ 2] /var/tmp/openmpi/lib/libopen-pal.so.20(+0x136d8)[0x1000008436d8]
[tuleta3:44800] [ 3] /lib/powerpc64le-linux-gnu/libc.so.6(__sbrk+0x64)[0x1000006012d4]
[tuleta3:44800] [ 4] /lib/powerpc64le-linux-gnu/libc.so.6(__default_morecore+0x18)[0x10000058bd78]
[tuleta3:44800] [ 5] /lib/powerpc64le-linux-gnu/libc.so.6(+0x944ec)[0x1000005844ec]
[tuleta3:44800] [ 6] /lib/powerpc64le-linux-gnu/libc.so.6(__libc_malloc+0x84)[0x100000586af4]
[tuleta3:44800] [ 7] /var/tmp/openmpi/lib/libopen-pal.so.20(opal_show_help_yyalloc+0x18)[0x1000008bffb0]
[tuleta3:44800] [ 8] /var/tmp/openmpi/lib/libopen-pal.so.20(opal_show_help_yy_create_buffer+0x60)[0x1000008bf3e8]
[tuleta3:44800] [ 9] /var/tmp/openmpi/lib/libopen-pal.so.20(opal_show_help_init_buffer+0x1c)[0x1000008c00a4]
[tuleta3:44800] [10] /var/tmp/openmpi/lib/libopen-pal.so.20(+0x8dddc)[0x1000008bdddc]
[tuleta3:44800] [11] /var/tmp/openmpi/lib/libopen-pal.so.20(+0x8db10)[0x1000008bdb10]
[tuleta3:44800] [12] /var/tmp/openmpi/lib/libopen-pal.so.20(opal_show_help_vstring+0x48)[0x1000008bd560]
[tuleta3:44800] [13] /var/tmp/openmpi/lib/libopen-rte.so.20(orte_show_help+0x68)[0x1000006f46c0]
[tuleta3:44800] [14] /var/tmp/openmpi/lib/libopen-rte.so.20(orte_init+0x3c8)[0x1000006e06a0]
[tuleta3:44800] [15] /var/tmp/openmpi/lib/libmpi.so.20(ompi_mpi_init+0x31c)[0x1000000ee5f4]
[tuleta3:44800] [16] /var/tmp/openmpi/lib/libmpi.so.20(MPI_Init+0x8c)[0x10000011d5d4]
[tuleta3:44800] [17] ./cpi[0x10000d10]
[tuleta3:44800] [18] /lib/powerpc64le-linux-gnu/libc.so.6(+0x24d00)[0x100000514d00]
[tuleta3:44800] [19] /lib/powerpc64le-linux-gnu/libc.so.6(__libc_start_main+0xc8)[0x100000514ef8]
[tuleta3:44800] *** End of error message ***
Segmentation fault (core dumped)
```

One of our developers looked into the crash and determined that there are some issues with opal/mca/memory/patcher/memory_patcher_component.c that trigger this on ppc64le:

gdb says we are here when we take the fault:

```
opal/mca/memory/patcher/memory_patcher_component.c:264
264 old_addr = __curbrk;
```

The assembly there is:
```
0x00001000007fda68 <+64>: ld r3,-26120(r2)
```

Which is:
```
488: 00 00 63 e8 ld r3,0(r3)
488: R_PPC64_TOC16_LO_DS .toc+0x18
```

Where section .toc has:
```
0000000000000018 R_PPC64_ADDR64 __curbrk
```

This is attempting to load the value of __curbrk via the TOC pointer. This TOC entry is pointing to unmapped memory.

He then points out a workaround:

When I stub out the code in memory_patcher_component.c in patcher_open() — all the calls to opal_patcher->patch_symbol() from "munmap" through "brk" — and use that mpi to build the cpi test, I get a working executable. I therefore believe that there is something no quite kosher with the way these intercepts are being done on the tuleta system.

For what it's worth, I also encountered a similar issue when building Open MPI 2.0.1 with GCC on our tuleta systems, so the problem does not appear to be unique to PGI compilers.

Are you aware of any issues with this routine?  Are there any adverse implications to stubbing out the code above, as our developer described?  (Doing this did make our simple test programs work.)

**Comment by hjelmn** [comment]
this is fixed on master. we has to work around a pgi asm bug among other things. i don't think i have moved it to 2.x or 2.0.x

**Comment by hjelmn** [comment]
Looks like I brought the patcher fixes to 2.0.x/2.x. Can you try master and see if it works? I may have missed something.

**Comment by cparrott73** [comment]
Hi Nathan,

Thanks so much for the responses.  I will pull master from git right away and try it on our POWER systems to see if it helps.  Will follow up once I have more info.

Thanks,

+chris

**Comment by cparrott73** [comment]
Hi Nathan,

master looks good on a tuleta I just tried, using a GCC 6.2.0 build here:

> cparrott@tuleta4 ~ $ mpicc -o cpi cpi.c
> cparrott@tuleta4 ~ $ mpirun -np 8 ./cpi
> Process 0 of 8 is on tuleta4
> Process 1 of 8 is on tuleta4
> Process 2 of 8 is on tuleta4
> Process 4 of 8 is on tuleta4
> Process 5 of 8 is on tuleta4
> Process 6 of 8 is on tuleta4
> Process 3 of 8 is on tuleta4
> Process 7 of 8 is on tuleta4
> pi is approximately 3.1415926544231247, Error is 0.0000000008333316
> wall clock time = 0.000269
> 

Thanks!

+chris

**Comment by jsquyres** [comment]
@cparrott73 Github pro tip: use three single-tick marks before and after blocks of text that you need to render as verbatim: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by hjelmn** [comment]
Ok, have you tried the 2.0.x nightly or just 2.0.1?

**Comment by cparrott73** [comment]
I just did a source pull on master.  I'll try v2.0.x next.  Thanks!

**Comment by cparrott73** [comment]
2.0.x looks good, too:

```
cparrott@tuleta4 /scratch/cparrott/ompi-2.0.x/build $ cd
cparrott@tuleta4 ~ $ mpicc -o cpi cpi.c
cparrott@tuleta4 ~ $ mpirun -np 8 ./cpi
Process 1 of 8 is on tuleta4
Process 2 of 8 is on tuleta4
Process 3 of 8 is on tuleta4
Process 5 of 8 is on tuleta4
Process 6 of 8 is on tuleta4
Process 7 of 8 is on tuleta4
Process 0 of 8 is on tuleta4
Process 4 of 8 is on tuleta4
pi is approximately 3.1415926544231247, Error is 0.0000000008333316
wall clock time = 0.000183
```

**Comment by hjelmn** [comment]
Alright. I will close this issue then as it is fixed for both next releases.
