### ISSUE TITLE
Remove --disable-mpi-io switch

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2185]
Per discussion on https://github.com/open-mpi/ompi/issues/2179, it's time to remove the `--disable-mpi-io` configure switch.

**Comment by hjelmn** [comment]
If this is going into 2.x then I will hold off on adding the commits from @ggouaillardet to fix this option in my PR.

**Comment by jsquyres** [comment]
I say "2.x" but I don't know if anyone has any time to work on this feature -- I filed this issue mainly so that we wouldn't forget / someone may do it someday.

If no one volunteers in the immediate future, you might as well add @ggouaillardet's commits to your C++ PR.

**Comment by edgargabriel** [comment]
To bring up another possibility, maybe we want to keep the  `--disable-mpi-io`  configure flag as a short cut to  `--disable-mpi-romio` +  `--disable-mpi-ompio`. That would however not remove the function prototypes and structure from mp.h

**Comment by jsquyres** [comment]
Actually, wait: I misspoke: this *can't* go to the 2.x branch at all, because it would break backwards compatibility.  So this is a 3.x issue.

**Comment by ggouaillardet** [comment]
i can do that

**Comment by jsquyres** [comment]
@ggouaillardet We owe you 🍻
