### ISSUE TITLE
"make check" ddt_benchmark is failing at Nvidia MTT

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2209]
@sjeaugey You have a "make check" test failing in MTT:

https://mtt.open-mpi.org/index.php?do_redir=2364

Can you please provide details / logs on what is happening there?

The MPI name is "eddy16112-cuda-rebase" -- what is that?  Is that master?  2.0.x?  2.x?  ...?

**Comment by sjeaugey** [comment]
@jsquyres don't worry about this one, it is a work-in-progress branch from UTK branch for CUDA optimizations and it is not ready yet (as you can see).

I sometimes add unstable github branches to my MTT (like I did for nathan mpool rewrite) when I'm concerned it could break CUDA support and before the pull request is made.

So, when the MPI version is ".", it is not the official Open MPI releases. I agree it would be better to show something like "this is a dev branch".
