### ISSUE TITLE
COMM_SPAWN broken in v2.0.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2234]
This is a mirror for #2030, but for v2.0.x (instead of v2.1.x).

Keep all general discussion about the issue over on #2030; put any specific v2.0.x information here.

**Comment by jsquyres** [comment]
It looks like #2215 fixes the issue for v2.x.  

@hjelmn Could we get a smaller version of it for v2.0.x?  (e.g., leaving out 91337bf5c818b752f8ab7e63705b4fea8f4c8dd7)?

**Comment by hppritcha** [comment]
@jsquyres I think this can be closed since #2381 is merged in.

**Comment by hppritcha** [comment]
This issue is closed by commit #2215
