### ISSUE TITLE
possible thread safety problems in v2.Xrelease

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#2287]
thread-tests-1.1 collcomp test is periodically hanging (timeout) in cisco community runs both
for v2.0.x and v2.1.x release streams:

https://mtt.open-mpi.org/index.php?do_redir=2376

**Comment by jsquyres** [comment]
@hjelmn @bosilca Could you have a look?

**Comment by hjelmn** [comment]
One common component in all the failed runs is the tcp btl. Any chance to see if it hangs/fails with just vader or sm?

**Comment by jsquyres** [comment]
I've been running the test with vader,self over the past 12 hours or so and it never hung.  But it was *slow* when I oversubscribed the machine (which is likely to be expected).  I'm re-running now with sm,self to see if there's a difference.

It could well be that I don't have a long enough timeout in MTT and/or should adjust the test to not overload the machine (i.e., more threads than cores).

**Comment by bosilca** [comment]
This test is not technically a multi-threaded stress test, it is a mild computationally intensive test disguised as a multi-threaded test. A single thread is doing MPI calls (allreduce on non-initialized data), while all the other threads are multiplying non-initialized vectors. I do not understand what exactly you expect from this test, but based on the values in the 3 randomly initialized arrays the test can last from few seconds with few hours.

**Comment by jsquyres** [comment]
@bosilca I just wanted it to not fail.  😄   (I didn't look at the content of the test at all)  We were just wondering if the failure of this test was something more systemic to our thread support overall, but I'm guessing it doesn't.  My test has been running with sm,self for the last 20+ minutes and has shown similar behavior as with vader,sm (i.e., it's slow, but not actually hanging).

I think I'm just going to adjust my MTT setup to let it run longer and therefore close this issue.  If it keeps failing, I'll open a new issue.
