### ISSUE TITLE
Recursive behavior in ompi_mpi_abort()

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#23]
Per [http://www.open-mpi.org/community/lists/devel/2007/08/2220.php this thread on the devel list], ompi_mpi_abort() may actually be invoked recursively via the progression engine.  Additionally it is possible that multiple threads may invoke ompi_mpi_abort() simultaneously in a THREAD_MULTIPLE scenario.  Clearly, only one thread should be allowed to do the actual "abort" processing.

Not-thread-safe protection was added near the top of ompi_mpi_abort() a while ago in the form of logic that looks like this:

```
    if (have_been_invoked) {
        return OMPI_SUCCESS;
    }
    have_been_invoked = true;
```

However, this is clearly bad because it violates assumptions elsewhere in the code that ompi_mpi_abort() will not return (i.e., Bad Things can/will happen, like segvs).  

Adding protection for the THREAD_MULTIPLE scenario is probably easy enough; looping over sleep (or progress?) is probably fine.  

But sleep/progress-looping is ''not'' the right solution for recursive invocations from the thread that is actually doing the abort processing because there are at least some cases where progress will not occur until control pops all the way back to the top of the progress stack.

So - what to do?

**Comment by rhc54** [comment]
Solved by introducing threaded OOB and PMIx support
