### ISSUE TITLE
Fix PMIx dstore bug #144 (space consumption)

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#2316]
Currently PMIx stores ~ 2.9kB per remote rank in the local hash table when running 272 ranks per node on knl systems. This needs to be fixed before 2.1.0 is released.

Bug cross-link: pmix/master#144

**Comment by artpol84** [comment]
Fixed through 
* https://github.com/pmix/master/pull/225
* https://github.com/pmix/master/pull/236
