### ISSUE TITLE
TCP BTL in docker container freezes (again, sorry)

### ISSUE THREAD

**Issue by d-a-v** [open-mpi/ompi#2320]
Hello,

When trying to run openmpi in a docker container using a bridge as the only existing network interface available, the application gets stuck.

A setup is available for anyone who wishes to [test](https://github.com/d-a-v/openmpi-bridge-docker).

This is a still real old problem. This https://github.com/open-mpi/ompi/issues/160 issue from 2014 expected the problem to be solved by ompi-v1.9+. 
I have not come to beg. I just want to highlight this bug again, because it would rock to run setups with slurm+openmpi in bridged docker containers, so to allow far easier HPC administration.

**Comment by ggouaillardet** [comment]
which version of Open MPI do you run ?

master branch blacklists interfaces named ```vir*```, and this is hard coded in ```oob/tcp```
so i am aware you cannot run ```mpirun``` on your host and put containers in your hostfile

the inline patch can help you
```patch
diff --git a/orte/mca/oob/tcp/oob_tcp_component.c b/orte/mca/oob/tcp/oob_tcp_component.c
index b610812..19ba1a9 100644
--- a/orte/mca/oob/tcp/oob_tcp_component.c
+++ b/orte/mca/oob/tcp/oob_tcp_component.c
@@ -514,10 +514,12 @@ static int component_available(void)
         /* get the name for diagnostic purposes */
         opal_ifindextoname(i, name, sizeof(name));
 
+#if 0
         /* ignore any virtual interfaces */
         if (0 == strncmp(name, "vir", 3)) {
             continue;
         }
+#endif
 
         /* handle include/exclude directives */
         if (NULL != interfaces) {
```

**Comment by d-a-v** [comment]
Hi, thanks.
I tried the master branch and the v2.0.x branch, with same issue.
The name of the interface inside the docker container is eth0, so the patch above has no effect (but still I tried too, and the name of the interface is indeed eth0 inside the 'name' variable).

**Comment by rhc54** [comment]
You might want to check on the slurm mailing list as I know people are doing this today - not sure what configuration was required.

**Comment by ggouaillardet** [comment]
I will try to reproduce this.
At first glance, all happens inside containers, and eth0 is the only avsilable interface, so from an Open MPI point of view, thst should be business as usual ...
The hang suggests ip forwarding on the hosts for container-to-container traffic does not work as it should 
If you have any chance, can you double check with tcpdump traffic gies through ?

**Comment by ggouaillardet** [comment]
fwiw, i was able to run ```examples/ring_c``` in a similar config (i use ```lxc``` containers directly)
i manually created ```virbr1``` and ```virbr2```, and manually added the ```iptables``` rules
```
# iptables -I INPUT -i virbr1 -j ACCEPT
# iptables -I INPUT -i virbr2 -j ACCEPT
# iptables -I FORWARD -i virbr1 -o virbr2  -j ACCEPT
# iptables -I FORWARD -i virbr2 -o virbr1  -j ACCEPT
```
and made sure ip forwarding is turned on
```
$ sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
```

there is no SE linux on my host nor my containers, and there are no ```iptables``` on the containers

**Comment by jsquyres** [comment]
Can you specify where the application is hanging?  I.e., is it even getting past the initial mpirun?  Are the MPI applications starting?  If so, do they get past MPI_INIT?  Do they successfully execute some MPI communication calls?  ...etc.

Also, can you send the ifconfig output / networking topology of your setup?

If it's a matter of Open MPI automatically choosing the "wrong" network (e.g., picking to use some container-only network that has the same IP range as other containers but is unreachable by any process outside of the current container), you can include/exclude specific networks with various runtime controls (MCA params -- CLI params, files, and/or env vars).

**Comment by d-a-v** [comment]
@jsquyres a lot of your questions are answered in the readme from the link in the OP. https://github.com/d-a-v/openmpi-bridge-docker
In brief: yes, ompi starts, but no communication. Ompi logs are provided. Mpich is running with the very same setup, so the network is working. Ifconfig and brctrl are shown. All networks are excluded except the only one available (eth0) with "btl self,tcp" and "oob/btl_tcp_include_if eth0".

@ggouaillardet as stated above, the network connectivity is not the cause. At the very end of the readme, brctl shows the two bridges each associated with the two containers. Theses two bridges are reachable one another from the two containers (seen as eth0 inside the containers). Brctl shows "vethxxxxx" so they are indeed associated to virtual ethernet interfaces (where docker0 default bridge is not) but there I'm lost.  "vethxxxxx" may be the cause why ompi do not like them (regarding the patch you proposed above). The two bridges I'm using are created by "docker network create" command.

In case you wish to quickly reproduce the case, clone the link in a bare linux virtual machine (kvm, virtualbox, not docker :) ) and run the scripts.

**Comment by jsquyres** [comment]
@d-a-v Oops!  Sorry for missing that info in the original post.  /me goes to read now... Nice; thanks for all the detail.

Can you try running with this patch and `--mca btl_base_verbose 100`? (you're already using that verbose level; you need to keep it that high to enable extra dumping)

```patch
diff --git a/opal/mca/btl/tcp/btl_tcp_endpoint.h b/opal/mca/btl/tcp/btl_tcp_endpoint.h
index 5e40551..b0647fe 100644
--- a/opal/mca/btl/tcp/btl_tcp_endpoint.h
+++ b/opal/mca/btl/tcp/btl_tcp_endpoint.h
@@ -85,7 +85,7 @@ void mca_btl_tcp_endpoint_shutdown(mca_btl_base_endpoint_t*);
  * Diagnostics: change this to "1" to enable the function
  * mca_btl_tcp_endpoint_dump(), below
  */
-#define WANT_PEER_DUMP 0
+#define WANT_PEER_DUMP 1
 
 #if OPAL_ENABLE_DEBUG && WANT_PEER_DUMP
 #define MCA_BTL_TCP_ENDPOINT_DUMP(LEVEL, ENDPOINT, INFO, MSG) mca_btl_tcp_endpoint_dump((LEVEL), __FILE__, __LINE__, __func__, (ENDPOINT), (INFO), (MSG))
```

This will output some more state about the TCP BTL connection status.  Without this patch, we only see the one side of trying to make a connection -- not what happens on the receiver (if anything).

**Comment by d-a-v** [comment]
Here are the WANT_PEER_DUMP defined to 1 logs: [gist](https://gist.githubusercontent.com/d-a-v/c58f5ae8a9450cc3d0a609c8d63fed6d/raw/9c6432b64c6375d493d408839eb0757a35bca372/want_peer_dump_1.log)

**Comment by ggouaillardet** [comment]
@d-a-v Open MPI is exclusively used inside containers. so from this point of view, there is only ```eth0``` and as far as i understand, there is even no way to know that this interface is part of a bridge on a host with a ```vethXXX``` name.
we did some tricks to exclude some virtual interfaces, and that could only interfere if Open MPI was using the host.

out of curiosity, what if you
```
$ ./ssh-to-container 10.243.1.3 " \
    cd '/tmp/'; \
    mpirun -mca plm_rsh_agent /home/user/openmpi-bridge-docker/ssh-to-container \
        --allow-run-as-root \
        -mca btl self,tcp \
        -mca btl_tcp_if_include eth0 \
        -mca oob_tcp_if_include eth0 \
        -mca btl_base_verbose 100 \
        -mca orte_debug 1 \
        -mca orte_debug_verbose 100 \
        -mca orte_base_help_aggregate 0 \
        -host 10.243.1.3,10.242.1.3  'sendrecv' \
    "
```

/* i swapped the two IP in the ```-host``` mpirun option */

with you current command, ```oob/tcp``` connects in one direction, and ```btl/tcp``` tries (and fails) to connect in the other direction

out of curiosity, which distro are you running on the host ?
do you use docker provided by the distro ? did you recompile the latest stable version ?
can you also post the iptables on your host ?

**Comment by bosilca** [comment]
David,

1. This might be a typo in the git repo, but I don’t see where you check the connection from 10.242.1.3 to 10.243.1.3. You check the connectivity from the host to 10.242.1.3, then from 10.242.1.3 to 10.242.1.3, and then finally from 10.243.1.3 to 10.242.1.3.

2. Some pertinent info from the gist. At the bottom of the gist (about 20 lines before) you can see the following 2 lines:
> [f4d8d0b73b66:00026] mca: bml: Using tcp btl for send to [[63377,1],0] on node 10.242.1.2
> [f4d8d0b73b66:00026] btl: tcp: attempting to connect() to [[63377,1],0] address 10.242.1.2 on port 1024
This indicates that the connection has been started, but as we don’t see anything related to accepting the connection I would assume it didn’t succeed. If you let the dockers run for over 20 minutes, you might eventually get a timeout.

3. Puzzling … I can see ORTE (via the OOB) using similar IP addressed to connect the 2 nodes, but the ORTE ports are in the higher end of the port range (after 48K). The fact that ORTE gets such a high port, while the BTL gets 1024 is puzzling.

  George.

**Comment by ggouaillardet** [comment]
@bosilca in my ```lxc``` environment, ```btl/tcp``` also gets port 1024, while ```oob/tcp``` receives a higher port.
privileged ports are (strictly) less than 1024, so i would not worry too much about this.

**Comment by ggouaillardet** [comment]
@bosilca 
```
MCA btl tcp: parameter "btl_tcp_port_min_v4" (current value: "1024", data source: default, level: 2 user/detail, type: int)
MCA btl tcp: parameter "btl_tcp_port_range_v4" (current value: "64511", data source: default, level: 2 user/detail, type: int)
```

without reading the code, that suggests Open MPI tries to bind to port 1024, 1025, ... 1024+64511 until ```bind``` successes, and that would explain why ```btl/tcp``` binds to port ```1024```.
```oob/tcp``` likely bind to port 0, so it gets assigned a higher value

**Comment by bosilca** [comment]
@ggouaillardet indeed, the port association is coming from the BTL itself.

**Comment by d-a-v** [comment]
@ggouaillardet 
- swapping IP does no change anything. I can provide the debug log if needed?
- both host and containers are ubuntu xenial 16.04 x64. Currently host is inside qemu/kvm because I am remotely working, but I get same behaviour on native host
- docker is docker-stable from get.docker.com, not the one from the distro. I will try with docker from stable source.
- iptables from host: [there](https://gist.githubusercontent.com/d-a-v/5c9e468da438873d26810b2db85fef89/raw/954e171ef7a314bf8ca58c73c88633c8f273ff6f/gistfile1.txt)

**Comment by d-a-v** [comment]
@bosilca 
1. you are right, I did not mention it. Here is an example of working connectivity: [there)[https://gist.githubusercontent.com/d-a-v/d79d6f1aa834aa48b25d83c8ed11ba66/raw/b8f571927ee8075763b8facfc855d8a708f184b9/gistfile1.txt]
2. I'll start the 20mn wait test right after this. Please note that the applications eat all available cpu while sitting and waiting for communication to succeed. So it seems not be a tcp send/receive not receiving acks.
3. That's beyond my knowledge, you guys got the answers by yourselves :) 


Knowing that both the applications eats cpu while waiting, is there an easy way to run gdb and break / examine the state (like: where is the ompi code looping)  ?
(so far I have never gdb'd a running multitask application)

**Comment by ggouaillardet** [comment]
@d-a-v i will install your environment because i have no clue of what is going wrong here.
we use ```libevent``` internally, and it makes debugging non trivial
you can simply run ```pstack``` on your MPI tasks, if should show one in ```MPI_Send``` and the other in ```MPI_Recv```

is ```selinux``` "running" on host ?

out of curiosity, you might want to try
```mpirun --mca btl_tcp_port_min_v4 48000 ...```
i am pretty much hopeless, but that is a cheap test

**Comment by d-a-v** [comment]
@bosilca 
2. 50mn later, no more output from debug log, still sitting eating cpu.

**Comment by d-a-v** [comment]
@ggouaillardet 
- I have not used libevent yet. I will try and see what I can do, thanks
- selinux is running nowhere
- `--mca btl_tcp_port_min_v4 48000` indeed changed the port values in debug logs, but with no other change.

**Comment by ggouaillardet** [comment]
@d-a-v i finally nailed it :-)

what happens is connections between containers are masqueraded, so i guess Open MPI silently drop the connection

```
$ ./ssh-to-container 10.242.1.2 strace -e accept nc -l 1024
Warning: Permanently added '10.242.1.2' (ECDSA) to the list of known hosts.
accept(3, {sa_family=AF_INET, sin_port=htons(42928), sin_addr=inet_addr("10.242.1.1")}, [16]) = 4
thanks for goold old lrc
+++ exited with 0 +++
```

```
$ ./ssh-to-container 10.243.1.2 "echo thanks for goold old lrc | nc 10.242.1.2 1024"
```

note the connection comes from ```10.242.1.1``` when ```10.243.1.2``` is expected

the following commands on your host will keep cross container traffic unmasqueraded

```
iptables -t nat -I POSTROUTING -o brtestdocker2 -s 10.242.1.0/24 -j ACCEPT
iptables -t nat -I POSTROUTING -o brtestdocker1 -s 10.243.1.0/24 -j ACCEPT
```

and the previous commands return

```
./ssh-to-container 10.242.1.2 strace -e accept nc -l 1024
Warning: Permanently added '10.242.1.2' (ECDSA) to the list of known hosts.
accept(3, {sa_family=AF_INET, sin_port=htons(42934), sin_addr=inet_addr("10.243.1.2")}, [16]) = 4
thanks for goold old lrc
+++ exited with 0 +++
```

then Open MPI is a happy panda  :-D


i do not know much about docker, but i guess what you need is direct docker to start containers with network bridged with your host interface (vs currently NAT network).

**Comment by jsquyres** [comment]
We should probably put some verbose messages on the receiver side when the TCP BTL drops unexpected incoming connections (i.e., something that would display if you `--mca btl_base_verbose 100`).

**Comment by ggouaillardet** [comment]
I will take a crack at it.
Note that at this stage, I only guessed unexpected incoming connections are silently dropped.

**Comment by d-a-v** [comment]
@ggouaillardet 
Thanks alot, it works with the postrouting rules !
Of course the container are masqueraded, but I never questioned myself about masquerading between local bridges too. I will try soon on the real setup (containers on different hosts not the same one as here).

@all
Big thanks, you guys saved my mental stability about a problem which is is definitely not yours.

@ggouaillardet 
> `$ ./ssh-to-container 10.243.1.2 "echo thanks for goold old lrc | nc 10.242.1.2 1024"`
this is just incredible :) 
I hope you did *not* get into that code, I did not even know select() at that time ('95). however I hope this piece of code brought you fun with your mates at n7 as it did for me.
world is small :)

**Comment by bosilca** [comment]
@ggouaillardet nice catch. Indeed, after we receive the initial handshake from the peer in mca_btl_tcp_component_recv_handler, we then extract the IP of the incoming socket and go in mca_btl_tcp_proc_accept. That's the moment where we will silently drop the connection, if the address doesn't match what we know about the peer (from the modex).

@d-a-v can you give a try to the following patch (it is for master):
```patch
diff --git a/opal/mca/btl/tcp/btl_tcp_proc.c b/opal/mca/btl/tcp/btl_tcp_proc.c
index f7decc4..e1667d2 100644
--- a/opal/mca/btl/tcp/btl_tcp_proc.c
+++ b/opal/mca/btl/tcp/btl_tcp_proc.c
@@ -808,6 +808,9 @@ void mca_btl_tcp_proc_accept(mca_btl_tcp_proc_t* btl_proc, struct sockaddr* addr
         return;
     }
     OPAL_THREAD_UNLOCK(&btl_proc->proc_lock);
+    opal_output(0, "btl: tcp: Incoming connection from %s does not match known addresses for peer %s. Drop !\n",
+                opal_net_get_hostname((struct sockaddr*)addr),
+                OPAL_NAME_PRINT(btl_proc->proc_opal->proc_name));
     /* No further use of this socket. Close it */
     CLOSE_THE_SOCKET(sd);
 }
```

**Comment by d-a-v** [comment]
@bosilca will do as soon as possible.

**Comment by d-a-v** [comment]
@bolsica your patch is informative. With my misconfigured network, here is what I get without any debugging option:

> i am 1, sending to 0
> Hello world: processor 0 of 2
> i am 0, recv from 1
> [a72ec539ca75:00019] btl: tcp: Incoming connection from 10.242.1.1 does not match known addresses for peer [[39018,1],1]. Drop !

This would have been very helpful in my case.

Thanks

**Comment by bosilca** [comment]
@d-a-v thanks for the testing. I will push the change in the master, but not before I have the time to dig a little bit more and understand why the closed socket is not detected by the remote peer. We now know the socket has been correctly closed, and this is supposed to trigger a 0-byte reception at the originator, which will then try to find another way to communicate with the peer. If no other way exists (which should be true in your case), the process is then supposed to abort. I really wonder why the second part of the protocol is not working correctly.

**Comment by jsquyres** [comment]
@bosilca This isn't complete, but perhaps a patch like this would be good:

```patch
diff --git a/opal/mca/btl/tcp/btl_tcp_proc.c b/opal/mca/btl/tcp/btl_tcp_proc.c
index f7decc4..2b03741 100644
--- a/opal/mca/btl/tcp/btl_tcp_proc.c
+++ b/opal/mca/btl/tcp/btl_tcp_proc.c
@@ -774,6 +774,7 @@ mca_btl_tcp_proc_t* mca_btl_tcp_proc_lookup(const opal_process_n
  */
 void mca_btl_tcp_proc_accept(mca_btl_tcp_proc_t* btl_proc, struct sockaddr* addr, i
 {
+    int len = 0;
     OPAL_THREAD_LOCK(&btl_proc->proc_lock);
     for( size_t i = 0; i < btl_proc->proc_endpoint_count; i++ ) {
         mca_btl_base_endpoint_t* btl_endpoint = btl_proc->proc_endpoints[i];
@@ -789,6 +790,9 @@ void mca_btl_tcp_proc_accept(mca_btl_tcp_proc_t* btl_proc, struc
                         sizeof(struct in_addr) ) ) {
                 continue;
             }
+
+            // Add space for: "xxx.xxx.xxx.xxx, "
+            len += 18;
             break;
 #if OPAL_ENABLE_IPV6
         case AF_INET6:
@@ -797,6 +801,9 @@ void mca_btl_tcp_proc_accept(mca_btl_tcp_proc_t* btl_proc, struc
                         sizeof(struct in6_addr) ) ) {
                 continue;
             }
+
+            // Add space for "xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx, "
+            len += 42;
             break;
 #endif
         default:
@@ -807,6 +814,51 @@ void mca_btl_tcp_proc_accept(mca_btl_tcp_proc_t* btl_proc, stru
         OPAL_THREAD_UNLOCK(&btl_proc->proc_lock);
         return;
     }
+
+    // Make a useful message to show about the fact that we dropped an
+    // inbound connection.
+    char *addr_str = alloca(len);
+    if (NULL == addr_str) {
+        addr_str = "error";
+    } else {
+        memset(addr_str, 0, len);
+        for (size_t i = 0; i < btl_proc->proc_endpoint_count; i++) {
+            mca_btl_base_endpoint_t* btl_endpoint = btl_proc->proc_endpoints[i];
+            if (btl_endpoint->endpoint_addr->addr_family != addr->sa_family) {
+                continue;
+            }
+
+            if (addr_str[0] != '\0') {
+                strncat(addr_str, ", ", len);
+            }
+
+            switch (addr->sa_family) {
+            case AF_INET:
+                strncat(addr_str,
+                        inet_ntoa(*((struct in_addr*)
+                                    &btl_endpoint->endpoint_addr->addr_inet)),
+                        len);
+                break;
+#if OPAL_ENABLE_IPV6
+            case AF_INET6:
+                strncat(addr_str,
+                        // JMS Need IPv6 equivalent of inet_ntoa()
+                        len);
+                break;
+#endif
+            default:
+                break;
+            }
+        }
+    }
+
+    opal_output_verbose(20, opal_btl_base_framework.framework_output,
+                        "btl: tcp: Incoming connection from %s does not match known
+                        opal_net_get_hostname((struct sockaddr*)addr),
+                        OPAL_NAME_PRINT(btl_proc->proc_opal->proc_name),
+                        btl_proc->proc_opal->proc_hostname,
+                        addr_str);
+
     OPAL_THREAD_UNLOCK(&btl_proc->proc_lock);
     /* No further use of this socket. Close it */
     CLOSE_THE_SOCKET(sd);
```

**Comment by bosilca** [comment]
If you want to print all the addresses of the peer, we have them somewhere (the URI we got from the modex).

**Comment by ggouaillardet** [comment]
an other approach is to mimick ```oob/tcp```
accept all connections, and use the ```sec``` framework to figure out whether a connection is legit or not.

that would allow Open MPI to support more complex/spaghetti networks with NAT and port forwarding. i do not see a need for it right now. later ... who knows ?

**Comment by jsquyres** [comment]
Fwiw, the use case for this particular drop case was to prevent network virus scanners from connecting to ompi jobs and confusing the TCP btl. This was a "good enough" fox for this particular use case. 

Sent from my phone. No type good.

**Comment by d-a-v** [comment]
@jsquyres 
I tried your patch along @bosilca's and here is what I got.

the string was not complete, here is how I wrote it. I also had to replace the alloca() by a static string because for some reasons I got segfaults - I just wanted to see the message:

```
opal_output_verbose(0, opal_btl_base_framework.framework_output,
        "btl: tcp: Incoming connection from %s does not match known addresses for peer %s [hostname=%s addr=%s]. Drop !\n",
        opal_net_get_hostname((struct sockaddr*)addr),
        OPAL_NAME_PRINT(btl_proc->proc_opal->proc_name),
        btl_proc->proc_opal->proc_hostname,
        addr_str);
```

result:
> [066679d8982a:00019] btl: tcp: Incoming connection from 10.242.1.1 does not match known addresses for peer [[41818,1],1] [hostname=7109145c5b71 addr=10.243.1.2]. Drop !

compared to previous:
> [066679d8982a:00019] btl: tcp: Incoming connection from 10.242.1.1 does not match known addresses for peer [[41818,1],1]. Drop !

This is indeed even more informative regarding the nat operation.
However, I don't understand why you put 20 instead of 0 into the loglevel parameter.

**Comment by d-a-v** [comment]
merged. /me thanks everyone
