### ISSUE TITLE
MPI_Comm_accept/MPI_Comm_connect did not work in singleton mode on 2.0.1

### ISSUE THREAD

**Issue by BrightWise** [open-mpi/ompi#2363]
I wrote server/client samples which using MPI_Comm_accept/MPI_Comm_connect to establish communications; however, the connection always failed with timeout after 60s whether mpirun is used or not:

Trying connect to 1843354423.0:3874605820
[host:12176] OPAL ERROR: Timeout in file base/pmix_base_fns.c at line 193
[host:12176] *** An error occurred in MPI_Comm_connect
[host:12176] *** reported by process [139843593111247,0]
[host:12176] *** on communicator MPI_COMM_SELF
[host:12176] *** MPI_ERR_UNKNOWN: unknown error
[host:12176] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[host:12176] ***    and potentially your MPI job)

BTW, I also ran the same samples on v1.10.4, and it worked.
I found that the port name generated from MPI_Open_port is a little different between 2.x and 1.x . Is this normal?
sample of 1.x : 3797352448.0;tcp://10.152.111.82,169.254.182.77:14343+3797352449.0;tcp://10.152.111.82,169.254.182.77::300
sanple of 2.x:
596325946.0:4290806060

**Comment by rhc54** [comment]
This is being fixed in v2.0.2 - patch is waiting for commit
