### ISSUE TITLE
CUDA-aware MPI with non-blocking cudaStream

### ISSUE THREAD

**Issue by hujiePKU** [open-mpi/ompi#2390]
Excuse me, I want to do CUDA-aware MPI communication in a host thread, but the default MPI setting is using cudaDefaultStream, which would blocking the main thread kernel-function. So how can I replace the defaultStream with non-blocking stream created by cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking) . Thank you very much!

**Comment by sjeaugey** [comment]
The CUDA-aware part of MPI should only be using asynchronous streams, not cudaStreamDefault. So, in theory, you should already have what you need.

**Comment by hujiePKU** [comment]
I got it, thank you for your reply. Since there is no interface to set cudaStream in MPI environment,  I always think that it use the cudaStreamDefault.

**Comment by jsquyres** [comment]
Looks like your question was answered; I'm closing this issue.  Feel free to re-open if you need further discussion on this topic.
