### ISSUE TITLE
Using mpirun on macOS with PETSc

### ISSUE THREAD

**Issue by devkhan** [open-mpi/ompi#2394]
I'm seeing the below error while running a project while running a binary with `mpirun` which depends on PETSc:

```
dyld: Library not loaded: /usr/local/opt/open-mpi/lib/libmpi_usempi_ignore_tkr.20.dylib
  Referenced from: /usr/local/opt/petsc/real/lib/libpetsc.3.7.dylib
  Reason: image not found
--------------------------------------------------------------------------
mpirun noticed that process rank 2 with PID 0 on node xxxxxxxxxxxx exited on signal 6 (Abort trap: 6).
```

Inside `/usr/local/opt/open-mpi/lib/`:

```
total 5816
-r--r--r--   1 admin   13880 Nov  9 23:36 libmca_common_sm.20.dylib
lrwxr-xr-x   1 admin      25 Nov  9 23:36 libmca_common_sm.dylib -> libmca_common_sm.20.dylib
-r--r--r--   1 admin  916988 Nov  9 23:36 libmpi.20.dylib
lrwxr-xr-x   1 admin      15 Nov  9 23:36 libmpi.dylib -> libmpi.20.dylib
-r--r--r--   1 admin   85252 Nov  9 23:36 libmpi_cxx.20.dylib
lrwxr-xr-x   1 admin      19 Nov  9 23:36 libmpi_cxx.dylib -> libmpi_cxx.20.dylib
-r--r--r--   1 admin  131364 Nov  9 23:36 libmpi_java.20.dylib
lrwxr-xr-x   1 admin      20 Nov  9 23:36 libmpi_java.dylib -> libmpi_java.20.dylib
-r--r--r--   1 admin  327328 Nov  9 23:36 libmpi_mpifh.20.dylib
lrwxr-xr-x   1 admin      21 Nov  9 23:36 libmpi_mpifh.dylib -> libmpi_mpifh.20.dylib
-r--r--r--   1 admin   30864 Nov  9 23:36 libmpi_usempi_ignore_tkr.a
-r--r--r--   1 admin  249968 Nov  9 23:36 libmpi_usempif08.20.dylib
lrwxr-xr-x   1 admin      25 Nov  9 23:36 libmpi_usempif08.dylib -> libmpi_usempif08.20.dylib
-r--r--r--   1 admin   19388 Nov  9 23:36 libompitrace.20.dylib
lrwxr-xr-x   1 admin      21 Nov  9 23:36 libompitrace.dylib -> libompitrace.20.dylib
-r--r--r--   1 admin  609760 Nov  9 23:36 libopen-pal.20.dylib
lrwxr-xr-x   1 admin      20 Nov  9 23:36 libopen-pal.dylib -> libopen-pal.20.dylib
-r--r--r--   1 admin  474060 Nov  9 23:36 libopen-rte.20.dylib
lrwxr-xr-x   1 admin      20 Nov  9 23:36 libopen-rte.dylib -> libopen-rte.20.dylib
-r--r--r--   1 admin   64972 Nov  9 23:36 mpi.jar
drwxr-xr-x  96 admin    3264 Nov  9 23:36 openmpi
drwxr-xr-x   9 admin     306 Nov  9 23:36 pkgconfig
```

`open-mpi` is installed using `brew` from `science` tap. I tried running `mpirun -n echo 'Hello'`, and it worked fine. I'm not sure if this is an issue with `open-mpi` or `PETSc`, so apologies and please let me know if I need to post this on `PETSc`.

**Comment by jsquyres** [comment]
What happens if you compile / run a simple MPI program (e.g., hello world, or ring -- see https://github.com/open-mpi/ompi/blob/master/examples/hello_usempi.f90 and https://github.com/open-mpi/ompi/blob/master/examples/ring_usempi.f90)?

**Comment by devkhan** [comment]
I'm not able to compile the fortran example that you gave, but other simple commands and binaries are working fine with `mpirun`. The problem is occurring when a binary refers `PETSc` and `PETSc` is dependent on `libmpi_usempi_ignore_tkr.20.dylib`, which doesn't exist (although a `libmpi_usempi_ignore_tkr.a` is available).

**Comment by devkhan** [comment]
Update: The C++ example worked fine.

**Comment by ggouaillardet** [comment]
@devkhan at first glance, it seems PETSc was not built against the Open MPI you are using.

how did you install Open MPI ?
i could not find any recipe in the science tap https://github.com/Homebrew/homebrew-science
```
brew install homebrew/science/open-mpi
brew install homebrew/science/openmpi
````
none of these command work ...

maybe you should try the "stock" Open MPI
```
brew install open-mpi
```
the missing file is in ```/usr/local/Cellar/open-mpi/lib```

**Comment by devkhan** [comment]
Yes, apologies for the misstatement, `open-mpi` was installed from the default tap. But the missing file is still not in `/usr/local/Cellar/open-mpi/lib`, in fact `/usr/local/opt/open-mpi` is just a symlink to `/usr/local/Cellar/open-mpi/2.0.1/`.

I'll try re-installing it and update here.

**Comment by ggouaillardet** [comment]
this is what i have on yosemite

```
$ ls -l /usr/local/Cellar/open-mpi/2.0.1/lib/libmpi_usempi_ignore_tkr.*
-r--r--r--  1 gilles  admin  38120 Nov 11 10:48 /usr/local/Cellar/open-mpi/2.0.1/lib/libmpi_usempi_ignore_tkr.20.dylib
lrwxr-xr-x  1 gilles  admin     33 Sep  3 05:09 /usr/local/Cellar/open-mpi/2.0.1/lib/libmpi_usempi_ignore_tkr.dylib -> libmpi_usempi_ignore_tkr.20.dylib
```

which flavour of OS X are you running on ?

**Comment by rhc54** [comment]
Please reopen if you continue to have issues
