### ISSUE TITLE
Problem about CUDA-aware MPI effiency 

### ISSUE THREAD

**Issue by hujiePKU** [open-mpi/ompi#2397]
I try to use CUDA-awre MPI and normal-MPI( cudaMemcpy and communicate by cpu)  respectively to do MPI_Allreduce at NVIDIA Tesla M40 by openmpi-1.8.5 and openmpi-2.0.1 complied with --with-cuda. The Tesla chip support GPUDirect, but I found that using CUDA_aware MPI is extremely slowly than normal-MPI. I want to know whether something wrong in my code.

source code:
#define ENV_LOCAL_RANK "OMPI_COMM_WORLD_LOCAL_RANK"

void SetDeviceBeforeInit() {
  char *localRankStr = NULL;
  int rank = 0, devCount = 0;
  cudaError_t cudaStat;
  // We extract the local rank initialization using an environment variable
  if ((localRankStr = getenv(ENV_LOCAL_RANK)) != NULL) {
    rank = atoi(localRankStr);
  }

  cudaDeviceReset();
  cudaThreadExit();

  cudaGetDeviceCount(&devCount);
  LOG(INFO) << "Device count " << devCount << " Rank: " << rank % devCount;

  cudaStat = cudaSetDevice(rank % devCount);
  if(cudaStat != cudaSuccess)
    LOG(FATAL) << "ERROR DEVICE SET FAILED\n";
}

int main(int argc, char** argv) {
  SetDeviceBeforeInit();

  MPI_Init(&argc, &argv);
  int rank, size;
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  MPI_Comm_size(MPI_COMM_WORLD, &size);

  const int strategy(atoi(argv[1]));
  const int count = 10000;

  float *data_gpu = NULL;
  float *data_cpu = NULL;
  size_t data_size = count * sizeof(float);
  cudaMalloc((void**)&data_gpu, data_size);
  cudaMallocHost((void**)&data_cpu, data_size);

  double t1, t2;
  t1 = MPI_Wtime();
  MPI_Barrier(MPI_COMM_WORLD);
  if (strategy == 0)
    MPI_CHECK(MPI_Allreduce(MPI_IN_PLACE, (void*)data_gpu, count, MPI_FLOAT, MPI_SUM, MPI_COMM_WORLD));
  else {
    cudaMemcpy((void*)data_cpu, (void*)data_gpu, data_size, cudaMemcpyDeviceToHost);
    MPI_CHECK(MPI_Allreduce(MPI_IN_PLACE, (void*)data_cpu, count, MPI_FLOAT, MPI_SUM, MPI_COMM_WORLD));
    cudaMemcpy((void*)data_gpu, (void*)data_cpu, data_size, cudaMemcpyHostToDevice);
  }
  t2 = MPI_Wtime();
  std::cout << "communication time " << t2-t1 << " second.\n";

  cudaFreeHost((void*)data_cpu);
  cudaFree((void*)data_gpu);
  MPI_Finalize();
}

----------------------------------------------
mpirun -np 2 ./test
CUDA-aware MPI use time: 0.08s
Normal MPI use time: 0.0002s

**Comment by sjeaugey** [comment]
Benchmarking only a single 40000 bytes operation can give hard to understand results. The first operation can take substantial time (in your case 8ms) to setup everything. The next (same) operations would likely be much faster. In the case of CUDA aware MPI, it may actually still steup things during the second transfer. So, if you want to benchmark speed of operations, you should probable warm-up the library, doing a couple of operations, then benchmark it.

Also, 40kB is small, so to time is small and the precision of MPI_Wtime() may not be sufficient, so most benchmarks do a repetition of 100 to 1000 operations and divide the time by that number (though that may bias the benchmark due to cache effects).

Finally, you should take the start time after the MPI Barrier, otherwise, a late process would make the barrier take a long time and you would not benchmark the allreduce operation only.

**Comment by hujiePKU** [comment]
I modified the start time after the MPI Barrier and did a repetition of 10000 and 100000 operations respectively to Allreduce 40000 bytes in a for circulation, but the result is that CUDA-aware MPI is still slower than normal cudaMemcpy strategy.
                                        10000 times                100000 times
CUDA-aware MPI               0.6794 s                     5.4254 s
Normal MPI                         0.5149 s                    4.3559 s

**Comment by bosilca** [comment]
I have modified the test to compile and do what it was supposed to [cuda_allreduce.cc](https://gist.github.com/bosilca/34c289c62bd6e3bb439dfc1f11bcef00). I have noticed similar performance as reported here, and after investigation it appears that the current MPI_Allreduce moves everything back on the CPU before doing the reduction. Thus, allocating and freeing the temporary memory, plus copying the data from and then to the devices, accounts for the extra overhead noticed.

**Comment by hujiePKU** [comment]
It means that the current MPI_Allreduce even all p2p and collective MPI don't support GPUDirect yet, so it still need to pass by CPU-memory. Is it right?

**Comment by bosilca** [comment]
I never mentionned anything about point-to-point. As I said  in my comment, MPI_Allreduce in the 2.0.1 (and prior) transfer the data to the CPU before doing the collective, and then transfer it back. This behavior seems to only be restricted to collective communications, point-to-point take advantage of GPUDirect (and other techniques) when available.

**Comment by hujiePKU** [comment]
I got it. Thank you for your attention and patience! I really except GPUDirect technique can be available for collective communications in the near future.

**Comment by leofang** [comment]
I found this thread from google. It seems that MPI_Allreduce still has similar bad performance in v3.1.1, am I right? I saw that it still copies the array from device to host (via async), does the reduction on host, and then transfers back to device.

**Comment by kose-y** [comment]
https://github.com/open-mpi/ompi/blob/98afc838aa53da88cba339f6dcbab256806a5745/ompi/mca/coll/cuda/coll_cuda_reduce.c

Just putting the related code for future reference.

**Comment by jakub-homola** [comment]
Just for completeness, this is a situation where [NCCL](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/collectives.html#allreduce) (NVIDIA Collective Communications Library) could be used. It is a library for collective communications directly between GPUs.
