### ISSUE TITLE
LLNL STAT tool not working with v2.0.2

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2411]
Per verbal report from @rhc54 on the show floor here at SC, apparently STAT is not working properly with v2.0.2.  Need to get this fixed.

**Comment by hppritcha** [comment]
Per discussion at the devel core meeting on 11/22 remove blocker label.  Can be fixed in a 2.0.3 release.

**Comment by hppritcha** [comment]
removing blocker label per devel core discussion 11/22.

**Comment by jsquyres** [comment]
Looks like this was fixed in #2425.
