### ISSUE TITLE
Cannot (intuitively) autoconf/CMake test for shmemx.h

### ISSUE THREAD

**Issue by nspark** [open-mpi/ompi#2483]
When testing for `shmemx.h` with autoconf's [`AC_CHECK_HEADER`](https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Generic-Headers.html), one has to explicitly specify `shmem.h` as an include prerequisite.

When testing for `shmemx.h` with CMake:
* [`CHECK_INCLUDE_FILE`](https://cmake.org/cmake/help/latest/module/CheckIncludeFile.html) fails because the dependence on `shmem.h` cannot be specified.
* [`CHECK_INCLUDE_FILES`](https://cmake.org/cmake/help/latest/module/CheckIncludeFiles.html) can be used by testing for both `shmem.h` and `shmemx.h` (in order) in a single test.

This is at best unintuitive behavior for users and can easily be fixed by including `shmem.h` from within `shmemx.h`.

**Comment by jsquyres** [comment]
@jladd-mlnx Per https://github.com/openshmem-org/specification/pull/27#issuecomment-264028864, it looks like the recommendation is to have `shmemx.h` be a standalone unit (i.e., not require including `shmem.h` beforehand).  Can that be done?

Or is there a reason to not `#include <shmem.h>` at the top of `shmemx.h`?

**Comment by nspark** [comment]
@jsquyres By "standalone unit", I think @BryantLam means that an autoconf/CMake test for `shmemx.h` shouldn't require explicit inclusion of `shmem.h` as a prerequisite. If `shmemx.h` includes `shmem.h` at its top as a way to satisfy that goal, that seems sufficient.

**Comment by jdinan** [comment]
Also, it should be valid for a user to include the SHMEM headers in any order.  It sounds like the following would not work with the current ```shmemx.h``` header:
```
#include <shmemx.h>
#include <shmem.h>
...
```

**Comment by jladd-mlnx** [comment]
This can be done. I will take care of it.

Josh

**Comment by jsquyres** [comment]
@jladd-mlnx @alex-mikheev Do you have any desire to PR this to the v2.0.x and/or v2.x series?

**Comment by jladd-mlnx** [comment]
Yes. Will do today.
