### ISSUE TITLE
Systematic Slowing down of mpi task

### ISSUE THREAD

**Issue by hujiePKU** [open-mpi/ompi#2495]
I find that the MPI task will slow down along with the procedure running some time. I try v1.8.5 and v2.0.1, the issue are the same.  The most tasks in my procedure is collective communication(Allreduce), I don't think it is a memory leak. When I clean the systematic cached memory manually, the procedure will recovery to normal speed. Does anyone meet the similar problem? Should I require some macro setting in MPI compile or running? Ask for a valid solution please.

**Comment by ggouaillardet** [comment]
@hujiePKU can you post a trimmed version of your program that can evidence the drop in performance and provide some more context (number of nodes, tasks per node, interconnect, how you "clean the cached memory")
