### ISSUE TITLE
arm_detection on Debian systems

### ISSUE THREAD

**Issue by amckinstry** [open-mpi/ompi#2514]
Attached is a patch used to detect "armhf" and "armel" architectures on Debian.
This patch has been used on Debian since 2012 ; no record locally of whether it has been forwarded to openmpi.org.

**Comment by ggouaillardet** [comment]
@amckinstry there is no attachment ...

**Comment by amckinstry** [comment]
[Uploading arm_detection.txt…]()
[Uploading arm_detection.zip…]()

**Comment by amckinstry** [comment]
Sorry, script blocker stopped the upload.

[arm_detection.txt](https://github.com/open-mpi/ompi/files/630908/arm_detection.txt)

**Comment by ggouaillardet** [comment]
@amckinstry does (auto-generated) configure need to be patched too ?
i guess only the m4 file need to be patched, and then autogen.pl has to be run.

**Comment by amckinstry** [comment]
Only the m4 file; autogen.pl automatically run on debian builds
