### ISSUE TITLE
Make builds bit-reproducible

### ISSUE THREAD

**Issue by amckinstry** [open-mpi/ompi#2518]
Debian has an ongoing initiative to make all builds bit-reproducible, for security and verification. As part of this, we need to avoid including date and timestrings, build paths, etc. from the binaries.
Currently we apply the following patch; would you please consider either removing __DATE__ or adding BIT_REPRODUCIBLE as a build-flag to avoid such constructs?

Thanks
Alastair McKinstry <mckinstry@debian.org>

```patch
Author: Alastair McKinstry <mckinstry@debian.org>
Description: Remove __DATE__ timestamps to make build bit-reproducible.
 Also: Sort file lists that are globbed. See https://bugs.debian.org/824263
Forwarded: no
Last-Updated: 2016-05-23

Index: openmpi-2.0.1/ompi/debuggers/ompi_msgq_dll.c
===================================================================
--- openmpi-2.0.1.orig/ompi/debuggers/ompi_msgq_dll.c
+++ openmpi-2.0.1/ompi/debuggers/ompi_msgq_dll.c
@@ -189,7 +189,7 @@ int mqs_version_compatibility (void)
 char *mqs_version_string (void)
 {
     return "Open MPI message queue support for parallel"
-           " debuggers compiled on " __DATE__;
+      " debuggers, Debian version ";
 } /* mqs_version_string */

 /* So the debugger can tell what interface width the library was compiled with */
```

**Comment by ggouaillardet** [comment]
@amckinstry is there a macro we can test instead ?
if not, does debian configure with --enable-debug ? we could then use this macro

**Comment by amckinstry** [comment]
There isn't an "official" macro yet, just patches for each package.
I'm using -DHAVE_BIT_REPRODUCIBLE with feature BIT_REPRODUCIBLE in CMake, which seems to be common, so maybe 
#ifdef HAVE_BIT_REPRODUCIBLE
would be enough, with perhaps --enable-bit-reproducible  for configure.

Note we intend to push bit-reproducibility as a common feature throughout open-source, but a bunch of patches to tools like gcc, etc. need to make their way through the system so that builds are reproducible outside Debian, as there are a lot of reasons why bit-repr. fails today.

**Comment by ggouaillardet** [comment]
@jsquyres any thoughts on that ?

as far as i am concerned, i am fine making Open MPI bit reproducible, even by default.
an option is to add yet an other configury option.
that being said, i do not see much value in displaying the compilation date ```__DATE__``` here.
could we replace it with ```OMPI_REPO_REV``` or the date the tarball was built.
i do not think there is such a macro yet, and as previously discussed, ```OMPI_REPO_REV``` is counter intuitive (```master``` branch is reported as ```v2.x-dev``` and so on)

**Comment by gpaulsen** [comment]
I'd think as long as we always pull the embedded date from the VERSION file, it should be acceptable.

**Comment by jsquyres** [comment]
@ggouaillardet @gpaulsen I agree -- that `__DATE__` isn't likely necessary in that string.  It would likely be ok to replace it with `OMPI_REPO_REV`.

**Comment by ggouaillardet** [comment]
so we can either use ```OMPI_REPO_REV``` or ```OMPI_RELEASE_DATE```
any preference ?

**Comment by jsquyres** [comment]
Come to think of it, neither of these things (`OMPI_REPO_REV` and `OMPI_RELEASE_DATE`) are immediately / obviously meaningful to a user to indicate what version of the Open MPI debug DLL they have.  Is there a reason we don't do something similar to (and perhaps slightly simpler than) what we do in `ompi/c/get_library_version.c`?

I suspect that the current string exists the way it does as a simple hack such that we didn't have to alloc any memory (and potentially leak it).  Two obvious suggestions jump out here:

1. Alloc memory / create the string once during the DLL startup, and the free it during the DLL shutdown (there's appropriate startup / shutdown hooks for such things).
1. Use a large, static char array (e.g., `char ompi_dll_version_string[256]`), and put appropriate safeguards to make sure we don't overwrite the end of that array.

**Comment by gpaulsen** [comment]
It is nice to have SOMETHING embedded in the binary for other tools to parse out.  It would be preferable to have both the version, AND a build date in that string, since the two of those should be able to somewhat uniquely identify any given library (and the library name).
It's also nice to have an API that returns something similar for tools that dlopen and dlsym to be able to make decisions about.  That shouldn't matter for all of our internal libraries, but might as well solve this problem once for each .so created.

**Comment by jsquyres** [comment]
@gpaulsen and I talked in IM.  We agree that having the same string from MPI_GET_LIBRARY_VERSION would likely be ok here.  Having the date when the tarball was built is not that important (note: the MPI_GET_LIBRARY_VERSION string includes the date that the tarball was *created* -- i.e., when it was *released* -- which will obviously stay the same regardless of whether you build that tarball today or next week).

**Comment by ggouaillardet** [comment]
i made #2543 to address this, can you please review ?

**Comment by amckinstry** [comment]
Looks good.
