### ISSUE TITLE
ROMIO+Lustre problems in OpenMPI 1.8.3

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#255]
A regression in OpenMPI 1.8.3 pertaining to configuring of romio with lustre support requested
has been reported.

http://www.open-mpi.org/community/lists/devel/2014/10/16106.php

This appears to be a regression from earlier 1.8 releases.

**Comment by jsquyres** [comment]
Is this related to http://www.open-mpi.org/community/lists/users/2015/01/26180.php ?

**Comment by roblatham00** [comment]
jeff, no, it's not related.  This iissue is when some luster header files and system header files are incompatible if X_OPEN_SOURCE set sufficiently high.   I want pread/pwrite, so I set X_OPEN_SOURCE, but then  quota.h tries to use some value that is incompatible with X_OPEN_SOURCE set that high. 

proper fix:  romio should not set X_OPEN_SOURCE and should implement a pread/pwrite (that simply calls seek + read/write) which romio can use if pread/pwrite unavailable,.

**Comment by hppritcha** [comment]
Rob, thanks for the explanation.  Would you take a patch to - at least for Lustre - that fixes romio per your suggestion?

**Comment by roblatham00** [comment]
I've got one under review! Meant to push it before I went on vacation.

**Comment by roblatham00** [comment]
If you want to cherry pick a fix from MPICH, the commits are these two:
- check for pwrite, provide our own version:  http://git.mpich.org/mpich.git/commit/4e80e1d2b9
- remove the troublesome X_OPEN_SOURCE declarations: http://git.mpich.org/mpich.git/commit/5a10283bf7fd
