### ISSUE TITLE
Stale variable in plm/slurm?

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#2569]
It seems that `launching_daemons` variable introduced in f11931306ab0cee4bbccd983462680f66f40db87 is not relevan anymore. I don't see any usage of it now. So I guess a dead code here:
https://github.com/open-mpi/ompi/blob/v2.x/orte/mca/plm/slurm/plm_slurm_module.c#L550:L557

This is relevant to master and v2.x/v2.0.x/1.10 and even 1.8/1.8.1 :)

@rhc54 could you take a look and confirm?

**Comment by rhc54** [comment]
Actually, that code still looks relevant to me - I suspect the flag should be getting set in the ```plm_slurm_start_proc``` function, and then cleared once the daemons are successfully started.

**Comment by artpol84** [comment]
I think that after bd8b4f7f1eff729d53c0a8b090d9f979c21230b2 (which is quite huge!) the usage of this variable was vanished:
https://github.com/open-mpi/ompi/commit/bd8b4f7f1eff729d53c0a8b090d9f979c21230b2#diff-359a4fb5d7888b070863796d3532c416L219

**Comment by artpol84** [comment]
Was this addressed or ignored?

**Comment by rhc54** [comment]
I believe the answer is simply that (a) it doesn't seem to be having any negative effects, and (b) if you care, then please submit a patch. Otherwise, no point in letting this sit around if nobody is going to address it - and I won't 😄
