### ISSUE TITLE
Routed RML message ordering problem

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#26]
From Ralph and Jeff: With the current RML retransmission scheme, we have a possible message ordering problem.  That is, if the RML queues up a message to transmit later, lots of other messages may (and frequently do) get transmitted successfully before the event timer wakes up and transmits the one message that was queued up.

This does not seem to affect overall functionality -- everything seems to work fine.  But I'm wondering if that's a side effect of how we use the RML/OOB and not really because it's bug-free. Specifically, I think that this RML queueing functionality is currently triggered either during an all-to-one or one-to-all kind of communication pattern.  So the ordering doesn't really matter.

But consider the following scenario:
- process A RML sends message 1 to process B
- the route map is not yet setup, so the message gets queued
- the route map arrives and process A sets itself up properly
- process A RML sends message 2 to process B on the same OOB tag as message 1
- process B receives message 2
- process A's event timer wakes up and transmits message 1
- process B receives message 1

Process B clearly gets these messages out of order.

I believe this could be very bad as we move away from an event-driven system to one that is message-driven as message ordering could have a major impact on behavior.

What we would really like to see happen, IMHO, is for the queued message to be delivered -immediately- when the contact info becomes known, and not wait for some arbitrary clock to tick down. The queued message(s) should go to the head of the line when that contact info shows up, in the order in which they were received.

Otherwise, we could get into some significant ordering issues once the next major ORTE update hits since all control logic will be sent via RML.

The current problem only shows up on startup during the allgather in modex, so it isn't a problem as (a) it is the collector that is slow to provide its contact info, and (b) the entire startup blocks on the collector getting all of the required info. I -suspect- we might therefore ride through this problem, but again, it is a "bug" that could easily bite us. Just can't predict where/when at the moment.

**Comment by rhc54** [comment]
It is ordered now as things are event-driven
