### ISSUE TITLE
PGI Fortran: link failure with Mac OS X

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#2604]
@PHHargrove 's testing of the 2.0.2rc1 with PGI 16.10 compiler showed issues with symbol relocation problems for code generated with PGI's fortran compiler:

https://mail-archive.com/devel@lists.open-mpi.org/msg19823.html

**Comment by PHHargrove** [comment]
Retest w/ Open MPI 3.0.0rc1 and PGI-17.4 shows that nothing has changed.

**Comment by hppritcha** [comment]
@sjeaugey we need to know whether or not Nvidia will be supporting PGI on OS-x.   If not, then we will indicate in the README that we don't support PGI on OS-x for Open MPI.

**Comment by hppritcha** [comment]
@gvallee here's on of the PGI related issues

**Comment by gvallee** [comment]
No news from PGI yet but we are trying to reach them again.

**Comment by gvallee** [comment]
PGI said it has been forwarded to the appropriate developer but did not give a timeframe for a potential fix.

**Comment by hppritcha** [comment]
not going to address in 2.0.4.

**Comment by hppritcha** [comment]
closed due to age.
