### ISSUE TITLE
PGI: libevent build failure on Mac OS-x

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#2605]
libevent has a configury problem that prevents building the OMPI internal version of libevent 
on OS-X when using PGI compilers (including 16.10).

The problem is described in more detail in this posting to devel:

https://mail-archive.com/devel@lists.open-mpi.org/msg19824.html

**Comment by hppritcha** [comment]
@sjeaugey any updates for this issue?

**Comment by sjeaugey** [comment]
I'm not sure what we should do on our side. Reading Paul's email, it seems someone added this GCC-specific flag which broke compilation with PGI on darwin. Should we remove it ? Or only add this flag when the compiler is GCC ?

**Comment by jsquyres** [comment]
@sjeaugey Agreed -- it seems like libevent's configury is incorrectly adding that compiler flag.  It seems like it would be a relatively straightforward configury fix (although for best results, it should probably also be sent upstream to libevent).  Can you supply a PR?

**Comment by hppritcha** [comment]
Another case of updating the README to indicate that we don't support PGI on OS-x.

**Comment by hppritcha** [comment]
@gvallee and here's another one.

**Comment by hppritcha** [comment]
closing.
