### ISSUE TITLE
Memory footprint

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#2650]
This issue is here just to track the memory footprint reduction efforts. We will post results tagged to master hashes here.

**Comment by rhc54** [comment]
@hjelmn @artpol84

**Comment by jsquyres** [comment]
@rhc54 I think there was a lot of work on this over the past 2 weeks -- is it worth posting updates here, or did those tracking updates go elsewhere?

**Comment by rhc54** [comment]
They just went to the specific tags, so no central tracking.
