### ISSUE TITLE
mpirun fails to spawn process across multiple nodes

### ISSUE THREAD

**Issue by puneet336** [open-mpi/ompi#2661]
Dear All,
I had compiled nas 3.3 BT benchmark (as well as CG,DT) using openmpi 2.0.1 compilers (compiled with gcc 4.4.7). 
The initial test for spawn:-
[spuneet.vfaculty@host02 bin]$ mpirun -np 4 -npernode 1 -machinefile hosts.txt /bin/hostname 
host01
host02
host03
host04

Now the Application spawning (which fails):-
 [puneet@host02 bin]$ mpirun -np 4 -npernode 1 -machinefile hosts.txt ./bt.E.4.mpi_io_full 
mpirun noticed that process rank 0 with PID 21183 on node host01 exited on signal 9 (Killed).
[puneet@host02 bin]$ echo $?
137

 [puneet@host02 bin]$ mpirun -np 4 -npernode 4 -machinefile hosts.txt ./bt.E.4.mpi_io_full 

 NAS Parallel Benchmarks 3.3 -- BT Benchmark 

 No input file inputbt.data. Using compiled defaults
 Size: 1020x1020x1020
 Iterations:  250    dt:   0.0000040
 Number of active processes:     4

 BTIO -- FULL MPI-IO write interval:   5

I had compiled NPB with mcmodel=medium.
Could this be a compiler bug?

**Comment by ggouaillardet** [comment]
Can you run 
dmesg
on all your nodes and double check the MPI tasks were not killed by the oom killer ?

**Comment by puneet336** [comment]
Hi,
I had contacted the developer.
As per him, every rank requires atleast 98GB  per rank. Whereas i have 64GB per node.
I do have some 512GB nodes. I will soon test & report my observations.
