### ISSUE TITLE
undefined symbol: orte_schizo_base_framework with dynamic build and python bindings

### ISSUE THREAD

**Issue by marksantcroos** [open-mpi/ompi#2663]
Hi @rhc54 ,

When using the latest master, with a dynamic build, and using the Python bindings, I get the warnings show below and resulting program doesn't work.
The equivalent C code works fine.
If I run the same Python script against a static build it works too.
Any idea?

Thanks!

Mark

```
[titan-login3:24063] mca_base_component_repository_open: unable to open mca_schizo_flux: /lustre/atlas/world-shared/bip103/openmpi/jan4-dyn/lib/openmpi/mca_schizo_flux.so: undefined symbol: orte_schizo_base_framework (ignored)
[titan-login3:24063] mca_base_component_repository_open: unable to open mca_schizo_ompi: /lustre/atlas/world-shared/bip103/openmpi/jan4-dyn/lib/openmpi/mca_schizo_ompi.so: undefined symbol: orte_schizo_base_framework (ignored)
[titan-login3:24063] mca_base_component_repository_open: unable to open mca_schizo_alps: /lustre/atlas/world-shared/bip103/openmpi/jan4-dyn/lib/openmpi/mca_schizo_alps.so: undefined symbol: orte_schizo_base_framework (ignored)
[titan-login3:24063] mca_base_component_repository_open: unable to open mca_schizo_slurm: /lustre/atlas/world-shared/bip103/openmpi/jan4-dyn/lib/openmpi/mca_schizo_slurm.so: undefined symbol: orte_schizo_base_framework (ignored)
[titan-login3:24063] mca_base_component_repository_open: unable to open mca_schizo_orte: /lustre/atlas/world-shared/bip103/openmpi/jan4-dyn/lib/openmpi/mca_schizo_orte.so: undefined symbol: orte_schizo_base_framework (ignored)
```

**Comment by marksantcroos** [comment]
> If you look in libopen-rte, do you see that symbol?

Yes, which is no surprise I guess, as otherwise I would have had the same issue for the CLI and C version:
```
> nm -D libopen-rte.so|grep orte_schizo_base_framework
00000000002e49c0 D orte_schizo_base_framework
```
Is there anything special about these symbols or might they just be the first that are looked up?

**Comment by rhc54** [comment]
Nothing special - and as I said, it seems to be instantiated and exported. If you grep for "base_framework", you should see all the frameworks since they all have the same symbol.

**Comment by ggouaillardet** [comment]
@marksantcroos iirc, a similar issue was previously reported.
The root cause was libmpi.so was dlopen'ed without the ```RTLD_NOW``` flag.
In your case, an other option is to configure Open MPI with ```--disable-dlopen```

**Comment by marksantcroos** [comment]
> The root cause was libmpi.so was dlopen'ed without the RTLD_NOW flag.

From what I can see CFFI does use RTLD_NOW for dlopen(). It might be a Cray specific issue.

> In your case, an other option is to configure Open MPI with --disable-dlopen

Thanks for the reminder on that flag, building a release with that now.

**Comment by marksantcroos** [comment]
> In your case, an other option is to configure Open MPI with --disable-dlopen

That does the trick indeed.

This is good enough, thanks both!
