### ISSUE TITLE
OS-X: opal_fifo test fails when using OS-X builtin atomics config option

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#2666]
@PHHargrove has reported a hang in the opal_fifo test:

```
On Macs running Yosemite (OS X 10.10 w/ Xcode 7.1) and El Capitan (OS X 10.11 w/ Xcode 8.1) I have configured with
    CC=cc CXX=c++ FC=/sw/bin/gfortran --prefix=... --enable-osx-builtin-atomics

Upon running "make check", the test "opal_fifo" hangs on both systems.
Without the --enable-osx-builtin-atomics things are fine.

I don't have data for Sierra (10.12).
```

link to original posting on devel:

https://www.mail-archive.com/devel@lists.open-mpi.org/msg19860.html

I'm having problems reproducing this on my mac running El Capitan.

**Comment by bosilca** [comment]
I cannot reproduce this on macSierra (.1 and .2) on an OMPI configured with --enable-osx-builtin-atomics.

**Comment by hppritcha** [comment]
@bosilca were you testing with master or with v2.0.x?

**Comment by hppritcha** [comment]
I checked both master and v2.0.x and can't reproduce the problem.  

However, I'm noticing on master that I can't seem to get the configury to set ```OPAL_ASSEMBLY_BUILTING == OPAL_BUILTIN_OSX```
in opal_config.h

It behaves correctly on 2.0.x.

**Comment by bosilca** [comment]
I used master.

**Comment by hjelmn** [comment]
At some point we should probably disable this option. Apple deprecated their atomics in favor of the ones in c11/c++11.

**Comment by PHHargrove** [comment]
I have tested on Sierra and don't see the problem there.  
I will retest the El Capitan system after it finishes installing system updates.  
The Yosemite system is definitely showing the problem.

**Comment by hppritcha** [comment]
How many cores do these systems have?

**Comment by PHHargrove** [comment]
> How many cores do these systems have?

The Yosemite and El Capitan systems each have just 2 cores.
However, the test was running for over 8 hours on the Yosemite system before I noticed it was hung.
Additionally, all of "make check" takes about 1 minute when I don't enable the OSX builtin atomics.

**Comment by PHHargrove** [comment]
After allowing OS X to reboot to complete installation of updates, the El Capitan system is OK now.
Therefore, I suspect the "hang" on that system may not have been genuine.

I am suspicious now that this may be Apple's bug.

**Comment by hppritcha** [comment]
Per discussion in the devel con today, closing this for now.

**Comment by PHHargrove** [comment]
Just for the record, this hang occurred again in my testing of 2.1.0rc2 on Yosemite.  
I am not concerned too much since this is only occurring with a non-default configure option, which in-turn is planned for removal in 3.0 (https://github.com/open-mpi/ompi/issues/2668)
