### ISSUE TITLE
Build problem on Cray XC30

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#2674]
I'm getting the following link error, even though the required libraries exist:

```shell
11:18:13  (master) ~/ompi/opal/mca/common/verbs$ make V=1
/bin/sh ../../../../libtool  --tag=CC   --mode=link gcc -std=gnu99  -g -Wall -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -pedantic -Werror-implicit-function-declaration -finline-functions -fno-strict-aliasing -mcx16 -pthread -version-info 0:0:0   -o libmca_common_verbs.la -rpath /cray_home/rhcastai/ompi/build/ompi/lib  libmca_common_verbs_la-common_verbs_basics.lo libmca_common_verbs_la-common_verbs_devlist.lo libmca_common_verbs_la-common_verbs_find_max_inline.lo libmca_common_verbs_la-common_verbs_find_ports.lo libmca_common_verbs_la-common_verbs_mca.lo libmca_common_verbs_la-common_verbs_port.lo libmca_common_verbs_la-common_verbs_qp_type.lo -losmcomp  -libverbs  -lrt  -lm -lutil   -lm -lutil  

libtool: link: gcc -std=gnu99 -shared  -fPIC -DPIC  .libs/libmca_common_verbs_la-common_verbs_basics.o .libs/libmca_common_verbs_la-common_verbs_devlist.o .libs/libmca_common_verbs_la-common_verbs_find_max_inline.o .libs/libmca_common_verbs_la-common_verbs_find_ports.o .libs/libmca_common_verbs_la-common_verbs_mca.o .libs/libmca_common_verbs_la-common_verbs_port.o .libs/libmca_common_verbs_la-common_verbs_qp_type.o   -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/usr/lib64 /usr/lib64/libosmcomp.so -libumad /usr/lib64/libibverbs.so -lnl-route-3 -lnl-3 -lpthread -ldl -lrt -lm -lutil  -mcx16 -pthread   -pthread -Wl,-soname -Wl,libmca_common_verbs.so.0 -o .libs/libmca_common_verbs.so.0.0.0

/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lnl-route-3
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lnl-3
collect2: error: ld returned 1 exit status
Makefile:1884: recipe for target 'libmca_common_verbs.la' failed
make: *** [libmca_common_verbs.la] Error 1
11:18:17  (master) ~/ompi/opal/mca/common/verbs$ ls /usr/lib64/*nl*
/usr/lib64/libanl.a
/usr/lib64/libnl-cli-3.so.200@
/usr/lib64/libnl-nf-3.so.200@
/usr/lib64/libanl.so@
 /usr/lib64/libnl-cli-3.so.200.18.0*
/usr/lib64/libnl-nf-3.so.200.18.0*
/usr/lib64/libmnl.so.0@ 
/usr/lib64/libnl-genl-3.so.200@
/usr/lib64/libnl-route-3.so.200@
/usr/lib64/libmnl.so.0.1.0*
/usr/lib64/libnl-genl-3.so.200.18.0*
/usr/lib64/libnl-route-3.so.200.18.0*
/usr/lib64/libnl-3.so.200@
/usr/lib64/libnl-idiag-3.so.200@ 
/usr/lib64/libnl.so.1@
/usr/lib64/libnl-3.so.200.18.0* 
/usr/lib64/libnl-idiag-3.so.200.18.0*
 /usr/lib64/libnl.so.1.1.4*
 
/usr/lib64/libnl3-200:
./  ../  cli/
 ```

@hjelmn @hppritcha Any ideas?

**Comment by jsquyres** [comment]
It looks like you have `libnl-route-3.so.200.18.0` and `libnl-3.so.200`, but not `libnl-route-3.so` and `libnl-3.so` (i.e., the plain `.so` versions of the library).  Is there a `dev` or `devel` RPM that you're missing?

**Comment by hppritcha** [comment]
HI Ralph,

On CrayXC systems running CLE 6 they only do a partial install of ibverbs
related RPMs.
They don't install devel rpms you would need.

In addition, there were changes to way Cray's verbs simulation library
works from CLE 5
that causes additional issues even if you manage to install the missing nl
libs yourself.

So, for those systems, you need to add --with-verbs=no.

Howard


2017-01-06 0:24 GMT-07:00 Ralph Castain <notifications@github.com>:

**Comment by jsquyres** [comment]
That's kinda lame -- those 2 libs are pulled in via dependencies (probably from librdmacm?).

Sounds like the configure.m4 for common/verbs should try to do a link (so that it can realize that it *can't* do a link, and therefore elect not to build).

**Comment by hppritcha** [comment]
we had a similar discussion I think when I was trying to build Open MPI to use UCX on some system (not Cray) that was missing devel RPMS and I was told it was "hard" to get configure to test this.  This problem is easily detected though if one were trying to build Open MPI rpms from a source tarball and the spec file was accurate.

**Comment by hppritcha** [comment]
Sorry one correction to last comment, it was not UCX but with MXM support.  It was on a student cluster and they didn't "know" about needing to install devel rpms required to build Open MPI with MXM support until we actually tried to build the Open MPI libs.

**Comment by rhc54** [comment]
Thanks @hppritcha - that did indeed solve the problem. I also see a warning coming out of the oob/alps component that I'll address and commit back.
