### ISSUE TITLE
PR #2596 introduced regression when configuring with -O3 optimization

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#2678]
#2596, which has been merged back in to v2.x and v.2.0.x introduced a major regression.  Open MPI can no longer be compiled with gcc (at least) at -O2 or -O3 for x86_64 without immediately segfaulting in MPI_Init.   The problem has been observed both for gcc 4.9 and 6.3.

orterun also fails with a similar segfault pattern.  If one uses the cpuid instruction directly (avoiding all the exb exchange stuff - which isn't necessary for x86_64), the problem vanishes.  

See comments to commit a718743a5c7017c13fb56950d16edd0b59f07108.
Although the problem was originally reported on a system with Opteron processors, 

@marksantcroos thanks for catching this.

**Comment by hjelmn** [comment]
Hmm, I tested this only with gcc on CTS-1. Optimized build (defaults to -O2). Will look at the backtrace and see what is going on.

**Comment by hjelmn** [comment]
Rather embarrassing. The cpuid code I copied from patcher only saved/restored the lower 32 bits of register b. PR open to fix.
