### ISSUE TITLE
Allgatherv crash on large buffer when using derived types

### ISSUE THREAD

**Issue by tjb900** [open-mpi/ompi#2743]
Hi!

Seeing a segfault inside allgatherv on a large buffer.  Reproducer attached (wouldn't let me attach .c).

send size per rank: 1.6GB
receive size: 6.2GB

Relevant details:

* OpenMPI versions: both 1.6.5 and 2.0.1
* Network: TCP
* fails with mpi_size=2,3,4,6

I plan to investigate this myself also, but am spread pretty thin so thought I'd report it here too.

Cheers,
Tim

[reproducer.c.txt](https://github.com/open-mpi/ompi/files/710959/reproducer.c.txt)

**Comment by tjb900** [comment]
It occurred to me that it might be an intel compiler problem, but have just reproduced with gcc 4.4.7 (old I know).

[info.txt](https://github.com/open-mpi/ompi/files/711023/info.txt)

**Comment by bosilca** [comment]
Tim, the provided reproducer is wrong. You are computing the size of your buffers (send and receive) in floats, but then you use the dt_yzplane as a datatype in the MPI_ALLGATHER function. This lead to moving data outside the legal boundaries of your allocated buffers, action that usually ends with a segfault. If I replace the 2 uses of dt_yzplane in the allgather with MPI_FLOAT (which should be the right type for the operation), everything works to completion. Until there is new evidence about a deeper problem in Open MPI I will close this issue.

**Comment by tjb900** [comment]
Hi Bosilca,

While I am certainly willing to believe I'm wrong, I don't agree with your interpretation in this case.  The counts and displacements are all in terms of the x coordinate only - very small numbers.  Changing the type of the MPI_Allgatherv to float will mean that only 1601 floats are exchanged.

Do you mind taking another look?

Thanks!
Tim

```
        uint64_t nxyz = (uint64_t)nx * (uint64_t)nyz;
	uint64_t nxyz_local = (uint64_t)local_nx * (uint64_t)nyz;

	float *sendbuf = malloc(nxyz_local*sizeof(float));
	float *recvbuf = malloc(nxyz*sizeof(float));
	memset(sendbuf, 0, nxyz_local*sizeof(float));
	memset(recvbuf, 0, nxyz*sizeof(float));

	int local_nx_exceptlast = (nx+mpi_size-1) / mpi_size;
	int displ[mpi_size], count[mpi_size];
	int i;
	for (i = 0; i < mpi_size-1; i++) {
		displ[i] = i*local_nx_exceptlast;
		count[i] = local_nx_exceptlast;
	}
	displ[mpi_size-1] = (mpi_size-1) * local_nx_exceptlast;
	count[mpi_size-1] = nx - displ[mpi_size-1];

	int ierr = MPI_Allgatherv(sendbuf, local_nx, dt_yzplane, recvbuf, count, displ, dt_yzplane, MPI_COMM_WORLD);
```

**Comment by bosilca** [comment]
I just did ;) Thanks for insisting, you were right the displacement and the count were correctly computed to fit in the receive buffer. It turned out the issue was deep inside out TCP transport, but 999d4973a should fix it.

**Comment by bosilca** [comment]
This issue is now fixed in master.
