### ISSUE TITLE
PMIx v1.2.1 Update for OMPI v2.1.0 release

### ISSUE THREAD

**Issue by jjhursey** [open-mpi/ompi#2744]
Placeholder issue that we need to update OMPI v2.1.0 to the eventual PMIx v1.2.1 which will contain some bug fixes that we would like to include in the v2.1.0 release.

**Comment by jsquyres** [comment]
Is this a dup of #2072?

**Comment by jjhursey** [comment]
@jsquyres Yes - I don't know which one we want to close.

**Comment by jsquyres** [comment]
Closing this one as a dup of #2072.
