### ISSUE TITLE
FAQ rsh_agent option deprecation is incorrect

### ISSUE THREAD

**Issue by broukema** [open-mpi/ompi#2761]
On http://www.open-mpi.de/faq/?category=rsh
there is some deprecation information:

>  v1.3 and later series: The orte_rsh_agent MCA parameter accepts a
>   colon-delimited list of programs to search for in your path to use
>   as the remote startup agent (the MCA parameter name plm_rsh_agent
>   also works, but it is deprecated).

which appears to me to be wrong in v2.0.2~git.20161225-8 (debian) and the present github master branch.

For example, lines 182-189 of

https://github.com/open-mpi/ompi/blob/master/orte/mca/plm/rsh/plm_rsh_component.c

indicate that pls_rsh_agent and orte_rsh_agent are flagged as deprecated, but plm_rsh_agent
is valid.

So this FAQ says the opposite of what the code says; also, pls_ should be added as 
another deprecated alias.

**Comment by rhc54** [comment]
Fixed - thanks!
