### ISSUE TITLE
v1.10, v2.0.x, and v2.x: Endless loop in the stack trace output

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2799]
@hjelmn found a case on a PSM2 cluster where he runs into an endless loop with backtrace output when an MPI process crashes.  In discussion in the Jan 2017 F2F meeting, we think it might not be related to PSM, but possibly something odd in the backtrace code.  @hjelmn is investigating, and will also investigate whether this affects the 2.0.x and 2.x branches.  It definitely does affect the v1.10 branch.

More details to come.

**Comment by jjhursey** [comment]
Related https://github.com/open-mpi/ompi/pull/1781

**Comment by rhc54** [comment]
This has been fixed for v1.10, so I'm closing it here
