### ISSUE TITLE
remove --enable-heterogenous configury option 

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#2802]
Mixed big endian/little endian no longer works in Open MPI and there are no plans currently to fix it.  To avoid user confusion, remove the configure --enable-heterogenous option.  Related to issue #639.

Rather than just removing entirely from the configury, it would be better to have configure print out an error message if this option is attempted and abort.

**Comment by ggouaillardet** [comment]
the test provided in #168 runs fine with master + a few patches of mine.
i am happy to maintain the ```--enable-heterogeneous``` option, maybe ```v2.1.0``` is a reasonable target so i can test and backport what is needed

there was a previous RFC to get rid of heterogeneous support at https://www.open-mpi.org/community/lists/devel/2014/04/14584.php
and we did not decide to get rid of that.

@jsquyres @bosilca any thoughts ?

**Comment by ggouaillardet** [comment]
fwiw, this was mentionned (and in a negative way) in that post that got some audience at that time
http://gentryx.de/news_the_troubling_state_of_MPI.html

**Comment by nrgraham23** [comment]
@jsquyres Do you want me to remove the dead code disabling this option will produce as well?  Or I can leave it in incase we decided to support this option again in the future.

**Comment by hppritcha** [comment]
Maintaining means testing.  If we are going to maintain I'd like to see either a MTT or CI test of the hetero feature.

**Comment by ggouaillardet** [comment]
the first step is to configure with ```--enable-heterogeneous``` and run MTT on a __homogeneous__ cluster.
this is currently done by @jsquyres , see https://mtt.open-mpi.org/index.php?do_redir=2387

the second step is to configure with ```--enable-heterogeneous``` on at least two heterogeneous arch, and tests/run MTT on an __heterogeneous__ cluster.
i believe @siegmargross run some basic tests on a regular basis (and we do get some reports when issues occur). i also run the ```ibm``` test suite on an heterogeneous cluster. the process is manual yet
(i do not think that could be fully automated in MTT, at least today) and i will see how i can upload the test results to MTT

**Comment by rhc54** [comment]
@ggouaillardet We talked about this on the telecon this morning, and bottom line is that we will apply our usual policy here: if someone is willing to maintain and test this feature, then no problem leaving it in the code. This probably applies sooner to v2.1 than v2.0.3, but if you can update the support and at least post on the PR your MTT results, then we are content to leave this alive.

**Comment by Kawashima-Azumi** [comment]
At present I don't care BE/LE support but one scenario of my use cases is to make remote calls to x86_64 servers (LE) with high electric power consumption from a low power 32-bit system (LE). Will this be affected if heterogeneous support is removed?

**Comment by jsquyres** [comment]
I think this issue is now moot, per https://github.com/open-mpi/ompi/issues/2802#issuecomment-276416135 and #2940.
