### ISSUE TITLE
Failure in Finalize when using Java Bindings

### ISSUE THREAD

**Issue by nrgraham23** [open-mpi/ompi#2811]
A pointer that was not allocated is being freed in the Finalize call.  This causes an endless loop of errors to occur, and you have to use the kill command to stop the Java processes (ctrl + c does not work).

This problem exists on master, but not in v2.0.x.  I will check the other release branches.

**Comment by ggouaillardet** [comment]
@nrgraham23 i will take care of that.

i recently plugged a bunch of memory leaks, and we end up in a non supported case here :
```MPI_Init()``` is not invoked from the main thread, so some data ends up being free'd twice

**Comment by nrgraham23** [comment]
I suspected it was related to the memory leak fixes.  Your pull request fixes the problem.

**Comment by nrgraham23** [comment]
@jsquyres @hppritcha Would it be possible to add a very simple sanity test to MTT for the Java bindings?  It was quite a while from when the Java bindings must have been broken to when I noticed they were broken.  Maybe something as simple as the Hello.java in the examples directory.
