### ISSUE TITLE
README update needed

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#2814]
Per discussion at the Open MPI developer workshop 1/24/17, it was decided we need a major update of the README to reflect current reality, esp. in terms of supported compilers, CPU types, and OS flavors.

**Comment by gpaulsen** [comment]
Need to include distributors on supported platform conversation.

Also some thoughts about wording the level of testing some platforms receive, and a petition for help testing certain platforms.

**Comment by hppritcha** [comment]
This issue has been addressed as part of 2.1.0 release.
