### ISSUE TITLE
abort job launch in case of mixed BE/LE environment

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#2817]
Open MPI doesn't currently support mixed big endian/little endian jobs.  In conjunction with a fix for issue #2802, a runtime check to detect the situation where some processes in the job are BE while others are  LE would be helpful.  Ideally a show help message would be emitted which explains that mixed BE/LE jobs are not currently supported.

**Comment by rhc54** [comment]
Isn't it true that the user would have already had to create separate binaries for the nodes, and so they knowingly violated our level of support? We now pass back to mpirun the local chip architecture, and so we could detect this problem rather easily (assuming mpirun is used to launch the app). No way it would go back to the 2.x series, but we could provide it for v3.x if you really want it.

**Comment by hppritcha** [comment]
moving the milestone for this issue to future.
