### ISSUE TITLE
missing Fortran interfaces in man pages

### ISSUE THREAD

**Issue by loveshack** [open-mpi/ompi#282]
It came up on the user list that the man pages for MPI routines only document the mpif.h interfaces,
not the module ones.  Jeff thought that could probably be fixed mechanically, but I don't see a
way of doing that without at least paste-able copies of the interfaces from the standard.  I might be able
to do it if anyone can point me to something like that, such as the source of the standard, perhaps.

**Comment by hppritcha** [comment]
this has been fixed.  just make sure to build with fortran support or else the man pages will only show 'c' interfaces.
