### ISSUE TITLE
Remove MXM MTL

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2849]
Per F2F Jan 2017 discussion, remove the MXM MTL for v3.0.0.

@jladd-mlnx was going to investigate if this was ok.  I'm filing a ticket here to make sure we don't forget.

**Comment by bwbarrett** [comment]
Brian, Howard,

We can safely deprecate MXM/MTL.

Josh



-----Original Message-----
From: Barrett, Brian [mailto:bbarrett@amazon.com] 
Sent: Tuesday, March 07, 2017 2:52 PM
To: Joshua Ladd <joshual@mellanox.com>
Cc: Pritchard Jr., Howard <howardp@lanl.gov>
Subject: Re: MXM MTL / Yalla PML

Thanks!  We won’t take any action until we hear from you.

Brian

On Mar 7, 2017, at 11:51 AM, Joshua Ladd <joshual@mellanox.com> wrote:

Hi, Brian

We can probably deprecate the MTL, but we will certainly want to continue supporting Yalla. Let me double check with Yossi and make sure he doesn't have any concerns about the MTL. 

Josh



-----Original Message-----
From: Barrett, Brian [mailto:bbarrett@amazon.com] 
Sent: Tuesday, March 07, 2017 2:47 PM
To: Joshua Ladd <joshual@mellanox.com>
Cc: Pritchard Jr., Howard <howardp@lanl.gov>
Subject: MXM MTL / Yalla PML

Josh -

For the 3.0 series, does Mellanox want to continue shipping / shipping the MXM MTL and/or the Yalla PML?  There’s an open issue about deprecation, so wanted to make sure we weren’t shipping something unnecessarily.

Thanks,

Brian

**Comment by jladd-mlnx** [comment]
👍

**Comment by jsquyres** [comment]
Looks like we unfortunately forgot to remove this in 3.0.0 (or 3.1.0) -- @bwbarrett will file a PR shortly to remove this from master (and thereby trigger the next release series to be v4.0.x).

**Comment by gpaulsen** [comment]
Howard said he'll do this.

**Comment by hppritcha** [comment]
this was actually closed via #5180
