### ISSUE TITLE
Remove SM BTL

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2851]
Per F2F Jan 2017 meeting, remove the SM BTL for v3.0.0.

We need to decide how to handle the "sm" BTL name for legacy script (i.e., those who still `mpirun --mca btl sm,BLAH ...`).

**Comment by miked-mellanox** [comment]
Can sm be alias for vader btl?

**Comment by jsquyres** [comment]
@miked-mellanox That's basically the question (i.e., aliasing vader is one option).  There is no infrastructure in place (yet) for aliasing component names.

**Comment by hjelmn** [comment]
I have a couple of open pull requests proposing such functionality but they neither got any traction. The problem with aliasing is it needs to be taken into account very early on in the component process. For that to work the aliasing support needs to be in the framework base.

I will take another crack at a solution in the next week or so.

**Comment by jsquyres** [comment]
This was done in #3889.
