### ISSUE TITLE
RoCE does not work out-of-the-box with the openib BTL

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2853]
Per https://www.mail-archive.com/devel@lists.open-mpi.org/msg19874.html, RoCE does not work out of the box with Open MPI 2.0.x (or 2.x).

The issue is that we no longer have a per-peer QP in the receive queues.

Per @hjelmn's suggestion, we need to modify the MCA param default values to add a PP QP when we're using RoCE (we do this for iWARP, but we do it in .ini files -- which we can't do for RoCE, because the vendor/part ID is the same for IB and RoCE Mellanox HCAs).

**Comment by awlauria** [comment]
Openib btl is removed. Closing.
