### ISSUE TITLE
MTT : spawn still crashing on master

### ISSUE THREAD

**Issue by sjeaugey** [open-mpi/ompi#2863]
In case you didn't see it :
https://mtt.open-mpi.org/index.php?do_redir=2385

I'm not sure it is a new problem (could have been around for a couple of weeks), I just don't remember seeing this rather explicit error message before, which may help.

```
PMIX ERROR: ERROR in file server/pmix_server_get.c at line 502
 Warning :: pmix_list_remove_item - the item 0x7f2ce4016ea0 is not on the list 0x7f2cea9eeab8 
mpirun: server/pmix_server_get.c:583: pmix_pending_resolve: Assertion `((0xdeafbeedULL << 32) +
0xdeafbeedULL) == ((pmix_object_t *) (lcd))->obj_magic_id' failed.
```

**Comment by rhc54** [comment]
I think I have this fixed with 0c8609ca165ea34059bd5d0b55ee08e576b8241a - let's see how MTT does overnight.
