### ISSUE TITLE
MPI_Ireduce broken

### ISSUE THREAD

**Issue by ggouaillardet** [open-mpi/ompi#2879]
open-mpi/ompi@045d0c5f4caffdf31fb2dd1cb4d7b8940c07d365 introduced a regression in the ```ibm/collective/ireduce_loc``` test (at least with 4 MPI tasks)

this has already been backported to the ```v2.0.x``` branch as open-mpi/ompi@f041083fdb42dfb3163a5ba24c0168a5a4179ebc

i will double check that, meanwhile
- @hppritcha @jsquyres we might want to roll an other ```v2.0.2``` rc (5?) that includes the fix
- @gpaulsen is there a test case that evidences the issue that is solved by this commit ?

**Comment by ggouaillardet** [comment]
i fixed master and made #2881 for the ```v2.0.x``` branch

**Comment by jsquyres** [comment]
@ggouaillardet Can you share the test you used to find this?  I'm running on master -- before your fix -- and `ibm/collective/ireduce_in_place.c` is passing for me (with any np).

**Comment by rhc54** [comment]
I saw it go by as committed to the ompi-tests repo

**Comment by gpaulsen** [comment]
@ggouaillardet, your update is correct.  It looks like there was a transcription error from Mark's original change.  Please accept @ggouaillardet's update.

**Comment by ggouaillardet** [comment]
@jsquyres ireduce_loc got broken (at least with 4 tasks)
i updated ireduce_big and added ireduce_big_in_place to evidence the initial bug and the regression.
everything is ok now
