### ISSUE TITLE
Add support for C11 atomics

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#2894]
This is a placeholder issue for the work adding C11 atomics. There are some open questions:

 - Since C11 atomics are part of the language standard it makes sense to put the support in opal/include/opal_stdatomic.h. If C11 atomics are not available this header will provide C11 compliant atomics using the atomics in opal/include/opal/sys. Does this make sense? The alternative is to make C11 atomics another directory in opal/include/opal/sys.

 - C11 only defines fetching then op atomics. The atomics in opal are all op then fetch. It is fairly straightforward to update the codebase to these new semantics but it may be surprising to off-tree components. We could rename all the internal atomics from opal_atomic_op to opal_atomic_fetch_op to indicate the change in semantics. Should we change the codebase to fetch then op? Alternatively, should we support both fetch then op and op then fetch?

- If we do change the semantics of our atomics should we continue to support the non-inline atomics? Some of them are stale and it will only get worse if we make the change.

- C11 defines add, sub, or, xor, and and. opal only defines add and sub. We can trivially add support for or, xor, and and to our atomics code for ppc, arm, arm64, sync builtin, and gcc builtin. Is this desirable? One component (osc/pt2pt) would benefit from the new calls.

@bosilca @ggouaillardet Comments?

**Comment by bosilca** [comment]
Before I comment more on this, I wanted to let you know that the C11 atomics are not compatible with the currently supported OpenMP memory model (which supports up to C99), and including stdatomic.h conflicts with some of the OpenMP flags (such as -fopenmp).

**Comment by bwbarrett** [comment]
@hjelmn do we still need this issue or can we close it at this point?

**Comment by hjelmn** [comment]
We have a newer issue for tracking this
