### ISSUE TITLE
Fix corner case of DDT launching

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#29]
As reported by Allinea:

If you have the Open MPI mpirun in your PATH and DDT is set to use MPICH Standard startup then when you start a program it will continuously launch new instances of the GUI.

This is because Open MPI has support for MPICH's -tv option but it's broken - it ignored the TOTALVIEW environment variable and launches DDT with: ddt -n NUMPROC -start PROGRAM. This, in turn, runs mpirun and spawns even more copies of DDT.

"mpirun -np 8 -tv user-app-path" needs to translate to "ddt -n 8 user-app-path"  if loading DDT --- except when the TOTALVIEW env var is set.   In that case you should execute 8 copies of $TOTALVIEW, one per proc on the target hosts. 

That should work for everything I can think of!  Our default Open MPI / DDT startup doesn't go via the "-tv" option so should be unaffected: the fix above is only to handle the case when the user has done something silly, ie. picked MPICH Standard instead of Open MPI from the available list.  From my understanding, the above fix shouldn't break totalview.

**Comment by rhc54** [comment]
Fixed long ago
