### ISSUE TITLE
libevent - Move opal_event_include logic to base

### ISSUE THREAD

**Issue by jjhursey** [open-mpi/ompi#2929]
Per comment on PR #2904 - The logic supporting MCA parameter `opal_event_include` is the same (nearly) in both the internal and external component. As such it should be moved to `base` to avoid code duplication.

**Comment by jsquyres** [comment]
@jjhursey This could probably be classified as a "bug", and therefore be eligible for v2.1.1.  Do you want this for v2.1.1, v3.0.0, or beyond?  Please update the milestone.

**Comment by jsquyres** [comment]
(in an effort to clear out the v2.1.0 milestone, I pre-emptively moved this to v2.1.1 -- feel free to update)

**Comment by jjhursey** [comment]
Let's move it to v3.0 - I don't think it's critical for me to get it into the v2.x series at this point.

**Comment by hppritcha** [comment]
Too late for 3.0.0.

**Comment by jjhursey** [comment]
With the move to 3rd party packages in `master`/`v5.x` the `opal_event_include` logic has been centralized [here](https://github.com/open-mpi/ompi/blob/23833935f368f61a9277035da0443287513c57e0/opal/util/event.c#L60-L66).
This issue can be closed.
