### ISSUE TITLE
mpirun man page audit

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#2930]
Comments from users indicate that we need to do an audit of the mpirun man page and make sure that it includes a description of all the options available on the mpirun command line.

At a minimum, the mpirun page should document all mpirun command line options that are shown when one runs ```mpirun --help```.

**Comment by hppritcha** [comment]
assigning to @nrgraham23

**Comment by nrgraham23** [comment]
@hppritcha @jsquyres Are there any options that need to be removed from the man page?

**Comment by jsquyres** [comment]
I'm not sure offhand -- I'm thinking you'll need to audit the mpirun code and make sure that:

1. everything that is in the code is in the man page
1. everything that is in the man page is in the code

**Comment by nrgraham23** [comment]
I have found a Fault Tolerance option that is available if FT is enabled.  Should I include this in the man page?  If so, should I tell the user how to enable FT at compile time?

**Comment by nrgraham23** [comment]
Howard told me the FT stuff had bit rotted, so I will not include it in the man page.

**Comment by rhc54** [comment]
We should remove that configure option as well - it won't even build or work
