### ISSUE TITLE
Revamp "mpirun --help" output

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2931]
Probably in conjunction with #2930, revamp the help output from `mpirun`.

Currently:

```
$ mpirun --help | wc -l
233
```

That's a *lot* of help output.  It's quite daunting for users to find what they're looking for in there.

We should take some inspiration from `git` and other CLI-option-right executables about how they display their help: only show a summary -- perhaps showing a handful of the most common help options, and then showing how to get *more* help for targeted information (e.g., similar or analogous to `git --help foo` gives you help about the `foo` subcommand for git).

Here's two ideas that might be helpful (at least somewhat drawing inspiration from `git --help`):

1. Currently, `mpirun --help` simply runs through all the possible CLI arguments and prints them along with their help string.  We should probably also be able to output some plain text lines -- maybe as just a header and footer...?
1. Maybe `mpirun --help foo` could list subsections of help topics.  Git shows specific common commands in its `git --help` output, but mpirun doesn't have to be exactly the same.  Perhaps things like `mpirun --help binding` shows all the binding/affinity options, and `mpirun --help dvm` shows all the DVM options, ...etc.  I.e., audit all of `mpirun`'s CLI options and put them into a small number of groups (where each group is a not-terribly-long list of CLI options), and then `mpirun --help` shows a listing of those groups.

This might also be applicable to other Open MPI executables, too (e.g., `ompi_info`?).  `mpirun` is just an obvious example to cite (because it has a zillion CLI options).

**Comment by hppritcha** [comment]
@jsquyres do you mean ```ompi_info``` rather than ```mpirun``` in the last sentence of the description?

**Comment by jsquyres** [comment]
Clarified the last sentence.

**Comment by nrgraham23** [comment]
The man page is already somewhat broken up into groups with things like:

Setting MCA parameters:

To manage files and runtime environment:

etc.

Those could function as the groups you mention in your #2.

**Comment by nrgraham23** [comment]
@rhc54 @jsquyres There is an array cmd_line_init with almost all of the command line options (I think the only one missing is -mca), and it is broken up into some groupings already.  I will model the enhanced help output after those groupings.

**Comment by nrgraham23** [comment]
I have broken all of the options up into several groups, most of which make sense to me.  I could use some feedback on these groups though.  @rhc54 @hppritcha @jsquyres 

Here is the file with the groups:

[ompi help output groups.txt](https://github.com/open-mpi/ompi/files/812379/ompi.help.output.groups.txt)

**Comment by jsquyres** [comment]
Comments:

* I agree the pmix server URI doesn't belong there.   @rhc54 Would you classify `mpirun`'s `--ompi-server` option a "Launch option" or a "DVM option"?
* Yes, I think that breaking up mapping, binding, and ranking options into separate groups would be good.  That stuff is confusing -- keep those sections small!

I think the other groups look good.

**Comment by rhc54** [comment]
server URI: it's hard to say where to put this. It's purpose is to service functions like "publish" and "lookup" - i.e., dynamics between jobs launched by different mpirun's. I guess lumping it in with DVM is as good as anything else I can come up with.

+1 on splitting mapping, ranking, and binding groups.

**Comment by nrgraham23** [comment]
Ok.  I have made the modifications you both suggested, cleaned up the list, and made some other changes.  I also uploaded the document to google docs so you guys can comment on it.

@hppritcha @jsquyres @rhc54 Please take a look and make some suggestions if you see something that is not in the right place.

https://docs.google.com/document/d/1Ck0Nmi0kckNqqaX3zLuOJBHmsrSkn1MQX95h8rtEUOw/edit?usp=sharing
