### ISSUE TITLE
OpenMPI 2.0.2 error on Linux

### ISSUE THREAD

**Issue by azukaitis** [open-mpi/ompi#2938]
I have a fortran application that mixes openmpi and openmp.  mpirun crashes before our application even starts.  I built openmpi 2.0.2 with gcc 5.3.0.

I build the openmpi package with:
    --enable-debug --enable-mem-debug --enable-event-debug

And get the following errors:
PMIX ERROR: UNPACK-FAILURE in file ../../../../../../openmpi-2.0.2/opal/mca/pmix/pmix112/pmix/src/server/pmix_server.c at line 2314
PMIX ERROR: UNPACK-INADEQUATE-SPACE in file src/client/pmix_client.c at line 182

Application worked fine with versions before 1.10.  Works fine with Intel Fortran.  Any thoughts or advice? 

Tony

**Comment by jsquyres** [comment]
This type of error typically occurs when you are unexpectedly mixing versions of Open MPI on different nodes.  E.g., you compile/run with Open MPI version A on one node, but ssh+your shell startup files pick up version B on a different node.

Can you verify that you are picking up the same exact version of Open MPI on all nodes?

**Comment by azukaitis** [comment]
This is a single node run using
mpirun -np 1

**Comment by jsquyres** [comment]
Ok, just a single node.

Let's check for the same effect, though -- can you `ldd your_program`, and make sure it's linking against the new Open MPI libraries?

Also, make sure that you didn't install the new Open MPI in the same prefix as the old Open MPI (this is a situation that is known not to work -- installing a new Open MPI does not uninstall the previous plugins and components from the old Open MPI, and that can lead to... unexpected code execution, which can effectively result in compatibility problems).

**Comment by azukaitis** [comment]
I wiped my install directory and rebuilt openmpi 2.0.2 in debug mode using
gcc-6.1.0.  I confirmed with ldd that I am only linking mpi libraries using
my install directory   PMIX error is gone now but I'm getting a segfault
now:

mpirun -np 1 mycode.mpi
mpirun noticed that process rank 0 with PID 190153 on node host exited on
signal 11 (Segmentation fault).

**Comment by jsquyres** [comment]
That is showing that your MPI process died (vs. `mpirun`).

You should probably use some standard debugging techniques to figure out *where* in your application it is dying.  I.e., is it a problem with Open MPI, or is it a bug in your application?

If you want to verify your Open MPI installation, you might want to try to examples in the `examples/` directory in the Open MPI tarball.  There's C and Fortran versions of MPI "hello world" and "send a message around in a ring".  ring will require 2 or more processes.
