### ISSUE TITLE
configuration: OMPI v2.x with external hwloc from the distro

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#2946]
@dannyauble reported the problem with OMPI configuration.

In the target environment `hwloc 1.11.3-2` was installed from the distro package in the default location in `/usr/`

For the case where we configured without parameters:
```
./configure ... --with-hwloc ...
```
not all hwloc paths was properly set and compilation failed.
@dannyauble noticed that `MCA_hwloc_external_header` was:
```
#define MCA_hwloc_external_header "hwloc.h"
```
instead of
```
#define MCA_hwloc_external_header "/usr/include/hwloc.h"
```
Problem can be solved by setting full path to hwloc at config time:
```
./configure ... --with-hwloc=/usr/ ...
```

**Comment by jsquyres** [comment]
This is likely related to https://github.com/open-mpi/ompi/issues/2616.

**Comment by ggouaillardet** [comment]
@artpol84 basically, the issue is we have a ```hwloc.h``` file in ```opal/mca/hwloc/hwloc.h``` and we automatically add ```-Iopal/mca/hwloc``` in the ```CPPFLAGS```.
bottom line, if we want the external ```hwloc.h```, we cannot simply
```c
#include <hwloc.h>
```
but we have to
```c
#include "/usr/include/hwloc.h"
```
(well, we do that via the ```MCA_hwloc_external_header" macro)

since the MCA framework is called ```hwloc```, then the header file must be named ```hwloc.h```.
imho, in order to correctly address this issue, the easiest way is to rename the ```hwloc``` framework
(```hwtopo``` ?). unfortunatly, this is also the longest path ...

**Comment by artpol84** [comment]
@jsquyres I think you are right. empty argument or `external` has same meaning. Closing this one.
