### ISSUE TITLE
v2.0.3: SGE launch problems

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2947]
Per https://www.mail-archive.com/users@lists.open-mpi.org/msg30566.html, users have reported problems using SGE with Open MPI v2.0.2 unless they `-mca plm_rsh_agent foo` on the `mpirun` command line.

@rhc54 said that he thought he found the problem, but didn't say specifically what it was.  

In https://www.mail-archive.com/users@lists.open-mpi.org/msg30579.html, Mark Dixon hypothesized that 71ec5cfb436977ea9ad409ba634d27e6addf6fae might be the culprit.

Ralph -- can you comment?

**Comment by jsquyres** [comment]
@rhc Should the `!=` in https://github.com/open-mpi/ompi/commit/71ec5cfb436977ea9ad409ba634d27e6addf6fae#diff-f556f53efc98e71d3bd13ee9945949feR272 be `==`?

**Comment by rhc54** [comment]
No - the commit that was done is simply incorrect. We have to always check for qrsh.

**Comment by jsquyres** [comment]
@rhc54 and I talked about this on the phone.  As mentioned, the check for "is it the default value" simply isn't the right test (regardless of whether the `!=` should be `==` or not).  He'll supply a fix soon.

**Comment by rhc54** [comment]
@jsquyres Digging deeper, the minimum fix is indeed to replace the equality test as you suggest. I have updated the logic in master to clarify things so the mistake isn't made again.

**Comment by jsquyres** [comment]
https://github.com/open-mpi/ompi/commit/dee2d8646d2e2055e2c86db9c207403366a2453d looks like the fix in master.  Did this get applied to v2.0.x and v2.1.x?

**Comment by jsquyres** [comment]
Per discussion with @rhc54: no, it did not get applied to v2.0.x or v2.1.x.  Would be good to get into both of those.  I'll leave this issue open for v2.0.3 and file another for v2.1.x, just to make sure we don't forget to include the fix for v2.1.1.

**Comment by hppritcha** [comment]
Closed via #3162
