### ISSUE TITLE
dvm: daemons quit after exceed available slots

### ISSUE THREAD

**Issue by naughtont3** [open-mpi/ompi#2987]
The DVM is not usable after exceeding available resources (i.e., non-oversubscribe case).  It seems like the next invocation runs into previous invocation's error and things shutdown. 

Brief summary with simplified setup (localhost w/ 2 slots) :
 - Run command that exceeds resources (e.g., `mpirun --hnp file:dvmuri -np 3 hello` but only 2 slots available) we get error 
 - Then run a valid command (e.g., `-np 2`) and the DVM calls `orte_quit()` b/c it thinks nobody is alive (e.g., `orte/mca/routed/base/routed_base_fns.c:281`).
- This early termination of DVM is why the frontend command fails (orterun) as it loses lifeline to HNP.

Steps for reproducing on a single host (few debug prints prefixed by DBG):
```
$ cat hosts-tiny 
sal9000 slots=2
```
```
  # DVM case
$ orte-dvm --hostfile hosts-tiny --report-uri dvmuri --daemonize
$ ps auwx | grep orte-dvm | grep -v grep
3t4      14684  0.2  0.2 776176  4436 ?        Ssl  11:04   0:00 orte-dvm --hostfile hosts-tiny --report-uri dvmuri --daemonize
$ orterun --hnp file:dvmuri -np 2 ./hello_c
[ORTE] Task: 0 is launched! (Job ID: [6429,1])
[sal9000:14787] Hello, world, I am 0 of 2
[sal9000:14788] Hello, world, I am 1 of 2
[sal9000:14787] (rank-0) Used Version: Open MPI v3.0.0a1, package: Open MPI 3t4@sal9000 Distribution, ident: 3.0.0a1, repo rev: v2.x-dev-3722-g578d881, Unreleased developer copy
[ORTE] Task: 0 returned: 0 (Job ID: [6429,1])
$ echo $?
0
$ ps auwx | grep orte-dvm | grep -v grep
3t4      14684  0.1  0.2 915676  5564 ?        Ssl  11:04   0:00 orte-dvm --hostfile hosts-tiny --report-uri dvmuri --daemonize
 #
 # NOTE: DVM launched but exceeded resources
 #
$ orterun --hnp file:dvmuri -np 3 ./hello_c
$ echo $?
69
 #
 # NOTE: DVM process still running
 # 
$ ps auwx | grep orte-dvm | grep -v grep
3t4      14684  0.1  0.2 915676  5596 ?        Ssl  11:04   0:00 orte-dvm --hostfile hosts-tiny --report-uri dvmuri --daemonize
  #
  # NOTE: Run a valid '-np 2' case, which triggers early orte_quit() for DVM
  #
$ orterun --hnp file:dvmuri -np 2 ./hello_c
$ echo $?
0
$
```
```
  #
  # Normal case w/o DVM (limiting to 2 slots so '-np 3' exceeds resources)
  # To show that we fail as expected at '-np 3'
  #
$ mpirun --hostfile hosts-tiny -np 2 ./hello_c
[sal9000:14047] Hello, world, I am 0 of 2
[sal9000:14048] Hello, world, I am 1 of 2
[sal9000:14047] (rank-0) Used Version: Open MPI v3.0.0a1, package: Open MPI 3t4@sal9000 Distribution, ident: 3.0.0a1, repo rev: v2.x-dev-3722-g578d881, Unreleased developer copy
$ echo $?
0
$ mpirun --hostfile hosts-tiny -np 3 ./hello_c
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 3 slots
that were requested by the application:
  ./hello_c
.
Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
[sal9000:14090] DBG: MAP_FAILED rc=-43
[sal9000:14090] DBG: NOBODY KNOWN ALIVE SO WE DIE!
$ echo $?
1
$ mpirun --hostfile hosts-tiny -np 2 ./hello_c
[sal9000:14147] Hello, world, I am 0 of 2
[sal9000:14148] Hello, world, I am 1 of 2
[sal9000:14147] (rank-0) Used Version: Open MPI v3.0.0a1, package: Open MPI 3t4@sal9000 Distribution, ident: 3.0.0a1, repo rev: v2.x-dev-3722-g578d881, Unreleased developer copy
$ echo $?
0
```

Testing environment:
 - OMPI master at 578d8819cffaa5aafe721c5bdaaef1c57f3e5b68
 - Build line:
     ```
      ./configure \
          --enable-orterun-prefix-by-default \
          --enable-debug \
         --prefix=/nfsscratch/tjn/local-ompi-dvmtest \
     && make && make install
     ```
 - Versions:
    ```
    autoconf: autoconf (GNU Autoconf) 2.69
    automake: automake (GNU automake) 1.14.1
    m4: m4 (GNU M4) 1.4.17
    libtool: libtool (GNU libtool) 2.4.2
    gcc: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
    ```

**Comment by naughtont3** [comment]
Tagging @rhc54 and @marksantcroos  b/c this is DVM related issue.

**Comment by rhc54** [comment]
So to ensure I understand: if you submit a use-case that exceeds available resources, then the DVM remains alive but terminates itself upon the next submission, whether that submission is valid or not? I suspect I know why that would be happening. May take a bit to fix, though.

**Comment by naughtont3** [comment]
Yes, that is what I see.  

It seems like the exit status of "bad" command gets recorded and not cleared.  BTW, the retval for 'orterun' that exceeds resources gets non-zero retval as expected.

**Comment by naughtont3** [comment]
Note, slight clarification.  I see that if the "next submission" is also invalid (exceeds resources) that does not cause DVM to exit.  The mapping failed notice is printed, and things keep going.  

But the next valid submission will cause the DVM to terminate.

**Comment by rhc54** [comment]
Ah, okay - I was just typing a note asking for clarification. 😄 

Thanks - will investigate

**Comment by naughtont3** [comment]
FWIW, I also see that the DVM's job state changes to TERMINATED in ["orte/mca/routed/base/routed_base_fns.c" around 281](https://github.com/open-mpi/ompi/blob/master/orte/mca/routed/base/routed_base_fns.c#L281).  

If you comment this out, you can continue to submit commands to DVM after an error.  This is obviously not the fix, but thought it might help with diagnosis.

**Comment by naughtont3** [comment]
Note, I do not seem to have this problem when running on Cray/ALPS, i.e,. after exceeding available resources, I can still issue commands to DVM w/o problem.

**Comment by naughtont3** [comment]
Also, this appears to be specific to the case where you have a single host.  I was able to run normally with multiple hosts, or all hosts remote, and under SLURM. Basically, it is specific to case when you have only 1 daemon running.

**Comment by naughtont3** [comment]
@rhc54 I may have isolated the problem.  I have created a PR with a change to the DVM errmgr that catches the MAP_FAILED case and avoids disabling routing.  In the case where you have a single daemon (host) you get the problem I reported b/c of indirect effect of setting `orte_routing_is_enabled = false`, which causes things to shutdown the DVM (https://github.com/open-mpi/ompi/blob/master/orte/mca/routed/base/routed_base_fns.c#L265).

I left debugs in PR for now, and will see what you say.  The change worked for my manual tests of single host and multiple hosts running w/ and w/o the DVM.

**Comment by naughtont3** [comment]
OK, I merged your PR to my branch and reran my test script and it passed.  I also signed off on my final commit that removed the debug print.  

I think I may have to amend my earlier commit with a sign-off b/c the checklist for PR shows "some commits not signed-off" so I guess I goofed with initial step.  Sorry.  Will look at that now.
