### ISSUE TITLE
host mapping mismatch on cray

### ISSUE THREAD

**Issue by marksantcroos** [open-mpi/ompi#2998]
This is on Blue Waters a Cray with Torque.

nodenames are in the shape of `nid%05d`, but entries in `$PBS_NODEFILE` are of the shape of `%d`.

- ras: tm
- plm: alps
- ess: alps

Until recently (at least Jan 18, bisect in progress) I could use the short format, but now it requires the full format. Is that an intentional change?

```
--------------------------------------------------------------------------
There are no allocated resources for the application:
  hostname
that match the requested mapping:
  -host: 19696

Verify that you have mapped the allocated resources properly for the
indicated specification.
```

**Comment by rhc54** [comment]
Not intentional so far as I am aware - I'd have to look to see what tripped it

**Comment by jjhursey** [comment]
Is this with `master` or one of the release branches?

**Comment by marksantcroos** [comment]
@jjhursey master.

**Comment by naughtont3** [comment]
Hi @marksantcroos, I happen to be testing with `master` today on a local Cray using Torque. It seems to be working, maybe we can sync up via email to see if the environments are different.

**Comment by naughtont3** [comment]
Actually, I bet I didn't run the same command as you.  I do get an error if i pass `--host` argument on command-line.  My bad.

```
$ cat $PBS_NODEFILE | uniq
28
29
$ mpirun -np 2 --map-by node ./mpiexample 
I am rank: 1 of 2  (host=nid00029)
I am rank: 0 of 2  (host=nid00028)
$ mpirun -np 2 --map-by node hostname
nid00028
nid00029
$ mpirun -np 1 --map-by node hostname
nid00028
$ mpirun --host 28 -np 1 --map-by node hostname
--------------------------------------------------------------------------
There are no allocated resources for the application:
  hostname
that match the requested mapping:
  -host: 28
.
Verify that you have mapped the allocated resources properly for the
indicated specification.
--------------------------------------------------------------------------
$
$ mpirun --host nid00028 -np 1 --map-by node hostname
--------------------------------------------------------------------------
No nodes are available for this job, either due to a failure to
allocate nodes to the job, or allocated nodes being marked
as unavailable (e.g., down, rebooting, or a process attempting
to be relocated to another node when none are available).
--------------------------------------------------------------------------
$ mpirun -np 1 --map-by node hostname
nid00028
$
```

**Comment by marksantcroos** [comment]
> I do get an error if i pass --host argument on command-line.
> $ mpirun --host 28 -np 1 --map-by node hostname

Right, that was my use-case indeed. Thanks for checking though!

**Comment by rhc54** [comment]
Sorry, I've been at a DOE workshop and just returned home. I'll take a look at this tomorrow. I'm somewhat surprised that it used to work, but will take your word for it 😄

**Comment by marksantcroos** [comment]
Thats my general state: being surprised if it works ;-)

**Comment by marksantcroos** [comment]
FYI: I'm still bisecting, but its kind of a pain because of most intermediate versions that are not working at all.

**Comment by rhc54** [comment]
I'm not sure it's entirely necessary for you to undergo that pain - let me take a look at it and see what is required to make this work. I suspect this is something that may have been working by accident as opposed to intent, but might be doable in a more guaranteed manner.

**Comment by marksantcroos** [comment]
It works again now, thanks!

Was it intentional or not that it worked before?
I tend to remember that the full hostname didn't work actually.

**Comment by rhc54** [comment]
I honestly don't know - I don't recall me doing anything like that, but it has been a long time since I touched that code.

**Comment by hxc123fau** [comment]
> Actually, I bet I didn't run the same command as you. I do get an error if i pass `--host` argument on command-line. My bad.
> 
> ```
> $ cat $PBS_NODEFILE | uniq
> 28
> 29
> $ mpirun -np 2 --map-by node ./mpiexample 
> I am rank: 1 of 2  (host=nid00029)
> I am rank: 0 of 2  (host=nid00028)
> $ mpirun -np 2 --map-by node hostname
> nid00028
> nid00029
> $ mpirun -np 1 --map-by node hostname
> nid00028
> $ mpirun --host 28 -np 1 --map-by node hostname
> --------------------------------------------------------------------------
> There are no allocated resources for the application:
>   hostname
> that match the requested mapping:
>   -host: 28
> .
> Verify that you have mapped the allocated resources properly for the
> indicated specification.
> --------------------------------------------------------------------------
> $
> $ mpirun --host nid00028 -np 1 --map-by node hostname
> --------------------------------------------------------------------------
> No nodes are available for this job, either due to a failure to
> allocate nodes to the job, or allocated nodes being marked
> as unavailable (e.g., down, rebooting, or a process attempting
> to be relocated to another node when none are available).
> --------------------------------------------------------------------------
> $ mpirun -np 1 --map-by node hostname
> nid00028
> $
> ```

I think you'd better add the --hostfile <hostfile_name> in mpirun script, 
for example: 
mpirun --allow-run-as-root -np $np --map-by node:pe=1  --hostfile hostfile/hostfile-dl-$SLURM_JOB_ID single_process.sh

It meas run single_process.sh per node. Every processing could be invoke in these nodes.
