### ISSUE TITLE
update NEWS and README for 2.1.0 release 

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#3033]
NEWS needs to be updated with a lot of stuff for 2.1.0.

**Comment by jsquyres** [comment]
@hppritcha First cut on NEWS was yesterday: https://github.com/open-mpi/ompi/commit/4917f0177b00d2e66c3f3ab1cc6afa3f9f691f50.  Still needs work, though -- e.g., there's a bunch of "JMS" annotations (my initials) where additional research was needed.  There may also be some missing items.

**Comment by hppritcha** [comment]
related to #3058

**Comment by jsquyres** [comment]
Done!
