### ISSUE TITLE
v2.1.x: PMIx ASM compile failure on SLES 12.2 with Sun CC

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#3048]
Per @siegmargross's mail to the users list (https://www.mail-archive.com/users@lists.open-mpi.org/msg30698.html), it looks like the PMIx that was embedded in OMPI v2.x is missing an ASM compile fix: https://github.com/pmix/master/pull/309

Not sure yet if this is a blocker for v2.1.0 or not.

**Comment by jjhursey** [comment]
I've created a PR against PMIx v1.2 to pick those changes:
 * https://github.com/pmix/master/pull/322

This got missed in the sweep before the PMIx v1.2.1 release. We can talk about it's impact on OMPI v2.1.0 release tomorrow during the teleconf.

**Comment by jsquyres** [comment]
@hppritcha and I just discussed this on the phone.  Per our initial discussion, we think we would like this in v2.1.0.  Is that possible?  (we can discuss tomorrow)

**Comment by jjhursey** [comment]
On the teleconf this morning the OMPI community decided to update the internal PMIx component with the two patches so they can release _soon_. I've filed PR #3062 to do that.

PMIx has accepted this fixes into their `v1.2` release series and will be included in the eventual `v1.2.2` release.

**Comment by hppritcha** [comment]
did #3062 fix this issue?

**Comment by siegmargross** [comment]
Yes, I think so. I was able to build openmpi-2.1.0rc2 with our Oracle/Sun compiler. Thank you very much to everybody for your help.
