### ISSUE TITLE
MPI_Iallreduce with CUDA-aware supported?

### ISSUE THREAD

**Issue by junjieqian** [open-mpi/ompi#3059]
Hi, I would like to know if MPI_Iallreduce with CUDA-aware is supported now? As in https://www.open-mpi.org/faq/?category=runcuda, it is not but the page has not been update since last July.

Thank you!

**Comment by sjeaugey** [comment]
Hi Junjie, the FAQ is correct, async collectives are still not supported.

**Comment by junjieqian** [comment]
Thank you, @sjeaugey!
