### ISSUE TITLE
MPI_UNPACK bug

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#3065]
There is a bug in MPI_UNPACK that is causing many MTT tests to fail.  The bug appears to be on v2.0.x and v2.x, but not master.

#3060 (v2.1.x) and #3061 (v2.0.x) have been proposed to fix the issue.  @ggouaillardet seems to think that there should be a different fix.

Filing this issue to track the problem.

@hppritcha v2.1.0 or v2.1.1?  Tentatively marked as v2.1.0 because it's causing a lot of MTT failures, and the fix appears straightforward / isolated / low risk.

**Comment by hppritcha** [comment]
I think this is a reasonable fix to go into a 2.1.0rc2 tarball.

**Comment by hppritcha** [comment]
Why are we just now detecting this in MTT?

**Comment by jsquyres** [comment]
I don't have a good answer, other than: perhaps we weren't looking at MTT close enough...?

**Comment by jsquyres** [comment]
This is now closed; MTT shows all these issues are fixed.
