### ISSUE TITLE
openmpi 2.: MPI_Wtick returns 10e-9, not 10e-6

### ISSUE THREAD

**Issue by ccaamad** [open-mpi/ompi#3089]
Hi,

The man page for `MPI_Wtick` claims that it should return 10e-6 on POSIX platforms. I've noticed that, at least on my system (centos7, x86_64), openmpi 2.0.1 returns 10e-9.

Is this intentional - should the man page be updated?

Cheers,

Mark

**Comment by bosilca** [comment]
The MPI time accuracy depends on your processor and OS, and also the fact that you ask for a monotonic time or not. You are right, the man page should be updated to reflect this flexibility.
