### ISSUE TITLE
v3.0.0 feature whitelist

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#3107]
Per the [2/28/17 devel core minutes](https://github.com/open-mpi/ompi/wiki/WeeklyTelcon_20170228) the following items made it to the v3.0.0 feature whitelist:
- [x] Hook Framework
- [x]  <del>Removing Internal hwloc component (well this hit some turbulence, see https://github.com/open-mpi/ompi/pull/3029, we're probably delaying this to the future)</del>
- [x] PMIx 2.0.0
- [x] UCX Allocator (SPML #2717 on master)
- [x] UCX multithreading API changes (PML)
- [x] <del> MPI_*_get_info/set_info() (#2941, dependent on MPI-Forum decisions) </del>

Note that it's not **normal** anymore with our new time-based release strategy to have such a feature whitelist, but owing to the fact we decided to do a one-off pulled in release of v3.0.0, we need a whitelist for must-have features that won't make a branch cut sometime in early March '17.

@jsquyres 
@gpaulsen

**Comment by jjhursey** [comment]
The Hook framework was merged into `master` as part of PR #2773 - so that can be checked off.

**Comment by gpaulsen** [comment]
The get/set Info stuff is very close, passed review, and just needs a rebase: PR #2941.

**Comment by hppritcha** [comment]
We will delay 2941 and hwloc removal to a future release.

**Comment by hppritcha** [comment]
@jladd-mlnx where are we with these UCX related features?

**Comment by hppritcha** [comment]
UCX multi-threading PR should be posted for master by end of this week according to @jladd-mlnx

**Comment by jladd-mlnx** [comment]
@hppritcha Done PR: #3168

**Comment by hppritcha** [comment]
@rhc54 any update on when PMIX 2 will get in to this branch?
@gpaulsen please add to agenda for this weeks con-call

**Comment by rhc54** [comment]
At this point, I would suggest we plan on defaulting back to the PMIx v1.2 and the code on the existing 3.x branch. I'm getting very little help on PMIx right now, and no help at all on the other issues still lingering for 3.0. Given that we are near the end of April, I see little to no prospect of this being done in time for a June release.

**Comment by hppritcha** [comment]
Thanks for the update Ralph!   Going with v1.2 sounds like the right thing to do at this point.

**Comment by rhc54** [comment]
Yeah, I think so. However, note that it seems highly unlikely that 3.0 can be released in June. For example, I see only one MTT test being run on the 3.x branch (yours, and it even failed one of its builds)

**Comment by gpaulsen** [comment]
I'd really like to find some way to make this work.  I'm talking with our PMIx developers to see if there is something we can do in this timeframe.

**Comment by bwbarrett** [comment]
We've pulled all the whitelist items into 3.0 and are back to bugfix only, so closing this ticket.
