### ISSUE TITLE
OSHMEM: shmem_ptr() always returns 0

### ISSUE THREAD

**Issue by nspark** [open-mpi/ompi#3108]
## Issue

Currently in OSHMEM, [`shmem_ptr()` will always return a null pointer](https://github.com/open-mpi/ompi/blob/1e2019ce2a903be24361b3424d8e98d27e941c6c/oshmem/shmem/c/shmem_ptr.c).

## Background

OpenSHMEM 1.1 included a note in the definition of `shmem_ptr()` that said:
> The `shmem_ptr` function is available only on systems where ordinary memory loads and stores are used to implement OpenSHMEM put and get operations.

which limited the functionality of `shmem_ptr()` to exclusively load/store-based OpenSHMEM implementations.

OpenSHMEM 1.2 clarified the behavior of `shmem_ptr()` to support non-null return values whenever direct load/store access _could_ be provided:

> The return value is a non-NULL address of the dest data object when it is accessible using memory loads and stores in addition to OpenSHMEM operations. Otherwise, a NULL address is returned.

The intent was to allow load/store access to symmetric memory between PEs on the same node.

## Bug Report / Feature Request

While load/store access to symmetric objects in the data segment may require XPMEM -- which, understandably, not all OSHMEM installations will have -- such support is desired for objects in the symmetric heap between PEs in the same load/store domain.

Ideally, calling `shmem_ptr()` should return non-null values for:
* All symmetric objects on the same node (data segment or symmetric heap), if XPMEM is available.
* Symmetric objects from the symmetric heap that are on the same node, if XPMEM is not available.

**Comment by hppritcha** [comment]
@jladd-mlnx this has been fixed, correct?  I thought this was fixed all the way back to 2.1.x.

**Comment by jladd-mlnx** [comment]
This is fixed in 3.1 on systems that support XPMEM.

**Comment by hppritcha** [comment]
Okay I'm going to close this as fixed.
