### ISSUE TITLE
OpenBSD: segv running ring with OpenMPI 2.1.0rc2 

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#3115]
Configuring 2.1.0rc2 with --enable-mca-no-build=patcher, @PHHargrove got a segfault.

See https://www.mail-archive.com/devel@lists.open-mpi.org//msg19985.html

**Comment by hppritcha** [comment]
per discussion in the devel core meeting we're not sure whether this is a setup issue specific to the system or a problem with ompi.  Keeping open but moving to future mileston.

**Comment by PHHargrove** [comment]
I have reproduced the SEGV 4 times and examined the core files each time.  
In three of four the `(gdb) info threads` output looks like:
```
(gdb) info threads
  3 process 69042  0x0db388e3 in kevent () at <stdin>:2
  2 process 25383  0x0064c53f in _dl_munmap () at /usr/src/libexec/ld.so/i386/ldasm.S:114
* 1 process 83270  0x0064dcf3 in _dl_find_symbol_obj (object=0x84af1000, name=0x98096ab "strsignal", hash=Variable "hash" is not available.
)
    at /usr/src/libexec/ld.so/resolve.c:540
```
The fourth is
```
(gdb) info threads
  3 process 58066  0x049dd8e3 in kevent () at <stdin>:2
  2 process 94456  0x0e35f7a6 in _dl_bind (object=0x83135e00, index=200)
    at /usr/src/libexec/ld.so/i386/rtld_machine.c:406
* 1 process 39038  0x0e35ccf3 in _dl_find_symbol_obj (object=0x883f4800, name=0xec7b02f "send", hash=Variable "hash" is not available.
)
    at /usr/src/libexec/ld.so/resolve.c:540
```

One common thread (pun intended) is that in addition to the faulting thread, there is always an additional thread also in an `_dl_*` function.  So, the possibility exists that this is an OS bug with respect to thread safety in the dynamic linker/loader.  However, it is also possible (and I will look into this as time allows) that Open MPI is failing to pass some option at link time required to get thread safety.

**Comment by PHHargrove** [comment]
>  However, it is also possible (and I will look into this as time allows) that Open MPI is failing to pass some option at link time required to get thread safety.

Adding `-pthreads` to the application link command did not help.

**Comment by PHHargrove** [comment]
I can confirm that configuring with `--disable-dlopen` lets me run ring_c more than 100 consecutive times without any failure.  So, that is probably the recommended work-around.

**Comment by rhc54** [comment]
Okay, thanks Paul!

@jsquyres Can you please add that to the README?

**Comment by jsquyres** [comment]
Got it in the updated README for v2.1.0 coming shortly...
