### ISSUE TITLE
Free/NetBSD: PMIX build failures using OpenMPI 2.1.0rc2

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#3116]
@PHHargrove reported a PMIX build failure when trying to build OpenMPI 2.1.0rc2 for Free/NetBSD systems at his disposal:

https://www.mail-archive.com/devel@lists.open-mpi.org//msg19986.html

He's providing a patch.

**Comment by rhc54** [comment]
Fixed here: https://github.com/pmix/pmix/pull/326

Will patch OMPI shortly

**Comment by hppritcha** [comment]
Closed via #3118
