### ISSUE TITLE
Remove loadleveler support

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#3167]
loadleveler is no longer being maintained by IBM and no appears to be willing to support it.  So time for it to be removed as a orte/ras component.  

@gpaulsen

**Comment by gpaulsen** [comment]
I asked internally to see if we have any legacy machines to test on.
Going forward IBM is not interested in maintaining support, but if we can find some internal resources we can test one time to determine it's current state.

**Comment by hppritcha** [comment]
Waiting for testing results from IBM.

**Comment by hppritcha** [comment]
any updates on IBM testing?

**Comment by hppritcha** [comment]
any updates from IBM?

**Comment by gpaulsen** [comment]
I still haven't tested yet.  I'll try to get it done this week, but I still need access to this older test cluster.
