### ISSUE TITLE
openib BTL should not register its mpool unless the BTL is actually used

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#3183]
Per https://github.com/open-mpi/ompi/issues/3182, the openib BTL is registering its mpool before it should -- even if the openib BTL is not actually used for communication with any peer processes.  This is causing MPI_ALLOC_MEM to register memory with verbs, even when there are no peers to reach via the verbs API.  Case in point is when running a job on a single node (where the verbs API is not used at all), ALLOC_MEM is still registering memory with the openib BTL/verbs API.

Instead, the openib BTL should not register its mpool until it has its add_procs invoked to setup communication with at least one peer (and it should remove its mpool once communications with the last peer are removed).

@hjelmn tells me that there's probably a lot of things in the openib module startup that could be deferred util first add_proc invocation.

@larrystevenwise @bharatpotnuri Can you look into the startup progression in openib and defer as much resource allocation / etc. until the first add_procs? (and appropriately tear things down when there are no more procs left)

**Comment by bharatpotnuri** [comment]
@jsquyres I am stuck with some other work, I will try to make some time for this. Shall look into it.
Thanks!

**Comment by hppritcha** [comment]
@bharatpotnuri any update on this issue?

**Comment by bharatpotnuri** [comment]
@hppritcha Sorry, I could not work on this.  I started looking into it now.

**Comment by hppritcha** [comment]
Not fixing this in the 2.0.x release stream.

**Comment by hppritcha** [comment]
@jsquyres I'm inclinded to close this as won't fix for v2.x.  What do you think?

**Comment by jsquyres** [comment]
Yeah, unless @hjelmn is going to fix this, I doubt anyone else is going to.
