### ISSUE TITLE
mpirun does not redirect stdout in openmpi-2.0.2

### ISSUE THREAD

**Issue by jfikar** [open-mpi/ompi#3188]
I have problem redirecting stdout to a file using mpirun > and openmpi-2.0.2, while openmpi-1.4.3 works as expected.

* Simple test script `test.sh`:
```bash
#!/bin/bash
while true
do
    sleep 5
    echo -n "."
done
```

* Run test:
`mpirun -n 4 ./test.sh > out& tail -f out` 

* Expected behaviour (1.4.3): out gets progressively filled with dots

* Wrong behaviour (2.0.2): out is empty all the time; stderr:
```
[warn] Epoll ADD(4) on fd 1 failed. Old events were 0; read change was 0 (none); write change was 1 (add); close change was 0 (none): Operation not permitted
```

On the other hand, this works also in 2.0.2
`mpirun -n 4 ./test.sh | tee out`

I'm on Gentoo Linux. Original [bugreport](https://bugs.gentoo.org/show_bug.cgi?id=612708).

**Comment by jsquyres** [comment]
FWIW, when I run with a vanilla build of Open MPI v2.0.2, I get the expected output that you describe (4 dots appearing every 5 seconds).

The warning message you are seeing on stderr is likely symptomatic and possibly indicates the real error.

@rhc54 Is there any verbosity that can be increased here to shed more light on what is failing in libevent?

**Comment by jfikar** [comment]
I just tried to compile the vanilla 2.0.2 with simply `./configure;make -j6`, but I'm not able to run it without installing:
```
openmpi-2.0.2/orte/tools/orterun/orterun -n 4 ./test

--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
But I couldn't open the help file:
    /usr/local/share/openmpi/help-opal-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
```

While the binary itself complains about symbols (that is expected I guess):
```
openmpi-2.0.2/orte/tools/orterun/.libs/orterun -n 4 ./test

openmpi-2.0.2/orte/tools/orterun/.libs/orterun: symbol lookup error: openmpi-2.0.2/orte/tools/orterun/.libs/orterun: undefined symbol: opal_libevent2022_event_assign
```

**Comment by jsquyres** [comment]
Check to make sure your LD_LIBRARY_PATH is pointing to the right place.

**Comment by jfikar** [comment]
shouldn't the script `openmpi-2.0.2/orte/tools/orterun/orterun` do it for me automagically?

**Comment by jsquyres** [comment]
`mpirun` is not a script, and no.  😄

**Comment by jfikar** [comment]
well, that orterun in the build folder, which I'm talking about is really a script:
```
#! /bin/sh

# orterun - temporary wrapper script for .libs/orterun
# Generated by libtool (GNU libtool) 2.4.6
#
# The orterun program cannot be directly executed until all the libtool
# libraries that it depends on are installed.
#
# This wrapper script should never be moved out of the build directory.
# If it is, it will not operate correctly.
...
```

anyway setting the LD_LIBRARY_PATH and using the binary in .libs gets me to the same point as using the wrapper
```
LD_LIBRARY_PATH=openmpi-2.0.2/orte/.libs:openmpi-2.0.2/opal/.libs  openmpi-2.0.2/orte/tools/orterun/.libs/orterun -n 4 ./test
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
But I couldn't open the help file:
    /usr/local/share/openmpi/help-opal-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
```

**Comment by rhc54** [comment]
Why not just install it into a prefix under your home directory?

**Comment by jsbronder** [comment]
Note that we do use the system libevent in Gentoo (rather than the bundled version).  I'm getting the same behavior as @jfikar using libevent-2.0.22.

It looks like that's been a culprit in the past https://bugzilla.redhat.com/show_bug.cgi?id=1235044

**Comment by rhc54** [comment]
That version should be okay - the error being reported is actually a known bug in the 2.0 series due to a race condition upon application process finalize. It is harmless, albeit annoying, and has nothing to do with the reported problem.

**Comment by jfikar** [comment]
local install works

the vanilla 2.0.2 works without problem with redirecting and there is no warning

**Comment by jsquyres** [comment]
Can you try configuring Open MPI v2.0.2 with `--with-libevent=external` (to pick up the system-level libevent)?

I wonder if there's some kind of buffering issue going on -- i.e., Open MPI *is* outputting the data properly, but your stdout/stderr/tty/whatever is buffering it.

Try emitting a newline after the "." in your script -- tty buffering is sometimes by a max char count *or* a newline.

**Comment by rhc54** [comment]
One possibility then is if the system libevent wasn't built with thread support. Our configure logic is supposed to check for that and error out if it isn't, but perhaps there is an error in those checks? You should see a libevent-pthreads library (or something like that, I may have misspelled the precise name)

**Comment by jfikar** [comment]
newline is not a problem, the actual program outputs a lot of lines, but it also gets not redirected

so the with `--with-libevent=external` the error is back

**Comment by jfikar** [comment]
libevent "should" have threads
```
emerge -pv libevent

These are the packages that would be merged, in order:

Calculating dependencies            ... done!  
[ebuild   R    ] dev-libs/libevent-2.1.8:0/2.1-6::gentoo  USE="ssl threads -debug (-libressl) -static-libs {-test}" ABI_X86="(64) -32 (-x32)" 0 KiB
```

**Comment by rhc54** [comment]
I may be misunderstanding that output - doesn't it point to a much older version of libevent?

**Comment by rhc54** [comment]
Or maybe I should just say, a different version?

**Comment by jfikar** [comment]
it should be libevent-2.1.8, we don't seem to have more recent in Gentoo

**Comment by jfikar** [comment]
the other number in brackets corresponds to the actual file name libevent-2.1.so.6, so some versions can be in principle installed simultaneously, but it is not my case

**Comment by rhc54** [comment]
I see the problem, then - you are actually too far ahead of us 😄 . There were a bunch of changes in libevent when they went from 2.0.x to 2.1.x, and we haven't yet made all the necessary adjustments. I'm afraid you'll have to step down for us. If you want to use an external copy, then please install libevent-2.0.22 and see if that resolves the problem.

**Comment by jfikar** [comment]
with libevent-2.0.22 I unfortunately see the same problem

**Comment by jsquyres** [comment]
How did you test with 2.0.22?

Did you uninstall libevent 2.1.x from your system, install libevent 2.0.22, then re-configure and re-build Open MPI with `--with-libevent=external` (so that it picks up the headers and libraries of libevent 2.0.22)?

If you didn't do that, you may have accidentally been using some kind of strange hybrid of libevent 2.1.x and 2.0.x between the build and run-time link.  Or possibly even still wholly using libevent 2.1.x.

FWIW: this is exactly why we bundle libevent -- forward and backward compatibility issues like this are really, really hard to maintain over the release lifetime of a given software package.  It may well be easier to simply use the libfabric that is bundled in Open MPI.  Or use a Gentoo recipe that specifically installs libevent 2.0.22, and then specifically points Open MPI at the libevent 2.0.22 headers.

---

(BTW, to answer an older question of yours from earlier: I didn't realize you were running `mpirun` from within the build tree.  The script you were using is a Libtool artifact that intends to make it possible to run from within a build tree, but since Open MPI makes heavy use of plugins, it is *significantly* easier to run from the install tree [vs. the build tree].  `mpirun` itself -- in the install tree -- is not a script, and must be pointed at the right run-time libraries to function properly.  That's what I was referring to in my answer.  Hope that helps explain my previous answer!)

**Comment by jfikar** [comment]
I did a downgrade of system libevent to 2.0.22, that's the only libevent now. Then I got a message to recompile the system openmpi-2.0.2...

But to be completely sure I did it once more your way, i.e. with the vanilla source and --with-libevent=external. The same result, empty out and the warning.

**jsbronder**  also said earlier, he sees the problem with 2.0.22 as well

The new version of libevent is somehow needed for ntp on my system, which I temporarily removed.

**Comment by jsquyres** [comment]
There must be something different about the system libevent vs. the embedded libevent (the embedded libevent is 2.0.22).

This is how we configure the embedded libevent in Open MPI:

```
./configure --disable-dns --disable-http --disable-rpc --disable-openssl \
    --enable-thread-support --disable-evport --prefix=/home/jsquyres/bogus \
    --disable-oshmem CPPFLAGS=-I/home/jsquyres/openmpi-2.0.2 \
    -I/home/jsquyres/openmpi-2.0.2 -I/home/jsquyres/openmpi-2.0.2/opal/include   \
    -I/home/jsquyres/openmpi-2.0.2/opal/mca/hwloc/hwloc1112/hwloc/include \
    -Drandom=opal_random --cache-file=/dev/null --srcdir=. --disable-option-checking
```

Note: `/home/jsquyres/openmpi-2.0.2` is the path of my source tree.  `--enable-thread-support` is likely the most important option in there.  The `-Drandom=opal_random` shouldn't affect libevent's core correctness -- we just do that so that libevent's use of `random()` doesn't perturb the application's use of `random`.

**Comment by jsbronder** [comment]
Here's mine:
```
/var/tmp/portage/dev-libs/libevent-2.0.22/work/libevent-2.0.22-stable/configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --libdir=/usr/lib64 --disable-debug-mode --disable-malloc-replacement --enable-openssl --disable-static --enable-thread-support
```

**Comment by rhc54** [comment]
I tested this with master and v3.x, and it works fine. At some point we will either break away from libevent or update our support to the libevent 2.1 series. Until then, I don't think there is much we can do here. Either way, we won't backport it to anything earlier than OMPI v3.0.
