### ISSUE TITLE
PMIX ERROR: UNPACK-PAST-END (persistent dvm)

### ISSUE THREAD

**Issue by marksantcroos** [open-mpi/ompi#3192]
One of our users is running into this issue quite frequently (https://github.com/radical-cybertools/radical.pilot/issues/1235):

```
[nid12737:01598] PMIX ERROR: UNPACK-PAST-END in file /lustre/atlas/world-shared/csc230/openmpi/src/ompi/opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c at line 113
[nid12737:01598] UNEXPECTED MESSAGE tag = 256
```

This is with persistent DVM and orterun, on  a 1024 core DVM running 1024 single core tasks.

This is with OMPI master tag 6da4dbb.

I'm still in the process of reproducing it, and seeing whether it also happens on the latest master, but wanted to get it out here, as people might have a clue already.

**Comment by rhc54** [comment]
That is an odd one - it's indicating that the client received an error notification, but the message had nothing in it (since the reported unpack error is at the first unpack operation). I just tried the DVM and it seems to be working fine, but I can't get to that scale. @hjelmn is reporting problems at 1024 as well, but the error symptom is different.

**Comment by rhc54** [comment]
I committed something that may have resolved this - can you try current master and see if it is still present?

**Comment by marksantcroos** [comment]
Thanks, will do.
It looks btw that this error was not the cause of the "1024 cores problem" that we were seeing, that was actually caused by (#1132).
Note that I had general problems with the latest master before your recent changes that I was still debugging and hadn't reported yet.
Hopefully I get to it today.

**Comment by rhc54** [comment]
Okay - we believe we have the ALPS node ordering problem fixed (at least, it is working for @hjelmn), so please let us know there too. Meantime, let's coordinate on the debug - we'll get this nailed down yet 😄

**Comment by marksantcroos** [comment]
This one I'm still seeing as of `d7f283c`.

**Comment by marksantcroos** [comment]
Sorry, ignore my latest statement for now.

**Comment by marksantcroos** [comment]
With master+#3310 I don't see them anymore. Closing for now. Thanks!
