### ISSUE TITLE
size of MPI_Offset on 32-bit machines

### ISSUE THREAD

**Issue by wkliao** [open-mpi/ompi#3195]
What should the size of MPI_Offset type be on 32-bit machines?
On one of my i386 machines, both the latest official OpenMPI releases 1.10.6 and 2.0.2 show sizeof(MPI_Offset) = 4.

FYI, the size is 8 when using MPICH on the same machine.

**Comment by wkliao** [comment]
An additional note. The OS on my 32-bit machine does support "Large File Support (LFS)" where data type off_t can be adjusted to be 64 bits with proper compile flags.

I am not sure whether this should be considered as a bug, but OpenMPI's configure.ac can simply add AC_SYS_LARGEFILE to enable LFS.

**Comment by wkliao** [comment]
After consulting with [Rajeev Thakur](https://github.com/rsth) and [Rob Latham](https://github.com/roblatham00) from the MPICH team, we believe it is a bug in OpenMPI to define MPI_Offset a 4-byte integer, if OpenMPI intended to support LFS on 32-bit machines that support LFS. If it is otherwise, we are interested to know the motivation behind it.

**Comment by edgargabriel** [comment]
I *think* that this part of the configure logic is actually fairly old, 
so its most likely not a recent bug or regression. We can look into 
fixing this, but realistically 32bit platforms are meanwhile fairly 
rare. Jeff and Howard, any opinions on that?

Edgar

**Comment by jsquyres** [comment]
Looks like this was done in purpose.  See the comment here: https://github.com/open-mpi/ompi/blob/master/config/ompi_find_mpi_aint_count_offset.m4#L62-L77

@hjelmn @bosilca Is this statement still true (keeping in mind that `sizeof(MPI_Offset)` must be <= `sizeof(MPI_Count)`):

> The entire BTL, PML, and convertor infrastructure rely on sizeof(MPI_Count) being <= sizeof(size_t).

If not, we can re-evaluate the size of `MPI_Offset` on 32 bit platforms (but I agree with @edgargabriel -- this unfortunately probably a low priority request).

**Comment by bosilca** [comment]
If the only constraint is the BTL, PML and the convertor then it should be safe to have MPI_Offset equal to size_t (this is also what the statement requires <=).

**Comment by hppritcha** [comment]
How impactive would relaxing this constraint be on all PMLs?  I'm concerned about needing to modify lots of converter code in the various PMLs.

**Comment by bosilca** [comment]
@hppritcha there will be 0 impact. Our code is already built over size_t and ssize_t.

**Comment by wkliao** [comment]
Just to ping this issue. Will there be a fix in the future for the 32-bit machines?

One of PnetCDF users reported this same problem today.
He is using OpenMPI 1.10.6 and OpenMPI 2.1 on a 32-bit machine.
