### ISSUE TITLE
update header file used by fs/lustre component

### ISSUE THREAD

**Issue by edgargabriel** [open-mpi/ompi#3223]
the fs/lustre component uses a deprecated header file (liblustreapi.h) instead of the newer version (lustreapi.h). Add the configure logic to detect the proper header file to include and use.

**Comment by hppritcha** [comment]
@edgargabriel do you think you will have a fix for this issue for 2.1.1?

**Comment by hppritcha** [comment]
@edgargabriel where are we on this issue?

**Comment by hppritcha** [comment]
@edgargabriel do you want this fix in 2.0.x?  If so, I think you need to open a PR against that branch too, otherwise I think this issue can be closed.

**Comment by edgargabriel** [comment]
I think we don't necessarily have to move this to the 2.0. series as well, it is in 2.1 and in 3.0. If necessary, we can still reopen it anytime.
