### ISSUE TITLE
Abstraction violation: sshmem/ucx and atomic/ucx include oshmem/mca/spml/ucx/spml_ucx.h

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#3224]
The sshmem/ucx and atomic/ucx components are directly including the spml_ucx.h header file from the spml/ucx component, and directly using symbols from the spml/ucx_component.

This is an abstraction violation and is not allowed in the MCA architecture.  It works if you `--disable-dlopen` (and slurp all components up into liboshmem), but it does not work if the components are all individual DSOs that are dlopened individually.

The atomic/ucx behavior exists on master, v3.x, v2.x, and v2.0.x.

The sshmem/ucx behavior exists on master and v3.x.

(I didn't bother checking back as far as v1.10)

**Comment by jsquyres** [comment]
@artpol84 @jladd-mlnx Is there an ETA when this will be fixed?

**Comment by jsquyres** [comment]
@artpol84 @jladd-mlnx @xinzhao3 This is now showing up in CI testing.  For example, I see this:

```
[juno001:05975] mca_base_component_repository_open: unable to open mca_atomic_ucx: /var/lib/jenkins/ompi-master/workspace/open-mpi.build.platforms@2/Platform/ARMv8/install/lib/openmpi/mca_atomic_ucx.so: undefined symbol: mca_spml_ucx (ignored)
```

In https://jenkins.open-mpi.org/jenkins/job/open-mpi.build.platforms/2953/Platform=ARMv8/console.

When will this be fixed?  It's a clear abstraction violation.

**Comment by artpol84** [comment]
@jsquyres sorry this fell out of my attention. I’ll check and get back to you.

**Comment by yosefe** [comment]
@hoopoepg pls add a fix to this as part of your oshmem atomic work

**Comment by hoopoepg** [comment]
@jsquyres there is PR where issue should be suppressed. could you check if it works?
https://github.com/open-mpi/ompi/pull/5380

**Comment by jsquyres** [comment]
@hoopoepg Sweet -- thank you!  Can you also PR this to v3.0.x?

**Comment by hoopoepg** [comment]
@jsquyres done: https://github.com/open-mpi/ompi/pull/5401
