### ISSUE TITLE
Tool attach failure

### ISSUE THREAD

**Issue by lee218llnl** [open-mpi/ompi#3243]
When using the latest OpenMPI commit (d782542c5ce403db835462005523afe2f2613da3) and trying to attach to an MPI job via LaunchMON (https://github.com/LLNL/LaunchMON) I get the following error:

```
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 60 slots
that were requested by the application:
  /nfs/tmp2/lee218/prefix/stat-travis/bin/STATD

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
```

I am on a system that allocated nodes via SLURM and this is on 2 nodes with 64 tasks. The application was launched with mpirun/orterun with 4 MPI processes, which might explain why it's trying to fill the node with 64-4=60 slots. However, it should only try launching 1 STATD daemon process per node. Let me know if there are more diagnostics that I can gather to help diagnose this. Note I am able to attach TotalView to the a similarly launched MPI job, so LaunchMON is doing something different than TotalView for process acquisition/daemon launch.

Perhaps similarly related, I notice that if I instead launch the MPI application using all 64 tasks that were allocated, my attempt to attach a tool results in:
```
--------------------------------------------------------------------------
All nodes which are allocated for this job are already filled.
--------------------------------------------------------------------------
```

Let me know if this should be submitted as a separate issue. I can provide additional diagnostics for this too if need be.

**Comment by lee218llnl** [comment]
@rhc54 can you help me look at this one or find someone else who can help?

**Comment by rhc54** [comment]
I can help, but need another day or two to get to it. Is this with OMPI's "master" branch?

**Comment by lee218llnl** [comment]
Thanks, and yes, this was on OMPI's master branch.

**Comment by rhc54** [comment]
@ggouaillardet I'm stuck resolving another issue - would you have a chance to look at this and/or perhaps https://github.com/open-mpi/ompi/issues/3247?

**Comment by ggouaillardet** [comment]
@lee218llnl can you please provide detailled instructions on how to reproduce the issue
- slurm script and sbatch command line
- launchmon command line

**Comment by lee218llnl** [comment]
The same steps outlined in #3247 should demonstrate this issue, albeit pointing to different versions of OpenMPI. Here's what I did:

git clone https://github.com/llnl/launchmon.git
cd launchmon/
export PATH=/collab/usr/global/tools/openmpi/toss_3_x86_64_ib/openmpi-test/bin:$PATH
./configure --with-test-rm=orte --with-test-rm-launcher=/collab/usr/global/tools/openmpi/toss_3_x86_64_ib/openmpi-test/bin/mpirun --with-test-installed --with-test-ncore-per-CN=2 --with-test-nnodes=1 --prefix=/nfs/tmp2/lee218/prefix/launchmon-openmpi-test && make clean && make -j 8 install && make -j 8 check
cd test/src
./test.launch_1

The error I get is:

[LMON_FE] launching the job/daemons via /collab/usr/global/tools/openmpi/toss_3_x86_64_ib/openmpi-test/bin/orterun

[LMON FE] 6 RM types are supported
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 30 slots
that were requested by the application:
  /g/g0/lee218/src/LaunchMON/test/src/be_kicker

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
<Apr 05 08:36:18> <LMON FE API> (INFO): FE-ENGINE connection timed out: 120
[LMON FE] FAILED


Thanks for looking into this.

**Comment by lee218llnl** [comment]
Also, if you modify the test.launch_1 script to make NUMTASKS fill the allocation, then you will get:
```

[LMON_FE] launching the job/daemons via /collab/usr/global/tools/openmpi/toss_3_x86_64_ib/openmpi-test/bin/orterun

[LMON FE] 6 RM types are supported
--------------------------------------------------------------------------
All nodes which are allocated for this job are already filled.
--------------------------------------------------------------------------
```

**Comment by rhc54** [comment]
Hmmm...just tried this with current head of master repo:
```
$ ./test.attach_1
This RM is not supported yet
./test.attach_1: line 95: fe_attach_smoketest: command not found
$
```
Did I miss something, or perhaps something has changed in master that fixed the problem? I configured with:
```
  $ ./configure --prefix=/home/common/launchmon/build --with-test-rm=orte --with-test-rm-launcher=mpirun --with-test-installed --with-test-nnodes=1
```
I have mpirun in my PATH.

**Comment by lee218llnl** [comment]
@rhc54 you may want to try giving configure the full path to mpirun

**Comment by rhc54** [comment]
Got different output, but it still ran:
```
$ ./test.attach_1
[rhc001:177054] CHECKING TOPOS
[rhc001:177054] SKIPPING
[rhc001:177054] CHECKING TOPOS
[LMON APP] singal handler installed for signum=10
<Apr 11 10:48:49> APP (INFO): stall for 3 secs
<Apr 11 10:48:52> APP (INFO): stall for 3 secs
<Apr 11 10:48:55> APP (INFO): stall for 3 secs
<Apr 11 10:48:58> APP (INFO): stall for 3 secs
<Apr 11 10:49:01> APP (INFO): stall for 3 secs
<Apr 11 10:49:04> APP (INFO): stall for 3 secs
./test.attach_1: line 95: fe_attach_smoketest: command not found
<Apr 11 10:49:07> APP (INFO): stall for 3 secs
<Apr 11 10:49:10> APP (INFO): stall for 3 secs
<Apr 11 10:49:13> APP (INFO): stall for 3 secs
<Apr 11 10:49:16> APP (INFO): stall for 3 secs
<Apr 11 10:49:19> APP (INFO): stall for 3 secs
<Apr 11 10:49:22> APP (INFO): stall for 3 secs
<Apr 11 10:49:25> APP (INFO): stall for 3 secs
$
```
Note that I had a bunch of leftover processes "hang_on_SIGUSR1" that I had to manually kill

**Comment by rhc54** [comment]
aha - I can now replicate. The test/src directory has to also be in the PATH. Will take a look at this.

**Comment by rhc54** [comment]
Just an FYI: I'm making progress on this, but will probably need another day to complete it

**Comment by rhc54** [comment]
I'm afraid I am going to need some help here - can you please outline what test.attach_1 is doing? I got past the first error message that you reported, but now I'm getting another one:
```
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 25 slots
that were requested by the application:
  /home/common/launchmon/master/test/src/be_kicker

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
```
It would really help if I understood exactly what you are trying to launch (e.g., is be_kicker a debugger daemon or another job? did the first job already terminate?), and how you are launching them (e.g., nprocs and mapping pattern).

**Comment by lee218llnl** [comment]
@rhc54 The be_kicker is a daemon. It just sends a signal to the MPI job that was launched (hence the first job is still running). There should only be on be_kicker launched per compute node. @dongahn may be able to provide more details.

**Comment by rhc54** [comment]
Hmmm...so how are you telling me to launch that daemon? Thru the debugger interface? If so, then it sounds like I'm telling it to launch too many - something I can easily fix.

**Comment by lee218llnl** [comment]
yes, it should be launching through the debugger interface.

**Comment by rhc54** [comment]
@lee218llnl I think I have this fixed now - please try the referenced PR

**Comment by rhc54** [comment]
Kewl - thx!

**Comment by lee218llnl** [comment]
@rhc54 I think you saw your own comment and prematurely closed this. In any case, I checked out the master branch of OpenMPI and was able to run LaunchMON's test.attach_1 case. However, with the master branch running test.launch_1 case seg faults. I'm not sure if this is because #3323 is not merged into master or if this is a separate problem. In any case, I think it is OK to consider this issue closed and I will open a new one regarding the current seg fault in master.

**Comment by lee218llnl** [comment]
FYI I submitted #3348 for the new seg fault. The seg fault appears to be in MPI_Init in the target process.

**Comment by rhc54** [comment]
Sorry, I saw the ```+1``` from dong and thought it was fixed. Will look at the new one.

**Comment by dongahn** [comment]
Sorry for the confusion. I gave you my thumbs-up for your quick response on this issue. Still thank you very much for looking into this, Ralph. Your effort is highly appreciated here!

**Comment by rhc54** [comment]
😄  Now I just have to get you guys to integrate PMIx into LaunchMON so this connection would be less fragile...
