### ISSUE TITLE
configure doesn't always honor LDFLAGS

### ISSUE THREAD

**Issue by yaronyg** [open-mpi/ompi#3246]
__Platform:__
macOS Sierra - 10.12.4
Compiler - llvm 4.0.0 installed via homebrew
openMPI version - 1.10.3 (supported release)

__Scenario:__

I want to compile openMPI with openMP support on macOS To this end I ran 'brew install --with-toolchain llvm' to get llvm 4.0 with openMP support. To make this work through I need to set a slew of environment variables:

```
export CC=/usr/local/opt/llvm/bin/clang
export CXX=/usr/local/opt/llvm/bin/clang++ 
export CXXFLAGS='-I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include/c++/v1/'
export CPPFLAGS='-I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include/c++/v1/'
export LDFLAGS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib'
```

I then run:

```
wget https://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.3.tar.bz2
tar xf openmpi-1.10.3.tar.bz2
cd openmpi-1.10.3
./configure --prefix=/usr/local/mpi 2>&1 | tee config.out
make -j $(sysctl -n hw.logicalcpu) 2>&1 | tee make.out
```

__Expected Result:__
Make succeeds

__Actual Result:__

```
ld: library not found for -lomp
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

__What's Going On:__
I did some digging around and what seems to be happening is that the Makefiles in /ompi/contrib/vt/vt/tools/vtfilter and friends aren't properly honoring LDFLAGS so they can't find libomp.dylib and hence fail.

**Comment by rhc54** [comment]
Add ```--disable-vt``` to your configure line for OMPI

**Comment by yaronyg** [comment]
Yup, that seems to have worked! At least everything compiles without complaint. Thanks!

**Comment by rhc54** [comment]
kewl
