### ISSUE TITLE
opal_list: refcount not 0 during append

### ISSUE THREAD

**Issue by ael-code** [open-mpi/ompi#3264]
I'm experiencing the following assertion failure in debug mode:
```
openmpi-2.1.0/opal/class/opal_list.h:547: _opal_list_append: Assertion `0 == tem->opal_list_item_refcount' failed
```
The call stack is the following:
```
opal/class/opal_list.h -> _opal_list_append
ompi/mca/coll/libnbc/nbc.c -> NBC_Start
ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c -> ompi_coll_libnbc_ireduce_scatter_block
ompi/mpi/c/ireduce_scatter_block.c -> PMPI_Ireduce_scatter_block
```
I'm running a multithreaded code.

Here you have my current openmpi environment configuration:
[ompi_info.txt](https://github.com/open-mpi/ompi/files/885439/ompi_info.txt)

Let me if you need some more info

**Comment by ggouaillardet** [comment]
@ael-code if you could provide a simple test program that evidences the issue, that would be great !

since you are running a multithreaded code, did you ```MPI_Init_thread(..., MPI_THREAD_MULTIPLE,...)``` ?
do you ```MPI_Ireduce_scatter_block(...)``` from several threads at the same time ?

**Comment by ael-code** [comment]
> @ael-code if you could provide a simple test program that evidences the issue, that would be great !
> 
Unfortunately I'm running a PDE simulator that is rather than simple :(

> since you are running a multithreaded code, did you MPI_Init_thread(..., MPI_THREAD_MULTIPLE,...) ?

Yes and `MPI_THREAD_MULTIPLE` is supported.

> do you MPI_Ireduce_scatter_block(...) from several threads at the same time ?
Only one thread on each rank is invoking the function. Indeed is it true that at every round is it possible that a different thread will invoke the function but always one thread at time.

In any case it seems that I cannot reproduce the bug any more... I'll close the issue until I can manage to properly reproduce it.

Sorry for the noise :)
