### ISSUE TITLE
mpicc -showme have no suboptions

### ISSUE THREAD

**Issue by robertsawko** [open-mpi/ompi#3297]
Hello,

I am looking at the mpicc from version 2.0.2 and it seems to me that the `-showme` option of the `mpicc` wrapper has no support for options. It used to be possible to do `-showme:link` `-showme:compile` etc for a substring of the wrapping command.

Please let me know if this is intentional.

**Comment by nrgraham23** [comment]
The options for mpicc -showme are working for me.  I installed v2.0.2 on my mac and ran the command to test it out, and I had no problems.

Did you upgrade from a different version of ompi?  When you did, did you blow away the previous install directory?  I have had some issues when forgetting to do that in the past.

I'd try reinstalling and see if you still get the same problem.

**Comment by jsquyres** [comment]
I, too, am unable to replicate your issue:

```
$ mpirun --version
mpirun (Open MPI) 2.0.2

Report bugs to http://www.open-mpi.org/community/help/
$ mpicc --showme
gcc -I/home/jsquyres/bogus/include -pthread -Wl,-rpath -Wl,/home/jsquyres/bogus/lib -Wl,--enable-new-dtags -L/home/jsquyres/bogus/lib -lmpi
$ mpicc --showme:link
-pthread -Wl,-rpath -Wl,/home/jsquyres/bogus/lib -Wl,--enable-new-dtags -L/home/jsquyres/bogus/lib -lmpi
$ mpicc --showme:compile
-I/home/jsquyres/bogus/include -pthread
```

And with v2.1.0:

```
$ mpirun --version
mpirun (Open MPI) 2.1.0

Report bugs to http://www.open-mpi.org/community/help/
$ mpicc --showme
gcc -I/home/jsquyres/bogus/include -pthread -Wl,-rpath -Wl,/home/jsquyres/bogus/lib -Wl,--enable-new-dtags -L/home/jsquyres/bogus/lib -lmpi
$ mpicc --showme:link
-pthread -Wl,-rpath -Wl,/home/jsquyres/bogus/lib -Wl,--enable-new-dtags -L/home/jsquyres/bogus/lib -lmpi
$ mpicc --showmecompile
gcc -I/home/jsquyres/bogus/include -pthread -Wl,-rpath -Wl,/home/jsquyres/bogus/lib -Wl,--enable-new-dtags -L/home/jsquyres/bogus/lib -lmpi
```

Is it possible that you're using an old version of Open MPI that doesn't support things like `:link` and `:compile`?  I don't remember the exact version that we started supporting those CLI options, but I'm almost certain they weren't in v1.0.0.

I'm going to tentatively close this issue; please let us know if you have further questions or if we need to re-open the issue.  Thanks!

**Comment by robertsawko** [comment]
Sorry, for a late reply. I am quite sure I am using one of the latest versions as I am compiling it myself 2.0.2. I've tried from a clean install and we keep directories separate for each version on our cluster. I am not sure if this significant but I am building on ppc64le. Also the mpirun turns out be some sort of script whereas with previous versions it looks more like a link to a binary.

**Comment by jsquyres** [comment]
In Open MPI, mpirun is a binary, not a script.

Specifically, after `make install`, then `$prefix/bin/mpirun` should be a binary.  If it's not, then you've somehow got some other `mpirun` (and possible some other `mpicc` and friends, too) that does not belong to Open MPI.

**Comment by robertsawko** [comment]
Ok... I may have found my problem. I had that option switched on:

```
--enable-script-wrapper-compilers
                          Use less featured script-based wrapper compilers
                          instead of the standard C-based wrapper compilers.
                          This option ignores the --disable-binaries option
                          and is mainly useful in cross-compile environments
```

**Comment by jsquyres** [comment]
Ah!  Yes, these script compilers have probably not been updated in forever.  I don't know if they have ever supported `:link` and friends.

Is there a reason you want those script compilers?

(I'm actually not sure why we still ship those...)

**Comment by bwbarrett** [comment]
We ship them for cross-compile environments (like, say, Kitten, where the libraries built can't run on the compile node).  They never supported :link and friends, because I'm kind of lazy and we had no need for those features.

**Comment by jsquyres** [comment]
Ah, ok.  We should probably:

1. Add :link and friends to the script compilers, and/or
1. Be a bit stronger that "you shouldn't use these unless you need cross-compilation"

**Comment by robertsawko** [comment]
The reason why I find `:link` useful is that OpenFOAM uses it, in it's scripting for detecting OpenMPI and setting up its own build environment. On the cluster I am working at right now, we have a configuration which is off the beaten tracks in terms of compile vs compute nodes, but I hope we'll be fine withtout the above option.

**Comment by jsquyres** [comment]
If you don't need cross compilation, you should be fine with the normal (binary) wrapper compilers.

**Comment by robertsawko** [comment]
Ok. Retried everything and `:link` and co are working. Thanks.
