### ISSUE TITLE
Implement a "better" MPI preconnect function

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#33]
As discussed in https://svn.open-mpi.org/trac/ompi/ticket/1207, implement a "better" MPI preconnect function (https://svn.open-mpi.org/trac/ompi/ticket/1207 encompassed 2 ideas: "print the MPI connection map" and "better MPI preconnect" -- so I'm splitting the preconnect stuff out into its own ticket for clarity).  Copied from the old ticket:

= New "preconnect all" functionaliy =

 * Should completely replace old MPI preconnect functionality.
 * Need a new PML interface function: connect_all() that will connect this process to all others that it knows about (i.e., all ompi_proc_t's that it's aware of, which takes care of the MPI-2 dynamics cases). The main idea is to use the new active-message functionality to send an AM message tag to the remote PML peer. The message will cause a no-op function to occur on the other side, but it will force the connection to be made.
   * For BTL-related PMLs: do a btl_alloc() followed by a btl_send(). Loop over the btl_send's until they all complete or fail (i.e., keep checking the ones that return RESOURCE_BUSY).
   * For MTL-related PMLs: the function may be a no-op if there's no way to guarantee that connections are made. Or it may use the same general technique as the BTL-related PMLs: send an AM tag to its remote PML peer that causes a no-op on the remote side, but forces the connection to be made. The MTL may have specific knowledge about what needs to be done to force a connection of its lower layer.

**Comment by bosilca** [comment]
I don't think there is currently any interest in doing any improvement on the preconnect support. As we now open the connections lazily, this preconnect capability will have a significant overhead on the MPI_Init.
