### ISSUE TITLE
 Not found in file base/state_base_fns.c at line 474

### ISSUE THREAD

**Issue by Jiadun** [open-mpi/ompi#3305]
The program works. However, after some steps, the following information continues to come up.
[username-HP-ZBook-15:28309] [[18408,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474

**Comment by rhc54** [comment]
I'm afraid that doesn't tel us anything. What version of OMPI are you using? How did you run your application (i.e., the cmd line)? What does your application do?

**Comment by Jiadun** [comment]
Thanks for your reply:)
1) open mpi 1.10.2
2) mpirun -np 1 python some.py
3) in some.py mpi4py is used to spawn independent mpi program which takes 2 processes. 
 more details is here https://groups.google.com/forum/#!topic/mpi4py/8dNs5ndQm-Y

**Comment by rhc54** [comment]
From what I can tell, it sounds like your “some.py” program is itself invoking mpirun? If so, then this won’t work - you cannot recursively call mpirun.

**Comment by Jiadun** [comment]
Yes in some.py mpi4py is used to spawn mpi-program esysparticle in each iteration.
MPI.COMM_SELF.Spawn('/usr/local/bin//esysparticle',
                         args=['load.py'],
                         maxprocs=2,info=info)
If the number of iterations is not large, then there is no complain like "...line 474".
On the contrary, there will come up
358 18.2595404558 0.0438127126986
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
359 18.2560228157 0.0438211546993
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: Not found in file base/state_base_fns.c at line 474
[bwjliu-HP-ZBook-15:08295] [[2330,0],0] ORTE_ERROR_LOG: The system limit on number of children a process can have was reached in file odls_default_module.c at line 928
Killed

**Comment by rhc54** [comment]
I believe a possible workaround was discussed on the user mailing list, but this isn't a mode of operation that we really support.

**Comment by Jiadun** [comment]
The problem mentioned above was induced by the not-elegant way in which Program A repeatedly spawns many independent program B. Now it is solved in the way that the many independent program B are only spawned once in the Program A.
