### ISSUE TITLE
OMPI assuming UD capable verbs device?

### ISSUE THREAD

**Issue by fsl-latif** [open-mpi/ompi#3330]
Running OMPI with an Iwarp RDMA device that supports only RC QP's yields this error. If I run with this -mca oob ^ud option, then this error is not seen BUT it appears OMPI is detecting this device as UD capable. I checked ibv_query_device and there doesn't appear to be any attribute which specifies UD vs RC. Do you know how OMPI determines if the vendor is UD capable or not? 

```
[root@Elder0024 open_mpi]# ./openmpi_imb.sh
--------------------------------------------------------------------------
Failed to create a queue pair (QP):

Hostname: Elder0024
Requested max number of outstanding WRs in the SQ:                1
Requested max number of outstanding WRs in the RQ:                2
Requested max number of SGEs in a WR in the SQ:                   511
Requested max number of SGEs in a WR in the RQ:                   511
Requested max number of data that can be posted inline to the SQ: 0
Error:    File exists

Check requested attributes.
--------------------------------------------------------------------------
```

***EDIT: Put in a verbatim block***

**Comment by jsquyres** [comment]
@jladd-mlnx @artpol84 This is an issue with the OOB UD component.  A quick look at the code seems to indicate that it assumes that any verbs device supports UD, but this is apparently not the case.  Can someone look at OOB UD to make it silently skip devices that do not support UD?

**Comment by artpol84** [comment]
@karasevb

**Comment by hjelmn** [comment]
udcm is supposed to disable itself on anything that isn't infiniband. See:

https://github.com/open-mpi/ompi/blob/master/opal/mca/btl/openib/connect/btl_openib_connect_udcm.c#L447

That check *used* to work. Does it need to be updated?

**Comment by artpol84** [comment]
@fsl-latif is this still an issue?
