### ISSUE TITLE
Seg fault under debugger launch

### ISSUE THREAD

**Issue by lee218llnl** [open-mpi/ompi#3348]
Thank you for taking the time to submit an issue!

## Background information

I've been testing some tool attach/launch features of OpenMPI and run into a few issues. Some of these have already been reported as #3243 and #3247 and @rhc has been helping look at those issues. I am currently getting a seg fault in MPI_Init when launching an application under a tool's control.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

I see this in the master branch as of commit 38d712ab96793d1764d32466d79e619197448a6d

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### Please describe the system on which you are running

* Operating system/version: RHEL 7
* Computer hardware: x86_64
* Network type: Infiniband

-----------------------------

## Details of the problem

Here's how to reproduce:

```
git clone https://github.com/llnl/launchmon.git
cd launchmon/
export PATH=/collab/usr/global/tools/openmpi/toss_3_x86_64_ib/openmpi-2.1.0/bin:$PATH
CFLAGS="-g -O0" CXXFLAGS="-g -O0" ./configure --prefix=/nfs/tmp2/lee218/prefix/launchmon-1.0.3b --with-test-rm=orte --with-test-rm-launcher=/collab/usr/global/tools/openmpi/toss_3_x86_64_ib/openmpi-2.1.0/bin/mpirun --with-test-installed --with-test-nnodes=1 && make clean && make -j 8 install && make -j 8 check
cd test/src
./test.launch_1
```

The error I see is:

```
bash-4.2$ ./test.launch_1
[LMON_FE] launching the job/daemons via /collab/usr/global/tools/openmpi/toss_3_x86_64_ib/openmpi-test/bin/orterun

[LMON FE] 6 RM types are supported
[LMON BE(0)] Target process:   178367, MPI RANK:     0
[LMON BE(0)] Target process:   178368, MPI RANK:     1
[LMON BE(0)] Target process:   178369, MPI RANK:     2
[LMON BE(0)] Target process:   178370, MPI RANK:     3
[LMON FE] Please check the correctness of the following proctable
[LMON FE] host_name: rzoz2
[LMON FE] executable_name: /nfs/tmp2/lee218/delete/launchmon/test/src/simple_MPI
[LMON FE] pid: 178367(rank 0)
[LMON FE] 
[LMON FE] host_name: rzoz2
[LMON FE] executable_name: /nfs/tmp2/lee218/delete/launchmon/test/src/simple_MPI
[LMON FE] pid: 178368(rank 1)
[LMON FE] 
[LMON FE] host_name: rzoz2
[LMON FE] executable_name: /nfs/tmp2/lee218/delete/launchmon/test/src/simple_MPI
[LMON FE] pid: 178369(rank 2)
[LMON FE] 
[LMON FE] host_name: rzoz2
[LMON FE] executable_name: /nfs/tmp2/lee218/delete/launchmon/test/src/simple_MPI
[LMON FE] pid: 178370(rank 3)
[LMON FE] 

[LMON FE] RM type is 8

[LMON FE] RM launcher's pid is 178354
[rzoz2:178367] *** Process received signal ***
[rzoz2:178367] Signal: Segmentation fault (11)
[rzoz2:178367] Signal code:  (0)
[rzoz2:178367] Failing at address: (nil)
[rzoz2:178367] [ 0] /usr/lib64/libc.so.6(+0x35250)[0x2aaaab376250]
[rzoz2:178367] *** End of error message ***
[rzoz2:178368] *** Process received signal ***
[rzoz2:178368] Signal: Segmentation fault (11)
[rzoz2:178368] Signal code:  (0)
[rzoz2:178368] Failing at address: (nil)
[rzoz2:178368] [ 0] /usr/lib64/libc.so.6(+0x35250)[0x2aaaab376250]
[rzoz2:178368] *** End of error message ***
[rzoz2:178369] *** Process received signal ***
[rzoz2:178369] Signal: Segmentation fault (11)
[rzoz2:178369] Signal code:  (0)
[rzoz2:178369] Failing at address: (nil)
[rzoz2:178369] [ 0] /usr/lib64/libc.so.6(+0x35250)[0x2aaaab376250]
[rzoz2:178369] *** End of error message ***
[rzoz2:178370] *** Process received signal ***
[rzoz2:178370] Signal: Segmentation fault (11)
[rzoz2:178370] Signal code:  (0)
[rzoz2:178370] Failing at address: (nil)
[rzoz2:178370] [ 0] /usr/lib64/libc.so.6(+0x35250)[0x2aaaab376250]
[rzoz2:178370] *** End of error message ***
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
orterun noticed that process rank 2 with PID 178369 on node rzoz2 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

[LMON FE] PASS: run through the end
```

I also get the seg fault when launching a job under TotalView (MPI hello world should suffice as a target). It looks like the seg fault occurs in the target process in MPI_Init.

**Comment by rhc54** [comment]
Got it - let me know what you see

**Comment by lee218llnl** [comment]
Thanks again @rhc54, #3349 does appear to fix the test.launch_1 seg fault that I reported here. I was also able to launch under TotalView and run. One note, however, is that if I do not select "Halt control group" in TotalView, ten I get this warning:

```
FINITE STATE MACHINE BALKED: (duid=159) TFSM: pfs_stop(8) [pftr_get_SIGSTOP(73)]

FINITE STATE MACHINE BALKED: (duid=159) TFSM: pfs_stop(8) [pftr_get_SIGSTOP(73)
```

I don't see this if I do "Halt control group" in TotalView and issue a "Go". Should I report another issue for this?

**Comment by rhc54** [comment]
You might need to take that one to TV for an explanation - it's coming from their code, and I honestly have no idea what it means. If you can get an explanation from them and pinpoint what we might be doing that triggers it, then let's file an issue for that and I'll try to tackle it.

Sorry I can't just take it on - I don't have a TV license :-(

**Comment by lee218llnl** [comment]
ah yes, that message is coming from TotalView, not OpenMPI. I'll run this by them and have them report an issue if it comes back to OpenMPI. Thanks again for all of your help! I hope we'll see an OpenMPI release with all these fixes. What's the outlook for that?

**Comment by rhc54** [comment]
They will be in the 3.0 release, currently planned for June. Thanks for the patience, and for providing me with instructions on LaunchMON so I now have a way to actually test against a debugger!
