### ISSUE TITLE
Romio update problem

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#337]
Seeing this with --disable-dlopen:

  CC       ompi_info.o
  CC       param.o
  SED      ompi_info.1
  CCLD     ompi_info
../../../ompi/.libs/libmpi.so: undefined reference to `MPIO_Err_return_file'
../../../ompi/.libs/libmpi.so: undefined reference to `MPIO_File_resolve'
../../../ompi/.libs/libmpi.so: undefined reference to `MPIO_Err_create_code'
../../../ompi/.libs/libmpi.so: undefined reference to `MPIO_File_free'
../../../ompi/.libs/libmpi.so: undefined reference to `MPIO_File_create'
collect2: error: ld returned 1 exit status

**Comment by hjelmn** [comment]
@ggouaillardet Can you take a look?

**Comment by ggouaillardet** [comment]
@hjelmn i fixed this in open-mpi/ompi@b746a8f584bf3a195b56d4baff21a564550aa400
could you please double check this ?

**Comment by hjelmn** [comment]
@ggouaillardet Looks good now. Thanks!
