### ISSUE TITLE
MPICH test suite failures

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#3408]
## Background information
At the end of 2015 I fixed multiple issues that was triggering failures for OMPI v2.x in my MTT.
Recently I discovered tat since MTT error detection is relying on the app to fail/hang, we have some false negatives (negative = no error) in our MTT results that are being submitted to `mtt.open-mpi.org`.

MPICH tests are not error-exiting if correctness check is failed. MTT will detect severe bug that causes Segfault or hang for those tests, but not correctness check failure.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v2.x, github recent.

## MTT reports with false-negatives
* struct-zero-count (https://mtt.open-mpi.org/index.php?do_redir=2422)
* get-elements-pairtype (https://mtt.open-mpi.org/index.php?do_redir=2423)
* large-count (https://mtt.open-mpi.org/index.php?do_redir=2424)
* contig-zero-count (https://mtt.open-mpi.org/index.php?do_redir=2425)
* struct-no-real-types (https://mtt.open-mpi.org/index.php?do_redir=2426)
* typename (https://mtt.open-mpi.org/index.php?do_redir=2427)
* allred (https://mtt.open-mpi.org/index.php?do_redir=2428)
* alltoallw1 (https://mtt.open-mpi.org/index.php?do_redir=2429)
* mprobe (https://mtt.open-mpi.org/index.php?do_redir=2430)

There might be different reasons causing those failures. I suggest to keep this Issue as the base and open separate ones for the individual problems, referencing them here.

**Comment by artpol84** [comment]
`contig-zero-count` test. The error is here:
https://github.com/pmodels/mpich/blob/master/test/mpi/datatype/contig-zero-count.c#L99

for ompi (extent  == 1) instead of 0.

**Comment by artpol84** [comment]
It seems the same for `struct-zero-count`
https://github.com/pmodels/mpich/blob/master/test/mpi/datatype/struct-zero-count.c#L99

**Comment by artpol84** [comment]
For struct-no-real-types
I'm getting 
```
error: extent is 9223372036854775798 but should be -10 in no_real_types_test()
type map is { (LB,10) }, so UB is 0 and extent is ub-lb
```
here: 
https://github.com/pmodels/mpich/blob/master/test/mpi/datatype/struct-no-real-types.c#L104:L112

**Comment by artpol84** [comment]
`typename`:
```
Expected MPI_LONG_LONG but got MPI_LONG_LONG_INT
MPI_INTEGER16 is not available
```

**Comment by artpol84** [comment]
`get-elements-pairtype`:
```
MPI_Get_elements returned count of -32766, should be 3
```

**Comment by artpol84** [comment]
`allred` (for this test not all runs are failing, but those are:

```
(9) Error for type MPI_FLOAT and op MPI_PROD
(7) Error for type MPI_FLOAT and op MPI_PROD
(29) Error for type MPI_FLOAT and op MPI_PROD
(51) Error for type MPI_FLOAT and op MPI_PROD
(17) Error for type MPI_FLOAT and op MPI_PROD
(21) Error for type MPI_FLOAT and op MPI_PROD
(35) Error for type MPI_FLOAT and op MPI_PROD
(53) Error for type MPI_FLOAT and op MPI_PROD
(31) Error for type MPI_FLOAT and op MPI_PROD
(45) Error for type MPI_FLOAT and op MPI_PROD
(39) Error for type MPI_FLOAT and op MPI_PROD
(49) Error for type MPI_FLOAT and op MPI_PROD
(23) Error for type MPI_FLOAT and op MPI_PROD
(37) Error for type MPI_FLOAT and op MPI_PROD
(11) Error for type MPI_FLOAT and op MPI_PROD
(13) Error for type MPI_FLOAT and op MPI_PROD
(19) Error for type MPI_FLOAT and op MPI_PROD
...
```

**Comment by kawashima-fj** [comment]
`typename` (https://github.com/pmodels/mpich/blob/master/test/mpi/datatype/typename.c):

```
Expected MPI_LONG_LONG but got MPI_LONG_LONG_INT
MPI_INTEGER16 is not available
```

`MPI_LONG_LONG` is defined as a synonym of `MPI_LONG_LONG_INT` (see MPI-3.1 p.26) and Open MPI does not distinguish.

`MPI_INTEGER16` is an optional datatype (see MPI-3.1 p.627 and p.674). If `INTEGER*16` is not supported by the Fortran compiler, `MPI_INTEGER16` may not be available.

So I think they are not problems.

**Comment by kawashima-fj** [comment]
`get-elements-pairtype` is related to #2366.

**Comment by ggouaillardet** [comment]
the error related to ```allred``` is caused by floating numbers.
if we replace ```a == b``` with ```abs((a-b)/a) < 1.e-6``` then the test is successful
(this is all macro based, and could be a bit tricky to fix in an elegant manner ...)

**Comment by gpaulsen** [comment]
@artemry-mlnx Can we close this issue?

**Comment by artpol84** [comment]
I think we ca.
