### ISSUE TITLE
OpenMPI redirect question concerning libevent

### ISSUE THREAD

**Issue by mckenzieme** [open-mpi/ompi#341]
We have installed OpenMPI 1.8.4 and noticed some issues with libevent (specifically from omp_info: MCA event: libevent2021 (MCA v2.0, API v2.0, Component v1.8.2) ).  Apparently, there was a bug fix in version 1.7 that modified epoll events on standard file descriptors.  These descriptors are being used by PBS for standard output and will result in the program hanging:
[warn] Epoll ADD(1) on fd 0 failed.  Old events were 0; read change was 1 (add); write change was 0 (none): Operation not permitted.  

If we run a program using input/output flags (vs.  a.out < input), this problem goes away.  Could you comment on this?  And provide a path forward?

**Comment by rhc54** [comment]
Could you please clarify - I assume you are launching the app using mpirun, yes? So does your cmd line look something like "mpirun -n N a.out < input"?

I'm trying to understand how PBS gets in the mix. mpirun launches its own daemons using PBS, but then they fork/exec the app procs and use standard techniques to capture the stdin/out of the children so we can forward IO. PBS shouldn't be seeing the children at all, hence my confusion.

**Comment by mckenzieme** [comment]
Yes, you are correct, I did not place the complete command:  “mpirun –np 16 a.out < input”  versus “mpirun –np 16 a.out –inputflag input”.  
I too, am baffled.  I conducted another test by re-compiling OpenMPI without epoll support and then forcing " –mca opal_event_include poll " removes the problem but is not very clean or convenient.

What do you recommend I should check?

Here is the configuration:
export CC=icc
export FC=ifort
./configure --prefix=${INSTALL_DIR} \
  --disable-dependency-tracking \
  --disable-silent-rules  \
  --enable-binaries \
  --enable-mpi-cxx \
  --enable-mpi-cxx-seek \
  --enable-shared --enable-static \
  --enable-openib-rdmacm  \
  --enable-fast-install \
  --with-devel-headers \
  --with-hwloc=internal \
  --with-tm=/opt/pbs/default/ \
  --with-verbs=yes  \
  --with-mxm=/opt/mellanox/mxm
  --with-io-romio-flags="--with-file-system=ufs+nfs+lustre" \
  --with-platform=contrib/platform/mellanox/optimized \
  CC="icc" CXX="icpc" FC="ifort"

Would you like the complete ompi_info -a ?

**Comment by rhc54** [comment]
No, that would be too much info. What kind of system is this on? Isn't it sufficient to compile OMPI without epoll support - i.e. do you really also need the MCA param?

**Comment by mckenzieme** [comment]
This is on a Intel E5 dual socket cluster with FDR.  Even when compiled without epoll support we are forced to pass the MCA parameter. If you don’t it fails to launch the process.

**Comment by rhc54** [comment]
If you compile OMPI without excluding epoll support and provide the parameter, it should work - yes?

In other words, it shouldn't take _both_ steps, just one.

What OS are you on?

**Comment by mckenzieme** [comment]
I am using CentOS 6.4.   Looking into the epoll support and without epoll support builds, both builds have the file: etc/openmpi-mca-params.conf    In which both have "opal_event_include=poll" I can comment this out and it would work (allowing redirects), however I do not know what else this would impact.

**Comment by rhc54** [comment]
My apologies, but I am slightly confused by the above comments. Are you saying that redirection works if you simply comment out the "opal_event_include=poll" line in your default MCA params file? If so, then you should definitely remove that line. We don't add it, so someone must have done so - but I can't imagine why.

**Comment by rhc54** [comment]
I'm assuming that removing the MCA param resolved the problem. Please let us know if that wasn't the case.

**Comment by mckenzieme** [comment]
yes
