### ISSUE TITLE
plm/alps related commit  2a57e71 needs to be pushed back to 1.8 

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#345]
Turns out the comment corruption in plm_alps_module.c which resulted in commit 2a57e71 was also present in the 1.8 branch.  The commit needs to be pushed back in order to fix builds of 1.8 on Cray/alps systems.

**Comment by hppritcha** [comment]
@marksantcroos

This issue is a dup of the issue open-mpi/ompi-release#167
We normally open issues on open-mpi/ompi even if its an issue in the current OMPI release.

**Comment by marksantcroos** [comment]
@hppritcha 
Will do next time!

**Comment by hppritcha** [comment]
@bturrubiates If you'd like, you could try to push commit 2a57e71 back in to ompi-release.

The suggested method for doing this is at https://github.com/open-mpi/ompi/wiki/SubmittingPullRequests
with the link at the bottom leading to a step by step process.  Note you can skip all the pushing
back to ompi/master related steps since the commit is already there.  

We can work on this tomorrow.
