### ISSUE TITLE
How to convey MPI context from python to c++?

### ISSUE THREAD

**Issue by hujiePKU** [open-mpi/ompi#3463]
I have already written a c++ code with open-mpi, and I wrote a python wrapper with mpi4py. It means that I need import an encapsulated package in python  and  start program with 'mpirun -np 4 python xx.py' . The problem is that how to convey the MPI context from python to c++,  communicating in c++ layer.  It has been bothering me for a log time. Could you please give any advice? Thanks a lot.

**Comment by ggouaillardet** [comment]
@hujiePKU this is a question you should ask mpi4py, probably best at http://groups.google.com/group/mpi4py

**Comment by hujiePKU** [comment]
Thank you for your information.

**Comment by bosilca** [comment]
@hujiePKU if by context you means MPI communicator, keep in mind that all predefined MPI communicators (of interest here MPI_COMM_SELF and MPI_COMM_WORLD) are the same for all languages. Thus, either you can use them directly, or you can use attributes to pass the info around).
