### ISSUE TITLE
MPI_LB and MPI_UB used in MPI_Type_create_subarray and MPI_Type_create_darray

### ISSUE THREAD

**Issue by bosilca** [open-mpi/ompi#349]
Following a post on the [MPICH mailing list](http://lists.mpich.org/pipermail/discuss/2015-January/003608.html), Gus Correa brought to our attention the fact that Open MPI have a similar issue.

It turns out that the MPI standard page 97 line 37 (for subarray) and page 100 line 43 (for darray) suggests the use of the LB and UB markers when building subarrays and darrays. Our literal interpretation of the standard allowed for the propagation of the hard version of these markers (which were deprecated in MPI 2.2) on all datatypes build using subarrays and darrays. Unfortunately, until MPI_LB and MPI_UB are not removed from the MPI standard (and not just deprecated), we are forced to propagate such markers if they exists in the base datatype used to build subarrays and darrays. However, in all other cases we can use the new soft markers via a resized datatype construction.

**Comment by bosilca** [comment]
open-mpi/ompi@19c9646 should fix this problem.

**Comment by rhc54** [comment]
Committed the fix to 1.8.4
