### ISSUE TITLE
1sided with some hosts single rank (osc=rdma)

### ISSUE THREAD

**Issue by markalle** [open-mpi/ompi#3548]
If I launch a 1sided test where some of the hosts have a single rank while other hosts have multiple ranks, the test fails with a message like
```
[[57223,1],2][btl_openib_component.c:3556:handle_wc] from ibmgpu06 to: ibmgpu05
error polling LP CQ with status REMOTE ACCESS ERROR status number 10 for
wr_id 22ae5e8 opcode 128  vendor error 136 qp_idx 3
```

Examples that would fail:
```
    hostA:2,hostB:1
    hostA:1,hostB:2
```
examples that would pass:
```
    hostA:1,hostB:1
    hostA:2,hostB:2
```

I hit the same error with openib, eg
```--mca pml ob1 --mca btl self,vader,openib --mca osc rdma```
and MXM, eg
```--mca pml yalla --mca osc rdma```
although for the 1sided calls I think the above both end up in btl openib.

I've hit this issue with top of master, although I don't think it's anything new. I was running on x86-64, a mix of redhat 6 and 7, with mellanox IB cards.

The testcase I used is 1sided.c from the ompi-tests test harness at ibm/onesided/1sided.c. For convenience here's a gist of it
    https://gist.github.com/markalle/f245fef3a3294e3dcd5ae3db47a882c5
the failure happens very early, when the test is essentially doing "fence; get; fence" with each rank getting from its left-neighbor.

```
% mpicc -o x 1sided.c
% mpirun -host hostA:2,hostB:1 -np 3 --mca pml ob1 --mca btl self,vader,openib -mca osc rdma ./x
```
In the run mode where the ranks are laid out like this:
```
    hostA : [ R0, R1 ]
    hostB : [ R2 ]
```
R2 is the rank who prints the message about the error when polling.

Tracing backward a bit, I think R0's call to ompi_osc_rdma_peer_setup() for R2 is coming out wrong. Toward the bottom it has
```
    if (base_region->len) {
        if (registration_handle_size) {
            ex_peer->super.base_handle = malloc (registration_handle_size);
```
but that base_region->len is 0 so the base_handle stays NULL, where in the good runs the base_region->len is the window size and base_handle gets set. Beyond that point I'm not sure where that data comes from.

**Comment by jsquyres** [comment]
@hjelmn Could you comment?  Thanks!

**Comment by hjelmn** [comment]
Hmm, I will take a look on Monday.

**Comment by markalle** [comment]
Thanks, for what it's worth I traced it a bit further and am finding
```    module->state_offset```
is involved in the inconsistency. On the 2-rank host it's 40, on the 1-rank host it's 16. 

All ranks seem to have consistent values for looking up each other's ```node_peer_data->base``` values, but in ```ompi_osc_rdma_peer_setup()``` when they start trying to pull data from each other, the offset they use is based on differing ```state_offset```. I did confirm that if R0 were to look at offset 16 instead of offset 40 that it finds the correct data for its ```base_region->len```.

I haven't tried changing state_offset to be the same at each rank, or changing the lookups to understand that it's different at each node.

**Comment by markalle** [comment]
Okay, I think I've fixed it by making allocate_state_single() match allocte_state_shared(). I'll make a pull request for it, but the diff is
```
--- a/ompi/mca/osc/rdma/osc_rdma_component.c
+++ b/ompi/mca/osc/rdma/osc_rdma_component.c
@@ -393,7 +393,8 @@ static int allocate_state_single (ompi_osc_rdma_module_t *module, void **base, s
 
     /* allocate anything that will be accessed remotely in the same region. this cuts down on the number of
      * registration handles needed to access this data. */
-    total_size = module->state_size + local_rank_array_size + leader_peer_data_size;
+    total_size = local_rank_array_size + module->region_size +
+        module->state_size + leader_peer_data_size;
 
     if (MPI_WIN_FLAVOR_ALLOCATE == module->flavor) {
         total_size += size;
@@ -408,7 +409,9 @@ static int allocate_state_single (ompi_osc_rdma_module_t *module, void **base, s
         return OMPI_ERR_OUT_OF_RESOURCE;
     }
 
-    module->state_offset = local_rank_array_size;
+// Note, the extra region_size after the local_rank_array_size is unused
+// space but is there to match what happens in allocte_state_shared()
+    module->state_offset = local_rank_array_size + module->region_size;
 
     module->state = (ompi_osc_rdma_state_t *) ((intptr_t) module->rank_array + module->state_offset);
     module->node_comm_info = (unsigned char *) ((intptr_t) module->state + module->state_size);
```

**Comment by markalle** [comment]
https://github.com/open-mpi/ompi/pull/3551

**Comment by lcebaman** [comment]
Has this been fixed in 3.0.0? I am getting this error in a similar situation...

**Comment by jsquyres** [comment]
@markalle @jjhursey It looks like this fix was applied to master, but it did not come over to v3.0.x (although I do see it in v3.1.x).  Should this fix have been applied to v2.x and/or v3.0.x?

**Comment by markalle** [comment]
yeah, I think it could stand to be cherry-picked into any branch it isn't present
