### ISSUE TITLE
If openMPI support EDR over SRIOV

### ISSUE THREAD

**Issue by longerzone** [open-mpi/ompi#3555]
Thank you for taking the time to submit an issue!

## Background information
I'm using Mellanox 100G EDR with SRIOV on KVM virtualization, and I want to use the RDMA to communicate between VM with EDR Virtual Function.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
1.10.5a

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Have test with configure default
./configure --prefix=... 
and configure with hpc-x
./configure --prefix=/usr/local/ompi --with0knem=.../hpxc-gcc-.../knem --with-fca=.../hpcx...fca --with-mxm=...hpcx.../mxm --with-platform=...mellanox/optimized --with-slurm
and then 
make && make install

### Please describe the system on which you are running

* Operating system/version: Redhat/CentOS 7.2
* Computer hardware: KVM virtualization
* Network type:  Mellanox 100G EDR -- virtual Function

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

The Mellanox OFED driver has the OpenMPI-1.10.5a1, from the name, I think it's a modified version by Mellanox. And I could run application over RDMA with command 
```shell
mpirun -np -mca btl_openib_if_include "mlx5_0:1" -x MXM_IB_USE_GRH=y IMB-MPI1 Pingpong'
```
But, after I install the original OpenMPI-1.10.5, I find that I cannot run application over RDMA.

**Comment by jladd-mlnx** [comment]
@longerzone Please clarify, which PML are you using. Yalla or OB1. You are mixing variables that indicate using OpenIB BTL (-mca btl_openib_if_include "mlx5_0:1") and Yalla (-x MXM_IB_USE_GRH=y). Which are you using?

**Comment by artpol84** [comment]
@longerzone, any updates?

**Comment by artpol84** [comment]
@longerzone Can this be closed?

**Comment by thananon** [comment]
Closing due to no response. Can be reopened.
