### ISSUE TITLE
Remove C/R functionality from v3.0.0

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#3558]
Per https://github.com/open-mpi/ompi/pull/3554#issuecomment-302822944, we discovered that the C/R functionality is accidentally still on the branch that will become the v3.0.0 release.

It needs to be removed.  It's quite possible that the small number of commits to remove the C/R functionality from the v2.x branch -- paired with #3554 -- could be sufficient.  I.e., it could just be an exercise of tracking down the removal commits from the v2.x branch.

**Comment by hppritcha** [comment]
@jsquyres I think PR #3888 does the moral equivalent of this for 3.0.0?

**Comment by bwbarrett** [comment]
This was completed; closing ticket.
