### ISSUE TITLE
yalla with irregular contig datatypes

### ISSUE THREAD

**Issue by markalle** [open-mpi/ompi#3566]
Yalla has a macro PML_YALLA_INIT_MXM_REQ_DATA that checks if a datatype is contiguous via opal_datatype_is_contiguous_memory_layout(dt,count) and if so it selects a size and lb that presumably is what will rdma, as
                ompi_datatype_type_size(_dtype, &size); \
                ompi_datatype_type_lb(_dtype, &lb); \
    
This failed when I gave it a datatype constructed as ```[ ...]``` with extent 4. What I mean by that datatype is
```
        lens[0] = 3;
        disps[0] = 1;
        types[0] = MPI_CHAR;
        MPI_Type_struct(1, lens, disps, types, &tmpdt);
        MPI_Type_create_resized(tmpdt, 0, 4, &mydt);
```
So there are 3 chars at offset 1, and the LB is 0 and the UB is 4.
    
So their macro decides that size=4 and lb=0 and later I suppose size is getting updated to 3 for the final rdma, and so a send of a buffer ```[ 0 1 2 3 ]``` gets recved as ```[ 0 1 2 x ]```. 

If size and lb in that macro are to represent the offset and size of the contiguous thing to be sent, then I think the true lb and true extent would be the proper items to use.

In the normal case of "regular" contiguous datatypes it would all be the same. But in the case of irregular offsets/LB/UB I think the true lb and true extent are always the right thing to use for any datatype,count that could have conceivably been identified as contiguous by opal_datatype_is_contiguous_memory_layout().

**Comment by markalle** [comment]
I meant to post the gist of the test case over here in the issue reoprt. This program hits the problem when run with the yalla PML at -np 2:
https://gist.github.com/markalle/24f101dfb20b6dfc5ebbe3c8aaa9505a

**Comment by jladd-mlnx** [comment]
@alinask Can you take a look at this, please.

**Comment by jjhursey** [comment]
@alinask @jladd-mlnx Mark posted PR #3567 with a fix if you want to review that.

**Comment by jjhursey** [comment]
@markalle Do you want to keep this issue open until the release branches have the fix merged in?

**Comment by markalle** [comment]
Fixed by https://github.com/open-mpi/ompi/pull/3567

**Comment by yosefe** [comment]
@markalle this patch causes a failure in this test: [MPI_Type_vector_basic_f](https://github.com/open-mpi/ompi-tests/blob/master/intel_tests/src/MPI_Type_vector_basic_f.F)
Looks like the datatype is empty but after the fix , true_ub-true_lb is used for the size.
Shall we revert to using `ompi_datatype_type_size(&size)`?
```
(gdb) p /x *datatype
$3 = {super = {super = {obj_class = 0x7ffff73419d0, obj_reference_count = 0x1}, flags = 0x14, id = 0x0, bdt_used = 0x0, size = 0x0, true_lb = 0x7fffffffffffffff, true_ub = 0x8000000000000000, 
    lb = 0x7fffffffffffffff, ub = 0x8000000000000000, nbElems = 0x0, align = 0x1, name = {0x0 <repeats 64 times>}, desc = {length = 0x1, used = 0x0, desc = 0xbb2bf0}, opt_desc = {length = 0x0, 
      used = 0x0, desc = 0x0}, btypes = {0x0 <repeats 47 times>}}, id = 0x4a, d_f_to_c_index = 0x4a, d_keyhash = 0x0, args = 0xbd4240, packed_description = 0x0, pml_data = 0x0, name = {0x0, 0x70, 0xba, 
    0x0, 0x0, 0x0, 0x0, 0x0, 0x50, 0x72, 0xba, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa0, 0x19, 0xba, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd0, 0x19, 0xba, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20, 0x1a, 0xba, 0x0, 0x0, 0x0, 0x0, 0x0, 
    0xb0, 0x1a, 0xba, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1c, 0xba, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf0, 0xff, 0xbc, 0x0, 0x0, 0x0, 0x0, 0x0}}
```

**Comment by markalle** [comment]
I guess we should switch to opal_datatype_span() then:
```
        ptrdiff_t len, offset; \
        \
        if (opal_datatype_is_contiguous_memory_layout(&(_dtype)->super, _count)) { \
            len = opal_datatype_span((_dtype), (_count), &offset); \
            (_req_base)->data_type          = MXM_REQ_DATA_BUFFER; \
            (_req_base)->data.buffer.ptr    = (char *)_buf + offset; \
            (_req_base)->data.buffer.length = len; \
```

If we just change to use ompi_datatype_type_size() that reintroduces the previous bug that I had fixed.

I feel like MPI is wrong when it reports the true extent as 1 for a type like this
```
    MPI_Type_vector(0, 1, 1, MPI_INT, &newtype);
```
But I have to admit degenerate cases can be confusing and I'd have to re-read the standard to be sure it's wrong.

But either way, my original code change to use true extent was based on a simplification (that should have been correct for any datatype identified as contiguous), but really the opal_datatype_span() function is the fully general function designed to handle all datatypes, contiguous or not, so if we use that we shouldn't have to worry.

**Comment by hppritcha** [comment]
@markalle  @yosefe can this issue be closed now?

**Comment by yosefe** [comment]
yes
