### ISSUE TITLE
concurrent accumulate osc=rdma

### ISSUE THREAD

**Issue by markalle** [open-mpi/ompi#3571]
The following MPI_Accumulate() testcase fails on master using -np 3 and osc=rdma:
https://gist.github.com/markalle/3405203fb2970f94ad515cce23b4f602

I'm running on x86-64 (redhat 6 and/or 7) with mellanox infiniband.

This test has every rank accumulate the buffer [1 1 1 1 1 1 1 1] to every peer over and over in a loop and expects to see [n n n n n n n n] at the end, where n = nloops * (nranks - 1).

The standard says concurrent accumulates are supposed to be allowed.

Is there a build-time option or an info argument I should be using that's maybe turned off by default, or is this just not supported?

**Comment by markalle** [comment]
@hjelmn Is there an MPI-standard argument to say this test shouldn't work, or do you think this is a legit issue?

**Comment by gpaulsen** [comment]
@hjelmn any thoughts?   I know you're busy...

**Comment by hjelmn** [comment]
Sounds like a bug. Will take a look now.

**Comment by hjelmn** [comment]
I see the problem. There is a typo in the exclusive lock code. Who wrote that anyway? :D.....

Pushing a fix now.
