### ISSUE TITLE
64k task limit with persistent dvm

### ISSUE THREAD

**Issue by marksantcroos** [open-mpi/ompi#3583]
The size of `next_jobid` being an `uint16_t` in `orte_plm_globals_t` limits the number of tasks that can be executed towards a persistent DVM to be 64k.

It fails here:
https://github.com/open-mpi/ompi/blob/master/orte/mca/plm/base/plm_base_jobid.c#L87, because it would overflow in constructing the `jdata->jobid` in:
https://github.com/open-mpi/ompi/blob/master/orte/mca/plm/base/plm_base_jobid.c#L95.

Anyone has an intuition for the impact of increasing the storage of these fields?

Are any of these actually dictated by the MPI standard or are these all implementation details?

**Comment by rhc54** [comment]
Nothing to do with any standard. We wanted to keep the proc name to 64-bits to manage memory footprint. With 32-bits required for the rank, that leaves 32-bits for the jobid. Then we have to separate the various mpirun incantations from each other so we can connect/accept across them. So we split the jobid in half, with 16-bits for the mpirun ID and 16-bits for the job ID within each mpirun.

Now the DVM doesn't have this connect/accept issue, and so we could use the entire 64-bits for the "local jobid", as it is called. Might take a little work in a few places (e.g., the OOB) where we actually split out the two fields, but shouldn't be all that bad.

**Comment by marksantcroos** [comment]
Thanks Ralph, that doesn't sound too bad. I'll take a crack at it.

**Comment by rhc54** [comment]
Most of what you'll need to do is in orte/util/name_fns.[c,h], adjusting the macros there for obtaining and modifying the job fields (e.g., ORTE_JOB_FAMILY). You'll also need to modify the session directory naming (orte/util/session_dir.c,h), to replace the job family with some other unique identifier for the dvm since users might have multiple dvm's in operation at the same time.

I guess if you can come up with a scheme for generating a unique dvm id, you could just replace the job family in those two code areas with it when we are in a dvm, and that might be pretty close to the entire change.

**Comment by rhc54** [comment]
I had a thought here: the job family is a global value unique to each mpirun (or orte-dvm - i'll use the two interchangeably here). We need it for two purposes:

- to create unique session directory names
- to identify when we are working across mpirun invocations, typically when supporting connect/accept operations that span two independent jobs

In both cases, there really is no need for us to package the job family inside the orte_process_name_t's jobid. This unnecessarily constrains the number of mpiruns that can co-exist in a cluster that shares nodes, and the number of simultaneous jobs one could have in a DVM.

So what if we simply store the job family as a new orte_job_family global, and make all 32-bits of the orte_jobid_t be the "local jobid"? We would have to modify the session directory code (orte/util/session_dir.c) to use orte_job_family, but that's a trivial change.

Probably the biggest change would be to the OOB. I'm thinking we could best handle that by modifying the oob header to include the job family as a separate field, and we'd have to probably modify the oob send/recv interfaces to somehow pass an identifier that allowed us to specify a target in another job family. Given that this is the unusual case, perhaps some kind of "attribute" list might be appropriate and would also give us added flexibility for future changes?

@marksantcroos @bosilca @abouteiller What do you guys think?

**Comment by rhc54** [comment]
Fixed in master and v5.0 - no plans to backport
