### ISSUE TITLE
Mysterious 32 bit MTT build failures on Absort

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#3610]
We're seeing odd MPI Install failures on 32 bit Absoft failures, but the log messages are not showing what the actual error is.

@cagoelz Can you shed any light, perchance, on what is failing in these builds?

https://mtt.open-mpi.org/index.php?do_redir=2446

**Comment by cagoelz** [comment]
The failures occur building ompi_datatype_external.lo:

  CC       ompi_datatype_external.lo
In file included from ompi_datatype_external.c:29:
../../ompi/communicator/communicator.h:265: error: size of array ‘padding’ is too large
make: *** [ompi_datatype_external.lo] Error 1

The code around ../../ompi/communicator/communicator.h:265 is

#define PREDEFINED_COMMUNICATOR_PAD (sizeof(void*) * 64)

struct ompi_predefined_communicator_t {
    struct ompi_communicator_t comm;
    char padding[PREDEFINED_COMMUNICATOR_PAD - sizeof(ompi_communicator_t)];
};

The size of ompi_communicator_t is larger than 256 bytes?

**Comment by bosilca** [comment]
git blame 50aa143ab67. On 32 bits architectures, as the void* size is 32 bits, the opal_hash_table_t becomes too large for the PREDEFINED_COMMUNICATOR_PAD. We might have an issue with our ABI ...

**Comment by jsquyres** [comment]
Ah!  Good point.

I guess we intended to allow 64 *pointers* worth of padding.  But in hindsight, that's a poor measure.  Should we just listed a number of bytes, instead?  (e.g., 64*8=512)

Sidenote: I'm not worried about our ABI between 32 and 64 bit builds.

**Comment by bosilca** [comment]
I was not worried about ABI 32 vs. 64 bit builds (it has no sense), but we will now have to increase the size of the PREDEFINED_COMMUNICATOR_PAD, which will translate into a ABI breakage.

**Comment by jsquyres** [comment]
Yes, we will break ABI for 32 bit builds.  But if we get this into 3.0 (and beyond), I'm not worried about it.

Do you agree?

**Comment by jsquyres** [comment]
@cagoelz I didn't say it earlier: thanks for the detailed compilation output!  😄
