### ISSUE TITLE
 fatal error: shmem.h when trying to compile mpicc

### ISSUE THREAD

**Issue by danindiana** [open-mpi/ompi#3629]
Thank you for taking the time to submit an issue!

## Background information
Working with the examples found in the openmpi-2.1.1/examples directory. 

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
Version 2.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

tarball from www.open-mpi.org

### Please describe the system on which you are running
speed@speed-desktop:~/Downloads/openmpi-2.1.1/examples$ screenfetch
                          ./+o+-       speed@speed-desktop
                  yyyyy- -yyyyyy+      OS: ubuntu Ubuntu 14.04 trusty
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 3.13.0-119-generic
           .++ .:/++++++/-.+sss/`      Uptime: 13h 51m
         .:++o:  /++++++++/:--:/-      Packages: 4118
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 4.3.11
       .:+o:+o/.          `+sssoo+/    Resolution: 1920x1080
  .++/+:+oo+o:`             /sssooo.   DE: Gnome 3.9.90
 /+++//+:`oo+o               /::--:.   WM: GNOME Shell
 \+/+o+++`o++o               ++////.   WM Theme: Adwaita
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Radiance [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: elementary-xfce-darker
        \+.++o+o``-````.:ohdhhhhh+     Font: Cantarell 11
         `:o+++ `ohhhhhhhhyo++os:      CPU: AMD FX-8350 Eight-Core @ 4GHz
           .o:`.syhhhhhhh/.oo++o`      GPU: GeForce GTX 750 Ti
               /osyyyyyyo++ooo+++/     RAM: 5560MiB / 24011MiB
                   ````` +oo+++o\:    
                          `oo++.      

## Details of the problem

When trying to compile some of the examples in the examples folder I get an error: 

For example: 

 shell$ mpicc oshmem_strided_puts.c -o oshmem_strided_puts
oshmem_strided_puts.c:28:19: fatal error: shmem.h: No such file or directory
 #include <shmem.h>
                   ^
compilation terminated.

or

shell$ mpif90 hello_usempi.f90 -o hello_usempi
hello_usempi.f90:14.8:

    use mpi
        1
Fatal Error: Cannot read module file 'mpi.mod' opened at (1), because it was created by a different version of GNU Fortran


I have included the make check output in text file if that helps. 

[makecheck.txt](https://github.com/open-mpi/ompi/files/1043902/makecheck.txt)

**Comment by ggouaillardet** [comment]
@danindiana in order to compile an OpenSHMEM program you should use ```oshcc``` instead of ```mpicc```

the fortran error is more puzzling.
could you please double check you are using the ```mpif90``` you just built and installed ?
also, if you built Open MPI some time ago, please make sure you are now using the same GNU Fortran version that the one you used when building Open MPI.

**Comment by gpaulsen** [comment]
Closing as above comment should have resolved.
