### ISSUE TITLE
About HCOLL Bcast in OMPI

### ISSUE THREAD

**Issue by mathbird** [open-mpi/ompi#3681]
Hi, 

Attached is a simple BCAST test  with a derived type with MPI_UB.  Using HCOLL, it gave us the following error message, although the test passed correctly. 

_Failed to query dtype contents_

in coll/hcoll/coll_hcoll_ops.c, changing the following line in the function mca_coll_hcoll_bcast lets the msg gone. 

    //dtype = ompi_dtype_2_hcoll_dtype(datatype, TRY_FIND_DERIVED);
    dtype = ompi_dtype_2_hcoll_dtype(datatype, **NO_DERIVED**);

Do you think it is the right change? Or you have better suggestion? Or HCOLL guys need to update their codes how to handle error checking?

[bc2.zip](https://github.com/open-mpi/ompi/files/1062287/bc2.zip)

**Comment by jladd-mlnx** [comment]
Hi,

Which version of OMPI are you using? We are looking at it.

Josh

**Comment by mathbird** [comment]
I am using master branch, so I believe 2.x also has the same issue.

**Comment by jladd-mlnx** [comment]
MPI_LB and MPI_UB are deprecated, and should not be used anymore. I think that's why you're seeing the message. We don't support this datatype in HCOLL. 

```
$mpicc bc2.c
bc2.c: In function ‘main’:
bc2.c:39:4: warning: ‘ompi_mpi_ub’ is deprecated (declared at /hpc/local/benchmarks/hpcx_install_Friday/hpcx-gcc-redhat7.2/ompi-v2.x/include/mpi.h:928): MPI_UB is deprecated in MPI-2.0 [-Wdeprecated-declarations]
    datatypes_array[1] = MPI_UB;
```

**Comment by jladd-mlnx** [comment]
In this case, HCOLL is unable to create an internal HCOLL datatype from the MPI datatype, and so it falls back to the Tuned Bcast. This is not a bug, and the HCOLL error is correct.  

When passing `NO_DERIVED` as the second argument to `ompi_dtype_2_hcoll_dtype`, you do not attempt to create an HCOLL datatype and end up returning `DTE_ZERO` as the HCOLL datatype from `ompi_dtype_2_hcoll_dtype` and this also results in falling back to tuned. This is absolutely NOT what you want to pass as the second argument to `ompi_dtype_2_hcoll_dtype` as this completwly bypasses the HCOLL datatype creation process. 

In both cases (`TRY_FIND_DERIVED`,`NO_DERIVED`) , `DTE_ZERO` is returned from the call to `ompi_dtype_2_hcoll_dtype` and Tuned Bcast is being invoked to handle the collective operation. There is no bug in the HCOLL library or in the coll/hcoll integration layer in OMPI.

**Comment by jjhursey** [comment]
Yeah it's not a bug in hcoll. As Dahai mentioned the test passes fine. It's just an annoying error message that cannot be suppressed (as far as I know).

**Comment by jladd-mlnx** [comment]
It cannot be suppressed. We will take a look and determine if we want to reduce the verbosity of the HCOLL datatype code in this instance for the HCOLL v3.8 release.

**Comment by mathbird** [comment]
why some other collective functions choose NO_DERIVED ?

**Comment by jladd-mlnx** [comment]
Because some HCOLL algorithms can support hardware assisted scatter gather types of operations and we need the HCOLL datatype map (e.g. Bcast) and others (most) have not been designed to do so. When we do add support for hardware scatter gather capabilities to an algorithm, then we will change OMPI entry point to `TRY_FIND_DERIVED`.
