### ISSUE TITLE
Double free or corruption with Open MPI and gfortran

### ISSUE THREAD

**Issue by winash12** [open-mpi/ompi#3698]
Thank you for taking the time to submit an issue!

## Background information

I am running a computational fluid dynamics software 

This is the output of lscpu

CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1 

and I am running OpenMPI's mpirun in the following way

mpirun -np 4 cfd 

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

I have used 2.1.1 and 1.10.1 and 2.0.0 and in all these three versions the same problem is reproduced 

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From source distribution tarball

### Please describe the system on which you are running

* Operating system/version: 
* Computer hardware: 
* Network type: 
Output of mpif90 and I got the problem with gfortran 5.4 as well
GNU Fortran (Ubuntu 4.8.5-4ubuntu2) 4.8.5

Output of uname -r 

4.4.0-79-generic

Output of cat /etc/issue

Ubuntu 16.04.2 LTS \n \l

Output of cat /etc/*release 

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

-----------------------------

## Details of the problem

I am getting this error when I run my weather simulation software - 

*** glibc detected *** ./a.out: double free or corruption (!prev): 0x00007fc6d0000c80 ***
04	======= Backtrace: =========
05	/lib64/libc.so.6[0x3411e75e66]
06/lib64/libc.so.6[0x3411e789b3]

From this link it appears that this is the cause of the problem - https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/564266

"From their examination our Development team concluded the underlying problem with openmpi 1.8.6 resulted from mixing out-of-date/incompatible Fortran RTLs. In short, there were older static Fortran RTL bodies incorporated in the openmpi library that when mixed with newer Fortran RTL led to the failure. They found the issue is resolved in the newer openmpi-1.10.1rc2 and recommend resolving requires using a newer openmpi release with our 15.0 (or newer) release." 

Could this be possible with my version as well ?

**Comment by winash12** [comment]
As suggested by experts here I checked to see if LD_LIBRARY_PATH and PATH had any issues I only have one current installation of OpenMPI in /usr/local/lib.

I also ran the example hello_oshmemfh from the examples directory and this is the output of that program for OpenMPI 1.10.1 
 mca: base: component_find: unable to open /usr/local/lib/openmpi/mca_ess_pmi: /usr/local/lib/openmpi/mca_ess_pmi.so: undefined symbol: opal_pmix_base_framework (ignored)
[aswin-Vostro-3800:09479] mca: base: component_find: oob "mca_oob_usock" uses an MCA interface that is not recognized (component MCA v2.1.0 != supported MCA v2.0.0) -- ignored
[aswin-Vostro-3800:09479] mca: base: component_find: grpcomm "mca_grpcomm_direct" uses an MCA interface that is not recognized (component MCA v2.1.0 != supported MCA v2.0.0) -- ignored
[aswin-Vostro-3800:09479] mca: base: component_find: unable to open /usr/local/lib/openmpi/mca_rcache_grdma: /usr/local/lib/openmpi/mca_rcache_grdma.so: undefined symbol: mca_rcache_base_registration_t_class (ignored)
[aswin-Vostro-3800:09479] mca: base: component_find: unable to open /usr/local/lib/openmpi/mca_mpool_hugepage: /usr/local/lib/openmpi/mca_mpool_hugepage.so: undefined symbol: opal_mpool_base_framework (ignored)
[aswin-Vostro-3800:09479] mca: base: component_find: coll "mca_coll_sync" uses an MCA interface that is not recognized (component MCA v2.1.0 != supported MCA v2.0.0) -- ignored
[aswin-Vostro-3800:09479] mca: base: component_find: unable to open /usr/local/lib/openmpi/mca_osc_rdma: /usr/local/lib/openmpi/mca_osc_rdma.so: undefined symbol: opal_recursive_mutex_t_class (ignored)

Hello, world, I am  0 of  1

**Comment by ggouaillardet** [comment]
@winash12 if you ```make install``` over a previous install, __some__ files will be overwritten, but __not__ all of them.
so i suggest you manually cleanup ```/usr/local/lib``` and then ```make install``` again.

an other option is to
```
./configure --enable-mpirun-prefix-by-default --prefix=/opt/openmpi-2.1.1
make install
```
assuming your ```LD_LIBRARY_PATH``` does not explicitly refers ```/usr/local/lib```, you should be just fine with
```
export PATH=/opt/openmpi-2.1.1/bin:$PATH
```

as i wrote earlier in the ML, i do invite you to try a MPICH-based library and see if the issue goes away.
the error message is way too generic, and at this stage, there is no way to figure out which of Open MPI or your application is to be blamed

**Comment by winash12** [comment]
@ggouaillardet - All your suggestions are appreciated. Please give me couple of days to get back to you and this forum after testing the ideas you have provided in ML and here. Thank you again for your time and your suggesions.

**Comment by ofloveandhate** [comment]
@winash12 resolution?

**Comment by winash12** [comment]
@ofloveandhate resolved several months ago

**Comment by jsquyres** [comment]
Thanks!  I'll close.

**Comment by ofloveandhate** [comment]
i had asked because a user i was supporting was getting a similar error to one previous in this thread:
```
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_shmem_base_select failed
  --> Returned value -1 instead of OPAL_SUCCESS
```
and we were looking for the solution.  turned out to be stale links from homebrew, and forcing the re-link using
```
 brew link --overwrite open-mpi
```
solved our problem.  thanks.
