### ISSUE TITLE
Bug in portals4 MTL?

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#373]
@regrant @tkordenbrock 

I'm confused by https://github.com/open-mpi/ompi/blob/master/ompi/mca/mtl/portals4/mtl_portals4_component.c#L59-L60 -- shouldn't those 2 pointers be flipped?

**Comment by hppritcha** [comment]
My bad.  I'll fix.  Must have missed the compile warning.

**Comment by tkordenbrock** [comment]
Thanks Howard, but I'll take care of it.  I need to run these changes
through MTT.


todd

**Comment by tkordenbrock** [comment]
Closed by b8b07d2
<https://github.com/open-mpi/ompi/commit/b8b07d2d62eeb28b68bed8250190042f88929757>
.
