### ISSUE TITLE
Cannot run job on the login node after RHEL security update

### ISSUE THREAD

**Issue by robertsawko** [open-mpi/ompi#3740]
After a recent security update we seem to have lost the ability to run on the login node for on a local P8 cluster. The job crashed with the following error:
```
mpirun -np 1 ./a.out 
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node hcplogin2 exited on signal 13 (Broken pipe).
--------------------------------------------------------------------------
```
The same binary works fine when I transfer my OMPI compilation and the binary to the compute cluster. The job is submitted with LSF. I've already tried compiling a few different versions: 2.0.2 and 2.1.1 all from source with the following config line:
```
../configure \
    --prefix=/gpfs/panther/local/apps/ibm/openmpi/2.1.1 \
    --enable-mpi-thread-multiple --enable-shared --disable-static \
    --enable-mpi-fortran=usempi --disable-libompitrace \
    --enable-wrapper-rpath \
    --with-lsf=/shared/lsf913/9.1 \
    --with-lsf-libdir=/shared/lsf913/9.1/linux3.10-glibc2.17-ppc64le/lib/ \
    --with-knem=/opt/knem-1.1.2.90mlnx1 \
    --with-mxm=/opt/mellanox/mxm \
    --with-fca=/opt/mellanox/fca \
    --with-cuda=/gpfs/panther/local/apps/cuda/8.0
```

The main difference is that the compute cluster has different networking e.g. infiniband, but other than that OMPI was actually compiled on the login node and it all used to work on both machines prior to a recent RHEL security update.

```
cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)
```
Also this is a ppc64le machine in case that makes any difference. Please let me know if you have any ideas on what may be causing it. Happy to provide more debug information.

**Comment by rhc54** [comment]
Usually the distros turn firewalls “on” by default after a security update - I’d check to see if that happened

**Comment by jjhursey** [comment]
@robertsawko Did you resolve your cluster issue? We have been running LSF on P8 systems for a while now, and it's working fine. I would check that all of the nodes are running the same version of Open MPI. The broken pipe message might mean that two different installed versions of Open MPI are trying to talk to one another.
