### ISSUE TITLE
Missing Remote Progress MPI_Win_flush_local

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#3750]
## Background information
We employ the following pattern for signaling completion between processes:

```c
int com_rank, root = 0;
// allocate MPI window
MPI_Win win = allocate_win();
// do some computation
...
// Process 0 waits for a signal
if (com_rank == root) {
  do {
    MPI_Fetch_and_op(NULL, &res,
      MPI_INT, com_rank, 0, MPI_NO_OP, win);
    MPI_Win_flush_local(com_rank, win);
  } while (res == 0);
} else {
  MPI_Accumulate(
    &val, &res, 1, MPI_INT, root, 0, MPI_SUM, win);
  MPI_Win_flush(root, win);
}
[...]
```

We use `MPI_Fetch_and_op` to atomically query the local memory location for a signal and `MPI_Accumulate` to send the signal (I have omitted the reset and other details for simplicity).

If running on a single node (my laptop), this code snippet reproducibly hangs, with the root process indefinitely repeating the do-while-loop and all other processes being stuck in `MPI_Win_flush`.

*Interesting observations*:
- If I replace the `MPI_Win_flush_local` with `MPI_Win_flush` the application does not hang. However, my understanding is that a local flush should be sufficient for `MPI_Fetch_and_op` with `MPI_NO_OP` as remote completion is not required.
- The hang only occurs on dynamic windows with memory from shared memory windows attached. 
- I do not observe the hang with MPICH 3.2. 
- I can only reproduce this on my laptop but not on our Linux Cluster with Infiniband network.

My expectation is that `MPI_Win_flush_local` provides progress but I am aware that the progress are rather vague, so I might be wrong there. Please correct me if that is the case.

I am attaching a small reproducer ([ompi_passive_target_hang_root_fetchop_minimal.c.zip](https://github.com/open-mpi/ompi/files/1099590/ompi_passive_target_hang_root_fetchop_minimal.c.zip)), which can be compiled as follows:

- With dynamic window:
```
mpicc -DUSE_DYNAMIC_WIN=1 ompi_passive_target_hang_root_fetchop_minimal.c
```
- With regular window:
```
mpicc -DUSE_DYNAMIC_WIN=0 ompi_passive_target_hang_root_fetchop_minimal.c
```

Please let me know if you need any additional information.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
Open MPI 2.1.1 release tarball.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Compiled from the release tarball without additional configure flags.

### Please describe the system on which you are running

* Operating system/version: GNU/Linux Mint 18.1, kernel 4.8.0-51-generic
* Computer hardware: Laptop (Thinkpad T460s)
* Network type:

**Comment by jsquyres** [comment]
Originally posted in https://www.mail-archive.com/users@lists.open-mpi.org/msg31260.html; @hjelmn asked the user to open a Github issue so that we can track it.

**Comment by hjelmn** [comment]
Please check #3770. It should fix the issue.

**Comment by devreal** [comment]
Thanks for the quick fix. I checked it and can confirm that I do not see hangs on my local system anymore when using `MPI_Win_flush_local`.
