### ISSUE TITLE
undefined reference to `opal_hwloc191*` while linking to caffe .

### ISSUE THREAD

**Issue by GerrieWell** [open-mpi/ompi#3763]
## Background information
I tried to compile this lib ,[Cysu/caffe](https://github.com/Cysu/caffe) .Since they didn't open issues, I have to summit my issue in this page ,it's troubled me for days.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

v1.10 & v1.8

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

```
./configure --with-cuda --prefix=/home/wuyong/libs/openmpi/
make 
make install
```

### Please describe the system on which you are running

* Operating system/version: ubuntu16.04
* Computer hardware: gtx1080
* Network type: none

-----------------------------

## Details of the problem

I got compile error like this . I've tried openmpi 1.8 and 1.10.

```
wuyong@xy-desktop:~/xy_share/reidPrj/person_search/caffe/build$ make
[  1%] Built target proto
[ 81%] Built target caffe
[ 82%] Built target finetune_net
[ 82%] Linking CXX executable caffe
/home/wuyong/libs/openmpi/lib/libopen-rte.so.12: undefined reference to `opal_hwloc191_hwloc_bitmap_list_sscanf'
/home/wuyong/libs/openmpi/lib/libopen-rte.so.12: undefined reference to `opal_hwloc191_hwloc_get_cpubind'
/home/wuyong/libs/openmpi/lib/libopen-rte.so.12: undefined reference to `opal_hwloc191_hwloc_bitmap_free'
/home/wuyong/libs/openmpi/lib/libopen-rte.so.12: undefined reference to `opal_hwloc191_hwloc_bitmap_compare'
/home/wuyong/libs/openmpi/lib/libopen-rte.so.12: undefined reference to `opal_hwloc191_hwloc_topology_get_support'
/home/wuyong/libs/openmpi/lib/libopen-rte.so.12: undefined reference to `opal_hwloc191_hwloc_bitmap_and'
/home/wuyong/libs/openmpi/lib/libopen-rte.so.12: undefined reference to `opal_hwloc191_hwloc_topology_destroy'
/home/wuyong/libs/openmpi/lib/libopen-rte.so.12: undefined reference to `opal_hwloc191_hwloc_bitmap_copy'
```

**my ccmake config like this  : **

```
MPI_CXX_COMPILER                 /home/wuyong/libs/openmpi/bin/mpicxx
 MPI_CXX_COMPILE_FLAGS
 MPI_CXX_INCLUDE_PATH             /home/wuyong/libs/openmpi/include
 MPI_CXX_LIBRARIES                /home/wuyong/libs/openmpi/lib/libmpi_cxx.so;/home/wuyong/libs/openmpi/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libOpenCL.so.
 MPI_CXX_LINK_FLAGS                -Wl,-rpath  -Wl,/home/wuyong/libs/openmpi/lib  -Wl,--enable-new-dtags
 MPI_C_COMPILER                   /home/wuyong/libs/openmpi/bin/mpicc
 MPI_C_COMPILE_FLAGS
 MPI_C_INCLUDE_PATH               /home/wuyong/libs/openmpi/include
 MPI_C_LIBRARIES                  /home/wuyong/libs/openmpi/lib/
 MPI_C_LINK_FLAGS                  -Wl,-rpath  -Wl,/home/wuyong/libs/openmpi/lib/  -Wl,--enable-new-dtags
 MPI_EXTRA_LIBRARY                /home/wuyong/libs/openmpi/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libOpenCL.so.1
```

> MPI_CXX_LIBRARIES                /home/wuyong/libs/openmpi/lib/libmpi_cxx.so;/home/wuyong/libs/openmpi/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libOpenCL.so.

Note this line this line. `/usr/lib/x86_64-linux-gnu/libOpenCL.so` is added by me for troubleshoot the problem .Refer to [编译错误求指导 · Issue #146 · yjxiong/caffe](https://github.com/yjxiong/caffe/issues/146)
and I have two version in my system and `LD_LIBRARY_PATH` .

```
wuyong@xy-desktop:~/xy_share/reidPrj/person_search/caffe/build$ find /usr/ -name libOpenCL*
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1.0.0
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1.0
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so
/usr/lib/x86_64-linux-gnu/libOpenCL.so.1.0.0
/usr/lib/x86_64-linux-gnu/libOpenCL.so.1
/usr/lib/x86_64-linux-gnu/libOpenCL.so
```

When I use openmpi 1.8 , it compiled successfully with warnings ,but  can't run caffe because openCL link error. When I use openmpi1.10, it's unable to compile . I assume there're some troubles with openCL , see the `ccmake .. ` output warning  .

```

 CMake Warning at src/caffe/CMakeLists.txt:20 (add_library):
   Cannot generate a safe runtime search path for target caffe because files
   in some directories may conflict with libraries in implicit directories:

     runtime library [libOpenCL.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/cuda-8.0/lib64
       /usr/local/cuda-8.0/targets/x86_64-linux/lib

   Some of these libraries may not be found correctly.
```

ps : `/usr/local/cuda-8.0/targets/x86_64-linux/lib` is soft linked to `/usr/local/cuda-8.0/lib64`

Can u help me ??

**Comment by ggouaillardet** [comment]
can you please run
```ldd /home/wuyong/libs/openmpi/lib/libopen-rte.so.12```
/* it should resolve ```libopen-pal.so.*``` in the same directory */
and then
```nm /home/wuyong/libs/openmpi/lib/libopen-pal.so.* | grep hwloc```

**Comment by GerrieWell** [comment]
@ggouaillardet 
it actually resolve open-pal in same dir.

```shell
wuyong@xy-desktop:~/xy_share/reidPrj/person_search/caffe/build$ ldd /home/wuyong/libs/openmpi/lib/libopen-rte.so.12
	linux-vdso.so.1 =>  (0x00007fff1e5ad000)
	libopen-pal.so.13 => /home/wuyong/libs/openmpi/lib/libopen-pal.so.13 (0x00007f27b80a3000)
```

And the outputs of` nm /home/wuyong/libs/openmpi/lib/libopen-pal.so.* | grep hwloc` contain opal_hwloc191_hwloc_bitmap_list_sscanf.

```
wuyong@xy-desktop:~/xy_share/reidPrj/person_search/caffe/build$ nm /home/wuyong/libs/openmpi/lib/libopen-pal.so.13 | grep opal_hwloc191_hwloc_bitmap_free
00000000000798e0 T opal_hwloc191_hwloc_bitmap_free
```
my system env variables are set like this : 

```shell
wuyong@xy-desktop:~/xy_share/reidPrj/person_search/caffe/build$ echo $LD_LIBRARY_PATH
/usr/lib/x86_64-linux-gnu/:/home/wuyong/libs/openmpi/lib/:/usr/local/lib/
wuyong@xy-desktop:~/xy_share/reidPrj/person_search/caffe/build$ echo $PATH
/home/wuyong/libs/openmpi/bin/:/home/wuyong/bin:/home/wuyong/.local/bin:/home/wuyong/anaconda3/bin:/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wuyong/bin
```

**Comment by jsquyres** [comment]
A few things:

1. If you're just starting with Open MPI, you should likely be using the latest version of Open MPI, if possible.  That's currently version 2.1.1.  1.10 and 1.8 are pretty old release series.
1. Before trying to get your caffe program running, start with something simple.  Are you able to build / run trivial MPI programs, such as https://github.com/open-mpi/ompi/blob/master/examples/hello_c.c and https://github.com/open-mpi/ompi/blob/master/examples/ring_c.c?  These should be in the `examples` directory of your Open MPI tarball (if you're using v1.8 or v1.10, you might want to use the examples from their respective tarballs -- the URLs I provided above use MPI APIs that may or may not have been in the v1.8 / v1.10 releases).

**Comment by GerrieWell** [comment]
@jsquyres

**Comment by GerrieWell** [comment]
@jsquyres 

```
wuyong@xy-desktop:~/xy_share/SDKs/openmpi-1.10.7/examples$ ./hello_c
Hello, world, I am 0 of 1, (Open MPI v1.10.7, package: Open MPI wuyong@xy-desktop Distribution, ident: 1.10.7, repo rev: v1.10.6-48-g5e373bf, May 16, 2017, 127)
wuyong@xy-desktop:~/xy_share/SDKs/openmpi-1.10.7/examples$ ./ring_c
Process 0 sending 10 to 0, tag 201 (1 processes in ring)
Process 0 sent to 0
Process 0 decremented value: 9
Process 0 decremented value: 8
Process 0 decremented value: 7
Process 0 decremented value: 6
Process 0 decremented value: 5
Process 0 decremented value: 4
Process 0 decremented value: 3
Process 0 decremented value: 2
Process 0 decremented value: 1
Process 0 decremented value: 0
Process 0 exiting
```

Examples work fine. I skim the example makefile, it didn't use `libopen-rte.so.12`. Maybe I should try some examples linking with `libopen-rte` ? Anyway, thanks your help. I'm gonna sleep.

**Comment by jsquyres** [comment]
No MPI apps should need to link to `libopen-rte` directly.  

What is the exact command that `[ 82%] Linking CXX executable caffe` is executing that causes the error?

**Comment by jsquyres** [comment]
@GerrieWell Ping

**Comment by jsquyres** [comment]
Closing this after nearly 2 months of inactivity.  Please feel free to re-open if you can supply more information; thanks.
