### ISSUE TITLE
Path to $TMPDIR too long (error in file oob_usockcomponent.c)

### ISSUE THREAD

**Issue by arosen93** [open-mpi/ompi#3798]
I am using OpenMPI 2.1.1 on a compute cluster with Torque/PBS. My system administrator installed it from a tarball. Whenever I submit a job that requires OpenMPI, I get the following error:

```
[qnode4047:29020] [[2752,0],1] bind() failed on error Address already in use (98)
[qnode4047:29020] [[2752,0],1] ORTE_ERROR_LOG: Error in file oob_usock_component.c at line 247
[qnode4047:29035] [[2752,1],6] usock_peer_recv_connect_ack: received unexpected process identifier [[2752,0],0] from [[2752,0],1]
[qnode4047:29015] [[2752,0],0]-[[2752,1],6] mca_oob_usock_peer_recv_handler: invalid socket state(1)
... (many more of the same error as above)
[qnode4047:29023] [[2752,1],0] usock_peer_recv_connect_ack: received unexpected process identifier [[2752,0],0] from [[2752,0],1]
```

I have traced this back to the $TMPDIR path being too long for this version of OpenMPI. When I change the $TMPDIR path manually to something short (or try submitting a job on another cluster that uses a different default and shorter $TMPDIR path), it runs without an issue. Unfortunately, I should not be changing the $TMPDIR path otherwise there will be I/O on a network drive instead of a local drive (where the default $TMPDIR path is set). I have not had this issue on the 1.x version of OpenMPI.

**Comment by rhc54** [comment]
Simplest solution:
```
$ ln -s $TMPDIR mytmpdir
$ export OMPI_MCA_orte_tmpdir_base=mytmpdir
```

**Comment by arosen93** [comment]
That may work for some, but I do not have permission to copy necessary files to the resulting directory. So, the issue remains even if there is a workaround solution that works for some. If you have too long a path name, it doesn't work, so I don't know if the issue should be closed.

**Comment by jsquyres** [comment]
@rhc54 Given that this comes up again and again, perhaps we should put a show_help message in with this specific workaround...?

**Comment by rhc54** [comment]
Not sure what you mean by "again and again", but it does crop up on rare occasions. You are welcome to add a show_help message if you think it necessary.
