### ISSUE TITLE
rework mca_btl_tcp_proc_accept code

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#38]
In the multicluster case, we've seen hanging connections, that's why I changed the acceptance rules in btl_tcp_proc.c (r18169). This change caused weird connection resets on sif and odin, unfortunately not reproducable somewhere else (for me).

JFTR, the discussion: http://www.open-mpi.org/community/lists/devel/2008/04/3711.php

I've reverted the commit in r18255 and took a look at the code. Let me come up with a two-line-fix in a few hours. I'll add tprins to this ticket for documentation purpose. The checkin will also refer to this ticket.

**Comment by jsquyres** [comment]
@bosilca I can't imagine this is still relevant any more; I'm going to close it.
