### ISSUE TITLE
Ensure v3.x commits are cherry picked to v3.0.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#3810]
Per https://github.com/open-mpi/ompi/pull/3806#issuecomment-313113763, it looks like there were at least a few PRs that were merged to the v3.x branch even after it was defunct (first email I see about creating a nightly v3.0.x tarball was on May 30).

Probably need to audit the logs on the v3.x branch and ensure that all PRs that were applied there got applied to the v3.0.x branch.

Assigning this to the v3.0.0 RMs simply because I don't know who else to assign it to...

**Comment by hppritcha** [comment]
#3677 looks suspect.
#3568 looks suspect.q

Note I don't have write permissions on v3.x branch now so can't merge.

**Comment by karasevb** [comment]
There is #3677 was already added to v3.0.x branch as a part of PR #3723

**Comment by bwbarrett** [comment]
Closing this issue; we completed the audit and haven't missed any patches.
