### ISSUE TITLE
Bug in cache line size detection for power architecture

### ISSUE THREAD

**Issue by nysal** [open-mpi/ompi#383]
This issue was first reported here - http://www.open-mpi.org/community/lists/devel/2015/02/16902.php

Due to the nature of the cache architecture on power, we don't export a coherency_line_size for L2 in sysfs. 
```shell
jnysal@c656f6n03:~$ ls -al /sys/devices/system/cpu/cpu0/cache/index2/
total 0
drwxr-xr-x 2 root root     0 Feb  9 08:55 .
drwxr-xr-x 6 root root     0 Feb  9 08:55 ..
-r--r--r-- 1 root root 65536 Feb  9 08:55 level
-r--r--r-- 1 root root 65536 Feb  9 08:55 number_of_sets
-r--r--r-- 1 root root 65536 Feb  9 08:55 shared_cpu_map
-r--r--r-- 1 root root 65536 Feb  9 08:55 size
-r--r--r-- 1 root root 65536 Feb  9 08:55 type
jnysal@c656f6n03:~$ ls -al /sys/devices/system/cpu/cpu0/cache/index1/
total 0
drwxr-xr-x 2 root root     0 Feb  9 08:55 .
drwxr-xr-x 6 root root     0 Feb  9 08:55 ..
-r--r--r-- 1 root root 65536 Feb  9 08:55 coherency_line_size
-r--r--r-- 1 root root 65536 Feb  9 08:55 level
-r--r--r-- 1 root root 65536 Feb  9 08:55 number_of_sets
-r--r--r-- 1 root root 65536 Feb  9 08:55 shared_cpu_map
-r--r--r-- 1 root root 65536 Feb  9 08:55 size
-r--r--r-- 1 root root 65536 Feb  9 08:55 type
-r--r--r-- 1 root root 65536 Feb  9 08:55 ways_of_associativity

jnysal@c656f6n03:~$ cat /sys/devices/system/cpu/cpu0/cache/index2/level 
2
jnysal@c656f6n03:~$ cat /sys/devices/system/cpu/cpu0/cache/index1/level 
1
jnysal@c656f6n03:~$ cat /sys/devices/system/cpu/cpu0/cache/index1/coherency_line_size 
128
```
So in opal/mca/hwloc/base/hwloc_base_util.c: fill_cache_line_size()
ompi ends up with a cache line size of zero. This causes the free list initialization failure reported by Paul. I can think of two ways to solve this:
1. If we are unable to get the L2 cache line size, try L1
2. If we are unable to get the L2 cache line size, use the default value (I think ompi default is 128, which works for us)

On a slightly unrelated note, ompi seems to iterate through all the L2 hwloc objects(eg. For a 2 socket Power 8 system thats about 24 objects), which seems to be by design. That might be seen as sub-optimal on larger SMP systems. 

A tentative patch based on approach 1 mentioned above:
```diff
diff --git a/ompi/mca/coll/libnbc/coll_libnbc_component.c b/ompi/mca/coll/libnbc/coll_libnbc_component.c
index 1a2a81a..2d7b82c 100644
--- a/ompi/mca/coll/libnbc/coll_libnbc_component.c
+++ b/ompi/mca/coll/libnbc/coll_libnbc_component.c
@@ -88,6 +88,7 @@ libnbc_open(void)
     int ret;
 
     OBJ_CONSTRUCT(&mca_coll_libnbc_component.requests, ompi_free_list_t);
+    OBJ_CONSTRUCT(&mca_coll_libnbc_component.active_requests, opal_list_t);
     ret = ompi_free_list_init(&mca_coll_libnbc_component.requests,
                               sizeof(ompi_coll_libnbc_request_t),
                               OBJ_CLASS(ompi_coll_libnbc_request_t),
@@ -97,7 +98,6 @@ libnbc_open(void)
                               NULL);
     if (OMPI_SUCCESS != ret) return ret;
 
-    OBJ_CONSTRUCT(&mca_coll_libnbc_component.active_requests, opal_list_t);
     /* note: active comms is the number of communicators who have had
        a non-blocking collective started */
     mca_coll_libnbc_component.active_comms = 0;
diff --git a/opal/mca/hwloc/base/hwloc_base_util.c b/opal/mca/hwloc/base/hwloc_base_util.c
index e209ee0..9f9eefa 100644
--- a/opal/mca/hwloc/base/hwloc_base_util.c
+++ b/opal/mca/hwloc/base/hwloc_base_util.c
@@ -175,27 +175,33 @@ int opal_hwloc_base_filter_cpus(hwloc_topology_t topo)
 
 static void fill_cache_line_size(void)
 {
-    int i = 0;
+    int i = 0, cache_level = 2;
     unsigned size;
     hwloc_obj_t obj;
     bool found = false;
 
     /* Look for the smallest L2 cache size */
     size = 4096;
-    while (1) {
-        obj = opal_hwloc_base_get_obj_by_type(opal_hwloc_topology,
-                                              HWLOC_OBJ_CACHE, 2,
-                                              i, OPAL_HWLOC_LOGICAL);
-        if (NULL == obj) {
-            break;
-        } else { 
-            found = true;
-            if (NULL != obj->attr &&
-                size > obj->attr->cache.linesize) {
-                size = obj->attr->cache.linesize;
+    while (cache_level > 0 && size == 4096) {
+        i=0; 
+        while (1) {
+            obj = opal_hwloc_base_get_obj_by_type(opal_hwloc_topology,
+                                                  HWLOC_OBJ_CACHE, cache_level,
+                                                  i, OPAL_HWLOC_LOGICAL);
+            if (NULL == obj) {
+                --cache_level;
+                break;
+            } else { 
+                found = true;
+                if (NULL != obj->attr &&
+                    obj->attr->cache.linesize > 0 &&
+                    size > obj->attr->cache.linesize) {
+                    size = obj->attr->cache.linesize;
+                }
             }
+            ++i;
         }
-        ++i;
     }
```
1.8.4 seems to work for some reason. I instrumented fill_cache_line_size() and it has the same bug, but it looks like opal_cache_line_size seems to be reset to 128 somewhere else. I can't seem to find out exactly where though. I'll send in a pull request based on what approach we want to adopt here.

**Comment by jsquyres** [comment]
The overall approach seems fine, but the specific double loop you posted doesn't feel right to me -- don't you want to break out of both loops as soon as you find a valid value?

BTW, it might be easier to file a PR and then we can comment directly in the code in your patch.

**Comment by nysal** [comment]
The original code also doesn't break out of the loop, if a valid value is found. It keeps looping through all L2 hwloc cache objects until it finds the smallest cache line size. Why is this needed? I mirrored this behaviour. I can change the logic to break out of the loop on the first value found. I'd like to understand the motivation for the previous logic before doing the change.

**Comment by jsquyres** [comment]
Ah, I think I see where I got confused.

How about changing:

```c
 while (cache_level > 0 && size == 4096) {
// to
 while (cache_level > 0 && !found) {
```

**Comment by nysal** [comment]
ompi 1.8.4 behaves differently from the master branch. fill_cache_line_size() seems to be invoked only by the mpirun process. The MPI processes use the default cache line size (128). This works as of today, but might not be really optimal for x86. I haven't investigated why this happens, will take a look soon.

**Comment by rhc54** [comment]
Looks like this was fixed

**Comment by Zhiming-Wang** [comment]
The issue was reappeared in our environment. Can we merge the fix into next release, v1.10.1 and v1.8.9?

**Comment by jsquyres** [comment]
@Zhiming-Wang @nysal In which version(s) did the problem appear: master, v2.x, v1.10.x?   (note that 1.8.x is likely dead -- the future is v1.10 and v2.x)  I.e., did the fix simply not get PR'ed over to v1.10.x and/or v2.x?

**Comment by Zhiming-Wang** [comment]
@jsquyres The issue was reappeared twice. At first time, openmpi-1.8.7-1.ppc64le.rpm was used. The second time, I can't get the specific version number. It must be pre-release version (v1.8.x) or the version from yum repository (v1.6.x).

**Comment by jsquyres** [comment]
@Zhiming-Wang Gotcha.  v1.8.x is dead; v1.6.x is long dead.  Can you reproduce in v1.10x (I'm guessing: yes) and/or v2.x?

**Comment by Zhiming-Wang** [comment]
@jsquyres 
I download the new release v1.10.0 from official website and built it on Power8 platform.
http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.0.tar.gz
For various reasons; I could not access the real-applications which were failed on Power8 platform.  I reappeared it at a unusual way. Is it a useful case?
$ $MPI_ROOT/bin/mpicc hello_world.c -o hw
$ ./hw
[power804nv:07666] mca: base: components_open: component coll / libnbc open function failed
[power804nv:07666] *** Process received signal ***
[power804nv:07666] Signal: Segmentation fault (11)
[power804nv:07666] Signal code: Address not mapped (1)
[power804nv:07666] Failing at address: 0x30
[power804nv:07666] [ 0] [0x3fff98420478]
[power804nv:07666] [ 1] /home/testmpi/dir_openmpi/ompi110-release/lib/openmpi/mca_coll_libnbc.so(+0x5368)[0x3fff96dd5368]
[power804nv:07666] [ 2] /home/testmpi/dir_openmpi/ompi110-release/lib/openmpi/mca_coll_libnbc.so(+0x5354)[0x3fff96dd5354]
[power804nv:07666] [ 3] /home/testmpi/dir_openmpi/ompi110-release/lib/libopen-pal.so.13(mca_base_component_close+0x40)[0x3fff97f6e390]
[power804nv:07666] [ 4] /home/testmpi/dir_openmpi/ompi110-release/lib/libopen-pal.so.13(mca_base_framework_components_open+0x1bc)[0x3fff97f6defc]
[power804nv:07666] [ 5] /home/testmpi/dir_openmpi/ompi110-release/lib/libopen-pal.so.13(mca_base_framework_open+0x18c)[0x3fff97f7b26c]
[power804nv:07666] [ 6] /home/testmpi/dir_openmpi/ompi110-release/lib/libmpi.so.12(ompi_mpi_init+0x614)[0x3fff98351234]
[power804nv:07666] [ 7] /home/testmpi/dir_openmpi/ompi110-release/lib/libmpi.so.12(MPI_Init+0x194)[0x3fff9837b224]
[power804nv:07666] [ 8] ./hw[0x10000a0c]
[power804nv:07666] [ 9] /lib/powerpc64le-linux-gnu/libc.so.6(+0x24d00)[0x3fff98114d00]
[power804nv:07666] [10] /lib/powerpc64le-linux-gnu/libc.so.6(__libc_start_main+0xc8)[0x3fff98114ef8]
[power804nv:07666] *** End of error message ***
Segmentation fault

If the fix was added, the "./hw" was passed.

**Comment by jsquyres** [comment]
Ok, good to know: it happens with v1.10.  Can you file a PR for v1.10?

Does it happen on master / v2.x?

**Comment by Zhiming-Wang** [comment]
The case was failed on v2.x. If the fix was added, it was passed.
It was passed on master. The fix already exists on master.
I will create  PR for both v1.10 and v2.x.
