### ISSUE TITLE
Issue when using btl/vader under heavy contention/

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#3845]
Thank you for taking the time to submit an issue!

## Background information

There is a longstanding bug in the ob1 pml that has bitten us yet again. Under heavy contention it is possible to get into a state where ob1 will not progress its send pending list even though there are network resources available. This happens when the BTL makes no callbacks (because there are none to be made) when there are fragments on the ob1 pending list. The quick fix is to update vader to avoid the issue but the real fix will be to update ob1 to periodically progress the send pending list 

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

All versions.

**Comment by hjelmn** [comment]
Working on the vader workaround now.

**Comment by jjhursey** [comment]
@hjelmn We are just trying to better understand the fix. in PR #3845 the discussion is about fixing a progression issue. How did that lead to a data corruption?
Or is the data corruption handled by #3844 and a hang fixed by PR #3845?

**Comment by hjelmn** [comment]
The data corruption is #3844 and the hang is #3845. Eventually I will make ob1 better with regard to  the pending list but modifying vader works for now.

**Comment by bwbarrett** [comment]
@hjelmn, where are we on this?

**Comment by hjelmn** [comment]
Complete. All branches merged.
