### ISSUE TITLE
Compilation error: SIGSEGV not declared here. First use in this function

### ISSUE THREAD

**Issue by victorsndvg** [open-mpi/ompi#3902]
### What version of Open MPI are you using?

OpenMPI 3.0.0 rc1 and also OpenMPI 2.1.1 

### Describe how Open MPI was installed

Both versions compiled from tarballs

### Please describe the system on which you are running

* Operating system/version:  RedHat 6 - kernel version 2.6.32-573.12.1.el6.x86_64

## Details of the problem

Error detected during compilation process.

Configuration has been performed with some external libraries:  hwloc, libverbs, pmix and libevent.

**Configuration and compilation commands:**
```
$ ./configure --with-hwloc=... --enable-shared --with-slurm --enable-mpi-thread-multiple --with-verbs-libdir=... --enable-mpirun-prefix-by-default --disable-dlopen --with-pmix=... --with-libevent=... --with-knem
$ make all install
```

**Error message:**
```
...

btl_vader_knem.c: En la función ‘mca_btl_vader_knem_init’:
btl_vader_knem.c:112:5: aviso: declaración implícita de la función ‘signal’ [-Wimplicit-function-declaration]
     signal (SIGSEGV, SIG_DFL);
     ^~~~~~
btl_vader_knem.c:112:13: error: ‘SIGSEGV’ no se declaró aquí (primer uso en esta función)
     signal (SIGSEGV, SIG_DFL);
             ^~~~~~~
btl_vader_knem.c:112:13: nota: cada identificador sin declarar se reporta sólo una vez para cada función en el que aparece
btl_vader_knem.c:112:22: error: ‘SIG_DFL’ no se declaró aquí (primer uso en esta función)
     signal (SIGSEGV, SIG_DFL);
                      ^~~~~~~
make[2]: *** [btl_vader_knem.lo] Error 1
make[2]: se sale del directorio `/mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility/openmpi-3.0.0rc1/opal/mca/btl/vader'
make[1]: *** [all-recursive] Error 1
make[1]: se sale del directorio `/mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility/openmpi-3.0.0rc1/opal'
make: *** [all-recursive] Error 

```

**Possible fix:**

In both versions, seems that adding `#include <signal.h>` in `btl_vader_knem.c` file avoid the issue in my case.

Thanks in advance.

This is the first time I post an issue here. Sorry if I did it in the wrong way.

Hope it helps!

**Comment by hjelmn** [comment]
Shoot. Debug code in a production release. Fixing.

**Comment by hjelmn** [comment]
For now just delete the offending line.

**Comment by victorsndvg** [comment]
:+1:

**Comment by hjelmn** [comment]
Merged into affected branches. Closing.
