### ISSUE TITLE
activating lazy_open for shared file pointers in ompio leads to erroneous error message

### ISSUE THREAD

**Issue by edgargabriel** [open-mpi/ompi#3904]
Thank you for taking the time to submit an issue!

## Background information

when activating the mca_io_ompio_sharedfp_lazy_open option in ompio, the code returns an erroneous error message when using MPI_MODE_APPEND. Fix will be provided immediately.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

master, 3.0, 2.x 

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

any configuration. The problem is however only occuring if the user enables the lazy_open switch for shared file pointers, which is not set by default + uses MPI_MODE_APPEND.

### Please describe the system on which you are running

* Operating system/version: 
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -np 2 ./hello_world
```

**Comment by bwbarrett** [comment]
@edgargabriel, is this still targeted for 2.1.x?  I see the label, but not a PR into v2.x...

**Comment by edgargabriel** [comment]
@bwbarrett I am contemplating to not move that to the 2.1 branch. The flag at this point really is just a minor optimization, that users would have to utilize very cautiously, i.e. know the conditions under which they can activate it.

**Comment by hppritcha** [comment]
@edgargabriel can we remove the target 2.x label since you're not planning to push back to 2.1?

**Comment by edgargabriel** [comment]
yes, lets do that.
