### ISSUE TITLE
Use project name when registering performance variables

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#3918]
## Background information

The MCA variables system uses the project name to create variable groups. Unfortunately the performance variable system does not. This is a bug in the MCA base.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

This affects Open MPI v2.0.x, v2.x, and v3.0.x.

**Comment by bwbarrett** [comment]
@hjelmn, I see commits for all the tagged targets; can this be closed?
