### ISSUE TITLE
Fix signal forwarding on ORTE

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#3943]
As reported on SLURM mailing list, orte daemons are not forwarding SIGSTOP and thus leaving application procs merrily spinning away. Although it was reported for v2.x, the user is content with a fix going into v3.0

**Comment by rhc54** [comment]
hmmm...auto-closing of issues doesn't seem to be working?

**Comment by bwbarrett** [comment]
@rhc54, auto-closing on GitHub only works on the default branch (master in our case).  It doesn't work on other branches.  This is documented, but not super obviously.

**Comment by tgpfeiffer** [comment]
(Also described the problem in <https://github.com/open-mpi/ompi/issues/2075#issuecomment-334346454>.) I have `mpirun` running in a Docker container and when I stop that container it seems that SIGTERM and SIGCONT are sent to the `mpirun` process (I hope that my reading of the `strace` output is correct) which (occasionally?) leads to an endless stream of
> (null): Forwarding signal 18 to job

messages in my standard output. In the PR that closed this issue that was mentioned (https://github.com/open-mpi/ompi/pull/3931#issuecomment-316207347) but I am wondering why that message is repeated again and again and how I can disable that.

**Comment by rhc54** [comment]
What OMPI version are you using?

**Comment by rhc54** [comment]
Never mind - I see from your other comment that it is 3.0.

**Comment by rhc54** [comment]
@jjhursey Are you IBM guys addressing this in Spectrum? Any possibility of patches from that coming over here?
