### ISSUE TITLE
Implement MPI_Comm_set_info() and MPI_Comm_get_info()

### ISSUE THREAD

**Issue by gpaulsen** [open-mpi/ompi#398]
Right now MPI_Comm_set_info() and get_info() are dummy functions that just throw away whatever data is given to it, and doesn't return anything.
These need to be implemented to work as stated in the MPI 3.0 Standard.

Dr. David Solt (IBM) has agreed to implement this functionality in the March 2015 timeframe.

**Comment by jsquyres** [comment]
We also talked about separating the functionality into two parts:

1. Move the central "key=value" functionality stuff down to the OPAL layer.
2. Keep the MPI semantics (implemented on top of the OPAL "key=value" stuff) up in the OMPI layer.

This would allow us to take values from the app that were set via MPI_Info API calls and pass them down to OPAL entities -- e.g., BTLs.

What's Dave Solt's Github ID?

**Comment by gpaulsen** [comment]
I pinged Dave, and he thinks he might be able to start tomorrow.

**Comment by dsolt** [comment]
Tomorrow, tomorrow I'll love you tomorrow.  Its only a day away.   Ok,  I'm seriously downloading the code and working on it right now!

**Comment by dsolt** [comment]
Can you think of a good MPI_Info that we could add a "subscriber" for?   I could make one up?  Like buffering=none  to turn all MPI_Send's into MPI_Ssends?

**Comment by jsquyres** [comment]
Sounds good to me.  :-)

**Comment by dsolt** [comment]
Does MPI_XXXX_get_info return an Info with all key/values that might be used by the underlying system even if the values are garbage, or only return key/values for which the underlying system has validated that the value made sense and had some influence on the system.   I plan to go with the later unless you think otherwise.

**Comment by edgargabriel** [comment]
Not sure whether it makes sense it this context or not, a looong time back (pre Open MPI) we had that idea of trying to separate communication on a per communicator basis, e.g. all communication on comm1 uses InfiniBand (or ATM at that time), on comm2 GE,  or similar. Today, we could think about trying to separate communication for File I/O and 'message passing' to use separate IB cards or ports (if you have multiple per node). An Info object might be optimal for that.

**Comment by jsquyres** [comment]
MPI 3.1 section 6.4 p249-250 says:

> MPI_COMM_GET_INFO returns a new info object containing the hints of the commu- nicator associated with comm. The current setting of all hints actually used by the system related to this communicator is returned in info_used. If no such hints exist, a handle to a newly created info object is returned that contains no key/value pair. The user is responsible for freeing info_used via MPI_INFO_FREE.
> Advice to users. The info object returned in info_used will contain all hints currently active for this communicator. This set of hints may be greater or smaller than the set of hints specified when the communicator was created, as the system may not recognize some hints set by the user, and may recognize other hints that the user has not set. (End of advice to users.)

**Comment by dsolt** [comment]
I read that but still not sure of the exact definition of "actually used by the system".   If I have an info that specifies "comm_method=USNIC" and comm_method is a "key" we look for and "USNIC" is a supported value for comm_method, but this system doesn't happen to have USNIC on it, so we ignore the setting.  Should "comm_method=USNIC" be returned by MPI_COMM_GET_INFO?   I think not, but the MPI3.1section6.4 is a little vague about that in my opinion.

**Comment by jsquyres** [comment]
It is a little vague.  My interpretation is along the lines of yours: return hints that are actually in use by the system.

Hence, when MPI_Comm_get_info() is called, it will callback all of the agents who registered with it, pass them the communicator and the info, and let them decide what to put in the info (or not) to be returned to the user.

Make sense?

**Comment by dsolt** [comment]
good, that's what I was thinking.   Then it is up to the callbacks to decide and I don't have to make the choice :)

**Comment by dsolt** [comment]
Another question... I have the code in place for MPI_Comm, but for MPI_Win and MPI_File there seems to already be some code in place.  I have not yet investigated how complete it is.  Do we want this change for Comm's only or should I make Comm, Win and File all consistent?

**Comment by dsolt** [comment]
Just looking at the portals4 get_info and set_info implementation, it looks like they return an info with "accumulating_ordering" and "no_locks" set, regardless of whether set_info was called or what was passed to set_info.

**Comment by jsquyres** [comment]
My comments:

* I think it would be good to support MPI_Win and MPI_File, too.  I.e., it would be good to do the same infrastructure for all 3.
* portals4: since this is early days for all this stuff, I think that component should be updated to conform to the newly-defined behavior.

**Comment by tkordenbrock** [comment]
I don't understand how osc-portals4 is out of compliance.

MPI 3.1 section 11.2.7 page 416

> MPI_WIN_SET_INFO sets new values for the hints of the window associated with win.  The call is collective on the group of win. The info object may be different on each process, but any info entries that an implementation requires to be the same on all processes must appear with the same value in each process's info object.
> Advice to users. Some info items that an implementation can use when it creates a window cannot easily be changed once the window has been created. Thus, an implementation may ignore hints issued in this call that it would have accepted in a creation call. (End of advice to users.)

The "no_locks" and "accumulate_ordering" hints are set at window creation (component_select) and cannot be changed using set_info.  So having set_info do nothing other than a barrier is compliant.

MPI 3.1 section 11.2.7 page 416-417

> MPI_WIN_GET_INFO returns a new info object containing the hints of the window associated with win. The current setting of all hints actually used by the system related to this window is returned in info_used. If no such hints exist, a handle to a newly created info object is returned that contains no key/value pair. The user is responsible for freeing info_used via MPI_INFO_FREE.
> Advice to users. The info object returned in info_used will contain all hints currently active for this window. This set of hints may be greater or smaller than the set of hints speciffed when the window was created, as the system may not recognize some hints set by the user, and may recognize other hints that the user has not set. (End of advice to users.)

The "no_locks" and "accumulate_ordering" hints are "actually used by the system".  If set_info is never called, never called with these hints or the window is created without these hints, get_info may return a "set of hints ... greater ... than the set of hints specified when the window was created".  So having get_info return hints set (explicitly or implicitly) during window creation is compliant.

**Comment by dsolt** [comment]
I don't think osc-portals4 is out of compliance, I was just pointing out what that code was doing currently and trying to work through how to make sure our interface supports that case.

**Comment by tkordenbrock** [comment]
OK.  Sounds good.

**Comment by hppritcha** [comment]
@dsolt can we close  this issue now?

**Comment by jjhursey** [comment]
See PR #2941

**Comment by hppritcha** [comment]
@jjhursey is this going to make it into master soon?

**Comment by hppritcha** [comment]
the PR sorry.

**Comment by jjhursey** [comment]
I think we are waiting for a review on PR #2941.

**Comment by jsquyres** [comment]
#2941 was merged.
