### ISSUE TITLE
Internal representation difference of a datatype with a gap

### ISSUE THREAD

**Issue by kawashima-fj** [open-mpi/ompi#3986]
Open MPI 2.0.2 and 2.0.3/master have different representation for a datatype with a gap. @bosilca Could you comment?

I run the following program.

```c
#include <mpi.h>

extern void ompi_datatype_dump(void *datatype);

int main(int argc, char* argv[])
{
    MPI_Datatype datatype;
    MPI_Init(&argc, &argv);
    MPI_Type_vector(2, 1, 2, MPI_INT, &datatype); // int(4B), gap(4B), int(4B)
    MPI_Type_commit(&datatype);
    ompi_datatype_dump(datatype);
    MPI_Type_free(&datatype);
    MPI_Finalize();
    return 0;
}
```

Open MPI 2.0.2 output:

```
Datatype 0xb631e0[] id 74 size 8 align 4 opal_id 0 length 4 used 3
true_lb 0 true_ub 12 (true_extent 12) lb 0 ub 12 (extent 12)
nbElems 2 loops 1 flags 104 (committed )-c-----GD--[---][---]
   contain OPAL_INT4
------PG---[---][---]      OPAL_LOOP 2 times the next 2 elements extent 8
--C---PGD--[---][---]      OPAL_INT4 count 1 disp 0x0 (0) extent 4 (size 4)
------PG---[---][---]  OPAL_END_LOOP prev 2 elements first elem displacement 0 size of data 4
-------G---[---][---]  OPAL_END_LOOP prev 3 elements first elem displacement 0 size of data 8
Optimized description
------PGD--[---][---]      OPAL_INT4 count 2 disp 0x0 (0) extent 8 (size 8)
-------G---[---][---]  OPAL_END_LOOP prev 1 elements first elem displacement 0 size of data 8

type 3 count ints 3 count disp 0 count datatype 1
ints:     2 1 2
types:    MPI_INT
```

Open MPI 2.0.3 and master output:

```
Datatype 0x15582f0[] id 74 size 8 align 4 opal_id 0 length 4 used 1
true_lb 0 true_ub 12 (true_extent 12) lb 0 ub 12 (extent 12)
nbElems 2 loops 0 flags 104 (committed )-c-----GD--[---][---]
   contain OPAL_INT4 
------PGD--[---][---]      OPAL_INT4 count 2 disp 0x0 (0) blen 0 extent 8 (size 8)
-------G---[---][---]  OPAL_END_LOOP prev 1 elements first elem displacement 0 size of data 8
Optimized description 
-cC---P-DB-[---][---]      OPAL_INT4 count 2 disp 0x0 (0) blen 1 extent 8 (size 8)
-------G---[---][---]  OPAL_END_LOOP prev 1 elements first elem displacement 0 size of data 8

type 3 count ints 3 count disp 0 count datatype 1
ints:     2 1 2 
types:    MPI_INT 
```

The notable difference is flags of the first elements of optimized descriptions (`------PGD--` and `-cC---P-DB-`). Open MPI 2.0.2 says there is a gap (`G`) but Open MPI 2.0.3 and master says there is *no* gap (`-`). Which one is correct? Or these flags are not siginificant? The difference comes from 148929b in v2.0.x and 639f4b1 in master.

This difference may not affect user's MPI programs but affects my OSC component. My OSC component reads/writes per contiguous block by analyzing OPAL datatype internal structure.

**Comment by kawashima-fj** [comment]
@bosilca Could you comment?

**Comment by bosilca** [comment]
@kawashima-fj the most notable difference is the introduction of the ```blen``` field which is the indicator that this is a composite vector. In fact the new representation saves space on the datatype description by packing the vector type as much as possible. Now the ```count``` is the number of repetitions of the ```blen``` block-length, each one with the specified ```extent```. The flags does not apply to the entire line but to the type that is represented by the ```blen``` counter.

Thus you will need to check the if the size of the type multiplied by blen is equal to the extent in order to know if the entire type (count * blen) is contiguous.

**Comment by kawashima-fj** [comment]
@bosilca Thanks for your explanation. I'll revise my code.
