### ISSUE TITLE
If libfabric is borked, configure unconditionally aborts

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#3995]
As an offshoot out of #3989, it was discovered that if configure determines that libfabric is borked (by linking in both libnl v1 and v3), then configure aborts.

Instead, it should obey `--with[out]-libfabric` CLI conventions (i.e., only abort if `--with-libfabric` was specified; otherwise, just skip libfabric support).

**Comment by jsquyres** [comment]
@PHHargrove Can you attach your full configure output and config.log to this issue?  I'm digging into this issue, and this might be a bit more complex than I initially thought.

**Comment by PHHargrove** [comment]
@jsquyres here you go (w/ .txt suffixes to make github happy):  
[config.log.txt](https://github.com/open-mpi/ompi/files/1191720/config.log.txt)  
[configure.out.txt](https://github.com/open-mpi/ompi/files/1191721/configure.out.txt)

**Comment by PHHargrove** [comment]
@jsquyres Let me know if access to the system is needed to resolve this.  I can reactivate your account on our cluster.

**Comment by hppritcha** [comment]
@jsquyres can this issue be closed now?

**Comment by jsquyres** [comment]
No. @PHHargrove reported an error with my latest patch (in #4016), and I haven't fixed it yet.
