### ISSUE TITLE
Typo in spml_ucx.c ?

### ISSUE THREAD

**Issue by tonycurtis** [open-mpi/ompi#3996]
Thank you for taking the time to submit an issue!

## Background information

possible typo in source code format string

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

commit 83d21e31302054eb24d12190ecd71cc9d3bb0f13 (HEAD -> master, origin/master, origin/HEAD)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Source from git clone

### Please describe the system on which you are running

* Operating system/version:  Fedora 26
* Computer hardware: VMWare VM (on Macbook)
* Network type: ethernet

-----------------------------

## Details of the problem

In oshmem/mca/spml/ucx/spml_ucx.c

```
    592 int mca_spml_ucx_quiet(void)
    593 {
    594     ucs_status_t err;
    595 
    596     err = ucp_worker_flush(mca_spml_ucx.ucp_worker);
    597     if (UCS_OK != err) {
    598          SPML_ERROR("fence failed: %s", ucs_status_string(err));
    599          oshmem_shmem_abort(-1);
    600          return OSHMEM_ERROR;
    601     }
    602     return OSHMEM_SUCCESS;
    603 }
```

shouldn't that say "quiet failed" on line 598 ?

**Comment by bwbarrett** [comment]
@jladd-mlnx, can you have someone take a look?

**Comment by jladd-mlnx** [comment]
@bwbarrett thanks. We will address this.

**Comment by bwbarrett** [comment]
@jladd-mlnx, ping
