### ISSUE TITLE
ORTE needs to work better with SLURM signal mechanisms

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#3998]
Our site (and other DOE CTS-1 system owners) are having problems with Open MPI/ORTEs interaction with SLURM's mechanism for propagating signals to processes in a job, in particular when using SLURM scancel of sbatch + --signal option.

The problem has to do with what's going on with the HNP, namely, that MPI processes are currently children of the HNP rather than a slurmd daemon.   SLURM doesn't know about the HNP or any child processes, so they are left out of any SLURM signaling.   Note the Cray SLURM environment is currently being treated differently so it doesn't have this problem.

**Comment by bwbarrett** [comment]
@hppritcha, which branches does this impact?

**Comment by ggouaillardet** [comment]
@hppritcha what is the behavior you would like/expect ?

1. slurm signals the HNP (and probably the tasks running on this node too), and then Open MPI does the signal propagation
2. slurm signals the HNP (but not its children), and then Open MPI does the signal propagation
3. slurm signals all processes (shells, mpirun, orted, mpi tasks, ...)
4. slurm signals mpirun (and some shells) and orted, and it is up to Open MPI to kill the MPI tasks

**Comment by hppritcha** [comment]
@bwbarrett oops forgot about this one.  Since it adds an mca parameter, I didn't think we normally would push this kind of a change back to current release branches.  My site is okay with a patch to solve this issue and we're going that route locally for the 2.1.x.  We are okay with this waiting till the next major release.

**Comment by rhc54** [comment]
Completed
