### ISSUE TITLE
pmix support for non-builtin atomics appear to be busted

### ISSUE THREAD

**Issue by PHHargrove** [open-mpi/ompi#4001]
With the 3.0.0rc2 tarball I've configured with `CC=xlc CXX=xlC FC=xlc --enable-debug --disable-builtin-atomics`.
In configure's output I see the following while configuring pmix2x:
```
checking for assembly architecture... POWERPC32
checking for builtin atomics... BUILTIN_NO
checking for pre-built assembly file... /bin/grep: /src/atomics/asm/asm-data.txt: No such file or directory
no (not in asm-data)
checking whether possible to generate assembly file... failed
configure: WARNING: Could not build atomic operations assembly file.
configure: WARNING: There will be no atomic operations for this build.
```

The "No such file or directory" appears to be an error.  
Examining pmix_config_asm.m4 is appears that `PMIX_TOP_SRCDIR` is used but never defined.

**Comment by rhc54** [comment]
I'll address it when I return on Friday

**Comment by rhc54** [comment]
Weird - PMIX_TOP_SRCDIR is defined in configure.ac way before pmix_config_asm.m4 is referenced. So I wonder why it got lost?

**Comment by rhc54** [comment]
Hmmm...looks like opal_config_asm.m4 has radically changed anyway, and another issue thread implies that maybe we need to update it for other reasons. I'm going to close this one and just track the update to the overall asm configure code.
