### ISSUE TITLE
remove references to removed coll/hierarch from README starting at v2

### ISSUE THREAD

**Issue by ggouaillardet** [open-mpi/ompi#4005]
As reported at https://stackoverflow.com/questions/45459262/mpi-and-hierarchical-collectives-missing-hierarch-coll-module-from-openmpi-2 README from ```v2``` should no more reference ```coll/hierarch``` since this module has been removed.

**Comment by ggouaillardet** [comment]
@bwbarrett @hppritcha fyi, this is a trivial documentation fix. i will do that tomorrow, and i hope it can make it for ```v3.0.0```. meanwhile, everyone is free to fix that if timing is critical

**Comment by jsquyres** [comment]
Looks like this is done everywhere.  Closing.
