### ISSUE TITLE
pkg-config will contain wrong ldflags

### ISSUE THREAD

**Issue by junghans** [open-mpi/ompi#406]
```
$ pkg-config --libs ompi-c
-Wl,-rpath -Wl,@\{libdir\} -Wl,--enable-new-dtags -lmpi
```
The `@\{libdir\}` seems to be an unexpanded left-over.

**Comment by jsquyres** [comment]
Oops!  How terrible.  I see this in both master and the v1.8 branch.  I'll fix.

Just curious -- we see so few people using pkg-config -- any particular reason you're using it?

**Comment by junghans** [comment]
Well, sometimes pkg-config is useful in cases when one cannot use mpicc, e.g. in combination with other compiler wrappers.

**Comment by jsquyres** [comment]
In the meantime, you can use the variants of `mpicc --showme:compile` and friends.  See `mpicc(1)` for more details.
