### ISSUE TITLE
v2.1.x: PMIx visibility issue

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#4069]
@rhc54 reminded me this morning that there is still a pending symbol visibility issue identified by @siegmargross for the v2.1.x series.

Ralph is working on it and should have a PR within a few days.  We won't hold up the v2.1.2rc for this issue, but wanted to file an issue just to make sure we track it.

**Comment by jsquyres** [comment]
I believe that this is the @siegmargross issue that was reported: https://www.mail-archive.com/users@lists.open-mpi.org/msg31383.html

**Comment by rhc54** [comment]
This should have been closed by #4080
