### ISSUE TITLE
Port madvise fix to v2.0.x branch

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#4078]
As discussed on https://github.com/open-mpi/ompi/issues/3685#issuecomment-321002480, need to port the madvise fix to the v2.0.x branch (it's a bit more work than was required to bring it to the v2.x and v3.0.x branches in PRs #4042 and #4041, respectively).

Adding this as an issue so that we don't forget / can track it.

**Comment by jsquyres** [comment]
@hjelmn Any progress on the port of this fix to v2.0.x?

**Comment by hppritcha** [comment]
@hjelmn could you take a look at this soon? We'd like to close out 2.0.x soon.

**Comment by hppritcha** [comment]
@hjelmn please close this issue if PR #4203 resolved it.

**Comment by jsquyres** [comment]
It does, so I'll close this issue.
