### ISSUE TITLE
shmem_broadcast not in OpenSHMEM

### ISSUE THREAD

**Issue by jdinan** [open-mpi/ompi#4098]
The ```shmem_broadcast``` routine provided by OSHMEM is not part of OpenSHMEM.  For compliance with OpenSHMEM, this routine should either be renamed to ```shmemx_broadcast``` (and moved to ```shmemx.h```) or removed.

## Background information

[OpenSHMEM v1.3](http://openshmem.org/site/sites/default/site_files/OpenSHMEM-1.3.pdf), Section 5:
> The OpenSHMEM header files for C and Fortran must contain only the interfaces and constant names defined in this specification.

and Section 8.6.3, broadcast routines.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

master: https://github.com/open-mpi/ompi/blob/master/oshmem/include/shmem.h.in#L542

**Comment by jsquyres** [comment]
@artpol84 @jladd-mlnx Can you guys have a look?

**Comment by jdinan** [comment]
Here's another one -- ```SHMEM_HEAP_TYPE``` is also not in the spec.

https://github.com/open-mpi/ompi/blob/master/oshmem/include/shmem.h.in#L76

**Comment by jdinan** [comment]
Also, ```SHMEM_HEAP_SIZE``` (```SHMEM_SYMMETRIC_SIZE``` is the constant defined by the spec.).

**Comment by jsquyres** [comment]
@artpol84 confirmed on the weekly dev webex that Mellanox will be looking into this.
