### ISSUE TITLE
Static link error on Cray XC30

### ISSUE THREAD

**Issue by lcebaman** [open-mpi/ompi#4127]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

2.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

module swap PrgEnv-cray  PrgEnv-intel
export CRAY_LINK_TYPE=static
CC=cc CXX=CC CXXFLAGS=-static CFLAGS=-static ./configure --enable-mpi-thread-multiple --enable-static --disable-shared

### Please describe the system on which you are running
Cray XC30
* Operating system/version: 
CLE 5.2
* Computer hardware: 
Intel Ivy Bridge
* Network type: 
Cray Aries interconnect
-----------------------------

## Details of the problem

Trying to compile OpenMPI on a Cray XC30 we get the following error
```shell
 CCLD     opal_wrapper
/usr/bin/ld: attempted static link of dynamic object `/usr/lib64/libpciaccess.so'
```

**Comment by hjelmn** [comment]
libpciaccess is only one of the libraries which Cray does not provide a static library for. If you want static linking you can disable pci support (not needed on Crays anyway) and memkind. When I get back to the office on Thursday i will see if there are others.

**Comment by lcebaman** [comment]
I am also getting `attempted static link of dynamic object `/usr/lib64/libmunge.so'`

**Comment by hppritcha** [comment]
munge presents a similar problem.  You'll need to build that package yourself and install in a non-default location, and set LDFLAGS to include the path where you installed libmunge.a

Is there a particular reason to build statically?

**Comment by hppritcha** [comment]
see #6897
