### ISSUE TITLE
Add 32 bit test for Jenkins & MTT

### ISSUE THREAD

**Issue by bwbarrett** [open-mpi/ompi#4157]
As discovered in https://github.com/open-mpi/ompi/issues/4146, we don't do any CI tests for 32 bit builds.  Just adding `-m32` to the compiler flags should be sufficient to smoke test so that we catch issues before MTT.  Likewise, Absoft is currently the only 32-bit MTT test; AWS will add one to its suite.

**Comment by awlauria** [comment]
OMPI decided to disable 32bit support per #11248. Closing.
