### ISSUE TITLE
PERUSE build broken in ob1

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#416]
It looks like some recent commits have caused minor breakage in `--enable-peruse` builds.

@hjelmn Can you have a look?  Probably pretty easy to fix.

```
Making all in mca/pml/ob1
make[2]: Entering directory `/home/jsquyres/git/o2/ompi/mca/pml/ob1'
  CC       pml_ob1_recvreq.lo
In file included from ../../../../ompi/mca/pml/base/pml_base_sendreq.h:29:0,
                 from pml_ob1.h:36,
                 from pml_ob1_recvreq.h:31,
                 from pml_ob1_recvreq.c:35:
pml_ob1_recvreq.c: In function 'mca_pml_ob1_recv_request_put_frag':
pml_ob1_recvreq.c:426:66: error: 'size' undeclared (first use in this function)
                                   &(recvreq->req_recv.req_base), size,
                                                                  ^
../../../../ompi/peruse/peruse-internal.h:98:36: note: in definition of macro 'PERUSE_TRACE_COMM_OMPI_EVENT'
             _comm_spec.count     = size;                                               \
                                    ^
pml_ob1_recvreq.c:426:66: note: each undeclared identifier is reported only once for each function it appears in
                                   &(recvreq->req_recv.req_base), size,
                                                                  ^
../../../../ompi/peruse/peruse-internal.h:98:36: note: in definition of macro 'PERUSE_TRACE_COMM_OMPI_EVENT'
             _comm_spec.count     = size;                                               \
                                    ^
make[2]: *** [pml_ob1_recvreq.lo] Error 1
```

**Comment by hjelmn** [comment]
Should we just add pvars to cover what peruse measured/tracked and finally kill peruse?

@bosilca I know we discussed what to do with peruse but I don't remember what we decided to do.

**Comment by bosilca** [comment]
We reached the conclusion that there is no alternative approach at the
PVAR/CVAR level. Do they provide a way to register callbacks on events?

**Comment by hjelmn** [comment]
Ah, yes. If event-based tools are still needed we have to leave peruse as is. The best we can do with MPI_T is expose timers for some of the events. For example, total matching time instead of events for matching start/complete.

**Comment by jsquyres** [comment]
Yes, I remember it the same way (leave PERUSE because it's event based).

Any chance someone can fix this build issue?  It's probably pretty easy (for someone who knows their way around ob1...).
