### ISSUE TITLE
MPI_T Segmentation Fault

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#4162]
Thank you for taking the time to submit an issue!

## Background information

Using the MPI_T interface can lead to a segmentation fault if:

1) Monitoring is disabled, and
2) dynamic components are enabled

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

master

### Please describe the system on which you are running

* Operating system/version: 
* Computer hardware: 
* Network type: 

-----------------------------

Any.

## Details of the problem

SEGV

Reproducer from LLNL:

```c
#include <stdio.h>
#include <mpi.h>

static MPI_T_pvar_session session;
static MPI_T_pvar_handle handle;

int main(int argc, char **argv) {
    int numRanks, myRank, threadsup, count, index;
    MPI_Comm comm;
    
    MPI_Init(&argc, &argv) ;
    MPI_Comm_size(MPI_COMM_WORLD, &numRanks) ;
    MPI_Comm_rank(MPI_COMM_WORLD, &myRank) ;
    comm = MPI_COMM_WORLD;
    
    PMPI_T_init_thread(MPI_THREAD_SINGLE,&threadsup);
    PMPI_T_pvar_session_create(&session);
    
    index = 1; //OpenMPI Index for the PVAR bound to an MPI_COMM object. This is where the issue happens.
    
    //Code segfaults here
    PMPI_T_pvar_handle_alloc(session, index, &comm, &handle, &count);
    
    MPI_Finalize() ;
    
    printf("Done.\n");
    return 0;
}
```

**Comment by jsquyres** [comment]
Confirmed: this was fixed long ago.  Closing.
