### ISSUE TITLE
Is OpenMPI good for building SMR?

### ISSUE THREAD

**Issue by rupc** [open-mpi/ompi#4168]
Hello!
I'm new to OpenMPI. And I'm considering building Byzantine fault tolerant state machine replication using OpenMPI for message passing framework. I know that many SMRs are built upon message passing framework as its communication layer. But when I have attempt to search interconnection between SMR and MPI, I found not many resources.
My question is "Is OpenMPI good for communication layer of SMR system?"
Thanks in advance!

**Comment by bosilca** [comment]
@rupc, MPI does not provide support for process fault, which is a requirement for any fault tolerant mechanism implemented on top of MPI. I would suggest you look into ULFM, which is an extension to the MPI standard to add support for handling process faults. You can find an implementation of ULFM for Open MPI at fault-tolerance.org (in the software section).
