### ISSUE TITLE
ORTE_ERROR_LOG: Not found in file plm_slurm_module.c at line 450

### ISSUE THREAD

**Issue by theodotos** [open-mpi/ompi#4178]
Thank you for taking the time to submit an issue!

## Background information

We have a 24 node cluster connected with 1GB Ethernet. There is Ubuntu 16.04 64 bit on all nodes.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

Open MPI:
Version: 1.10.2-8ubuntu1

SLURM:
Version: 0.4.3-2build1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Deployed via Ansible from the ubuntu repositories

### Please describe the system on which you are running

* Operating system/version: Ubuntu 16.04 64 bit
* Computer hardware: 24 x IBM System X3755 M3
* Network type: 1 x 1GB Ethernet

-----------------------------

## Details of the problem

We have installed Open MPI and Slurm an all nodes. They have been installed from the Ubuntu repos and deployed through Ansible.

We have created this test Fortran program:

```
program hello
  use MPI
  integer rank, size, ierror, tag, status(MPI_STATUS_SIZE)

  call MPI_INIT(ierror)
  call MPI_COMM_SIZE(MPI_COMM_WORLD, size, ierror)
  call MPI_COMM_RANK(MPI_COMM_WORLD, rank, ierror)
  if(rank==0)print*,'total number of processes = ',size
  Call MPI_BARRIER(MPI_COMM_WORLD, ierror )
  print*, 'node', rank, ': Hello world'
  call MPI_FINALIZE(ierror)
end program hello
```

Compiled with:

```
mpif90 -o test.out test.f90
```

Salloc seems to be working fine.

```
mpirun -n 4 ./test.out

total number of processes =            4
  node           3 : Hello world
  node           2 : Hello world
  node           0 : Hello world
  node           1 : Hello world
```

We have created this script for sbatch:

```
cat <<EOF > submit

#!/bin/bash -l
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=32
#SBATCH --time="UNLIMITED"
#SBATCH --error=job.%j.%N.err
#SBATCH --output=job.%j.%N.out
#SBATCH --export=ALL
source /etc/profile.d/modules.sh

mpirun -n 64 test.out  | tee 'output'
```

When we run the script:

```
sbatch submit
```

... we get:

```
[node01:01572] [[6466,0],0] ORTE_ERROR_LOG: Not found in file plm_slurm_module.c at line 450
```

**Comment by jsquyres** [comment]
Open MPI v1.10.2 is fairly old at this point -- is there any chance that you can upgrade to the latest v2.1.1 (https://www.open-mpi.org/software/ompi/v2.1/)?  Or, if you're tied to the v1.10 release series, could you upgrade to the latest in the v1.10 series to get all the bug fixes that were applied to that series?  (v1.10.7, available here https://www.open-mpi.org/software/ompi/v1.10/)

**Comment by theodotos** [comment]
OK I'll try a newer release and be back.

**Comment by theodotos** [comment]
Now we have version 2.1.1:

```
# mpirun --version
mpirun (Open MPI) 2.1.1
```

But the problem persists:

```
[node07:47882] [[22799,0],0] ORTE_ERROR_LOG: Not found in file plm_slurm_module.c at line 450
```

**Comment by rhc54** [comment]
It means that we aren't finding "srun" - when you execute "sbatch", you are winding up in a shell that doesn't include the SLURM binaries in its path

**Comment by theodotos** [comment]
You are right! *slurm-client* was not installed on the nodes. After we install the *slurm-client* package, it worked!

Thankee-sai
