### ISSUE TITLE
IPv6 support in rdmacm cpc of openib

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#42]
Currently, rdmacm cannot handle if an IPv6 address is passed in (regardless of whether the adapter can handle it or not).  This should be fixed as soon as possible.

When rdmacm is setting up the listeners threads (via the cbc_query call), it must verify the hca/port in question has a valid IP address.  To make this check, it calls mca_btl_openib_rdma_get_ipv4addr (in ompi/mca/btl/openib/btl_openib_iwarp.c) which queries the IPv4 address.  This needs to be expanded to check for IPv6 addresses.

Also, rdmacm should check to see if IPv6 is supported by the adapter and handle failure of rdma_bind_addr based on that parameter.  Based upon the value of the IP address and the value of the attribute max_raw_ipv6_qp, we can set the sin_family to AF_INET or AF_INET6 when creating the listener.

**Comment by rhc54** [comment]
openib component is going away
