### ISSUE TITLE
possible pml/ob1 multi-rail performance regression

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#420]
David Turner posted some [results](http://www.open-mpi.org/community/lists/devel/2015/02/17004.php) to ompi devel which appear to show performance problems when using multiple nics.

**Comment by hppritcha** [comment]
@hjelmn 
I'm going to close this unless anyone thinks this is important.

**Comment by bosilca** [comment]
Why would anyone care about this?

**Comment by jsquyres** [comment]
@hppritcha did the problem get resolved?  If not, it should stay open.

**Comment by hppritcha** [comment]
not that I know of.

**Comment by hjelmn** [comment]
We don't even know exactly how the regression happened. The multi-rail code in ob1 hasn't really changed so it should continue to function as it always has.

**Comment by jsquyres** [comment]
@hjelmn Fair enough, but I thought Dave showed that it didn't.  So it seems like until we investigate, we shouldn't close this issue.

**Comment by bosilca** [comment]
Sorry guys I think I did click on the wrong button "Comment and Close" instead of "Comment". I'll rollback my action.

**Comment by jsquyres** [comment]
@bosilca Just to clarify: your "Why would anyone care about this?" comment was snarkasm, right?

**Comment by rolfv** [comment]
i am not sure this is related, but I also ran into a somewhat similar issue.
http://www.open-mpi.org/community/lists/devel/2015/02/17065.php

**Comment by hppritcha** [comment]
closing this issue.  won't fix.
