### ISSUE TITLE
Compile error when using both --disable-mca-dso and --with-devel-headers

### ISSUE THREAD

**Issue by nmorey** [open-mpi/ompi#4208]
On SUSE LEap 42.3, using either a git tarball of v3.0.0 or the packaged release from the site, build fails:
```
[  156s] make[5]: Entering directory '/home/abuild/rpmbuild/BUILD/openmpi-3.0.0/opal/mca/pmix/pmix2x/pmix/src'
[  156s] make[5]: *** No rule to make target '/home/abuild/rpmbuild/BUILD/openmpi-3.0.0/opal/libopen-pal.la', needed by 'libpmix.la'.  Stop.
```

Tried make without -j, same thing.

```
$ cd opal
$ make libopen-pal.la
[some stuff builds ...]
make: *** No rule to make target 'mca/pmix/pmix2x/libmca_pmix_pmix2x.la', needed by 'libopen-pal.la'.  Stop.
$ cd mca/pmix/pmix2x/
$ make libmca_pmix_pmix2x.la
[some stuff builds ...]
make: *** No rule to make target '/home/abuild/rpmbuild/BUILD/openmpi-3.0.0/opal/mca/pmix/pmix2x/pmix/src/libpmix.la', needed by 'libmca_pmix_pmix2x.la'.  Stop.
$ cd pmix/src/
$ make libpmix.la
[some stuff builds ...]
make: *** No rule to make target '/home/abuild/rpmbuild/BUILD/openmpi-3.0.0/opal/libopen-pal.la', needed by 'libpmix.la'.  Stop.
```

Configure is 
```
./configure --host=x86_64-suse-linux-gnu --build=x86_64-suse-linux-gnu \
--program-prefix= --disable-dependency-tracking --prefix=/usr \
--exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc \
--datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/lib \
--localstatedir=/var --sharedstatedir=/usr/com --mandir=/usr/share/man \
--infodir=/usr/share/info --disable-dependency-tracking \
--prefix=/usr/lib64/mpi/gcc/openmpi3 --exec-prefix=/usr/lib64/mpi/gcc/openmpi3 \
--bindir=/usr/lib64/mpi/gcc/openmpi3/bin --datadir=/usr/lib64/mpi/gcc/openmpi3/share \
--includedir=/usr/lib64/mpi/gcc/openmpi3/include --libdir=/usr/lib64/mpi/gcc/openmpi3/lib64 \
--mandir=/usr/lib64/mpi/gcc/openmpi3/share/man --disable-static --enable-builtin-atomics \
--with-libltdl=/usr --with-verbs --with-pmix=internal --enable-mpi-thread-multiple \
--with-psm --with-devel-headers '--with-package-string=Open MPI2 Distribution for SUSE' \
--enable-mpi-fortran=usempi --disable-mca-dso --disable-silent-rules \
--disable-wrapper-rpath
```

You can find full build log here:
https://build.opensuse.org/build/home:NMoreyChaisemartin:branches:science:HPC/openSUSE_Leap_42.3/x86_64/openmpi3/_log

**Comment by rhc54** [comment]
Remove the --with-pmix=internal and see if that works

**Comment by ggouaillardet** [comment]
as a side note, you might also want to replace ```--with-libltdl=/usr``` with ```-with-libltdl```

**Comment by nmorey** [comment]
@rhc54 same thing

**Comment by ggouaillardet** [comment]
the root cause is in ```opal/mca/pmix/pmix2x/configure.m4```
```
    AS_IF([test "$with_devel_headers" = "yes"],
          [AS_IF([test "$enable_dlopen" != "no"],
                 [opal_pmix_pmix2x_args="--with-pmix-extra-lib=$OPAL_TOP_BUILDDIR/opal/lib${OPAL_LIB_PREFIX}open-pal.la $opal_pmix_pmix2x_args"])
opal_pmix_pmix2x_args="--with-devel-headers  $opal_pmix_pmix2x_args"])
```
do we really need the ```--with-pmix-extra-lib``` option ?
so far, it seems to work just fine without it

**Comment by ggouaillardet** [comment]
@nmorey this is very likely a bug, that is triggered by __both__ ```--disable-mca-dso``` __and__ ```--with-devel-headers```
As a workaround, you can get rid of one of these two options.
An other option is to hack ```configure``` and remove the line where ```--with-pmix-extra-lib``` is prepended to ```$opal_pmix_pmix2x_args```

**Comment by jsquyres** [comment]
@nmorey Question: is there a reason you're using `--with-devel-headers` and `disable-mca-dso`?  The former is really only meant for people who are writing Open MPI plugins and who do not have an Open MPI source tree available -- it is *not* meant for general users who are writing MPI applications.  The latter is really only intended for extreme scale users who are concerned about a bazillion `dlopen()`'s hitting a network filesystem when MPI jobs start up simultaneously across hundreds or thousands of servers.

**Comment by ggouaillardet** [comment]
@nmorey there is indeed a simpler workaround, simply use ```--disable-dlopen``` instead of ```--disable-mca-dso```.

@jsquyres from ```configure --help```

```
  --enable-dlopen         Whether build should attempt to use dlopen (or
                          similar) to dynamically load components. Disabling
                          dlopen implies --disable-mca-dso. (default: enabled)

  --enable-mca-dso=LIST   Comma-separated list of types and/or type-component
                          pairs that will be built as run-time loadable
                          components (as opposed to statically linked in), if
                          supported on this platform. The default is to build
                          all components as DSOs.
```

should ```--disable-mca-dso``` be equivalent to ```--disable-dlopen``` instead ?

**Comment by nmorey** [comment]
@ggouaillardet  @jsquyres The devel-headers should be dropped. I don't know why it's still there.
I added the disable-mca-dso for two reasons:
- We had an issue where shmem support was not found without this
- It fixed automatic dependency detection from the RPM

This ws done some time ago so I don't remember the exact details

**Comment by jsquyres** [comment]
@ggouaillardet Yeah, you're right -- I was mixing up `--disable-mca-dso` and `--disable-dlopen` in my brain.  Disregard what I said about `--disable-mca-dso`, above.

@nmorey `--disable-mca-dso` with no arguments should be a no-op.  Another question (unrelated to your issue): is there a reason you're saying `--enable-mpi-fortran=usempi`?  This will disable the Fortran '08 bindings.  If you have a modern gfortran, the Fortran '08 bindings should work just fine.  You should be able to `--enable-mpi-fortran=usempif08` if you want to ensure that the `mpif.h`, `mpi` module, and `mpi_f08` module are all enabled.

Per what @ggouaillardet mentioned above, removing `--with-devel-headers` might workaround the bug.

**Comment by nmorey** [comment]
@jsquyres Once again legacy reasons (that may be bad).
I copied a lot of what we do for openmpi 1.10. I need to dig into the changelogs to see if there was a bug that justified this.

**Comment by nmorey** [comment]
Apparently it was done due to some bug in gcc4. I'll drop this flag too

**Comment by jsquyres** [comment]
@nmorey Ok, great -- let us know how it goes.  We do have a bug to fix here, but hopefully by deleting some of these now-unnecessary flags for you, the issue goes away (i.e., the bug is a combination of flags that should rarely/never happen).

**Comment by nmorey** [comment]
@jsquyres Seems to compile OK now. Thanks

**Comment by jsquyres** [comment]
@nmorey Exxxccellent.  Thank you!

I'm going to rename this issue to more accurately describe the bug that still needs to be fixed, but I think it's probably a little lower priority.

**Comment by nmorey** [comment]
@jsquyres FYI, after some debugging I was able to remove the --disable-mca-dso option.
The bug was due to lib/openmpi/*.so being packaged in the openmpi-devel package and not available at runtime.

**Comment by rhc54** [comment]
We resolved this by no longer connecting devel-headers with installation of the standalone PMIx library.
