### ISSUE TITLE
Outdated README link

### ISSUE THREAD

**Issue by AntoineD** [open-mpi/ompi#4220]
This link points to the obsolete repo
https://github.com/open-mpi/ompi/blob/79f82f2c6da3910c45865bb543d53f34580fe6e4/README#L1439

**Comment by ggouaillardet** [comment]
thanks for the report, would you mind issuing a PR for that ?

**Comment by AntoineD** [comment]
Yes I will.

**Comment by jsquyres** [comment]
Fixed via #4221.
