### ISSUE TITLE
No PMIx shared lib when --enable-static is set

### ISSUE THREAD

**Issue by nmorey** [open-mpi/ompi#4238]
On v3.0.0

Building openmpi generate these files:
/usr/lib64/mpi/gcc/openmpi3/lib64/pmix/mca_pnet_opa.so
/usr/lib64/mpi/gcc/openmpi3/lib64/pmix/mca_psec_native.so
/usr/lib64/mpi/gcc/openmpi3/lib64/pmix/mca_psec_none.so
/usr/lib64/mpi/gcc/openmpi3/lib64/pmix/mca_psensor_file.so
/usr/lib64/mpi/gcc/openmpi3/lib64/pmix/mca_psensor_heartbeat.so
/usr/lib64/mpi/gcc/openmpi3/lib64/pmix/mca_ptl_tcp.so
/usr/lib64/mpi/gcc/openmpi3/lib64/pmix/mca_ptl_usock.so

If --enable-static is set (adding --enable-shared as no impact), these file are not generated anymore.
I would expect them to be present AND a static version.

During configure I see this which seems wrong
```
[  406s] checking if user requested PMI support... no
[  406s] checking which components should be disabled... 
[  406s] checking which components should be direct-linked into the library... 
[  406s] checking which components should be run-time loadable... none
[  406s] configure: WARNING: *** Shared libraries have been disabled (--disable-shared)
[  406s] configure: WARNING: *** Building MCA components as DSOs automatically disabled
[  406s] checking which components should be static... none
```

**Comment by jsquyres** [comment]
Those are all plugins (similar to the plugins in `$prefix/lib/openmpi`).

When you `--enable-static`, all plugins are slurped up into their respective libraries (i.e., they aren't standalone DSOs any more).  See the README: https://github.com/open-mpi/ompi/blob/master/README#L773-L777

**Comment by nmorey** [comment]
OK. Makes sense.
I did not notice that for the lib/openmpi as even in static mode, this one exists:
lib64/openmpi/libompi_dbg_msgq.so

**Comment by jsquyres** [comment]
Yes, `libompi_dbg_msgq.so` is a plugin for an external debugger (i.e., it adds Open MPI functionality to the Totalview and DDT debuggers -- it's not a plugin *for* Open MPI; it's a plugin *from* Open MPI).
