### ISSUE TITLE
Do not build CUDA support in hwloc when --without-cuda is specified

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#4248]
* Originally reported in #4219 
* Master PR to fix the issue: #4245 

Needs to be applied to v2.x and v3.0.x.  It *may* be desirable to also apply this to v2.0.x.  @jsquyres and @hppritcha will discuss.

**Comment by jsquyres** [comment]
@Mazay0 Thanks for reporting the original issue in #4219.  This issue is to track applying the fix to all the release branches.

**Comment by jsquyres** [comment]
See #4257 for a follow-on commit that could be added to all these PRs.

**Comment by hppritcha** [comment]
this fix has been back ported to all relevant branches. closing.
