### ISSUE TITLE
compiling ROMIO with PVFS2 support 

### ISSUE THREAD

**Issue by edgargabriel** [open-mpi/ompi#426]
compiling the ompi master and enabling PVFS2 support in ROMIO will lead to an error at compile time

adio/ad_pvfs2/ad_pvfs2_aio.c: In function 'ADIOI_PVFS2_AIO_contig':

adio/ad_pvfs2/ad_pvfs2_aio.c:126:6: error: implicit declaration of function 'PMPIX_Grequest_class_create' [-Werror=implicit-function-declaration]
      MPIX_Grequest_class_create(ADIOI_GEN_aio_query_fn,
      ^

adio/ad_pvfs2/ad_pvfs2_aio.c:131:2: error: implicit declaration of function 'PMPIX_Grequest_class_allocate' [-Werror=implicit-function-declaration]
  MPIX_Grequest_class_allocate(ADIOI_PVFS2_greq_class, aio_req, request);
  ^

Note, that Open MPI sets the --disable-aio flag when configuring ROMIO. My suspicion is that there is 
some protection through macros (HAVE_MPI_GREQUEST_EXTENSIONS or one of the AIO macros) is missing from this file, but not entirely sure.

@roblatham00 Any ideas/suggestions how to resolve that?

**Comment by roblatham00** [comment]
I thought we fixed this years ago?  Ah, wait, we set the function pointers
correctly last year, but we are probably still building the (unused) aio
routines.   I'll generate a pull request.

==rob

**Comment by hppritcha** [comment]
You mean a PR for romio not for ompi's romio component right?

**Comment by roblatham00** [comment]
ompi is all Edgar!  this is specifically for the ROMIO component.

On Wed, Feb 25, 2015 at 10:02 AM, Howard Pritchard <notifications@github.com

**Comment by roblatham00** [comment]
Oh, wait, I see what @hppritcha was asking.  nope, I made a commit to OpenMPI's ROMIO (which I will immediately apply to MPICH's ROMIO, too)
