### ISSUE TITLE
Disable Fortran (77 at least) in Romio

### ISSUE THREAD

**Issue by sjeaugey** [open-mpi/ompi#4281]
Open MPI has recently deprecated the use of the F77/FFLAGS environment variables (in favor of FC/FCFLAGS), but the ROMIO configure is still looking for F77. I don't think it is used in the end, but it would be cleaner to disable F77 in ROMIO (to avoid users being confused).

In fact, maybe we should disable Fortran completely in ROMIO, it seems to be only used to compile tests, not the library.

**Comment by ggouaillardet** [comment]
good idea, simply adding ```--disable-f77 --disable-f90``` to ```romio``` ```configure``` does the trick.
i will be issuing a PR sometimes today
