### ISSUE TITLE
loopback verbs connections: per adapter setting

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#43]
Most current iWARP devices (June 2008) cannot make connections between two processes on the same server.  As such, btl_openib.c has been set to mark all local peers on iWARP transports as "unreachable".  However, there is nothing in the iWARP spec that prevents loopback connections; it's an implementation decision.

The real solution is to add another parameter to the INI file that indicates whether a given adapter can handle loopback connections or not.  This is likely not too important to do until an iWARP NIC supports loopback connections or an IB NIC doesn't support loopback connections.

**Comment by awlauria** [comment]
Openib btl is removed. Closing.
