### ISSUE TITLE
Naming conflict for shmem_put/get in shmem-compat.h

### ISSUE THREAD

**Issue by BryantLam** [open-mpi/ompi#4307]
[shmem-compat.h is included after a compiler check for C11 support.](https://github.com/open-mpi/ompi/blob/3660cedc4871c21f2902db8634807cf4c30f1e57/oshmem/include/shmem.h.in#L51) OpenSHMEM 1.3 added type-generic `shmem_put` and `shmem_get` that are defined as macros [later in `shmem.h.in`](https://github.com/open-mpi/ompi/blob/3660cedc4871c21f2902db8634807cf4c30f1e57/oshmem/include/shmem.h.in#L208-L219) and subsequently conflict with the function declarations in [`shmem-compat.h`](https://github.com/open-mpi/ompi/blob/3660cedc4871c21f2902db8634807cf4c30f1e57/oshmem/include/shmem-compat.h#L39-L40).

One solution is to add a check in `shmem-compat.h` that checks for `OSHMEM_HAVE_C11` to prefer the C11 generics, but this provides an invisible breaking change to existing codes that erroneously depend on `shmem-compat.h`'s `shmem_put`. It would be better to get rid of the function declarations in `shmem-compat.h` now that it sufficiently conflicts with the OpenSHMEM specification.

**Comment by artpol84** [comment]
@karasevb please address

**Comment by artpol84** [comment]
Fixed by #4638
