### ISSUE TITLE
OSHMEM-Fortran : No available spml components were found!

### ISSUE THREAD

**Issue by ChinouneMehdi** [open-mpi/ompi#4390]
Open-MPI 3.0.0
Installed using SPACK.
* Operating system/version: Ubuntu 16.04
* Computer hardware: Intel Core i7
* Network type: Shared Memory

-----------------------------

## Details of the problem

This program run successfully with Open-MPI 2.1.1 

```fortran
program whoami

  implicit none
  include 'shmem.fh'

  integer :: shmem_n_pes, shmem_my_pe
  integer :: npes, me

  call shmem_init ()
  npes = shmem_n_pes ()
  me = shmem_my_pe ()

  write (*, "(A5, I4, A4, I4)") "I am ", me, " of ", npes

  call shmem_finalize()

end program whoami
```
```shell
shell$ oshfort hello.f90 -o hello
shell$ oshrun -n 4 ./hello
I am    1 of    4
I am    2 of    4
I am    3 of    4
I am    0 of    4
```
but with Open-MPI 3.0.0 it gives this error message:
```
No available spml components were found!

This means that there are no components of this type installed on your
system or all the components reported that they could not be used.

This is a fatal error; your SHMEM process is likely to abort.  Check the
output of the "ompi_info" command and ensure that components of this
type are available on your system.  You may also wish to check the
value of the "component_path" MCA parameter and ensure that it has at
least one directory that contains valid MCA components.
--------------------------------------------------------------------------
[DESKTOP-9J4RLOC:18534] SPML ikrit cannot be selected
[DESKTOP-9J4RLOC:18535] SPML ikrit cannot be selected
[DESKTOP-9J4RLOC:18536] SPML ikrit cannot be selected
[DESKTOP-9J4RLOC:18537] SPML ikrit cannot be selected
[DESKTOP-9J4RLOC:18529] 3 more processes have sent help message help-oshmem-memheap.txt / find-available:none-found
[DESKTOP-9J4RLOC:18529] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

**Comment by ChinouneMehdi** [comment]
Thank you for your support!

**Comment by jladd-mlnx** [comment]
@ChinouneMehdi Hi. In OMPI 3.x we removed the Yoda SPML. Please use the UCX SPML. In order to do so, you will need to install the UCX library. Once it's installed, please configure your OMPI with the `--with-ucx=/path/to/ucx` flag and rebuild. You can obtain a UCX release tarball from:
https://github.com/openucx/ucx/releases

**Comment by ChinouneMehdi** [comment]
To build ucx you need mpi. to build openmpi with ucx you need ucx ?!

**Comment by miked-mellanox** [comment]
No need mpi to build ucx,it is standalone lib on top of verbs.

**Comment by jladd-mlnx** [comment]
@ChinouneMehdi UCX is a stand alone point-to-point library. It supports Verbs, shared memory, and uGNI interconnect. Once it's installed, you can build Open MPI on top of UCX.

**Comment by ChinouneMehdi** [comment]
Could you update README file with these information. because I thought it does not support shared memory
>UCX currently supports:
> - OFA Verbs;
>  - Cray's uGNI;
 > - NVIDIA CUDA drivers.
there is no mention of shared memory.

**Comment by nicmcd** [comment]
I've having this same problem. I built ucx then built openmpi with ucx. I still get the same error. If I run "shmemrun ls" everything works. If I run "shmemrun myapp" it doesn't work. Why not? My program is just a simple shmem hello world. What is breaking?

**Comment by yosefe** [comment]
@nicmcd can you please attach full command line and output? 
Also, which OpenMPI branch/revision is being used (we made UCX the default just recently)?

**Comment by artpol84** [comment]
@nicmcd any progress on this?

**Comment by artpol84** [comment]
@ChinouneMehdi do you still observe the problem?

**Comment by ChinouneMehdi** [comment]
OpenMPI 3.1.0 Built using [spack](https://github.com/spack/spack)
```shell
spack install openmpi fabrics=ucx
```
the output : 
```shell
--------------------------------------------------------------------------
WARNING: Linux kernel CMA support was requested via the
btl_vader_single_copy_mechanism MCA variable, but CMA support is
not available due to restrictive ptrace settings.

The vader shared memory BTL will fall back on another single-copy
mechanism if one is available. This may result in lower performance.

  Local host: DESKTOP-9J4RLOC
--------------------------------------------------------------------------
[1528554886.680507] [DESKTOP-9J4RLOC:95   :0]         select.c:312  UCX  ERROR no remote registered memory access transport to <no debug data>: self/self - Destination is unreachable, tcp/eth1 - no put short, tcp/wifi0 - no put short, mm/sysv - Destination is unreachable, mm/posix - Destination is unreachable
[1528554886.680503] [DESKTOP-9J4RLOC:96   :0]         select.c:312  UCX  ERROR no remote registered memory access transport to <no debug data>: self/self - Destination is unreachable, tcp/eth1 - no put short, tcp/wifi0 - no put short, mm/sysv - Destination is unreachable, mm/posix - Destination is unreachable
[1528554886.680510] [DESKTOP-9J4RLOC:97   :0]         select.c:312  UCX  ERROR no remote registered memory access transport to <no debug data>: self/self - Destination is unreachable, tcp/eth1 - no put short, tcp/wifi0 - no put short, mm/sysv - Destination is unreachable, mm/posix - Destination is unreachable
[1528554886.680503] [DESKTOP-9J4RLOC:98   :0]         select.c:312  UCX  ERROR no remote registered memory access transport to <no debug data>: self/self - Destination is unreachable, tcp/eth1 - no put short, tcp/wifi0 - no put short, mm/sysv - Destination is unreachable, mm/posix - Destination is unreachable
--------------------------------------------------------------------------
It looks like SHMEM_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during SHMEM_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open SHMEM
developer):

  SPML add procs failed
  --> Returned "Out of resource" (-2) instead of "Success" (0)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
SHMEM_ABORT was invoked on rank 1 (pid 96, host=DESKTOP-9J4RLOC) with errorcode -1.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A SHMEM process is aborting at a time when it cannot guarantee that all
of its peer processes in the job will be killed properly.  You should
double check that everything has shut down cleanly.

Local host: DESKTOP-9J4RLOC
PID:        96
--------------------------------------------------------------------------
[DESKTOP-9J4RLOC:00095] Error spml_ucx.c:293 - mca_spml_ucx_add_procs() ucp_ep_create failed: Destination is unreachable
[DESKTOP-9J4RLOC:00095] Error spml_ucx.c:326 - mca_spml_ucx_add_procs() add procs FAILED rc=-2
[DESKTOP-9J4RLOC:00096] Error spml_ucx.c:293 - mca_spml_ucx_add_procs() ucp_ep_create failed: Destination is unreachable
[DESKTOP-9J4RLOC:00096] Error spml_ucx.c:326 - mca_spml_ucx_add_procs() add procs FAILED rc=-2
[DESKTOP-9J4RLOC:00097] Error spml_ucx.c:293 - mca_spml_ucx_add_procs() ucp_ep_create failed: Destination is unreachable
[DESKTOP-9J4RLOC:00097] Error spml_ucx.c:326 - mca_spml_ucx_add_procs() add procs FAILED rc=-2
[DESKTOP-9J4RLOC:00098] Error spml_ucx.c:293 - mca_spml_ucx_add_procs() ucp_ep_create failed: Destination is unreachable
[DESKTOP-9J4RLOC:00098] Error spml_ucx.c:326 - mca_spml_ucx_add_procs() add procs FAILED rc=-2
[DESKTOP-9J4RLOC:00095] Error: pshmem_init.c:73 - _shmem_init() SHMEM failed to initialize - aborting
[DESKTOP-9J4RLOC:00096] Error: pshmem_init.c:73 - _shmem_init() SHMEM failed to initialize - aborting
[DESKTOP-9J4RLOC:00097] Error: pshmem_init.c:73 - _shmem_init() SHMEM failed to initialize - aborting
[DESKTOP-9J4RLOC:00098] Error: pshmem_init.c:73 - _shmem_init() SHMEM failed to initialize - aborting
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
oshrun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[33845,1],0]
  Exit code:    255
--------------------------------------------------------------------------
[DESKTOP-9J4RLOC:00090] 3 more processes have sent help message help-btl-vader.txt / cma-permission-denied
[DESKTOP-9J4RLOC:00090] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[DESKTOP-9J4RLOC:00090] 3 more processes have sent help message help-shmem-runtime.txt / shmem_init:startup:internal-failure
[DESKTOP-9J4RLOC:00090] 3 more processes have sent help message help-shmem-api.txt / shmem-abort
[DESKTOP-9J4RLOC:00090] 3 more processes have sent help message help-shmem-runtime.txt / oshmem shmem abort:cannot guarantee all killed
```

**Comment by jladd-mlnx** [comment]
Hi,

In the 3.x series we removed the Yoda SPML, which means that UCX is now the
default SPML. If you do not have an InfiniBand device on your setup, then
you will need to install XPMEM (https://github.com/hjelmn/xpmem) in order
to run OpenSHMEM applications over the UCX shared memory TL.

Best,

Josh

**Comment by nicmcd** [comment]
@artpol84 First I installed openmpi but it gave me the "No available spml components were found!" error. I then followed your advice about using UCX, but then I get the following:

You can see oshrun uptime works, oshrun on my hello world app with one PE works, but it fails with my hello world and two PEs. 

FYI: this is only on a single machine attempting to use only shared memory.

`nic@super820:~/hello_shmem$ oshrun -n 2 uptime
 10:38:34 up 21 days, 19:16, 12 users,  load average: 0.08, 0.28, 0.52
 10:38:34 up 21 days, 19:16, 12 users,  load average: 0.08, 0.28, 0.52
nic@super820:~/hello_shmem$ oshrun -n 1 hello
 0 of 1 on super820
nic@super820:~/hello_shmem$ oshrun -n 2 hello
  *** Error in `hello': double free or corruption (!prev): 0x00000000015c8450 ***
  *** Error in `hello': double free or corruption (!prev): 0x0000000000883490 ***
  [1532450323.354998] [super820:14663:0]         select.c:312  UCX  ERROR no remote registered memory access transport to <no debug data>: self/self - Destination is unreachable, tcp/eno1 - no put short, mm/sysv - Destination is unreachable, mm/posix - Destination is unreachable, cma/cma - no put short
  [1532450323.354998] [super820:14664:0]         select.c:312  UCX  ERROR no remote registered memory access transport to <no debug data>: self/self - Destination is unreachable, tcp/eno1 - no put short, mm/sysv - Destination is unreachable, mm/posix - Destination is unreachable, cma/cma - no put short
  [super820:14663] Error spml_ucx.c:293 - mca_spml_ucx_add_procs() ucp_ep_create(proc=1/2) failed: Destination is unreachable
  [super820:14664] Error spml_ucx.c:293 - mca_spml_ucx_add_procs() ucp_ep_create(proc=1/2) failed: Destination is unreachable
  ======= Backtrace: =========
  ======= Backtrace: =========
  /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f70b0ae27e5]
  /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fcae7c787e5]
  /lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f70b0aeb37a]
  /lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fcae7c8137a]
  /lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f70b0aef53c]
  /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_spml_ucx.so(mca_spml_ucx_add_procs+0x336)[0x7f709edeeaa6]
  /lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fcae7c8553c]
  /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_spml_ucx.so(mca_spml_ucx_add_procs+0x336)[0x7fcad5f8daa6]
  /home/nic/openmpi/openmpi-3.1.1-bin/lib/liboshmem.so.40(oshmem_shmem_init+0x23f)[0x7fcae8204d4f]
  /home/nic/openmpi/openmpi-3.1.1-bin/lib/liboshmem.so.40(pshmem_init+0x48)[0x7fcae82077e8]
  hello[0x4008e2]
  00400000-00401000 r-xp 00000000 08:02 38668385                           /home/nic/hello_shmem/hello
  00600000-00601000 r--p 00000000 08:02 38668385                           /home/nic/hello_shmem/hello
  00601000-00602000 rw-p 00001000 08:02 38668385                           /home/nic/hello_shmem/hello
  01458000-01685000 rw-p 00000000 00:00 0                                  [heap]
  7f7094000000-7f7094021000 rw-p 00000000 00:00 0
  7f7094021000-7f7098000000 ---p 00000000 00:00 0
  7f709ba88000-7f709ba9e000 r-xp 00000000 08:02 25956731                   /lib/x86_64-linux-gnu/libgcc_s.so.1
  7f709ba9e000-7f709bc9d000 ---p 00016000 08:02 25956731                   /lib/x86_64-linux-gnu/libgcc_s.so.1
  7f709bc9d000-7f709bc9e000 rw-p 00015000 08:02 25956731                   /lib/x86_64-linux-gnu/libgcc_s.so.1
  7f709bc9e000-7f709bda3000 rw-s 00000000 00:15 58                         /dev/shm/ucx_posix_mm__super820_1584bddbfb20eb9e (deleted)
  7f709bda3000-7f709bdae000 r-xp 00000000 08:02 25952537                   /lib/x86_64-linux-gnu/libnss_files-2.23.so
  7f709bdae000-7f709bfad000 ---p 0000b000 08:02 25952537                   /lib/x86_64-linux-gnu/libnss_files-2.23.so
  7f709bfad000-7f709bfae000 r--p 0000a000 08:02 25952537                   /lib/x86_64-linux-gnu/libnss_files-2.23.so
  7f709bfae000-7f709bfaf000 rw-p 0000b000 08:02 25952537                   /lib/x86_64-linux-gnu/libnss_files-2.23.so
  7f709bfaf000-7f709bfb5000 rw-p 00000000 00:00 0
  7f709bfb5000-7f709bfc0000 r-xp 00000000 08:02 25952544                   /lib/x86_64-linux-gnu/libnss_nis-2.23.so
  7f709bfc0000-7f709c1bf000 ---p 0000b000 08:02 25952544                   /lib/x86_64-linux-gnu/libnss_nis-2.23.so
  7f709c1bf000-7f709c1c0000 r--p 0000a000 08:02 25952544                   /lib/x86_64-linux-gnu/libnss_nis-2.23.so
  7f709c1c0000-7f709c1c1000 rw-p 0000b000 08:02 25952544                   /lib/x86_64-linux-gnu/libnss_nis-2.23.so
  7f709c1c1000-7f709c1d7000 r-xp 00000000 08:02 25952447                   /lib/x86_64-linux-gnu/libnsl-2.23.so
  7f709c1d7000-7f709c3d6000 ---p 00016000 08:02 25952447                   /lib/x86_64-linux-gnu/libnsl-2.23.so
  7f709c3d6000-7f709c3d7000 r--p 00015000 08:02 25952447                   /lib/x86_64-linux-gnu/libnsl-2.23.so
  7f709c3d7000-7f709c3d8000 rw-p 00016000 08:02 25952447                   /lib/x86_64-linux-gnu/libnsl-2.23.so
  7f709c3d8000-7f709c3da000 rw-p 00000000 00:00 0
  7f709c3da000-7f709c3e2000 r-xp 00000000 08:02 25952522                   /lib/x86_64-linux-gnu/libnss_compat-2.23.so
  7f709c3e2000-7f709c5e1000 ---p 00008000 08:02 25952522                   /lib/x86_64-linux-gnu/libnss_compat-2.23.so
  7f709c5e1000-7f709c5e2000 r--p 00007000 08:02 25952522                   /lib/x86_64-linux-gnu/libnss_compat-2.23.so
  7f709c5e2000-7f709c5e3000 rw-p 00008000 08:02 25952522                   /lib/x86_64-linux-gnu/libnss_compat-2.23.so
  7f709c5e3000-7f709c5e4000 ---p 00000000 00:00 0
  7f709c5e4000-7f709cde4000 rw-p 00000000 00:00 0
  7f709cde4000-7f709cdf3000 r-xp 00000000 08:02 42470124                   /home/nic/openmpi/openmpi-3.1.1-bin[super820:14663] *** Process received signal ***
  [super820:14663] Signal: Aborted (6)
  [super820:14663] Signal code:  (-6)
  /lib/openmpi/mca_osc_ucx.so
  7f709cdf3000-7f709cff2000 ---p 0000f000 08:02 42470124                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_ucx.so
  7f709cff2000-7f709cff3000 r--p 0000e000 08:02 42470124                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_ucx.so
  7f709cff3000-7f709cffc000 rw-p 0000f000 08:02 42470124                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_ucx.so
  7f709cffc000-7f709d002000 r-xp 00000000 08:02 42470111                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_sm.so
  7f709d002000-7f709d201000 ---p 00006000 08:02 42470111                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_sm.so
  7f709d201000-7f709d202000 r--p 00005000 08:02 42470111                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_sm.so
  7f709d202000-7f709d204000 rw-p 00006000 08:02 42470111                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_sm.so
  7f709d204000-7f709d220000 r-xp 00000000 08:02 42470118                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_pt2pt.so
  7f709d220000-7f709d420000 ---p 0001c000 08:02 42470118                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_pt2pt.so
  7f709d420000-7f709d421000 r--p 0001c000 08:02 42470118                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_pt2pt.so
  7f709d421000-7f709d422000 rw-p 0001d000 08:02 42470118                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_pt2pt.so
  7f709d529000-7f709d62e000 rw-s 00000000 00:15 87                         /dev/shm/ucx_posix_mm__super820_007ce194ccc53dc6 (deleted)
  7f709d62e000-7f709d65e000 r-xp 00000000 08:02 42470121                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_rdma.so
  7f709d65e000-7f709d85d000 ---p 00030000 08:02 42470121                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_rdma.so
  7f709d85d000-7f709d85e000 r--p 0002f000 08:02 42470121                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/o[super820:14663] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7fcae7fdc390]
  [super820:14663] [ 1] penmpi/mca_osc_rdma.so
  7f709d85e000-7f709d85f000 rw-p 00030000 08:02 42470121                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_osc_rdma.so
  7f709d85f000-7f709d87d000 r-xp 00000000 08:02 42470061                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_libnbc.so
  7f709d87d000-7f709da7d000 ---p 0001e000 08:02 42470061                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_libnbc.so
  7f709da7d000-7f709da7e000 r--p 0001e000 08:02 42470061                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_libnbc.so
  7f709da7e000-7f709da7f000 rw-p 0001f000 08:02 42470061                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_libnbc.so
  7f709da7f000-7f709da81000 r-xp 00000000 08:02 42470064                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_self.so
  7f709da81000-7f709dc81000 ---p 00002000 08:02 42470064                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_self.so
  7f709dc81000-7f709dc82000 r-/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7fcae7c36428]
  [super820:14663] [ 2] -p 00002000 08:02 42470064                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_self.so
  7f709dc82000-7f709dc83000 rw-p 00003000 08:02 42470064                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_self.so
  7f709dc88000-7f709dc91000 r-xp 00000000 08:02 42470445                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_scoll_basic.so
  7f709dc91000-7f709de90000 ---p 00009000 08:02 42470445                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_scoll_basic.so
  7f709de90000-7f709de91000 r--p 00008000 08:02 42470445                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_scoll_basic.so
  7f709de91000-7f709de92000 rw-p 00009000 08:02 42470445                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_scoll_basic.so
  7f709de92000-7f709de9f000 r-xp 00000000 08:02 42470055                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_basic.so
  7f709de9f000-7f709e09f000 ---p 0000d000 08:02 42470055                   /hom/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7fcae7c3802a]
  [super820:14663] [ 3] e/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_basic.so
  7f709e09f000-7f709e0a0000 r--p 0000d000 08:02 42470055                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_basic.so
  7f709e0a0000-7f709e0a1000 rw-p 0000e000 08:02 42470055                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_basic.so
  7f709e0a1000-7f709e0a5000 r-xp 00000000 08:02 42470058                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_inter.so
  7f709e0a5000-7f709e2a4000 ---p 00004000 08:02 42470058                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_inter.so
  7f709e2a4000-7f709e2a5000 r--p 00003000 08:02 42470058                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_inter.so
  7f709e2a5000-7f709e2a6000 rw-p 00004000 08:02 42470058                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_inter.so
  7f709e2a6000-7f709e2a8000 r-xp 00000000 08:02 42469196                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/libmca_common_s/lib/x86_64-linux-gnu/libc.so.6(+0x777ea)[0x7fcae7c787ea]
  [super820:14663] [ 4] m.so.40.10.0
  7f709e2a8000-7f709e4a7000 ---p 00002000 08:02 42469196                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/libmca_common_sm.so.40.10.0
  7f709e4a7000-7f709e4a8000 r--p 00001000 08:02 42469196                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/libmca_common_sm.so.40.10.0
  7f709e4a8000-7f709e4a9000 rw-p 00002000 08:02 42469196                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/libmca_common_sm.so.40.10.0
  7f709e4a9000-7f709e4af000 r-xp 00000000 08:02 42470068                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_sm.so
  7f709e4af000-7f709e6ae000 ---p 00006000 08:02 42470068                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_sm.so
  7f709e6ae000-7f709e6af000 r--p 00005000 08:02 42470068                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_sm.so
  7f709e6af000-7f709e6b0000 rw-p 00006000 08:02 42470068                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_sm.so
  7f709e6b0000-7f709e6b3000 r-xp 00000000 08:0/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fcae7c8137a]
  [super820:14663] [ 5] 2 42470075                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_sync.so
  7f709e6b3000-7f709e8b2000 ---p 00003000 08:02 42470075                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_sync.so
  7f709e8b2000-7f709e8b3000 r--p 00002000 08:02 42470075                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_sync.so
  7f709e8b3000-7f709e8b4000 rw-p 00003000 08:02 42470075                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_sync.so
  7f709e8b4000-7f709e8c3000 r-xp 00000000 08:02 42470078                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_tuned.so
  7f709e8c3000-7f709eac2000 ---p 0000f000 08:02 42470078                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_tuned.so
  7f709eac2000-7f709eac3000 r--p 0000e000 08:02 42470078                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_coll_tuned.so
  7f709eac3000-7f709eac4000 rw-p 0000f000 08:02 42470078                   /home/nic/openmpi/openmpi-/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fcae7c8553c]
  [super820:14663] [ 6] /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_spml_ucx.so(mca_spml_ucx_add_procs+0x336)[0x7fcad5f8daa6]
  [super820:14663] [ 7] 3.1.1-bin/lib/openmpi/mca_coll_tuned.so
  7f709eae2000-7f709ebe7000 rw-s 00000000 00:05 16318486                   /SYSV00000000 (deleted)
  7f709ebe7000-7f709ebeb000 r-xp 00000000 08:02 42470449                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_scoll_mpi.so
  7f709ebeb000-7f709edea000 ---p 00004000 08:02 42470449                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_scoll_mpi.so
  7f709edea000-7f709edeb000 r--p 00003000 08:02 42470449                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_scoll_mpi.so
  7f709edeb000-7f709edec000 rw-p 00004000 08:02 42470449                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_scoll_mpi.so
  7f709edec000-7f709edf1000 r-xp 00000000 08:02 42470452                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_spml_ucx.so
  7f709edf1000-7f709eff0000 ---p 00005000 08:02 42470452                   /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_spml_ucx.so
  7f709eff0000-7f709eff1000 r--p 00004000 08:02 42470452       /home/nic/openmpi/openmpi-3.1.1-bin/lib/liboshmem.so.40(oshmem_shmem_init+0x23f)[0x7fcae8204d4f]
  [super820:14663] [ 8] /home/nic/openmpi/openmpi-3.1.1-bin/lib/liboshmem.so.40(pshmem_init+0x48)[0x7fcae82077e8]
  [super820:14663] [ 9] hello[0x4008e2]
  [super820:14663] [10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fcae7c21830]
  [super820:14663] [11] hello[0x4007e9]
  [super820:14663] *** End of error message ***
  [super820:14664] *** Process received signal ***
  [super820:14664] Signal: Aborted (6)
  [super820:14664] Signal code:  (-6)
  [super820:14664] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f70b0e46390]
  [super820:14664] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f70b0aa0428]
  [super820:14664] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f70b0aa202a]
  [super820:14664] [ 3] /lib/x86_64-linux-gnu/libc.so.6(+0x777ea)[0x7f70b0ae27ea]
  [super820:14664] [ 4] /lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f70b0aeb37a]
  [super820:14664] [ 5] /lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f70b0aef53c]
  [super820:14664] [ 6] /home/nic/openmpi/openmpi-3.1.1-bin/lib/openmpi/mca_spml_ucx.so(mca_spml_ucx_add_procs+0x336)[0x7f709edeeaa6]
  [super820:14664] [ 7] /home/nic/openmpi/openmpi-3.1.1-bin/lib/liboshmem.so.40(oshmem_shmem_init+0x23f)[0x7f70b106ed4f]
  [super820:14664] [ 8] /home/nic/openmpi/openmpi-3.1.1-bin/lib/liboshmem.so.40(pshmem_init+0x48)[0x7f70b10717e8]
  [super820:14664] [ 9] hello[0x4008e2]
  [super820:14664] [10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f70b0a8b830]
  [super820:14664] [11] hello[0x4007e9]
  [super820:14664] *** End of error message ***
  -------------------------------------------------------
  Primary job  terminated normally, but 1 process returned
  a non-zero exit code. Per user-direction, the job has been aborted.
  -------------------------------------------------------
  --------------------------------------------------------------------------
  oshrun noticed that process rank 0 with PID 0 on node super820 exited on signal 6 (Aborted).
  --------------------------------------------------------------------------
  `

**Comment by jsquyres** [comment]
@nicmcd A double free error seems to be different than the originally-reported "no components found" issue.  Can you please re-file this as a new issue?
