### ISSUE TITLE
BTLs progress should progress up to one real message

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#44]
The SM BTL component progress currently progresses only one message per connection even if the message is really a control message (in this case an ACK message).  The negative impact of this is if a program does an MPI_Iprobe it will end up doing multiple MPI_Iprobes  when in theory for certain cases it really should only need to do one MPI_Iprobe.

So for the SM BTL component progress I propose draining all control messages until we've either hit an empty fifo or a "real" message.

The other BTLs will need to be investigated to make sure they adhere to similar rules otherwise you would end up with inconsistent results depending on the BTL you are using.

**Comment by thananon** [comment]
2014, sm btl. wow.
