### ISSUE TITLE
file corruption with MPI I/O from NetCDF fortran interface

### ISSUE THREAD

**Issue by koomie** [open-mpi/ompi#4404]
## Background information

Over in OpenHPC land, we have encountered a regression with parallel I/O using the NetCDF fortran interface and OpenMPI. This is new with testing of v3.0.0 (v1.10.7 did not exhibit).  In particular, we are seeing file corruption doing a simple write test (e.g. using https://raw.githubusercontent.com/Unidata/netcdf-fortran/master/nf_test/f90tst_parallel.f90) when using `ompio` which is the new default. If we override the default to revert back to `romio314` all is groovy.  We can easily just use romio for our CI environment, but wanted to report in case it is useful.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

* OpenMPI: v3.0.0
* netCDF: v4.4.1.1
* netcdf-fortran: v4.4.4
* pHDF5: v1.10.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Built as RPM starting from release tarball. Build collateral for ompi is here:

https://build.openhpc.community/package/show/OpenHPC:1.3:Update3:Factory/openmpi-gnu

### Please describe the system on which you are running

* Operating system/version: CentOS 7.4
* Computer hardware: x86_64 (Broadwell)
* Network type: multiple - ethernet, FDR InfiniBand, and OPA

**Comment by edgargabriel** [comment]
Thanks for the bug report, I will have a look at it. What file system was that on?

**Comment by koomie** [comment]
This is running multi-node out of an NFS file system. Apologies if this is a duplicate of #4334, but it might be worth mentioning that all of our other parallel I/O related tests seem to work ok in this same NFS environment. (e.g C interface was ok).

**Comment by edgargabriel** [comment]
this was my original suspicion , but I will definitely have a look at it. I ran a while back the pnetcdf tests on my local development machine, and we didn't have any problems if I remember right.

**Comment by koomie** [comment]
thx, i can reproduce pretty easily so happy to try applying a patch locally if it is helpful.

**Comment by edgargabriel** [comment]
I am fairly confident that this is in fact also an NFS locking problem. All fortran-netcdf tests pass on my local development platform as well as on the cluster over NFS when using the new fix that will be in the 3.0.1 release. If I disable locking (basically the behavior of ompio in the 2.0.x, 2.1.x and 3.0.0 release), the tests fail.
~> salloc -N 4 -n 4
~> mpirun -np 4 ./f90tst_parallel 
   *** Testing netCDF-4 parallel I/O from Fortran 90.
 *** SUCCESS!

 abriel@crill:~/netcdf-fortran-4.4.4/nf_test> mpirun --mca fs_ufs_lock_algorithm 1 -np 4 ./f90tst_parallel 
   *** Testing netCDF-4 parallel I/O from Fortran 90.
 Error: NetCDF: HDF error
STOP 2
 Error: NetCDF: HDF error
STOP 2
STOP 2
 Error: NetCDF: HDF error
STOP 2
 Error: NetCDF: HDF error
HDF5: infinite loop closing library

Not sure if you have a chance to test the current 3.0.1 branch (which has not yet been released ) to confirm my findings.
