### ISSUE TITLE
Open nonexisting file, expect MPI_ERR_NO_SUCH_FILE but got MPI_ERR_FILE

### ISSUE THREAD

**Issue by wkliao** [open-mpi/ompi#4412]
When opening a non-existing file, error class MPI_ERR_NO_SUCH_FILE is expected but I got MPI_ERR_FILE instead. Looking into the source file fs_ufs_file_open.c lines 88 to 91, I found errno was ignored.
https://github.com/open-mpi/ompi/blob/ae4f310c0b59b76278df81c78f4a1beaadb764a6/ompi/mca/fs/ufs/fs_ufs_file_open.c#L88

In ROMIO, the translation of errno to proper MPI error classes has been handled correctly, where ADIOI_Err_create_code is doing the translation. See https://github.com/open-mpi/ompi/blob/ae4f310c0b59b76278df81c78f4a1beaadb764a6/ompi/mca/io/romio314/romio/adio/ad_ufs/ad_ufs_open.c#L54

Here is a short test program to reproduce.

```
#include <stdio.h>
#include <unistd.h> /* unlink() */
#include <mpi.h>

int main(int argc, char **argv)
{
    int err, errorclass, errorStringLen;
    char *filename="tooth_fairy", errorString[MPI_MAX_ERROR_STRING];
    MPI_File fh;

    MPI_Init(&argc,&argv);

    unlink(filename); /* delete file and ignore error */

    err = MPI_File_open(MPI_COMM_WORLD, filename, MPI_MODE_RDONLY,
                       MPI_INFO_NULL, &fh);
    if (err != MPI_SUCCESS) {
        MPI_Error_class(err, &errorclass);
        if (errorclass != MPI_ERR_NO_SUCH_FILE) {
            MPI_Error_string(err, errorString, &errorStringLen);
            printf("MPI_File_open expects MPI_ERR_NO_SUCH_FILE but got %s\n",
                   errorString);
        }
    }

    MPI_Finalize();
    return 0;
}
```

**Comment by edgargabriel** [comment]
yes, admittedly the error codes reported by ompio are not yet as good as 
it could be, not just for file_open. I can fix file_open easily if this 
is important for your code, an overhaul of the error codes handling 
ompio might take however a bit longer.

Nevertheless, one question out of curiosity: do you handle in your code 
the scenario where a File_open failed truly differently depending on the 
error code returned?   In my opinion, if the File_open fails for reading 
an input file, you will have to abort the application anyway, 
independent of whether you mistyped the name, name was too long, or you 
don't have permission to access that file. Most codes that I have worked 
with check only for the error code being MPI_SUCCESS vs. anything else.

Thanks
Edgar

**Comment by wkliao** [comment]
I wonder why my test program does not go through the romio route in ompi/ompi/mca/io/romio314, but through ompi/ompi/mca/fs. One easy fix might be to force to use romio route.

I agree with you about the behavior for applications when file open fails.
But I am a PnetCDF library developer. The library needs to report the errors that describe the cause as much as it can. We leave users to decide whether to stop the program or not. PnetCDF has an error code corresponding to ENOENT.

**Comment by edgargabriel** [comment]
On 10/27/2017 3:05 PM, Wei-keng Liao wrote:

> I wonder why my test program does not go through the romio route in 
> ompi/ompi/mca/io/romio314, but through ompi/ompi/mca/fs. One easy fix 
> might be to force to use romio route.
>
the default mpi I/O module since Open MPI 2.0.0 is ompio for most file 
systems, with Lustre being the exception. And yes, you can force using 
romio by setting the e.g.

mpirun --mca io romio314 ....

on the command line (or the same parameter in .openmpi/mca-params.conf 
file).

> I agree with you about the behavior for applications when file open fails.
> But I am a PnetCDF library developer. The library needs to report the 
> errors that describe the cause as much as it can. We leave users to 
> decide whether to stop the program or not. PnetCDF has an error code 
> corresponding to ENOENT.
>
understood. I will create a patch for fs/ufs to return the correct error 
codes. Note however that there is a similar issue in the fbtl/posix 
component for the preadv/pwritev calls, and fixing that one is bit more 
involved, I do not have the time right now to rework that part of the code.

**Comment by wkliao** [comment]
Thanks for the tip. That trick works fine with me. I will add a note in PnetCDF.

Since you mention ompio module, is ompio a completely different MPI-IO implementation from ROMIO? And does OpenMPI intend to replace romio with it in the future?

**Comment by ggouaillardet** [comment]
Open MPI has a modular architecture, and several components can implement the same framework.
In this case, the framework is `io` and the `romio314` and `ompio` components can implement it.
`ompio` and `romio314` are very different implementations of the same framework.
When `ompio` is production ready for the Lustre filesystem, it is likely it will become the default component for the `io` framework, regardless the filesystem.

That being said, i do not think we plan to get rid of the `romio314` (or an other component based on a more recent version of MPICH ROM-IO), so end users should always have two options.
So the answer to your question is no, strictly speaking, `ompio` will not replace the MPICH ROM-IO  based component.

**Comment by edgargabriel** [comment]
Issue has been already fixed.
