### ISSUE TITLE
Configure can't continue

### ISSUE THREAD

**Issue by kalravibhor** [open-mpi/ompi#4417]
Hi,

I am trying to compile dSP5.1 and in an effort to do the same, I need to install open-mpi on a OS X 10.12 system. Unfortunately, I run into a lot of errors while trying to install open-mpi via brew and hence follow the instructions on the below mentioned tutorial:

https://wiki.helsinki.fi/display/HUGG/Open+MPI+install+on+Mac+OS+X

I am working with open-mpi ver.2.2. However I am unable to complete the configuration process. I wanted to ensure that I don't link the library with clang because of which I had already faced a tonne of issues. Below is the configure command that I ran after changing my directory to the extracted openmpi directory.

`./configure CC=gcc-6 CXX=g++-6 --prefix=/usr/local`

`configure: WARNING: Your compiler does not support offsetof macro
configure: error: Configure: Cannot continue`

Looking forward to helping responses from experts on the forum. Thanks in advance.

**Comment by ggouaillardet** [comment]
there is on Open MPI 2.2 ...
can you please clarify which version you are using, then compress and upload your config.log
did you face issues with Open MPI and clang ?

**Comment by kalravibhor** [comment]
@ggouaillardet : Apologies, I am on ver.2.1.2. I have attached the config.log file in lieu of the fact that the message becomes too long to post. Since the movement of openmp support with clang to llvm, I tried following instructions on multiple forums and official blogs to install and have always run into multiple errors. 

[config.log](https://github.com/open-mpi/ompi/files/1426210/config.log)

Waiting to hear your thoughts on this. Thanks !

**Comment by ggouaillardet** [comment]
that is odd, `gcc-6` is unable to compile this simple program
```c
#include <stddef.h>
int main() {
    struct foo { int a, b;};
    size_t offset = offsetof(struct foo, b);
    return 0;
}
```

can you try to compile it with both `clang` and `gcc-6` ?
```
gcc -c conftest.c
gcc-6 -c conftest.c
```

then can you
```
gcc-6 -E conftest.c
```
and post the output ?


fwiw, i am unable to reproduce this on OS X 10.13 with `gcc-7` from `home-brew`

**Comment by kalravibhor** [comment]
Even I have the homebrew version of gcc-6 installed. Turns out both gcc and gcc-6 are able to compile the program. Below is the output for `gcc-6 -R conftest.c`

# 1 "conftest.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "conftest.c"
# 1 "/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h" 1 3 4
# 149 "/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h" 3 4

# 149 "/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h" 3 4
typedef long int ptrdiff_t;
# 216 "/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h" 3 4
typedef long unsigned int size_t;
# 328 "/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h" 3 4
typedef int wchar_t;
# 426 "/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h" 3 4
typedef struct {
  long long __max_align_ll __attribute__((__aligned__(__alignof__(long long))));
  long double __max_align_ld __attribute__((__aligned__(__alignof__(long double))));
} max_align_t;
# 2 "conftest.c" 2


# 3 "conftest.c"
int main() {
    struct foo { int a, b;};
    size_t offset =
# 5 "conftest.c" 3 4
                   __builtin_offsetof (
# 5 "conftest.c"
                   struct foo
# 5 "conftest.c" 3 4
                   ,
# 5 "conftest.c"
                   b
# 5 "conftest.c" 3 4
                   )
# 5 "conftest.c"
                                          ;
    return 0;
}

**Comment by kalravibhor** [comment]
Even I have the homebrew version of gcc-6 installed. Turns out both gcc and gcc-6 are able to compile the program. Below is the output for gcc-6 -R conftest.c

# 1 "conftest.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "conftest.c"
# 1 "/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h" 1 3 4
# 149 "/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h" 3 4

# 149 "/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h" 3 4
typedef long int ptrdiff_t;
# 216 "/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h" 3 4
typedef long unsigned int size_t;
# 328 "/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h" 3 4
typedef int wchar_t;
# 426 "/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h" 3 4
typedef struct {
  long long __max_align_ll __attribute__((__aligned__(__alignof__(long long))));
  long double __max_align_ld __attribute__((__aligned__(__alignof__(long double))));
} max_align_t;
# 2 "conftest.c" 2


# 3 "conftest.c"
int main() {
    struct foo { int a, b;};
    size_t offset =
# 5 "conftest.c" 3 4
                   __builtin_offsetof (
# 5 "conftest.c"
                   struct foo
# 5 "conftest.c" 3 4
                   ,
# 5 "conftest.c"
                   b
# 5 "conftest.c" 3 4
                   )
# 5 "conftest.c"
                                          ;
    return 0;
}

**Comment by ggouaillardet** [comment]
there is likely something busted in your environment.


would you mind trying again
```
gcc-6 -c -O3 -DNDEBUG -finline-functions -fno-strict-aliasing  conftest.c
```

and if it works, try to run `configure` again ?


here is the error message from your `config.log` related to this part, it mentions `llvm` though the preprocessed files you posted earlier clearly refers `gcc-6` from `home-brew`

```
configure:18544: checking for functional offsetof macro
configure:18557: gcc-6 -c -O3 -DNDEBUG -finline-functions -fno-strict-aliasing  conftest.c >&5
In file included from conftest.c:171:0:
/usr/local/Cellar/llvm/5.0.0/lib/clang/5.0.0/include/stddef.h:34:19: error: missing binary operator before token "("
 #if !__has_feature(modules)
                   ^
/usr/local/Cellar/llvm/5.0.0/lib/clang/5.0.0/include/stddef.h:46:42: error: missing binary operator before token "("
 #if !defined(_PTRDIFF_T) || __has_feature(modules)
                                          ^
/usr/local/Cellar/llvm/5.0.0/lib/clang/5.0.0/include/stddef.h:57:39: error: missing binary operator before token "("
 #if !defined(_SIZE_T) || __has_feature(modules)
                                       ^
/usr/local/Cellar/llvm/5.0.0/lib/clang/5.0.0/include/stddef.h:71:42: error: missing binary operator before token "("
      !defined(_RSIZE_T)) || __has_feature(modules)
                                          ^
/usr/local/Cellar/llvm/5.0.0/lib/clang/5.0.0/include/stddef.h:83:40: error: missing binary operator before token "("
 #if !defined(_WCHAR_T) || __has_feature(modules)
                                        ^
conftest.c: In function 'main':
conftest.c:175:25: error: unknown type name 'size_t'
 struct foo {int a, b;}; size_t offset = offsetof(struct foo, b);
                         ^~~~~~
```

**Comment by kalravibhor** [comment]
`gcc-6 -c -O3 -DNDEBUG -finline-functions -fno-strict-aliasing  conftest.c` worked like a charm. However on trying to configure again, it leads to the same error.

`checking for weak symbol support... no
checking for macro weak symbol support... no
checking for functional offsetof macro... no
configure: WARNING: Your compiler does not support offsetof macro
configure: error: Configure: Cannot continue`

In light of problems in my environment, it would be great if you could suggest how to pursue a fresh install which is guaranteed to work. Thanks !

**Comment by ggouaillardet** [comment]
I cannot make any sense from this error ! Try uninstalling homebrew clang compilers and see if it helps.

**Comment by jsquyres** [comment]
Are you sure that the `gcc-6` you're using to manually compile your test programs is the same `gcc-6` that `configure` is using?  I ask for 2 reasons:

1. The error messages cite `/usr/local/Cellar/llvm/5.0.0/lib/clang/5.0.0/include/stddef.h` -- but note the llvm/clang references in that filename.  That seems like the "wrong" `stddef.h` file for the `gcc-6` compiler.
1. The `conftest.c` file that you stated *does* work cites a *different* `stddef.h` file: `/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6/gcc/x86_64-apple-darwin16.6.0/6.4.0/include/stddef.h` -- note that it is within the gcc 6.4.0 tree.

That dichotomy seems to be the issue here: you need to get the `gcc-6` that Open MPI's configure is using to use the correct `stddef.h`.  Indeed, the clang `stddef.h` file has what `gcc-6` considers to be an *error*, which causes *everything* to fail; the fact that Open MPI's `configure` test for`offsetof` fails appears to just be the symptom, not the real issue.

**Comment by kalravibhor** [comment]
@jsquyres : It looks like I am using the same. gcc-6 resides in /usr/local/bin which is at the begining of the path. However the gcc-6 is brew installed but most notably not a part of the llvm clang bundle. Consequently the gcc-6 symlink in /usr/local/bin points to the actual directory where it was installed i.e. a Cellar directory.

Let me know if that makes sense. Thanks !

**Comment by jsquyres** [comment]
That makes sense, but still, somehow your `gcc-6` is apparently somehow picking up the "wrong" `stddef.h` when it is running inside `configure`.  That seems to be the real problem.

This test (the `offsetof` test) is actually pretty early in `configure` -- so @ggouaillardet's suspicion that there's something in your and/or `configure`'s environment that is screwing up `gcc-6` (i.e., such that it picks up the "wrong" `stddef.h`) is starting to feel like a pretty good guess...

**Comment by ggouaillardet** [comment]
strictly speaking, i did not give you the full `conftest.c` since i trimmed some macros.
some might be causing the issue, so can you please try to compile this one with
```
gcc-6 -c -O3 -DNDEBUG -finline-functions -fno-strict-aliasing  conftest.c
```
also, what does
```
env | grep -i llvm
```
says on your platform ?

```c
/* confdefs.h */
#define PACKAGE_NAME "Open MPI"
#define PACKAGE_TARNAME "openmpi"
#define PACKAGE_VERSION "2.1.2"
#define PACKAGE_STRING "Open MPI 2.1.2"
#define PACKAGE_BUGREPORT "http://www.open-mpi.org/community/help/"
#define PACKAGE_URL ""
#define OPAL_ARCH "x86_64-apple-darwin16.7.0"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define __EXTENSIONS__ 1
#define _ALL_SOURCE 1
#define _GNU_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define _TANDEM_SOURCE 1
#define OMPI_MAJOR_VERSION 2
#define OMPI_MINOR_VERSION 1
#define OMPI_RELEASE_VERSION 2
#define OMPI_GREEK_VERSION ""
#define OMPI_REPO_REV "v2.1.1-188-g6157ed8"
#define OMPI_TARBALL_VERSION "2.1.2"
#define OMPI_VERSION "2"
#define OMPI_RELEASE_DATE "Sep 20, 2017"
#define ORTE_MAJOR_VERSION 2
#define ORTE_MINOR_VERSION 1
#define ORTE_RELEASE_VERSION 2
#define ORTE_GREEK_VERSION ""
#define ORTE_REPO_REV "v2.1.1-188-g6157ed8"
#define ORTE_TARBALL_VERSION "2.1.2"
#define ORTE_VERSION "2"
#define ORTE_RELEASE_DATE "Sep 20, 2017"
#define OSHMEM_MAJOR_VERSION 2
#define OSHMEM_MINOR_VERSION 1
#define OSHMEM_RELEASE_VERSION 2
#define OSHMEM_GREEK_VERSION ""
#define OSHMEM_REPO_REV "v2.1.1-188-g6157ed8"
#define OSHMEM_TARBALL_VERSION "2.1.2"
#define OSHMEM_VERSION "2"
#define OSHMEM_RELEASE_DATE "Sep 20, 2017"
#define OPAL_MAJOR_VERSION 2
#define OPAL_MINOR_VERSION 1
#define OPAL_RELEASE_VERSION 2
#define OPAL_GREEK_VERSION ""
#define OPAL_REPO_REV "v2.1.1-188-g6157ed8"
#define OPAL_TARBALL_VERSION "2.1.2"
#define OPAL_VERSION "2"
#define OPAL_RELEASE_DATE "Sep 20, 2017"
#define OPAL_ENABLE_MEM_DEBUG 0
#define OPAL_ENABLE_MEM_PROFILE 0
#define OPAL_ENABLE_TIMING 0
#define OPAL_ENABLE_DEBUG 0
#define OPAL_WANT_PRETTY_PRINT_STACKTRACE 1
#define OPAL_ENABLE_PTY_SUPPORT 1
#define OPAL_ENABLE_DLOPEN_SUPPORT 1
#define OPAL_ENABLE_HETEROGENEOUS_SUPPORT 0
#define OPAL_ALIGN_WORD_SIZE_INTEGERS 0
#define OPAL_WANT_HOME_CONFIG_FILES 1
#define OPAL_ENABLE_IPV6 0
#define OPAL_PACKAGE_STRING "Open MPI Kronos@Vibhors-MacBook-Pro.local Distribution"
#define OPAL_IDENT_STRING "2.1.2"
#define OPAL_MAX_PROCESSOR_NAME 256
#define OPAL_MAX_ERROR_STRING 256
#define OPAL_MAX_OBJECT_NAME 64
#define OPAL_MAX_INFO_KEY 36
#define OPAL_MAX_INFO_VAL 256
#define OPAL_MAX_PORT_NAME 1024
#define OPAL_MAX_DATAREP_STRING 128
#define OPAL_ENABLE_CRDEBUG 0
#define OPAL_ENABLE_GETPWUID 1
#define OPAL_ENABLE_PROGRESS_THREADS 0
#define OPAL_HAVE_SOLARIS 0
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NETINET_TCP_H 1
#define HAVE_STRUCT_SOCKADDR_IN 1
#define OPAL_CUDA_SUPPORT 0
#define OPAL_CUDA_SYNC_MEMOPS 0
#define OPAL_CUDA_GET_ATTRIBUTES 0
#define OPAL_CUDA_GDR_SUPPORT 0
#define ORTE_WANT_ORTERUN_PREFIX_BY_DEFAULT 0
#define ORTE_ENABLE_STATIC_PORTS 1
#define OMPI_WANT_MPI_INTERFACE_WARNING 1
#define OMPI_GROUP_SPARSE 0
#define OMPI_WANT_PERUSE 0
#define OMPI_WANT_MPI_CXX_SEEK 1
#define MPI_PARAM_CHECK ompi_mpi_param_check
#define OMPI_PARAM_CHECK 1
#define OMPI_BUILD_FORTRAN_F08_SUBARRAYS 0
#define OSHMEM_SPEC_COMPAT 0
#define OSHMEM_PARAM_CHECK 0
#define OPAL_CC "gcc-6"
#define STDC_HEADERS 1
#define _GNU_SOURCE 1
#define OPAL_C_HAVE_BUILTIN_EXPECT 1
#define OPAL_C_HAVE_BUILTIN_PREFETCH 1
#define OPAL_C_HAVE_BUILTIN_CLZ 1
#define OPAL_CC_USE_PRAGMA_IDENT 0
#define OPAL_CC_USE_IDENT 0
#define OPAL_CC_USE_PRAGMA_COMMENT 
#define OPAL_CC_USE_CONST_CHAR_IDENT 1
#define HAVE_INT8_T 1
#define HAVE_UINT8_T 1
#define HAVE_INT16_T 1
#define HAVE_UINT16_T 1
#define HAVE_INT32_T 1
#define HAVE_UINT32_T 1
#define HAVE_INT64_T 1
#define HAVE_UINT64_T 1
#define HAVE___INT128 1
#define HAVE_LONG_LONG 1
#define HAVE___FLOAT128 1
#define HAVE_LONG_DOUBLE 1
#define HAVE_COMPLEX_H 1
#define HAVE_FLOAT__COMPLEX 1
#define HAVE_DOUBLE__COMPLEX 1
#define HAVE_LONG_DOUBLE__COMPLEX 1
#define HAVE_INTPTR_T 1
#define HAVE_UINTPTR_T 1
#define HAVE_MODE_T 1
#define HAVE_SSIZE_T 1
#define HAVE_PTRDIFF_T 1
#define SIZEOF_CHAR 1
#define SIZEOF_SHORT 2
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 16
#define SIZEOF___FLOAT128 16
#define SIZEOF_FLOAT__COMPLEX 8
#define SIZEOF_DOUBLE__COMPLEX 16
#define SIZEOF_LONG_DOUBLE__COMPLEX 32
#define SIZEOF_VOID_P 8
#define SIZEOF_SIZE_T 8
#define SIZEOF_SSIZE_T 8
#define SIZEOF_PTRDIFF_T 8
#define SIZEOF_WCHAR_T 4
#define SIZEOF_PID_T 4
#define OPAL_ALIGNMENT_BOOL 1
#define OPAL_ALIGNMENT_INT8 1
#define OPAL_ALIGNMENT_INT16 2
#define OPAL_ALIGNMENT_INT32 4
#define OPAL_ALIGNMENT_INT64 8
#define OPAL_ALIGNMENT_CHAR 1
#define OPAL_ALIGNMENT_SHORT 2
#define OPAL_ALIGNMENT_WCHAR 4
#define OPAL_ALIGNMENT_INT 4
#define OPAL_ALIGNMENT_LONG 8
#define OPAL_ALIGNMENT_LONG_LONG 8
#define OPAL_ALIGNMENT_FLOAT 4
#define OPAL_ALIGNMENT_DOUBLE 8
#define OPAL_ALIGNMENT_LONG_DOUBLE 16
#define OPAL_ALIGNMENT___FLOAT128 16
#define OPAL_ALIGNMENT_FLOAT_COMPLEX 4
#define OPAL_ALIGNMENT_DOUBLE_COMPLEX 8
#define OPAL_ALIGNMENT_LONG_DOUBLE_COMPLEX 16
#define OPAL_ALIGNMENT_VOID_P 8
#define OPAL_ALIGNMENT_SIZE_T 8
#define OPAL_NEED_C_BOOL 1
#define SIZEOF__BOOL 1
/* end confdefs.h.  */
#include<stddef.h>
int
main ()
{
struct foo {int a, b;}; size_t offset = offsetof(struct foo, b);
  ;
  return 0;
}
```

**Comment by kalravibhor** [comment]
@jsquyres : Makes sense. Looks like there something promising came out of @ggouaillardet ' test. 

I am able to compile the new `conftest.c` file with `gcc-6`. In addition to which I ran `env | grep -i llvm` which results in the below mentioned output : 

`CPLUS_INCLUDE_PATH=/Users/Kronos/build/include:/usr/local/Cellar/llvm/5.0.0/lib/clang/5.0.0/include:/Users/Kronos/build/include:/usr/local/Cellar/llvm/5.0.0/lib/clang/5.0.0/include:
LIBRARY_PATH=/Users/Kronos/build/lib:/usr/local/Cellar/llvm/5.0.0/lib/clang/5.0.0/lib:/Users/Kronos/build/lib:/usr/local/Cellar/llvm/5.0.0/lib/clang/5.0.0/lib:
C_INCLUDE_PATH=/Users/Kronos/build/include:/usr/local/Cellar/llvm/5.0.0/lib/clang/5.0.0/include:/Users/Kronos/build/include:/usr/local/Cellar/llvm/5.0.0/lib/clang/5.0.0/include:`

Looks like both my `CPP` and `C` paths have been using clang all the time. This might be causing configure to find clang and then compile using that. Am I correct to assume that reseting it will help ? Will give it a shot nonetheless. 

Let me know your thoughts on this. Thanks !

**Comment by ggouaillardet** [comment]
yep, unset these environment variables and let's see how things go ...

**Comment by kalravibhor** [comment]
Good news ... It seemed to have worked !!! However if I could trouble you again so to to guide me how to install C++ bindings for open-mpi (since it has been deprecated) which is essentially central to my idea.

`Build MPI C++ bindings (deprecated): no`

Kindly let me know what are the flags for building C++ bindings if any ? Thanks !

**Comment by ggouaillardet** [comment]
simply `configure --enable-mpi-cxx ...`

**Comment by kalravibhor** [comment]
@ggouaillardet : Thanks a lot for your help. All seems fine now :)

**Comment by jsquyres** [comment]
@kalravibhor Glad it all worked out -- happy MPI'ing!

**Comment by Pulsar18** [comment]
I actually have the same problem, when I run the `env | grep -i llvm` command I just get a blank line. 
What could the problem maybe be?

**Comment by ggouaillardet** [comment]
@Pulsar18 please upload your `config.log`

**Comment by Pulsar18** [comment]
@ggouaillardet: This is the `config.log`:
[config.log](https://github.com/open-mpi/ompi/files/1771305/config.log)

**Comment by ggouaillardet** [comment]
It seems `/usr/include/stdio.h` is missing. Did you install the Command Line Tools package ?

**Comment by jsquyres** [comment]
@Pulsar18 Per what @ggouaillardet said, it looks like your compiler installation is incomplete.  Once you are able to compile a simple "hello world" C program, Open MPI should compile and install properly.

If you still have problems, please open a new github issue.  Thanks!

**Comment by Pulsar18** [comment]
Thanks a lot.

**Comment by jinfagang** [comment]
Same error here in 2022.... how to resolve

**Comment by ggouaillardet** [comment]
@jinfagang please open a new issue and provide the required information.

As you pointed, this is 2022, and no one should be using Open MPI 2.x with gcc 6 from brew.
