### ISSUE TITLE
Missing progress on dynamic window while polling on allocated window

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#4434]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
Open MPI 3.0.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Installed from release tarball using `./configure && make` (no configure flags set)

### Please describe the system on which you are running

* Operating system/version: Linux 4.10.0-38-generic
* Computer hardware: Lenovo T460s (single node)
* Network type: sm

-----------------------------

## Details of the problem

Consider one process (P1) polling locally on a regular window (W1) for a local value to change (using `MPI_Win_lock`+`MPI_Get`+`MPI_Win_unlock`) while a second process (P2) tries to read from a memory location in a dynamic window (W2) on process P1 (using `MPI_Rget`+`MPI_Wait`, other combinations affected as well). P2 will later update the memory location waited on by P1. However, the read on the dynamic window stalls as the (local) read on W1 on P1 does not trigger progress on the dynamic window W2, causing the application to deadlock.

It is my understanding that process P1 should guarantee progress on any communication it is involved in while calling MPI functions, irregardless of the window or window type, and thus the communication should succeed. Is this assumption correct? Or is P1 required to access W2 as well to ensure progress? I can trigger progress on W2 on P1 by adding a call to `MPI_Iprobe` but that seems like a hack to me. Also, if both W1 and W2 are regular (allocated) windows the communication succeeds.

I am attaching a small reproducer: [ompi_dynamicwin_hang.tar.gz](https://github.com/open-mpi/ompi/files/1436461/ompi_dynamicwin_hang.tar.gz)

(initially reported on the user mailing)

**Comment by jsquyres** [comment]
@hjelmn This seems to be a one-sided issue, and a reproducer was attached.  Can you have a look?

**Comment by devreal** [comment]
I cannot reproduce this on current master so I'm closing this issue.
