### ISSUE TITLE
unrecognized options: --enable-mpi-thread-multiple

### ISSUE THREAD

**Issue by yokattame** [open-mpi/ompi#4435]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v3.0.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
from a source tarball
https://www.open-mpi.org/software/ompi/v3.0/
dowload openmpi-3.0.0.tar.gz

### Please describe the system on which you are running

* Operating system/version: ubuntu

## Details of the problem
When I code "./configure --prefix=/usr/local --with-cuda --enable-mpi-thread-multiple --with-pmi --with-slurm", there is a warning "unrecognized options: --enable-mpi-thread-multiple"

**Comment by ggouaillardet** [comment]
the option was removed starting from the v3.0 series, but this does not seem clear from the `README`

iiuc, the overhead is so minimal (compared to previous releases and/or some alternate MPI implementations) this option does not make any more sense, so it is fine it was removed.

> commit 230d04327e654534e14d44808c3e4526773d1331
> Author: Nathan Hjelm <hjelmn@me.com>
> Date:   Tue Feb 23 09:58:32 2016 -0700
> 
>     ompi: always enable MPI_THREAD_MULTIPLE support
>     
>     This commit removes the --with-mpi-thread-multiple option and forces
>     MPI_THREAD_MULTIPLE support. This cleans up an abstration violation
>     in opal where OMPI_ENABLE_THREAD_MULTIPLE determines whether the
>     opal_using_threads is meaningful. To reduce the performance hit on
>     MPI_THREAD_SINGLE programs an OPAL_UNLIKELY is used for the
>     check on opal_using_threads in OPAL_THREAD_* macros.
>     
>     This commit does not clean up the arguments to the various functions
>     that take whether muti-threading support is enabled. That should be
>     done at a later time.
>     
>     Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>
>

**Comment by jsquyres** [comment]
Looks like this is resolved; feel free to re-open if you have further questions.

**Comment by Aniruddh25** [comment]
If MPI_THREAD_MULTIPLE is enabled by default, then at least the output of ompi_info should indicate it. 
I see the following output after installing v3.0.0 Open MPI. Should I simply assume that even if says no, it has been enabled ?

$ ompi_info | grep -i thread
          Thread support: posix (MPI_THREAD_MULTIPLE: no, OPAL support: yes, OMPI progress: no, ORTE progress: yes, Event lib: yes)
   FT Checkpoint support: no (checkpoint thread: no)

**Comment by ggouaillardet** [comment]
I am afraid you are running the wrong `ompi_info`.

`MPI_THREAD_MULTIPLE` is hard coded in the `v3.0` release/branch

https://github.com/open-mpi/ompi/blob/v3.0.0/ompi/tools/ompi_info/param.c#L311-L317

**Comment by Aniruddh25** [comment]
You are right. I wasn't aware that an older version  Open MPI: 1.10.2 was already installed in my /usr/bin ubuntu machine.

After running the ompi_info from the v3.0 installation location, I do see thread support is enabled:

Thread support: posix (MPI_THREAD_MULTIPLE: **yes**, OPAL support: yes,
                          OMPI progress: no, ORTE progress: yes, Event lib:
                          yes)
