### ISSUE TITLE
Sun compiler doesn't like embedded PMIx

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#4436]
In testing the 2.0.4rc2 using Sun 5.15 compiler, Siegmar reported hit the following build failure:

thank you very much for the fix. Unfortunately, I still get an error
with Sun C 5.15.

loki openmpi-2.0.4rc2-Linux.x86_64.64_cc 125 tail -30 log.make.Linux.x86_64.64_cc
  CC       src/client/pmix_client.lo
"/export2/src/openmpi-2.0.4/openmpi-2.0.4rc2/opal/include/opal/sys/x86_64/atomic.h", line 161: warning: parameter in inline asm statement unused: %3
"/export2/src/openmpi-2.0.4/openmpi-2.0.4rc2/opal/include/opal/sys/x86_64/atomic.h", line 207: warning: parameter in inline asm statement unused: %2
"/export2/src/openmpi-2.0.4/openmpi-2.0.4rc2/opal/include/opal/sys/x86_64/atomic.h", line 228: warning: parameter in inline asm statement unused: %2
"/export2/src/openmpi-2.0.4/openmpi-2.0.4rc2/opal/include/opal/sys/x86_64/atomic.h", line 249: warning: parameter in inline asm statement unused: %2
"/export2/src/openmpi-2.0.4/openmpi-2.0.4rc2/opal/include/opal/sys/x86_64/atomic.h", line 270: warning: parameter in inline asm statement unused: %2
"../../../../../../openmpi-2.0.4rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client.c", line 235: redeclaration must have the same or more restrictive linker scoping: OPAL_PMIX_PMIX112_PMIx_Get_version
"../../../../../../openmpi-2.0.4rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client.c", line 240: redeclaration must have the same or more restrictive linker scoping: OPAL_PMIX_PMIX112_PMIx_Init
"../../../../../../openmpi-2.0.4rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client.c", line 408: redeclaration must have the same or more restrictive linker scoping: OPAL_PMIX_PMIX112_PMIx_Initialized
"../../../../../../openmpi-2.0.4rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client.c", line 416: redeclaration must have the same or more restrictive linker scoping: OPAL_PMIX_PMIX112_PMIx_Finalize
"../../../../../../openmpi-2.0.4rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client.c", line 488: redeclaration must have the same or more restrictive linker scoping: OPAL_PMIX_PMIX112_PMIx_Abort
"../../../../../../openmpi-2.0.4rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client.c", line 616: redeclaration must have the same or more restrictive linker scoping: OPAL_PMIX_PMIX112_PMIx_Put
"../../../../../../openmpi-2.0.4rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client.c", line 703: redeclaration must have the same or more restrictive linker scoping: OPAL_PMIX_PMIX112_PMIx_Commit
"../../../../../../openmpi-2.0.4rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client.c", line 789: redeclaration must have the same or more restrictive linker scoping: OPAL_PMIX_PMIX112_PMIx_Resolve_peers
"../../../../../../openmpi-2.0.4rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client.c", line 852: redeclaration must have the same or more restrictive linker scoping: OPAL_PMIX_PMIX112_PMIx_Resolve_nodes
cc: acomp failed for ../../../../../../openmpi-2.0.4rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client.c
Makefile:1242: recipe for target 'src/client/pmix_client.lo' failed
make[4]: *** [src/client/pmix_client.lo] Error 1
make[4]: Leaving directory '/export2/src/openmpi-2.0.4/openmpi-2.0.4rc2-Linux.x86_64.64_cc/opal/mca/pmix/pmix112/pmix'
Makefile:1486: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/export2/src/openmpi-2.0.4/openmpi-2.0.4rc2-Linux.x86_64.64_cc/opal/mca/pmix/pmix112/pmix'
Makefile:1935: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/export2/src/openmpi-2.0.4/openmpi-2.0.4rc2-Linux.x86_64.64_cc/opal/mca/pmix/pmix112'
Makefile:2301: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/export2/src/openmpi-2.0.4/openmpi-2.0.4rc2-Linux.x86_64.64_cc/opal'
Makefile:1800: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
loki openmpi-2.0.4rc2-Linux.x86_64.64_cc 125

**Comment by rhc54** [comment]
I would recommend we not pursue this and just recommend the user upgrade OMPI.

**Comment by hppritcha** [comment]
Update the 2.0.x README with a blurb about this problem #4447 .  Closing this as won't fix.

**Comment by hppritcha** [comment]
See
https://www.mail-archive.com/users@lists.open-mpi.org//msg31725.html
for the discussion on the user mail list.
