### ISSUE TITLE
error when install install openmpi 3.0.0,  variable undeclared

### ISSUE THREAD

**Issue by tobyyouup** [open-mpi/ompi#4441]
When install openmpi 3.0.0 following the instructions in https://www.open-mpi.org/faq/?category=building#easy-build and download 3.0.0 files and run with command "make all install", it shows error ："UCP_MEM_MAP_ALLOCATE’ undeclared", the details of the log is:

```
make[2]: Entering directory `/home/xx/openmpi-3.0.0/oshmem/mca/sshmem/ucx'
  CC       sshmem_ucx_module.lo
sshmem_ucx_module.c: In function ‘segment_create’:
sshmem_ucx_module.c:104:33: error: ‘UCP_MEM_MAP_ALLOCATE’ undeclared (first use in this function)
     mem_map_params.flags      = UCP_MEM_MAP_ALLOCATE|UCP_MEM_MAP_FIXED;
                                 ^
sshmem_ucx_module.c:104:33: note: each undeclared identifier is reported only once for each function it appears in
sshmem_ucx_module.c:104:54: error: ‘UCP_MEM_MAP_FIXED’ undeclared (first use in this function)
     mem_map_params.flags      = UCP_MEM_MAP_ALLOCATE|UCP_MEM_MAP_FIXED;
                                                      ^
make[2]: *** [sshmem_ucx_module.lo] Error 1
make[2]: Leaving directory `/home/xx/openmpi-3.0.0/oshmem/mca/sshmem/ucx'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/xx/openmpi-3.0.0/oshmem'
make: *** [all-recursive] Error 1
```

My system is ubuntu 14.04, glibc 2.19.   So where is the problem?

**Comment by miked-mellanox** [comment]
can it be that ucx version you compile with is outdated?
@yosefe

**Comment by tobyyouup** [comment]
@miked-mellanox @yosefe   Thanks for your reply, Then how could I fix this?

**Comment by brminich** [comment]
@tobyyouup, what is your UCX version? 
You may download the latest UCX here: https://github.com/openucx/ucx. Plz, check [Compiling UCX](https://github.com/openucx/ucx/wiki) section on Wiki.

Then you need to add `--with-ucx=<UCX_INSTALL_PATH>` parameter to your OMPI configure and build it again.  (UCX_INSTALL_PATH is the folder where you installed UCX)

This should resolve the issue

**Comment by jsquyres** [comment]
@tobyyouup I'm going to pre-emptively close this issue because I think @miked-mellanox and @brminich's replies should resolve your issue.

If their suggestions don't fix the issue, please reply with all the info cited here (https://www.open-mpi.org/community/help/), and we can re-open the issue to discuss further.

Thanks!

**Comment by tobyyouup** [comment]
@jsquyres  @brminich  Yes, it actually solved my problem, thanks!
