### ISSUE TITLE
MPI I/O is very slow on NFS since commit 8779384bf

### ISSUE THREAD

**Issue by ericch1** [open-mpi/ompi#4446]
Hi,

I am compiling with ompi/v3.0.x branch each night and I just noticed that since oct 26, our nightly validation tests where taking a huge amount of time to complete.

More precisely, the commit 8779384bf is making our code going very slow at writing.
If I use commit 6e910d1c4 or before, everything is fine.

I suspect something related with mpi i/o since the huge difference is at the end of the test, when we write.  See times:

before:
<pre>
routine      sec(WC)   sec(SelfUser)  sec(SelfSys)
WRITE_MPI    3.3241     1.0231        0.2038
</pre>

after:
<pre>
routine      sec(WC)   sec(SelfUser)  sec(SelfSys)
WRITE_MPI    605.3284   161.4893      162.1422      
</pre>

we are mostly using MPI_File_write_all_begin/end in combination with MPI_File_set_view with types created with MPI_Type_indexed.

Here is some information on how we build OpenMPI:

http://www.giref.ulaval.ca/~cmpgiref/ompi_3.x/2017.10.26.22h00m02s_config.log
http://www.giref.ulaval.ca/~cmpgiref/ompi_3.x/2017.10.26.22h00m02s_ompi_info_all.txt

OMPI environment variables at execution time:
<pre>
OMPI_COMM_WORLD_RANK=0
OMPI_MCA_pmix=^s1,s2,cray,isolated
OMPI_MCA_orte_ess_num_procs=10
OMPI_MCA_ess_base_vpid=0
OMPI_MCA_ess_base_jobid=2495741953
OMPI_MCA_orte_launch=1
OMPI_MCA_orte_num_nodes=1
OMPI_COMM_WORLD_LOCAL_RANK=0
OMPI_MCA_orte_hnp_uri=2495741952.0;tcp://132.203.7.33:37957
OMPI_ARGV=mpi_v=2 outilVtune=False verbose=True Beowulf=False outilMassif=False verifNewDelete=True NbNoeuds=10 outilPerfRecord=False verifValgrind=False Mode=PasCreeEtalon outilCallgrind=False RepertoireDestination=/users/cmpbib/compilations/zorg/linux_ompi_3.x/TV2017-11-03_00h37m49sEDT/opt/Test.MortierDiffusion RepertoireTest=/pmi/cmpbib/compilation_BIB_ompi_3.x/COMPILE_AUTO/TestValidation/Ressources/opt/Test.MortierDiffusion Prefixe=carres_4x_01_10procs outilPerfStat=False
OMPI_MCA_initial_wdir=/pmi/cmpbib/compilation_BIB_ompi_3.x/COMPILE_AUTO/TestValidation/Ressources/opt
OMPI_UNIVERSE_SIZE=4
OMPI_MCA_mpi_yield_when_idle=1
OMPI_COMMAND=Test.MortierDiffusion.opt
OMPI_FILE_LOCATION=/tmp/TV_2017.11.02.22h04m48s.S1B/ompi.zorg.40031/pid.24166/0/0
OMPI_APP_CTX_NUM_PROCS=10
OMPI_MCA_orte_precondition_transports=51f796f8c69a9a34-16d2e167dadfd3fe
OMPI_MCA_orte_jobfam_session_dir=/tmp/TV_2017.11.02.22h04m48s.S1B/ompi.zorg.40031/pid.24166
OMPI_MCA_orte_tmpdir_base=/tmp/TV_2017.11.02.22h04m48s.S1B
OMPI_COMM_WORLD_LOCAL_SIZE=10
OMPI_COMM_WORLD_SIZE=10
OMPI_MCA_mpi_param_check=1
OMPI_FIRST_RANKS=0
OMPI_MCA_orte_top_session_dir=/tmp/TV_2017.11.02.22h04m48s.S1B/ompi.zorg.40031
OMPI_MCA_orte_app_num=0
OMPI_MCA_plm_base_verbose=5
OMPI_MCA_orte_ess_node_rank=0
OMPI_MCA_ess=pmi
OMPI_MCA_shmem_RUNTIME_QUERY_hint=mmap
OMPI_MCA_hwloc_base_binding_policy=none
OMPI_MCA_rmaps_base_oversubscribe=1
OMPI_COMM_WORLD_NODE_RANK=0
OMPI_NUM_APP_CTX=1
OMPI_MCA_orte_local_daemon_uri=2495741952.0;tcp://132.203.7.33:37957
</pre>

Is anybody else encountering same problem?

Thanks,

Eric

**Comment by bwbarrett** [comment]
@edgargabriel, can you chime in?

**Comment by edgargabriel** [comment]
what file system is this on? The commit does have an impact on 
performance, there is however as part of the commit also an MCA 
parameter that allows to control the behavior of ompio.

If you want to have the same behavior as before, you need to set the mca 
parameter

fs_ufs_lock_algorithm 1

On regular UNIX file systems (i.e. not NFS), this should still be the 
case. On NFS, I would recommend that you try first to set this parameter to

fs_ufs_lock_algorithm 3

and see whether this helps.

Edgar

**Comment by ericch1** [comment]
for the nighlty tests, I am writing on NFS.

I just re-ran the test:
I confirm that writing to local disk is OK.
Using "export OMPI_MCA_fs_ufs_lock_algorithm=3" is "not working" meaning stays slow.
Using "export OMPI_MCA_fs_ufs_lock_algorithm=1" is good.

I will change my environment variable, but I isn't it somewhat not easy for users to know how to tune this?

Anyway, thanks for the quick answer! :)

Eric

**Comment by edgargabriel** [comment]
Glad to hear that this helped (Although I hoped that the value of 3 
would help a bit as well).

So here is the problem: up to recently, we ( = ompio) did not pay too 
much attention to NFS, but we had recently a couple of bug reports on 
the mailing list that we had to address, and which lead to the patch 
that you referred to.

In the patch, I decided to err on the side of caution and correctness, 
since the default values (which make it slow) are the only ones with 
which I could make our entire test-suite pass over NFS. If users did not 
have an issue with correctness over NFS in their application previously 
(which is for various reasons not as uncommon as one might think 
initially), they can gradually relax the locking requirements and see 
whether the data is still correct.

Thanks
Edgar

**Comment by ericch1** [comment]
Ok, thanks for theses informations.

All I can add, is that we haven't seen any "data" problems with OMPI/v2.x and OMPI/v3.0.x recently and even afterl oct 26 the (slowly) written data was ok.

I understand that we are not having a sufficient coverage over MPI I/O as you do.
But, since our software needs only the functions we use, It is ok like that... ;)

Other information: the I/O was obviously slow when we used 8 processes or more.  At 20 processes, it was deadly slow.

Thanks again,
Eric

**Comment by edgargabriel** [comment]
yes, but as described above, there is an MCa parameter that the user can use to have the previous behavior

**Comment by jsquyres** [comment]
Cool.  I'm just going to change the title of the issue to "MPI I/O is very slow **on NFS** since commit 8779384bf".

**Comment by chhu** [comment]
I can confirm this while trying openmpi 3.0.1rc3.
We just have shared mem machine on nfs4. 
Write to local disk with default: speed OK
Write to NFS4, default: Not OK. (~30min to write 280MB)
Write to NFS4, OMPI_MCA_fs_ufs_lock_algorithm=3 same, slow.
Write to NFS4, OMPI_MCA_fs_ufs_lock_algorithm=1 OK, 10s.
Luckily I found this thread!

**Comment by edgargabriel** [comment]
thank you for the feedback. I am contemplating whether we made the right choice for the default value of this parameter. Basically, we had two bug reports during the fall for MPI I/O over NFS, and those scenarios are only handled correctly when using the default values of fs_ufs_lock_algorithm. On the other hand, we are now punishing performance wise potentially significantly more users over NFS.

**Comment by chhu** [comment]
Seems you have different bugs on both ends... Hope you'll solve it!
