### ISSUE TITLE
mpool/memkind: Fails to build with newer versions of memkind

### ISSUE THREAD

**Issue by zzzoom** [open-mpi/ompi#4466]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v3.0.0. The problem is also present in v2.x and master.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Building OpenMPI from source with Intel xppsl 1.5.3 present, no memkind options mentioned in configure.

### Please describe the system on which you are running

* Operating system/version: CentOS 7.4
* Computer hardware: Xeon Phi 7210
* Network type: Infiniband

-----------------------------

## Details of the problem

The `memkind` interface currently used by OpenMPI has been deprecated since [version 1.3.0](https://github.com/memkind/memkind/releases/tag/v1.3.0). When building OpenMPI, configure automatically detects memkind but it fails to link missing symbols (`memkind_get_kind_by_partition`) later.
RedHat 7.4 and Intel xppsl are distributing newer versions of the library.

**Comment by hppritcha** [comment]
close via #4949
