### ISSUE TITLE
Get/set error handler functions are not actually thread safe

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#4477]
Thank you for taking the time to submit an issue!

## Background information

We use atomics in the various error handler get/set routines but it is possible to get into a situation where a thread calling an error handler get routine can call OBJ_RETAIN on a freed pointer.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

All versions.This is an old old bug.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

N/A

### Please describe the system on which you are running

* Operating system/version: N/A
* Computer hardware: N/A
* Network type: N/A

-----------------------------

## Details of the problem

The problem path can occur when one thread calls `MPI_*_get_errhandler` and goes to sleep between the `cmpset` loop and the retain. If another thread calls `MPI_*_set_errhandler` then `MPI_Errhandler_free` while the get thread is asleep then the retain call in the get thread is called on an invalid pointer.

**Comment by bosilca** [comment]
This is not the part that I am concerned about, as concurrently manipulating error handlers or concurrently manipulating the error handler in the same communicator is clearly unsafe. I am concerned about asynchronous progress, where a progress thread is trying to trigger the error handler as the user is manipulating it.

**Comment by hjelmn** [comment]
@bosilca Ah, I see. That is the case I did not think about. There is no need for the atomic on the get but there is still a need for the atomic on the set. That why I asked for your review :). Will re-add the atomic on set.

**Comment by hjelmn** [comment]
Ok, fixed.
