### ISSUE TITLE
ompi program hangs when there were multiple NICs

### ISSUE THREAD

**Issue by li7hui** [open-mpi/ompi#4486]
Thank you for taking the time to submit an issue!

## Background information
Mellanox HPCX 3.0.x
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
Mellanox HPCX 3.0.x OpenMPI 3.0.x

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Installed from tar.gz

### Please describe the system on which you are running

* Operating system/version: 
CentOS 7.3
* Computer hardware: 
Dell R530
* Network type: 
Mellanox ConnectLX4 card
-----------------------------
```shell
shell$ mpirun --host rdma04,rdma06 -np 2 --bind-to core --display-map -mca pml ob1 -mca btl self,vader,openib --mca btl_openib_cpc_include rdmacm --map-by node -mca btl_openib_receive_queues P,65536,256,192,128 -mca mpi_add_procs_cutoff 4 ./hello_c
```
Hello,
 I ran the opnempi 3.0.x provided by Mellanox HPCX, but the mpi program just hange there for minutes, and never get executed.

The command lines I used is:
mpirun --host rdma04,rdma06 -np 2 --bind-to core --display-map -mca pml ob1 -mca btl self,vader,openib --mca btl_openib_cpc_include rdmacm --map-by node -mca btl_openib_receive_queues P,65536,256,192,128 -mca mpi_add_procs_cutoff 4 ./hello_c

btw, there were multiple NIC on the servers, which is the Mellanox, BroadCom, Emulex. The device name of Mellanox is mlx5_1. I think the problem is that OMPI does not select the right NIC, and then just hangs. 
 Please give me some hints how to solve this issue. Many thanks.

**Comment by miked-mellanox** [comment]
can you try to run it with mxm (pml yalla, which is default), instead of pml=on1 (openib btl) and specify desired device explicitly, i.e.

```
mpirun --host rdma04,rdma06 -np 2 --bind-to core --display-map --map-by node  -mca mpi_add_procs_cutoff 4 -x MXM _ RDMA _ PORTS=mlx5_ 0:1 ./hello_c
```

**Comment by vspetrov** [comment]
Moreover, since it is HPCX you also need to add "-x HCOLL_MAIN_IB=mlx5_0:1 " for libhcoll collective module.

**Comment by li7hui** [comment]
![hpcx_ompi](https://user-images.githubusercontent.com/1718938/32657227-eb405368-c64f-11e7-8f51-808096f0c841.png)

Hello, the problem still exist by using the following scripts:
mpirun --host rdma04,rdma06 -np 2 --bind-to core --display-map --map-by node  -mca mpi_add_procs_cutoff 4 -x MXM_RDMA_PORTS=mlx5_0:1 -x HCOLL_MAIN_IB=mlx5_0:1 ./hello_c

How shall I debug the problem please? Is there something like debug level?

**Comment by miked-mellanox** [comment]
Plz try select mxm explicitly,seems other cards take precedence in your setup:
-mca pml yalla

**Comment by li7hui** [comment]
Hello, the problem still exsits, as the openmpi program hangs as before.  I checked the RDMA connection between the two nodes with ib_send_bw, and it completed with success.

**Comment by alinask** [comment]
@li7hui Are you using a resource manager (slurm, pbs, ...)? 
If not, after loading HPC-X, please add '-x LD_LIBRARY_PATH' in the command line.
Please do the same if you are running from a compute node (rdma04?)

**Comment by li7hui** [comment]
@alinask   I thought I found the problem now.  I made two tests, one is to make the rdma connection between two servers: rdm04 and rdm06, the other test is to make the rdma connection between another two servers: rdm77 and rdm06. In the first test, I can only use the mlx5_1. If I uses the mlx5_0, the test fails. In the second test, I can only use the mlx5_0. If I uses the mlx5_1, the test fails. This is very odd, because you have to specify different Mellanox device for the RDMA connection. Can someone help me out with this issue.  The picture is as follows: 
![mlx5_0](https://user-images.githubusercontent.com/1718938/32712804-70cbbee0-c881-11e7-99e1-3d1987e772c6.png)
![mlx5_1](https://user-images.githubusercontent.com/1718938/32712815-76c74f58-c881-11e7-8dc7-216efc105e2c.png)

**Comment by alinask** [comment]
@li7hui Could you please post the output of 'ibstat' and 'ibdev2netdev' from each of the hosts?
Also, does 'ping' work between _all_ the hosts? 
How do you run ib_send_bw from the server side? from rdma06
When the test fails, which error do you get?

**Comment by li7hui** [comment]
@alinask Hello, these are the post of output of "ibstat" and "ibdev2netdev" from each of the hosts:

![ibstat_rdma04](https://user-images.githubusercontent.com/1718938/32728286-a868c472-c8ba-11e7-8743-177191ddae7c.png)
![ibstat_rdma06](https://user-images.githubusercontent.com/1718938/32728290-ae83b2cc-c8ba-11e7-9b89-66981bba7bd6.png)
![ibstat_rdm77](https://user-images.githubusercontent.com/1718938/32728294-b520d600-c8ba-11e7-9760-72edffddc9d4.png)

How do you run ib_send_bw from the server side? from rdma06
The script run ib_send_bw: 
ib_send_bw -d mlx5_0 -i 1 -F --report_gbits

When the test fails, which error do you get?
![rdma_fails](https://user-images.githubusercontent.com/1718938/32728324-d7537df4-c8ba-11e7-8351-41ca27c0de72.png)

Regards!

**Comment by li7hui** [comment]
btw: what kind of bonding mode should i use in order to support ompi please? i can set up this and check

**Comment by li7hui** [comment]
@miked-mellanox @vspetrov @alinask @jsquyres @npe9 
Hello All, 
I disabled the second port of the Mellanox ConnectX-4LX card, which is the ifcfg-p3p2. Also I removed the ifcfg-bond0. Now I can run the OpenMPI program on multiple nodes successfully. 

Regards!

**Comment by alinask** [comment]
@li7hui According to your first screenshot of ib_send_bw it seems that the default gids that the hosts use are different: rdma77 uses GID index 5 while rdma04 uses GID index 3.
In this case, please use the '-x' option to specify the GID index you would like to use.

**Comment by jladd-mlnx** [comment]
@li7hui can we close the issue?

**Comment by alinask** [comment]
@li7hui I'll close this issue for now. Please reopen if needed.
