### ISSUE TITLE
Problem using MPI_Open_port and friends

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#4496]
A user reported an issue trying to use MPI_OPEN_PORT and friends using Open MPI: https://www.mail-archive.com/users@lists.open-mpi.org//msg31730.html

Further testing by @rhc54 shows the test fails across all supported branches: (2.x, 3.0.x, 3.x), as well as master.

The test case is on dropbox:

https://www.dropbox.com/s/azo5ti4kjg12zjy/MPI_Ports.tar.gz?dl=0

**Comment by rhc54** [comment]
I don't see any plans/prospects for supporting that method going forward. Since it has been 2.5 years and nobody else feels the urge to come up with a solution, I'm closing this for now.
