### ISSUE TITLE
memkind API change causing failure to build with latest official version of xppsl from Intel

### ISSUE THREAD

**Issue by akesandgren** [open-mpi/ompi#4519]
## Background information
OpenMPI is using a deprecated API for memkind.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v2.1.1 has the problem and so does the master branch as far as i can see.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Building from source and looking at the git master.

### Please describe the system on which you are running

* Operating system/version: Ubuntu Xenial 16.04
* Computer hardware: Intel KNL
* Network type: Irrelevant since it fails in building

-----------------------------

## Details of the problem

The API for memkind was changed 2016-08-22 and the "enum memkind_base_partition" was moved to memkind_deprecated.h. It has since (2017-02-08) been moved completely to the internal API and is no longer available.

(Although there is an update to memkind master 2017-09-11 that sort of reverts that for the sake of OpenMPI explicitly)

My main problem is that the latest available release of xppsl from Intel (which is the supported libmemkind on KNL) does not contain that last change. (And Intel will likely complain during support calls if we use anything else)

Since it is deprecated it should no longer be used.

**Comment by akesandgren** [comment]
Note that the latest release of memkind upstream (not Intel), i.e. v1.6.0, is also lacking the commit which makes OpenMPI build.

**Comment by hppritcha** [comment]
related to #4466

**Comment by ggouaillardet** [comment]
@akesandgren meanwhile, you can opt not to compile the `mpool/memkind` module by configur'ing Open MPI with the `--enable-mca-no-build=mpool-memkind` option.

**Comment by akesandgren** [comment]
Already did that, well i used --without-memkind but the effect is good enough for the moment.

**Comment by hppritcha** [comment]
close via #4949
