### ISSUE TITLE
osc-monitoring component build fails when osc-portals4 is configured

### ISSUE THREAD

**Issue by tkordenbrock** [open-mpi/ompi#4523]
The osc-monitoring configury searches for a Portals4 installation, but does not use any of the configure variables in Makefile.am.  When compiling osc-monitoring, the compile fails because portals4.h cannot be found.

This problem exists on master and v3.1.x.

**Comment by jsquyres** [comment]
Just to track a little history here: 

* #4521 was the initial fix for this.  It seems to be a small fix for it.
* #4527 was later introduced that was a big bigger and, among other things, fixed this issue (in a different way than #4521).

Hence, #4521 was closed in favor of #4527.  But #4527 is not yet complete.

**Comment by clementFoyer** [comment]
#4527 is merged, thus clothing this Issue for target: master.
#4817 is approved, waiting to be merged in order to close for target: v3.1.x

**Comment by bwbarrett** [comment]
Both master and 3.1.x now have the patch, so closing this issue.
