### ISSUE TITLE
Is --with-ucx meant to work if OpenUCX is not installed at configure time?

### ISSUE THREAD

**Issue by chrissamuel** [open-mpi/ompi#4536]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

3.0.0 release tarball.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Build with easybuild, modified to include the following relevant options:

```
configopts += '--with-verbs '  # Enable OpenIB support
configopts += '--with-ucx '  # Enable UCX support
configopts += '--with-slurm=/usr/local/slurm/latest '  # Enable Slurm support
configopts += '--with-pmi=/usr/local/slurm/latest '  # Enable PMI2 Slurm support
configopts += '--without-mxm ' # Disable Mellanox MXM
configopts += '--without-hcoll ' # Disable Mellanox HCOLL
configopts += '--with-cuda=/usr/local/easybuild/software/CUDA/9.0.176 ' # Enable
 CUDA support
```

### Please describe the system on which you are running

* Operating system/version:  RHEL 7.4 with 4.13.12-1.el7.elrepo.x86_64 kernel (for CephFS support)
* Computer hardware: Dell (that's all I know sorry)
* Network type: Mellanox ConnectX-5 (multi-host variant)

-----------------------------

## Details of the problem

In trying to help a group to track down issues with RoCE I've done a build of 3.0.0 with --with-ucx as we found that having that enabled before probes for verbs interfaces and caused crashes prior to MLNX_OFED 4.2 and so I had assumed that it was functional.

However, doing some more googling around it seems from the OpenUCX site that you need to install their software first.

Is this correct, and should therefore --with-ucx cause configure to exit should OpenUCX not be found?

Or does MNLX_OFED 4.2 include support for UCX (I can't see that documented)?

```
  Configure command line: '--prefix=/usr/local/easybuild/software/OpenMPI/3.0.0-GCC-6.2.0-cuda-ucx' '--with-threads=posix' '--enable-shared' '--enable-mpi-thread-multiple' '--enable-mpirun-prefix-by-default' '--with-hwloc=/usr/local/easybuild/software/hwloc/1.11.3-GCC-6.2.0' '--with-verbs' '--with-ucx' '--with-slurm=/usr/local/slurm/latest' '--with-pmi=/usr/local/slurm/latest' '--without-mxm' '--without-hcoll' '--with-cuda=/usr/local/easybuild/software/CUDA/9.0.176'
```
```
             MCA pml ucx: ---------------------------------------------------
             MCA pml ucx: parameter "pml_ucx_verbose" (current value: "0", data source: default, level: 9 dev/all, type: int)
                          Verbose level of the UCX component
             MCA pml ucx: parameter "pml_ucx_priority" (current value: "5", data source: default, level: 3 user/all, type: int)
                          Priority of the UCX component
             MCA pml ucx: parameter "pml_ucx_num_disconnect" (current value: "1", data source: default, level: 3 user/all, type: int)
                          How may disconnects go in parallel
            MCA rte base: ---------------------------------------------------
```

**Comment by karasevb** [comment]
Hello
> Is this correct, and should therefore --with-ucx cause configure to exit should OpenUCX not be found?

Yes, this is correct.
UCX should be installed first.  If you setted the flag `--with-ucx` it mean OMPI must be exactly built with UCX, and case when UCX was not found the OMPI  build progress can not be continued.

**Comment by chrissamuel** [comment]
```
UCX should be installed first. If you setted the flag --with-ucx it mean OMPI must be exactly built with UCX, and case when UCX was not found the OMPI build progress can not be continued.
```
Thanks for that - it appears that MLNX_OFED does indeed include undocumented (as far as I see) support for UCX.   Running my own configure I can see it detects Open UCX and digging further I can see it looks for the ucp.h header.  That is owned by the ucx-devel RPM which has the same build host info as other OFED packages.

Thanks for your help!

All the best,
Chris
