### ISSUE TITLE
OpenMPI 3.0.0 MPI_COMM_SPAWN child fails to MPI_INIT

### ISSUE THREAD

**Issue by CalugaruVaxile** [open-mpi/ompi#4555]
I have a very simple code: 
master (houprg118061) spawns a slave (houprg118069) 
slave connects to master
master sends value = 500 to slave
slave adds 1
slave sends 501 back to master
master prints 501
everyone shuts down.

Code works perfectly with OpenMPI 1.6.4 and with mpich 3.2.1. However OpenMPI 3.0.0 fails. Actually even OpenMPI 3.0.0 succeeds if spawning on the same host. Spawning on remote host(s) though, fails systematically. Please do let me know if you have a cure/workaround for this. I would love to stay with OpenMPI 3.0.0 and not switch to mpich. OS is Debian 6

```
MASTER MPIINIT
MASTER houprg118061 TRies Spawn
SLAVE houprg118069 STARTS
SLAVE houprg118069 TRIES MPIINIT
[houprg118069:17124] [[42756,0],1] ORTE_ERROR_LOG: Not found in file orted/pmix/pmix_server_fence.c at line 198
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[42756,2],0]) is on host: houprg118069
  Process 2 ([[42756,1],0]) is on host: unknown!
  BTLs attempted: self tcp

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_dpm_dyn_init() failed
  --> Returned "Unreachable" (-12) instead of "Success" (0)
--------------------------------------------------------------------------
[houprg118069:17128] *** An error occurred in MPI_Init_thread
[houprg118069:17128] *** reported by process [46912434864130,140733193388032]
[houprg118069:17128] *** on a NULL communicator
[houprg118069:17128] *** Unknown error
[houprg118069:17128] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[houprg118069:17128] ***    and potentially your MPI job)
[houprg118069:17128] [[42756,2],0] ORTE_ERROR_LOG: Unreachable in file dpm/dpm.c at line 433
```

Master code:

```cxx
#include <iostream>
#include <cstring>
#include <mpi.h>
#include <unistd.h>
#include <limits.h>

using namespace std;

int main() {
  char slavejobtospawn[500];
  strcpy(slavejobtospawn, "/rdfs/home/ggavaza/mpitry/stdal/stdal");
  
  MPI_Comm worker_comm_;
  MPI_Info minfo;
  int mpistat;

  // == init MPI
  int mpiInitialized;
  char localhost[HOST_NAME_MAX];
  mpistat = gethostname(localhost, HOST_NAME_MAX);
  mpistat = MPI_Initialized(&mpiInitialized);
  if(!mpiInitialized) {
    int provided;
    mpistat = MPI_Init_thread(0, 0, MPI_THREAD_MULTIPLE, &provided);
//     mpistat = MPI_Init_thread(0, 0, MPI_THREAD_SINGLE, &provided);
    if (provided < MPI_THREAD_MULTIPLE) {
      cout << "ERROR: The MPI library does not have full thread support" << endl;
      mpistat = MPI_Abort(MPI_COMM_WORLD, 1);
    };
    cout << "MASTER MPIINIT" << endl;
  };
  
  char hostin[120];
  strcpy(hostin, "lamhosts_tmp");
  
  cout << "MASTER " << localhost << " TRies Spawn" << endl;
  
  mpistat = MPI_Info_create(&minfo);
  mpistat = MPI_Info_set(minfo, "add-hostfile", hostin);
  mpistat = MPI_Comm_spawn(slavejobtospawn, MPI_ARGV_NULL, 
           1, minfo, 0, MPI_COMM_WORLD, &worker_comm_, MPI_ERRCODES_IGNORE);
   
  cout << "MASTER " << localhost << " SPAWNED SUCCESS" << endl;
  
  int value = 500;
  cout << "value =" << value << endl;
  mpistat = MPI_Send(&value, 1, MPI_INT, 0, 0, worker_comm_);
  MPI_Status MPIerr;
  mpistat = MPI_Recv(&value, 1, MPI_INT, 0, 0, worker_comm_, &MPIerr);
  cout << "updated value =" << value << endl;
  
  
  
  // == stop MPI
  mpistat = MPI_Finalize();
  cout << "MASTER " << localhost << "  SHUTTING DOWN" << endl;        
  return 0;
}
```

Slave code:

```cxx
#include <iostream>
#include <mpi.h>
#include <unistd.h>
#include <limits.h>

using namespace std;

int main() {
  int rank_;
  int master_;
  MPI_Comm slave_Comm_;
  MPI_Status MPIerr;
  int mpistat;
  // == init MPI
  int mpiInitialized;
  char localhost[HOST_NAME_MAX];
  mpistat = gethostname(localhost, HOST_NAME_MAX);
  cout << "SLAVE " << localhost << " STARTS" << endl;
  mpistat = MPI_Initialized(&mpiInitialized);
  if(!mpiInitialized) {
    int provided;
    cout << "SLAVE " << localhost << " TRIES MPIINIT" << endl;
    mpistat = MPI_Init_thread(0, 0, MPI_THREAD_MULTIPLE, &provided);
    if (provided < MPI_THREAD_MULTIPLE) {
      cout << "ERROR: The MPI library does not have full thread support" << endl;
      mpistat = MPI_Abort(MPI_COMM_WORLD, 1);
    };
    cout << "SLAVE " << localhost << " DONE SOME MPIINIT" << endl;
  };
  master_ = 0;
  mpistat = MPI_Comm_get_parent(&slave_Comm_);
  
  cout << "SLAVE " << localhost << " CONNECTED TO PARENT" << endl;
  
  int value;
  mpistat = MPI_Recv(&value, 1, MPI_INT, 0, 0, slave_Comm_, &MPIerr);
  value++;
  mpistat = MPI_Send(&value, 1, MPI_INT, 0, 0, slave_Comm_);
  
  // == stop MPI
  mpistat = MPI_Finalize();
  cout << "SLAVE " << localhost << " SHUTTING DOWN" <<endl;
  return 0;
}
```

Cheers,
George

**Comment by rhc54** [comment]
It works fine for me with the head of the v3.0.x branch (to be released as v3.0.1, I believe):
```
$ mpirun --map-by node -n 3 ./simple_spawn
[884146177:0 pid 34161] starting up on node rhc001!
[884146177:2 pid 34162] starting up on node rhc001!
[884146177:1 pid 40426] starting up on node rhc002.cluster!
0 completed MPI_Init
Parent [pid 34161] about to spawn!
2 completed MPI_Init
Parent [pid 34162] about to spawn!
1 completed MPI_Init
Parent [pid 40426] about to spawn!
[884146178:0 pid 34167] starting up on node rhc001!
[884146178:1 pid 40429] starting up on node rhc002.cluster!
[884146178:2 pid 34168] starting up on node rhc001!
Parent done with spawn
Parent sending message to child
Parent done with spawn
2 completed MPI_Init
Hello from the child 2 of 3 on host rhc001 pid 34168
0 completed MPI_Init
Hello from the child 0 of 3 on host rhc001 pid 34167
Child 0 received msg: 38
Parent done with spawn
1 completed MPI_Init
Hello from the child 1 of 3 on host rhc002.cluster pid 40429
Parent disconnected
Parent disconnected
Child 2 disconnected
Child 0 disconnected
Parent disconnected
Child 1 disconnected
34161: exiting
34167: exiting
40426: exiting
34168: exiting
34162: exiting
40429: exiting
$
```
My test code:
```
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/param.h>

#include <mpi.h>

int main(int argc, char* argv[])
{
    int msg, rc;
    MPI_Comm parent, child;
    int rank, size;
    char hostname[MAXHOSTNAMELEN];
    pid_t pid;
    char *env_rank,*env_nspace;

    env_rank = getenv("PMIX_RANK");
    env_nspace = getenv("PMIX_NAMESPACE");
    pid = getpid();
    gethostname(hostname, sizeof(hostname));

    printf("[%s:%s pid %ld] starting up on node %s!\n", env_nspace, env_rank, (long)pid, hostname);

    MPI_Init(NULL, NULL);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    printf("%d completed MPI_Init\n", rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);
    MPI_Comm_get_parent(&parent);
    /* If we get COMM_NULL back, then we're the parent */
    if (MPI_COMM_NULL == parent) {
        pid = getpid();
        printf("Parent [pid %ld] about to spawn!\n", (long)pid);
        if (MPI_SUCCESS != (rc = MPI_Comm_spawn(argv[0], MPI_ARGV_NULL, 3, MPI_INFO_NULL,
                                                0, MPI_COMM_WORLD, &child, MPI_ERRCODES_IGNORE))) {
            printf("Child failed to spawn\n");
            return rc;
        }
        printf("Parent done with spawn\n");
        if (0 == rank) {
            msg = 38;
            printf("Parent sending message to child\n");
            MPI_Send(&msg, 1, MPI_INT, 0, 1, child);
        }
        MPI_Comm_disconnect(&child);
        printf("Parent disconnected\n");
    }
    /* Otherwise, we're the child */
    else {
        MPI_Comm_rank(MPI_COMM_WORLD, &rank);
        MPI_Comm_size(MPI_COMM_WORLD, &size);
        pid = getpid();
        printf("Hello from the child %d of %d on host %s pid %ld\n", rank, 3, hostname, (long)pid);
        if (0 == rank) {
            MPI_Recv(&msg, 1, MPI_INT, 0, 1, parent, MPI_STATUS_IGNORE);
            printf("Child %d received msg: %d\n", rank, msg);
        }
        MPI_Comm_disconnect(&parent);
        printf("Child %d disconnected\n", rank);
    }

    MPI_Finalize();
    fprintf(stderr, "%d: exiting\n", pid);
    return 0;
}
```

**Comment by rhc54** [comment]
Note that my test does not use MPI_THREAD_MULTIPLE, which could make a difference in the MPI layer (but not in the spawn itself).

**Comment by CalugaruVaxile** [comment]
Hi Ralph,

many thanks for your reply! I am happy to see spawning working on remote
host; however I notice one difference between my code and yours: my code
spawns a standalone binary. Would it be possible for you to test that
scenario, too?
Otherwise: do you have an RC, or may I have the code you used in this
example - so I can try too, on my side? If this is not possible/available,
may I have an estimate date when an RC will be available?

Cheers,
George

**Comment by rhc54** [comment]
The only differences I see in the codes are:
* you ask for MPI_THREAD_MULTIPLE. While I know people have been trying to get that to work, I don't know if they have looked at the dynamic use-case. Since your code doesn't actually need thread multiple, I would suggest trying without it
* you spawn a different executable, but that is transparent to the implementation - the code never looks at what is being executed. My simple_spawn code executes the same steps.
* your slave checks for MPI_Initialized before initializing. I don't understand the rationale for doing so as it is impossible for that code as written to already be initialized. It should be harmless, but is another point of difference.

My test code is in the distribution: orte/test/mpi/simple_spawn.c. The included Makefile should support building it.

There is no RC yet, but you can always just clone the github repo and checkout the v3.0.x branch. Then just run autogen.pl prior to doing your usual configure/make procedure.

**Comment by CalugaruVaxile** [comment]
Hi Ralph,

I think I know where the problem is. Would you please mind modify your code and use a non-MPI_INFO_NULL MPI_Info object? 
Using MPI_INFO_NULL worked for me, too. Unfortunately this is not enough. In my case, the host(s) available for spawn are not known when the job starts; rather, the scheduler gives the job some nodes upon request. These nodes need to be registered in the MPI_info so that the spawned process starts where the scheduler decides.  

What I do for testing (and what fails) is this:
1. vi a hostfile
2.  mpistat = MPI_Info_set(minfo, "add-hostfile", hostfile);
3. spawn with the "minfo" (not with MPI_INFO_NULL)
4. either run with 
./executable
or
mpirun -n 1 ./executable
(no hosts specified in the command line)
I also tried
mpirun -n 1 -H <localhost> ./executable
to no avail

In the actual code I would not use "add-hostfile" but "add-hosts". The difference is (I would say) minor.
Please don't focus on the MPI_Init_Thread. It's a red herring, MPI_Init_thread succeeds in other standalone designs. 

I really believe the MPI_info is the issue here

Cheers,
George

**Comment by rhc54** [comment]
What scheduler are you using? If you are in a managed environment (e.g., slurm or Torque), then we won't support adding hosts to the original detected allocation.

**Comment by CalugaruVaxile** [comment]
Hi Ralph,

house-made scheduler, pretty much created for dynamic resource allocation.
Used OpenMPI 1.6.4 the way I described you for over two years, works
perfectly. I need to move away from 1.6.4 though, due to buggy
intercomm_create and intercomm_merge, plus the MPI3 features. Please
confirm that OpenMPI will no longer support dynamic host allocation (1.6.4
supported it pretty well, too bad you discontinue support for this
feature).

Cheers,
George

**Comment by rhc54** [comment]
I didn't say we don't support it - I said that we don't support it for HPC resource managers such as slurm and torque as they don't support dynamic allocations. Sometimes people pass us additional nodes outside their allocation in such environments, and we can't support that request.

I suspect this is a bug, but don't have time right now to investigate. Perhaps someone else can?

**Comment by CalugaruVaxile** [comment]
Hi Ralph,

oh, my bad! I am glad that you are still supporting the feature. Bugs are
just part of our trade :)

Cheers,
George

**Comment by rhc54** [comment]
one more thing you can try is to add "--novm" to your mpirun cmd line. There are two launch methods in OMPI - this tries the alternate one.

**Comment by CalugaruVaxile** [comment]
Many thanks, Ralph! I will try that and I will let you know if it works.

Cheers,
George

**Comment by CalugaruVaxile** [comment]
I am sorry but adding --novm doesn't change anything

Cheers,
George

**Comment by nevion** [comment]
@rhc54  / @jsquyres  - can you please test  4.0.5 on orte/test/mpi/simple_spawn.c - without any job manager - just ssh based host lists fail - I'm unable to find a working configuration with openmpi that doesn't freeze up in the listed sample  in MPI_Init in the child and MPI_Comm_spawn in the parent:

```
mpirun -mca pml ob1 -mca btl tcp,self -H node1,node2 --map-by ppr:1:node:oversubscribe `pwd`/spawn_test
[207880193:0 pid 3698] starting up on node node1!
[207880193:1 pid 16532] starting up on node node2!
0 completed MPI_Init
Parent [pid 3698] about to spawn!
[207880194:2 pid 3701] starting up on node node1!
1 completed MPI_Init
Parent [pid 16532] about to spawn!
[207880194:1 pid 16535] starting up on node node2!
[207880194:2 pid 16536] starting up on node node2!
```

However, mpich-3.3.2 w/ nemesis worked on this example without issue on the same nodeset.  I was even able to try it with '-map-by node -ppn 2' with mpich.
