### ISSUE TITLE
MPI_Reduce MPI_MIN and MPI_MAX

### ISSUE THREAD

**Issue by aliomarabdelazim** [open-mpi/ompi#4558]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
OpenMPI 2.0.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
easybuild

### Please describe the system on which you are running

* Operating system/version: 
CentOS v. 3.10.0
* Computer hardware: 
Intel Broadwell
* Network type: 
OmniPath
-----------------------------

## Details of the problem
I have a code that do some computations distributed among the MPI ranks, I use MPI_Wtime to measure the time each rank spends in finding the solution, 

double tpar1 = MPI_Wtime()

//do computation

double tpar2 = MPI_Wtime()

Then, I make a reduce of these times to measure the lowest starting time and the latest finish time
double Tpar1, Tpar2;
	MPI_Reduce(&tpar1,&Tpar1,1,MPI_DOUBLE,MPI_MIN,DATAOWNER,MPI_COMM_WORLD);
	MPI_Reduce(&tpar2,&Tpar2,1,MPI_DOUBLE,MPI_MAX,DATAOWNER,MPI_COMM_WORLD);
Then the program prints the difference between Tpar2 and Tpar1 as the makespan

Firstly I was using this code with Intel MPI 2017, and it was working fine. 
I tried the same code, however, the time printed ( the difference between Tpar2 and Tpar1) is by far wrong.
I suspect that MPI_MIN and MPI_MAX are not working as I expect and as it was working with the Intel MPI

I think there should not be a different behavior of the MPI_MAX and MPI_MIN between intel and OpenMPI 
Thank you for your help

**Comment by bosilca** [comment]
First, the return of MPI_Wtime is some absolute value that only makes sense on the process that gather it, and only as part of an interval computation (t2-t1 on the local process). Moreover, if your application clocks are not strongly synchronized (which is not an MPI requirement) computing the difference between the min entry time and the max exit time has little meaning. There is not a simple answer on how to synchronize distributed applications, but there is a large literature on how to globally synchronize distributed clocks.

A quicker way to do this is to allow each process to compute it's local computation cost, and then use reduce to get the max.

**Comment by jsquyres** [comment]
I think @bosilca answered your question, so I'm going to close the issue.  Feel free to re-open if it wasn't fully addressed.

**Comment by aliomarabdelazim** [comment]
Thank you very much for your reply. It seems that it is an effect of unsynchronized clocks as you suggested. Thanks.
