### ISSUE TITLE
need to verify Open MPI complies with MPI Forum ticket #419

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#456]
Need to verify that Open MPI complies with corrections made in MPI 3.1 standard concerning neighborhood collectives and non-symmetric graphs.  MPI Forum Ticket [#419](https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/419).

**Comment by hjelmn** [comment]
Ticket says there is no impact to implementers so we don't really *need* to do anything. It would be nice to have a check for a symmetric graph though. This check could probably be done at communicator creation and enforced in the neighborhood collective routines.

**Comment by hppritcha** [comment]
per @hjelmn 's comment closing this.
