### ISSUE TITLE
liblapacke.a is not present in install

### ISSUE THREAD

**Issue by timjim333** [open-mpi/ompi#4560]
## Background information
I want to link to LAPACKE libraries (such as liblapacke.a) but they are not in the `PREFIX/lib` directory after compiling. I have made sure that NO_LAPACKE is commented out in `Makefile.rule`. The computer is the same as in: https://github.com/open-mpi/ompi/issues/4499

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v3.0.0

-----------------------------

## Details of the problem
Compiling and installing OpenBLAS, I expected to see `liblapacke.a` in my `lib` directory but on running a `ls` in my PREFIX, I see:
```bash
FIa164@afispb07:~/programs/openblas/OpenBLAS-0.2.20$ ls *
bin:

include:
cblas.h  f77blas.h  lapacke_config.h  lapacke.h  lapacke_mangling.h  lapacke_utils.h  openblas_config.h

lib:
cmake          libopenblas_sandybridgep-r0.3.0.dev.a   libopenblas.so    pkgconfig
libopenblas.a  libopenblas_sandybridgep-r0.3.0.dev.so  libopenblas.so.0
```

I'm not sure if this a valid question. Did the LAPACKE libraries not copy over during the install? Or is this the correct behaviour? Is `liblapacke.a` something that I should compile myself? Thanks for your time.

**Comment by jsquyres** [comment]
@timjim333 OpenBLAS is not part of Open MPI.  I think you need to ask this question to the OpenBLAS maintainers.

**Comment by martin-frbg** [comment]
With OpenBLAS, you will get a single library that contains BLAS, LAPACK and LAPACKE.

**Comment by timjim333** [comment]
Apologies, I'd posted in the wrong forum - juggling a few install problems
correctly. Thanks for the info forever!
