### ISSUE TITLE
posix_memalign gets called with zero alignment in some circumstances

### ISSUE THREAD

**Issue by benmenadue** [open-mpi/ompi#4564]
`posix_memalign` requires an alignment that is a power of two and a multiple of `sizeof(void *)`. However, there is a call to `mpool_alloc` (and thus `mca_mpool_default_alloc`) in `mca_mpool_base_alloc` that passes an alignment of 0 -- which isn't a power of two.

I haven't noticed this actually cause a crash under normal circumstances, but TotalView does catch the call and bail. Perhaps the code path is only taken when debugging?

This is present in master.

**Comment by benmenadue** [comment]
I'm just testing a patch for this, will PR shortly if it compiles.

**Comment by hjelmn** [comment]
Close when the commits in #4565 are in v2.x, v3.0.x, and v3.1.x.

**Comment by jsquyres** [comment]
The fix has now been merged everywhere; closing this issue.
