### ISSUE TITLE
Open MPI missing MPI_COMM_DUP_FN and relatives for mpi_f08 bindings

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#460]
It appears the the mpi_f08 bindings for MPI_Comm_dup_fn, etc. are missing.  Looks like they
should be in attr-fn-f08-callback-interfaces.h.

**Comment by ggouaillardet** [comment]
i have some stuff ready for that, and I will pr tomorrow

**Comment by jsquyres** [comment]
This issue will be fixed by #623.
