### ISSUE TITLE
Update PMIx to v2.1.0

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#4605]
Need to refresh PMIx in OMPI v3.1.0 prior to release - should only be an internal-to-PMIx update, but needed to ensure backward compatibility with earlier PMIx and OMPI releases.

Will try to complete ASAP.

**Comment by rhc54** [comment]
Waiting on https://github.com/pmix/pmix/issues/586

**Comment by rhc54** [comment]
@bwbarrett @jsquyres I was going to provide a vanilla version of the official PMIx v2.1.0 release. However, it just hit me that the cleanup registration code won't be in that release - it involved adding attributes etc that moved it into PMIx v3.

Do you want the cleanup code here? It solves the problem of leftover files in /dev/shm, which is why I ask. Would mean taking the embedded pmix code currently in master.

**Comment by karasevb** [comment]
https://github.com/pmix/pmix/issues/586 was closed, and related PRs are merged https://github.com/pmix/pmix/pull/613, https://github.com/pmix/pmix/pull/614.

**Comment by karasevb** [comment]
@rhc54 Do we have any other blockers to update PMIx?

**Comment by rhc54** [comment]
Not that I know of, but I do need to resolve the question I posted above.

**Comment by karasevb** [comment]
@rhc54 can we sync PMIx v2.1 early than mentioned feature will be resolved? Since we faced the failure during testing with internal PMIx which was fixed here https://github.com/pmix/pmix/pull/614.

**Comment by rhc54** [comment]
I'm afraid Monday is a national holiday over here, so I don't know who will be around. I suspect this will at least need to wait until Tues or Wed before anything could be committed, regardless.

**Comment by artpol84** [comment]
@rhc54 Let's discuss this on Todays call.

**Comment by jladd-mlnx** [comment]
@karasevb since Ralph is no longer working on the OMPI project, please do the merge. 

@alinask @artpol84 FYI...

**Comment by karasevb** [comment]
Done #4746

**Comment by bwbarrett** [comment]
We've merged 2.1 (and now 2.1.1) into 3.1, so closing this issue.
