### ISSUE TITLE
MPI_Aint addressing arithmetic functions needed

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#464]
The MPI-3.1 MPI_Aint helper functions MPI_Aint_add and MPI_Aint_diff need to be implemented.
See MPI-Forum ticket [349](https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/349) and sections 2.6.4 and 4.1.5 of the MPI-3.1 standard document.

**Comment by jsquyres** [comment]
This is now done.
