### ISSUE TITLE
has less cpus than requested ones

### ISSUE THREAD

**Issue by CharlesxrWu** [open-mpi/ompi#4676]
Thank you for taking the time to submit an issue!

## Background information
mpirun (Open MPI) 3.0.0
ubuntu 16.04 TLS
### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
git clone and build from source

### Please describe the system on which you are running

* Operating system/version: ubuntu16.04
* Computer hardware: Dell R320
* Network type: 

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -np 2 ./hello_world
```
```shell
/home/*/.openmpi/bin/mpirun -n 2 --hostfile my_hosts -cpus-per-proc 10 /home/*/anaconda3/envs/pytorch/bin/python example.py
```
```shell
/home/*/.openmpi/bin/mpirun -n 2 --hostfile my_hosts -cpus-per-rank 10 /home/*/anaconda3/envs/pytorch/bin/python example.py
```
The server has 16 physical cores.
However, I have the problem:
```shell
A request for multiple cpus-per-proc was given, but a directive
was also give to map to an object level that has less cpus than
requested ones:

  #cpus-per-proc:  10
  number of cpus:  8
  map-by:          BYNUMA

Please specify a mapping level that has more cpus, or else let us
define a default mapping that will allow multiple cpus-per-proc.
```

**Comment by ggouaillardet** [comment]
Can you try to add the `-map-by core` option ?

FWIW, assigning one MPI task on two sockets (8+2 cores) will likely lead to suboptimal perfomances

**Comment by CharlesxrWu** [comment]
That's my hostile

node1 slots=1
node2 slots=1

'''shell
/home/*/.openmpi/bin/mpirun -n 2 --hostfile my_hosts --map-by core /home/*/anaconda3/envs/pytorch/bin/python example.py
'''
I use --map-by core, the problem is:
'''shell
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[36096,1],1]
  Exit code:    2
'''
Each task only occupies one core, which is slow to preprocess data. I want to run the task with all cores in the node, which I can do use python example.py in single node.

**Comment by ggouaillardet** [comment]
As a workaround, try to `-bind-to none` and get rid of the `-cpus-per-xyz` option.

**Comment by CharlesxrWu** [comment]
```shell
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[36178,1],1]
  Exit code:    2
```

I exec the command
```shell
 /home/*/.openmpi/bin/mpirun -np 2 --hostfile my_hosts -bind-to none /home/*/anaconda3/envs/pytorch/bin/python example.py
```
still cannot work.

**Comment by rhc54** [comment]
The error states that your program exited with non-zero status - that has nothing to do with OMPI, but is likely a problem in your code.

**Comment by CharlesxrWu** [comment]
@rhc54 I use the OMPI to exchange the data in my distributed work. It can get the right answer. However, the problem is that each task in each node just uses one core, which make the speed slow. I try the cpus-per-proc, cpus-per-rank and so on, but it still cannot work. I an not understand what you mean "that has nothing to do with OMPI". Can u explain it? Thank you!

**Comment by rhc54** [comment]
You reported the following error:
```
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[36178,1],1]
  Exit code:    2
```
This is showing that your program exited with a non-zero status, indicating an error in your program. Errors in your program aren't something OMPI can fix 😄

**Comment by hppritcha** [comment]
closing.  can be reopened if @CharlesxrWu is still seeing this.
