### ISSUE TITLE
--cpuset is not working when head node has different topology than compute nodes

### ISSUE THREAD

**Issue by miked-mellanox** [open-mpi/ompi#469]
setup:

* headnode (nodeA), Compute node (nodeB,nodeC).
* nodeA has different cpu topology than B,C

problem:

When mpirun --cpuset is executed from headnode but hostlist uses nodeB,nodeC - the mpirun consults nodeA topology for cpu-list instead nodeB/nodeC.

command line to reproduce

``` shell
nodeB% mpirun -np 2 -H nodeB,nodeC --cpu-set 12,13,14,15,17,18,19,20,21,22,23  
-mca hwloc_base_verbose 100  -mca ess_base_verbose 10  osu_bw
```

logs:

* mpirun from nodeB (problem not exists when launched from nodeA):
ftp://bgate.mellanox.com/upload/from_node.txt

* mpirun from nodeA (mpirun fails)
 ftp://bgate.mellanox.com/upload/debug_cpuset.txt

**Comment by rhc54** [comment]
Been fixed
