### ISSUE TITLE
Merge Fortran ERRCODES_IGNORE fix to v2.x, v3.0.x, v3.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#4693]
@nathanweeks submitted an F08 ERRCODES_IGNORE fix to master in #4681.

It needs to be applied to:

* v2.x
* v3.0.x
* v3.1.x

On the one hand, I'd like to apply the fix to v2.0.x even if we never release from there again.  But OTOH, there's a pretty small barrier-to-entry from moving from v2.0.x to v2.1.x.  So I think: let's not apply it to v2.0.x as an encouragement for people to upgrade to (at least) v2.1.x.

***NOTE:*** This is another issue that breaks backwards compatibility for F08.  However, as noted on #4681, correct MPI programs *could not compile* because of this bug.  Hence, this is an issue where we should fix it, note that we broke backwards compatibility (because the user app must have been incorrect if it had been able to compile before) in README, and move ok.

Are the v2.x and v3.x RMs ok with this?

**Comment by bwbarrett** [comment]
@jsquyres, can we close this bug now?
