### ISSUE TITLE
dvm: early exit of prun when another job completes

### ISSUE THREAD

**Issue by naughtont3** [open-mpi/ompi#4702]
### Version of Open MPI 

 - Open MPI `master` at c1b1bfc 

### How Open MPI was installed 

 - Reproducible on single node, normal Linux cluster instance with source build of `master`
 - My configure/build line:

    ```
       ./configure \
           --enable-debug \
          --enable-orterun-prefix-by-default \
          --with-devel-headers \
          --with-memory-manager=none \
          --enable-oshmem \
          --disable-vt \
         --prefix=/home/tjn/projects/ompi/ompi-devel/local \
   && make -j 4 && make install
    ```

### System where tests are running

* Operating system/version:  Linux
* Computer hardware:  x86_64
* Network type: ethernet

-----------------------------

## Details of the problem

When testing concurrent `prun` commands, the 2nd instance terminates early when the 1st instance finishes.  Example  using a basic `sleep` command:

```
   orte-dvm --daemonize
     # NOTE:  `sleep 6` run in the background
   prun -n 1 --verbose sleep 6 & prun -n 1 --verbose sleep 60 
```

General description of the steps:
 - Assume `sleep 6` gets ORTE-JobID=3 and `sleep 60` gets ORTE-JobID=4
 - When `sleep 6` finishes, the `evhandler()` in `prun` (JobID=3) fires and the tool exits cleanly
 - The problems is that when `sleep 6` finishes, the `evhandler()` in `prun` (JobID=4) **also** fires and the tool exits. The actual `sleep 60` executable is still running.

Note: 
 - Quick hack for testing with this example case was to use a global variable in `prun` to check the JobID in `evhandler()` and avoid setting `active=false` if JobID in cbdata not match the global variable.

```
elk2:$ orte-dvm --mca btl ^openib --mca oob tcp --daemonize
   # NOTE:  `sleep 6` run in the background
elk2:$ prun -n 1 --verbose sleep 6 & prun -n 1 --verbose sleep 60
[1] 13989
[node253:13989] JOB [12629,3] EXECUTING
[node253:13989] JOB [12629,3] (DEBUG) EXECUTING              <-- NOTE: PID of JID=3 (set global var)
[node253:13990] JOB [12629,4] EXECUTING
[node253:13990] JOB [12629,4] (DEBUG) EXECUTING              <-- NOTE: PID of JID=4 (set global var)

[node253:13989] JOB [12629,3] COMPLETED WITH STATUS 0
[node253:13989] JOB [12629,3] (DEBUG) COMPLETED
[node253:13990] JOB [12629,3] COMPLETED WITH STATUS 0             <--- NOTE: Wrong JID for PID 
[node253:13990] JOB [12629,4] (DEBUG) COMPLETED                   <--- NOTE: JID from hack global var
[node253:13990] DBG: BOGUS JOBID AVOID SETTING ACTIVE/QUITTING
[node253:13990] DBG: EARLY EXIT OF EVHANDLER

[node253:13990] JOB [12629,4] COMPLETED WITH STATUS 0
[node253:13990] JOB [12629,4] (DEBUG) COMPLETED
[1]+  Done                    prun -n 1 --verbose sleep 6
elk2:$
elk2:$ jobs
elk2:$ prun -terminate
TERMINATING DVM...DONE
elk2:$
```

**Comment by naughtont3** [comment]
Hi @rhc54, adding mention so you see for guidance.  Thanks

**Comment by rhc54** [comment]
The problem is that prun is registering to be notified of job terminations - but not discriminating on _which_ job. ORTE automatically notifies all registered requestors when a job terminates, which is why the second prun gets the notification.

There are a couple of possible solutions here. Let me ponder a little.

**Comment by rhc54** [comment]
I'm still getting a warning about an invalid file descriptor from orte-dvm when it terminates, but otherwise things are running fine. Thanks for the heads-up!

**Comment by naughtont3** [comment]
Great! Thanks Ralph.  Also, the note you added about the calling cbfunc() in prun's evhandler was helpful.  My local testing edit was similar to your fix, but I returned before calling the cbfunc() and therefore would mess up progress, which explains why some tests would hang. Thanks.
