### ISSUE TITLE
Provide pkg-config files for OSHMEM

### ISSUE THREAD

**Issue by nspark** [open-mpi/ompi#4730]
## Feature Request

Currently, Open MPI only provides `pkg-config` files for `ompi`, but not for OSHMEM. This issue requests that `oshmem.pc` (and/or `oshmem-c.pc`) be provided with an OSHMEM installation.

**Comment by ggouaillardet** [comment]
@nspark can you please give #4737 a try ?

the patch can be manually downloaded at https://github.com/open-mpi/ompi/pull/4737.patch

note you will need recent autotools in order to run `autogen.pl`

**Comment by nspark** [comment]
@ggouaillardet Thanks for addressing this issue. I built OSHMEM from your branch and the `pkg-config` files all seemed to work fine for compiling my OpenSHMEM programs.

**Comment by awlauria** [comment]
Master PR was merged. If this is desired for v5.0.x, please cherry pick over.

**Comment by awlauria** [comment]
This got re-merged in:
https://github.com/open-mpi/ompi/pull/8976

**Comment by awlauria** [comment]
v5.0.x: https://github.com/open-mpi/ompi/pull/9064
