### ISSUE TITLE
mpirun ignores unique subdomains in hostfile entries

### ISSUE THREAD

**Issue by Cerebus** [open-mpi/ompi#4732]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
openmpi 3.0.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Distribution binary package

### Please describe the system on which you are running
* Operating system/version:  Alpine Linux 3.5
* Computer hardware: ARM32v7
* Network type: Docker overlay
-----------------------------
## Details of the problem
When a hostfile contain unique FQDNs, mpirun treats each entry with the same host-part as the same node.  E.g., if the hostfile is:
```
mpi-worker.1.foo.net
mpi-worker.2.foo.net
```

mpirun treats this as one node with two slots.  If slots are specified, e.g.,:
```
mpi-worker.1.foo.net slots=2
mpi-worker.2.foo.net slots=2
````
mpirun returns the error:
```
--------------------------------------------------------------------------
A hostfile was provided that contains multiple definitions
of the slot count for at least one node:

  hostfile:  hosts
  node:      mpi-worker

You can either list a node multiple times, once for each slot,
or you can provide a single line that contains "slot=N". Mixing
the two methods is not supported.

Please correct the hostfile and try again.
--------------------------------------------------------------------------
```
## Expected behavior
mpirun should parse the complete hostname to determine uniqueness.

**Comment by Cerebus** [comment]
For the interested, I'm deploying OpenMPI on top of Docker Swarm as an easy way to experiment with HPC on Raspberry Pi 3 clusters.  Code is based on a [this project](https://github.com/NLKNguyen/alpine-mpich) which used MPICH, but MPICH isn't packaged for Alpine.   

Everything works except for this bit.  Docker swarm names service containers as <servicename>.<instance#>.<randomid>.<networkservicename> (e.g., " mpi-worker.1.sxqqwrrnalxej8s1rfurudzjk.mpi-net"). The master node collects worker node IDs dynamically via a SSH callback, but trying to collect the IP addresses is more of a PITA.  It would be nice if mpirun was FQDN aware.

Startup on mpirun is slow as crap, tho.

I'll post up a git project eventually.

**Comment by jjhursey** [comment]
By default, ORTE uses the short hostname `mpi-worker` as it assumes that all hosts are using the same domain. You can change this by setting this MCA parameter `-mca orte_keep_fqdn_hostnames t` (fqdn - fully qualified domain names).

Give that a try and let us know if it fixes the issue.

**Comment by gothicVI** [comment]
> Give that a try and let us know if it fixes the issue.

Thank you so much! This finally allowed me to run my stuff after way too long searching for the cause of the error.
