### ISSUE TITLE
iof stdin routing may have a problem

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#4744]
Per discussion on the users list, there may be a problem with `mpirun a.out < foo` (potentially where `foo` is a "large enough" file).

* Here's the message where @edgargabriel determined that the problem discussed in that thread is most likely not specific to MPI-IO: https://www.mail-archive.com/users@lists.open-mpi.org/msg31954.html
* Here's the beginning of the thread (for the entire context): https://www.mail-archive.com/users@lists.open-mpi.org/msg31909.html

In loose verbal discussions about this issue, we're wondering if IOF is somehow not sending the last chunk of the input file.

Of note is that there were some logic changes in IOF recently: 374c824a5cbd619dd1fa3e167bcd1cbe252ecdd0 and d9ad918a14f64434936fdfeb4dd266f792ce7170.  Might be worth seeing if those inadvertently caused the issue...?

**Comment by ggouaillardet** [comment]
i can reproduce the issue with a long enough input file.
indeed, the last chunks are not written.

`strace mpirun` shows that `mpirun` is reading chunks of 4096 bytes from 
stdin, and then writing chunks of 4096 bytes to the pipe to process 0.

if all `write()` success, then there is no issue ( for example, a `6515` 
characters file).
when the input is big enough (for example, a `650015` file on my 
system), then a bunch of `write()` fail with `-EAGAIN`, then the last 
chunk(s) if not written.

here are the last lines of `strace mpirun`

```
write(28, "05.83301       6805.00049\n   680"..., 4096) = 4096
write(28, "8.83301       6868.00049\n   6869"..., 4096) = -1 EAGAIN 
(Resource temporarily unavailable)
read(0, ".50000       9956.83301       99"..., 4096) = 2847
read(0, "", 4096)                       = 0
write(28, "8.83301       6868.00049\n   6869"..., 4096) = 4096
write(28, ".83301       6931.00049\n   6932."..., 4096) = -1 EAGAIN 
(Resource temporarily unavailable)
write(28, ".83301       6931.00049\n   6932."..., 4096) = 4096
write(28, "83301       6994.00049\n   6995.6"..., 4096) = -1 EAGAIN 
(Resource temporarily unavailable)
read(0, "", 4096)                       = 0
```

i noted that
  - the 46 `4096` characters full chunks and the remaining `2847` 
characters chunk are not written to the pipe
  - after `read(0, ...)` returns `0`, there is yet an other attempt to 
`read(0, ...)`


here is my test program (note this does not have to be a MPI app)

```fortran
program bar
   IMPLICIT NONE
   !
   INTEGER :: ierr
   INTEGER :: stdtmp
   CHARACTER(LEN=512) :: dummy
   INTEGER, PARAMETER :: stdin  = 5    ! unit connected to standard input
   INTEGER, PARAMETER :: stdout = 6    ! unit connected to standard output

   !
   !
      OPEN(UNIT = stdtmp, FILE="output", FORM='formatted', &
           STATUS='unknown', IOSTAT = ierr )
      IF ( ierr > 0 ) GO TO 30
      !
      dummy=' '
      WRITE(stdout, '(5x,a)') "Waiting for input..."
      DO WHILE ( TRIM(dummy) .NE. "MAGICALME" )
         READ (stdin,fmt='(A512)',END=20) dummy
         WRITE (stdtmp,'(A)') trim(dummy)
      END DO
      !
20   CLOSE ( UNIT=stdtmp, STATUS='keep' )
30   write (*,*) 'done'
end program
```

my `input` file is at https://gist.github.com/ggouaillardet/c9aefedf9a4372f7a7fa43158464256f

the simply `mpirun -np 1 a.out < input`

`input` and `output` files should be identical (which is the case when `mpirun` is not used)

@rhc54 can you please take a look at it ?

**Comment by ggouaillardet** [comment]
@rhc54 i just read your email to `devel-core` and will hence re-assign this to myself

**Comment by ggouaillardet** [comment]
here is a patch that seems to fix the issue

```patch
diff --git a/orte/mca/iof/hnp/iof_hnp_read.c b/orte/mca/iof/hnp/iof_hnp_read.c
index 1e30ac5..237be2a 100644
--- a/orte/mca/iof/hnp/iof_hnp_read.c
+++ b/orte/mca/iof/hnp/iof_hnp_read.c
@@ -14,6 +14,8 @@
  *                         reserved.
  * Copyright (c) 2014-2017 Intel, Inc.  All rights reserved.
  * Copyright (c) 2017      Mellanox Technologies. All rights reserved.
+ * Copyright (c) 2018      Research Organization for Information Science
+ *                         and Technology (RIST).  All rights reserved.
  * $COPYRIGHT$
  *
  * Additional copyrights may follow
@@ -202,6 +204,12 @@ void orte_iof_hnp_read_local_handler(int fd, short event, void *cbdata)
 
         /* if num_bytes was zero, or we read the last piece of the file, then we need to terminate the event */
         if (0 == numbytes) {
+            if (0 != opal_list_get_size(&proct->stdinev->wev->outputs)) {
+                /*
+                 * some stuff has to be sent, so make sure the next OBJ_RELEASE() won't get lose that nor close any fd
+                 * also, we won't ORTE_IOF_READ_ACTIVATE(mca_iof_hnp_component.stdinev) for nothing anymore */
+                OBJ_RETAIN(proct->stdinev->wev);
+            }
             /* this will also close our stdin file descriptor */
             OBJ_RELEASE(proct->stdinev);
         } else {
```

incidentally, i noted the `iof_base_input_files` option looks unused.
Though the MCA parameter value is stored, it is never used.

Is this something we should fix or remove ?

imho, an interesting option would be to have the MPI task(s) directly use a file instead of `stdin` (e.g. do not use `iof`).
Though `mpirun ... < file` should work, we generally advise to use an app parameter (when available) instead of using `stdin`. If this option was implemented in `mpirun`, that could save us a few times.

**Comment by rhc54** [comment]
@ggouaillardet I'm not sure I understand the patch. You are retaining the wev write event, but releasing the stdinev object that holds the wev in the very next line? At the very least, doesn't that leak the wev?

If input_files is unused, feel free to go ahead and remove it - I honestly don't recall its purpose.

We have been advising users to not redirect stdin for more than a decade - yet some still persist. Sigh. I'm not sure what option for mpirun you are proposing - are you talking about having mpirun read a file and forward it to a target proc's stdin? If so, I have no objection, though I don't know how many people will use it.

**Comment by ggouaillardet** [comment]
@rhc54 thanks for your time !

I initially thought there would be a memory leak, but I was happily surprised the `wev` write event gets released (and destroyed) somewhere else.

I will double check the status of `input_files` on other branches, and if the handling was not removed accidentally, i will simply remove the option.

The option I am suggesting is __not__ to involve `iof` any more.
instead of 
```
mpirun a.out < input
```
the new
```
mpirun -i input a.out
```
would (I oversimplify)
```
mpirun sh -c 'a.out < input'
```

`mpirun` or `orted` would (so to speak) `dup2(inputfile, 0)` before `exec`'ing `a.out` on the required ranks.
That would obviously only work if the input file is available on these ranks, but that would decrease the load of `mpirun` (and `orted` too when `stdin` has to be forwarded on ranks not running where `mpirun` is invoked).

**Comment by rhc54** [comment]
I don't think you can do that redirection as the input file typically is not available on the compute node, which is why someone is forwarding it. However, having mpirun read the file instead of getting it thru the stdin straw (with all the pty etc. issues) would be more reliable.

**Comment by ggouaillardet** [comment]
back to the `input_files` thing, it is used by the `iof/mr_hnp` component on the `v2.x` branch, but this component is no more in `master` nor the `v3` branches, so I will remove the option.

I understand the input file __might not__ be available on the compute nodes, so in order to cover all cases, we need someone (and `mpirun` is the perfect candidate) to do the forwarding.
In the case of Quantum Espresso, an end user suggested to use the app command line to pass the input file) e.g.
```
mpirun qe -i input
```
instead of
```
mpirun qe < input
```
so that suggests the input file is available on the compute nodes.
I was simply offering an option to have Open MPI do it when the app cannot do it natively, and reduce the load on `mpirun`, `orted` and the network at the same time.

Anyway, I am fine dropping that idea.
Out of curiosity, don't we avoid the pty issues by having the end user
```
mpirun a.out < input
```
instead of
```
cat input | mpirun a.out
```

**Comment by rhc54** [comment]
Yeah, we dropped map/reduce support, so go ahead and remove that option.

Agree that dropping the idea might be the right thing to do for now - keep things simple. The app can always take the input file on its cmd line.

I agree about the pty thing, but unfortunately users do the latter cmd as well - it's a jungle out there ☹️

**Comment by ggouaillardet** [comment]
ok, i removed the option and PR vs the `v3.1.x` branch at open-mpi/ompi#4756

i found an issue with my patch. `proct->stdinev` is used after being `OBJ_RELEASE()`'ed, so i will rework it.

**Comment by ggouaillardet** [comment]
here is a new revision of the fix
```patch
diff --git a/orte/mca/iof/base/base.h b/orte/mca/iof/base/base.h
index af664cd..8444615 100644
--- a/orte/mca/iof/base/base.h
+++ b/orte/mca/iof/base/base.h
@@ -105,6 +105,7 @@ typedef struct {
     orte_iof_write_event_t *wev;
     bool xoff;
     bool exclusive;
+    bool closed;
 } orte_iof_sink_t;
 ORTE_DECLSPEC OBJ_CLASS_DECLARATION(orte_iof_sink_t);
 
diff --git a/orte/mca/iof/base/iof_base_frame.c b/orte/mca/iof/base/iof_base_frame.c
index 8b21b26..3efa63d 100644
--- a/orte/mca/iof/base/iof_base_frame.c
+++ b/orte/mca/iof/base/iof_base_frame.c
@@ -241,6 +241,7 @@ static void orte_iof_base_sink_construct(orte_iof_sink_t* ptr)
     ptr->wev = OBJ_NEW(orte_iof_write_event_t);
     ptr->xoff = false;
     ptr->exclusive = false;
+    ptr->closed = false;
 }
 static void orte_iof_base_sink_destruct(orte_iof_sink_t* ptr)
 {
@@ -305,7 +306,6 @@ static void orte_iof_base_write_event_construct(orte_iof_write_event_t* wev)
 }
 static void orte_iof_base_write_event_destruct(orte_iof_write_event_t* wev)
 {
-    fprintf(stderr, "destroying %p\n", wev);
     opal_event_free(wev->ev);
     if (ORTE_PROC_IS_HNP && NULL != orte_xml_fp) {
         int xmlfd = fileno(orte_xml_fp);
diff --git a/orte/mca/iof/hnp/iof_hnp.c b/orte/mca/iof/hnp/iof_hnp.c
index 2d4bdf3..ca38472 100644
--- a/orte/mca/iof/hnp/iof_hnp.c
+++ b/orte/mca/iof/hnp/iof_hnp.c
@@ -13,7 +13,7 @@
  * Copyright (c) 2007      Cisco Systems, Inc.  All rights reserved.
  * Copyright (c) 2011-2013 Los Alamos National Security, LLC.  All rights
  *                         reserved.
- * Copyright (c) 2014-2017 Research Organization for Information Science
+ * Copyright (c) 2014-2018 Research Organization for Information Science
  *                         and Technology (RIST). All rights reserved.
  * Copyright (c) 2016-2017 Intel, Inc. All rights reserved.
  * Copyright (c) 2017      Mellanox Technologies. All rights reserved.
@@ -629,6 +629,10 @@ static void stdin_write_handler(int fd, short event, void *cbdata)
             ORTE_IOF_READ_ACTIVATE(mca_iof_hnp_component.stdinev);
         }
     }
+    if (sink->closed && 0 == opal_list_get_size(&wev->outputs)) {
+        /* the sink has already been closed and everything was written, time to release it */
+        OBJ_RELEASE(sink);
+    }
     return;
   finish:
     OBJ_RELEASE(wev);
diff --git a/orte/mca/iof/hnp/iof_hnp_read.c b/orte/mca/iof/hnp/iof_hnp_read.c
index 1e30ac5..7864bb4 100644
--- a/orte/mca/iof/hnp/iof_hnp_read.c
+++ b/orte/mca/iof/hnp/iof_hnp_read.c
@@ -14,6 +14,8 @@
  *                         reserved.
  * Copyright (c) 2014-2017 Intel, Inc.  All rights reserved.
  * Copyright (c) 2017      Mellanox Technologies. All rights reserved.
+ * Copyright (c) 2018      Research Organization for Information Science
+ *                         and Technology (RIST).  All rights reserved.
  * $COPYRIGHT$
  *
  * Additional copyrights may follow
@@ -202,8 +204,13 @@ void orte_iof_hnp_read_local_handler(int fd, short event, void *cbdata)
 
         /* if num_bytes was zero, or we read the last piece of the file, then we need to terminate the event */
         if (0 == numbytes) {
-            /* this will also close our stdin file descriptor */
-            OBJ_RELEASE(proct->stdinev);
+            if (0 != opal_list_get_size(&proct->stdinev->wev->outputs)) {
+                /* some stuff has yet to be written, so delay the release of proct->stdinev */
+                proct->stdinev->closed = true;
+            } else {
+                /* this will also close our stdin file descriptor */
+                OBJ_RELEASE(proct->stdinev);
+            }
         } else {
             /* if we are looking at a tty, then we just go ahead and restart the
              * read event assuming we are not backgrounded
```

**Comment by rhc54** [comment]
Looks much better - thx!

**Comment by ggouaillardet** [comment]
The fix has been merged into `master` and both `v3` branches.
