### ISSUE TITLE
PMIx external component code not auto-generated

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#4771]
I'm seeing this on master as well as 3.1. The external PMIx component corresponding to the embedded version in the opal/pmix framework auto-generates its component code from the embedded plugin. This works fine under default build conditions, but fails when ```--enable-static --disable-shared```.

I suspect this is just an issue of the Makefile.am code to generate the files not running in static builds, but I'm not enough of an expert to tell.

@ggouaillardet Can you please take a look?

**Comment by ggouaillardet** [comment]
@rhc54 i am now trying this
```patch
diff --git a/opal/mca/pmix/ext3x/Makefile.am b/opal/mca/pmix/ext3x/Makefile.am
index c13fa42..61da6be 100644
--- a/opal/mca/pmix/ext3x/Makefile.am
+++ b/opal/mca/pmix/ext3x/Makefile.am
@@ -1,7 +1,7 @@
 #
 # Copyright (c) 2014-2017 Intel, Inc. All rights reserved.
 # Copyright (c) 2015      Cisco Systems, Inc.  All rights reserved.
-# Copyright (c) 2015      Research Organization for Information Science
+# Copyright (c) 2015-2018 Research Organization for Information Science
 #                         and Technology (RIST). All rights reserved.
 # Copyright (c) 2017      IBM Corporation.  All rights reserved.
 # $COPYRIGHT$
@@ -63,6 +63,7 @@ mca_pmix_ext3x_la_LIBADD = $(top_builddir)/opal/lib@OPAL_LIB_PREFIX@open-pal.la
 
 noinst_LTLIBRARIES = $(component_noinst)
 libmca_pmix_ext3x_la_SOURCES =$(sources)
+nodist_libmca_pmix_ext3x_la_SOURCES = $(nodist_sources)
 libmca_pmix_ext3x_la_CFLAGS = $(opal_pmix_ext3x_CFLAGS)
 libmca_pmix_ext3x_la_CPPFLAGS = $(opal_pmix_ext3x_CPPFLAGS)
 libmca_pmix_ext3x_la_LDFLAGS = -module -avoid-version $(opal_pmix_ext3x_LDFLAGS)
```

**Comment by ggouaillardet** [comment]
i pushed open-mpi/ompi@0285c633483c5635dc73fcf3336e6485d98ad255 to fix that.
i also pushed open-mpi/ompi@0481277e93490fd89c8a005beb7c5a8f6263ed01, and issued #4775 so `pmix/ext3x` can be built (regardless static vs dynamic library)

**Comment by bwbarrett** [comment]
@ggouaillardet, is the merge in 4782 sufficient for closing this bug?

**Comment by ggouaillardet** [comment]
@bwbarrett yes, we are good and I am no closing this issue.
