### ISSUE TITLE
asm test suite failures - atomic_cmpset

### ISSUE THREAD

**Issue by opoplawski** [open-mpi/ompi#478]
Building openmpi dev-1330-g7640507 on Fedora Rawhide i686 I get:

```
FAIL: atomic_cmpset
===================

atomic_cmpset: atomic_cmpset.c:224: main: Assertion `opal_atomic_add_32(&val32, 5) == (42 + 5)' failed.

FAIL: atomic_cmpset_noinline
============================

atomic_cmpset_noinline: atomic_cmpset_noinline.c:224: main: Assertion `opal_atomic_add_32(&val32, 5) == (42 + 5)' failed.
```

Also seeing (may not be related):

```
make[4]: Entering directory '/builddir/build/BUILD/openmpi-dev-1330-g7640507/test/asm'
basename: extra operand '--test-name'
Try 'basename --help' for more information.
```

**Comment by hjelmn** [comment]
Weird. Is this also with gcc 5?

**Comment by opoplawski** [comment]
yes

**Comment by hjelmn** [comment]
Can't reproduce on OSX with GCC 5 20150315 on x86_64. Will try on Ubuntu Linux 14.04.2.

**Comment by hppritcha** [comment]
where are we on this issue?

**Comment by jsquyres** [comment]
The failure of atomics in this bug is likely related to/causing the vader failure in #473.

**Comment by hjelmn** [comment]
@opoplawski Which gcc snapshot produced this failure? I can't reproduce with the latest.

**Comment by opoplawski** [comment]
Just fired off another test build: http://koji.fedoraproject.org/koji/taskinfo?taskID=9315351  And the i386 tests are still failing, see https://kojipkgs.fedoraproject.org//work/tasks/5354/9315354/build.log.  x86_64 is fine.

This is with openmpi-dev-1364-gf588ad7 and gcc 5.0.0-0.21.fc23.  Hard to tell what's in the Fedora gcc build, as they pull in some extra stuff -but looks like mostly svnrev 221517 date 20150319

**Comment by hjelmn** [comment]
Thanks. I have only tested x86_64. I will give i386 a try tonight and see if I can reproduce the failure.

Were the vader failures with i386 as well?

**Comment by opoplawski** [comment]
Yes, the vader issues are only see on i386 as well

**Comment by hjelmn** [comment]
I was able to reproduce the bug with gcc 5 with the -m32 option. Looking at the disassembled binary this is clearly a gcc bug. I will provide more details tomorrow.

**Comment by hjelmn** [comment]
Actually, this *is* an Open MPI bug. We are using the = constraint modifier for a read/write operand. This combined with aggressive optimization is what is causing the problem.

Fixing now.

**Comment by opoplawski** [comment]
I can confirm that the commit appears to fix the atomic tests on i386 for me.
