### ISSUE TITLE
MPI_Comm_spawn_multiple Fortran bindings

### ISSUE THREAD

**Issue by ggouaillardet** [open-mpi/ompi#4788]
The `spawn_argvsnull_mpifh` test from the `ibm` test suite occasionally crashes.

The test program declares
```fortran
    integer, parameter :: count = 2
    character(512) :: commands(2)
```
and then
```fortran
    call mpi_comm_spawn_multiple(count, commands, ...)
```

so far, that is pretty much like the example 10.2 from MPI 3.1 standard at page 387.

The standard says
> MPI_COMM_SPAWN_MULTIPLE(count, array_of_commands, ...)
IN count number of commands (positive integer, significant to MPI only at root | see advice to users)
IN array_of_commands programs to be executed (array of strings, significant only at root)

> Advice to users. The argument count is interpreted by MPI only at the root, as is
array_of_argv. Since the leading dimension of array_of_argv is count, a non-positive
value of count at a non-root node could theoretically cause a runtime bounds check
error, even though array_of_argv should be ignored by the subroutine. If this happens,
you should explicitly supply a reasonable value of count on the non-root nodes. (End
of advice to users.)

```fortran
MPI_COMM_SPAWN_MULTIPLE(COUNT, ARRAY_OF_COMMANDS, ...)
INTEGER COUNT
CHARACTER*(*) ARRAY_OF_COMMANDS(*)
```

note Fortran 2008 bindings are consistent with older Fortran bindings.

Unless I overlooked it, the standard does __not__ states that `array_of_commands` is an array of `count` "strings", but instead
```fortran
CHARACTER*(*) ARRAY_OF_COMMANDS(*)
```

in `ompi_comm_spawn_multiple_f()` we follow the standard literally, and end up with
```c
    ompi_fortran_argv_f2c(array_commands, cmd_string_len,
                          cmd_string_len, &c_array_commands);
```

So in this case,Open MPI requires the test program declares
```fortran
    character(512) :: commands(3)
    commands(3) = ' '
```
(or any string, empty or with white spaces only).
FWIW, we are lucky most of the time, and that likely explains why the issue never popped up before.

To me, there is something fishy here ...

I would have naively expected the standard states

```fortran
CHARACTER*(*) ARRAY_OF_COMMANDS(COUNT)
```
and we handle `array_of_commands` accordingly in Open MPI.

There might be a rationale for the current standard, but
 - I am surprised it is not described
 - what should happen if `array_of_commands` has less or more that `count` commands ?
 - The Fortran example is incorrect (even if examples are not normative iirc)

Could you please share your thoughts on that ?
Then I will be happy to report it to the MPI Forum if needed.

**Comment by bosilca** [comment]
You are right, the standard is not clear on the commands. The ```array_of_commands``` should be of type ```array_of_commands(count)``` similarly to ```array_of_argv```. We should bring this to the Forum attention.

**Comment by ggouaillardet** [comment]
Thanks George !

I reported this to the MPI Forum at https://lists.mpi-forum.org/pipermail/mpi-comments/2018-February/000260.html

**Comment by jsquyres** [comment]
I think Bill Long agreed with Gilles: https://lists.mpi-forum.org/pipermail/mpiwg-fortran/2018-February/003544.html

**Comment by ggouaillardet** [comment]
my concern is that this answers basically suggests the examples are normative. Also, there is no plan on whether the standard should be clarified/reworded and the signature should be updated or not.

But yes, we agree on what the MPI standard _should_ be, so let's not overthink it and merge and backport the PRs.

**Comment by jsquyres** [comment]
Agreed.  I think the Forum's response is "We'd love to see your pull request" (with new text).  😄 

I think there's two options:

1. Just add a small amount of text stating that `array_of_commands` is of length `count`.
1. Change the prototype to be `array_of_commands(count)`

I think the 2nd option has terrible backwards compatibility issues.  So the first option is likely both the easiest and the best.  My $0.02.
