### ISSUE TITLE
btl-portals4 segfaults when running osu_latency

### ISSUE THREAD

**Issue by tkordenbrock** [open-mpi/ompi#4801]
On the OMPI users mailing list, Brian Larkins reported a segfault in btl-portals4 when running osu_latency.

The problem is a series of add_procs()/del_procs() calls that cause btl-portals4 to free top level Portals4 resources.  Any additional add_procs() calls will trigger the segfault.

Brian reported this problem using v3.0.0, but it also exists on master and v3.1.x.

**Comment by awlauria** [comment]
PR's merged. Closing.
