### ISSUE TITLE
Relative path in output redirection

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#4806]
## Background information

I am using the `--output-filename` parameter to redirect the output of my application processes into individual files in a relative output directory. The working directory is a subdirectory of my home directory mounted via NFS. Output redirection seems to work correctly for all processes running on the first node (the node that runs rank 0) while all other processes create output directories in $HOME (instead of the subdirectory).

### What version of Open MPI are you using?
OpenMPI 3.0.0 installed from release tarball (also reproducible with 2.1.1)

-----------------------------

## How to reproduce:
```
# two procs, one per node
~/test $ mpirun -n 2 -N 1 --output-filename output.log ls
output.log
output.log
~/test $ ls output.log/*
rank.0

# two procs, single node
~/test $ mpirun -n 2 -N 2 --output-filename output.log ls
output.log
output.log
~/test $ ls output.log/*
rank.0  rank.1
```
Notice that in the first case the output from rank 1 is missing in the folder `output.log`.

I should note that I sometimes observe the following error when running the application directly in the $HOME directory: 
```
$ mpirun -n 2 -N 1 --output-filename output.log ls
[n121301:25598] [[60171,0],1] ORTE_ERROR_LOG: File open failure in file
/path/to/mpi/openmpi/3.0.0-intel-17.0.4/openmpi-3.0.0/orte/mca/iof/base/iof_
base_setup.c at line 314
[n121301:25598] [[60171,0],1] ORTE_ERROR_LOG: File open failure in file
/path/to/mpi/openmpi/3.0.0-intel-17.0.4/openmpi-3.0.0/orte/mca/iof/orted/iof
_orted.c at line 184
[n121301:25598] [[60171,0],1] ORTE_ERROR_LOG: File open failure in file
/path/to/mpi/openmpi/3.0.0-intel-17.0.4/openmpi-3.0.0/orte/mca/iof/base/iof_
base_setup.c at line 237
[n121301:25598] [[60171,0],1] ORTE_ERROR_LOG: File open failure in file
/path/to/mpi/openmpi/3.0.0-intel-17.0.4/openmpi-3.0.0/orte/mca/odls/base/odl
s_base_default_fns.c at line 1147
```

A workaround is to specify an absolute path to `--output-filename`.

**Comment by hppritcha** [comment]
forgot to close when #4809 was merged
