### ISSUE TITLE
PMIx/v2.1 mca/ptl early release bug

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#4830]
Open it here to keep track. 
@bwbarrett @jsquyres @jjhursey @jladd-mlnx this is a blocker for v3.1 - we observed the issue with OMPI v3.1 testing.
The fix is pending the check/review in PMIx/master (https://github.com/pmix/pmix/pull/673), will need to port it to PMIx/v2.1 and bring it here.

**Comment by artpol84** [comment]
PMIx/master PR is merged.
v2.1 is filed: https://github.com/pmix/pmix/pull/674

**Comment by artpol84** [comment]
PMIx/v2.1 PR is merged so PMIx side is fixed.
@bwbarrett @jsquyres what is the preferred way to bring this into OMPI v3.1? Port the commit or create a huge PR similar to #4746?

**Comment by rhc54** [comment]
Huge PR??? There aren't very many changes in going from PMIx v2.1.0 to v2.1.1 - so why would this be "huge"?

**Comment by rhc54** [comment]
Yeah, I think they would be better off as there were a few bugs found since we released v2.1.0 - might as well sweep them all up. However, it is up to them. I just wanted to clarify that it shouldn't be a large amount of change, which is what your earlier comment implied.

**Comment by artpol84** [comment]
Thank you for the information @rhc54.

**Comment by artpol84** [comment]
Sync v2.1:
https://github.com/open-mpi/ompi/pull/4831

**Comment by artpol84** [comment]
Fix is in v3.1.x, issue can be closed.
