### ISSUE TITLE
MPI_OFFSET_KIND defined differently than in MPICH on 32bit architectures

### ISSUE THREAD

**Issue by rathann** [open-mpi/ompi#4846]
## Background information
MPI_OFFSET_KIND=4 in OpenMPI while it equals 8 in MPICH on 32bit arches. I don't know which is correct, but this difference has caused compilation issues in cp2k-5.1 with MPICH:
```
[...]
/builddir/build/BUILD/cp2k-5.1/src/mpiwrap/message_passing.F:3588:70:
                                     type_descriptor%type_handle, ierr)
                                                                      1
Error: Type mismatch in argument 'array_of_displacements' at (1); passed INTEGER(8) to INTEGER(4)
[...]
```

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
openmpi-2.1.1-5.fc28.i686

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Fedora package.

### Please describe the system on which you are running

* Operating system/version: Fedora rawhide (development branch)
* Computer hardware: 32-bit x86 and ARM (i686 and armv7hl)
* Network type: N/A

-----------------------------

## Details of the problem
Steps to Reproduce:
1. `grep MPI_OFFSET_KIND= mpich-i386/mpif.h mpich-i386/mpiof.h openmpi-i386/mpif-config.h`

Actual results:
```
mpich-i386/mpif.h:       PARAMETER (MPI_OFFSET_KIND=8)
mpich-i386/mpiof.h:      PARAMETER (MPI_OFFSET_KIND=           8)
openmpi-i386/mpif-config.h:      parameter (MPI_OFFSET_KIND=4)
```

Expected results:
The value should be the same across MPI implementations.

Additional info:
https://lists.cp2k.org/private/cp2k-dev/2018-January/000856.html
https://bugzilla.redhat.com/show_bug.cgi?id=1535966

**Comment by ggouaillardet** [comment]
Thanks for the report.

I checked the MPI 3.1 standard and found

> 2.5.7 File Offsets
> For I/O there is a need to give the size, displacement, and offset into a file. These quantities
> can easily be larger than 32 bits which can be the default size of a Fortran integer. To
> overcome this, these quantities are declared to be INTEGER (KIND=MPI_OFFSET_KIND) in
> Fortran. In C one uses MPI_Offset. These types must have the same width and encode
> address values in the same manner such that offset values in one language may be passed
> directly to another language without conversion.

As far as I understand, it kind of suggests `MPI_OFFSET_KIND=8` but it only requires `MPI_OFFSET_KIND` and `sizeof(MPI_Offset)` are identical. Could you please double check this is the case ?

As far as `cp2k` is concerned,
```fortran
#if __MPI_VERSION > 2
   INTEGER, PARAMETER, PUBLIC :: file_offset = MPI_OFFSET_KIND
#else
   INTEGER, PARAMETER, PUBLIC :: file_offset = int_8
#endif
```
so, assuming `4 == sizeof(MPI_Offset)`, the error could be in `cp2k`.

@jsquyres @bosilca could you please comment ?

**Comment by bosilca** [comment]
@ggouaillardet is right, the only thing imposed/required by the MPI standard is that the 2 values are in sync. In OMPI we define MPI_Offset to be of the same length as MPI_Count, which is defined to be an size_t (to match the type of the size argument in read). So, the type of the MPI_Offset depends on the size of size_t on the target platform.

**Comment by rathann** [comment]
Referring to [glibc](https://www.gnu.org/software/libc/manual/html_node/File-Positioning.html), I think this should be the same type as the POSIX `off_t` and, possibly, it should depend on `_FILE_OFFSET_BITS` system define value.

**Comment by ggouaillardet** [comment]
@rathann `MPI_OFFSET_KIND` must comply to the MPI standard, no more, no less.
It **could** be similar to `off_t`, and I can clearly see a rationale for that, but the standard does not mandate that.
Note `_FILE_OFFSET_BITS` is checked when Open MPI is built, so if `MPI_Offset` is equivalent to `off_t`, you would have to make sure the `_FILE_OFFSET_BITS` macro is the same when Open MPI was built and when you are building your application. IMHO, this would be very error prone.

**Comment by rathann** [comment]
It looks like this is actually a duplicate of https://github.com/open-mpi/ompi/issues/3195 .
