### ISSUE TITLE
mpirun launch on cray broken (general case)

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#487]
mpirun based launch on cray is currently broken unless the system is configured to have LDAP or other authentication available on the compute nodes.

@hjelmn

**Comment by hppritcha** [comment]
@rhc54 

If you can get usock to work when getpwuid isn't available that would suffice to solve this problem.
Be aware however, that some cray customers don't allow one to use writeable tmp.  There are alternatives but I'd need to give you pointers on that.

Nathan, are you really able to run current master HEAD on cielito?  Does cielito project LDAP to the compute nodes?

**Comment by rhc54** [comment]
I confess I'm scratching my head a bit as I can't find any reference to getpwuid in the usock code. It does, however, require that the session directories are available so we have a place to put the named pipe. Are you not allowing session directories to be built? If so, where do you put things that are session-specific?

**Comment by hjelmn** [comment]
Not sure why getpwuid works on Cielito. Didn't encounter a Cray system where it didn't work until Edison.

I don't like using getpwuid just to get a unique name for the session directories. The uid is sufficient for our support needs. Do Open MPI users really need/want the username in the name of the session directory? If that still is the case we should add logic to disable getpwuid if running on a Cray system.

**Comment by rhc54** [comment]
We have all the #if’s in there for that purpose - all you have to do is set —disable-getpwuid. We have always had a username in the session directory to avoid conflicts, but we can revisit it at some point

**Comment by hppritcha** [comment]
tested master on edison and mpirun based launch works again.  usock is working now.
thanks Ralph.  closing.
