### ISSUE TITLE
Make command doesn't work

### ISSUE THREAD

**Issue by Pulsar18** [open-mpi/ompi#4870]
I am trying to install OpenMPI and I have run into the following problem:
[output terminal.txt](https://github.com/open-mpi/ompi/files/1771507/output.terminal.txt)
The configure step finished without an error. The corresponding log file is here:
[config.log](https://github.com/open-mpi/ompi/files/1771512/config.log)
(I am using gcc-mp-6 because I couldn't install gcc6 via brew.
Furthermore, I am following this tutorial on the web:
https://wiki.helsinki.fi/display/HUGG/Open+MPI+install+on+Mac+OS+X)
Any help would be much appreciated.

**Comment by bwbarrett** [comment]
This is caused by an interaction between GCC and MacOS, as described in https://github.com/open-mpi/ompi/issues/4373.  We will have a "fix" in Open MPI 3.0.1, by disabling syslog support in those cases.
