### ISSUE TITLE
Possible illegal memory access in ompi_request_default_wait_some

### ISSUE THREAD

**Issue by AndrewGaspar** [open-mpi/ompi#4896]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
```
pn1707994:scratch agaspar$ port info openmpi
openmpi @3.0.0 (science, parallel, net)
```

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Installed via MacPorts

### Please describe the system on which you are running

* Operating system/version: macOS Sierra
* Computer hardware: MacBook Pro (2017)
* Network type: running only on host (shared memory?)

-----------------------------

## Details of the problem
`ompi_request_default_wait_some` is writing to `array_of_indices` past `outcount`. See [this loop](https://github.com/open-mpi/ompi/blob/master/ompi/request/req_wait.c#L422) in req_wait.c.

The MPI v3.1 spec [seems to indicate](https://github.com/mpi-forum/mpi-issues/issues/86#issuecomment-371645898) that `array_of_indices` should not be written to past the value of `outcount`, and does not explicitly state that `array_of_indices` is of size `incount`. The user could reasonably expect that they need not pass an `array_of_indices` larger than the number of _active_ requests in `array_of_requests`.

**Comment by hjelmn** [comment]
@bosilca What do you think?

**Comment by bosilca** [comment]
From MPI perspective the maximum number of completed request is bounded only by the number of input requests, and thus the most logical size for the array_of_indices and array_of_status must be equal to the number of input requests.

The MPI standard makes clear reference to what the user should expect in the array_of_indices and array_of_status upon return of the 2 incriminated function. It said nothing about how MPI can use this array internally.

The code this issue make reference is an optimization that uses the array_of_indices to decrease the number of atomic operations. My take is that the current behavior of OMPI is reasonable.

**Comment by AndrewGaspar** [comment]
> From MPI perspective the maximum number of completed request is bounded only by the number of input requests, and thus the most logical size for the array_of_indices and array_of_status must be equal to the number of input requests.

My only issue with this statement is that I think it's missing one word: it should be "is bound only by the number of **active** input requests" - you can't complete requests that are not active.

**Comment by AndrewGaspar** [comment]
I'm also not quite sure I understand the optimization - couldn't you change the atomic exchange from

```c
        indices[i] = OPAL_ATOMIC_COMPARE_EXCHANGE_STRONG_PTR(&request->req_complete, &_tmp_ptr, &sync);
        if( !indices[i] ) {
            /* If the request is completed go ahead and mark it as such */
            assert( REQUEST_COMPLETE(request) );
            num_requests_done++;
        }
```
to


```c
        bool is_pending = OPAL_ATOMIC_COMPARE_EXCHANGE_STRONG_PTR(&request->req_complete, &_tmp_ptr, &sync);
        if( !is_pending ) {
            /* If the request is completed go ahead and mark it as such */
            assert( REQUEST_COMPLETE(request) );
            indices[num_requests_done++] = i;
        }
```

Then in the post-SYNC_WAIT loop, you should be able to efficiently check if the request has already been completed - since the `indices` array is sorted, you should be able to change this check:

```c
        if( !indices[i] ){
            indices[num_requests_done++] = i;
        } else if( !OPAL_ATOMIC_COMPARE_EXCHANGE_STRONG_PTR(&request->req_complete, &_tmp_ptr, REQUEST_PENDING) ) {
            indices[num_requests_done++] = i;
        }
```

to (pseudo-ish code)

```c
        if ( i_requests_done != num_requests_done && indices[i_requests_done] == i ) {
            // The request was marked as completed prior to synchronization and is already in indices
            // i_requests_done is initialized to 0 at beginning of loop
            i_requests_done++;
            continue;
        }

        if( !OPAL_ATOMIC_COMPARE_EXCHANGE_STRONG_PTR(&request->req_complete, &_tmp_ptr, REQUEST_PENDING) ) {
            // num_requests_done would not be re-initialized to 0 like it is now
            indices[num_requests_done++] = i;
        }
```

I _think_ that would allow you to do the same number of atomic compare exchanges without having to write past `outcount`. I might be missing something, though.

**Comment by bosilca** [comment]
You are willingly doing tests on non active requests and you complain that MPI assumes that all requests could potentially be completed ?

The code you propose might work, but the result is not a monotonically increasing array_of_indices. I put up a PR #4897, lightly tested at this point to address your concern. That being said I am not convinced by its need, but the patch was trivial.

**Comment by AndrewGaspar** [comment]
> You are willingly doing tests on non active requests and you complain that MPI assumes that all requests could potentially be completed ?

Isn't that how `MPI_Waitsome` is typically used? e.g. you have an array of requests and you keep passing it into MPI_Waitsome until all the requests are complete

I imagine most users don't compress the array of requests between each call to MPI_Waitsome.

**Comment by AndrewGaspar** [comment]
> but the result is not a monotonically increasing array_of_indices
I don't think this is required by the standard - is this just desirable so that you get linear memory access when using the indices?

**Comment by bosilca** [comment]
So in your scenario the users do not compress the array of requests, but they do reallocate a smaller array for array_of_indices. Sketchy at best, and certainly suboptimal.

Most scenarios I'm familiar with, all arrays are allocated once and at the max size, and the remaining active requests are indeed packed to minimize the overheads in the MPI library.

**Comment by AndrewGaspar** [comment]
> So in your scenario the users do not compress the array of requests, but they do reallocate a smaller array for array_of_indices. Sketchy at best, and certainly suboptimal.

My specific scenario was that I was trying to preserve the list of existing completed request indices. So you advance the `indices` pointer by `outcount` between each call to `MPI_Waitsome`.

**Comment by jsquyres** [comment]
For cross-reference, this is being discussed at the MPI Forum in https://github.com/mpi-forum/mpi-issues/issues/86.
