### ISSUE TITLE
Improve ompi_info's component detection system

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#49]
ompi_info has a hard-coded list of frameworks that must be manually updated every time a new framework has been added.  This has long-since been noted as an abstraction violation and "icky".  Some idle chat at yesterday's MPI Forum meeting between George, Josh, and myself resulted in thinking of a way to fix this problem and make ompi_info be much more generic:
- Have autogen.sh create a C array of strings of all framework names that is instantiated somewhere (probably in OPAL)
- Add a new MCA base "open all the components" routine (that probably uses much of the same infrastructure as the current "open this framework's components") that does the following:
  - Traverses mca_base_component_paths and opens ''all'' components that it finds (regardless of type)
  - Traverses the autogen.sh-created list of frameworks and lt_dlsym's looking for the framework's symbol of statically linked components
  - Move all framework-level MCA parameter registration out of mca_<framework>_open() functions to a new function: mca_<framework>_register_mca().  lt_dlsym for this symbol for each framework, and call it if it exists
- ompi_info therefore will get a list of ''all'' components which can then be sorted and displayed as appropriate

It may be desirable as part of this process to also separate MCA base component MCA parameter registration from the "open" function (because the "open" function does have a distinct purpose [to be a first-line place to check whether the component wants to run] that is currently munged together with registering component-level MCA parameters.  For backwards compatibility, the MCA base can continue to call the component open function if an MCA register function is not available.

**Comment by jsquyres** [comment]
This was long-since done.  Closing.
