### ISSUE TITLE
Remove async thread from openib BTL

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#491]
The real solution to #490 is to remove the async thread from the openib BTL.

**Comment by jsquyres** [comment]
@hjelmn is waiting for @rh54 to create an OPAL progress thread (i.e., a separate libevent base than the one that is hooked to ompi_progress() / opal_progress(), which is for synchronous progress).

**Comment by jsquyres** [comment]
@hjelmn opal_progress_thread now exists on master -- did you want to tackle this one now?

**Comment by awlauria** [comment]
Openib btl is removed. Closing.
