### ISSUE TITLE
Executable cannot be named test

### ISSUE THREAD

**Issue by blegat** [open-mpi/ompi#4917]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

3.0.0-1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Using the `pacman` package manager or Arch Linux.

### Please describe the system on which you are running

* Operating system/version: Linux 4.15.8-1-ARCH
* Computer hardware: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor
* Network type: Intel Corporation Ethernet Connection (2) I219-LM

-----------------------------

## Details of the problem

Consider the simple code (any code does the same in fact)
```c
#include <mpi.h>

int main(int argc, char* argv[])
{
    MPI_Init(&argc, &argv);
    MPI_Finalize();
    return 0;
}
```
If the executable name chosen is `test`, the following happen:
```shell
shell$ mpicxx main.cpp -o test
shell$ mpirun test
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
shell$ mpiexec test
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
```
The error message is not very helpful (I spent a lot of time trying to figure out what was happening ^^)

**Comment by bosilca** [comment]
```test``` is a UNIX utility (```man test```). When called without an argument it always returns 1. The error message clearly identified the cause of the job creation failure. You can call your application test but then either you make sure your PATH includes your directory before the system ones, or you use a path (```mpirun ./test```).
