### ISSUE TITLE
Window memory alignment not suitable for long double

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#4952]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

Vanilla Open MPI 3.0.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

installed from release tarball using `./configure && make && make install`

### Please describe the system on which you are running

* Operating system/version: Linux Mint 18.3, kernel 4.13.0-36, 64bit
* Computer hardware: Lenovo T460s
* Network type: 

-----------------------------

## Details of the problem

We have recently added support for `long double` to our distributed data structures that are built on top of MPI and found similar crashes to the ones we have reported in https://www.mail-archive.com/users@lists.open-mpi.org/msg30621.html. I have not been able to reproduce this with a small example but some analysis indicates that the memory that is handed out by MPI_Win_allocate is guaranteed to be aligned to 8 Byte while `sizeof(long double)` on my machine is 16 Byte. The clang 5.0 compiler issues `vmovaps` XMM stores to write to `long double` variables, which require the target memory to be aligned to 128 bit boundaries, potentially causing a segmentation fault on non-aligned memory accesses.

AFAICS, since MPI supports `long double` through `MPI_LONG_DOUBLE` the memory that is handed out by MPI functions should meet the requirements of this type. Thus, `MPI_Alloc_mem`, `MPI_Win_allocate`, and `MPI_Win_allocate_shared` should provide memory that is aligned to 16 Byte to avoid this problem.

I originally posted this problem on the user ML where it seems to have gotten lost. Sorry for the double post.

**Comment by bwbarrett** [comment]
I don't think MPI_C_LONG_DOUBLE_COMPLEX would require 32 byte alignment.  It's not a native data type on any architecture that exists today (or is likely to exist in the medium term).  I think always align on 16 bytes is a sane choice.  Neither MPI_ALLOC_MEM nor MPI_WIN_ALLOC are really suitable for lots of small allocations, so padding to 16 bytes is sane enough.  Doing anything with disp_unit seems like insanity to me.

**Comment by ggouaillardet** [comment]
I am fine not doing anything with `disp_unit`.

What about a new MCA parameter for the alignment ?
For example, and for performance reasons, it might be better to align on 64 bytes on `AVX512` capable processors.
I do not have a strong opinion on the default value, and I would be fine with 16 bytes.

**Comment by bosilca** [comment]
I would align all MPI allocated memory to the cache size boundary, and delegate to the user the responsibility to match that to her needs.

**Comment by ggouaillardet** [comment]
@bosilca this information is currently stored in `opal_cache_line_size` on `mpirun` or `orted` (e.g. from the MPI app point of view, is has the default value `128`).

That raises the question, how to get that ?
If `mpirun` is used, that can be passed via the environment, but what about direct run ?
should the MPI app detect the full node topology just to get the cache line size (in my experience, that would be terribly slow when many tasks are running on the same node) ?
or should PMIx be involved (and how) ?

@rhc54 do you have anything to suggest ?

**Comment by bosilca** [comment]
[StackOverflow](https://stackoverflow.com/questions/794632/programmatically-get-the-cache-line-size) has the answer, as usual.

**Comment by jsquyres** [comment]
Doesn't hwloc have this info?  `obj->attr->cache.linesize`

**Comment by ggouaillardet** [comment]
The info is already available on the daemon, but not the app.

We can use an other method to retrieve it, or retrieve it from the daemon.
I an still on the fence regarding which is the best way to achieve that.

**Comment by rhc54** [comment]
When direct launched, or when launched by mpirun prior to HWLOC shared memory support, the apps have to get their own topology, which they do down in opal/hwloc. Thus, they can simply retrieve it directly.

When launched by mpirun, they have access to the topology via HWLOC's shared memory.

So apps do indeed currently have access to the info as @jsquyres described, regardless of how they are launched.

**Comment by ggouaillardet** [comment]
when `mpirun` is used without `--bind-to none`, the HWLOC topology is not retrieved because of some shortcuts is `orte_ess_base_proc_binding`. `srun` is just fine.

I think always retrieving the topology would be an overkill, so I fixed that by using an environment variable in `schizo/ompi`, and I opened #4983 for that purpose (plus some cleanup)

**Comment by hjelmn** [comment]
Regardless of what we decide to do the standard only guarantees malloc-alignment. This is usually 8-byte alignment. It is always up to the user (and the standard is explicit about this for ```MPI_Fetch_and_op()```) to align their datatypes.

```
It is the user’s responsibility to guarantee that, when using the accumulate functions, the target displacement argument is such that accesses to the window are properly aligned according to the data type arguments in the call to the MPI_Fetch_and_op function.
```

**Comment by benmenadue** [comment]
> Regardless of what we decide to do the standard only guarantees malloc-alignment.

I thought `malloc` was guaranteed to be suitably aligned to hold an object of _any_ type (not counting directives to over-align, etc)? If so, since the x86_64 ABI says that `long double` must be 16B aligned, `malloc` (and thus `MPI_Alloc_mem`) should be returning (at least) 16B-aligned addresses.

**Comment by hjelmn** [comment]
Was wrong, the standard doesn't event specify malloc-alignment. It doesn't even mention alignment. So, it looks like we can return 1-byte aligned if we felt like it. And, yes, I stand corrected. On x86_64 the minimum malloc alignment is 16. We probably *should* return that alignment but since it is not required it is still up to the user to align their data.

**Comment by devreal** [comment]
> FWIW, it might be worth modifying the text for MPI_Alloc_mem return memory with the same alignment as requirements as malloc(). I don't know if this has been discussed at the forum before.

Is there an update on this? Has this been discussed at the forum (or maybe will be next week?) 

From a user perspective, it would be helpful to be able to pass a request for a specific alignment to the window allocation function in the form of an info key (I heard yesterday at the wg conf call that there are already multiple new info keys in discussion). The default alignment should match the minimum alignment guarantees of `malloc` (16 Byte) and since the MPI implementation has to ensure alignment anyway it should be easy to incorporate the user's alignment request. Leaving the alignment to the user is certainly an option but would require additional handling and exchange of offsets in the application to make sure one-sided operations do not access memory before the alignment boundary, which seems tedious and error prone. For contiguous shared memory, the alignment would only be relevant for the start of the contiguous memory region.
