### ISSUE TITLE
Make OpenSHMEM not build if a viable SPML is not available

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#4956]
Per discussion in the 2018-03 Dallas Open MPI meeting, we decided to have Open SHMEM decide to not build itself if a viable SPML is not found (at the time of this writing).  We should also emit this decision at the end of `configure` with the rest of the summary information.

This is targeted at v4.0.0.  @bwbarrett volunteered to implement this.

**Comment by gpaulsen** [comment]
@bwbarrett are you working on this?  Is this still on target for v4.0.0 (release in 1 month)?

**Comment by bwbarrett** [comment]
it was done months ago.  Guess I forgot to close the issue.
