### ISSUE TITLE
don't try to build mpool/memkind component against memkind 1.4 or higher

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#4971]
The memkind API was complete rewritten in release 1.4 and is incompatible with the mpool/memkind in all release branches.  Add a configury check to just not compile this component if memkind 1.4 or higher is installed.

**Comment by rhc54** [comment]
@hppritcha Looking at the memkind repo on github, it appears they have been fixing OMPI compile issues internally - they just aren't sharing the fixes. I'll smack them.

**Comment by ggouaillardet** [comment]
@rhc54 my understanding is Open MPI cannot be built with `1.4` <= `memkind` < `1.7`, did I miss something ?

**Comment by rhc54** [comment]
Yes, changes were made to restore backward compatibility. I'm talking with them now.

**Comment by rhc54** [comment]
I'm told that the memkind v1.7.0 release restores the compatibility fixes for OMPI. Waiting to find out when the distros will be picking it up (they now ship 1.4.0).

**Comment by rhc54** [comment]
Here is what I'm discovering. First, I'm trying to convey to them that they need to change the major release number when they break API - not sure that is getting thru, but I'm also given the feeling that there may not be any more memkind releases, or at least nothing anytime soon.

Second, it looks really risky to be using the "experimental" APIs we had in our earlier code, even with them being restored in 1.7.

Given that v1.4 is what is getting shipped in distros, and there is no way to know if/when that will be updated (heck, they didn't pick up 1.5 or 1.6 at all), I'd suggest the following:

1. update master to use the new official APIs in 1.4 and above
1. change the configury to look for a new API that didn't exist prior to 1.4, and disable memkind support if not found
1. backport that to at least the 3.0 series
1. if we want to do something for the 2.x series, I would just disable memkind

**Comment by hppritcha** [comment]
hmm... memkind mpool component isn't present in v2.0.x so removing that label.

**Comment by hppritcha** [comment]
fix merged in to all release branches.  closing.
