### ISSUE TITLE
ompio and MPI_MODE_SEQUENTIAL and NFS

### ISSUE THREAD

**Issue by dshrader** [open-mpi/ompi#4991]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

2.1.2 and 3.0.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

release tarball

### Please describe the system on which you are running

* Operating system/version: RHEL 7
* Computer hardware: Intel Xeon CPUs
* Network type: Intel Omnipath

-----------------------------

## Details of the problem

When using MPI_MODE_SEQUENTIAL in MPI_FILE_OPEN with an NFS target and using ompio, we get the following error:

mca_sharedfp_lockedfile_file_open: Error during file open

Here is a reproducer written in fortran:

```fortran
PROGRAM main
    use mpi

    integer ierr, i, myrank, BUFSIZE, thefile, c50, c22, c19, c16

    call MPI_INIT(ierr)
    call MPI_COMM_RANK(MPI_COMM_WORLD, myrank, ierr)

    call MPI_FILE_OPEN(MPI_COMM_WORLD, 'testfile', &
                       MPI_MODE_WRONLY + MPI_MODE_CREATE + MPI_MODE_SEQUENTIAL, &
                       MPI_INFO_NULL, thefile, ierr)

    call MPI_FILE_CLOSE(thefile, ierr)
    call MPI_FINALIZE(ierr)
END PROGRAM main
```
If the above program is compiled as a.out, here is the output from trying to run it while in a NFS directory:
```shell
shell$ mpirun --map-by ppr:1:node ./a.out
[001.localdomain:151509] mca_sharedfp_lockedfile_file_open: Error during file open
[002.localdomain:36249] mca_sharedfp_lockedfile_file_open: Error during file open
shell$
```
If romio is used instead, the program runs fine:
```shell
shell$ mpirun --map-by ppr:1:node -mca io romio314 ./a.out
shell$
```
If MPI_MODE_SEQUENTIAL is removed from the source, the program runs without an error with both ompio and romio. Running out of lustre also works for both ompio and romio.

**Comment by edgargabriel** [comment]
Thank you for the bug report, I will look into that. I am a bit confused on the usage of MPI_MODE_SEQUENTIAL to be honest, would it be possible to extend the example by at least one additional functional call (write) to see how you are using the file afterwards in your code?

**Comment by edgargabriel** [comment]
to maybe extend on my previous message, I understand what is going on, for the fix it would be good to have an understanding on how the file is subsequently used. Are you using shared file pointers operations afterwards?

**Comment by dshrader** [comment]
Here is a version of the reproducer that does something with the file, but it isn't too complicated. It was an earlier version of the reproducer.

```fortran
PROGRAM main
    use mpi

    integer ierr, i, myrank, BUFSIZE, thefile, c50, c22, c19, c16
    parameter (BUFSIZE=100) 
    integer buf(BUFSIZE) 
    integer(kind=MPI_OFFSET_KIND) disp     

    call MPI_INIT(ierr)
    call MPI_COMM_RANK(MPI_COMM_WORLD, myrank, ierr)

    do i = 0, BUFSIZE 
        buf(i) = myrank * BUFSIZE + i 
    enddo 
    call MPI_FILE_OPEN(MPI_COMM_WORLD, 'testfile', &
                       MPI_MODE_WRONLY + MPI_MODE_CREATE + MPI_MODE_SEQUENTIAL, &
                       MPI_INFO_NULL, thefile, ierr)
    call MPI_FILE_WRITE_ORDERED(thefile,buf,BUFSIZE,MPI_INTEGER, &
                        MPI_STATUS_IGNORE, ierr)

    call MPI_FILE_CLOSE(thefile, ierr)
    call MPI_FINALIZE(ierr)

END PROGRAM main
```

**Comment by dshrader** [comment]
Thank you for taking a look, @edgargabriel!

**Comment by edgargabriel** [comment]
@dshrader thanks, this is a big help!

**Comment by edgargabriel** [comment]
I can confirm that with pr 4997 the code executes correctly.
