### ISSUE TITLE
Add PGI debugger invocation to orte_base_user_debugger MCA param default value

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#5]
From the user's mailing list http://www.open-mpi.org/community/lists/users/2006/07/1558.php, Andrew Caird found that the following command line syntax "mostly" works with the PGI debugger:

```
mpirun --debugger "pgdbg @mpirun@ @mpirun_args@" --debug -np 2 ./cpi 
```

Hence, we can add "pgdbg @mpirun@ @mpirun_args@ to the default value of orte_base_user_debugger so that it will be found automatically and users don't need to specify it.

However, Andrew noted that the PGI debugger doesn't fully support Open MPI yet (right now, it shows some warning message, which may be indicative of deeper problems).  PGI support says that they are [pleasantly] surprised that it works with Open MPI at all, but hope to support Open MPI by the end of the year or so.

This ticket is a placeholder to add the pgdbg value to orte_base_user_debugger once the PGI debugger supports Open MPI.  I don't want to add it before then because it could be misleading to users.

**Comment by gpaulsen** [comment]
I'll do in my spare time.

**Comment by gpaulsen** [comment]
as of #8570, #8571, and #8572 PGI Debugger attach through MPIR has been fixed on current release branches.
master branch now uses PRRTE and prefers the pmix-tool attach approach for modern debuggers.
