### ISSUE TITLE
It should be safe to run "mpiexec -v" as root in version 1.8.2

### ISSUE THREAD

**Issue by rtmclay** [open-mpi/ompi#500]
Switching from version 1.6.5 to 1.8.2, I have found out that root can not run "mpiexec -v" to report the version.  mpiexec for version 1.8.2 report that running "mpiexec -v" as can be a problem and doesn't report the version.    It should still report the version and not produce the error message.

**Comment by rhc54** [comment]
Good point - I've pushed the change to the master, and am scheduling it for 1.8.5 release.

Thanks for bringing it to my attention!
