### ISSUE TITLE
Change configury logic to prefer external hwloc/libevent/pmix

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#5031]
Based on [Dallas March 2018 face-to-face meeting notes](https://github.com/open-mpi/ompi/wiki/Meeting-Minutes-2018-03#everything-else), we want to shift the focus in v4.0.x away from the embedded hwloc, libevent, and pmix to external versions of these libraries.

Specifically, change the configury logic:

1. If user preference for external was specified:
   * Look for external support.
   * If external support is found and is compatible (e.g., the version/API/ABI/whatever is good), use it.
   * Otherwise, abort `configure`
1. If user preference for internal was specified:
   * Use it.
1. If no user preference was specified, look for external support.
   1. If external support is found:
       * If the external version is compatible (e.g., the version/API/ABI/whatever is good):
           * If the external version is `>=` the internal version, use the external version.
           * If the external version is `<` the internal version, emit a warning and use the internal version.
       * If the external version is *not* compatible:
           * Emit a warning and use the internal version.
   1. If external support is *not* found
       * Use the internal version.

Also add relevant `ompi_info` output somewhere indicating whether we are using internal or external versions, and give the reason why.

**Comment by jsquyres** [comment]
The bullets above were initially created from notes from the Dallas March 2018 meeting.  Discussion welcome, especially before I start implementing.  😄

**Comment by ggouaillardet** [comment]
What is the rationale for using the internal version if external version `<` internal version __but__ the external version is compatible ?

At first glance, I would simply print a warning and use the external version.

**Comment by jsquyres** [comment]
Per discussion on 2018-07-10 webex, for PMIx:
* If external PMIx < v1.2.5, it is not compatible
* External PMIx v1.2.5 is *compatible*, but is not *desirable* because there are PMIx v2.0.x features that the OMPI code base uses.

**Comment by jsquyres** [comment]
Note that the current status of master moved a few steps towards this scheme, but it also did a few things that are explicitly *not* in this scheme.

For example, if the external component is configured successfully, it doesn't even try with the internal component -- which is contradictory to https://github.com/open-mpi/ompi/issues/5031#issuecomment-379304676: "The thought there was that if the user didn't specify a preference, then we should just give them the latest version, regardless of whether it is internal or external."

So there is definitely still work to be done.

**Comment by ggouaillardet** [comment]
IIRC, when the end user does not explicitly request anything, the external component version is tested, and is __not__ selected if its version is lower than the embedded component.

**Comment by gpaulsen** [comment]
Can we close this issue now that PR #5472 has been merged to v4.0.x ?
