### ISSUE TITLE
plm/rsh: rank ordering per hosts

### ISSUE THREAD

**Issue by karasevb** [open-mpi/ompi#5043]
The issue observes when running mpirun from the compute node. The rank order per hosts does not match the requested order that settled through `-H`. The rank 0 is assign only for the "mpirun host" instead of the first specified host.

Reproducer:
```
user@cn2
$ mpirun --mca ras_base_verbose 5 --debug-daemons -H cn01:1,cn02:1,cn03:1,cn04:1 ./hello_c
...
    (i, host, exe, pid) = (0, cn02, ./hello_c, 148943)   
    (i, host, exe, pid) = (1, cn01, ./hello_c, 170979) <-- here is expected to assign a rank 0
    (i, host, exe, pid) = (2, cn03, ./hello_c, 42596)
    (i, host, exe, pid) = (3, cn04, ./hello_c, 29560)
...
```
Thanks @ggouaillardet for the report of this issue (https://github.com/open-mpi/ompi/commit/52e81ee4b124172ffe99ebb056cd6cd40221b5cb#commitcomment-28481492)

**Comment by ggouaillardet** [comment]
I guess this is a related issue
```
cn01$ mpirun --host cn01:1,cn02:1,cn01:1,cn02:1 ...
```
starts the first two tasks on `cn01` and the last two on `cn02`,
when the even ranks should be on `cn01` and the odd ranks should be on `cn02`

**Comment by rhc54** [comment]
These statements are actually incorrect. The -H option has never promised to act like the sequential mapper, which is what you are implying. All it does is assign slots to the various nodes.

If the community wants to change that behavior, I would advise a large dose of caution. This would be a completely different behavior than users have ever seen, and will almost certainly break things for a range of people.

**Comment by ggouaillardet** [comment]
Thanks for the insight.

What about the `-machinefile` option ? Should it act like the sequential mapper ?

**Comment by karasevb** [comment]
@rhc54 thanks for the clarification. Let's close this issue.
If someone really wants to change the behavior of the sequential mapper, will open the issue again.
