### ISSUE TITLE
without-lustre build issue

### ISSUE THREAD

**Issue by mdidomenico4** [open-mpi/ompi#5067]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

3.0.1

### Please describe the system on which you are running
* Operating system/version: rhel 7.4 
* Computer hardware: x86_64

## Details of the problem

./configure --prefix=/openmpi --disable-oshmem --without-slurm --without-lustre

make -j 4 && make install
...snipped...
CCLD libmca_fs_lustre.la
../../../../libtool: line 7489: cd: no/lib: No such file or directory
libtool: error: cannot determine absolute directory name of 'no/lib'

**Comment by jsquyres** [comment]
Do you have a space in your source or build tree directory name?

Open MPI's configure/build system probably does not handle spaces well.

**Comment by mdidomenico4** [comment]
there are no spaces

the resulting Makefiles seemed to have this added

fs_lustre_LDFLAGS = -Lno/lib
OMPI_PKG_CONFIG_LDFLAGS = -Lno/lib -Wl,-rpath -Wl,no/lib -Wl,-rpath -Wl,${libdir} -Wl,--enable-new-dtags
same for OMPI_WRAPPER_EXTRA_FC_LDFLAGS and OMPI_WRAPPER_EXTRA_LDFLAGS

**Comment by jsquyres** [comment]
Oh, I see -- it added `$with_luster`, which is `no`.  Got it.  Yeah, that's a bug.

**Comment by jsquyres** [comment]
This was fixed on master long ago (and automatically became part of the v4.0.x branch).  But the fixes were not cherry picked to the release branches.

Just created PRs for v3.0.x and v3.1.x.

**Comment by jsquyres** [comment]
This has now been merged to all relevant release branches.  Closing.
