### ISSUE TITLE
MCA relative priority option

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#51]
It was suggested that we have a way of allowing the user to specify a list of components in a relative ordering of selection versus the current method of setting each component priority manually.

So have something like:
```
  shell$ mpirun -mca fwrk_relative foo,bar,baz myapp
```

There is an include list of "foo,bar,baz" but the priorities are set relative to their placement in the list. So we try to select "foo" first then "bar" then "baz" and if none of them become selected then we can error out which is the default when an include list is given.

**Comment by jsquyres** [comment]
@hjelmn I'm assuming this won't be fixed.
