### ISSUE TITLE
Build fails intermittently in libmpi_usempi_ignore_tkr.la

### ISSUE THREAD

**Issue by amckinstry** [open-mpi/ompi#5114]
## Background information

This is seen in the Debian packaging builds.  Maybe 1/20 times, its difficult to track down. 
The Debian bug is: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896861 

### What version of Open MPI are you using? 
3.0.1 rc5 (Incorrectly seen in logs as 3.0.1; is not believed to be relevant)

#### What Architectures
 Multiple archs. Debian unstable / testing. During build, so network type irrelevant ? 

## Details of the problem

An example can be seen here:
https://buildd.debian.org/status/fetch.php?pkg=openmpi&arch=arm64&ver=3.0.1-4&stamp=1523694740&raw=0

The build fragment is:
```
make[3]: Entering directory '/<<PKGBUILDDIR>>/ompi/mpi/fortran/use-mpi-ignore-tkr'
FCLD     libmpi_usempi_ignore_tkr.la /usr/bin/i686-linux-gnu-ld: cannot find -l-L/usr/lib/gcc/i686-linux-gnu/7
collect2: error: ld returned 1 exit status
Makefile:1866: recipe for target 'libmpi_usempi_ignore_tkr.la' failed
make[3]: *** [libmpi_usempi_ignore_tkr.la] Error 1
```
_Something_ is causing libtool to incorrectly add "-l", and it appears to be a race condition.

**Comment by jsquyres** [comment]
Whoa.  That's truly weird.  I haven't seen non-determinism in the build system in a long, long time.  I've seen *bugs*, but not *non-determinism*.  😦 

Let me go reply on the Debian bug -- we'll try to keep the discussion over there.

**Comment by ggouaillardet** [comment]
@amckinstry I noted

```
configure \
	--with-libevent=external \
	--enable-mpi-thread-multiple \
	--with-hwloc=/usr/ \
	--with-libltdl=/usr/
```

the `--enable-mpi-thread-multiple` option is no more supported (we now __always__ build support for `MPI_THREAD_MULTIPLE` since its overhead is virtually not measurable when `MPI_THREAD_MULTIPLE` is not required by the application)

you should also replace `--with-FOO=/usr` with `--with-FOO=external`

(iirc, there was a bug that required to use `/usr` and this should be fixed now)

for the sake of debugging, I also suggest you print the content of the external `.la` files (e.g. `libevent.la`, `libhwloc.la` and `libltdl.la` - I am AFK, so you please double check the file names and their location on debian systems).
Last but not least, it would really help printing `config.log` when `make` fails.

**Comment by amckinstry** [comment]
The --with-hwloc=external --with-libltdl=external failed for me. (If you wish I can open a separate issue on that).

I've enabled printing out the config.log, .la file contents on build failures, to catch problems.
However for the moment I've also enabled non-parallel builds (ie make -j1 ) to get the transition through - and the problem isn't appearing. When the transition is complete I'll get back to this.

**Comment by bwbarrett** [comment]
@amckinstry can you file a different issue on the `=external` options failing; we should definitely fix that.  Thanks!

**Comment by amckinstry** [comment]
So, we have a log of an incident on mipsel, where this happened. $(make) -j1 so no parallelism ...

https://buildd.debian.org/status/fetch.php?pkg=openmpi&arch=mipsel&ver=3.1.0-4&stamp=1527099159&raw=0

Search on error: to see the point of failure; just after that the log dumps the output of config.log, and then 'cats' the .la files.

**Comment by ggouaillardet** [comment]
The error occurs the first time we try to build a shared library with `gfortran`.
`g++` also pulls a lot of references to `/usr/lib/gcc/mipsel-linux-gnu/7` but there is no error.

At that stage, my only guess is something is wrong with the generated `libtool`.

Could you also dump the generated `libtool` when an error occurs ?

**Comment by jsquyres** [comment]
Check out my reply at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896861#42.

I think we need to see the `.la` files that Open MPI's build system is accessing -- I suspect that one of them is malformed somehow (which is how we got a naked `-l` followed by `-L/usr/lib/gcc/....`).

**Comment by jsquyres** [comment]
@amckinstry We'll need to see the `.la` files, too -- particularly the ones outside of the Open MPI source tree that Open MPI is linking against (e.g., if you're linking against an external libevent, etc.).

**Comment by amckinstry** [comment]
@jsquyres If you look at the bug report URL above, you'll see (search a bit) that the .la files generated within openmpi are dumped. We don't keep/use .la files for external packages, so while libevent was external,  we don't use its .la file.

**Comment by jsquyres** [comment]
@amckinstry Oh!  I missed the `.la` files nestled in the end of the build output in https://buildd.debian.org/status/fetch.php?pkg=openmpi&arch=mipsel&ver=3.1.0-4&stamp=1527099159&raw=0; sorry!

Looking at the relevant Makefile.am, it looks like `libompi_usempi_ignore_tkr.la` only links against one internal `.la` file: `libpen-pal.la`:

```
lib@OMPI_LIBMPI_NAME@_usempi_ignore_tkr_la_LIBADD = \
        $(OMPI_TOP_BUILDDIR)/opal/lib@OPAL_LIB_PREFIX@open-pal.la
```

And from the URL you cited, it looks like here's `libopen-pal.la` (although I see the same contents twice; I'm not sure why):

```
# libopen-pal.la - a libtool library file
# Generated by libtool (GNU libtool) 2.4.6 Debian-2.4.6-2.1
#
# Please DO NOT delete this file!
# It is necessary for linking the library.

# The name that we can dlopen(3).
dlname='libopen-pal.so.40'

# Names of this library.
library_names='libopen-pal.so.40.10.0 libopen-pal.so.40 libopen-pal.so'

# The name of the static archive.
old_library=''

# Linker flags that cannot go in dependency_libs.
inherited_linker_flags=' -pthread'

# Libraries that this one depends upon.
dependency_libs=' -ldl -lrt -lm -lutil -lhwloc -levent -levent_pthreads'

# Names of additional weak libraries provided by this library
weak_library_names=''

# Version information for libopen-pal.
current=50
age=10
revision=0

# Is this an already installed library?
installed=no

# Should we warn about portability when linking against -modules?
shouldnotlink=no

# Files to dlopen/dlpreopen
dlopen=''
dlpreopen=''

# Directory that this library needs to be installed in:
libdir='/usr/lib/mipsel-linux-gnu/openmpi/lib'
```

I don't see anything unusual in there, and certainly no naked `-l` options.

Yeah, so I guess the next step is what @ggouaillardet said - we need to see the `libtool` script so that we can see how it goes from

```
/bin/bash ../../../../libtool  --tag=FC   --mode=link gfortran -I../../../../ompi/include -I../../../../ompi/include -I../../../.. -I../../../..  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -O3 -version-info 50:0:10  -Wl,-z,relro    -o libmpi_usempi_ignore_tkr.la -rpath /usr/lib/mipsel-linux-gnu/openmpi/lib mpi-ignore-tkr.lo mpi-ignore-tkr-sizeof.lo /&lt;&lt;PKGBUILDDIR&gt;&gt;/opal/libopen-pal.la -lrt -lm -lutil   -lhwloc  -levent -levent_pthreads
```

to

```
libtool: link: gfortran -shared  -fPIC  .libs/mpi-ignore-tkr.o .libs/mpi-ignore-tkr-sizeof.o   -Wl,-rpath -Wl,/<<PKGBUILDDIR>>/opal/.libs -Wl,-rpath -Wl,/usr/lib/mipsel-linux-gnu/openmpi/lib /<<PKGBUILDDIR>>/opal/.libs/libopen-pal.so -lrt -lutil -lhwloc -levent -levent_pthreads -l -L/usr/lib/gcc/mipsel-linux-gnu/7 -L/usr/lib/gcc/mipsel-linux-gnu/7/../../../mipsel-linux-gnu -L/usr/lib/gcc/mipsel-linux-gnu/7/../../../../lib -L/lib/mipsel-linux-gnu -L/lib/../lib -L/usr/lib/mipsel-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/mipsel-linux-gnu/7/../../.. -lgfortran -lm -lc -lgcc_s  -g -O2 -fstack-protector-strong -O3 -Wl,-z -Wl,relro   -pthread -Wl,-soname -Wl,libmpi_usempi_ignore_tkr.so.40 -o .libs/libmpi_usempi_ignore_tkr.so.40.10.0
```

(i.e., with the bogus `-l` with no argument)

This is certainly feeling more and more like a `libtool` issue.  That being said, there's still a small chance that it's our fault, because we do patch a few of the autotools files during `autogen.pl`...

**Comment by amckinstry** [comment]
Ok, got examples of failure logs here; https://buildd.debian.org/status/fetch.php?pkg=openmpi&arch=armel&ver=3.1.1.real-4%2Bb1&stamp=1532439131&raw=0

The libtools generated are different, in the FC tag sections.

GOOD:
```
# The directories searched by this compiler when creating a shared library.
compiler_lib_search_dirs="/usr/lib/gcc/mips64el-linux-gnuabi64/8 /usr/lib/gcc/mips64el-linux-gnuabi64/8/../../../mips64el-linux-gnuabi64 /usr/lib/gcc/mips64el-linux-gnuabi64/8/../../../../lib /lib/mips64el-linux-gnuabi64 /lib/../lib /usr/lib/mips64el-linux-gnuabi64 /usr/lib/../lib /usr/lib/gcc/mips64el-linux-gnuabi64/8/../../.."

# Dependencies to place before and after the objects being linked to
# create a shared library.
predep_objects="/usr/lib/gcc/mips64el-linux-gnuabi64/8/../../../mips64el-linux-gnuabi64/crti.o /usr/lib/gcc/mips64el-linux-gnuabi64/8/crtbeginS.o"
postdep_objects="/usr/lib/gcc/mips64el-linux-gnuabi64/8/crtendS.o /usr/lib/gcc/mips64el-linux-gnuabi64/8/../../../mips64el-linux-gnuabi64/crtn.o"
predeps=""
postdeps="-lgfortran -lm -lgcc_s -lm -lgcc_s -lc -lgcc_s"

# The library search path used internally by the compiler when linking
# a shared library.
compiler_lib_search_path="-L/usr/lib/gcc/mips64el-linux-gnuabi64/8 -L/usr/lib/gcc/mips64el-linux-gnuabi64/8/../../../mips64el-linux-gnuabi64 -L/usr/lib/gcc/mips64el-linux-gnuabi64/8/../../../../lib -L/lib/mips64el-linux-gnuabi64 -L/lib/../lib -L/usr/lib/mips64el-linux-gnuabi64 -L/usr/lib/../lib -L/usr/lib/gcc/mips64el-linux-gnuabi64/8/../../.."
```

BAD:
```
# The directories searched by this compiler when creating a shared library.
compiler_lib_search_dirs=""

# Dependencies to place before and after the objects being linked to
# create a shared library.
predep_objects=""
postdep_objects="/usr/lib/gcc/mips64el-linux-gnuabi64/7/../../../mips64el-linux-gnuabi64/crti.o /usr/lib/gcc/mips64el-linux-gnuabi64/7/crtbeginS.o /usr/lib/gc\
c/mips64el-linux-gnuabi64/7/crtendS.o /usr/lib/gcc/mips64el-linux-gnuabi64/7/../../../mips64el-linux-gnuabi64/crtn.o"
predeps=""
postdeps="-l -l -L/usr/lib/gcc/mips64el-linux-gnuabi64/7 -L/usr/lib/gcc/mips64el-linux-gnuabi64/7/../../../mips64el-linux-gnuabi64 -L/usr/lib/gcc/mips64el-lin\
ux-gnuabi64/7/../../../../lib -L/lib/mips64el-linux-gnuabi64 -L/lib/../lib -L/usr/lib/mips64el-linux-gnuabi64 -L/usr/lib/../lib -L/usr/lib/gcc/mips64el-linux-\
gnuabi64/7/../../.. -lgfortran -lm -lgcc_s -lm -lgcc_s -lc -lgcc_s"
```
(Note: compiler version has moved from gcc 7.4 to 8.1 between these logs, but that doesn't appear to be relevant).
These entries are generated via `configure` (eg. variable `postdeps_FC` becomes postdeps in the relevant fragment, but I can't see where a race condition is happening / can occur in configure.

**Comment by amckinstry** [comment]
The Debian build process changes config/libtool.m4 a version, with the change:
```
diff /usr/share/aclocal/libtool.m4 config/libtool.m4

4950,4952d4938
<   linux* | k*bsd*-gnu | gnu*)
<     _LT_TAGVAR(link_all_deplibs, $1)=no
<     ;;
5015,5017d5000
<   linux* | k*bsd*-gnu | gnu*)
<     _LT_TAGVAR(link_all_deplibs, $1)=no
<     ;;
5272c5255
<     netbsd* | netbsdelf*-gnu)
---
>     netbsd*)
5793d5775
<     _LT_TAGVAR(link_all_deplibs, $1)=no
```

might be relevant. The patch has:
```
File Edit Options Buffers Tools Diff Help
## Do not link against deplibs.  This is not needed for shared libs
## on atleast ELF systems since those already know which libs they
## need themself.  This seems to break a few things and will be fixed
## in a better way in a future upstream version.
```

I'm struggling to find the cause of the race condition, though, given that only one thread should be involved in ./autogen.pl (though multiple processors are present). Either: (1) some sub-process (ld ? gcc ? ) are giving different results via a race, or its filesystem (different orders when  doing readdir() somewhere), though LC_ALL=POSIX is set at the top.

**Comment by jsquyres** [comment]
Wow -- that's crazy differences between those two `libtool` snippits.  😦

I think this definitely moved into the "not Open MPI's fault" category.  Can this be raised with the Libtool developers?

**Comment by amckinstry** [comment]
Indeed; the changes to libtool are implicated, but no fortran-specific changes were made, so I'm still digging (and have contacted the libtool maintainers).

**Comment by amckinstry** [comment]
Just to note this issue is also being tracked here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896861

So far its been traced to having "-L" in tmpdir build paths on Debian.

**Comment by jsquyres** [comment]
Huh; I wonder why I wasn't able to reproduce it...?

Here's what I did (also listed on the Debian bug):

```
$ cd /home/jsquyres/openmpi-releases
$ mkdir -p build/openmpi-LjweZK
$ cd build/openmpi-LjweZK
$ tar xf ../../openmpi-3.0.1.tar.bz2
$ cd openmpi-3.0.1
$ ./configure --prefix=$HOME/bogus |& tee config.out
$ make -j 32 |& tee make.out
```

I am using:

* Autoconf 2.69
* Automake 1.15 (*** you are using 1.15.1 -- do we think that makes a difference?)
* Libtool 2.4.6

**Comment by jsquyres** [comment]
@amckinstry Should we close this issue?

**Comment by amckinstry** [comment]
Yes, closing.
