### ISSUE TITLE
Allreduce Question

### ISSUE THREAD

**Issue by elibol** [open-mpi/ompi#5120]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

v1.10.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

`sudo apt-get install openmpi-bin`

### Please describe the system on which you are running

* Operating system/version: Ubuntu 16.04
* Computer hardware: AWS m4.16xlarge
* Network type: TCP (25Gbps dedicated bandwidth)

-----------------------------

## Details of the problem

I have a single MPI process on each node in a 16 cluster node, and I would like to maximize throughput between these processes during allreduce. Some questions about the `MPI_Allreduce` method:

1. Does OpenMPI utilize multiple threads to simultaneously send and receive data, or does it handle sends and receives on a single thread?
2. If OpenMPI handles sends/receives on a single thread by default, is there any way to configure OpenMPI to use separate threads for sends and receives?
3. Is it possible to configure OpenMPI to use more than one socket to send data and more than one socket to receive data? I understand this is one way to approach 25Gbps sends and receives.

**Comment by bosilca** [comment]
1. The current version of Open MPI sequentialize the sends and receives into a single thread. Depending on the underlying algorithm it tries to maintain overlap between send/recv by using a double buffering strategy.
1. In the current version there is no opportunity to use separate threads in the same collective algorithm.
1. I am not sure I understand the question and how it differs from the previous one.

**Comment by elibol** [comment]
Thank you.
