### ISSUE TITLE
ORTE doesn't understand SLURM 17.11 new MPMD job support

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#5137]
SchedMD recently added support for an  MPMD style allocation request and job launch support.  Recent here means 17.11.5, maybe also 17.11.4.  At any rate, an SALLOC or SBATCH sets new environment variables that the ORTE runtime doesn't understand, thus leading to a failure to launch with mpirun.  

An example on my cluster with 17.11.5 installed - a cluster with a mix of Haswell's and KNL's so I want to use the two sides asymmetrically:

```
/users/hpp@foobar-cray:salloc -N 1 -n 4 -p standard : -N 2 -n 4 -p knl
salloc: Pending job allocation 100689
salloc: job 100689 queued and waiting for resources
salloc: job 100689 has been allocated resources
salloc: Granted job allocation 100689
salloc: Waiting for resource configuration
salloc: Nodes nid00024 are ready for job
/users/hpp@nid00024:~>env | grep TASKS_PER
SLURM_TASKS_PER_NODE_PACK_GROUP_0=4
SLURM_TASKS_PER_NODE_PACK_GROUP_1=2(x2)
```

Well, the ORTE is looking for SLURM_TASKS_PER_NODE and doesn't see it, so it fails to launch.

**Comment by rhc54** [comment]
Might want to look at moving to PMIx to get the allocation - we are continually chasing their changes in envars, and maintaining that across all versions is absurd.

**Comment by hppritcha** [comment]
going to try a Q&D solution first in slurm ras component, longer term move ras framework into pmix.

**Comment by rhc54** [comment]
I think it is a little worse than even that - ORTE currently doesn't track nodes by type when mapping jobs. You'll need to add some logic in the rmaps framework for specifying which type of node to use for each app, which means also modifying the orte_app_context_t struct (or adding attributes to indicate which type of node is being requested, which is probably the better option)

**Comment by hppritcha** [comment]
closing this since ORTE is going away.  If it becomes important in the future, an issue should be opened on prrte project: https://github.com/openpmix/prrte
