### ISSUE TITLE
improve parsability of ompi_info --parsable output

### ISSUE THREAD

**Issue by lebedov** [open-mpi/ompi#515]
As of OpenMPI 1.8.4, the output of `ompi_info --parsable` is difficult to parse because some of the fields, e.g., (`build:timestamp`) contain colons. This could be addressed by quoting such fields as is done in most variations of the CSV format, e.g., `build:timestamp:"Tue Dec 23 15:47:28 EST 2014"` 

See mailing list discussion [here](http://www.open-mpi.org/community/lists/users/2015/04/26647.php).

**Comment by rhc54** [comment]
We talked about this today and decided we can't change it for the 1.8 series as that might well break people who are already using it. However, we'll certainly consider the change for 1.9, so I'm adjusting the milestone accordingly.

**Comment by jsquyres** [comment]
@lebedov What you say makes sense.

I think, per the note on the mailing list, there may well be a few cases where there are multiples names -- e.g., the value is not necessarily always after the 2nd colon.  E.g.,

```
package:Open MPI jsquyres@savbu-usnic-a Distribution
ompi:version:full:1.8.5rc2
ompi:version:repo:v1.8.4-214-gc540cf8
ompi:version:release_date:Unreleased developer copy
orte:version:full:1.8.5rc2
orte:version:repo:v1.8.4-214-gc540cf8
orte:version:release_date:Unreleased developer copy
opal:version:full:1.8.5rc2
opal:version:repo:v1.8.4-214-gc540cf8
opal:version:release_date:Unreleased developer copy
mpi-api:version:full:3.0
ident:1.8.5rc2
```

See #527 for a suggestion of how this could work.  @lebedov Would you mind trying that PR and seeing if it's what you think it should be?

**Comment by jsquyres** [comment]
I'm going to close this issue; all further discussion should happen on #527.
