### ISSUE TITLE
segmentation fault in mpirun

### ISSUE THREAD

**Issue by jarrah42** [open-mpi/ompi#5165]
Version 3.1.0 (also 2.x)
source tarball
Mac OS X 10.13.3

The following command generates a signal 11. This command is used by the Eclipse Parallel Tools Platform (PTP) to obtain process location information.

mpirun -np 3 -mca orte_show_resolved_nodenames 1 -display-map echo hi
 Data for JOB [32122,1] offset 0 Total slots allocated 4
[MAC104826:61219] *** Process received signal ***
[MAC104826:61219] Signal: Segmentation fault: 11 (11)
[MAC104826:61219] Signal code: Address not mapped (1)
[MAC104826:61219] Failing at address: 0x0
[MAC104826:61219] [ 0] 0   libsystem_platform.dylib            0x00007fff63b5af5a _sigtramp + 26
[MAC104826:61219] [ 1] 0   libsystem_c.dylib                   0x00007fff9c97b6b8 __global_locale + 0
[MAC104826:61219] [ 2] 0   libopen-rte.40.dylib                0x00000001038a3fb0 orte_dt_print_map + 1088
[MAC104826:61219] [ 3] 0   libopen-rte.40.dylib                0x00000001038fa69e orte_rmaps_base_display_map + 222
[MAC104826:61219] [ 4] 0   libopen-rte.40.dylib                0x00000001038e2eac orte_odls_base_default_construct_child_list + 3484
[MAC104826:61219] [ 5] 0   mca_odls_default.so                 0x0000000103c81fe3 orte_odls_default_launch_local_procs + 19
[MAC104826:61219] [ 6] 0   libopen-rte.40.dylib                0x00000001038bf12d orte_daemon_recv + 605
[MAC104826:61219] [ 7] 0   libopen-rte.40.dylib                0x00000001039027f2 orte_rml_base_process_msg + 450
[MAC104826:61219] [ 8] 0   libopen-pal.40.dylib                0x000000010399cf8a opal_libevent2022_event_base_loop + 1802
[MAC104826:61219] [ 9] 0   mpirun                              0x00000001038929b3 orterun + 291
[MAC104826:61219] [10] 0   libdyld.dylib                       0x00007fff638d9115 start + 1
[MAC104826:61219] [11] 0   ???                                 0x0000000000000009 0x0 + 9
[MAC104826:61219] *** End of error message ***
Segmentation fault: 11

**Comment by rhc54** [comment]
FWIW: works fine on master

**Comment by ggouaillardet** [comment]
This has been reported on the mailing list and fixed (on master) in #5088 and #5095, and backported into all the release branches. 

meanwhile, you can manually download and apply the patch at https://github.com/open-mpi/ompi/pull/5096.patch for the v3.1.x branch.

**Comment by jarrah42** [comment]
I tried the head of 3.0.x and it works. Thanks!
