### ISSUE TITLE
PMIx: backward compatibility with previous RMs

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#5177]
I noticed this in v3.1.x: In the hwloc topo get function a new PMIx variable is used:
https://github.com/open-mpi/ompi/blob/5d920bcc1a268c22fd1a5770ee29d294f6af7cd9/opal/mca/hwloc/base/hwloc_base_util.c#L347

This change went unnoticed by us and Slurm plugin wasn't updated. So Slurm plugin provides the old key named `PMIX_LOCAL_TOPO` instead of `PMIX_HWLOC_XML_V1` and I thought that it would be correct to test this key as well.

**Comment by jsquyres** [comment]
@karasevb @artpol84 This issue is back from May 2018.  Any progress?

**Comment by artpol84** [comment]
@karasevb ?
