### ISSUE TITLE
Segmentation fault on Mac

### ISSUE THREAD

**Issue by juliohm** [open-mpi/ompi#5178]
A few weeks (or months) ago, something changed about hwloc that is leading to segmentation faults only on Mac: https://travis-ci.org/juliohm/ImageQuilting.jl

I don't have a Mac myself, but my colleague yesterday had the same issue on his Mac and reported to me. I got access to the machine and was able to confirm that the segmentation fault is caused by a few commands such as `lstopo`. I wonder if this issue is in your radar already, and what can be done to solve it properly?

I appreciate any help here,

**Comment by ggouaillardet** [comment]
Did you mean to report this to the hwloc repository ?

FWIW, I quickly checked the logs and could not incriminate hwloc at first glance.

**Comment by juliohm** [comment]
Thank you @ggouaillardet , I got confused on the hwloc webpage and clicked on the wrong link probably that in turn made me open the issue here.

I am positive that the issue is in hwloc, I have a friend with a Mac where I was able to consistently get the segfault by just typing `lstopo` in the prompt.

I will open the issue in the appropriate repo.

Best,
