### ISSUE TITLE
master: configure failure due to redefinition of OPAL_C_HAVE__STATIC_ASSERT (among others)

### ISSUE THREAD

**Issue by benmenadue** [open-mpi/ompi#5190]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

master@385d91b

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### Please describe the system on which you are running

* Operating system/version: CentOS 6.9 + custom kernel (based on CentOS 7.4 kernel)
* Computer hardware: Fujitsu PRIMERGY
* Network type: Mellanox InfiniBand FDR

-----------------------------

## Details of the problem

Configuring master is failing in hwloc:hwloc2a because OPAL_C_HAVE__STATIC_ASSERT (among others) is being appended to `confdefs.h` by each test for that language feature. If a second or subsequent test succeeds, you end up with a redefinition of that macro, which then causes a test in hwloc:hwloc2a to fail because it uses `-Werror`.

For example, both of these add `#define OPAL_C_HAVE__STATIC_ASSERT 0`
```
configure:15649: checking if gcc -std=gnu11 supports C11 _Static_assert
configure:15649: checking if gcc -std=c11 supports C11 _Static_assert
```
but then this test (erroneously, see #5189) adds `#define OPAL_C_HAVE__STATIC_ASSERT 1`
```
configure:15665: gcc -c -DNDEBUG -g -march=native -c11  conftest.c >&5
```

Here's the failure in hwloc:hwloc2a (tidied up for readability):
```
configure:81547: checking if gcc -std=gnu99 supports -fvisibility=hidden
configure:81563: gcc -std=gnu99 -o conftest -DNDEBUG -g -march=native -fvisibility=hidden -Werror    -I/short/z00/bjm900/build/openmpi-mofed4.2/master/build/gcc/debug-0/opal/mca/hwloc/external/hwloc/include -I/apps/cuda/9.0/include    conftest.c -lrt -lm -lutil  -lz 
 -lhwloc  >&5
conftest.c:117:1: error: "OPAL_C_HAVE__STATIC_ASSERT" redefined
conftest.c:112:1: error: this is the location of the previous definition
configure:81563: $? = 1
configure: failed program was:
...
| #define OPAL_C_HAVE__THREAD_LOCAL 0
| #define OPAL_C_HAVE_ATOMIC_CONV_VAR 0
| #define OPAL_C_HAVE__ATOMIC 0
| #define OPAL_C_HAVE__GENERIC 0
| #define OPAL_C_HAVE__STATIC_ASSERT 0
| #define OPAL_C_HAVE__THREAD_LOCAL 0
| #define OPAL_C_HAVE_ATOMIC_CONV_VAR 0
| #define OPAL_C_HAVE__ATOMIC 0
| #define OPAL_C_HAVE__GENERIC 0
| #define OPAL_C_HAVE__STATIC_ASSERT 0
| #define OPAL_C_HAVE__THREAD_LOCAL 0
| #define OPAL_C_HAVE_ATOMIC_CONV_VAR 0
| #define OPAL_C_HAVE__ATOMIC 0
| #define OPAL_C_HAVE__GENERIC 0
| #define OPAL_C_HAVE__STATIC_ASSERT 1
| #define OPAL_C_HAVE__THREAD_LOCAL 0
| #define OPAL_C_HAVE_ATOMIC_CONV_VAR 0
| #define OPAL_C_HAVE__ATOMIC 0
| #define OPAL_C_HAVE__GENERIC 0
| #define OPAL_C_HAVE__STATIC_ASSERT 1
...
configure:81579: result: no
configure:81596: error: Symbol visibility support requested but compiler does not seem to support it.  Aborting
```

**Comment by benmenadue** [comment]
Yep, exactly. I started working on a patch that instead tests for C11 support via `__STDC_VERSION__` with the various compiler flags and then, once that was found, test for the various features. Would you be happy with that approach?

**Comment by jsquyres** [comment]
Yes, that sounds great.  Thanks!

**Comment by ggouaillardet** [comment]
I issued a PR some times ago, and it has been stale for a while ... checking now.

**Comment by ggouaillardet** [comment]
This is #4822 I will rebase (and solve conflicts) and retest from now

**Comment by thananon** [comment]
I believe this issue is fixed and can be closed?

**Comment by jsquyres** [comment]
@thananon Yeah, let's go ahead and close.  @benmenadue and/or @ggouaillardet go ahead and re-open if the issue isn't fixed.  Thanks!
