### ISSUE TITLE
osc/rdma does not keep track of outstanding atomic op.

### ISSUE THREAD

**Issue by thananon** [open-mpi/ompi#5195]
**branch:** master;
**module:** osc/rdma
**btl**: ofi (in development) / sockets provider.

`ompi_osc_rdma_free()` does not enforce the remaining atomic operation completion. (It has the counter for outstanding rdma but not for atomic op) This leads to target window being freed before atomic operation completion and leads to segfault. This only happens to sockets provider as it is slow.

I verified this by forcing completion of atomic operation in btl_progress() but that is not ideal. I think the osc/rdma should handle this.

**Comment by thananon** [comment]
@hppritcha , this is the cause of sockets provider failing/segfaulting in osu tests.

**Comment by hjelmn** [comment]
Ah. Thanks for reporting this. Should be easy to fix

**Comment by hjelmn** [comment]
I think I have a fix. Testing it now.
