### ISSUE TITLE
btl/ofi: build failed with libfabric version< 1.5.

### ISSUE THREAD

**Issue by thananon** [open-mpi/ompi#5214]
@rhc54 reported build failed in master with new btl/ofi.

The cause is the newer MR mode bits which doesnt exist in libfabric version < 1.5.
```
btl_ofi_component.c:64:23: error: 'FI_MR_VIRT_ADDR' undeclared (first use in this function)
          (mr_mode & ~(FI_MR_VIRT_ADDR | FI_MR_ALLOCATED | FI_MR_PROV_KEY)) == 0)) {
                       ^
btl_ofi_component.c:64:23: note: each undeclared identifier is reported only once for each function it appears in
btl_ofi_component.c:64:41: error: 'FI_MR_ALLOCATED' undeclared (first use in this function)
          (mr_mode & ~(FI_MR_VIRT_ADDR | FI_MR_ALLOCATED | FI_MR_PROV_KEY)) == 0)) {
                                         ^
btl_ofi_component.c:64:59: error: 'FI_MR_PROV_KEY' undeclared (first use in this function)
          (mr_mode & ~(FI_MR_VIRT_ADDR | FI_MR_ALLOCATED | FI_MR_PROV_KEY)) == 0)) {
                                                           ^
btl_ofi_component.c: In function 'mca_btl_ofi_init_device':
btl_ofi_component.c:416:42: error: 'FI_MR_VIRT_ADDR' undeclared (first use in this function)
         ofi_info->domain_attr->mr_mode & FI_MR_VIRT_ADDR) {

```

The BTL checks for opal/common/ofi ok flag to start building. However, the common flag does not take into account the api version. 

I have a patch that put version checking in the initialization but this still does not solve the problem of the 'unknown flags' at compile time.

```diff
-    libfabric_api = FI_VERSION(1, 5);       /* 1.5 because of the newer API */
+    libfabric_api = fi_version();
+
+    /* Bail if version < 1.5. */
+    if (FI_VERSION_LT(FI_VERSION(1, 5), libfabric_api)) {
+        BTL_VERBOSE(("ofi btl disqualified: libfabric version < 1.5."));
+        return NULL;
+    }
```

Do you have any suggestion for this? Do we have a way to check libfabric version at compile time? I looked at btl/usnic and mtl/ofi but it seems like they dont need those flags so it is ok.

@hppritcha @jsquyres

**Comment by jsquyres** [comment]
Yes, you need to put a check in `ompi/mca/btl/ofi/configure.m4` that checks for whether `FI_MR_PROV_KEY` exists (or any other symbols that don't exist prior to v1.5).

You can choose what to do if they don't exist -- either refuse to compile the component (i.e., the component simply requires libfabric >= v1.5), or have some `#define` that enables a compatibility mode in your C code that can handle if those symbols are not present.

**Comment by thananon** [comment]
@jsquyres 
Thank you. It's gonna take some time for me to understand autoconf. I will try to get it done by Monday but for now #5216 will work if needed.
