### ISSUE TITLE
osc/rdma: cannot handle more than 1 completion at a time.

### ISSUE THREAD

**Issue by thananon** [open-mpi/ompi#5256]
I discussed this with @hppritcha and @hjelmn and just creating this issue for tracking.  We mentioned this in #5205 .

The problem is when osc_rdma do aggrregate flush, it is doing a foreach over a list and flushing them one by one but some completion might trigger the callback to free the list member and lead to segfault.

If we fix this problem, we will see some performance bump from the BTL.

**Comment by thananon** [comment]
I just want to report that for some reason, I dont see any problem when handling more than 1 completion at a time anymore.

**Comment by hjelmn** [comment]
I got rid of the aggregation code some time ago. It did little but complicate the code and game single-threaded bandwidth benchmarks.

**Comment by jsquyres** [comment]
@thananon Should this issue be closed?  It looks like @hjelmn fixed the problem...?

**Comment by thananon** [comment]
Yes, I can no longer reproduce the behavior.
