### ISSUE TITLE
Sending SIGTSTP during init with orte_forward_job_control on causes hang

### ISSUE THREAD

**Issue by evandeaubl** [open-mpi/ompi#526]
In 1.8.4, there seems to be a small time window during job initialization where sending the SIGTSTP signal to suspend the job causes the MPI job to permanently hang. Sending SIGCONT to the mpirun process does not cause the job to continue, and it also does not respond to other signals (SIGINT, SIGTERM). ompi-ps indicates the state of the job is PENDING APP LAUNCH, and the process state is INITIALIZED. A ps on the remote node shows the remote shell and orted processes suspended, but the sleep process has not been started.

Here is the command that reproduced the problem (the usleep duration will likely need to be tweaked to find the value that causes the hang):

mpirun --host <remote host> --mca orte_forward_job_control 1 sleep 3 & usleep 800000; kill -TSTP $!

Turning orte_debug_daemons on makes it look like the time window is just after the add_local_procs event is received by the orted process. In situations where the TSTP is received before or significantly after (~.1s) that event, the job doesn't hang.

**Comment by rhc54** [comment]
Please reopen if you see this happening on OMPI master or the soon-to-be-released 3.0
