### ISSUE TITLE
OSC shared memory fence segfault

### ISSUE THREAD

**Issue by PeterGottesman** [open-mpi/ompi#5262]
When running the `onesided/c_strided_getacc_indexed_shared` test, an `open` syscall is failing when initializing shared memory with `MPI_Win_allocate_shared`. Execution is continuing until the uninitialized shared memory is accessed by a call to `MPI_Win_fence`, at which point the process segfaults.

The segfault specifically occurs at [line 103 of osc_sm_active_target.c](https://github.com/open-mpi/ompi/blob/master/ompi/mca/osc/sm/osc_sm_active_target.c#L103) (because `module->global_state` is NULL).
The failing open syscall occurs during at [line 495 of shmem_mmap_module.c](https://github.com/open-mpi/ompi/blob/master/opal/mca/shmem/mmap/shmem_mmap_module.c#L495).

The stdout/stderr can be seen here:
https://mtt.open-mpi.org/index.php?do_redir=2633

@hjelmn I believe this is up your alley

**Comment by hjelmn** [comment]
That looks like a new failure mode. Will take a look tomorrow.

**Comment by jsquyres** [comment]
@hjelmn FWIW, the file that fails to open in shmem_mmap_module.c:495 is `/dev/shm/vader_segment.savbu-usnic-a.58f00001.1`.

**Comment by PeterGottesman** [comment]
@hjelmn This is still appearing on MTT. Any luck tracking down the issue?

**Comment by hjelmn** [comment]
Not yet. I haven't been able to recreate the issue. Plan to try again this week.

**Comment by jsquyres** [comment]
Per 2018-06-26 webex, please re-create with a debug build and run with `osc_base_verbose 100` and send output to @hjelmn.

Note: this is happening across the board on master, v3.0, v3.1.  😢

**Comment by jsquyres** [comment]
Per off-issue discussion, @hjelmn found the issue before we sent him the verbose output.  See #5341.
