### ISSUE TITLE
Randomly reports more processes than cpus about when running under torque cgroups

### ISSUE THREAD

**Issue by twhitehead** [open-mpi/ompi#5266]
Thank you for taking the time to submit an issue!

## Background information

We run OpenMPI on our cluster under torque.  Users processes are bound to their allocated CPUs using cgroups.  Since sometime between 1.6 and 1.10 (and going all the way up to 3.1), OpenMPI, when told to bind to cores, seems to be confused with regard to the number of cpus available in this setup and reports messages such as the following before aborting

> A request was made to bind to that would result in binding more processes than cpus on a resource:
> 
>    Bind to:     CORE
>    Node:        orc265
>    #processes:  2
>    #cpus:       1
> 
> You can override this protection by adding the "overload-allowed" option to your binding directive.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

I have tried 1.6.2, 1.10.7, 2.1.3, and 3.1.0 and observed the behaviour in all of them but 1.6.2 (from an outsiders perspective it looks like the binding/topology stuff got a significant working over between 1.6 and 1.10, which I suspect introduced this issue).

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

It was installed using the Nix package manager.  Nix builds it in a chroot environment with nothing but a basic system including gcc, gfortran, libibverbs, torque, zlib, openssl, numactl, pkgconfig, and perl available.  The config flags "--prefix" and "--enable-orterun-prefix-by-default" were provided.

### Please describe the system on which you are running

* Operating system/version: CentOS 6
* Computer hardware: 320 x AMD Opteron @ 2.2 GHz (2 sockets x 12 cores/socket)
* Network type: QDR InfiniBand

## Details of the problem

MPI jobs (e.g., a simple hello world application) using recent versions of OpenMPI (i.e., not 1.6, but definitely 1.10 and greater) die randomly (i.e., about 50% of them) on setup when using `--bind-to core` with the message

> A request was made to bind to that would result in binding more processes than cpus on a resource:
> 
>    Bind to:     CORE
>    Node:        orc265
>    #processes:  2
>    #cpus:       1
> 
> You can override this protection by adding the "overload-allowed" option to your binding directive.

I have added some debugging dumps to the start and have the following information to go with the above error (the error has been observed in a variety of programs, the one above being a simple C hello world example where each node prints its rank and they all sum a variable).  Note that everything is being launched directly from the pbs_mom (torque daemon) via the tm ras MCA.

```
torque allocated cpus: orc280/6+orc265/18+orc265/17+orc265/10+orc265/9+orc265/8
```

```
orc265 lstopo dump: cgroup limited to cpus 8-10,17-18
Machine (32GB)
  Socket L#0 (16GB)
    NUMANode L#0 (P#0 8190MB)
    NUMANode L#1 (P#1 8192MB)
      L2 L#0 (512KB) + L1d L#0 (64KB) + L1i L#0 (64KB) + Core L#0 + PU L#0 (P#8)
      L2 L#1 (512KB) + L1d L#1 (64KB) + L1i L#1 (64KB) + Core L#1 + PU L#1 (P#9)
      L2 L#2 (512KB) + L1d L#2 (64KB) + L1i L#2 (64KB) + Core L#2 + PU L#2 (P#10)
  Socket L#1 (16GB)
    NUMANode L#2 (P#3 8192MB) + L2 L#3 (512KB) + L1d L#3 (64KB) + L1i L#3 (64KB) + Core L#3 + PU L#3 (P#17)
    NUMANode L#3 (P#2 8192MB) + L2 L#4 (512KB) + L1d L#4 (64KB) + L1i L#4 (64KB) + Core L#4 + PU L#4 (P#18)
  HostBridge L#0
    PCIBridge
      PCI 15b3:673c
        Net L#0 "ib0"
        Net L#1 "ib1"
        OpenFabrics L#2 "mlx4_0"
    PCIBridge
      PCI 8086:10c9
        Net L#3 "eth0"
      PCI 8086:10c9
        Net L#4 "eth1"
    PCIBridge
      PCI 8086:10c9
        Net L#5 "eth2"
      PCI 8086:10c9
        Net L#6 "eth3"
    PCIBridge
      PCI 102b:0522
    PCI 1002:4391
    PCI 1002:439c
      Block L#7 "sda"
```

```
orc280 lstopo dump: cgroup limited to cpus 6
Machine (32GB)
  Socket L#0 (16GB)
    NUMANode L#0 (P#0 8190MB)
    NUMANode L#1 (P#1 8192MB) + L2 L#0 (512KB) + L1d L#0 (64KB) + L1i L#0 (64KB) + Core L#0 + PU L#0 (P#6)
  Socket L#1 (16GB)
    NUMANode L#2 (P#3 8192MB)
    NUMANode L#3 (P#2 8192MB)
  HostBridge L#0
    PCIBridge
      PCI 15b3:673c
        Net L#0 "ib0"
        Net L#1 "ib1"
        OpenFabrics L#2 "mlx4_0"
    PCIBridge
      PCI 8086:10c9
        Net L#3 "eth0"
      PCI 8086:10c9
        Net L#4 "eth1"
    PCIBridge
      PCI 8086:10c9
        Net L#5 "eth2"
      PCI 8086:10c9
        Net L#6 "eth3"
    PCIBridge
      PCI 102b:0522
    PCI 1002:4391
    PCI 1002:439c
      Block L#7 "sda"
```

You can find over 100 additional job running reports (showing a variety of failures and successes including the above one) along with the hello world C code here.  These were all generated using the current 3.1.0 release (although all earlier release I tested back to 1.10 do the same).  The failure rate was right around 50% (66 of 118 ended in the above error message).

https://www.sharcnet.ca/~tyson/openmpi-bind-issue.tar.gz

The format of the log files is

```
torque host and cpu assigment
node0 hostname
cat of cpus from cpuset cgroup mount showing cpus proceses started on node0 are limited to
lstopo dump on node0
node1 hostname
cat of cpus from cpuset cgroup mount showing cpus proceses started on node1 are limited to
lstopo dump on node1
...
output from mpirun of hello world program with `--bind-to core` and `--report-bindings`
job summary info from job system
```

**Comment by rhc54** [comment]
Perhaps I'm missing it - what is the mpirun cmd line you are using?

**Comment by twhitehead** [comment]
```

**Comment by rhc54** [comment]
I'm not that familiar with torque, so perhaps I'm missing it. Where is the cgroup restriction being applied to the daemons launched by mpirun? Does torque automatically restrict anything started by that shell program to the defined cgroup on each node? Or does it only restrict things that are started by a torque tool - i.e., something that calls the torque daemon on the remote node to have it start an application out there?

I ask because you aren't specifying how many procs to run on your cmd line. In that case, what happens is that mpirun launches a daemon on each node in the allocation. The daemon reports back how many cores it sees on that node. mpirun then assigns a number of procs equal to the number of cores and tells the daemons to launch them.

If the daemon sees cores outside the cgroup as being "available", then you'll get a number of procs that is beyond what the cgroup can support. This would generate the error you show.

What you can do to test this is to assign a number of procs/node equal to the size of the cgroup using the -npernode N option. If that works, then the problem is likely that mpirun is computing too many procs, probably due to some race condition between application of the cgroup constraint and sensing of the available cpus by the daemon during startup.

Remember, cgroups works by first starting the proc and then placing the pid in the cgroup. Thus, there is a window of time where the proc is not constrained - if the sensing of cpus happens during that window, then you will encounter this error.

**Comment by twhitehead** [comment]
My understanding is that openmpi uses the torque library to get the allocation information and launch the processes. When you dump the process hierarchy they show up as descendants for the torque pbsmon  daemon that runs on each node.

I can see how a race condition with the cgroup assignment, as I'm understanding you are suggesting, would account for this error. As a test, I'll try adding a delay to the process startup and see if the error goes away.

Thank you very much for the quick response and sharp deduction skills!

**Comment by rhc54** [comment]
The delay would have to be in the startup of the daemon itself, not the application procs. What you'll need to do is create a shell script that does something like this:
```sh
sleep(1)
exec "orted $*"
```
and then add "--launch-agent myscript" to your mpirun cmd line

**Comment by ggouaillardet** [comment]
This could be a related issue (that does not involve torque)

I use two nodes `n[0-1]` and forced `sshd` on `n1` in a cpuset with cpus `[1-2]` (note cpu 0 is **not** part of the cpuset)
and then from `n0`

```
[gilles@n0 ~]$ mpirun --host n1 --bind-to core --report-bindings true
--------------------------------------------------------------------------
Open MPI tried to bind a new process, but something went wrong.  The
process was killed without launching the target application.  Your job
will now abort.

  Local host:        n1
  Application name:  /usr/bin/true
  Error message:     hwloc_set_cpubind returned "Error" for bitmap "0"
  Location:          ../../../../../../src/ompi-master/orte/mca/rtc/hwloc/rtc_hwloc.c:382
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun was unable to start the specified application as it encountered an
error:

Error code: 1
Error name: (null)
Node: n1

when attempting to start process rank 0.
--------------------------------------------------------------------------
```

**Comment by rhc54** [comment]
@ggouaillardet Just for the sake of my old brain, help me try to understand your scenario. You define a cgroup on n1 and then execute mpirun from n0. mpirun starts an orted on n1 - but how did that orted get added to the cgroup? Guess I'm confused as to how this is operating, so any clarification would be appreciated.

**Comment by ggouaillardet** [comment]
@rhc54 I put `sshd` into the cpuset (I just realized I used cpuset and not croup !) and then used `plm/rsh` so `orted` inherited the cpuset from sshd.
I should give cgroups a try, but that might have to wait until Monday.

**Comment by rhc54** [comment]
Hmmm...is this with master (i.e., with the hwloc 2.0 support)? Or with a release based on hwloc 1.11? I ask because there was a significant change in the 2.0 integration and how we handled "available" cpus, and I'm wondering if that is broken.

**Comment by ggouaillardet** [comment]
Surprisingly, both latest `master` and `v3.1.x` have the same behavior.

**Comment by rhc54** [comment]
That is surprising. Another way to test this is just to add the --cpu-set option to mpirun. This will apply a "mask" to the discovered cpus and only bind inside the result. If that works, then it tells us that the problem lies in the discovery process itself, and not in ORTE.

**Comment by rhc54** [comment]
In other words, this should tell us if ORTE is trying to work outside the bounds, or if ORTE is being given bad information.

**Comment by twhitehead** [comment]
Sorry for such a long delay in getting back on this.  I launch the job under a torque session with the command as suggested
```
mpirun ./launch --bind-to core --hetero-nodes --launch-agent launch.sh <prog> <args>
```
where the `launch` is
```
#!/bin/bash
sleep 5
exec ./result/bin/orted "$@"
```
But I just get the message that `orted` doesn't support `--bind-to core`.
```
./result/bin/orted: Error: unknown option "--bind-to"
```


Thanks!  -Tyson

**Comment by rhc54** [comment]
Weird - I don’t see this message on the github issue. I’ll reply here anyway.

Sorry we weren’t clear - your cmd line isn’t quite correct. Here is what we were expecting:

```
mpirun --bind-to core --hetero-nodes --launch-agent ./launch <prog> <args>
```
This tells ORTE to use your launch script to start the remote orted.

**Comment by twhitehead** [comment]
Sorry about the disappearing message.  I realized there were some mistakes, so I deleted it and reran with them corrected.  Forgot that it would have emailed people.  What I ended up launching with was
```
mpirun --bind-to core --launch-agent launch <program> <args>
```
where `launch` is the script
```
#!/bin/bash
sleep 5
exec orted "$@"
```

It seems, however, that I am still seeing the error message
```
--------------------------------------------------------------------------
A request was made to bind to that would result in binding more
processes than cpus on a resource:

   Bind to:     CORE
   Node:        orc343
   #processes:  2
   #cpus:       1

You can override this protection by adding the "overload-allowed"
option to your binding directive.
--------------------------------------------------------------------------
[orc343:57381] 2 more processes have sent help message help-orte-rmaps-base.txt / rmaps:binding-overload
[orc343:57381] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

Thanks!  -Tyson

PS:  It turns out our admins are repaving this cluster with a slurm based system, so I won't be able to test anything more in a couple of weeks.  I guess that will solve the problem (in an unsatisfying way).

**Comment by rhc54** [comment]
Truly odd - honestly unsure of what to try next. We can take a look at the ```--cpuset``` option and see what that tells us, but I doubt anyone here will have access to a torque system to take this any further. Hopefully you won't see the same behavior once your machine is repaved, though you might if it is indeed an issue with hwloc.

**Comment by hppritcha** [comment]
@twhitehead is this still an issue?

**Comment by twhitehead** [comment]
We no longer have any torque based clusters, so I cannot test this anymore. I would suggest we just close the ticket then. If someone else is still experiencing it, they can open it back up.
