### ISSUE TITLE
MPI_Waitsome implementation is breaking MPI standard

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#5268]
According to the discussion at the MPI Forum (https://github.com/mpi-forum/mpi-issues/issues/86) the current implementation of MPI_Waitsome in Open MPI is not correct.

Currently, we are using `indices` array to store temporal information and consider that the size of `indices` is equal to an income `count` parameter [req_wait.c:422](https://github.com/open-mpi/ompi/blob/f9bfb9d2393fb6db3698ebb80945e34fceaaea91/ompi/request/req_wait.c#L422).
However according to the discussion at the forum today it is not guaranteed that the size of the `indices` is equal to the `count`. Consider the following example:
```C
int reqs_left = total_requests;
int offset = 0;
int indices[total_requests];
while(request_left) {
    int outcount;
    MPI_Waitsome( total_requests, requests, &outcount, indices + offset, MPI_STATUSES_IGNORE);
    offset += outcount;
    requests_left -= outcount;
}
```

**Comment by artpol84** [comment]
I expect mpi-forum/mpi-issues#86 to be updated later today, but I'm opening the ticket now to make sure we are keeping track of it.

**Comment by Akshay-Venkatesh** [comment]
Cross referencing https://github.com/open-mpi/ompi/pull/4897
Looks there's an approved PR for this

**Comment by hppritcha** [comment]
Looks like this problem is also in 3.0.x and 3.1.x.

**Comment by bosilca** [comment]
Reading through the [MPI Forum ticket \#86](https://github.com/mpi-forum/mpi-issues/issues/86) I understand that the forum validated our implementation by making incount the length of array_of_requests, array_of_indices, and array_of_statuses.

**Comment by artpol84** [comment]
I think they forgot to update the ticket.

**Comment by artpol84** [comment]
@bosilca please see https://github.com/mpi-forum/mpi-standard/pull/42

**Comment by bosilca** [comment]
I know I commented on the ticket. I don't think the forum should bless an unoptimized way of writing code.

**Comment by jsquyres** [comment]
@bosilca @artpol84 Do we need to do anything here?

**Comment by bosilca** [comment]
Yes, we should merge #4897.

**Comment by jsquyres** [comment]
#4897 merged.  Closing this issue.
