### ISSUE TITLE
pmix_list_remove_item failed assertion following OSC segfault

### ISSUE THREAD

**Issue by PeterGottesman** [open-mpi/ompi#5335]
In several tests the following error is occurring following a segfault caused by #5262.
```
Warning :: pmix_list_remove_item - the item
0x2aaaac037cc0 is not on the list 0x2aaaab48e7a8 
mpirun: server/pmix_server.c:2318: _mdxcbfunc: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) ==
((pmix_object_t *) (tracker))->obj_magic_id' failed.
```

Here is a sample bt from win_allocate:
```
(gdb) bt
#0  0x000000000073f5c0 in ?? ()
#1  0x00002aaaaab37fb0 in ompi_win_free (win=0x73f060) at win/win.c:362
#2  0x00002aaaaabaf5cb in PMPI_Win_free (win=0x7fffffffcd58) at pwin_free.c:53
#3  0x0000000000401104 in main (argc=1, argv=0x7fffffffce58) at win_allocate.c:43
```
It seems the issue is at [win/win.c:362](https://github.com/open-mpi/ompi/blob/master/ompi/win/win.c#L362), where a call is made to a stale function pointer. 

See https://mtt.open-mpi.org/index.php?do_redir=2641 for all tests currently encountering this issue.

@hjelmn @rhc54

**Comment by rhc54** [comment]
I suspect things get rather crazy after a segfault - I can look to harden the PMIx server, but it wouldn't be a priority. I'd say the error of concern here is the OSC segfault which you cover in #5262, yes?

**Comment by PeterGottesman** [comment]
That was my suspicion, I just wanted to open this up in case it was a symptom of some other pmix issue.

**Comment by rhc54** [comment]
Don't think so - it's a race condition where the server sees the proc go away and cleans up, but ORTE still calls back with some modex info in it. Need to ensure the cleanup is complete and avoid the problem.

**Comment by PeterGottesman** [comment]
As #5262 was solved, closing this.
