### ISSUE TITLE
Missing 'end interface' in current OMPI master branch 

### ISSUE THREAD

**Issue by fsciortino** [open-mpi/ompi#5346]
The code at  `ompi/ompi/mpi/fortran/use-mpi-tkr/mpi-f90-removed-interfaces.h ` is clearly missing an `end interface` at the very end. This was identified by @jmstover while discussing OpenMPI and mpi4py compatibility in Singularity: [https://github.com/singularityware/singularity/issues/1689#issuecomment-400748085](url). 

As a consequence of the missing `end interface`, installation of the latest release of OMPI may crash at the make step. Addition of the line 
` echo "end interface" >> ompi/mpi/fortran/use-mpi-tkr/mpi-f90-removed-interfaces.h`
between the "configure" and the "make" step solves the problem, as expected.

**Comment by jsquyres** [comment]
Fixed!  Thanks for bringing it to our attention.
