### ISSUE TITLE
Excessive MPI_Handler_function deprecated warnings: just from including mpi.h

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#5357]
We recently added `--enable-mpi1-compatibility` and by default no longer compile things that were removed from the standard long ago.  We also added deprecation markers to scold users when they use these ancient functions.  These are generally Good Things.

However, if you compile with `--enable-mpi1-compatibilty`, just the act of `#include <mpi.h>` results in deprecation warnings.  For example, here's compiling `examples/hello_c.c`:

```
mpicc -g  hello_c.c  -o hello_c
In file included from hello_c.c:11:0:
/home/jsquyres/bogus/include/mpi.h:2673:1: warning: ‘MPI_Handler_function’ is deprecated: MPI_Handler_function was removed in MPI-3.0; use MPI_Win_errhandler_function instead [-Wdeprecated-declarations]
 OMPI_DECLSPEC  int MPI_Errhandler_create(MPI_Handler_function *function,
 ^
/home/jsquyres/bogus/include/mpi.h:2712:1: warning: ‘MPI_Handler_function’ is deprecated: MPI_Handler_function was removed in MPI-3.0; use MPI_Win_errhandler_function instead [-Wdeprecated-declarations]
 OMPI_DECLSPEC  int PMPI_Errhandler_create(MPI_Handler_function *function,
 ^
```

This is because `MPI_Handler_function` is a deprecated/removed type, but it is used in the MPI-1 functions `[P]MPI_Errhandler_create()`, which are prototyped in `mpi.h`.

We should not be causing warnings like this *just for enabling MPI-1 compatibility* -- specifically when the MPI application is not using any MPI-1 functionality.

What is odd, however, is that we don't get warnings for other function typedefs, like `MPI_Copy_function`, and others.  This is what I don't understand, and why I haven't just created a PR that simply removes the deprecation warning from `MPI_Handler_function` in `mpi.h`.

Does anyone know why this is happening?

FYI @hjelmn

**Comment by hjelmn** [comment]
Guess my approach was heavy handed. We have to remove the deprecated warning on the types that are causing the problem or we can make them void*s where they are used in mpi.h

**Comment by jsquyres** [comment]
Here's all the function pointer typedefs in mpi.h.in: https://github.com/open-mpi/ompi/blob/master/ompi/include/mpi.h.in#L418-L433

I'm happy to make a PR that removes those attributes.  ...but why is it *only* causing a problem for `MPI_Handler_function`?  That's my real question.

**Comment by jsquyres** [comment]
Oh, I just answered my own question by reading the code a little more carefully.  `MPI_Comm_errhandler_fn` was deprecated (which is not used anywhere else in `mpi.h.in`); `MPI_Comm_errhandler_function` was not.

So I think the only deprecation/removed warning that needs to be removed is for `MPI_Handler_function`.  I'll file a PR.
