### ISSUE TITLE
XPMEM detected but ./configure says it's not

### ISSUE THREAD

**Issue by mkre** [open-mpi/ompi#5377]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

v3.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

from a source tarball

## Details of the problem

I'm configuring Open MPI to support XPMEM. I'm pointing `./configure` towards my XPMEM directory, and it seems like it's correctly detected. So far, so good. However, the summary output of `./configure` reads
```
Transports
-----------------------
...
Shared memory/XPMEM: no
...
```
I think the problem is in `config/opal_check_xpmem.m4` in the definition of the macro `OPAL_CHECK_XPMEM` in line 104:
```
OPAL_SUMMARY_ADD([[Transports]],[[Shared memory/XPMEM]],[$1], $opal_check_cray_xpmem_happy])
```
Instead of adding the result of the XPMEM check to the summary, the result of the (failing) Cray-XPMEM check is added. Replacing this line with
```
OPAL_SUMMARY_ADD([[Transports]],[[Shared memory/XPMEM]],[$1], $opal_check_xpmem_happy])
```
fixes the problem and leads to the expected output `Shared memory/XPMEM: yes`.

## Patch

If I understood the issue correctly, it can be fixed with the following patch:
```
diff --git a/config/opal_check_xpmem.m4 b/config/opal_check_xpmem.m4
index aed1323..58cfff3 100644
--- a/config/opal_check_xpmem.m4
+++ b/config/opal_check_xpmem.m4
@@ -101,7 +101,7 @@ AC_DEFUN([OPAL_CHECK_XPMEM], [
            fi
        fi
 
-       OPAL_SUMMARY_ADD([[Transports]],[[Shared memory/XPMEM]],[$1],[$opal_check_cray_xpmem_happy])
+       OPAL_SUMMARY_ADD([[Transports]],[[Shared memory/XPMEM]],[$1],[$opal_check_xpmem_happy])
     fi
 
     AS_IF([test "$opal_check_xpmem_happy" = "yes"], [
```
I can also post a pull request if required.

**Comment by ggouaillardet** [comment]
Should we instead have `yes` in the summary if either cray __or__ stock xpmem is available ?

@hjelmn any thoughts ?

**Comment by hjelmn** [comment]
Yes. this is the correct patch

**Comment by ggouaillardet** [comment]
@hjelmn on second thought, if cray xpmem works, then `opal_check_xpmem_happy` is set to `yes`, so the initially suggested patch is correct (e.g. my suggestion is an overkill).

@mkre can you please issue a PR ? note you need to sign-off your commit (IANAL, make sure you understand the implications) so it can be accepted in Open MPI.

**Comment by jsquyres** [comment]
@mkre 👍 on what others said.  Please make a PR against master, and we'll merge it in.  Then it can be cherry-picked to the release branches.

Thank you!

**Comment by jsquyres** [comment]
Leaving this issue open until we decide which release branches #5403 needs to be cherry picked to (note: #5403 was merged to master before v4.0.x was created, so it doesn't need to be picked there).

**Comment by jsquyres** [comment]
Executive decision on 2018-09-14: per above, this is not an issue for v4.0.x.  Target v3.0.x and v3.1.x (PRs filed).  Not worth it for v2.1.x.

**Comment by jsquyres** [comment]
Now merged to all relevant release branches.  Closing.
