### ISSUE TITLE
MPI onesided test hangs

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#538]
I don't know if the test is correct or not, but the onesided/t_winf test hangs on master and v1.8 branches.

The hang happens somewhere in this block of code:

https://github.com/open-mpi/ompi-tests/blob/master/onesided/t_winf.f90#L215-L238

**Comment by jsquyres** [comment]
Similarly, the cxx-test-suite hangs during the test of MPI::Win::wait on the v1.8 branch (where the C++ bindings are still built by default):

```
* MPI::Win...                                     
  - Alloc_mem...                                  PASS
  - Create...                                     PASS
  - Fence...                                      
    o Accumulate...                               PASS
  - Fence...                                      PASS
  - Lock...                                       PASS
  - Put...                                        PASS
  - Get...                                        PASS
  - Set_name/Get_name...                          PASS
  - Get_group...                                  PASS
  - Post/Start/Wait/Complete/Test...              
    o Post...                                     PASS
    o Test...                                     PASS
    o Start...                                    PASS
    o Put...                                      PASS
    o Complete...                                 PASS
    o Wait...                                     [...hang...]
```

**Comment by hjelmn** [comment]
Wrote a C version of the part of t_winf that is hanging and I can't get it to hang.

**Comment by hjelmn** [comment]
Will enable the C++ bindings in my build and see what is happening there.

**Comment by jsquyres** [comment]
@hjelmn Is t_winf hanging for you?  I ran it through DDT and it shows that t_winf is hanging on line 221 (the MPI_Win_wait()).
