### ISSUE TITLE
MPI_Type_vector() without striding but send > 2 GB

### ISSUE THREAD

**Issue by asylvest** [open-mpi/ompi#5387]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
2.1.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Compiled from source tarball using gcc 4.9.1

### Please describe the system on which you are running

* Operating system/version:  RHEL 7
* Computer hardware: 16 core Intel machine
* Network type: TCP

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -np 2 ./hello_world
```

I have a large 2D float image which I am asynchronously sending a subset of columns to another rank on via MPI_Isend() and asynchronously receiving on that other rank via MPI_Irecv().  So, I'm creating an

MPI_Type_vector(totalNumRowsToSend, numColsToSend, totalNumColsInImage, MPI_FLOAT, dataType)

And then I perform the MPI_Isend() / MPI_Irecv() sending in the vector's data type and a count of 1.  The amount of data I'm sending is large - it's well over INT_MAX but totalNumRowsToSend, numColsToSend, and totalNumColsInImage are all less than INT_MAX.

When numColsToSend < totalNumColsInImage, everything works properly.

Occasionally, I actually need to send all columns of the image.  I wasn't treating this as a special case in the code, so I'd end up creating an MPI_Type_vector() where numColsToSend == totalNumColsInImage and I'd expect all columns to be sent.  I get strange behavior - there's no error or crash on the send or receive side, but not all of the pixels seem to be sent.

I'm guessing there's a check in the underlying Open MPI code which notices that it can do a single contiguous send - no striding is needed - but that that optimized path through the code is using an int somewhere and can't handle > 2 GB.

In the meantime I'm working around this by adding a check in my calling code and when numColsToSend == totalNumColsInImage I make an MPI_Type_contiguous() instead.  This works fine but of course it would be nice if that check wasn't needed on my end.

**Comment by ggouaillardet** [comment]
can you please upload a simple program that evidences the issue ?

**Comment by bosilca** [comment]
By looking at the generated datatype I can't see a difference between the 2 ways of creating them (vector and contiguous). Thus, I assume the issue here is that one of the BTL/PML might handle the 2 types differently, but with the information available so far on this issue it is impossible to know where to continue looking.

**Comment by jsquyres** [comment]
@asylvest Without a small reproducer program, we can't really go much further on this.  If you can supply us with a small program that shows the issue, we can re-open this issue.  Thanks!
