### ISSUE TITLE
v2.x: PMIx timeout in dynamic tests

### ISSUE THREAD

**Issue by PeterGottesman** [open-mpi/ompi#5396]
I am seeing the following error in several tests on v2.x on Cisco MTT:
```
[mpi012:04020] OPAL ERROR: Timeout in file base/pmix_base_fns.c at line 195
[mpi012:04020] *** An error occurred in MPI_Init
[mpi012:04020] *** on a NULL communicator
[mpi012:04020] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[mpi012:04020] ***    and potentially your MPI job
```
The full list of impacted tests is [here](https://mtt.open-mpi.org/index.php?do_redir=2649).

Currently I am unable to reproduce this error, although it is causing a large number of failures (~500). I will continue to run tests tomorrow and hopefully get some more information.

@rhc54 Any insight into what might be occurring here?

**Comment by rhc54** [comment]
MPI dynamics are not supported in OMPI v2.x - those tests are guaranteed to fail and should not be executing.

**Comment by PeterGottesman** [comment]
Thanks Ralph! I will push an updated INI in a few.
