### ISSUE TITLE
Incorrect intent on Fortran 08 interfaces to MPI_All* routines

### ISSUE THREAD

**Issue by PhilippOtte** [open-mpi/ompi#5442]
The intent of the receive buffer is declared incorrectly as intent(in) in all MPI_All* routines in the mpi-f08 module on the master branch of version 3.1. According to version 3.1 of the MPI standard (appendix A.3.3), the intent of the receive buffers should be intent(inout) (default). Note that the intent of the receive buffer in MPI_Recv is set according to the standard.

If the receive buffer is of intent(in), the compiler is free to optimize the routine in illegal ways.
For example, the compiler is allowed to interchange the following two calls:
```Fortran
call MPI_Alltoall(sndbuf,100,MPI_INT,recvbuf,100,MPI_INT,MPI_COMM_WORLD)
call MPI_Allreduce(sndbuf,recvbuf,1,MPI_INT,MPI_MAX,MPI_COMM_WORLD)
```
into:
```Fortran
call MPI_Allreduce(sndbuf,recvbuf,1,MPI_INT,MPI_MAX,MPI_COMM_WORLD)
call MPI_Alltoall(sndbuf,100,MPI_INT,recvbuf,100,MPI_INT,MPI_COMM_WORLD)
```

The problem could easily be fixed by setting the intent of recvbuf in all MPI_All* routines to intent(inout).

**Comment by PhilippOtte** [comment]
Thank you Gilles for the explanation. I will pose a PR with corrected function definitions for the MPI_All* and MPI_Iall* interfaces and their ompi interfaces.

**Comment by PhilippOtte** [comment]
I filed a PR. Please note that I was very careful while editing but was not able to compile the files as I did not manage to compile required parts of the code on my machine.

**Comment by jsquyres** [comment]
@ggouaillardet I made a v3.1.x (#5781) and v4.0.x (#5780) PRs corresponding the master PR you made (#5453).  But I ran into conflicts trying to make a v3.0.x PR.

Could you make a backport PR for v3.0.x?

**Comment by jsquyres** [comment]
This was merged against all the release branches a while ago.
