### ISSUE TITLE
Bug-Report: You missed the definition of OMPI_IMPORTS in mpi.h (1.6.2 binary installer for win32)

### ISSUE THREAD

**Issue by compressible** [open-mpi/ompi#5465]
Thank you for taking the time to submit an issue!

### Describe how Open MPI was installed
Just click next and next to install it

### Please describe the system on which you are running

* Operating system/version:   Win7 (32bit mode)

-----------------------------

## Details of the problem

`OMPI_IMPORTS` should be defined in mpi.h, but acturally it's not.  So while my vs2010 linking aginst libmpi.lib , the variables cannot be find.  Add `OMPI_IMPORTS` definition in mpi.h(in installer package) will fix the bug.

**Comment by PeterGottesman** [comment]
Version 1.6.2 is long out of maintenance and is six years old at this point. If you really need to run on windows, you should still be able to use a cygwin build of it.
Try using the cygwin 3.1.x build and see if you are still running into similar issues.

**Comment by jsquyres** [comment]
@compressible @PeterGottesman is correct: v1.6.2 is no longer maintained.  Indeed, "native" builds of Open MPI on Windows are no longer supported in recent versions, but the Cygwin community still maintains patches (and diligently sends them back upstream to us) for building/running Open MPI on Windows in a Cygwin environment.

Given the lack of reply, I'm going to close this issue.
