### ISSUE TITLE
incorrect link in the FAQ page

### ISSUE THREAD

**Issue by mherkazandjian** [open-mpi/ompi#5481]
Hi,

In the FAQ page 

   https://www.open-mpi.org/faq/?category=openfabrics#ib-locked-pages-user

the following hyperlink

       http://www.kernel.org/pub/linux/libs/pam/Linux-PAM-html/

points to a location that is empty. Is this intentional?

**Comment by PeterGottesman** [comment]
Thanks for letting us know. Unfortunately, the FAQs are becoming quite dated. It is on my TODO to get them updated but it certainly won't happen overnight.
For the record, the correct URL for that seems to be http://www.linux-pam.org/Linux-PAM-html/sag-pam_limits.html.

**Comment by mherkazandjian** [comment]
no worries. Thank you for the updated link.

**Comment by jsquyres** [comment]
Fixed in https://github.com/open-mpi/ompi-www/pull/84.  It'll auto-deploy on the web site in a few minutes.  

Thanks for pointing out the stale link!
