### ISSUE TITLE
bind-to core seems not work

### ISSUE THREAD

**Issue by DensenLiu** [open-mpi/ompi#5488]
i run the osu benchmark,use by core and by muna,it has a little difference. In theory, there should be a 30% gap.
 
shell$mpirun --allow-run-as-root -np 2 --bind-to core --map-by core osu_latency
# OSU MPI Latency Test v5.4.1
# Size          Latency (us)
0                       0.52
1                       0.60
2                       0.60
4                       0.64
8                       0.63
16                      0.69
32                      0.70
64                      0.70
128                     0.79
256                     0.84
512                     1.04
1024                    1.21
2048                    1.43
4096                    2.70
8192                    2.97
16384                   4.00
32768                   5.34
65536                   8.33
131072                 15.98
262144                 35.74
524288                 70.56
1048576               139.44
2097152               286.12
4194304               572.76

==============================================
shell$mpirun --allow-run-as-root -np 2 --bind-to core --map-by numa osu_latency
# OSU MPI Latency Test v5.4.1
# Size          Latency (us)
0                       0.72
1                       0.78
2                       0.77
4                       0.90
8                       0.90
16                      1.08
32                      1.11
64                      1.07
128                     1.33
256                     1.38
512                     1.64
1024                    2.08
2048                    2.46
4096                    4.20
8192                    4.16
16384                   4.72
32768                   6.09
65536                   9.23
131072                 16.60
262144                 36.51
524288                 70.26
1048576               136.71
2097152               281.61
4194304               570.64
**

**Comment by rhc54** [comment]
You don't say what version of OMPI you are using, but it probably is something more recent than 1.7 which is when we started binding by default. For np=2 we automatically bind-to core, so there shouldn't be any difference in your results.

**Comment by DensenLiu** [comment]
thank for your answer.
My OMPI version is 3.1.0. on one hand, i use --bind to core --map-by core,the two core in the same numa,and on the other hand,the two core in the different numa.  According to the architecture of the cpu, It should takes longer to communicate across numa.
my cpu  model is Intel(R) Xeon(R) CPU E5-2699 v3.

mpirun --allow-run-as-root -np 2 --bind-to core --map-by core --report-bindings osu_latency
 MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../../../../../../../../../../../..][../../../../../../../../../../../../../../../../../..]
 MCW rank 1 bound to socket 0[core 1[hwt 0-1]]: [../BB/../../../../../../../../../../../../../../../..][../../../../../../../../../../../../../../../../../..]
==========================================================
mpirun --allow-run-as-root -np 2 --bind-to core --map-by numa --report-bindings osu_latency    
MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../../../../../../../../../../../..][../../../../../../../../../../../../../../../../../..]
 MCW rank 1 bound to socket 1[core 18[hwt 0-1]]: [../../../../../../../../../../../../../../../../../..][BB/../../../../../../../../../../../../../../../../..]

**Comment by DensenLiu** [comment]
thank for your answer.
My OMPI version is 3.1.0. on one hand, i use --bind to core --map-by core,the two core in the same numa,and on the other hand,the two core in the different numa. According to the architecture of the cpu, It should takes longer to communicate across numa.
my cpu model is Intel(R) Xeon(R) CPU E5-2699 v3.
-----------------------------------------------------
mpirun --allow-run-as-root -np 2 --bind-to core --map-by core --report-bindings osu_latency
MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../../../../../../../../../../../..][../../../../../../../../../../../../../../../../../..]
MCW rank 1 bound to socket 0[core 1[hwt 0-1]]: [../BB/../../../../../../../../../../../../../../../..][../../../../../../../../../../../../../../../../../..]
-----------------------------------------------------
mpirun --allow-run-as-root -np 2 --bind-to core --map-by numa --report-bindings osu_latency
MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../../../../../../../../../../../..][../../../../../../../../../../../../../../../../../..]
MCW rank 1 bound to socket 1[core 18[hwt 0-1]]: [../../../../../../../../../../../../../../../../../..][BB/../../../../../../../../../../../../../../../../..]

**Comment by rhc54** [comment]
I'll have to let someone else address your timing results - you might want to change the title of this issue, however, as the binding options seem to be working just fine. If you don't trust the OMPI report on their location, you can always use the numa cmd line to verify it:
```shell
$ mpirun -H rhc001:24 -n 2 --map-by socket --report-bindings --bind-to core  numactl -s
policy: default
preferred node: current
physcpubind: 0 24 
cpubind: 0 
nodebind: 0 
membind: 0 1 
[rhc001:182024] MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../../../../../..][../../../../../../../../../../../..]
[rhc001:182024] MCW rank 1 bound to socket 1[core 12[hwt 0-1]]: [../../../../../../../../../../../..][BB/../../../../../../../../../../..]
policy: default
preferred node: current
physcpubind: 12 36 
cpubind: 1 
nodebind: 1 
membind: 0 1 
```

**Comment by DensenLiu** [comment]
thank you ,I`ll create a new issue,and close this one.
