### ISSUE TITLE
Improve error handling in openib component init and add_procs

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#55]
The current error handling in module_init and add_procs is abysmal and usually results in segv's after the openib BTL returns.

Part of the issue is: what should the BTL do if add_procs() fails?  I started a discussion here:

    http://www.open-mpi.org/community/lists/devel/2008/08/4498.php

I have much of the cleanup work done, but need a ruling on what the BTL is supposed to do if add_procs() fails.

**Comment by rhc54** [comment]
Per Mellanox, this can be closed. Any further work will be done on a separate new ticket.
