### ISSUE TITLE
opal/util/cmd_line warning

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#5511]
In head of master using gcc-7.3:
```shell
cmd_line.c: In function 'opal_cmd_line_make_opt3':
cmd_line.c:1037:26: warning: 'e.ocl_otype' may be used uninitialized in this function [-Wmaybe-uninitialized]
     option->clo_otype = e->ocl_otype;
```

**Comment by awlauria** [comment]
@rhc54 this may be fixed by the merging of https://github.com/open-mpi/ompi/pull/7299. Can you verify? I don't have that version of gcc available to me.

**Comment by rhc54** [comment]
No idea - I'd consider this stale after this much time. Can always reopen it if it shows up again.
