### ISSUE TITLE
MPI_Init failed: PMIX ERROR: UNPACK-PAST-END in file unpack.c

### ISSUE THREAD

**Issue by chhzh123** [open-mpi/ompi#5535]
## Background information
I'm running a parallel program on a Linux server, however the program crashed when executing  `MPI_Init(&argc, &argv);`.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v3.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Directly downloaded openmpi-3.1.1.tar.gz from https://www.open-mpi.org/software/ompi/v3.1/ and installed.

### Please describe the system on which you are running

* Operating system/version:  Ubuntu 18.04 LTS
* Computer hardware: Intel Xeon CPU (12 core)

-----------------------------

## Details of the problem

The program seems crashed in the first place.
The main function is like this

```cpp
int main(int argc, char* argv[]) {
  MPI_Init(&argc, &argv);
  // do something
  MPI_Finalize();
}
```

It's quite simple, but I got the following errors.

```shell
$ mpirun -np 12 main
[HAS-T640:11663] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 206
[HAS-T640:11663] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 147
[HAS-T640:11663] PMIX ERROR: UNPACK-PAST-END in file client/pmix_client.c at line 228
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[HAS-T640:11663] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[HAS-T640:11663] OPAL ERROR: Error in file pmix2x_client.c at line 109
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
[HAS-T640:11664] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 206
[HAS-T640:11664] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 147
[HAS-T640:11664] PMIX ERROR: UNPACK-PAST-END in file client/pmix_client.c at line 228
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[HAS-T640:11664] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[HAS-T640:11664] OPAL ERROR: Error in file pmix2x_client.c at line 109
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[60311,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

I don't know what the errors mean and how to fix them.
I make sure I correctly installed OpenMPI, because I have run the examples given in your package without errors.

**Comment by rhc54** [comment]
Did you compile your application using the correct mpicc? Your app appears to be using a different version of PMIx than is in mpirun.

**Comment by chhzh123** [comment]
@rhc54 What do you mean by "the correct mpicc"? I did compile my application using OpenMPI and succeeded.

If they are different, how can I check the version of PMIx in mpirun and in the application?

**Comment by rhc54** [comment]
What I'm asking is if you recompiled your application using the mpicc from this installation of OMPI? This error often appears because a user failed to do so - they ran an executable compiled with some prior version of OMPI.

**Comment by chhzh123** [comment]
It is the version problem. Thanks a lot!
