### ISSUE TITLE
MPI preventing ROS Workspace from Building

### ISSUE THREAD

**Issue by jav-solo** [open-mpi/ompi#5566]
Thank you for taking the time to submit an issue!

## Background information
I have build this ROS workspace before without issues in ROS Indigo and UBuntu 14.04 and I am trying to migrate my workspace to ROS Kinetic and Ubuntu 16.04

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v1.10.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
I am not sure but I believe it was either through ROS or MoveIt!

### Please describe the system on which you are running

* Operating system/version: Ubuntu 16.4

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

I am getting the following build error. It seems like a linking issue in my CMakeLists.txt but I cannot figure it out. 

```
/usr/bin/ld: CMakeFiles/build_tree.dir/src/build_tree.cpp.o: undefined reference to symbol '_ZN3MPI8Datatype4FreeEv'
//usr/lib/libmpi_cxx.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [/home/jlp/fanuc_kws/devel/.private/classifier/lib/classifier/build_tree] Error 1
make[1]: *** [CMakeFiles/build_tree.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: CMakeFiles/nearest_neighbors.dir/src/nearest_neighbors.cpp.o: undefined reference to symbol '_ZN3MPI8Datatype4FreeEv'
//usr/lib/libmpi_cxx.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [/home/jlp/fanuc_kws/devel/.private/classifier/lib/classifier/nearest_neighbors] Error 1
make[1]: *** [CMakeFiles/nearest_neighbors.dir/all] Error 2
/usr/bin/ld: CMakeFiles/correspondence_grouping.dir/src/correspondence_grouping.cpp.o: undefined reference to symbol '_ZN3MPI8Datatype4FreeEv'
//usr/lib/libmpi_cxx.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [/home/jlp/fanuc_kws/devel/.private/classifier/lib/classifier/correspondence_grouping] Error 1
make[1]: *** [CMakeFiles/correspondence_grouping.dir/all] Error 2
make: *** [all] Error 2
cd /home/jlp/fanuc_kws/build/classifier; catkin build --get-env classifier | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
```

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -np 2 ./hello_world
```

**Comment by ggouaillardet** [comment]
please extract your link command.

that kind of error can happen if for example your object has undefined reference to `foo()`, that is provided by `libfoo.so`, but you only link with `libbar.so` that depends on `libfoo.so`. In this case, you need to explicitly link with `libbar.so` __and__ `libfoo.so`.

Note the MPI C++ bindings have been removed from the MPI standard a while ago and are no more built by default. Also, Open MPI `v1.10` series is no more supported (`v2.1`, `v3.0` and `v3.1` are)

**Comment by jsquyres** [comment]
Is there any chance you can upgrade to Open MPI v3.1.2?

As @ggouaillardet mentioned, the v1.10 series isn't really supported any more.

**Comment by jav-solo** [comment]
That did not work, however simply putting find_package(PCL REQUIRED) after the other find_packages(), but before it looks for the HDF5 package. Thank you for your help.
