### ISSUE TITLE
v2.0.x: osc/rdma: MPI_Win_unlock segfaults

### ISSUE THREAD

**Issue by derbeyn** [open-mpi/ompi#5581]
Thank you for taking the time to submit an issue!

## Background information
using osc/rdma
calling osu_acc_latency -m create -s lock

leads to a segfault in MPi_Win_unlock()

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v2.0.x

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### Please describe the system on which you are running

* Operating system/version: 
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem

MPI_Win_unlock() segfaults because of an access to a NULL pointer in ompi_osc_rdma_lock_btl_fop().
This issue is specific to v2.0.x: starting from v2.x, the locking code has been reworked and the issue implicitely fixed.

will submit a fix

**Comment by jsquyres** [comment]
Fixed via #5582.
