### ISSUE TITLE
Missing symbols on Haiku

### ISSUE THREAD

**Issue by extrowerk** [open-mpi/ompi#5588]
Hi,

## Background information

i'm on my way to get openmpi working on Haiku. The recipe is already made and the required patch upstreamed. During the test it fails and i can't find the culprit.
While i know Haiku is not a main platform for openmpi project, porting a software to some uncommon OS can help to find bugs and to maintain better portability trough testing on different platforms, compilers.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

3.1.1, yet untested on 3.1.2 but i start the build right now to test it.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

The current Haiku recipe resides here:
https://github.com/haikuports/haikuports/tree/78e07fe663a367249cd933f482447fa7a4626b88/sys-cluster/openmpi

Compiler: GCC7.3.0
Arch: x86_64

### Please describe the system on which you are running

* Operating system/version: Haiku shredder 1 hrev52254 Aug 20 2018 15:59:03 x86_64 x86_64 Haiku

* Computer hardware: x86_64
* Network type: unrelated

-----------------------------

## Details of the problem

Tests fails due missing symbols in openmpi lib:

```
FAIL: predefined_gap_test
=========================

runtime_loader: /sources/openmpi-3.1.1/opal/.libs/libopen-pal.so.40.10.1: Troubles relocating: Symbol not found
yval_parse_done'
FAIL predefined_gap_test (exit status: 4)
```

Strange, but somehow the symbol name got truncated. Grepping the source tree points to different symbol:

* opal_util_keyval_parse_done
* pmix_util_keyval_parse_done

Running the test manually runtime_loader reports unturncated:

```
runtime_loader: /boot/system/lib/libopen-pal.so.40.10.1: Could not resolve symbol 'opal_util_keyval_parse_done'
resolve symbol "opal_util_keyval_parse_done" returned: -2147478780
```

I can't seem to find where this symbol comes from and what am i doing wrong. 
I would greatly appreciate any help. Let me know if you need any more info.

Thanks!

**Comment by bwbarrett** [comment]
I don't know much about Haiku, but the missing symbol is part of Open MPI's use of Yacc/Bison.  Including the config.log file from your build of Open MPI as well as some information about whether Haiku uses some BSD Yacc variant or GNU Bison (and which version of either) would probably be a good starting point.

That code hasn't changed in <long time>, so I'd expect you'll see the issue across all current releases.

**Comment by extrowerk** [comment]
Tested with 3.1.2, the problem appears to be the same:
```
FAIL: predefined_gap_test
=========================

runtime_loader: /sources/openmpi-3.1.2/opal/.libs/libopen-pal.so.40.10.2: Troubles relocating: Symbol not found
yval_parse_done'
FAIL predefined_gap_test (exit status: 4)
```

**Comment by extrowerk** [comment]
@bwbarrett : Thanks for the reply.
The current recipe doesn't defines yacc or bison as dependency, thus they will be not available in the chroot. Are one of them is a mandatory dependency? If so, shouldn't it emit some error or warning?

Current bison port: bison-3.0.5-1-x86_64.hpkg
Yacc would be also available: byacc-20180609-1-x86_64.hpkg

**Comment by extrowerk** [comment]
@bwbarrett : here is the earlier 3.1.1 config log without bison or yacc:
https://gist.github.com/extrowerk/21ca5ae128faa6f6995d3e5ac5b39ecc

And here is a 3.1.2 log with bison and yacc defined in recipe as dependency:
https://gist.github.com/extrowerk/f12373b977d1e8a9a0f4a2c68918b919

**Comment by extrowerk** [comment]
@bwbarrett : thanks, adding bison to the deps solved the problem, now all test passes with 3.1.2.
Please consider to add bison or yacc to the configure checks.

**Comment by extrowerk** [comment]
@ggouaillardet : I assume you haven't met with Haiku recipes yet, they are a simple bash script which defines what are the requiments and dependecies, declares the provided libs and executables, pulls the tarball, extracts it and creates a chroot environment, ataches the defined packages and its dependencies tothe chroot and builds the software as it defined in BUILD() and INSTALL().

 I suppose the current recipe and patchset shows i did not mess with the timestamps: https://github.com/haikuports/haikuports/pull/2947/files

No idea why i had to add bison, but now works as it supposed so i'm happy.

Should i upstream the new patches?

**Comment by ggouaillardet** [comment]
@extrowerk I am extremely puzzled ...

note the `TEST()` recipe is

```
LIBRARY_PATH=$LIBRARY_PATH:$sourceDir/ompi/.libs:$sourceDir/opal/.libs:$sourceDir/orte/.libs make check
```

so when you `make check` within haiku, it uses `/sources/openmpi-3.1.1/opal/.libs/libopen-pal.so.40.10.1`, but when you `make check` from the command line, it uses `/boot/system/lib/libopen-pal.so.40.10.1`.

So you'd rather manually run
```
LIBRARY_PATH=$LIBRARY_PATH:$sourceDir/ompi/.libs:$sourceDir/opal/.libs:$sourceDir/orte/.libs make check
```

did you run `TEST()` __after__ `INSTALL()` ?
I do not believe you should have to set `LD_LIBRARY_PATH` manually (and this is an other story, and a less important one)

I will also fix upstream `test/util/opal_path_nfs.c`, the `HAVE_SYS_MOUNT_H` macro should be used instead of `__HAIKU__`

note that if you mean to use `libevent` provided by haiku (e.g. __not__ the embedded `libevent`, you need to `configure --with-libevent=external`).
since you are building from a tarball and you do not `autogen.pl`, `libtoolize` is not needed here,
(`libtoolize` might have an impact on which `dl` component is built though).


even if I am positive `bison` is not required, can you upload `config.log` with and without `bison` in the dependency ? otherwise it is very hard to compare both log files.

**Comment by rhc54** [comment]
Just to reinforce what @ggouaillardet is saying - Open MPI does _not_ use ```bison``` or ```yacc``` in its build system. We use ```flex```, and you are meeting that dependency because ```bison``` pulls it in as it also depends on ```flex```.

However, we _only_ need ```flex``` when you build from a repo, not a tarball - hence the puzzlement.

**Comment by extrowerk** [comment]
The TEST() stage is a bit complicated, let me try to explain.

After creating the chrooted environment, all the required packages will be attached, and the recipe will be built.
The recipe have INSTALL() part too, but unlike standard installs in Unix/Linux word, the libs will be installed into a DESTROOT for packaging. The installed files will be sorted to different subpackages, runtime, development, etc., some files will be adjusted, the files gets packaged into their respective packages, and the packages will be moved to the "results" folder.

While technically the files are installed, the packages won't get automatically attached to the system, so the "/boot/system/lib/libopen-pal.so.40.10.1" file won't be available after the BUILD() stage. That would contaminate the builder bots, as they using selected packages and the rest would be attached only if they defined in the recipe and only at the beginning of the build process. This is the only way to guarantee there is no extra dependencies, only what is defined in the recipe.

TEST() won't run automatically, one have to start the "haikuporter" tool with the ```--test``` arg to get it tested. In this case the REQUIRED packages will be attached to a clean chroot env, where the test will run. The package with the runtime libs or with the development files won't be attached, so the runtime libs will be accessed from ```/sources/openmpi-3.1.1/opal/.libs/libopen-pal.so.40.10.1```. 
The runtime_loader will searching for libs only in the system lib folder and in the ./lib folder, but OpenMPI places them in ```.libs``` subfolder, thus I had to adjust the LIBRARY_PATH.

I hope it is clear now.

(Btw, i do my ports first normally, like anybody would do on Linux, and after i got it work i do the same in the chroot, that's the reason for mixed outputs in some cases, sorry about that.

**Comment by extrowerk** [comment]
@rhc54 @ggouaillardet : I'm almost sure some declared dependencies are unneeded, will doublecheck and clean it up this weekend and will provide the config logs too. Thanks for the input Guys!

**Comment by extrowerk** [comment]
I can't seem to reproduce it anymore, let's close it till it again surfaces.
