### ISSUE TITLE
Implement remote send cancel in OB1

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#56]
It's not too difficult to add another active message tag in OB1 for canceling remote sends.  It could go something like this:
- Local OB1 cancel call is invoked to cancel a send
- Local OB1 gets the sequence number of the message to send; it sends it to the peer with the AM tag for "cancel"
- Remote OB1 get AM tag "cancel" / invokes the cancel function
- Remote OB1 checks to see if the seq has been matched or not (i.e., if it's on the unexpected queue).  If not, delete the message.
- Remote OB1 returns a message on the AM tag for "cancel results" to the local OB1 indicating whether the message was canceled or not.
- Local OB1 gets AM tag "cancel results" and finds out whether the cancel succeeded or not

**Comment by bosilca** [comment]
The MPI forum will deprecate the cancel of sends. There is no need for this functionality.
