### ISSUE TITLE
v3.1.2 release is actually v3.1.2rc2 ?

### ISSUE THREAD

**Issue by amckinstry** [open-mpi/ompi#5604]
The current release of ompi 3.1.x (https://github.com/open-mpi/ompi/commit/5a14e33d7761f8a1eb2d7f629c26062952aa7ef5) is named 'v3.1.2.tar.gz', but is v.3.1.2rc2 inside.

**Comment by amckinstry** [comment]
Ok, digging further ...

https://github.com/open-mpi/ompi/releases gives "3.1.2" but actually points to 3.1.2rc2.

The email https://www.mail-archive.com/announce@lists.open-mpi.org/msg00114.html
refers to the v2.1 directory. Changing "v2.1" to "v3.1"  gets you to the correct v.3.1.2 tarballs

**Comment by jsquyres** [comment]
Yes, in git (5a14e33d7761f8a1eb2d7f629c26062952aa7ef5), the value in `VERSION` is 3.1.2rc2.  Per our release process, this is actually expected.

The released tarballs on https://www.open-mpi.org/software/ompi/v3.1/ are not just a straight tar of the git sources -- we do post-process the git sources to make a final tarball (run the autotools, run flex, the final tweak to `VERSION`, ...etc.).  I.e., the output of `make dist` != `git clone ...`.

I just double-checked the tarballs on open-mpi.org and they *do* contain the correct VERSION values (i.e., no `rc` tags).  Whew!

To be clear: we've never actually distributed Open MPI tarballs through github -- the only official releases are on open-mpi.org (which nowadays pipe through download.open-mpi.org which is an AWS cloudfront yadda yadda yadda).

The NEWS item you're referring to is *almost* identical to the 2.1.5 NEWS item -- but:

1. it was important enough to mention in the v3.1.2 NEWS
1. it's just *slightly* different:
    1. The v2.1.5 NEWS cross-references the v3.0.1 and v3.1.2 releases
    1. The v3.1.2 NEWS cross-references the v2.1.5 and v3.0.1 releases

**Comment by jsquyres** [comment]
Oh crud; right after I submitted that comment, I see the *link* you're referring to in https://www.mail-archive.com/announce@lists.open-mpi.org/msg00114.html -- it points to the v2.1 page.

I'll see if I can get that fixed.

**Comment by amckinstry** [comment]
Ok. I get the rationale but the git tarball == git clone and not dist tarball is confusing and could lead to errors. Best to put some distinction in the name. I'll ensure to grab the open-mpi.org version from here (its got the SHA sums, too).

**Comment by jsquyres** [comment]
Ok.  I updated the last bunch of releases on https://github.com/open-mpi/ompi/releases to have a message saying "don't download these / get the real releases from www.open-mpi.org".

**Comment by jsquyres** [comment]
I'm assuming this is now resolved -- I'm closing.  Feel free to ping further if you have more information / questions / etc.

**Comment by jsquyres** [comment]
Update: mail-archive does not want to edit the message for us (which is kinda understandable, actually).  So we're stuck with the incorrect link in https://www.mail-archive.com/announce@lists.open-mpi.org/msg00114.html.
