### ISSUE TITLE
How to increase the max number of communicators for shared windows to ulimited?

### ISSUE THREAD

**Issue by pflee2002** [open-mpi/ompi#5645]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
OpenMPI 2.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
from the source downloaded from openmpi website

### Please describe the system on which you are running
Ubuntu 18.0
* Operating system/version: 
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem
I am using MPI_Win_allocate_shared to allocate memories. I can't creating more windows then about the hard limit of communicators. How can I improve the max number of communicators  to unlimited? 

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.
I
**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -np 2 ./hello_world
```

**Comment by ggouaillardet** [comment]
You are likely hitting the limit that is set by the `pml` component.

`pml/ob1` you are likely using internally stores contextid on `16` bits, and hence a `65535` limit on the number of communicators.
you might want to investigate `pml/ucx` that stores contextid on `20` bits.
`pml/yalla` might have a higher limit and that could be an option depending on the hardware you are using.

All that being said, you should more likely rethink your application so it does not require a huge number of windows.

**Comment by jsquyres** [comment]
👍 on what @ggouaillardet said: if you need that many windows, you might want to re-think your architecture.  Yes, it may be *convenient* to allocate that many windows, but it almost certainly won't be *efficient*.

Additionally: one point Gilles left out: in Open MPI, windows are backed by communicators behind the scenes because they share some of the back-end infrastructure.  That's why you can't create more windows than you can communicators.

**Comment by pflee2002** [comment]
Thanks. I will change my architecture.

**Comment by jsquyres** [comment]
Cool.  Good luck.
