### ISSUE TITLE
Infinite recursion in libnbc/libdict

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#5670]
Clang compiling Open MPI master head on MacOS shows that this function is an infinite recursion:

https://github.com/open-mpi/ompi/blob/b83ad04e4ec504ae7ab1c1e3ad318970634b4257/ompi/mca/coll/libnbc/libdict/hb_tree.c#L173-L177

It doesn't look like this code path is referenced in a few places, but is never actually used.

@bosilca Is this safe to delete?

**Comment by bosilca** [comment]
dict_search, the only function that could use hb_tree_csearch, is never called. I guess it is then safe to leave this in and maybe call abort inside.

**Comment by jsquyres** [comment]
Do we need to report this upstream to someone?

Sent from my phone. No type good.

On Sep 11, 2018, at 10:07 PM, bosilca <notifications@github.com<mailto:notifications@github.com>> wrote:


dict_search, the only function that could use hb_tree_csearch, is never called. I guess it is then safe to leave this in and maybe call abort inside.

**Comment by bosilca** [comment]
libnbc is still supported ? We never really pushed upstream all updates to it, so by now our version is heavily altered.

**Comment by jsquyres** [comment]
Gotcha.
