### ISSUE TITLE
undefined symbol: psmx_eq_open in libmca_common_libfabric

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#569]
When configuring ompi with default --enable-dlopen one now gets warnings about an undefined symbol (psmx_eq_open) at job launch, 
e.g.

[mu1567.localdomain:16525] mca_base_component_repository_open: unable to open mca_mtl_ofi: /users/hpp/ompi_install/lib/libmca_common_libfabric.so.0: undefined symbol: psmx_eq_open (ignored)

**Comment by jsquyres** [comment]
@yburette Can you have a look?

**Comment by yburette** [comment]
Is this with the embedded libfabric?

**Comment by j-xiong** [comment]
sound like an older version of libfabric is dlopened.

**Comment by hppritcha** [comment]
yes, I think its just by chance that psmx_eq_open is showing up.  Its
probably a generic thing about the way the ompi is building libfabric
embedded and that libfabric by default doesn't export internal symbols.
Seems to confuse the ompi mca framework.  Don't understand why yet.


2015-05-04 12:17 GMT-06:00 Yohann Burette <notifications@github.com>:

**Comment by hppritcha** [comment]
Never mind think I found the problem in the top level Makefile.am in the embedded libfabric. checking

**Comment by hppritcha** [comment]
the psmx_eq.c was missing from the source file listing for the psm provider in the "embedding" makefile.
so its an ompi mca problem not really a psm provider problem.

**Comment by yburette** [comment]
Strange... I thought we had fixed that problem before.
@jsquyres: could there be a problem in the way the embedded libfabric gets updated?

**Comment by jsquyres** [comment]
If that was a mistake in the top-level Makefile.am, that should be outside the embedded copy of libfabric (and therefore not subject to change when the embedded libfabric is updated).

Perhaps we/I just goofed in there at some point and erased a fix to that Makefile.am.  :(


> On May 4, 2015, at 4:36 PM, Yohann Burette <notifications@github.com> wrote:
> 
> Strange... I thought we had fixed that problem before.
> @jsquyres: could there be a problem in the way the embedded libfabric gets updated?
> 
> —
> Reply to this email directly or view it on GitHub.
> 


-- 
Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by hppritcha** [comment]
I'm putting together a fix

2015-05-04 14:43 GMT-06:00 Jeff Squyres <notifications@github.com>:
