### ISSUE TITLE
bml/r2: closing already closed BTL in some cases.

### ISSUE THREAD

**Issue by thananon** [open-mpi/ompi#5739]
mca_bml_r2_del_procs() will do a double free if the BTL is presented on both `btl_send` and `btl_rdma` list, resulted in segfault in MPI_Finalize. (see both for loop at 620 and 637)

https://github.com/open-mpi/ompi/blob/dccf780546e9cb49066bd76121b01293aa6d4b97/ompi/mca/bml/r2/bml_r2.c#L605-L656

btl/uct and btl/ofi did a workaround on this issue by using hash table on del_proc. However, this will still be a problem for other BTL with both send and rdma capabilities. I just reproduced this on btl/openib. Should we fix this from r2 or the BTL has to implement their own workaround?

I can reproduce this on 4.0.0rc1.

**Comment by jsquyres** [comment]
(github pro tip: use permalinks to paste in code from a github repo)

I would say that this should be fixed in r2.

**Comment by hppritcha** [comment]
Did code check on openib, ugni, uct, and ofi btls and their methods appear to protect from this double free situation.  Closing.
