### ISSUE TITLE
make install not right but won't fail without gawk

### ISSUE THREAD

**Issue by seisowl** [open-mpi/ompi#5760]
Thank you for taking the time to submit an issue!

## Background information
make install is not successful without gawk
should fail if gawk is not available.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
commit 3f598e9e8334128897e9fe6d71891b6a5101a0c7 (HEAD -> master, origin/master, origin/HEAD)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
git clone from master

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04

**Comment by jsquyres** [comment]
Can you provide more specific information?  Your background information section is confusing -- you say that make install fails without gawk, and it should fail if gawk is not available.  So I'm not clear on exactly what you're asking for.

Additionally, what exactly is failing, and how?

Please upload:
* stdout/stderr from running configure
* the `config.log` file
* output from `make install`

Thanks.

**Comment by seisowl** [comment]
OK, "make install" appeared as successful but the target bin directory had no useful binaries except many symbolic links pointing to non-exsisting ones.  Scroll back to the output of "make install" i saw two lines (maybe more) complaining "gawk" is missing but the process continued.
After I installed gawk, everything is OK.
I cannot go back to give you the old output because I am already using the system. Hope the above make the issue clear.

**Comment by jsquyres** [comment]
It's a little hard to test this on a system that already has `gawk`.  We probably never ran into this problem because I'm a little surprised that you can have a linux machine without `awk` or `gawk` installed.

Can you just run `configure` again (perhaps into a bogus prefix so that you don't overwrite your current/working Open MPI) on a system without `gawk`, save the output, and then make/make install, also saving the output?

**Comment by seisowl** [comment]
I am on Ubuntu 18.04 (i.e. 2018/04 release), by default awk and nawk are installed as expected but gawk is a separate package that I need to "apt install gawk".

Attached are configure.log, make.log, make_install.log (They are stderr/stdout, I did not attach the 6.8MB config.log generated by the system).
[configure.log](https://github.com/open-mpi/ompi/files/2413716/configure.log)
I do see:
configure.log
41:checking for gawk... no
1425:checking for gawk... no
1889:checking for gawk... no
3475:checking for gawk... no

This time everything was fine on a machine without gawk. 
I do suspect that I did the "./configure" and "make -j" on a faster machine (which had gawk), while that disk was a shared nfs, I did "make install" on the other machine which did not have gawk.

**Comment by rhc54** [comment]
Makes sense - thanks for clarifying!

**Comment by jsquyres** [comment]
Ah, that would definitely be a problem -- our build process does assume that if `configure`, `make all`, and `make install` are not run on the same machine, they are running on a functionally identical machine.  I.e., if it found `gawk` on one machine, it will expect to find `gawk` on another machine.

And by "our build process", I mean "the GNU Auto tools" (automake, autoconf, libtool).

As @rhc54 said -- thanks for clarifying!
