### ISSUE TITLE
Is OpenMPI supporting RDMA?

### ISSUE THREAD

**Issue by ghostplant** [open-mpi/ompi#5789]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
openmpi-bin=1.10 (installed from Ubuntu 16.04 universe repository)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

We have some metals equipped with MELLANOX OFED ConnectX-5 Ethernet Cards supporting RDMA data transfer. When using OpenMPI to launch applications, is it automatically take advantage of RDMA channel, or how to configure `mpiexec` to enable it?

### Please describe the system on which you are running

* Operating system/version:  Ubuntu 16.04 x86-64
* Computer hardware: C4140
* Network type: Mellanox MT28800 ConnectX-5

-----------------------------

**Comment by ghostplant** [comment]
@jsquyres
Thank you! I just saw a not-fast send/recv performance, and I don't know how to verify the running OpenMPI really detect ConnectX-5 RDMA successfully without using other slower communication channel. Is there a way to confirm the RDMA offloading?

**Comment by jsquyres** [comment]
I'll direct you to Mellanox to help you with that...

@jladd-mlnx @artpol84 Can one of you followup with @ghostplant?

**Comment by ghostplant** [comment]
@jedbrown Great! I'll arrange some detailed logs during the application execution just a short later!

**Comment by ghostplant** [comment]
There are 3 same-hardware metals with hostname node-130, node-131, node-132 respectively.
And this is how I run the mpi test problem under Ubuntu 16.04 (I already update openmpi-bin to v3.1.2):

I got some warning at the beginning of the running program, but the program can still run normally including MPI_Send/MPI_Recv/..

```sh
node-130# mpirun --allow-run-as-root --bind-to none --mca oob_tcp_if_include enp216s0 \
          --mca btl_tcp_if_include enp216s0 -x NCCL_SOCKET_IFNAME=enp216s0 --map-by slot \
          -np 3 --host node-130,node-131,node-132 /opt/mpi-test-example.bin

vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed                                                                                                                   [71/1851]
--------------------------------------------------------------------------
No OpenFabrics connection schemes reported that they were able to be
used on a specific port.  As such, the openib BTL (OpenFabrics
support) will be disabled for this port.

  Local host:           node-130
  Local device:         mlx5_0
  Local port:           1
  CPCs attempted:       udcm
--------------------------------------------------------------------------
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
[node-130:00035] 2 more processes have sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
[node-130:00035] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

(following outputs are from MPI program after MPI_Init() is invoked, and everything after is fine and success)
```

More INFO:
1) the interface `enp216s0` is the only one interface that support RDMA, and all 3 nodes are of the same hardware;
2) The MLNX_OFED driver is installed as well;

```sh
node-130/node-131/node-132# lspci | grep mell -i
d8:00.0 Ethernet controller: Mellanox Technologies MT28800 Family [ConnectX-5]

node-130/node-131/node-132# ip route
default via 10.244.48.1 dev eno3 onlink
10.244.48.0/24 dev eno3  proto kernel  scope link  src 10.244.48.130
192.168.2.0/24 dev enp216s0  proto kernel  scope link  src 192.168.2.130

node-130/node-131/node-132# dpkg -l | grep mlnx-ofed-kernel-dkms
ii  mlnx-ofed-kernel-dkms                           4.2-OFED.4.2.1.0.0.1.gf36c870              all          DKMS support for mlnx-ofed kernel modules
```

**Comment by ghostplant** [comment]
If I run all the same test using openmpi-bin v1.10 (from Ubuntu 16.04 apt repo), I got a different warning at the startup of MPI program:

```sh
--------------------------------------------------------------------------
WARNING: No preset parameters were found for the device that Open MPI
detected:

  Local host:            node-131
  Device name:           mlx5_0
  Device vendor ID:      0x02c9
  Device vendor part ID: 4119

Default device parameters will be used, which may result in lower
performance.  You can edit any of the files specified by the
btl_openib_device_param_files MCA parameter to set values for your
device.

NOTE: You can turn off this warning by setting the MCA parameter
      btl_openib_warn_no_device_params_found to 0.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
No OpenFabrics connection schemes reported that they were able to be
used on a specific port.  As such, the openib BTL (OpenFabrics
support) will be disabled for this port.

  Local host:           node-131
  Local device:         mlx5_0
  Local port:           1
  CPCs attempted:       udcm
--------------------------------------------------------------------------
```

**Comment by abeltre1** [comment]
@ghostplant did you try installing a later version of openmpi like @jsquyres suggested. That may have a lot of benefits when running MPI over InfiniBand (IB).

**Comment by ghostplant** [comment]
@abeltre1 Yeal, I tried both v3.1.2 and v1.10.2, but all got the following warning when calling `MPI_Init(0,0)`:

```sh
--------------------------------------------------------------------------
No OpenFabrics connection schemes reported that they were able to be
used on a specific port.  As such, the openib BTL (OpenFabrics
support) will be disabled for this port.

  Local host:           node-130
  Local device:         mlx5_0
  Local port:           1
  CPCs attempted:       rdmacm, udcm
--------------------------------------------------------------------------
```

**Comment by artpol84** [comment]
@ghostplant 
Assuming you are trying to run with IB device (please let me know if this is a wrong assumption).

Given that you were working with v3.1.x and opnib BTL was highly likely to be selected for your runs. I think you can verify that by setting `-mca btl_base_verbose` and checking for the verbose output).

Current Mellanox recommendation is to use UCX pml component. In order to do that you will need:
* Install UCX from https://github.com/openucx/ucx
* Configure Open MPI "--with-ucx="path-to-UCX""
* Launch your application with `mpirun -mca pml ucx -mca-btl self -x UCX_NET_DEVICES="your-mlx-device" -x UCX_TLS="your-TLS" <other-options>
For TLS selection refer [here](https://github.com/openucx/ucx/wiki/UCX-environment-parameters). Essentially for IB it selects the transport. You should consider RC or DC transports to try (so rc, rc_x, dc dc_x). I haven't found DC transports in the descriptions by the link but they are available in recent UCX versions.

Hope this helps, please let me know how it goes.

**Comment by abeltre1** [comment]
> ed that they were able to be used on a specific port. As such, the openib BTL (OpenFabrics support) will be disabled for this port. Local host: node-130 Local device: mlx5_0 Local port: 1

@ghostplant  Please run the following commands and share your output: 

1. sudo /etc/init.d/openibd restart
![image](https://user-images.githubusercontent.com/11620908/46981571-ef230b80-d0a6-11e8-9b97-f463b3759b0b.png)

2. sudo mst status 

![image](https://user-images.githubusercontent.com/11620908/46981527-c0a53080-d0a6-11e8-9c94-6d4eb1673e30.png)

**Comment by abeltre1** [comment]
> Thanks. Seems that mst is not loaded, is it important?
> 
> ```shell
> root@node-130:~#  /etc/init.d/openibd status
> 
>   HCA driver loaded
> 
> Configured Mellanox EN devices:
> enp216s0
> 
> Currently active Mellanox devices:
> enp216s0
> 
> The following OFED modules are loaded:
> 
>   rdma_ucm
>   rdma_cm
>   ib_ipoib
>   mlx4_core
>   mlx4_ib
>   mlx4_en
>   mlx5_core
>   mlx5_ib
>   ib_uverbs
>   ib_umad
>   ib_ucm
>   ib_cm
>   ib_core
>   mlxfw
>   mlx5_fpga_tools
> 
> root@node-130:~# mst status
> MST modules:
> ------------
>     MST PCI module is not loaded
>     MST PCI configuration module is not loaded
> 
> PCI Devices:
> ------------
> 
> d8:00.0
> ```


It is not required. I wanted to see if you had any special package installed.

**Comment by ghostplant** [comment]
@abeltre1 OK. So I passes `--mca oob_tcp_if_include enp216s0 --mca btl_tcp_if_include enp216s0` to mpiexec command, and is it enough to enable the best performance of Connect-X5?

**Comment by artpol84** [comment]
@ghostplant
Thing that caught my eye.
* `oob_tcp_if_include` is a tcp OOB (out-of-Band) option
* `btl_tcp_if_include` is a tcp BTL option
None of them affect openib BTL, for openib BTL you have to use oob_openib_if_include IIRC or something similar.

**Comment by artpol84** [comment]
The device name you have is `mlx5_0` if you want to go through IB interface.

**Comment by artpol84** [comment]
It looks like you are using an Ethernet HCA and if you want to use it with RDMA you need a RoCE.
see https://www.open-mpi.org/faq/?category=openfabrics#ompi-over-roce

**Comment by abeltre1** [comment]
> The device name you have is `mlx5_0` if you want to go through IB interface.

@ghostplant  instead of using `enp216s0` use the actual device which was suggested by @artpol84.

**Comment by ghostplant** [comment]
@abeltre1 @artpol84 Thanks, and yes, the network interface is RoCE not InfiniBand, and the device name is mlx5_0.

But according to commands from ompi-over-roce documentation, I hardly found any options work in my environment, such as `--mca btl_openib_cpc_include rdmacm` for which mpiexec reports rdmacm is not supported and only udcm is supported, so do many other options for RoCE.

So still the only option I found work is still `--mca oob_tcp_if_include enp216s0 --mca btl_tcp_if_include enp216s0` but as you said it doesn't enable RDMA over ethernet for mlx5_0.

So can you give me the correct option that I can enable the RDMA for this netcard? The RoCE doc just didn‘t help...

**Comment by ghostplant** [comment]
@artpol84 Thank you. Do you know which `--mca xxx` should I append to the argument? As far as my tried, only `xxx_tcp_if_include enp216s0` works in my Connect-X5 environment.. Others `--mca` devices will either report `not found` or hang on `MPI_init()`

**Comment by artpol84** [comment]
To use UCX you need to
1. Get the recent release from https://github.com/openucx/ucx/releases
1. Build and make it avaliable to your machines
1. Configure OMPI "--with-ucx="path-to-ucx" and rebuild/reinstall it

Afterwards when you launch you set UCX pml:
`$ mpirun -mca btl self -mca pml ucx ....`

To control which device and what transport are being used you can add following env variables:
`$ mpirun -mca btl self -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_TLS=rc,shm ....`
Try to experiment with different TLS's see [here](https://github.com/openucx/ucx/wiki/UCX-environment-parameters) for more info.

**Comment by ghostplant** [comment]
Wow, thank you. I'll try that.

**Comment by ghostplant** [comment]
@artpol84 Hi, I installed ucx and new ompi, and got the following error when running the program:
```sh
LD_LIBRARY_PATH=/usr/local/lib mpiexec -H 192.168.2.130:2 -mca btl self -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:0 -x UCX_TLS=rc,shm     -x NCCL_SOCKET_IFNAME=enp216s0     --allow-run-as-root --bind-to none -x NCCL_DEBUG=INFO ./all-reduce.py
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 1 slots
that were requested by the application:
  ./all-reduce.py

Either request fewer slots for your application, or make more slots available
for use.
```

Any solution?

**Comment by abeltre1** [comment]
> @artpol84 Hi, I installed ucx and new ompi, and got the following error when running the program:
> 
> ```shell
> LD_LIBRARY_PATH=/usr/local/lib mpiexec -H 192.168.2.130:2 -mca btl self -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_TLS=rc,shm     -x NCCL_SOCKET_IFNAME=enp216s0     --allow-run-as-root --bind-to none -x NCCL_DEBUG=INFO ./all-reduce.py
> --------------------------------------------------------------------------
> There are not enough slots available in the system to satisfy the 1 slots
> that were requested by the application:
>   ./all-reduce.py
> 
> Either request fewer slots for your application, or make more slots available
> for use.
> ```
> 
> Any solution?

try creating a hostfile with only the IP address (i.e., 192.168.2.130)

**Comment by ghostplant** [comment]
OK, I created the hostfile, but the mpirun just hangs on booting the program:

```sh
LD_LIBRARY_PATH=/usr/local/lib mpiexec -np 2 --hostfile ./hostfile -mca btl self -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_TLS=rc,shm     -x NCCL_SOCKET_IFNAME=enp216s0   -x LD_LIBRARY_PATH=/usr/local/lib  --allow-run-as-root --bind-to none -x NCCL_DEBUG=INFO ./all-reduce.py
```

It connects to localhost only with np = 2, and all possible OpenSSH rsa_keys are configured correctly.

**Comment by jsquyres** [comment]
Where did your job hang?  Did you `all-reduce.py` application launch?

**Comment by ghostplant** [comment]
@jsquyres It hangs at the beginning of mpiexec, no any output displays. Is there a way to show runtime debugging logs for mpiexec?

**Comment by jsquyres** [comment]
I assume you're still using Open MPI 3.1.2?

I'm a little concerned about setting your `LD_LIBRARY_PATH` solely to `/usr/local/lib` -- don't you need to *prefix* your `LD_LIBRARY_PATH` with `/usr/local/lib`?

Also, there should be no functional difference between `-H 192.168.2.130:2` and `--hostfile ./hostfile` (with `cat hostfile` == `192.168.2.130 slots=2`).

```
$ LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH \
    mpiexec -np 2 \
    --hostfile ./hostfile \
    -mca btl self \
    -mca pml ucx \
    -x UCX_NET_DEVICES=mlx5_0:1 \
    -x UCX_TLS=rc,shm\
    -x NCCL_SOCKET_IFNAME=enp216s0 \
    -x LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH \
    --allow-run-as-root \
    --bind-to none \
    -x NCCL_DEBUG=INFO \
    ./all-reduce.py
```

Note that if you're launching solely on the local node, you don't need the additional `-x LD_LIBRARY_PATH` because all children processes will inherit the `LD_LIBRARY_PATH` you set on the beginning of the command line.

Also note that if you're using the UCX PML, the `--mca btl self` setting is ignored (the UCX PML doesn't use the BTL modules).

I'm not sure why you've got `--bind-to none` in there -- is Open MPI's CPU affinity causing a problem?

While debugging this launch issue, you should probably launch a non-Python code.  I.e., try to launch the standard Linux command `hostname` to make sure it is launching properly.  This verifies basic launcher functionality.  If that works, then launch the `hello_c` from the `examples` directory in the Open MPI distribution.  This verifies basic MPI startup functionality.  If that works, then launch the `ring_c` from `examples.  This verifies basic MPI message passing.  Once all of those work, then try your Python code again.

Try adding `--debug-daemons` and/or `--display-devel-map` to your run.   You can also add `--mca rmaps_base_verbose 100`, `--mca plm_base_verbose 100`, and/or `--mca odls_base_verbose 100`.

**Comment by jsquyres** [comment]
Are you running in a scheduler/resource manager job (e.g., SLURM or Torque or the like), perchance?

Can you run with all the `--debug..`, `--display..`, and `--mca ...` params I sent above and send the output?

**Comment by ghostplant** [comment]
```sh
root@node-131:/fatbin# LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH     mpiexec --host 192.168.2.131  --hostfile ./hostfile    -mca pml ucx     -x UCX_NET_DEVICES=mlx5_0:1     -x UCX_TLS=rc,shm  --allow-run-as-root --display-devel-map --debug-daemons    ./test 
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 1
slots that were requested by the application:

  ./test

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
--------------------------------------------------------------------------
[node-131:128012] [[5609,0],0] orted_cmd: received halt_vm cmd
[node-131:128012] [[5609,0],0] orted_cmd: all routes and children gone - exiting
```

**Comment by jsquyres** [comment]
1. Are you running under a scheduler/resource manager?
1. Can you also add `--mca rmaps_base_verbose 100`, `--mca plm_base_verbose 100`, and/or `--mca odls_base_verbose 100`, too?

**Comment by ghostplant** [comment]
No any manager, just a fresh Ubuntu 16.04 server, and I don't get this error if I use legacy version like OpenMPI-1.10.

```sh
root@node-131:/fatbin# LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH     mpiexec --host 192.168.2.131  --hostfile ./hostfile    -mca pml ucx     -x UCX_NET
_DEVICES=mlx5_0:1     -x UCX_TLS=rc,shm  --allow-run-as-root --display-devel-map --debug-daemons --mca rmaps_base_verbose 100 --mca plm_base_verbose 100 --mc
a odls_base_verbose 100   ./test
[node-131:133235] mca: base: components_register: registering framework plm components
[node-131:133235] mca: base: components_register: found loaded component slurm
[node-131:133235] mca: base: components_register: component slurm register function successful
[node-131:133235] mca: base: components_register: found loaded component rsh
[node-131:133235] mca: base: components_register: component rsh register function successful
[node-131:133235] mca: base: components_register: found loaded component isolated
[node-131:133235] mca: base: components_register: component isolated has no register or open function
[node-131:133235] mca: base: components_open: opening plm components
[node-131:133235] mca: base: components_open: found loaded component slurm
[node-131:133235] mca: base: components_open: component slurm open function successful
[node-131:133235] mca: base: components_open: found loaded component rsh
[node-131:133235] mca: base: components_open: component rsh open function successful
[node-131:133235] mca: base: components_open: found loaded component isolated
[node-131:133235] mca: base: components_open: component isolated open function successful
[node-131:133235] mca:base:select: Auto-selecting plm components
[node-131:133235] mca:base:select:(  plm) Querying component [slurm]
[node-131:133235] mca:base:select:(  plm) Querying component [rsh]
[node-131:133235] mca:base:select:(  plm) Query of component [rsh] set priority to 10
[node-131:133235] mca:base:select:(  plm) Querying component [isolated]
[node-131:133235] mca:base:select:(  plm) Query of component [isolated] set priority to 0
[node-131:133235] mca:base:select:(  plm) Selected component [rsh]
[node-131:133235] mca: base: close: component slurm closed
[node-131:133235] mca: base: close: unloading component slurm
[node-131:133235] mca: base: close: component isolated closed
[node-131:133235] mca: base: close: unloading component isolated
[node-131:133235] mca: base: components_register: registering framework rmaps components
[node-131:133235] mca: base: components_register: found loaded component round_robin
[node-131:133235] mca: base: components_register: component round_robin register function successful
[node-131:133235] mca: base: components_register: found loaded component mindist
[node-131:133235] mca: base: components_register: component mindist register function successful
[node-131:133235] mca: base: components_register: found loaded component ppr
[node-131:133235] mca: base: components_register: component ppr register function successful
[node-131:133235] mca: base: components_register: found loaded component resilient
[node-131:133235] mca: base: components_register: component resilient register function successful
[node-131:133235] mca: base: components_register: found loaded component seq
[node-131:133235] mca: base: components_register: component seq register function successful
[node-131:133235] mca: base: components_register: found loaded component rank_file
[node-131:133235] mca: base: components_register: component rank_file register function successful
[node-131:133235] [[59797,0],0] rmaps:base set policy with NULL device NONNULL
[node-131:133235] mca: base: components_open: opening rmaps components
[node-131:133235] mca: base: components_open: found loaded component round_robin
[node-131:133235] mca: base: components_open: component round_robin open function successful
[node-131:133235] mca: base: components_open: found loaded component mindist
[node-131:133235] mca: base: components_open: component mindist open function successful
[node-131:133235] mca: base: components_open: found loaded component ppr
[node-131:133235] mca: base: components_open: component ppr open function successful
[node-131:133235] mca: base: components_open: found loaded component resilient
[node-131:133235] mca: base: components_open: component resilient open function successful
[node-131:133235] mca: base: components_open: found loaded component seq
[node-131:133235] mca: base: components_open: component seq open function successful
[node-131:133235] mca: base: components_open: found loaded component rank_file
[node-131:133235] mca: base: components_open: component rank_file open function successful
[node-131:133235] mca:rmaps:select: checking available component round_robin
[node-131:133235] mca:rmaps:select: Querying component [round_robin]
[node-131:133235] mca:rmaps:select: checking available component mindist
[node-131:133235] mca:rmaps:select: Querying component [mindist]
[node-131:133235] mca:rmaps:select: checking available component ppr
[node-131:133235] mca:rmaps:select: Querying component [ppr]
[node-131:133235] mca:rmaps:select: checking available component resilient
[node-131:133235] mca:rmaps:select: Querying component [resilient]
[node-131:133235] mca:rmaps:select: checking available component seq
[node-131:133235] mca:rmaps:select: Querying component [seq]
[node-131:133235] mca:rmaps:select: checking available component rank_file
[node-131:133235] mca:rmaps:select: Querying component [rank_file]
[node-131:133235] [[59797,0],0]: Final mapper priorities
[node-131:133235]       Mapper: ppr Priority: 90
[node-131:133235]       Mapper: seq Priority: 60
[node-131:133235]       Mapper: resilient Priority: 40
[node-131:133235]       Mapper: mindist Priority: 20
[node-131:133235]       Mapper: round_robin Priority: 10
[node-131:133235]       Mapper: rank_file Priority: 0
[node-131:133235] mca: base: components_register: registering framework odls components
[node-131:133235] mca: base: components_register: found loaded component pspawn
[node-131:133235] mca: base: components_register: component pspawn has no register or open function
[node-131:133235] mca: base: components_register: found loaded component default
[node-131:133235] mca: base: components_register: component default has no register or open function
[node-131:133235] mca: base: components_open: opening odls components
[node-131:133235] mca: base: components_open: found loaded component pspawn
[node-131:133235] mca: base: components_open: component pspawn open function successful
[node-131:133235] mca: base: components_open: found loaded component default
[node-131:133235] mca: base: components_open: component default open function successful
[node-131:133235] mca:base:select: Auto-selecting odls components
[node-131:133235] mca:base:select:( odls) Querying component [pspawn]
[node-131:133235] mca:base:select:( odls) Query of component [pspawn] set priority to 1
[node-131:133235] mca:base:select:( odls) Querying component [default]
[node-131:133235] mca:base:select:( odls) Query of component [default] set priority to 10
[node-131:133235] mca:base:select:( odls) Selected component [default]
[node-131:133235] mca: base: close: component pspawn closed
[node-131:133235] mca: base: close: unloading component pspawn
[node-131:133235] mca:rmaps: mapping job [59797,1]
[node-131:133235] AVAILABLE NODES FOR MAPPING:
[node-131:133235]     node: node-131 daemon: 0
[node-131:133235] mca:rmaps: setting mapping policies for job [59797,1] nprocs 0
[node-131:133235] mca:rmaps[158] mapping not given - using bycore
[node-131:133235] mca:rmaps[304] binding not given - using bycore
[node-131:133235] mca:rmaps:ppr: job [59797,1] not using ppr mapper PPR NULL policy PPR NOTSET
[node-131:133235] mca:rmaps:seq: job [59797,1] not using seq mapper
[node-131:133235] mca:rmaps:resilient: cannot perform initial map of job [59797,1] - no fault groups
[node-131:133235] mca:rmaps:mindist: job [59797,1] not using mindist mapper
[node-131:133235] mca:rmaps:rr: mapping job [59797,1]
[node-131:133235] AVAILABLE NODES FOR MAPPING:
[node-131:133235]     node: node-131 daemon: 0
[node-131:133235] mca:rmaps:rr: mapping no-span by Core for job [59797,1] slots 0 num_procs 1
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 1
slots that were requested by the application:

  ./test

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
--------------------------------------------------------------------------
[node-131:133235] [[59797,0],0] orted_cmd: received halt_vm cmd
[node-131:133235] [[59797,0],0] orted_cmd: all routes and children gone - exiting
[node-131:133235] mca: base: close: component default closed
[node-131:133235] mca: base: close: unloading component default
[node-131:133235] mca: base: close: component round_robin closed
[node-131:133235] mca: base: close: unloading component round_robin
[node-131:133235] mca: base: close: component mindist closed
[node-131:133235] mca: base: close: unloading component mindist
[node-131:133235] mca: base: close: component ppr closed
[node-131:133235] mca: base: close: unloading component ppr
[node-131:133235] mca: base: close: component resilient closed
[node-131:133235] mca: base: close: unloading component resilient
[node-131:133235] mca: base: close: component seq closed
[node-131:133235] mca: base: close: unloading component seq
[node-131:133235] mca: base: close: component rank_file closed
[node-131:133235] mca: base: close: unloading component rank_file
[node-131:133235] mca: base: close: component rsh closed
[node-131:133235] mca: base: close: unloading component rsh

```

**Comment by jsquyres** [comment]
This issue has been idle for 3 weeks; I'm going to close it.  Let us know if you still want to investigate / we should re-open the issue.  Thanks!
