### ISSUE TITLE
conftest doesn't link against lmxm

### ISSUE THREAD

**Issue by robertsawko** [open-mpi/ompi#5813]
Hi,

We're spending some time building a conda openmpi package for RHEL ppc64le. conda appears to be very fussy about broken tests in the configure stage so we spotted a problem thanks to it.

We are using the latest 3.1.2 version but the problem was also present in earlier versions. We are using a configure script invocation which looks like this.

```bash
../openmpi-${VERSION}/configure \
    --prefix=${INSTALL_DIR} \
    --enable-mpi-thread-multiple --enable-shared --disable-static \
    --enable-mpi-fortran=usempi --disable-libompitrace \
    --enable-wrapper-rpath \
    --enable-mpi-fortran=yes \
    --with-lsf=${LSF_LIBDIR%%linux*} \
    --with-lsf-libdir=$LSF_LIBDIR \
    --with-knem=${KNEM_DIR} \
    --with-mxm=/opt/mellanox/mxm \
    --with-cuda=/usr/local/cuda \
    && make -j20 && make install
```

Basically the code breaks on the line testing for `mxm_cleanup`. We've made a change which looks like this:

```
--- configure	2018-08-22 16:00:52.000000000 +0100
+++ configure_v2	2018-10-01 15:06:47.057122735 +0100
@@ -301893,9 +301893,10 @@
 for ac_lib in '' mxm; do
   if test -z "$ac_lib"; then
     ac_res="none required"
+    LIBS="-lmxm"
   else
     ac_res=-l$ac_lib
-    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+    LIBS="-lmxm -l$ac_lib  $ac_func_search_save_LIBS"
   fi
   if ac_fn_c_try_link "$LINENO"; then :
   ac_cv_search_mxm_cleanup=$ac_res

```
And also the same in line 301827 and that appears to work. The problem is that even though libdir of mxm is picked up properly there's no `-lmxm` in the gcc invocation. We can patch the configure script but the problem must be higher up, probably in the configure.ac file.

Please advise.

**Comment by hoopoepg** [comment]
hi
try this patch:
```
[18:01:28;sergeyo@hpchead:bhome/sergeyo/ompi]$ git diff
diff --git a/config/ompi_check_mxm.m4 b/config/ompi_check_mxm.m4
index 8e5aa2b..2c01190 100644
--- a/config/ompi_check_mxm.m4
+++ b/config/ompi_check_mxm.m4
@@ -45,7 +45,7 @@ AC_DEFUN([OMPI_CHECK_MXM],[
                                  [mxm/api/mxm_api.h],
                                  [mxm],
                                  [mxm_cleanup],
-                                 [],
+                                 [-lmxm],
                                  [$ompi_check_mxm_dir],
                                  [$ompi_check_mxm_libdir],
                                  [ompi_check_mxm_happy="yes"],
```
not sure if this helps, but let's try :)

**Comment by hoopoepg** [comment]
but don't forget re-start autogen.pl to apply fix

**Comment by jsquyres** [comment]
@hoopoepg I do not think that that is the correct fix.  Need to see the user's `config.log` to see the actual errors when configure was trying to find the mxm libraries.

**Comment by robertsawko** [comment]
Many thanks both of you for quick responses. I should have sent the log before.

[config.log.tar.gz](https://github.com/open-mpi/ompi/files/2435199/config.log.tar.gz)

If I run this from the command line it runs fine as the test is propbably not critical(?), but when we build it inside conda the thing fails. We could suppress it, but we thought we'll bring this up in case it may be useful for future packaging.

**Comment by robertsawko** [comment]
I believe there's the same problem with `ucp_cleanup` and multiple other functions are missing. This manifests itself with `undefined reference` linker error in various places. With mxm though it was clear that gcc is using the right `-L` location but isn't simply including `-lmxm` in the test build.

**Comment by hoopoepg** [comment]
@robertsawko I can't extract it :(

**Comment by hoopoepg** [comment]
@robertsawko according config.log MXM was successfully detected on your system. OMPI uses iterative algorithm for detection required modules - it adds configuration arguments step-by-step till test application is failed to compile. How conda knows about failed tests? Maybe it is option to reduce error level for it?

**Comment by hoopoepg** [comment]
on line 129149 there is evaluation of MXM using -lmxm option, evaluation on line 128408 fails, but next one should detect MXM correctly

**Comment by yosefe** [comment]
@robertsawko is there MXM in LD_LIBRARY_PATH environment when running ./configure?

**Comment by robertsawko** [comment]
You're right. There isn't. I will add it it and take a look.

**Comment by robertsawko** [comment]
Sorry, I still wasn't able to test it as we seem to be having a longer cluster shutdown here at STFC.

Meanhwhile though I am back to my doubts on whether this is a real issue or not. I'd like to emphesize OMPI does build correctly with the above, but surely the gcc call I mentioned above must be a problem. It is pointing to the location where the library sits, doesn't actually link it, but ends up breaking because of the failed symbol. Would `$LD_LIBRARY_PATH` change anything here?

Also I can confirm that that if I modify a relevant line in `configure` this test works fine, but my fix isn't really good as the configure, as far as I understand, is generated through autoconf tools.

**Comment by jsquyres** [comment]
Just to clarify: what exactly is the problem that you are reporting?

The config.log shows that it found MXM properly.  

```
configure:303306: checking if MCA component mtl:mxm can compile
configure:303308: result: yes
```

If you look in `$prefix/lib/openmpi`, you should see the file `mca_mtl_mxm.so`, further confirming that Open MPI build and installed MXM support properly.

As @hoopoepg mentioned, Open MPI's configure uses an iterative method to look for libraries.  You will almost certainly see some failures in the configure output/log, and in your case, ultimately it figured out how to build against the MXM library.  Huzzah!  It seems to be working as designed.

If you are running Open MPI jobs and not seeing MXM levels of performance -- or even if you're running `ompi_info` and not seeing the `mxm` MTL listed (e.g., `ompi_info | grep mxm` shows nothing), it could well be because you don't have `LD_LIBRARY_PATH` set properly (to include the MXM libdir).  As such, when Open MPI tries to open a plugin that uses the MXM library, it can't find the dependent MXM library, and therefore fails to open that plugin.  That's not an error to Open MPI -- Open MPI just skips that plugin and moves on.

Try setting your `LD_LIBRARY_PATH` to include the libdir for MXM and run `ompi_info` and your Open MPI apps again, and see if that works for you.
