### ISSUE TITLE
btl/uct: hang in endpoint connection with multithreaded with IB.

### ISSUE THREAD

**Issue by thananon** [open-mpi/ompi#5820]
@hjelmn I worked in btl/uct and bumped into this problem where in the endpoint connect stage. If we have more than 1 context, it has this race condition where everyone is trying to create the endpoint. I understand that ugni does not have this problem as you can connect directly to the interface.

I printed out several steps below, the application is ping-ping with 2 threads on each side.

rank 0:
```
[a01.alembert:35166] got connection request for endpoint 0xa3c0e0. length = 28
[a01.alembert:35166] got connection request for endpoint 0xa3c0e0. length = 24
[a01.alembert:35166] ep 0xa3c0e0 is now ready...
[a01.alembert:35166] mca: bml: Using uct btl for send to [[36789,1],1] on node a02
[a01.alembert:35166] got connection request for endpoint 0xa3c0e0. length = 28
[a01.alembert:35166] got connection request for endpoint 0xa3c0e0. length = 28
[a01.alembert:35166] got connection request for endpoint 0xa3c0e0. length = 24
[a01.alembert:35166] ep 0xa3c0e0 is now ready...

[a01.alembert:35166] ep 0xa3c0e0 is not ready for frag 0xa7f600
```
In rank 0, we can see that the endpoint is marked as ready twice but failed to send. This might be a race condition. I understand that if the frag is not ready, it gets put into `pending_frags` list and will get marked ready once endpoint becomes available but the endpoint is already available. So we have a frag stuck in the list?

rank 1:
```
[a02.alembert:30092] got connection request for endpoint 0xa3b990. length = 28
[a02.alembert:30092] ep 0xa3b990 is not ready for frag 0xa731c0
[a02.alembert:30092] got connection request for endpoint 0xa3b990. length = 24
[a02.alembert:30092] ep 0xa3b990 is now ready...
[a02.alembert:30092] marking frag 0xa731c0 ready
[a02.alembert:30092] progress_pending: frag 0xa731c0 has become ready, sending...
[a02.alembert:30092] ep 0xa3b990 is not ready for frag 0xa731c0
[a02.alembert:30092] ep 0xa3b990 is not ready for frag 0xa73040
[a02.alembert:30092] got connection request for endpoint 0xa3b990. length = 28
[a02.alembert:30092] got connection request for endpoint 0xa3b990. length = 24
[a02.alembert:30092] ep 0xa3b990 is now ready...
[a02.alembert:30092] marking frag 0xa73040 ready
[a02.alembert:30092] progress_pending: frag 0xa73040 has become ready, sending...
[a02.alembert:30092] got connection request for endpoint 0xa3b990. length = 24
[a02.alembert:30092] got connection request for endpoint 0xa3b990. length = 28
```
In rank 1, it seems to be fine. The frag is marked ready and sent.

I create this issue as a tracker. I am currently working on debugging this but hope that you might be able to suggest me so I can look into the right direction.

**Comment by hjelmn** [comment]
Thanks for looking at this. I noticed this bug as well. Have been focusing on dc performance and will take a look at this shortly.
