### ISSUE TITLE
Commit broke TCP BTL when IPv6 is enabled

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#585]
Git bisect shows that a7b0c00 broke the TCP BTL when `--enable-ipv6` is used (this commit does not appear to be the problem; it seems to have exposed a latent bug elsewhere; see below).

Before this commit, I can `mpirun --mca btl tcp,sm,self --host a,b ring_c` and it works fine.  After this commit, I get this:

```sh
Process 0 sending 10 to 1, tag 201 (2 processes in ring)
[[11195,1],0][/home/jsquyres/git/ompi-bisect/opal/mca/btl/tcp/btl_tcp_endpoint.c:776:mca_
btl_tcp_endpoint_start_connect] from mpi026 to: mpi027 Unable to connect to the peer fe80
::2657:20ff:fe1b:5000 on port 4: Invalid argument

[mpi026:08760] /home/jsquyres/git/ompi-bisect/ompi/mca/pml/ob1/pml_ob1_sendreq.c:193 FATAL
```

This is on machines with 4 IP interfaces, none of which have IPv6 enabled in the OS (although they do have IPv6 link-local addresses -- the OS just puts them there, even if you disable IPv6 networking on that interface).

It looks like commit a7b0c00 did the Right thing: in `opal_init()`, it moved the setup of the OPAL "net" functionality to be below the setup of MCA vars.  Before the commit, the OPAL "net" functionality always got a NULL/empty `opal_net_private_ipv4` string.  After the commit, `opal_net_private_ipv4` has the value that it is supposed to have.

However, this apparently exposes some kind of latent bug in either the TCP BTL or the OPAL "if" (interface) functionality: after this commit, the TCP BTL tries to use the IPv6 interfaces (and fails).  Before this commit, the IPv6 interfaces were [somehow] not used in the TCP BTL / didn't generate this error.

I don't grok what is going on here yet; this is a placeholder to figure out the real issue.

**Comment by bosilca** [comment]
The output was wrong as the port was printed in network byte order. I pushed open-mpi/ompi@675dccf to fix this particular issue. Unfortunately this doesn't solve the issue.

Here is what is happening when IPV6 is enabled (on my machine at least but this apply easily to any other environment). The BTL TCP reports 2 interfaces, one IPV4 and one IPV6. On the first send the IPV6 interface is used, but unfortunately this one is not configured so the connect will fail (this is the one that print the first part of the message). As the connection fails on this endpoint, all the pending fragments have their callback triggered with an error. And here the PML is getting the info, and drastically kill the job by deciding that the peer cannot be joined (despite the fact that there are others BML endpoints to the peer).

open-mpi/ompi@a7b0c00 eabled is the IPV6 to enable itself as a possible alternative, allowing this error to be triggered.

**Comment by jsquyres** [comment]
I think there's multiple issues uncovered here:

* if_linux_ipv6.c is not ignoring disabled interfaces like it should.  I.e., we shouldn't even have 2 TCP BTL modules when all IPv6 networking is disabled.  That being said, I'm not sure why the IPv6 addresses exist on my machine when my /etc/sysconfig/network file contains `NETWORKING_IPV6=no` (which is the RHEL 6.x default).
* Should we simply ignore link local IPv6 addresses at https://github.com/open-mpi/ompi/blob/master/opal/mca/if/linux_ipv6/if_linux_ipv6.c#L122 ?  I'm not an IPv6 expert, but my understanding of IPv6 link local addresses are that they are the functional equivalent of the IPv4 169. addresses.  
  * Additionally, I think it is permissable (and encouraged?) for a single interface to have *both* a link local address *and* a global address.
  * Plus, at least in my case, we're picking up both an IPv6 address *and* an IPv4 address for the same interface.  We really should figure this out in the TCP BTL (i.e., de-duplicate, so to speak) so that we only end up with *one* TCP BTL module -- not one for each address (because the addresses refer to the same interface).  So perhaps the real solution to this particular issue is to de-duplicate the IPv4 and IPv6 addresses to only generate one TCP BTL module per actual interface (vs. per address).  The question of which address to use to contact a peer is a different question... (that I don't quite know how to answer -- should we try *all* "suitable" addresses to contact that peer?  (e.g., public addresses and private addresses if they're on the same network?)
* If we *do* keep these link local addresses, then they should be considered "private" -- i.e., the comment (and logic) at https://github.com/open-mpi/ompi/blob/master/opal/mca/btl/tcp/btl_tcp_proc.c#L563-L587 is incorrect.  That doesn't solve this particular issue, but it is

**Comment by ggouaillardet** [comment]
@jsquyres i know almost nothing about IPV6 and i did a bit of research :
- each IPV6 interface has an IPV6 link local address
- this is a non routable address
- when using an IPV6 link local address, the interface to be used must be explicitly specified :
  ping6 <my ipv6 address> fails but ping6 -I<my ipv6 interface> <my ipv6 address> does work :
```
$ ping6 fe80::0123:4567:89ab:cdef
connect: Invalid argument
$ ping6 -I eth0 fe80::0123:4567:89ab:cdef
64 bytes from fe80::0123:4567:89ab:cdef: icmp_seq=1 ttl=64 time=0.033 ms
```

I could not find any logic in the tcp btl to use the right interface.
The ```Invalid argument``` error occurs because connect is invoked with ```sin6_scope_id=0```

At this stage, my fastest/shortest/easiest way is to simply ignore link local addresses in the tcp btl.

From a pragmatic point of view, we do not (yet) support a single subnet, ipv6 only, link local addresses only cluster. As far as i am concerned, that should be documented even if i do not see this as a limitation.

**Comment by jsquyres** [comment]
@ggouaillardet How about ignoring link local addresses in if_linux_ipv6.c?  This would obviate the need to put something in oob TCP and the TCP BTL.

**Comment by jsquyres** [comment]
cddc894 contains the fix for the initially-reported bug on this issue, and therefore closed this issue.

It fully explains why commit a7b0c00 broke things w.r.t. IPv6: now that the `opal_net_private_ipv4` MCA param is being read properly, and therefore `opal_ifinit()` is properly classifying local IP interfaces as "private" instead of "public," the missing `continue` statement in the TCP BTL proc/interface matching logic for private networks mistakenly allowed execution to fall through and *also* make an IPv6 match (thereby overwriting the IPv4 private network match).

There's still other issues raised by this ticket, though:

1. Why do we tie TCP BTL modules to IP *addresses* instead of *interfaces*?  Right now, we make a TCP BTL module for each IP *address* found -- even though they may share the same *interface*.  Even though it would mean multiple listening fd's on a single BTL module, why don't we re-orient the TCP BTL module to be one per *interface*?  This might make it easier to figure out when there's multiple paths (e.g., IPv4 and IPv6) between a single pair of interfaces, and therefore OMPI should probably only use one of them.
1. I recently sent George pointers about the usnic BTL's bipartite graph method for matching local/remote interfaces (vs. the giant 2D matrix thing that is created in the TCP BTL).  That might be worth porting over to the TCP BTL (or generalizing out into common code somewhere that the TCP BTL, usNIC BTL, ?and TCP OOB? can all use).
1. We should make some definitive decision about IPv6 link-local addresses: either explicitly disallow them by default (perhaps via MCA param -- as George points out, it would be good to exclude them in a similar way that other interfaces are excluded: via `if_exclude` type MCA params... but I think we'd need some kind of new notation to denote IPv6 link local addresses), or allow them and support them properly.  For example, there's currently a few places (e.g., opal/util/net.c and btl_tcp_proc.c) that explicitly assume that all IPv6 addresses are public.

I unfortunately can't rationalize spending the time to fix the TCP BTL in these ways (unless someone wants some help generalizing the bipartite graph matching stuff out of the usNIC BTL) -- so I leave it to @bosilca or @ggouaillardet to make new github issues to cover these items.
