### ISSUE TITLE
MPI_Waitall problem in utilizing MPI Fortran interfaces "use mpi, and use mpi_f08"

### ISSUE THREAD

**Issue by yafshar** [open-mpi/ompi#587]
utilizing MPI Fortran interfaces "use mpi, and use mpi_f08" does not match with "mpif.h" when I am 
using MPI_Waitall and give MPI_STATUS_IGNORE as an input

```fortran
   CALL MPI_Waitall(count,array_of_requests,MPI_STATUS_IGNORE,IERROR)
```
It will give me an error
```
Error: There is no specific subroutine for the generic 'mpi_waitall' at (1)
```
which is totally fine when I utilize "mpif.h" interface. 
What should I use for MPI_STATUS_IGNORE in case of array_of_requests

**Comment by jsquyres** [comment]
You should use MPI_STATUSES_IGNORE (note that it is plural).  It is technically different than MPI_STATUS_IGNORE (note that it is singular).

The mpif.h interfaces are not cross-checked by the compiler at compile-time; the "use mpi" and "use mpi_f08" interfaces are checked by the compiler at compile-time.


> On May 16, 2015, at 5:39 AM, yafshar <notifications@github.com> wrote:
> 
> utilizing MPI Fortran interfaces "use mpi, and use mpi_f08" does not match with "mpif.h" when I am 
> using MPI_Waitall and give MPI_IGNORE_STATUS as an input
> 
>    CALL MPI_Waitall(count,array_of_requests,MPI_STATUS_IGNORE,IERROR)
> It will give me an error
> 
> Error: There is no specific subroutine for the generic 'mpi_waitall' at (1)
> 
> which is totally fine when I utilize "mpif.h" interface. 
> What should I use for MPI_STATUS_IGNORE in case of array_of_requests
> 
> —
> Reply to this email directly or view it on GitHub.
> 


-- 
Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by vondele** [comment]
At least with openmpi 1.8.6 this problem is not fixed using MPI_STATUSES_IGNORE:

       CALL mpi_waitall(count, requests, MPI_STATUSES_IGNORE, ierr)
                                                                  1
Error: There is no specific subroutine for the generic ‘mpi_waitall’ at (1)

**Comment by jsquyres** [comment]
On May 24, 2016, at 10:30 AM, Joost VandeVondele <notifications@github.com> wrote:
> 
> At least with openmpi 1.8.6 this problem is not fixed using MPI_STATUSES_IGNORE:
> 
>    CALL mpi_waitall(count, requests, MPI_STATUSES_IGNORE, ierr)
>                                                               1
> Error: There is no specific subroutine for the generic ‘mpi_waitall’ at (1)

This was likely a bug in the v1.8.8 Fortran interfaces.  Try upgrading to the latest v1.10.x version.

-- 
Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by vondele** [comment]
The issue is still present in v1.10.2 if the requests are a rank 2 array.

> cat test.f90 
   SUBROUTINE mp_waitall_2(requests)
      USE mpi
      INTEGER, DIMENSION(:, :), INTENT(inout)  :: requests
      INTEGER                                  :: ierr
      INTEGER                                  :: count
      count = SIZE(requests)
      CALL mpi_waitall(count, requests, MPI_STATUSES_IGNORE, ierr) 
   END SUBROUTINE mp_waitall_2

> mpif90 test.f90 
test.f90:7:67:

       CALL mpi_waitall(count, requests, MPI_STATUSES_IGNORE, ierr) 
                                                                   1
Error: There is no specific subroutine for the generic ‘mpi_waitall’ at (1)

**Comment by rhc54** [comment]
@jsquyres was probably asking you to test the 1.10.3 nightly tarball as it contains fixes that might deal with this - at least, some things went in that discussed this issue.

https://www.open-mpi.org/nightly/v1.10/

**Comment by jsquyres** [comment]
I am not a Fortran expert: does your declaration of `requests` match what is required by the MPI spec?

```fortran
interface MPI_Waitall

subroutine MPI_Waitall(count, array_of_requests, array_of_statuses, ierror)           
  integer, intent(in) :: count
  integer, dimension(count), intent(inout) :: array_of_requests
  integer, dimension(MPI_STATUS_SIZE, *), intent(out) :: array_of_statuses            
  integer, intent(out) :: ierror
end subroutine MPI_Waitall

end interface
```

I'm asking specifically about your use of `DIMENSION(:, :)`.  I notice that if you change it to `DIMENSION(:)`, the program compiles fine.

**Comment by vondele** [comment]
It would not be compatible with the interface definition you provide. 

It would be compatible with a declaration such as

subroutine MPI_Waitall(count, array_of_requests, array_of_statuses, ierror)   
  integer, intent(in) :: count
  integer, dimension(*), intent(inout) :: array_of_requests
  integer, dimension(MPI_STATUS_SIZE, *), intent(out) :: array_of_statuses   
  integer, intent(out) :: ierror
end subroutine MPI_Waitall

which is similar to what is provided under 'Fortran syntax' at 
https://www.open-mpi.org/doc/v1.8/man3/MPI_Waitall.3.php

So, if this is what the mpi standard specifies, it would mean that code conforming to the mpif.h interface would not conform to the 'use mpi' interface (and we would have to fix our code). Looking at the standard, yes, it seems to be the case.

**Comment by jsquyres** [comment]
Wait, I don't think you're correct.  :-)

Note that MPI-3.1 has *two* Fortran interfaces:

```fortran
MPI_Waitall(count, array_of_requests, array_of_statuses, ierror)
    INTEGER, INTENT(IN) ::  count
    TYPE(MPI_Request), INTENT(INOUT) ::  array_of_requests(count)
    TYPE(MPI_Status) ::  array_of_statuses(*)
    INTEGER, OPTIONAL, INTENT(OUT) ::  ierror

MPI_WAITALL(COUNT, ARRAY_OF_REQUESTS, ARRAY_OF_STATUSES, IERROR)
    INTEGER COUNT, ARRAY_OF_REQUESTS(*)
    INTEGER ARRAY_OF_STATUSES(MPI_STATUS_SIZE,*), IERROR
```

The `count` length of requests is only specified for the F08 binding -- it is not specified for the `mpif.h` / `use mpi` bindings.  So if OMPI is forcing requests to have a specific dimension size (i.e., count), that seems like a bug.

Right?  (again, I'm not a Fortran expert... please confirm!)

**Comment by vondele** [comment]
I see, so yes, I would say that the interface provided by OMPI in 'use mpi' doesn't match the subroutine MPI_WAITALL provided above, i.e. the assumed size vs. explicit-shape problem. The problem is that the current OMPI interface requires a 1D array whereas this is not required by the MPI_WAITALL definition.

Unrelated, it is a pity that mpi_f08 interface requires explicitly a 1D array, using a 2D array of requests is rather logical if e.g. a 2D Cartesian topology is used.
