### ISSUE TITLE
error: `BCOL-BASESMUMA Failed to create rcache for KNEM device`

### ISSUE THREAD

**Issue by angainor** [open-mpi/ompi#5872]
I have configured and compiled `master` version `date2018-10-09` with external PMIx (2.1.2) / hwloc / libevent (SLURM integration). I also use HPCX 2.2, but I compiled master version of UCX with it.

I get the following error / warning message when running the osu barrier test:

```
[...]
[c11-8.cluster:113971][bcol_basesmuma_component.c:501:hmca_bcol_basesmuma_init_query] BCOL-BASESMUMA Failed to create rcache for KNEM device
[c11-9.cluster:193153][bcol_basesmuma_component.c:501:hmca_bcol_basesmuma_init_query] BCOL-BASESMUMA Failed to create rcache for KNEM device
[...]
```

Haven't seen anything like this with v3.1.1 or earlier.

The test runs through, and first glance it gives results similar to 3.1.1, so it's not critical - just noise, and I don't know why it's here. Any ideas?

Marcin

**Comment by yosefe** [comment]
@angainor can you pls try with UCX v1.4.x branch? there could be incompatibility between the binary hcoll and UCX master (ucm_events were added to rcache params )?
adding @bureddy @vspetrov

**Comment by angainor** [comment]
@yosefe Thanks, branch 1.4 works without complaints!

**Comment by jsquyres** [comment]
@yosefe Is there a combination of versions that is known to not work?  If so, that type of thing should be tested for, at configure and/or run time.

**Comment by QuesarVII** [comment]
I'm having the same knem rcache error on a new cluster running CentOS 7.5 w/ kernel 3.10.0-862.14.4.el7.x86_64, slurm 18.08, Mellanox OFED 4.4-2.0.7.0, CUDA 10.0, and the stable 3.1.2 OpenMPI release.

Interestingly, the openmpi version included with MOFED (3.1.1rc1) does not have any errors when I test it instead of building OpenMPI myself.

OpenMPI was built including slurm, mxm, hcoll, knem, and cuda.

**Comment by QuesarVII** [comment]
Further investigation has shown this error is being generated by hcoll.  If I either use "-mca coll_hcoll_enable 0" or not include hcoll when compiling, it works without error.

Is this something the OpenMPI devs can resolve? Or do I need Mellanox to fix this?

**Comment by jsquyres** [comment]
@QuesarVII FYI: @yosefe is a Mellanox developer in the Open MPI project.

**Comment by vspetrov** [comment]
@QuesarVII just to clarify: are you using hcoll from MOFED (which ver?) to build you OMPI? Which ucx are you using (if any) ? Are you using UCX from MOFED as well or you have another version installed in your system?

**Comment by QuesarVII** [comment]
I am not using ucx at all.  I'm using the hcoll from MOFED.

**Comment by chunyulin** [comment]
Hi, I encounter this issue as well if I run with OMPI_MCA_coll_hcoll=1. However, OSU collective benchmark shows a slightly smaller latency for smaller problem size. Do you have any update on this issue ? Thanks.

I use openmpi-3.1.4 / 4.0.1 + CUDA10 + ucx 1.5 + knem-1.1.3.90mlnx1 +  MXM 3.7.
