### ISSUE TITLE
mpirun failing with not enough slots available

### ISSUE THREAD

**Issue by iassiour** [open-mpi/ompi#5894]
Hi ,

I am using mpi version 3.1.2. 

The following fails with "not enough slots" problem

$(MPIHOME)/mpirun -H host1 -np 1 mpi_master : -H host1,host1 -np 2 mpi_slave

host1 appears three times so I would expect the slot counter to match the -np 3.

It seems to be caused by the fact that I have split the count  along the two programs.

i.e. something like this works:
$(MPIHOME)/mpirun -H host1,host1,host1 -np 3 mpi_master

Could you please have a look and let me know if this a bug.

**Comment by rhc54** [comment]
Yep, it is a bug - PR is coming
