### ISSUE TITLE
`event_base_verbose` doesn't work in 4.0.x

### ISSUE THREAD

**Issue by angainor** [open-mpi/ompi#5954]
Checked out and compiled v4.0.x branch on my laptop: 

```
$ mpirun -mca event_base_verbose 100 ls
[angainor-Latitude-E6540:08228] mca: base: components_register: registering framework event components
[angainor-Latitude-E6540:08228] mca: base: components_register: found loaded component external
[angainor-Latitude-E6540:08228] mca: base: components_register: component external register function successful
[err] evthread initialization must be called BEFORE anything else!
```

Works fine when I decrease the verbosity level to 0.

**Comment by ggouaillardet** [comment]
@angainor I cannot reproduce this issue. which OS are you running on and how did you `configure` Open MPI ?

**Comment by angainor** [comment]
Can't check right now, but one thing that jumps into my head is I use
external libevent and pmix.

m

**Comment by ggouaillardet** [comment]
sure, please also include the libevent version.

**Comment by ggouaillardet** [comment]
@rhc54 I am able to reproduce this with the latest `libevent` (either from their `master` branch or a `2.1.8` package).

The error occurs when `pmix_rte_init()` calls `evthread_use_pthreads()` a second time (it was previously invoked by `opal`).

Here is the related PMIx code

```c
   /* if an external event base wasn't provide, create one */
    if (!pmix_globals.external_evbase) {
        /* tell libevent that we need thread support */
        pmix_event_use_threads();

        /* create an event base and progress thread for us */
        if (NULL == (pmix_globals.evbase = pmix_progress_thread_init(NULL))) {
            error = "progress thread";
            ret = PMIX_ERROR;
            goto return_error;
        }
    }
```

One option could not __not__ to call `pmix_event_use_threads()`, but I guess that would only work for Open MPI. An other option could be to have Open MPI setup and external evbase (via the `PMIX_EVENT_BASE` key). Or we could also use an intermediate option such as adding yet an other key only __not__ to call `pmix_event_use_threads()`.

Could you please advise ?

**Comment by angainor** [comment]
@ggouaillardet That's funny, because now I can't reproduce it. We have `libevent-2.0.21-4.el7.x86_64` on a Centos 7.5, and I did not install any newer version. So maybe there is another way to trigger it?

**Comment by ggouaillardet** [comment]
@angainor this error message was introduced in `libevent 2.1.6-beta`, so my guess is you tested on an other system and/or an other external libevent library.

**Comment by angainor** [comment]
@ggouaillardet @rhc54 OK, I know what happened. This is what I get when running on my Ubuntu laptop, with libevent 2.1.6. So you're right - it was a new `libevent`. And it was OpenMPI with `--enable-debug`. This is the full configure line:

```
$ ./configure --with-pmix=/home/angainor/work/pmi/install-pmix --prefix=/home/angainor/work/pmi/install-ompi --enable-debug --with-libevent=/usr
```
