### ISSUE TITLE
possible problem with rank file processing

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#5965]
@siegmargross is encountering problems using the rank file option while testing Open MPI 4.0.0rc5.
See https://www.mail-archive.com/users@lists.open-mpi.org//msg32798.html.

He reported the following
```
I've installed openmpi-v4.0.0rc5 on my "SUSE Linux
Enterprise Server 12.3 (x86_64)" with Sun C 5.15 (Oracle Developer
Studio 12.6), gcc-6.4.0, icc-19.x, and pgcc-18.4 Unfortunately, I
still get the same error that I reported yesterday.

loki config_files 114 mpicc --showme
gcc -I/usr/local/openmpi-4.0.0_64_gcc/include -fexceptions -pthread -std=c11 -m64 -Wl,-rpath -Wl,/usr/local/openmpi-4.0.0_64_gcc/lib64 -Wl,--enable-new-dtags 
-L/usr/local/openmpi-4.0.0_64_gcc/lib64 -lmpi

loki config_files 115 which mpiexec
/usr/local/openmpi-4.0.0_64_gcc/bin/mpiexec

loki config_files 116 tail -1 rf_loki
rank 0=loki slot=0:0;1:0

loki config_files 117 mpiexec -report-bindings -np 1 -rf rf_loki hostname
[loki:01325] [[39569,0],0] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file 
../../../../openmpi-4.0.0rc5/orte/mca/odls/base/odls_base_default_fns.c at line 612
loki config_files 118
```

**Comment by karasevb** [comment]
Similar problem mentioned in https://github.com/open-mpi/ompi/issues/6277. 
Is this problem still relevant?

**Comment by jsquyres** [comment]
Good question.  You might want to ask on @siegmargross on the mailing list -- he doesn't usually do much here on GitHub.

**Comment by siegmargross** [comment]
I've been on vacation until this weekend. I'll try to build the latest versions of Open MPI tomorrow and let you know if the problem still exists. Hopefully, I can do the tests because we are upgrading our lab to the latest SuSE Linux version and I don't know the current state of the lab and the machine at my office.

**Comment by siegmargross** [comment]
I was able to build openmpi-v4.0.x-201903220241-97aa434 and openmpi-master-201903260242-dfbc144 with gcc-7.4.0, icc-19.0.3.199, and pgcc-18.4-0. "mpiexec -report-bindings -np 1 -rf rf_loki hostname" works for both versions and all compilers. "rf_loki" contains the line "rank 0=loki slot=0:0;1:0".

**Comment by karasevb** [comment]
@siegmargross Thank you!
Since it works, the issue can be closed.
