### ISSUE TITLE
ampi support

### ISSUE THREAD

**Issue by teamblubee** [open-mpi/ompi#5967]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
GH_TAGNAME=	ee6cb4b9990cb15962b0b2c25446442fda8c8fb1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
git clone

### Please describe the system on which you are running

* Operating system/version: FreeBSD 12
* Computer hardware: intel i7 laptop
* Network type: wired

-----------------------------

## Details of the problem

Does openmpi support AMPI: http://charm.cs.uiuc.edu/research/ampi/
It's an option on adol-c and I couldn't find anything online so I am asking here.

**Comment by jsquyres** [comment]
As I understand it, AMPI is an entirely different implementation of MPI than Open MPI.

I.e., AMPI is a standalone MPI implementation -- it is unrelated to Open MPI, and does not use any other MPI implementation under the covers (including Open MPI).

**Comment by teamblubee** [comment]
> As I understand it, AMPI is an entirely different implementation of MPI than Open MPI.
> 
> I.e., AMPI is a standalone MPI implementation -- it is unrelated to Open MPI, and does not use any other MPI implementation under the covers (including Open MPI).

Okay, thank you.
