### ISSUE TITLE
open mpi error:bash: orted: command not found

### ISSUE THREAD

**Issue by astrung** [open-mpi/ompi#599]
When i use mpirun on a computing cluster with 2 nodes,i get this error:
bash: orted: command not found
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
    -My command:
mpicc testprogram.c
mpirun -np 5 --hostfile .mpi_hostfile ./a.out
    -If i run in a single node:
mpirun -np 5 --host localhost ./a.out >>> it works fine.(localhost is master,and my compile program in this node)
mpirun -np 5 --host slave ./a.out       >>> still same error.
So my problem is my slave right???but how to fix it ??I have installed openmpi in slave node(but with another path-not same in master).

**Comment by jsquyres** [comment]
It is likely that you do not have your PATH set correctly for non-interactive logins on the remote server.  See the FAQ for more info on setting the PATH properly (to include the "prefix" option): http://www.open-mpi.org/faq/?category=running#run-prereqs

**Comment by astrung** [comment]
When i try to test:
Node1(master):which mpirun:/usr/local/bin/mpirun
Node2(slave):which mpirun:/$USER/openmpi/bin
And when i run this command from master:
mpirun --hosts master,slave -np 4 a.out>>>same error
But when i run from slave:
mpirun --hosts master,slave -np 4 a.out>>>work fine.
It looks like that mpi will find in default location(/usr/local/...) when run and if i set another PATH for slave,it can not find????

**Comment by jsquyres** [comment]
Note that there is a difference between interactive logins and non-interactive logins.  The FAQ I cited explains both the "prefix" option and how you should be setup for non-interactive logins.
