### ISSUE TITLE
(ompi-)prun cannot connect to orte-dvm 

### ISSUE THREAD

**Issue by angainor** [open-mpi/ompi#5992]
I've compiled the current v4.0.x branch with an external PMIx 3.0.2. I'm having issues trying to connect to `orte-dvm`. 

I start the DVM as a system server:

```
$ orte-dvm -d -system-server
[c11-5.cluster:58921] procdir: /tmp/ompi.c11-5.51453/dvm/0/0
[c11-5.cluster:58921] jobdir: /tmp/ompi.c11-5.51453/dvm/0
[c11-5.cluster:58921] top: /tmp/ompi.c11-5.51453/dvm
[c11-5.cluster:58921] top: /tmp/ompi.c11-5.51453
[c11-5.cluster:58921] tmp: /tmp
[c11-5.cluster:58921] sess_dir_cleanup: job session dir does not exist
[c11-5.cluster:58921] sess_dir_cleanup: top session dir does not exist
[c11-5.cluster:58921] procdir: /tmp/ompi.c11-5.51453/dvm/0/0
[c11-5.cluster:58921] jobdir: /tmp/ompi.c11-5.51453/dvm/0
[c11-5.cluster:58921] top: /tmp/ompi.c11-5.51453/dvm
[c11-5.cluster:58921] top: /tmp/ompi.c11-5.51453
[c11-5.cluster:58921] tmp: /tmp
DVM ready
```

However, I can't seem to convince `ompi-prun`, nor the `prun` from the reference server repo to connect:

```
$ prun -system-server-first ls
[c11-5.cluster:58987] PMIX ERROR: NOT-SUPPORTED in file ptl_tcp.c at line 1058
[c11-5.cluster:58987] PMIX ERROR: NOT-SUPPORTED in file ptl_tcp.c at line 790
[c11-5.cluster:58987] PMIX ERROR: NOT-SUPPORTED in file ptl_tcp.c at line 1058
[c11-5.cluster:58987] PMIX ERROR: NOT-SUPPORTED in file ptl_tcp.c at line 790
[c11-5.cluster:58987] PMIX ERROR: NOT-SUPPORTED in file ptl_tcp.c at line 1058
[c11-5.cluster:58987] PMIX ERROR: NOT-SUPPORTED in file ptl_tcp.c at line 790
[c11-5.cluster:58987] [prun.c:743] PMIx Error: UNREACHABLE
```

As a side-note, I can `prun` when instead of `orte-dvm` I use the reference server `prte`, also compiled with the same external PMIx version.

Am I doing somethings wrong? Should I start the DVM in a different way maybe?

**Comment by rhc54** [comment]
@gpaulsen @hppritcha Both the orte-dvm and ompi-prun tools need to be removed from OMPI v4.0.0 prior to release as they are defunct and no longer maintained.

**Comment by angainor** [comment]
@rhc54 Is there a simple way to get the same functionality now with ompi / orted? Or should I use the PMIx reference server?

**Comment by rhc54** [comment]
Yes - PRRTE is your way forward.
