### ISSUE TITLE
MPI-1/MPI-2 deprecated functions (in addition to the deleted functions) were #if'ed out of mpi.h

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#5999]
We've long-since discussed that Open MPI v4.0.x will not contain any functions/symbols that have been deleted from MPI-3.1 (i.e., ancient MPI-1/2 symbols that were deprecated for a long time and then eventually deleted).

This was done by `#if`'ing out these symbols in `mpi.h.in`.

We discovered in the 2018-10-30 webex that the functions that are still *deprecated* in MPI-3.1 are *also* `#if`'ed out in `mpi.h.in`.  This is not what we intended -- we only wanted to (effectively) hide the *deleted* functions.

This needs to be fixed before v4.0.0 goes out the door.

@gpaulsen said that he would fix this.

**Comment by hjelmn** [comment]
Yeah, looks like they got caught up in the MPI-1 cleanup. Should be simple to fix.

**Comment by jsquyres** [comment]
Merged to master in #6013.  Awaiting v4.0.x cherry pick PR.

**Comment by gpaulsen** [comment]
merged to v4.0.x (for v4.0.0) in https://github.com/open-mpi/ompi/pull/6018.
Can close this now, as this is NOT going back to earlier releases.
