### ISSUE TITLE
How to uninstall without installed directory

### ISSUE THREAD

**Issue by astrung** [open-mpi/ompi#600]
I have install openmpi1.8.4 2 months ago,and now i want to reinstall 1.8.5.But i have remove the installed directory,so i dont have any "configure" file to run make uninstall.So can we have another ways to remove it????

**Comment by jsquyres** [comment]
Open MPI only installs files in the installation tree -- it doesn't modify files, or put files outside the installation tree.  So you basically have three options:

1. If you installed Open MPI into a tree by itself (e.g., if you supplied `--prefix=/opt/openmpi-1.8.4`), you can just `rm -rf /opt/openmpi-1.8.4` -- job done.
2. If you installed Open MPI into a tree with other things (e.g., if you supplied `--prefix=/usr/local`), you can remove the individual Open MPI files yourself.  E.g., `rm -rf /usr/local/lib/libmpi* /usr/local/lib/openmpi ...`).  But for you to track down all the individual files to remove could be painful / annoying / error-prone.
3. Same as #2, you could also download Open MPI 1.8.4 again, run `configure` with the prefix that you used to install 1.8.4 initially, and then just run `make uninstall`.  That is, you don't have to *build* 1.8.4 -- just `configure` it with the same prefix you did before.  Then Open MPI's "make" infrastructure will have enough information to `make uninstall`.

Option #3 might be your best bet.  It's a little circumspect, but it'll work.  Let us know.

**Comment by jsquyres** [comment]
Closing this due to lack of replies in a month.  Feel free to reply on the issue if you need further info.

**Comment by hikingpig** [comment]
Thank you! That's exactly what I'm looking for. I got "tcp_peer_recv_connect_ack: received different version..." because I installed 1 version of OMPI in /usr/local (1.10.2 version) but I compiled everything with another version (1.8.5). So I have to remove the 1.10.2 version before running anything. Your guide works just beautifully.
