### ISSUE TITLE
Fail to compile with Clang clang:  no file : '../../../opal/.libs/libopen-pal.so'

### ISSUE THREAD

**Issue by Carloon** [open-mpi/ompi#6025]
## Background information
I am installing into a brand new docker container. Nothing else is running. There are no other source code trees.
I added these apps:  autoconf automake libtool m4 flex
This is the first time I have tried to install open-mpi, so I could be doing something really dumb. I just don't what. 
### What version of Open MPI are you using? 
openmpi-3.1.3

### Describe how Open MPI was installed 
```shell
cd ~
mkdir open-mpi
cd ~/open-mpi
wget https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.3.tar.bz2
tar xf *.bz2
```

### Please describe the system on which you are running

* Operating system/version: 
     Open MPI is being installed into a docker container running Ubuntu 18.04.1 LTS
* Computer hardware: 
     iMac (Retina 5K, 27-inch, 2017), 3.4 GHz Intel Core i5, 8 GB 2400 MHz DDR4
* Network type: 
    ethernet to internet router
-----------------------------

## Details of the problem
If I do:
```shell
./configure CC=clang CXX=clang++ LD=clang --prefix=$HOME/openmpi-install
sudo make
```
I get the result shown below. But everything compiles if I do
```shell
./configure --prefix=$HOME/openmpi-install
sudo make
```
  I also tried installing in 'cd ~', but it didn't change anything.

```shell
 ... ... ...
Making all in tools/wrappers
make[2]: Entering directory '/home/ubuntu/open-mpi/openmpi-3.1.3/opal/tools/wrappers'
  CC       opal_wrapper.o
  CCLD     opal_wrapper
clang: error: no such file or directory: '../../../opal/.libs/libopen-pal.so'
Makefile:1876: recipe for target 'opal_wrapper' failed
make[2]: *** [opal_wrapper] Error 1
make[2]: Leaving directory '/home/ubuntu/open-mpi/openmpi-3.1.3/opal/tools/wrappers'
Makefile:2376: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/open-mpi/openmpi-3.1.3/opal'
Makefile:1898: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
Thank you for your attention,
carlton.mills@runtimeverification.com
Urbana, Illinois

**Comment by jsquyres** [comment]
Works for me with clang 7.0.0 if I do not specify `LD=clang`.  I.e.:

```
shell$ ./configure CC=clang CXX=clang++ --prefix=$HOME/openmpi-install
shell$ make -j 32
```

**Comment by Carloon** [comment]
It fixed the problem. I can compile it.

**Comment by spanigrahi1** [comment]
i am tring to compile with llvm compiler , 
./configure   --prefix=${MPI_DIR}   CC=clang   CXX=clang++   FC=flang-new   CFLAGS="${CFLAGS}"   CXXFLAGS="${CXXFLAGS}"   FCFLAGS="${FCFLAGS} ${ADD_FLAGS}"   --enable-mpi-fortran=all   --enable-mpi1-compatibility   --with-slurm   --without-cuda   --enable-shared   --enable-static   --with-ucx=${UCX_DIR}   --with-hcoll=${HCOLL_DIR}   --with-ucc=${UCC_DIR}   --with-hwloc=${HWLOC_DIR}   --with-knem=${KNEM_DIR}   --with-xpmem=${XPMEM_DIR}   --with-pmix=internal   LDFLAGS="-fPIC"   2>&1 | tee log.0

make -j gives me error ,
clang: error: no such file or directory: '../../../opal/.libs/libopen-pal.so' make[2]: *** [Makefile:1884: opal_wrapper] Error 1 make[2]: Leaving directory '~/build/ompi418/llvm-aocc/aof600/openmpi-4.1.8/opal/tools/wrappers' make[1]: *** [Makefile:2387: all-recursive] Error 1 make[1]: Leaving directory '~/build/ompi418/llvm-aocc/aof600/openmpi-4.1.8/opal' make: *** [Makefile:1905: all-recursive] Error 1
