### ISSUE TITLE
undefined symbol: mca_psensor_file_component

### ISSUE THREAD

**Issue by benmenadue** [open-mpi/ompi#6056]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

3.1.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

release tarball, `./configure && make && make install`

### Please describe the system on which you are running

* Operating system/version: CentOS 6.10
* Computer hardware: various
* Network type: IB

-----------------------------

## Details of the problem

Launching an program produces these warnings:
```
[raijin7:07223] pmix_mca_base_component_repository_open: "mca_psensor_file" does not appear to be a valid psensor MCA dynamic component (ignored): /apps/openmpi/3.1.3/lib/pmix/mca_psensor_file.so: undefined symbol: mca_psensor_file_component. ret -1
```
There's one from each MPI process and 1 for the `mpirun`. The same happens regardless of whether we use the internal pmix distribution of an external build of PMIx 2.1.4.

I think the problem is a missing `PMIX_EXPORT` on https://github.com/open-mpi/ompi/blob/17040631627b760efe3da95b4fc75eaf1d1aca4c/opal/mca/pmix/pmix2x/pmix/src/mca/psensor/file/psensor_file.h#L32 I'm just testing this at the moment; if it fixes it, can I PR into the 3.1.x branch? (I can't PR it to master since these files are branch-specific.)

**Comment by benmenadue** [comment]
I just logged a PR against v3.1.x (#6057) but GitHub is being weird and giving me a 404 when I try to display it.

**Comment by jsquyres** [comment]
This has been merged everywhere; closing.

**Comment by spikebike** [comment]
I'm getting this with openmpi-4.0.1 compiled with PMIX-2.1.4.  When I try to run:
'''
Module openmpi/4.0.1 loaded 
[c5-88:17196] pmix_mca_base_component_repository_open: "mca_psensor_file" does not appear to be a valid psensor MCA dynamic component (ignored): /share/apps/pmix-2.1.4/gcc7/lib/pmix/mca_psensor_file.so: undefined symbol: mca_psensor_file_component. ret -1
'''

**Comment by jsquyres** [comment]
@spikebike Please open a new issue; thanks.

**Comment by spikebike** [comment]
$jsquyres I rebuilt with PMIX-2.2.2 and it worked.  Do you want me to file a bug if it's only triggered when building with PMIX-2.1.4?
