### ISSUE TITLE
degrade

### ISSUE THREAD

**Issue by tdr1991** [open-mpi/ompi#6079]
Hi everyone，

I have installed mpi v4，but mpi4py does not seems to support v4，the error is "src/mpi4py.MPI.c:167054:62: error: use of undeclared identifier 'MPI_LB'; did you mean 'MPI_IO'?", so how to degrade v4 to v3/v2?

**Comment by kawashima-fj** [comment]
`MPI_LB` cannot be used by defaut in Open MPI 4.0.0.

From README of Open MPI 4.0.0:

> Note that starting with Open MPI v4.0.0, prototypes for several
> legacy MPI-1 symbols that were deleted in the MPI-3.0 specification
> (which was published in 2012) are no longer available by default in
> mpi.h.  Specifically, several MPI-1 symbols were deprecated in the
> 1996 publishing of the MPI-2.0 specification.  These deprecated
> symbols were eventually removed from the MPI-3.0 specification in
> 2012.
(snip)
> All that being said, if you are unable to immediately update your
> application to stop using these legacy MPI-1 symbols, you can
> re-enable them in mpi.h by configuring Open MPI with the
> --enable-mpi-compatibility flag.

Though I don't know whether the latest mpi4py still uses `MPI_LB`, `--enable-mpi-compatibility` may help you.

**Comment by kawashima-fj** [comment]
@tdr1991 If you want to use Open MPI 4.0.0 with your mpi4py, yes. Asking mpi4py community not to use `MPI_LB` and other deleted MPI features is another option.

Of course, using an older version of Open MPI is another option. If you have installation of an older version, mpi4py will use the version if you set the environment variable `PATH` or something.

**Comment by tdr1991** [comment]
@kawashima-fj ok, thank you.

**Comment by ggouaillardet** [comment]
@tdr1991 note `MPI_LB` is no more visible but is still there, and Open MPI 4.0.0 is binary compatible with 3.1.3.

That means that yet an other option is to build `mpi4py` with Open MPI 3.1.3, and then change Open MPI to 4.0.0 "under the hood".

**Comment by tdr1991** [comment]
@ggouaillardet thank you, the author of mpi4py has fixed it, we can install it this quick way:

pip install https://bitbucket.org/mpi4py/mpi4py/get/maint.tar.gz

**Comment by jsquyres** [comment]
@dalcinl rocks!  Thanks for the speedy fix, Lisandro!

**Comment by dalcinl** [comment]
@jsquyres Well, my fix just aliased `MPI_LB` to `MPI_DATATYPE_NULL`.  The issue I'm facing is that mpi4py is still supporting legacy MPI 1.x implementations. I was tempted to access the real thing through an external declaration, but you guys warn that you may remove it from the library any time soon. So to make my life easy I'm just exposing `LB` as `NULL`, and if any mpi4py user complains, I'll redirect the blame to you guys :-).

PS: Will you ever put mpi4py under your regression tests? My own CI tests are currently broken with latest Open MPI releases, eg: https://travis-ci.org/mpi4py/mpi4py/jobs/454977105 and https://circleci.com/gh/mpi4py/mpi4py/125

**Comment by jsquyres** [comment]
@dalcinl Yeah, it's going to be a long road to finally getting rid of this stuff.  The `MPI_LB` (and friends) will definitely be there throughout all of 4.x (i.e., 4.0.x and beyond).  Whether we remove it from 5.0.x -- only time will tell.  Depends on how much pushback we get on this.

As for mpi4py: I actually have a little time this upcoming week.  Did you send me some starter testing scripts at some point?  I have to integrate them into MTT, but seeing what you do for testing steps would be helpful.

**Comment by jsquyres** [comment]
I see https://bitbucket.org/mpi4py/mpi4py/src/39ca784226460f9e519507269ebb29635dc8bd90/bitbucket-pipelines.yml?at=master&fileviewer=file-view-default; using that as a basis...

**Comment by dalcinl** [comment]
@jsquyres That's the best option if you are running tests on a docker container. However, if you some other in-house CI infrastructure like Jenkins, then maybe it is faster to pre-install Python, NumPy and . Cython. After that, either from within a mpi4py's git checkout or after unpacking a release tarball, and making sure your have `mpicc` in `$PATH`, then these commands should build and test mpi4py (from the local build, no need to install it to test):

```
python3 setup.py clean --all # clean any previous build
python3 setup.py build # build using `mpicc` in `$PATH`
mpiexec -n 1 python3 $PWD/test/runtests.py
mpiexec -n 5 python3 $PWD/test/runtests.py -f
mpiexec -n 1 python3 $PWD/demo/futures/test_futures.py
mpiexec -n 5 python3 $PWD/demo/futures/test_futures.py -f
mpiexec -n 1 python3 -m mpi4py.futures $PWD/demo/futures/test_futures.py
mpiexec -n 5 python3 -m mpi4py.futures $PWD/demo/futures/test_futures.py -f
```
