### ISSUE TITLE
oob:ud is .ompi_ignored in v1.10.0

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#609]
@hjelmn @rhc54 I just noticed that oob:ud is .ompi_ignored on the v1.10 branch.  Is the oob:ud component stable on master?  Should it be brought over to the v1.10 branch?

@miked-mellanox @jladd-mlnx may also have opinions here...?

(this is an open question -- I don't have an opinion here; I just noticed this and thought that someone might want to enable ud in the v1.10.0 release)

**Comment by jladd-mlnx** [comment]
It doesn't make sense to include it in 1.10. We revived it in master to
support PMIx collectives on IB systems. It can stay .ompi_ignored in 1.10
and will go live with PMIx in the 2.0 release.

Josh

**Comment by jsquyres** [comment]
Roger.
