### ISSUE TITLE
README update: XPMEM is ok these days

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#6090]
Per @hjelmn's comment on https://www.mail-archive.com/users@lists.open-mpi.org/msg32858.html:

> I really need to update that wording. It has been awhile and the [XPMEM] code seems to have stabilized. It’s quite safe to use and supports some of the latest kernel versions.

**Comment by hjelmn** [comment]
@jsquyres This is the wording in the README of hjelmn/xpmem . Will fix soon. Probably worth putting a note about XPMEM in our README though.

**Comment by gpaulsen** [comment]
I removed awaiting code, since this is a doc only issue.

**Comment by gpaulsen** [comment]
README looks okay in v4.0.x
