### ISSUE TITLE
OpenMPI 4.0.0 doesn't build with gcc/gfortran 6.3.0 when using make -j

### ISSUE THREAD

**Issue by dorier** [open-mpi/ompi#6115]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

4.0.0, from the archive provided on the website.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

I tried with spack (`spack install openmpi`) and by downloading the archive and compiling it manually.

### Please describe the system on which you are running

* Operating system/version: Debian 9
* Computer hardware: x86_64
* Network type: Ethernet

-----------------------------

## Details of the problem

I tried installing openmpi 4.0.0 with spack first, this was failing during the build process. I downloaded the archive and tried compiling it manually, invoking `make` with `-j`, this was failing. Calling `make` without a `-j` option was successful.

**Comment by jsquyres** [comment]
Can you provide more detail about what failed?

Parallel builds (i.e., via `make`'s `-j` option) are fully supported.

**Comment by dorier** [comment]
Indeed, my bad: `make -j` was exhausting the memory and swap space on my machine, leading to some of the make processes being killed. Adding more swap space solved it. I'm closing the issue.

**Comment by jsquyres** [comment]
FWIW: I notice that recent versions of `make` treat `-j` as "spawn as many concurrent processes as possible".  This is different than older versions of `make` which treat `-j` as "spawn num_processors processes".

Specifically, in the `ompi/mpi/c` directory, there are 385 `*.c` files.  In the old `-j` behavior, you'd only spawn a small, finite number of simultaneous compiles (e.g., 8, 16, 32, or some other "small" number like that).  With the new `make -j` behavior, you'll spawn 385 simultaneous compiles.  Bad Things can happen.

Hence, scripts that invoke `make -j` (without specifying a value to the `-j` argument) are susceptible to this change in `make` default behavior over time.  😦   Indeed, I had to update some of my own scripts to always add a value after `-j` for this exact reason.
