### ISSUE TITLE
UCX components missing owner.txt

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#6119]
Thank you for taking the time to submit an issue!

## Background information

We require all components to have an owner.txt file giving the current owner and development status of the component.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

All versions

## Details of the problem

The owner of pml/ucx and osc/ucx need to add owner.txt files to master. I do not know if this is required for release branches (probably not as we don't typically delete/heavily modify components from releases).

**Comment by jsquyres** [comment]
@yosefe Can you guys make `owner.txt` files?  Should take all of 5 minutes.  Thanks!
