### ISSUE TITLE
v4.0.x: configure fails in pmix detection

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#6127]
Trying to build branch v4.0.x on my local laptop fails with the following error:

```
$ ../configure
[...]
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking for struct sockaddr_in... yes
configure: pmix builddir: /home/joseph/src/openmpi/git/ompi/build/opal/mca/pmix/pmix4x/pmix
configure: pmix srcdir: /home/joseph/src/openmpi/git/ompi/opal/mca/pmix/pmix4x/pmix
configure: Detected VPATH build
checking for pmix version... ../../../../../../opal/mca/pmix/pmix4x/pmix/configure: line 20040: /home/joseph/src/openmpi/git/ompi/opal/mca/pmix/pmix4x/pmix/config/pmix_get_version.sh: No such file or directory
configure: error: Cannot continue
configure: /bin/bash '../../../../../../opal/mca/pmix/pmix4x/pmix/configure' *failed* for opal/mca/pmix/pmix4x/pmix
checking if v4.x component is to be used... yes - using the internal v4.x library
configure: WARNING: INTERNAL PMIX FAILED TO CONFIGURE
configure: error: CANNOT CONTINUE
```

In `opal/mca/pmix/pmix4x/pmix/config.log` I can only see:
```
configure:20028: pmix builddir: /home/joseph/src/openmpi/git/ompi/build/opal/mca/pmix/pmix4x/pmix
configure:20030: pmix srcdir: /home/joseph/src/openmpi/git/ompi/opal/mca/pmix/pmix4x/pmix
configure:20033: Detected VPATH build
configure:20038: checking for pmix version
configure:20042: error: Cannot continue
```

I don't see where the error comes from.

Configuration succeeds on branch `master`. Maybe `v4.0.x` is missing a PR?

**Comment by devreal** [comment]
I'm attaching both [`opal/mca/pmix/pmix4x/pmix/config.log`](https://github.com/open-mpi/ompi/files/2622162/opal_pmix_config.log.tar.gz) and  [`config.log`](https://github.com/open-mpi/ompi/files/2622164/config.log.tar.gz)

**Comment by rhc54** [comment]
I just did a VPATH build on the head of v4.0.x on my Mac and it built fine. You might want to check that you have an up-to-date clone of the branch as lots of things have been committed.

**Comment by ggouaillardet** [comment]
there is no `pmix4x` in the `v4.0.x` branch, so you likely have some files to cleanup (and you will likely need to run `autogen.pl` after)

**Comment by devreal** [comment]
@ggouaillardet I totally forgot about this after changing branches (mostly working on CMake projects these days...). After running `autogen.pl` everything works as expected. Sorry for the noise.

**Comment by jsquyres** [comment]
@devreal You might also want to run `git clean -dfx .` when switching branches.  We do have differing sets of components between the various branches in git -- doing the `git clean` will make sure to remove directories that shouldn't be there / aren't tracked by git on a particular branch.

(I say this because I've run into this exact issue myself 😉)
