### ISSUE TITLE
UCX PML error messages on ARM v8 CI platform

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#6134]
On ARMv8 CI testing, I see messages like this:

```
[1543445279.655409] [juno001:29049:0]       ib_iface.c:444  UCX  ERROR ibv_create_cq(cqe=256) failed: Cannot allocate memory
[juno001:29049] pml_ucx.c:212 Error: Failed to create UCP worker
[1543445279.669130] [juno001:29050:0]       ib_iface.c:444  UCX  ERROR ibv_create_cq(cqe=256) failed: Cannot allocate memory
[juno001:29050] pml_ucx.c:212 Error: Failed to create UCP worker
```

For example, #6133 (a README change on master) shows these messages when running "hello world" and other trivial tests: https://jenkins.open-mpi.org/jenkins/job/open-mpi.build.platforms/4123/Platform=ARMv8/console 

@hppritcha @shamisp Is this expected on the ARMv8 CI platform?

**Comment by shamisp** [comment]
Let me ask IT to reboot it

**Comment by jsquyres** [comment]
@shamisp This is still happening -- e.g., https://jenkins.open-mpi.org/jenkins/job/open-mpi.build.platforms/4137/Platform=ARMv8/console

Note that this is not causing failures, these are just warning messages and UCX ends up being ignored.  If this is not intentional (i.e., if you intend to use UCX on this CI platform), you should add relevant `--mca` CLI params to force its use.

**Comment by hppritcha** [comment]
what does ```ibv_devinfo -vvv``` on juno report?

**Comment by jsquyres** [comment]
@hppritcha I assume that's a question for @shamisp, right?  I have no access to ARM's Open MPI CI machines.

**Comment by shamisp** [comment]
I'm OOO, but once I'm connected, I will take a look again.

**Comment by hppritcha** [comment]
@hoopoepg can this issue be close?

**Comment by hoopoepg** [comment]
hi @hppritcha 
I think yes.

thank you
