### ISSUE TITLE
commit ea35e47  breaks cray build

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#616]
commit ea35e47 breaks build of ompi for cray

**Comment by jsquyres** [comment]
@hppritcha I can't seem to find this commit in the ompi repo.  Which commit are you referring to?

**Comment by ggouaillardet** [comment]
i forgot some git add in my last three commits (missing fortran bindings) and that broke many things.
I am afk, so feel free to revert them.

**Comment by hppritcha** [comment]
fixed the commit sha in description.
