### ISSUE TITLE
MPI_THREAD_MULTIPLE support on ppc64le error

### ISSUE THREAD

**Issue by robertsawko** [open-mpi/ompi#6171]
I am running several openmpi versions on ppc64le, but mainly 3.1.x. As per another issue I compiled my own UCX and pointed the build scripts to it. According to the notes I've got MPI_THREAD_MULTIPLE is now a default so I remove the `-with-thread-multiple` from the configure script and the build goes fine.

When running any program though, every rank seems to be producing the following error message:
```
[pge328:67669] ../../../../../openmpi-3.1.2/ompi/mca/pml/ucx/pml_ucx.c:226 Error: UCP worker does not support MPI_THREAD_MULTIPLE
```

Is that something I need to bo worried about? How to fix this? Please advise.

**Comment by yosefe** [comment]
@robertsawko looks like UCX was compiled without multii-thread support - need to add `--enable-mt` to UCX `./configure` command

**Comment by yosefe** [comment]
"checking for mt" print here is unrelated, looks like it's related to "manifest tool"
there is no special print when multi-thread is enabled, but you should see something like this:
```
$ grep ENABLE_MT config.status
D["ENABLE_MT"]=" 1"
```

**Comment by robertsawko** [comment]
Thanks, @yosefe. I do seem to get the right value:
```
grep ENABLE_MT build-ucx-1.4.0/config.status 
D["ENABLE_MT"]=" 1"
```

**Comment by robertsawko** [comment]
But I just found that UCX has an info application and here the picture is clear:
```ucx_info  -b | grep MT
#define ENABLE_MT                 0
```

**Comment by yosefe** [comment]
any chance there are some leftovers in the build environment?
what does `ucx_info -v` say?

**Comment by robertsawko** [comment]
What do you mean by leftovers? I can't find anything obvious.

```
# UCT version=1.4.0 revision 973dfb1
# configured with: --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/gpfs/paragon/local/apps/dev//compiler/gcc/6.4/ucx/1.4.0 --enable-mt --without-java --disable-doxygen-doc

```

**Comment by robertsawko** [comment]
@yosefe I think there were some "leftovers" in the openmpi directory actually. I built several different versions and wasn't deleting the old ones properly.

I learnt another lesson. This is what I do in my build scripts now:
```bash
${SRC_DIR}/configure \
     --prefix=${INSTALL_DIR} \
    ...
   && make -j16
rm -rf $INSTALL_DIR 2> /dev/null
make install
```
