### ISSUE TITLE
"Administrative rules" Wiki page title misspelled

### ISSUE THREAD

**Issue by apjanke** [open-mpi/ompi#6186]
(I deleted the issue template stuff because this Issue is about the open-mpi/ompi GitHub project stuff, and not Open MPI itself.)

---------

The Wiki page for "Administrative rules" at https://github.com/open-mpi/ompi/wiki/Admistrative-rules has its title misspelled as "Admistrative-rules".

Can this be fixed?

It looks like this may be a carryover from the old Trac Wiki at https://svn.open-mpi.org/trac/ompi/wiki; I see some links to https://svn.open-mpi.org/trac/ompi/wiki/Admistrative%20rules in the `community/lists/devel` posts over in the ompi-www repo. Changing the new wiki shouldn't title break those links to the old one, because it doesn't look like there's a redirect set up.

If this is changed, will also need to update links in https://github.com/open-mpi/ompi-www in the `about/members/index.php`, `community/contribute/index.php`, and `faq/contributing.inc` pages:

* https://github.com/open-mpi/ompi-www/blob/0e9fa370b74d633b9265e6616c882f0fe157c9d4/about/members/index.php#L18
* https://github.com/open-mpi/ompi-www/blob/0e9fa370b74d633b9265e6616c882f0fe157c9d4/community/contribute/index.php#L87-L89
* https://github.com/open-mpi/ompi-www/blob/0e9fa370b74d633b9265e6616c882f0fe157c9d4/faq/contributing.inc#L99
* https://github.com/open-mpi/ompi-www/blob/0e9fa370b74d633b9265e6616c882f0fe157c9d4/faq/contributing.inc#L114

And also one link in the `ompi` repo in [`.github/CONTRIBUTING.md`](https://github.com/apjanke/ompi/blob/52235014164710a78400dd47c4198c6d83189c7e/.github/CONTRIBUTING.md):

```
To that end, we require that all Git commits contributed to Open MPI
have a "Signed-off-by" token indicating that the commit author agrees
with [Open MPI's Contributor's
Declaration](https://github.com/open-mpi/ompi/wiki/Admistrative-rules#contributors-declaration).
```

**Comment by hppritcha** [comment]
@apjanke could you double check our spelling now?

**Comment by jsquyres** [comment]
I think is all fixed now.  Thanks!
