### ISSUE TITLE
 How can I get the global bindings in root rank? 

### ISSUE THREAD

**Issue by thzhao** [open-mpi/ompi#6215]
Thank you for taking the time to submit an issue!

## Background information

I want to get the process distance when MPI are running. I try to call function get_distance_matrix() in ompi\opal\mca\btl\usnic\btl_usnic_hwloc.c, but the distance of the local node's socket is returned. Then I use hwloc_get_cpubind() ,still the local bind is returned. 

So, is there an api or data structure that I can use to get the globe binding information in one process. For example, in rank 0 I can know where the rank 7 is running and which core rank 7 is binding.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

mpirun (Open MPI) 4.0.0rc5 with UCX

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

installed from a git clone.

### Please describe the system on which you are running
* Operating system/version: 
CentOS Linux release 7.2.1511 (Core)
* Computer hardware: 
Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz，Core(s) per socket: 12
* Network type: 
MellanoxConnectX-3 Pro，10Gbs
-----------------------------

## Details of the problem
```
...
 if (0 != hwloc_distances_get_by_type(opal_hwloc_topology, HWLOC_OBJ_CORE,
                                         &matrix_nr, &matrix,
                                         HWLOC_DISTANCES_KIND_MEANS_LATENCY, 0) || 0 == matrix_nr) {
          return;
        }else{
                printf("printf distance\n");

                print_distances(matrix);
        }

```
```shell
shell$ mpirun -np 4 -H c01:1,c02:1,c03:1,cu04:1 -x UCX_NET_DEVICES=mlx4_0:1 -x UCX_TLS=rc -x UCX_SHM_DEVICES=sysv ./get_distance
```
printf distance
          0     1
    0    10    21
    1    21    10

**Comment by jsquyres** [comment]
> So, is there an api or data structure that I can use to get the globe binding information in one process. For example, in rank 0 I can know where the rank 7 is running and which core rank 7 is binding.

Open MPI does not expose that information to user applications, sorry.  You will need to call hwloc calls manually.
