### ISSUE TITLE
master: PMIx assertion failures during abort

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#6222]
I'm seeing a fair number of PMIx assert failures on master when a job is aborting.  It doesn't happen 100% of the time, but it seems fairly frequent:

```
pmix_list_remove_item - the item 0x2aaaac036110 is not on the list 0x2aaaab471608 
mpirun: server/pmix_server.c:2342: _mdxcbfunc: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (tracker))->obj_magic_id' failed.
```

Here's a backtrace from one of the `orterun` corefiles:

```
#1  0x55804d7b in OPAL_MCA_PMIX4X_PMIx_Finalize (info=0x0, ninfo=0)
    at client/pmix_client.c:823
#2  0x557a2b1a in pmix4x_client_finalize () at pmix4x_client.c:203
#3  0x555bafc6 in clean_abort (fd=7, flags=2, arg=0x0) at ess_hnp_module.c:933
#4  0x5574d454 in event_process_active_single_queue (base=0x806f9b0, activeq=0x806fd40)
    at event.c:1370
#5  0x5574d67f in event_process_active (base=0x806f9b0) at event.c:1440
#6  0x5574dcc8 in opal_libevent2022_event_base_loop (base=0x806f9b0, flags=1)
    at event.c:1644
#7  0x08048fa7 in orterun (argc=16, argv=0xffffcc14) at orterun.c:200
#8  0x08048c2c in main (argc=16, argv=0xffffcc14) at main.c:13
```

It appears to be choking on this line in `pmix_client.c`:

```
PMIX_LIST_DESTRUCT(&pmix_client_globals.pending_requests);
```

@rhc54 Can you have a look?  Is there more information I can provide?

**Comment by rhc54** [comment]
@ggouaillardet and I just fixed a bunch of problems like this - I believe most of the fixes were in PMIx master, though we have made a number of changes in PRRTE as well. You might start by simply updating the embedded pmix4x component to the head of the PMIx master branch. Sadly, we don't make nightly tarballs, but it's easy enough to generate one 😄

**Comment by rhc54** [comment]
If you find that doesn't fully resolve the problems, then you'll likely need to look at somehow "upstreaming" the PRRTE changes and/or doing something with the opal/pmix glue code. Either one won't be easy, I fear, so definitely try updating the embedded version first.

**Comment by jsquyres** [comment]
@ggouaillardet just made #6223; let's see how that does.

(Cisco just entered its shutdown; my MTT servers are now mostly powered off for the next week or two)

**Comment by jsquyres** [comment]
I just re-enabled Cisco MTT after our holiday shutdown.  Let's see how it goes.

**Comment by jsquyres** [comment]
At first glance, this seems to have helped tremendously -- I'm not seeing TB of corefiles any more.  Thanks!
