### ISSUE TITLE
Autodetected presence of ugni overrides --with-pmi for PMI2

### ISSUE THREAD

**Issue by chrissamuel** [open-mpi/ompi#6274]
Thank you for taking the time to submit an issue!

## Background information

I spent a few hours this morning trying to help a user understand why OpenMPI built on an Intel cluster with certain Cray libraries installed fails to correctly wire up its ranks (everything thinks it is rank 0).

In the end it appears it is the result of this line in opal/mca/pmix/s2/configure.m4

`    AS_IF([test "$opal_enable_pmi2" = "yes" && test "$opal_check_ugni_happy" = "no"],`

This results in the autodetected presence of the Cray ugni libraries disabling PMI2 support, despite it being explicitly requested with --with-pmi=/path/to/slurm

I can confirm that configuring with --with-ugni=no fixes the problem.

Is there a better way to handle this to prevent this unexpected behaviour? 

My personal suggestion would be to abort configuration with an explanation if --with-pmi was requested but ugni is auto-detected (the user wanted pmi so it's best to tell them it isn't going to work in this case).

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

Seen in 3.1.3 but the same line appears to be in 4.0.0 and the current git master.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

I was testing from tarball, the user was building from a git branch.

### Please describe the system on which you are running

* Operating system/version: Standard Intel cluster
* Computer hardware: x86-64 Skylake servers
* Network type: Infiniband

-----------------------------

## Details of the problem

see above.

**Comment by hppritcha** [comment]
yes this is kind of a hacky way.  Can you tell what other Cray libraries are installed on the system?

**Comment by chrissamuel** [comment]
Hi Howard,

Thanks for this - it looks like a lot as it is based off of our eslogin node image but using opensuse as a base rather than SLES.  Includes MOFED and CUDA driver.

cgpu01:~ # rpm -qa '*cray*' | wc -l
183

Includes Cray's xpmem, ugni, etc. I can fire you a full list by private email if that helps?

All the best,
Chris

**Comment by hppritcha** [comment]
closing as won't fix.   Cray XC network is getting long in the tooth as is the GNI BTL.
