### ISSUE TITLE
Memory Leak in MPI_Get_elements_x

### ISSUE THREAD

**Issue by ax3l** [open-mpi/ompi#6291]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

`master` as of 352b667323d02c0eb7c2df6325554645ffe56920

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From source via `spack`.

### Please describe the system on which you are running

* Operating system/version: Debian 9
* Computer hardware: ThinkPad
* Network type: Local

-----------------------------

## Details of the problem

The function `opal_datatype_compute_ptypes` in https://github.com/open-mpi/ompi/blob/352b667323d02c0eb7c2df6325554645ffe56920/ompi/datatype/ompi_datatype_get_elements.c#L52 allocates datatypes in https://github.com/open-mpi/ompi/blob/98afc838aa53da88cba339f6dcbab256806a5745/opal/datatype/opal_datatype_get_count.c#L161 that don't seem to be freed.

Seen while running a small MPI-I/O example with HDF5 `develop`: https://forum.hdfgroup.org/t/hdf5bug-h5fd-mpio-collective-chunking/5279

**Comment by ggouaillardet** [comment]
@ax3l thanks for the report !

Meanwhile, feel free to manually download and apply the patch at https://github.com/open-mpi/ompi/pull/6292.patch

**Comment by ggouaillardet** [comment]
The fix has landed into both `master` and `v4.0.x` branch, so I am now closing this issue.

**Comment by ax3l** [comment]
Thanks a lot!
