### ISSUE TITLE
Configure check for libfabric fails in loading the correct lib

### ISSUE THREAD

**Issue by xtus** [open-mpi/ompi#6364]
Hi,

I tested v4.0.0 tarball and git master 5aef3148d33c1864d5429a26c223680183f16af3

I configure using ``--with-ofi`` pointing to an install of libfabric 1.7.0 with ABI 1.2

System-wide is also installed libfabric 1.6.2 with ABI 1.1

The configure check ``checking if libfabric requires libnl v1 or v3`` returns ``v3``, but is actually failing trying to load the system-wide libfabric instead of the ``--with-ofi`` one:
```
./conftest: /lib64/libfabric.so.1: version `FABRIC_1.2' not found (required by ./conftest)
```

The libfabric 1.7.0 is not listed in ``LD_LIBRARY_PATH``.
I would expect the check to use RPATH, but looking at ``config.log`` is not the case.

I'm running CentOS 7.6.1810, x86_64, Omni-Path network.

Regards,
Marco

**Comment by jsquyres** [comment]
Can you submit your config.log file?  (you may need to put it in a gist or pastebin or somesuch)

**Comment by xtus** [comment]
Thanks for the quick reply. Here you go: [config.log on gist](https://gist.github.com/0ab57def7bbac7cd3c61f333dff8bfd7)

**Comment by ggouaillardet** [comment]
@xfus I am afraid your `config.log` was truncated. can you please compress it and upload it again ?

We do not use `-rpath` unless `--enable-mpirun-prefix-by-default` is used in the `configure` command line.
That being said, I am not sure we would add it here.
I suggest you first try with `--enable-mpirun-prefix-by-default` and if it does not work, you can add libfabric 1.7.0 to your `LD_LIBRARY_PATH` as a workaround.

**Comment by xtus** [comment]
@ggouaillardet Sorry about that, gist truncate the preview by default; the full version is hidden by the RAW button, i.e. [config.log 6MiB uncompressed](https://gist.githubusercontent.com/xtus/0ab57def7bbac7cd3c61f333dff8bfd7/raw/441b26ddcabfd13abc461cd1d184555c3f245ee7/ompi_issue_6364_config.log)

Using `--enable-mpirun-prefix-by-default` does not fix the configure issue.

I have to say that without `--enable-mpirun-prefix-by-default` and without `LD_LIBRARY_PATH` workaround, ignoring the configure`version 'FABRIC_1.2' not found` and going ahead with the build, everything works fine. All OMPI library and bin include the correct `RPATH` to libfabric 1.7.0, and compiled code have the correct `RUNPATH`

An `mpicc --showme` returns:
```
gcc -I/home/marco/ompi/install/include -fexceptions -pthread
    -L/home/marco/libfabric/install/lib
    -L/home/marco/ucx/install/lib
    -L/usr/lib64
    -Wl,-rpath -Wl,/home/marco/libfabric/install/lib
    -Wl,-rpath -Wl,/home/marco/ucx/install/lib
    -Wl,-rpath -Wl,/usr/lib64
    -Wl,-rpath -Wl,/home/marco/ompi/install/lib
    -Wl,--enable-new-dtags
    -L/home/marco/ompi/install/lib -lmpi
```

`RPATH` for OMPI lib and bin:
`/home/marco/ompi/install/lib:/home/marco/libfabric/install/lib:/home/marco/ucx/install/lib`

`RUNPATH` for compiled code against OMPI:
`/home/marco/libfabric/install/lib:/home/marco/ucx/install/lib:/usr/lib64:/home/marco/ompi/install/lib`

**Comment by gpaulsen** [comment]
This should be fixed if retested with newer libfabric.  Closing.
