### ISSUE TITLE
UCX mpool warning at program end

### ISSUE THREAD

**Issue by angainor** [open-mpi/ompi#6376]
We see plenty of similar warning messages at the end of the execution of one user's code:

```
[1549709400.885570] [c8-1:59909:0]          mpool.c:38   UCX  WARN  object 0xe9d9464c0 was not returned to mpool ucp_requests
```
The code is compiled with the Intel compiler + OpenMPI 3.1.1 + HPCx 2.2. I'm guessing this warning means that some communication requests were not completed at the end of the program. Is there a scenario, in which something like this could happen due to an erroneous user program? E.g., would that be triggered by incomplete non-blocking communication? Or is this some internal problem with OpenMPI / UCX?

Of course - the warnings don't come every time.. I'd appreciate any thoughts. 

Thanks!

**Comment by yosefe** [comment]
if user application does not MPI_Wait for a nonblocking request, it may happen

**Comment by angainor** [comment]
@yosefe Thanks! that was also my suspicion. I'll tell them to verify the comm implementation.
