### ISSUE TITLE
Can I use a FORTRAN program using open Mpi in my single computer

### ISSUE THREAD

**Issue by engTaher** [open-mpi/ompi#6393]
Thank you for taking the time to submit an issue!

## Details of the problem
Hello everyone
I got a FORTRAN program from my supervisor, but it was work in workstation core i 16,
can I run this code in my single PC, Ubuntu OS,
This program use Openmpi

and what is the steps
I set up open mpi-4.0.0
set the path and then I don't know is it needed to create SSH with other PC or I can read only my processor in My PC.
I think it is very  primitive question
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
openmpi-4.0.0
### Please describe the system on which you are running
Ubuntu 18.10

**Comment by jsquyres** [comment]
Yes, Open MPI can be used with multiple processors on a single machine (e.g., a laptop).  Open MPI does not use ssh in this case (because ssh is an application used to launch processes on remote computers); it just launches as many processes as you tell it on the local machine.

**Comment by engTaher** [comment]
That is great, But how the MPI deal with the processor nodes in my labtop, I mean how to move from node to another. Is it need SSH in this PC, or it needs just hostfile. 
what is the modification should be done for the hosts file, which IP address should one use.
Thanks

**Comment by jsquyres** [comment]
I'm so sorry; I totally missed your reply.

I'm not sure I understand what you're asking.  By "processor nodes in my laptop", do you mean the individual processor cores?  If so, ssh is not needed for that.  Open MPI will just see and use the local processor cores.  ssh is only needed when you start using more than just your individual laptop (e.g., other desktops, laptops, or servers).

You can just `mpirun -np 4 my_mpi_program`, and it will start 4 copies of `my_mpi_program` on your local machine (i.e., `MPI_COMM_WORLD` ranks 0 through 3).

**Comment by jsquyres** [comment]
I'm going to close this for lack of activity.
