### ISSUE TITLE
pml/ucx: data integrity issue

### ISSUE THREAD

**Issue by AboorvaDevarajan** [open-mpi/ompi#6396]
### What version of Open MPI are you using? 
ompi master

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
git clone

### Configuration options

**UCX - branch (v1.5.x)**

`./contrib/configure-release --prefix=/nfs_smpi_ci/abd/src/ucx-install`

**OMPI - branch (master)**

`./configure --prefix=/nfs_smpi_ci/abd/src/ompi-install --with-ucx=/nfs_smpi_ci/abd/src/ucx-install/ --enable-debug`

### Please describe the system on which you are running

* Operating system/version: 

Red Hat Enterprise Linux Server release 7.5 (Maipo)

* Computer hardware: 

Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                160
On-line CPU(s) list:   0-159
Thread(s) per core:    8
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Model:                 1.0 (pvr 004c 0100)
Model name:            POWER8NVL (raw), altivec supported
CPU max MHz:           4023.0000
CPU min MHz:           2061.0000
L1d cache:             64K
L1i cache:             32K
L2 cache:              512K
L3 cache:              8192K
NUMA node0 CPU(s):     0-79
NUMA node1 CPU(s):     80-159

-----------------------------

## Details of the problem

Forcing to use pml ucx exposes a data integrity issue, Here is the test case that fails:
https://gist.github.com/AboorvaDevarajan/efab498afcdf6c71ec8af8d3b589c572

```
c712f6n06$ mpicc test.c -o test

c712f6n06$ mpirun -np 8 -mca pml ucx --mca btl ^vader,tcp,openib -x UCX_NET_DEVICES=mlx5_0:1 ./leakcatch

--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[47895,1],1]) is on host: c712f6n06
  Process 2 ([[47895,1],0]) is on host: c712f6n06
  BTLs attempted: self

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
0
1
2
3
[c712f6n06:19648] 7 more processes have sent help message help-mca-bml-r2.txt / unreachable proc
[c712f6n06:19648] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
4
5
6
7
8
9
ERROR: buf 760 element 0 is 46 should be 248
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 7 in communicator MPI_COMM_WORLD
with errorcode 16.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

As we can see the test aborts with a data integrity issue, when I force and use ob1 pml the test seems to be passing. 

Attaching ompi and ucx config logs,

[ucx_config.log](https://github.com/open-mpi/ompi/files/2874999/ucx_config.log)
[ompi_config.log](https://github.com/open-mpi/ompi/files/2875011/ompi_config.log)

**Comment by hoopoepg** [comment]
@AboorvaDevarajan hi
sorry for late response

unfortunately we can't reproduce your issue.
but could you make some investigations for us?
could you try to add command line parameters to mpirun:
--mca opal_common_ucx_opal_mem_hooks 1 -x UCX_MEM_MMAP_HOOK_MODE=none

thank you

**Comment by hoopoepg** [comment]
@AboorvaDevarajan there is conflict of memory hooks installed by btl uct and pml ucx.
to eliminate it you may exclude btl uct from build, add btl uct to exclusion list (--mca btl ^vader,tcp,openib,uct) or add command line parameters --mca opal_common_ucx_opal_mem_hooks 1 -x UCX_MEM_MMAP_HOOK_MODE=none

@yosefe this is same issue with Bistro we investigated some time ago

**Comment by yosefe** [comment]
@hoopoepg thanks for the analysis. How can we detect such errors? maybe add UCM API for testing malloc hooks, and run it from OMPI late initialization phase, such as add_procs?

**Comment by hoopoepg** [comment]
@yosefe the problem is in components who uses UCX as transport (btl UCT or HCOLL) - they may want to have completed initialization on earlier stages.

here is only one robust solution: force using external (OMPI provided) hooks in OMPI environment, but here could be issue too: in case if UCX is used indirectly (HCOLL case) - it could be problematic to get hooks

**Comment by yosefe** [comment]
@hoopoepg at first step i would like to at least be able to detect such error (e.g that UCX hooks were overwritten) and fail the application in this case.
then we can propose to either disable some BTLs, or use OMPI's hooks

**Comment by AboorvaDevarajan** [comment]
@hoopoepg I tried using the options today to avoid conflicts with the hooks as mentioned 
```--mca opal_common_ucx_opal_mem_hooks 1 -x UCX_MEM_MMAP_HOOK_MODE=none```
I can confirm that it works, did multiple runs and the test case passed.

**Comment by hoopoepg** [comment]
@AboorvaDevarajan glad to see that workaround helped.
we added detection of such issues into UCX master and into OMPI master/4.0

can we close this issue?

**Comment by AboorvaDevarajan** [comment]
Thanks @hoopoepg  sorry for the delay. I was not able to verify the issue with ucx:master/ompi:master
since there are some build issues. 

```
btl_uct_endpoint.c: In function 'mca_btl_uct_endpoint_connect_iface':
btl_uct_endpoint.c:119:5: error: implicit declaration of function 'uct_ep_create_connected' [-Werror=implicit-function-declaration]
     ucs_status = uct_ep_create_connected (tl_context->uct_iface, device_addr, iface_addr, &tl_endpoint->uct_ep);
     ^
```
But however, I was able to manually cherry pick the fix https://github.com/openucx/ucx/pull/3338 to UCX v1.5.1 and verify it, where it precisely shows the warning messages when pml ucx and btl uct are used. 

```
common_ucx.c:149  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
```

so I'm closing this.
