### ISSUE TITLE
Some Intel tests fail in heterogeneous configuration

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#64]
I ran some of the intel tests against OMPI v1.3, r19845 on a heterogeneous cluster.  One node consisted of SPARC and the other node consisted of AMD with both nodes running Solaris.  Both installations of OMPI were configured with --enable-heterogeneous.

I restricted the datatypes being tested to MPI_INT.  I ran the all_tests_no_perf_c list of tests which consists of 239 tests.  Of that group, 232 PASS and 7 FAIL.  This is what an mpirun looked like.

```
mpirun -np 8 -mca btl self,sm,tcp -host burl-ct-v440-0,burl-ct-v40z-0 `pwd`/src/MPI_Abort_c
```

Here is a list of tests that fail.

```
MPI_Allgatherv_c
MPI_Irecv_pack_c
MPI_Recv_init_pack_c
MPI_Recv_pack_c
MPI_Sendrecv_replace_ring_c
MPI_collective_message_c
MPI_collective_overlap_c
```

I have attached the failure from the MPI_Allgatherv_c and the MPI_Recv_pack_c to give an idea of the failure.  

I also did the same set of tests with MPI_FLOAT and the results were the same with the 7 tests failing.  I have not expanded the list beyond that yet.

**Comment by rhc54** [comment]
No longer valid
