### ISSUE TITLE
Need DDT fixes ported to v3.0.x and v3.1.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#6436]
@bosilca @ggouaillardet: Could I impose on you to port the commits from #6295 and #6326 to v3.0.x and v3.1.x?

I ask because we apparently need these to fix #6285 for v3.0.x and v3.1.x.

I tried cherry-picking them, but I run into conflicts, and I'm a bit nervous about trying to sort through this code to get the right resolutions.

FYI: @edgargabriel @ax3l

**Comment by bosilca** [comment]
They are both pending.

**Comment by jsquyres** [comment]
These are now both merged to v3.0.x and v3.1.x.  Closing.
