### ISSUE TITLE
make-authors.pl might fail with a shallow clone

### ISSUE THREAD

**Issue by ggouaillardet** [open-mpi/ompi#6452]
(ran from my own account's) travis failed with the following error message

```
/usr/bin/perl "./contrib/dist/make-authors.pl" --skip-ok --quiet --srcdir="."
New AUTHORS file written.

*** WARNING: The following people had the same email address:
***   Arm, Thananon Patinyasakdikul

*******************************************************************************
*** YOU SHOULD EDIT THE .mailmap FILE TO RESOLVE THESE WARNINGS!
*******************************************************************************
make[1]: *** [AUTHORS] Error 1
```

the root cause is travis uses a shallow clone (e.g. `git clone --depth=50 ...` and an unexpected consequence is a merge commit was not marked as merged any more (and that merge commit had an unexpected author). FWIW, `git clone --depth=51 ...` works fine.

A possible fix is to `git fetch --unshallow` (works with git >= 1.8) either in `travis.yml` before performing `make distcheck`, or even automatically in `make-authors.pl` (or we could _fetch some more commits_ until `make-authors.pl` works.

any thoughts ?

**Comment by bwbarrett** [comment]
Alternatively, given that we no longer use Travis for any of the CI, should we just remove the .travis.yml and finish shutting all that down?

**Comment by jsquyres** [comment]
Yeah, that might be the easiest solution (i.e., remove `.travis.yml`).  If we ever bring it back, we can debug then.

**Comment by awlauria** [comment]
I opened up the quick PR to try and resolve this ticket.

I don't have an environment to test whether the proposed solution actually works.
