### ISSUE TITLE
v4.0.x: ompi_info field for MPI-1 compat symbols in mpi.h?

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#6470]
While reading https://github.com/open-mpi/ompi/pull/6469, I realized that there's no `ompi_info` field indicating whether `mpi.h` includes the MPI-1 compat symbols or not.

We should probably add this.  Should be a trivial thing to add.

It might be specific just to v4.0.x, but *maybe* we might want to add it to master (just hard-coded to "no") for continuity into v5.0.x...?

**Comment by gpaulsen** [comment]
Good idea.  I'll give this a go today.

**Comment by hppritcha** [comment]
@gpaulsen see #6471

**Comment by hppritcha** [comment]
closing as both master and v4.0.x have been updated
