### ISSUE TITLE
Double-lock interlock in pmix-finalize

### ISSUE THREAD

**Issue by abouteiller** [open-mpi/ompi#6472]
## Background information

A bug causing PMIx events to trigger during finalization while cross-holding locks has been resolved in master, but is still present in v4.0.x

master PR: #5975

Severity is not 'blocker' since the use-case to make the error manifest is rather elaborate, but it would still be a stability enhancement to the 4.x series.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

v4.0.x

**Comment by abouteiller** [comment]
Issue is also present in 3.1.x, as well as in the pmix-tools interface.

**Comment by rhc54** [comment]
> as well as in the pmix-tools interface.

Do you mean it is in PMIx itself?

**Comment by abouteiller** [comment]
I mean that the pmix[2,3,4]_tools_fini function in pmix[2,3,4]_client.c has the same code pattern that triggers the bug in pmix_[2,3,4]_finalize

I have not verified that this causes the same problem to arise (but I would expect so) for tools termination.

**Comment by abouteiller** [comment]
The bug is not present in the pmix library itself.

**Comment by abouteiller** [comment]
The bug is **not** present in upstream prrte

**Comment by rhc54** [comment]
Yeah, I wouldn't expect it to be over there as it appears mostly due to the opal/pmix abstraction layer. Thanks for backporting it.

**Comment by abouteiller** [comment]
All PRs have been merged.
