### ISSUE TITLE
MPI_Iprobe segmentation fault in a simple multi-thread send-receive program.

### ISSUE THREAD

**Issue by recolic** [open-mpi/ompi#6475]
Note that I'm not sure that it's a bug in OpenMPI!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

OpenMPI 4.0.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

ArchLinux offical repository: extra/openmpi 4.0.0-1

### Please describe the system on which you are running

* Operating system/version: ArchLinux, Linux 5.0.0-arch1-1-ARCH
* Computer hardware: Intel Core i5-4200H @ 4x 3.4GHz, 15.4GiB RAM
* Network type: localhost

-----------------------------

## Details of the problem

I experienced a strange undefined behavior in MPI_Iprobe. I run the following program with `mpirun -np 4 ./mpi`, sometimes AddressSanitizer reports `free a not malloc-ed address` on `MPI_Iprobe`, sometimes AddressSanitizer reports `SEGV on unknown address 0x000000000000` on `MPI_Barrier`, sometimes it simply hang, sometimes it reports a memory leak.

This is a minimal reproduce:

```c++
// mpicxx -o mpi -std=c++14 -g -fsanitize=address -fno-omit-frame-pointer  mpi.cpp

#include <mpi.h>
#include <stdio.h>

#include <thread>
namespace rlib {
    void mpi_assert(int b) {
        if(b != MPI_SUCCESS)
            throw std::runtime_error("hugs");
    }
}

static inline void move_and_reown(const int n_proc, const int rank) {
    const auto recv_thread_func = [](volatile bool &flagStopThread) {
        while(not flagStopThread) {
            int have_msg_flag = 0;
            MPI_Status stat;
            rlib::mpi_assert(MPI_Iprobe(MPI_ANY_SOURCE, MPI_ANY_TAG, MPI_COMM_WORLD, &have_msg_flag, &stat));
            if(have_msg_flag) {
                double received_msg;
                rlib::mpi_assert(MPI_Recv(&received_msg, 1, MPI_DOUBLE, stat.MPI_SOURCE, stat.MPI_TAG, MPI_COMM_WORLD, &stat));
            }
        }
    };

    volatile bool flag_stop_recv_thread = false;
    std::thread recv_thread(recv_thread_func, std::ref(flag_stop_recv_thread));

    const int new_rank = (rank + 1) % n_proc;

    double packet = 1.1;
    MPI_Status stat;
    rlib::mpi_assert(MPI_Send(&packet, 1, MPI_DOUBLE, new_rank, 7, MPI_COMM_WORLD));


    rlib::mpi_assert(MPI_Barrier(MPI_COMM_WORLD));
    flag_stop_recv_thread = true;
    recv_thread.join();
    printf("%d: recv thread exited.\n", rank);
}

int main(int argc, char **argv) {
    int n_proc, rank;
    MPI_Init(&argc, &argv);
    MPI_Comm_size(MPI_COMM_WORLD, &n_proc);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    printf("nproc=%d, rank=%d\n", n_proc, rank);

    //for (int step = 0; step < 1000; step++) {
        move_and_reown(n_proc, rank);
        printf("%d: Loop success\n", rank);
    //}

    MPI_Finalize();

    return 0;
}
```

Please compile it with command `mpicxx -o mpi -std=c++14 -g -fsanitize=address -fno-omit-frame-pointer  mpi.cpp`, run it with command `mpirun --hostfile hostfile -np 4 ./mpi`, and the content of `hostfile` is `localhost slots=4`

**Comment by ggouaillardet** [comment]
First, you must fix your program and `MPI_Init_thread(&argc, &argc, MPI_THREAD_MULTIPLE, &provided)` instead of `MPI_Init()`. That being said, I am getting errors even after the fix is applied.

**Comment by recolic** [comment]
> First, you must fix your program and `MPI_Init_thread(&argc, &argc, MPI_THREAD_MULTIPLE, &provided)` instead of `MPI_Init()`. That being said, I am getting errors even after the fix is applied.

The problem disappears after fixing the problem with MPI_Init_thread...........

**Comment by jsquyres** [comment]
@ggouaillardet What problems are you running in to?

**Comment by bosilca** [comment]
There are few hundreds of m emory leaks in the initialization, but other than that I can't get the program to fail.
