### ISSUE TITLE
MPI_Info_get failing after MPI_Win_get_info 

### ISSUE THREAD

**Issue by sam6258** [open-mpi/ompi#6506]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v4.0.x branch

### Please describe the system on which you are running

POWER9 ppc64le rhel 7.6

-----------------------------

## Details of the problem

Gist of testcase can be found here: https://gist.github.com/sam6258/997b1695707d47be9c040227bba7b547

The problem here looks like this line is returning NULL, causing the value to not be shown in the info object that we get from MPI_Info_get. https://github.com/open-mpi/ompi/blob/836c80c4421007b16205c98a8159044182eef611/opal/util/info_subscriber.c#L306

`opal_infosubscribe_change_info` looks like it is being called from `MPI_Win_set_info`, but there is no callback associated with the value. 

This appears to fail with a majority of the OSC components (ucx, pt2pt are two that can be used to recreate).

If the test case is modified to use simple `MPI_Info_set`, `MPI_Info_dup`, and then `MPI_Info_get`, things work fine, but the indirection caused by storing the info object on the window seems to be causing problems.

I'm not quite sure how to fix this yet, and am looking for some direction. Appreciate any help you can give. Thanks.

**Comment by ggouaillardet** [comment]
Thanks for the report.

note the program works as you expect with the latest `master` branch.

That being said, from the standard (MPI 3.1, chapter 11 page 416)

> Advice to users. Some info items that an implementation can use when it creates
> a window cannot easily be changed once the window has been created. Thus, an
> implementation may ignore hints issued in this call that it would have accepted in a
> creation call. (End of advice to users.)

so at that stage (I did not check what the code is doing) I am not even sure this is a genuine bug since
per the standard, Open MPI is allowed to ignore a hint set by `MPI_Win_set_info()` and nothing is said about what `MPI_Win_set_info()` nor `MPI_Win_get_info()` should return in that case.

Note if you pass `info_in` to `MPI_Win_allocate()` and do not call `MPI_Win_set_info()`, then `MPI_Win_get_info()` does correctly return the hint in both `master` and `v4.0.x`

@jsquyres @hjelmn any feedback will be appreciated.

**Comment by jsquyres** [comment]
Per MPI 3.0, if those components are not using the `no_locks` info key, it's ok for them not to return it, right?

That being said, I think new / definitive text was put in about info keys and what values must be returned in the MPI 4.0 2018 draft (https://www.mpi-forum.org/docs/drafts/mpi-2018-draft-report.pdf).  @sam6258 Can you check this text and see what it says about info keys/values that must be returned?  That might change what we need to do here.

**Comment by sam6258** [comment]
This test case may be invalid. I found this in the 3.1 standard to support that an implementation does not have to return those values back from MPI_Win_get_info if not used:
> The current setting of all hints actually used by the system related to this window is returned in info_used

I see this statement in the 4.0 draft that seems to also support this case under `MPI_Win_get_info`:
> An MPI implementation is required  to  return  all  hints  that  are  supported  by the implementation and have default values specified

I think the heart of this issue is what does it mean to "ignore hints". The way I'm looking at that, I can see two meanings.

1) ignore hints means to acknowledge a hint was given and choose not to act on a particular hint if an optimization or special codepath is not available.
2) ignore hints means not to acknowledge a hint at all.

In the v4.0.x code, it currently looks like we have case 2, but as @ggouaillardet mentioned, it looks like case 1 is the interpretation in master. Previously, I have seen case 1 in the 3.x branches as well. 

So while not required, an implementation may return back those values still, correct?
If this is the case, then I would expect a user must be prepared to handle case 2, but an implementation may choose to support case 1.

**Comment by jsquyres** [comment]
"hints actually used by the system" was the problematic phrase from <= v3.1.  It wasn't well-defined at all.

I think the v4.0 draft text is more clear: if we support `no_locks` *at all*, then we need to return it in the info.  I'm kinda guessing that we only need to do this on master (i.e., where we'll ultimately be MPI-4.0-compliant); I don't think we need to do this on the v4.0 OMPI branch.

Meaning:
* I think the v4.0.x branch reflects MPI-3.1 behavior
* From what @ggouaillardet and you describe, it sounds like master reflects (upcoming) MPI-4.0 behavior (which, in this case, is backwards compatible with MPI-3.1)

Right?

**Comment by sam6258** [comment]
I believe that sounds correct, and from our discussion, I've modified IBM osc component to follow the standard a bit better. I'll close the issue for now unless people want to discuss more, but sounds like we are on the same page. Thanks!
