### ISSUE TITLE
ORTE regex function parsing segfault when hostnames contain UUID or large numbers

### ISSUE THREAD

**Issue by alichnewsky** [open-mpi/ompi#6507]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

v4.0.0 release tarball.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

compiled from tarball using gcc 4.9.2 on centos.
```
 ./configure --prefix=$installdir --with-pic
```

### Please describe the system on which you are running

* Operating system/version: 
CentOS containers on Google Cloud Platform "container optimized OS" host VM (meaning chromeOS with linux 4.14. )
* Computer hardware: 
Intel Skylake CPU
* Network type: 
ethernet

-----------------------------

## Details of the problem

my  machines have hostnames that do contain uuids, or numbers > 2^31 -1 .

This results occasional segmentation fault  when launching MPI jobs, no matter if the machine file contains host names or ip addresses.

I am using hostnames like `az-469791030863870-4180085177944178270-abcd` resulting into orte regexp such as `az-[15:3213060094]-4180085177944178270-abcd,[2:10].128.1.57`

I was able to gather the the following call stack:
```
#0  in raise () from /lib64/libc.so.6
#1   in abort () from /lib64/libc.so.6
#2  in free_check () from /lib64/libc.so.6
#3  in regex_parse_node_range () from /third-party/lib/libopen-rte.so.40
#4  in orte_regx_base_extract_node_names () from /third-party/lib/libopen-rte.so.40
#5  in orte_regx_base_nidmap_parse () from /third-party/lib/libopen-rte.so.40
#6  in orte_ess_base_orted_setup () from /third-party/lib/libopen-rte.so.40
#7  in rte_init () from /third-party/lib/openmpi/mca_ess_env.so
#8  in orte_init () from /third-party/lib/libopen-rte.so.40
#9  in orte_daemon () from /third-party/lib/libopen-rte.so.40
#10 in main ()
```

I did not find a standalone unit test for this module, but something along these lines would demonstrate it easily.

```
#include <string.h>
#include <orte/mca/regx/base/base.h>

int main(int arg, char** argv) {

 char** n = { NULL };
 char*** names = &n;
 char* regexp = "az-[15:3213060094]-4180085177944178270-abcd,[2:10].128.1.57";

 int ret = orte_regx_base_extract_node_names( regexp, &names);

 return 0;
}
```

**Comment by rhc54** [comment]
Yes, we are aware of the problem - the fix has already been committed to master and I am working (as I type) on the port to the v4.0.1 branch. Sorry for the problem.

**Comment by alichnewsky** [comment]
A patch for the v4.0.x branch is [straightforward](https://github.com/alichnewsky/ompi/commit/23ebf8e36ad203db8f74a75b6fa466e6aa512fd3)  (use `strtoull()` in `orte/mca/regx/base/regx_base_default_fns.c` to fill `size_t` variables, not `atoi()` or `strtol()`  )....

**Comment by alichnewsky** [comment]
if you are going to back port the fix, I won't figure out the proper incantation to get my local IP lawyer to let me submit it ;-)

**Comment by rhc54** [comment]
Yeah, we went a different way and dumped the regex method in favor of compression. Kept hitting too many corner-cases where it failed.

**Comment by awlauria** [comment]
Closing as fixed based on comments.
