### ISSUE TITLE
MPI_Irecv+MPI_Isend random slow when using openib RDMA RoCE

### ISSUE THREAD

**Issue by LiweiPeng** [open-mpi/ompi#6514]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? 
This problem was found on both OpenMPI 3.1.3, 3.1.1. 

### Describe how Open MPI was installed 
OpenMPI was built from source code.

### Please describe the system on which you are running

* Operating system/version: CentOS 7.4. 3 nodes are used, 1 process/node.
* Computer hardware: PC
* Network type: Mellanox CX4-LX, RDMA RoCE v2

-----------------------------

## Details of the problem
In my source code (see below), I used MPI_Irecv(), MPI_Isend(), MPI_Waitall() to perform an all gather operation. 

- When running this code using TCP, the program runs smoothly and no problem was found. 
- When running using openib on RDMA RoCE, if using 2 nodes (1 process/node), it works great.
- When running on 3 or 4 nodes (1 process/node), 90% of the time the program runs at expected speed. 10% of the time it is about 10 times slower than normal.

Although the same thing can be achieved using other MPI APIs, my application is designed using these APIs for now.

command used
```shell
shell$ mpirun --machinefile m.txt  --map-by ppr:1:node --mca btl openib,self,vader --mca btl_openib_cpc_include rdmacm --mca btl_openib_rroce_enable 1  --mca btl_openib_receive_queues P,256,256:S,128,256,192,128:S,2048,1024,1008,64:S,12288,1024,1008,64:S,131072,1024,1008,64 --mca btl_openib_cuda_async_recv false mytest
```
```code
#include <mpi.h>
#include <stdlib.h>

const size_t kDataSize = 1024 * 1024 * 16;
const int kLoop = 50;

void BenchAllgather() {
  int numprocs = 0;
  int rank = 0;
  MPI_Comm_size(MPI_COMM_WORLD, &numprocs);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);

  float* send_cpu = (float *)malloc(kDataSize*sizeof(float));
  float* recv_cpu = (float *)malloc(kDataSize*sizeof(float));

  MPI_Request* request = new MPI_Request[numprocs*2];

  for (int i = 0; i < kLoop; ++i) {
    for (int k = 0; k < numprocs; ++k) {
       MPI_Irecv(recv_cpu + k * (kDataSize / numprocs),
                 kDataSize / numprocs,
                 MPI_FLOAT,
                 k,
                 0,
                 MPI_COMM_WORLD,
                 &(request[k]));
     }

    for (int k = 0; k < numprocs; ++k) {
      MPI_Isend(send_cpu + k * (kDataSize) / numprocs,
                kDataSize / numprocs,
                MPI_FLOAT,
                k,
                0,
                MPI_COMM_WORLD,
                &(request[k+numprocs]));
    }

    MPI_Waitall(numprocs*2, request, MPI_STATUSES_IGNORE);
    MPI_Barrier(MPI_COMM_WORLD);
  }

  free(send_cpu);
  free(recv_cpu);
  delete [] request;
}

int main(int argc, char** argv) {
  MPI_Init(&argc, &argv);
  BenchAllgather();
  MPI_Finalize();
  return 0;
}
```

**Comment by jsquyres** [comment]
Is your network configured for lossless operation?  RoCE v2 requires lossless to be configured.  If it is not, you can experience drops, and the RoCE v2 wire protocol will perform sluggishly.

**Comment by LiweiPeng** [comment]
@jsquyres Yes, my network is configured to be lossless RoCE. On the same cluster, I also ran many MPI benchmarks, like IMB benchmark, OSU benchmarks. These benchmark performance numbers all look good. But none of these benchmarks have the same API design like what I used above.

**Comment by jsquyres** [comment]
I only mention it because seeing wild performance fluctuations like this are typically caused by mis-configured no-drop.

Have you tried using UCX?  Mellanox no longer supports the openib BTL -- it's deprecated in Open MPI v4.0 and will likely disappear in Open MPI v5.0.

**Comment by LiweiPeng** [comment]
I didn't try UCX. Since it is the future, I can give it a try .

**Comment by LiweiPeng** [comment]
this turned out to be network switch configuration issues, which caused unstable network. It is not related to openmpi. so close it.
