### ISSUE TITLE
make use of new info keys for MPI window creation

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#652]
MPI Forum ticket [369](https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/369) adds info keys to potentially allow for some optimizations in the implementation of ```MPI_Win_create``` and friends.
Open MPI would probably benefit from optimizations that make use of these info keys.

**Comment by jsquyres** [comment]
@hjelmn This is done already, isn't it?

**Comment by jsquyres** [comment]
@hjelmn Is this already done?

**Comment by hjelmn** [comment]
I have a pull request that updates the MPI_Win_get_info code to set these keys. The enhanced one-sided code is the only component that sets any of the new flags.

**Comment by jsquyres** [comment]
Can you cite the PR here on this issue so that we have the cross-link?

**Comment by hppritcha** [comment]
closing this.
