### ISSUE TITLE
btl_tcp_links broken?

### ISSUE THREAD

**Issue by asylvest** [open-mpi/ompi#6521]
## Background information
I'm trying to use the `btl_tcp_links` option which does not appear to be working

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
4.0.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
From the source tarball; vanilla configure / make with no special configure options

### Please describe the system on which you are running

* Operating system/version: RHEL 7
* Computer hardware: AWS C5 instances (Intel)
* Network type: TCP

-----------------------------

## Details of the problem
According to the FAQ at https://www.open-mpi.org/faq/?category=tcp#tcp-multi-links, `btl_tcp_links` is supposed to be working in 4.0.0, but I'm not seeing any performance difference when using it.

I'm using 2 x c5.18xlarge instances in AWS which have 25 Gbps connectivity via TCP (note these are not the c5n instances which have EFA).  Using `iperf3` with the `-P` option to drive multiple ports, I achieve over 24 Gbps when communicating between two instances.

I have a trivial MPI benchmark which uses one rank per host and sends 10 GB from one rank to the other via `MPI_Send()` / `MPI_Recv()`.  Running like this:
```
mpirun -N 1 --bind-to none --hostfile hosts.txt /path/to/my/application
```
I get around 9 Gbps.

My understanding is I can do the equivalent of `iperf3`'s `-P` flag by using the `--mca btl_tcp_links` flag with OpenMPI.  I attempted to do this via:
```
mpirun --mca btl_tcp_links 4 -N 1 --bind-to none --hostfile hosts.txt /path/to/my/application
```
However, I still get the same 9 Gbps; I tried changing the value to 2 or 3 which also made no difference.

Is there an additional flag or anything else I need to set?  Is there a way I can run in a verbose mode to tell if multiple ports really are open?  Or is something still not working properly in 4.0.0?  I do have some use cases where I have a small number of hosts that need to transfer a large amount of data so I would benefit from getting this working.

Thanks for the help.

**Comment by bwbarrett** [comment]
In my testing, `btl_tcp_links` appears to be working with the OSU bandwidth benchmarks.  I can drive 10 Gbps with no options and ~20 Gbps with (lots of) tuning.  That being said, the `btl_tcp_links` implementation leaves something to be desired and won't work for all situations.  It *only* helps with large message bandwidth; eager messages are always sent down the "0th" TCP connection.  The eager cross-over is 64 KiB so, without seeing your application, my assumption is that you're sending smaller messages.  Also, if your application is not bandwidth bound, you won't see any performance difference.

@bosilca, do you remember why you chose to set the latency and bandwidth for the "extra" connections between any two ranks to 1/2 that of the 0th connection?

**Comment by asylvest** [comment]
Thanks for the info @bwbarrett.  I have my test application on another system so I can't just cut and paste it here but it was extremely simple and is sending large messages.  In pseudocode, it boiled down to:
```
start timer
for (size_t ii = 0; ii < 10; ++ii)
{
    if (rank == 0)
        MPI_Send() // 2 GB of MPI_BYTE to rank 1
    else
        MPI_Recv() // 2 GB of MPI_BYTE from rank 0
}
stop timer
print bandwidth
```

So, each `MPI_Send() / MPI_Recv()` was 2 GB.  Based on your note above, I would have expected this to benefit from `btl_tcp_links`.

**Comment by bosilca** [comment]
`btl_tcp_links` set to anything smaller than 4 seldomly works. Going for more than 5 seems to somehow fix the issue and the expected number of connections is created (according to lsof on the compute nodes). I guess a potential short terms solution is to use a number of links larger than 5.

However, at least on my hardware (not AWS) increasing the number of links seems to negatively impact performance, the more links the less performance we get. With 1 single link I'm up to 19gbps (consistently), but as I increase the number of links the performance becomes lesser and less stable (at 6 it varies between 16Gbps and 7 Gbps). Please keep in mind that the behavior on my hardware is certainly not representative of AWS.

Regarding @bwbarrett question we do not stripe the small messages across multiple interface in order to avoid out-of-sequence messages on the receiver (and it provides a real performance boost for multi-threaded applications).

**Comment by asylvest** [comment]
OK this is strange.  I just ran some tests, measured performance and observed open ports with `lsof`, and match what you said.  With `btl_tcp_links` <= 4, I only see one port get opened.  Starting at 5, it seems to honor the requested number of ports.  However, my aggregate bandwidth doesn't increase at anywhere near the rate that it does with `iperf3` (with iperf3, just letting it use 2-3 links is sufficient to get me to 24 Gbps).  With OMPI, with 1 link, I get 9 Gbps; with 5 links I get 10 Gbps .  Setting it to a ridiculous value like 40 gets me up to 13 Gbps (and `lsof` confirms 40 ports are opened); performance starts to go down to 11 Gbps with 80 ports.

Are there other OMPI-specific TCP network settings I should be adjusting to improve performance?  I know in general fine-tuning network performance is non-trivial, but since out of the box `iperf3` is able to nearly max out the bandwidth, it seems like these must be application-specific settings that can be tweaked rather than messing with MTU sizes, etc.
