### ISSUE TITLE
OPAL ERROR： Not initialized in file pmix3x_client.c at line 113 An error occurred in MPI_Init_thread

### ISSUE THREAD

**Issue by ascenoputing** [open-mpi/ompi#6533]
### What version of Open MPI are you using? 
openmpi -3.1.2,  openmpi-4.0.0

### Describe how Open MPI was installed 

from tarball 

### Please describe the system on which you are running

* Operating system/version: Ubuntu 16
* Computer hardware:  i7 Core, nvidia 1080
* Network type: 

-----------------------------

## Details of the problem
I am running the examples  get the error

```
OPAL ERROR： Not initialized in file pmix3x_client.c at line 113 An error occurred in MPI_Init_thread 
Not initialized in file pmix3x_client.c at line 113
[server13:13286] OPAL ERROR: Not initialized in file pmix3x_client.c at line 113
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[server13:13279] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[server13:13286] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[server13:13278] OPAL ERROR: Not initialized in file pmix3x_client.c at line 113
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[server13:13278] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[server13:13277] OPAL ERROR: Not initialized in file pmix3x_client.c at line 113
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[server13:13277] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
```

***EDIT:*** Added verbatim block to make it more readable

**Comment by ascenoputing** [comment]
What version of Open MPI are you using?
openmpi -3.1.2, openmpi-4.0.0

Describe how Open MPI was installed
from tarball

Please describe the system on which you are running
Operating system/version: Ubuntu 16
Computer hardware: i7 Core, nvidia 1080
Network type:

**Comment by ascenoputing** [comment]
**What version of Open MPI are you using?**
openmpi -3.1.2, openmpi-4.0.0

**Describe how Open MPI was installed**
from tarball

**Please describe the system on which you are running**
Operating system/version: Ubuntu 16
Computer hardware: i7 Core, nvidia 1080
Network type:

**Comment by jsquyres** [comment]
Can you be a bit more specific about what you are doing and how you are invoking Open MPI?

E.g., are you trying to run an MPI program on a single node?  Across multiple nodes?  ...?

**Comment by winnettR** [comment]
I just had a similar problem reported on clients' systems after an openmpi update. The problem disappeared when the version of mpirun used to launch the job was changed to match the openmpi used to build the application (v4.0.1).

**Comment by jsquyres** [comment]
It's been 4 weeks without followup information from the original poster, so I'm going to go ahead and close this issue.
