### ISSUE TITLE
Security issue with libevent included in openmpi 3.1.3 and libevent 2.0.22

### ISSUE THREAD

**Issue by mwheinz** [open-mpi/ompi#6537]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

OpenMPI 2.1.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

As part of the OPA IFS package

### Please describe the system on which you are running

* Operating system/version: RHEL 7.x, possibly others.
* Computer hardware: Intel x86_64
* Network type: OPA

-----------------------------

## Details of the problem

This is more of a heads up than anything else - a security scanning tool has reported that the version of OpenMPI included with current IFS releases is using a version of libevent with known vulnerabilities.

The good news is that the vulnerabilities don't appear to be in code that OpenMPI actually uses, and that newer versions of OpenMPI do not have this issue.

We're currently evaluating the possibility of patching the IFS provided version of OpenMPI to remove the vulnerable code.

**Comment by jsquyres** [comment]
Thanks for the heads up.  Let us know what you come up with in terms of patches.

**Comment by ggouaillardet** [comment]
@mwheinz If you are packaging Open MPI, you might want to consider using external components for `hwloc`, `libevent` and `pmix` and let your distro (e.g. RedHat) fix the security issues for you.
