### ISSUE TITLE
Shared memory not getting cleaned up

### ISSUE THREAD

**Issue by aingerson** [open-mpi/ompi#6547]
Using Open MPI v4.0.0 compiled from source on RHEL7.4

-----------------------------

## Details of the problem
I've already let @rhc54 know about this, but figured I'd add this here for record keeping/tracking.

On our CI testing of libfabric + Open MPI, I've noticed a lot of "vader_segments" in /dev/shm that are accumulating from all our testing. I think this is related to issue #5798 and was fixed with commit c076be52afc19b1a8c1884ff7e66b04122c7ab23 but I don't think this patch was pulled into 4.0.x. If this was fixed in a different version, which version and sorry about the spam!

**Comment by jsquyres** [comment]
@gpaulsen @hppritcha FYI.  This may end up being a dup of #6565, but #6565 has much more detail.

**Comment by jsquyres** [comment]
@aingerson Thanks for the research to find c076be5.  I've put this information on #6565; even though that one was filed later, it has additional detail.  So I'm going to close this one as a dup -- let's keep following on #6565.

**Comment by leofang** [comment]
Also dup: #6322
