### ISSUE TITLE
need to verify that Open MPI RMA compliant with active target synchronization

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#655]
The MPI 3.0 errata tickets [437](https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/437), [434](https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/434), [435](https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/435) clarify behavior of active target synchronization for shared memory windows.

Need to check that Open MPI is complying with these errata items.

**Comment by hjelmn** [comment]
Cool, will do.

**Comment by jsquyres** [comment]
@hjelmn Any progress?

**Comment by jsquyres** [comment]
@hjelmn is this done?

**Comment by hppritcha** [comment]
closing this.
