### ISSUE TITLE
Possibly, incorrect MPI_Type_indexed behavior with zero blockLenght

### ISSUE THREAD

**Issue by vspetrov** [open-mpi/ompi#6575]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
master

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
compiled from source, git clone open-mpi/ompi/master

### Please describe the system on which you are running

* Operating system/version: RHEL 7.4 
* Computer hardware: x86
* Network type: n/a

-----------------------------

## Details of the problem
Consider the test case:
```
#include <mpi.h>
#include <stdio.h>

int main (int argc, char **argv) {
    int rank, size;
    MPI_Datatype dtype;
    int dt_count = 1;
    int pBlockLength[1] = {0};
    int pDisps[1] = {0};
    MPI_Aint lb, extent;

    MPI_Init(&argc, &argv);

    MPI_Type_indexed(dt_count, pBlockLength, pDisps, MPI_DOUBLE_COMPLEX, &dtype);
    MPI_Type_commit(&dtype);
    MPI_Type_get_extent(dtype, &lb, &extent);

    printf("lb: %llu, extent %llu\n",
           (long long unsigned)lb, (long long unsigned)extent);
    MPI_Finalize();
}
```
Compile and run on a single node:
```
mpicc mpi_create_indexed.c -g -o mci
mpirun -np 1 ./mci
lb: 9223372036854775807, extent 1
```

In this test user creates an Indexed dtype with count = 1 and pBlockLength[0] = 0;
The resulting dtype has huge LB  and extent = 1. I would expect this dtype to have LB=UB=TRUE_UB=TRUE_LB=EXTENT=0. 

1. Do i understand correctly that the test is MPI spec compliant ? From the spec i read that the entries of pBlockLength have to be non-negative. So all looks legit. 
2. Do you agree that the resulting dtype must have zero extent and lb,ub?
3. MPICH handles this case this way: [mpich_type_indexed](https://github.com/pmodels/mpich/blob/66218a1a6ab2f58e6fd1c5eef3968aa6ac32d76d/src/mpi/datatype/type_indexed.c#L158) So, the check if at least one entry of pBlockLength is non-zero and only then create the dtype otherwise mpich would return an empty type.

One more notice: i think that similar fallback logic in OMPI (for example, [here](https://github.com/open-mpi/ompi/blob/163bbd4f047df738bc96870cc8458e3c674febea/ompi/datatype/ompi_datatype_create_indexed.c#L81)) is incorrect. We create an empty dtype with:
```
ompi_datatype_add( *newType, &ompi_mpi_datatype_null.dt, 0, 0, 0);
```
which calls
```
opal_datatype_add( &pdtBase->super, &pdtAdd->super, count, disp, extent );
```
but if the count is set to 0 (like in this case) opal_datatype_add would just leave the newType uninitialized https://github.com/open-mpi/ompi/blob/98afc838aa53da88cba339f6dcbab256806a5745/opal/datatype/opal_datatype_add.c#L119.

**Comment by vspetrov** [comment]
Same applies for vector type (blength can be zero, and the fallback returns not initialized dtype).

**Comment by ggouaillardet** [comment]
@bosilca can you please comment ?

**Comment by bosilca** [comment]
The example is correct, and OMPI outcome obviously wrong. The reason behind this is some old cruft from the time where the LB and UB markers were not deprecated. A clean solution could be started from
```diff
diff --git a/ompi/datatype/ompi_datatype_create_indexed.c b/ompi/datatype/ompi_datatype_create_indexed.c
index 457efb1e6f..97b0c36a02 100644
--- a/ompi/datatype/ompi_datatype_create_indexed.c
+++ b/ompi/datatype/ompi_datatype_create_indexed.c
@@ -39,19 +39,23 @@ int32_t ompi_datatype_create_indexed( int count, const int* pBlockLength, const
     ptrdiff_t extent, disp, endat;
     size_t dLength;

-    if( 0 == count ) {
+    /* ignore all cases that lead to an empty type */
+    ompi_datatype_type_size(oldType, &dLength);
+    for( i = 0; (i < count) && (0 == pBlockLength[i]); i++ );
+    if( (i == count) || (0 == dLength) ) {
         return ompi_datatype_duplicate( &ompi_mpi_datatype_null.dt, newType);
     }

-    disp = pDisp[0];
-    dLength = pBlockLength[0];
+    disp = pDisp[i];
+    dLength = pBlockLength[i];
     endat = disp + dLength;
     ompi_datatype_type_extent( oldType, &extent );

     pdt = ompi_datatype_create( count * (2 + oldType->super.desc.used) );
-    for( i = 1; i < count; i++ ) {
-        if( endat == pDisp[i] ) {
-            /* contiguous with the previsious */
+    for( i += 1; i < count; i++ ) {
+        if( 0 == pBlockLength[i] )  /* ignore empty length */
+            continue;
+        if( endat == pDisp[i] ) { /* contiguous with the previsious */
             dLength += pBlockLength[i];
             endat += pBlockLength[i];
         } else {
```
by applying the same logic to all datatype creation functions.
