### ISSUE TITLE
time consuming by mpirun invoke

### ISSUE THREAD

**Issue by tingweiwu** [open-mpi/ompi#6579]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
`openmpi-3.1.2`

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
```
# Install Open MPI
 mkdir /tmp/openmpi && \
    cd /tmp/openmpi && \
    wget https://www.open-mpi.org/software/ompi/v3.1/downloads/openmpi-3.1.2.tar.gz && \
    tar zxf openmpi-3.1.2.tar.gz && \
    cd openmpi-3.1.2 && \
    ./configure --enable-orterun-prefix-by-default && \
    make -j $(nproc) all && \
    make install && \
    ldconfig && \
    rm -rf /tmp/openmpi
```

### Please describe the system on which you are running

* Operating system/version: 
 `ubuntu16.04`
* Computer hardware: 
 `V100GPU+InfiniBand  `
* Network type: 
 `docker cni networker  `
-----------------------------

## Details of the problem
I run mpirun in the container 
**CASEA: with container cni network**
```
mpirun -x NCCL_DEBUG=INFO python tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --variable_update horovod
```
and  following env is set in the pod(container)
```
OMPI_MCA_plm_rsh_agent:          /etc/mpi/kubexec.sh
OMPI_MCA_orte_default_hostfile:  /etc/mpi/hostfile
```
and the output as follwing
```
+ /opt/kube/kubectl exec mpijob-horovod-2-worker-0 -- /bin/sh -c+      PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "379584512" -mca ess_base_vpid 1 -mca ess_base_num_procs "3" -mca orte_node_regex "mpijob-horovod-[1:2]-launcher-ncdwv,mpijob-horovod-[1:2]-worker-0,mpijob-horovod-[1:2]-worker-1@0(3)" -mca orte_hnp_uri "379584512.0;tcp://192.168.60.207:59751" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca pmix "^s1,s2,cray,isolated"
POD_NAME=mpijob-horovod-2-worker-1
+ shift
+ /opt/kube/kubectl exec mpijob-horovod-2-worker-1 -- /bin/sh -c     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "379584512" -mca ess_base_vpid 2 -mca ess_base_num_procs "3" -mca orte_node_regex "mpijob-horovod-[1:2]-launcher-ncdwv,mpijob-horovod-[1:2]-worker-0,mpijob-horovod-[1:2]-worker-1@0(3)" -mca orte_hnp_uri "379584512.0;tcp://192.168.60.207:59751" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca pmix "^s1,s2,cray,isolated"
begin to training at 2019-03-29 09:19:00

```

**CASEB: with container host-network**
run with pod host-network
the cmd in the worker pod is
```
/usr/sbin/sshd -p 12345; sleep infinity
```

and cmd in launcher pod is , IP1 and IP2 is the host IP where worker pods runnig
```
-  mpirun -np 16 -H IP1:8,IP2:8 -bind-to none -map-by slot -x NCCL_SOCKET_IFNAME=ib0 -mca btl_tcp_if_exclude docker0,tunl0,lo -x NCCL_DEBUG=ERROR -x LD_LIBRARY_PATH -mca plm_rsh_args "-p 12345 -vvvv" python tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --variable_update horovod
```

and  the costtime of mpirun invoke
caseA(mpijob)： 1min42s
caseB(host-network) ： 2s

do you have any suggestion about this difference?

I have post the issue here https://github.com/kubeflow/mpi-operator/issues/103 
he wonder if container networking is confusing existing code paths and causing this when figure out the network topology at the begining

**Comment by ggouaillardet** [comment]
First, you have to manually make sure `kubexec.sh` works at normal speed
(if not, that indicates at least one non Open MPI issue, such as kubernetes or (reverse)DNS

Then I suggest you try with a non MPI program first, for example
```
time mpirun <mpirun args> true
```
if caseA is still much slower than caseB, then you can
```
mpirun --mca oob_tcp_base_verbose 10 <mpirun args> true
```
and hopefully, you will notice some timeout on a/some interface(s), and you can simply only include the "good" one(s)
```
mpirun --mca oob_tcp_if_include 192.168.0.0/24 <mpirun args> true
```

if that fix your problem you can try your MPI app, and you might as well have to select the same interfaces but for MPI TCP communications
```
mpirun --mca oob_tcp_if_include 192.168.0.0/24 <mpirun args> --mca btl_tcp_if_include 192.168.0.0/24 <your MPI app>
```

**Comment by tingweiwu** [comment]
@ggouaillardet  quite appreciate for your attention and suggestion. I will try this

**Comment by jsquyres** [comment]
Haven't heard back on this in many months; I assume the issue is resolved.  Closing.
