### ISSUE TITLE
MPI_THREAD_MULTIPLE and UCX

### ISSUE THREAD

**Issue by nevion** [open-mpi/ompi#6593]
Since UCX is the way of the future and openib was... problematic wrt MPI_THREAD_MULTIPLE, what is the status and plan for MPI_THREAD_MULTIPLE and UCX?

~~It seems like it's still unsupported~~
https://github.com/open-mpi/ompi/blob/07e5c54a4605ea28ef57288db4f57622e597417b/ompi/mca/pml/ucx/pml_ucx.c#L282-L288 

~~What would it take to get it there and what plans are in the works?~~

~~Is there any infiniband based path that works with MPI_THREAD_MULTIPLE besides ipoib with openmpi?~~

Do any other MPI implementations have support for UCX and MPI_THREAD_MULTIPLE?

Is UCX [ready for it internally](https://github.com/openucx/ucx/wiki/UCT-Design#thread-safety) wrt infiniband or mlnx5 transports?  Cursory review of the uct code seems like it's thought about, at least.

I used to use openib w/ threads, but at some point I started getting hangs in software using it, like https://github.com/open-mpi/ompi/issues/4863 - so I moved back to ipiob . And then there's the [roadmap](https://github.com/open-mpi/ompi/wiki/5.0.x-FeatureList)  - so it's somewhat understood the state of openib, but it's a bit of a trying time to have no performant MPI_THREAD_MULTIPLE options and nothing materializing.

**Comment by yosefe** [comment]
@nevion need to configure ucx with multi thread support:
`$ucx_dir/contrib/configure-release --enabble-mt`
then, the check `(attr.thread_mode != UCS_THREAD_MODE_MULTI)` will be evaluated fo `0`

**Comment by nevion** [comment]
@yosefe ah, I didn't glean from the comment block that it was a build time related issue.  I thought I tried that, but I will try more carefully.

I'm still interested in hearing how tested the threading support is with openmpi and ucx, though.

**Comment by yosefe** [comment]
@nevion we are constantly running MTT with OpenMPI+UCX and multi-threaded tests.

**Comment by jsquyres** [comment]
@yosefe Can you guys add an FAQ item about this on the OMPI web site?  That would make this kind of question Google-able.

Thanks!
