### ISSUE TITLE
MacOS pmix divide by zero on master

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#6595]
This issue is just to track / mirror the corresponding PMIx issue (because it has evidenced itself in MPI runs on MacOS): https://github.com/pmix/pmix/issues/1210

Short version:

* Open MPI master only (no release branches)
* MacOS only
* A divide-by-zero error is occurring when attempting to use mpirun to launch apps (e.g., `mpirun -np 2 ring_c`)

All followup is occurring on https://github.com/pmix/pmix/issues/1210.

**Comment by rhc54** [comment]
This has been fixed now in both OMPI and PMIx.
