### ISSUE TITLE
segfault in orte_util_pass_node_info when running 2 mpi processes on the same node

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [open-mpi/ompi#6606]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

I'm on master at this commit:
```
bash-4.2$ git log --oneline | head
c80a842 Merge pull request #6602 from edgargabriel/topic/io_array_refactor
```

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

```
  Configure command line: '--prefix=/ccs/home/akshayvenk/ompi/build' '--enable-mpirun-prefix-by-default' '--with-cuda=/sw/summit/cuda/9.2.148' '--with-ucx=/ccs/home/akshayvenk/ucx-github/build' '--enable-mpi-fortran=no'
```

### Please describe the system on which you are running

  Summit

-----------------------------

## Details of the problem

I'm trying to run `hostname` on 2 cores on the same node. Seems like mpirun tries to run the executable on login node even though the hostfile has just the compute node with slots, max-slots information. Am I doing something incorrectly? This used to work on a previous version of ompi (a few weeks old at least).

```
bash-4.2$ cat hostfile
h41n10 slots=2 max-slots=2

bash-4.2$ mpirun -np 2 -hostfile hostfile hostname
[login1:116976] *** Process received signal ***
[login1:116976] Signal: Segmentation fault (11)
[login1:116976] Signal code: Address not mapped (1)
[login1:116976] Failing at address: 0x10
[login1:116976] [ 0] [0x2000000504d8]
[login1:116976] [ 1] /ccs/home/akshayvenk/ompi/build/lib/libopen-rte.so.0(orte_util_pass_node_info+0xfe8)[0x2000000ba9b8]
[login1:116976] [ 2] /ccs/home/akshayvenk/ompi/build/lib/libopen-rte.so.0(orte_plm_base_daemons_reported+0x29c)[0x2000000fbdec]
[login1:116976] [ 3] /ccs/home/akshayvenk/ompi/build/lib/libopen-pal.so.0(opal_libevent2022_event_base_loop+0xcd0)[0x200000215790]
[login1:116976] [ 4] mpirun[0x10001278]
[login1:116976] [ 5] mpirun[0x10000e08]
[login1:116976] [ 6] /usr/lib64/libc.so.6(+0x25100)[0x200000505100]
[login1:116976] [ 7] /usr/lib64/libc.so.6(__libc_start_main+0xc4)[0x2000005052f4]
[login1:116976] *** End of error message ***
Segmentation fault (core dumped)
```
I seem to be able to trick mpirun with the following to have the desired result though:
```
bash-4.2$ cat hostfile
h41n11 slots=0 max-slots=0
h41n10 slots=2 max-slots=2

bash-4.2$ mpirun -np 2 -hostfile hostfile hostname
h41n10
h41n10
```

cc @jsquyres

**Comment by jsquyres** [comment]
Do you know the relation of this @edgargabriel branch to master?

I note that there have been a bunch of changes with regards to PMIX and friends on master in the not-distance past.

**Comment by rhc54** [comment]
Let's close this - things have changed so much that this is no longer relevant
