### ISSUE TITLE
make-authors.pl does not work correctly when run in a git submodule.

### ISSUE THREAD

**Issue by mwheinz** [open-mpi/ompi#6614]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

3.1.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone, then locally cloned as a git submodule.

### Please describe the system on which you are running

* Operating system/version: N/A
* Computer hardware: N/A
* Network type: N/A

-----------------------------

## Details of the problem

make-authors.pl checks that .git exists and is a directory before getting the git log - but when a repo is checked out as a submodule of a larger repository, .git is not a directory, it's just a text file. This can cause make-authors.pl to terminate inappropriately.

```

**Comment by mwheinz** [comment]
The problem is that the script wants .git to be a directory. This is not true in the case where ompi is being built as a git submodule. The patch is nearly trivial, change "if [ -d .git ]" to "if [ -e .git ]".

**Comment by jsquyres** [comment]
Oh ya, can't say we even thought of that use case.  😮 

Your fix sounds pretty trivial.  What is `.git` in the submodule if it's not a directory -- is it a sym link or something?

Want to submit a PR?  😄

**Comment by ggouaillardet** [comment]
If I use worktree (this is not a submodule as reported), `.git` is a one ASCII line.
I cloned in `/home/gilles/src/ompi-master`, and then `git worktree add /home/gilles/src/ompi-pmix ompi-pmix`. `.git` contains
```
gitdir: /home/gilles/src/ompi-master/.git/worktrees/ompi-pmix
```

**Comment by mwheinz** [comment]
> Your fix sounds pretty trivial. What is `.git` in the submodule if it's not a directory -- is it a sym link or something?

It's  text file containing a relative filepath to the "real" .git directory. For example, "../../.git/modules/repos/wfr-ompi"

**Comment by jsquyres** [comment]
This is now merged everywhere.
