### ISSUE TITLE
Cherry pick ob1 fixes to release branches

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#6633]
Need to cherry-pick the commits from the PRs listed below to v2.x, v3.0.x, v3.1.x, and v4.0.x:

* #6556 (e630046a4b82bc01379fb055af4c0e414c2a8e8f): pml/ob1: fixed local handle sent during PUT control message
* #6621 (a16cf0e4dd6df4dea820fecedd5920df632935b8): Fix the leak of fragments for persistent sends

Note that a16cf0e4dd6df4dea820fecedd5920df632935b8 contains use of `OPAL_THREAD_SUB_FETCH_SIZE_T` and `OPAL_THREAD_ADD_FETCH_SIZE_T`, neither of which exist before v4.0.x.  Porting to the older branches is therefore a bit complex -- I took a whack at it and was not confident enough in what I finally managed to get to compile.

**Comment by jsquyres** [comment]
FYI: @EmmanuelBRELLE

**Comment by bosilca** [comment]
I'm working on a fix for the PUT issue. If there is no rush to push this in, let's wait for few days until I'm done.

**Comment by jsquyres** [comment]
@bosilca Any updates?  We're looking at the possibility of 4.0.2 in the "near" future.

**Comment by bosilca** [comment]
Not enough hours in a day. I'm on the datatype issue right now, so I put this one aside. I might get to it before the end of the week.

**Comment by gpaulsen** [comment]
@bosilca Any updates? We're looking at the possibility of 4.0.2 in the "near" future.

**Comment by angelhd1999** [comment]
Same problem here, the only "solution" I have found is to do:

`export OMPI_MCA_btl_vader_backing_directory=/tmp`

before the _mpirun_ execution.

**Comment by jsquyres** [comment]
`mpirun --mca btl_vader_backing_directory /tmp ...` should be equivalent.  You can also set MCA params in a file -- see https://www.open-mpi.org/faq/?category=tuning#setting-mca-params.

**Comment by gpaulsen** [comment]
PR #6634 cherry-picks these two fixes to v4.0.x branch.
Removing the Target: v4.0.x label to reflect that.

**Comment by gpaulsen** [comment]
@jsquyres Have these fixes been backported to v3.1.x and v3.0.x?  Can we close this Issue?

**Comment by awlauria** [comment]
I think this can be closed?

**Comment by awlauria** [comment]
Closing - this went into the 4.0 series and is in master. 3.0 is closed as far as I know. If someone disagrees, please reopen.
