### ISSUE TITLE
MPI_Comm_accept/connect hangs

### ISSUE THREAD

**Issue by leofang** [open-mpi/ompi#6642]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

v1.10.2, v3.1.3, v3.1.4, v4.0.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

v1 was unknown; v3 and v4 were built from officially released sources

### Please describe the system on which you are running

v1 was unknown; v3 and v4:
- Operating system/version: Debian GNU/Linux 8 (jessie)
- Computer hardware: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz + 512 GB RAM
- Network type: tcp/ip

-----------------------------

## Details of the problem

My colleague and I were testing the server/client communication with the canonical example (see, e.g., https://github.com/bjpop/haskell-mpi/tree/master/test/examples/clientserver or P.393 of the [MPI-3.1 Standard](https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf)). I also tested this example in Python using mpi4py. All tests were done on single nodes (no inter-node communication).

We first start the server process in one terminal, and then either copy the port information manually to the client process in another terminal, or use `MPI_Publish_name()`/`MPI_Lookup_name()` if the `omni-server` daemon has been launched. With all versions of Open MPI that we tested, **except for v4.0.1** the connection hangs at `MPI_Comm_accept()`/`MPI_Comm_connect()`; v4.0.1 works as expected.

In my tests I launched the MPI processes with `mpirun -n 1`.

Attn: @bsmind

**Comment by rhc54** [comment]
That sounds right - we know it was broken for some time. No plans to do anything with the v1.10 series. Backporting a fix to the v3.x series might be possible, but I don't know if/when someone might do it. Probably best to stick with the v4.x series for such things.

**Comment by leofang** [comment]
@rhc54 thank you very much for your quick reply! It's reassuring to learn that this bug is known. Please feel free to close this issue if it's not going to be addressed in older versions (<v4). Thanks again.
