### ISSUE TITLE
Errors using contexts in OSHMEM 4.1.0

### ISSUE THREAD

**Issue by lariesen** [open-mpi/ompi#6682]
We're encountering problems using contexts in OSHMEM 4.1.0. on a small Infiniband 4 machine. Codes without contexts work.  As soon as we introduce contexts we start to get errors.

We installed HPC-X 2.3.0 and rebuilt UCX and then OpenMPI.

UCX build:
./configure --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --without-java --prefix=$HPCX_HOME/ucx --enable-mt

ompi build:
export LD_LIBRARY_PATH=$HPCX_HOME/hcoll/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$HPCX_HOME/sharp/lib:$LD_LIBRARY_PATH
./configure --prefix=$HPCX_HOME/ompi --with-platform=contrib/platform/mellanox/optimized --with-hcoll=$HPCX_HOME/hcoll --with-ucx=$HPCX_HOME/ucx --enable-oshmem

In one case if we:

shmem_ctx_create(...)
(do work with context)
shmem_barrier_all()

The barrier hangs.  If instead we

shmem_ctx_create()
(do work with context)
shmem_ctx_destroy()
shmem_barrier_all()

then the barrier completes.

In a very simple test:

shmem_ctx_create()
shmem_barrier_all()

we get error message from the barrier but it completes.  If you destroy the context before the barrier - no error messages.

We have another app which is crashing in shmem_ctx_long_atomic_fetch_add().  I wrote a simple reproducer which is copied below.  Depending on how we run it we either crash in the fetch_add or get error messages from a subsequent barrier.  PEs that don't crash in fetch_add show correct output values after the fetch_add.  Any ideas?

/*
* Run with 2 PEs, 1 ppn, fetch_add succeeds and get error in last barrier
*
[c01:77010:0:77010] rc_verbs_iface.c:63   FATAL: send completion with error: transport retry counter exceeded
*
* Run with more than 1 ppn, get error in fetch_add for some PEs.
*
[1557515773.667071] [c02:58872:0]       mm_posix.c:449  UCX  ERROR Error returned from open in attach. Permission denied. File name is: /proc/58875/fd/75
[1557515773.667112] [c02:58872:0]          mm_ep.c:76   UCX  ERROR failed to connect to remote peer with mm. remote mm_id: 252866199552606
*
*/
#include <stdlib.h>
#include <iostream>
#include <shmem.h>

long fa_val;

int main(int argc, char *argv[]) {
  shmem_init();
  int mype = shmem_my_pe();
  int npes = shmem_n_pes();
  fa_val = mype;

  shmem_ctx_t ctx_id;
  int rc = shmem_ctx_create(0, &ctx_id);
  if (rc) {
    std::cerr << "error creating context" << std::endl;
    exit(1);
  }
  shmem_barrier_all();

  long add_val = 100;
  int other_pe = (mype + 1) % npes;
  std::cerr << "GO FETCH_ADD " << mype << " -> " << other_pe << std::endl;
  long got_val = shmem_ctx_long_atomic_fetch_add(ctx_id, &fa_val, add_val, other_pe);
  std::cerr << "DONE FETCH_ADD " << mype << " -> " << other_pe << std::endl;

  shmem_ctx_destroy(ctx_id);
  std::cerr << "GO BARRIER " << mype << std::endl;
  shmem_barrier_all();
  std::cerr << "DONE BARRIER " << mype << std::endl;

  std::cout << mype << " DONE got from " << other_pe << ": " << got_val << std::endl;
  std::cout << mype << " DONE my fetched/added value now " << fa_val << std::endl;
  shmem_finalize();
}

**Comment by lriesen** [comment]
I don't have permission to assign anyone to this issue.  Could you add the three suggested by Ralph Castain below to this issue?  Thanks.


_Hi Lee Ann

I fear so - and assign it to @hoopoepg , @brminich and @yosefe

Ralph

> On May 17, 2019, at 11:14 AM, Riesen, Lee Ann via users

**Comment by jladd-mlnx** [comment]
I assigned it to myself, which means my team is working it in priority order. We are taking it and it will be fixed as soon as possible.

**Comment by janjust** [comment]
@lariesen , I have a hard time reproducing this issue , can you try with hpcx-v2.4?
Alternatively, can you please share the exact commits found in your v2.3 version and info about the system that you are using: ofed version, devices, etc.

**Comment by lariesen** [comment]
I just installed HPC-X 2.4 and re-ran our previously failing tests and they pass.  So this is good.  I looked at the version numbers for OpenSHMEM in shmem.h for HPC-X 2.3 and HPC-X 2.4.  It looks 2.4.0 reverted back to an older version of OSHMEM.  Is that the case?  Do you know why? Just curious.

>grep VERSION ./2.3.0/ompi/include/shmem.h
#define OSHMEM_MAJOR_VERSION 4
#define OSHMEM_MINOR_VERSION 1
#define OSHMEM_RELEASE_VERSION 0

>grep VERSION ./2.4.0/ompi/include/shmem.h
#define OSHMEM_MAJOR_VERSION 4
#define OSHMEM_MINOR_VERSION 0
#define OSHMEM_RELEASE_VERSION 2

**Comment by artpol84** [comment]
@lariesen this was a versioning mistake in OMPI (see https://github.com/open-mpi/ompi/commit/0c3e76ec908444c51c2ef774da4cd89ecce49f99).
HPCX 2.3 picked it up accidentally.

**Comment by janjust** [comment]
@lariesen , if the above solution is satisfactory, please close the issue.

**Comment by lariesen** [comment]
Closing because problems can not be reproduced with latest HPC-X package
