### ISSUE TITLE
 int32_t versions of shmem_wait_until() shmem_test() expect 64-bit values

### ISSUE THREAD

**Issue by sam6258** [open-mpi/ompi#6712]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

I have reproduced this issue in OMPI master and v4.0.x.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Built from source.

### Please describe the system on which you are running

* Operating system/version: RHEL 7.6
* Computer hardware: POWER9 ppc64le
* Network type: N/A (Issue reproducible on a single node)

-----------------------------

## Details of the problem

Unit tests (`cxx_test_shmem_wait_until.cpp` and `cxx_test_shmem_test.cpp`) from this bucket are failing: https://github.com/Sandia-OpenSHMEM/SOS/tree/master/test/unit

I have a proposed fix coming and will link the PR to this issue.

```> oshrun -n 2 cxx_test_shmem_wait_until
PE 1 received incorrect value with TEST_SHMEM_WAIT_UNTIL(int32_t)
PE 1 received incorrect value with TEST_SHMEM_WAIT_UNTIL(uint32_t)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
oshrun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[54404,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by artpol84** [comment]
Thanks, @sam6258.
Looking forward to the fix.
