### ISSUE TITLE
I got wrong results in  MPI_SUM MPI_C_FLOAT_COMPLEX

### ISSUE THREAD

**Issue by NicolasYL** [open-mpi/ompi#6752]
Thank you for taking the time to submit an issue!

#Background information

#What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

v2.1

### Please describe the system on which you are running

* Operating system/version: win10

-----------------------------

# Details of the problem
code:
```c++
complex<float> a, mpi_result;
split(new_map, nullptr, &a);
cout << iRank << " : " << a << endl;
MPI_Barrier(MPI_COMM_WORLD);
MPI_Reduce(&a, &mpi_result, 1, MPI_C_FLOAT_COMPLEX, MPI_SUM, 0, MPI_COMM_WORLD);`
```

result is:

![image](https://user-images.githubusercontent.com/47812418/59193509-8b5ecd00-8bb8-11e9-8bb1-8d57f9d7e257.png)

I want to know what's the difference between **0**  and **-9.31323e-10**

**Comment by jsquyres** [comment]
By definition, the difference between 0 and -9.31323e-10 is 9.31323e-10.  😄

Remember that 9.3e-10 is 0.0000000093.  That's a very, very small number -- very close to 0.

Also recall that MPI is doing a series of floating point operations, and that single-precision floating point numbers (and computers in general) only have limited precision.  Check out articles like https://en.wikipedia.org/wiki/Round-off_error for a longer explanation.

If you're expecting the results to be (something, 0.0), the fact that you got (something, 9.3e-10) might actually be "close enough".
