### ISSUE TITLE
FPE due to int rounding in cost_calc of common_ompio_aggregators.c

### ISSUE THREAD

**Issue by haraldkl** [open-mpi/ompi#6758]
### Please describe the system on which you are running
* Operating system/version: Arch Linux
* Computer hardware: Intel x86
* Network type: Single node

-----------------------------

## Details of the problem
When compiling our application with floating point error checking activated, the resulting executable linked against OpenMPI fails with an floating point exception when calling MPI_File_set_view.
Debugging this revealed that this is due to the cost_calc function in ompi/mca/common/ompio/common_ompio_aggregators.c.
There a real division is assigned to an intermediate variable c, which is then again assigned to the real variable n_as. If the division happens to be smaller than 1, this can become 0. As n_as is subsequently used in another division, we end up with a division by 0 in this case.

e79ecd4 fixes the issue for me, by avoiding the intermediate assignment to an integer variable. Please let me know whether that would be suitable for a pull-request, or if it needs some other kind of fixing.

**Comment by edgargabriel** [comment]
@haraldkl please feel free to file a pr with this patch, it looks good to me. If possible, having a reproducer for the bug would also be helpful, since I could add it to our regular testsuite to avoid that we break it later accidentally.

**Comment by jsquyres** [comment]
@haraldkl @edgargabriel Can you add "target" labels to this issue so that we know what release branches are affected?  Thanks.

**Comment by edgargabriel** [comment]
@jsquyres sure, will do. This part of the code is only in master and 4.0.x

**Comment by haraldkl** [comment]
Here is a (probably not minimal Fortran) program to reproduce the problem:
[crash_mpiio.txt](https://github.com/open-mpi/ompi/files/3287098/crash_mpiio.txt)

To reproduce: compile with floating point exceptions active and run with 5 processes (or some other count that does not divide 16 and is larger than 4), i.e. with gfortran:
`$ mpif90 -ffpe-trap=invalid,zero,overflow crash_mpiio.f90`
`$ mpiexec -np 5 ./a.out`

**Comment by hppritcha** [comment]
#6774 fixes this in 4.0.x
