### ISSUE TITLE
segfault in PMIx when using `--oversubscribe`

### ISSUE THREAD

**Issue by angainor** [open-mpi/ompi#6761]
I compiled OpenMPI 4.0.1 with internal PMIx, using GCC version 8.3.0 (Ubuntu 8.3.0-6ubuntu1~18.10). No interconnect / UCX libs, pure local installation. Then, I compile the simplest program with `mpicc -g test.c`

```
#include <mpi.h>
int main(int argc, char *argv[])
{
    MPI_Init(&argc, &argv);
    MPI_Finalize();
}
```

I run with `mpirun --oversubscribe -np 64 ./test`. When using `-np 31` and more I see the following segfault

```
 *** Process received signal ***
 Signal: Segmentation fault (11)
 Signal code: Address not mapped (1)
 Failing at address: 0x7ff61dd13008
 [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x41100)[0x7ff61db56100]
 [ 1] /home/angainor/work/institution/usit/prace_6ip/install/lib/pmix/mca_gds_ds21.so(pmix_gds_ds21_lock_init+0x6b4)[0x7ff61cc887cc]
 [ 2] /home/angainor/work/institution/usit/prace_6ip/install/lib/libmca_common_dstore.so.1(pmix_common_dstor_init+0x983)[0x7ff61ca55655]
 [ 3] /home/angainor/work/institution/usit/prace_6ip/install/lib/pmix/mca_gds_ds21.so(+0x23f4)[0x7ff61cc873f4]
 [ 4] /home/angainor/work/institution/usit/prace_6ip/install/lib/openmpi/mca_pmix_pmix3x.so(OPAL_MCA_PMIX3X_pmix_gds_base_select+0x1a6)[0x7ff61cc1fe0f]
 [ 5] /home/angainor/work/institution/usit/prace_6ip/install/lib/openmpi/mca_pmix_pmix3x.so(OPAL_MCA_PMIX3X_pmix_rte_init+0x11cc)[0x7ff61cbcf6f2]
 [ 6] /home/angainor/work/institution/usit/prace_6ip/install/lib/openmpi/mca_pmix_pmix3x.so(OPAL_MCA_PMIX3X_PMIx_Init+0x2f4)[0x7ff61cb70b5b]
 [ 7] /home/angainor/work/institution/usit/prace_6ip/install/lib/openmpi/mca_pmix_pmix3x.so(pmix3x_client_init+0x346)[0x7ff61cb219f4]
 [ 8] /home/angainor/work/institution/usit/prace_6ip/install/lib/openmpi/mca_ess_pmi.so(+0x29e5)[0x7ff61d4919e5]
 [ 9] /home/angainor/work/institution/usit/prace_6ip/install/lib/libopen-rte.so.40(orte_init+0x350)[0x7ff61da0a369]
 [10] /home/angainor/work/institution/usit/prace_6ip/install/lib/libmpi.so.40(ompi_mpi_init+0x428)[0x7ff61dd80838]
 [11] /home/angainor/work/institution/usit/prace_6ip/install/lib/libmpi.so.40(MPI_Init+0x8e)[0x7ff61ddcfe73]
 [12] ./commbench.x(+0x1167)[0x5588e6f9e167]
 [13] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7ff61db3909b]
 [14] ./commbench.x(+0x108a)[0x5588e6f9e08a]
 *** End of error message ***
```
@rhc54, do you have any ideas? I haven't found anything, but is this maybe a known problem? 

Thanks for any help!

**Comment by rhc54** [comment]
I believe we have seen this before, but I don't recall the status of it. @artpol84 @karasevb Do you have any insights?

IIRC, the immediate fix was to add one of the following two envar values to your environment:

* PMIX_MCA_gds=^ds21

* PMIX_MCA_gds=hash

I'd try these in order as using solely the hash will impact your memory footprint a bit (depending on scale of the procs/node)

**Comment by artpol84** [comment]
@rch54
I think the issue with ds21 we had was addressed in https://github.com/pmix/pmix/pull/1156.
And there are refs to the ports to 2.2 and 3.1

**Comment by artpol84** [comment]
@angainor is there a way to get more insights?
Backtrace in GDB with exact line would be a good starting point.

**Comment by artpol84** [comment]
I just noticed oversubscribed specifics of your case.
@karasevb please try to reproduce.

**Comment by rhc54** [comment]
@angainor Also might be worth testing it against the current head of the v3.1.x branch of the repo. As @artpol84 pointed out, there was a commit that might be related and has been added to that branch.

**Comment by angainor** [comment]
@rhc54 @artpol84 Yepp, I tested against the 3.1 branch, and it works now without problems! Thanks a lot!
