### ISSUE TITLE
Deadlock on sequential calls of MPI_Barrier 

### ISSUE THREAD

**Issue by MSDandrea** [open-mpi/ompi#6772]
Hello folks, while debbuging my application I stumbled at a weird behavior of MPI_Barrier.

My program during some executions entered in deadlock when  MPI_Barrier was called consecutively, for more information see the _Details of the problem_ section.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

Version 4.0.1 (latest at the time).

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Pacman package manager

### Please describe the system on which you are running

* Operating system/version:
```shell
$ uname -a
Linux Laptop 5.1.9-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 11 16:18:09 UTC 2019 x86_64 GNU/Linux
``` 
* Computer hardware: 
```shell
$ cat /proc/cpuinfo 
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
stepping        : 9
microcode       : 0x21
cpu MHz         : 1197.262
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds
bogomips        : 5190.10
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

```
    same for processors 1,2 and 3.
    4GB of RAM.
* Network type: 
all process are running locally 

-----------------------------

## Details of the problem

While debugging my code in search of why a MPI_Recv in a thread wasn't being spawned I wrote two consecutive `MPI_Barrier(MPI_COMM_WORLD); `, one at the main function and another in a function called by main.

In some runs this code would deadlock, so i attached a GDB through CLion to each process so I could see where each process would be stuck.

Rank 0:
![image](https://user-images.githubusercontent.com/13471887/59986805-b1e82380-960e-11e9-9382-b0a24ba78a4a.png)

![image](https://user-images.githubusercontent.com/13471887/59986824-c9271100-960e-11e9-9030-9ff4ca56a3cb.png)

Rank 1:
![image](https://user-images.githubusercontent.com/13471887/59986862-f378ce80-960e-11e9-9682-d7f39245db99.png)

![image](https://user-images.githubusercontent.com/13471887/59986870-fb387300-960e-11e9-9548-be86b3894f56.png)
   

My question is if this is a Bug, or if I'm doing something wrong.
Thanks in advance.

**Comment by ggouaillardet** [comment]
can you please post a reproducer ? it is virtually impossible to tell whether the bug is in Open MPI or in your code (e.g. not all processes call `MPI_Barrier()` when they should.
you might also want to try MPICH or a derivative.
If both MPI implementations have your app hang, then there is a huge probability the bug is not in the MPI library.

**Comment by MSDandrea** [comment]
Sorry for the delay. It was a bug in my code, I noticed later that I was using MPI_Init instead of MPI_Init_thread, after I changed to MPI_Init_thread the deadlocks stopped occurring. 

Thanks.
