### ISSUE TITLE
ugni btl fails some threadsafe tests.

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#682]
ugni periodically fails in some of the thread-tests-1.1 using longer messages.

**Comment by jsquyres** [comment]
@hppritcha is this a dup of #662?

**Comment by jsquyres** [comment]
Umm... no it's not. #662 is about vader, not ugni. Duh!

**Comment by hppritcha** [comment]
unfortunately not, well it might be, but xpmem and ugni have different
registration caches (the cray udreg stuff).
At any rate, not clear its a dup.


2015-06-29 14:59 GMT-06:00 Jeff Squyres <notifications@github.com>:

**Comment by hppritcha** [comment]
May get to this in a future v2.x release.  Depends a lot on adoption of OFI MTL and related components going forward for Cray XC systems.  The OFI GNI provider is abundantly thread-safe and may be a better route for **robust** support of MPI_THREAD_MULTIPLE going forward.

**Comment by hppritcha** [comment]
Closing this issue.
