### ISSUE TITLE
error on Mac OS X with Fortran MPI

### ISSUE THREAD

**Issue by ahaichen** [open-mpi/ompi#6827]
I am trying to run FORTRAN with MPI on my Mac. It goes fine with one core. But with more than 1 core, there will be always an error 

Program received signal SIGABRT: Process abort signal.

The code is just initialized and finalized the MPI. Thanks a lot. 

##----------------------------------------------
Program fortran_test
USE MPI
IMPLICIT NONE

  integer err,my_rank,ierr,p

  call MPI_Init(ierr)
  call MPI_Comm_rank(MPI_COMM_WORLD, my_rank, ierr)
  call MPI_Comm_size(MPI_COMM_WORLD, p, ierr)
 
  ! do nothing 

  call MPI_Finalize(ierr)
END
##----------------------------------------------

## Background information---------------------
OS: macOS Mojave
Open MPI: 4.0.1, installed from source
ompi_info:
mca_base_component_repository_open: unable to open mca_io_romio314:  9): Symbol not found: _ompi_mpi_finalized

**Comment by edgargabriel** [comment]
You are pulling in mca_io_romio314, which is actually not available in the 4.0.x release. The romio version in the 4.0.x release is romio321  Did you by any chance overwrite an existing Open MP installation without removing the directory first? This might lead to having a romio314 module from a previous installation (e.g. OpenMPI 3.1.x) , and that could lead to the problem that you observed.

**Comment by ahaichen** [comment]
Thanks for your reply. I install the new version when I got this problem on Fortran. So do you mean if I clean up and reinstall the openmpi, it will be fine? Thanks.

**Comment by edgargabriel** [comment]
I would suspect so.

**Comment by ahaichen** [comment]
Sure. Thanks. I will try it.

**Comment by jsquyres** [comment]
Haven't heard from this user in a few months, so I'm closing the issue.
