### ISSUE TITLE
openmpi-3.1.1 np=256 ppn=128  UCX_TLS=rc fail

### ISSUE THREAD

**Issue by ivyJchen** [open-mpi/ompi#6854]
Thank you for taking the time to submit an issue!

## Background information
I am running into problems across 2 machines with openmpi-3.1.1 by set   **UCX_TLS=rc** flag. but with openmpi4.0 ，it is ok。

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

openmpi v3.1.1  
ucx：1.6.0
knem：1.1.3.90mlnx1
xpmem：0.2
hcoll：v4.3.2711 (9353efc)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
./configure prefix=/home/openmpi/openmpi_gcc7.3.0/ompi3.1.1_debug
                          --with-knem  --with-xpmem   --with-ucx  --with-hcoll
                          --enable-orterun-prefix-by-default  --enable-debug

### Please describe the system on which you are running

* Operating system/version: 
centos7.6  4.14.0-115.el7a.0.1.aarch64
* Computer hardware: 
aarch64-unknown-linux-gnu

* Network type: 
infiniband (mlx5)
MLNX_OFED_LINUX-4.6-1.0.1.1-rhel7.6alternate-aarch64-ext.iso
-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:

when I run the shell with openmpi3.1.1 
[root@host50 openmpi]# mpirun --allow-run-as-root -np 256 --hostfile hosts    -x coll_hcoll_enable=1 -x HCOLL_MAIN_IB=mlx5_0:1 -x UCX_TLS=rc  /ssd/centos7.6/osu-micro-benchmarks-5.4.3/mpi/collective/osu_allreduce
Failed
            the file: hosts
            host50 slots=128
            host51 slots=128
I got the infomaition:
[host50:10887] pml_ucx.c:118 Error: Failed to receive UCX worker address: Not found (-13)
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  PML add procs failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
[host50:10887] *** An error occurred in MPI_Init
[host50:10887] *** reported by process [440139777,122]
[host50:10887] *** on a NULL communicator
[host50:10887] *** Unknown error
[host50:10887] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[host50:10887] ***    and potentially your MPI job)
[host50:10874] pml_ucx.c:118 Error: Failed to receive UCX worker address: Not found (-13)
[host50:10818] pml_ucx.c:118 Error: Failed to receive UCX worker address: Not found (-13)
[host50:10838] pml_ucx.c:118 Error: Failed to receive UCX worker address: Not found (-13)
[host50:10847] pml_ucx.c:118 Error: Failed to receive UCX worker address: Not found (-13)
[host50:10861] pml_ucx.c:118 Error: Failed to receive UCX worker address: Not found (-13)
[host50:10915] pml_ucx.c:118 Error: Failed to receive UCX worker address: Not found (-13)
[host50:10925] pml_ucx.c:118 Error: Failed to receive UCX worker address: Not found (-13)
[1564475752.425597] [host54:51632:0]          ib_md.c:1930 UCX  ERROR ibv_open_device(mlx5_0) failed: Cannot allocate memory
[1564475752.425793] [host54:51632:0]    ucp_context.c:871  UCX  ERROR No usable transports/devices, asked rc on all devices
[host50:09390] 127 more processes have sent help message help-mpi-btl-openib.txt / error in device init
[host50:09390] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[host50:09390] 7 more processes have sent help message help-mpi-runtime.txt / mpi_init:startup:internal-failure
[host50:09390] 7 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal unknown handle
-------------------------------------------------------------------------------------------
when I ran the  next cmd：
shell: mpirun --allow-run-as-root -np 160 --hostfile hosts_80_80   -x coll_hcoll_enable=1 -x HCOLL_MAIN_IB=mlx5_0:1 -x UCX_TLS=rc  /ssd/centos7.6/osu-micro-benchmarks-5.4.3/mpi/collective/osu_allreduce
the file hosts_80_80
		host50 slots=80
		host51 slots=80
it  got success .
-----------------------------------------------------------------------------------------
when I run the shell with openmpi4.0,it was ok. 
[root@host50 openmpi]# mpirun --allow-run-as-root -np 256 --hostfile hosts    -x coll_hcoll_enable=1 -x HCOLL_MAIN_IB=mlx5_0:1 -x UCX_TLS=rc  /ssd/centos7.6/osu-micro-benchmarks-5.4.3/mpi/collective/osu_allreduce

**Comment by yosefe** [comment]
@ivyJchen pls try to increase device BAR size by mlxconfig tool to allow more contexts (requires reboot):
```
sudo mst start
sudo mlxconfig -d /dev/mst/mt4119_pciconf0 -y s PF_LOG_BAR_SIZE=8
```
NOTE: 'mt4119_pciconf0' below should be replaced by another name according to the device model on your machine, for example mt4115_pciconf0 or mt4117_pciconf0.

**Comment by ivyJchen** [comment]
ibv_devinfo -v | grep ctx
Failed to open device
        max_device_ctx:                 508

**Comment by ivyJchen** [comment]
@yosefe Yossi thanks for answer 。by the way ，what is the default SIZE of the mlxconfig  PF_LOG_BAR_SIZE . and how to see the config.

**Comment by yosefe** [comment]
default is 5:
```
$ sudo mlxconfig -d /dev/mst/mt4119_pciconf0 q|grep PF_LOG_BAR_SIZE
         PF_LOG_BAR_SIZE                     5    
```

**Comment by ivyJchen** [comment]
@yosefe  thanks very much . it solved my problem

**Comment by viniciusferrao** [comment]
Any workaround if I'm not using Mellanox OFED distribution? mlxconfig is not available.

**Comment by yosefe** [comment]
@viniciusferrao can you try building mlxconfig tool from https://github.com/Mellanox/mstflint?
