### ISSUE TITLE
Fortran MPI_FILE_GET_POSITION bug

### ISSUE THREAD

**Issue by wkliao** [open-mpi/ompi#6858]
Fortran test program ompi/mca/io/romio321/romio/test/fmisc.f.in
fails when calling MPI function MPI_FILE_GET_POSITION.

I tested it with the master branch and 4.0.1 release, both built with romio and without romio.
Note the Fortran file is created after running configure and available in BUILD_DIR/ompi/mca/io/romio321/romio/test/fmisc.f

The same test program passes when compiled with MPICH.
I checked MPI standard about the function MPI_FILE_GET_POSITION and
the value returned by MPICH is correct.

**Comment by edgargabriel** [comment]
Thanks for the bug report, I will look into it.

**Comment by gpaulsen** [comment]
@edgargabriel Can we close this issue now?

**Comment by edgargabriel** [comment]
Sorry for my silence on this. I could make create a patch for 3.1, the bug is also in the 3.0.x and 3.1.x series, it is really a question to the release managers whether they would like to have that fix.

**Comment by jsquyres** [comment]
@edgargabriel How big of a fix is this?

**Comment by edgargabriel** [comment]
@jsquyres the fix itself is very localized to one file, and only really affects a special case (fixing the calculations for moving the file pointer to the end of the file in the case where the actual end of the file offset is however not part of your file view).

**Comment by jsquyres** [comment]
If it's nice and small like this, and you don't mind, we'd take fixes like this for v3.0.x and v3.1.x.  👍

**Comment by edgargabriel** [comment]
ok, will do, give me a day or two for creating the pr's

**Comment by gpaulsen** [comment]
I think has been resolved on all release branches.  Closing.
