### ISSUE TITLE
ibm test failing 

### ISSUE THREAD

**Issue by DebRez** [open-mpi/ompi#6859]
Since the pull request #6811 was merged into ompi master I get the following error when tests are compiling:

/usr/bin/ld: op_usempif08.o: in function `somewhat_less_':
scratch/TestGet_IBM/ompi-tests/ibm/collective/op_usempif08.F90:68: undefined reference to `mpi _f08_types_mp_ompi_datatype_op_ne_'
/usr/bin/ld: op_usempif08.o: in function `MAIN__':
scratch/TestGet_IBM/ompi-tests/ibm/collective/op_usempif08.F90:172: undefined reference to `mpi_f08_types_mp_ompi_op_op_ne_'
/usr/bin/ld: link errors found, deleting executable `op_usempif08'
make[2]: *** [Makefile:2618: op_usempif08] Error 1

Open MPI was installed using the MTT python client, from https://download.open-mpi.org/nightly/open-mpi/master

This error is happening on Cori at NERSC, Fog at LANL and Trinitite at LANL. All very different systems.

**Comment by ggouaillardet** [comment]
Thanks for the report, this has been fixed in #6861
