### ISSUE TITLE
Card detection issue with RHEL 7.7 (kernel 3.10.0-1062.el7.x86_64)

### ISSUE THREAD

**Issue by ksheumaker** [open-mpi/ompi#6881]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

Tried releases v3.0.4 and v3.1.4

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

compiled from source

### Please describe the system on which you are running

* Operating system/version:  RHEL 7.7 kernel 3.10.0-1062.el7.x86_64
* Computer hardware:  Intel skylake systems
* Network type: Mellanox EDR

-----------------------------

## Details of the problem

When starting any MPI job I get the following error in my jobs output:
```shell
[node01.cluster:122172] 5 more processes have sent help message help-mpi-btl-openib.txt / no device params found
[node01.cluster:122172] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[node01.cluster:122172] 2 more processes have sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
````

dmesg on the nodes provides this erorr:
```shell
[  347.271231] mlx5_core 0000:18:00.0 ib0: "orted" wants to know my dev_id. Should it look at dev_port instead? See Documentation/ABI/testing/sysfs-class-net for more info.
```

I have a very similar issue with MVAPICH2 2.3.1

```shell
[node01.cluster:mpi_rank_0][mv2_get_hca_type] **********************WARNING***********************
[node01.cluster:mpi_rank_0][mv2_get_hca_type] Failed to automatically detect the HCA architecture.
[node01.cluster:mpi_rank_0][mv2_get_hca_type] This may lead to subpar communication performance.
[node01.cluster:mpi_rank_0][mv2_get_hca_type] ****************************************************
```

It seems there was some kind of API change for detecting the IB cards?

**Comment by yosefe** [comment]
@ksheumaker which HCA is installed on the system?
can yous pls compile OpenMPI 4.0.1 release with UCX support as described in: https://github.com/openucx/ucx/wiki/OpenMPI-and-OpenSHMEM-installation-with-UCX. UCX is the best way to utilize Mellanox HCAs and is up-to-date with latest devices IDs.

**Comment by ksheumaker** [comment]
The HCA is MCX555A-ECAT.  I've used these exact model of cards w/ OpenMPI 3.X on other systems without issue.  The only change on this one is the newer RHEL 7.7 kernel.

I will try 4.0.1 w/ UCX and report back.

**Comment by yosefe** [comment]
@ksheumaker do you have MLNX_OFED on the system, or are you using rdma-core library from RHEL 7.7?

**Comment by ksheumaker** [comment]
rdma-core from 7.7

**Comment by ksheumaker** [comment]
With the git versions of ucx and ompi (as referenced in the document), I do not see any errors from my job output, however this message is still present on the nodes via dmesg

```shell
[ 1489.582845] mlx5_core 0000:18:00.0 ib0: "orted" wants to know my dev_id. Should it look at dev_port instead? See Documentation/ABI/testing/sysfs-class-net for more info.
```

**Comment by yosefe** [comment]
@ksheumaker perhaps, adding "-mca btl self" to the mpirun command line could help. It would disable btl/openib, which may be the reason for these messages.

**Comment by jsquyres** [comment]
@yosefe A better way to disable the openib BTL is to supply `--mca btl ^openib` (which explicitly disables the openib BTL, vs. explicitly enabling a different BTL).

**Comment by ksheumaker** [comment]
Thanks everyone for the help.  I found out the issue, these machines have intel i40e ethernet cards, and the i40iw iwarp driver was being loaded automatically.  It appears that was the culprit, if I forced openmpi to the mlx5 device then everything worked as expected.

**Comment by alexschroeter** [comment]
@ksheumaker how did you do force it to the mlx5 device?
