### ISSUE TITLE
How can I verify that I'm actually using RoCE with UCX?

### ISSUE THREAD

**Issue by marmistrz** [open-mpi/ompi#6883]
### OpenMPI version
3.1.4
I didn't use 4.x because of the outdated version of hwloc in Ubuntu repositories

### How Open MPI was installed
From source tarball, `./configure --with-hwloc --enable-openib-rdmacm --with-verbs --with-ucx`

### System

* Operating system/version: Ubuntu 18.04
* Computer hardware: 
* Network type: Ethernet

-----------------------------

## Details of the problem

I'm trying to run an MPI application over Ethernet using Soft RoCE (RXE). The kernel used is 4.15.0-55-generic, with `rdma-core` 17.1 (from the Ubuntu repositories). At first I tried using it with the openib backend (to no avail), I switched to OpenUCX. I've done some preliminary benchmarks on the go and now I'd like to reproduce the tests once more, to verify my results. Here is where it gets tricky.

1. Only some of my tests are affected by RXE configuration, which makes me unsure if the applications are actually using RDMA properly. The only thing I can do is to pass `--mca btl_base_verbose 100 --mca pml_ucx_verbose 100` which makes it clear that UCX is used, but not whether or not RDMA is employed
2. I'm unable to disable the pml ucx backend: passing `--mca pml ^ucx` results in an error instead of choosing the btl backend:
```
  PML add procs failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
```
3. Nothing changes if I fail to pass `-x UCX_NET_DEVICES=rxe0:1`. Even the performance is the same. This conflicts with what is described in the [FAQ](https://www.open-mpi.org/faq/?category=openfabrics#ompi-over-roce-ucx-pml)
4. Nothing changes in the application log (but sometimes the performance is inferior) if I disable rxe altogether by `sudo rxe_cfg stop`

The question is: how can I validate:
* which communication backend is chosen by OpenMPI (btl/pml, ucx/tcp/shared memory)
* that RDMA is properly detected and used

I know I can validate RDMA using `ibv_rc_pingpong` but this validates if the setup is correct, not if OpenMPI actually makes use of RDMA

Remark: It'd be really useful if OpenMPI succinctly printed the communication actually used without any verbosity options. If such a change won't be too complicated, I'm open to implementing it as a PR.

**Comment by yosefe** [comment]
@marmistrz The FAQ entry is a bit misleading. By default, UCX would utilize the available devices, even if `-x UCX_NET_DEVICES=rxe0:1` is not specified explicitly.

There a few ways to validate this:
1. If there are any packet/data counters or statistics in RXE, like in hardware RoCE, they can indicate if RXE is used.
2. Compile UCX in debug mode as described [here](https://github.com/openucx/ucx/wiki/OpenMPI-and-OpenSHMEM-installation-with-UCX#ucx-installation), by using `./contrib/configure-devel`. Then, run the application with `mpirun -x UCX_LOG_LEVEL=data  ... <app> <args>`. This would print all sent and received packets and will indicate which transport is being used.

**Comment by marmistrz** [comment]
@yosefe thanks for the reply. UCX logging worked for me if I built OpenUCX using `./configure`. Probably using `configure-release` would not and this is something I will definitely want to use in the future. RXE doesn't seem to have any counters. 

IMO, it's really bad that OpenMPI doesn't print this information in an easily accessible manner, so I'm willing to contribute this feature. Would you be willing to guide me? Where does the selection of the network backend happen in the OpenMPI code? Would it be difficult to provide this feature to both 3.x and 4.x branches?

Btw. is it possible to force RoCE when using UCX without explicitly providing the device? Something like saying: "I want to use RoCE but with whichever device available"

**Comment by yosefe** [comment]
@marmistrz OpenMPI has top-level "pml" components which eventually select UCX, but OpenMPI can't  tell which transport UCX eventually uses because it's a different library and SW layer. you can see probably which pml is selected by setting "-mca pml_base_verbose"
On UCX side, it's possible to force using "RDMA" transports (RoCE or IB, whatever is available) by passing -x UCX_TLS=ib to mpirun.

**Comment by marmistrz** [comment]
Thanks! @yosefe and would such a feature be accepted in UCX? This shouldn't substantially affect the performance (unlike full-fledged logging)

**Comment by yosefe** [comment]
@marmistrz you can run UCX with UCX_LOG_LEVEL=info to show a short summary of what is used
@brminich FYI

**Comment by marmistrz** [comment]
@yosefe `UCX_LOG_LEVEL` has no effect when configured by `contrib/configure-release`.

**Comment by yosefe** [comment]
@marmistrz which UCX version are you using? Release build enables INFO-level logging.

**Comment by marmistrz** [comment]
@yosefe 
```
# UCT version=1.6.0 revision 24d3af9
# configured with: --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check
```
It was configured with `configure-release`. I'm getting ERROR level logging but no INFO level logging (I ran the IMB PingPong benchmark to test it)

**Comment by brminich** [comment]
Unfortunately this logging is not included into v1.6. Is it possible to try with UCX master?
(the logging is added by [this UCX PR](https://github.com/openucx/ucx/pull/3511)

**Comment by yosefe** [comment]
@marmistrz starting with next UCX release (v1.7.0, or UCX master branch today) the release mode logging will be INFO

**Comment by marmistrz** [comment]
Great, I'll test it on Monday :)

**Comment by marmistrz** [comment]
It appears not to be the case for me, but INFO logging does work for me for release mode if explicitly enabled: (this was actually done directly on the host, without RoCE)
```
marcin@hostname:~/mpi-benchmarks-IMB-v2019.3$ mpirun --mca btl ^vader,tcp,openib,uct -n 2 ./IMB-MPI1 PingPong | head -n 10
#------------------------------------------------------------
#    Intel(R) MPI Benchmarks 2019 Update 3, MPI-1 part    
#------------------------------------------------------------
# Date                  : Mon Aug 26 12:09:01 2019
# Machine               : x86_64
# System                : Linux
# Release               : 5.3.0-050300rc5-generic
# Version               : #201908182231 SMP Sun Aug 18 22:33:18 UTC 2019
# MPI Version           : 3.1
# MPI Thread Environment: 
[hostname:03333] mpirun: SIGPIPE detected on fd 13 - aborting
[hostname:03333] mpirun: SIGPIPE detected on fd 13 - aborting
mpirun: abort is already in progress...hit ctrl-c again to forcibly terminate

marcin@hostname:~/mpi-benchmarks-IMB-v2019.3$ UCX_LOG_LEVEL=info mpirun --mca btl ^vader,tcp,openib,uct -n 2 ./IMB-MPI1 PingPong | head -n 10
[1566814148.941358] [hostname:3473 :0]     ucp_worker.c:1468 UCX  INFO  ep_cfg[1]: tag(self/memory cma/memory); 
[1566814148.941432] [hostname:3474 :0]     ucp_worker.c:1468 UCX  INFO  ep_cfg[1]: tag(self/memory cma/memory); 
[1566814148.941402] [hostname:3473 :0]     ucp_worker.c:1468 UCX  INFO  ep_cfg[2]: tag(posix/memory cma/memory); 
[1566814148.941471] [hostname:3474 :0]     ucp_worker.c:1468 UCX  INFO  ep_cfg[2]: tag(posix/memory cma/memory); 
#------------------------------------------------------------
#    Intel(R) MPI Benchmarks 2019 Update 3, MPI-1 part    
#------------------------------------------------------------
# Date                  : Mon Aug 26 12:09:08 2019
# Machine               : x86_64
# System                : Linux
[hostname:03467] mpirun: SIGPIPE detected on fd 13 - aborting
[hostname:03467] mpirun: SIGPIPE detected on fd 13 - aborting
mpirun: abort is already in progress...hit ctrl-c again to forcibly terminate

marcin@hostname:~/mpi-benchmarks-IMB-v2019.3$ ucx_info -v
# UCT version=1.7.0 revision 2c338ef
# configured with: --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/usr
```

But when used with RoCE the info-level logging indeed prints the RDMA interface used. Thanks!
```
[1566815490.047313] [hostname:11414:0]     ucp_worker.c:1468 UCX  INFO  ep_cfg[2]: tag(rc/rocep0s31f6:1); 
```

**Comment by jsquyres** [comment]
Looks like this question was answered a while ago; I'm closing the issue.
