### ISSUE TITLE
mpirun is unable to launch jobs on Cray XC40 machine when --enable-static is used

### ISSUE THREAD

**Issue by dshrader** [open-mpi/ompi#6897]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
3.1.4 and master nightly snapshot from Aug 13th

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

source tarball in all cases

### Please describe the system on which you are running

* Operating system/version: Cray Linux Environment 6.0, based on SLES 12.3
* Computer hardware: Intel
* Network type: Cray Aries

Resource manager: Slurm 18.08.7

-----------------------------

## Details of the problem

If `--enable-static` is used when configuring Open MPI on our Cray XC40 machines, mpirun is unable to launch jobs. The following configure line is sufficient to reproduce the issue on the Cray machine I have access to:

```$> ./configure --enable-static --prefix=...```

I can compile hello_c.c from the examples directory with the Open MPI compiled from the above command, but running it with mpirun has no output and I have to manually kill the process. Srun does work.

Here are the basic commands to reproduce/showcase the problem:

```
$> cd openmpi-3.1.4 # or openmpi-master-201908130353-ae1f7e0
$> ./configure --enable-static --prefix=../install
$> make
$> make install
$> export PATH=/full/path/to/install/bin:$PATH
$> cd examples
$> mpicc hello_c.c
$> salloc -N 1
$> mpirun -n 2 ./a.out
...no output...
^C
$> srun -n 2 ./a.out
Hello, world, I am 0 of 2, (Open MPI v4.1.0a1, package: Open MPI dshrader@tt-fey1 Distribution, ident: 4.1.0a1, repo rev: v2.x-dev-7101-gae1f7e0, Unreleased developer copy, 144)
Hello, world, I am 1 of 2, (Open MPI v4.1.0a1, package: Open MPI dshrader@tt-fey1 Distribution, ident: 4.1.0a1, repo rev: v2.x-dev-7101-gae1f7e0, Unreleased developer copy, 144)
```

After consulting with @hppritcha, he recommended I open an issue here on github. Is there something else that I should be doing to get `--enable-static` to work on a Cray XC40?

**Comment by rhc54** [comment]
Try adding `--disable-shared` to your OMPI configure line to ensure that everything is properly included in the built product.

**Comment by dshrader** [comment]
I added `--disable-shared`, but I can now not compile... It has been a long while since I've compiled with so many static libraries, so this could be my own error. In case it isn't, and there is something up with Open MPI, here is the compile-time error:

```
ld: /usr/projects/hpctools/dshrader/src/openmpi/install-master-201908130353-ae1f7e0-intel-18.0.5/lib/libopen-pal.a(reachable_netlink_utils_common.o): in function `opal_reachable_netlink_rt_raw_parse_cb':
reachable_netlink_utils_common.c:(.text+0x10): undefined reference to `nlmsg_hdr'
ld: reachable_netlink_utils_common.c:(.text+0x35): undefined reference to `nlmsg_data'
ld: reachable_netlink_utils_common.c:(.text+0x5a): undefined reference to `nlmsg_parse'
ld: reachable_netlink_utils_common.c:(.text+0x71): undefined reference to `nla_get_u32'
ld: reachable_netlink_utils_common.c:(.text+0x91): undefined reference to `nla_get_u32'
ld: reachable_netlink_utils_common.c:(.text+0xda): undefined reference to `nlmsg_data'
ld: reachable_netlink_utils_common.c:(.text+0xe4): undefined reference to `nlmsg_size'
ld: /usr/projects/hpctools/dshrader/src/openmpi/install-master-201908130353-ae1f7e0-intel-18.0.5/lib/libopen-pal.a(reachable_netlink_utils_common.o): in function `opal_reachable_netlink_rt_lookup':
reachable_netlink_utils_common.c:(.text+0x178): undefined reference to `nl_socket_alloc'
ld: reachable_netlink_utils_common.c:(.text+0x18e): undefined reference to `nl_connect'
ld: reachable_netlink_utils_common.c:(.text+0x19e): undefined reference to `nl_socket_disable_seq_check'
ld: reachable_netlink_utils_common.c:(.text+0x1b8): undefined reference to `nl_socket_get_fd'
ld: reachable_netlink_utils_common.c:(.text+0x1e4): undefined reference to `nl_close'
ld: reachable_netlink_utils_common.c:(.text+0x1ec): undefined reference to `nl_socket_free'
ld: reachable_netlink_utils_common.c:(.text+0x242): undefined reference to `nlmsg_alloc_simple'
ld: reachable_netlink_utils_common.c:(.text+0x265): undefined reference to `nlmsg_append'
ld: reachable_netlink_utils_common.c:(.text+0x276): undefined reference to `nla_put_u32'
ld: reachable_netlink_utils_common.c:(.text+0x286): undefined reference to `nla_put_u32'
ld: reachable_netlink_utils_common.c:(.text+0x28e): undefined reference to `nlmsg_hdr'
ld: reachable_netlink_utils_common.c:(.text+0x299): undefined reference to `nl_socket_get_local_port'
ld: reachable_netlink_utils_common.c:(.text+0x2b3): undefined reference to `nlmsg_set_proto'
ld: reachable_netlink_utils_common.c:(.text+0x2c8): undefined reference to `nl_send'
ld: reachable_netlink_utils_common.c:(.text+0x2d3): undefined reference to `nlmsg_free'
ld: reachable_netlink_utils_common.c:(.text+0x30c): undefined reference to `nl_socket_modify_cb'
ld: reachable_netlink_utils_common.c:(.text+0x318): undefined reference to `nl_recvmsgs_default'
ld: reachable_netlink_utils_common.c:(.text+0x346): undefined reference to `nl_close'
ld: reachable_netlink_utils_common.c:(.text+0x34e): undefined reference to `nl_socket_free'
ld: reachable_netlink_utils_common.c:(.text+0x36e): undefined reference to `nl_geterror'
ld: reachable_netlink_utils_common.c:(.text+0x393): undefined reference to `nl_geterror'
ld: reachable_netlink_utils_common.c:(.text+0x3b3): undefined reference to `nl_geterror'
ld: reachable_netlink_utils_common.c:(.text+0x3d5): undefined reference to `nl_geterror'
ld: reachable_netlink_utils_common.c:(.text+0x3f7): undefined reference to `nl_geterror'
```

I can't find a library that is supposed to provide these functions, either on my system or in the Open MPI source, so I am a bit at a loss. I'll keep looking for them, but if anyone knows what linking parameters I need to add, please let me know!

**Comment by hjelmn** [comment]
That is expected. Static only builds have been broken since CLE6. I found no way to fix them.

**Comment by dshrader** [comment]
I was hoping that I could at least identify the missing library and link it in dynamically, but so far, I haven't found it. Yeah, I think a 100% static build on these machines isn't possible, but linking in static Open MPI libraries to an application should be possible, correct?

**Comment by dshrader** [comment]
Found the missing library: libnl-3. I included it in the mpicc command when compiling hello_c.c and then I tried to run it. Mpirun still hangs while srun works:

```
$> mpicc /usr/lib64/libnl-3.so.200 hello_c.c
$> mpirun -n 2 ./a.out
^C
$> srun -n 2 ./a.out
Hello, world, I am 1 of 2, (Open MPI v4.1.0a1, package: Open MPI dshrader@tt-fey1 Distribution, ident: 4.1.0a1, repo rev: v2.x-dev-7101-gae1f7e0, Unreleased developer copy, 144)
Hello, world, I am 0 of 2, (Open MPI v4.1.0a1, package: Open MPI dshrader@tt-fey1 Distribution, ident: 4.1.0a1, repo rev: v2.x-dev-7101-gae1f7e0, Unreleased developer copy, 144)
```

So, the issue still remains when using `--disable-shared`.

**Comment by dshrader** [comment]
Any other thoughts or suggestions?

**Comment by jsquyres** [comment]
@hppritcha Can you comment?

**Comment by hppritcha** [comment]
I'll work with Dave on this.

**Comment by hppritcha** [comment]
Okay now I remember.  ```orterun``` and ```orted``` don't work if they are linked against the cray pmi so.  Could you add the following env. variable to your shell and try running ```hostname``` with the mpirun?

```
export PMI_NO_PREINITIALIZE=1
```

**Comment by dshrader** [comment]
That does indeed get mpirun to work. Thank you!

Is this something that Open MPI can work around in the future, or is this something that we'll get to deal with long-term thanks to cray-pmi?

**Comment by hppritcha** [comment]
I think this is a good question for the Cray/HPE shasta folks.  I'd just add this env. variable to the OMPI module file on the LANL crays.

**Comment by hppritcha** [comment]
can we close this issue?

**Comment by dshrader** [comment]
Yep, I am ok with closing the issue.
