### ISSUE TITLE
RPM build option --define 'build_all_in_one_rpm 0' appears to be broken

### ISSUE THREAD

**Issue by jschwartz-cray** [open-mpi/ompi#6900]
## Background information
Trying to build RPMs from the SRPM

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v4.0.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Trying to build RPMs

### Please describe the system on which you are running

* Operating system/version: CentOS Linux release 7.5.1804 (Core)
* Computer hardware: Docker
* Network type: N/A

-----------------------------

## Details of the problem

```
rpmbuild \
    --define 'build_all_in_one_rpm 0' \
    --rebuild openmpi-4.0.1-1.src.rpm
```

fails with:

```
+ find /root/rpmbuild/BUILDROOT/openmpi-4.0.1-1.x86_64 -name config.log -exec rm -f '{}' ';'
+ /usr/bin/mkdir -p /root/rpmbuild/BUILDROOT/openmpi-4.0.1-1.x86_64//opt/openmpi/4.0.1/share/openmpi/modulefiles/openmpi/
+ cat
+ rm -f all.files runtime.files remaining.files devel.files docs.files
+ find /root/rpmbuild/BUILDROOT/openmpi-4.0.1-1.x86_64 -type f -o -type l
+ sed -e s@/root/rpmbuild/BUILDROOT/openmpi-4.0.1-1.x86_64@@
+ /bin/true
+ cat all.files
+ egrep '/lib/|/lib64/|/lib32/|/bin/|/etc/|/help-'
+ /bin/true
+ egrep -vi 'mpic|mpif|ortec|f77|f90|pkgconfig|\.la$|\.a$' tmp.files
+ /bin/true
+ rm -f tmp.files
+ grep -v -f runtime.files all.files
+ cat remaining.files
+ /bin/true
+ egrep -v '/man/|/doc/'
+ grep -v -f devel.files remaining.files
+ grep -v /opt/openmpi/4.0.1/share/openmpi runtime.files
+ mv tmp.files runtime.files
+ grep -v /opt/openmpi/4.0.1/include devel.files
+ mv tmp.files devel.files
+ grep -v /opt/openmpi/4.0.1/man docs.files
error: Bad exit status from /var/tmp/rpm-tmp.eNEf1x (%install)
```

whereas changing build_all_in_one_rpm to 1 works fine.

**Comment by jsquyres** [comment]
Sorry for taking forever to address this.

Looks like this was fixed before v4.0.2 was released:

* Master PR #6659 / 013f5b03f5c7a621955b3647e5031f7e904fedbd
* v4.0.x PR #6663 / 84b3536f61f5046db870026678b3e89d99cb3e10
