### ISSUE TITLE
need PR 6855 pushed back to release branches

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#6927]
PR #6855 needs to be merged back in to v4.0.x, v3.1.x, and v3.0.x

**Comment by hppritcha** [comment]
PR #6946 clears label 4.0.x

**Comment by hkuno** [comment]
I'm sorry it is taking me so long to submit the PRs for v3.0.x and v3.1.x.
While we can show that we can hit the issue in 4.0.x by using ucx over IB with "--mca pml_ucx_opal_mem_hooks true", we aren't sure if this works in earlier builds, and it is taking time to reproduce this issue in v3.0.x and v3.1.x.

**Comment by jsquyres** [comment]
@hkuno Did this turn out to be unnecessary on v3.0.x / v3.1.x?

**Comment by hppritcha** [comment]
closing this as we don't plan to release updates to 3.0.x and 3.1.x
