### ISSUE TITLE
tag-output tag [jobid, MCW_rank] at the end of the line.

### ISSUE THREAD

**Issue by sddi** [open-mpi/ompi#6948]
OPENMPI version: 3.1.4
centos: 7.3
I use the following command:

mpirun --allow-run-as-root --tag-output --hostfile ${host_file} -n ${total_num} -npernode 1 --display-map -wdir ${work_path} ${work_bin}

it writes at the end of the line: ":==>Day 20190731 --------[1,0]"

How to set [jobid, MCW_rank] at the begin of the line?

**Comment by rhc54** [comment]
The tag is always put at the beginning of a line. I would guess that the line here is not terminated with a "\n" and so the tag appears to be showing up at the end, when in fact it is at the beginning of the next line.

**Comment by sddi** [comment]
thank you! OK, i will try it.
