### ISSUE TITLE
Regression v4.0.2 in spml/ikrit: missing MCA_MEMHEAP_SEG_COUNT

### ISSUE THREAD

**Issue by gpaulsen** [open-mpi/ompi#6977]
### What version of Open MPI are you using?
* failing in v4.0.x branch, sometime after v4.0.1

spml/ikrit is giving me an error at build time:
```
ompi/oshmem/mca/spml/ikrit/spml_ikrit.c:28:0:
../../../../../ompi/oshmem/mca/spml/ikrit/spml_ikrit.h:79:31: error: ‘MCA_MEMHEAP_SEG_COUNT’ undeclared here (not in a function)
     spml_ikrit_mkey_t   mkeys[MCA_MEMHEAP_SEG_COUNT];
```

I then grepped in v4.0.1 versus top of v4.0.x and saw the following:
```
[][ompi-v4.0.x] git status
# On branch v4.0.x
nothing to commit, working directory clean
 [][ompi-v4.0.x] find . -type f -exec grep -H MCA_MEMHEAP_SEG_COUNT {} \;
./oshmem/mca/spml/ikrit/spml_ikrit.h:    spml_ikrit_mkey_t   mkeys[MCA_MEMHEAP_SEG_COUNT];

 [][ompi-v4.0.x] git checkout v4.0.1

You are in 'detached HEAD' ...

[][ompi-v4.0.x] find . -type f -exec grep -H MCA_MEMHEAP_SEG_COUNT {} \;
./oshmem/mca/spml/ucx/spml_ucx.h:    spml_ucx_cached_mkey_t   mkeys[MCA_MEMHEAP_SEG_COUNT];
./oshmem/mca/spml/ikrit/spml_ikrit.h:    spml_ikrit_mkey_t   mkeys[MCA_MEMHEAP_SEG_COUNT];
./oshmem/mca/memheap/base/memheap_base_mkey.c:    if (segno >= MCA_MEMHEAP_SEG_COUNT) {
./oshmem/mca/memheap/base/base.h:#define MCA_MEMHEAP_SEG_COUNT  (SYMB_SEG_INDEX+1)
```

**Comment by gpaulsen** [comment]
@yosefe can you please take a look?

It looks like this `MCA_MEMHEAP_SEG_COUNT` was removed in:
```
commit fc41c161344ed699240cca466151254f6d46769a
Author: Yossi Itigin <yosefe@mellanox.com>
Date:   Tue May 7 22:14:41 2019 +0300

    OSHMEM: Add support for shmemx_malloc_with_hint()

    - added multiple segments processing
    - added shmemx_malloc_with_hint call + set of hints
```

**Comment by yosefe** [comment]
adding @hoopoepg 
@gpaulsen @jsquyres  is it ok we remove ikrit altogether? it's obsoleted by spml/ucx

**Comment by gpaulsen** [comment]
I think it's okay to remove it on master, but I think it need to stay on the release branch.  @hppritcha, @jsquyres do you agree?

**Comment by hoopoepg** [comment]
fixed compilation in master branch: https://github.com/open-mpi/ompi/pull/6979
will be back-ported into release branches later

**Comment by jsquyres** [comment]
> I think it's okay to remove it on master, but I think it need to stay on the release branch. @hppritcha, @jsquyres do you agree?

Agreed: must fulfill our backwards compat guarantees on a single release train.

**Comment by hppritcha** [comment]
@hoopoepg can this issue be closed now?

**Comment by gpaulsen** [comment]
Yes.
Thanks all.
