### ISSUE TITLE
UCX: compile errors with `--enable-timing` and `--enable-mem-debug`

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#6995]
Per https://www.mail-archive.com/devel@lists.open-mpi.org/msg20933.html, there are compile errors if one builds with UCX and `--enable-timing` or `--enable-mem-debug`.

These are apparently present on master and v4.0.x.

**Comment by karasevb** [comment]
Refs https://github.com/open-mpi/ompi/pull/6072 relatively errors with `--enable-timing`

**Comment by jsquyres** [comment]
See also #7926 and #7927.
