### ISSUE TITLE
Have hard time to spawn process on two nodes in Slurm system

### ISSUE THREAD

**Issue by YuxinxinChen** [open-mpi/ompi#7007]
Thank you for taking the time to submit an issue!

## Background information
I am trying to run a simple hello-world mpi program on a slurm system
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
openmpi-4.0.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
unzip the tar.gz file
I install with default configure file and then make all install
Follow this: https://www.open-mpi.org/faq/?category=building

### Please describe the system on which you are running

* Operating system/version: CentOS Linux 7
* Computer hardware: Intel CPU
* Network type:  Infiniband mlx5_0

-----------------------------

## Details of the problem
I compiled the hello word code mpic++.
I would like to run 2 processes on 2 nodes, each on one node.
I ``salloc`` two nodes and login in the bash of one of them and run
```shell
mpirun --mca btl_openib_allow_ib 1 -np 2  mpi-send -host ivb113,ivb114
```
However, it doesn't run on two nodes but runs two processes on one node.
If I run
```shell
mpirun --mca btl_openib_allow_ib 1 -np 2  -pernode mpi-send -host ivb113,ivb114
```
It returns error: 
Your job has requested more processes than the ppr for
this topology can support:

  App: mpi-send
  Number of procs:  2
  PPR: 1:node

Please revise the conflict and try again.

This is confusing. 
Thanks for your help in advance

**Comment by ggouaillardet** [comment]
Can you please post your `salloc` command line?
