### ISSUE TITLE
orte_init failed and hwloc_base_binding_policy

### ISSUE THREAD

**Issue by bilias** [open-mpi/ompi#7008]
Hi,
I've compiled openmpi-3.1.4:
./configure --prefix=/usr/local/openmpi-ofed/intel/3.1.4 --disable-dlopen --enable-mpi-fortran --enable-mpi-cxx --enable-shared --enable-static --disable-java --with-platform=contrib/platform/mellanox/optimized --with-verbs --with-hwloc=internal --with-lustre --with-slurm --with-io-romio-flags=--with-file-system=ufs+nfs+lustre --with-pmi=/usr

and having problem running simple mpi code:

```
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  Getting core object failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[node46:02324] Local abort before MPI_INIT completed completed successfully, but am not ab
le to aggregate error messages, and not able to guarantee that all other processes were ki
lled!
```

**This happens only with the default
hwloc_base_binding_policy = core**
in openmpi-mca-params.conf

**If I comment it out then all is good.**
Program is submitted with slurm
```sh
#!/bin/sh
#SBATCH --partition=test
#SBATCH --nodes=2
#SBATCH --ntasks=40
module load mpi/intel/openmpi-3.1.4
srun ./hello
```

program is:
```c
#include <mpi.h>
#include <stdio.h>

int main(int argc, char** argv) {
    // Initialize the MPI environment
    MPI_Init(NULL, NULL);

    // Get the number of processes
    int world_size;
    MPI_Comm_size(MPI_COMM_WORLD, &world_size);

    // Get the rank of the process
    int world_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

    // Get the name of the processor
    char processor_name[MPI_MAX_PROCESSOR_NAME];
    int name_len;
    MPI_Get_processor_name(processor_name, &name_len);

    // Print off a hello world message
    printf("Hello world from processor %s, rank %d out of %d processors\n",
           processor_name, world_rank, world_size);

    // Finalize the MPI environment.
    MPI_Finalize();
}
```

```
mpicc --showme
icc -I/usr/local/openmpi-ofed/intel/3.1.4/include/openmpi -I/usr/local/openmpi-ofed/intel/3.1.4/include/openmpi/opal/mca/hwloc/hwloc1117/hwloc/include -I/usr/local/openmpi-ofed/intel/3.1.4/include/openmpi/opal/mca/event/libevent2022/libevent -I/usr/local/openmpi-ofed/intel/3.1.4/include/openmpi/opal/mca/event/libevent2022/libevent/include -I/usr/local/openmpi-ofed/intel/3.1.4/include -pthread -L/usr/lib64 -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/usr/local/openmpi-ofed/intel/3.1.4/lib -Wl,--enable-new-dtags -L/usr/local/openmpi-ofed/intel/3.1.4/lib -lmpi
```

**Comment by jsquyres** [comment]
Sorry; missed when this issue was originally filed.

That's a weird error; it seems to indicate that hwloc wasn't able to find the core resources on your machine.

Do you have a standalone install of hwloc?  If not, can you install it and send the output of `lstopo`?  (or `lstopo-no-graphics` or `hwloc-ls` or whatever your distro calls it?)

**Comment by bilias** [comment]
Thanks for the answer.
hwloc is installed from distro ( CentOS6)

# hwloc-ls 
Machine (96GB)
  NUMANode L#0 (P#0 48GB)
    Socket L#0 + L3 L#0 (25MB)
      L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
        PU L#0 (P#0)
        PU L#1 (P#20)
      L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
        PU L#2 (P#1)
        PU L#3 (P#21)
      L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2
        PU L#4 (P#2)
        PU L#5 (P#22)
      L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3
        PU L#6 (P#3)
        PU L#7 (P#23)
      L2 L#4 (256KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4
        PU L#8 (P#4)
        PU L#9 (P#24)
      L2 L#5 (256KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5
        PU L#10 (P#5)
        PU L#11 (P#25)
      L2 L#6 (256KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6
        PU L#12 (P#6)
        PU L#13 (P#26)
      L2 L#7 (256KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7
        PU L#14 (P#7)
        PU L#15 (P#27)
      L2 L#8 (256KB) + L1d L#8 (32KB) + L1i L#8 (32KB) + Core L#8
        PU L#16 (P#8)
        PU L#17 (P#28)
      L2 L#9 (256KB) + L1d L#9 (32KB) + L1i L#9 (32KB) + Core L#9
        PU L#18 (P#9)
        PU L#19 (P#29)
    HostBridge L#0
      PCIBridge
        PCI 15b3:1003
          Net L#0 "ib0"
          Net L#1 "ib1"
          OpenFabrics L#2 "mlx4_0"
      PCIBridge
        PCI 8086:1521
          Net L#3 "eth0"
        PCI 8086:1521
          Net L#4 "eth1"
      PCIBridge
        PCIBridge
          PCIBridge
            PCIBridge
              PCI 102b:0534
  NUMANode L#1 (P#1 48GB) + Socket L#1 + L3 L#1 (25MB)
    L2 L#10 (256KB) + L1d L#10 (32KB) + L1i L#10 (32KB) + Core L#10
      PU L#20 (P#10)
      PU L#21 (P#30)
    L2 L#11 (256KB) + L1d L#11 (32KB) + L1i L#11 (32KB) + Core L#11
      PU L#22 (P#11)
      PU L#23 (P#31)
    L2 L#12 (256KB) + L1d L#12 (32KB) + L1i L#12 (32KB) + Core L#12
      PU L#24 (P#12)
      PU L#25 (P#32)
    L2 L#13 (256KB) + L1d L#13 (32KB) + L1i L#13 (32KB) + Core L#13
      PU L#26 (P#13)
      PU L#27 (P#33)
    L2 L#14 (256KB) + L1d L#14 (32KB) + L1i L#14 (32KB) + Core L#14
      PU L#28 (P#14)
      PU L#29 (P#34)
    L2 L#15 (256KB) + L1d L#15 (32KB) + L1i L#15 (32KB) + Core L#15
      PU L#30 (P#15)
      PU L#31 (P#35)
    L2 L#16 (256KB) + L1d L#16 (32KB) + L1i L#16 (32KB) + Core L#16
      PU L#32 (P#16)
      PU L#33 (P#36)
    L2 L#17 (256KB) + L1d L#17 (32KB) + L1i L#17 (32KB) + Core L#17
      PU L#34 (P#17)
      PU L#35 (P#37)
    L2 L#18 (256KB) + L1d L#18 (32KB) + L1i L#18 (32KB) + Core L#18
      PU L#36 (P#18)
      PU L#37 (P#38)
    L2 L#19 (256KB) + L1d L#19 (32KB) + L1i L#19 (32KB) + Core L#19
      PU L#38 (P#19)
      PU L#39 (P#39)

**Comment by jsquyres** [comment]
Github pro tip: enclose verbatim sections of text with lines of three single tick marks to get verbatim mode / disable markup.  https://help.github.com/en/articles/creating-and-highlighting-code-blocks

Does the same thing happen with Open MPI v4.0.2?

**Comment by bilias** [comment]
Tried 4.0.2 and works fine.
However I didn't compile with --disable-dlopen this time, plus I added some more options for my mellanox infiniband.

./configure --prefix=/usr/local/openmpi-ofed/intel/4.0.2 --enable-mpi-fortran --enable-mpi-cxx --enable-shared --enable-static --disable-mpi-java --with-platform=contrib/platform/mellanox/optimized --with-verbs --with-hwloc=/usr --with-lustre --with-slurm --with-io-romio-flags=--with-file-system=ufs+nfs+lustre --with-pmi=/usr --with-ucx=/usr/local/ucx/intel/1.6.1 --with-mxm=/opt/mellanox/mxm --with-fca=/opt/mellanox/fca --with-hcoll=/opt/mellanox/hcoll

Open MPI configuration:
-----------------------
Version: 4.0.2
Build MPI C bindings: yes
Build MPI C++ bindings (deprecated): yes
Build MPI Fortran bindings: mpif.h, use mpi, use mpi_f08
MPI Build Java bindings (experimental): no
Build Open SHMEM support: yes
Debug build: no
Platform file: contrib/platform/mellanox/optimized

Miscellaneous
-----------------------
CUDA support: no
HWLOC support: external
Libevent support: internal
PMIx support: Internal
 
Transports
-----------------------
Cisco usNIC: no
Cray uGNI (Gemini/Aries): no
Intel Omnipath (PSM2): no
Intel TrueScale (PSM): yes
Mellanox MXM: yes
Open UCX: yes
OpenFabrics OFI Libfabric: no
OpenFabrics Verbs: no
Portals4: no
Shared memory/copy in+copy out: yes
Shared memory/Linux CMA: yes
Shared memory/Linux KNEM: no
Shared memory/XPMEM: no
TCP: yes
 
Resource Managers
-----------------------
Cray Alps: no
Grid Engine: no
LSF: no
Moab: no
Slurm: yes
ssh/rsh: yes
Torque: no
 
OMPIO File Systems
-----------------------
Generic Unix FS: yes
Lustre: yes
PVFS2/OrangeFS: no

**Comment by jsquyres** [comment]
Can you try a similar comparison of the two?  I.e., use as many of the same `configure` options as possible?

**Comment by bilias** [comment]
well, I just retried the 3.1.4 with having
hwloc_base_binding_policy = core
and I cannot reproduce the error...
Maybe something else was on the way

thanks anyway and sorry for the trouble :)

**Comment by jsquyres** [comment]
No worries -- glad you got it working!  👏
