### ISSUE TITLE
OPAL ERROR: Unreachable in file pmix3x_client.c at line 112

### ISSUE THREAD

**Issue by amirhajibabaei** [open-mpi/ompi#7025]
version of Open MPI: 4.0.1

installation from source (.tar.gz)

Operating system/version: Ubuntu 18.04

-----------------------------

I have a mpi-aware executable which I run by a command like 
``` shell
mpirun -np 1 ./exe
```

It's the same, If I open a file named `run.sh` and in it I write:
``` shell
./exe
```
and, I execute by
``` shell
mpirun -np 1 bash run.sh
```

But when I want  to execute `./exe` two consecutive times by modifying `run.sh` as
``` shell
./exe
./exe
```
and invoking by the same `mpirun -np 1 bash run.sh` command, the second `./exe` fails with the following error:
``` shell
[amir-MS-7A37:11554] OPAL ERROR: Unreachable in file ../../../../../openmpi-4.0.1/opal/mca/pmix/pmix3x/pmix3x_client.c at line 112
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
```

**Comment by ggouaillardet** [comment]
This is expected, `MPI_Init()` cannot be invoked twice by the same MPI rank (even if done via two distinct processes)

**Comment by amirhajibabaei** [comment]
That helped, thanks.

**Comment by karanveersingh5623** [comment]
> This is expected, `MPI_Init()` cannot be invoked twice by the same MPI rank (even if done via two distinct processes)

Hi , so how can we configure different ranks for MPI ? I am executing mpi using Srun
