### ISSUE TITLE
OSHMEM/spml/ucx: Race condition in the multi-threaded Private contexts situation

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#7029]
When the context is created as `private` underlying UCX worker is created in the unprotected mode [[link](https://github.com/open-mpi/ompi/blob/master/oshmem/mca/spml/ucx/spml_ucx.c#L609)] (no locking is used to ensure the thread-safety of the worker).

According to the OSHMEM spec, the private context is not intended for the shared use and is not expected to be progressed by any thread other than a creator (owning thread). 

In `shmem_ctx_quiet()`, the calling thread is mainly progressing the UCX worker that corresponds to the context passed as the argument [[link](https://github.com/open-mpi/ompi/blob/master/oshmem/mca/spml/ucx/spml_ucx.c#L852)]. However once in a while, it also calls opal_progress() [[link](https://github.com/open-mpi/ompi/blob/master/opal/mca/common/ucx/common_ucx.h#L68)].

The `opal_progress()` is a global function that, in particular, performs the progress on all of the context workers (including private/unprotected ones) [[link](https://github.com/open-mpi/ompi/blob/master/oshmem/mca/spml/ucx/spml_ucx_component.c#L144)] that in parallel may be progressed by an owning thread causing a race condition.

Solution (based on the discussion with @manjugv and @janjust):
The private contexts should not be globally exposed and should not be added to `mca_spml_ucx.active_array` list.

FYI: @jladd-mlnx, @yosefe, @brminich, @hoopoepg

**Comment by artpol84** [comment]
@janjust, please put the right target version labels.

**Comment by artpol84** [comment]
Ref: https://github.com/open-mpi/ompi/pull/7065

**Comment by artpol84** [comment]
Closed by #7065

**Comment by artpol84** [comment]
@janjust please see if #7065 needs to be ported back to v4.

**Comment by janjust** [comment]
@artpol84 , v4.0 is broken too, see #7215, tested using our perf benchmarks.

**Comment by awlauria** [comment]
PR's merged, closing.
