### ISSUE TITLE
32-openmpi with -fdefault-integer-8 in Fortran

### ISSUE THREAD

**Issue by ahaichen** [open-mpi/ompi#7056]
Dear all,

I am trying to compile a simple Fortran code with the flag "-fdefault-integer-8" to test the long integer. the MPI is compiled as 32-bit. The initialize and finalize of MPI is working fine. But once I add the MPI_BCAST function, it shows "no specific subroutine for the generic ‘mpi_bcast’".  I am wondering if I have to compile the MPI in 64-bit way to make it works with interger*8. I have attached the code. Thanks.

Best, Alan

Platform: MacOS
MPI version: v4.0.1
compile: mpifort test.f90  -fdefault-integer-8
!-------------------------------------------------------------------------
!-------------------------------------------------------------------------
!-------------------------------------------------------------------------
Program fortran_test
USE mpi_f08
IMPLICIT NONE

  integer(kind=mpi_integer_kind) ::  err
  integer(kind=mpi_integer_kind) ::  my_rank
  integer(kind=mpi_integer_kind) ::  ierr
  integer(kind=mpi_integer_kind) ::  p
  integer*8 ::   ii

  call MPI_Init(ierr)
  call MPI_Comm_rank(MPI_COMM_WORLD, my_rank, ierr)
  call MPI_Comm_size(MPI_COMM_WORLD, p, ierr)

  if(my_rank==1) ii=1
  if(my_rank==0) ii=0
 
  CALL MPI_BCAST(ii,1,MPI_integer8,0,MPI_COMM_WORLD,ierr)
  call MPI_Finalize(ierr)
end

**Comment by jsquyres** [comment]
I'm not quite sure I understand what you are trying to do.

The sample Fortran you sent is not valid MPI -- you're passing `integer(kind=mpi_address_kind)` parameters to `MPI_Init()` (and others).  That is not correct -- `MPI_Init()` (and others) take default `integer` parameters.

If you want to compile your application with `-fdefault-integer-8`, then you should configure and build Open MPI that way, too.

**Comment by ahaichen** [comment]
Thanks. I have found the issue. Actually it is the numbers I put in the MPI_BCAST that cause the problem. when using tag -fdefault-integer-8, the number will be automatically 64 bit, which mismatch the 32-bit compiled MPI. 

The test is actually intended to check if we can safely switch between default 4 or 8 integer in Fortran with the 32 compiled MPI.

Thanks anyway 

Best, Alan
