### ISSUE TITLE
Some libfabric transports in the OFI MTL do not handle "arbitrarily-sized" messages

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7058]
Per https://github.com/open-mpi/ompi/issues/6976, the PSM2 transport in the OFI MTL does not handle messages larger than 4GB bytes (other OFI providers do).  The verbs libfabric provider has a similar issue -- it is limited to 2GB messages.

PR's on master/v4.0.x/v3.1.x/v3.0.x were added to make the ofi MTL obey the libfabric property specifying the max message size (`ep_attr->max_msg_size`): #7003, #7004, #7005, #7006.  This at least makes Open MPI noisly fail to send large messages in this case (vs. silently fail, which is what it was doing before).

This is a good stop-gap solution, but the proper solution is to allow MPI applications to send "arbitrarily-sized" messages (i.e., messages only limited by resources such as memory space).

**Comment by bwbarrett** [comment]
As we discussed in the dev meeting yesterday, added a README note that we're not going to fix this and customers should approach their provider developers to fix it there.
