### ISSUE TITLE
opal/common/ucx: Simple one-sided test case fails with UCX

### ISSUE THREAD

**Issue by AboorvaDevarajan** [open-mpi/ompi#7101]
### Distribution used 
ompi - master and ucx - master (clone)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

**UCX configuration: (master branch)**
```
./autogen.sh
./contrib/configure-release-mt --without-java --prefix=$shared_dir/ucx-install --with-cuda=/usr/local/cuda
make 
make install 
```
**OMPI configuration: (master branch)**
```
./autogen.pl
./configure --enable-mca-no-build=btl-uct --enable-mpi1-compatibility --prefix $shared_dir/install --with-cuda=/usr/local/cuda --with-ucx=$shared_dir/ucx-install 
make
make install
```

### Please describe the system on which you are running

* Operating system/version: RHEL 7.6
* Computer hardware: ppc64le (POWER8NVL)
* Network type: IB, shmem

-----------------------------

## Details of the problem

Here is the test case which I'm using:
https://gist.github.com/AboorvaDevarajan/287067606ade089cc3499ab34d703311

```
# mpicc simple_win_test.c -o simple_win_test
# $MPI_ROOT/bin/mpirun --timeout 600 -np 2  -mca backtrace_lwcore_enable t --get-stack-traces --report-state-on-timeout -mca plm rsh --prefix $MPI_ROOT --mca osc ucx,sm --mca pml ucx --mca btl ^vader,tcp,openib,uct --mca opal_common_ucx_opal_mem_hooks 1 -x UCX_MEM_MMAP_HOOK_MODE=none -x LD_LIBRARY_PATH ./simple_win_test 
```

Once in a while the above test case fails with this error:

```
[1571571024.385372] [c712f6n05:127020:0] ucp_mm.c:116  UCX  ERROR failed to register address 0x10001d30adf0 length 8192 on md[5]=cuda_cpy: Input/output
```
Here is some debug info which I got so far:

During `MPI_Win_create` for the above configuration we take up the `cuda_copy` (ucx->uct) path and do a `cudaHostRegister` of the memory, and the corresponding `cudaHostUnregister` is not invoked in `MPI_Win_free` but it's deferred to a later point,
https://github.com/open-mpi/ompi/blob/master/opal/mca/common/ucx/common_ucx_wpool.c#L1008
if the same memory is alllocated during `MPI_Win_create` in the next iteration `cudaHostRegister` will fail with error no: 712 which is `cudaErrorHostMemoryAlreadyRegistered`.

I have one question:

Do we always take the cuda_copy path when we configure OMPI / UCX with CUDA enabled? Is there a way to disable it for applications with just host buffers?

**Comment by yosefe** [comment]
@AboorvaDevarajan can you try removing cuda_copy: add "-x UCX_TLS=sm,ib,tcp" to mpirun.
BTW, why are these parameters used: "--mca opal_common_ucx_opal_mem_hooks 1 -x UCX_MEM_MMAP_HOOK_MODE=none"?

Adding @bureddy  - we should not fail for multiple time registration in UCT cuda_copy

**Comment by AboorvaDevarajan** [comment]
@yosefe With "-x UCX_TLS=sm,ib,tcp" the test fails with some other failure signatures. Here is one of the stacktrace. (SEGFAULT)

```$MPI_ROOT/bin/mpirun --timeout 600 -np 2 --mca osc ucx --mca pml ucx --mca btl ^vader,tcp,openib,uct -x UCX_TLS=shm,ib,tcp -x LD_LIBRARY_PATH -mca opal_common_ucx_verbose 0 --tag-output  ./simple_win_test```

```
#0  0x0000100003a80338 in ibv_madvise_range.part.5 () from /lib64/libibverbs.so.1
#1  0x0000100003ab7568 in mlx5_alloc_buf () from /lib64/libmlx5.so.1
#2  0x0000100003ab7c5c in mlx5_alloc_preferred_buf () from /lib64/libmlx5.so.1
#3  0x0000100003ae7ab0 in mlx5_alloc_cq_buf () from /lib64/libmlx5.so.1
#4  0x0000100003b01514 in create_cq () from /lib64/libmlx5.so.1
#5  0x0000100003b03690 in mlx5_create_cq () from /lib64/libmlx5.so.1
#6  0x0000100003a82550 in ibv_create_cq () from /lib64/libibverbs.so.1
#7  0x0000100003a1162c in uct_ib_mlx5_exp_md_umr_qp_create (md=0x1000177bc220) at mlx5/exp/ib_exp_md.c:43
#8  0x0000100003a11d18 in uct_ib_mlx5_exp_md_open (ibv_device=<optimized out>, md_config=0x1000177b67c0, p_md=0x3ffff2f89490) at mlx5/exp/ib_exp_md.c:427
#9  0x0000100003a0d304 in uct_ib_md_open (component=<optimized out>, md_name=<optimized out>, uct_md_config=0x1000177b67c0, md_p=0x3ffff2f89550) at base/ib_md.c:1185
#10 0x000010000360d6fc in uct_md_open (component=<optimized out>, md_name=<optimized out>, config=<optimized out>, md_p=0x1000177b5c00) at base/uct_md.c:62
#11 0x000010000358feec in ucp_fill_tl_md (tl_md=0x1000177b5c00, md_rsc=0x3ffff2f895d0, cmpt_index=7 '\a', context=0x1000177b5300) at core/ucp_context.c:832
#12 ucp_add_component_resources (context=0x1000177b5300, cmpt_index=7 '\a', avail_devices=0x3ffff2f89c60, avail_tls=0x3ffff2f89d80, dev_cfg_masks=0x3ffff2f89da8, 
    tl_cfg_mask=0x3ffff2f89de0, config=0x1000177b2f10) at core/ucp_context.c:1043
#13 0x0000100003590fdc in ucp_fill_resources (config=0x1000177b2f10, context=0x1000177b5300) at core/ucp_context.c:1179
#14 ucp_init_version (api_major_version=<optimized out>, api_minor_version=<optimized out>, params=<optimized out>, config=0x1000177b2f10, context_p=0x100146c0310)
    at core/ucp_context.c:1461
#15 0x0000100003553d6c in ucp_init (params=0x3ffff2f89fa8, config=0x1000177b2f10, context_p=0x100146c0310)
    at /nfs_smpi_ci/abd/workspace/os/ucx-install/include/ucp/api/ucp.h:1238
#16 0x000010000355579c in opal_common_ucx_wpool_init (wpool=0x100146c02a0, proc_world_size=2, enable_mt=false) at common_ucx_wpool.c:176
#17 0x000010001253bad8 in component_select (win=0x1000177b20c0, base=0x3ffff2f8a2a0, size=0, disp_unit=4, comm=0x1000002c2040 <ompi_mpi_comm_world>, 
    info=0x1000002ca990 <ompi_mpi_info_null>, flavor=1, model=0x3ffff2f8a290) at osc_ucx_component.c:333
#18 0x0000100000234dc0 in ompi_osc_base_select (win=0x1000177b20c0, base=0x3ffff2f8a2a0, size=0, disp_unit=4, comm=0x1000002c2040 <ompi_mpi_comm_world>, 
    info=0x1000002ca990 <ompi_mpi_info_null>, flavor=1, model=0x3ffff2f8a290) at base/osc_base_init.c:78
#19 0x0000100000101244 in ompi_win_create (base=0x0, size=0, disp_unit=4, comm=0x1000002c2040 <ompi_mpi_comm_world>, info=0x1000002ca990 <ompi_mpi_info_null>, 
    newwin=0x3ffff2f8a428) at win/win.c:246
#20 0x00001000001c2500 in PMPI_Win_create (base=0x0, size=0, disp_unit=4, info=0x1000002ca990 <ompi_mpi_info_null>, comm=0x1000002c2040 <ompi_mpi_comm_world>, 
    win=0x3ffff2f8a428) at pwin_create.c:81
#21 0x0000000010000e10 in main ()
```

These parameters `--mca opal_common_ucx_opal_mem_hooks 1 -x UCX_MEM_MMAP_HOOK_MODE=none`  are used since sometime back when there was a conflict between ompi and ucx hooks https://github.com/open-mpi/ompi/issues/6396, I guess its not needed anymore and can be ignored.

**Comment by yosefe** [comment]
@AboorvaDevarajan which MLNX_OFED / driver version is used?

**Comment by AboorvaDevarajan** [comment]
```
ucx-test]$ ofed_info -s
MLNX_OFED_LINUX-4.7-1.0.0.2:
```

**Comment by awlauria** [comment]
Is this still an issue? Seems from the closed PR it may be fixed. @AboorvaDevarajan can you please re-test?

**Comment by AboorvaDevarajan** [comment]
I tested this with recent OMPI master + UCX master and it passes now. Closing this.
