### ISSUE TITLE
Non-blocking wildcard receive fails to receive data in OpenMPI 2.1.1

### ISSUE THREAD

**Issue by jprotze** [open-mpi/ompi#7118]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
```
mpirun --version
mpirun (Open MPI) 2.1.1
```

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

OpenMPI as delivered with Ubuntu 18.04.3 LTS

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04.3 LTS
* Kernel: 5.0.0-32-generic #34~18.04.2-Ubuntu SMP x86_64 GNU/Linux
* Computer hardware: x86_64 notebook
* Network type: n/a

-----------------------------

## Details of the problem

```C
#include <stdio.h>
#include <mpi.h>

int main(){
  MPI_Request r[1]={MPI_REQUEST_NULL};
  char rbuf[10]="fail";
  char sbuf[10]="test";
  MPI_Init(NULL,NULL);
  MPI_Irecv(rbuf, 10, MPI_CHAR, MPI_ANY_SOURCE, 10,
                MPI_COMM_WORLD, r);
  MPI_Send(sbuf, 5, MPI_CHAR, 0, 10, MPI_COMM_WORLD);
  MPI_Wait(r, MPI_STATUS_IGNORE);
  printf("%s\n",rbuf);
  return MPI_Finalize();
}
```
Execution with one process should result in a print of "test". With OpenMPI 2.1.1 the code prints "fail".
The code prints "test" when compiled with OpenMPI 3/4 or other MPI implementations.

The faulty behavior seems to depend on the non-blocking receive with `MPI_ANY_SOURCE`, different variants of send have no influence. Using a blocking receive or a specific source fixes the issue.

**Comment by ggouaillardet** [comment]
Iirc this is a know issue that only occurs if Open MPI is built with `—enable-heterogeneous`. At that time, it was decided **not** to backport the fix to the `v2` branch.

So your options are to either upgrade Open MPI or rebuild it without the infamous option.

**Comment by jprotze** [comment]
Ok, thanks for the feedback. Good to hear that the issue is known and actually addressed in the higher versions. 
I do not really depend on this version and use this local installation just for mobile code development.
