### ISSUE TITLE
Configure Error for installation of openmpi-1.10.1

### ISSUE THREAD

**Issue by StellaQJ** [open-mpi/ompi#7129]
## Background information
I tried to install openmpi-1.10.1 but I failed to configure.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
./configure --prefix=$PATH/LIBRARIES/openmpi --enable-static --enable-mpi-thread-multiple --without-usnic --enable-mpi-cxx CC=gcc CXX=g++ FC=gfortran FCFLAGS=-m64 F77=gfortran FFLAGS=-m64
make all
make install

### Please describe the system on which you are running

* Operating system/version: 
`3.10.0-957.21.2.el7.x86_64`

* Computer hardware: 
`NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"`
-----------------------------

## Details of the problem
I am not able to configure and install openmpi-1.10.1. Would anyone please kindly give me some suggestions on this issue? Thanks a lot in advance.
When I configure, the first error I got as below:
`gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:5981: $? = 1
configure:5970: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.`
Other error messages are as follow:
`conftest.c:10:10: fatal error: ac_nonexistent.h: No such file or directory
 #include <ac_nonexistent.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
configure:6497: $? = 1
configure: failed program was:
| /* confdefs.h */`

I also attached the configure log: [https://www.dropbox.com/s/5zgrh80yuut1y0e/config.log?dl=0](url)
Here is the make log: [https://www.dropbox.com/s/2qoznk7s8cp8txz/make_log.txt?dl=0](url)

**Comment by jsquyres** [comment]
Looks like you asked the same question [on the user's mailing list](https://www.mail-archive.com/users@lists.open-mpi.org/msg33526.html).

I'll close the issue here.
