### ISSUE TITLE
Need --mca options with mpirun to allocate all cores in cluster 

### ISSUE THREAD

**Issue by ealemany** [open-mpi/ompi#7150]
Thank you for taking the time to submit an issue!

## Background information
1 Maser node 
10 nodes with 12 cores each
--hostfile
radonc-phaser01 slots=12
radonc-phaser02 slots=12
radonc-phaser03 slots=12
radonc-phaser04 slots=12
radonc-phaser05 slots=12
radonc-phaser06 slots=12
radonc-phaser07 slots=12
radonc-phaser08 slots=12
radonc-phaser09 slots=12
radonc-phaser10 slots=12

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
OpenMPI-4.0.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

OpenMPI was installed from source tarball

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04
* Computer hardware: AMD
* Network type: tcp, nfs

-----------------------------

## Details of the problem

From the Master node we ran:
```shell
shell$ mpirun --hostfile /home/ompi/hostsfile -np 20 BEAM_FLASH_SCAN -i wb_right_block.egsinp -p FLASH60MeV
```

The command did not give us any error message. However, when i did "htop" the job is using only 2 cores. The --hostfile has 10 nodes with 12 cores each. I would expect to see 20 cores across the 10 nodes. Instead ii see  1 core from one node and 1 core from another node. Here is the output of "htop" command:
```shell
orted -mca ess env -mca ess_base_jobid 3792306176 -mca ess_base_vpid 4 -mca ess_base_num_procs 10 -mca orte_node_regex phaser-manager,radonc-phaser[2:1-9]@0(10) -mca orte_hnp_uri 3792306176.0;tcp://10.112.0.24:60753 -mca plm rsh --tree-spawn -mca orte_parent_uri 3792306176.0;tcp://10.112.0.24:60753 -mca pmix ^s1,s2,cray,isolated
``` 
It seems as if I need to configure and then include --mca options in the mpirun command, but i really do not know how.

Thank you for your help

Eric
N.B: i have also attached the an output text file of the "htop" command line.

[mpi_orte_only_2_cores.txt](https://github.com/open-mpi/ompi/files/3816182/mpi_orte_only_2_cores.txt)

**Comment by rhc54** [comment]
Your text file is a little hard for me to parse. I'm curious as to why you are saying it is running on only two "cores" and if we have a terminology or typo problem. Your mpirun cmd line would cause it to run on two "nodes", notably phaser01 and 02 as the two of them provide 20 "cores" for the 20 processes, and we will by default map a process to a core.

Any chance you are saying "core" when you mean "node"?

I also note that your text file is only showing "orted" - I don't see any application process in the output but maybe I am missing it due to the parsing issue. The orted daemon will of course only use one core. Question is: where are the application procs?

**Comment by ealemany** [comment]
Sorry for the confusion.
I “htop” on every node in the cluster ( radonc-phaser[01-10] ) and I noticed that  1 core and 1 process  on node radon-phaser01 and 1 core, 1 process on node radon-phaser04 were utilized. Therefore, I concluded the mpirun command was launched
only on two nodes using 1 core, 1 process each. Our first goal was to run mpirun allocating 20 cores total in the cluster of 10 nodes. If we were successful our next attempt would have been to run mpirun with 120 cores.

 “ Your mpirun cmd line would cause it to run on two "nodes", notably phaser01 and 02 as the two of them provide 20 "cores" for the 20 processes, and we will by default map a process to a core."
So why are they only two nodes running 1 process on each?


"I also note that your text file is only showing "orted" - I don't see any application process in the output but maybe I am missing it due to the parsing issue.
From what I understand “orted” command is not intended to be manually invoked and that is why I don’t understand what I am seeing in “htop"


"Question is: where are the application procs?”
That’s a question I am asking myself but maybe this is not the right place to ask this kind of question. The post-docs run EGSnrc software. This Software is OpenMPI ready. In order to compile an user code with OpenMPI support, user would go to their code directory and run " make mpi"
Then, the user will run mpirun command like this: $mpirun -np #NUM_PROCS $(user_code)_mpi -i input_file -p pegs_file

Since the “htop” output shows - -mca message I thought that maybe I was missing - - mac parameters/options


____________________________________________________________________________________________________________________________



Eric F.  Alemany
Systems Administrator for Research
EXO Extended Operations

Stanford Medicine - Technology & Digital Services
Stanford, California 94305








On Nov 6, 2019, at 11:40 AM, Ralph Castain <notifications@github.com<mailto:notifications@github.com>> wrote:


Your text file is a little hard for me to parse. I'm curious as to why you are saying it is running on only two "cores" and if we have a terminology or typo problem. Your mpirun cmd line would cause it to run on two "nodes", notably phaser01 and 02 as the two of them provide 20 "cores" for the 20 processes, and we will by default map a process to a core.

Any chance you are saying "core" when you mean "node"?

I also note that your text file is only showing "orted" - I don't see any application process in the output but maybe I am missing it due to the parsing issue. The orted daemon will of course only use one core. Question is: where are the application procs?

**Comment by jsquyres** [comment]
Your mpirun command is reasonable (`mpirun --hostfile /home/ompi/hostsfile -np 20 BEAM_FLASH_SCAN -i wb_right_block.egsinp -p FLASH60MeV`).  From the hostfile you show in the description, I would expect 12 `BEAM_FLASH_SCAN` processes to run on `radonc-phaser01`, and 8 more to run on `radonc-phaser02`.

The `orted` is a helper user-level process that we launch.  It should be transient (i.e., it should disappear when `mpirun` completes) and is usually solely behind-the-scenes / most users don't notice it.

You might want to try `mpirun`'ing non-MPI applications to test that everything is working properly.  E.g., try 

```
shell$ mpirun --hostfile /home/ompi/hostsfile -np 20 hostname
```

You should see 12 outputs from 01 and 8 from 02.

Note that Open MPI's mapper packs in processes per host by slot.  That's why it takes up all 12 slots on the first host and then 8 more from the 2nd host.  If you want to go round robin the other way, you can:

```
shell$ mpirun --hostfile /home/ompi/hostsfile -np 20 --map-by node hostname
```

In this case, you should see two hostname outputs from each of your 10 nodes.

Once you have that working properly, then try with a simple "hello world" and/or "ring" MPI applications.  If you built Open MPI from source, you can go into the "examples" directory in the source tree and type `make`.  Then try running `hello_c` and `ring_c` that were just built.

The `hello_c` program just does MPI initialization/finalization, but does not send any actual MPI messages.  The `ring_c` program sends a simple MPI message around a ring 10 times.

If you can run `hostname` properly but then fail `hello_c`, the error messages that come up will be a good data point.  If you can run `hello_c` but fail `ring_`, the error messages that come up will be a good data point.

Make sense?

**Comment by ealemany** [comment]
Thank you for explaining in details  how OpenMPI works. The mpirun command you had me run are great testing programs. All make sense and here is the output of the mpirun commands you suggested I tried. All of them worked well.
Any suggestion as to why BEAM_FLASH_SCAN processes will not run?

Thank you for all your help.

1) shell$ mpirun --hostfile /home/ompi/hostsfile -np 20 hostname

mpirun --hostfile /home/ompi/hostsfile -np 20 hostname
radonc-phaser02
radonc-phaser02
radonc-phaser02
radonc-phaser02
radonc-phaser02
radonc-phaser02
radonc-phaser02
radonc-phaser02
radonc-phaser01
radonc-phaser01
radonc-phaser01
radonc-phaser01
radonc-phaser01
radonc-phaser01
radonc-phaser01
radonc-phaser01
radonc-phaser01
radonc-phaser01
radonc-phaser01
radonc-phaser01


2) shell$ mpirun --hostfile /home/ompi/hostsfile -np 20 --map-by node hostname

mpirun --hostfile /home/ompi/hostsfile -np 20 --map-by node hostname
radonc-phaser02
radonc-phaser09
radonc-phaser02
radonc-phaser09
radonc-phaser01
radonc-phaser05
radonc-phaser05
radonc-phaser01
radonc-phaser07
radonc-phaser07
radonc-phaser04.stanford.EDU<http://radonc-phaser04.stanford.EDU>
radonc-phaser04.stanford.EDU<http://radonc-phaser04.stanford.EDU>
radonc-phaser10
radonc-phaser10
radonc-phaser06
radonc-phaser06
radonc-phaser08
radonc-phaser08
radonc-phaser03
radonc-phaser03


3)  try with a simple "hello world”

ompi@phaser-manager:~/openmpi-4.0.1/examples$ mpirun --hostfile /home/ompi/hostsfile -np 20 /media/homes/ompi/openmpi-4.0.1/examples/hello_c
Hello, world, I am 14 of 20, (Open MPI v4.0.0, package: Open MPI root@radonc-phaser02 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 115)
Hello, world, I am 18 of 20, (Open MPI v4.0.0, package: Open MPI root@radonc-phaser02 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 115)
Hello, world, I am 1 of 20, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)
Hello, world, I am 12 of 20, (Open MPI v4.0.0, package: Open MPI root@radonc-phaser02 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 115)
Hello, world, I am 2 of 20, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)
Hello, world, I am 13 of 20, (Open MPI v4.0.0, package: Open MPI root@radonc-phaser02 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 115)
Hello, world, I am 4 of 20, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)
Hello, world, I am 15 of 20, (Open MPI v4.0.0, package: Open MPI root@radonc-phaser02 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 115)
Hello, world, I am 7 of 20, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)
Hello, world, I am 16 of 20, (Open MPI v4.0.0, package: Open MPI root@radonc-phaser02 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 115)
Hello, world, I am 8 of 20, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)
Hello, world, I am 17 of 20, (Open MPI v4.0.0, package: Open MPI root@radonc-phaser02 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 115)
Hello, world, I am 9 of 20, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)
Hello, world, I am 19 of 20, (Open MPI v4.0.0, package: Open MPI root@radonc-phaser02 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 115)
Hello, world, I am 10 of 20, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)
Hello, world, I am 11 of 20, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)
Hello, world, I am 3 of 20, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)
Hello, world, I am 5 of 20, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)
Hello, world, I am 6 of 20, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)
Hello, world, I am 0 of 20, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)


4)and/or “ring"

ompi@phaser-manager:~/openmpi-4.0.1/examples$ mpirun --hostfile /home/ompi/hostsfile -np 20 /media/homes/ompi/openmpi-4.0.1/examples/ring_c
Process 0 sending 10 to 1, tag 201 (20 processes in ring)
Process 0 sent to 1
Process 0 decremented value: 9
Process 0 decremented value: 8
Process 0 decremented value: 7
Process 0 decremented value: 6
Process 0 decremented value: 5
Process 0 decremented value: 4
Process 0 decremented value: 3
Process 0 decremented value: 2
Process 0 decremented value: 1
Process 0 decremented value: 0
Process 0 exiting
Process 1 exiting
Process 2 exiting
Process 3 exiting
Process 4 exiting
Process 5 exiting
Process 6 exiting
Process 7 exiting
Process 8 exiting
Process 9 exiting
Process 12 exiting
Process 10 exiting
Process 11 exiting
Process 13 exiting
Process 14 exiting
Process 15 exiting
Process 16 exiting
Process 17 exiting
Process 18 exiting
Process 19 exiting
ompi@phaser-manager


____________________________________________________________________________________________________________________________



Eric F.  Alemany
Systems Administrator for Research
EXO Extended Operations

Stanford Medicine - Technology & Digital Services
Stanford, California 94305








On Nov 6, 2019, at 3:12 PM, Jeff Squyres <notifications@github.com<mailto:notifications@github.com>> wrote:


Your mpirun command is reasonable (mpirun --hostfile /home/ompi/hostsfile -np 20 BEAM_FLASH_SCAN -i wb_right_block.egsinp -p FLASH60MeV). From the hostfile you show in the description, I would expect 12 BEAM_FLASH_SCAN processes to run on radonc-phaser01, and 8 more to run on radonc-phaser02.

The orted is a helper user-level process that we launch. It should be transient (i.e., it should disappear when mpirun completes) and is usually solely behind-the-scenes / most users don't notice it.

You might want to try mpirun'ing non-MPI applications to test that everything is working properly. E.g., try

shell$ mpirun --hostfile /home/ompi/hostsfile -np 20 hostname


You should see 12 outputs from 01 and 8 from 02.

Note that Open MPI's mapper packs in processes per host by slot. That's why it takes up all 12 slots on the first host and then 8 more from the 2nd host. If you want to go round robin the other way, you can:

shell$ mpirun --hostfile /home/ompi/hostsfile -np 20 --map-by node hostname


In this case, you should see two hostname outputs from each of your 10 nodes.

Once you have that working properly, then try with a simple "hello world" and/or "ring" MPI applications. If you built Open MPI from source, you can go into the "examples" directory in the source tree and type make. Then try running hello_c and ring_c that were just built.

The hello_c program just does MPI initialization/finalization, but does not send any actual MPI messages. The ring_c program sends a simple MPI message around a ring 10 times.

If you can run hostname properly but then fail hello_c, the error messages that come up will be a good data point. If you can run hello_c but fail ring_, the error messages that come up will be a good data point.

Make sense?

**Comment by jsquyres** [comment]
On Nov 7, 2019, at 10:15 AM, ealemany <notifications@github.com> wrote:
> 
> Thank you for explaining in details how OpenMPI works. The mpirun command you had me run are great testing programs. All make sense and here is the output of the mpirun commands you suggested I tried. All of them worked well. 

Excellent.

> Any suggestion as to why BEAM_FLASH_SCAN processes will not run? 

Do you have the source code for it, or is it just a binary?

I ask because it looks like your Open MPI setup is working properly, but something in the application is failing.

If the application is source code and you compiled it against your Open MPI installation, then it's *probably* an error in the application somewhere.  Standard C / Fortran debugging techniques apply.

If the application is an ISV binary, you might need to check what version of Open MPI it is expecting.  E.g., if it's expecting Open MPI v3.0.x or v3.1.x, those are not ABI compatible with Open MPI v4.0.x.  All manner of mayhem can go wrong if it's the wrong ABI.

-- 
Jeff Squyres
jsquyres@cisco.com

**Comment by ealemany** [comment]
> Do you have the source code for BEAM_FLASH_SCAN, or is it just a binary?

I will ask the post-doc running this software since this is a bit beyond my expertise. But since you confirmed that my OpenMPI setup is working properly, I now lean towards the possibility that it is “probably” an error in the application.
As soon as I hear back from the post-doc, I will post his answer.


____________________________________________________________________________________________________________________________



Eric F.  Alemany
Systems Administrator for Research
EXO Extended Operations

Stanford Medicine - Technology & Digital Services
Stanford, California 94305








On Nov 7, 2019, at 3:44 PM, Jeff Squyres <notifications@github.com<mailto:notifications@github.com>> wrote:

On Nov 7, 2019, at 10:15 AM, ealemany <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> Thank you for explaining in details how OpenMPI works. The mpirun command you had me run are great testing programs. All make sense and here is the output of the mpirun commands you suggested I tried. All of them worked well.

Excellent.

> Any suggestion as to why BEAM_FLASH_SCAN processes will not run?

Do you have the source code for it, or is it just a binary?

I ask because it looks like your Open MPI setup is working properly, but something in the application is failing.

If the application is source code and you compiled it against your Open MPI installation, then it's *probably* an error in the application somewhere. Standard C / Fortran debugging techniques apply.

If the application is an ISV binary, you might need to check what version of Open MPI it is expecting. E.g., if it's expecting Open MPI v3.0.x or v3.1.x, those are not ABI compatible with Open MPI v4.0.x. All manner of mayhem can go wrong if it's the wrong ABI.

--
Jeff Squyres
jsquyres@cisco.com<mailto:jsquyres@cisco.com>

**Comment by ealemany** [comment]
Here is the post-doc’s answer to - Do you have the source code for it, or is it just a binary?

"BEAM_FLASH_SCAN is a binary. Most of the source code is available in the .mortran and .mortlst files in the BEAM_FLASH_SCAN directory."

I assume then the issue has to do with ABI. At this point we (the post-docs and i)  would need to check with the EGSrnc developer group.


On the same note, when I run the different mpirun commands you suggested earlier it all worked well. However, I encountered an issue when I ran a smile “hello world” MPI application
with more than 3 nodes.
The mpirun command on 3 nodes   $mpirun --hostfile /home/ompi/hostsfile -np 20 /media/homes/ompi/openmpi-4.0.1/examples/hello_c
works well
But I run the same command but with 48 cores 4 nodes $mpirun --hostfile /home/ompi/hostsfile -np 48 /media/homes/ompi/openmpi-4.0.1/examples/hello_c
[radonc-phaser01:04291] [[46181,0],1] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
[radonc-phaser05:13564] [[46181,0],5] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
[radonc-phaser03:01646] [[46181,0],3] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[46181,0],1] FORCE-TERMINATE AT Data unpack would read past end of buffer:-26 - error grpcomm_direct.c(359)

This is something that should be reported to the developers.
--------------------------------------------------------------------------
[radonc-phaser09:10168] [[46181,0],9] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
[radonc-phaser07:04255] [[46181,0],7] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
[radonc-phaser08:04197] [[46181,0],8] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
[radonc-phaser06:03039] [[46181,0],6] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
[radonc-phaser02:22175] [[46181,0],2] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
[radonc-phaser04.stanford.EDU:14714<http://radonc-phaser04.stanford.edu:14714>] [[46181,0],4] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
[radonc-phaser10:14505] [[46181,0],10] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
[phaser-manager:08309] 9 more processes have sent help message help-errmgr-base.txt / simple-message
[phaser-manager:08309] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

 Do you know what the issue might be?


____________________________________________________________________________________________________________________________



Eric F.  Alemany
Systems Administrator for Research
EXO Extended Operations

Stanford Medicine - Technology & Digital Services
Stanford, California 94305








On Nov 7, 2019, at 3:44 PM, Jeff Squyres <notifications@github.com<mailto:notifications@github.com>> wrote:

On Nov 7, 2019, at 10:15 AM, ealemany <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> Thank you for explaining in details how OpenMPI works. The mpirun command you had me run are great testing programs. All make sense and here is the output of the mpirun commands you suggested I tried. All of them worked well.

Excellent.

> Any suggestion as to why BEAM_FLASH_SCAN processes will not run?

Do you have the source code for it, or is it just a binary?

I ask because it looks like your Open MPI setup is working properly, but something in the application is failing.

If the application is source code and you compiled it against your Open MPI installation, then it's *probably* an error in the application somewhere. Standard C / Fortran debugging techniques apply.

If the application is an ISV binary, you might need to check what version of Open MPI it is expecting. E.g., if it's expecting Open MPI v3.0.x or v3.1.x, those are not ABI compatible with Open MPI v4.0.x. All manner of mayhem can go wrong if it's the wrong ABI.

--
Jeff Squyres
jsquyres@cisco.com<mailto:jsquyres@cisco.com>

**Comment by rhc54** [comment]
That almost always means that you have an older version of OMPI on the compute nodes than you have on the node where mpirun is being executed.

**Comment by ealemany** [comment]
That makes sense. So what I did I checked $ompi_info | head    on 4 nodes and they all have openMPI-4.0.1. The head-node/master-node where I run mpirun command also has openMPI-4.0.1
I modified my - -hostfile to only reflects the 4 nodes (with  openMPI-4.0.1)  and I then ran $ mpirun --hostfile /home/ompi/hostsfile4.0.1 -np 48 /media/homes/ompi/openmpi-4.0.1/examples/hello_c
And I got the error message "[radonc-phaser01:04291] [[46181,0],1] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355……………."

But when I run the same mpirun command  with 36 cores $ mpirun --hostfile /home/ompi/hostsfile4.0.1 -np 36 /media/homes/ompi/openmpi-4.0.1/examples/hello_c
I have the expected result
"Hello, world, I am 3 of 36, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser01 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)
Hello, world, I am 25 of 36, (Open MPI v4.0.1, package: Open MPI root@radonc-phaser05 Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019, 115)…………………………………"

Interesting isn’t it ?
____________________________________________________________________________________________________________________________



Eric F.  Alemany
Systems Administrator for Research
EXO Extended Operations

Stanford Medicine - Technology & Digital Services
Stanford, California 94305








On Nov 10, 2019, at 11:21 AM, Ralph Castain <notifications@github.com<mailto:notifications@github.com>> wrote:


That almost always means that you have an older version of OMPI on the compute nodes than you have on the node where mpirun is being executed.

**Comment by ealemany** [comment]
I uninstalled/removed  OpenMPI-4.0.1 on all nodes including the node where mpirun is being executed, downloaded and installed OpenMPI-4.0.2 from openmpi.org with 
'''shell
shell$ ./configure --prefix=/usr/local/.openmpi
'''
'''shell
shell$ make
'''
'''shell
shjell$ sudo make install all
'''
when i run the mpirun command with 36 cores (3 nodes)
'''shell
shell$ mpirun --hostfile /home/ompi/hostsfile -np 36  /media/homes/ompi/openmpi-4.0.2/examples/hello_c
'''
I got the expected results.

However when i run the mpirun command with 48 cores (4 nodes)
'''shell
shell$ mpirun --hostfile /home/ompi/hostsfile -np 48  /media/homes/ompi/openmpi-4.0.2/examples/hello_c
'''
I have the following error message
'''shell
shell$[radonc-phaser03:03700] [[40167,0],3] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
[radonc-phaser02:03451] [[40167,0],2] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
[radonc-phaser01:05602] [[40167,0],1] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[40167,0],1] FORCE-TERMINATE AT Data unpack would read past end of buffer:-26 - error grpcomm_direct.c(359)

This is something that should be reported to the developers.
--------------------------------------------------------------------------
[phaser-manager:02295] 2 more processes have sent help message help-errmgr-base.txt / simple-message
[phaser-manager:02295] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
'''

**Comment by rhc54** [comment]
I believe the problem here has to do with whether or not the launch message is being compressed. It appears there is a bug in there somewhere. When you tested the OMPI installation (per the instructions from @jsquyres), you only used 20 procs - hence, the message was small enough to fall under the threshold for compression. Larger runs (e.g., 48 procs) probably just cross that threshold.

Try configuring OMPI ```--without-zlib``` and see if that helps fix the problem.

**Comment by ealemany** [comment]
Do you mean to run ./configure like this:

./configure --prefix=/usr/local/.openmpi. - -without-zlib

____________________________________________________________________________________________________________________________



Eric F.  Alemany
Systems Administrator for Research
EXO Extended Operations

Stanford Medicine - Technology & Digital Services
Stanford, California 94305








On Nov 13, 2019, at 5:47 PM, Ralph Castain <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe the problem here has to do with whether or not the launch message is being compressed. It appears there is a bug in there somewhere. When you tested the OMPI installation (per the instructions from @jsquyres<https://github.com/jsquyres>), you only used 20 procs - hence, the message was small enough to fall under the threshold for compression. Larger runs (e.g., 48 procs) probably just cross that threshold.

Try configuring OMPI --without-zlib and see if that helps fix the problem.

**Comment by rhc54** [comment]
Yeah - use the same configure line as before but add ```--without-zlib``` to it

**Comment by ealemany** [comment]
Do you I need to uninstall OpenMPI-4.0.2 on the  4 nodes I already configured?

____________________________________________________________________________________________________________________________



Eric F.  Alemany
Systems Administrator for Research
EXO Extended Operations

Stanford Medicine - Technology & Digital Services
Stanford, California 94305








On Nov 13, 2019, at 8:59 PM, Ralph Castain <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah - use the same configure line as before but add --without-zlib to it

**Comment by rhc54** [comment]
You'll need to install the reconfigured version wherever it will be executed, yes. Usually one does that by installing to an NFS-mounted directory (instead of the system default directory that is purely local) and adding "--enable-orterun-prefix-by-default" to the configure line. Something like this:
```
./configure --prefix=<nfs>/ompi --enable-orterun-prefix-by-default --without-zlib
```
Then you prepend \<nfs>/ompi/bin to your PATH and \<nfs>/ompi/lib to your LD_LIBRARY_PATH and execute. This avoids having to install OMPI multiple times and avoids the issue of using different versions across the nodes.

**Comment by ealemany** [comment]
Thank you for the detailed instructions about installing OMPI via NFS-mounted directory. I read the instructions in https://www.open-mpi.org//faq/?category=building#easy-build “where should I install Open MPI” but the instructions are not as clear as yours.
I think I have been doing it wrong all this time by installing OMPI locally on each machine. I will follow your suggestion and reconfigured all the nodes.

Thank you again for your all your help on this project.
____________________________________________________________________________________________________________________________



Eric F.  Alemany
Systems Administrator for Research
EXO Extended Operations

Stanford Medicine - Technology & Digital Services
Stanford, California 94305








On Nov 14, 2019, at 7:32 AM, Ralph Castain <notifications@github.com<mailto:notifications@github.com>> wrote:


You'll need to install the reconfigured version wherever it will be executed, yes. Usually one does that by installing to an NFS-mounted directory (instead of the system default directory that is purely local) and adding "--enable-orterun-prefix-by-default" to the configure line. Something like this:

./configure --prefix=<nfs>/ompi --enable-orterun-prefix-by-default --without-zlib


Then you prepend <nfs>/ompi/bin to your PATH and <nfs>/ompi/lib to your LD_LIBRARY_PATH and execute. This avoids having to install OMPI multiple times and avoids the issue of using different versions across the nodes.

**Comment by rhc54** [comment]
Please reopen if you still have a problem.
