### ISSUE TITLE
libc++ version header conflict

### ISSUE THREAD

**Issue by isuruf** [open-mpi/ompi#7155]
From libc++ 8.0 and above, a header named `version` is included by libc++ headers and the file named `VERSION` in the root of this repo conflicts with it on case insensitive file systems. Can the file be renamed?

cc @minrk

**Comment by ggouaillardet** [comment]
does the conflict occur when building Open MPI ? (If so, could you please detail the environment so it can be reproduced and investigated ?)

or does it occur when you are compiling an enduser application ? (If so, which file(s) are causing the conflict? there are several `version.h` in the Open MPI source code, but only the `openshmem` one is installed by default)

**Comment by isuruf** [comment]
> does the conflict occur when building Open MPI ? (If so, could you please detail the environment so it can be reproduced and investigated ?)

Yes. Build failure occurs when building OpenMPI, not an end user application. This is on OSX 10.13 with a source build of clang 9.0.0 and libc++ 9.0.0 targeting OSX 10.9. Let me know if you need any more details. I've seen this error before in several packages with VERSION files in the repo root and can be reproduced if you use libc++>=8.0.0.

>  (If so, which file(s) are causing the conflict? there are several version.h in the Open MPI source code, but only the openshmem one is installed by default)

It's not the `version.h` files, but the `VERSION` file in the root of this repo that is the issue.

```
make[2]: Entering directory '/usr/local/miniconda/conda-bld/openmpi-mpi_1573512864370/work/ompi/mpi/cxx'
  CXX      mpicxx.lo
In file included from mpicxx.cc:24:
In file included from ./mpicxx.h:42:
In file included from /usr/local/miniconda/conda-bld/openmpi-mpi_1573512864370/_build_env/bin/../include/c++/v1/map:479:
In file included from /usr/local/miniconda/conda-bld/openmpi-mpi_1573512864370/_build_env/bin/../include/c++/v1/__tree:14:
In file included from /usr/local/miniconda/conda-bld/openmpi-mpi_1573512864370/_build_env/bin/../include/c++/v1/iterator:421:
In file included from /usr/local/miniconda/conda-bld/openmpi-mpi_1573512864370/_build_env/bin/../include/c++/v1/__functional_base:14:
In file included from /usr/local/miniconda/conda-bld/openmpi-mpi_1573512864370/_build_env/bin/../include/c++/v1/type_traits:417:
In file included from /usr/local/miniconda/conda-bld/openmpi-mpi_1573512864370/_build_env/bin/../include/c++/v1/cstddef:37:
../../../version:1:3: error: invalid preprocessing directive
# Copyright (c) 2008      Sun Microsystems, Inc.  All rights reserved.
  ^
../../../version:2:3: error: invalid preprocessing directive
# Copyright (c) 2008-2019 Cisco Systems, Inc.  All rights reserved.
  ^
../../../version:3:3: error: invalid preprocessing directive
# Copyright (c) 2011      NVIDIA Corporation.  All rights reserved.
  ^
../../../version:4:3: error: invalid preprocessing directive
# Copyright (c) 2013      Mellanox Technologies, Inc.
  ^
../../../version:5:27: error: invalid preprocessing directive
#                         All rights reserved.
                          ^
../../../version:6:3: error: invalid preprocessing directive
# Copyright (c) 2017      Los Alamos National Security, LLC.  All rights
  ^
../../../version:7:27: error: invalid preprocessing directive
#                         reserved.
                          ^
../../../version:8:3: error: invalid preprocessing directive
# Copyright (c) 2018      IBM Corporation.  All rights reserved.
  ^
../../../version:9:3: error: invalid preprocessing directive
# Copyright (c) 2018      Research Organization for Information Science
  ^
../../../version:10:27: error: invalid preprocessing directive
#                         and Technology (RIST).  All rights reserved.
                          ^
../../../version:12:3: error: invalid preprocessing directive
# This is the VERSION file for Open MPI, describing the precise
  ^
../../../version:13:3: error: invalid preprocessing directive
# version of Open MPI in this distribution.  The various components of
  ^
../../../version:14:3: error: invalid preprocessing directive
# the version number below are combined to form a single version
  ^
../../../version:15:3: error: invalid preprocessing directive
# number string.
  ^
../../../version:17:3: error: invalid preprocessing directive
# major, minor, and release are generally combined in the form
  ^
../../../version:18:3: error: invalid preprocessing directive
# <major>.<minor>.<release>.
  ^
../../../version:20:1: error: C++ requires a type specifier for all declarations
major=4
^
../../../version:20:8: error: expected ';' after top level declarator
major=4
       ^
../../../version:24:3: error: invalid preprocessing directive
# greek is generally used for alpha or beta release tags.  If it is
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by ggouaillardet** [comment]
thanks for the lengthy explanation, I now fully understand how the conflict occurs.

I will wait for inputs from other developers, since this is a quite a generic issue.
For example, the embedded `hwloc` and `openpmix` projects also feature a `VERSION` file in their root directory, and I guess many other projects do so.

An other approach would be **not** to have the root of the repo in the list of include directories.

Note the error is triggered by the C++ bindings ... that have been removed from the MPI standard more than 10 years ago (and are only built if Open MPI is configured with `--enable-mpi-cxx`), so a temporary workaround could be not to use this option.

**Comment by ggouaillardet** [comment]
@isuruf I issued #7156 in order to address this issue. If you get a chance, could you please confirm it works for you?

**Comment by jsquyres** [comment]
Given that #7156 died, perhaps the only other solution is to rename `VERSION` --> `VERSION.txt`.  Sigh.  How annoying!  😢 

Probably needs to go to v3.0.x, v3.1.x, v4.0.x.

**Comment by isuruf** [comment]
Opened https://github.com/open-mpi/ompi/pull/7163

**Comment by isuruf** [comment]
Thanks everyone

**Comment by jsquyres** [comment]
@isuruf Sorry this took so long -- it fell off our radar after November, and I only recently re-discovered the open PR.
