### ISSUE TITLE
wrong environment in Docker

### ISSUE THREAD

**Issue by Sunmon** [open-mpi/ompi#7157]
Thank you for taking the time to submit an issue!

## Background information
Found some problem while 'mpirun on docker'

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
openMPI 4.0.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Dockerfile
COPY ./openmpi-docker /openmpi-docker (# same as (https://github.com/open-mpi/ompi/archive/master.zip))
WORKDIR /openmpi-docker
RUN ./configure --prefix="/usr/local/openmpi"
RUN make install
RUN apt-get install -y openssh-client

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04.3 LTS, Docker 19.03.2
* Computer hardware: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
* Network type: Not use

-----------------------------

## Details of the problem

There are some problems on mpi when running on the docker.
I think mpi does not notice container environment.
Here are not-working commands I found:
- np
- --cpu-set
- --bind-to core

### How to test

1. build image by using dockerfile
2. `docker run -it --cpuset-cpus="1,2" [openmpiImg]  //only use cpu1, cpu2
3. command
   3.1. mpirun --allow-run-as-root -np 4 [example.out]
   3.2. mpirun --allow-run-as-root --cpu-set 0,1 [example.out]
   3.3. mpirun  --allow-run-as-root --bind-to coe [example.out]

- -np option: 
np %d is bigger than cpuset. So it has to print 'slot error' but I does not.

- --cpu-set:
docker container did not allowed to use cpu0. So, when I check cpu usage by `htop`, I can found that only cpu1 is running.
But running with this command `mpirun --allow-run-as-root --cpu-set 0 [example.out], it causes error and eventually use both cpus, number cpu 1 and cpu 2.

- --bind-to core:
when I use --bind-to core option, it prints error

---

All above problems does not appear when using cgroup.. Only appears on docker.
I fixed the `-np` bug, but it is a temporary measure. (I will pull request)

**Comment by rhc54** [comment]
@bgoglin 

I believe the problem here is that root may not be constrained to the designated cpus. Thus, hwloc sees all cpus as available. However, I defer to Brice.

**Comment by bgoglin** [comment]
(should have posted this here instead of in the PR)
@Sunmon hwloc already supports cgroups, so things should work fine. One thing that isn't supported in current releases is Linux cgroups v2 (I added it to git a couple weeks ago), but your problem seems to involve cgroups v1 only.
Can you run hwloc-gather-topology inside that docker and send the generated tarball to me (brice.goglin@inria.fr) so that I try to debug why it fails here?
Otherwise the output of lstopo when hwloc is configured with --enable-debug would also be helpful.

**Comment by bgoglin** [comment]
By the way, make sure the container has the cgroup mount point in /proc/mounts, otherwise we have no way to find out where the cgroup information is (we cannot hardwire /sys/fs/cgroup/cpuset as your patch does).

**Comment by bgoglin** [comment]
@Sunmon ping ?

**Comment by Sunmon** [comment]
@bgoglin Thanks. I was too busy to reply and did not know you are waiting... so sorry. I will close the Issue. Thank you for sharing your opinion.

**Comment by bgoglin** [comment]
@sunmon Well it would be nice if you could answer my questions above or let us know how you fixed this issue.
