### ISSUE TITLE
MPI_Dims_create returns unexpected result for odd square numbers.

### ISSUE THREAD

**Issue by aw32** [open-mpi/ompi#7186]
OpenMPI 4.0.2 on Arch Linux

The documentation for MPI_Dims_create says:
`The dimensions are set to be as close to each other as possible, using an appropriate divisibility algorithm.`
However, the function returns (25,1) for 25, while the expected result is (5,5).
It seems like the factorization algorithm in `ompi/mpi/c/dims_create.c` stops too early.
Maybe it should run while d < sqrtnum+2 or d < sqrtnum+4.
https://github.com/open-mpi/ompi/blob/119b1c312e11ee956841a9552ea4f49ac6141549/ompi/mpi/c/dims_create.c#L243
This is even mentioned in the following comment.
https://github.com/open-mpi/ompi/blob/119b1c312e11ee956841a9552ea4f49ac6141549/ompi/mpi/c/dims_create.c#L249

Example:
```c
#include <stdio.h>
#include <mpi.h>
int main(int argc, char **argv) {
  MPI_Init(NULL, NULL);
  int dims[2] = {0,0};
  MPI_Dims_create(25, 2, dims);
  printf("%d %d\n", dims[0], dims[1]);
  MPI_Finalize();
  return 0;
}
```

**Comment by hppritcha** [comment]
Closed via #7296 and #7189
