### ISSUE TITLE
cant get /opt/mpi/bin/mpiexec -f nodesips -n 2 python test.py to work

### ISSUE THREAD

**Issue by Conan-Wolf** [open-mpi/ompi#7187]
the file i have all the ips of the nodes are in nodesips the hostnames of the pi's are Slave1-3 with the master being called Master

version 3.1.3

i followed this website's tut https://raspberrytips.com/raspberry-pi-cluster/

* Operating system/version: Raspbian/Debian-based
* Computer hardware: raspberrypi 4 
* Network type: LAN cat6

```HYDU_sock_connect (/opt/mpi-dl/mpich-3.3/src/pm/hydra/utils/sock/sock.c:145): unable to get host address for Master (4)
[proxy:0:0@Slave1] main (/opt/mpi-dl/mpich-3.3/src/pm/hydra/pm/pmiserv/pmip.c:183): unable to connect to server Master at port 40677 (check for firewalls!)

**Comment by hjelmn** [comment]
Error message shows mpich hydra not Open MPI.

**Comment by ggouaillardet** [comment]
This is a MPICH error message, and this project is Open MPI. Make sure you do not mix libraries/executables from both implementations.

**Comment by Conan-Wolf** [comment]
oh crap... sorry about that
