### ISSUE TITLE
"There was an error initializing an OpenFabrics device" on Mellanox ConnectX-6 system

### ISSUE THREAD

**Issue by mkre** [open-mpi/ompi#7188]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

3.1.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

from a source tarball

### Please describe the system on which you are running

* Operating system/version: CentOS 7.6, MOFED 4.6
* Computer hardware: Dual-socket Intel Xeon Cascade Lake
* Network type: Mellanox IB ConnectX-6

-----------------------------

## Details of the problem

Hi,

we get the following warning when running on a CX-6 cluster:
```
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   wvhpc02n018
  Local device: mlx5_0
--------------------------------------------------------------------------
```

We are using `-mca pml ucx` and the application is running fine. The warning message seems to be coming from BTL/openib (which isn't selected in the end, because UCX is available). However, even when using BTL/openib explicitly using 

```
-mca btl_openib_warn_no_device_params_found 0 -mca pml cm -mca btl self,vader,openib -mca pml_base_verbose 100 -mca btl_base_verbose 100 -mca mca_base_verbose 100 -mca btl_openib_verbose true
```

, the application is running fine despite the warning (log: [openib-warning.txt](https://github.com/open-mpi/ompi/files/3878544/openib-warning.txt)).

Is there a way to silence this warning, other than disabling BTL/openib (which seems to be running fine, so there doesn't seem to be an urgent reason to do so)? 

Is there a known incompatibility between BTL/openib and CX-6? If that's the case, we could just try to detext CX-6 systems and disable BTL/openib when running on them.

Thanks,
Moritz

**Comment by gpaulsen** [comment]
Hello.  Thanks for posting this issue.
ConnextX-6 support in openib was just recently added to the v4.0.x branch (i.e. not in the latest v4.0.2 release)
It's currently awaiting merging to v3.1.x branch in this Pull Request:
https://github.com/open-mpi/ompi/pull/7179

**Comment by mkre** [comment]
Thanks. As the warning due to the missing entry in the configuration file can be silenced with `-mca btl_openib_warn_no_device_params_found 0` (which we already do), I guess the other warning which we are still seeing will be fixed by including the `case 16` in the bandwidth calculation in `common_verbs_port.c`. 

As there doesn't seem to be a relevant MCA parameter to disable the warning (please correct me if I'm wrong), we will have to disable BTL/openib if we want to avoid this warning on CX-6 while waiting for Open MPI 3.1.6/4.0.3. 

I guess this answers my question, thank you very much!

**Comment by jsquyres** [comment]
Or you can use the UCX PML, which is Mellanox's preferred mechanism these days.

That being said, 3.1.6 is likely to be a long way off -- if ever.  We'll likely merge the v3.0.x and v3.1.x versions of this PR, and they'll go into the snapshot tarballs, but we are not making a commitment to ever release v3.0.6 or v3.1.6.

**Comment by mkre** [comment]
> Or you can use the UCX PML, which is Mellanox's preferred mechanism these days.

Sure, this is what we do. However, the warning is also printed (at initialization time I guess) as long as we don't disable OpenIB explicitly, even if UCX is used in the end.

**Comment by jsquyres** [comment]
Sorry -- I just re-read your description more carefully and you mentioned the UCX PML already.

Could you try applying the fix from https://github.com/open-mpi/ompi/pull/7179 to see if it fixes your issue?  Ironically, we're waiting to merge that PR because Mellanox's Jenkins server is acting wonky, and we don't know if the failure noted in CI is real or a local/false problem.

**Comment by mkre** [comment]
> Could you try applying the fix from #7179 to see if it fixes your issue?

Yes, I can confirm: No more warning messages with the patch.

**Comment by RobbieTheK** [comment]
LMK is this should be a new issue but the `mca-btl-openib-device-params.ini` file is missing this Device vendor ID:
```
  Device name:           mlx5_0
  Device vendor ID:      0x02c9
  Device vendor part ID: 4123

```
In the updated .ini file there is `0x2c9` but notice the extra 0 (before the 2)

This is on OpenMPI 4.1.1 in RHEL 8.

**Comment by bwbarrett** [comment]
@RobbieTheK if you don't mind opening a new issue about the params typo, that would be great!

**Comment by RobbieTheK** [comment]
> @RobbieTheK if you don't mind opening a new issue about the params typo, that would be great!

I found

**Comment by jsquyres** [comment]
@RobbieTheK Go ahead and open a new issue so that we can discuss there.  That's better than continuing a discussion on an issue that was closed ~3 years ago.  Thanks!
