### ISSUE TITLE
Checkpoint/restart hangs with MPI_ANY_SOURCE and MPI_ANY_TAG

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#72]
The default CRCP (checkpoint/restart coordination protocol) component (bkmrk) does not properly handle `MPI_ANY_SOURCE` and `MPI_ANY_TAG` as discussed in ticket #1619.

So applications that depend on these two MPI keys may see occasional hangs while checkpointing. This is due to a mishandling of bookmark data in these two cases.

This ticket replaces #1619 as a more precise definition of the problem.

**Comment by jjhursey** [comment]
The C/R code has been removed from the current master and all current releases. I'm going to close this bug for now.
