### ISSUE TITLE
Communicator Split Type NUMA Behavior

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#7214]
See thread on user list:

https://www.mail-archive.com/users@lists.open-mpi.org/msg33589.html

related to #7201

**Comment by jsquyres** [comment]
v3.0.x/v3.1.x release manager decision: we will not be bringing this fix back to the v3.0.x or v3.1.x branches.  The fix for this will only be on v4.0.x and forward.

**Comment by gpaulsen** [comment]
I believe https://github.com/open-mpi/ompi/pull/7201 is  intended to resolve this Issue.
