### ISSUE TITLE
Incorrect bindings of nodes to user-hostlist when using the Slurm allocation

### ISSUE THREAD

**Issue by karasevb** [open-mpi/ompi#7234]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
git clone from master
commit cf9a5fb06c71188a2312b37a0a5da33af733604d

-----------------------------

## Details of the problem

The problem reproduces when `mpirun` uses under Slurm allocation and concurrently uses the user hostlist (-H, --hostfile, etc..): orte daemons use node indexes according to nodes in Slurm allocation, but a user-provided list has its own indexes which are not matching with the Slurm's list. That leads to mismatching in procs bindings.

```shell
shell$ salloc -N4 
salloc: Granted job allocation 4
shell$ sinfo 
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
debug*       up   infinite      4  alloc cn[1-4]
shell$ cd ompi/master/examples/

// the order of nodes (`-H cn1,cn2`) matches to the Slurm allocation [1] 
shell$ mpirun -n 2 --map-by node --bind-to core -H cn1,cn2 --report-bindings ./hello_c
[cn2:03032] MCW rank 1 bound to socket 0[core 0[hwt 0]]: [B/.]
[cn1:03259] MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/.]

// the order of user-nodelist ('-H cn1,cn4') does not match the allocation [2]
shell$ mpirun -n 2 --map-by node --bind-to core -H cn1,cn4 --report-bindings ./hello_c
[cn1:03241] MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/.]
[cn4:03166] MCW rank 1 not bound
```
Case [1] works well. But in the case [2], compute nodes inited with `ORTE_PROC_MY_NAME->vpid = vpid + slurm_nodeid;`, where `cn1` gets` ORTE_PROC_MY_NAME->vpid = 1`, and `cn4` gets `ORTE_PROC_MY_NAME->vpid = 2`:
https://github.com/open-mpi/ompi/blob/cf9a5fb06c71188a2312b37a0a5da33af733604d/orte/mca/ess/slurm/ess_slurm_module.c#L165-L166
The problem arise here:
https://github.com/open-mpi/ompi/blob/cf9a5fb06c71188a2312b37a0a5da33af733604d/orte/mca/rmaps/base/rmaps_base_binding.c#L765-L772
At this point `jdata->map->nodes->size` is 4 and `jdata->map->nodes` contains cn[1-4] nodes with indexes 1-4  (as provided by Slurm allocation), that does not match with local index for node `cn4` in line: https://github.com/open-mpi/ompi/blob/cf9a5fb06c71188a2312b37a0a5da33af733604d/orte/mca/rmaps/base/rmaps_base_binding.c#L770
Because local node `cn4` has `ORTE_PROC_MY_NAME->vpid = 2` that corresponds to the node index = 2 gotten for node `cn2` (according to Slurm allocation) that leads to incorrect bindings

I note that all compute nodes get a full node-list corresponded to the Slurm allocation independently of which nodes are involved or not in this job. Probably `mpirun` should not propagate nodes to orted daemons which not involved in the job.

The simple way to avoid this problem is disabling to use the Slurm allocation hostlist by adding `-mca ras ^slurm`, but this option makes sense to use only when to have a user-provided hostlist. In this case, the orte daemons get only the node-list in which the nodes involving in the current job.

**Comment by jsquyres** [comment]
@karasevb Do you have a code-based suggestion for how to fix this?

Remember, we're now living in a Post-Ralph World (PRW): it's up to us to fix these kinds of issues now...

**Comment by karasevb** [comment]
@artpol84 FYI

**Comment by artpol84** [comment]
> @karasevb Do you have a code-based suggestion for how to fix this?
Remember, we're now living in a Post-Ralph World (PRW): it's up to us to fix these kinds of issues now...

@jsquyres, we will check our resource availability.
But, in general, given that ORTE is being replaced with PRRTE, does it makes sense to spend time fixing this? I recall from telecon's that PRRTE doesn't have binding feature (but it wasn't 100% then)

@karasevb it is important to make sure which versions of OMPI are affected. v4.x?

**Comment by rhc54** [comment]
PRRTE definitely supports binding on a per-job basis. Might be worth checking PRRTE master to see if the problem exists there (likely does) - if so, fixing it on that side would make sense though it would be harder to backport to earlier versions of OMPI.

**Comment by jladd-mlnx** [comment]
@karasevb please check if this issue exists in 4.x.

**Comment by rhc54** [comment]
Closing as this doesn't seem relevant any longer.
