### ISSUE TITLE
Update CUDA / Ompipath FAQ docs

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7240]
From https://www.mail-archive.com/devel@lists.open-mpi.org/msg20994.html:

> I recently figured out that when running multi-GPU MPI application (one MPI process to one GPU) on a computer using Intel Omni-Path, you need to do the GPU binding before MPI initialization, according to Intel documentation. If this seems correct to you, could you update your "Running CUDA-aware" web page accordingly ? This would help people to know what is the correct order.
> 
> Sincerely
> Thomas

@Akshay-Venkatesh @mwheinz Can one of you do this?  Thanks.

**Comment by mwheinz** [comment]
Okay. I'm looking into "best practices" now.

**Comment by mwheinz** [comment]
Should this issue be in https://github.com/open-mpi/ompi-www/issues ?

**Comment by jsquyres** [comment]
Er -- ya, I probably should have filed it there, sorry.

Regardless, if you file a PR in ompi-www, you can say "Fixes <full URL of this issue>" and it will close this issue when you merge the PR.

**Comment by mwheinz** [comment]
I've created a pull request, https://github.com/open-mpi/ompi-www/pull/289 but I don't seem to be able to add reviewers to it, so I'm leaving this note here as a heads-up.
