### ISSUE TITLE
TCP BTL tries binding to address already in use

### ISSUE THREAD

**Issue by wckzhang** [open-mpi/ompi#7246]
Running osu microbenchmark 5.6.2 collective osu_alltoall using the TCP BTL with 2304 MPI processes on 64 nodes causes the following error on message sizes >= 256:
```
[1,32]<stderr>:[ip-172-31-5-242][[9856,1],32] btl_tcp_endpoint.c:733:mca_btl_tcp_endpoint_start_connect] bind on local address (172.31.5.242:0) failed: Address already in use (98)
```
This occurs on Open MPI 3.1.4, 4.0.2, and master.

Open MPI was installed from a git clone, and also preinstalled.

This is running on Amazon Linux.

My mpirun command is as follows:

```shell
$ mpirun --tag-output -mca pml ob1 -mca btl tcp,self -np 2304 -N 36 /scratch/install/libexec/osu-micro-benchmarks/mpi/collective/osu_alltoall -i 1 -m 256: -x 0
```
I've been told this has been reproduced with half the number of MPI processes, but have not been able to test it. Also does not fail gracefully, just hangs.

**Comment by wckzhang** [comment]
The cause of this problem is that OpenMPI has used all available ephemeral ports, thus failed to open more ports.

Details is like the following:
mca_btl_tcp_endpoint_send() is called to send a piece of message. It will call mca_btl_tcp_endpoint_start_connect() to establish a connection.

mca_btl_tcp_endpoint_start_connect() will then call bind() to bind to a socket. In the call to bind(), port was set to 0, which allow system to randomly pick an available port defined in /proc/sys/net/ipv4/ip_local_port_range

The range defined in /proc/sys/net/ipv4/ip_local_port_range is between 32768 and 60999, which means there are 28,231 ports can be used.

In the case of alltoall() on 1,152 processes, I can see that all of these 28,231 ports have been used, which caused the call to bind() to fail, hence the error message:

```mca_btl_tcp_endpoint_start_connect] bind on local address (172.31.11.43:0) failed: Address already in use (98)```

**Comment by wckzhang** [comment]
Unfortunately, as discussed in the open mpi 2020 02 meeting, as a community, we have decided not to fix this issue.

**Comment by geligeli** [comment]
Is there a suggested workaround for this? Or will alltoall just not be supported with many ranks over tcp?

**Comment by bosilca** [comment]
Keep in mind what you are trying to do, an all-to-all with multiple processes per node. Due to the communication pattern, each of the processes will try to create a connection with each other process (minus the ones on the local node but let's ignore this for now), and this connection establishment will requires a port. So if you have c processes per node on a job of p processes, this will require at least c*(p-c) available ports per node.

Going back to your case, 2304 processes on 64 nodes means 36 processes per node. Thus, each node will need at least 36*(2304-26) ports available, aka. about 83k ports, way above what is usually available. 
 
As a workaround, make sure your setup falls below the maximum available ports. Keep in mind that these ports are also used by other apps/daemons/services, including our RTE, so you will need to give them some slack.

**Comment by geligeli** [comment]
What I don't get is that in my case, MPI_alltoall() with a single MPI_INT sent from each rank to each rank works fine (sending sizes of data about to be sent). But when I actually send the payload with MPI_alltoallv then I hit the port exhaustion issue. Why would alltoall work?

**Comment by ggouaillardet** [comment]
@geligeli by default, collectives are provided by the `coll/tuned` component.
Under the hood, it selects the fastest algorithm based on communicator and message size.

In your case, I suggest you manually force the `bruck` algorithm.
This is not the fastest algorithms, but it requires less connections so
 - you will not reach the limit
 - even if you could push that limit, less connections means a faster "initialization" time (e.g. the very first `MPI_Alltoall()` in which most connections are established will be faster)

**Comment by geligeli** [comment]
So i looked and it seems MPI_alltoallv only supports `basic linear` and `pairwise` as algorithms

(ompi_info --param coll tuned -l 9 | grep alltoallv)

Now i tried several things to limit the number of concurrent connections:

a) Staggered alltoallv where for each invocation only a subset of ranks take part in the alltoallv.
b) Manual implementation for alltoall by doing several MPI_isend / MPI_recv manually.

in both cases i eventually hit the port exhaustion bug which is super frustrating. Is it possible that one a connection rank-a <-> rank-b is established it's kept forever? Or are the ports eventually freed again? Can this be forced?

**Comment by bosilca** [comment]
Connections are opened because processes need to communicate, for as long as you keep the same communication pattern (Alltoall with variable sizes) there is nothing you can do to reduce the number of needed connections. Moreover, once a connection is opened we keep it up until MPI_Finalize, so there is no recycling of the ports.

The only potential solution I see come from your setup and/or application. Can you move your app to a different setup ? Less nodes or at least less processes per node ? Can you change the communication pattern ?

**Comment by athota** [comment]
> It's possible that you could use a different communication component though, iirc UCX has TCP support on by default for example.

I have been following this thread and tried the UCX suggestion; without any customization, with UCX, the alltoall run fails at message sizes above 65536. I also noticed that the run is 10X slower compared to a standard OpenMPI without UCX. 

Limiting the UCX run to just one specific interface (the fastest available), the run fails at message sizes above 256 again. 

Some more background: we are hitting this issue when running across four nodes, each with two 64 core AMD Rome CPUs. That is overall only 512 processes. It sounds like there is not much else to try or do, but it is super unfortunate that there is no workaround for this. 

I am not running into this issue when using MVAPICH, so we are looking into migrating everything to MVAPICH.

**Comment by bosilca** [comment]
Setting apart the issue with UCX, are you saying that with MVAPICH you do not have the issue with the number of ports ? This is really curious.

**Comment by athota** [comment]
That is right, standard MVAPICH build with osu_alltoall. The MVAPICH job is still running though, successful up to message size 524288 and no errors so far.

**Comment by bosilca** [comment]
That is interesting. I revisited the entire discussion again, and something does not look right to me. If the issue was really the lack of ports, it should not have worked for any size, but your original message somehow implies that it worked for messages below 256 bytes. Is that true ?

Have you tried to restrict the number of interfaces used by Open MPI (using --mca btl_tcp_if_include eth0, or CIDR) ?

**Comment by athota** [comment]
That is true, the alltoall run works for messages up to 256 with standard OpenMPI. And up to message sizes 65536 with OpenMPI+UCX. So message sizes 1, 2, 4, 8, ... 256 all work, 512 fails. 

I tried restricting OpenMPI to a single interface( the fastest available), that did not help. The openmpi-mca-params.conf file had this one line that is not commented out when this was tried: 
btl_tcp_if_exclude = lo,eno0,eno1

**Comment by bosilca** [comment]
Can you leave just one interface in there. You don't need lo, as OMPI will use shared memory for intranode communications. Thus, you need to set the BTL appropriately, --mca BTL tcp,self,vader (or tcp,self,sm depending on the version you are testing with).

**Comment by athota** [comment]
I think that is what I tried to do, with "btl_tcp_if_exclude = lo,eno0,eno1" I am excluding lo, eno0, eno1 right? That leaves just enp33s0, which is what we want to use. Or am I missing something? 

Also, specifying "--mca BTL tcp,self,vader" on the command line did not change anything. 

The MVAPICH job completed successfully btw, all the way up to a message size of 1048576.

**Comment by ggouaillardet** [comment]
@athota `--mca btl_tcp_if_include enp33s0` leaves no room for error.

The initially reported issue was with `MPI_Alltoall()`. Did you force the `bruck` algorithm and did it help?

**Comment by bosilca** [comment]
I'll be back next week, and I'll run some test to see how many ports we are currently using. I think I know the answer on the BTL side, but I wonder if the issue is not that we are sharing the available ports with PRRTE.

**Comment by athota** [comment]
> @athota `--mca btl_tcp_if_include enp33s0` leaves no room for error.
Tried this just now, no change in behavior, failed at message size above 256. 

> The initially reported issue was with `MPI_Alltoall()`. Did you force the `bruck` algorithm and did it help?
I am using the alltoall benchmark from the OSU microbenchmarks and I don't know what algorithm they are using to implement this. The original reporter of the issue was running this https://www.ics.uzh.ch/~teyssier/ramses/RAMSES.html when they ran into this error.

**Comment by wckzhang** [comment]
Using the benchmark just calls the MPI API. You want to change the algorithms by setting a couple mpirun flags:

```
--mca coll_tuned_use_dynamic_rules 1 --mca coll_tuned_allgather_algorithm 3
```

The alltoall algorithms are (where 0 is default - tuned):
```
static const mca_base_var_enum_value_t alltoall_algorithms[] = {                
    {0, "ignore"},                                                              
    {1, "linear"},                                                              
    {2, "pairwise"},                                                            
    {3, "modified_bruck"},                                                      
    {4, "linear_sync"},                                                         
    {5, "two_proc"},                                                            
    {0, NULL}                                                                   
};
```

**Comment by athota** [comment]
Tried this just now, fails at the same spot with the same error again.

**Comment by mkasemer** [comment]
I hate to reply to such an old thread, but I have a similar issue and I want to confirm that it is the same (and if so if there is, seemingly, no fix).

On a system with 16x64 cores, jobs submitted via Slurm:
```
#!/bin/bash
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=64

mpirun --mca pml ob1 --mca btl self,tcp,vader --bind-to core --mca btl_tcp_if_include eno1np0 --mca btl_tcp_links 1 -np $SLURM_NTASKS binary
```

This is giving errors from every node:
```
...
[cn8][[311,1],510][../../../../../../opal/mca/btl/tcp/btl_tcp_endpoint.c:730:mca_btl_tcp_endpoint_start_connect] bind on local address (10.115.79.16:0) failed
: Address already in use (98)
...
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    accept failed
But I couldn't open the help file:
    /usr/share/openmpi/help-mpi-btl-tcp.txt: Too many open files.  Sorry!
--------------------------------------------------------------------------
```

However, I am able to successfully submit 2 jobs on 8x64 processors simultaneously (thus filling the whole system).

Thanks for any further insight.

**Comment by bosilca** [comment]
My reading of this output is that the root cause is too many open files preventing the TCP BTL from opening new sockets. The error message generated by the BTL TCP is unfortunately not very clear, but you can see the "Too many open files" part toward the end.

You have 64 processes per node, each potentially opening one socket with every other non-local peer. Thus that means `64 * (15 * 64 * 1)` sockets opened per node, which is quite a significant number (~62k), leaving little room for other processes. Increase the limit, or ask your sysadmin to do so.

**Comment by mkasemer** [comment]
Naive question: but how would I go about increasing the limit (or checking the current limit)?

**Comment by bosilca** [comment]
`ulimit -n` shows the limit of files descriptors, `ulimit -a` shows more info. I don't know a standard way to increase this limits, it will depend on the distro. You might either have to manually change it in /etc/security/limits.conf or /etc/sysctl.conf, or use `sysctl -w fs.file-max=***`, or something else. The only constant here is that this operation need to be done as root.

**Comment by mkasemer** [comment]
Alright, I've raised the hard and soft number of open files limit on all nodes via `/etc/security/limits.conf` with `* - nofile 999999`. No longer am I getting any "too many open files" errors, but I am still getting similar errors to above. I've attached the full log file (from job number 500). Head node is named "cauchy", while compute nodes are named "cn1" through "cn16".

[error.500.txt](https://github.com/open-mpi/ompi/files/13895013/error.500.txt)

**Comment by ggouaillardet** [comment]
By default, Open MPI will use all the available interface pairs between two processes.

What if you restrict the traffic to a single interface, for example
```
mpirun --mca btl_tcp_if_include eth0 ...
```

you can double check how many ports can be used on a node with
```
sysctl net.ipv4.ip_local_port_range
```
so make sure there range is wide enough.

**Comment by mkasemer** [comment]
Regarding your first point, I believe we are restricting to a single interface (but again, I'm a relatively naive user, so correct me if I am misunderstanding):
```
#!/bin/bash
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=64

mpirun --mca pml ob1 --mca btl self,tcp,vader --bind-to core --mca btl_tcp_if_include eno1np0 --mca btl_tcp_links 1 -np $SLURM_NTASKS binary
```

Regarding the second point, I think you are on to something:
```
net.ipv4.ip_local_port_range = 32768	60999
```
So, only 28231 ports in range. From @bosilca 's above comment, should I interpret that to mean that we need `64 * (15 * 64 * 1) = 61440` ports in range on each node?

**Comment by ggouaillardet** [comment]
Yep, have your sysadmin make a wider port range (e.g. `1025 - 65535`)

**Comment by jsquyres** [comment]
If someone ends up here in the future, please open a new issue (and possibly refer to this one) rather than extending this old issue.  Thanks!
