### ISSUE TITLE
Problem with vprotocol pessimist...

### ISSUE THREAD

**Issue by blindFS** [open-mpi/ompi#7247]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

4.0.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

homebrew / source code of v4.0.2 / os distribution package of docker image ubuntu 18.04

### Please describe the system on which you are running

* Operating system/version: macos
* Computer hardware: x86
* Network type: localhost/docker bridge

-----------------------------

## Details of the problem

I'm not sure how to use the message logging feature of vprotocol pessimist.

`mpirun -n foo -mca vprotocol pessimist -mca pml_v_output stdout -mca pml_v_verbose 100 bar` always show this kind of info:

```
[9bbe1c696cac:00016] vprotocol_pessimist: component_init: threads are enabled, and not supported by vprotocol pessimist fault tolerant layer, will not load
```

I've tried to recompile ompi with several different configurations, just can't get rid of pthread support,  according to `ompi_info |grep -i thread`:

```
Thread support: posix (MPI_THREAD_MULTIPLE: yes, OPAL support: yes, OMPI progress: no, ORTE progress: yes, Event lib: yes)
```

Any ideas of vprotocol pessimist might be helpful, thanks!

**Comment by bosilca** [comment]
Something changed in the PML initialization sequence that broke the interception mechanism used by the PML V (the one that handle the vprotocols). Until we find a more suitable solution, a quick workaround is to change the static initialization of pml_v_enable_mpi_thread_multiple to 0 in ompi/mca/pml/v/pml_v_component.c line 65 (in master).

**Comment by blindFS** [comment]
@bosilca thanks for your quick reply. I've tried the fix, it does help to pass the sanity check, 😃.

One final question, where do I suppose to find the logged info?  By `-mca pml_v_output stdout` I'm hoping to inspect the info directly, `-output-filename foo` doesn't help neither.

I am running the default ring_c.c in ${PROJ}/examples (which invokes MPI_Send/Recv) in a docker bridged mini cluster with 4 nodes.
As far as I can see, there's no additional info with pessimist enabled.

**Comment by blindFS** [comment]
I finally managed to get what I want through these modifications:
``` diff
--- openmpi-4.0.2/ompi/mca/pml/v/pml_v_component.c	2019-10-08 02:20:48.000000000 +0800
+++ ompi_src/ompi/mca/pml/v/pml_v_component.c	2019-12-19 11:57:30.000000000 +0800
@@ -59,7 +59,7 @@
 };
 
 static bool pml_v_enable_progress_treads = OPAL_ENABLE_PROGRESS_THREADS;
-static bool pml_v_enable_mpi_thread_multiple = 1;
+static bool pml_v_enable_mpi_thread_multiple = 0;
 
 static char *ompi_pml_vprotocol_include_list;
 static char *ompi_pml_v_output;
--- openmpi-4.0.2/ompi/mca/pml/v/pml_v_output.h	2019-10-08 02:20:48.000000000 +0800
+++ ompi_src/ompi/mca/pml/v/pml_v_output.h	2019-12-19 16:05:13.000000000 +0800
@@ -74,7 +74,8 @@
     va_start(list, fmt);
     ret = vasprintf(&str, fmt, list);
     assert(-1 != ret);
-    opal_output_verbose(V, mca_pml_v.output, "%s", str);
+    // opal_output_verbose(V, mca_pml_v.output, "%s", str);
+    opal_output_verbose(-1000, 0, "%s", str);
     free(str);
     va_end(list);
 }
--- openmpi-4.0.2/opal/include/opal_config.h.in	2019-10-08 02:23:49.000000000 +0800
+++ ompi_src/opal/include/opal_config.h.in	2019-12-19 16:15:07.000000000 +0800
@@ -2298,7 +2298,7 @@
 #undef OPAL_ENABLE_CRDEBUG
 
 /* Whether we want developer-level debugging code or not */
-#undef OPAL_ENABLE_DEBUG
+// #undef OPAL_ENABLE_DEBUG
 
 /* Whether we want to enable dlopen support */
 #undef OPAL_ENABLE_DLOPEN_SUPPORT
```

I'd like to know whether there's a more proper way to make this happen.
Feel free to close this issue if it's not important.

**Comment by bosilca** [comment]
I am not sure I understand what you are trying to achieve here, but the debug information will not give you anything related to the communications in your application. The PML V dumps the message logs into a shared memory file, mapped onto the temporary Open MPI directory. The pattern os the filename is ${TMP}/ompi.${NODE}/pid.${PID}/x/y/vprotocol_pessimist-senderbased.

I have a solution to your problem, I will post a PR later today.

**Comment by blindFS** [comment]
A log file will be perfect for me. But I've checked these paths:
```
/tmp
/var/tmp
${HOME}/.tmp
/var/log
```
There's no ompi related files. My os is a ubuntu 18.04 based docker image.
Besides, I'd like to specify the pessimist log directory.

Looking forward to your PR, many thanks!

**Comment by bosilca** [comment]
First try to find the OMPI tmp directory, that should mostly be located in /tmp. The name of this directory is ompi.${NODENAME}.${PID}. Once you have this directory and the vprotocol is correctly enabled (using your command from above) you should be able to search for a file starting with `vprotocol*` (```find . -name vprotocol*```).

**Comment by blindFS** [comment]
Great, thanks!
