### ISSUE TITLE
Use letsencrypt for https

### ISSUE THREAD

**Issue by dns2utf8** [open-mpi/ompi#7251]
Hi all

I noticed #1922 is still open today. Using [letsencrypt](https://letsencrypt.org/) could solve the problem by providing free certificates.

Cheers,
Stefan

**Comment by jsquyres** [comment]
Thanks for the suggestion.  See my explanation on https://github.com/open-mpi/ompi/issues/1922#issuecomment-567226706 -- we're using a AWS, a CDN, and the certificate management built into that system.  It would be difficult to use letsencrypt.

**Comment by jsquyres** [comment]
Per https://github.com/open-mpi/ompi/issues/1922#issuecomment-567228774, I think I was incorrect: we _do_ use LetsEncrypt for our non-CDN sites.

I'll close this issue, and we'll keep following up on #1922 for whatever is wrong with the naked domain name https site.
