### ISSUE TITLE
OpenMPI/Rmpi seems to result in slaves stuck to default binding

### ISSUE THREAD

**Issue by rsettlage** [open-mpi/ompi#7295]
## Background information

I think this is ultimately more of a question than a bug report at this point.  I don't see how to tag this as a question on my side.

I am running Centos 7, Slurm 17.11, Intel 18.2 (or GCC 7.0.3), OpenMPI 4.0.1, R 3.6.1 and finally Rmpi 0.6-9.

The basic behavior is that I start up R, spawn some R slaves, and those slaves spawn an openmp process.  Based on the number of slaves spawned, I am stuck into the default OpenMPI binding, ie the Rslaves are stuck to a core or socket binding for 2 or 3+ slaves.  I THINK the issue is on the Rmpi side, but I am not sure how to verify this.  And of course, having SLURM in the mix makes me suspicious of that as well.

Here is what I see (simplifying the output a bit):

```
2 Rslaves spawned:
mpirun -np 1 --bind-to none --hostfile hostfile --mca mpi_warn_on_fork 0 --mca btl_openib_allow_ib 1 --map-by ppr:1:node --report-bindings --mca ras ^slurm Rscript omp_test_S2.R
[ca235:18923] MCW rank 0 is not bound (or bound to all available processors)
[ca235:18911] MCW rank 0 bound to socket 0[core 2[hwt 0]]: [././B/././././././././.][./././././././././././.]
[ca236:06650] MCW rank 1 bound to socket 0[core 0[hwt 0]]: [B/././././././././././.][./././././././././././.]


3 Rslaves spawned
mpirun -np 1 --bind-to none --hostfile hostfile --mca mpi_warn_on_fork 0 --mca btl_openib_allow_ib 1 --map-by ppr:1:node --report-bindings --mca ras ^slurm Rscript omp_test_S3.R
[ca235:21654] MCW rank 0 is not bound (or bound to all available processors)
[ca235:21641] MCW rank 0 bound to socket 0[core 0, ... [hwt 0]]: [B/B/B/B/B/B/B/B/B/B/B/B][./././././././././././.]
[ca236:09163] MCW rank 1 bound to socket 0[core 0, ... [hwt 0]]: [B/B/B/B/B/B/B/B/B/B/B/B][./././././././././././.]
[ca236:09163] MCW rank 2 bound to socket 1[core 12, ...[hwt 0]]: [./././././././././././.][B/B/B/B/B/B/B/B/B/B/B/B]
```

My hostfile is essentially specifying slots=2 on node 1 and slots=1 or 2 on node 2 depend on which config I am running (2 or 3 slaves).  BTW, I have to add the `--mca ras ^slurm` to get the expected mpi.universe.size, if I don't do that, it is equal to the requested tasks-per-node*cpus-per-node.

### So the Questions:

1. Based on the output, the R master started with mpirun appears to be started with the correct binding, it is the slaves that don't seem to get the message (no pun intended ;p ).  Am I interpreting this correctly?

2. How can I query this to determine on which side of the mpirun/spawn.comm.Rslaves the issue lies?  Is there a Rslave side env variable I can check (or better yet, set)?  Our suspicion is that the info object from mpi.comm.spawn is not being set correctly, but I have yet to be able to figure out how to query that object. <https://rdrr.io/cran/Rmpi/man/mpi.comm.spawn.html>

3. I can do `mpirun -np 2 --bind-to none openmp_example` and see that my openmp process spreads across the desired cores, is this the desired way to run things going forward?  I see pdbMPI R looks like this is the way the examples are run.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Basic configure in module spec file:
```
./configure --prefix="%{INSTALL_DIR}" \
            --with-cma \
            --enable-dlopen \
            --enable-shared \
            --with-mxm=/opt/mellanox/mxm \
            --with-pmi=/usr \
            --with-slurm
          #invalid configure options removed Jan 2018:
            #--with-threads \
            #--enable-mpi-thread-multiple
```

### Please describe the system on which you are running

* Operating system/version: Centos 7
* Computer hardware: HPE cluster, Skylake, 2 Voltas
* Network type: Mellanox ConnectX5 IB

I have a bit more troubleshooting on this issue via StackExchange here <https://stackoverflow.com/questions/59400720/slurm-openmpi-r-rmpi-openmp-issue>

**Comment by rhc54** [comment]
So long as you are using "mpirun" to start the job, the presence of Slurm is irrelevant.

OMPI changed its default behavior in v4.0 such that child jobs no longer automatically "inherit" the map/bind directives of their parents. Lots of reasons why this was done. In this case, you probably do want the children to inherit the directives, so you need to set the "rmaps_base_inherit" MCA parameter (either on the mpirun cmd line or in the environment). Any non-zero value is fine as it is a boolean parameter.

**Comment by rsettlage** [comment]
Well, that fixed it, thanks!

**Comment by rhc54** [comment]
Please pass that along on Stackoverflow as well so others can find the answer there.
