### ISSUE TITLE
Attempt to create loopback QP during startup

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#73]
In [source:/trunk/ompi/mca/btl/openib/btl_openib.c@20346#L344 btl_openib.c], we blindly assume the following:

 * iWARP devices cannot create lookback QPs
 * IB device can create loopback QPs

These assumptions may be true today, but may not always be true.  Instead, we should attempt to create a QP to ourselves and see if it works.  If it does, then the device is capable of loopback.  If we can't, then the device is not capable of it.

**Comment by jsquyres** [comment]
This will never be fixed.
