### ISSUE TITLE
32 bit builds failing on master

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7302]
32 bit builds are failing on master:

```
In file included from ../../../opal/mca/shmem/shmem.h:52,
                 from base/shmem_base_close.c:27:
../../../opal/mca/shmem/shmem_types.h:107: error: requested alignment is not a power of 2In file included from ../../../opal/mca/shmem/shmem.h:52,
                 from base/shmem_base_open.c:29:
../../../opal/mca/shmem/shmem_types.h:107: error: requested alignment is not a power of 2

In file included from ../../../opal/mca/shmem/shmem.h:52,
                 from base/shmem_base_select.c:30:
../../../opal/mca/shmem/shmem_types.h:107: error: requested alignment is not a power of 2In file included from ../../../opal/mca/shmem/shmem.h:52,
                 from base/shmem_base_wrappers.c:25:
../../../opal/mca/shmem/shmem_types.h:107: error: requested alignment is not a power of 2
```

One of the lines in question is

https://github.com/open-mpi/ompi/blob/02f02e7c1ed3742e6d87603b1d7acc7bd48103cd/opal/mca/shmem/shmem_types.h#L107

It appears that in a 32 bit build, this line is being used to define `OPAL_ALIGN_MIN`:

https://github.com/open-mpi/ompi/blob/02f02e7c1ed3742e6d87603b1d7acc7bd48103cd/opal/include/opal/align.h#L35

Which sets `OPAL_ALIGN_MIN` to `sizeof(long double)`, which is 12 (!!) on a 32 bit build:

```
$ cat foo.c
#include <stdio.h>
int main(int argc, char *argv[])
{
    printf("sizeof long double: %d\n", sizeof(long double));
    return 0;
}
$ gcc -m32 foo.c -o foo ; ./foo
sizeof long double: 12
```

And 12, indeed, is not a power of two.  😦 

`git blame` on https://github.com/open-mpi/ompi/blob/02f02e7c1ed3742e6d87603b1d7acc7bd48103cd/opal/include/opal/align.h#L35 identifies @devreal as the guilty party.  Joseph, could you have a look?

**Comment by devreal** [comment]
See https://github.com/open-mpi/ompi/pull/7124 :)

**Comment by jsquyres** [comment]
😆 

Ok, this is a dup of #7121.
