### ISSUE TITLE
UCX  ERROR Failed to allocate Issues mlx4_0

### ISSUE THREAD

**Issue by jaysullivan** [open-mpi/ompi#7312]
Hi All,

At one point in time, when my applications does a write operation, it pulls from all the ranks and consolidates down. When this happens I get the following printed to STDOUT:
[1579192987.880374] [HOSTNAME:440443:0]            sys.c:619  UCX  ERROR shmget(size=4263936 flags=0x7b0) for mm_recv_desc failed: No space left on device, please check shared memory limits by 'ipcs -l'
[1579192987.880437] [HOSTNAME:440443:0]        mm_sysv.c:69   UCX  ERROR failed to allocate 4259952 bytes with mm for mm_recv_desc
[1579192987.880455] [HOSTNAME:440443:0]        uct_mem.c:126  UCX  ERROR failed to allocate 4259952 bytes using md sysv for mm_recv_desc: Out of memory
[1579192987.880465] [HOSTNAME:440443:0]          mpool.c:176  UCX  ERROR Failed to allocate memory pool (name=mm_recv_desc) chunk: Out of memory

The versions of OpenMPI: 3.1.3 and 4.0.2
OFED Version: MLNX_OFED_LINUX-4.5-1.0.1.0 (OFED-4.5-1.0.1)
OS: CentOS Linux release 7.6.1810 (Core) 
Compiler: Intel 18.0.1
Network: FDR

# ibstat
CA 'mlx4_0'
	CA type: MT4099
	Number of ports: 1
	Firmware version: 2.42.5000
	Hardware version: 1
	Node GUID: 0x98039b0300cef070
	System image GUID: 0x98039b0300cef073
	Port 1:
		State: Active
		Physical state: LinkUp
		Rate: 56
		Base lid: 890
		LMC: 0
		SM lid: 1
		Capability mask: 0x02514868
		Port GUID: 0x98039b0300cef071
		Link layer: InfiniBand

Openmpi was built from distribution tar ball, configure line: ./configure --prefix=/blah/4.0.2 CC=icc CXX=icpc FC=ifort F77=ifort --with-verbs=no --with-tm=/opt/pbs --with-lustre

From what I've found online so far, indicated to increase kernel.shmmni to a larger value. this has helped, but now I'm set to 65536. Further digging indicates, unless I re-compile the kernel, the max I can have is 32768, so not sure if the 65536 even helps. 

What seems to happens is at some point in time I max out the shared-memory segments on the system and just generates a backlog. Eventually my code finishes, but it takes quite a while for the entire thing to get through it's backlog. 

Any idea what I can do to fix this, where I need to adjust? I'm at a loss as to what I need to do.

I'm also sorry. I don't have a known way to replicate this issue outside of using a CFD code. 

Thank you in advance,
-Jay

**Comment by jaysullivan** [comment]
Also pardon if this went to the wrong area. Let me know and i'll move it.

-jay

**Comment by dmitrygx** [comment]
@jaysullivan could open the issue for the [OpenUCX community](https://github.com/openucx/ucx), please?

**Comment by gpaulsen** [comment]
Referenced in [OpenUCX community issue 4684](https://github.com/openucx/ucx/issues/4684)

**Comment by gpaulsen** [comment]
Closing on Open-MPI side, as this appears to be a ucx issue.
