### ISSUE TITLE
HWLOC gitignore needs updating

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#7316]
Now that we are using a submodule for the embedded hwloc, I'm seeing the following after building OMPI:
```shell
$ git st
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   opal/mca/hwloc/hwloc2/hwloc (untracked content)
```
When I look into the hwloc directory, I find:
```shell
$ git st
HEAD detached at f1a2e22a
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	config/ltmain.sh.orig

nothing added to commit but untracked files present (use "git add" to track)
```
Someone needs to add that file to HWLOC's .gitignore

**Comment by rhc54** [comment]
@bgoglin FYI

**Comment by bgoglin** [comment]
I assume you cannot put that in the OMPI .gitignore because hwloc is a submodule? That would have been better given that OMPI is the one patching hwloc's ltmain.sh.

**Comment by rhc54** [comment]
I can try and see...

**Comment by rhc54** [comment]
Tried and no joy - the problem is that the git checkout in the submodule sees the change and flags it as being uncommitted. The upper level OMPI git just reports that the submodule thinks it has been changed. No way to ignore it, I'm afraid.

**Comment by bgoglin** [comment]
Pushed to hwloc master and v2.1.

**Comment by rhc54** [comment]
@jsquyres Can you please update the git module tag? It wasn't clear to me where it was pointing and the best way to update it.

**Comment by jsquyres** [comment]
Yep, I can update.
