### ISSUE TITLE
Weird error message from MPI_Init_thread

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#7320]
I am experimenting with TAMPI [1], which for some reason introduces a new thread-level `MPI_TASK_MULTIPLE`. Due to wrong library linking order, I managed to bypass the TAMPI library and pass `MPI_TASK_MULTIPLE` directly to Open MPI's `MPI_Init_thread`. Of course, Open MPI barked at it, which lead to this quite humorous (albeit misleading) error message:

```
*** The MPI_Init_thread() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
```

Obviously my application calling *the real* `MPI_Init_thread` this way is erroneous but maybe Open MPI can provide a more helpful error message in case the `required` argument to `MPI_Init_thread` is off?

[1] https://github.com/bsc-pm/tampi/

**Comment by ggouaillardet** [comment]
It took me a few seconds to understand this, so here is a reproducer that might help others

```c
#include <mpi.h>

int main(int argc, char *argv[]) {
    int provided;
    MPI_Init_thread(&argc, &argv, -1, &provided);
    return 0;
}
```
and the output
```
$ mpicc mpi.c
$ ./a.out 
*** The MPI_Init_thread() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[host:06011] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

**Comment by ggouaillardet** [comment]
BTW, is it safe to have `MPI_Init_thread()` simply abort the program here?
Or is there a legit scenario in which `MPI_Init_thread()` should return with `MPI_ERR_ARG` ?

**Comment by bosilca** [comment]
For consistency we should do the same as all the other functions. Moreover, there are ongoing discussions in the Forum about the scope of the default error handler, and being able to set it via ```mpirun``` parameters (or info keys).
