### ISSUE TITLE
opal_gethostname segfaults

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#7322]
We have always permitted the use of ```opal_output``` prior to successfully executing ```opal_init```, with the output simply being printed to stderr. However, if you hit that scenario now, the program segfaults because ```opal_gethostname``` accesses ```opal_process_info.nodename```, which hasn't been defined yet.

What you need to do is have ```opal_gethostname``` check for ```NULL```, and if it finds it, then go ahead and call ```gethostname``` instead. Or do the protection in ```opal_output```.

I don't care which option gets used, but we shouldn't be segfaulting for no reason.

**Comment by jsquyres** [comment]
Fair point.  I'll fix.
