### ISSUE TITLE
MTL priorities not working?

### ISSUE THREAD

**Issue by yburette** [open-mpi/ompi#735]
Hi,

I was trying to run OMPI without any -mca parameter but it fails.
My build has both the PSM and the OFI MTLs. libfabric has both the PSM and sockets providers.

It looks like both MTLs are actually opened and the OFI MTL is being selected. I thought the priority scheme put in place would select the PSM MTL first.

I also tried to add --mca mtl_ofi_priority -100 to no avail...

@hppritcha @jsquyres @afriedle-intel @jithinjosepkl 
What do you think? Am I missing anything?

Yohann

```
$ mpirun --mca pml cm --mca mtl_base_verbose 100 -host f007,f008 -n 2 IMB-MPI1 PingPong
[f008:143227] mca: base: components_register: registering mtl components
[f008:143227] mca: base: components_register: found loaded component psm
[f008:143227] mca: base: components_register: component psm register function successful
[f008:143227] mca: base: components_register: found loaded component ofi
[f008:143227] mca: base: components_register: component ofi register function successful
[f008:143227] mca: base: components_open: opening mtl components
[f008:143227] mca: base: components_open: found loaded component psm
[f007:153573] mca: base: components_register: registering mtl components
[f007:153573] mca: base: components_register: found loaded component psm
[f008:143227] mca: base: components_open: component psm open function successful
[f008:143227] mca: base: components_open: found loaded component ofi
[f008:143227] mca: base: components_open: component ofi open function successful
[f007:153573] mca: base: components_register: component psm register function successful
[f007:153573] mca: base: components_register: found loaded component ofi
[f007:153573] mca: base: components_register: component ofi register function successful
[f007:153573] mca: base: components_open: opening mtl components
[f007:153573] mca: base: components_open: found loaded component psm
[f007:153573] mca: base: components_open: component psm open function successful
[f007:153573] mca: base: components_open: found loaded component ofi
[f007:153573] mca: base: components_open: component ofi open function successful
[f008:143227] select: initializing mtl component psm
[f007:153573] select: initializing mtl component psm
[f007:153573] select: init returned success
[f007:153573] select: initializing mtl component ofi
[f008:143227] select: init returned success
[f008:143227] select: initializing mtl component ofi
[f007:153573] select: init returned success
[f007:153573] mca: base: close: component psm closed
[f007:153573] mca: base: close: unloading component psm
[f007:153573] select: component ofi selected

IMB-MPI1:153573 terminated with signal 11 at PC=7fda650e871e SP=7fff7625b8a8.  Backtrace:
[f008:143227] select: init returned success
[f008:143227] mca: base: close: component psm closed
[f008:143227] mca: base: close: unloading component psm
[f008:143227] select: component ofi selected

IMB-MPI1:143227 terminated with signal 11 at PC=7fae4fd3d71e SP=7fffa5e3db18.  Backtrace:
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node f007 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

**Comment by hppritcha** [comment]
Hi Yohann,

is this master or 1.10?
trying to reproduce on our qlogic cluster...

Howard


2015-07-22 10:30 GMT-06:00 Yohann Burette <notifications@github.com>:

**Comment by jsquyres** [comment]
FWIW, component priorities are restricted to the [0, 100] range -- so setting a priority of -100 likely won't do anything...?

What's the priority of PSM vs. the OFI component?

**Comment by hppritcha** [comment]
psm == 100, ofi == 10.

i think psm is not initializing for some reason for Yohann.


2015-07-22 10:39 GMT-06:00 Jeff Squyres <notifications@github.com>:

**Comment by yburette** [comment]
Hi Howard,

I was using 1.10.0rc2 that Ralph posted. But I'm thinking it would be the same with master.

To me it looks more like both MTLs get initialized, no?

Yohann

```
[f007:153573] select: initializing mtl component psm
[f007:153573] select: init returned success
[f007:153573] select: initializing mtl component ofi
[f007:153573] select: init returned success
[f007:153573] mca: base: close: component psm closed
[f007:153573] mca: base: close: unloading component psm
[f007:153573] select: component ofi selected
```

**Comment by hppritcha** [comment]
I think you probably want for 1.10.0rc2 to work for customers, so I'll work off that instead.

Hmmm... you're right but it looks like there is something missing from the psm mtl.
Looks ike the psm mtl is missing vital commits from master.
I'd suggest looking at eb977de5 as a start.

**Comment by hppritcha** [comment]
time to start on rc3 it looks like.  There were some other commits I did about that time for intro of the ofi mtl.  Looks like you may want to checkout #363.

**Comment by yburette** [comment]
Yes, I think you're right. That whole commit is missing.

@rhc54

**Comment by jsquyres** [comment]
Can one of you file a new PR for the missing stuff?

**Comment by hppritcha** [comment]
Sure.

**Comment by hppritcha** [comment]
Any other work done besides commit open-mpi/ompi-release@ed587fb in pulling from master to 1.10?

**Comment by yburette** [comment]
How about 869041f770d6b52896f28fdd3e1f1a7c34219397?

**Comment by hppritcha** [comment]
hopefully -Xignore-all-whitespace will help.

**Comment by hppritcha** [comment]
Opened PR open-mpi/ompi-release#409.

This will have to be reviewed by impacted MTL authors before being pulled in, esp. since the cherry-pick had conflicts.

**Comment by hppritcha** [comment]
came up fix for the segfault (Nathan and me).  too much inlining in ofi and probably psm2.
I'll open a new PR for that fix.  Meanwhile the priority selection stuff needs to get reviewed.
