### ISSUE TITLE
Mac OS Catalina: clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by acse-fk4517** [open-mpi/ompi#7357]
Thank you for taking the time to submit an issue!

## Background information
I have installed open-mpi on macOS Catalina using the command `brew install open-mpi`. I have also installed llvm through brew. That also appears to be working. The IDE I am using is CLion.

My CLion IDE  is set as follows:

<img width="1019" alt="Screenshot 2020-02-03 at 21 41 06" src="https://user-images.githubusercontent.com/56031768/73693339-ed32f080-46cd-11ea-9288-9c5f90becccb.png">

Using the command line, I can get the code to compile and run using the following:

- mpic++ main.cpp
- mpirun a.out

Now, I want to use a CMake file in order to make my work flow easier. My CMake file consists of the following:

```
cmake_minimum_required(VERSION 3.15)
project(Project)

set(CMAKE_CXX_STANDARD 17)

set(LDFLAGS "-L/usr/local/Cellar/open-mpi/4.0.2/lib")
set(CPPFLAGS "-I/usr/local/Cellar/open-mpi/4.0.2/include")

include_directories(/usr/local/Cellar/llvm/9.0.1/include)
link_directories(/usr/local/Cellar/llvm/9.0.1/lib)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${GCC_COVERAGE_COMPILE_FLAGS} ${LDFLAGS} ${CPPFLAGS} -fopenmp")

add_executable(main main.cpp)

target_link_libraries(main)
```

Now the issue is when I try to run and build this, I get the following error:

<img width="983" alt="Screenshot 2020-02-03 at 21 49 52" src="https://user-images.githubusercontent.com/56031768/73693998-2324a480-46cf-11ea-8960-8496ac2690aa.png">

This seems to be caused by the `-fopenmp` flag. If I remove this flag and try and build and run, I get the following error instead:

<img width="1123" alt="Screenshot 2020-02-03 at 21 44 46" src="https://user-images.githubusercontent.com/56031768/73693856-e658ad80-46ce-11ea-9f61-34241be55c8a.png">

Can someone please advise me on how I can fix this, if indeed it can be fixed? I am new to this library  (and C++ generally) and would very much like to use it. I have been stuck on this for hours. 

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

> mpirun (Open MPI) 4.0.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

I installed using Homebrew on macOS Catalina (macbook pro).

**Comment by jsquyres** [comment]
Greetings @acse-fk4517.  You closed the issue -- did you resolve the problem?

**Comment by acse-fk4517** [comment]
Hi @jsquyres I did manage to fix it - just a noob mistake when using cmake! Thanks

**Comment by jsquyres** [comment]
@acse-fk4517 Cool.  If you weren't aware of it, FYI: https://www.open-mpi.org/faq/?category=mpi-apps#cant-use-wrappers
