### ISSUE TITLE
Question about btl_uct_component

### ISSUE THREAD

**Issue by afernandezody** [open-mpi/ompi#7359]
Hello OMPI Team,
I'm trying to install OMPIv4.0.2 in an EPYC2 system running on Ubuntu 18.04 with a 200 Gb HDR Mellanox ConnectX-6. The installation is simply `./configure --prefix=/opt/openmpi --with-sge` and 
`make -j`
I was getting an error (Makefile:1895: recipe for target 'libmca_common_ucx.la' failed) that I fixed by installing UCX(1.7.0) but ran into an unexpected error:

```
btl_uct_component.c: In function ‘mca_btl_uct_component_init’:
btl_uct_component.c:434:5: warning: implicit declaration of function ‘uct_query_md_resources’; did you mean ‘uct_md_query_tl_resources’? [-Wimplicit-function-declaration]
     uct_query_md_resources (&resources, &resource_count);
     ^~~~~~~~~~~~~~~~~~~~~~
     uct_md_query_tl_resources
btl_uct_component.c:447:5: warning: implicit declaration of function ‘uct_release_md_resource_list’; did you mean ‘uct_release_tl_resource_list’? [-Wimplicit-function-declaration]
     uct_release_md_resource_list (resources);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
     uct_release_tl_resource_list
btl_uct_component.c: In function ‘mca_btl_uct_component_process_uct_md’:
btl_uct_component.c:383:5: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
     (void) asprintf (&tmp, "uct.%s", module->md_name);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:1898: recipe for target 'btl_uct_component.lo' failed
make[2]: *** [btl_uct_component.lo] Error 1
make[2]: Leaving directory '/home/benchmarks/openmpi-4.0.2/opal/mca/btl/uct'
Makefile:2361: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/benchmarks/openmpi-4.0.2/opal'
Makefile:1879: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

```
There could be several potential reasons (I'm unsure if the minor incompatibility with UCX 1.7.0 discussed in several other threads has been fully solved or even if it could be related at all with this error message). Any suggestion on which is the root of the problem or how to circumvent it would be welcomed. 
Thank you.

**Comment by bosilca** [comment]
This has been fixed in master with a3026c016a and 9d345d9aa, and both of these patches are in 4.0.2. The only way to get this error is if the configuration script does not detect the correct version of UCX and use the UCX 1.6 API. 

Check your configure output of your configure for something like below:
```
--- MCA component btl:uct (m4 configuration macro)
checking for MCA component btl:uct compile mode... dso
checking check uct version... yes
checking UCT version compatibility... UCT version not compatible - need UCX 1.7 or older
checking if MCA component btl:uct can compile... no
```

Your error might be explained if you updated the version of UCX to 1.7 but didn't run the configure again.

**Comment by afernandezody** [comment]
Hi @**bosilca**,
The PRs that you mention seem to have been committed in November, whereas the stable version of v4.0.2 is dated in early October. No problem, this evening I'll retry the installation and, if it's still not working, I'll just move on to one of the development versions for v4.0.3. Thanks.

**Comment by bosilca** [comment]
My bad, I was not looking at the release but I was using the current 4.0.2 branch. Next release is just around the corner, meanwhile you can simply clone the 4.0.x branch.

**Comment by afernandezody** [comment]
Hi @**bosilca**,
It works with v4.0.3rc3. It took me a while to circle back in order to close the ticket. Looking forward to the stable release of v4.0.3. Thanks.

**Comment by datakid** [comment]
Have also just hit this bug. Is 4.0.3 far off?
