### ISSUE TITLE
BTL TCP: static assert must be protected

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7361]
The use of `_Static_assert()` must be protected by:

```c
#if (__STDC_VERSION__ >= 201112L)
// ...blah...
#endif
```

Recent commit e958f3cf2248cd19d2eb91c223b2009488c85279 didn't protect its use of `_Static_assert()` in the TCP BTL, and it's causing failures on gcc 4.4.7 (i.e., RHEL 6 default compiler).

https://github.com/open-mpi/ompi/blob/827e9f66af94b9269b15c3fd54b7e578f5740821/opal/mca/btl/tcp/btl_tcp_addr.h#L65

@wckzhang This was your commit -- can you have a look?

**Comment by jsquyres** [comment]
@hjelmn just confirmed for me: static assert is C11 (not C99), which is why we need to protect the use of them.

**Comment by wckzhang** [comment]
I took a look, it looks like awlauria has sent out a PR which I approved. Nice catch!
