### ISSUE TITLE
Internal hwloc build broken on master

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#7369]
I pulled current master and did a `git submodule update --init --recursive` before running `autogen.pl`. Now the build of the internal hwloc fails with the following errors:

```
  CC       components.lo
../../../../../../../opal/mca/hwloc/hwloc2/hwloc/hwloc/components.c: In function ‘hwloc_disc_component_register’:
../../../../../../../opal/mca/hwloc/hwloc2/hwloc/hwloc/components.c:258:17: error: ‘struct opal_hwloc201_hwloc_disc_component’ has no member named ‘phases’
   if (!component->phases
                 ^~
../../../../../../../opal/mca/hwloc/hwloc2/hwloc/hwloc/components.c:259:20: error: ‘struct opal_hwloc201_hwloc_disc_component’ has no member named ‘phases’
       || (component->phases != HWLOC_DISC_PHASE_GLOBAL
                    ^~
../../../../../../../opal/mca/hwloc/hwloc2/hwloc/hwloc/traversal.c: In function ‘opal_hwloc201_hwloc_get_depth_type’:
../../../../../../../opal/mca/hwloc/hwloc2/hwloc/hwloc/traversal.c:44:10: error: ‘HWLOC_TYPE_DEPTH_MEMCACHE’ undeclared (first use in this function); did you mean ‘HWLOC_TYPE_DEPTH_MISC’?
     case HWLOC_TYPE_DEPTH_MEMCACHE:
          ^~~~~~~~~~~~~~~~~~~~~~~~~
          HWLOC_TYPE_DEPTH_MISC
../../../../../../../opal/mca/hwloc/hwloc2/hwloc/hwloc/traversal.c:44:10: note: each undeclared identifier is reported only once for each function it appears in
../../../../../../../opal/mca/hwloc/hwloc2/hwloc/hwloc/components.c:259:32: error: ‘HWLOC_DISC_PHASE_GLOBAL’ undeclared (first use in this function); did you mean ‘HWLOC_BITS_PER_LONG’?
       || (component->phases != HWLOC_DISC_PHASE_GLOBAL
                                ^~~~~~~~~~~~~~~~~~~~~~~
                                HWLOC_BITS_PER_LONG
../../../../../../../opal/mca/hwloc/hwloc2/hwloc/hwloc/traversal.c:45:14: error: ‘HWLOC_OBJ_MEMCACHE’ undeclared (first use in this function); did you mean ‘HWLOC_OBJ_L1ICACHE’?
       return HWLOC_OBJ_MEMCACHE;
```
and many more...

Configure detects the existing hwloc to be too old so it chooses the internal one:

```
Miscellaneous
-----------------------
CUDA support: no
HWLOC support: internal (external hwloc version is less than internal version 2.0)
Libevent support: internal
PMIx support: Internal
```

I tried going back before #7366 but that didn't help, so I assume it's not the culprit.

**Comment by bgoglin** [comment]
This is very strange. It sounds like it's compiling hwloc 2.1 internals with older hwloc headers. Did hwloc work as a submodule before in that clone? Can you check you don't have a stale hwloc copy in another subdirectory below opal/mca/hwloc that somehow wasn't removed when switching to submodules? Since there's hwloc201 in your errors, I was thinking the pre-submodule hwloc 2.0.1 is still there (not sure why it would be used).

**Comment by jsquyres** [comment]
I'm not running into this problem.

Can you attach your `config.log` and the stdout from running `configure`?

**Comment by devreal** [comment]
The old hwloc was still lingering around:

```
$ git status opal/mca/hwloc/
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	opal/mca/hwloc/hwloc201/

```

Manually deleting `opal/mca/hwloc/hwloc201/` did the trick for me. Closing.

**Comment by jsquyres** [comment]
@devreal Git pro tip: `git clean -dfx` will completely clean your git tree of all files not tracked by git (use with care!!).  This can be helpful for deleting module subdirs like this -- e.g., when you switch between branches, or when a commit removes a module subdir (but its build product persists), etc.

**Comment by devreal** [comment]
@jsquyres Damn, I just saw your email on the devel mailing list about submodules and checking the wiki before complaining about broken builds, don't know how that slipped through. Will be more careful next time :)
