### ISSUE TITLE
How to disable ucx  during OpenMPI run?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [open-mpi/ompi#7388]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
 4.0.2a1
### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
OpenMPI comes from mellanox ofed driver.
### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
N/A
### Please describe the system on which you are running

* Operating system/version: centos 7.6
* Computer hardware: x86_64
* Network type: Ethernet
-----------------------------
## Details of the problem
Today I begin to run TensorFlow with OpenMPI. There is a mellanox rdma nic, but I don't want OpenMPI to use rdma to transport, and what I actually want is tcp BTL, so my scripts is:
```
mpirun -np 2 --host 10.0.22.2:1,10.0.24.2:1 \
	       --mca pml ob1 \
	       --mca btl tcp,vader,self \
	       sh worker.sh
```
The ip 10.0.22.2 and 10.0.24.2 is mellanox rdma nic, but I only want to use tcp BTL to transport. 
And during run, OpenMPI raise an error:
```
[gpu5.maas:180661:1][bcol_ucx_p2p_sendrecv.h:171:create_ep] UCXP2P UCX returned connect error: Destination is unreachable
[gpu5.maas:180661:1][bcol_ucx_p2p_component.c:562:hmca_bcol_ucx_p2p_init_query] UCXP2P hmca_bcol_ucx_p2p_preconnect() failed

[1581492713.059878] [gpu5:180661:0]         select.c:410  UCX  ERROR no active messages transport to <no debug data>: tcp/rdma2 - Destination is unreachable
[gpu4.maas:190670:0][bcol_ucx_p2p_sendrecv.h:171:create_ep] UCXP2P UCX returned connect error: Destination is unreachable
[gpu4.maas:190670:0][bcol_ucx_p2p_component.c:562:hmca_bcol_ucx_p2p_init_query] UCXP2P hmca_bcol_ucx_p2p_preconnect() failed

[1581492713.058107] [gpu4:190670:0]         select.c:410  UCX  ERROR no active messages transport to <no debug data>: tcp/rdma2 - Destination is unreachable
[gpu5.maas:180661] Error: coll_hcoll_module.c:301 - mca_coll_hcoll_comm_query() Hcol library init failed
MPI Environment initialized. Process id: 1 Total processes: 2 || Hostname: gpu5.maas 
[gpu4.maas:190670] Error: coll_hcoll_module.c:301 - mca_coll_hcoll_comm_query() Hcol library init failed
```
I think that this error is raised by OpenMPI's ucx component,  which means that OpenMPI don't use tcp BTL to transport, so can any one tell me how to disable ucx component and enable tcp BTL when transport?

**Comment by bwbarrett** [comment]
Unfortunately, Open MPI doesn't have a good way of universally saying "don't use this transport".  The UCX errors are coming from the `hcoll` collectives component, which is Mellanox's accelerated collectives library.  Adding `-mca coll ^hcoll` should disable the Mellanox-specific collectives.

**Comment by Keepmoving-ZXY** [comment]
How about compile OpenMPI without ucx support?

**Comment by jsquyres** [comment]
You can do this:

```
$ ./configure --without-ucx ...
```

**Comment by Keepmoving-ZXY** [comment]
ok, I have a try.

**Comment by jsquyres** [comment]
When your build is done, you can use `ompi_info` to check.  `ompi_info` tells you lots of things about your Open MPI installation.  E.g.:

```
$ ompi_info | egrep 'ucx|hcoll`
```

If you built without UCX support, that should return nothing.

If somehow you accidentally did build with UCX support, you can also delete the UCX plugins from the installation tree.  For example:

```
$ ./configure --prefix=$HOME/ompi-install && make -j 32 install
...lots of output...

$ ompi_info | egrep 'ucx|hcoll'
...see the UCX and hcoll plugins listed...

$ cd $HOME/lib/openmpi
$ rm *ucx* *hcoll*
$ ompi_info | egrep 'ucx|hcoll'
...see the UCX and hcoll plugins NOT listed...
```

**Comment by bwbarrett** [comment]
Although, again, since the problem is HCOL (which uses UCX under the covers), you probably want to have *both* `--without-ucx` and `--without-hcol`, or you're going to use TCP for point to point and UCX for collectives.

**Comment by jsquyres** [comment]
> Although, again, since the problem is HCOL (which uses UCX under the covers), you probably want to have _both_ `--without-ucx` and `--without-hcol`, or you're going to use TCP for point to point and UCX for collectives.

Good catch; thanks.  I thought hcoll only spoke UCX, and therefore was covered by `--with[out]-ucx`.  Huh.

**Comment by Keepmoving-ZXY** [comment]
I have compiled OpenMPI with `--without-ucx` and `--without-hcol`, and the scripts run normal finally.

**Comment by Keepmoving-ZXY** [comment]
Thank you very much @jsquyres  @bwbarrett

**Comment by dmitrygx** [comment]
@Keepmoving-ZXY

> There is a mellanox rdma nic, but I don't want OpenMPI to use rdma to transport, and what I actually want is tcp BTL

If you are going to use TCP and shared-memory transports instead of RDMA-aware transport, you can also do this with UCX by setting `UCX_TLS=tcp,sm` env variable and giving `-mca pml ucx` to mpirun command line. `UCX_NET_DEVICES=<IP interface name>` can be used to specify an IP interface that you are going to use for TCP communications (TCP chooses the most fastest by default). The TCP from the latest UCX should give you a nice performance. Let us know if you need help to try this option.

**Comment by Keepmoving-ZXY** [comment]
ok, I will have a try.
