### ISSUE TITLE
mpirun context sensitive help gone with prrte replacement

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#7389]
Not sure how important it is, but the context sensitive mpirun help that was added with the OMPI 3 series is gone now on master owing to the prrte replacment of orte, it seems.

**Comment by rhc54** [comment]
Yep! Couldn't stand that thing as it was like playing 21-questions to guess what category a help issue was flagged under. I kept winding up going back to the code to find out the category, which meant I already got the answer from the code itself.

**Comment by rhc54** [comment]
This won't be coming back
