### ISSUE TITLE
Strange mpi_f08 alloc_mem MTT failures

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#739]
@rhc54 pointed out some strange MTT failures with regards to mpi_f08 and MPI_ALLOC_MEM:

    http://mtt.open-mpi.org/index.php?do_redir=2245

The problem appears only in builds (in master and v1.10) when you build `--disable-weak-symbols` and run the IBM test suite problem pt2pt/allocmem_usempif08.  The specific problem that occurs is that an assertion about MPI_COMM_WORLD fails during MPI_FINALIZE.  I'm at a loss to explain why; the MPI f08 bindings have nothing to do with weak symbols.  Further, the assertion failure disappears when you comment out the data validation portion of the test -- which is a read-only portion of the code (!).

I am able to reproduce this with gcc 5.1 on my RHEL 6.5 cluster.  So far, I am at a loss to explain why this is happening.  Next steps: try a different compiler / compiler version.

**Comment by ggouaillardet** [comment]
@jsquyres would https://github.com/open-mpi/ompi/pull/432 fix this issue ?
i will rebase it to confirm it is ready to be merged.
currently, MPI_STATUSES_IGNORE is handled as an array or requests if ompi is configure'd with --disable-weak-symbols, and this is prone to memory corruption

**Comment by jsquyres** [comment]
Mmm... interesting point: you're right, #432 may fix this issue.

Let's finish up #432 (I just put some comments on it), and see if this issue goes away.

**Comment by ggouaillardet** [comment]
ok, will do
note I wrote some tests just for this issue
waitsome_usempif08
testall_usempif08

**Comment by ggouaillardet** [comment]
#432 did fix this issue (see mtt results at http://mtt.open-mpi.org/index.php?do_redir=2247)
