### ISSUE TITLE
mpirun - no output to stderr/stdout if prrte launch_orted_on_hn is true

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#7399]
By default, the mpirun now in master following the orted removal no longer forwards stdout/stderr from MPI processes in a job if the PRRTE launch_orted_on_hn mca parameter is set to true.

Its not clear how to feed the get the mpirun/prun binary to do the equivalent of
```
prte --daemonize --system-server
prun -n 4 --system-server-first
```
from the mpirun command line.  The help documents a system-server-first option but this doesn't seem to be applicable.

**Comment by rhc54** [comment]
I checked this with my laptop docker containers and it doesn't work. However, it also didn't work for OMPI v4.x.

@hppritcha Is it working for you on v4.x? Just trying to understand if I can use my docker containers to test it.

**Comment by hppritcha** [comment]
things are working fine on v4.0.x for me - using mpirun/orte.

**Comment by hppritcha** [comment]
this problem appears to be resolved with most recent pmix/prrte submodules.   I can no longer reproduce so closing.
