### ISSUE TITLE
Better error message when no openib loopback

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#74]
Certain host-side !OpenFabrics devices do not support loopback connections (right now the openib BTL assumes all iWARP devices fall into this category).  If you run multiple MPI processes on the same host with such a device and do not use the "sm" BTL, you get an amorphous "MPI process X could not connect to MPI process Y" error message.

It would be much better if we show a better error message -- possibly from the openib BTL? (but there may be abstraction violation issues for a BTL to display such an error message; that's why this is a ticket) -- that says "you're using the openib BTL, but the device ABC doesn't support loopback, so you need to use the sm BTL as well."

I.e., give a very specific error message.  Need to think about how to do this "properly"...

**Comment by hppritcha** [comment]
Kicking down the road to 3.x

**Comment by jsquyres** [comment]
This is marked as "won't fix", so I'll close this ancient issue.
