### ISSUE TITLE
OMPI/master treats PMIx namespace as an integer instead of string

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#7433]
@rhc54 

I and @hppritcha faced a problem trying to run Slurm with OMPI/master and PMIx/v3.1.3.
After PMIx_Init is invoked [[here](https://github.com/open-mpi/ompi/blob/master/ompi/runtime/ompi_rte.c#L534)], `myproc` variable contains:
```
533         /* initialize the selected module */
534         if (!PMIx_Initialized() && (PMIX_SUCCESS != (ret = PMIx_Init(&myproc, NULL, 0)))) {
(gdb) p myproc
$3 = {nspace = "slurm.pmix.2.7", rank = 0}
```
which is correct.

However, a few lines below the modex key is requested with `namespace = "0"`.
```
(gdb) frame 1
#1  0x00007feb6326ef87 in ompi_rte_init (pargc=0x0, pargv=0x0)
    at /hpc/mtr_scrap/users/artemp/SLURM/2020_02_15_OMPI_master/slurm_deploy/deploy_files/src/ompi/ompi/runtime/ompi_rte.c:570
570         OPAL_MODEX_RECV_VALUE(rc, PMIX_LOCAL_RANK,
(gdb) frame 0
#0  ompi_pmix_snprintf_jobid (jobid_string=0x7ffe3d012cd0 "pmix.optional", size=255, jobid=0)
    at /hpc/mtr_scrap/users/artemp/SLURM/2020_02_15_OMPI_master/slurm_deploy/deploy_files/src/ompi/ompi/runtime/ompi_rte.c:438
438             rc = snprintf(jobid_string, size, "%ld", (long) jobid);
(gdb) n
439             if (0 > rc) {
(gdb) p jobid_string
$4 = 0x7ffe3d012cd0 "0"
```

I believe that the flaw in the logic is in `ompi_pmix_convert_string_to_jobid` that assumes that jobid is always an integer [[link](https://github.com/open-mpi/ompi/blob/master/ompi/runtime/ompi_rte.c#L424)] which is not true for PMIx standard:
```C
 *jobid = strtoul(jobidstring, NULL, 10);
```

**Comment by rhc54** [comment]
I take it you invoked the application using `srun`? Which means `PRRTE` isn't involved.

This is probably something the OMPI community is going to have to discuss. What we did before was to create a lookup table in the opal/pmix code and convert the nspace on every call to a PMIx function by searching thru the table for the numeric jobid. This could be recreated in the `OPAL_PMIX_CONVERT_NAME` macro, and there would need to be some further glue to register the jobid/nspace so it got into the table.

Or one could replace the numeric jobid in the OMPI code with the `pmix_nspace_t`. Don't know which way the community would like to go - likely worth bringing up at a telecon.

**Comment by artpol84** [comment]
> I take it you invoked the application using srun? Which means PRRTE isn't involved.

That is correct.

**Comment by rhc54** [comment]
FWIW: this non-integer nspace coming from the PMIx plugin is going to break MPICH and MVAPICH as well. I know it conforms to the standard - just a heads-up that the consumers of it are expecting a string representation of a number.

**Comment by artpol84** [comment]
Thanks, I'll double-check this

**Comment by artpol84** [comment]
It seems to me that MPICH is doing the right thing [[link] during initialization by storing namespace in the global var `pmix_proc` (https://github.com/pmodels/mpich/blob/2bb15c6e875386fa542a037663680d2736156159/src/util/mpir_pmi.c#L97)]:
```C
    pmi_errno = PMIx_Init(&pmix_proc, NULL, 0);
    MPIR_ERR_CHKANDJUMP1(pmi_errno != PMIX_SUCCESS, mpi_errno, MPI_ERR_OTHER,
                         "**pmix_init", "**pmix_init %d", pmi_errno);

    rank = pmix_proc.rank;
    PMIX_PROC_CONSTRUCT(&pmix_wcproc);
    MPL_strncpy(pmix_wcproc.nspace, pmix_proc.nspace, PMIX_MAX_NSLEN);
    pmix_wcproc.rank = PMIX_RANK_WILDCARD;

    pmi_errno = PMIx_Get(&pmix_wcproc, PMIX_JOB_SIZE, NULL, 0, &pvalue);
    MPIR_ERR_CHKANDJUMP1(pmi_errno != PMIX_SUCCESS, mpi_errno, MPI_ERR_OTHER,
                         "**pmix_get", "**pmix_get %d", pmi_errno);
    size = pvalue->data.uint32;
    PMIX_VALUE_RELEASE(pvalue);
```

**Comment by rhc54** [comment]
But are they referencing all other procs by their string nspace? Or are they converting to a numeric jobid and using that? I'm not familiar enough with MPICH to know if they are based on string IDs or numeric ones. I thought that at some point it all switches over to numbers, but again, I haven't looked at their code for a while now.

**Comment by artpol84** [comment]
They either using strings like [[here](https://github.com/pmodels/mpich/blob/2bb15c6e875386fa542a037663680d2736156159/src/util/mpir_pmi.c#L97:L100)] or they leave it as NULL like [[here](https://github.com/pmodels/mpich/blob/2bb15c6e875386fa542a037663680d2736156159/src/util/mpir_pmi.c#L241:L245)] and rely on PMIx to take care of this [[link](https://github.com/openpmix/openpmix/blob/a0af6c6b4df0c2dca0c4d68def21f3fe0bdd8e4e/src/client/pmix_client_get.c#L227)]. 
Btw, I checked in the standard and (at least on PMIx_Get page) and I don't immediately see this feature (proc.nspace == NULL) documented.

**Comment by artpol84** [comment]
The bottom line, I'm 99% sure that at least MPICH is ok with the plugin.

**Comment by rhc54** [comment]
Good - that means MVAPICH is likely okay too. So the OMPI folks will have to decide how they want to proceed.

I'll look for the nspace = NULL thing - I  believe it is there, but I don't recall precisely where. May need better explanation.

**Comment by artpol84** [comment]
> I'll look for the nspace = NULL thing - I believe it is there, but I don't recall precisely where. May need a better explanation.

Yeah, I think it should be where PMIx_Get is described (even if there will be duplications), or (as it is also related to PMIx_Get_nb at least) there have to be a reference to the section describing possible proc values and their meanings.

**Comment by artpol84** [comment]
with https://github.com/open-mpi/ompi/pull/7441 and https://github.com/open-mpi/ompi/pull/7451 the issue seems fixed.
Thanks @rhc54 !
