### ISSUE TITLE
Remove all the rest of the FT code

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7437]
There's still a bunch of FT things left over in the code base that should be removed:

* opal/tools/opal-checkpoint
* opal/tools/opal-restart
* Various AM_CONDITIONALs, such as `WANT_FT`, `WANT_FT_CR`, `WANT_FT_THREAD`
* config/opal_setup_ft.m4
* `OPAL_ENABLE_FT_*` preprocessor macros
* ...possibly more?  I stopped looking

**Comment by bosilca** [comment]
Not all of them are related to C/R. ULFM uses quite a few, so the removal should be done carefully.

**Comment by jsquyres** [comment]
Gotcha.

Of the list above, can you identify what ULFM is using?

**Comment by bosilca** [comment]
@abouteiller.

**Comment by abouteiller** [comment]
Can be removed without side effects on ULFM:
1. opal/tools/*: we do not use at all.
2. WANT_FT_CR: we do not use, can remove all blocks of code between ifdef ENABLE_FT_CR
3. WANT_FT_THREAD/ENABLE_FT_THREAD: this pertains only to opal/runtime/opal_cr.[ch]. We do not use. 

What we need to KEEP:
1. config/opal_setup_ft.m4: NEEDED. We reuse most of the logic to add the FT_MPI case alongside the FT_CR case. We do not use any of the logic for WANT_FT_THREAD. 
2. some schizo specific behavior about --enable-recovery, and the mpirun/orte logic to handle persistent DVM/PRRTE).

**Comment by jsquyres** [comment]
Cross-reference this against #7740.

**Comment by jjhursey** [comment]
Things to remove
- [ ] opal-checkpoint tool
- [ ] opal-restart tool
- [ ] WANT_FT_CR code blocks
- [ ] WANT_FT_THREAD/ENABLE_FT_THREAD code blocks
- [ ] `pml/crcpw`
- [ ] `opal/mca/crs` framework (@abouteiller do you all use anything here?)

**Comment by jjhursey** [comment]
PR #8311 should resolve this issue.

**Comment by jjhursey** [comment]
PR #8312 has been merged. This can be closed
