### ISSUE TITLE
external pmix needing extern libevent/hwloc needs checking again

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#7458]
something happened to the configury on master and it no longer errors out if one is using an external pmix config option but not libevent.  Needs to be fixed prior to release of 5.0.0.

**Comment by hppritcha** [comment]
@rhc54 do we need to check for external hwloc as well?  We didn't do that in older releases, just libevent.

**Comment by rhc54** [comment]
I'm afraid so - PMIx didn't use hwloc in v2 (which is in OMPI v3), but does starting with v3 (which is in OMPI v4).

**Comment by hppritcha** [comment]
closed via #7506
