### ISSUE TITLE
Bring back "component alias" functionality

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7471]
Per the [Feb 2020 face-to-face meeting](https://github.com/open-mpi/ompi/wiki/Meeting-2020-02), we're going to bring the "component alias" functionality back (i.e., @hjelmn opened a PR about this forever ago, but it never got merged).

For v5.0, we'd like to:

1. Delete the existing "sm" BTL
2. Rename "vader" to be "sm"
3. Make "vader" be an alias to "sm"

This requires bringing back / finishing the "component alias" functionality.

**Comment by hjelmn** [comment]
Still working on this. Estimate ~ 2 weeks development time given my work/home schedule this month.

**Comment by jsquyres** [comment]
Ok.  Planned branch (i.e., feature completeness) for v5.0 is April 30.

**Comment by awlauria** [comment]
Completed with #7671 merged to master.
