### ISSUE TITLE
Master compile break with hwloc 1.5.2

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7489]
Per the 2020-02 face-to-face, we agreed to keep hwloc v1.5.x as the minimum supported version of hwloc because CentOS 6 still ships hwloc 1.5.x (see https://github.com/open-mpi/ompi/wiki/Meeting-2020-02).

Latest master is showing MTT compile fails against hwloc v1.5.x:

https://mtt.open-mpi.org/index.php?do_redir=3206

Here's the detail:

```
hwloc/hwloc_base_dt.c: In function ‘prrte_hwloc_copy’:
hwloc/hwloc_base_dt.c:157:12: error: implicit declaration of function ‘hwloc_topology_dup’; did you mean ‘hwloc_topology_load’? [-Werror=implicit-function-declaration]
     return hwloc_topology_dup(dest, src);
            ^~~~~~~~~~~~~~~~~~
            hwloc_topology_load
```

FYI @bgoglin

**Comment by bgoglin** [comment]
Looks like HAVE_HWLOC_TOPOLOGY_DUP got set by external/configure.m4 for some reason. How do I get the configure log of that build?

**Comment by jsquyres** [comment]
I found the issue -- it's a compile bug in PRRTE.  See https://github.com/openpmix/prrte/pull/426.
