### ISSUE TITLE
Cleanup all pending libevent events

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#75]
r20566 added an event_base_free() into opal_event_fini() in order to clean up some memory upon shutdown.

Unfortunately, event_base_free() includes some assert()'s to ensure that libevent is totally empty (e.g., there are no pending events).  The rest of OMPI currently does not always clean up its pending events nicely (obvious examples that jump to mind are the modex and OOB pending receives that [may] have corresponding libevent events).  In these cases, the assert() will fail and we'll core dump (doh!).  

Needless to say, this is filling up disks that are running nightly MTT.  Bad.  :-)

The proper fix is to go clean up all pending libevent events before calling opal_event_fini() (e.g., pending OOB receives, etc.).  Tracking down all of these places could be a bit tricky and take a little time.  As such, I'm just about to commit a workaround that simply #if 0's out these asserts so that we don't keep dumping core.  

This ticket is a placeholder to fix the issue for real in the future.

**Comment by rhc54** [comment]
This was fixed long ago
