### ISSUE TITLE
fi_close(domain) EBUSY in mca_btl_ofi_finalize

### ISSUE THREAD

**Issue by hkuno** [open-mpi/ompi#7504]
### Please describe the system on which you are running

* Operating system/version:  CentOS
* Computer hardware: dl385
* Network type: N/A (for example, sockets) 

-----------------------------

## Details of the problem

When running osu\_put\_latency with a basic provider (in this case, sockets):

```shell
${bin}/mpirun --bind-to none --mca btl ^openib,tcp,vader --mca mtl ^psm,psm2,portals4 --mca pml ^ucx --mca mtl_ofi_provider_include sockets --mca btl_ofi_provider_include sockets --mca btl_ofi_disable_sep true --mca mtl_ofi_enable_sep 0 
${libexec}/osu-micro-benchmarks/mpi/one-sided/osu_put_latency -m 4194304:4194304
```

... fi\_close returns -FI\_EBUSY when mca\_btl\_ofi\_finalize tries to close the domain because dom->ref > 0 .

```shell
(gdb) step
sock_dom_close (fid=0x241e4b8) at prov/sockets/src/sock_dom.c:180
180             dom = container_of(fid, struct sock_domain, dom_fid.fid);
(gdb) list
175     }
176
177     static int sock_dom_close(struct fid *fid)
178     {
179             struct sock_domain *dom;
180             dom = container_of(fid, struct sock_domain, dom_fid.fid);
181             if (ofi_atomic_get32(&dom->ref))
182                     return -FI_EBUSY;
183
184             sock_conn_stop_listener_thread(&dom->conn_listener);
(gdb) n
181             if (ofi_atomic_get32(&dom->ref))
(gdb)
182                     return -FI_EBUSY;
```

When OFI Libfabric binds objects to endpoints, before the object can
be successfully closed, the endpoint must first be freed.  For scalable
endpoints, objects can also be bound to transmit and receive contexts,
and for objects that are bound to contexts, we need to first free the
contexts before freeing the endpoint. We also need to clear the memory
registration cache before closing the domain.

If we don't clean up properly, then fi\_close may not be able to close
the domain because its ref count will be non-zero.

**Comment by awlauria** [comment]
@hkuno did #7505 fix this? If so, we can close this issue.

**Comment by hkuno** [comment]
**> @hkuno did #7505 fix this? If so, we can close this issue.

@awlauria Yes, #7505 fixes this. We can close this isssue.
