### ISSUE TITLE
HWLOC information exported by Slurm/PMIx is not honored starting from v4.x

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#7507]
The Slurm plugin is still using legacy PMIx key to export hwloc topology:
```C
#define OPAL_PMIX_LOCAL_TOPO "pmix.ltopo"
```
It works fine in v3.x.
https://github.com/open-mpi/ompi/blob/v3.0.0rc1/opal/mca/hwloc/base/hwloc_base_util.c#L262

For some reason, in v.4 querying of this variable was removed. This causes up to 5 seconds of delays during job startup. 

I would like to return the support of this variable back in v4.
@hppritcha do you think it is possible?

**Comment by hppritcha** [comment]
@gpaulsen let's discuss on Monday if there's time.

**Comment by gpaulsen** [comment]
Closing.  PR 7536 merged to v4.0.x.  Will be in v4.0.4
