### ISSUE TITLE
What's the difference of map-by and bind-to

### ISSUE THREAD

**Issue by Leslie-Fang** [open-mpi/ompi#7515]
Open-MPI version:
3.0.4

Question:
When I use the mpirun, What's the difference of map-by and bind-to?

**Comment by jjhursey** [comment]
The `mpirun` man page has a pretty good description of these two options with a few examples:
 * https://www.open-mpi.org/doc/v3.0/man1/mpirun.1.php#sect9

```
mapping (--map-by)
  Assigns a default location to each process
ranking (--rank-by)
  Assigns an MPI_COMM_WORLD rank value to each process
binding (--bind-to)
  Constrains each process to run on specific processors
```
