### ISSUE TITLE
Bump minimum flex up to 2.35

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7520]
Per discussion in the Portland F2F meeting, we're bumping the minimum required flex version up to 2.35.

**Comment by jsquyres** [comment]
From 5.0 wiki:

* HACKING says we allow flex >= 2.5.4 because of CentOS 5. I think it's ok to disregard CentOS / RHEL 5 now -- let's bump the minimum version of flex up to 2.5.35 (see HACKING for details).
    * 2020-02: AGREED
    * RHEL 5 is officially dead.
    * @hjelmn is excited about removing a bunch of old flex-compat code.
    * Yes, let's move the min flex up to 2.5.35.

**Comment by jsquyres** [comment]
This is already done on master: https://github.com/open-mpi/ompi/blob/ddc19559af7a1efe9a68a183030fb943c4733341/contrib/dist/make_dist_tarball#L30

**Comment by awlauria** [comment]
@jsquyres looks like that version was added 10 years ago. Do we want a more recent version?
https://github.com/open-mpi/ompi/commit/08fbd6c644ffc1c3888e430eccc4873c4a4c57a4

**Comment by jsquyres** [comment]
Nope.  Flex is very slow moving.  We're not using any modern features.

I don't think our use of flex has even changed in ~10 years.  😄
