### ISSUE TITLE
Startup problems

### ISSUE THREAD

**Issue by chchang6** [open-mpi/ompi#7528]
Thank you for taking the time to submit an issue!

## Background information
Hi--We are troubleshooting problems with running MPI codes at scale. The jobs are failing with 
```
    ORTE does not know how to route a message to the specified daemon
    located on the indicated node:

      my node:   r1i0n8
      target node:  r1i0n9

    This is usually an internal programming error that should be
    reported to the developers. In the meantime, a workaround may
    be to set the MCA param routed=direct on the command line or
    in your environment. We apologize for the problem.
```
The runtime command and relevant environment being used is
```
    export OMPI_MCA_plm_base_version=5
    export OMPI_MCA_routed=direct
    export OMPI_MCA_routed_base_verbose=8
    export OMPI_MCA_plm_no_tree_spawn=1
    export OMPI_MCA_btl_openib_receive_queues="S,65536,1024,1008,64"
    `which mpirun` -np $((ranks_per_node*i)) --hostfile ./hostfile_ompi --show-progress --debug-daemons --get-stack-traces ./main3d_nomxm_noslurm
```

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
3.1.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Because we are disentangling Slurm issues from MPI issues from fabric issues, I have tried to build OpenMPI divorced as much from Slurm as possible. So, 
```
    [cchang@el3 ompi_git]$ git rev-parse HEAD
    96b70713db36c671db7723a5e7a2004ae21104f8
```
with configuration command
```
    ./configure --prefix=/nopt/nrel/apps/openmpi/3.1.3-noslurm_nomxm-gcc-7.3.0 --without-pmi --without-slurm --with-gnu-ld --with-verbs=/usr --with-lustre --without-mxm --enable-mpi-cxx --enable-mpi-fortran --without-scif --enable-static --enable-openib-rdmacm-ibaddr
```

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
```
[cchang@el3 ompi_git]$ git submodule status
[cchang@el3 ompi_git]$
```

### Please describe the system on which you are running

* Operating system/version: CentOS 7.4
* Computer hardware: Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz, 2*18-core, 96GB DRAM
* Network type: Mellanox EDR Infiniband

-----------------------------

## Details of the problem

The test case is the Amr/Advection_AmrCore tutorial of Amrex (https://github.com/AMReX-Codes/amrex). Compiler is a constant GCC 7.3.0 across tests. The errors that I am currently seeing are as described above; a successful run should not show much in stderr. Stdout should produce program-specific iteration data, but in the current tests simply hangs with no stdout.

I have managed to get a successful run at 128 nodes (4608 ranks), but consistent failure at 200 nodes (7200 ranks). These test numbers arose from testing our max_qp setting @ 262144, which I'm hypothesizing is low and may be unable to support larger scale jobs consistently. I believe it should be able to support 7200 ranks as configured, though (262144/36^2 = 202 nodes).

Let me know what other information is needed, thanks.

**Comment by jjhursey** [comment]
Can you try with the lastest 4.0.3?

There were some larger-scale fixes that went into the v4.x series that couldn't be easily ported back to the v3.x series. IIRC there is still some work to do in the v3.x series at scales above 64 or 128 nodes (I cannot find the issue on that at the moment). I wonder if you are running into that.

**Comment by chchang6** [comment]
Hi Josh, thanks for the info. I'll give v4 a spin and see if that resolves this issue. Will update.

**Comment by chchang6** [comment]
Running into mundane build problem with OpenMPI master branch,
configure:76702: checking hwloc building mode
configure:76704: result: embedded
configure:76733: hwloc builddir: /nopt/nrel/apps/openmpi/dist/ompi_git/opal/mca/hwloc/hwloc1117/hwloc
configure:76735: hwloc srcdir: /nopt/nrel/apps/openmpi/dist/ompi_git/opal/mca/hwloc/hwloc1117/hwloc
configure:76743: checking for hwloc version
configure:76747: error: Cannot continue

[cchang@el3 ompi_git]$ ls opal/mca/hwloc/hwloc1117/hwloc
include  Makefile.in  src

**Comment by jsquyres** [comment]
Can you try from a nightly snapshot tarball?  https://www.open-mpi.org/nightly/v4.0.x/

Building from git is tricky (e.g., we use git submodules now).

**Comment by chchang6** [comment]
Sorry for the delay, multiple issues. Got the Mar 8 snapshot built with

```
./configure --prefix=/nopt/nrel/apps/openmpi/4.0.x-unthr-gcc-7.3.0 --with-pmi=/nopt/slurm/current --with-gnu-ld --with-verbs=/usr --with-lustre --with-mxm=/opt/mellanox/mxm --enable-mpi-cxx --enable-mpi-fortran --without-scif --enable-static --enable-openib-rdmacm-ibaddr
```

Runs up to 16 nodes (576 ranks) fine with (we're using Slurm):

```
export OMPI_MCA_btl_openib_allow_ib="true"
srun --ntasks=576 --distribution=block,Pack ./$EXECUTABLE $INPUTS > log_${TEST_SUFFIX}
```

However with 32 nodes (1152 ranks) I see in stderr

```
--------------------------------------------------------------------------
No OpenFabrics connection schemes reported that they were able to be
used on a specific port.  As such, the openib BTL (OpenFabrics
support) will be disabled for this port.

  Local host:           r8i1n1
  Local device:         mlx5_0
  Local port:           1
  CPCs attempted:       rdmacm, udcm
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A call to mkdir was unable to create the desired directory:

  Directory: /tmp/scratch
  Error:     File exists

Please check to ensure you have adequate permissions to perform
the desired operation.
--------------------------------------------------------------------------
[r4i5n27:115859] [[3567,0],1091] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 107
[r4i5n27:115859] [[3567,0],1091] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 346
[r4i5n27:115859] [[3567,0],1091] ORTE_ERROR_LOG: Error in file ess_pmi_module.c at line 486
--------------------------------------------------------------------------
It looks like orte_init failed for some reason;...
```
Any suggestions for further testing are welcome!

**Comment by chchang6** [comment]
OK, by setting TMPDIR and TEMPDIR to an alternative location (not sure which is operative here), I've been able to get the snapshot working up to 384 nodes and counting. So looks good from here, closing out. Thanks for the help.
