### ISSUE TITLE
[Q] cartesian communicator and locality 

### ISSUE THREAD

**Issue by angainor** [open-mpi/ompi#7531]
I am wondering about the current implementation of the Cartesian communicator in OpenMPI. I am doing some tests with ompi 4.0.2 compiled against hwloc 1.11.8-4.el7.x86_64 from Centos 7.6. As I understand, if I set `reorder=1` in `MPI_Cart_create`, then MPI has the possibility to reorder the ranks to better fit the underlying hw topology. 

I tested rank placement on 4 compute nodes and compared the rank IDs and rank neighborhood obtained from the Cartesian communicator when running an application with `-map-by node` and `-map-by core`. I would hope that OpenMPI renumbers the ranks in a way to maximize node locality (and maybe NUMA locality) for neighbors in the Cartesian rank space, but the rank numbering is always the same as in the original communicator, and the neighborhood doesn't change.

Having a quick look at the implementation, topology seems to be somehow taken into account in `cart_create.c`, especially this line

```
     /* Now let that topology module rearrange procs/ranks if it wants to */
    err = topo->topo.cart.cart_create(topo, old_comm,
                                      ndims, dims, periods,
                                      (0 == reorder) ? false : true, comm_cart);
```
Am I using a too-old hwloc version for this to kick in, or is there other limitations?

FYR, here is the complete test code:
```
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>

int main(int argc, char *argv[])
{
    int dims[3] = {0}, periodic[3] = {1,1,1}, coords[3], nb_cart;
    int size, rank, rank_cart;
    MPI_Comm comm_cart;

    MPI_Init(&argc, &argv);
    MPI_Comm_size(MPI_COMM_WORLD, &size);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    MPI_Dims_create(size, 3, dims);
    if(rank==0) printf("dims %d %d %d\n", dims[0], dims[1], dims[2]);

    MPI_Cart_create(MPI_COMM_WORLD, 3, dims, periodic, 1, &comm_cart);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank_cart);
    MPI_Cart_coords(comm_cart, rank_cart, 3, coords);
    coords[0] += 1;
    MPI_Cart_rank(comm_cart, coords, &nb_cart);
    printf("%d %d nb %d\n", rank, rank_cart, nb_cart);

    MPI_Barrier(MPI_COMM_WORLD);
    MPI_Finalize();
}
```

Thanks!

**Comment by bosilca** [comment]
Marcin,

We are not honoring the reorder flag in the cartesian topology. If you want
reordering you need to use a distributed graph (with the treematch topo
module enabled).

George.

**Comment by angainor** [comment]
@bosilca Thanks, I will try that. Do you think that it would be an idea to implement in the future in OpenMPI? It would be very useful to have since it would increase the number of NUMA and node-local data exchanges in applications based on structured cartesian grids. User-side re-mapping of the rank order is of course possible, but I guess it would be easily done inside the Cartesian communicator.

**Comment by bosilca** [comment]
Sure, it can certainly be done help some types of applications. Bill Gropp published a [paper](http://wgropp.cs.illinois.edu/bib/talks/tdata/2018/nodecart-final.pdf) on this subject not long ago.

**Comment by angainor** [comment]
@bosilca Exactly what I was thinking about, thanks!
