### ISSUE TITLE
"mpirun -np 1 ..." emits warning

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7565]
I could be wrong, but I thought we decided to whitelist `-np` as an allowable "single dash" option, simply because of its massive prevalence out in the user community.

I notice that it's still emitting a warning:

```
$ mpirun -np 1 uptime
--------------------------------------------------------------------------
WARNING: All multi-character command line options must be prefixed with double
dashes, not a single dash:

  Deprecated option:   -np
  Corrected option:    --np

We have updated this for you and will proceed. However, this will be treated
as an error in a future release. Please update your command line.
--------------------------------------------------------------------------

******* Corrected cmd line: mpirun --np 1 uptime


 15:04:20 up 200 days, 10:36, 80 users,  load average: 0.48, 1.53, 1.26
```

Can we whitelist it to not emit this warning?

If someone points me in the right direction, I'd be happy to submit a PR.

**Comment by rhc54** [comment]
It was, but somehow it slipped out from under the protection. I have an update coming that touches that area - easy enough to fix it there.

**Comment by jsquyres** [comment]
Thanks!
