### ISSUE TITLE
-L/usr/lib64 linking flags when lustre is in system space

### ISSUE THREAD

**Issue by dshrader** [open-mpi/ompi#7580]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

3.1.6 and 4.0.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From release tarball

### Please describe the system on which you are running

* Operating system/version: OS is based on RHEL 7
* Computer hardware: Intel
* Network type: Omnipath

-----------------------------

## Details of the problem

For some time now, I have had `-L/usr/lib64 -Wl,-rpath -Wl,/usr/lib64` appear in my Open MPI helper files (e.g., `<install dir>/share/openmpi/mpicc-helper.txt`). These linking flags are inappropriate as they artificially elevate the priority of every library in `/usr/lib64` at execution time (see the man page for ld-linux.so), which is pretty much every library on my system. I have been manually removing the flags from the helper files up until now.

It looks like this comes from two semi-competing blocks of code in configure. In 4.0.3's configure, at around line 295134, `ompi_check_lustre_dir` is set to `/usr` because `with_lustre` is empty (verified for my case with print statements). Then, on line 295140, `ompi_check_lustre_libdir` is set to `$ompi_check_lustre_dir/lib64`. This effectively sets `ompi_check_lustre_libdir` to `/usr/lib64`. Then, on line 295981, there is a test on whether or not `ompi_check_lustre_libdir` is empty, which it isn't. In the conditional where it isn't empty, the string `-L$ompi_check_lustre_libdir` is added to `fs_lustre_LDFLAGS` and `LDFLAGS`. This is where the string makes its way in to the set of permanent flags. It can be seen in the final list of variables in config.log and in lustre-specific variables in the Makefiles. At some point, the -rpath portion gets added; possibly in the `make install` step?

I commented out lines 295983 and 295984 in configure and rebuilt Open MPI. This keeps `-L$ompi_check_lustre_libdir` from being added to fs_lustre_LDFLAGS and LDFLAGS. There was no `-L/usr/lib64 -Wl,-rpath -Wl,/usr/lib64` string in the helper scripts, which tells me that the root cause of that string's appearance is indeed in that area of configure.

In talking with Howard, it looks like the first section of code (around line 295134) might not be necessary. The second section of code (the one around line 295981) seems to deal with lustre libraries and headers in system space; that code just can't run because of settings made in the first section. I commented out lines 295133 through 295143 in an unmodified 4.0.3 configure, and rebuilt Open MPI. The problematic `-L/usr/lib64 -Wl,-rpath -Wl,/usr/lib64` flags where indeed missing from the helper scripts, and Open MPI seemed to work as expected.

Thanks,
David

**Comment by hppritcha** [comment]
fixed via #7661
