### ISSUE TITLE
Cannot compile on Mac with Nag 6.2

### ISSUE THREAD

**Issue by pbrady** [open-mpi/ompi#7583]
I'm on MacOS Catalina and attempting to use Nag6.2 as the fortran compiler to build Open MPI v4.0.3 (source tarball).  I have tried using the system clang compilers as well as gcc/g++ 9.3 from homebrew.  If I use gfortran from homebrew then open mpi compiles without issue so Nag appears to be the culprit here. 

The configure step appears to be successful and I've attached the [config.log](https://github.com/open-mpi/ompi/files/4411489/config.log).

`make` is able to run for quite some time but I keep getting the following error:
```shell
Making all in mpi/fortran/use-mpi-tkr
  PPFC     mpi.lo
NAG Fortran Compiler Release 6.2(Chiyoda) Build 6255
Error: ../../../../../ompi/mpi/fortran/use-mpi-tkr/mpi.F90, line 23: Invalid #line directive
Error: ../../../../../ompi/mpi/fortran/use-mpi-tkr/mpi.F90, line 25: Syntax error
       detected at <invalid token>@MODULE
Error: ../../../../../ompi/mpi/fortran/use-mpi-tkr/mpi.F90, line 46: Invalid #line directive
Error: ../../../../../ompi/mpi/fortran/use-mpi-tkr/mpi.F90, line 47: Invalid #line directive
Error: ../../../../../ompi/mpi/fortran/use-mpi-tkr/mpi.F90, line 47: Syntax error
Error: ../../../../../ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h, line 27: Syntax error
       detected at END@FUNCTION
```

I get the same errors when trying to compile Open MPI v3.1.5.

Any advice on how to fix this would be greatly appreciated.

**Comment by ggouaillardet** [comment]
On Linux, `.f90` files are compiled with the "standard" flags, but `.F90` files are preprocessed before being compiled.
Both error message and the OS X case insensitive filesystem points to the `.F90` not being preprocessed on OS X.

Assuming any fortran file can be preprocessed by NAG compiler via the `-fpp` flag, I would suggest you try
```
configure FCFLAGS=-fpp ...
```
and see if it helps

**Comment by pbrady** [comment]
Was able to compile and successfully run `make check` with the added `-fpp` option.  I'll leave this issue open because this seems like something that should be handled by the build system.  Feel free to close if you disagree.

**Comment by ggouaillardet** [comment]
I agree this is something that should be handled automatically.

Do you have any possibility to run the same test on Linux?
On second thought, I am not sure OSX case insensitive filesystem is involved here.

**Comment by ggouaillardet** [comment]
@pbrady could you please give a try to #7584?

you can manually download the patch at https://github.com/open-mpi/ompi/pull/7584.patch and apply it vs the 4.0.3 sources, and then run `./autogen.pl --force` (note this requires recent autotools)

This should automatically add the `-fpp` flag to `nagfor`.

**Comment by pbrady** [comment]
@ggouaillardet I tested the patch and was able to compile successfully with the following config:

```shell
../configure FC=nagfor
```
Your patch is correctly adding `-fpp` and fixes my issues.

On linux we build with nagfor without explicitly specifying `FCFLAGS` so this is mac related.  However, gfortran does the expected thing on mac (as it does on linux) while nag behaves differently.

**Comment by nncarlson** [comment]
Let's make sure it doesn't screw up x86_64 platforms.  There NAG passes '.F90' source files through the preprocessor automatically

**Comment by pbrady** [comment]
@nncarlson Are you going to test the patch on a linux box?

**Comment by nncarlson** [comment]
> @nncarlson Are you going to test the patch on a linux box?

I was going to let you test it :-) but I guess I can.  What exactly should I apply the patch to?  Is the latest 4.0.x release good enough, or do I need to clone the repo?

**Comment by pbrady** [comment]
Autotools builds character and I think I acquired enough yesterday to last awhile.  I used the 4.0.3 src tarball and applied the patch via `git apply` at the top level directory after unpacking.

**Comment by nncarlson** [comment]
Uh, actually would you mind testing it?  Is the VPN usable for you to the petaca machines?  I'd test with both NAG 6.2 and 7.0 just to be sure.

**Comment by pbrady** [comment]
I appear to be cursed with a decent VPN connection today... I'll report back in a bit

**Comment by jsquyres** [comment]
![everything-is-fine](https://user-images.githubusercontent.com/617316/78163216-1219ba80-7416-11ea-85db-d40f5eaa9330.jpg)

**Comment by pbrady** [comment]
I applied the patch and was able to successfully configure, compile and check openmpi with nag6.2 and 7.0 on linux.

@ggouaillardet This patch fixes my issues on mac and does not cause any problems on linux.

**Comment by ggouaillardet** [comment]
FWIW, the patch is not NAG nor OSX specific, and was designed not to break existing environments.

 * compile a `.F90` files that fails if not preprocessed
   - if success, then no change
   - if fail, then try to compile the same `.F90` file with the `-fpp` flag
      - if success, add the `-fpp` flag to `FCFLAGS`
     - if fail, then abort
