### ISSUE TITLE
mpirun fails with multiple clients

### ISSUE THREAD

**Issue by aasraoui** [open-mpi/ompi#7607]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
Openmpi version:
openmpi-4.0.1

Os:
```
CentOS Linux release 8.1.1911 (Core)
root@client2 ~]# uname -r
4.18.0-147.5.1.el8_1.x86_64
[root@client2 ~]#
```

Openmpi version:
openmpi-4.0.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

openmpi-4.0.1.tar.gz

### Please describe the system on which you are running

* Operating system/version: 
* Computer hardware: 
* Network type: 

os 8.1
network 40Gig mellanox

## Details of the problem

```
[root@client2 ~]# /home/root/.openmpi/bin/mpirun --allow-run-as-root --hostfile myhostfile -np 2 ./mdtest -F -n 1 -d "/mnt/beegfs"
/root/.bashrc: line 11: mpirun: command not found
declare -x DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/0/bus"
declare -x HOME="/root"
declare -x LANG="en_US.UTF-8"
declare -x LOGNAME="root"
declare -x OLDPWD
declare -x OMPI_MCA_orte_precondition_transports="13241234acffedeb-abcdefabcdef1233"
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"
declare -x PWD="/root"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_CLIENT="10.10.10.12 40130 22"
declare -x SSH_CONNECTION="10.10.10.12 40130 10.10.10.14 22"
declare -x USER="root"
declare -x XDG_RUNTIME_DIR="/run/user/0"
declare -x XDG_SESSION_ID="284"
-- started at 04/06/2020 19:10:55 --

mdtest-1.9.3 was launched with 2 total task(s) on 2 node(s)
Command line used: ./mdtest -F -n 1 -d /mnt/beegfs
Path: /mnt
FS: 50.0 GiB   Used FS: 12.1%   Inodes: 25.0 Mi   Used Inodes: 0.7%
--------------------------------------------------------------------------
WARNING: Open MPI accepted a TCP connection from what appears to be a
another Open MPI process but cannot find a corresponding process
entry for that peer.

This attempted connection will be ignored; your MPI job may or may not
continue properly.

  Local host: client3
  PID:        15216
--------------------------------------------------------------------------
```

**Comment by jsquyres** [comment]
I see the following in your output:

```
/root/.bashrc: line 11: mpirun: command not found
```

That is a potential problem source and should be fixed before digging any deeper.

**Comment by aasraoui** [comment]
the mpirun is invoked from this path:/home/root/.openmpi/bin/mpirun 
there is no reference for mpirun in the .bashrc ..
thanks!

**Comment by jsquyres** [comment]
There must be somewhere -- that line is in your output.  One way or another, that error should be resolved before digging deeper.

**Comment by aasraoui** [comment]
thanks jsquyres,  trying to use mpirun from  mlnx-ofed 4.5 on centos 7.6
it is reporting the ucx versions of 1.5, although ofed4.5 is using version 1.8


[root@client4 hpcx-v2.6.0-gcc-MLNX_OFED_LINUX-4.5-1.0.1.0-redhat7.6-x86_64]# mpirun --allow-run-as-root --hostfile mfile.1 -np 2 ./mdtest -F 1 -n 1 /mnt/beegfs
[1587490450.253368] [client5:20941:0]    ucp_context.c:1187 UCX  WARN  UCP version is incompatible, required: 1.8, actual: 1.5 (release 0 /lib64/libucp.so.0)
[1587490450.305198] [client5:20941:0]         ucp_ep.c:502  UCX  ERROR the parameter params->address must not be NULL
[client5:20941] pml_ucx.c:385  Error: ucp_ep_create(proc=1) failed: Invalid parameter
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  PML add procs failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
[client5:20941] *** An error occurred in MPI_Init
[client5:20941] *** reported by process [1850998785,1]
[client5:20941] *** on a NULL communicator
[client5:20941] *** Unknown error
[client5:20941] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[client5:20941] ***    and potentially your MPI job)
[root@client4 hpcx-v2.6.0-gcc-MLNX_OFED_LINUX-4.5-1.0.1.0-redhat7.6-x86_64]#

**Comment by jsquyres** [comment]
@jladd-mlnx @artpol84 @yosefe Can someone from Mellanox help this user?  Thanks!

**Comment by jladd-mlnx** [comment]
@aasraoui it looks like you're trying to run HPC-X v2.6 over RoCE (and *not* MPI from MOFED.)  It also looks like there is a UCX version mismatch between host 1 and host 2 as specified in your Hostfile. Per the HPC-X user manual:

> When HPC-X is launched with Open MPI in an environment where there is no resource manager installed (slurm,pbs, etc.),or when it is launched from a compute node, the OMPI default rsh/ssh based launcher will be used. This would prevent the
launch from propagating the library path to the compute nodes. Thus, make sure to pass LD_LIBRARY_PATH variable as follows:
`% mpirun -x LD_LIBRARY_PATH -np 2 -H host1,host2 $HPCX_MPI_TESTS_DIR/examples/hello_c`

Can you try adding `-x LD_LIBRARY_PATH` to your command line, please.

**Comment by aasraoui** [comment]
@jladd-mlnx, thanks this works!! 
do you have documentation on how to launch with with slurs ?

hpcx-v2.6.0-gcc-MLNX_OFED_LINUX-4.5-1.0.1.0-redhat7.6-x86_64]# mpirun -v --oversubscribe --allow-run-as-root -x LD_LIBRARY_PATH --hostfile mfile.1 -np 32 ./mdtest -F 1 -n 8 -i 3 -d /mnt/beegfs
-- started at 04/22/2020 13:11:26 --

mdtest-1.9.3 was launched with 32 total task(s) on 2 node(s)
Command line used: ./mdtest -F 1 -n 8 -i 3 -d /mnt/beegfs
Path: /mnt
FS: 50.0 GiB   Used FS: 12.8%   Inodes: 25.0 Mi   Used Inodes: 0.7%

32 tasks, 256 files

SUMMARY: (of 3 iterations)
   Operation                      Max            Min           Mean        Std Dev
   ---------                      ---            ---           ----        -------
   File creation     :       3951.763       2655.029       3437.650        562.407
   File stat         :      45515.562      12424.590      28888.420      13509.826
   File read         :      15126.774       8775.478      12712.117       2807.379
   File removal      :       4525.857       4247.262       4380.144        114.097
   Tree creation     :       1430.535        828.896       1057.671        265.912
   Tree removal      :       1460.752        909.470       1242.657        239.322

-- finished at 04/22/2020 13:11:26 --

**Comment by jladd-mlnx** [comment]
@aasraoui Great news! As for SLURM, you will first need to have your cluster admin install [SLURM](https://slurm.schedmd.com/overview.html ). Once that is done, you won't need to specify a hostfile or forward the `LD_LIBRARY_PATH` into the remote environment. Launching will "just work". I'm going to go ahead and close this issue.
