### ISSUE TITLE
MPI_Intercomm_merge fails when multiple interfaces are on node

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#7620]
https://mtt.open-mpi.org/index.php?do_redir=3216

The intercomm_create test ends with an intercomm_merge of the three different communicators. However, it appears that the various processes wind up with different ordering of the resulting communicator, resulting in errors for "unexpected identifier" when the procs attempt to communicate using the final merged communicator.
```text
b: MPI_Intercomm_create( intra, 0, intra, MPI_COMM_NULL, 201, &inter) [rank 3]
b: MPI_Intercomm_create( intra, 0, intra, MPI_COMM_NULL, 201, &inter) [rank 2]c:
MPI_Intercomm_create( MPI_COMM_WORLD, 0, intra, 0, 201, &inter) [rank 3]
a: MPI_Intercomm_create( ab_intra, 0, ac_intra, 2, 201, &inter) (0)
c: MPI_Intercomm_create( MPI_COMM_WORLD, 0, intra, 0, 201, &inter) [rank 2]
a: MPI_Intercomm_create( ab_intra, 0, ac_intra, 2, 201, &inter) (0)a: intercomm_create (0)
a: barrier on inter-comm - before
c: intercomm_create (0)
c: barrier on inter-comm - before
c: barrier on inter-comm - after
c: intercomm_create (0)
c: barrier on inter-comm - before
c: barrier on inter-comm - after
b: intercomm_create (0)
b: barrier on inter-comm - before
b: barrier on inter-comm - aftera: intercomm_create (0)
a: barrier on inter-comm - before
a: barrier on inter-comm - after
b: intercomm_create (0)
b: barrier on inter-comm - before
b: barrier on inter-comm - after
a: barrier on inter-comm - after
c: intercomm_merge(0) (0) [rank 5]
c: intercomm_merge(0) (0) [rank 4]
a: intercomm_merge(0) (0) [rank 1]
b: intercomm_merge(1) (0) [rank 2]a: intercomm_merge(0) (0) [rank 0]
b: intercomm_merge(1) (0) [rank
3][ip-172-31-69-97][[46516,2],1][btl_tcp_endpoint.c:653:mca_btl_tcp_endpoint_recv_connect_ack]
received unexpected process identifier: got [[46516,2],0] expected [[46516,3],0]
[ip-172-31-69-97:57348] pml_ob1_sendreq.c:189
FATAL[ip-172-31-69-97][[46516,3],1][btl_tcp.c:566:mca_btl_tcp_recv_blocking] recv(13) failed:
Connection reset by peer (104)
(null)
(null)
(null)
```

**Comment by bosilca** [comment]
When the BTLs are correctly configured (aka single IP interface per node) this test passes every time. The issue here seems to arise from the BTL TCP IP matching as indicated by the error message.

**Comment by rhc54** [comment]
@bosilca If this helps, I'm told by @markalle that IBM is running single node, so this is all happening on only one node. I guess TCP is involved as we still don't have inter-job shmem support, but it seems a little odd that the TCP matching code doesn't work even when all procs are on the same node.

How do we fix it?

**Comment by bosilca** [comment]
Right, TCP BTL takes over, even for single node runs, as soon as we have multiple jobs. The error with the matching is related to the support for multiple interfaces, if @markalle limits the active interfaces (btl_tcp_if_include or btl_tcp_if_exclude) the matching code is not needed, and the test will work seamlessly. (BTW as I said in my prior answer I did limit the interfaces used).

The code currently in use for matching IPs was developed by Amazon (git blame indicates @wckzhang). We might get some help from there.

**Comment by rhc54** [comment]
@bwbarrett @rajachan @wckzhang Can we get some help here? I agree we could just limit the interfaces on the IBM MTT machine, but that just deflects the problem into the user community. This seems like a pretty simple scenario that we should handle.

**Comment by bwbarrett** [comment]
That's, um, weird.  I'll raise it internally, but not sure how fast we'll be able to respond.

**Comment by markalle** [comment]
I think @awlauria was the one saying that the IBM MTT was single host, but if I'm reading the above right, this is a test out of the `ibm/` directory but is it an IBM run of MTT?  Anyway I'm just saying that to say I'm not certain that the above is single host.

**Comment by rhc54** [comment]
Oh - sorry about that @markalle ! Old fossil brain at work again.

Yes, that is from one of many IBM MTT runs that are showing this failure.

**Comment by rhc54** [comment]
My bad - should correct myself. The link in the original issue comment is to an example from Amazon Slurm test. However, there are multiple ones from IBM as well. I just cited this one at semi-random as the failure signature is the same for all.

**Comment by wckzhang** [comment]
Taking a look at it, I'll try to reproduce it manually.

**Comment by wckzhang** [comment]
I'm having a bit of difficulty reproducing this. I went through the MTT logs for IBM's dynamic/intercomm_create tests: [This search](https://mtt.open-mpi.org/index.php?limit=&wrap=&trial=&enable_drilldowns=&yaxis_scale=&xaxis_scale=&hide_subtitle=&split_graphs=&remote_go=&do_cookies=&phase=test_run&text_start_timestamp=2021-01-09+01%3A11%3A59+-+2021-03-16+01%3A11%3A59&text_platform_hardware=%5Eppc64le%24&show_platform_hardware=show&text_os_name=%5ELinux%24&show_os_name=show&text_mpi_name=%5Eompi-nightly-v4.1.x%24&show_mpi_name=show&text_mpi_version=&show_mpi_version=show&text_suite_name=%5Eibm%24&show_suite_name=show&text_test_name=all&show_test_name=hide&text_np=%5E2%24&show_np=show&text_full_command=dynamic%2Fintercomm_create&show_full_command=show&text_http_username=%5Eibm%24&show_http_username=show&text_local_username=all&show_local_username=hide&text_platform_name=%5Eibm-community%24&show_platform_name=show&click=Detail&phase=test_run&test_result=_run_f&text_compute_cluster_id=&text_os_version=&show_os_version=&text_platform_type=&show_platform_type=&text_submit_id=&text_hostname=&show_hostname=&text_mpi_get_id=&text_mpi_install_compiler_id=&text_mpi_install_configure_id=&text_mpi_install_id=&text_compiler_name=&show_compiler_name=&text_compiler_version=&show_compiler_version=&text_vpath_mode=&show_vpath_mode=&text_endian=&show_endian=&text_bitness=&show_bitness=&text_configure_arguments=&text_exit_value=&show_exit_value=&text_exit_signal=&show_exit_signal=&text_duration=&show_duration=&text_client_serial=&show_client_serial=&text_result_message=&text_result_stdout=&text_result_stderr=&text_environment=&text_description=&text_test_build_id=&text_test_build_compiler_id=&text_test_run_id=&text_test_name_id=&text_test_run_command_id=&text_test_suite_id=&text_performance_id=&text_launcher=&show_launcher=&text_resource_mgr=&show_resource_mgr=&text_network=&show_network=&text_parameters=&show_parameters=&lastgo=summary).

All of the failures seem to be with either ^tcp or only with self & vader. The only failure I could see that could be with TCP was this one:

Command:
```
mpirun  --np 2   --prefix /tmp/mpiczar/scratch/ompi-4.1.x_gcc/installs/Z6qw/install dynamic/intercomm_create
```
Output:
```

--------------------------------------------------------------------------
 WARNING: There was an error initializing an OpenFabrics device. 

   Local host:   c656f6n09
   Local device: mlx5_0
 --------------------------------------------------------------------------
[c656f6n09:03056] [[7767,1],1] selected pml ob1, but peer [[7767,1],0] on c656f6n09 selected pml ucx
 --------------------------------------------------------------------------
 MPI_INIT has failed because at least one MPI process is unreachable
 from another. This *usually* means that an underlying communication
 plugin -- such as a BTL or an MTL -- has either not loaded or not
 allowed itself to be used.  Your MPI job will now abort.

  You may wish to try to narrow down the problem; 

  * Check the output of ompi_info to see which BTL/MTL plugins are
     available.
  * Run your application with MPI_THREAD_SINGLE.
  * Set the MCA parameter btl_base_verbose to 100 (or mtl_base_verbose,
    if using MTL-based communications) to see exactly which
    communication plugins were considered and/or discarded.
 --------------------------------------------------------------------------
[c656f6n09:03056] *** An error occurred in MPI_Init
[c656f6n09:03056] *** reported by process [509018113,1] 
[c656f6n09:03056] *** on a NULL communicator
[c656f6n09:03056] *** Unknown error
[c656f6n09:03056] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[c656f6n09:03056] ***    and potentially your MPI job)[c656f6n09:03051] 1 more process has sent help message help-mpi-btl-openib.txt / error in device init
[c656f6n09:03051] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

This one is a bit odd, but I'm not convinced that it's due to interface matching, not sure why one process selects ob1 and the other selects ucx.

I ran with 2 interfaces and a hostfile, though I didn't compile with UCX. I had no issues passing the test with both intra and inter node with 1 or 2 interfaces. I verified that the interfaces were being detected and matched as well in the btl.

```
[ec2-user@ip-172-31-15-217 tcp]$ mpirun -np 2 -N 1 --hostfile ~/hfile --mca pml ob1 ~/ibm/dynamic/intercomm_create
b: MPI_Intercomm_create( intra, 0, intra, MPI_COMM_NULL, 201, &inter) [rank 3]
b: MPI_Intercomm_create( intra, 0, intra, MPI_COMM_NULL, 201, &inter) [rank 2]
a: MPI_Intercomm_create( ab_intra, 0, ac_intra, 2, 201, &inter) (0)
c: MPI_Intercomm_create( MPI_COMM_WORLD, 0, intra, 0, 201, &inter) [rank 3]
a: MPI_Intercomm_create( ab_intra, 0, ac_intra, 2, 201, &inter) (0)
c: MPI_Intercomm_create( MPI_COMM_WORLD, 0, intra, 0, 201, &inter) [rank 2]
c: intercomm_create (0)
c: barrier on inter-comm - before
a: intercomm_create (0)
a: barrier on inter-comm - before
c: intercomm_create (0)
c: barrier on inter-comm - before
b: intercomm_create (0)
b: barrier on inter-comm - before
a: intercomm_create (0)
a: barrier on inter-comm - before
b: intercomm_create (0)
b: barrier on inter-comm - before
c: barrier on inter-comm - after
c: barrier on inter-comm - after
a: barrier on inter-comm - after
b: barrier on inter-comm - after
a: barrier on inter-comm - after
b: barrier on inter-comm - after
a: intercomm_merge(0) (0) [rank 1]
c: intercomm_merge(0) (0) [rank 1]
c: intercomm_merge(0) (0) [rank 0]
a: intercomm_merge(0) (0) [rank 0]
b: intercomm_merge(1) (0) [rank 4]
b: intercomm_merge(1) (0) [rank 5]
c: barrier (0)
a: barrier (0)
a: barrier (0)
b: barrier (0)
c: barrier (0)
b: barrier (0)
```

Can someone let me know how many interfaces they were able to reproduce this with and/or a recent MTT run it occurred in? I wonder if it's related to some slurm or ucx interaction, but it's a little unclear to me what the reproducer for this issue is.

**Comment by wckzhang** [comment]
Going through more mtt logs, I found [some more recent runs](https://mtt.open-mpi.org/index.php?limit=&wrap=&trial=&enable_drilldowns=&yaxis_scale=&xaxis_scale=&hide_subtitle=&split_graphs=&remote_go=&do_cookies=&phase=test_run&text_start_timestamp=2021-01-09+01%3A11%3A59+-+2021-03-16+01%3A11%3A59&text_platform_hardware=all&show_platform_hardware=show&text_os_name=all&show_os_name=show&text_mpi_name=all&show_mpi_name=show&text_mpi_version=&show_mpi_version=show&text_suite_name=%5Eibm%24&show_suite_name=show&text_test_name=all&show_test_name=hide&text_np=%5E2%24&show_np=show&text_full_command=dynamic%2Fintercomm_create&show_full_command=show&text_http_username=all&show_http_username=show&text_local_username=all&show_local_username=hide&text_platform_name=all&show_platform_name=show&click=Detail&phase=test_run&test_result=_run_f&text_compute_cluster_id=&text_os_version=&show_os_version=&text_platform_type=&show_platform_type=&text_submit_id=&text_hostname=&show_hostname=&text_mpi_get_id=&text_mpi_install_compiler_id=&text_mpi_install_configure_id=&text_mpi_install_id=&text_compiler_name=&show_compiler_name=&text_compiler_version=&show_compiler_version=&text_vpath_mode=&show_vpath_mode=&text_endian=&show_endian=&text_bitness=&show_bitness=&text_configure_arguments=&text_exit_value=&show_exit_value=&text_exit_signal=&show_exit_signal=&text_duration=&show_duration=&text_client_serial=&show_client_serial=&text_result_message=&text_result_stdout=&text_result_stderr=&text_environment=&text_description=&text_test_build_id=&text_test_build_compiler_id=&text_test_run_id=&text_test_name_id=&text_test_run_command_id=&text_test_suite_id=&text_performance_id=&text_launcher=&show_launcher=&text_resource_mgr=&show_resource_mgr=&text_network=&show_network=&text_parameters=&show_parameters=&lastgo=summary)

It looks like we're seeing this on some amazon runs:

```
b: MPI_Intercomm_create( intra, 0, intra, MPI_COMM_NULL, 201, &inter) [rank 3]
b: MPI_Intercomm_create( intra, 0, intra, MPI_COMM_NULL, 201, &inter) [rank 2]a:
MPI_Intercomm_create( ab_intra, 0, ac_intra, 2, 201, &inter) (0)
c: MPI_Intercomm_create( MPI_COMM_WORLD, 0, intra, 0, 201, &inter) [rank 3]a: MPI_Intercomm_create(
ab_intra, 0, ac_intra, 2, 201, &inter) (0)
c: MPI_Intercomm_create( MPI_COMM_WORLD, 0, intra, 0, 201, &inter) [rank 2]a: intercomm_create (0)
a: barrier on inter-comm - before
a: barrier on inter-comm - afterc: intercomm_create (0)
c: barrier on inter-comm - before
c: barrier on inter-comm - after
c: intercomm_create (0)
c: barrier on inter-comm - before
c: barrier on inter-comm - after
b: intercomm_create (0)
b: barrier on inter-comm - before
b: barrier on inter-comm - after
a: intercomm_create (0)
a: barrier on inter-comm - before
a: barrier on inter-comm - after
b: intercomm_create (0)
b: barrier on inter-comm - before
b: barrier on inter-comm - after
c: intercomm_merge(0) (0) [rank 1]
c: intercomm_merge(0) (0) [rank 0]
a: intercomm_merge(0) (0) [rank 1]
b: intercomm_merge(1) (0) [rank 4]
a: intercomm_merge(0) (0) [rank 0]b: intercomm_merge(1) (0) [rank 5]
--------------------------------------------------------------------------
WARNING: Open MPI accepted a TCP connection from what appears to be a
another Open MPI process but cannot find a corresponding process
entry for that peer.

This attempted connection will be ignored; your MPI job may or may not
continue properly.

  Local host: ip-172-31-4-201
  PID:        52825
--------------------------------------------------------------------------
[ip-172-31-4-201][[52898,2],1][btl_tcp_endpoint.c:657:mca_btl_tcp_endpoint_recv_connect_ack]
received unexpected process identifier: got [[52898,2],0] expected [[52898,3],0]
malloc debug: pml:ob1: mca_pml_ob1_match_completion_free: operation failed with code -12
[ip-172-31-4-201:00000] *** An error occurred in Socket closed
[ip-172-31-4-201:00000] *** reported by process [3466723330,0]
[ip-172-31-4-201:00000] *** on a NULL communicator
[ip-172-31-4-201:00000] *** Unknown error
[ip-172-31-4-201:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[ip-172-31-4-201:00000] ***    and MPI will try to terminate your MPI job as well)
[ip-172-31-4-201:00000] *** An error occurred in Socket closed
[ip-172-31-4-201:00000] *** reported by process [3466723330,1]
[ip-172-31-4-201:00000] *** on a NULL communicator
[ip-172-31-4-201:00000] *** Unknown error
[ip-172-31-4-201:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[ip-172-31-4-201:00000] ***    and MPI will try to terminate your MPI job as
well)[ip-172-31-4-201:00000] *** An error occurred in Socket closed
[ip-172-31-4-201:00000] *** reported by process [3466723329,0]
[ip-172-31-4-201:00000] *** on a NULL communicator
[ip-172-31-4-201:00000] *** Unknown error
[ip-172-31-4-201:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[ip-172-31-4-201:00000] ***    and MPI will try to terminate your MPI job as
well)[ip-172-31-4-201:00000] *** An error occurred in Socket closed
[ip-172-31-4-201:00000] *** reported by process [3466723329,1]
[ip-172-31-4-201:00000] *** on a NULL communicator
[ip-172-31-4-201:00000] *** Unknown error
[ip-172-31-4-201:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[ip-172-31-4-201:00000] ***    and MPI will try to terminate your MPI job as
well)[ip-172-31-4-201:00000] *** An error occurred in Socket closed
[ip-172-31-4-201:00000] *** reported by process [3466723331,0]
[ip-172-31-4-201:00000] *** on a NULL communicator
[ip-172-31-4-201:00000] *** Unknown error
[ip-172-31-4-201:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[ip-172-31-4-201:00000] ***    and MPI will try to terminate your MPI job as well)
```

The Amazon MTT runs only run with a single interface, so this seems a bit unusual to me. I wasn't able to reproduce this manually with a single interface with a similar mpirun command as before.

The other failure:

```
--------------------------------------------------------------------------
[[18473,1],1]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: ip-172-31-5-233

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
----------------------------------------------------------------------------------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[18473,2],0]) is on host: ip-172-31-5-233
  Process 2 ([[18473,1],0]) is on host: unknown!
  BTLs attempted: self tcp vader

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------[ip-172-31-5-233:60635]
[[18473,1],0] ORTE_ERROR_LOG: Unreachable in file dpm/dpm.c at line 433
[ip-172-31-5-233:60636] [[18473,1],1] ORTE_ERROR_LOG: Unreachable in file dpm/dpm.c at line 433
[ip-172-31-5-233:60641] [[18473,2],0] ORTE_ERROR_LOG: Unreachable in file dpm/dpm.c at line 433
[ip-172-31-5-233:60642] [[18473,2],1] ORTE_ERROR_LOG: Unreachable in file dpm/dpm.c at line
433[ip-172-31-5-233:60636] *** An error occurred in MPI_Comm_spawn
[ip-172-31-5-233:60636] *** reported by process [1210646529,1]
[ip-172-31-5-233:60636] *** on communicator MPI_COMM_WORLD
[ip-172-31-5-233:60636] *** MPI_ERR_INTERN: internal error
[ip-172-31-5-233:60636] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[ip-172-31-5-233:60636] ***    and potentially your MPI
job)--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_dpm_dyn_init() failed
  --> Returned "Unreachable" (-12) instead of "Success" (0)
--------------------------------------------------------------------------[ip-172-31-5-233:60642]
*** An error occurred in MPI_Init
[ip-172-31-5-233:60642] *** reported by process [1210646530,1]
[ip-172-31-5-233:60642] *** on a NULL communicator
[ip-172-31-5-233:60642] *** Unknown error
[ip-172-31-5-233:60642] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[ip-172-31-5-233:60642] ***    and potentially your MPI job)[ip-172-31-3-136:27343] 3 more processes
have sent help message help-mpi-btl-base.txt / btl:no-nics
[ip-172-31-3-136:27343] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error
messages[ip-172-31-3-136:27343] 3 more processes have sent help message help-mca-bml-r2.txt /
unreachable proc
[ip-172-31-3-136:27343] 1 more process has sent help message help-mpi-errors.txt /
mpi_errors_are_fatal
[ip-172-31-3-136:27343] 1 more process has sent help message help-mpi-runtime.txt /
mpi_init:startup:internal-failure
[ip-172-31-3-136:27343] 1 more process has sent help message help-mpi-errors.txt /
mpi_errors_are_fatal unknown handle
```

I saw this same error with the ibm tests with only self, vader. Seems unusual that process 2 host is unknown.
```
  Process 2 ([[18473,1],0]) is on host: unknown!
```

**Comment by rhc54** [comment]
I can't comment on what you are seeing. All I can say is that the most common problem we have had is the one you report in the first half of your prior comment - i.e., getting connection request from an incorrect/unexpected process identifier. @bosilca found that this went away when he restricted the system to a single TCP device, hence his conclusion that it is a reachability issue.

I leave it to you to figure out what to do from here 😄

**Comment by bosilca** [comment]
Let me try to clarify what I found. Multiple interfaces were a prerequisite, even if they were not all used. In my case, I had multiple discovered TCP interfaces per node (ipoib and at least one ethernet), but I'm not sure if they were all used or could all have been used (due to the routing tables). Anyway, once I forced a single interface (via btl_tcp_if_include) I was unable to reproduce the error on more than 100 runs.

**Comment by awlauria** [comment]
I tried reproducing on our nodes, and can't. We do have some failures with `intercomm_create` in the IBM mtt, but all failures are when btl/tcp is excluded, for example [here](https://mtt.open-mpi.org/index.php?limit=&wrap=&trial=&enable_drilldowns=&yaxis_scale=&xaxis_scale=&hide_subtitle=&split_graphs=&remote_go=&do_cookies=&phase=test_run&text_start_timestamp=2021-03-16+03%3A23%3A53+-+2021-03-19+17%3A23%3A53&text_platform_hardware=%5Eppc64le%24&show_platform_hardware=show&text_os_name=%5ELinux%24&show_os_name=show&text_mpi_name=%5Eompi-nightly-v5.0.x%24&show_mpi_name=show&text_mpi_version=%5Ev5.0.x-202103160305-0d6a41e%24&show_mpi_version=show&text_suite_name=all&show_suite_name=show&text_test_name=all&show_test_name=hide&text_np=all&show_np=show&text_full_command=intercomm_create&show_full_command=show&text_http_username=%5Eibm%24&show_http_username=show&text_local_username=all&show_local_username=hide&text_platform_name=%5Eibm-community%24&show_platform_name=show&click=Detail&phase=test_run&test_result=_run_f&text_compute_cluster_id=&text_os_version=&show_os_version=&text_platform_type=&show_platform_type=&text_submit_id=&text_hostname=&show_hostname=&text_mpi_get_id=&text_mpi_install_compiler_id=&text_mpi_install_configure_id=&text_mpi_install_id=&text_compiler_name=&show_compiler_name=&text_compiler_version=&show_compiler_version=&text_vpath_mode=&show_vpath_mode=&text_endian=&show_endian=&text_bitness=&show_bitness=&text_configure_arguments=&text_exit_value=&show_exit_value=&text_exit_signal=&show_exit_signal=&text_duration=&show_duration=&text_client_serial=&show_client_serial=&text_result_message=&text_result_stdout=&text_result_stderr=&text_environment=&text_description=&text_test_build_id=&text_test_build_compiler_id=&text_test_run_id=&text_test_name_id=&text_test_run_command_id=&text_test_suite_id=&text_performance_id=&text_launcher=&show_launcher=&text_resource_mgr=&show_resource_mgr=&text_network=&show_network=&text_parameters=&show_parameters=&lastgo=summary). Which I believe is expected.

**Comment by rhc54** [comment]
Extensive investigation on OMPI master cannot replicate this problem - we have concluded that recent changes in PRRTE have fixed it there. This has been included in the upcoming v5 release, which should be coming along soon. In the interim, you are welcome to try one of the nightly tarballs from either the master or v5 branch (https://www.open-mpi.org/nightly/). Please reopen if you continue to see this problem there.

**Comment by wckzhang** [comment]
I did a bisect and concluded that this patch fixes the issue:

```
commit 772bc830c44c92efb92fe87e771bb6d59e8b0ee0 (HEAD -> bisect)
Author: Ralph Castain <rhc@pmix.org>
Date:   Wed Feb 17 07:53:25 2021 -0800

    Remove stale OPAL dss and opal_tree code
    
    With the switch to PRRTE, there is no remaining need or use
    for the dss - it is all in PRRTE now.  The opal_tree class
    is also no longer used anywhere.
    
    Signed-off-by: Ralph Castain <rhc@pmix.org>
```

**Comment by rhc54** [comment]
That's....disturbing.

**Comment by bosilca** [comment]
I am not sure I understand how removing unused code could fix an issue. As I could replicate the issue pretty easily, let me try to see if I can get it to trigger with today's master.

**Comment by bosilca** [comment]
I confirm all tests run to completion. I still don't understand why, but at this point that is secondary. 
👍
