### ISSUE TITLE
MTT master: intercomm_create failure

### ISSUE THREAD

**Issue by awlauria** [open-mpi/ompi#7626]
https://mtt.open-mpi.org/index.php?do_redir=3222

```
b: intercomm_create (0)
b: barrier on inter-comm - before
a: intercomm_create (0)
a: barrier on inter-comm - beforeb: intercomm_create (0)
b: barrier on inter-comm - before
a: barrier on inter-comm - after
c: barrier on inter-comm - after
c: barrier on inter-comm - after
b: barrier on inter-comm - after
a: barrier on inter-comm - afterb: barrier on inter-comm - after
c: intercomm_merge(0) (0) [rank 5]
a: intercomm_merge(0) (0) [rank 1]
c: intercomm_merge(0) (0) [rank 4]
b: intercomm_merge(1) (0) [rank 2]
a: intercomm_merge(0) (0) [rank 0]
b: intercomm_merge(1) (0) [rank
3]--------------------------------------------------------------------------
WARNING: Open MPI accepted a TCP connection from what appears to be a
another Open MPI process but cannot find a corresponding process
entry for that peer.

This attempted connection will be ignored; your MPI job may or may not
continue properly.

  Local host: ip-172-31-75-247
  PID:        116153
--------------------------------------------------------------------------[ip-172-31-75-247][[9840,2],1][btl_tcp_endpoint.c:653:mca_btl_tcp_endpoint_recv_connect_ack]
received unexpected process identifier: got [[9840,2],0] expected [[9840,3],0]
[ip-172-31-75-247:116154] pml_ob1_sendreq.c:189
FATAL[ip-172-31-75-247][[9840,3],1][btl_tcp.c:566:mca_btl_tcp_recv_blocking] recv(13) failed:
Connection reset by peer (104)
(null)
(null)
(null)
```

**Comment by awlauria** [comment]
@rhc54 I was able to reproduce this.

What I found was that the output shown in the original ticket (which happens on aws, not ibm machines):

- hangs with UCX
- and the above wrong answer when using `--mca pml ob1`.

**Comment by rhc54** [comment]
It is true that this report was for Amazon - but the ones shown here (https://github.com/open-mpi/ompi/issues/7639) are for IBM.

**Comment by jjhursey** [comment]
Any updates on this issue?

**Comment by awlauria** [comment]
checking MTT results, the failure no longer [reproduces](https://mtt.open-mpi.org/index.php?limit=&wrap=&trial=&enable_drilldowns=&yaxis_scale=&xaxis_scale=&hide_subtitle=&split_graphs=&remote_go=&do_cookies=&phase=test_run&text_start_timestamp=past+48+hours&text_platform_hardware=all&show_platform_hardware=show&text_os_name=all&show_os_name=show&text_mpi_name=all&show_mpi_name=show&text_mpi_version=all&show_mpi_version=show&text_suite_name=all&show_suite_name=show&text_test_name=all&show_test_name=hide&text_np=all&show_np=show&text_full_command=intercomm_create&show_full_command=show&text_http_username=all&show_http_username=show&text_local_username=all&show_local_username=hide&text_platform_name=all&show_platform_name=show&click=Summary&phase=test_run&text_compute_cluster_id=&text_os_version=&show_os_version=&text_platform_type=&show_platform_type=&text_submit_id=&text_hostname=&show_hostname=&text_mpi_get_id=&text_mpi_install_compiler_id=&text_mpi_install_configure_id=&text_mpi_install_id=&text_compiler_name=&show_compiler_name=&text_compiler_version=&show_compiler_version=&text_vpath_mode=&show_vpath_mode=&text_endian=&show_endian=&text_bitness=&show_bitness=&text_configure_arguments=&text_exit_value=&show_exit_value=&text_exit_signal=&show_exit_signal=&text_duration=&show_duration=&text_client_serial=&show_client_serial=&text_result_message=&text_result_stdout=&text_result_stderr=&text_environment=&text_description=&text_test_build_id=&text_test_build_compiler_id=&text_test_run_id=&text_test_name_id=&text_test_run_command_id=&text_test_suite_id=&text_performance_id=&text_launcher=&show_launcher=&text_resource_mgr=&show_resource_mgr=&text_network=&show_network=&text_parameters=&show_parameters=&lastgo=summary). Closing.

It will fail when run without tcp and only sm, but I think that is expected.
