### ISSUE TITLE
OpenMPI ./configure --with-hwloc=<dir> fails in opal/mca/threads/pthreads/configure.m4

### ISSUE THREAD

**Issue by BrendanCunningham** [open-mpi/ompi#7644]
## Background information
Am building ompi/master and required hwloc, libevent, and pmix libraries under my `~/` to be able to develop without overwriting my distro's installed ompi. To do this, I configure hwloc, libevent, pmix, and ompi with `--prefix=~/projects/ompi_master_build_issue`.

Am using the following versions of hwloc, libevent, and pmix:
- libevent, heads/master, commit 0d2f1700
- hwloc, heads/master, commit 8249f30d
- pmix, heads/master, commit c9e85ea3

simple_build.sh that I have used to reproduce both failure and successes detailed below is include at end of thsi bug description. Script can and should be run as non-root user.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
ompi, master, commit 1a46e95b

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
git clone of ompi/master at hash mentioned above. Did `git submodule init && git submodule update` afterward.

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
```
git submodule status
4a43c39c89037f52b4e25927e58caf08f3707c33 opal/mca/hwloc/hwloc2/hwloc (hwloc-2.1.0rc2-53-g4a43c39c)
427dd6b738da5075620fbc4555e7c97b3a65fdb6 opal/mca/pmix/pmix4x/openpmix (v1.1.3-2321-g427dd6b7)
b624eae87078e32b3fb60a5dbe18557c2d276aa4 prrte (dev-30504-gb624eae8)
```

### Please describe the system on which you are running
* Operating system/version: RHEL 8.1, kernel 4.18.0-80.el8.x86_64
* Computer hardware: Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz, 
* Network type: OPA HFI in back-to-back configuration

## Details of the problem
Configuring and building ompi with internal {hwloc, libevent, pmix} succeeds (see simple_build.sh below). ompi internal-library ./configure output includes `checking if threads have different pids (pthreads on linux)... no`.

Successfully configured, built, and installed external {hwloc, libevent, pmix} to `~/projects/ompi_master_build_issue/install`. But ompi `./configure --with-libevent="$install_dir" --with-hwloc="$install_dir" --with-pmix="$install_dir" --without-psm2` fails. This is the error output:
```
	...
	--- MCA component threads:pthreads (m4 configuration macro, priority 30)
	checking for MCA component threads:pthreads compile mode... static
	checking if C compiler and POSIX threads work as is... no
	checking if C++ compiler and POSIX threads work as is... no
	checking if Fortran compiler and POSIX threads work as is... no
	checking if C compiler and POSIX threads work with -Kthread... no
	checking if C compiler and POSIX threads work with -kthread... no
	checking if C compiler and POSIX threads work with -pthread... yes
	checking if C++ compiler and POSIX threads work with -Kthread... no
	checking if C++ compiler and POSIX threads work with -kthread... no
	checking if C++ compiler and POSIX threads work with -pthread... yes
	checking if Fortran compiler and POSIX threads work with -Kthread... no
	checking if Fortran compiler and POSIX threads work with -kthread... no
	checking if Fortran compiler and POSIX threads work with -pthread... yes
	checking for pthread_mutexattr_setpshared... yes
	checking for pthread_condattr_setpshared... yes
	checking for PTHREAD_MUTEX_ERRORCHECK_NP... yes
	checking for PTHREAD_MUTEX_ERRORCHECK... yes
	checking if threads have different pids (pthreads on linux)... yes
	configure: WARNING: This version of Open MPI only supports environments where
	configure: WARNING: threads have the same PID.  Please use an older version of
	configure: WARNING: Open MPI if you need support on systems with different
	configure: WARNING: PIDs for threads in the same process.  Open MPI 1.4.x
	configure: WARNING: supports such systems, as does at least some versions the
	configure: WARNING: Open MPI 1.5.x series.
	configure: error: Cannot continue
```
Where the 6 WARNING lines only exist in opal/mca/threads/pthreads/configure.m4.

ompi/config.log gives this as the failing command:
```
	configure:155935: gcc -o conftest -O3 -DNDEBUG -Wall -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -pedantic -Werror-implicit-function-declaration -finline-functions -fno-strict-aliasing -mcx16 -pthread -I/nfs/site/home/jbcunnin/projects/ompi_master_build_issue//include   -I/nfs/site/home/jbcunnin/projects/ompi_master_build_issue/include  -I/nfs/site/home/jbcunnin/projects/ompi_master_build_issue/include    -L/nfs/site/home/jbcunnin/projects/ompi_master_build_issue//lib  -L/nfs/site/home/jbcunnin/projects/ompi_master_build_issue//lib  conftest.c -lrt -lm -lutil  -lhwloc  -levent -levent_pthreads  >&5
	conftest.c:699:5: warning: function declaration isn't a prototype [-Wstrict-prototypes]
	 int main() {
		 ^~~~
	configure:155935: $? = 0
	configure:155935: ./conftest
	./conftest: error while loading shared libraries: libhwloc.so.0: cannot open shared object file: No such file or directory
	configure:155935: $? = 127
	configure: program exited with status 127
```
This part of opal/mca/threads/pthreads/configure.m4 builds and runs a program to test if all threads in a process have the same PID (I'll call this the pthreads-same-pids test). It is a configuration failure if they have different PIDs. Beyond standard C library headers, the pthreads-same-pids test code only includes `pthread.h`.

Building the pthreads-same-pids test code separately using the gcc line from config.log succeeds. Running the pthreads-same-pids test program fails on the same loader error. The program runs without the loader error if I build it with the same gcc line but remove ` -lhwloc  -levent -levent_pthreads` from it.

git bisect found ee351742 introduced opal/mca/threads/pthreads/configure.m4. Same test was present prior to this commit in config/opal_check_pthread_pids.m4.

Same pthreads-same-pids test program is also present in opal/mca/pmix/pmix4x/openpmix/config/pmix_check_pthread_pids.m4 and prrte/config/prrte_check_pthread_pids.m4.

## Proposed solution
Since hwloc and libevent are not needed to build/run pthreads-same-pids, they should not be included as library dependencies. If pthreads include/lib locations can be configured, these locations should be used as compiler and linker flags for the pthreads-same-pids test program. However the pthreads include/lib paths are not obviously configurable through `ompi/configure` at this time.

## simple_build.sh
```
#!/bin/bash
set -x
set -e

install_dir=~/projects/ompi_master_build_issue/install

make_external=0

if [[ $make_external -eq 1 ]] ; then
	cd libevent
	./autogen.sh
	./configure --prefix="$install_dir"
	make
	make install

	cd ../hwloc
	./autogen.sh
	./configure --prefix="$install_dir"
	make
	make install

	cd ../pmix
	./autogen.pl
	./configure --prefix="$install_dir" --with-libevent="$install_dir" --with-hwloc="$install_dir" --without-psm2
	make
	make install
	
	cd ../ompi
	env AUTOMAKE_JOBS=$(nproc) ./autogen.pl
	./configure --prefix="$install_dir" --with-libevent="$install_dir" --with-hwloc="$install_dir" --with-pmix="$install_dir"
	make
	make install
else
	cd ompi
	env AUTOMAKE_JOBS=$(nproc) ./autogen.pl
	./configure --prefix="$install_dir" --with-libevent=internal --with-hwloc=internal --with-pmix=internal --without-psm2
	make
	make install
fi
```

**Comment by hppritcha** [comment]
@BrendanCunningham i'm having problems reproducing but think this is fixed by PR #7764. Could you give it a try?

**Comment by BrendanCunningham** [comment]
Yep, I'll see if I can reproduce it before and after PR #7764.

**Comment by BrendanCunningham** [comment]
Summary: Yes, configure issue is fixed by PR #7764.

Details: Checked out your PR branch, reverted HEAD commit, built, verified could still produce original issue.

Did 'git reset --hard HEAD' on your PR branch, ran build script, and verified that configure got past the pthreads-have-different-pids test in config.log.

**Comment by awlauria** [comment]
Closing as #7764 has been merged.

**Comment by awlauria** [comment]
Oops - it was closed not merged..Reopening. @hppritcha did this get fixed in an other PR?

**Comment by hppritcha** [comment]
#7968 is the same as #7764 just with more verbiage in the commit message per @jsquyres request.

**Comment by awlauria** [comment]
Thanks - did we want to close this issue?

**Comment by hppritcha** [comment]
yes
