### ISSUE TITLE
constants not recognized with ifort on OS X

### ISSUE THREAD

**Issue by MicroTed** [open-mpi/ompi#7653]
Summary: Intel ifort not recognizing special constants (e.g., mpi_in_place). Is there a work-around for this? (The PMIX error at the end also occurs when compiling with gfortran, so I assume that is a separate issue.)

MacOS 10.13.6 (High Sierra), iMac Pro
Open MPI version: 4.0.3 (though also occurs with 2.1.2), installed from source
ifort Version 13.0.3.198 Build 20130606 (yes, it's old)
CC is Apple LLVM version 10.0.0 (clang-1000.11.45.5)

The initial problem that was noticed was allreduce calls with MPI_IN_PLACE returning zero. Eventually I found the ompi_test_fortran_constants function that conveniently show that all the given constants are not recognized correctly. (gfortran compile works properly with ierr=1)

Result of the test program below is
mimac:COMMAS% mpirun -np 4 x.mpiconstcheck
Hello, world, I am  0 of  4: Open MPI v4.0.3, package: Open MPI ted.mansell@4354-tmansell-mp Distribution, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020                                                                                                                                     
Hello, world, I am  1 of  4: Open MPI v4.0.3, package: Open MPI ted.mansell@4354-tmansell-mp Distribution, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020                                                                                                                                     
Hello, world, I am  3 of  4: Open MPI v4.0.3, package: Open MPI ted.mansell@4354-tmansell-mp Distribution, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020                                                                                                                                     
Hello, world, I am  2 of  4: Open MPI v4.0.3, package: Open MPI ted.mansell@4354-tmansell-mp Distribution, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020                                                                                                                                     
WARNING: Fortran MPI_BOTTOM not recognized properly
WARNING: Fortran MPI_IN_PLACE not recognized properly
WARNING: Fortran MPI_ARGV_NULL not recognized properly
WARNING: Fortran MPI_ARGVS_NULL not recognized properly
WARNING: Fortran MPI_STATUS_IGNORE not recognized properly
WARNING: Fortran MPI_STATUSES not recognized properly
 constants tests: ierr =            0
[4354-tmansell-mp:74832] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206
[4354-tmansell-mp:74834] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206
[4354-tmansell-mp:74835] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206
[4354-tmansell-mp:74831] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206

______________________________________

!---------------------------------------------------
!
! Copyright (c) 2004-2006 The Trustees of Indiana University and Indiana
!                         University Research and Technology
!                         Corporation.  All rights reserved.
! Copyright (c) 2006-2015 Cisco Systems, Inc.  All rights reserved.
! $COPYRIGHT$
!
! Sample MPI "hello world" application using the Fortran mpif.h
! bindings.
!
        program main
!        use mpi
        implicit none
        include 'mpif.h'
        integer ierr, rank, size, len
        real xin, xout
        integer, parameter :: kb = 0, ke = 41
        integer :: nk,n,k
!        double precision :: xindp, xoutdp, dumk1(kb:ke),dumk2(kb:ke)
!        real :: dumk1r(kb:ke),dumk2r(kb:ke)
        character(len=MPI_MAX_LIBRARY_VERSION_STRING) version

        call MPI_INIT(ierr)
        call MPI_COMM_RANK(MPI_COMM_WORLD, rank, ierr)
        call MPI_COMM_SIZE(MPI_COMM_WORLD, size, ierr)
        call MPI_GET_LIBRARY_VERSION(version, len, ierr)

        write(0, '("Hello, world, I am ", i2, " of ", i2, ": ", a)') &
     &        rank, size, version

        call mpi_barrier(MPI_COMM_WORLD,ierr)

        IF ( rank == 0 ) THEN 
!          write(*,*) 'mpi_in_place = ',mpi_in_place
!          write(*,*) 'loc(mpi_in_place) = ',loc(mpi_in_place)
        
        call ompi_test_fortran_constants(MPI_BOTTOM, MPI_IN_PLACE, &
                                   MPI_ARGV_NULL, MPI_ARGVS_NULL,    &
                                   MPI_STATUS_IGNORE, MPI_STATUSES_IGNORE,  &
                                   ierr)
          write(*,*) 'constants tests: ierr = ',ierr
        ENDIF
        
        call MPI_FINALIZE(ierr)

        end
!---------------------------------------------------

**Comment by hppritcha** [comment]
@MicroTed we just did put some fixes for fortran constants in the 4.0.x branch.  Would you mind retesting against the nightly tarball at
https://www.open-mpi.org/software/ompi/v4.0/
thanks

**Comment by MicroTed** [comment]
I will try it! Thanks!

**Comment by MicroTed** [comment]
@hppritcha  I'm sorry to report that it didn't change my result. (Using openmpi-v4.0.x-202004280241-849b560). I might see if I can try a trial version of the current ifort.

...
Hello, world, I am  3 of  4: Open MPI v4.0.3rc4, package: Open MPI ted.mansell@4354-tmansell-mp Distribution, ident: 4.0.3rc4, repo rev: v4.0.3-43-g849b560, Unreleased developer copy                                                                              
WARNING: Fortran MPI_BOTTOM not recognized properly
WARNING: Fortran MPI_IN_PLACE not recognized properly
WARNING: Fortran MPI_ARGV_NULL not recognized properly
WARNING: Fortran MPI_ARGVS_NULL not recognized properly
WARNING: Fortran MPI_STATUS_IGNORE not recognized properly
WARNING: Fortran MPI_STATUSES not recognized properly

**Comment by MicroTed** [comment]
For comparison, I compiled mpich 3.3.2 with the same tools, and there at least MPI_IN_PLACE appears to work correctly (it doesn't have that test subroutine, but I tested the MPI_IN_PLACE flag with a couple ALLREDUCE calls).

**Comment by jsquyres** [comment]
@MicroTed We're doing a sweep through old Open MPI bugs and noticed this one.  Does this still happen?  Do you know if it happens with a newer MacOS and/or a newer Intel compiler?  The compiler you cited is very, very old (7 years?)...

**Comment by jsquyres** [comment]
Closing due to lack of reply.  If this is still an issue, please let us know.

**Comment by MicroTed** [comment]
@jsquyres  
FYI, with the recent 2021 OneAPI compilers from Intel (FC=ifort CC=icc CXX=icpc) and OpenMPI 4.1.0, the result is the same (erroneous all_reduce when using MPI_IN_PLACE).
