### ISSUE TITLE
Incorrect + misleading output from --report-bindings

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7660]
A customer reported misleading / incorrect output from `mpirun --report-bindings ...` in the Open MPI v4.0.x series.  @rhc54 and I talked about this, and the customer run a few experiments with master (i.e., what will become v5.0.x).

The customer runs a SLURM cluster, and they allocate by core.  Meaning: multiple SLURM jobs may co-exist on the same server.  SLURM dutifully sets a cgroup with the cores that each SLURM job will utilize.  For example, here's a simple sbatch script:

```
#!/usr/bin/bash

hwloc-bind --get
mpirun --report-bindings hwloc-bind --get
```

Running it on via `sbatch`, asking for 2 cores (with Open MPI master) gives the following output:

```
==> slurm-629774.out <==
0x00003c00
[a1a-u2-c4-b1:118346] MCW rank 0 bound to socket 0[core 0[hwt 0]]: [[<B/././.>][[]
[a1a-u2-c4-b1:118346] MCW rank 1 bound to socket 0[core 1[hwt 0]]: [[<./B/./.>][[]
[a1a-u2-c4-b1:118346] MCW rank 2 bound to socket 0[core 2[hwt 0]]: [[<././B/.>][[]
[a1a-u2-c4-b1:118346] MCW rank 3 bound to socket 0[core 3[hwt 0]]: [[<./././B>][[]
0x00000400
0x00000800
0x00002000
0x00001000
```

The socket/core numbers in the text output seem to be relative to the cgroup.  We found this confusing -- we thought it was telling us that it was actually bound to socket 0 core 0.  But it wasn't.   It was core 0 _relative to the cgroup_.

Additionally, the diagram off to the right seemed to be inaccurate in a few ways:

- extra `[` for each socket
- only show the cores in the cgroup

The latter was from a prior effort to limit the size of the diagram displayed when cgroups are used.  E.g., on 128 or 256 HWT machines, the digram may be gigantic, and the user may only care about a single core in the diagram.

We should do the following:

* display the correct socket/core/hwt IDs -- not values relative to the cgroup
* maybe only display hwt info if there are >1 HWTs
* make sure the `<>` NUMA notation is at the right level
* have a better diagram (on the right) that both limits the size when possible, but still conveys an accurate representation of where the proc is bound

@rhc54 wrote much-abbreviated versions of this in the PRRTE repo:

* https://github.com/openpmix/prrte/issues/523
* https://github.com/openpmix/prrte/issues/524

Additionally, we're still using the word `socket` in both CLI input and displayed output.  It would probably be much more appropriate to use the word `package` these days.

**Comment by awlauria** [comment]
Blocker for ompi 5.0 release.

**Comment by gpaulsen** [comment]
Need to re-test with ompi master / prrte master.

**Comment by rhc54** [comment]
I believe this should be fixed by https://github.com/open-mpi/ompi/pull/8558. @jsquyres Can you confirm?

**Comment by jsquyres** [comment]
I'll check with the fine folks at WFU.  Thanks!

**Comment by markalle** [comment]
I didn't run in the same configuration as reported, but I did just confirm by hand that master prints sane looking reports from inside a cgroup, eg reporting what it's using relative to WHOLE_SYSTEM.

But is the cset2mapstr() output really gone with no options to turn it back on?  All I see is the cset2str() output, eg
it can tell me
```
rank 0: bound to package[0][hwt:4-7,12]
rank 1: bound to package[0][hwt:13-15,20] package[1][hwt:92]
```
This gives a little more information than just printing a raw bitmask since it tells what package things are on.

But I don't see any option to get the full visual hardware ordered display like this
```
rank 0: [..../BBBB/..../B.../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../....][..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../....]
rank 1: [..../..../..../.BBB/..../B.../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../....][..../B.../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../....]
```
I still find the cset2mapstr() output like above much easier to interpret at a glance, even if it's long on modern machines

**Comment by rhc54** [comment]
Update on https://github.com/openpmix/prrte/issues/570 if this problem resurfaces. No plans to provide the longer display.

**Comment by jsquyres** [comment]
Just to close the loop on this: got confirmation from the folks at WFU -- the issue seems to be fixed; huzzah!
