### ISSUE TITLE
ORTE -> PRRTE changes for users need to be documented, users educated

### ISSUE THREAD

**Issue by awlauria** [open-mpi/ompi#7668]
From ompi email chain, sent by @rhc54:

```
So here is an interesting consequence of moving from ORTE to PRRTE. In ORTE, you 
could express any mapping policy as an MCA param - e.g., the following:

OMPI_MCA_rmaps_base_mapping_policy=core
OMPI_MCA_rmaps_base_display_map=1

would be the equivalent of a cmd line that included "--map-by core --display-map"

When defining what we wanted on the OMPI v5 cmd line, we removed some options like 
--display-map and replaced them with modifiers, so the above would have been replaced with:

OMPI_MCA_rmaps_base_mapping_policy=core:display

The move to PRRTE, however, means more than just changing the "OMPI" to "PRRTE".
PRRTE doesn't support setting the default mapping policy to include "report" as that
would mean we would be reporting the map for every job that was ever launched.
Definitely not something the persistent DVM users would appreciate!

So if you put:

PRRTE_MCA_rmaps_default_mapping_policy=core:display

(note the name change!!!) in your environment, you are going to get an error when you
execute "mpirun":

=====
A mapping policy modifier was provided that is not supported as a default value:

 Modifier:  display

You can provide this modifier on a per-job basis, but it cannot
be the default setting.
=======

And you will error out. However, it is perfectly okay to put "--map-by core:display" on your
cmd line - that is legit and understood as it only applies to that specific job.

It's these changes, plus the name changes (e.g., we replace "base" with "default" to
emphasize these are ONLY the default settings), that will need to be communicated.
```

**Comment by jsquyres** [comment]
@jsquyres volunteered to take a first pass at this.

**Comment by jjhursey** [comment]
Related PRRTE items:
 * https://github.com/openpmix/prrte/issues/450
 * https://github.com/openpmix/prrte/pull/557

**Comment by gpaulsen** [comment]
What's the status of this documentation now?

How much more docs do we need to do before rc1?

**Comment by naughtont3** [comment]
dropping note here based on user interaction today, the details on map/bind has been mentioned but we also need to include how to set those via MCA envvars (e.g., PRTE_MCA_rmaps_default_mapping_policy=core, PRTE_MCA_hwloc_default_binding_policy=package, etc.)

**Comment by rhc54** [comment]
You can document those, but that won't help users with existing scripts and/or default param files. I'd suggest you also (or instead - your choice) add the required translation logic to the schizo/ompi component to make that transparent.

**Comment by qkoziol** [comment]
I've read this issue's history and believe that the requirement here is to document the change in OMPI's online documentation.   Does anyone think otherwise?

**Comment by qkoziol** [comment]
@naughtont3 - What's the acceptance criteria for moving this ticket to the "done" column?

**Comment by qkoziol** [comment]
PR that documents the MCA parameter changes up for review:  https://github.com/open-mpi/ompi/pull/11890

@jsquyres @naughtont3 @gpaulsen @janjust @rhc54

**Comment by qkoziol** [comment]
PR for merge to 5.0 branch:  https://github.com/open-mpi/ompi/pull/11926

**Comment by wenduwan** [comment]
5.0.0 released. Closing.
