### ISSUE TITLE
Provide new manpage on mapping/ranking/binding

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#7689]
Cover all the PRRTE variations

**Comment by naughtont3** [comment]
See also:
 - https://github.com/openpmix/openpmix/pull/1752

**Comment by jsquyres** [comment]
@naughtont3 Agreed!  The goal would be to able to write this new man page in markdown, not nroff.

**Comment by rhc54** [comment]
Closed by https://github.com/openpmix/prrte/pull/773
