### ISSUE TITLE
btl/ugni using incorrect topology

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#7692]
In `mca_btl_ugni_init`, a decision on the number of virtual devices to use is based on getting the number of cores on the node. However, HWLOC will return that value based on the number of cores available to the PRRTE daemon - which is _not_ the same as the number of cores available to the application. For example, the user may have specified a cpuset (a.k.a., "soft" cgroup) that only applies to the application's procs.

Correct computation of the number of available cores requires that you get the `PMIX_JOB_CPUSET`, mask the complete_cpuset against it to find the actually available cpus, and then obtain the count of cores from within that cpuset.

**Comment by hppritcha** [comment]
I'm removing the blocker label on this issue as the intersection in terms of users between
- those using Open MPI on cray systems
- using a cpuset on Cray XC's (not even sure cray XCs are typically configured to allow users to do this)
is, if not zero, certainly very small.

**Comment by hppritcha** [comment]
we're not going to fix this.
