### ISSUE TITLE
master: code in opal will try to bind in non-mpirun scenerio

### ISSUE THREAD

**Issue by awlauria** [open-mpi/ompi#7694]
For example - with prun.

This code needs to be refactored or removed entirely.

**Comment by awlauria** [comment]
@jsquyres @rhc54 the issue discussed earlier today. If I worded it incorrectly, or it needs more detail, feel free to update.

**Comment by rhc54** [comment]
I don't think we know if this is true - my point was only that we did this at one time and it should be checked and removed if still present. IIRC, it was actually done in ORTE, so it may no longer be relevant.

**Comment by jsquyres** [comment]
Just to be clear -- I volunteered for #7695, not this one.  😉

**Comment by awlauria** [comment]
ok - is this still a valid issue or should be closed in favor of #7695?

**Comment by jsquyres** [comment]
@awlauria It needs to be checked.

**Comment by awlauria** [comment]
This is fixed here: https://github.com/open-mpi/ompi/pull/9686
