### ISSUE TITLE
nolocal option not working w/ master

### ISSUE THREAD

**Issue by naughtont3** [open-mpi/ompi#7703]
The "nolocal" option is not excluding the local machine when passed to `mpirun`.  This is on master.  The `--nolocal` gets noted and translated to the newer `--map-by :NOLOCAL`, but the actual mapping does not work to exclude the local node.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

-  ompi master @ b66e27d

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

- git clone of master @ b66e27d
 

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

 - ompi submodules status
    ```
     4a43c39c89037f52b4e25927e58caf08f3707c33 opal/mca/hwloc/hwloc2/hwloc (hwloc-2.1.0rc2-53-g4a43c39)
     d5619eed03c844195ab9e34e7ece6c4f1d6c4596 opal/mca/pmix/pmix4x/openpmix (v1.1.3-2361-gd5619ee)
     233c395d8de79f828d967491053593f2ff4dd4cb prrte (dev-30538-g233c395)
    ```

### Please describe the system on which you are running

* Operating system/version:  Linux
* Computer hardware:  
* Network type: 

-----------------------------

## Details of the problem

The localhost is not being excluded from host list when passing the "nolocal" option.

```shell

    node0:$ cat hosts 
    node0
    node1
    node2
    node3
    node4
    node5
    node0:$ mpirun --hostfile hosts --np 1 hostname
    node0
    node0:$ mpirun --hostfile hosts --np 1 --nolocal hostname
    --------------------------------------------------------------------------
    WARNING: A deprecated command line option was used.

      Deprecated option:   --nolocal
        Corrected option:    --map-by :NOLOCAL

        We have updated this for you and will proceed. However, this will be
        treated
        as an error in a future release. Please update your command line.
        --------------------------------------------------------------------------


        ******* Corrected cmd line: mpirun --hostfile hosts --np 1 --map-by
        :NOLOCAL hostname


        node0
        node0:$ mpirun --hostfile hosts --np 1 --map-by :NOLOCAL  hostname
        node0
        node0:$ mpirun --hostfile hosts --np 1 --map-by ppr:1:node:NOLOCAL
        hostname
        node0
        node0:$
```

- Debug log:  [DBG.txt](https://github.com/open-mpi/ompi/files/4587701/DBG.txt)

**Comment by rhc54** [comment]
FWIW: I have this fixed, but it is mixed in with the branch addressing the binding issues. Will commit it when I get that branch working properly.

**Comment by naughtont3** [comment]
@rhc54 was PR openpmix/prrte#546 that branch, or something still pending?  i pulled openpmix/prrte#546 and updated prrte master and still see issue.  I guess I should have filed this in runtime repo (prrte), sorry about that.

**Comment by naughtont3** [comment]
@rhc54 does your other branch also have dash-host mapping edits?  Asking to know if I should look further into openpmix/openpmix#1750 related to `--host` issue on node assignment.

**Comment by rhc54** [comment]
I haven't fixed it yet, but I have identified the issue and laid out what has to happen. Unfortunately, it involves things that are in the middle of what I'm currently touching, and so it will have to wait a bit until I get the binding stuff done.

**Comment by naughtont3** [comment]
Thanks @rhc54!  No rush, I just wanted to know if i should check on things before telecon today. I did notice that will error out now with latest prrte, which is better to make sure does not silently pass. Thx!

**Comment by awlauria** [comment]
Will retest.

**Comment by naughtont3** [comment]
Fixed.

```
[3t4@node0 DETERMINED-SEALION]$ more hosts
node0
node1
node2
node3
node4
node5
[3t4@node0 DETERMINED-SEALION]$ mpirun --hostfile hosts --np 1 hostname
node0
[3t4@node0 DETERMINED-SEALION]$ mpirun --hostfile hosts --np 1 --nolocal hostname
--------------------------------------------------------------------------
WARNING: A deprecated command line option was used.

  Deprecated option:   --nolocal
  Corrected option:    --map-by :NOLOCAL

We have updated this for you and will proceed. However, this will be treated
as an error in a future release. Please update your command line.
--------------------------------------------------------------------------


******* Corrected cmd line: mpirun --hostfile hosts --np 1 --map-by :NOLOCAL hostname


node1
[3t4@node0 DETERMINED-SEALION]$ mpirun --hostfile hosts --np 1 --map-by :NOLOCAL  hostname
node1
[3t4@node0 DETERMINED-SEALION]$ cd source/ompi-git-br-master/
[3t4@node0 ompi-git-br-master]$ git describe 
v2.x-dev-7821-g0a21a58
[3t4@node0 ompi-git-br-master]$ git describe ; git submodule status
v2.x-dev-7821-g0a21a58
 4a43c39c89037f52b4e25927e58caf08f3707c33 opal/mca/hwloc/hwloc2/hwloc (hwloc-2.1.0rc2-53-g4a43c39)
 30e2bf8d7317656bd854c431cc0695f60e952e14 opal/mca/pmix/pmix4x/openpmix (v1.1.3-2414-g30e2bf8)
 9e5d018fcfbd3de35ad4b3d6e7fb061043da41b0 prrte (dev-30615-g9e5d018)
[3t4@node0 ompi-git-br-master]$
