### ISSUE TITLE
Remove osc/pt2pt from OMPI master

### ISSUE THREAD

**Issue by mwheinz** [open-mpi/ompi#7715]
The only remaining use for the pt2pt transport is to get one-sided messaging when using OPA. Removing it is in preparation for supporting the use of the OFI BTL as a replacement.

(Other pieces will include adding reference counting to the PSM2 library to allow multiple transports to open the library and checking for the reference counting capability when initializing the PSM2 MTL.)

**Comment by awlauria** [comment]
This PR to remove it is open:

https://github.com/open-mpi/ompi/pull/7621

**Comment by mwheinz** [comment]
> This PR to remove it is open:

Doh! You're right. I'd forgotten.
