### ISSUE TITLE
Add check for PSM2 reference counting to PSM2 MTL

### ISSUE THREAD

**Issue by mwheinz** [open-mpi/ompi#7721]
As discussed, a feature is being added to libpsm2 to correctly handle the case where the library is opened by multiple OMPI transports in the same process. (For example, the OFI BTL and the PSM2 MTL).

**Comment by hppritcha** [comment]
@mwheinz can this issue be closed?

**Comment by mwheinz** [comment]
Oops. Yeah, sorry.
