### ISSUE TITLE
"No route to host" Error of running Open MPI on databricks clusters 

### ISSUE THREAD

**Issue by umusa** [open-mpi/ompi#7723]
Sorry for the previous question, which was not presented well. 

I have downloaded 
        https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.3.tar.gz
and installed on databricks cluster.

      Operating system/version: Linux 4.4.0 Ubuntu
      Computer hardware: x86_64
       Network type: databricks

The cluster has 3 nodes:

      Driver node: 8 cores
      two worker nodes: each has 8 cores

My hostfile:
    
      Driver databricks's cluster ID + IP address
      worker1 IP address
      worker2 IP address

My command run from databricks notebook:

        sudo mpirun --allow-run-as-root -np 25 --hostfile my_hostfile ./MY_C_APP 

I got:
      
      ssh: connect to host DRIVER_NODE_IP port 22: No route to host
      ssh: connect to host  ONE_WORKER_NODE_IP  port 22: No route to host

It seems that the nodes cannot communicate with each other ?

thanks

--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   MY_DATABRICKS_CLUSTER_ID_IP
  target node:  one worker node IP

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.

**Comment by ggouaillardet** [comment]
Nodes must be able to SSH passwordless to each other (among other things)

The error message suggests you have firewall(s) preventing SSH connections.

Is `mpirun` running on `DRIVER_NODE_IP`?
In that case, it looks odd `mpirun` basically tries to ssh to itself.

**Comment by umusa** [comment]
yes, mpirun running on  DRIVER_NODE_IP.

**Comment by ggouaillardet** [comment]
It is fine to have `DRIVER_NODE_IP` in your hostfile, but I am puzzled why `mpirun` tries to ssh to itself (instead of simply forking the MPI tasks). Anyway, first fix your SSH/firewall issue and see how it goes.

Let's do it one step at a time :
 - `sudo ssh DRIVER_NODE_IP hostname`
 - `sudo ssh ONE_WORKER_NODE_IP hostname`
and when it works
 - `sudo mpirun --allow-run-as-root -np 25 --hostfile my_hostfile hostname`
and finally
 - `sudo mpirun --allow-run-as-root -np 25 --hostfile my_hostfile ./MY_C_APP`

**Comment by umusa** [comment]
I run the command from python notebook on databricks.

    %sh
     sudo ssh -T DRIVER_NODE_IP 

I got:
      ssh: connect to host 10.71.82.129 port 22: No route to host

**Comment by umusa** [comment]
I have restart the cluster and try it again.
   
I got:

       Host key verification failed.

**Comment by umusa** [comment]
I also run 

    ping  DRIVER_NODE_IP 

it works. But,
      ping ONE_WORKER_NODE_IP 

does not work. 

it seems that all nodes cannot talk to each other.

**Comment by ggouaillardet** [comment]
This is infrastructure related and you have to figure it out by yourself.
When this is working and you are still facing some Open MPI issue, you are welcome to follow up here.
