### ISSUE TITLE
Error: option pandoc requires an argument

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#7724]
I just pulled current upstream `master` into my fork, updated all submodules, and found the build breaking:

```
$ git submodule update --remote
$ ./autogen.pl -j 8
$ cd build/
$ ../configure CC=gcc CXX=g++ FC=gfortran --with-ucx=$HOIME/opt/ucx-1.8.0/ --with-slurm --disable-man-pages
```

The error I'm getting seems to come from the prrte submodule:
```
make[3]: Entering directory `prrte/src/tools/pcc'
/bin/sh ../../../libtool  --tag=CC   --mode=link gcc  -DNDEBUG -O3 -fvisibility=hidden -finline-functions -fno-strict-aliasing -mcx16 -pthread      -o pcc pcc.o /home/jschuch/src/openmpi/git/devreal/build_master/opal/libopen-pal.la    ../../../src/libprrte.la -lm -lutil  -lz -lz  
libtool: link: gcc -DNDEBUG -O3 -fvisibility=hidden -finline-functions -fno-strict-aliasing -mcx16 -pthread -o .libs/pcc pcc.o  ../../../src/.libs/libprrte.so opal/.libs/libopen-pal.so -ldl -lrt -lm -lutil -lz -pthread -Wl,-rpath -Wl,prrte/config/md2nroff.pl --source=../../../../../prrte/src/tools/pcc/pcc.1.md --dest=pcc.1 --pandoc=
Option pandoc requires an argument
Invalid command line argument.

Options:
  --source FILE  Source Markdown filename
  --dest FILE    Destination nroff file
  --pandoc FILE  Location of pandoc executable
  --help         This help list
  --verbose      Be verbose when running
```

Pandoc isn't installed on that system and I haven't bothered installing it myself. A previous fork (sometime mid April) accepted the `--disable-man-pages` flawlessly.

The Open MPI repo stands at `3078485eee5b5153c511d0b03671443146cd7836` and the PRRTE submodule at `7389e17c5dd4ea7c07198267ab4a5260bc6e5bba`

**Comment by rhc54** [comment]
Problem is that we haven't yet linked the OMPI-level configure flags to the PRRTE and PMIx level configure, and thus those levels are not getting the `--disable-man-pages` option passed down to them.

**Comment by jsquyres** [comment]
Yeah, sorry @devreal -- the Pandocification hasn't made it up through the Open MPI submodules yet...

In the meantime, note that you can get a static Pandoc Linux binary from https://github.com/jgm/pandoc/releases/tag/2.9.2.1 (i.e., the pandoc-2.9.2.1-linux-amd64.tar.gz
 tarball contains a Pandoc Linux binary).

**Comment by jsquyres** [comment]
@devreal I'm actually unable to replicate this issue with today's master:

```
$ git describe
v2.x-dev-7777-g3078485eee

$ git submodule
 4a43c39c89037f52b4e25927e58caf08f3707c33 opal/mca/hwloc/hwloc2/hwloc (hwloc-2.1.0rc2-53-g4a43c39c)
 4996218a7a13a0ec59c94ffd72ead6d95d6acb4e opal/mca/pmix/pmix4x/openpmix (v1.1.3-2366-g4996218a)
 9cf321a38d36900702fd9c0862f633f4981b740d prrte (psrvr-v2.0.0rc1-3179-g9cf321a38d)
```

Can you verify with these (or later) versions?

**Comment by devreal** [comment]
@jsquyres For me the latest commit on master is `3078485`

```
commit 3078485eee5b5153c511d0b03671443146cd7836 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Merge: 4460e8ba8e 0fc2033c75
Author: Howard Pritchard <hppritcha@gmail.com>
Date:   Mon May 11 09:02:22 2020 -0600

    Merge pull request #7712 from shintaro-iwasaki/fix7697
    
    opal/mca/threads/argobots: fix compilation error
```

That is also what I see on https://github.com/open-mpi/ompi/commits/master. I don't see the commit you mention (`g3078485eee`). Strange

**Comment by jsquyres** [comment]
That's the same commit.

`git describe` puts an extra `g` before the hash: `v2.x-dev-7777-g3078485eee` == git hash 3078485eee.

Looking at earlier comments on this PR, I see you mentioned 3078485eee earlier -- sorry.  But you're at a different prrte commit than master currently is: you're at https://github.com/openpmix/prrte/commit/7389e17c5dd4ea7c07198267ab4a5260bc6e5bba, but master is at https://github.com/openpmix/prrte/commit/9cf321a38d36900702fd9c0862f633f4981b740d.

Have you run `git submodule update`?

**Comment by devreal** [comment]
Ah darn, should have paid more attention... I have run `git submodule update` mutliple times, yes. Will try again...

**Comment by devreal** [comment]
The system I was testing this on is offline until further notice so it seems like I won't be able to check the commit hashes anytime soon. I think this is a potential source of error though if things break because I forgot to `git submodule update` after a `git pull`. Could the `autogen.pl` check that the correct submodule commits are available?

**Comment by devreal** [comment]
I pulled current master and all submodules (`git submodule update --remote`) this morning and I'm seeing the exact same issue. OMPI is `v2.x-dev-7783-g9996b9f`, prrte is `dev-30566-g3f7a91e`.

**Comment by devreal** [comment]
Tried again today with current `master` and updated all submodules (Open MPI `g4d0c23c`, PRRTE `g32bdb54`) and couldn't reproduce this anymore. Closing.

**Comment by jsquyres** [comment]
Thanks for testing, @devreal
