### ISSUE TITLE
Support HWLOC < 2.0

### ISSUE THREAD

**Issue by awlauria** [open-mpi/ompi#7725]
It has been determined that OMPI 5.0 needs to support HWLOC versions < 2.0 based on this 3rd party package support list:

https://github.com/open-mpi/ompi/wiki/OMPI-Third-Party-Packages

Work needs to be done to make sure master/5.0 supports this. We also need to add testing infrastructure to MTT/CI for this as well.

**Comment by jsquyres** [comment]
Specifically:
* Amazon Linux uses hwloc v1.7
* Several Linux distros use hwloc v1.11

**Comment by awlauria** [comment]
We added hwloc v1.11 to our ibm nightly master mtt, and has run without any notable issue for several weeks.
