### ISSUE TITLE
MTLs are inappropriately calling exit() or abort()

### ISSUE THREAD

**Issue by mwheinz** [open-mpi/ompi#7726]
As a part of discussing #7699, it was pointed out that there are several error paths in the OFI MTL that call exit() and several in the Portals MTL that call abort(). These are inappropriate and need to be rethought, possibly replacing them with calls to ompi_rte_abort().

**Comment by awlauria** [comment]
@mwheinz can this issue be closed?

**Comment by mwheinz** [comment]
> @mwheinz can this issue be closed?

No, these problems still exist in the OFI provider. Assigning it to myself since there doesn't seem to be anyone in particular maintaining the OFI MTL.

**Comment by mwheinz** [comment]
I can't promise to get to this anytime soon but I've added it to my internal bug queue. It's low priority because it's been in the code without complaint since 2018.

**Comment by awlauria** [comment]
No worries - thanks.

**Comment by janjust** [comment]
@mwheinz Going over older issues, is this still relevant?

**Comment by mwheinz** [comment]
Unfortunately I no longer work for that company and I haven't worked on Open MPI since 2021.

**Comment by janjust** [comment]
closing as stale
