### ISSUE TITLE
UCX MTL performance degradation

### ISSUE THREAD

**Issue by bosilca** [open-mpi/ompi#7727]
I noticed a drastic performance degradation with UCX PML on our small test platform, 8 Linux nodes ConnectX-4.

## Background information
Master was based on 3a036f8486605a plus the patch to allow UCX 1.8 to be used. I compare 4.0 vs master with different UCX version. In all cases I placed one process per node using --map-by.

The outcome can be seen in the graph below. The 4.0 with UCX PML (line 4.0-ucx-ucx) and all flavors of OB1 PML and UCX BTL (1.7 and 1.8) perform  similarly in terms of bandwidth. However, master using UCX PML with both UCX versions see a bandwidth degradation of about half.

[UCX PML vs UCT BTL.pdf](https://github.com/open-mpi/ompi/files/4617338/UCX.PML.vs.UCT.BTL.pdf)

**Comment by yosefe** [comment]
@bosilca can you pls post the command lines for the test runs?

**Comment by bosilca** [comment]
```mpirun --np 2 --map-by node --mca pml ucx ./NPmpi```
```mpirun --np 2 --map-by node --mca pml ob1 --mca btl uct,self ./NPmpi```

**Comment by janjust** [comment]
@bosilca @yosefe @jladd-mlnx  , just fyi, I measured on our thor (x86) system I'm not observing the same behavior.
```
[tomislavj@thor006 pt2pt]$ ofed_info -s
MLNX_OFED_LINUX-4.7-3.2.9.0:
CA 'mlx5_1'
        CA type: MT4123
        Number of ports: 1
        Firmware version: 20.27.2008
        Hardware version: 0
        Node GUID: 0x98039b03008553f7
        System image GUID: 0x98039b03008553f6
        Port 1:
                State: Active
                Physical state: LinkUp
                Rate: 100
                Base lid: 260
                LMC: 0
                SM lid: 1
                Capability mask: 0x2651e848
                Port GUID: 0x98039b03008553f7
                Link layer: InfiniBand
[tomislavj@thor006 pt2pt]$ mpirun --np 2 --mca pml ucx -x UCX_NET_DEVICES=mlx5_1:1 --map-by node --bind-to core:REPORT -H thor006:1,thor007:1 ./osu_bibw
[thor006:28039] MCW rank 0 bound to socket 0[core 0[hwt 0]]: [[<B/././././././././././././././.>][[<./././././././././././././././.>]
[thor007:29170] MCW rank 1 bound to socket 0[core 0[hwt 0]]: [[<B/././././././././././././././.>][[<./././././././././././././././.>]
# OSU MPI Bi-Directional Bandwidth Test v5.6.2
# Size      Bandwidth (MB/s)
1                      10.54
2                      20.46
4                      41.33
8                      82.39
16                    163.31
32                    307.03
64                    527.84
128                  1061.43
256                   648.64
512                  2597.66
1024                 4440.33
2048                 8169.26
4096                14319.28
8192                19337.12
16384               20580.67
32768               21230.24
65536               22593.61
131072              23350.43
262144              24152.83
524288              24384.41
1048576             24473.07
2097152             24528.24
4194304             24573.81
```
![image](https://user-images.githubusercontent.com/3287332/81865913-17e5de00-9534-11ea-922c-c7789c3edb1f.png)

**Comment by bosilca** [comment]
I confirm, UCX 1.8.1 with master (9996b9f) seems to work just fine again.
