### ISSUE TITLE
Request to reopen #6823

### ISSUE THREAD

**Issue by goduck777** [open-mpi/ompi#7731]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.0.x daily build

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From source tarball

### Please describe the system on which you are running

* Operating system/version: RHEL 7
* Computer hardware: IBM Power9 CPU

-----------------------------

## Details of the problem

I got the same issue as described in issue #6823. This issue was fixed in v4.0.x branch before. However, when using the recent daily tarball for v4.0.x, this problem reappears. I added a comment in #6823. I think it should be reopened.

After some tests, I found changes between 20200210 and 20200324 brought back this error.

**Comment by rhc54** [comment]
Does it show up on the nightly tarball from OMPI master?

**Comment by goduck777** [comment]
Yes, I tried openmpi-v4.0.x-202005050241-3b600b8, and the error is still there.

**Comment by rhc54** [comment]
That is the nightly tarball from the 4.0.x branch - I'm talking about master:
https://download.open-mpi.org/nightly/open-mpi/master/openmpi-master-202005120242-3078485.tar.bz2

Could you please test that one?

**Comment by goduck777** [comment]
sorry I missed word "master". I have tested it and can confirm there is no problem with master branch.

However, master branch is not compatible with PMIX installed on my cluster. I hope it can be fixed in 4.0.x branch.

**Comment by rhc54** [comment]
It helps to know where to look for the difference, so thanks for confirming master is good.

What version of PMIx is on your cluster? OMPI v4.0.x is using PMIx v3.1.5 internally, and (barring some mistake) OMPI master should support that level.

**Comment by goduck777** [comment]
It is PMIx 1.x. I'm not sure if it is PMIx's problem, but I can only use mpirun by specifying hostfile, otherwise it will give error.

**Comment by rhc54** [comment]
I see - yes, that is a very old PMIx. Are you building OMPI v4.0.x against that PMIx?? If so, that may well be a significant part of the problems you are experiencing. Please ensure that you are using OMPI's internal PMIx and not the external PMIx 1.x version.

When you are trying to run `mpirun` without a hostfile, what RM are you using? Slurm, JSM, ??

**Comment by goduck777** [comment]
No, I am building OMPI using internal PMIx.

I am using Slrum.

**Comment by rhc54** [comment]
If Slurm's PMIx support is being built against the old PMIx v1.x release, then that is the reason why you have to use the hostfile. The compatibility chart [here](https://pmix.org/support/faq/how-does-pmix-work-with-containers/) shows what is supported.

Any chance you can configure Slurm to use PMIx v3.1.5 instead? Would allow you to run OMPI with both `srun` and `mpirun`.

Won't impact your original issue - that is a separate problem that will take some investigation.

**Comment by goduck777** [comment]
I agree that building a new slurm will solve this issue. However, I am only a user of the cluster and don't have admin right, so I guess it is not possible for me. The admins don't want to upgrade in case it will break the system.

**Comment by goduck777** [comment]
I don't think srun support spawning a new process, or does it?

**Comment by rhc54** [comment]
I don't believe so, no.

**Comment by bwbarrett** [comment]
@rhc54 I'm having trouble following; what's the right next step here?

**Comment by rhc54** [comment]
There are two things that got conflated in this discussion: an issue with direct launch using Slurm+PMIx, and the issue of shared memory between different jobs (the parent and child of a comm_spawn).

I don't think there is a solution to the first issue - if they cannot update the PMIx being used by Slurm, then you can't use OMPI+PMIx with it. They'd have to use the Slurm PMI-1 or PMI-2 support and build OMPI accordingly.

The second issue looks like something changed that is causing the comm_spawn to no longer rendezvous in vader. It could be something in ORTE (we have to provide the locality for both the parent and child to the child procs upon spawn), or it could be something in vader that no longer correctly handles this case. I'm not aware of any ORTE changes in the 4.x branches, so I'm more inclined to suspect the latter - probably best to do a diff between the two hashes and see what changed in those areas?

**Comment by rhc54** [comment]
Just glancing at the PR history, the following ones seem to touch relevant code during the cited time period:

https://github.com/open-mpi/ompi/pull/7463
https://github.com/open-mpi/ompi/pull/7508
https://github.com/open-mpi/ompi/pull/7638

The last two are the most likely culprits.

**Comment by rhc54** [comment]
Without newer version of PMIx, I see no way to resolve this one.
