### ISSUE TITLE
mpiexec -wdir and other MPI standard options are reported deprecated

### ISSUE THREAD

**Issue by abouteiller** [open-mpi/ompi#7738]
`mpiexec -wdir` is reported as deprecated, in favor of `--wdir`. 

This is problematic because the MPI standard, in "Chapter 8.8 Portable MPI Startup" states that mpiexec is optional, but if mpiexec is provided, it must be of a fixed form that accepts standardized arguments exactly (then provides a list of arguments that correspond to the MPI_INFO that are standardized to pass to MPI_COMM_SPAWN). 

All these parameters have a fixed, single dash form.

Full text of the standard for reference. 
```
While a standardized startup mechanism improves the usability of MPI, the range of
environments is so diverse (e.g., there may not even be a command line interface) that
MPI cannot mandate such a mechanism. Instead, MPI specifies an mpiexec startup
command and recommends but does not require it, as advice to implementors. However,
if an implementation does provide a command called mpiexec, it must be of the form
described below.

It is suggested that be at least one way to start <program> with an initial
MPI_COMM_WORLD whose group contains <numprocs> processes. Other arguments to
mpiexec may be implementation-dependent.


Analogous to MPI_COMM_SPAWN, we have <maxprocs>
mpiexec -n <numprocs> <program>
Advice to implementors. Implementors, if they do provide a special startup command for
MPI programs, are advised to give it the following form. The syntax is chosen in 
order that mpiexec be able to be viewed as a command-line version of MPI_COMM_SPAWN
(See Section 10.3.4).

mpiexec 
  -n 
  -soft
  -host
  -arch
  -wdir
  -path
  -file
...
       <command line>
```

Three options are available: 

1. do not deprecate the single-dash form of these arguments
2. work on the standard side to make double-dash form acceptable
3. I am wrong, and line 20 above "if an implementation does provide a command called mpiexec, it must be of the form described below" does not mandate that we use single-dash arguments to be compliant. 

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

master

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

not relevant.

**Comment by markalle** [comment]
I'm not sure specifically about ```-wdir```; my reading of the standard makes it sound optional.  I do however see ```mpirun -configfile``` that doesn't look optional, so that may be an argument against the universal ban on single hyphen long command line options.

OMPI doesn't support command line option aggregation, eg interpreting ```-abc``` as ```-a -b -c``` so I think the argument for banning ```-wdir``` type of options is based necessity but on trying to follow the GNU convention.

I've been told the new rule is from the posix standard but I haven't seen it there (?).  I think it's just a GNU convention, not part of the posix standard.

**Comment by bosilca** [comment]
It does say “must be”, which does not sound optional to me. However, these restrictions only seems to apply to mpiexec, and not to any other means of starting up (aka. not to mpirun).

**Comment by abouteiller** [comment]
Agreed, that is only for `mpiexec`.

**Comment by rhc54** [comment]
Just remember - we simply link `mpirun` to `mpiexec`. We don't differentiate between them.

**Comment by rhc54** [comment]
Should also point out that of the options listed above, we only support `wdir` and `path`. So if we are saying we have to support the others, then we have a problem.

**Comment by awlauria** [comment]
Est. 1 week.

**Comment by abouteiller** [comment]
A second part of this issue is the deprecation of standard mandated spawn info key. Just like the `mpiexec` parameters these keys are listed in the standard and should not be deprecated

I have prepared a PR to do this part. PR #7844

**Comment by rhc54** [comment]
This has been dealt with in PRRTE.
