### ISSUE TITLE
some tests failed

### ISSUE THREAD

**Issue by beew** [open-mpi/ompi#7739]
Thank you for taking the time to submit an issue!

## Background information
compile open-mpi from source, build success with no issue but some tests failed

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
4.0.1, 4.0.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
from source,

built only with configure with no option.

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

I build only with release tar balls

### Please describe the system on which you are running

OS: Ubuntu 16.04

Hardware: Intel® Core™ i7-7820HK CPU @ 2.90GHz × 8 , Graphics GeForce GTX 1070/PCIe/SSE2

Network type: WLAN

-----------------------------

## Details of the problem
compiled open-mpi , configure and make went through with no issue, but got some failures for make check

```
make  check-TESTS
make[3]: Entering directory '/home/bernard/src/openmpi-4.0.1/test/datatype'
make[4]: Entering directory '/home/bernard/src/openmpi-4.0.1/test/datatype'
PASS: unpack_hetero
../../config/test-driver: line 107:  2370 Segmentation fault      "$@" > $log_file 2>&1
FAIL: opal_datatype_test
PASS: checksum
FAIL: position_noncontig
PASS: ddt_raw
PASS: position
../../config/test-driver: line 107:  2417 Segmentation fault      "$@" > $log_file 2>&1
FAIL: ddt_raw2
PASS: ddt_pack
../../config/test-driver: line 107:  2558 Segmentation fault      "$@" > $log_file 2>&1
FAIL: unpack_ooo
PASS: external32
PASS: ddt_test

```

After that it didn't exit back to the terminal prompt. "top" showed that this process is running  forever consuming 100% cpu
```
lt-large_data 

```

**Comment by jsquyres** [comment]
@beew I have found that this happens if you have an installed Open MPI that can be found in your PATH / LD_LIBRARY_PATH when you run `make check`.  I.e., the Automake `make check` infrastructure gets confused between which library it should use, and chooses the wrong one.  Things go downhill from there.

Can you verify that you do not have any other Open MPI in your PATH / LD_LIBRARY_PATH when you `make check`?

**Comment by beew** [comment]
Hmmm.. this is funny

I have installed 4.0.1 in /opt and prepend it to $PATH and $LD_LIBRARY_PATH. Commenting it out and recompile now make check works for both 4.0.1 if configure with no option or --with-cuda, or with --mpi-cxx but not both

for 4.0.2 make check failed even only enable-mpixx

But make check again failed for both with same errors if configure with --enable-cuda and --enable-mpi-cxx

The failures are always the same.

**Comment by jsquyres** [comment]
I cannot reproduce the problem with `--enable-mpicxx` and `make check`.

The next step would likely be to run the test manually and see if you can reproduce the problem.  If you can, triple check that you're linking against the shared libraries that you think you are linking against.

**Comment by beew** [comment]
Hi, how do I check which libraries it links against other than changing LD_LIBRARY_PATH?

**Comment by jsquyres** [comment]
If you're on Linux, use the `ldd` command.  For example:

```
# This the the libdir of my installation prefix
$ cd $HOME/bogus/lib
$ ldd libmpi.so
    linux-vdso.so.1 =>  (0x00002aaaaaaab000)
        libopen-rte.so.40 => /home/jsquyres/bogus/lib/libopen-rte.so.40 (0x00002aaaaae81000)
        libopen-pal.so.40 => /home/jsquyres/bogus/lib/libopen-pal.so.40 (0x00002aaaab19c000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaab519000)
        libpciaccess.so.0 => /usr/lib64/libpciaccess.so.0 (0x00002aaaab71e000)
        librt.so.1 => /lib64/librt.so.1 (0x00002aaaab926000)
        libm.so.6 => /lib64/libm.so.6 (0x00002aaaabb2e000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00002aaaabdb3000)
        libz.so.1 => /lib64/libz.so.1 (0x00002aaaabfb6000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaac1cc000)
        libc.so.6 => /lib64/libc.so.6 (0x00002aaaac3ea000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003491200000)
```

**Comment by beew** [comment]
I don't know why I can't reproduced it consistently.
After having failed for hours at the same spot for openmpi-4.0.3 (same with 4.0.1 and 4.0.2) it suddenly works. The build environment has been identical. The only think I have changed in configure is to have set a prefix to a test directory rather than /opt/openmpi. Could it because it detects the already installed version there even though I have removed the LD_LIBRARY_PATH? 

From test dir (openmpi 4.0.3)
```
ldd libmpi.so
	linux-vdso.so.1 =>  (0x00007ffd283f3000)
	libopen-rte.so.40 => /home/bernard/src/ompi_test/lib/libopen-rte.so.40 (0x00007ffa04141000)
	libopen-pal.so.40 => /home/bernard/src/ompi_test/lib/libopen-pal.so.40 (0x00007ffa03e41000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ffa03c39000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffa03930000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffa03713000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffa03349000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ffa0312f000)
	libevent-2.0.so.5 => /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5 (0x00007ffa02ee9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffa02ce5000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007ffa048b5000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007ffa02ae2000)
	libevent_pthreads-2.0.so.5 => /usr/lib/x86_64-linux-gnu/libevent_pthreads-2.0.so.5 (0x00007ffa028df000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffa04717000)
	libevent_core-2.0.so.5 => /usr/lib/x86_64-linux-gnu/libevent_core-2.0.so.5 (0x00007ffa026b5000)
```

**Comment by jsquyres** [comment]
Open MPI's installation doesn't know anything about other Open MPI installations on the same machine -- it just knows about the `--prefix` you gave it.  It doesn't matter if that prefix is `/opt/openmpi` or `/home/bernard/src/ompi_test` or anything else that doesn't conflict with system-level things.

But if `LD_LIBRARY_PATH` (or similar) muddles the issue by unintentionally pointing to another Open MPI installation, then Weirdness(tm) can definitely occur during `make check`.

**Comment by beew** [comment]
I meant to say that the prefix in configure already has a version of openmpi install even though I have removed it from LD_LIBRARY_PATH. Now to follow up I just renamed /opt/openmpi to /opt/openmpi-bk and recompiled openmpi with prefix /opt/openmpi and this time was successful!

**Comment by beew** [comment]
After testing a few more times, the culprit is setting prefix=target in configure where target already has an earlier version of openmpi installed (usually I removed it after configure instead of before). Removing the earlier version from target before running ./configure --prefix=target fixes the problem.
