### ISSUE TITLE
OpenMPI cuda aware wrong result

### ISSUE THREAD

**Issue by yongjun67** [open-mpi/ompi#7746]
I am developing FDTD code on  GPU. I tried to use OpenMPI cuda ware option to send and receive data between GPUs. 

First try: Copy data from GPU to CPU, call MPI_Isend and MPI_Irecv to send and receive data. Copy data from CPU to GPU. The result is correct.

Second try: Directly call MPI_Isend and MPI_Irecv to send and receive data between GPU. The result will diverge after some times.

It looks like cuda aware mpi call lost data precision.

We are using OpenMPI 4.0.2. We download the source code from OpenMPI website and build with cuda-aware enabled.

Any suggestion will help.

Thanks,

Yongjun

**Comment by bosilca** [comment]
Do you wait for completion of your nonblocking calls ?

You might want to take a look at
https://github.com/open-mpi/ompi/issues/7733 to understand some of the
potential issues while mixing MPI and CUDA.

  George.

**Comment by yongjun67** [comment]
Hi George,

Thanks for your reply. Yes, we always use MPI_Wait for no blocking mpi calls.

Yongjun

**Comment by bosilca** [comment]
And you always wait for a CUDA event on the kernel that generates the data before your MPI_Isend ? Is there any way you can post some kind of reproducer here ?

**Comment by yongjun67** [comment]
Hi George,

Below is my code example


	kernelPrepadata <<< >>>( ... )

	if( id == 0 )
	{
		tag = 1;
		MPI_Isend( sendBufDev, iBufSize, MPI_FLOAT,
			1, tag, MPI_COMM_WORLD, &request[0]);

		tag = 2;
		MPI_Irecv( recvBufDev, iBufSize, MPI_FLOAT,
			1, tag, MPI_COMM_WORLD, &request[1]);
	}
	else
	{
		tag = 2;
		MPI_Isend( sendBufDev, iBufSize, MPI_FLOAT,
			0, tag, MPI_COMM_WORLD, &request[2]);

		tag = 1;
		MPI_Irecv( recvBufDev, iBufSize, MPI_FLOAT,
			0, tag, MPI_COMM_WORLD, &request[3]);
	}

	MPI_Wait( &request[0] , &status[0] );
	MPI_Wait( &request[1] , &status[1] );
	MPI_Wait( &request[2] , &status[2] );
	MPI_Wait( &request[3] , &status[3] );

	kernelSimulation<<< >>> ( ... )

**Comment by bosilca** [comment]
The CUDA kernel submission being asynchronous you need to synchronize your stream in order to access the updated (the correct) content of your buffers during the MPI call. Otherwise, your kernel and the MPI call will execute concurrently, and MPI might send that has not been updated yet. This is exactly what is under discussion in the other thread I pointed to.

**Comment by yongjun67** [comment]
Thanks. I will try.

**Comment by yongjun67** [comment]
Hi George,

The issue was solved. Thank you very much for your help.

Yongjun
