### ISSUE TITLE
OpenMPI warning message

### ISSUE THREAD

**Issue by yongjun67** [open-mpi/ompi#7752]
I built OpenMPI with LSF support. When I ran OpenMPI on a machines that LSF library was not set in LD_LIBRARY_PATH, I got the following warning message:

mca_base_component_repository_open: unable to open mca_plm_lsf: libbat.so: cannot open shared object file: No such file or directory (ignored)

If I set LD_LIBRARY_PATH, then I will not see the message.
 
How can I avoid this message output?

Thanks,

Yongjun

**Comment by jjhursey** [comment]
The `lsf` components in Open MPI (`plm/lsf`, `ess/lsf`, `ras/lsf`) link against LSF's `libbat.so` library. The path to that library must be in your `LD_LIBRARY_PATH` for the components to be loaded properly. If it is not in your `LD_LIBRARY_PATH` then you will get that warning message and the LSF functionality will disable itself. The warning message is coming from the `dlopen` of the components during selection.

If you have LSF on all of your machines the best way to make sure that LSF's libraries are in your search path is to source the `$LSF_TOP/conf/profile.lsf` in your default system profile (or individual user profiles).

If you are trying to use the same Open MPI build across systems with LSF and without LSF that warning can be difficult to avoid safely. On systems with LSF, you can source the `profile.lsf`. On systems without LSF, you don't necessarily want to source the `profile.lsf` (it won't hurt anything though) and may want to suppress that warning message.

To suppress the warning message you can set the MCA parameter `mca_base_component_show_load_errors` to `0` (you can set it in the environment by `export OMPI_MCA_mca_base_component_show_load_errors=0` if that is more manageable). Note that setting that MCA parameter will silence these types of warnings for all components. This means that you might miss other warnings about missing dependent libraries that you will want to see.

**Comment by yongjun67** [comment]
Thank you very much.
