### ISSUE TITLE
mtl-portals4: Call add_procs through PML

### ISSUE THREAD

**Issue by tkordenbrock** [open-mpi/ompi#7763]
Shamelessly cribbed from Michael Heinz' cribbing of Brian Barrett's issue #7571 - Update Portals4 MTL to use the correct add_procs call.

> Change ompi_mtl_ofi_get_endpoint() to call the active PML's add_procs() rather than the OFI MTL add_procs() directly when discovering a new process during operation.
> Functionally, this has no impact in correct operation. However, the current behavior means that the heterogenous and active PML checks are not being executed in the dynamic discovery case.

**Comment by jsquyres** [comment]
@tkordenbrock Are you going to back-port this to v4.0.x and v4.1.x?

**Comment by tkordenbrock** [comment]
@jsquyres This was back-ported in #7890 and #7891, but the issue was never closed.  Sorry about that.  Closing now.
