### ISSUE TITLE
Not able to run MPI job on multiple nodes of a cluster

### ISSUE THREAD

**Issue by yogitanegi** [open-mpi/ompi#7796]
**Execution on one node of cluster(gpu7)** : 

[capc@gpu7 hybrid_slurm_scripts]$ mpirun ./a.out 
--------------------------------------------------------------------------
WARNING: There is at least non-excluded one OpenFabrics device found,
but there are no active ports detected (or Open MPI was unable to use
them).  This is most certainly not what you wanted.  Check your
cables, subnet manager configuration, etc.  The openib BTL will be
ignored for this job.

  Local host: gpu7
--------------------------------------------------------------------------
We have 28 processes.
Process 1 reporting for duty.
Process 2 reporting for duty.
Process 3 reporting for duty.
Process 4 reporting for duty.
Process 5 reporting for duty.
Process 6 reporting for duty.
Process 7 reporting for duty.
Process 8 reporting for duty.
Process 9 reporting for duty.
Process 10 reporting for duty.
Process 11 reporting for duty.
Process 12 reporting for duty.
Process 13 reporting for duty.
Process 14 reporting for duty.
Process 15 reporting for duty.
Process 16 reporting for duty.
Process 17 reporting for duty.
Process 18 reporting for duty.
Process 19 reporting for duty.
Process 20 reporting for duty.
Process 21 reporting for duty.
Process 22 reporting for duty.
Process 23 reporting for duty.
Process 24 reporting for duty.
Process 25 reporting for duty.
Process 26 reporting for duty.
Process 27 reporting for duty.
[gpu7:43668] 27 more processes have sent help message help-mpi-btl-openib.txt / no active ports found
[gpu7:43668] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

**Execution on another node of cluster(gpu6)** : 

[capc@gpu6 hybrid_slurm_scripts]$ mpirun ./a.out 
--------------------------------------------------------------------------
WARNING: There is at least non-excluded one OpenFabrics device found,
but there are no active ports detected (or Open MPI was unable to use
them).  This is most certainly not what you wanted.  Check your
cables, subnet manager configuration, etc.  The openib BTL will be
ignored for this job.

  Local host: gpu6
--------------------------------------------------------------------------
We have 28 processes.
Process 1 reporting for duty.
Process 2 reporting for duty.
Process 3 reporting for duty.
Process 4 reporting for duty.
Process 5 reporting for duty.
Process 6 reporting for duty.
Process 7 reporting for duty.
Process 8 reporting for duty.
Process 9 reporting for duty.
Process 10 reporting for duty.
Process 11 reporting for duty.
Process 12 reporting for duty.
Process 13 reporting for duty.
Process 14 reporting for duty.
Process 15 reporting for duty.
Process 16 reporting for duty.
Process 17 reporting for duty.
Process 18 reporting for duty.
Process 19 reporting for duty.
Process 20 reporting for duty.
Process 21 reporting for duty.
Process 22 reporting for duty.
Process 23 reporting for duty.
Process 24 reporting for duty.
Process 25 reporting for duty.
Process 26 reporting for duty.
Process 27 reporting for duty.
[gpu6:51490] 27 more processes have sent help message help-mpi-btl-openib.txt / no active ports found
[gpu6:51490] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

**Execution on multiple nodes**

[capc@gpu6 hybrid_slurm_scripts]$ mpirun --hostfile my_hostfile ./a.out 
bash: conda: command not found
orted: Error: unknown option "--hnp-topo-sig"
Type 'orted --help' for usage.
Usage: orted [OPTION]...
   -am <arg0>            Aggregate MCA parameter set file list
-d|--debug               Debug the OpenRTE
   --daemonize           Daemonize the orted into the background
   --debug-daemons       Enable debugging of OpenRTE daemons
   --debug-daemons-file  Enable debugging of OpenRTE daemons, storing output
                         in files
-h|--help                This help message
   --hnp                 Direct the orted to act as the HNP
   --hnp-uri <arg0>      URI for the HNP
   -nodes|--nodes <arg0>  
                         Regular expression defining nodes in system
   -output-filename|--output-filename <arg0>  
                         Redirect output from application processes into
                         filename.rank
   --parent-uri <arg0>   URI for the parent if tree launch is enabled.
   -report-bindings|--report-bindings 
                         Whether to report process bindings to stderr
   --report-uri <arg0>   Report this process' uri on indicated pipe
-s|--spin                Have the orted spin until we can connect a debugger
                         to it
   --set-sid             Direct the orted to separate from the current
                         session
   --singleton-died-pipe <arg0>  
                         Watch on indicated pipe for singleton termination
   --test-suicide <arg0>  
                         Suicide instead of clean abort after delay
   --tmpdir <arg0>       Set the root for the session directory tree
   -tune <arg0>          Application profile options file list
   -xterm|--xterm <arg0>  
                         Create a new xterm window and display output from
                         the specified ranks there

For additional mpirun arguments, run 'mpirun --help <category>'

The following categories exist: general (Defaults to this option), debug,
    output, input, mapping, ranking, binding, devel (arguments useful to OMPI
    Developers), compatibility (arguments supported for backwards compatibility),
    launch (arguments to modify launch options), and dvm (Distributed Virtual
    Machine arguments).
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------

**Content of my_hostfile**

gpu6
gpu7

I am able to run MPI job is successfully on both nodes separately, but not able to run parallely on both nodes.
Can anyone guide me regarding this?

**Comment by rhc54** [comment]
It appears the two nodes have very different OMPI versions on them.

**Comment by yogitanegi** [comment]
Both have same OMPI version, I have checked using ompi_info & mpiexec --version

**Comment by ggouaillardet** [comment]
In your script, did you double check that
which mpirun
is pointing to the binary you expect?

also, the `conda` related error is suspicious


you might also want to try replacing
mpirun
with
`which mpirun`
(this is "which mpirun" between backquotes, not sure how github markdown is
gonna display this...)

and see if it helps.

>

**Comment by yogitanegi** [comment]
Its pointing to the same binary in both the nodes, I have checked.

**Comment by yogitanegi** [comment]
The above error got solved.
Now, its getting hang on execution 

[capc@gpu6 mpi_tests]$ /opt/openmpi4.0.3/build/bin/mpirun --host gpu7,gpu6 ./a.out 
bash: conda: command not found
--------------------------------------------------------------------------
WARNING: There is at least non-excluded one OpenFabrics device found,
but there are no active ports detected (or Open MPI was unable to use
them).  This is most certainly not what you wanted.  Check your
cables, subnet manager configuration, etc.  The openib BTL will be
ignored for this job.

  Local host: gpu7
--------------------------------------------------------------------------
We have 2 processes.
--------------------------------------------------------------------------
WARNING: Open MPI accepted a TCP connection from what appears to be a
another Open MPI process but cannot find a corresponding process
entry for that peer.

This attempted connection will be ignored; your MPI job may or may not
continue properly.

  Local host: gpu6
  PID:        29209
--------------------------------------------------------------------------
[gpu6:29203] 1 more process has sent help message help-mpi-btl-openib.txt / no active ports found
[gpu6:29203] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

Is this due to the reason that ports are down because its giving "no active ports found"

**Comment by ggouaillardet** [comment]
do you want to close this issue and follow up at https://stackoverflow.com/questions/62301355/error-in-mpi-program-execution-no-active-ports-found ?

**Comment by yogitanegi** [comment]
Sure :+1:
