### ISSUE TITLE
Improper use of 'basename' in regression-tests

### ISSUE THREAD

**Issue by cponder** [open-mpi/ompi#7804]
I'm building OpenMPI 4.0.2 & 4.0.4rc2 using the PGI 20.5 compiler.
Running the "make check" command, i get these messages
```
basename: extra operand ‘--test-name’
Try 'basename --help' for more information.
```

**Comment by cponder** [comment]
This is on Ubuntu 18.04.

I grep'd to see instances of the string "--test-name" but can't tell where it's being passed to the "basename" primitive. The messages come out when the tests in the "test/asm" (atomic tests) directory are run, not anywhere else.

**Comment by jsquyres** [comment]
The `make check` engine is wholly in control of GNU Automake; I don't think we have any unique code in there.

Can you track down a little further where this is happening?  I don't know if `make V=1 check` emits any additional output...?

**Comment by cponder** [comment]
V=1 doesn't tell me anything more:
```
make[4]: Entering directory '/gpfs/fs1/SHARE/Utils/OpenMPI/4.0.4rc2/PGI-20.5_CUDA-11.0.1.0_450.36.06_UCX-1.8.0_HWLoc-2.2.0_ZLib-1.2.11/distro/test/asm'
basename: extra operand ‘--test-name’
Try 'basename --help' for more information.
```

**Comment by cponder** [comment]
Using this wrapper
```
#!/bin/bash
echo $* 1>&2
/usr/bin/basename $*
```
I get this output
```
make[4]: Entering directory '/gpfs/fs1/SHARE/Utils/OpenMPI/4.0.4rc2/PGI-20.5_CUDA-11.0.1.0_450.36.06_UCX-1.8.0_HWLoc-2.2.0_ZLib-1.2.11/distro/test/asm'
/bin/bash ../../config/test-driver --test-name atomic_barrier --log-file atomic_barrier.log --trs-file atomic_barrier.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./atomic_barrier
/usr/bin/basename: extra operand ‘--test-name’
Try '/usr/bin/basename --help' for more information.
```
It looks like this should be the arguments to some other command, unless the above command was supposed to be evaluated before it is passed to the `basename` command.

Is there some flag I can put into the wrapper so I get a backtrace of where it was invoked from?

**Comment by cponder** [comment]
I tried adding things like
```
echo ${BASH_SOURCE[0]} ${BASH_LINENO[0]} 1>&1
echo ${BASH_SOURCE[1]} ${BASH_LINENO[0]} 1>&1
```
or 
```
 echo $(caller 0) 1>&2
 echo $(caller 1) 1>&2
```
but they didn't return anything beyond
```
--> Testing /home/cponder/bin/basename 0
```
It looks like these commands, at least, don't give any visibility into the components of the test harness (probably not written in bash).

**Comment by cponder** [comment]
The command
```
fgrep -r -- --test-name distro
```
(where 'distro' is where I unpacked the source tarball) gives 168 lines, most of which look pretty much the same as this one
```
distro/test/class/Makefile: $(am__check_pre) $(LOG_DRIVER) --test-name "$$f"
```
so I think the problem is down in the expression that $(am__check_pre) is evaluating to.

**Comment by jsquyres** [comment]
Hah.  I found it.

Looks like we're using a hook in the AM tests engine to insert our own `run_tests` script:

https://github.com/open-mpi/ompi/blob/fcdcb593bb0676bf4f16cbef554bf0e32f15ff10/test/asm/Makefile.am#L21

And `run_tests` is https://github.com/open-mpi/ompi/blob/master/test/asm/run_tests. 

And guess what?  `run_tests` calls `basename`.  😄 

I found the fix and filed a PR: https://github.com/open-mpi/ompi/pull/7834

Thanks for bringing this to our attention!

**Comment by cponder** [comment]
Thank you for following up on this!
I'm trying to clear out regression-failures while I figure out why my app is breaking, in case there's a connection. Not in this case, of course, but it looked like a programming oversight that might be easy to identify & fix.
OpenMPI 4.0.4 is out now, but hopefully the errors with go away in the next one...
