### ISSUE TITLE
GNU-only flags in build

### ISSUE THREAD

**Issue by cponder** [open-mpi/ompi#7805]
I'm building OpenMPI 4.0.4rc using the PGI 20.5 compiler on Ubuntu 18.04.
I see quite a few of these messages
```
checking dynamic linker characteristics... pgcc-Warning-Unknown switch: -print-search-dirs
pgc++-Error-Unknown switch: -print-prog-name=ld
pgcc-Warning-Unknown switch: -fasynchronous-unwind-tables
pgcc-Warning-Unknown switch: -finline-functions
```
They don't cause the build to fail-out because I use this form to downgrade the invalid switch to a warning:
```
export CC="pgcc -noswitcherror"
```

**Comment by cponder** [comment]
Maybe the discovery step using the autotools config can be used to detect whether the switches are valid for the compiler or not.

**Comment by jsquyres** [comment]
It looks like the `checking dynamic linker characteristics` test is part of GNU Libtool.

It could well be that GNU Libtool doesn't recognize / handle all of pgcc's flags properly...?

Is this the first place in the output where these warnings/errors appear?  Or are those flags inserted in CFLAGS (or whatever) earlier in `configure`?

**Comment by cponder** [comment]
This one only shows up during the config so I probably shouldn't have mentioned it:
```
pgc++-Error-Unknown switch: -print-prog-name=ld
```
The other two are being tested in the config
```
checking if -fasynchronous-unwind-tables compiler flag works... yes
checking if pgcc -noswitcherror supports -finline-functions... yes
checking for final compiler unwind flags... -fasynchronous-unwind-tables
```
but keep giving warnings during the build:
```
pgcc-Warning-Unknown switch: -fasynchronous-unwind-tables
pgcc-Warning-Unknown switch: -finline-functions
```
I think my using `-noswitcherror` is causing a false pass on these tests so they end up being inserted into the build.

**Comment by jsquyres** [comment]
So you're saying the only real error is `pgc++-Error-Unknown switch: -print-prog-name=ld`?

Can you send the output listed here: https://www.open-mpi.org/community/help/

**Comment by cponder** [comment]
Ok this is my bad -- if I leave out the `-noswitcherror` completely, then the `config` is (correctly) recognizing that they aren't valid and then they are not used in the rest of the build.
I'm closing this one.
(FYI -- I believe I had added this flag trying to get around some other error (maybe a linkage issue) that ended up being fixed some other way).

**Comment by cponder** [comment]
Here's what brought the problem on to begin with: when I build without any `-noswitcherror` flags, I get this error
```
libtool: link: pgcc -shared  -fpic -DPIC  .libs/mca_pmix_s2_la-pmix_s2_component.o .libs/mca_pmix_s2_la-pmix_s2.o .libs/mca_pmix_s2_la-pmi2_pmap_parser.o   -Wl,-rpath -Wl,/usr/local/src/openmpi-4.0.2/opal/.libs -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib ../../../../opal/.libs/libopen-pal.so -L/usr/lib -L/usr/lib64 /usr/lib/x86_64-linux-gnu/libpmi2.so -lrt -lutil -lz /usr/local/lib/libhwloc.so -lm -lcudart -lnvidia-ml -lnuma -latomic -levent -levent_pthreads -lc  -O2 -m64 -tp=zen   -pthread -Wl,-soname -Wl,mca_pmix_s2.so -o .libs/mca_pmix_s2.so
pgcc-Error-Unknown switch: -pthread
Makefile:1829: recipe for target 'mca_pmix_s2.la' failed
make[2]: *** [mca_pmix_s2.la] Error 1
make[2]: Leaving directory '/usr/local/src/openmpi-4.0.2/opal/mca/pmix/s2'
make[1]: *** [install-recursive] Error 1
Makefile:2361: recipe for target 'install-recursive' failed
```
This particular is from OpenMPI 4.0.2. During the `configure` phase, I can't tell if it is checking whether the `-pthread` is valid or not. I only see the flag show up, though only in this one part of the build.
That being said, I'm not sure this is a problem with 4.0.4rc2 so I'll check there to see if I need to re-open this.

**Comment by jsquyres** [comment]
Ok.  If you do re-open, please send all the information listed in https://www.open-mpi.org/community/help/
