### ISSUE TITLE
unexpected binding with srun

### ISSUE THREAD

**Issue by angainor** [open-mpi/ompi#7806]
I have tested OpenMPI 4.0.3, but also 3.1.4. When running applications with `srun`, it seems that OpenMPI is honoring the binding scheme set by `srun`, unless it is the `none` scheme, or a mask containing all cores. Consider the following start line:

`OMP_NUM_THREADS=128 srun --tasks-per-node=1 --cpus-per-task=128 -N 1 -n 1 --cpu-bind=verbose,mask_cpu:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF ./hello`

where `hello` is a hybrid MPI-OpenMP program. In the above case all threads are bound to CPU core 0. This happens to be because `hwloc_base_binding_policy=core` (the problem goes away if I set it to `none`), but in this case I think it is unexpected for two reasons:
1. I explicitly asked `srun` for a 'bind to all' setting, yet all my threads run on a single core
2. the default employed by OpenMPI (bind to core) might not be the most intuitive in the case of hybrid MPI + threads applications.

As of 1, It is enough for me to modify a single bit in the above mask and the behavior is as I would expect. I guess OpenMPI does not touch `srun`'s affinity settings as long as they are not equivalent to `-bind-to none`? Is this the desired behavior?

As of 2, I understand that the problem is of course difficult to solve in a perfect way. I imagine that OpenMPI could detect some hybrid cases (e.g., when `--cpus-per-task` is used in slurm, or `OMP_NUM_THREADS` is set) and modify the default `bind-to` setting to produce affinity maps that use multiple cores, e.g., with  some variant of `PE=..`. I guess complex / smart affinity maps could be designed depending on NUMA hierarchy, but at least it would be good to allow the threads to run on more than 1 core.

**Comment by rhc54** [comment]
See https://github.com/open-mpi/ompi/pull/7511

**Comment by angainor** [comment]
@rhc54 Thank you! I missed that. It seems that this PR addresses the first part (forced OMPI binding when I would expect no binding). Do you also have any thoughts about what to do by default with hybrid MPI-thread applications?

**Comment by rhc54** [comment]
Usually the best performance in that model is to bind to socket/NUMA/package. It keeps all the threads localized while allowing max usage of the available cpus. If you have a multi-socket system, not binding to a socket can cause the threads to fall on different sockets, causing loss of performance due to NUMA impact.

**Comment by angainor** [comment]
@rhc54 Yea, it's even more complex on the Epyc's, which have 4 NUMA nodes per socket :) So binding to socket is wrong, but binding to numa is also wrong in general, because you might have, say, 2 ranks per socket. If you bind to numa, you're using half of the system.

But in either case, in that scenario OMPI is currently by default binding to core, which makes all threads run on the same core. My question was, could OMPI detect hybrid runs with multiple threads per rank and try to assign an affinity map large enough to hold all threads?

**Comment by angainor** [comment]
preferably with reasonable binding / mapping among numa nodes :) but anything will be better than running on a single core.

**Comment by rhc54** [comment]
I'm not sure how we would do that - at one point, I had implemented detection of OpenMP directives that guided the binding pattern, but I got yelled down for it and so it was removed. Probably something that requires some thought as it will become a more common problem over time.

**Comment by angainor** [comment]
In the slurm case it is simple - you specify `--cpus-per-task`, which could (maybe) be translated to `PE=..`. For the `mpirun` case I would maybe leave all to the user, who should do the correct thing. But with `srun` I am already doing the correct thing (`--cpus-per-task`) and then I have to do it again by thinking about cpu masks.

**Comment by rhc54** [comment]
How does Slurm translate the `--cpus-per-task` directive? Does it show up as an envar? I would have thought it would show up in the binding mask, but apparently not?

**Comment by angainor** [comment]
@rhc54 This is what I get on our system - I think we have task affinity disabled in slurm:
```
$ srun --tasks-per-node=1 --cpus-per-task=128 -N 1 --time=04:30:00 env | grep SLURM
SLURM_PRIO_PROCESS=0
SLURM_UMASK=0002
SLURM_JOB_NAME=env
SLURM_JOB_CPUS_PER_NODE=128
SLURM_NTASKS=1
SLURM_NPROCS=1
SLURM_CPUS_PER_TASK=128
SLURM_NTASKS_PER_NODE=1
SLURM_JOB_ID=109091
SLURM_JOBID=109091
SLURM_STEP_ID=0
SLURM_STEPID=0
SLURM_NNODES=1
SLURM_JOB_NUM_NODES=1
SLURM_NODELIST=b1389
SLURM_JOB_PARTITION=normal
SLURM_TASKS_PER_NODE=1
SLURM_SRUN_COMM_PORT=36353
SLURM_JOB_NODELIST=b1389
SLURM_STEP_NUM_NODES=1
SLURM_STEP_NUM_TASKS=1
SLURM_STEP_TASKS_PER_NODE=1
SLURM_STEP_LAUNCHER_PORT=36353
SLURM_STEP_RESV_PORTS=16374-16375
SLURM_PMIX_MAPPING_SERV=(vector,(0,1,1))
SLURM_CPUS_ON_NODE=128
SLURM_CPU_BIND=quiet,mask_cpu:0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
SLURM_CPU_BIND_LIST=0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
SLURM_CPU_BIND_TYPE=mask_cpu:
SLURM_CPU_BIND_VERBOSE=quiet
SLURM_TASK_PID=222642
SLURM_NODEID=0
SLURM_PROCID=0
SLURM_LOCALID=0
SLURM_GTIDS=0
SLURM_JOB_UID=51453
SLURM_JOB_GID=51453
```
I have removed some irrelevant envars. You are right - it seems that sometimes `--cpus-per-task` do show up in the mask, but not always, and not in a helpful way. For example in this case the mask is all `F`'s, which is correct, but OMPI decides that this means 'go ahead bind'.

It seems there are problems with slurm also. For example, if I use `--tasks-per-node=4` (aka not 1), but start less than 4 ranks (watch the `-n`), then the binding mask is always all `F`'s (which screws up OMPI). When I finally get to `-n 4` then the binding mask is finally perfect! 
```
$ srun --tasks-per-node=4 -n 1 --cpus-per-task=32 -N 1 --time=04:30:00 env | grep SLURM_CPU_BIND=
SLURM_CPU_BIND=quiet,mask_cpu:0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```
```
$ srun --tasks-per-node=4 -n 2 --cpus-per-task=32 -N 1 --time=04:30:00 --account=nn9997k env | grep SLURM_CPU_BIND=
SLURM_CPU_BIND=quiet,mask_cpu:0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
SLURM_CPU_BIND=quiet,mask_cpu:0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```
```
$ srun --tasks-per-node=4 -n 3 --cpus-per-task=32 -N 1 --time=04:30:00 --account=nn9997k env | grep SLURM_CPU_BIND=
SLURM_CPU_BIND=quiet,mask_cpu:0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
SLURM_CPU_BIND=quiet,mask_cpu:0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
SLURM_CPU_BIND=quiet,mask_cpu:0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```
```
$ srun --tasks-per-node=4 -n 4 --cpus-per-task=32 -N 1 --time=04:30:00 --account=nn9997k env | grep SLURM_CPU_BIND=
SLURM_CPU_BIND=quiet,mask_cpu:0x000000000000000000000000FFFFFFFF000000000000000000000000FFFFFFFF,0x0000000000000000FFFFFFFF000000000000000000000000FFFFFFFF00000000,0x00000000FFFFFFFF000000000000000000000000FFFFFFFF0000000000000000,0xFFFFFFFF000000000000000000000000FFFFFFFF000000000000000000000000
SLURM_CPU_BIND=quiet,mask_cpu:0x000000000000000000000000FFFFFFFF000000000000000000000000FFFFFFFF,0x0000000000000000FFFFFFFF000000000000000000000000FFFFFFFF00000000,0x00000000FFFFFFFF000000000000000000000000FFFFFFFF0000000000000000,0xFFFFFFFF000000000000000000000000FFFFFFFF000000000000000000000000
SLURM_CPU_BIND=quiet,mask_cpu:0x000000000000000000000000FFFFFFFF000000000000000000000000FFFFFFFF,0x0000000000000000FFFFFFFF000000000000000000000000FFFFFFFF00000000,0x00000000FFFFFFFF000000000000000000000000FFFFFFFF0000000000000000,0xFFFFFFFF000000000000000000000000FFFFFFFF000000000000000000000000
SLURM_CPU_BIND=quiet,mask_cpu:0x000000000000000000000000FFFFFFFF000000000000000000000000FFFFFFFF,0x0000000000000000FFFFFFFF000000000000000000000000FFFFFFFF00000000,0x00000000FFFFFFFF000000000000000000000000FFFFFFFF0000000000000000,0xFFFFFFFF000000000000000000000000FFFFFFFF000000000000000000000000
```

**Comment by artpol84** [comment]
Please see an update here: https://github.com/open-mpi/ompi/pull/7511#issuecomment-655082155

**Comment by rhc54** [comment]
@jsquyres Could someone please close this? It has been complete for some time.
