### ISSUE TITLE
Do not assume that __STDC_VERSION__ is defined

### ISSUE THREAD

**Issue by ckhroulev** [open-mpi/ompi#7810]
## Background information

CI builds of our C++ code use a set of pedantic warning flags with `-Werror` to ensure that it compiles without warnings.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.0.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Package `libopenmpi-dev (4.0.3-0ubuntu1)` on Ubuntu 20.04 LTS.

### Please describe the system on which you are running

* Operating system/version: Ubuntu 20.04 LTS
* Computer hardware: any
* Network type: any

## Details of the problem

When building C++ code using GCC 9.3 compilation of all source files that include `mpi.h` fails because `__STDC_VERSION__` is not defined.

Note that C++ compilers don't have to define `__STDC_VERSION__`, so all uses of `__STDC_VERSION__` in public headers should be protected. (See https://github.com/google/brotli/issues/398, for example.)

Please see below for a minimal example.

```
builder@499dd19be7cf:~$ cat test.cc 
#include <mpi.h>

int main(int argc, char **argv) {
  return 0;
}
builder@499dd19be7cf:~$ mpicxx --version
g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

builder@499dd19be7cf:~$ mpiexec --version
mpiexec (OpenRTE) 4.0.3

Report bugs to http://www.open-mpi.org/community/help/
builder@499dd19be7cf:~$ mpicxx -Wundef -Werror test.cc 
In file included from test.cc:1:
/usr/lib/x86_64-linux-gnu/openmpi/include/mpi.h:316:16: error: "__STDC_VERSION__" is not defined, evaluates to 0 [-Werror=undef]
  316 | #        elif (__STDC_VERSION__ >= 201112L)
      |                ^~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

**Comment by ckhroulev** [comment]
See also: https://github.com/open-mpi/ompi/issues/7099

**Comment by jsquyres** [comment]
Well that sucks.  Is there some other `#define` that is always there that can be used instead?

FYI: @hjelmn This is going to be a problem for C11 detection (e.g., https://github.com/open-mpi/ompi/blob/master/config/opal_setup_cc.m4#L84).

**Comment by hjelmn** [comment]
Another irritating C++-ism. WG21 should have required this to be set based on the level of C that they are compatible with.

We can assume C89 if __STDC_VERSION__ is not defined since that is the greatest commonality between C++ and C.

**Comment by hjelmn** [comment]
And, no. It won't break our detection. Compiling Open MPI with CC=g++ or something similar is user error.

**Comment by jsquyres** [comment]
PR #7817 fixes this on master.
