### ISSUE TITLE
MPI failing to bind a process to socket

### ISSUE THREAD

**Issue by ChaiBapchya** [open-mpi/ompi#7816]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.0.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Tarball
https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.1.tar.gz

### Please describe the system on which you are running

* Operating system/version: Ubuntu
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem
https://github.com/aws/sagemaker-training-toolkit/blob/8281b567dbf848c4482be78c4b009e9a619d081c/src/sagemaker_training/mpi.py#L182-L225
```
mpirun --host algo-1-xgg08:2 -np 2 --allow-run-as-root --display-map --tag-output -mca btl_tcp_if_include eth0 -mca oob_tcp_if_include eth0 -mca plm_rsh_no_tree_spawn 1 -bind-to socket -map-by slot -mca pml ob1 -mca btl ^openib -mca orte_abort_on_non_zer
o_status 1 -x NCCL_MIN_NRINGS=4 -x NCCL_SOCKET_IFNAME=eth0 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x LD_PRELOAD=/usr/local/lib/python3.6/site-packages/gethostname.cpython-36m-x86_64-linux-gnu.so -x AWS_ACCESS_KEY_ID -x AWS_SECRET_ACCESS_KEY -x AWS_SESSION_TOKEN -x
SM_HOSTS -x SM_NETWORK_INTERFACE_NAME -x SM_HPS -x SM_USER_ENTRY_POINT -x SM_FRAMEWORK_PARAMS -x SM_RESOURCE_CONFIG -x SM_INPUT_DATA_CONFIG -x SM_OUTPUT_DATA_DIR -x SM_CHANNELS -x SM_CURRENT_HOST -x SM_MODULE_NAME -x SM_LOG_LEVEL -x SM_FRAMEWORK_MODULE -x SM_INPUT_DIR -x
SM_INPUT_CONFIG_DIR -x SM_OUTPUT_DIR -x SM_NUM_CPUS -x SM_NUM_GPUS -x SM_MODEL_DIR -x SM_MODULE_DIR -x SM_TRAINING_ENV -x SM_USER_ARGS -x SM_OUTPUT_INTERMEDIATE_DIR -x PYTHONPATH /usr/local/bin/python3.6 -m mpi4py hvd_mnist_mxnet.py
```

For this input, [using MPI for Horovod with NCCL on MXNet]
```
algo-1-xgg08_1  | WARNING: Open MPI tried to bind a process but failed.  This is a
algo-1-xgg08_1  | warning only; your job will continue, though performance may
algo-1-xgg08_1  | be degraded.
algo-1-xgg08_1  |
algo-1-xgg08_1  |   Local host:        8b66742c1bd5
algo-1-xgg08_1  |   Application name:  /usr/local/bin/python3.6
algo-1-xgg08_1  |   Error message:     failed to bind memory
algo-1-xgg08_1  |   Location:          rtc_hwloc.c:447
```

**Comment by ChaiBapchya** [comment]
Related issue https://github.com/open-mpi/ompi/issues/7368

**Comment by bgoglin** [comment]
If OMPI is using a hwloc 1.x, make sure you have numactl developement headers installed (libnuma-dev package on Ubuntu).

**Comment by rhc54** [comment]
@bgoglin Since this keeps coming up, should we put an FAQ for it somewhere? Perhaps update that warning message?

**Comment by bgoglin** [comment]
Yes, but I don't understand why this problem isn't mostly gone already. Isn't OMPI 4.0.x using the embedded hwloc 2 by default? That one doesn't need numa headers anymore. Are people explicitly requesting the use of an external hwloc, and they happen to have a 1.x?

**Comment by rhc54** [comment]
Yeah, I'm pretty sure that is what is happening - just people configuring with external packages. Remember, the distributors all package strictly with external hwloc and friends - so if people install via rpm, then that is what they get.

**Comment by ChaiBapchya** [comment]
> If OMPI is using a hwloc 1.x, make sure you have numactl developement headers installed (libnuma-dev package on Ubuntu).

Any way to verify which hwloc ver is being used?

**Comment by ChaiBapchya** [comment]
> Yeah, I'm pretty sure that is what is happening - just people configuring with external packages. Remember, the distributors all package strictly with external hwloc and friends - so if people install via rpm, then that is what they get.

what is the way to ensure 2.x hwloc is used [embedded default in openmpi 4.0+]? are we consuming from the wrong location?

**Comment by bgoglin** [comment]
Post your OMPI configure command-line to check if you're using the embedded or external hwloc (or even attach config.log). And post the output of 'dpkg -l | grep hwloc' to check which hwloc is installed by your Ubuntu. Make sure somebody else did not build/installed another hwloc somewhere else.

**Comment by ChaiBapchya** [comment]
These are set of mpi config commands in our dockerfile
```
# Install Open MPI
RUN mkdir /tmp/openmpi \
 && cd /tmp/openmpi \
 && curl -fSsL -O https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.1.tar.gz \
 && tar zxf openmpi-4.0.1.tar.gz \
 && cd openmpi-4.0.1 \
 && ./configure --enable-orterun-prefix-by-default \
 && make -j $(nproc) all \
 && make install \
 && ldconfig \
 && rm -rf /tmp/openmpi

# Create a wrapper for OpenMPI to allow running as root by default
RUN mv /usr/local/bin/mpirun /usr/local/bin/mpirun.real \
 && echo '#!/bin/bash' > /usr/local/bin/mpirun \
 && echo 'mpirun.real --allow-run-as-root "$@"' >> /usr/local/bin/mpirun \
 && chmod a+x /usr/local/bin/mpirun

# Configure OpenMPI to run good defaults:
#   --bind-to none --map-by slot --mca btl_tcp_if_exclude lo,docker0
RUN echo "hwloc_base_binding_policy = none" >> /usr/local/etc/openmpi-mca-params.conf \
 && echo "rmaps_base_mapping_policy = slot" >> /usr/local/etc/openmpi-mca-params.conf
```

I don't see any other package build/install another hwloc. 
Actually, in my nvidia-docker container
I can see openmpi but can't find hwloc
```
# mpirun --version
mpirun.real (OpenRTE) 4.0.1

Report bugs to http://www.open-mpi.org/community/help/
```

```
# dpkg -l | grep hwloc
```
Makes me question if hwloc is installed correctly or not.

**Comment by ChaiBapchya** [comment]
@bgoglin gentle ping.

**Comment by ChaiBapchya** [comment]
@bgoglin @rhc54 Any chance did you get time to look at it?

**Comment by ChaiBapchya** [comment]
I tried to install libnuma-dev in that docker container but it still throws unable to bind process error.

**Comment by rhc54** [comment]
I cannot help with the problem, but I do want to note that the message you received didn't actually say it couldn't bind the process. What it said was that it couldn't bind memory, which means that the hooks required to set the kernel's memory allocation policy such that it would ensure the memory was local to the process could not be found.

I'm not sure if you understood the difference, so I wanted to point it out. Your process is indeed being bound as requested - we just cannot ensure that any memory allocations are local to it.

**Comment by rhc54** [comment]
Closing as this doesn't seem to be a bug in OMPI so much as a limitation in Docker and/or missing required libraries.
