### ISSUE TITLE
  FCLD     libmpi_usempif08.la  ld: library not found for -lhwloc

### ISSUE THREAD

**Issue by mignonph75** [open-mpi/ompi#7818]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
4.0.4

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

from source distribution

### Please describe the system on which you are running

* Operating system/version:  macOS 10.5.5
* Computer hardware: macbook air i7 intel core (2 cores)
* Network type: non

-----------------------------

## Details of the problem

make fails

Making all in mpi/fortran/use-mpi-f08
  FCLD     libmpi_usempif08.la
ld: library not found for -lhwloc
collect2: error: ld returned 1 exit status
make[2]: *** [libmpi_usempif08.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -np 2 ./hello_world
```

**Comment by ggouaillardet** [comment]
What is your `configure` command line and which compilers (C/C++/Fortran) are you using?

**Comment by mignonph75** [comment]
configure command line ./configure was performed without options

which gcc
/usr/bin/gcc
ls -l /usr/bin/gcc
-rwxr-xr-x  1 root  wheel  31488 28 mai 01:37 /usr/bin/gcc

which gfortran
/usr/local/bin/gfortran
ls -l /usr/local/bin/gfortran
lrwxr-xr-x  1 kassad  admin  34 14 jui 21:30 /usr/local/bin/gfortran -> ../Cellar/gcc/9.3.0_1/bin/gfortran

**Comment by mignonph75** [comment]
thank you for helping

**Comment by mignonph75** [comment]
[config.log](https://github.com/open-mpi/ompi/files/4777983/config.log)

**Comment by mignonph75** [comment]
[Makefile.txt](https://github.com/open-mpi/ompi/files/4777987/Makefile.txt)

**Comment by ggouaillardet** [comment]
Is there any reason you want to use `/usr/bin/gcc` (which an apple customized `clang`)?

If you want to use GNU 9.3 compilers, you can

```
configure CC=gcc-9 CXX=g++-9
```

**Comment by ggouaillardet** [comment]
it seems the root cause is `/usr/bin/gcc` looks for libs in `/usr/local/lib` by default (and hence expect to find `libhwloc.dylib` there, but `gfortran` does not look for lib in `/usr/local/lib` and is hence unable to link with `-lhwloc`.

**Comment by mignonph75** [comment]
**with configure CC=gcc-9 CXX=g++-9**

makefile performed successfully !

thank you for helping me

**Comment by hppritcha** [comment]
Here's what I'm seeing on an aarch64 platform using gcc 9.3.0, ompi 4.0.4, and ucx 1.7:
```
PASS: ma/test-coalesce.x
PASS: ma/test-inquire.x
XFAIL: ma/testf.x
FAIL: global/testing/elempatch.x
PASS: global/testing/getmem.x
PASS: global/testing/mtest.x
PASS: global/testing/mulmatpatchc.x
PASS: global/testing/normc.x
PASS: global/testing/matrixc.x
PASS: global/testing/ntestc.x
PASS: global/testing/ntestfc.x
PASS: global/testing/packc.x
PASS: global/testing/patch_enumc.x
PASS: global/testing/print.x
PASS: global/testing/scan_addc.x
PASS: global/testing/scan_copyc.x
PASS: global/testing/testc.x
PASS: global/testing/testmatmultc.x
PASS: global/testing/testmult.x
PASS: global/testing/testmultrect.x
PASS: global/testing/gemmtest.x
PASS: global/testing/thread_perf_contig.x
PASS: global/testing/thread_perf_strided.x
PASS: global/testing/threadsafec.x
PASS: global/testing/read_only.x
PASS: global/testing/unpackc.x
PASS: global/testing/bin.x
PASS: global/testing/blktest.x
PASS: global/testing/g2test.x
PASS: global/testing/g3test.x
PASS: global/testing/ga_lu.x
PASS: global/testing/ga_shift.x
FAIL: global/testing/ghosts.x
PASS: global/testing/jacobi.x
PASS: global/testing/mir_perf2.x
PASS: global/testing/mmatrix.x
PASS: global/testing/mulmatpatch.x
PASS: global/testing/nbtest.x
PASS: global/testing/nb2test.x
PASS: global/testing/ndim.x
PASS: global/testing/patch.x
PASS: global/testing/patch2.x
PASS: global/testing/patch_enumf.x
PASS: global/testing/perfmod.x
PASS: global/testing/perform.x
PASS: global/testing/perf.x
PASS: global/testing/perf2.x
FAIL: global/testing/pg2test.x
FAIL: global/testing/pgtest.x
FAIL: global/testing/scan.x
PASS: global/testing/simple_groups.x
PASS: global/testing/sparse.x
PASS: global/testing/sprsmatmult.x
PASS: global/testing/stride.x
PASS: global/testing/testeig.x
PASS: global/testing/testmatmult.x
PASS: global/testing/testsolve.x
FAIL: global/testing/test.x
PASS: global/testing/simple_groups_comm.x
PASS: global/testing/ga-mpi.x
PASS: global/testing/lock.x
PASS: global/testing/simple_groups_commc.x
PASS: global/testing/nga-onesided.x
PASS: global/testing/nga-patch.x
PASS: global/testing/nga-periodic.x
PASS: global/testing/nga-scatter.x
PASS: global/testing/nga-util.x
PASS: global/testing/ngatest.x
PASS: global/examples/lennard-jones/lennard.x
PASS: global/examples/boltzmann/boltz.x
PASS: ga++/testing/elempatch.x
PASS: ga++/testing/mtest.x
PASS: ga++/testing/ntestc.x
PASS: ga++/testing/testc.x
PASS: ga++/testing/testmult.x
FAIL: ga++/testing/threadsafecpp.x
=================================
7 of 77 tests failed
See ./test-suite.log
Please report to hpctools@pnl.gov
=================================
```
I used the configure options given in an above comment.
I had
export OMPI_MCA_osc=ucx
export OMPI_MCA_pml=ucx
set in my shell.

**Comment by hppritcha** [comment]
sorry wrong issue.

**Comment by hppritcha** [comment]
@mignonph75 does @ggouaillardet 's solution suffice to address this issue?

**Comment by mignonph75** [comment]
Yes

**Comment by subodh-malgonde** [comment]
> it seems the root cause is `/usr/bin/gcc` looks for libs in `/usr/local/lib` by default (and hence expect to find `libhwloc.dylib` there, but `gfortran` does not look for lib in `/usr/local/lib` and is hence unable to link with `-lhwloc`.

You are right. Here is the official documentation on this issue (includes possible fixes) - [Why do I get errors about hwloc or libevent not found?](https://www.open-mpi.org/faq/?category=building#libevent-or-hwloc-errors-when-linking-fortran)
