### ISSUE TITLE
Incompatibility mpirun / xonsh (PATH modified)

### ISSUE THREAD

**Issue by paugier** [open-mpi/ompi#7832]
Sorry to post this here. I guess it is not a issue from OpenMPI, but I don't know and I don't understand what could be the issue. You may be able to provide some hints how to solve this problem.

I'm trying to use the shell xonsh and it seems that `mpirun` (Open MPI 4.0.3 on Ubuntu 20.04) prepends "/usr/bin:/usr/bin" before the PATH when launched from xonsh (and not from bash or fish).

```
$ cat print_path.sh                                                
#!/usr/bin/env bash
echo $PATH
$ $PATH = "/usr/bin:/sbin:/bin"                                    
$ ./print_path.sh                                                  
/usr/bin:/sbin:/bin
$ mpirun -np 1 ./print_path.sh                                     
/usr/bin:/usr/bin:/usr/bin:/sbin:/bin        # <- this is the problem!
$ bash                                                             
$ export PATH="/usr/bin:/sbin:/bin"
$ mpirun -np 1 ./print_path.sh
/usr/bin:/sbin:/bin
$ fish
Welcome to fish, the friendly interactive shell
~> export PATH="/usr/bin:/sbin:/bin"
~> mpirun -np 1 ./print_path.sh
/usr/bin:/sbin:/bin
```

The original xonsh issue xonsh/xonsh/issues/3617

**Comment by ggouaillardet** [comment]
That is indeed pretty odd.

in `xonsh`,  what if you replace
`mpirun -np 1 ./print_path.sh`
with
`env mpirun -np 1 ./print_path.sh`

**Comment by rhc54** [comment]
Potential problem: the rsh launcher attempts to detect the remote shell so it can adapt the cmd line used to launch the remote daemons. It doesn't know anything about `xonsh` (I've never heard of it before), and so it is likely getting confused. Not sure what precisely it would do with the path in that circumstance, but it could easily prepend the usual standard path. Solution might be simply to update that detection code to identify the new shell.

**Comment by paugier** [comment]
Yes, it is much better with env!
```
$ mpirun -np 1 ./print_path.sh                                     
/usr/bin:/usr/bin:/usr/bin:/sbin:/bin
$ env mpirun -np 1 ./print_path.sh                                 
/usr/bin:/sbin:/bin
```
I don't understand why, but at least it is a good workaround. Thanks!

**Comment by ggouaillardet** [comment]
@rhc54 the issue occurs on a single node, where `rsh` is out of the picture.

the issue/surprising behavior can be evidenced by running (under bash)

`/usr/bin/mpirun -np 1 ./print_path.sh`.

Under the hood,
`mpirun -np 1 ./print_path.sh
will result in (in `bash`)
`execve ("/usr/bin/mpirun", ["mpirun", "-np", "1", "./print_path.sh"], [...])`
but in `xonsh`
`execve ("/usr/bin/mpirun", ["/usr/bin/mpirun", "-np", "1", "./print_path.sh"], [...])`

That explains why the same command produces different results depending on which shell is used.
I will upload the xonsh ticket.

**Comment by laloch** [comment]
Thanks again for investigating the issue @ggouaillardet. I have opened xonsh/xonsh#3627 with a fix making Xonsh behave consistently with other shells. I think this `mpirun` feature should be documented on the `mpirun` man page.
