### ISSUE TITLE
About memory requirement for MPI code on LSF

### ISSUE THREAD

**Issue by yongjun67** [open-mpi/ompi#7842]
Hi experts,

When I run MPI code on LSF, how can I require memory for per-job, not per-host?
For example,
          bsub  -n 4 -R "rusage[mem=100]" myprg
The 100MB memory is per-host. How can I require total memory 400MB? Each myprg needs 100MB.

Thanks,

Yongjun

**Comment by rhc54** [comment]
You'd probably be better off asking the LSF community about that one - it's an LSF cmd line issue, not anything related to OMPI or MPI.
