### ISSUE TITLE
OFI MTL being auto-selected

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#785]
If there are no other available MTLs, the OFI MTL with the sockets provider will be selected over OB1 (and any BTLs).

This is very undesirable...

@yburette Can you have a look?

**Comment by yburette** [comment]
Yes, I bet we will get the same issue with other providers such as MXM, right?

There are two priorities schemes here:
1) between MTLs (e.g. PSM vs OFI MTLs)
2) between PMLs (e.g. OB1 vs CM PMLs)

The OFI MTL doesn't have any control on 2). CM has higher priority over OB1 if any MTL can work.
I guess the only way to fix this is to ignore the sockets OFI provider unless explicitly requested by the user with "--mca mtl_ofi_provider sockets".

@jsquyres Would this work?

**Comment by jsquyres** [comment]
Yes, this is probably a good idea -- I think the sockets OFI provider is really only intended for debugging/testing.  It's not necessarily going to give higher performance than the TCP BTL, right?

**Comment by yburette** [comment]
@jsquyres You're absolutely right, the sockets provider is mostly for testing.

I'll create a PR shortly.

**Comment by jsquyres** [comment]
This should be fixed by #788.
