### ISSUE TITLE
Failed in check-TESTS at opal_proc_table when installing on MacOSX

### ISSUE THREAD

**Issue by zhucaoxiang** [open-mpi/ompi#7864]
## Background information

* open-mpi version: v4.0.4
* Install: Homebrew/2.4.1
* Compiler: GCC/9.3.0
* Operating system/version: OSX/10.15
* Computer hardware: Intel x86-64h Haswell
* Network type: Wifi (?)

-----------------------------

## Details of the problem
Hi, I am trying to install `open-mpi` on my MacBook pro 2019. I was using `homebrew` for the installment with the compiler of `GCC/9.3.0`. I got an error at the stage of `check-TESTS` and the failing case is `opal_proc_table` with an error message of `../../config/test-driver: line 107: 40503 Bus error: 10           "$@" > $log_file 2>&1; FAIL: opal_proc_table`. 

Below is the detailed log.
```
/Library/Developer/CommandLineTools/usr/bin/make  check-TESTS
PASS: opal_bitmap
PASS: ompi_rb_tree
PASS: opal_hash_table
PASS: opal_tree
../../config/test-driver: line 107: 40503 Bus error: 10           "$@" > $log_file 2>&1
FAIL: opal_proc_table
PASS: opal_list
PASS: opal_value_array
PASS: opal_pointer_array
PASS: opal_lifo
PASS: opal_fifo
============================================================================
Testsuite summary for Open MPI 4.0.4
============================================================================
# TOTAL: 10
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See test/class/test-suite.log
Please report to http://www.open-mpi.org/community/help/
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

HOMEBREW_VERSION: 2.4.1
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: a89b56598bf2334bf53fb9e55694551ecf680916
Last commit: 33 hours ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: 8cbd98cef88481708a37bd930a77b9ae03db188b
Core tap last commit: 14 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.SlKxDkEHUE/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: 11.5
XQuartz: 2.7.11 => /opt/X11

HOMEBREW_CC: gcc-9
HOMEBREW_CXX: g++-9
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/openssl@1.1:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.15
PKG_CONFIG_PATH: /usr/local/opt/gmp/lib/pkgconfig:/usr/local/opt/isl/lib/pkgconfig:/usr/local/opt/mpfr/lib/pkgconfig:/usr/local/opt/hwloc/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/libevent/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/gcc/bin:/usr/local/opt/hwloc/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/libevent/bin:/usr/bin:/bin:/usr/sbin:/sbin

```

I also tried to switch back to using `clang` and got the same error. Besides, when I downloaded the sources of `open-mpi/4.0.4` and installed manually with `./configure CC=gcc-9 --with-hwloc=internal --with-libevent=internal && make all install`, I got the error of "not found library hwloc".

**Comment by jsquyres** [comment]
We have seen this `make check` problem before when you already have a different Open MPI installation in your PATH / LD_LIBRARY_PATH.

Can you confirm that there are no other Open MPI installations in your PATH / LD_LIBRARY_PATH?

Also, can you specify the exact command you used to homebrew install Open MPI?  When I did it on my High Sierra laptop, it installed Open MPI binaries (and therefore didn't invoke `make check`):

```
$ brew install openmpi
==> Downloading https://homebrew.bintray.com/bottles/gcc-9.3.0_1.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/57/57e53d66ad43fe05b5a2f93d6a7cfd472713
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/open-mpi-4.0.4.catalina.bottle.tar
==> Downloading from https://akamai.bintray.com/b4/b45ead03ae109edf9e21641c95936971bc26
######################################################################## 100.0%
==> Installing dependencies for open-mpi: gcc
==> Installing open-mpi dependency: gcc
==> Pouring gcc-9.3.0_1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/gcc/9.3.0_1: 1,461 files, 287.6MB
==> Installing open-mpi
==> Pouring open-mpi-4.0.4.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/open-mpi/4.0.4: 752 files, 11.3MB
Removing: /Users/jsquyres/Library/Caches/Homebrew/open-mpi--4.0.3.catalina.bottle.tar.gz... (3.3MB)
```

For your second error (about hwloc), can you provide more information?  At a minimum, we need to see the output from `configure`.  Providing all the information listed at https://www.open-mpi.org/community/help/ would be awesome.

**Comment by zhucaoxiang** [comment]
@jsquyres Thanks for your reply. That might be the reason. I installed open-mpi at the very beginning, but it was associated with `clang`. So I `brew rm open-mpi` and checked with `which mpicc` (not found). I re-installed it with the following command to enforce using `gcc-9`.
```
brew install open-mpi --build-from-source --cc=gcc-9
Warning: You passed `--cc=gcc-9`.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.

==> Downloading https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.
Already downloaded: /Users/xiaoxiayuan/Library/Caches/Homebrew/downloads/06057f5e60fea05610b6a364060522b45b5810e0c740d74ff9e10d317e6141f1--openmpi-4.0.4.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/open-mpi/4.0.4 --enable-ipv6 --with-l
==> make all
==> make check
Last 15 lines from /Users/xiaoxiayuan/Library/Logs/Homebrew/open-mpi/03.make:
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See test/class/test-suite.log
Please report to http://www.open-mpi.org/community/help/
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by zhucaoxiang** [comment]
@jsquyres When I build from the downloaded source, I used the following command.
```
./configure CC=/usr/local/bin/gcc-9 --with-hwloc=internal --with-libevent=internal && make all install
```

The error I got was
```
ld: library not found for -levent
collect2: error: ld returned 1 exit status
make[2]: *** [libmpi_usempif08.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```
I have tried different solutions searched from the internet. During the trials, I also saw errors with `hwloc` even though I explicitly enforce `--with-hwloc=internal --with-libevent=internal `.

**Comment by jsquyres** [comment]
Is there a reason you're building Open MPI from source with Homebrew rather than using the binary / already-compiled version?

I don't know why `make check` is failing in the Homebrew packaging, but it doesn't fail for me when I build Open MPI either from a git clone or a 4.0.4 tarball on my Mac, with either the MacOS gcc or the homebrew gcc-9.  So I'm not sure why the Homebrew packaged one is failing.  🤷‍♂️

In the meantime, if you're unable to build Open MPI from a tarball, the information you sent was not enough to diagnose the issue.  Please send all the build information from here: https://www.open-mpi.org/community/help/

**Comment by jsquyres** [comment]
@zhucaoxiang Ping.

**Comment by zhucaoxiang** [comment]
@jsquyres Thanks for asking. I did the last trial yesterday and it worked after I explicitly specify the `hwloc` and `libevent` path. For some reason, using `--with-hwloc=internal` or using the default searching doesn't work. One possibility is that when I was using `homebrew`, it downloads `hwloc` and `libevent` in `/usr/local/Cellar` and this confuses the code.

```
./configure --enable-mpi-cxx --with-hwloc=/usr/local --with-libevent=/usr/local CC=/usr/local/bin/gcc-9 CXX=/usr/local/bin/g++-9
```

BTW, I got one error during the configure, although it doesn't affect my installation. I am not quite sure if this would be helpful.
```
checking for objdump... objdump
checking if .note.GNU-stack is needed... /Library/Developer/CommandLineTools/usr/bin/objdump: error: 'conftest.o': Invalid/Unsupported object file format.
no
```

The `homebrew` one seems working if I export `OMPI_CC=gcc-9` and `OMPI_CXX=G++-9` after installation, but I need `C++ bindings` so I have to build it from source.

**Comment by hppritcha** [comment]
@zhucaoxiang is this still a problem?

**Comment by zhucaoxiang** [comment]
@hppritcha I haven't followed this issue. I moved away and began to use the code on my Linux cluster. You can either close this ticket or keep it as a reference. Thanks!

**Comment by xiongdawei** [comment]
> @jsquyres Thanks for asking. I did the last trial yesterday and it worked after I explicitly specify the `hwloc` and `libevent` path. For some reason, using `--with-hwloc=internal` or using the default searching doesn't work. One possibility is that when I was using `homebrew`, it downloads `hwloc` and `libevent` in `/usr/local/Cellar` and this confuses the code.
> 
> ```
> ./configure --enable-mpi-cxx --with-hwloc=/usr/local --with-libevent=/usr/local CC=/usr/local/bin/gcc-9 CXX=/usr/local/bin/g++-9
> ```
> 
> BTW, I got one error during the configure, although it doesn't affect my installation. I am not quite sure if this would be helpful.
> 
> ```
> checking for objdump... objdump
> checking if .note.GNU-stack is needed... /Library/Developer/CommandLineTools/usr/bin/objdump: error: 'conftest.o': Invalid/Unsupported object file format.
> no
> ```
> 
> The `homebrew` one seems working if I export `OMPI_CC=gcc-9` and `OMPI_CXX=G++-9` after installation, but I need `C++ bindings` so I have to build it from source.



> @jsquyres Thanks for asking. I did the last trial yesterday and it worked after I explicitly specify the `hwloc` and `libevent` path. For some reason, using `--with-hwloc=internal` or using the default searching doesn't work. One possibility is that when I was using `homebrew`, it downloads `hwloc` and `libevent` in `/usr/local/Cellar` and this confuses the code.
> 
> ```
> ./configure --enable-mpi-cxx --with-hwloc=/usr/local --with-libevent=/usr/local CC=/usr/local/bin/gcc-9 CXX=/usr/local/bin/g++-9
> ```
> 
> BTW, I got one error during the configure, although it doesn't affect my installation. I am not quite sure if this would be helpful.
> 
> ```
> checking for objdump... objdump
> checking if .note.GNU-stack is needed... /Library/Developer/CommandLineTools/usr/bin/objdump: error: 'conftest.o': Invalid/Unsupported object file format.
> no
> ```
> 
> The `homebrew` one seems working if I export `OMPI_CC=gcc-9` and `OMPI_CXX=G++-9` after installation, but I need `C++ bindings` so I have to build it from source.

May I ask how did you specify the liven path.
