### ISSUE TITLE
portals4: fix inappropriate use of abort() in mtl-portals4 and coll-portals4 components

### ISSUE THREAD

**Issue by tkordenbrock** [open-mpi/ompi#7865]
As mentioned in https://github.com/open-mpi/ompi/issues/7726, the mtl-portals4 and coll-portals4 components call abort() in their progress threads when portals4 error events are generated.  Find a friendlier way to exit.

**Comment by jsquyres** [comment]
@tkordenbrock Are you going to back port this to v4.0.x and v4.1.x?

**Comment by tkordenbrock** [comment]
@jsquyres This was back-ported in #7894 and #7895, but the issue was never closed.  Sorry about that.  Closing now.
