### ISSUE TITLE
mpiexec always reports `stdout` as a terminal

### ISSUE THREAD

**Issue by simonbyrne** [open-mpi/ompi#7868]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.0.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Homebrew on MacOS, Cluster provided version on Linux

### Please describe the system on which you are running

* Operating system/version: MacOS & Linux
* Computer hardware: x86
* Network type: n/a

-----------------------------

## Details of the problem

When launching a program under `mpiexec`, it always reports `stdout` as a terminal (`-t 1`), even when output is redirected:
```
$ mpiexec -n 1 bash -c 'if [ -t 1 ] ; then echo "terminal"; else echo "not a terminal"; fi'
terminal

$ mpiexec -n 1 bash -c 'if [ -t 1 ] ; then echo "terminal"; else echo "not a terminal"; fi' > output ; cat output
terminal

$ mpiexec --version
mpiexec (OpenRTE) 4.0.2
```

Is there an option to disable this?

**Comment by rhc54** [comment]
I've never heard of one - but a code contribution (targeting the OMPI master branch) to do so is welcome! Note that the OMPI master branch uses PRRTE (https://github.com/openpmix/prrte) as its runtime, so the patch would have to go there.
