### ISSUE TITLE
Need to explicitly set --with-hwloc=internal for successful build

### ISSUE THREAD

**Issue by rzambre** [open-mpi/ompi#7869]
## Background information

Got the following error at the end of compilation.

```
../../../opal/.libs/libopen-pal.so: error: undefined reference to 'hwloc_distances_get_by_depth'
../../../opal/.libs/libopen-pal.so: error: undefined reference to 'hwloc_distances_release'
../../../opal/.libs/libopen-pal.so: error: undefined reference to 'hwloc_topology_set_io_types_filter'
../../../opal/.libs/libopen-pal.so: error: undefined reference to 'hwloc_shmem_topology_adopt'
```

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.0.4 relase tarball

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

```
../configure --prefix=/data/homezvol2/rzambre/libraries/openmpi-4.0.4/install --with-ucx=/data/homezvol2/rzambre/libraries/ucx/install/master --enable-mca-no-build=btl-uct --without-verbs
```

### Please describe the system on which you are running

* Operating system/version: CentOS 7.7 
* Computer hardware: x86
* Network type: Mellanox IB

-----------------------------

## Details of the problem

The build successfully completes if I use `--with-hwloc=internal`. So, is this a problem of my environment or OpenMPI's build system?

**Comment by bgoglin** [comment]
Thos function are hwloc 2.x functions that are not in 1.x, hence you could be using hwloc 2.x headers with hwloc 1.x libs. Can you show how hwloc in installed on your system (which version(s) and where) and whether you specified something in the environment for hwloc include and lib path?

**Comment by jsquyres** [comment]
@bgoglin In OMPI v4.0.x, we support hwloc>=v1.5, so there's probably some missing protection of those hwloc2 functions somewhere.

**Comment by rzambre** [comment]
@bgoglin I have my own installation of hwloc-2.1.0 whose, `bin`, `lib`, `include` paths I have included in the `PATH`, `LD_LIBRARY_PATH`, `LIBRARY_PATH`, `C_INCLUDE_PATH`, and `CPLUS_INCLUDE_PATH` environment variables.

```
[rzambre@login-i15:~] $hwloc-info --version
hwloc-info 2.1.0
[rzambre@login-i15:~] $which hwloc-info
~/libraries/hwloc-2.1.0/install/bin/hwloc-info
[rzambre@login-i15:~] $printenv |grep hwloc
CPLUS_INCLUDE_PATH=/data/homezvol2/rzambre/libraries/ucx/install/master/include:/data/homezvol2/rzambre/libraries/hwloc-2.1.0/install/include:/data/homezvol2/rzambre/libraries/autotools/install/include
LIBRARY_PATH=/data/homezvol2/rzambre/libraries/ucx/install/master/lib:/data/homezvol2/rzambre/libraries/hwloc-2.1.0/install/lib:/data/homezvol2/rzambre/libraries/autotools/install/lib
LD_LIBRARY_PATH=/data/homezvol2/rzambre/libraries/ucx/install/master/lib:/data/homezvol2/rzambre/libraries/hwloc-2.1.0/install/lib:/data/homezvol2/rzambre/libraries/autotools/install/lib:/data/opt/apps/intel/2020u1/compilers_and_libraries/linux/lib/intel64:/opt/apps/gcc/8.4.0/lib64:/opt/apps/gcc/8.4.0/lib:/opt/apps/gcc/8.4.0/lib/gcc/x86_64-pc-linux-gnu/8.4.0
PATH=/data/homezvol2/rzambre/libraries/ucx/install/master/bin:/data/homezvol2/rzambre/libraries/hwloc-2.1.0/install/bin:/data/homezvol2/rzambre/libraries/autotools/install/bin:/data/opt/apps/intel/2020u1/compilers_and_libraries/linux/bin/intel64:/data/opt/apps/intel/2020u1/compilers_and_libraries/linux/bin:/opt/apps/gcc/8.4.0/bin:/data/utils/system-files/system-wide-env-setup:/usr/lib64/qt-3.3/bin:/data/homezvol2/rzambre/perl5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/dell/srvadmin/bin:/data/homezvol2/rzambre/bin
C_INCLUDE_PATH=/data/homezvol2/rzambre/libraries/ucx/install/master/include:/data/homezvol2/rzambre/libraries/hwloc-2.1.0/install/include:/data/homezvol2/rzambre/libraries/autotools/install/include
```

**Comment by bgoglin** [comment]
@jsquyres I manually verified, couldn't find any non-protected call to these functions. Do you guys still don't have a CI building OMPI on hwloc 1.x?

@rzambre Check whether there are some hwloc official packages from your distrib installed. It really seems to me you have a hwloc 1.x library somewhere that the compiler picks up first when linking. If you have updatedb, "locate libhwloc" will help. Also I hope UCX doesn't install its own hwloc (check in /data/homezvol2/rzambre/libraries/ucx/install/).

**Comment by jsquyres** [comment]
@rzambre Please send all the build information listed on https://www.open-mpi.org/community/help/

**Comment by gpaulsen** [comment]
When using your own installation of hwloc, it's best to pass the path to that into configure via `--with-hwloc=/data/homezvol2/rzambre/libraries/hwloc-2.1.0/install`.

I just tried the above with Open-MPI v4.0.x branch, and hwloc from the v1.11 tag, and it built and linked correctly on my ppc64le node.

**Comment by gpaulsen** [comment]
@rzambre, are you still able to reproduce the issue?  If not, may we close this?

**Comment by rzambre** [comment]
We can close this issue since it seems to be specific to my environment. Thank you for looking into this.
