### ISSUE TITLE
Unable to find environmental variables

### ISSUE THREAD

**Issue by liqi17thu** [open-mpi/ompi#7878]
## Details of the problem

I want to determine the local_rank and world_size using following code in python:
```
local_rank = int(os.environ.get('OMPI_COMM_WORLD_RANK') or 0)
world_size = int(os.environ.get('OMPI_COMM_WORLD_SIZE') or 1)
```
but I find those environmental variables don't exist. The default version of Open MPI is v1.10.3, so I also try to install the newest version from the source tarball, which is v4.0.4. But the environmental variables are still not set.

### Please describe the system on which you are running

* Operating system/version: Linux 16.04.5 LTS (Xenial Xerus)
* Remote Execution: Password-less SSH
* All software/homes/etc on share FileSystem

**Comment by awlauria** [comment]
What is the output when you print them? I am unable to reproduce, copying your script and running under mpirun:

```
$. ./exports/bin/mpirun -np 2 ./scipt.py 
mpirun -np 2 ./scipt.py 
local rank: 1
world size: 2
local rank: 0
world size: 2

```

**Comment by liqi17thu** [comment]
Actually I am using apex distributed data-parallel, so more complete code in script is 
```
local_rank = int(os.environ.get('OMPI_COMM_WORLD_RANK') or 0)
world_size = int(os.environ.get('OMPI_COMM_WORLD_SIZE') or 1)

torch.distributed.init_process_group(backend='nccl', init_method=dist_url, world_size=word_size,
                                                 rank=local_rank, group_name='mtorch')
gpu_id = torch.distributed.get_rank() % torch.cuda.device_count()
torch.cuda.set_device(gpu_id)
```

 Before I can simply run 
```
python script.py
```
and everything goes well. But after switching to a new public cluster it doesn't work anymore and I find the problem is above environmental variables are not set. Another issue is I am running 1 job using 2 machines, so in the past, I use OMPI_COMM_WORLD_RANK to check whether machine I am using, but now it doesn't work anymore.

**Comment by ggouaillardet** [comment]
these environment variable are set by `mpirun` or `mpiexec`. If your cluster features direct launch (e.g. `srun` or cray alps), these environment variables are not set.
is there any reason why you would not use `mpi4py` and the python equivalent of `MPI_Comm_rank()` and `MPI_Comm_size()` ?
not you might be luckier with the `PMIX_*` variables such as `PMIX_RANK`.

**Comment by liqi17thu** [comment]
I use two machines (each with 4 GPUs) to run a PyTorch-based job. I use a bash script to set up the environment and run the python script. Now two machines run the script simultaneously (before I can use OMPI_COMM_WORLD_RANK to make sure only one machine set up the environment but now it is set up twice) and two independent python jobs are launched.

**Comment by sjeaugey** [comment]
@liqi17thu are you sure you are using MPI/mpirun ? as far as I know PyTorch has its own launcher so that's likely why you are having issues.

Getting the Open MPI environment variables only works when using Open MPI.
