### ISSUE TITLE
Timer triggered checkpoint

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#79]
Per discussion on the [http://www.open-mpi.org/community/lists/users/2009/06/9772.php Users List] it would be useful to have a timer triggered checkpoint of the application.

The user could set an MCA parameter to automatically checkpoint every X minutes.

**Comment by jjhursey** [comment]
The C/R code has been removed from the current master and all current releases. I'm going to close this bug for now.

**Comment by jjhursey** [comment]
The C/R code has been removed from the current master and all current releases. I'm going to close this bug for now.
