### ISSUE TITLE
./configure step is returning "zsh: no such file or directory"

### ISSUE THREAD

**Issue by octavia-crompton** [open-mpi/ompi#7908]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.0.4

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From a source tarball

### Please describe the system on which you are running

* Operating system/version:  MacOS Catalina Version 10.15.4
* Computer hardware: MacBookPro16,1
* Network type: Wi-Fi

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -np 2 ./hello_world
```

I am trying to install ompi, but the configuration step (./configure --prefix=$MPI_DIR) is returning the error:

zsh: no such file or directory: ./configure

Is there a configuration file that I am missing?

**Comment by ggouaillardet** [comment]
what is the shell you are using when invoking `configure` ?
if `zsh`, where is `zsh` installed and what is your `$PATH` ?

**Comment by jsquyres** [comment]
Are you in the directory from the expanded Open MPI tarball when you run `./configure`?

**Comment by jsquyres** [comment]
Closing this due to no response from the submitter.
