### ISSUE TITLE
MPI_Datatype when use MPI

### ISSUE THREAD

**Issue by ahaichen** [open-mpi/ompi#7920]
Hi All,

In fortran, When `USE MPI_F08`, we can define something like 

```fortran
TYPE(MPI_Datatype) :: my_int

if(...) then
  my_int=MPI_integer4
else 
  my_int=MPI_integer8
endif
```
I am wondering if there is a way to do this when `USE MPI`.  Thanks a lot ~

**Comment by jsquyres** [comment]
My $0.02: `use mpi_f08` is *always* better than `use mpi`.  😄   `use mpi_f08` gives you distinct types for MPI handles, and `use mpi` does not.  This gives you much better protection from common programmer mistakes.

That being said, if you want the equivalent in `use mpi`, just change `type(MPI_Datatype)` to `INTEGER`.

**Comment by ahaichen** [comment]
@jsquyres sure, thanks ~
