### ISSUE TITLE
Obtaining cache line size from hwloc topo info

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7937]
Per @bosilca reporting, it looks like we might be getting the cache line size too late during the initialization process (e.g., on master, it was as late as the modex).  This might be after some parts of code may be using the cache line size before it has actually been initialized properly.

@rhc54 reports that we don't get the topology information until someone actually needs it in the v4.0.x/v4.1.x branches.

Need to investigate this and potentially fix it.

**Comment by bosilca** [comment]
Here is how I fixed it in the smcuda BTL (https://github.com/open-mpi/ompi/pull/7931/commits/fd4ca394e2400289dc46dd757a6a78caf05783be).

**Comment by bosilca** [comment]
Based on the discussion we had a the call today I looked at the usages of the opal_cache_line_size before the call to HWLOC init. With the patch above only the MPOOL tree is using it before it is set to the correct value. I can try to push the call to opal_hwloc_base_get_topology even earlier, but I still don't think this is the correct fix as we need the opal_cache_line_size to be a constant for every subsystem in OMPI/OPAL, which means we need to get the correct value extremely early, preferably in opal_init_util.

@bgoglin is there a way to extract the cache line size from HWLOC without doing the entire local topology discovery ?

**Comment by bgoglin** [comment]
@bosilca No.

**Comment by rhc54** [comment]
We can easily fix this once PMIx and HWLOC come out from under their MCA frameworks. We can immediately init PMIx in `MPI_Init` and then get the topology - just can't do that while those packages are covered by MCA as we first have to init the MCA base.

**Comment by bosilca** [comment]
This will happen to too late in the initialization process, forcing all components/framework to delay the creation of cache line dependent objects until late in the initialization process. Not very practical.

Fortunately neither PRRTE nor PMIx rely on the cache line (PRRTE defines it but never use it and the dstore framework in PMIx define its own cache line size).

Another solution would be to bring back the original mechanism to detect the cache line size (similar to the code in PMIx), and do  it very in the OPAL utils process.

**Comment by rhc54** [comment]
Given that we call `opal_init_util` from `MPI_Init`, my expectation was that we would put the call to`PMIx_Init` before that point since PMIx does not in any way rely on OPAL. We could then immediately call `get_topology` since that function (modified it to do just the minimum we need) also doesn't have any OPAL dependency. So I don't understand how that can be "too late" - nothing else will have been done yet.

**Comment by jsquyres** [comment]
Per discussion on the 21 July 2020 (some of this is a summary from above):

* This problem is in the v4.0.x and v4.1.x series
* It may also be in the 3.0.x and 3.1.x series -- we need to check.
* This is not an issue on master; there's a different code path on master and we have hwloc data available earlier.
* This is a correctness issue: at time X, we use cache line size A, and at time Y (where X>Y), we use cache line size B.
    * This is because at time X, we use the fixed value of 128, and at time Y, we use the actual cache line size from hwloc.
* This is problematic in some cases that cause correctness issues (e.g., CUDA support in smcuda).
* The fix George put in earlier is not sufficient.
* We probably need to make an OPAL function that gets the cache line size and is always safe to call (i.e., doesn't read it from the hwloc data).  We can probably steal this code from PMIX dstore -- @bosilca points out that this code area has the syscalls/sys file reads/ioctls/etc. that are needed for portability.
    * @bosilca says he can look into this.
    * @janjust is also going to ask internally in NVIDA to see if we can get some help, since this affects CUDA

**Comment by gpaulsen** [comment]
Worked around for v4.0.5 with https://github.com/open-mpi/ompi/pull/8009

**Comment by gpaulsen** [comment]
Worked around for v4.1.0 with https://github.com/open-mpi/ompi/pull/8006.

Still hoping for a fix for master / v5.0.0

**Comment by rhc54** [comment]
> Still hoping for a fix for master / v5.0.0

Not sure I understand - from comments above, we already have a fix for master - yes? Once the configure separation is complete, it is trivial to obtain the hwloc data as early as desired.

**Comment by bwbarrett** [comment]
@rhc54 Yes, master is currently correct (because it has the same 128 padding in the internal structures as the release branches).  We do still have the lurking problem of having a cache line size constant in OPAL that isn't constant.  We should clean that up, before it trips someone else up.  Options include setting the cache line size to -1 or some absurd value until it is filled in, making the cache line size a helper function that properly initializes or errors rather than returning a default, or something we haven't thought of yet.  But we should remove that sharp edge before we cut ourselves again.

**Comment by rhc54** [comment]
@bwbarrett Do you have a sense as to when you will push the fix to the configure logic (moving hwloc, pmix, and libevent to the project level) branch? Soon as that happens, I can easily ensure that the OPAL cache line is set at the beginning of time.

**Comment by gpaulsen** [comment]
@rhc54 Has this been fixed in master yet?

**Comment by rhc54** [comment]
Not yet

**Comment by gpaulsen** [comment]
This is a blocker for v5.0.0 release.  Can anyone please assign themselves so we know someone is working on this?

**Comment by rhc54** [comment]
Done - pretty trivial, as noted above.

**Comment by gpaulsen** [comment]
thanks!
