### ISSUE TITLE
Launch using srun results in an error in MPI_Init

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#7949]
@bertwesarg and I are experiencing an issue when launching applications built against Open MPI 4.0.4 using the srun command. The error we get is:

```
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
```

I can launch the same application using `mpirun` without problems. `configure` was called with `--with-ucx --enable-debug --with-slurm` and the final output of `configure` acknowledges that support for SLURM is enabled.

Any idea where to start here? What knobs do I need to turn to get some more useful information? I tried enabling some verbose settings with the following:

```
$ OMPI_MCA_ess_base_verbose=100 OMPI_MCA_ras_base_verbose=100 srun -n 1 -N 1 ./a.out
```

Trying to step through `ompi_mpi_init` with a debugger I can see that the call to `ompi_rte_init` fails. From it I see the following output:

```
mca: base: components_register: registering framework ess components
mca: base: components_register: found loaded component pmi
mca: base: components_register: component pmi has no register or open function
mca: base: components_open: opening ess components
mca: base: components_open: found loaded component pmi
mca: base: components_open: component pmi open function successful
mca:base:select: Auto-selecting ess components
mca:base:select:(  ess) Querying component [pmi]
mca:base:select:(  ess) Query of component [pmi] set priority to 35
mca:base:select:(  ess) Selected component [pmi]
```

This doesn't seem to be terribly helpful (to me at least). Any help would be more than welcome.

**Comment by rhc54** [comment]
The problem is that you (a) didn't configure OMPI to support Slurm's PMI libraries instead of PMIx, and (b) didn't tell `srun` to use Slurm's PMIx support when launching the job, assuming Slurm was configured with PMIx.

**Comment by rhc54** [comment]
I suppose one could add a "timeout" to the PMIx init code...?

We don't auto-build against Slurm PMI libs for legal reasons as those libs are GPL - we require that the person building OMPI take responsibility for any licensing issues that result from linking code against OMPI when it is built in a GPL-included mode.

**Comment by devreal** [comment]
> I suppose one could add a "timeout" to the PMIx init code...?

I'm not sure the issue I'm seeing was a timeout issue. The call to `ompi_rte_init` seems to fail immediately. I was thinking along the lines of "PMIx failed to communicate with SLURM resource scheduler, consider building against PMI libs". Not sure that can be auto-detected but it would have been helpful ^^

> We don't auto-build against Slurm PMI libs for legal reasons as those libs are GPL - we require that the person building OMPI take responsibility for any licensing issues that result from linking code against OMPI when it is built in a GPL-included mode.

That is indeed tragic, but understandable.

**Comment by devreal** [comment]
Closing as it was resolved by adding `--with-pmi=/usr --with-pmi-libdir=/usr/lib64` to `configure`
