### ISSUE TITLE
Question: obtain/specify the memory alignement in MPI_Win_allocate and MPI_Alloc_mem

### ISSUE THREAD

**Issue by thomasgillis** [open-mpi/ompi#7955]
Thank you for taking the time to answer my question

## My question:
I am using `MPI_Win_allocate` to allocate RMA memory.
I need to access it using a standard for loop and I would like to help its vectorization.
Therefore I wish to inform the compiler about the alignment of the memory, allocated using `MPI_Win_allocate`.

I have then two associated questions:
- is it possible to retrieve the alignment of the memory (using a function, I can always compute it afterward of course)? The ideal situation would be to have a macro for it.
- is it possible to request a given alignment when using `MPI_Win_allocate` and/or `MPI_Alloc_mem`? Of course, compatibility with the MPI internal alignment has to be ensured.

-> I use Open MPI v4.0.3

**Comment by devreal** [comment]
@thomasgillis Unfortunately, MPI 3.1 had no guarantee on alignment and/or any facility to query or control the alignment of window memory. However, MPI 4.0 will provide info keys for `MPI_Alloc_mem` and `MPI_Win_allocate` to hint at a desired alignment. I don't think this has been implemented in Open MPI but I take this issue as a reminder to implement this feature soon.

For the time being, you can allocate aligned memory using `posix_memalign` and create the window using `MPI_Win_create`. That may negatively impact performance implications for on-node communication but should give you the same performance for inter-node communication IIRC.

**Comment by thomasgillis** [comment]
@devreal thank you for your feedback!

I saw recently that the standard MPI-4 is not complete yet
Do you have an estimated time of arrival for its implementation? 2022?

**Comment by devreal** [comment]
IIRC, the 4.0 standard is slated for publication by the end of this year / early next year. I started looking into implementing this and hope to put up a PR early August.

**Comment by devreal** [comment]
@thomasgillis Support or the `mpi_minimum_alignment` info key has been merged into `master` and will be part of the 5.0 release (https://github.com/open-mpi/ompi/pull/7985). Does that solve your issue? Can we close this ticket?

**Comment by thomasgillis** [comment]
Yes! Thx a lot.
