### ISSUE TITLE
opal_info_get: why use memcpy without range check?

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#7961]
I just found that `opal_info_get` indiscriminately copies `valuelen` bytes of an info key using `memcpy`, even if that ~key~ value is shorter. This seems to run counter to what the documentation states:

```C
/**
 *   Get a (key, value) pair from an 'MPI_Info' object
 *
 *   @param info Pointer to opal_info_t object
 *   @param key null-terminated character string of the index key
 *   @param valuelen maximum length of 'value' (integer)
 *   @param value null-terminated character string of the value
 *   @param flag true (1) if 'key' defined on 'info', false (0) if not
 *               (logical)
 *
 *   @retval OPAL_SUCCESS
 *
 *   In C and C++, 'valuelen' should be one less than the allocated
 *   space to allow for the null terminator.
 */
OPAL_DECLSPEC int opal_info_get (opal_info_t *info, const char *key, int valuelen,
                                 char *value, int *flag);
```

The way I read this is that  `valuelen` is the upper bound for the space in `value`, i.e., it is ok if the `value` is shorter. Plus, the `value` will be null-terminated.

 I then found that `opal_info_get_bool` does not check for the length of the value before calling `opal_info_get`, effectively copying 256B of memory, of which the majority is likely uninitialized (and valgrind indeed complains about it).

So I wonder:
1) Is my reading of the interface definition correct?

2)  Why is `memcpy` used here (instead of `strncpy` or `opal_string_copy`)? Interestingly, the comment in `opal_info_get_nolock` states that this is unsafe (but given the note on C/C++ in the interface documentation using `opal_string_copy` *should* be safe):

```C
        // Note: we copy exactly (valuelen) characters, because that's
        // what the caller asked for.  Don't use opal_string_copy()
        // here, because that will guarantee to \0-terminate what is
        // copied (i.e., potentially copy (valuelen-1) chars and then
        // an additional \0).  Instead: copy over exactly (valuelen)
        // characters, and if that's not \0-terminated, then so be it.
        memcpy(value, search->ie_value, valuelen);
```
    So is the reason that `opal_string_copy()` would do the right thing (TM)?

3) Is that really a sound interface if even a function implemented in the same file uses it in the wrong way?

**Comment by devreal** [comment]
Digging deeper into this, it seems that almost all users of `opal_get_info` (or `ompi_get_info`) expect the documented behavior, allocating some buffer whose size is independent of the actual value length and then passing that size (often `-1`, but not always) to `opal_info_get`.

There is at least one place that is broken: https://github.com/open-mpi/ompi/blob/master/ompi/mca/fs/lustre/fs_lustre_file_open.c#L72 where a string of size `MPI_MAX_INFO_KEY` (currently 36) is allocated but the size of `MPI_MAX_INFO_VAL` (currently 1024) is passed as the length, potentially resulting in memory corruption.

I propose to change the implementation of `opal_info_get` to follow the documented behavior, including the expectation that the value buffer has space for `valuelen+1`  chars and using `opal_string_copy` to ensure null-termination using that additional character if needed. Plus, checking all users of `[opal|ompi]_info_get` for correct use. Unless there are objections I will post a PR in the coming weeks.

We may want consider a function such as `opal_info_get_strdup` which simply calls `strdup` on the stored value and passes ownership of the resulting buffer to the caller. That would avoid allocating 1k buffers on the stack of the caller and/or the snake pit of proper C string termination but would involve some dynamic memory management (not sure that is relevant as info key handling is usually not in the critical path and the allocations are small).

**Comment by bosilca** [comment]
I think a lot of issues in there were inherited from a time when the info was only used in the MPI layer, with data with a fixed length, and with possible uses from Fortran (which explain the memcpy instead of strcopy). However, taking in account that we now set the value with opal_string_copy (in opal_info_set_nolock), we should be able to copy it out using the same function (or we will copy uninitialized/incorrect  data).

I don't think opal_info_get_strdup is a good idea for 2 reasons: 1) we don't want the upper level to be able to alter the content of an info ever, 2) this functions should be called outside the critical path.

**Comment by devreal** [comment]
Fixed by https://github.com/open-mpi/ompi/pull/8330, closing.
