### ISSUE TITLE
Segfault when calling MPI_Compare_and_swap

### ISSUE THREAD

**Issue by navigatore** [open-mpi/ompi#7967]
## Runtime environment

* OpenMPI version: 4.0.4 (installed from distribution package)
* GCC version: 10.1.0 (installed from distribution package)
* Operating system: Arch Linux
* CPU: AMD Ryzen 7 3700X
* Network type: N/A

-----------------------------

## Details of the problem

When running _locally_ [this simple program](https://gist.github.com/navigatore/9e8d3a555ca8f365f056798960027fc4) there is segfault when calling MPI_Compare_and_swap function. Such behavior is observable every time when using at least two processes and 64-bit wide datatype. Everything looks fine if I use only a single process or when the used datatype is smaller than 64-bit. Maybe this issue is related to #7027.

### Console output
Below is the console output from an example run of the aforementioned program:

```
$ mpirun -c 2 ./a.out 
[ryzen:05454] *** Process received signal ***
[ryzen:05454] Signal: Segmentation fault (11)
[ryzen:05454] Signal code: Address not mapped (1)
[ryzen:05454] Failing at address: 0x7fa9840fb2e8
[ryzen:05455] *** Process received signal ***
[ryzen:05455] Signal: Segmentation fault (11)
[ryzen:05455] Signal code: Address not mapped (1)
[ryzen:05455] Failing at address: 0x7efe3ae5b2f0
[ryzen:05454] [ 0] /usr/lib/libpthread.so.0(+0x14960)[0x7efe40e20960]
[ryzen:05454] [ 1] /usr/lib/openmpi/openmpi/mca_btl_vader.so(+0x6f97)[0x7efe3ae38f97]
[ryzen:05454] [ 2] /usr/lib/openmpi/openmpi/mca_btl_vader.so(mca_btl_vader_poll_handle_frag+0x91)[0x7efe3ae368e1]
[ryzen:05454] [ 3] /usr/lib/openmpi/openmpi/mca_btl_vader.so(+0x4d95)[0x7efe3ae36d95]
[ryzen:05454] [ 4] /usr/lib/openmpi/libopen-pal.so.40(opal_progress+0x2c)[0x7efe40afb19c]
[ryzen:05454] [ 5] /usr/lib/openmpi/openmpi/mca_osc_rdma.so(ompi_osc_rdma_compare_and_swap+0x30e)[0x7efe3a7ad6ae]
[ryzen:05454] [ 6] [ryzen:05455] [ 0] /usr/lib/libpthread.so.0(+0x14960)[0x7fa9854bf960]
[ryzen:05455] [ 1] /usr/lib/openmpi/openmpi/mca_btl_vader.so(+0x6f97)[0x7fa9840d8f97]
[ryzen:05455] /usr/lib/openmpi/libmpi.so.40(PMPI_Compare_and_swap+0xe6)[0x7efe40ec03b6]
[ryzen:05454] [ 7] ./a.out(+0x12a5)[0x560a7e0672a5]
[ryzen:05454] [ 8] [ 2] /usr/lib/openmpi/openmpi/mca_btl_vader.so(mca_btl_vader_poll_handle_frag+0x91)[0x7fa9840d68e1]
[ryzen:05455] [ 3] /usr/lib/openmpi/openmpi/mca_btl_vader.so(+0x4d95)[0x7fa9840d6d95]
[ryzen:05455] [ 4] /usr/lib/libc.so.6(__libc_start_main+0xf2)[0x7efe40c6c002]
[ryzen:05454] [ 9] ./a.out(+0x10ee)[0x560a7e0670ee]
[ryzen:05454] *** End of error message ***
/usr/lib/openmpi/libopen-pal.so.40(opal_progress+0x2c)[0x7fa98519a19c]
[ryzen:05455] [ 5] /usr/lib/openmpi/openmpi/mca_osc_rdma.so(ompi_osc_rdma_compare_and_swap+0x30e)[0x7fa97ee486ae]
[ryzen:05455] [ 6] /usr/lib/openmpi/libmpi.so.40(PMPI_Compare_and_swap+0xe6)[0x7fa98555f3b6]
[ryzen:05455] [ 7] ./a.out(+0x12a5)[0x55d1383c92a5]
[ryzen:05455] [ 8] /usr/lib/libc.so.6(__libc_start_main+0xf2)[0x7fa98530b002]
[ryzen:05455] [ 9] ./a.out(+0x10ee)[0x55d1383c90ee]
[ryzen:05455] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node ryzen exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

### Faulty addresses

From my experiments with a bit more complicated examples it looked like the faulty address a program is trying to access is either `0x150` or the address of the end of the allocated window (it was true even if the window was significantly bigger and I was trying to CAS only single 64-bit wide value with displacement equal to 0).

**Comment by bosilca** [comment]
This seems to have been fixed in both master and the upcoming 4.1. Following the trail of #7113, I confirm that cherry-picking 02dd877d into 4.0.x series fixes this issue.

**Comment by navigatore** [comment]
I compiled current master and indeed the problem with segfaults disappeared. Good to know that it is fixed already - I'm closing this issue.

**Comment by devreal** [comment]
Sorry, must have missed to backport that patch back then. Thanks @bosilca for investigating. Will post a PR to 4.0.x once I confirmed it applies cleanly and builds correctly.

**Comment by devreal** [comment]
Should be fixed through https://github.com/open-mpi/ompi/pull/7969 (not sure why it didn't auto-close the issue)
