### ISSUE TITLE
Oversubscribe fails during shared memory initialization

### ISSUE THREAD

**Issue by jarrah42** [open-mpi/ompi#7971]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.0.4

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

`brew install openmpi`

### Please describe the system on which you are running

* Operating system/version: macOS 10.15.5 (Catalina)
* Computer hardware: Mac Mini
* Network type: N/A

-----------------------------

## Details of the problem

Using a trivial hello world MPI program:

```
$ mpirun -np 8 --oversubscribe  ./x
hi from 0 (8)
hi from 2 (8)
hi from 1 (8)
hi from 3 (8)
hi from 4 (8)
hi from 5 (8)
hi from 6 (8)
hi from 7 (8)
--------------------------------------------------------------------------
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  macmini
  System call: unlink(2) /var/folders/rt/wcyvxs8j70g_1s95hc64g_z40000gq/T//ompi.macmini.503/pid.79258/1/vader_segment.macmini.27680001.6
  Error:       No such file or directory (errno 2)
--------------------------------------------------------------------------
[macmini:79258] 1 more process has sent help message help-opal-shmem-mmap.txt / sys call fail
[macmini:79258] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
$
```

Without oversubscribe (with or without `--oversubscribe` option):

```
$ mpirun -np 4 --oversubscribe  ./x
hi from 3 (4)
hi from 0 (4)
hi from 1 (4)
hi from 2 (4)
$
```

**Comment by ggouaillardet** [comment]
That can happen if the filename gets truncated.
try
`export TMPDIR=/tmp`
before calling `mpirun`

**Comment by jarrah42** [comment]
That does appear to work around the issue. It should really be fixed so that mpirun works out of the box.

**Comment by rhc54** [comment]
I would welcome any suggestions on how one might do that - the root cause is Apple's decision to move the default TMPDIR to a very long named location. I cannot think of any way we could just arbitrarily pick some other spot without potentially causing problems for the system.

**Comment by alexmechanic** [comment]
@rhc54 is it really that long that MPI path addition makes it overflow? Mine TMPDIR was `/var/folders/_m/yw88_yxx41d4wz7c36zzvq_h0000gn/T/`, which is 49 chars, which is, IMO, is definitely not "a very long named location" that can lead MPI runtime to fail (except library path var is limited to char[255], but in that case MPI could produce path suffix >= 206 chars, which is also questioning design).
Could you introduce into the issue a bit deeper with that context?

**Comment by jsquyres** [comment]
@alexmechanic Open MPI makes a hierarchy of folders under the tmpdir, some of which have long names, themselves.  This is what leads the filename limit to get longer than whatever the filesystem limit is.

**Comment by alexmechanic** [comment]
> @alexmechanic Open MPI makes a hierarchy of folders under the tmpdir, some of which have long names, themselves. This is what leads the filename limit to get longer than whatever the filesystem limit is.

Well, that makes more sense now. And hence, being said you know exactly the reason of the issue, what is preventing from adding: simple path length check to produce exact and meaningful error message about the known and trackable path issue?

Don't get we wrong, I do not argue with source of the issue, I do not understand why the issue source in known, this ticket is closed, but nobody tried to make anything to get user correct information when this issue comes out. Instead, their only choice is Googling and prey they come to this ticket at last.
