### ISSUE TITLE
I can't install open-mpi

### ISSUE THREAD

**Issue by Mateusf31** [open-mpi/ompi#7976]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
Open-MPI v4.0.4

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
I am trying to install and configure the mpi with intel fortran. I used these commands: ./configure --prefix=/usr/local/ F77=/home/mateus/intel/bin/ifort FC=/home/mateus/intel/bin/ifort F90=/home/mateus/intel/bin/ifort

### Please describe the system on which you are running

* Operating system/version: 
[config.log](https://github.com/open-mpi/ompi/files/5004098/config.log)
* Computer hardware: Intel i3 3110M 4GB
* Network type: LAN

-----------------------------

## Details of the problem

I installed intel fortran and tried to set the open-mpi settings to use ifort, when I try to install open-mpi it stops at the following excerpt:
+++ Configuring MCA framework hwloc
checking for no configure components in framework hwloc... 
checking for m4 configure components in framework hwloc... external, hwloc201

--- MCA component hwloc:external (m4 configuration macro, priority 90)
checking for MCA component hwloc:external compile mode... static
checking --with-hwloc-libdir value... simple ok (unspecified value)
checking looking for external hwloc in... ()
checking hwloc.h usability... no
checking hwloc.h presence... no
checking for hwloc.h... no
checking if MCA component hwloc:external can compile... no

--- MCA component hwloc:hwloc201 (m4 configuration macro, priority 80)
checking for MCA component hwloc:hwloc201 compile mode... static
checking if hwloc external component succeeded... no
configure: hwloc:external failed, so this component will be used
checking hwloc building mode... embedded
configure: hwloc builddir: /home/mateus/Área de Trabalho/openmpi-4.0.4/opal/mca/hwloc/hwloc201/hwloc
configure: hwloc srcdir: /home/mateus/Área de Trabalho/openmpi-4.0.4/opal/mca/hwloc/hwloc201/hwloc
checking for hwloc version... ./configure: line 82222: /home/mateus/Área: No such file or directory
configure: error: Cannot continue

**Comment by rhc54** [comment]
This is likely the problem: `Área de Trabalho` has spaces in the pathname. I'm willing to bet that HWLOC's configure script doesn't handle that well. Try putting OMPI somewhere that doesn't have spaces in the pathname.

**Comment by bgoglin** [comment]
@rhc54 Indeed, I can fix this specific error, but libtool warns anyway, so I am not sure it's worth enforcing this to work.
configure: WARNING: Libtool does not cope well with whitespace in `pwd`

**Comment by rhc54** [comment]
@bgoglin I wouldn't bother - as you note, libtool doesn't like it, nor does autoconf in many cases. Even if you did make it work for HWLOC, I suspect the configure would just fail somewhere else.
