### ISSUE TITLE
mca comm_method needs docs / CI test for v5.0

### ISSUE THREAD

**Issue by gpaulsen** [open-mpi/ompi#7987]
https://github.com/open-mpi/ompi/pull/5507 brought in a cool new feature we want to talk about for v5.0

TO do so, we need to advertise the mca parameter in our FAQ, and other docs as appropreate.
Also the commit message says that `-mca comm_method 1` should be how we enable this feature, but it appears that when it was reworked, the mca parameter changed, and was not updated.

We should also create a few simple tests in https://github.com/open-mpi/ompi-tests to exercise this code.

**Comment by awlauria** [comment]
@markalle is this resolved or does it still need to be documented?

**Comment by wenduwan** [comment]
`comm_method` is not documented yet.
