### ISSUE TITLE
Issue with external libpmix and libevent(-2.0)

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#7990]
I am trying to build the latest `master` on Red Hat 7.8 with external PMIx (to get Open MPI work with the SLURM installation). 

Trying to point `configure` to the pmix libraries first:

```
$ ../configure CC=gcc CXX=g++ FC=gfortran --with-ucx=/home/jschuch/opt/ucx-1.8.0/  --with-pmix=/usr --with-pmix-libdir=/usr/lib64
[...]
checking for MCA component pmix:external compile mode... static
configure: WARNING: EXTERNAL PMIX SUPPORT REQUIRES USE OF EXTERNAL LIBEVENT AND HWLOC
configure: WARNING: LIBRARIES. THESE LIBRARIES MUST POINT TO THE SAME ONES USED
configure: WARNING: TO BUILD PMIX OR ELSE UNPREDICTABLE BEHAVIOR MAY RESULT
configure: error: PLEASE CORRECT THE CONFIGURE COMMAND LINE AND REBUILD
```

Looking at the libraries libpmix is linked against, I see:

```
$ ldd /usr/lib64/libpmix.so
	libevent-2.0.so.5 => /lib64/libevent-2.0.so.5 (0x00007f19717e6000)
	libhwloc.so.5 => /lib64/libhwloc.so.5 (0x00007f19713a6000)
[...]
```

So I tried to point configure to these libraries:

```
$ ../configure CC=gcc CXX=g++ FC=gfortran --with-ucx=/home/jschuch/opt/ucx-1.8.0/  --with-pmix=/usr --with-pmix-libdir=/usr/lib64 --with-hwloc=/usr --with-hwloc-libdir=/usr/lib64 --with-libevent=/ --with-libevent-libdir=/lib64
[...]
--- MCA component event:external (m4 configuration macro, priority 90)
checking for MCA component event:external compile mode... static
checking --with-libevent-libdir value... not found
configure: WARNING: Expected file /lib64/libevent.* not found
configure: error: Cannot continue
```

Note that configure is looking for `libevent.so` but the file present is `libevent-2.0.so.5`:

```
$ ls /lib64/libevent*
/lib64/libevent-2.0.so.5       /lib64/libevent_core-2.0.so.5.1.9   /lib64/libevent_openssl-2.0.so.5      /lib64/libevent_pthreads-2.0.so.5.1.9
/lib64/libevent-2.0.so.5.1.9   /lib64/libevent_extra-2.0.so.5      /lib64/libevent_openssl-2.0.so.5.1.9
/lib64/libevent_core-2.0.so.5  /lib64/libevent_extra-2.0.so.5.1.9  /lib64/libevent_pthreads-2.0.so.5
```

Is that a weird configuration quirk on that system? Right now, I cannot tell whether that libevent was installed by the admins or comes out of a package. Is there a workaround available?

**Comment by ggouaillardet** [comment]
Open MPI needs the `devel` package in order to build Open MPI

(e.g. `libevent-devel` provides `libevent.so` (probably in `/usr/lib64`) and the header files (e.g. `/usr/include/event/event.h`)

I suggest you double check the `libevent-devel` package is installed (and `rpm -ql libevent-devel` will list the files it is made of)

**Comment by devreal** [comment]
Thanks, I send a request to the administrators for the devel packages...

**Comment by rhc54** [comment]
FWIW: you don't need to build OMPI with the same PMIx that was used for Slurm - PMIx maintains cross-version compatibility. You should be able to simply build OMPI with its internal PMIx and use it that way, avoiding the need for external libevent and hwloc.
