### ISSUE TITLE
OpenMPI 4.0.4 fails with LSF in distributed mode on a Power9 system

### ISSUE THREAD

**Issue by milancurcic** [open-mpi/ompi#8000]
Thank you for taking the time to submit an issue!

## Background information

Hi OpenMPI,

I'm building OpenMPI with IBM Advance Toolchain (gcc-8.3.1 fork) on a Power9 HPC system. I'm able to run in parallel on a single node, however I get an error trying to run on multiple nodes using the LSF scheduler. Details below.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.0.4 (release tarball).

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From a source/distribution tarball.

### Please describe the system on which you are running

* Operating system/version: 

```
$ cat /proc/version 
Linux version 4.14.0-115.el7a.ppc64le (mockbuild@ppc-055.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)) #1 SMP Tue Sep 25 12:28:39 EDT 2018
```

* Computer hardware:  [Triton](https://ccs.miami.edu/resources/compute-systems) at the University of Miami. IBM Power9/Nvidia Volta – 6 Racks, IBM declustered storage – 2 Racks, 96 IBM Power 9 servers.

* Network type: Unknown. How can I find out?

-----------------------------

## Details of the problem

Here's my error message when trying to run a parallel program on more than 1 node:

```
[t080:01876] [[3290,0],0] ORTE_ERROR_LOG: The specified application failed to start in file plm_lsf_module.c at line 347
--------------------------------------------------------------------------
The LSF process starter (lsb_launch) failed to start the daemons on
the nodes in the allocation.
 Returned : -1
 lsberrno : (16) Unknown user

This may mean that one or more of the nodes in the LSF allocation is
not setup properly. Below is a list of the 1 nodes that were passed
to lsb_launch:
t083
--------------------------------------------------------------------------
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[3290,0],0] FORCE-TERMINATE AT (null):1 - error plm_lsf_module.c(380)

This is something that should be reported to the developers.
--------------------------------------------------------------------------
```

And here's my LSF submit script:

```
#!/bin/bash
#BSUB -J mpi_latency
#BSUB -o log.out
#BSUB -e log.err
#BSUB -W 0:01
#BSUB -q normal
#BSUB -n 80
#BSUB -R "span[ptile=40]"
#BSUB -P paris

mpiexec mpi_latency
```

The program runs correctly if I run it on up to 40 processes (single node). As soon as I try to move to a distributed memory run, I get the error message above.

The LSF is (I think) the IBM's fork:

```
$ env | grep LSF
LSF_SERVERDIR=/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/etc
LSF_LIBDIR=/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/lib
LSF_BINDIR=/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/bin
LSF_ENVDIR=/opt/ibm/lsfsuite/lsf/conf
```

Here's some mpicc and compiler info:

```
$ mpicc --show
gcc -I/home/mcurcic/opt/openmpi-4.0.4_at-12.0/include -pthread -Wl,-rpath -Wl,/home/mcurcic/opt/openmpi-4.0.4_at-12.0/lib -Wl,--enable-new-dtags -L/home/mcurcic/opt/openmpi-4.0.4_at-12.0/lib -lmpi
$ mpicc --version | head -1
gcc (GCC) 8.3.1 20190304 (Advance-Toolchain-at12.0) [revision 269374]
```

Here's the preamble of my config.log:

```
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by Open MPI configure 4.0.4, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --with-lsf=/opt/ibm/lsfsuite/lsf/10.1 --with-lsf-libdir=/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/lib --prefix=/home/mcurcic/opt/openmpi-4.0.4_at-12.0

## --------- ##
## Platform. ##
## --------- ##

hostname = login1
uname -m = ppc64le
uname -r = 4.14.0-115.el7a.ppc64le
uname -s = Linux
uname -v = #1 SMP Tue Sep 25 12:28:39 EDT 2018

/usr/bin/uname -p = ppc64le
/bin/uname -X     = unknown

/bin/arch              = ppc64le
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/mcurcic/opt/openmpi-4.0.4_at-12.0/bin
PATH: /home/mcurcic/opt/htop-2.2.0/bin
PATH: /share/apps/at-12.0/hdf5/1.8.16/lib
PATH: /share/apps/at-12.0/hdf5/1.8.16/bin
PATH: /opt/at12.0/bin
PATH: /opt/at12.0/sbin
PATH: /usr/bin
PATH: /opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/etc
PATH: /opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/bin
PATH: /opt/ibm/lsfsuite/ext/ppm/10.2/bin
PATH: /opt/ibm/lsfsuite/ext/ppm/10.2/linux2.6-glibc2.3-ppc64le/bin
PATH: /usr/local/bin
PATH: /usr/local/sbin
PATH: /usr/sbin
PATH: /opt/ibutils/bin
PATH: /bin
PATH: /usr/lpp/mmfs/bin
PATH: /opt/ibm/jre/bin
PATH: /home/mcurcic/.local/bin
PATH: /home/mcurcic/bin
```

A sysadmin suggested configuring OpenMPI with explicit LSF library flags, however this didn't make a difference in behavior, so I  assume that configure was finding them automatically.

Perhaps noteworthy is that the config.log reports that lsb_launch couldn't be found:

```
configure:194470: checking for library containing lsb_launch
configure:194501: gcc -o conftest -O3 -DNDEBUG -fsigned-char -finline-functions -fno-strict-aliasing -pthread -I/home/mcurcic/install/openmpi-4.0.4/opal/mca/event/libevent2022/libevent -I/home/mcurcic/install/openmpi-4.0.4/opal/mca/event/libevent2022/libevent/include -I/home/mcurcic/install/openmpi-4.0.4/opal/mca/hwloc/hwloc201/hwloc/include -DNO_WARN_X86_INTRINSICS  -I/opt/ibm/lsfsuite/lsf/10.1/include   -L/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/lib conftest.c -lnsl -lrt -lm -lutil  -lz  >&5
/share/compilers/ibm/at12.0/bin/../lib/gcc/powerpc64le-linux-gnu/8.3.1/../../../../powerpc64le-linux-gnu/bin/ld: /tmp/cc4qYf1F.o: in function `main':
conftest.c:(.text.startup+0x14): undefined reference to `lsb_launch'
collect2: error: ld returned 1 exit status
```

I'm out of ideas and so is the sysadmin. Do you have any hints on how I could debug this further or a specific way to configure OpenMPI for this system?

Thank you!

**Comment by jjhursey** [comment]
This part of the error message seems to indicate that it is an LSF issue and not necessarily MPI
```
The LSF process starter (lsb_launch) failed to start the daemons on
the nodes in the allocation.
 Returned : -1
 lsberrno : (16) Unknown user
```

Under the hood Open MPI uses the LSF blaunch API to start the daemons on the compute nodes. I would start by getting an allocation and trying a `blaunch hostname` to see if that works. If it doesn't then you will need to look at the LSF setup. If it does work then we can look a bit deeper into how Open MPI is calling it.

As a short term workaround, you can try using ssh.rsh launching instead of LSF launching by specifying the `--mca plm rsh` parameter to `mpirun`.

**Comment by gpaulsen** [comment]
@milancurcic Did you determine the source of your issue?  Can we close this Open-MPI ticket?

**Comment by milancurcic** [comment]
Thank you @jjhursey and @gpaulsen. Yes, I think it can be closed. I didn't find a solution, but the sysadmin urged me to move away from trying to get this to work (unsupported by the vendor). They agreed it looked like an LSF issue.
