### ISSUE TITLE
Singleton execution fails with pmix3x component in combination with srun --mpi=none

### ISSUE THREAD

**Issue by bartoldeman** [open-mpi/ompi#8004]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
v4.0.3, compiled from source code with internal PMIx 3.1.5, Slurm PMI-2 support, but NO PMI-1 support, so the pmix s1 component is missing.

### Please describe the system on which you are running

* Operating system/version: CentOS Linux release 7.7.1908 (Core)
* Computer hardware: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
* Network type: Infiniband controller: Mellanox Technologies MT27800 Family [ConnectX-5]

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

when running in a salloc session (with `SallocDefaultCommand=\"srun -n1 -N1 --mem-per-cpu=0 --pty --preserve-env --mpi=none bash\"`) running either singleton `./hello` or `srun -n 1 --mpi=none ./hello` gives the following output:

```
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[blg4115.int.ets1.calculquebec.ca:127416] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

expected output:
```
Hello world from processor blg4115.int.ets1.calculquebec.ca, rank 0 out of 1 processors
```

The following are all workarounds:
* compile and use the PMI-1 component (but I'd like to avoid that since the libslurm dependency is annoying)
* use `srun -n 1 ./hello` (which then implies --mpi=pmix_v3 in our configuration)
* use `mpirun -n 1 ./hello`
* use `unset SLURM_STEP_ID && ./hello`
* use `unset SLURM_NODELIST && ./hello`
so there are many workaround but I'd expect a simple `./hello` to work out of the box in such a scenario too.

```
#include <mpi.h>
#include <stdio.h>

int main(int argc, char** argv) {
    // Initialize the MPI environment
    MPI_Init(NULL, NULL);

    // Get the number of processes
    int world_size;
    MPI_Comm_size(MPI_COMM_WORLD, &world_size);

    // Get the rank of the process
    int world_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

    // Get the name of the processor
    char processor_name[MPI_MAX_PROCESSOR_NAME];
    int name_len;
    MPI_Get_processor_name(processor_name, &name_len);

    // Print off a hello world message
    printf("Hello world from processor %s, rank %d out of %d processors\n",
           processor_name, world_rank, world_size);

    // Finalize the MPI environment.
    MPI_Finalize();
}
```

**Comment by rhc54** [comment]
This has been fixed in the OMPI master and v5 branches, with v5 scheduled for release in the near future. Unfortunately, there are no plans to backport those fixes to earlier releases. In the interim, you are welcome to use a nightly tarball from either of those branches (https://www.open-mpi.org/nightly/).
