### ISSUE TITLE
Move treematch support to v3.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#804]
This is a ticket to ensure that we don't forget to move treematch over to v2.x when it has soaked on master long enough.

**Comment by jsquyres** [comment]
@bosilca Looks like this was addressed in #725 -- is treematch complete on v2.0.0 / should we close this issue?

**Comment by bosilca** [comment]
No, nothing has been moved into the 2.x yet. I assign this issue to me, so that I can keep track of it.

**Comment by hppritcha** [comment]
should the milestone for this issue be moved to v2.x?

**Comment by jsquyres** [comment]
at this point, I think so.

**Comment by bosilca** [comment]
I can create the PR now, but I was waiting for a decent period of time with this on master before.

**Comment by jsquyres** [comment]
Your call.  If you think it's ready for v2.0.0, cool.  If you want to wait until v2.1.0, that's fine too.

**Comment by bosilca** [comment]
it is gaining traction, I would rather prefer to have it in the official release, so that people will get access to it by default.

**Comment by hjelmn** [comment]
@bosilca Has this been done?

**Comment by bosilca** [comment]
Still work in progress.

**Comment by jsquyres** [comment]
Moved to v3.0.0.

**Comment by jsquyres** [comment]
Looks like this was done.
