### ISSUE TITLE
Incorrect reduction with op avx and dtype "overflow"

### ISSUE THREAD

**Issue by vspetrov** [open-mpi/ompi#8045]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
master and v4.1.x

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
v4.1.x gitclone (abfc6ba) with ucx pml

### Please describe the system on which you are running
RH7.6, x86, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz

-----------------------------

## Details of the problem
Test: 2 ranks Allreduce, with "short" dtype, and "SUM" op, where the result of the reduction overflows the short type.
```
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>

#define COUNT 8
/* #define VALUE 16383 // PASS */
#define VALUE 16384 //FAIL

int main(int argc, char** argv) {
    short sbuf[COUNT], rbuf[COUNT];
    short correct = VALUE + VALUE;
    int rank, i;
    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    for(i=0; i<COUNT; i++){
            sbuf[i] = VALUE;
    }
    MPI_Allreduce(sbuf, rbuf, COUNT, MPI_SHORT, MPI_SUM, MPI_COMM_WORLD);
    for(i=0; i<COUNT; i++) {
        if(rbuf[i] != correct) {
            printf("Incorrect value at %d: rbuf %hd, correct %hd\n",
                   i, rbuf[i] , correct);
            break;
        }
    }
    MPI_Finalize();
    return 0;
}
```

Run on 2 ranks, 1 node:
```
mpirun -np 2  --map-by core -mca coll ^hcoll  ./repro 8
Incorrect value at 0: rbuf 32767, correct -32768
Incorrect value at 0: rbuf 32767, correct -32768
```

Same run w/o "op avx" passes:
```
mpirun  -mca op ^avx -np 2  --map-by core -mca coll ^hcoll  ./repro 8
```

The test would also pass if in the code above the VALUE is 16383, so that there is no SHORT type overflow during MPI_SUM.

**Comment by devreal** [comment]
Signed integer overflow is undefined behavior in C, MPI and/or the compiler could do anything. IIRC, @bosilca mentioned that AVX has overflow behavior that is different from non-AVX instructions.

**Comment by vspetrov** [comment]
@devreal yes, makes sense. thanks.

**Comment by vspetrov** [comment]
@devreal the same reproduces for "unsigned short". Shouldn't it just wrap around or is it "undef" as well?

**Comment by bosilca** [comment]
Yes, ops with all types will generate overflow. Why are you defining which way to handle overflow is valid ? We can argue that the way AVX handle overflow is more coherent, adding something over the MAX value will not change that value, so one might figure out that it reached the type upper bound.

All overflow operations are handled differently with AVX. The MPI standard does not mandate how overflow is to be handled, which means as long as we are consistent across operations (and we are), the answer is valid.

**Comment by vspetrov** [comment]
@bosilca (asking for my understanding) what does MPI spec say about the overflow of unsigned int? Should it be the same as C standard (ie, wrap around to zero) or it is also undefined in MPI spec? 
Does this mean, that AVX does not confirm to C standard for unsigned types?

**Comment by bosilca** [comment]
I was not aware that the C language mandate a specific behavior, and a quick search seems to confirm that it does not in fact standardize the outcome for integer types despite the fact that many programmers incorrectly assume a wrap-around due to the two's complement arithmetic (https://www.gnu.org/software/autoconf/manual/autoconf-2.64/html_node/Integer-Overflow-Basics.html).

On the MPI standard, the overflow is never mentionned for anything else than address computations, and there the behavior is undefined. MPI should remain neutral from binding to a particular language, or it will be a mess to transpose that behavior to a different language. Based on all this I think it is an incorrect user behavior to rely on a specific outcome for overflow, in which case the AVX overflow approach is as good as any other.

**Comment by gpaulsen** [comment]
@vspetrov Can we close this as undefined behavior?

**Comment by jsquyres** [comment]
I agree with @bosilca.  The behavior is undefined, so we should close this issue.
