### ISSUE TITLE
AVX fails to compile with gcc <= v6

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#8046]
Cisco is seeing AVX compile failures when gcc is <= v6: https://mtt.open-mpi.org/index.php?do_redir=3264

It would probably be easiest to just disable AVX support if the compiler is too old / does not support whatever is needed.  I.e., it's probably not worth adding workarounds to make older versions of gcc work with the AVX component.

**Comment by bosilca** [comment]
It only tries to build the AVX and AVX2 version of the ops, which seems reasonable. The same compiler was able, during configure, to compile and build an executable using the load/store instructions corresponding to the same subset of vector instructions (CPUID flag AVX2), but then it fails to find the math and bit operations.

Please check in the output.log what is says about the AVX/AVX2 detection.

**Comment by bosilca** [comment]
@jsquyres are you still seeing these failures or can we close this issue ?

**Comment by jsquyres** [comment]
Works now!  Closing.
