### ISSUE TITLE
Bring over Fortran MPI_Status conversion function fixes to v4.1.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#8047]
Bring over #7762 and #8043 to the v4.1 branch.

I marked this as "minor" because although technically it's a bug in MPI conformance, this bug has been un-noticed -- for years -- in both Open MPI and MPICH.  So it's definitely not too important.

But OTOH, it should be simple cherry-picks from master to v4.1.x.  Hopefully, it's easy to do.

**Comment by jsquyres** [comment]
@ggouaillardet Do you have a little time to try to do this, perchance?

**Comment by ggouaillardet** [comment]
This is simple if we first cherry-pick 98bc7af7d4dce3fe9106ffff39c0b129b9466d40 (change the definition of `type(MPI_Status)` in `use-mpi-f08`).

I cannot remember what we decided about that
 - this breaks ABI, so no backport
 - the code is broken, so breaking ABI is a lesser evil here

If we choose not to backport the type definition change, we would have reimplement the conversion subroutine
(no more `memcpy()` ...). That's not rocket science, but a bit time consuming.

can you please advise on how you want to move forward?
(I should be able to find some time next week)

**Comment by jsquyres** [comment]
Excellent point -- I forgot about the ABI-breaking stuff.  Thanks for the reminder.

Let's not bring this over to v4.1.x, then.  We only found this bug by an internal audit, not a real MPI code -- this is pretty low priority.  We'll let it all be fixed in v5.0.
