### ISSUE TITLE
prted.o: undefined reference to symbol 'event_priority_set'

### ISSUE THREAD

**Issue by sbromberger** [open-mpi/ompi#8064]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
Trying to compile ompi `08f68671dbc807c5d6199c3c45622969393b510c` on Raspberry Pi 4 running Ubuntu 20.04 LTS
`libevent-dev/focal,now 2.1.11-stable-1 arm64` installed via `apt`

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
`autogen.jl` followed by `./configure --prefix /usr/local`

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
```
seth@red:~/tmp/ompi master $ git submodule status
 4a43c39c89037f52b4e25927e58caf08f3707c33 opal/mca/hwloc/hwloc2/hwloc (hwloc-2.1.0rc2-53-g4a43c39c)
 415a4e34869ad0430ac7af7ff04a3520370aa59e opal/mca/pmix/pmix4x/openpmix (v1.1.3-2466-g415a4e34)
 c75d9767728337eb55e0e4b7e826177022514985 prrte (dev-30690-gc75d976772)
```

### Please describe the system on which you are running
Ubuntu 20.04 LTS running on
Raspberry Pi aarch64
1G Ethernet 

-----------------------------

## Details of the problem
after `autogen.pl`, I ran `./configure --prefix=/usr/local`. The build failed with
```shell
make[3]: Leaving directory '/nfs/auto/home/seth/tmp/ompi/prrte/src/mca/state/prted'
Making all in tools/prted
make[3]: Entering directory '/nfs/auto/home/seth/tmp/ompi/prrte/src/tools/prted'
  CC       prted.o
prted.c: In function ‘main’:
prted.c:412:9: warning: ignoring return value of ‘pipe’, declared with attribute warn_unused_result [-Wunused-result]
  412 |         pipe(wait_pipe);
      |         ^~~~~~~~~~~~~~~
  CCLD     prted
/usr/bin/ld: prted.o: undefined reference to symbol 'event_priority_set'
/usr/bin/ld: /lib/aarch64-linux-gnu/libevent_core-2.1.so.7: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:893: prted] Error 1
make[3]: Leaving directory '/nfs/auto/home/seth/tmp/ompi/prrte/src/tools/prted'
make[2]: *** [Makefile:1824: all-recursive] Error 1
make[2]: Leaving directory '/nfs/auto/home/seth/tmp/ompi/prrte/src'
make[1]: *** [Makefile:857: all-recursive] Error 1
make[1]: Leaving directory '/nfs/auto/home/seth/tmp/ompi/prrte'
make: *** [Makefile:1537: all-recursive] Error 1
```

**Comment by ggouaillardet** [comment]
@rhc54 This is a genuine issue that is evidenced by the Ubuntu linker.

it seems there is something wrong with the glue:
Open MPI uses the external libevent, but prrte is configured to use Open MPI `event.h`

here is the snippet from `config/ompi_setup_prrte.m4`

```
       if test -z $with_libevent || test "$with_libevent" = "internal" || test "$with_libevent" = "yes"; then
            opal_prrte_libevent_arg="--with-libevent-header=$OMPI_TOP_SRCDIR/opal/mca/event/event.h"
        else
            if test "$with_libevent" = "external"; then
                opal_prrte_libevent_arg="--with-libevent"
            else
                opal_prrte_libevent_arg="--with-libevent=$with_libevent"
            fi
        fi
```

IIRC, on the `master` branch, we now only uses the internal libevent if Open MPI is explicitly configured with `--with-libevent=internal`, in that case, should the first test be changed to `if test "$with_libevent" = "internal"`

**Comment by ggouaillardet** [comment]
@sbromberger Thanks for the bug report!

Meanwhile, you can `configure --with-libevent=external ...` to work around this issue.

**Comment by rhc54** [comment]
All of that configure code is being redone by @bwbarrett

**Comment by ggouaillardet** [comment]
@bwbarrett one more datapoint

Though I still think we should explicitly `-levent` when linking `prted` when an external `libevent` is used, I noted a different `libtool` behavior between CentOS8 and Ubuntu 20.4

on CentOS8
```
$ make V=1
/bin/sh ../../../libtool  --tag=CC   --mode=link gcc  -DNDEBUG -O3 -fvisibility=hidden -finline-functions -fno-strict-aliasing -mcx16 -pthread   -o prted prted.o /home/gilles/build/ompi/opal/libopen-pal.la    ../../../src/libprrte.la -lm -lutil  -lz  
libtool: link: gcc -DNDEBUG -O3 -fvisibility=hidden -finline-functions -fno-strict-aliasing -mcx16 -pthread -o .libs/prted prted.o  ../../../src/.libs/libprrte.so /home/gilles/build/ompi/opal/.libs/libopen-pal.so -ldl -lrt -levent_core -levent_pthreads -lm -lutil -lz -pthread -Wl,-rpath -Wl,/usr/local/lib
```

on ubuntu
```
$ make V=1
/bin/bash ../../../libtool  --tag=CC   --mode=link gcc  -DNDEBUG -O3 -fvisibility=hidden -finline-functions -fno-strict-aliasing -mcx16 -pthread   -o prted prted.o /home/gilles/build/ompi/opal/libopen-pal.la    ../../../src/libprrte.la -lm -lutil   
libtool: link: gcc -DNDEBUG -O3 -fvisibility=hidden -finline-functions -fno-strict-aliasing -mcx16 -pthread -o .libs/prted prted.o  /home/gilles/build/ompi/opal/.libs/libopen-pal.so ../../../src/.libs/libprrte.so -lm -lutil -pthread
/usr/bin/ld: prted.o: undefined reference to symbol 'event_priority_set'
/usr/bin/ld: /lib/x86_64-linux-gnu/libevent_core-2.1.so.7: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:893: prted] Error 1
```

we do not `-levent` on CentOS nor ubuntu, but only on CentOS, `libtool` passed `-levent_core -levent_pthreads` to the link command line (I guess because these are dependencies from `libopen-pal.la`)

both `libopen-pal.la` are identical, except one was generated with libtool `2.4.6` and the other with `2.4.6 Debian-2.4.6-14`

```
$ cat /home/gilles/build/ompi/opal/libopen-pal.la
# libopen-pal.la - a libtool library file
# Generated by libtool (GNU libtool) 2.4.6
#
# Please DO NOT delete this file!
# It is necessary for linking the library.

# The name that we can dlopen(3).
dlname='libopen-pal.so.0'

# Names of this library.
library_names='libopen-pal.so.0.0.0 libopen-pal.so.0 libopen-pal.so'

# The name of the static archive.
old_library=''

# Linker flags that cannot go in dependency_libs.
inherited_linker_flags=' -pthread'

# Libraries that this one depends upon.
dependency_libs=' -ldl -lrt -lm -lutil -levent_core -levent_pthreads'

# Names of additional weak libraries provided by this library
weak_library_names=''

# Version information for libopen-pal.
current=0
age=0
revision=0

# Is this an already installed library?
installed=no

# Should we warn about portability when linking against -modules?
shouldnotlink=no

# Files to dlopen/dlpreopen
dlopen=''
dlpreopen=''

# Directory that this library needs to be installed in:
libdir='/usr/local/lib'
```

**Comment by bwbarrett** [comment]
@rhc54 tagged me because he would really like me to post a PR from https://github.com/bwbarrett/ompi/tree/feature/3rdparty-packaging and clean up some of these issues that way.

@ggouaillardet your callouts are all correct, from a certain point of view.  The event header relocation is because of the way Open MPI currently integrates Libevent.  We did not want the `ev_` symbols in the libmpi.so namespace, so there are `#define`s to change them to `opal_ev_`, which means that PRRTE needs those symbols mangled as well.  Hence, the weird include.

It does look like we have a problem with including the right libevent in some situations when an external libevent is used with PRRTE.  This isn't worth fixing in the existing infrastructure.  I need to post a PR from the above mentioned patch so that we get out of some of the games.

**Comment by sbromberger** [comment]
Thank you all for the very quick response and interesting discussion. I'm giving `--with-libevent=external` a try now and will update once I have results.

**Comment by sbromberger** [comment]
It compiled and installed, but I'm still getting some errors that seem to be related:
```
+seth@red:~ $ ls -l `which mpirun`
lrwxrwxrwx 1 root root 4 Sep 28 18:04 /usr/local/bin/mpirun -> prte*
+seth@red:~ $ ls -l /usr/local/bin/prte
-rwxr-xr-x 1 root root 63200 Sep 28 18:04 /usr/local/bin/prte*
+seth@red:~ $ /usr/local/bin/prte 
/usr/local/bin/prte: error while loading shared libraries: libprrte.so.2: cannot open shared object file: No such file or directory
```

This is after I tried `mpirun ./mpi_test`. `mpi_test.c` contains
```
#include <stdio.h>
#include <unistd.h>
#include <mpi.h>
int main(int argc, char** argv){
    int node;
    char hostname[1024];
    hostname[1023] = '\0';
    gethostname(hostname, 1023);
    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &node);
    printf("Hello World from Node %d, hostname %s!\n", node, hostname);
    MPI_Finalize();
}
```

and running it by itself (after `mpicc -o mpi_test mpi_test.c` yields:
```

+seth@red:~ $ ./mpi_test
[red.c.net:880805] mca_base_component_repository_open: unable to open mca_pml_monitoring: libmca_common_monitoring.so.0: cannot open shared object file: No such file or directory (ignored)
[red.c.net:880805] mca_base_component_repository_open: unable to open mca_coll_monitoring: libmca_common_monitoring.so.0: cannot open shared object file: No such file or directory (ignored)
[red.c.net:880805] mca_base_component_repository_open: unable to open mca_coll_sm: libmca_common_sm.so.0: cannot open shared object file: No such file or directory (ignored)
[red.c.net:880805] mca_base_component_repository_open: unable to open mca_osc_monitoring: libmca_common_monitoring.so.0: cannot open shared object file: No such file or directory (ignored)
Hello World from Node 0, hostname red.c.net!
```

Unsure what to do here.

**Comment by bwbarrett** [comment]
The real fix is in https://github.com/open-mpi/ompi/pull/8069.

**Comment by sbromberger** [comment]
Thanks, @bwbarrett - I can certainly wait a bit if #8069 is going to be merged soon, and I'm happy to provide results when it is.

**Comment by ggouaillardet** [comment]
@sbromberger try `export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` and see if it helps.

IIRC, Open MPI assumes `/usr/local/lib` is in the default search path and does not add it via the `-rpath` option to the linker.

**Comment by sbromberger** [comment]
@ggouaillardet that did it. Thanks. Is there a way to rebuild it so I won't need to change `LD_LIBRARY_PATH`?

**Comment by ggouaillardet** [comment]
A simple option is to install Open MPI in a different location
(e.g. `configure --prefix=/opt/openmpi ...`)

You can also add `/usr/local/lib` to your search path
(as root, add `/usr/local/lib` to `/etc/ld.so.conf` and run `ldconfig`)

You might also force that via the `configure` command line (I did not test it though)
`configure LDFLAGS=-Wl,-rpath,/usr/local/lib ...`

**Comment by sbromberger** [comment]
This is perfect. Thank you:

```
+seth@red:~ $ mpirun -H orange,red ./mpi_test
Hello World from Node 1, hostname red.c.net!
Hello World from Node 0, hostname orange.c.net!
```

**Comment by sbromberger** [comment]
Should I close this out, or is there followup activity required to get this working generally?

**Comment by bwbarrett** [comment]
I think we've resolved these issues in master with some recent (1 week ago) changes.  Can you try again and see if it works out of the box now?

**Comment by rhc54** [comment]
Please reopen if you continue to see the problem.
