### ISSUE TITLE
`MPI_Wait` does not terminate for cancelled requests

### ISSUE THREAD

**Issue by SpinTensor** [open-mpi/ompi#8078]
Hi all,

## Background information
I am running the system Openmpi version 4.0.3 on ubuntu 20.04.1 LTS, normally installed via `apt install libopenmpi-dev`. gcc version is system internal version 9.3.0.
Everything runs on my one workstation on one Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz CPU with 16GiB Memory. So no communication via some fabric.

-----------------------------

## Details of the problem

Here is a small test code:
```
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv) {
   MPI_Init(&argc, &argv);
   int comm_size;
   MPI_Comm_size(MPI_COMM_WORLD, &comm_size);
   int my_rank;
   MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);

   int nints = 65536;
   int* sbuffer = (int*) malloc(nints*sizeof(int));

   if (my_rank == 0) {
      int flag;
      MPI_Request myrequest;
      MPI_Status mystatus;
      printf("Sending message from rank %d to rank %d\n", my_rank, 1); 
      MPI_Irsend(sbuffer, nints, MPI_INT, 1, 0, MPI_COMM_WORLD, &myrequest);
      MPI_Request_get_status(myrequest, &flag, &mystatus);
      printf("Request status flag = %s\n", flag ? "true" : "false");
      printf("Canceling\n");
      MPI_Cancel(&myrequest);
      printf("Canceled\n");
      MPI_Request_get_status(myrequest, &flag, &mystatus);
      printf("Request status flag = %s\n", flag ? "true" : "false");
      MPI_Test_cancelled(&mystatus, &flag);
      printf("Test cancelled flag = %s\n", flag ? "true" : "false");
      printf("Starting Wait\n");
      MPI_Wait(&myrequest, &mystatus);
      printf("Finished Wait\n");
   }   

   free(sbuffer);
   sbuffer=NULL;

   MPI_Finalize();

   return 0;
}
```
Compilation with `mpicc -o test test.c`
Execution with `mpirun -np 2 ./test`

In the code process 0 starts a non-blocking send to process 1 and cancels it immediately with `MPI_Cancel`.
Then the cancelled communication is finished with an `MPI_Wait`.
Process 1 does basically nothing.
Note that there is no matching receive on process 1.

The program outputs:
```
Sending message from rank 0 to rank 1
Request status flag = false
Canceling
Canceled
Request status flag = false
Test cancelled flag = true
Starting Wait
```
and then hangs indefinitely in the `MPI_Wait`. 
According to the output the communication is never finished (as expected) and then is cancelled sucessfully (as expected). The standard (MPI 3.1 Section 3.8.4 Cancel) states (that "It is still necessary to call `MPI_REQUEST_FREE`, `MPI_WAIT` or `MPI_TEST` or any of the derived operations) with the cancelled request as argument after the call to `MPI_CANCEL`".
I suspect something is wrong in the interaction of cancel and wait.

Another curiosity I found with the same code is if `nints = 1` is set.
Then the program output is:
```
Sending message from rank 0 to rank 1
Request status flag = true
Canceling
Canceled
Request status flag = true
Test cancelled flag = false
Starting Wait
Finished Wait
```
As you can see the first call to `MPI_Request_get_status` states that the communication is finished although there is no matching receive on process 1. 
Subsequently the `MPI_Cancel` fails to cancel the job (as expected if the communication is completed.). The `MPI_Wait` is executed without any problem and the program terminates.
I suspect, that the message is so small that it gets copied in some buffer and and then considered completed. With the larger message the buffer is probably to small to hold the complete message.
I explicitly selected `MPI_Irsend` to send the message, because I don't want the message to be delivered in this test. The standard states (MPI 3.1 Section 3.7 Nonblocking Communication) "A nonblocking **ready** send can be started only if a matching receive is posted.

Would be nice if someone could have look at it. 

Thanks and best regards,
Felix

**Comment by awlauria** [comment]
Hi, thanks for the report. Can you post the output of:

`mpirun --version` ?

**Comment by SpinTensor** [comment]
Hi, thanks for the quick reply. Here is the output:

```
mpirun (Open MPI) 4.0.3

Report bugs to http://www.open-mpi.org/community/help/
```

**Comment by bosilca** [comment]
There are several issues here.
1. the ready send should not have been used without an already posted receive. As defined by the standard in the section you pointed, the ready should not be started without a posted recv, but not by the MPI library, but by the user. Thus, your example is technically incorrect. OMPI is too lax and transform the ready send into a normal send instead of waiting for confirmation from the peer and raising an error if the receive request has not been already posted.
2. You should have used a synchronous send instead of the ready send, as the synchronous send will confirm the posted receive.
3. a send can be cancelled but in very rare conditions. The next version of the MPI standard will clarify this, and remove support for cancel for all send operations.

I checked your example with OB1 PML and the cancelled status remains unset, which is the correct behavior. You might use the default UCX PML, and you have identified an incorrect handling of the cancel there.

**Comment by SpinTensor** [comment]
Hi, 
thanks for investigating and pointing out the issues. Regarding the Irsend I must have misinterpreted the standard. Thanks for correcting me, I learned something new :).
I checked the 4.0 standard draft and indeed the the MPI_Cancel is marked deprecated. Therefore, I think it is not necessary to investigate further, and I will close this issue.
Thanks and best regards,
Felix
