### ISSUE TITLE
monitoring component traces or timestamp?

### ISSUE THREAD

**Issue by ericalinsync** [open-mpi/ompi#8084]
I've been using the monitoring component (by using --mca pml_monitoring_enable 2) in v.4.0.3 and was wondering, is it possible to get timestamp information or traces of the messages using the monitoring component?

**Comment by bosilca** [comment]
The monitoring components only deliver aggregated information about the different types of communications (pt2pt, collective, one sided). For more detailed information about messages you should take a look at the PERUSE support in OMPI, and maybe to the more recent MPI_T events.
