### ISSUE TITLE
mpiexec on FreeBSD cloud system fails when opmi_hosts 

### ISSUE THREAD

**Issue by qkoziol** [open-mpi/ompi#8097]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

% /usr/local/mpi/openmpi/bin/mpirun --version
mpirun (Open MPI) 4.0.5

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

FreeBSD ports system

### Please describe the system on which you are running

* Operating system/version: FreeBSD 12.1
* Computer hardware: Some cloud VM that probably isn't easy to figure out (let me know if this is important)
* Network type: Good question, difficult to figure out easily right now.

-----------------------------

## Details of the problem

I'm setting up a FreeBSD system in the cloud to run HDF5 tests on, etc.    I received the following error during that process.

#**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```
/usr/local/mpi/openmpi/bin/mpiexec --prefix /usr/local/mpi/openmpi --hostfile opmi_hosts -np 6 ./t_mpi
--------------------------------------------------------------------------
Open RTE was unable to open the hostfile:
    opmi_hosts
Check to make sure the path and filename are correct.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[28733,0],0] FORCE-TERMINATE AT (null):1 - error base/ras_base_allocate.c(352)

This is something that should be reported to the developers.
--------------------------------------------------------------------------```

**Comment by hppritcha** [comment]
If you give a fully qualified path to the hostfile and see if that works?

**Comment by hppritcha** [comment]
oh also check the hostfile name.

**Comment by rhc54** [comment]
Please reopen if that didn't fix the problem.
