### ISSUE TITLE
TCP BTL timeouts

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#81]
Cisco and Mellanox have done some testing and found that in some cases, the TCP BTL can report errors (this is from OMPI v1.3.3):

```
[svbu-mpi044][[55297,1],7][btl_tcp_frag.c:216:mca_btl_tcp_frag_recv] mca_btl_tcp_frag_recv: readv failed: Connection timed out (110)
```

We're not sure where the error lies yet; here seem to be the conditions that are necessary to reproduce the error:
- Running on 10G (1G appears to work fine).  Cisco has reproduced the error on Chelsio hardware; Mellanox has reproduced on multiple different 10G vendor NICs.
- Run the IMB 3.2 benchmarks in a loop (default runs; give no command line parameters to IMB); the error occurs somewhere after 12 hours of running.
- np=16, ppn=4, tcp+self BTL (no need for sm).

This error is reproducible in the 1.2 series, the 1.3 series, and the SVN trunk.

The fact that this error takes 12+ hours to occur (and many IMB runs) seems to imply that this is likely an OS / driver issue.  But the fact that it happens on multiple vendor NICs seems to imply that it's a race condition in OMPI that happens so infrequently that it takes many runs to occur.  Mellanox did MPICH2 runs on the same hardware that experienced the OMPI failure for about 24 hours and did not run into any problems.  This also points to the possibility of the problem being in OMPI.

So -- we don't know yet where the error is occurring.  We're still investigating.

**Comment by jsquyres** [comment]
This is super stale; I'm closing.
