### ISSUE TITLE
Question: measuring MPI launching and running performance with VMs/Containers as an alternative

### ISSUE THREAD

**Issue by jma562** [open-mpi/ompi#8100]
Thank you for taking the time to submit an issue!

## Background information
I plan to do some tests on large MPI job launching and running performance (e.g., hundreds to thousands  of nodes).
Without an actual environment that consists of such a large number of physical servers,  I'd like to find a reliable way to measure the performance metrics using VMs or containers. 

I understand that using VMs/containers, one of the key factors of performance: the network latency cannot be fully simulated.

I'm wondering if anyone has ever done similar measurement before on VMs/Containers and reliably mapped the results to the results generated in an environment of actual physical servers. 

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
Open MPI V4.0.4

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Source tar ball

### Please describe the system on which you are running

* Operating system/version: Centos 
* Computer hardware: X86
* Network type: Ethernet

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

As described above, it's a question. I'm looking for advices.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -np 2 ./hello_world
```

**Comment by ggouaillardet** [comment]
This is not an Open MPI related question.

Maybe https://simgrid.org meets your requirements.
