### ISSUE TITLE
MPI_T_pvar_get_index misbehaving?

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#812]
[Per the discussion on the devel mailing list](http://www.open-mpi.org/community/lists/devel/2015/08/17747.php), it looks like MPI_T_pvar_get_index() might be misbehaving...?

Here's @bosilca's reproducer:

```c
    err = MPI_T_pvar_get_num(&numPvar);
    if(err) MPI_Abort(MPI_COMM_WORLD, 0);
    printf("%d MPI Performance Variables\n", numPvar);

    for(i = 0; i < numPvar; i++) {
      nameLen = sizeof(name);
      descLen = sizeof(desc);
      err = MPI_T_pvar_get_info(i, name, &nameLen, &verbosity,
                                &varClass, &datatype, &enumtype, desc,
                                &descLen, &binding, &isReadonly,
                                &isContinous, &isAtomic);
      if( (MPI_SUCCESS != err) && (MPI_T_ERR_INVALID_INDEX != err) ) {
        printf("Failed to read Pvar %d/%d\n", i, numPvar);
        MPI_Abort(MPI_COMM_WORLD, 0);
      }
      printf("\t%s\tClass-%d\tBinding-%d\tReadonly-%s\tContinous-%s\tAtomic-%s\t%s\n",
             name, varClass, binding, isReadonly ? "T" : "F",
             isContinous ? "T" : "F", isAtomic ? "T" : "F", desc);
      err = MPI_T_pvar_get_index(name, binding, &pvar_idx);
      if (err != MPI_SUCCESS) {
        printf("cannot find %s pvar\n", name);
        MPI_Abort(MPI_COMM_WORLD, 0);
      }
      if( pvar_idx != i )
        printf("This is weird (%d != %d)!\n", pvar_idx, i);
    }
```

**Comment by hjelmn** [comment]
I will double-check with the tools working group. My interpretation is that when a variable goes away MPI_T_pvar/cvar_get_info can return an error. The caller should ignore the error and move on.

I might be wrong though given that there is an example in the standard that stops reading variables as soon as soon as one of the info functions returns an error.

**Comment by hjelmn** [comment]
I can very quickly modify the get_info code to return variable info for variables that have gone away.

**Comment by hjelmn** [comment]
Looks like the behavior in Open MPI is indeed correct. Closing.

**Comment by jijo733** [comment]
MPI_T_pvar_get_index() returns ZERO for all valid variable names.
