### ISSUE TITLE
Documentation: MPI_Win_attach is not collective

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#8137]
Parts of the man page of `MPI_Win_attach` seem to be a verbatim copy of `MPI_Win_create` and states that this is a collective operation, which in case of `MPI_Win_attach` it is not. See: https://github.com/open-mpi/ompi/blob/master/ompi/mpi/man/man3/MPI_Win_attach.3in#L71

This should be fixed to reflect the actual behavior of `MPI_Win_attach` and should also contain at least a sentence on `MPI_Win_detach`.

**Comment by jsquyres** [comment]
@devreal Got a few minutes to write a sentence about this?  😄

**Comment by devreal** [comment]
I'll post a fix tomorrow, yes :)

**Comment by hppritcha** [comment]
@devreal reminder to post a fix for this doc issue

**Comment by devreal** [comment]
PRs have been merge:

- master: https://github.com/open-mpi/ompi/pull/8625
- 5.0.x: https://github.com/open-mpi/ompi/pull/8644
- 4.0.x: https://github.com/open-mpi/ompi/pull/8646

Waiting to be merged:
- 4.1.x: https://github.com/open-mpi/ompi/pull/8645

**Comment by jsquyres** [comment]
Thanks for the reminder on the v4.1.x -- merged.
