### ISSUE TITLE
-rpath -Wl,/usr/lib64 in wrapper linker_flag when libevent in system space. 

### ISSUE THREAD

**Issue by Nortamo** [open-mpi/ompi#8141]
## Background information

Similar to #7580 which was solved in #7656.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

- openmpi-4.0.5 release tarball from <https://www.open-mpi.org/software/ompi/v4.0/>

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

- directly installed from the tarball. 

```wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.5.tar.gz
   tar -xvf openmpi-4.0.5.tar.gz
   cd openmpi-4.0.5 
   ./configure --with-libevent=/usr
```

### Please describe the system on which you are running

* Operating system/version: RHEL 7.7 
* Computer hardware:  Xeon Gold 6230 (cascade lake)
* Network type: Mellanox HDR InfiniBand
* Compiler: gcc-9.1.0 and pgi-20.9 both produce the same behavior. 

Same behavior is also produced on a laptop (centos 7.8.2 , intel i7-6600U )  using gcc 8.3.0

-----------------------------

## Details of the problem

When configuring openmpi with `./configure --with-libevent=/usr` the `<wrapper_name>-wrapper-data.txt.` files
, and consequently the mpi wrappers contain `-rpath -Wl,/usr/lib64`.   

This causes issues when mpic++  is used to compile c++ code which is not compatible with the system `libstdc++.so`
as the wrapper rpath modification precedes any rpath modifications passed to the wrapper on the command line.

Not that severe as one can just edit the generated `wrapper-data.txt` file or do some `LD_PRELOAD` tricks, but as #7580 was also classified as a bug I thought this is quite similar.

**Comment by gpaulsen** [comment]
@bwbarrett is this the same as #8990 ?

**Comment by bwbarrett** [comment]
Yes; I think this issue has already been fixed in the release branch and is just waiting for a release.

**Comment by jsquyres** [comment]
@Nortamo Can you try any of the nightly tarballs?  The fix should already be available on all relevant branches: https://www.open-mpi.org/nightly/

**Comment by Nortamo** [comment]
Looks like it is working. Generated linker flags are now just ` -Wl,-rpath -Wl,@{libdir}  -Wl,--enable-new-dtags` 
instead of ``-L/usr/lib64    -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,@{libdir} -Wl,--enable-new-dtags` when configuring with ``./configure --with-libevent=/usr`

**Comment by jsquyres** [comment]
Excellent.  I'll close this issue, then.  Thanks for the confirmation!
