### ISSUE TITLE
OPAL ERROR: Unreachable in file /home/pawan/OpenFOAM/ThirdParty-v2006/openmpi-4.0.3/opal/mca/pmix/pmix3x/pmix3x_client.c at line 112

### ISSUE THREAD

**Issue by neelshah0034** [open-mpi/ompi#8169]
Version OpenFOAM_v2006

I have a mpi-aware executable which I run by a command like

`mpiexec -np 2 snappyHexMesh -overwrite -parallel`

I am getting the following error: - 

`OPAL ERROR: Unreachable in file /home/pawan/OpenFOAM/ThirdParty-v2006/openmpi-4.0.3/opal/mca/pmix/pmix3x/pmix3x_client.c at line 112 `
`*** An error occurred in MPI_Init_thread`
`*** on a NULL communicator`
`*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,`
`***    and potentially your MPI job)`

Moreover, I think the path mentioned in the above Topic should be different. As instead of "/home/pawan/OpenFOAM/..." it should be "/home/neel/OpenFOAM/....". But, I don't know how to change that. 
Could anyone can guide me?

Thank you
Neel Shah

**Comment by rhc54** [comment]
> Moreover, I think the path mentioned in the above Topic should be different.

At a guess, I would say that you are using an Open MPI build that was done by someone else - the path being reported is the location of the source code used to build the library.

> OPAL ERROR: Unreachable in file /home/pawan/OpenFOAM/ThirdParty-v2006/openmpi-4.0.3/opal/mca/pmix/pmix3x/pmix3x_client.c at line 112 

Sounds like the `mpiexec` you are using isn't the one from Open MPI. Do a `which mpiexec` and ensure you really are picking up the one from OMPI and not MPICH.

**Comment by neelshah0034** [comment]
I agree, however I don't know to change the path that is used to build the library. Could you please guide me through that?

Sure I would try using OMPI.

Thnak you
Neel Shah

**Comment by neelshah0034** [comment]
> > Moreover, I think the path mentioned in the above Topic should be different.
> 
> At a guess, I would say that you are using an Open MPI build that was done by someone else - the path being reported is the location of the source code used to build the library.
> 
> > OPAL ERROR: Unreachable in file /home/pawan/OpenFOAM/ThirdParty-v2006/openmpi-4.0.3/opal/mca/pmix/pmix3x/pmix3x_client.c at line 112
> 
> Sounds like the `mpiexec` you are using isn't the one from Open MPI. Do a `which mpiexec` and ensure you really are picking up the one from OMPI and not MPICH.
