### ISSUE TITLE
--map-by numa question: change from 4.0.5 to latest

### ISSUE THREAD

**Issue by tonycurtis** [open-mpi/ompi#8170]
Thank you for taking the time to submit an issue!

## Background information

Latest OMPI doesn't understand ppr:N:numa.  Works with 4.0.5.  Replacing `numa` with `package` works on this system, but `numa` is explicitly listed as an option.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

git master @ 5b25a06c7d27ef5dbdeb85740592ae4550de8273

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git-clone

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

``` 
 952a986999027667b4d83bd257ea0efd9f908520 3rd-party/openpmix (v1.1.3-2485-g952a9869)
 545863e6dc055233456116da6dc85be2b307f8e2 3rd-party/prrte (dev-30707-g545863e6dc)
```

### Please describe the system on which you are running

* Operating system/version:  CentOS 8
* Computer hardware: arm (a64fx)
* Network type:  IB

-----------------------------

## Details of the problem

```mpirun -n 2 --map-by ppr:1:numa ./a.out
--------------------------------------------------------------------------
An unrecognized value was given for the number of processes
per resource (ppr) to be mapped on each node:

  Value:  numa
  PPR:  1:numa

The specification must be a number, followed by a colon, followed
by the resource type. For example, a value of "1:slot" indicates that
anything over one process per slot is to be considered oversubscribed.
Only values for "hwthread", "core", "package",
"l1cache", "l2cache", "l3cache", "numa", and "node" are allowed. Note that
enough characters must be provided to clearly specify the desired
resource (e.g., "nu" for "numa").
--------------------------------------------------------------------------
```

**Comment by jjhursey** [comment]
This was fixed in PRRTE in https://github.com/openpmix/prrte/pull/690 - so will be resolve in the next sync with that project.

**Comment by rhc54** [comment]
Just to provide an update here, as promised. We have come up with a way of doing this in all ("older" and "newer") architectures. I am working on implementation now and have found no roadblocks. I'm not sure when it will appear in an OMPI release - hopefully v5.0.0, but could be a little later.

**Comment by rhc54** [comment]
The solution is in https://github.com/openpmix/prrte/pull/1141 - should be in the v5.0.0 release. I'll look at possibly bringing it back to the 4.x series as well since it proved fairly simple.

**Comment by rhc54** [comment]
The v5.0 solution is in https://github.com/open-mpi/ompi/pull/9643.
