### ISSUE TITLE
OMPI_UNIVERSE_SIZE and "mpirun does not support recursive calls"

### ISSUE THREAD

**Issue by dmitry-kabanov** [open-mpi/ompi#8171]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
v4.0.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Homebrew in macOS

### Please describe the system on which you are running

* Operating system/version: macOS 10.15.7
* Computer hardware: MacBook with 4-core CPU
* Network type: running on localhost only

-----------------------------

## Details of the problem

I try to use `open-mpi` with `mpi4py.futures` together (this is subpackage of `mpi4py` to easily run independent tasks). The documentation of `mpi4py` says that
under Open MPI you can use the following command

```shell
shell$ OMPI_UNIVERSE_SIZE=3 posixtime mpirun -n 1 python python-script.py
```
to start with one process and then expand into master-workers thing where OMPI_UNIVERSE_SIZE controls the number of the processes.
However, this does not work, as the following errors is reported:
```
**********************************************************                                                                                                                                           mpirun does not support recursive calls                                                           ********************************************************** 
```

Even when I do the following simple command:
```shell
shell$ OMPI_UNIVERSE_SIZE=3 mpirun -n 1 hostname
```
 I still get this error, so that it is not `mpi4py` specific.

Thanks!

**Comment by rhc54** [comment]
> documentation of mpi4py says that
under Open MPI you can use the following command
>
> shell$ OMPI_UNIVERSE_SIZE=3 posixtime mpirun -n 1 python python-script.py
>
> to start with one process and then expand into master-workers thing where OMPI_UNIVERSE_SIZE controls the number of the processes.

To the best of my knowledge (as the writer of the OMPI runtime), such a command has never worked in Open MPI. I suspect the documentation you cite is incorrect.

> Even when I do the following simple command:
>
> shell$ OMPI_UNIVERSE_SIZE=3 mpirun -n 1 hostname
>
> I still get this error, so that it is not mpi4py specific.

That is correct - mpirun is checking for internal envars and finding them. Open MPI does not support recursive calls for `mpirun`.

**Comment by dmitry-kabanov** [comment]
Thank you very much for the clarification.

Although I still do not understand how to set MPI_UNIVERSE_SIZE attribute when I use Open MPI. This attribute is required to spawn new MPI processes. MPI standard https://www.mcs.anl.gov/research/projects/mpi/mpi-standard/mpi-report-2.0/node111.htm says that one of the possibilities to set it is via an environment variable. For me, `OMPI_UNIVERSE_SIZE` looks like the correct environment variable to use and the Open MPI FAQ page https://www.open-mpi.org/faq/?category=running#mpi-environmental-variables also says this:

> OMPI_UNIVERSE_SIZE - the number of process slots allocated to this job. Note that this may be different than the number of processes in the job.

**Comment by rhc54** [comment]
I believe you have misunderstood - the `OMPI_UNIVERSE_SIZE` envar is how **we** tell **you** the number of slots allocated to the job. It isn't used by you to tell us that value. We get the number of slots from your resource manager (if your system has one) or from a hostfile.

**Comment by dmitry-kabanov** [comment]
Ah, ok, I see now. I thought this is a user-specified variable.
I will ask the developer of `mpi4py` to change documentation then.

Thank you!

**Comment by dalcinl** [comment]
@rhc54 OK, yes, I have a documentation bug, but setting the variable manually probably working at some point, even if just by accident. My misunderstanding, sorry about the noise.

But then I have to ask the obvious question. Suppose you are running on a 32 cores machine, you want to start an application sequentially, i.e. `mpiexec -n 1 ./app.exe ...`, but you want Open MPI to report to the application that the MPI universe size is 16 (and not 32). It is possible to do that in Open MPI in a quick and easy way? Using MPICH's `mpiexec` I can pass a `-usize 16` option.

**Comment by rhc54** [comment]
`mpiexec -n 1 -host <hostname>:16 ...`

**Comment by dalcinl** [comment]
Trivial indeed! Thanks, Ralph!
