### ISSUE TITLE
Using CRIs for MPI_THREAD_MULTIPLE

### ISSUE THREAD

**Issue by rzambre** [open-mpi/ompi#8179]
I am interested in evaluating Open MPI's MPI_THREAD_MULTIPLE performance on a simple message-rate benchmark.
[1] says that CRIs are part of Open MPI.

(1) Could you inform me if Open MPI supports CRIs for both InfiniBand and Omni-Path?
(2) Does Open MPI support CRIs for both point-to-point and RMA operations? 
(3) Do I need to do anything special (build Open MPI a certain way / set some environment variables / set some runtime parameters / etc.) to use CRIs correctly?

[1] https://www.icl.utk.edu/files/publications/2019/icl-utk-1255-2019.pdf

**Comment by thananon** [comment]
Hi rzambre.

1. Currently Open MPI supports CRI in btl/ucx and btl/ugni. This will work for infiniband and Gemini. We had some support for Omnipath but if IIRC, it has since been removed.


To use CRI with Infiniband:
- Specify btl/ucx via MCA parameter `--mca pml ob1` `--mca btl uct`.
- Adjust number of CRI `--mca btl_uct_num_contexts_per_module (num)`

2. Infiniband has only point to point support but Gemini has both.
3. Nothing is needed in building Open MPI but set MCA params as I mention above.

**Comment by rzambre** [comment]
Here is how I built Open MPI:
`../configure --prefix=/path/to/open-mpi-master/install --with-ucx=/path/to/ucx/install/master --with-hwloc=internal && make -j 40 install`

but when I run using

```
export OMP_PLACES=cores
export OMP_PROC_BIND=close
export UCX_NET_DEVICES=mlx5_0:1
export UCX_TLS=rc_x
mpirun -n 2 --hostfile ${HOSTFILE} -x OMP_PLACES -x OMP_PROC_BIND -x UCX_NET_DEVICES -x UCX_TLS --mca pml ob1 --mca btl uct --mca btl_uct_num_contexts_per_module 1 ./multiple_isir_waitall_mbw_mr -T 1 -S 8
```

I get this error

```
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      hpc3-15-18
Framework: btl
Component: uct
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  mca_bml_base_open() failed
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
[hpc3-15-15:00000] *** An error occurred in MPI_Init_thread
[hpc3-15-15:00000] *** reported by process [252903425,0]
[hpc3-15-15:00000] *** on a NULL communicator
[hpc3-15-15:00000] *** Unknown error
[hpc3-15-15:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[hpc3-15-15:00000] ***    and MPI will try to terminate your MPI job as well)
```

How can I ensure that the uct component is enabled in Open MPI?

**Comment by rzambre** [comment]
@thananon just a friendly reminder about this. Could you provide me with things I could try to check what the error is?

**Comment by thananon** [comment]
Hi @rzambre , sorry I have not checked in with this account for a while. Are you still pursuing this? I see that you did not compile with btl/uct (OMPI has different modules for ucx and uct). You will have to specify this in configure flag.

**Comment by rzambre** [comment]
Thanks for catching that.
Closing this for now, will look into it a later time.
