### ISSUE TITLE
autogen: config/prte_get_version.sh: line 95: ./getdate.sh: No such file or directory

### ISSUE THREAD

**Issue by tonycurtis** [open-mpi/ompi#8182]
Thank you for taking the time to submit an issue!

## Background information

Getting message

```
config/prte_get_version.sh: line 95: ./getdate.sh: No such file or directory
```

repeatedly during autogen.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

github master @ 62a76c9e7d17c4b05e3a23531030fbecf9255fed

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

```
 c4fe45f982b6cdf818f9d42d2bdf3a92019f92e4 3rd-party/openpmix (v1.1.3-2613-gc4fe45f9)
 8cc88dd7f7627c2238b9b7bac2e68fe5a6092f7e 3rd-party/prrte (dev-30749-g8cc88dd7f7)
```

### Please describe the system on which you are running

* Operating system/version: CentOS 8
* Computer hardware: ARM (a64fx)
* Network type: IB

-----------------------------

## Details of the problem

```
3. Running autotools on top-level tree

==> Remove stale files
==> Writing m4 file with autogen.pl results
==> Writing txt file with all the mca component paths
==> Running autoreconf
Running: autoreconf -ivf --warnings=all,no-obsolete,no-override -I config
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config --force --warnings=all,no-obsolete,no-override -I config
config/prte_get_version.sh: line 95: ./getdate.sh: No such file or directory
config/prte_get_version.sh: line 95: ./getdate.sh: No such file or directory
config/prte_get_version.sh: line 95: ./getdate.sh: No such file or directory
...
...
...
```

**Comment by jsquyres** [comment]
Thanks @tonycurtis 

1. PMIx fixes: https://github.com/openpmix/openpmix/pull/1920 and https://github.com/openpmix/openpmix/pull/1921
1. PRRTE fix: https://github.com/openpmix/prrte/pull/682
1. Open MPI fix: https://github.com/open-mpi/ompi/pull/8185

Everything is still churning through CI.
