### ISSUE TITLE
shared/static problem

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#82]
I had a problem compiling Open MPI on my MAC OS X laptop. It failed with strange errors as undefined variables at link time. I did most of usual tricks, disable the visibility, compile only the shared version, nothing helped. I blamed the autoconf 2.64, then the gcc 4.4, [then myseld] until I read carefully the output of configure. I realized that I had installed a home made version of g95, which do not support shared libraries. The strange thing is that the --disable-mpi-f77 doesn't seems to prevent looking for the F77 and F90 compilers. As a result, the build was changed to _always_ a static build, but with some of the visibility features on which generate all my problems. Removing the g95 compiler, magically solved all my issues. --enable-shared and --disable-static really behave as they should.

I assign this ticket to Jeff, as he's one of the most knowledgeable about out build system.

**Comment by rhc54** [comment]
can be reopened if someone cares
