### ISSUE TITLE
hwloc for ompi 4.1.0rc3

### ISSUE THREAD

**Issue by zhngaj** [open-mpi/ompi#8225]
OS: RHEL 8.2
ompi version: 4.1.0rc3 (https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.0rc3.tar.bz2)

I built a RPM package for openmpi-4.1.0rc3. When installing it, I got the following error
```
Error:
 Problem: conflicting requests
  - nothing provides pkgconfig(hwloc) needed by openmpi-4.1.0rc3-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
I installed `hwloc`, but it did not help. I had to install `hwloc-devel` in order to proceed successfully. 
I'm wondering if it's expected?

I saw a note **RHEL base repositories make the HWLOC libraries and binaries available, but not the devel headers. Weird.** [here](https://github.com/open-mpi/ompi/wiki/OMPI-Third-Party-Packages). Does this mean `hwloc-devel` is required for installing openmpi-4.1.0rc3 rpm package?

**Comment by rhc54** [comment]
Not for _installing_ an rpm, but you do need it to _build_ an rpm. You need the hwloc headers in order to compile OMPI if you are using an external hwloc (and not the one that comes embedded in OMPI).

**Comment by jsquyres** [comment]
@zhngaj If that answers your questions, please close the issue.  Thanks!

**Comment by zhngaj** [comment]
Sure, @jsquyres 
@rhc54 Thanks for your reply. Just to double check that if I build the rpm with `--with-hwloc=internal`, I don't need to install hwloc-devel package by myself, correct?

**Comment by rhc54** [comment]
Correct

**Comment by zhngaj** [comment]
Sorry, I still have a question to follow up.

I think `--with-hwloc=internal` is the default setting, that's why I did NOT encounter any issue when I built the RPM earlier, even though without explicitly passing `--with-hwloc=internal` and without hwloc package installed. I just tried passing `--with-hwloc=internal` explicitly, building ompi rpm is still fine.

My problem is still there, which complains hwloc when I yum install the ompi rpm package.
```
[ec2-user@ip-172-31-12-84 home]$ sudo yum install -y ompi_build/RPMS/x86_64/openmpi-4.1.0rc3-1.el8.x86_64.rpm
Last metadata expiration check: 1:14:38 ago on Tue 17 Nov 2020 08:05:45 PM UTC.
Error:
 Problem: conflicting requests
  - nothing provides pkgconfig(hwloc) needed by openmpi-4.1.0rc3-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
My question is that why it complains `hwloc` when I do yum install ompi rpm package?

**Comment by rhc54** [comment]
This is something in your rpm spec file - looks like it is expecting hwloc to be external and complaining that it cannot find it.

**Comment by zhngaj** [comment]
Hmm, I downloaded openmpi-4.0.5.tar.bz2 and openmpi-4.1.0rc3.tar.bz2, extracted and compared the two contrib/dist/linux/openmpi.spec, I did not see difference. So I'm a bit confused why hwloc is required in 4.1.0rc3, but not in 4.0.5, and where does this package requirement bit get inserted from.

**Comment by rhc54** [comment]
If you don't have much experience building rpm's, it might be good to get some local help with it. It can be a little tricky. I'm not sure it is something we can help with remotely very efficiently.

If someone else on the OMPI list has time to help, please chime in - I don't build OMPI rpm packages myself. Frankly, the primary method for installing OMPI is just to configure with a dedicated prefix location (e.g., /opt/local/openmpi) so you can cleanly delete it if necessary. Avoids lots of rpm headaches.

**Comment by zhngaj** [comment]
The current PMIx's [configure.ac]( 
https://github.com/open-mpi/ompi/blob/v4.1.x/opal/mca/pmix/pmix3x/pmix/configure.ac#L269-L270) will write hwloc as `Requires` in created pmix.pc.

```
# Dependencies that themselves have a pkg-config file available.
#
PC_REQUIRES=""
AS_IF([test "$pmix_hwloc_support_will_build" = "yes"],
      [PC_REQUIRES="$PC_REQUIRES hwloc"])
```

I enabled verbose ouput during rpmbuild, I can see that pkg-config was invoked to process all *.pc files to query `requires` information. As shown in the snippet below, pkgconfig(hwloc), pkgconfig(libevent), and pkgconfig(zlib) are echo-ed when processing pmix.pc.
```
...
+ echo /usr/bin/pkg-config
++ dirname /home/ec2-user/SubspaceEFAInstaller/ompi_build/BUILDROOT/openmpi41-aws-4.1.0rc3-1.el8.x86_64/opt/amazon/openmpi/lib64/pkgconfig/pmix.pc
+ DIR=/home/ec2-user/SubspaceEFAInstaller/ompi_build/BUILDROOT/openmpi41-aws-4.1.0rc3-1.el8.x86_64/opt/amazon/openmpi/lib64/pkgconfig
+ export PKG_CONFIG_PATH=/home/ec2-user/SubspaceEFAInstaller/ompi_build/BUILDROOT/openmpi41-aws-4.1.0rc3-1.el8.x86_64/opt/amazon/openmpi/lib64/pkgconfig:/home/ec2-user/SubspaceEFAInstaller/ompi_build/BUILDROOT/openmpi41-aws-4.1.0rc3-1.el8.x86_64/opt/amazon/openmpi/lib64/pkgconfig/../../share/pkgconfig
+ PKG_CONFIG_PATH=/home/ec2-user/SubspaceEFAInstaller/ompi_build/BUILDROOT/openmpi41-aws-4.1.0rc3-1.el8.x86_64/opt/amazon/openmpi/lib64/pkgconfig:/home/ec2-user/SubspaceEFAInstaller/ompi_build/BUILDROOT/openmpi41-aws-4.1.0rc3-1.el8.x86_64/opt/amazon/openmpi/lib64/pkgconfig/../../share/pkgconfig
+ /usr/bin/pkg-config --print-requires --print-requires-private /home/ec2-user/SubspaceEFAInstaller/ompi_build/BUILDROOT/openmpi41-aws-4.1.0rc3-1.el8.x86_64/opt/amazon/openmpi/lib64/pkgconfig/pmix.pc
+ read n r v
+ '[' -n hwloc ']'
+ echo -n 'pkgconfig(hwloc) '
+ '[' -n '' ']'
+ echo
+ read n r v
+ '[' -n libevent ']'
+ echo -n 'pkgconfig(libevent) '
+ '[' -n '' ']'
+ echo
+ read n r v
+ '[' -n zlib ']'
+ echo -n 'pkgconfig(zlib) '
+ '[' -n '' ']'
+ echo
+ read n r v
+ read filename
+ exit 0
...
```

I think such `requires` information query is related to rpmbuild's auto-dependency generation logic. If I disable it by passing `--define 'disable_auto_requires 1'` in rpmbuild command line,  `/usr/bin/pkg-config --print-requires --print-requires-private` won't be invoked. 

`PC_REQUIRES="$PC_REQUIRES hwloc"` should not be set if configured with internal hwloc (in which case pmix_hwloc_source=embeded), IMO. So I tried with the following change. And I didn't see pkgconfig(hwloc) as `Requires` at the end of rpmbuild log, and the installation can proceed without complaining.
```
#
# Dependencies that themselves have a pkg-config file available.
#
PC_REQUIRES=""
AS_IF([test "$pmix_hwloc_source" != "embedded"],
      [PC_REQUIRES="$PC_REQUIRES hwloc"])
```  

Please let me know if it makes sense.

**Comment by rhc54** [comment]
Sounds reasonable - you want to open a PR against openpmix master for us?

**Comment by zhngaj** [comment]
Sure.

**Comment by zhngaj** [comment]
openpmix master and v3.2 branch have different places and values assigned to`pmix_hwloc_source` in case of embedded mode.
For master branch, it's src/mca/ploc/hwloc/configure.m4 [link](https://github.com/openpmix/openpmix/blob/master/src/mca/ploc/hwloc/configure.m4), and `cobuild`; while for v3.2 branch, it's config/pmix_setup_hwloc.m4[link](https://github.com/openpmix/openpmix/blob/v3.2/config/pmix_setup_hwloc.m4), and `embedded`. 

I think OMPI v4.1.x is ingesting OpenPMIx v3.2 branch, so I opened two PRs.
https://github.com/openpmix/openpmix/pull/1939 against master branch, and 
https://github.com/openpmix/openpmix/pull/1940 against v3.2 branch.

Please let me know if it complies with openpmix's convention.

**Comment by zhngaj** [comment]
PR merged, close.
