### ISSUE TITLE
mpif-sizeof.h compilation issue with Flang compiler: More than seven dimensions specified for array 

### ISSUE THREAD

**Issue by sarats** [open-mpi/ompi#8232]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
v4.0.4rc3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
MPI installed system-wide by a cluster adminstrator, most likely from a tarball.

### Please describe the system on which you are running

* Operating system/version: CentOS Linux release 8.1.1911 Aarch64
* Computer hardware: Arm/Fujitsu A64FX
* Network type: EDR infiniband

-----------------------------

## Details of the problem

When compiling an application with ARM 20.3 on A64FX, I ran into the following:

The troublemakers are in mpif-sizeof.h from Openmpi.
```
  66       CHARACTER, DIMENSION(1,1,1,1,1,1,1,*)::x                                                                                                                                                                  
  72       CHARACTER, DIMENSION(1,1,1,1,1,1,1,1,*)::x                                                                                                                                                                
```
Errors:
```
/usr/mpi/gcc/openmpi-4.0.4rc3/bin/mpifort -DHAVE_MPI -DHOMMEXX_CONFIG_IS_CMAKE -DHOMME_WITHOUT_PIOLIBRARY -DINCLUDE_CMAKE_FCI -DSPMD -I/ccsopen/home/yss/repos/homme/arm-ne256-vecsize8 -I/ccsopen/home/yss/repos/E3SM/components/homme/utils/cime/src/share/timing -I/ccsopen/home/yss/repos/homme/arm-ne256-vecsize8/utils/cime/src/share/timing -g -c /ccsopen/home/yss/repos/E3SM/components/homme/utils/cime/src/share/timing/perf_utils.F90 -o CMakeFiles/timing.dir/perf_utils.F90.o
 F90-S-0047-More than seven dimensions specified for array (/usr/mpi/gcc/openmpi-4.0.4rc3/include/mpif-sizeof.h: 66)
 F90-S-0047-More than seven dimensions specified for array (/usr/mpi/gcc/openmpi-4.0.4rc3/include/mpif-sizeof.h: 72)
 F90-S-0047-More than seven dimensions specified for array (/usr/mpi/gcc/openmpi-4.0.4rc3/include/mpif-sizeof.h: 72)
...
F90-F-0008-Error limit exceeded (/usr/mpi/gcc/openmpi-4.0.4rc3/include/mpif-sizeof.h: 102)
F90/aarch64 Linux FlangArm F90  - 1.5 2017-05-01: compilation abortedCompiler

$ mpifort --versionArm C/C++/Fortran Compiler version 20.3 (build number 543) (based on LLVM 9.0.1)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /sw/wombat/ARM_Compiler/20.3/arm-linux-compiler-20.3_Generic-AArch64_RHEL-8_aarch64-linux/bin
```

I filed an issue with the Flang community (https://github.com/flang-compiler/flang/issues/953) but apparently 15 dimensions for an array is a Fortran 2008 feature which is not currently supported.

I see that mpif-sizeof.h is generated based on some results from configure tests from https://github.com/open-mpi/ompi/blob/8bbd20102994e64e69a8ab3a9ac730d311d352ed/ompi/include/Makefile.am#L79

Wondering if there is a configure option for OpenMPI that will help workaround this issue.

**Comment by ggouaillardet** [comment]
The path suggests Open MPI was built with GNU compilers (e.g. `gfortran`).

The right fix is to rebuild Open MPI with ARM compilers (e.g. `armflang`) (and incidentally, consider modernizing your Fortran app to `use mpi_f08` or at least `use mpi` instead of the "legacy" `include 'mpif.h'`.

Note Open MPI can be installed in your `$HOME` directory and you might not have to involve your sysadmin in doing this.

**Comment by sarats** [comment]
Thanks @ggouaillardet, that makes sense. This is a testbed cluster with different nodes (h/w), overlooked the mixed compiler aspect for MPI.

**Comment by ggouaillardet** [comment]
you're welcome!
I will now close this issue.

**Comment by tardigradus** [comment]
I'm getting the same error.  This is in fact a system with mixed hardware (Intel and AMD nodes) and I am trying to compile on one of AMD nodes.  However, I don't think I am mixing the architectures in the way @sarats did, since the OpenMPI in the error message corresponds to the compiler:

    F90-S-0047-More than seven dimensions specified for array 
    (/trinity/shared/easybuild/arch/x86_64/amd/zen3/software/OpenMPI/4.1.4-GCC-11.3.0/include/mpif-sizeof.h: 66)

    $ which mpifort
    /trinity/shared/easybuild/arch/x86_64/amd/zen3/software/OpenMPI/4.1.4-GCC-11.3.0/bin/mpifort

Where else might I be going wrong?

**Comment by tardigradus** [comment]
Looks like the compiler I'm using, AOCC 4.0, is based on flang 14.0.6, which does not support Fortran 2018 and therefore not more than seven dimensions.

**Comment by ggouaillardet** [comment]
Your best bet is to rebuild Open MPI with flang.

Then consider 'use mpi' instead of 'include mpi-f.h'
