### ISSUE TITLE
"no-slot-list" missing from help-rmaps_rank_file.txt

### ISSUE THREAD

**Issue by jwagnerhki** [open-mpi/ompi#8270]
## Background information

```
mpirun -np 3 -rf rf  hostname
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    no-slot-list
from the file:
    help-rmaps_rank_file.txt
But I couldn't find that topic in the file.  Sorry!
```

```
cat rf
rank 0=node1
rank 1=node2
rank 2=node3
```

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v1.10.7

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Rocks, but also checked out tag v1.10.7 from git

## Details of the problem

There is a reference to 'no-slot-list' in:

```orte/mca/rmaps/rank_file/rmaps_rank_file.c:   orte_show_help("help-rmaps_rank_file.txt","no-slot-list", true, rank, rfmap->node_name);```

However, the corresponding help entry is missing from that help file.

**Comment by awlauria** [comment]
Hi - can you try adding `slots=` as described here:
https://www.open-mpi.org/doc/v4.0/man1/mpirun.1.php#sect10

I get the same as you do without it on a more modern 4.x branch, but with it it works. That said, I'm not positive if not specifying slots is supposed to work - if not a better error message would certainly be helpful.

```
$. mpirun -np 3 -rf rf hostname
f10n17
f10n17
f10n18
$. cat rf
rank 0=f10n17 slot=1
rank 1=f10n18 slot=0
rank 2=f10n17 slot=2
```

**Comment by rhc54** [comment]
Errrr...we really don't support v1.10 any longer - it is way too old. Any chance you could update to a more modern version?

As @awlauria Mentioned, the more modern version may still require a slots= entry. I don't know why the rank-file mapper requires it, but should we choose to change that requirement, the change definitely won't go back as far as v1.10.

**Comment by awlauria** [comment]
Yeah any fixes for this would go into 4.x/master/5.0.

It's not clear from the wiki if this is supported without `slots=`. But as Ralph mentioned there's probably no reason why it couldn't be.

**Comment by rhc54** [comment]
The "slots=" entry is not required any longer in OMPI v5, which should be released soon. In the interim, you are welcome to use a nightly tarball from either the master or v5 branch (https://www.open-mpi.org/nightly/).
