### ISSUE TITLE
Update ROMIO in v4.1.x branch

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#8271]
Due to several ongoing discussions (see #8249, for example), we're almost certainly going to upgrade ROMIO in the v4.1.x branch.

It may or may not be in time for v4.1.0, but I'm filing this issue so that it stays on our radar.

**Comment by ggouaillardet** [comment]
see my latest attempt (to be finalized) in #8279

**Comment by bwbarrett** [comment]
I'm going to close this ticket; at this point, we would not refresh ROMIO in the 4.1.x branch.
