### ISSUE TITLE
Implement "better" XML handling for mpirun

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#83]
After many hours of discussions about XML handling, we came up with what might be a reasonable approach.  It certainly ''seems'' to be much better than it is handled now (XML handling is sprinkled throughout the code base in lots of places, but lots of corner cases are not [and cannot easily be] handled).  

See http://www.open-mpi.org/community/lists/devel/2009/09/6823.php for details on a scheme that could be implemented that would be much better than the current system.

I'm simply recording this ticket here in case someone wants to implement it someday (tentatively assigning it to IBM).  Cisco does not have the resources to do it at this time.

**Comment by rhc54** [comment]
It is as good as it will ever be
