### ISSUE TITLE
Open MPI in Xcode

### ISSUE THREAD

**Issue by tnorlund** [open-mpi/ompi#8301]
I'm having trouble running Open MPI in Xcode. I can execute it just find, but when calling `MPI_Init(NULL, NULL);`, I get an error: `Failed to retrieve device information! Invalid enumerated value!`.

# Setup
I used Homebrew to install Open MPI. I then used `pkg-config` to find the libraries, headers, and linker flags required:

```bash
% pkg-config --cflags --libs ompi
-I/usr/local/Cellar/open-mpi/4.0.5/include -L/usr/local/Cellar/open-mpi/4.0.5/lib -L/usr/local/opt/libevent/lib -lmpi
```

From here, I added the header and libraries.

<img width="1512" alt="Xcode_MPIPaths" src="https://user-images.githubusercontent.com/26452518/102648202-f0836f00-411b-11eb-9804-34c4905243a9.png">

and the linker flags.

<img width="1512" alt="Xcode_LinkerFlags" src="https://user-images.githubusercontent.com/26452518/102648228-faa56d80-411b-11eb-9284-cb0bb02fcf52.png">

```
-I/usr/local/Cellar/open-mpi/4.0.5/include \
-L/usr/local/Cellar/open-mpi/4.0.5/lib \
-L/usr/local/opt/libevent/lib \
-lmpi
```

Finally, I added the executable, `orterun`, with the correct input arguments.

<img width="1512" alt="Xcode_Arguments" src="https://user-images.githubusercontent.com/26452518/102648477-6d164d80-411c-11eb-86fc-946d27ef2dc5.png">

<img width="1468" alt="Xcode_Schema" src="https://user-images.githubusercontent.com/26452518/102648426-507a1580-411c-11eb-9d20-695c605e9457.png">

I can execute the [hello world](https://mpitutorial.com/tutorials/mpi-hello-world/) example fine, but when calling MPI_Init I get some errors. Here is the total output:

```
2020-12-18 10:19:48.235265-0800 orterun[44036:1914221] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=44036
2020-12-18 10:19:48.235699-0800 orterun[44036:1914221] SecTaskCopyDebugDescription: orterun[44036]/0#-1 LF=0
2020-12-18 10:19:48.284287-0800 orterun[44036:1914221] [CL_INVALID_OPERATION] : OpenCL Error : Failed to retrieve device information! Invalid enumerated value!

2020-12-18 10:19:48.284337-0800 orterun[44036:1914221] [CL_INVALID_OPERATION] : OpenCL Error : Failed to retrieve device information! Invalid enumerated value!

2020-12-18 10:19:48.284362-0800 orterun[44036:1914221] [CL_INVALID_OPERATION] : OpenCL Error : Failed to retrieve device information! Invalid enumerated value!

2020-12-18 10:19:48.284385-0800 orterun[44036:1914221] [CL_INVALID_OPERATION] : OpenCL Error : Failed to retrieve device information! Invalid enumerated value!

2020-12-18 10:19:48.284437-0800 orterun[44036:1914221] [CL_INVALID_OPERATION] : OpenCL Error : Failed to retrieve device information! Invalid enumerated value!

2020-12-18 10:19:48.284474-0800 orterun[44036:1914221] [CL_INVALID_OPERATION] : OpenCL Error : Failed to retrieve device information! Invalid enumerated value!

Hello world from processor Tylers-MacBook-Pro.local, rank 1 out of 4 processors
Hello world from processor Tylers-MacBook-Pro.local, rank 3 out of 4 processors
Hello world from processor Tylers-MacBook-Pro.local, rank 0 out of 4 processors
Hello world from processor Tylers-MacBook-Pro.local, rank 2 out of 4 processors
Program ended with exit code: 0
```

How do I get rid of the device information warning?

**Comment by jsquyres** [comment]
Interesting.  I can't say I've ever tried to launch Open MPI via XCode.

If I load Open MPI via Homebrew and compile `hello_c.c` on the command line and run it, I do not get the same warnings you're getting:

```sh
# The simple way
$ mpicc hello_c.c -o hello

# The explicit way
$ pkg-config --cflags --libs ompi
-I/usr/local/Cellar/open-mpi/4.0.5/include -L/usr/local/Cellar/open-mpi/4.0.5/lib -L/usr/local/opt/libevent/lib -lmpi
$ gcc -I/usr/local/Cellar/open-mpi/4.0.5/include hello_c.c -c
$ gcc hello_c.o -L/usr/local/Cellar/open-mpi/4.0.5/lib -L/usr/local/opt/libevent/lib -lmpi -o hello_c
$ mpirun -np 2 hello
Hello, world, I am 0 of 2, (Open MPI v4.0.5, package: Open MPI brew@Catalina Distribution, ident: 4.0.5, repo rev: v4.0.5, Aug 26, 2020, 108)
Hello, world, I am 1 of 2, (Open MPI v4.0.5, package: Open MPI brew@Catalina Distribution, ident: 4.0.5, repo rev: v4.0.5, Aug 26, 2020, 108)
```

(`mpirun` is a sym link to `orterun`)

I can't imagine why `orterun` would be linked against OpenCL...?

**Comment by davidlcorbitt** [comment]
@tnorlund what was the resolution?

**Comment by deadfffool** [comment]
I wonder it ,too.

**Comment by hyoklee** [comment]
+1

**Comment by tnorlund** [comment]
https://www.tylernorlund.com/blog/using-libraries-with-xcode/

**Comment by hyoklee** [comment]
Thanks @tnorlund ! 

Any idea for mpich? I can't select `mpirun -> mpiexec.hydra` in Xcode.
<img width="801" alt="mpich_mpirun" src="https://user-images.githubusercontent.com/4994401/233793635-3242c100-228b-4dcf-ad53-1dcf8d2a8c99.png">

**Comment by williamdavie** [comment]
Dealing with this issue and access to https://www.tylernorlund.com/blog/using-libraries-with-xcode/ is denied. Can someone help?

**Comment by jsquyres** [comment]
@hyoklee This github is about Open MPI.  I'm afraid we can't answer questions about MPICH -- you'll need to ask them about that.  Sorry!

**Comment by hyoklee** [comment]
@jsquyres OK, thanks!
