### ISSUE TITLE
OFI MTL: ring_c and connectivity_c hang when using PSM2 provider

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#8305]
In doing some sanity checks of the OFI support in various releases I noticed that the PSM2 provider no longer works on the master and v4.1.x branches.

```
hpp@sn196:/users/hpp/ompi/examples_sn>mpirun --mca mtl_ofi_provider_include sockets -np 4 ./ring_c
Process 0 sending 10 to 1, tag 201 (4 processes in ring)
Process 0 sent to 1
Process 0 decremented value: 9
Process 0 decremented value: 8
Process 0 decremented value: 7
Process 0 decremented value: 6
Process 0 decremented value: 5
Process 0 decremented value: 4
Process 0 decremented value: 3
Process 0 decremented value: 2
Process 0 decremented value: 1
Process 0 decremented value: 0
Process 0 exiting
Process 1 exiting
Process 2 exiting
Process 3 exiting

hpp@sn196:/usr/projects/artab/users/hpp/ompi/examples_sn>mpirun --mca mtl_ofi_provider_include psm2 -np 4 ./ring_c
Process 0 sending 10 to 1, tag 201 (4 processes in ring)
Process 0 sent to 1
```

master (and probably 4.1.x) does work with the GNI and verbs:rxm providers.
v4.0.x works nominally with the psm2 provider

**Comment by rajachan** [comment]
master and 4.1.x work with the EFA provider too.

**Comment by mwheinz** [comment]
An Intel employee just reported to me that they used git bisect to trace a hang in IMPI 4.1 to  issue 8178 - which was a change provided by an EFA developer. I've asked for more details.

**Comment by mwheinz** [comment]
In my defense when I approved #8178 I was recovering from surgery...

**Comment by mwheinz** [comment]
Howard, when you were running your tests were you running more than one rank per node? @acgoldma indicated that the his issue doesn't happen when running only 1 rank per node.

**Comment by jsquyres** [comment]
@rajachan FYI.

**Comment by rajachan** [comment]
https://github.com/open-mpi/ompi/pull/8178 would affect provider selection only and not the datapath. If the PSM provider was chosen, I'm not sure what in that change could be causing a hang a few transfers in. Unless the test was done on a system with multiple NICs of course, and the behavior might have changed. Do share more details once you have them, I'll double-check the logic in my PR. Perhaps a stack trace and MTL verbose logs to confirm which provider was chosen by each of those ranks.

**Comment by acgoldma** [comment]
I was able to work with @mwheinz to reproduce on a single node. 

While dumping some of the fi_info data returned with and without the patch I noticed that the fi_info that has a cq_data_size of 0 was being returned with the patch form #8178. I looked at the old code from before that patch and the same was happening in the first call to fi_getinfo(). However, on the second call this struct was not being returned. 

Upon comparing the before and after, i noted the hints in the new patch was missing one line:
     `hints->domain_attr->cq_data_size = sizeof(int);`

Adding that back seems to fix the issue. I will push a patch in a bit after some more testing.

```
diff --git a/ompi/mca/mtl/ofi/mtl_ofi_component.c b/ompi/mca/mtl/ofi/mtl_ofi_component.c
index 0594ba8882..67963253f0 100644
--- a/ompi/mca/mtl/ofi/mtl_ofi_component.c
+++ b/ompi/mca/mtl/ofi/mtl_ofi_component.c
@@ -629,6 +629,10 @@ ompi_mtl_ofi_component_init(bool enable_progress_threads,
         hints->domain_attr->threading = FI_THREAD_DOMAIN;
     }

+    if ((MTL_OFI_TAG_AUTO == ofi_tag_mode) || (MTL_OFI_TAG_FULL == ofi_tag_mode)) {
+        hints->domain_attr->cq_data_size = sizeof(int);
+    }
+
     switch (control_progress) {
     case MTL_OFI_PROG_AUTO:
        hints->domain_attr->control_progress = FI_PROGRESS_AUTO;

```

**Comment by rajachan** [comment]
Ah, yes 😓, thanks for catching that.

There might be exposing a PSM provider bug or MTL bug in here though. Without a big enough CQ data buffer, the MTL will fall back to MTL_OFI_TAG_1.  I'd guess forcing that with your fix will still cause the test to hang? (`OMPI_MCA_mtl_ofi_tag_mode=ofi_tag_1`; which will use 12 bits for the communicator, 18 bits source rank, and 32 bits tag)
