### ISSUE TITLE
[from StackOverflow] MPI returns incorrect results for one of processes

### ISSUE THREAD

**Issue by hoopoepg** [open-mpi/ompi#8310]
Original issue: https://stackoverflow.com/questions/65281642/mpi-returns-incorrect-results-for-one-of-processes

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
OpenMPI 4.0.4 and/or Fedora 33

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
OMPI was installed from ofocoall repository using dnf tool

### Please describe the system on which you are running

* Operating system/version:  Fedora 33

-----------------------------

## Details of the problem

User is trying to run application (sources below) on 4 nodes and get's incorrect result (output below), disabling mpl ucx resolves issue.

Filling issue here because OMPI may be involved as well as UCX.

Reproducer:
```
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>

int main(int argc, char **argv)
{
        int mpirank, mpisize;
        int tabsize = atoi(*(argv + 1));

        MPI_Init(&argc, &argv);
        MPI_Comm_rank(MPI_COMM_WORLD, &mpirank);
        MPI_Comm_size(MPI_COMM_WORLD, &mpisize);

        unsigned long int sum = 0;
        int rcvsize = tabsize / mpisize;
        int *rcvbuf = malloc(rcvsize * sizeof(int));
        int *tab = malloc(tabsize * sizeof(int));
        int totalsum = 0;

        if(mpirank == 0){

                for(int i=0; i < tabsize; i++){
                        *(tab + i) = 1;
                }


        }
                MPI_Scatter(tab, tabsize/mpisize, MPI_INT, rcvbuf, tabsize/mpisize, MPI_INT, 0, MPI_COMM_WORLD);
   
        for(int i=0; i < tabsize/mpisize; i++){
                sum += *(rcvbuf + i);
        }

        printf("%d sum = %ld %d\n", mpirank, sum, tabsize/mpisize);
        MPI_Reduce(&sum, &totalsum, 1, MPI_INT, MPI_SUM, 0, MPI_COMM_WORLD);

        if(mpirank == 0){
                printf("The totalsum = %li\n", totalsum);
        }

        MPI_Finalize();

        return 0;
}
```

output:
```
$ mpirun -np 4 03_array_sum 120000000
1 sum = 29868633 30000000
2 sum = 30000000 30000000
0 sum = 30000000 30000000
3 sum = 30000000 30000000
The totalsum = 119868633
```

**Comment by awlauria** [comment]
Thanks for opening. Looks like this is duped by https://github.com/open-mpi/ompi/issues/8321.
Closing as that one has more discussion.
