### ISSUE TITLE
OFI MTL/BTL: random segfaults at MPI_Finalize when using GNI provider

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#8315]
When using the OFI libfabric GNI provider with Open MPI master and v4.1.x branches, periodic segfaults during MPI_Finalize are observed.  This problem is not observed in the 4.0.x branch.  This likely has something to do with the libfabric API version being requested and changes in behavior.

The problem goes away if
- the ofi btl is put on the mca-no-build list
- the disable-dlopen configure option is used

**Comment by jsquyres** [comment]
@hppritcha Has this been resolved?

**Comment by hppritcha** [comment]
Closing this as EOL is in sight for the GNI libfabric provider.
