### ISSUE TITLE
PMIx Not Installing - Linux

### ISSUE THREAD

**Issue by zosman1** [open-mpi/ompi#8326]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
Master- 982949c25ed1c81e8cc768b8e09455b7b2d79cd1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Downloaded from git clone, stuck on configure

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

```
 > git submodule status                                                                                                       master
 cc6d7d02b23b9be9a5eb87a34bc2f11511cafc39 3rd-party/openpmix (v4.0.0)
 78357dee102c6a3dd7ab21e5d854913a9cb0b89a 3rd-party/prrte (dev-30804-g78357dee10)
```

### Please describe the system on which you are running

* Operating system/version:  Arch Linux,  5.9.14-arch1-1
* Computer hardware: Dell XPS 15
* Network type: Wifi

-----------------------------

## Details of the problem

During the configure stage of install I get an error that I have not been able to solve, I've attached it below, I've tried re-running the configure command with sudo as my assumption was that the file was not created because of the scripts lack of permissions but I still run into the same error, anyone have any ideas?

Thanks!

```
sudo ./configure --enable-mpi-java --with-jdk-dir=/lib/jvm/java-8-openjdk 
...
============================================================================
== Configure PMIx
============================================================================
checking --with-pmix value... not found
configure: WARNING: Expected file /usr/include/pmix.h not found
configure: error: Cannot continue
configure: ===== done with 3rd-party/prrte configure =====
configure: error: PRRTE configuration failed.  Cannot continue.

```

**Comment by rhc54** [comment]
I think the error message is telling you exactly what is wrong:
```text
checking --with-pmix value... not found
```
Something messed up the OMPI configure logic causing PRRTE to think you told it to use an external PMIx installation in the default location.  I'd guess you just did a "git pull" to update your clone? We changed the PMIx branch the submodule pointed to, and that can create some problems unless you do the magic dance:
```text
git submodule sync
git submodule update --init --recursive --remote
```
Or you might try a fresh clone.

**Comment by zosman1** [comment]
This is a pretty fresh clone- I just deleted and recloned about an hour ago, any other ideas?

**Comment by rhc54** [comment]
Well, you could check your environment to ensure you don't have any "with_pmix" envars - it would be unusual, but it has happened. If what you showed is your entire configure cmd line, you could try removing the java directives to see if that is causing the problem. You could also try adding `--with-pmix=internal` to force the issue.

Afraid I can't come up with anything else - we aren't seeing this anywhere, so I'm not sure of the possible cause.

**Comment by zosman1** [comment]
``` 
> printenv | grep pmix             
>                  
  ```
  So it looks like there's no pmix environment variables
  
  ```
  > sudo ./configure 
  ...
  ============================================================================
== Configure PMIx
============================================================================
checking --with-pmix value... not found
configure: WARNING: Expected file /usr/include/pmix.h not found
configure: error: Cannot continue
configure: ===== done with 3rd-party/prrte configure =====
configure: error: PRRTE configuration failed.  Cannot continue.
```

It looks like this happens even if I exclude the java stuff

```
> sudo ./configure --with-pmix=internal

============================================================================
== Configure PMIx
============================================================================
checking --with-pmix value... not found
configure: WARNING: Expected file /usr/include/pmix.h not found
configure: error: Cannot continue
configure: ===== done with 3rd-party/prrte configure =====
configure: error: PRRTE configuration failed.  Cannot continue.
```

Also looks like this happens with that flag,

This is a pretty minimal system with not much else installed, do you have any other ideas on what could be messing with this?

**Comment by rhc54** [comment]
Afraid not - you'll likely have to wait until next week for folks to return from the holidays. Meantime, you could post your config.log and the stdout/err from running configure so they can look at it.

**Comment by zosman1** [comment]
Thanks for the help! 
I've attached both below

[output.txt](https://github.com/open-mpi/ompi/files/5758323/output.txt)
[config.log](https://github.com/open-mpi/ompi/files/5758322/config.log)

**Comment by ggouaillardet** [comment]
@zosman1 where are located the system `pmix.h` and `libpmix.so` on your system?

out of curiosity, any reason why you `sudo configure` ? 
a typical install process consists in`configure; make; sudo make install`
keep in mind that `sudo ...` will likely reset all the environment variables.

**Comment by zosman1** [comment]
Found em:

`/usr/local/include/pmix.h`
`/usr/local/lib/libpmix.so`

I was running with sudo to try to get the configure working, out of curiosity I just tried running it again and got the same error

looks like it's expecting the pmix.h to be in /usr/include but mine is in /usr/local/include, any ideas why?

**Comment by ggouaillardet** [comment]
I suspect the `output.txt` you posted does not match the (truncated) `config.log`: the former was not generated with `--with-pmix=internal`.

Open MPI looks happy with the external PMIx

```
checking pmix.h usability... yes
checking pmix.h presence... yes
checking for pmix.h... yes
```

but `prrte` is expecting `PMIx` in `/usr` and is not looking for into `/usr/local` by default, hence the error.

So if you are willing to use the external PMIx, you can `configure --with-pmix=/usr/local`.

If you are willing to use the internal PMIx, you can `configure --with-pmix=internal`.
I will need the full `config.log` and also `3rd-party/prrte/config.log` to investigate what is going wrong

@rhc54, should `config/opal_check_pmi.m4` be removed? this looks like a stale file.

**Comment by zosman1** [comment]
Here we go:


I generated the output.txt by running `./configure &>output.txt` On my side I haven't truncated any logs, if there's an argument I need to use to get the full log let me know!

 
[output.txt](https://github.com/open-mpi/ompi/files/5759436/output.txt)
[prrte-config.log](https://github.com/open-mpi/ompi/files/5759437/prrte-config.log)
[config.log](https://github.com/open-mpi/ompi/files/5759438/config.log)

**Comment by rhc54** [comment]
> should config/opal_check_pmi.m4 be removed? this looks like a stale file.

Yes - the PMIx integration is now in opal_config_pmix.m4

**Comment by ggouaillardet** [comment]
@zosman1 this is now consistent with what I described:
 - if you want to use the external PMIx, `configure --with-pmix=/usr/local`
 - if you want to use the internal PMIx, `configure --with-pmix=internal`

and if it still fails, please post the same three files so I can have a look

**Comment by zosman1** [comment]
so, it looks like this works `configure --with-pmix=/usr/local`

my question is, shouldn't this be the default behavior?

**Comment by ggouaillardet** [comment]
@zosman1 can you please post the three files for `configure --with-pmix=internal`?

FWIW, some systems do search `/usr/local` by default and some do not.
I can certainly agree you felt into a non user-friendly use case:
Open MPI considers the external PMIx can be used as is (since it is in `/usr/local`),
but PRRTE cannot find it (since it only searches `/usr`)

I defer it to @rhc54 to suggest the right way of handling this.

**Comment by zosman1** [comment]
Sorry for the delay, here you go: 

[config.log](https://github.com/open-mpi/ompi/files/5762542/config.log)
[prrte-config.log](https://github.com/open-mpi/ompi/files/5762543/prrte-config.log)
[output.txt](https://github.com/open-mpi/ompi/files/5762544/output.txt)

**Comment by zosman1** [comment]
Resolved with https://github.com/open-mpi/ompi/pull/8331
