### ISSUE TITLE
Cannot install h5py: "undefined symbol: ompi_mpi_info_null"

### ISSUE THREAD

**Issue by ajayp1** [open-mpi/ompi#8327]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.0.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

source, tar.gz

### Please describe the system on which you are running

* Operating system/version: Ubuntu 16.04 LTS
* Computer hardware: Acer Aspire A715-72G
* Network type: 

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

I have attempted to install the library h5py against multiple versions of hdf5 and OpenMPI. According to [this comment](https://forum.hdfgroup.org/t/struggling-to-build-hdf5-with-parallel-libraries/6293/4) and [this post](https://forum.hdfgroup.org/t/hdf5-and-openmpi/5437), I should be able to run both HDF5 1.10.5 and OpenMPI 4.0.1 without any compatibility issues. 

However, after trying to install h5py, I am getting the following error:
```
error: /usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so: undefined symbol: ompi_mpi_info_null
```

After attempting to install many different versions of both hdf5 and OpenMPI, I have no idea what I'm doing wrong. I have also ccoured google and can't find anything helpful. Any input is appreciated

**Comment by ggouaillardet** [comment]
what does `ldd /usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so` reports?

**Comment by ajayp1** [comment]
I have since resolved the error, and it turns out I needed to add openmpi to my RPATH when installing HDF5. If anyone stumbles on this issue in the future, you need to go through the ./configure file for hdf5 and look for the cmd argument that lets you specify the RPATH. Then, when you execute ./configure, you precede it by setting that arg = /your/openmpi/path/. Unfortunately, I'm not at the machine in question so I can't look up this argument. 

Without adding openmpi to your RPATH,  `/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so` does not find the variables in `/usr/local/openmpi/lib/lbimpi.so` (i think that's the name of it..) and thus lots of symbols, including `ompi_mpi_info_null`, remain undefined. 

I think you can close this issue.

**Comment by ajayp1** [comment]
I have since resolved the error, and it turns out I needed to add openmpi to my RPATH when installing HDF5. If anyone stumbles on this issue in the future, you need to go through the ./configure file for hdf5 and look for the cmd argument that lets you specify the RPATH. Then, when you execute ./configure, you precede it by setting that arg = /your/openmpi/path/. Unfortunately, I'm not at the machine in question so I can't look up this argument. 

Without adding openmpi to your RPATH,  `/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so` does not find the variables in `/usr/local/openmpi/lib/lbimpi.so` (i think that's the name of it..) and thus lots of symbols, including `ompi_mpi_info_null`, remain undefined. 

I think we can close this issue.

**Comment by benoitlucienjosephmarchand** [comment]
actually all you need to do is "make CC=mpicc"

**Comment by ajayp1** [comment]
For whatever reason, I could not simply export CC=mpicc. I had to specify the full path of mpicc and then specify the RPATH. Not sure why

**Comment by benoitlucienjosephmarchand** [comment]
> For whatever reason, I could not simply export CC=mpicc. I had to specify the full path of mpicc and then specify the RPATH. Not sure why

I meant to use "make CC=mpicc" when building the package, not to "export CC=mpicc".  There's an issue with the latest hdf5 parallel build where it uses CC to compile parallel IO libraries.

**Comment by xiaowang119** [comment]
> > For whatever reason, I could not simply export CC=mpicc. I had to specify the full path of mpicc and then specify the RPATH. Not sure why
> 
> I meant to use "make CC=mpicc" when building the package, not to "export CC=mpicc". There's an issue with the latest hdf5 parallel build where it uses CC to compile parallel IO libraries.

Hi, I have encountered the same problem, so what does the "make CC=mpicc" ?  I have done

> CC=/usr/local/wyj-mpich/bin/mpicc CXX=/usr/local/wyj-mpich/bin/mpicxx ./configure --prefix=/usr/local/wyj-hdf5 --enable-parallel --enable-hl --enable-shared --enable-static

and all right. But next the "make" occours some errors

> /usr/bin/ld: ../src/.libs/libhdf5.so: undefined reference to `ompi_mpi_op_sum'
/usr/bin/ld: ../src/.libs/libhdf5.so: undefined reference to `ompi_mpi_byte'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1240: testhdf5] Error 1
make[1]: Leaving directory '/home/wyj/hdf5-1.8.11/test'
make: *** [Makefile:539: all-recursive] Error 1

**Comment by jsquyres** [comment]
Looks like you are mixing Open MPI and MPICH (you cited `ompi_mpi_op_sum`, which is from Open MPI, but you also cited `CXX=/usr/local/wyj-mpich/bin/mpicxx`, which looks like it's from an MPICH install).  These are two entirely different implementations of the MPI standard that are not link-compatible with each other.

Be consistent and use entirely Open MPI or entirely MPICH, and it will likely work.

Please open a new issue if you find a problem with Open MPI; thanks.

**Comment by jsquyres** [comment]
The lines you have pasted have only shown that there is an error; you snipped out all the lines that could possibly describe what the actual error is.

Please open a new issue rather than continuing to comment on an old, unrelated, closed issue.  Thanks.
