### ISSUE TITLE
macOS: levent_core missing for OpenMPI 4.0.5

### ISSUE THREAD

**Issue by ax3l** [open-mpi/ompi#8332]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.0.5

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

I am trying to install Open MPI 4.0.5 on macOS 10.15 via Spack using AppleClang as the compiler. The instance runs on Azure Pipelines as part of my quality assurance scripts, since I don't own a mac.

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

N/A

### Please describe the system on which you are running

* Operating system/version: macOS 10.15
* Computer hardware: x86_64
* Network type: cloud (single node, 2 vcores)

-----------------------------

## Details of the problem

Compiling OpenMPI fails with the following error messages:

```
  PPFC     profile/pwin_wait_f08.lo
  FCLD     libmpi_usempif08.la
ld: library not found for -levent_core
collect2: error: ld returned 1 exit status
make[2]: *** [libmpi_usempif08.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
==> Error: ProcessError: Command exited with status 2:
    'make' '-j3'

6 errors found in build log:
     353      checking the name lister (/usr/bin/nm -B) interface... BSD nm
     354      checking for fgrep... /usr/bin/grep -F
     355      checking if .proc/endp is needed... no
     2055     checking if __sync_bool_compare_and_swap() gives correct results.
              .. yes
     2056     checking if .proc/endp is needed... no
     2057     checking directive for setting text section... .text
     2058     checking directive for exporting symbols... .globl
     2059     checking for objdump... objdump
  >> 2060     checking if .note.GNU-stack is needed... /Applications/Xcode_12.2
              .app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/b
              in/objdump: error: 'conftest.o': Invalid/Unsupported object file 
              format
     2061     no
     2062     checking suffix for labels... :
     2063     checking prefix for global symbol labels... _
     2064     checking prefix for lsym labels... L
     2065     checking prefix for function in .type...
     2066     checking if .size is needed... no

     ...

     16982      PPFC     profile/pwin_test_f08.lo
     16983      PPFC     profile/pwin_unlock_f08.lo
     16984      PPFC     profile/pwin_unlock_all_f08.lo
     16985      PPFC     profile/pwin_wait_f08.lo
     16986      FCLD     libmpi_usempif08.la
     16987    ld: library not found for -levent_core
  >> 16988    collect2: error: ld returned 1 exit status
  >> 16989    make[2]: *** [libmpi_usempif08.la] Error 1
  >> 16990    make[1]: *** [all-recursive] Error 1
  >> 16991    make: *** [all-recursive] Error 1
```

**Comment by ax3l** [comment]
cc @jjhursey @jsquyres @gpaulsen @rhc54 since the last change I can see was from #7698

**Comment by ax3l** [comment]
Is libevent an optional or required dependency of Open MPI? Is it a dependency of Open MPI on all platforms?

Potentially it's only a dependency declaration that is missing in Spack.

**Comment by jsquyres** [comment]
It is required on all platforms.

Open MPI has an embedded copy of libevent, however.  I think your issue is this: https://www.open-mpi.org/faq/?category=building#libevent-or-hwloc-errors-when-linking-fortran

**Comment by ax3l** [comment]
Thanks a lot, will migrate this downstream to Spack then!

**Comment by jsquyres** [comment]
👍 

Be sure to also read: https://www.open-mpi.org/faq/?category=building#internal-or-external-hwloc-and-libevent

**Comment by ax3l** [comment]
Thanks, Jeff!
