### ISSUE TITLE
ompi - errhandler fortran test fails

### ISSUE THREAD

**Issue by AboorvaDevarajan** [open-mpi/ompi#8341]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
master

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
git clone

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
```
[abodevar@f8n02 ompi]$ git submodule status
 cf5b492ce474bb7032f94c633e5f068293e69c2c 3rd-party/openpmix (v1.1.3-2641-gcf5b492c)
 080c116a85667a413097fe987634d3c733b3400f 3rd-party/prrte (dev-30767-g080c116a85)

```

### Please describe the system on which you are running

* Operating system/version: RH8.2
* Computer hardware: ppc64le
* Network type: IB

-----------------------------

## Details of the problem

Here is the minimal reproducer:
https://raw.githubusercontent.com/AboorvaDevarajan/mpi-tests/main/errhandler.F

```
[abodevar@f8n02 src]$ mpif77 errhandler.F -o errhandler
[abodevar@f8n02 src]$ mpirun -np 2 ./errhandler
 name 1: MPI_COMM_WORLD                                                 :
 name 2: Tp� �X���h ��S��%:
 name 1: MPI_COMM_WORLD                                                 :
 name 2: Tp� �X?��h @}2��%:
[abodevar@f8n02 src]$ 
```
In the error handler the comm_name contains garbage value.

Looks like for the fortran case, C to Fortran conversion is not done here:
https://github.com/open-mpi/ompi/blob/master/ompi/errhandler/errhandler_invoke.c#L51

Here is a probable fix:
https://github.com/open-mpi/ompi/pull/8342

With the fix:
```
[abodevar@f8n02 src]$ mpirun -np 2 ./errhandler
 name 1: MPI_COMM_WORLD                                                 :
 name 2: MPI_COMM_SELF                                                  :
 name 1: MPI_COMM_WORLD                                                 :
 name 2: MPI_COMM_SELF                                                  :
```

**Comment by jsquyres** [comment]
Good catch!
