### ISSUE TITLE
ompi_info does not display registrations with stack variables

### ISSUE THREAD

**Issue by jjhursey** [open-mpi/ompi#8345]
I've noticed that if a component calls `mca_base_component_var_register` with a `storage` argument (last argument) that is a variable declared in the scope of the function then it will not be shown in `ompi_info`.

```
static int my_component_register(void)
{
    int verbose = 0;
    (void) mca_base_component_var_register(&mca_FWK_COMP_component.version, "verbose",
               NULL, MCA_BASE_VAR_TYPE_INT, NULL, 0, 0,
               OPAL_INFO_LVL_9, MCA_BASE_VAR_SCOPE_READONLY,
               &verbose);
    return OMPI_SUCCESS;
}
```

The workaround is to declare the storage variable in the global scope
```
int my_component_verbose = 0;
static int my_component_register(void)
{
    (void) mca_base_component_var_register(&mca_FWK_COMP_component.version, "verbose",
               NULL, MCA_BASE_VAR_TYPE_INT, NULL, 0, 0,
               OPAL_INFO_LVL_9, MCA_BASE_VAR_SCOPE_READONLY,
               &my_component_verbose);
    return OMPI_SUCCESS;
}
```

The above example shows 'verbose', but this impacts any other MCA parameter being registered.

**Comment by rhc54** [comment]
@jjhursey That isn't really a bug in the variable code - that is an error in your component_register code. You cannot use a stack variable in the var_register function. It has to be global static memory. This is documented in the opal/mca headers.

**Comment by jjhursey** [comment]
Thanks. I found the doc [here](https://github.com/open-mpi/ompi/blob/master/opal/mca/base/mca_base_var.h#L418-L428) - so technically this is invalid code.

It still seems weird that it causes `ompi_info --all` not to show it.

**Comment by rhc54** [comment]
Yeah, that is weird - not sure I understand why that would happen.
