### ISSUE TITLE
mpi.h:339:59: error: expected primary-expression before ‘static_assert’

### ISSUE THREAD

**Issue by puneet336** [open-mpi/ompi#8358]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
OpenMPI - 4.1.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
source

### Please describe the system on which you are running

* Operating system/version:  Centos8

-----------------------------

## Details of the problem

During compilation of HPCC code i get - 
[user@node hpcc-1.5.0]$ make arch=Linux_ompi410_oblas0310  2>&1|tee make_logs
mkdir -p hpl/lib/Linux_ompi410_oblas0310
( cd hpl/lib/arch/build ; make arch=Linux_ompi410_oblas0310 -f Makefile.hpcc )
make[1]: Entering directory '/home/user/HPCC/OPENMPI/gcc10/src/hpcc-1.5.0/hpl/lib/arch/build'
/home/puneet/MySoftwares/COMPILER/MPI/OPENMPI/4.1.2_gcc10.2.0v02/bin/mpicxx -o ../../../src/comm/HPL_packL.o -c ../../../src/comm/HPL_packL.c -DAdd__ -DF77_INTEGER=int -DStringSunStyle -DHPL_DETAILED_TIMING -DHPL_PROGRESS_REPORT -DHPL_STDC_HEADERS -I/home/user/HPCC/OPENMPI/gcc10/src/hpcc-1.5.0/hpl//include -I/home/user/HPCC/OPENMPI/gcc10/src/hpcc-1.5.0/hpl//include/Linux_ompi410_oblas0310 -I/home/user/HPL/OPENMPI/gcc10v02/DEPS/v1//include  -O3 -march=native  -mprefer-vector-width=256 -std=c++11 -fomit-frame-pointer -funroll-loops -W -Wall
In file included from /home/user/HPCC/OPENMPI/gcc10/src/hpcc-1.5.0/hpl//include/hpl.h:75,
                 from ../../../src/comm/HPL_packL.c:50:
/home/user/HPCC/OPENMPI/gcc10/src/hpcc-1.5.0/hpl//include/hpl_misc.h:54: warning: "HPL_STDC_HEADERS" redefined
   54 | #define HPL_STDC_HEADERS
      |
<command-line>: note: this is the location of the previous definition
In file included from /home/user/HPCC/OPENMPI/gcc10/src/hpcc-1.5.0/hpl//include/hpl_pmisc.h:54,
                 from /home/user/HPCC/OPENMPI/gcc10/src/hpcc-1.5.0/hpl//include/hpl.h:80,
                 from ../../../src/comm/HPL_packL.c:50:
../../../src/comm/HPL_packL.c: In function ‘int HPL_packL(HPL_T_panel*, int, int, int)’:
/home/puneet/MySoftwares/COMPILER/MPI/OPENMPI/4.1.2_gcc10.2.0v02/include/mpi.h:339:59: error: expected primary-expression before ‘static_assert’
  339 | #define THIS_FUNCTION_WAS_REMOVED_IN_MPI30(func, newfunc) static_assert(0, #func " was removed in MPI-3.0.  Use " #newfunc " instead.")
      |                                                           ^~~~~~~~~~~~~
/home/puneet/MySoftwares/COMPILER/MPI/OPENMPI/4.1.2_gcc10.2.0v02/include/mpi.h:2861:27: note: in expansion of macro ‘THIS_FUNCTION_WAS_REMOVED_IN_MPI30’
 2861 | #define MPI_Address(...)  THIS_FUNCTION_WAS_REMOVED_IN_MPI30(MPI_Address, MPI_Get_address)
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../src/comm/HPL_packL.c:172:22: note: in expansion of macro ‘MPI_Address’
  172 |             ierr =   MPI_Address( bufs[nbufs], &disp[nbufs] );
      |                      ^~~~~~~~~~~
/home/puneet/MySoftwares/COMPILER/MPI/OPENMPI/4.1.2_gcc10.2.0v02/include/mpi.h:339:59: error: expected primary-expression before ‘static_assert’
  339 | #define THIS_FUNCTION_WAS_REMOVED_IN_MPI30(func, newfunc) static_assert(0, #func " was removed in MPI-3.0.  Use " #newfunc " instead.")
      |                                                           ^~~~~~~~~~~~~
/home/puneet/MySoftwares/COMPILER/MPI/OPENMPI/4.1.2_gcc10.2.0v02/include/mpi.h:2861:27: note: in expansion of macro ‘THIS_FUNCTION_WAS_REMOVED_IN_MPI30’
 2861 | #define MPI_Address(...)  THIS_FUNCTION_WAS_REMOVED_IN_MPI30(MPI_Address, MPI_Get_address)
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../src/comm/HPL_packL.c:186:25: note: in expansion of macro ‘MPI_Address’
  186 |                ierr =   MPI_Address( bufs[nbufs], &disp[nbufs] );
      |                         ^~~~~~~~~~~
/home/puneet/MySoftwares/COMPILER/MPI/OPENMPI/4.1.2_gcc10.2.0v02/include/mpi.h:339:59: error: expected primary-expression before ‘static_assert’
  339 | #define THIS_FUNCTION_WAS_REMOVED_IN_MPI30(func, newfunc) static_assert(0, #func " was removed in MPI-3.0.  Use " #newfunc " instead.")
      |                                                           ^~~~~~~~~~~~~
/home/puneet/MySoftwares/COMPILER/MPI/OPENMPI/4.1.2_gcc10.2.0v02/include/mpi.h:2861:27: note: in expansion of macro ‘THIS_FUNCTION_WAS_REMOVED_IN_MPI30’
 2861 | #define MPI_Address(...)  THIS_FUNCTION_WAS_REMOVED_IN_MPI30(MPI_Address, MPI_Get_address)
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../src/comm/HPL_packL.c:200:22: note: in expansion of macro ‘MPI_Address’
  200 |             ierr =   MPI_Address( bufs[nbufs], &disp[nbufs] );
      |                      ^~~~~~~~~~~
../../../src/comm/HPL_packL.c:204:7: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
  204 |       for( i = 1; i < nbufs; i++ ) disp[i] -= disp[0]; disp[0] = 0;
      |       ^~~
../../../src/comm/HPL_packL.c:204:56: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
  204 |       for( i = 1; i < nbufs; i++ ) disp[i] -= disp[0]; disp[0] = 0;
      |                                                        ^~~~
In file included from /home/user/HPCC/OPENMPI/gcc10/src/hpcc-1.5.0/hpl//include/hpl_pmisc.h:54,
                 from /home/user/HPCC/OPENMPI/gcc10/src/hpcc-1.5.0/hpl//include/hpl.h:80,
                 from ../../../src/comm/HPL_packL.c:50:
/home/puneet/MySoftwares/COMPILER/MPI/OPENMPI/4.1.2_gcc10.2.0v02/include/mpi.h:339:59: error: expected primary-expression before ‘static_assert’
  339 | #define THIS_FUNCTION_WAS_REMOVED_IN_MPI30(func, newfunc) static_assert(0, #func " was removed in MPI-3.0.  Use " #newfunc " instead.")
      |                                                           ^~~~~~~~~~~~~
/home/puneet/MySoftwares/COMPILER/MPI/OPENMPI/4.1.2_gcc10.2.0v02/include/mpi.h:2869:31: note: in expansion of macro ‘THIS_FUNCTION_WAS_REMOVED_IN_MPI30’
 2869 | #define MPI_Type_struct(...)  THIS_FUNCTION_WAS_REMOVED_IN_MPI30(MPI_Type_struct, MPI_Type_create_struct)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../src/comm/HPL_packL.c:211:19: note: in expansion of macro ‘MPI_Type_struct’
  211 |          ierr =   MPI_Type_struct( nbufs, blen, disp, type,
      |                   ^~~~~~~~~~~~~~~
make[1]: *** [Makefile.hpcc:130: ../../../src/comm/HPL_packL.o] Error 1
make[1]: Leaving directory '/home/user/HPCC/OPENMPI/gcc10/src/hpcc-1.5.0/hpl/lib/arch/build'
make: *** [Makefile:8: all] Error 2

**Comment by hjelmn** [comment]
The error message tells you what is wrong. You are using functions that are no longer provided by MPI since 3.0.

**Comment by jsquyres** [comment]
@puneet336 I'm a little confused because there is no Open MPI v4.1.2 -- we only just released v4.1.0 very recently.

Also, you might want to look at https://www.open-mpi.org/faq/?category=mpi-removed.

Hope that helps.

**Comment by puneet336** [comment]
Default gcc verion was gcc 8 with centos 8.
when i load gcc10, this error goes away and compilation works fine.
