### ISSUE TITLE
Advice: recommended params for a generic setup

### ISSUE THREAD

**Issue by amckinstry** [open-mpi/ompi#8367]
So, this is a request for advice rather than a bug report.

I'm a maintainer of the MPI stack in Debian, so : OpenMPI is the default MPI (we also ship mpich), but also pmix, ucx, etc.

Increasingly it makes sense to build the MPI versions of apps by default, but as a generic distro we cannot assume
Infiniband is present/used on our systems; now with UCX we get:

```
root@debian:/openmpi-4.1.0/debian/tests# mpirun  -n 2 ./hello
[1610465245.269420] [debian:800759:0]      rdmacm_cm.c:638  UCX  ERROR rdma_create_event_channel failed: No such device
[1610465245.349752] [debian:800759:0]     ucp_worker.c:1432 UCX  ERROR failed to open CM on component rdmacm with status Input/output error
[debian:800759] ../../../../../../ompi/mca/pml/ucx/pml_ucx.c:273  Error: Failed to create UCP worker
[1610465245.414575] [debian:800757:0]      rdmacm_cm.c:638  UCX  ERROR rdma_create_event_channel failed: No such device
[1610465245.414624] [debian:800757:0]     ucp_worker.c:1432 UCX  ERROR failed to open CM on component rdmacm with status Input/output error
[debian:800757] ../../../../../../ompi/mca/pml/ucx/pml_ucx.c:273  Error: Failed to create UCP worker
 node           1 : Hello world
 node           0 : Hello world
```

The problem is: OpenIB and UCX warnings are likely to both annoy users and also break test suites when run on plain multicore/ethernet systems.
We can ship with warnings silenced, eg ` /etc/openmpi/openmpi-mca-params.conf' has:
```
## 
btl_base_warn_component_unused=0
# Avoid openib in case applications use fork: see https://github.com/ofiwg/libfabric/issues/6332
# If you wish to use openib and know your application is safe, remove the following:
btl_base_exclude=openib
```
So, should I add another exclude for ucx , and leave it to cluster admins to enable in the conf file ?Thank you for taking the time to submit an issue!

**Comment by amckinstry** [comment]
Argh. I misread, I thought I was submitting to openmpi. Moved and closing, sorry.

**Comment by jjhursey** [comment]
@amckinstry This is the right place for Open MPI. I'll re-open this ticket.

This sounds like a good question for the UCX folks on how best to handle this in the v4.x series, and moving forward.

**Comment by amckinstry** [comment]
I can silence UCX warnings (above) using:
```
mpirun --mca pml ^ucx  -n 2 ./hello
```
to disable UCX by default. How can I do so in `/etc/openmpi/openmpi-mca-params.conf` ?
The equivalent `mpl_base_exclude=ucx` doesn't appear to exist.

**Comment by ggouaillardet** [comment]
@amckinstry simply add the following line in `openmpi-mca-params.conf`

```
pml = ^ucx
```

that might not be enough since UCX can be used by `btl/uct` if `pml/ob1` is used, and `osc/ucx` for rdma
in that case, you also need to add
```
btl = ^uct
osc = ^ucx
```
you might also consider this alternative to also avoid `btl/openib` (that issues warnings by default)
```
btl = ^uct,openib
```

**Comment by jsquyres** [comment]
@jladd-mlnx @hoopoepg Someone from the UCX community should probably make these messages better (i.e., it's not an error if there's no IB equipment present).  This just causes downstream packagers to disable UCX.

**Comment by jsquyres** [comment]
Another user posted a UCX error message yesterday -- I don't know if it's related or helps track this down: https://www.mail-archive.com/users@lists.open-mpi.org/msg34257.html

**Comment by jladd-mlnx** [comment]
@janjust

**Comment by jladd-mlnx** [comment]
@yosefe

**Comment by jsquyres** [comment]
@open-mpi/ucx FYI.

**Comment by yosefe** [comment]
@amckinstry the error `[1610465245.269420] [debian:800759:0]      rdmacm_cm.c:638  UCX  ERROR rdma_create_event_channel failed: No such device` should not happen even if there is no RDMA device on the system. We will reproduce the issue see how to avoid such error from UCX side. adding @alinask and @evgeny-leksikov
