### ISSUE TITLE
OMPI configuration failure with master branch and libfabric enabled 

### ISSUE THREAD

**Issue by zhngaj** [open-mpi/ompi#8395]
With OMPI master branch (1faba6589e (HEAD -> master) Merge pull request #8382 from rhc54/topic/mst) and libfabric enabled, I encountered configuration failure when building submodule openpmix.

**git log:**
```
[ec2-user@ip-172-31-17-88 ompi]$ git log --oneline
1faba6589e (HEAD -> master) Merge pull request #8382 from rhc54/topic/mst
2309047ae1 Switch back to PMIx master branch
206c8131c5 Merge pull request #8384 from rhc54/topic/args
540b2dc16d Expose the PMIx/PRRTE unique configure args
a6cf2cd661 Merge pull request #8372 from bosilca/topic/icc_avx
228fc4147f Merge pull request #8369 from edgargabriel/topic/aio_progress
a2041bea59 Always specify the target architecture for AVX
...
```

**submodule status:**
```
[ec2-user@ip-172-31-17-88 ompi]$ git submodule status
 174500cb2acba3b2f9fdc8eaea36e74ae54f1d5b 3rd-party/openpmix (v1.1.3-2744-g174500cb)
 5b666f963f8d68a4751d64bef3b3294665cea9e9 3rd-party/prrte (dev-30821-g5b666f963f)
```
**Configure command:**
``` 
./configure --prefix=/fsx/ompi/install --with-libfabric=/fsx/libfabric/install
```
**Configure error:**
```
...
============================================================================
== CURL
============================================================================
checking where to find curl.h... unknown
looking for header in unknown
checking curl.h usability... no
checking curl.h presence... no
checking for curl.h... no
looking for header in unknown/include
checking curl.h usability... no
checking curl.h presence... no
checking for curl.h... no
checking libcurl support available... no
checking --with-ofi value... sanity check ok (/fsx/libfabric/install)
checking --with-ofi-libdir value... simple ok (unspecified)
checking looking for OFI libfabric in... (/fsx/libfabric/install)
looking for header in /fsx/libfabric/install
checking rdma/fabric.h usability... no
checking rdma/fabric.h presence... no
checking for rdma/fabric.h... no
looking for header in /fsx/libfabric/install/include
checking rdma/fabric.h usability... yes
checking rdma/fabric.h presence... yes
checking for rdma/fabric.h... yes
looking for library without search path
checking for library containing fi_getinfo... no
looking for library in /fsx/libfabric/install/lib64
checking for library containing fi_getinfo... (cached) no
looking for library in /fsx/libfabric/install/lib
checking for library containing fi_getinfo... (cached) no
configure: WARNING: OFI libfabric support requested (via --with-ofi or --with-libfabric), but not found.
configure: error: Cannot continue.
configure: ===== done with 3rd-party/openpmix configure =====
configure: error: Could not find viable pmix build.
```

I narrowed the issue down to PR #8382 specifically, and looks like the it's related to the change [here](https://github.com/openpmix/openpmix/compare/34fa2ca7bea3e6d4e2a40b5ca37a5b3401d41615...174500cb2acba3b2f9fdc8eaea36e74ae54f1d5b#diff-c9fd642535c8a9218580344fb1a7daaa89bfb9cb14e005554f2e4f30c43afd89R802). @rhc54 Do you have any quick idea of what could be wrong here?

**Comment by zhngaj** [comment]
The configuration works fine when using 206c8131c5 as HEAD, and the following submodules.
```
[ec2-user@ip-172-31-17-88 ompi]$ git log --oneline | head -2
206c8131c5 Merge pull request #8384 from rhc54/topic/args
540b2dc16d Expose the PMIx/PRRTE unique configure args
```
```
[ec2-user@ip-172-31-17-88 ompi]$ git submodule update --init
Submodule path '3rd-party/openpmix': checked out '34fa2ca7bea3e6d4e2a40b5ca37a5b3401d41615'
Submodule path '3rd-party/prrte': checked out '4d7ba56f9e655b5d51b720c52b5839dcc3dac207'
```

**Comment by ggouaillardet** [comment]
@zhngaj can you please compress and post your `3rd-party/openpmix/config.log` file?

**Comment by zhngaj** [comment]
@ggouaillardet here is 3rd-party/openpmix/config.log 
[config.log](https://github.com/open-mpi/ompi/files/5839855/config.log)

**Comment by ggouaillardet** [comment]
It looks like there is no `/fsx/libfabric/install/lib64/libfabric.so` nor `/fsx/libfabric/install/lib/libfabric.so`.
Can you please confirm the content of these directories?

**Comment by rhc54** [comment]
@ggouaillardet I copied the ofi m4 code from OMPI over the weekend as we needed to detect if libfabric was around. It worked fine for me in my test VM, but that has libfabric in the default locations. I wonder if this is also a problem in OMPI master? If not, then I wonder why the difference. There is some configure code for passing arguments down to the 3rd party packages - perhaps something is missing there?!

**Comment by ggouaillardet** [comment]
I just checked the code and at first glance it looks good to me.
I noted there is no `-L/fsx/libfabric/install/lib64` in the gcc command line (!).
`LDFLAGS` is set in the code, but it looks like `AC_SEARCH_LIBS` ignores it ...
FWIW, `CPPFLAGS` is set and used by `AC_CHECK_HEADERS`.

@zhngaj which `autoconf` version did you use?

**Comment by ggouaillardet** [comment]
never mind, same issue here with `./configure --with-libfabric=...` invoked from `3rd-party/openpmix`

**Comment by ggouaillardet** [comment]
oh I see ...

first we test without any `$LDFLAGS`
```
looking for library without search path
checking for library containing fi_getinfo... no
```
and it fails (obviously)

then we try with `LDFLAGS=-L/fsx/libfabric/install/lib64`

```
looking for library in /fsx/libfabric/install/lib64
checking for library containing fi_getinfo... (cached) no
```

except we try nothing but use the result we just cached (so it's yet an other no ... without even trying)


the logical conclusion is this never worked ... and yet it did, so I must be missing something here.

**Comment by zhngaj** [comment]
@ggouaillardet I can confirm /fsx/libfabric/install/lib and .so files are there.

So you mean even though it looks for library in /fsx/libfabric/install/lib eventually, but it's still using the cached result (based on the test without any `$LDFLAGS` previously), which will never work. Is that correct?
```
looking for library without search path
checking for library containing fi_getinfo... no
looking for library in /fsx/libfabric/install/lib64
checking for library containing fi_getinfo... (cached) no
looking for library in /fsx/libfabric/install/lib
checking for library containing fi_getinfo... (cached) no
...
```

**Comment by ggouaillardet** [comment]
It never worked because we likely never ran into this before.
I mean `PMIX_CHECK_PACKAGE()` is not called with a non empty `prefix` **and** an emptry `libdir-prefix`.
I mimicked `pmix_setup_libev.m4` and came with this patch (to be applied on openpmix)

```patch
diff --git a/config/pmix_check_ofi.m4 b/config/pmix_check_ofi.m4
index c92f239..3d85e8e 100644
--- a/config/pmix_check_ofi.m4
+++ b/config/pmix_check_ofi.m4
@@ -108,7 +108,15 @@ AC_DEFUN([_PMIX_CHECK_OFI],[
                  [AC_MSG_RESULT([(default search paths)])])
            AS_IF([test ! -z "$with_ofi_libdir" && \
                          test "$with_ofi_libdir" != "yes"],
-                 [pmix_ofi_libdir=$with_ofi_libdir])
+                 [pmix_ofi_libdir=$with_ofi_libdir],
+                 [if test -d $with_ofi/lib; then
+                      pmix_ofi_libdir=$with_ofi/lib
+                  elif test -d $with_ofi/lib64; then
+                      pmix_ofi_libdir=$with_ofi/lib64
+                  else
+                      AC_MSG_RESULT([Could not find $with_ofi/lib or $with_ofi/
+                      AC_MSG_ERROR([Can not continue])
+                  fi])
           ])

     AS_IF([test $pmix_ofi_happy = yes],
```

**Comment by ggouaillardet** [comment]
Note if `$with_ofi/lib` exists but the right library is in `$with_ofi/lib64`, I suspect the test will fail because only the former is given a try.

**Comment by ggouaillardet** [comment]
@zhngaj the inline patch above should fix the issue (at least as far as `openpmix` and `libfabric` are concerned)

**Comment by zhngaj** [comment]
Thanks @ggouaillardet, it makse sense to me.

One minor thing: It should be `AC_MSG_RESULT([Could not find $with_ofi/lib or $with_ofi])` instead of `AC_MSG_RESULT([Could not find $with_ofi/lib or $with_ofi/`.

**Comment by ggouaillardet** [comment]
@zhngaj thanks for spotting the lines were truncated, I edited the patch to fix that.
(fwiw, it was meant to be `... or $with_ofi/lib64`)

**Comment by zhngaj** [comment]
Yep.
Since we found the issue, and the fix will be applied to openpmix, close the issue.
