### ISSUE TITLE
Communicator construction/destruction slow with coll sm

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#84]
The coll sm component is somewhat "slow" when creating and destroying communicators because it mmap's upon construction and munmap's upon destruction.  In most applications, this is probably not an issue.  But in applications that create and destroy many communicators frequently, the effect can be noticeable.

For example in the ompi-tests/ibm test suite, the communicator/comm_dup_f test calls MPI_COMM_DUP 100k times.  With coll tuned or basic, this takes just a few seconds (usually <10 secs).  With coll sm, it takes minutes.

An obvious way to help this issue would be to cache mmap'ed regions upon communicator destruction (i.e., don't munmap them).  Then, if an equivalent group of processes creates a new sm coll, use that cached region.  However, some care would need to be taken to ensure that the cached regions don't consume too much memory (e.g., make a bunch of communicators, free them, then make some more, potentially with non-equivalent sets of processes, thereby "orphaning" potentially a bunch of mmap regions on the cache list).  

To be clear: especially with increasing core counts in commodity servers, it would seem like some kind of intelligent eviction policy is needed to ensure that the total resources consumed by the cached region list is not "too much".

I have no cycles to implement such an optimization at the moment.  I'm filing this enhancement in the hopes that someone gets to it someday.

**Comment by rhc54** [comment]
Fixed long ago
