### ISSUE TITLE
Remove PMIx requirement from opal_check_ofi.m4

### ISSUE THREAD

**Issue by kholland-intel** [open-mpi/ompi#8407]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
master

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
git clone

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
N/A

### Please describe the system on which you are running
N/A

* Operating system/version: 
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem

Hello,

I would like to use opal_check_ofi.m4 verbatim from the openmpi upstream for [Sandia OpenSHMEM](https://github.com/Sandia-OpenSHMEM/SOS). However, it appears that there is a [block of code](https://github.com/open-mpi/ompi/blob/master/config/opal_check_ofi.m4#L136) that makes using PMIx a requirement when building with OFI. As of now, we do not require our users to have PMIx, by default. Is it possible for this requirement to be moved so that we are able to pull this file directly without having to diverge our file from the upstream version?

Thank you!

**Comment by rhc54** [comment]
I believe this has been answered - please reopen if it remains.
