### ISSUE TITLE
Failed to bind to uncontinuous core int SMT machine

### ISSUE THREAD

**Issue by Qinghe12** [open-mpi/ompi#8420]
## Background information
I tried to bind mpi process to different core in a SMT machine as following but failed:

cmd：mpirun -np 2  --allow-run-as-root  taskset -c 0,2 ./graph500_reference_bfs 20 16

I  observed that  two  processes run in core 0 and core 1 as default.

openmpi version:  v4.0.5
compilation：./configure --prefix=/xxxx
make 
make install

**Comment by ggouaillardet** [comment]
What are you trying to achieve?

How do you observe that the processes run on cores 0 and 1?
