### ISSUE TITLE
datatype unpack: potential incorrect assert

### ISSUE THREAD

**Issue by hoopoepg** [open-mpi/ompi#8466]
Thank you for taking the time to submit an issue!

## Background information
During debugging of issue https://github.com/open-mpi/ompi/issues/8442 we found strange assert, details below

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
Found at least in 4.1.x and master branches

## Details of the problem
there is assert at https://github.com/open-mpi/ompi/blob/56ed3a630907f3c30ecf780e1d506468275c87ea/opal/datatype/opal_datatype_unpack.h#L99
but call from https://github.com/open-mpi/ompi/blob/56ed3a630907f3c30ecf780e1d506468275c87ea/opal/datatype/opal_datatype_unpack.c#L204
is ```unpack_partial_blocklen(... count_desc=1, ...)```
because https://github.com/open-mpi/ompi/blob/56ed3a630907f3c30ecf780e1d506468275c87ea/opal/datatype/opal_datatype_unpack.c#L172
which produces assert shot in any case on this call path.

is this issue or I missed something in this world? :)

@jsquyres could it be artefact of some refactoring?

**Comment by jsquyres** [comment]
@bosilca will have a look; datastuff is in his domain...

**Comment by jsquyres** [comment]
@bosilca mentioned on the Tuesday call on 9 Mar 2021 that this assert is correct.  This code path shouldn't be used for partial datatypes, so the assert is actually doing its job correctly here.  The fact that this assert is tripping means that the real problem is somewhere else (perhaps related to #8442).

**Comment by hoopoepg** [comment]
hmmm, than call https://github.com/open-mpi/ompi/blob/56ed3a630907f3c30ecf780e1d506468275c87ea/opal/datatype/opal_datatype_unpack.c#L204 is incorrect

**Comment by jsquyres** [comment]
Re-opening because the fix has been merged on master, but still needs to be merged to v4.0.x, v4.1.x, and v5.0.x.

**Comment by hppritcha** [comment]
closed as fixes have been merged into 4.0.x, 4.1.x, 5.0.x, and master.
