### ISSUE TITLE
flux support on master

### ISSUE THREAD

**Issue by ggouaillardet** [open-mpi/ompi#8490]
I gave `flux` a shot on my cluster.
It works out of the box with the latest release branch, but not with the `master` branch.

Here is the error message

```
$ flux mini run -n1 ./ring_c.master 
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      XYZ
Framework: pmix
Component: flux
```

a workaround is to
```
$ flux mini run -n1 env -u OMPI_MCA_pmix ./ring_c.master
```

What happens here is `flux` automatically sets the following environment variables
 - `OMPI_MCA_orte_tmpdir_base`
 - `OMPI_MCA_pmix=flux`
 - `OMPI_MCA_schizo=flux`

The issue is with `OMPI_MCA_pmix=flux`.
Since `pmix` is now a first class citizen, there is no more `pmix/flux` component, and my understanding is there is no more component ... but `opal` is unaware of that, tries to open `pmix/flux` as asked and aborts because there is no such component.

Of course, `flux` could do it differently, but can we do something about it?

FWIW, I tried declaring the `pmix` framework with `MCA_BASE_FRAMEWORK_FLAG_REGISTERED` or `MCA_BASE_REGISTER_STATIC_ONLY` but that only resulted in a crash.

Incidentally, I believe the `OMPI_MCA_orte_tmpdir_base` and `OMPI_MCA_schizo` environment variables are ignored. Should `flux` set different ones?

**Comment by rhc54** [comment]
Nothing we can do - flux needs to upgrade to support PMIx directly instead of using PMI-1. LLNL is aware of this but hasn't gotten around to it yet.

**Comment by ggouaillardet** [comment]
Got it, thanks!

I just noticed I did not realize that my workaround simply made `flux` spawn `n` instances of rank `0` instead of a job of `n` ranks ...
