### ISSUE TITLE
Potential deadlock with multiple TCP BTL devices

### ISSUE THREAD

**Issue by bwbarrett** [open-mpi/ompi#8498]
We found a "deadlock" situation with OB1 and the TCP BTL when there are multiple network endpoints AND there is a non-OMPI communication layer in use.  In this case, the situation was found when running the NCCL tests, which are testing NCCL's non-MPI communication stack, but using MPI for synchronization and launching.  The code in question is essentially:

```C
MPI_Init()
NCCL_Iniit
MPI_Barrier(MPI_COMM_WORLD)
NCCL_allreduce(<everyone>
MPI_Barrier(MPI_COMM_WORLD)
```

Like MPI_ALLREDUCE, NCCL's allreduce necessarily has barrier semantics, in that everyone must contribute their part before the answer can be known and distributed.  The code was running 24 processes per node on 3 nodes, and each node had 4 network adapters.

The barrier algorithm used for this situation is the recursive doubling algorithm, which has an SSend as the final step for the cleanup of the non-power-of-2 case.  The "fixup" processes with the SSend involve fewer communications between ranks than there were number of BTLs.  So the SSend results in a round robin btl pick that has not established a connection, starting the connection process.  The Ack from the receiving process also picks a new BTL, without an established connection, which results in the TCP connection process starting.  The TCP BTL starts the connect, then returns succes to the PML, which completes the receive, which completes the barrier, which means the process enters the NCCL allreduce, where it stays until the sending process joins.  But the sending process is stuck in MPI_Barrier waiting for the ack that will never come, because it is stuck in the receiving process, which is currently stuck in the NCCL allreduce.

I think the right solution for this particular case is for OB1 to use the same endpoint to send the SSend ack as was used to receive the header fragment, so that it will never result in a connection establishment handshake.  Another option would be to have OB1 wait for completion before completing the receive, but that seems like it could have negative impact on performance.

Of course, neither of those solutions would solve the problem of a short message send that never got sent, either because of connection establishment or because the packet got queued.

**Comment by gpaulsen** [comment]
merged to all release branches.  Closing.
