### ISSUE TITLE
tcp btl lack of diagnostic output and bad failure modes

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#85]
On a very long thread on the users list (started here, http://www.open-mpi.org/community/lists/users/2009/09/10712.php, eventually moved off-list), I ended up digging through the TCP BTL connection logic.  I discovered two things:
1. If you run with --mca btl_base_verbose 100, the TCP BTL reports very little of what it is doing during wireup, making networking misconfiguration and other kinds of problems very difficult to identify.
2. If an error occurs during the TCP BTL wireup (e.g., connect(2) fails), error handling is pretty much non-existent, meaning that the PML isn't notified that anything went wrong, and the job will therefore usually hang.  ''Sometimes'' the TCP BTL prints a diagnostic error message indicating that something went wrong, but usually it does not.

I have an hg branch with a lot more diagnostic TCP BTL wireup output that I plan to put back to the trunk eventually (I actually consider this a defect, not a feature enhancement).  I also am working to make OMPI do "something reasonable" (to include possibly even aborting) if an error occurs during TCP BTL wireup.

Finally, I'll likely be adding a feature in the TCP BTL wireup: a brief handshake right after the initial connect/accept to pass a magic number to ensure that the peer is actually Open MPI (vs. some other random entity that happens to connect to my listening socket).  Ralph suggested today on the engineering call to use the version number info in the modex to check for compatible versions.

**Comment by jsquyres** [comment]
I'm throwing this to IBM @gpaulsen @dsolt.  Do you guys care?

**Comment by gpaulsen** [comment]
did this get into master?
Yes, extra debug info is always a good thing, unless it affects performance. :)

**Comment by jsquyres** [comment]
The bitbucket that the mailing list post refers to is quite stale -- it was never directly brought back into master.

However, I think that various people have put in at least *some* of those features over time (e.g., I think @rhc54 or @bosilca put in some kind of magic number handshake...?).

It might not be a bad idea to compare the content of the commit that was cited (https://bitbucket.org/jsquyres/tcp-debug-printf/commits/9efe756cda30/) and see if similar functionality was put in.  And then make a new PR with whatever functionality was not put in.

One thing to be aware of, and one reason I never got around to finishing the work: using blocking sends/receives to exchange the magic number handshake stuff is a bad idea.  It is conceivable that some agent could connect to a TCL BTL listening socket and send fewer bytes than is required by the magic number handshake, but then never disconnect.  This would effectively hang the OMPI TCP BTL receiver in the blocking receive forever.  Something a little more clever needs to be done to effect a magic number handshake robustly.

**Comment by mohanasudhan** [comment]
Can we close this issue based on recent PR? let me know if you need anything more. Thx

**Comment by bwbarrett** [comment]
@mohanasudhan, if you think you covered the issues, go ahead and close.

**Comment by mohanasudhan** [comment]
closing this issue as per #3955
