### ISSUE TITLE
OSHMEM installs man pages even if --disable-oshmem is used

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#850]
@miked-mellanox @jladd-mlnx Can someone at Mellanox have a look?

Thanks.

**Comment by miked-mellanox** [comment]
@igor-ivanov - could you please take a look. thanks

**Comment by hppritcha** [comment]
@igor-ivanov can this issue be closed?

**Comment by igor-ivanov** [comment]
@hppritcha yes
