### ISSUE TITLE
Build with lustre headers breaks Open MPI

### ISSUE THREAD

**Issue by bertwesarg** [open-mpi/ompi#8508]
I can trigger this bug:

- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898743

with an Open MPI 4.0.5 build on Ubuntu 20.04/amd64 in file ompi/mca/fs/lustre/fs_lustre.c.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

- lustre package 2.14.0 (https://downloads.whamcloud.com/public/lustre/lustre-2.14.0/ubuntu2004/client)
- UCX 1.9.0
  - `./contrib/configure-release --prefix=/usr/local --enable-devel-headers`
- Open MPI 4.0.5
  - `../configure --prefix=/usr/local`

### Please describe the system on which you are running

* Operating system/version: Ubuntu 20.04
* Computer hardware: amd64

**Comment by bertwesarg** [comment]
@blastmaster

**Comment by edgargabriel** [comment]
@bertwesarg thank you for the report, any chance that you can post the actual error message along with the configure output of the lustre section? I Don't have access right now to lustre 2.14.0, but will see whether we can recreate the error somewhere

**Comment by bertwesarg** [comment]
I do not have the error handy, though its the same as the one in the debian bug. The file `ompi/mca/fs/lustre/fs_lustre.c` includes through some other files `linux/lustre/lustre_user.h`, which does include `linux/fs.h`. It also includes `sys/mount.h` directly. I can also reproduce the error directly with the mini-example in the bug report, not lustre or Open MPI involved. My fix for Open MPI was to `#undef` all `MS_*` defines before the `#include <sys/mount.h>`. Though not sure, if this is a proper fix.

**Comment by edgargabriel** [comment]
I looked at the debian bug that you linked to , but I am honestly not sure what to do about that, since (as you pointed out) it is not really an Open MPI issue the way it looks. You are basically saying that the order of include statements matters, or we should add some #undef statements for some versions of libc?

**Comment by bertwesarg** [comment]
Actually, I cannt find a reason, why `sys/mount.h` needs to be included in this file in the first place. The same may also true for all the other `sys/` headers. I may get to check, which header is actually needed.

**Comment by edgargabriel** [comment]
the code that was using some of that functionality has migrated to fs/base/fs_base_get_parent_dir.c 
so the include statements might be in fact pointless in the lustre fs component. They are however also there in the fs_base_get_parent_dir.c

**Comment by bertwesarg** [comment]
but this does not include the `linux/fs.h` header via the lustre include

**Comment by edgargabriel** [comment]
So does removing the following block:

```
#ifdef HAVE_SYS_STATFS_H
#include <sys/statfs.h> /* or <sys/vfs.h> */
#endif
#ifdef HAVE_SYS_PARAM_H
#include <sys/param.h>
#endif
#ifdef HAVE_SYS_MOUNT_H
#include <sys/mount.h>
#endif
#ifdef HAVE_SYS_STAT_H
#include <sys/stat.h>
#endif
```

from fs_lustre.c resolve the problems? If it does, that is an easy fix that we can apply!

**Comment by bertwesarg** [comment]
Open MPI 4.0.5 builds when removing all `sys/` includes. Will create a PR.
