### ISSUE TITLE
Issue: A call to mkdir was unable to create the desired directory

### ISSUE THREAD

**Issue by KineticTheory** [open-mpi/ompi#8510]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.0.5

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Installed by the sysadmin, presumably from a distribution tarball.

### Please describe the system on which you are running

* Operating system/version: Red Hat Enterprise Linux 8.1 (Ootpa)
* Computer hardware: ARM cavium (ThunderX2-B0-CN9980-2200LG4077-ES-Y-G)
* Network type: Stand alone; tcpip is available but not used for this case.

I'm seeing this same issue on x86_64 and Power9 platforms as well, but it is more prevalent on ARM.

-----------------------------

## Details of the problem

I'm having trouble running several small MPI jobs _simultaneously_ on a single node.  We do this 'packed-the-node' type of testing for CI and regression tests.  For example, I might run **ten** 4-rank MPI jobs simultaneously on a node with 40 cores.  We use Kitware's CTest to manage when jobs start. This workflow allows us to run about 1000 small rank MPI jobs in 10 minutes.  However, this pattern seems to cause OpenMPI to fail. 

When running as described above, we frequently, we encounter this error:

```
--------------------------------------------------------------------------
A call to mkdir was unable to create the desired directory:

  Directory: /tmp/ompi.cn809.2017
  Error:     File exists

Please check to ensure you have adequate permissions to perform
the desired operation.
--------------------------------------------------------------------------
[cn809:402438] [[5812,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 107
[cn809:402438] [[5812,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 346
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_session_dir failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
```

The launch command typically looks like: `mpirun -bind-to none -n 4 app.x`

For this system, the `/tmp` directory is purged after each SLURM allocation is released and is clean when I start my jobs. The specific directory name selected by OpenMPI contains a node name (cn809) and my user id (2017).  Since I have exclusive access to this node during my allocation, I am the only person with read/write access to this directory.

I don't know the OpenMPI code logic, but presumably, this directory is being created for one mpi job while another mpi job is cleaning up.  With out any type of atomic checks in the `opal_os_dirpath_create`, this condition seems likely to occur and might be the root cause of the error above.  Can someone confirm this diagnosis?  What can be done to avoid this error while allowing multiple `mpirun` jobs to run simultaneously on a node?

**Comment by hppritcha** [comment]
@KineticTheory are you building OMPI via spack?  I could try to provide you a patch file via a spack PR if that's the case.

**Comment by KineticTheory** [comment]
> @KineticTheory are you building OMPI via spack? I could try to provide you a patch file via a spack PR if that's the case.

No, I'm not building it myself.  I'm using pre-installed versions provided on Darwin.  But thanks for the offer!

If you have a potential work around, we could ask Dave to provide a friendly-user testing version for me to try.

**Comment by rhc54** [comment]
It looks like the code in v4.0.x is slightly out-of-date - the code in OMPI master adds the PID to the directory name to avoid this conflict.

**Comment by KineticTheory** [comment]
> It looks like the code in v4.0.x is slightly out-of-date - the code in OMPI master adds the PID to the directory name to avoid this conflict.

I think the version I'm using has this PID extension.  I also see failures of the form:
```
A call to mkdir was unable to create the desired directory:

  Directory: /tmp/ompi.cn809.2017/pid.402429
  Error:     No such file or directory
```

**Comment by rhc54** [comment]
The odds of a pid collision are minuscule - is there some permission issue getting in the way?

**Comment by KineticTheory** [comment]
> The odds of a pid collision are minuscule - is there some permission issue getting in the way?

Agreed.  I'm only running about 1000 jobs so it is hard to imagine that this is the issue. Does OpenMPI attempt to remove the parent directory (eg. `/tmp/ompi.cn809.2017`) directory after each job?  That could cause a conflict.

I can't see how there could be a permissions issue.  The `/tmp` filespace is a ram disk that is created new for each SLURM allocation. I will try pointing OpenMPI to a different filesystem to see if that helps.  Is `--mca orte_tmpdir_base <dir>` the best way to do this?

**Comment by rhc54** [comment]
>  Is --mca orte_tmpdir_base <dir> the best way to do this?

Yep

> Does OpenMPI attempt to remove the parent directory (eg. /tmp/ompi.cn809.2017) directory after each job? 

Yes, each `mpirun` is trying to do that by checking to see if the directory is empty underneath it. We probably need to do a `flock` or something to provide better protection. In the interim, you could provide a unique top-level dir for each run (I know that's annoying). Something like `/tmp/jobnumberstring` for `orte_tmpdir_base` would suffice

**Comment by KineticTheory** [comment]
I think using tmp directories of the form `/tmp/ompi.cn809.2017-pid.402429` might solve my issue (no parent directory).  I'm not sure `flock` would be needed with completely separate tmp directories per process.

**Comment by rhc54** [comment]
It wouldn't, but OMPI doesn't do that for a reason. It leads to cleanup problems for sys admins when they are in environments where completely blasting `/tmp` between jobs isn't an option and it is more convenient to be able to clobber any stale session directories if they have a user-based name.

**Comment by rhc54** [comment]
Your "hack" sounds like the correct solution for that scenario. Please reopen if you require anything further.

**Comment by pramodk** [comment]
I am seeing same issue in [our Github Actions CI](https://github.com/neuronsimulator/nrn/actions/runs/3562304491/jobs/5983925338). Is there any other option than encoding "hack" mentioned above?

Having such workaround for multiple projects especially via CMake is not convenient. As the issue is closed, I am wondering if this behaviour will be changed in future releases.

**Comment by KineticTheory** [comment]
@pramodk This is fixed in the latest versions of `openmpi`.  We are using version 4.1.1 and no longer encounter this issue.

**Comment by pramodk** [comment]
Ok. In our CI on MacOS, I see brew installed version `4.1.4`:

```console
-- Found MPI_C: /usr/local/Cellar/open-mpi/4.1.4_2/lib/libmpi.dylib (found version "3.1") 
[222](https://github.com/neuronsimulator/nrn/actions/runs/3569674567/jobs/5999862916#step:16:223)
-- Found MPI_CXX: /usr/local/Cellar/open-mpi/4.1.4_2/lib/libmpi.dylib (found version "3.1") 
[223](https://github.com/neuronsimulator/nrn/actions/runs/3569674567/jobs/5999862916#step:16:224)
-- Found MPI: TRUE (found version "3.1")  
[224](https://github.com/neuronsimulator/nrn/actions/runs/3569674567/jobs/5999862916#step:16:225)
-- Detected OpenMPI 4.1.4
```

and still has errors like below [here](https://github.com/neuronsimulator/nrn/actions/runs/3569674567/jobs/5999862916#step:16:2361):

![image](https://user-images.githubusercontent.com/666852/204455543-853ab1c9-b811-4e9b-a777-2433fff882e5.png)

**Comment by rhc54** [comment]
That's a different problem that is unique to the Mac. A while back, Apple decided to make the default tmpdir something with a very long name. When we add that long "ompi.xxx" directory and filename to the end of it, the result is too long for the Mac.

What you need to do is set your `TMPDIR` envar to point to a tmpdir that has a shorter name. We typically use just our home directory and create a "tmp" there, and then set `TMPDIR=<home>/tmp` in the environment.

**Comment by pramodk** [comment]
thank you @rhc54 for pointing that out! I have incorporated workaround in our CI. Will update here if I see any other related issue.
