### ISSUE TITLE
Default set "ompi_mpi_yield_when_idle" when configuring for user-level threads

### ISSUE THREAD

**Issue by janciesko** [open-mpi/ompi#8526]
When OMPI is configured for ULT and no ompi_mpi_yield_when_idle is passed at runtime, the progress thread is not guaranteed to progress and the app deadlocks. The association between using ULTs and setting this option might not be always clear to the user.
Solution: set default to true when configuring with non pthread threading mca.
Affects progress thread only.

**Comment by shintaro-iwasaki** [comment]
Thanks. This make sense. If this change won't affect the default behavior of Open MPI (i.e., when a ULT is not used), I guess this patch is reasonably acceptable. Will you write a patch for it? If not, I can write a patch and create a PR for this (please give me a week or so).

**Comment by devreal** [comment]
@janciesko There is a constant `OPAL_THREAD_YIELD_WHEN_IDLE_DEFAULT` that should control whether yielding is enabled by default (set to true for the ULT backends). That is not working? Or am I confusing something here?

**Comment by janciesko** [comment]
I just saw it, yes, this resolves the issue.
