### ISSUE TITLE
Open MPI throws error while unlinking internal file

### ISSUE THREAD

**Issue by dmitry-kabanov** [open-mpi/ompi#8531]
Thank you for taking the time to submit an issue!

## Background information
I have a Python script that works over `Open MPI` and `mpi4py`. After script finishes, an error is thrown "No such file or directory", with the file being some file created by `Open MPI` for internal needs.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
```
❯ mpirun --version                                                                               
mpirun (Open MPI) 4.0.5
```

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
I've installed Open MPI with Homebrew on macOS Big sur.

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
N/A

### Please describe the system on which you are running

* Operating system/version: macOS 11.1 (20C69)
* Computer hardware: iMac Pro (2017)
* Network type: localhost

-----------------------------

## Details of the problem

I have a python script working over OpenMPI and `mpi4py`. When script finishes, an error message is thrown:

```
Saving cross-validated predictions of AveragingWindfield to _output/cv-predictions-aver.csv
--------------------------------------------------------------------------
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  feynman.uq.rwth-aachen.de
  System call: unlink(2) /var/folders/qv/bqrbht6n6q3dhq0503j2ly_w0000gp/T//ompi.feynman.502/pid.75838/1/vader_segment.feynman.d4950001.3
  Error:       No such file or directory (errno 2)
--------------------------------------------------------------------------
[feynman.uq.rwth-aachen.de:75838] 3 more processes have sent help message help-opal-shmem-mmap.txt / sys call fail
[feynman.uq.rwth-aachen.de:75838] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

This error does not have anything to do with my Python script, as the message "Saving cross-validated..." is basically the last message in this script (followed by actually save of the file).

I noticed that in the path `/var/folders/qv/bqrbht6n6q3dhq0503j2ly_w0000gp/T//ompi.feynman.502/pid.75838/1/vader_segment.feynman.d4950001.3`, directory `pid.75838` does not exist.

**Comment by yiqiangjizhang** [comment]
I solve it using these commands in this issue:
(The one that worked for me is the last one)

See:
https://github.com/Microsoft/WSL/issues/3397#issuecomment-417876710

Try this:
$ echo 0 > /proc/sys/kernel/yama/ptrace_scope
or
$ sudo echo 0 > /proc/sys/kernel/yama/ptrace_scope
or
$ echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope

**Comment by dmitry-kabanov** [comment]
@yiqiangjizhang I work in macOS, these commands are not applicable. But anyway, thanks!

**Comment by hppritcha** [comment]
@dmitry-kabanov does your script invoke mpirun multiple times or do you invoke the script within another script that ends up effectively running mpirun's back to back?

**Comment by dmitry-kabanov** [comment]
@hppritcha I run `mpirun` from terminal (precisely, under tmux) using the following command:

    mpirun -n 4 python -m mpi4py.futures run-with-different-learning-rates.py

which is a python script that does not explicitly invoke any other `mpirun`s.

**Comment by rhc54** [comment]
There is a known problem on Mac ever since they moved user tmp directories to an absurdly long pathname. Try adding a "tmp" directory under your home, and then export TMPDIR to point there.


On Mar 29, 2021, at 2:50 PM, Dmitry Kabanov ***@***.*** ***@***.***> > wrote:


@hppritcha I run mpirun from terminal (precisely, under tmux) using the following command:


mpirun -n 4 python -m mpi4py.futures run-with-different-learning-rates.py


which is a python script that does not explicitly invoke any other mpiruns.

**Comment by hppritcha** [comment]
@dmitry-kabanov can you try @rhc54 suggestion about setting TMPDIR?

**Comment by hppritcha** [comment]
closing.  please reopen if TMPDIR workaround doesn't help.

**Comment by kitchenknif** [comment]
Ran into this issue on OpenMPI 4.1.4 installed via homebrew on a M1 macbook pro running macOS Monterey.

TMPDIR is set to ~/tmp

I am running a [MEEP](https://github.com/NanoComp/meep/) script using mpirun (`mpirun -n 3 python3 script.py`).

If I run using a single process, I don't run into any errors, but running with more than one, I get the error
```
--------------------------------------------------------------------------
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  MacBook-Pro.local
  System call: unlink(2) /Users/pavel/tmp/ompi.MacBook-Pro.501/pid.4533/1/vader_segment.MacBook-Pro.501.50d80001.5
  Error:       No such file or directory (errno 2)
--------------------------------------------------------------------------
```

At more than one process, the error starts popping up, but only leads to data loss at 6 or 7 processes, but I'm not sure that this is a hard rule.
