### ISSUE TITLE
UCX symbol error

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#8542]
When building master HEAD with UCX 1.9.0, I get a symbol error with the `mxa_atomic_ucx.so` component:

```
$ oshmem_info|& grep atomic
[mpi013:06230] mca_base_component_repository_open: unable to open mca_atomic_ucx: /home/jsquyres/bogus/lib/openmpi/mca_atomic_ucx.so: undefined symbol: mca_spml_ucx (ignored)
```

FYI @open-mpi/ucx

**Comment by gpaulsen** [comment]
We believe this issue can also be hit on v40.x and v4.1.x.  @hppritcha believe he's seen this on v4.0.x, and @hoopoepg says from a code point of view those branches should also be affected.

Please PR to v4.0.x and v4.1.x after it's been merged to master.   Thanks!

**Comment by hoopoepg** [comment]
yep, I will check on 4.x branches if it is affected and apply fix if needed.
but preliminary conclusion is OMPI v 4.x are affected too
