### ISSUE TITLE
ORTE [[14412,0],0] FORCE-TERMINATE AT (null):1 - error plm_slurm_module.c(471)

### ISSUE THREAD

**Issue by danecross** [open-mpi/ompi#8554]
Hello, 

I got this strange error when trying to run an executable (made from [this github](https://bitbucket.org/phopkins/gizmo-public/src/master/)) on a Cray XC40 supercomputer using slurm. I am ssh'ing to a SUSE Linux Enterprise Server 15 SP1. Here is a list of the modules I have loaded, including the openmpi module version 4.0.4:

- intel/19.0.5                
- craype/2.7.3             
- craype-network-aries    
- cray-libsci/20.09.1     
- pmi/5.0.17              
- atp/3.8.1               
- perftools-base/20.10.0
- PrgEnv-intel/6.0.9
- gsl/2.6
- cray-hdf5/1.12.0.0
- cray-fftw/3.3.8.8
- pmi-lib/5.0.17
- openmpi/intel/4.0.4

I attached the error file below:
[err.txt](https://github.com/open-mpi/ompi/files/6084606/err.txt)

Let me know if you need any other information!

Dane

**Comment by jsquyres** [comment]
Greetings @danecross.  I think the error message is telling you what is wrong:

```
The SLURM process starter for OpenMPI was unable to locate a
usable "srun" command in its path. Please check your path
and try again.
```

Open MPI uses the SLURM `srun` command to launch processes in the SLURM environment.  In your case, it looks like it couldn't find that command.  You might want to check that environment modules you've loaded and/or otherwise set the PATH to find `srun`.

**Comment by rhc54** [comment]
Please reopen if setting the PATH to include `srun` didn't fix the problem.

**Comment by srinivamd** [comment]
setting allow setuid to `no` in singularity.conf resolved it.

**Comment by srinivamd** [comment]
@rhc54 We are seeing the same error message cited in this issue on RHEL8 and CentOS8 compute nodes running singularity image which has application and MPI libraries included. The same singularity image works fine on Ubuntu compute nodes. Slurm 22.05.4.1.
No module loaded as environment is contained in the container.
The `srun` is in the `PATH` as simply running `which srun` finds it. Non MPI applications run fine.
Searching the web found many hits but none helpful.
Built `openpmi v4.2.1` and installed it.
Is there any other OS configuration, firewall, etc. that needs to configured properly to address this error?

**Comment by rhc54** [comment]
Not sure I fully understand your scenario. Are you saying you have Slurm in the singularity container? It so, that would seem odd. Or are you saying you have Slurm external to the singularity image, mpirun is internal to the image, and...is mpirun trying to start the images?

Could you please explain how you are attempting to launch this job?

**Comment by srinivamd** [comment]
@rhc54 Sorry for the lack of info. And thank you for your quick response!
We have slurm installed on the compute node. From the login node, we run `sbatch` to submit run the `singularity` image of the application `rochpl` which is built with its own `openmpi`. The `sbatch` file has this `singularity run` command:
```
singularity run /shared/apps/bin/rochpl_5.0.5_49.sif  mpirun_rochpl -P 2 -Q 4 -N 256000 --NB 512
```
The same `sbatch` file when submitted to a compute node running `Ubuntu 22` or `SLES15 SP4` runs the `singularity` contained application correctly. But, when submitted to a compute node running RHEL 8, we get this error:
```
--------------------------------------------------------------------------
The SLURM process starter for OpenMPI was unable to locate a
usable "srun" command in its path. Please check your path
and try again.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[545,0],0] FORCE-TERMINATE AT (null):1 - error ../../../../../orte/mca/plm/slurm/plm_slurm_module.c(475)

This is something that should be reported to the developers.
--------------------------------------------------------------------------
```
Wondering whether the above error indicates some sort of setup issue.
@ozziemoreno @sidamd Tagging my teammates

**Comment by rhc54** [comment]
It has been ages since I used singularity, and nearly as long since I used srun, so forgive my poor memory. I take it that sbatch gets an allocation for you and then executes one instance of your cmd line. The "singularity" on the cmd line instantiates one instance of the specified singularity image, executing your `mpirjn_rochpl` wrapper (which is inside the container) that does some kind of cmd line mashing before calling mpirun.

Is that accurate?

If so, then does your wrapper kickoff singularity on the remote nodes? Or is mpirun supposed to be doing it? Or is sbatch doing it?

I'm poking because I'm trying to understand where mpirun should be finding srun. My guess is that the singularity permissions on RHEL 8 are different from the other environments, thus precluding mpirun from seeing the srun outside the container (and mpirun is inside it). It could also be some other problem as ORTE error messages aren't always completely accurate as to the problem (other than that something went wrong).

**Comment by srinivamd** [comment]
> Is that accurate?

Yes, that is correct.

> If so, then does your wrapper kickoff singularity on the remote nodes? Or is mpirun supposed to be doing it? Or is sbatch doing it?

I missed some details. The sbatch is set up to run on a single node.
```
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
```
The `srun` and other commands are under `/usr/bin` on each node. The `mpirun` inside the container does not look for `srun` as we can run the `singularity` command by itself from the command line on any host (without `slurm`)

**Comment by rhc54** [comment]
Guess I'm confused by your last statement - mpirun is clearly looking for srun:
```
--------------------------------------------------------------------------
The SLURM process starter for OpenMPI was unable to locate a
usable "srun" command in its path. Please check your path
and try again.
--------------------------------------------------------------------------
```
You might try adding `--mca plm ^slurm` to your mpirun cmd line in your wrapper, or putting `OMPI_MCA_plm=^slurm` in your environment so it doesn't try to use srun.

**Comment by srinivamd** [comment]
Thanks @rhc54  I tried adding `--mac plm ^slurm` but it didn't help.

The error happens when running `singularity run` after `salloc` also. We are debugging it more, and thank you for your helpful suggestions. Here's the `salloc` console log:
```
$ salloc -w smc-r07-07 -p 2P8G2H_MI210_RHEL8 --exclusive --mem=0 --gres=gpu:8
salloc: Granted job allocation 10776
salloc: Waiting for resource configuration
salloc: Nodes smc-r07-07 are ready for job
$ singularity run /shared/apps/bin/rochpl_5.0.5_49.sif mpirun_rochpl -P 2 -Q 4 -N 256000 --NB 512
INFO:    Converting SIF file to temporary sandbox...
--------------------------------------------------------------------------
The SLURM process starter for OpenMPI was unable to locate a
usable "srun" command in its path. Please check your path
and try again.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[22468,0],0] FORCE-TERMINATE AT (null):1 - error ../../../../../orte/mca/plm/slurm/plm_slurm_module.c(475)

This is something that should be reported to the developers.
--------------------------------------------------------------------------
INFO:    Cleaning up image...
$ echo $PATH
/usr/share/Modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
$ which srun
/usr/bin/srun
```

**Comment by srinivamd** [comment]
@rhc54 
Tracing shows the failing case has `orte_ifislocal` going to `opal_ifislocal` which is not in the passing case. `LD_DEBUG=all` trace snippet:
Fail
```
    414089:     symbol=orte_ifislocal;  lookup in file=/opt/rochpl/tpl/openmpi/bin/mpiexec [0]
    414089:     symbol=orte_ifislocal;  lookup in file=/opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0]
    414089:     binding file /opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0] to /opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0]: normal symbol `orte_ifislocal'
    414089:     symbol=opal_ifislocal;  lookup in file=/opt/rochpl/tpl/openmpi/bin/mpiexec [0]
    414089:     symbol=opal_ifislocal;  lookup in file=/opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0]
    414089:     symbol=opal_ifislocal;  lookup in file=/opt/rochpl/tpl/openmpi/build/../lib/libopen-pal.so.40 [0]
    414089:     binding file /opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0] to /opt/rochpl/tpl/openmpi/build/../lib/libopen-pal.so.40 [0]: normal symbol `opal_ifislocal'
    414089:     symbol=opal_ifaddrtoname;  lookup in file=/opt/rochpl/tpl/openmpi/bin/mpiexec [0]
    414089:     symbol=opal_ifaddrtoname;  lookup in file=/opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0]
    414089:     symbol=opal_ifaddrtoname;  lookup in file=/opt/rochpl/tpl/openmpi/build/../lib/libopen-pal.so.40 [0]

```
PASS
```
   507460:     symbol=orte_ifislocal;  lookup in file=/opt/rochpl/tpl/openmpi/bin/mpiexec [0]
    507460:     symbol=orte_ifislocal;  lookup in file=/opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0]
    507460:     binding file /opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0] to /opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0]: normal symbol `orte_ifislocal'
    507460:     symbol=orte_get_job_data_object;  lookup in file=/opt/rochpl/tpl/openmpi/bin/mpiexec [0]
    507460:     symbol=orte_get_job_data_object;  lookup in file=/opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0]
    507460:     binding file /opt/rochpl/tpl/openmpi/build/../lib/openmpi/mca_plm_slurm.so [0] to /opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0]: normal symbol `orte_get_job_data_object'
    507460:     symbol=orte_plm_base_setup_virtual_machine;  lookup in file=/opt/rochpl/tpl/openmpi/bin/mpiexec [0]
    507460:     symbol=orte_plm_base_setup_virtual_machine;  lookup in file=/opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0]
    507460:     binding file /opt/rochpl/tpl/openmpi/build/../lib/openmpi/mca_plm_slurm.so [0] to /opt/rochpl/tpl/openmpi/build/../lib/libopen-rte.so.40 [0]: normal symbol `orte_plm_base_setup_virtual_machine'
```
Not sure whether the above helps but that is the first point of deviation. We cloned/duplicated the RHEL8 disk and booted up another host, different IP with it. The node running the cloned disk has the PASS codepath and is able to run the `singularity` container as expected. All the libraries were built on the original host, then cloned: could some library have hardcoded host info that the cloned host is immune to? Confusing!

**Comment by srinivamd** [comment]
Got it working now.
Apparently, the hostname returned by `gethostname` was uppercase that failed addr resolution. Set hostname using `hostnamectl set-hostname` to lowercase name and it works now.
Thank you @rhc54  for your responses and helpful suggestions!

**Comment by RobbieTheK** [comment]
We are getting this error as well and have a similar environment to @srinivamd 

Based on the [LBPM container in Nvidia's catalog](https://catalog.ngc.nvidia.com/orgs/hpc/containers/lbpm)
`singularity run --nv -B $BENCHMARK_DIR:/benchmark --pwd /benchmark docker://nvcr.io/hpc/lbpm:2020.10 ./run.sh`

Where `run.sh` has:
```
#!/bin/bash
export GPU_ARCH="sm70" # Valid options are: sm60, sm70, sm75, sm80
export LBPM_DIR=/usr/local/LBPM_$GPU_ARCH/
mpirun --allow-run-as-root -np 1 -mca pml ucx -x UCX_TLS=sm,cuda_copy -report-bindings --tag-output \
$LBPM_DIR/bin/lbpm_color_simulator input.db
```
We get:

```
INFO legacy OFED driver set: 4.9-0.1.7.0          
--------------------------------------------------------------------------
The SLURM process starter for OpenMPI was unable to locate a
usable "srun" command in its path. Please check your path
and try again.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[53800,0],0] FORCE-TERMINATE AT (null):1 - error plm_slurm_module.c(475)
```

If I add `--mca plm ^slurm`: 

```
bash: orted: command not found
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).

```

```
mpirun --version
mpirun (Open MPI) 4.0.3rc4
```
` NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7  `

**Comment by rhc54** [comment]
Believe this has been answered if you look at the comment one above yours.

**Comment by RobbieTheK** [comment]
> Believe this has been answered if you look at the comment one above yours.

Where would I be checking for hostname?

**Comment by srinivamd** [comment]
> > Believe this has been answered if you look at the comment one above yours.
> 
> Where would I be checking for hostname?

@RobbieTheK  Check `/etc/hosts` for an entry for `hostname` output. In my case, the entry had uppercase and after fixing the hostname to be lowercase, the host name resolution worked, and got past the problem. Hope that helps.

**Comment by srinivamd** [comment]
> I saw you used `LD_DEBUG=all` were there other debugging options you used?

I traced the failure, used `strace` to `ifislocal` call that failed which caused that strange failure message.

Regarding uppercase or lowercase in hostname, I used this small test on the host, compute/worker node to debug:
```
#include <stdio.h>
#include <unistd.h>
#include <sys/socket.h>

int main()
{
int rc;
char hostname[50];
rc = gethostname(hostname,sizeof(hostname));
if(rc == 0){
  printf("hostname = %s\n",hostname);
}
return 0;
}
```
It is similar to what the `ifislocal` function does.
