### ISSUE TITLE
Compilation error OPAL_VAR_SCOPE_PUSH called on "PMIX_VERSION which is already defined

### ISSUE THREAD

**Issue by aicampbell** [open-mpi/ompi#8562]
Hi, I'm trying to compile openMPI 4.1.0 for a SLURM environment on Ubuntu 20.04.

I have tried a simple configure to start with like this:  
```shell
./configure --with-slurm --prefix=/home/aicampbell/openmpi-4.1.0/build
```
 
but I get the following error:

`--- MCA component pmix:pmix3x (m4 configuration macro)
checking for MCA component pmix:pmix3x compile mode... dso
configure: WARNING: Found configure shell variable clash at line 170105!
configure: WARNING: OPAL_VAR_SCOPE_PUSH called on "PMIX_VERSION",
configure: WARNING: but it is already defined with value "3.1.5"
configure: WARNING: This usually indicates an error in configure.
configure: error: Cannot continue
`

I have also tried this thinking it couldn't find the right pmix version on the system:
```shell
./configure --with-slurm --prefix=/home/aicampbell/openmpi-4.1.0/build --with-pmix=/usr/lib/x86_64-linux-gnu/pmix 
```

Is there something I'm doing wrong or forgetting?
Many thanks  
Here are the PMIX variables set:
```shell
env | grep PMIX
PMIX_HOSTNAME=somehost
PMIX_SECURITY_MODE=native
PMIX_GDS_MODULE=ds21,ds12,hash
PMIX_SYSTEM_TMPDIR=/tmp
PMIX_BFROP_BUFFER_TYPE=PMIX_BFROP_BUFFER_NON_DESC
PMIX_PTL_MODULE=tcp,usock
PMIX_DSTORE_21_BASE_PATH=/var/lib/slurm-llnl/slurmd/pmix.924450.0//pmix_dstor_ds21_2110860
PMIX_VERSION=3.1.5
SLURM_PMIX_MAPPING_SERV=(vector,(0,1,1))
PMIX_RANK=0
PMIX_SERVER_URI2=pmix-server.2110860;tcp4://127.0.0.1:58897
PMIX_SERVER_URI3=pmix-server.2110860;tcp4://127.0.0.1:58897
PMIX_SERVER_URI21=pmix-server.2110860;tcp4://127.0.0.1:58897
PMIX_DSTORE_ESH_BASE_PATH=/var/lib/slurm-llnl/slurmd/pmix.924450.0//pmix_dstor_ds12_2110860
PMIX_SERVER_TMPDIR=/var/lib/slurm-llnl/slurmd/pmix.924450.0/
PMIX_NAMESPACE=slurm.pmix.924450.0

```

**Comment by rhc54** [comment]
I'm puzzled as to how all those PMIx variables got set. Did you `srun ./configure ...`? Or are you configuring from within a `salloc` allocation?

**Comment by aicampbell** [comment]
I created an interactive job so that I could compile openmpi on the node.

`srun -n 1 --pty bash -i`

Sshing to the node as root doesn't have the variable set. I cant ssh to the node directly as my user.

**Comment by jsquyres** [comment]
Our build system has some rudimentary error checks to prevent some shell scripting mistakes.  The problem you're running in to is that a shell variable that is set by SLURM is also being used by Open MPI's `configure` script, and that's tripping one of our error checks.

It looks like we never anticipated building Open MPI in a SLURM environment.  😄 

The quick/easy fix is to unset at least `PMIX_VERSION` before running `configure`.  I don't know if you'll run into other `PMIX_*` variable error checks as well, but the solution should be the same for all of them.
