### ISSUE TITLE
ompi/datatype: performance regression in mpi reduce collective

### ISSUE THREAD

**Issue by AboorvaDevarajan** [open-mpi/ompi#8568]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
`ompi - master`

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
`git clone`

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
```
git submodule status
-517d954a4a3929fe27e69f35cbe00a419c143dbf 3rd-party/openpmix
-67addf25843e7765d6aee19b51a3165d08a9eace 3rd-party/prrte
```

### Please describe the system on which you are running

* Operating system/version: RHEL8
* Computer hardware: ppc64le
* Network type: IB

-----------------------------

##Details of the issue

There is a performance degradation of around 40%  seen in the reduce collectives.

List of tests that are regressed: (in ompi-tests/ibm test suite)
``` 
reduce_scatter_nocommute_stride_in_place
reduce_scatter_nocommute_stride
reduce_nocommute_stride_in_place
```

Looks like the performance regression is seen after this patch is merged due to additional `cuGetPointerAttribute` checks that is introduced which is expensive.
https://github.com/open-mpi/ompi/pull/8007

Here is the execution time difference with and without the patch for `reduce_scatter_nocommute_stride_in_place` test.

```
Current master branch:

real 12m38.018s 
user 502m13.207s
sys 0m20.600s

After reverting the patch:

real 8m46.316s
user 348m29.361s
sys 0m21.723s
```

Here is a probable fix: https://github.com/open-mpi/ompi/pull/8569

**Comment by jsquyres** [comment]
This has been fixed / #8569 has been merged.
