### ISSUE TITLE
btl/vader performance regression (that can be observed on fat nodes)

### ISSUE THREAD

**Issue by ggouaillardet** [open-mpi/ompi#8603]
Following the discussion on the ML related to a performance regression between Open MPI 3.1.1 and 4.1.0,
here are my findings:

The performance regression can be observed on fat nodes with the fftw builtin benchmark and the following command line

```
mpirun --map-by core --rank-by core --bind-to core --mca pml ob1 --mca btl vader,self  ./mpi-bench -opatient -r1000 -s icf1000000
```

`git bisect` pointed me to open-mpi/ompi@7c8a1fb437

I ran this on a quad socket intel node with 18 cores per socket.
At 112 cores, the degradation is over 15%

![vader](https://user-images.githubusercontent.com/7233259/111064049-4c7c4a80-84f5-11eb-82ae-a14c9624349b.png)

If I read the commit message between the lines, the workaround that is needed for gcc < 6 was applied on all x86_64 based on the assumption it does not introduce any performance penalty.
The data above show otherwise, so we might want to improve this, for example by only applying the workaround for gcc < 6, or by **not** applying it for gcc >= 6 (depending on how we want to treat non GNU compilers)

@hjelmn could you please comment on this issue?

**Comment by BiplabRaut** [comment]
Although originally I reported the performance regression between Open MPI 3.1.1 and 4.1.0 when using GCC compiler, now I have found that AMD's AOCC (based on llvm/clang version 12) compiler also has this regression.
So, I am just wondering if there is more than just this commit 7c8a1fb that is causing this regression.

On a separate topic, it is also found by me that openMPI v4.1.0 is not getting compiled with llvm/clang - I checked with the compiler version 12. There are errors related to AVX512  ISA support. Does openMPI4.1.0 by default try to compile AVX512 without checking compiler support flags?
Older version openMPI4.0.5 could be compiled with llvm/clang.

**Comment by ggouaillardet** [comment]
the workaround for gcc<6 bug is applied on x86_64 regardless the compiler that is used, so I am not surprised there is a similar regression with AOCC.

several changes were made to `op/avx` (that can use AVX512 instructions), so I strongly encourage you to try the latest `4.1.1rc1` and see if it helps.
If not, please open a new issue with the required information.

**Comment by hjelmn** [comment]
clang also exposes gcc built-ins. So, this is expected. Someone should just change the problematic code to match the x86_64 atomics when on that architecture and PR it to v4.0.x and v4.1.x. I can review but I don't have the time right now to test the fix as my primary Open MPI development machine is not running x86.

**Comment by BiplabRaut** [comment]
After applying the patch, I thoroughly tested various test cases of FFTW using its in-built benchmark test program.
Many of the test cases, that showed regression previously as compared to openMPI3.1.1, have now improved with significant gains.

However, there are still few test cases where the performance is lower than openMPI3.1.1.
Are there more performance issues in openMPI4.x that need to be discovered?

Please check the below details.

1) For problem size 1024x1024x512 :-
     $   mpirun --map-by core --rank-by core --bind-to core  ./fftw/mpi/mpi-bench -opatient -r500 -s dcif1024x1024x512
     openMPI3.3.1_stock performance -> 147 MFLOPS
     openMPI4.1.0_stock performance -> 137 MFLOPS
     openMPI4.1.0_patch performance -> 137 MFLOPS
2) For problem size 512x512x512 :-
     $   mpirun --map-by core --rank-by core --bind-to core  ./fftw/mpi/mpi-bench -opatient -r500 -s dcif512x512x512
     openMPI3.3.1_stock performance -> 153  MFLOPS
     openMPI4.1.0_stock performance -> 144 MFLOPS
     openMPI4.1.0_patch performance -> 147 MFLOPS

FFTW MPI bench test binary can be compiled from sources https://github.com/amd/amd-fftw OR https://github.com/FFTW/fftw3

**Comment by BiplabRaut** [comment]
Dear Gilles,
                 I tried the inline patch as discussed in https://github.com/open-mpi/ompi/pull/8622#issuecomment-800776864 .

This has fixed the regression completely for the remaining test cases in FFTW MPI in-built test bench - which was persisting even after using the git patch https://patch-diff.githubusercontent.com/raw/open-mpi/ompi/pull/8623.patch as merged by you.
So, it seems there is a performance difference between   __asm__ __volatile__("": : :"memory"); and __atomic_thread_fence (__ATOMIC_ACQUIRE) on x86_64.

I would request you to please make this change and merge it to respective openMPI branches - please intimate if possible whenever that takes place.
I also request you to plan for an early 4.1.1rc2 release at least by June 2021.

**Comment by jsquyres** [comment]
@BiplabRaut @ggouaillardet This has been resolved, right?  Is the fix merged everywhere / should we close this issue?

**Comment by BiplabRaut** [comment]
Hi Jeff,
          The issue has been resolve with the patch https://github.com/open-mpi/ompi/pull/8789. I simply applied the patch and tested it. 
Regarding fix being merged everywhere, @ggouaillardet would know it better.

The issue can be closed from my side. 
Thanks.

**Comment by awlauria** [comment]
#8789 was applied to all release branches:

v5.0.x: https://github.com/open-mpi/ompi/pull/8794
v4.1.x: https://github.com/open-mpi/ompi/pull/8795
v4.0.x: https://github.com/open-mpi/ompi/pull/8796

Thanks - closing.
