### ISSUE TITLE
PSM2 MTL: check for PSM2_REFCOUNT_CAP doesn't obey --with-psm2

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#8651]
The PSM2 MTL configury doesn't take into account non-default PSM2 install locations when checking for PSM2_REFCOUNT_CAP definition in psm2.h.

**Comment by awlauria** [comment]
@hppritcha can this be closed?

**Comment by hppritcha** [comment]
no needs to be PRd over to 5.0.x first on my todo list for today.

**Comment by awlauria** [comment]
@hppritcha I actually already brought it over to v5.0.x here:

https://github.com/open-mpi/ompi/commit/939129fc1ba805fdf2f90742f88244f609690e4b
https://github.com/open-mpi/ompi/pull/8714
