### ISSUE TITLE
mpirun --version/--help segfaulting

### ISSUE THREAD

**Issue by cniethammer** [open-mpi/ompi#8658]
## Background information

> mpirun --version
> Segmentation fault (core dumped)

I guess this is a prrte issue, which we hit here, but as `mpirun` of Open MPI reports the error I'll open the issue here at first place.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
$ git show
commit d18d3f6172ee06087f9452c79a7f8bfb8732c01a (HEAD -> master, origin/master, origin/HEAD)

$ git submodule 
 7145774ed059c9c3eca277805b419a16b8a68ca3 3rd-party/openpmix (v1.1.3-2852-g7145774e)
 284d15d7b9be51c07ae3a3964b1567fde1a106e2 3rd-party/prrte (dev-31005-g284d15d7b9)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

`./configure --with-hcoll=/opt/hcoll/4.6.3125-fc613b79 --with-tm=/opt/pbs --with-ucx=/opt/ucx/1.10.0
`

Running on CentOS 8
gcc (GCC) 10.2.0
autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.16.1
libtool (GNU libtool) 2.4.6

-----------------------------

## Details of the problem

```
(gdb) run --version

(gdb) backtrace 
#0  0x0000000000000000 in ?? ()
#1  0x000000000040515b in prte (argc=<optimized out>, argv=<optimized out>) at prte.c:433
#2  0x00007fffebe777b3 in __libc_start_main () from /lib64/libc.so.6
#3  0x000000000040369e in _start ()

(gdb) 
433              schizo->output_version();

(gdb) print schizo.output_version 
$2 = (prte_schizo_base_module_output_version_fn_t) 0x0
```

**Comment by jjhursey** [comment]
Yeah we saw and fixed this over in PRRTE https://github.com/openpmix/prrte/issues/832
The update that Ralph just pushed to master should resolve it.
