### ISSUE TITLE
Regression: MPI_Info_get_nthkey() broken in master

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#8664]
This is a trivial reproducer:
```python
In [1]: from mpi4py import MPI

In [2]: info = MPI.Info.Create()

In [3]: info.Set('key', 'value')

In [4]: info.Get_nthkey(0)
```
Output:
```
python3: pinfo_get_nthkey.c:97: PMPI_Info_get_nthkey: Assertion `OPAL_OBJ_MAGIC_ID == ((opal_object_t *) (key))->obj_magic_id' failed.
```
See [mpi4py testsuite failure](https://github.com/mpi4py/mpi4py-testing/runs/2160993576?check_suite_focus=true).

**Comment by devreal** [comment]
I just tested this with a recent master:

```C
#include <mpi.h>
#include <stdio.h>
#include <string.h>

int main()
{
  MPI_Init(NULL, NULL);
  MPI_Info info;
  MPI_Info_create(&info);
  MPI_Info_set(info, "key", "value");
  char buf[MPI_MAX_INFO_KEY];
  memset(buf, MPI_MAX_INFO_KEY, '\0');
  MPI_Info_get_nthkey(info, 0, buf);

  printf("info key 0: %s\n", buf);

  MPI_Finalize();

  return 0;
}
``` 

Correctly prints:

```
$ mpirun -n 1 ./test_info_get_nthkey
info key 0: key
```

@dalcini can you please test and see if you can reproduce it with this C test?

**Comment by dalcinl** [comment]
Looks like your master was not recent enough.

```
$ mpicc tmp.c 
$ ./a.out 
a.out: pinfo_get_nthkey.c:97: PMPI_Info_get_nthkey: Assertion `OPAL_OBJ_MAGIC_ID == ((opal_object_t *) (key))->obj_magic_id' failed.
[kw60439:1760662] *** Process received signal ***
[kw60439:1760662] Signal: Aborted (6)
[kw60439:1760662] Signal code:  (-6)
[kw60439:1760662] [ 0] /lib64/libpthread.so.0(+0x141e0)[0x7fbda3c6a1e0]
[kw60439:1760662] [ 1] /lib64/libc.so.6(gsignal+0x145)[0x7fbda3ac89d5]
[kw60439:1760662] [ 2] /lib64/libc.so.6(abort+0x116)[0x7fbda3ab18a4]
[kw60439:1760662] [ 3] /lib64/libc.so.6(+0x26789)[0x7fbda3ab1789]
[kw60439:1760662] [ 4] /lib64/libc.so.6(+0x36026)[0x7fbda3ac1026]
[kw60439:1760662] [ 5] /home/devel/mpi/openmpi/dev/lib/libmpi.so.0(MPI_Info_get_nthkey+0x2ad)[0x7fbda3d75f6e]
[kw60439:1760662] [ 6] ./a.out[0x4011c4]
[kw60439:1760662] [ 7] /lib64/libc.so.6(__libc_start_main+0xf2)[0x7fbda3ab31e2]
[kw60439:1760662] [ 8] ./a.out[0x4010be]
[kw60439:1760662] *** End of error message ***
Aborted (core dumped)
```

**Comment by dalcinl** [comment]
I built from a git clone on Fedora 33 (GCC 10.21), and configured with:

```
./configure --disable-dependency-tracking --enable-debug --enable-mem-debug --disable-man-pages --disable-mpi-fortran
```

The mpi4py testsuite failure I linked is running on the GitHub Action Ubuntu 20.04 runners.

**Comment by devreal** [comment]
Thanks for testing, I found the bug: https://github.com/open-mpi/ompi/pull/8665

**Comment by dalcinl** [comment]
@jsquyres This kind of regressions are the consequence of insufficient testing. I'm setting this thing up in GitHub Actions [[link]](https://github.com/mpi4py/mpi4py-testing/blob/master/.github/workflows/openmpi.yml) to make the point that integrating mpi4py testsuite in Open MPI testing infrastructure should be relatively easy. Porting this stuff to Azure Pipelines should trivial (actually, the mpi4py part of it is mostly done [[link]](https://github.com/mpi4py/mpi4py/blob/master/.azure/steps.yml)).

**Comment by jsquyres** [comment]
I just merged the PR which fixes this issue, but... ZOMG.  Thank you @dalcinl for the GitHub Actions file!  I'm slightly tweaking it and testing it on my own setup, but I can foresee putting this on the main Open MPI repo in the very near future.

![thank-you](https://user-images.githubusercontent.com/617316/112008303-bbf8c800-8afb-11eb-9898-e64244faa326.gif)

**Comment by dalcinl** [comment]
> I'm slightly tweaking it and testing it on my own setup

Please share your tweaks once you are done! I'm particularly interested on adding a matrix with different configure options, or perhaps better, sets of runtime MCA options.
