### ISSUE TITLE
Regression: MPI_Info_dup() broken

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#8675]
Another MPI_Info API regression in master:

Reproducer:
```python
info = MPI.Info.Create()
info.Set('key', 'value')
dupe = info.Dup()
print(info.Get_nkeys())
print(dupe.Get_nkeys())
```
Output:
```
1
0
```

**Comment by dalcinl** [comment]
@devreal You may want to take care of this one.

**Comment by devreal** [comment]
I will. I was relying on Open MPI's CI to catch these things but I guess that was too optimistic...

**Comment by jsquyres** [comment]
We only run some stuff in CI; much of the testing runs nightly in MTT.

That being said, if we start running mpi4py in regular CI, that will be most helpful.

**Comment by dalcinl** [comment]
> That being said, if we start running mpi4py in regular CI, that will be most helpful.

Well, maybe at some point you may consider writing tests in Python? You can even do this in a separate repo, and use it in GitHub Actions after running mpi4py testsuite. One of the reasons I have test for such trivial things like `MPI_Info_dup` is that test are so easy to write. Note that mpi4py testing infrastructure is somewhat dated, there are better Python testing frameworks that Python's stdlib `unittests` package. Another (perhaps small) advantage of testing MPI with Python is that you run a lot of tests in a single parallel execution, so you can exercise many components (pt2pt, coll, osc, io, etc) and check for possible bad interactions between them.
