### ISSUE TITLE
Do not require a C++ compiler to build Open MPI

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#8689]
> I ran ./configure --disable-man-pages. It did not work, configure cannot find a C++ compiler.

Yeah, we should fix that, too.  There's no need for a C++ compiler any more.

_Originally posted by @jsquyres in https://github.com/open-mpi/ompi/issues/8682#issuecomment-805731262_

**Comment by jsquyres** [comment]
Also see https://github.com/open-mpi/ompi/issues/136
