### ISSUE TITLE
ompi_info fails to link with --enable-mca-static: libopen-pal.so: undefined reference to `ucm_test_external_events'

### ISSUE THREAD

**Issue by acolinisi** [open-mpi/ompi#8718]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

856a2b7f6f6f3380c7617114d9007fa00e631095

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Built from source.

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

Submodules are empty, uninitialized.
PMIX, PRRTE, UCX are all built and installed into prefix separately.

### Please describe the system on which you are running

* Operating system/version: Gentoo Prefix
* Computer hardware: ppc64le

-----------------------------

The build of OpenMPI started failing after this commit:

```
commit 856a2b7f6f6f3380c7617114d9007fa00e631095
Merge: ff1ba016d6 930260cb45
Author: Brian Barrett <bbarrett@amazon.com>
Date:   Thu Mar 25 07:17:07 2021 -0700

    Merge pull request #8132 from bwbarrett/feature/3rdparty-packaging
    
    Change MCA component build style default to static
```

I did rebuild UCX (latest master), PRRTE (latest master), before building OMPI -- made no difference.

The failing link line is (note: I removed the `-D*` args from the link line for clarity):
```
powerpc64le-unknown-linux-gnu-gcc -O3 -finline-functions \
-Wl,-O1 -Wl,--as-needed -o .libs/ompi_info ompi_info.o param.o  \
../../../ompi/.libs/libmpi.so -L/usr/lib64 -L/autofs/nccs-svm1_home1/acolin\
/casper/gpref/gp-k/usr/lib64 -L=/autofs/nccs-svm1_home1/acolin/casper\
/gpref/gp-k/usr/lib64 -L/autofs/nccs-svm1_home1/acolin/casper/gpref/gp-\
k/usr/lib -L=/usr/lib -lgpfs /tmp/acolin-portage/portage/sys-cluster/openmpi-\
5.1.0_pre20210326/work/openmpi-5.1.0_pre20210326-.ppc64/opal/.libs\
/libopen-pal.so ../../../opal/.libs/libopen-pal.so /autofs/nccs-svm1_home1\
 /acolin/casper/gpref/gp-k/usr/lib64/libucp.so -luct /autofs/nccs-svm1_home1\
 /acolin/casper/gpref/gp-k/usr/lib64/libuct.so -lucs /autofs/nccs-svm1_home1\
 /acolin/casper/gpref/gp-k/usr/lib64/libucs.so -lucm /autofs/nccs-\
 svm1_home1/acolin/casper/gpref/gp-k/usr/lib64/libucm.so -lbfd -levent \
  /autofs/nccs-svm1_home1/acolin/casper/gpref/gp-k/usr/lib64/libpmix.so \
  -ldl -levent_core -levent_pthreads -lhwloc -lpthread -lrt -lm -lutil \
  -pthread -Wl,-rpath -Wl,/autofs/nccs-svm1_home1/acolin/casper/gpref/gp-k/usr/lib64 \
  /autofs/nccs-svm1_home1/acolin/casper/gpref/gp-k/usr/lib\
  /gcc/powerpc64le-unknown-linux-gnu/10.2.0/../../../../powerpc64le-\
  unknown-linux-gnu/bin/ld: /tmp/acolin-portage/portage/sys-cluster\
 /openmpi-5.1.0_pre20210326/work/openmpi-5.1.0_pre20210326-.ppc64\
 
 /opal/.libs/libopen-pal.so: undefined reference to `ucm_test_external_events'
```

I don't understand what confuses the linker, `nm` and `readelf -d` don't reveal any obvious problems:
```
$ nm /autofs/nccs-svm1_home1/acolin/casper/gpref/gp-k/usr/lib64/libucm.so | grep ucm_test_external_events                                 
00000000000078a0 T ucm_test_external_events

$ nm /tmp/acolin-portage/portage/sys-cluster/openmpi-5.1.0_pre20210326/work/openmpi-5.1.0_pre20210326-.ppc64/opal/.libs/libopen-pal.so | grep ucm_test_external_events
00000000000264a0 t 0000001a.plt_call.ucm_test_external_events
                 U ucm_test_external_events
```

Workaround: configure with `--enable-mca-dso` (which was the old default).

The link line with `--enable-mca-dso` (that links successfully) does not contain the UCX libraries, fwiw:
```
powerpc64le-unknown-linux-gnu-gcc -Wl,-O1 -Wl,--as-needed -o \
.libs/ompi_info ompi_info.o param.o  ../../../ompi/.libs/libmpi.so -L/autofs\
/nccs-svm1_home1/acolin/casper/gpref/gp-k/usr/lib -L=/usr/lib /tmp/acolin-\
portage/portage/sys-cluster/openmpi-5.1.0_pre20210326/work/openmpi-\
5.1.0_pre20210326-.ppc64/opal/.libs/libopen-pal.so ../../../opal/.libs/libopen-\
pal.so -levent /autofs/nccs-svm1_home1/acolin/casper/gpref/gp-k/usr/lib64 \
/libpmix.so -ldl -levent_core -levent_pthreads -lhwloc -lpthread -lrt -lm \
-lutil -pthread -Wl,-rpath -Wl,/autofs/nccs-svm1_home1/acolin/casper/\
gpref/gp-k/usr/lib64
```

I know this has little chance of being resolved unless someone reproduces it, but I figured I should report it just for FYI. There's a workaround, so I don't need to debug this further.

**Comment by jsquyres** [comment]
@bwbarrett @rhc54 I don't know if this is related to https://github.com/openpmix/prrte/issues/871 or not, but we should probably talk it through.

**Comment by jsquyres** [comment]
@acolinisi Can you send the config.log from your build?  We don't fully understand how all the terms got into your link line.

Thanks!

**Comment by acolinisi** [comment]
[openmpi-link-failure-config.log](https://github.com/open-mpi/ompi/files/6213745/openmpi-link-failure-config.log)

But, please put this on hold. I should have debugged this further. The underlying issue(s) probably always been there, just somehow masked/nonfatal with `--enable-mca-dso`, the `--enable-mca-static` probably just exposed it.

I see at least one (classic) issue with the link line that I somehow failed to notice. There's mixing going on between prefix and host, which is always bad, not always avoidable, and has to be managed carefully. `-L/usr/lib` and `-L/usr/lib64` are pointing to the host system, which is bad, and shouldn't be there. The libgpfs only exists on the host though, like LFS/ALPS libs, so it needs to be included carefully from the host. If I include libgpfs.so explicitly on the link like, I make some progress. Also, I see host's `hwloc.so` being chosen (presumably an issue at configure stage; investigating...), this should be easily fixable.

**Comment by acolinisi** [comment]
Got it to build with `--enable-mca-static` by simply adding `--without-gpfs`, i.e by disabling GPFS which was the most likely cause for `-L/usr/lib -L/usr/lib64`. GPFS is autodetected by default, but autodetection is bad for Gentoo Prefix builds, because it ends up violating the prefix boundary and looking outside the prefix into the host. My build recipe should have been setting all flags explicitly; it was an oversight that the file system flags were not set explicitly.

The reason for failure was essentially the presence of `-L/usr/lib -L/usr/lib64` but it was not limited to the link line of ompi_info, these flags caused problems somewhere earlier in the build (e.g. when linking libmpi.so) but did not cause a fatal failure at that time, but they doomed the build to eventually fail.  The exact way that the linker got confused is still strange, but I don't blame it; it was fed broken previously linked .so files.

It remains an open question how to build against host's libgpfs.so without pulling in bad `-L` flags. Would need to force configure to somehow issue the flags `/usr/lib64/gpfs.so` instead of instead of `-L/usr/lib64 -lgpfs` for `--with-gpfs`. This is out-of-scope of OpenMPI, though, a concern of Gentoo Prefix build recipe, even if it means patching configure.

Question: what functionality am I missing by disabling this GPFS file system support in OpenMPI? (Thanks.)

I'm closing this and apologize for wasting time.

**Comment by jjhursey** [comment]
@gpaulsen or @markalle Do you have a feel for the question from above:
 > Question: what functionality am I missing by disabling this GPFS file system support in OpenMPI? (Thanks.)
