### ISSUE TITLE
App run failed with openmpi-master

### ISSUE THREAD

**Issue by oleotiger** [open-mpi/ompi#8743]
## Background information
I wanna use `--cpu-set` options of mpirun and it only works in newer version such as v5.0.x and master. But I have got errors when compiling openmpi.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
openmpi master branch
head : commit 05693a877b1fb88d5d747aebd4cc96f97ea63cae

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
from a git clone
```
./configure --prefix=/home/software/libs/openmpi-master --enable-mpi1-compatibility --with-ucx=/home/software/libs/ucx-1.9.0/ --with-knem=/home/software/libs/knem/1.1.3/  --with-ofi=/home/software/libs/libfabric-1.12.0 
 make -j 48 
make install
```

### Please describe the system on which you are running

* Operating system/version: CentOS Linux release 7.6.1810 (Core)
* Computer hardware:  Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
* Network type:  mellonax CX-5

-----------------------------

## Details of the problem

With openmpi master branch installed, I compile 2 opensource applications: wrf v3.8.1 and lammps 30Nov20.

I wanna to try if it works correctly locally. I get error messages as shown below.

When I run `./wrf.exe` with conus2.5:
```
--------------------------------------------------------------------------
Open MPI failed an OFI Libfabric library call (fi_endpoint).  This is highly
unusual; your job may behave unpredictably (and/or abort) after this.

  Local host: 6248r-node121
  Location: mtl_ofi_component.c:516
  Error: Invalid argument (22)
--------------------------------------------------------------------------
 starting wrf task            0  of            1
```
It exits very quicklly. No more output is printed.

If I run with mpirun:
`/home/software/libs/openmpi-master/bin/mpirun --allow-run-as-root -hostfile hostfile -np 6 -N 6 --bind-to core  -x OMP_NUM_THREADS=1 -mca pml ucx -mca btl ^vader,tcp,openib,uct -mca io romio321 -x UCX_TLS=self,sm,rc -x UCX_NET_DEVICES=mlx5_0:1   ./wrf.exe`
there is directly : `Segmentation fault`. No more output.

When I run `./lmp -sf opt -in in.lj`, I get correctly output of lammps but error message of openmpi as well.
```
--------------------------------------------------------------------------
Open MPI failed an OFI Libfabric library call (fi_endpoint).  This is highly
unusual; your job may behave unpredictably (and/or abort) after this.

  Local host: 6248r-node121
  Location: mtl_ofi_component.c:516
  Error: Invalid argument (22)
--------------------------------------------------------------------------
LAMMPS (30 Nov 2020)
Lattice spacing in x,y,z = 1.6795962 1.6795962 1.6795962
Created orthogonal box = (0.0000000 0.0000000 0.0000000) to (33.591924 33.591924 33.591924)
  1 by 1 by 1 MPI processor grid
Created 32000 atoms
  create_atoms CPU = 0.003 seconds
Neighbor list info ...
  update every 1 steps, delay 5 steps, check yes
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 2.8
  ghost atom cutoff = 2.8
  binsize = 1.4, bins = 24 24 24
  1 neighbor lists, perpetual/occasional/extra = 1 0 0
  (1) pair lj/cut/opt, perpetual
      attributes: half, newton on
      pair build: half/bin/atomonly/newton
      stencil: half/bin/3d/newton
      bin: standard
Setting up Verlet run ...
  Unit style    : lj
  Current step  : 0
  Time step     : 0.005
Per MPI rank memory allocation (min/avg/max) = 15.82 | 15.82 | 15.82 Mbytes
Step Temp E_pair E_mol TotEng Press
       0         1.44   -6.7733681            0   -4.6134356   -5.0197073
     100   0.75745998   -5.7584998            0   -4.6223453   0.20729996
Loop time of 1.69597 on 1 procs for 100 steps with 32000 atoms

Performance: 25472.124 tau/day, 58.963 timesteps/s
99.9% CPU use with 1 MPI tasks x no OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 1.1885     | 1.1885     | 1.1885     |   0.0 | 70.08
Neigh   | 0.45353    | 0.45353    | 0.45353    |   0.0 | 26.74
Comm    | 0.017078   | 0.017078   | 0.017078   |   0.0 |  1.01
Output  | 0.00014385 | 0.00014385 | 0.00014385 |   0.0 |  0.01
Modify  | 0.025416   | 0.025416   | 0.025416   |   0.0 |  1.50
Other   |            | 0.01133    |            |       |  0.67

Nlocal:        32000.0 ave       32000 max       32000 min
Histogram: 1 0 0 0 0 0 0 0 0 0
Nghost:        19669.0 ave       19669 max       19669 min
Histogram: 1 0 0 0 0 0 0 0 0 0
Neighs:    1.20318e+06 ave 1.20318e+06 max 1.20318e+06 min
Histogram: 1 0 0 0 0 0 0 0 0 0

Total # of neighbors = 1203176
Ave neighs/atom = 37.599250
Neighbor list builds = 11
Dangerous builds = 0
Total wall time: 0:00:01
```

If I run mpirun directly:
```
[root@6248r-node121 lammps_host_hostfile_121_np_24_slots_48_cpuset_0_20210331105614]# mpirun
Segmentation fault
[root@6248r-node121 lammps_host_hostfile_121_np_24_slots_48_cpuset_0_20210331105614]# mpirun -h
Segmentation fault
[root@6248r-node121 lammps_host_hostfile_121_np_24_slots_48_cpuset_0_20210331105614]# mpirun --help
Segmentation fault
[root@6248r-node121 lammps_host_hostfile_121_np_24_slots_48_cpuset_0_20210331105614]# mpirun --allow-run-as-root --help
Segmentation fault

```

How could I fix the problem?

**Comment by awlauria** [comment]
@oleotiger can you pull the latest master? I was unable to reproduce the segv at 92389c364df669822bb6d72de616c8ccf95b891c

**Comment by oleotiger** [comment]
> Based on your output there was probably an issue with prrte that has since been pulled in, looks like those pointers got updated a few times since your hash.

I pulled and recompile the newest master branch.

Again, there is no error and compiling is finished correctly. 

```
[root@6248r-node122 ompi]# mpirun -h
Segmentation fault (core dumped)
```

But there is still segmentation fault.

**Comment by awlauria** [comment]
Thanks @oleotiger, we'll take another look.

**Comment by rhc54** [comment]
I have the segfault fixed - just need to update OMPI. Cannot speak to the rest. Key is that @oleotiger is running as _root_ and not a regular user.

**Comment by oleotiger** [comment]
I pulled again and compiled openmpi of  latest version. It works.  Thank you .
