### ISSUE TITLE
Build failure with gcc-10.2.0

### ISSUE THREAD

**Issue by seraphzl** [open-mpi/ompi#8750]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
openmpi-4.1.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
from a source tarball openmpi-4.1.0.tar.bz2
./configure --prefix=/opt/openmpi-4.1.0 --enable-static --enable-mca-static
make all install

### Please describe the system on which you are running

* Operating system/version: Linux localhost.localdomain 3.10.0-1062.12.1.el7.x86_64 #1 SMP Wed Feb 5 09:10:55 CST 2020 x86_64 x86_64 x86_64 GNU/Linux

-----------------------------

## Details of the problem

Build failure with gcc-10.2.0

```shell
  CC       libdatatype_reliable_la-opal_datatype_pack.lo
In file included from opal_datatype_pack.c:40:0:
../../opal/datatype/opal_datatype_pack.h: In function ‘pack_contiguous_loop’:
../../opal/datatype/opal_datatype_pack.h:173:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(size_t _i = 0; _i < _copy_loops; _i++ ) {
     ^
../../opal/datatype/opal_datatype_pack.h:173:5: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [libdatatype_reliable_la-opal_datatype_pack.lo] Error 1

```

**Comment by hjelmn** [comment]
Are you sure that you are using the same compiler for configure as the build? configure will check if a flag is needed for C99 mode. No flag is needed for gcc 10. If the compiler used by make is an older version of gcc (4.x) it does require a flag and will error out in this exact way when compiling C99 code.

**Comment by seraphzl** [comment]
@hjelmn You are correct! I forgot to change the PATH where gcc-10.3.0 would be when make all install. Thank you.
