### ISSUE TITLE
mpirun-launched apps "hang" in init when configured with external 3rd party libs

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#8757]
Configured OMPI with external 3rd-party libs using:
```shell
$ ./autogen.pl --no-oshmem --exclude io-romio321,topo-treematch,io-ompio,pmix,prrte --no-3rdparty=hwloc-2.4.0,romio321,libevent-2.1.12,treematch,pmix,prrte

$ ./configure --prefix=/Users/rhc/openmpi/build --with-platform=contrib/platform/intel/bend/mac --with-pmix=/Users/rhc/pmix/build/clean --with-prrte=/Users/rhc/pmix/build/prrte --with-hwloc=/Users/rhc/hwloc/build/v2.2.0 --with-libevent=/Users/rhc/libevent/build
```
The external PMIx and PRRTE repos were each built against the same libevent and hwloc repos used in this OMPI configure. The libevent build used was also at v2.1.12, matching OMPI's internal version. All built just fine. However, when I tried a simple one-node example:
```shell
$ mpirun -n 2 ./hello_c
```
the job hung in PMIx_Init waiting for mpirun to respond to a request for its job-level info. Attaching to mpirun shows the process to be simply looping thru libevent. The application process is sitting in PMIx_Init waiting for a reply from mpirun.

I did not observe this behavior when I rebuilt OMPI to use the internal components - it appears something relating to use of the external components. Note that the PRRTE installation works fine on its own - i.e., I can use `prterun` to execute an application without problem.

**Comment by awlauria** [comment]
This is the same as https://github.com/open-mpi/ompi/issues/8776

I re-verified this works now. Closing.
