### ISSUE TITLE
Intel MPI benchmark test reduce_scatter/reduce_scatter_block/gather fail (out of memory)

### ISSUE THREAD

**Issue by wzamazon** [open-mpi/ompi#8765]
Thank you for taking the time to submit an issue!

## Background information

IMB test reduce_scatter/reduce_scattter_block/gather fail because out of memory.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.1.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

rpm

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

N/A

### Please describe the system on which you are running

* Operating system/version: Amazon linux 2
* Computer hardware: 32 nodes, each instance has  2 Intel skylake (Xeon 8124m) cpu, 192 GB of memory
* Network type: EFA

## Details of the problem

When running IMB-MPI1 test using 32 nodes (each node has 2 Intel Skylake cpu and 192 GB of memory), the test failed with the following collectives at different message size:

1. reduce_scatter at 2mb message size
2. reduce_scatter_block at 2 mb message size
3. gather at 16 mb message size

The following is steps to reproduce:

1. install intel mpi benchmark (IMB)
```
git clone https://github.com/intel/mpi-benchmarks.git
cd mpi-benchmarks
export CC=mpicc
export CXX=mpicxx
export CPPFLAGS=-DCHECK
make -j 36
```
2. run reduce_scatter with 2MB message size.
2a. create a text file `msglen` with `2097152` in it.
2b. run imb using the following command
```
mpirun -tag-output -n 1152 -N 36  \
        --hostfile ../../../32instances \
        /fsx/ALinux2/dev/imb/mpi-benchmarks-ompi-4.1.x/IMB-MPI1 \
        -npmin 1152 -mem 6 Reduce_scatter -time 1000 -iter 1 -msglen msglen
```
The error message I got is

```
[1,0]<stdout>:# /fsx/ALinux2/dev/imb/mpi-benchmarks-ompi-4.1.x/IMB-MPI1 -npmin 1152 -mem 6 Reduce_scatter -time 1000 -iter 1 -msglen msglen -mem 6
[1,0]<stdout>:
[1,0]<stdout>:# Message lengths were user defined
[1,0]<stdout>:#
[1,0]<stdout>:# MPI_Datatype                   :   MPI_BYTE
[1,0]<stdout>:# MPI_Datatype for reductions    :   MPI_FLOAT
[1,0]<stdout>:# MPI_Op                         :   MPI_SUM
[1,0]<stdout>:#
[1,0]<stdout>:#
[1,0]<stdout>:
[1,0]<stdout>:# List of Benchmarks to run:
[1,0]<stdout>:
[1,0]<stdout>:# Reduce_scatter
[1,0]<stderr>:iter 0 of 1: before reduce_scatter
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
```
Following the same step, one can run reduce_scatter_block test at 2MB and gather test at 16MB.

I later found out the reason for the error is because system ran out of memory, and the process was killed by oom killer

**Comment by wzamazon** [comment]
I did some debugging and found that the default algorithm of reduce_scatter/reduce_scatter_block/gather are using memory.

In my test, the community size is 1152, and message size is 2MB.

In this case, reduce_scatter is using the butterfly algorithm, which will allocate `2 * number_mpi_ranks * message_size` of memory for each process. This combined with the fact there are 36 MPI ranks on each node, resulted memory usage of 162 GB on each instance.

The same situation apply to reduce_scatter_block, which is also using the butterfly algorithm  and is using 162 GB of memory.

For gather, the binomial algorithm was used for 1152 ranks and 16MB of message size. For this algorithm, all process with even MPI rank will allocate `number_of_mpi_ranks * message_size`. So on each instance, this algorithm require `18 x 1152 x 16` MB (324 GB) of memory.

**Comment by wzamazon** [comment]
One solution I can think of is to use an algorithm that uses less message for large message sizes and communicator size.

For reduce_scatter there is an non-overlapping algorithm, which uses much less memory

For reduce_scatter_block, there is the basic_linear algorithm.

For gather, there is also the basic_linear algorithm.

For this solution, we need to decide what kind of memory usage is acceptable for a collective algorithm. Then in `coll_tuned_decision_fixed.c`, we can calculate the switching message size we need to use the safe algorithm.

For example, say we decide reduce_scatter should not allocate more than 1GB of memory on each process, then for communicator size of 1024, we need to use the basic linear algorithm for message size > 512K.

**Comment by wenduwan** [comment]
This is still an issue as of today. We haven't got capacity to fix it yet in Amazon.

**Comment by wenduwan** [comment]
We intend to fix this in AWS tuning file. Closing.
