### ISSUE TITLE
mpicxx no longer includes -pthread when required

### ISSUE THREAD

**Issue by bwbarrett** [open-mpi/ompi#8766]
With https://github.com/open-mpi/ompi/commit/38e53f331c22e0059552101f5b1513eccd5a56cc, mpicxx/mpic++ no longer includes `-pthread` when needed.  This is causing link errors on one of our internal multi-threaded codes.

**Comment by jsquyres** [comment]
Wow... weird.

I'm happy to revert, but I'm not sure how that change affects anything.  All the code that was removed does is set the shell variable `$solaris_use_stlport4`, which isn't used anywhere in OMPI's configure any more.

Was this found via a git bisect that didn't locate the right commit, perchance?

**Comment by awlauria** [comment]
#8791 has been merged, closing. Thanks!
