### ISSUE TITLE
Pack/unpack external broken for long double real and complex datatypes

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#8770]
Looks like the pack/unpack external operations do not roundtrip for long double (real and complex) datatypes with current ompi@master.

This is my trivial Python reproducer

```
from mpi4py import MPI
import numpy as np

datatype = MPI.LONG_DOUBLE
typecode = MPI._typecode(datatype)
iarray = np.array([1,2,3], dtype=typecode)
oarray = np.zeros(3, dtype=typecode)

n = datatype.Pack_external_size("external32", len(iarray))
work = bytearray(n)
datatype.Pack_external("external32", iarray, work, 0)
datatype.Unpack_external("external32", work, 0, oarray)

print(iarray)
print(oarray)
```

Running on my Linux-64 workstation I get the following output (both lines are expected to be the same):
```
[1. 2. 3.]
[8.40525786e-4933 8.40525786e-4933 1.26078868e-4932]
```

@jsquyres I understand that supporting external32 for `long double [complex]` is a bit tricky. You probably have to rely on a compiler quad-precision type like GCC `__float128` for a proper implementation, see [MPI 3.1](https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node333.htm#Node333) Table 13.2 pp. 580  [RFC 1832](https://tools.ietf.org/html/rfc1832), Sec. 3.8, but if it cannot be supported, then perhaps you should error rather that let things success silently and end up with broken data? Or maybe this is just a trivial bug?

**Comment by gpaulsen** [comment]
@markalle You posted a fix for external32, that now needs rebasing.  Might PR https://github.com/open-mpi/ompi/pull/7919 fix this issue?

**Comment by markalle** [comment]
Offhand I doubt my 7919 would be related, although if there is a difference between the system `sizeof(long double)` and the `MPI_Type_size(MPI_LONG_DOUBLE,)` then it could be.

I just now ran a similar C program:
https://gist.github.com/markalle/ad7e69f026471e2baa8e842c938d8048
and it was successful, at least on my system where `sizeof(long double)` and `MPI_Type_size(MPI_LONG_DOUBLE,)` were both 16.

**Comment by bosilca** [comment]
With the current master plus PR #8769 both the C and python code give the correct result on x86_64 and ARM (M1).
