### ISSUE TITLE
Open MPI's configure complains about OpenPMIx flags

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#8771]
I've tried to disable curl support in OMPI's internal OpenPMIx (OMPI master @`g583382f574`) and passed `--without-curl` to the top-level configure, which results in a warning that the flag is unknown:

```
$ ../configure ... --without-curl
configure: WARNING: unrecognized options: --without-curl
```

According to @bwbarrett this should not happen as the top-level configure should be aware of the 3rd party configure flags so I'm opening this for tracking.

**Comment by jjhursey** [comment]
I cannot seem to reproduce this on my machine. I'm using `master` at ca65630bb8f266aae5ceea4fe1358b09506724f3 and tried with `./configure --without-curl`.

```
============================================================================
== CURL
============================================================================
checking libcurl support available... no
```

**Comment by devreal** [comment]
@jjhursey Thanks for checking! Is it possible to find the list of slurped in 3rd party configure options? I see the warning on two different systems and would like to understand why. Unfortunately, I am not at all familiar with OMPI's build system...

**Comment by cniethammer** [comment]
@devreal you can check the corresponding config.log in the 3rd-party directories. For me the `--without-curl` is passed correctly to the submodule configures. But maybe there are side effects from other options? Could you paste the full configure line.

**Comment by devreal** [comment]
The flags are passed to the 3rd party packages correctly. The reason I opened this issue is because of the warning at the very beginning of the top-level configure invocation:

```
$ ../configure --without-curl
configure: WARNING: unrecognized options: --without-curl
```

My understanding is that this warning should not occur since the top-level configure is supposed to be aware of the 3rd party package options.

**Comment by jjhursey** [comment]
@devreal `autogen.pl` will create a `config/auto-extracted-pmix-configure-args.m4` and a `config/auto-extracted-prrte-configure-args.m4` for the configure options extracted from OpenPMIx and PRRTE, respectively. There are comments in the files on where each extracted configure option was found.

These autogenerated files are included into the top level configure in `config/opal_config_pmix.m4` and `config/ompi_setup_prrte.m4`.

**Comment by devreal** [comment]
Thanks, I see most flags being ignored:

```
# Warning: Excluded: curl
# ---------------------------------------- Above from 3rd-party/openpmix//config/pmix_check_curl.m4:35
```
Other ignored flags are `hwloc` and `libevent`. 

Any idea why these are excluded?

**Comment by jjhursey** [comment]
My local copy has this instead:
```
        AC_ARG_WITH([curl],
                    [AS_HELP_STRING([--with-curl(=DIR)],
                                    [Build curl support (default=no), optionally adding DIR/include, DIR/lib, and DIR/lib64 to the search path for headers and libraries])])
# ---------------------------------------- Above from 3rd-party/openpmix//config/pmix_check_curl.m4:37

    AC_ARG_WITH([curl-libdir],
            [AS_HELP_STRING([--with-curl-libdir=DIR],
                    [Search for Curl libraries in DIR])])
# ---------------------------------------- Above from 3rd-party/openpmix//config/pmix_check_curl.m4:41
```

A couple of things to check on your build:
 * In your `autogen.pl` output are there any warnings around the `=== PMIx` lines of output? That is where the extract script is activated.
 * Look at `config/auto-generated-ompi-exclude.ini` to see if somehow the curl options were added to the OMPI exclude list. It will be on a line like
```
# OMPI : AC_ARG_ENABLE : From ....m4:...
OPTION: curl
```
 * Add debugging to the extract script to see why it might have rejected the curl options` ./config/extract-3rd-party-configure.pl -p "3rd-party/openpmix/" -n "PMIx" -d`

I wonder if something in the extract script is not working properly more globally.

**Comment by awlauria** [comment]
Any update on this?

**Comment by devreal** [comment]
@bwbarrett The CURL options do appear in the `config/auto-generated-ompi-exclude.ini` file. I tried removing the file and re-running the autogen.pl script but they reappeared. What is causing these options to be added there?

```
$ grep curl config/auto-generated-ompi-exclude.ini
# OMPI : AC_ARG_WITH : From ./opal/mca/pmix/pmix4x/openpmix/config/pmix_check_curl.m4:34
OPTION: curl
# OMPI : AC_ARG_WITH : From ./opal/mca/pmix/pmix4x/openpmix/config/pmix_check_curl.m4:38
OPTION: curl-libdir
# PMIx : AC_ARG_WITH : From 3rd-party/openpmix//config/pmix_check_curl.m4:35
OPTION: curl
# PMIx : AC_ARG_WITH : From 3rd-party/openpmix//config/pmix_check_curl.m4:39
OPTION: curl-libdir
```

**Comment by jjhursey** [comment]
I see the issue: `./opal/mca/pmix/pmix4x/`
That directory doesn't exist on [`master`](https://github.com/open-mpi/ompi/tree/master/opal/mca/pmix) or `v5.0` as it was replaced by the [`3rd-party`](https://github.com/open-mpi/ompi/tree/master/3rd-party) mechanism.

If you do a `git clean -d -f` that'll clean out everything that is not in git (beware if you have any local changes). Then try re-running autogen. I think that will resolve the issue.

You should only see 2 lines in that file after autogen:
```
# PMIx : AC_ARG_WITH : From 3rd-party/openpmix//config/pmix_check_curl.m4:35
OPTION: curl
# PMIx : AC_ARG_WITH : From 3rd-party/openpmix//config/pmix_check_curl.m4:40
OPTION: curl-libdir
```

**Comment by devreal** [comment]
@jjhursey Thanks, I purged the directory `./opal/mca/pmix/pmix4x/` and the warning is gone :+1: Closing.
