### ISSUE TITLE
mpiexec -N does not work

### ISSUE THREAD

**Issue by abouteiller** [open-mpi/ompi#8782]
`mpiexec -N x` should restrain the number of processes spawned per node to `x`. It does not. 

Defect present in both master and v5.0.x, as it is inherited from PRTE.

```python
salloc -N 4 mpiexec -n 4 -N 1 --display map hello

salloc: Nodes b[02-05] are ready for job

========================   JOB MAP   ========================
Data for JOB mpiexec-saturn-25004@1 offset 0 Total slots allocated 160
    Mapping policy: BYPACKAGE:NOOVERSUBSCRIBE  Ranking policy: SLOT Binding policy: PACKAGE:IF-SUPPORTED
    Cpu set: N/A  PPR: N/A  Cpus-per-rank: N/A  Cpu Type: CORE


Data for node: b02      Num slots: 40   Max slots: 0    Num procs: 4
        Process jobid: mpiexec-saturn-25004@1 App: 0 Process rank: 0 Bound: package[0][core:0-9]
        Process jobid: mpiexec-saturn-25004@1 App: 0 Process rank: 1 Bound: package[1][core:10-19]
        Process jobid: mpiexec-saturn-25004@1 App: 0 Process rank: 2 Bound: package[0][core:0-9]
        Process jobid: mpiexec-saturn-25004@1 App: 0 Process rank: 3 Bound: package[1][core:10-19]

=============================================================

PROCESS  h: b02.bezout  r/s: 003/004.
PROCESS  h: b02.bezout  r/s: 001/004.
PROCESS  h: b02.bezout  r/s: 002/004.
PROCESS  h: b02.bezout  r/s: 000/004.
```

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
master: 470eaca7 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #8777 from abouteiller/bugfix/spawn-info      Austen Lauria  3 hours ago

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

 git submodule status
 1e65ca3116481800d51eecbd121a64f32b8662ad 3rd-party/openpmix (v1.1.3-2935-g1e65ca31)
 9c6e914cf9d867ae928059daf8e066cbb34ed66c 3rd-party/prrte (dev-31116-g9c6e914c)

prte: commit 9c6e914c (HEAD -> master, origin/master, origin/HEAD) Merge pull request #906 from rhc54/topic/atm                     Ralph Castain   4 days ago

### Please describe the system on which you are running

* Operating system/version: CentOS 7.2
* Computer hardware: x86_64
* Network type: mlx4
* SLURM managed

**Comment by devreal** [comment]
I'm seeing the same behavior on our cluster with a similar submodule configuration: the -N flag seems to be ignored entirely.

**Comment by abouteiller** [comment]
The corresponding expected underlying behavior with `--map-by ppr:X:node` works as intended. So it is just a matter of linking the two together again.

**Comment by rajachan** [comment]
The simplification of the schizo framework in PMIx https://github.com/openpmix/prrte/pull/819 changed behaviors here. This PR caught a bunch of missing remaps: https://github.com/openpmix/prrte/pull/891, looks like -N did not make it in.  Linking this issue to https://github.com/openpmix/prrte/issues/709 so we don't lose track of it.

**Comment by jsquyres** [comment]
Just for linkage: looks like https://github.com/openpmix/prrte/pull/914 will fix the issue (whenever that gets synced over here to the OMPI repo).

**Comment by rhc54** [comment]
probably tomorrow or Fri, unless someone needs it sooner (I just updated this late afternoon)

**Comment by rhc54** [comment]
It is in https://github.com/open-mpi/ompi/pull/8811 - just waiting for someone to bless it

**Comment by jsquyres** [comment]
Looks like #8811 was merged.  Closing this issue.
