### ISSUE TITLE
Library not found for -levent_core openmpi

### ISSUE THREAD

**Issue by claysurmeier** [open-mpi/ompi#8813]
## Background information

I am downloading OpenMPI and building from source to enable parallel computing with Neuron: https://www.neuron.yale.edu/neuron/download/compilestd_osx

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

openmpi-4.1.0.tar.gz

Downloaded from: https://www.open-mpi.org/software/ompi/v4.1/

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

I attempted to build OpenMPI using the following commands:

cd ~/local/src
tar xzf ~/Downloads/openmpi*.gz
cd openmpi*
./configure --prefix=$HOME/local # <---- encountered error here (and subsequent lines because not configured)
make
make install

### Please describe the system on which you are running

* Operating system/version: Mac OSX Catalina v10.15.17
* Computer hardware: Macbook Pro '19
* Network type: 

-----------------------------

## Details of the problem

When trying to ./configure I get: Error 1

ld: Library not found for -levent_core openmpi

Thanks in advance for any comments or suggestions!

**Comment by bwbarrett** [comment]
Can you please include a bit more of the configure output?  That's a weird error to see from configure, and it is difficult to guess what is going wrong from just that output.  If possible, attaching the full output of configure as well as the `config.log` file would be best.

**Comment by claysurmeier** [comment]
Running configure today did not produce this output, but got the message instead while running make -- perhaps I misremembered where the problem was occurring. In any event, I've attached the config log and an extension of the make error outputs. Hope this helps.
[make.log](https://github.com/open-mpi/ompi/files/6311667/make.log)
[config.log](https://github.com/open-mpi/ompi/files/6311668/config.log)

**Comment by jsquyres** [comment]
@bwbarrett `configure` found `-levent_core`, but then `make` failed when trying to link `libmpi_usempif08.la`:

```
  FCLD     libmpi_usempif08.la
ld: library not found for -levent_core
```

Kinda odd that this worked before (with `-levent`).  Perhaps there's a typo in a shell variable somewhere...?

@claysurmeier Can you run:

```
cd ompi/mpi/fortran/use-mpi-f08
make V=1 2>&1 | tee fortran-make.out
```

And send us the `fortran-make.out` (we only need to see the detail of the link step that failed -- you don't need to do a full rebuild).

And maybe also send us the file `ompi/mpi/fortran/use-mpi-f08/Makefile`?

**Comment by claysurmeier** [comment]
[fortran-make.out.txt](https://github.com/open-mpi/ompi/files/6312840/fortran-make.out.txt)

[Makefile.txt](https://github.com/open-mpi/ompi/files/6312846/Makefile.txt)

**Comment by jsquyres** [comment]
@claysurmeier I see the issue: https://www.open-mpi.org/faq/?category=building#libevent-or-hwloc-errors-when-linking-fortran

**Comment by claysurmeier** [comment]
@jsquyres Thanks, I'll look into that thread. Cheers!
