### ISSUE TITLE
Memory patcher conflicts with OMPI and libfabric

### ISSUE THREAD

**Issue by rajachan** [open-mpi/ompi#8822]
We had [ported OMPI’s patcher code](https://github.com/ofiwg/libfabric/pull/6264) to libfabric not too long ago to get notifications about memory events for its registration cache.  Libfabric also has a userfaultfd notifier, but it defaults to the patcher-based “memhooks” notifier given the additional coverage it provides. Given how patcher uses jump statements to patch the various calls, we can not really stack multiple patcher hooks atop each other. When testing the OFI BTL with EFA, we observed silent data corruption with some benchmarks and root caused it to libfabric using stale registrations having failed to invalidate entries after OMPI’s patcher taking over the hooks.

UCX has a mechanism to take in external events from applications, `ucm_set_external_event()`. OMPI uses this mechanism in the UCX PML to invoke `ucm_vm_munmap()` from a unmap callback based on its internal memory hook events. We can achieve a similar workflow with libfabric's `FI_MR_MMU_NOTIFY` mode. While this mode was designed with a different use-case in mind (allowing registrations that are not backed by physical pages), we should be able to use it in conjunction with `fi_mr_refresh()` to take external events from applications like OMPI. To be specific, libfabric providers can make `FI_MR_MMU_NOTIFY` a soft requirement. If an application does not support it, they can continue using memhooks as is. If an application like OMPI does support that mode, providers can rely on fi_mr_refresh() notifications in place of the internal monitor (or perhaps in addition to userfaultfd) to determine when to evict an entry from the cache. 

On the Open MPI side, the provider query logic will have to set FI_MR_MMU_NOTIFY mode and call fi_mr_refresh() on unmap events. Rcache uses the OPAL memory hooks, so it registers a callback to react to memory events (mca_rcache_base_mem_cb). For what the OFI components need, we can register another OFI-specific callback from common OFI code used both by the BTL and the MTL (which will eventually want to use a cache for CUDA buffers given the cost of querying CUDA buffer attributes). This OFI-specific callback can then directly pass on the notification to libfabric via fi_mr_refresh(). This will all be provider-agnostic. 

@open-mpi/ofi @hppritcha @shefty, thoughts?

**Comment by shefty** [comment]
Conceptually, I think this could work, and I like the proposed flow.

The problem I see is fi_mr_refresh() takes a mr as input, which requires that the application register the region.

**Comment by wzamazon** [comment]
When MR cache is used, we can find the MR from cache?

**Comment by shefty** [comment]
The app needs to pass the MR into fi_mr_refresh().  To do that it needs to initiate the registration call.

The MR is only really needed here in order to route to the correct control() function.  We could call the domain->control() operation instead, but that would be through fi_control() directly.  Plus that behavior does not relate directly with FI_MR_MMU_NOTIFY as it's currently defined.

We're really wanting the app to hook into the memory monitor.

**Comment by wzamazon** [comment]
It seems we can have a new fi_control command on an fi_domain object, and each provider can choose how or whether to implement it. Does it look right?

**Comment by rajachan** [comment]
Wei had raised the point about fids when I discussed the proposal with him. I agree, having a global fid would be useful for things like this. IIRC, we'd discussed using fi_control() in the past for core component controls (like disabling/enabling the cache); which would also need a special fid of some sort.

**Comment by awlauria** [comment]
@bwbarrett @hppritcha this looks like a blocker for v5.0.0. Agree?

**Comment by shefty** [comment]
libfabric added the ability for ompi to import its memory patcher support through libfabric commit 7759f8c.  There's no guarantee that the code will work as-is, since there's no implementation that uses it yet.  But in theory the updates needed on the ompi side shouldn't be difficult.

**Comment by gpaulsen** [comment]
Is anyone looking at this?

**Comment by bwbarrett** [comment]
AWS is suppose to be looking at this, but we're a bit behind.

**Comment by wckzhang** [comment]
Going to start working on this

**Comment by wckzhang** [comment]
I was thinking this is kind of something we would like to get into 4.1.2 (Since this would be useful to us), but in the middle of writing the code, I realized that this is an ABI break and 1.13.x libfabric feature. I'm not sure what our proper procedure is for dealing with version requirements with an ABI break in a minor version update (I'd be surprised if we can get away with requiring libfabric 1.13). Does anyone have an idea what I should do for versioning?

**Comment by wzamazon** [comment]
Why this change would break ABI?

**Comment by wckzhang** [comment]
Wouldn't break Open MPI's ABI, but the new libfabric API is an ABI break

**Comment by wckzhang** [comment]
What I'm asking is, in Open MPI is it okay if we ask for a newer libfabric version in a minor version update, especially if that libfabric version is an ABI break.

**Comment by hppritcha** [comment]
@wckzhang from the app perspective this is not an ABI break, but there could be issues for packages if all of a sudden in an update release we need a newer version of libfabric.  If possible, we should have a fallback to support older libfabric API when we are confident the selected provider doesn't have this MR caching issue.

**Comment by gpaulsen** [comment]
Merged to v5.0 and master.  closing

**Comment by wckzhang** [comment]
The current checks for libfabric are compile time only. Need to add run-time checking in case someone runs the new code with an older libfabric and things completely break.

**Comment by wckzhang** [comment]
(Since libfabric 1.13 will still be ABI compatible but there are a lot of bugs in the import monitor code, need to add run-time checking to only use import monitor in 1.14+)

**Comment by bwbarrett** [comment]
There are three issues with the code today.  AWS is working on patches for next week:

1. we need to sort out the memory framework initialization.  Common components shouldn't be opening frameworks, and should definitely be checking error codes.
2. We forgot to add comments.
3. We need to sort out the version / feature test behaviors William mentioned earlier.

**Comment by wckzhang** [comment]
Added some comments - https://github.com/open-mpi/ompi/pull/9387

**Comment by bwbarrett** [comment]
Adding a v4.1.x tag to block that release, as the early initialization issue got pushed to the v4.1.x branch as well.

**Comment by bwbarrett** [comment]
Most of the master changes were merged as part of https://github.com/open-mpi/ompi/issues/8822.  One outstanding issue is that the patcher framework should really fail to patch the binary if it has already been patched.  Someone at AWS is working on that patch.

**Comment by wckzhang** [comment]
Everything we need has been merged into master but not all backported. Should we wait until the backports are all done?

**Comment by awlauria** [comment]
@wckzhang is everything backported now? Not sure if we can close this or not.

**Comment by wckzhang** [comment]
Yes it can be closed

**Comment by awlauria** [comment]
Thanks!
