### ISSUE TITLE
mca_sharedfp_lockedfile_file_open: Error during file open

### ISSUE THREAD

**Issue by J-shel** [open-mpi/ompi#8825]
Hello,

## Background information
I'm running an application, which reads input files from local storage on each node since our parallel storage system is under maintenance. And I got the following message. The application got stuck here.
[n406:131617] [86]mca_sharedfp_lockedfile_file_open: Error during file open
[n356:132695] [65]mca_sharedfp_lockedfile_file_open: Error during file open
[n354:131282] [64]mca_sharedfp_lockedfile_file_open: Error during file open
[n431:129012] [97]mca_sharedfp_lockedfile_file_open: Error during file open
[n488:128123] [122]mca_sharedfp_lockedfile_file_open: Error during file open
[n468:130410] [113]mca_sharedfp_lockedfile_file_open: Error during file open

It all goes well when I using the parallel storage system. I wonder is there any settings that should be added behind mpirun to indicate that we are using or only using local storage on each node?

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
mpirun (Open MPI) 4.1.1rc2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
The OpenMPI was installed as follows:
./configure --prefix=/user/local/openmpi CC=icc CXX=icpc FC=ifort --with-ucx=/usr
make
make install

I'm using ucx1.10, and it was installed under /usr.
The job was running using 
mpirun -mca pml ucx -mca btl ^uct -x UCX_NET_DEVICES=mlx5_0:1 --hostfile hostname -np 2048 ./app.exe

### Please describe the system on which you are running
* Operating system/version: CentOS Linux release 7.6.1810 (Core)
* Computer hardware: 
$lscpu
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 56
On-line CPU(s) list: 0-55
Thread(s) per core: 1
Core(s) per socket: 28
Socket(s): 2
NUMA node(s): 2
Vendor ID: GenuineIntel
CPU family: 6
Model: 85
Model name: Intel(R) Xeon(R) Gold 6258R CPU @ 2.70GHz
Stepping: 7
CPU MHz: 999.975
CPU max MHz: 4000.0000
CPU min MHz: 1000.0000
BogoMIPS: 5400.00
Virtualization: VT-x
L1d cache: 32K
L1i cache: 32K
L2 cache: 1024K
L3 cache: 39424K
NUMA node0 CPU(s): 0-27
NUMA node1 CPU(s): 28-55
* Network type: 
$ibstat
CA 'mlx5_0'
CA type: MT4123
Number of ports: 1
Firmware version: 20.29.2002
Hardware version: 0
Node GUID: 0x0c42a10300387d0c
System image GUID: 0x0c42a10300387d0c
Port 1:
State: Active
Physical state: LinkUp
Rate: 100
Base lid: 749
LMC: 0
SM lid: 1988
Capability mask: 0x2651e848
Port GUID: 0x0c42a10300387d0c
Link layer: InfiniBand
CA 'mlx5_1'
CA type: MT4123
Number of ports: 1
Firmware version: 20.29.2002
Hardware version: 0
Node GUID: 0x0c42a10300387d38
System image GUID: 0x0c42a10300387d38
Port 1:
State: Down
Physical state: Polling
Rate: 10
Base lid: 65535
LMC: 0
SM lid: 0
Capability mask: 0x2651e848
Port GUID: 0x0c42a10300387d38
Link layer: InfiniBand

Thank you!

**Comment by edgargabriel** [comment]
@J-shel thank you for the report. Can I ask  a few questions for clarification? If you say "reads input files from local storage" do you mean e.g. separate hard drives on each node? If yes, this would be a situation that MPI I/O is not really designed for, MPI I/O is assuming shared storage to all nodes. The only situation where this is expected to work is if you would restrict the communicator used during MPI_File_open to have only processes on one node, or in the extreme case MPI_COMM_SELF.

**Comment by J-shel** [comment]
Hi,
yes, by "reads input files from local storage", I mean reading separate hard drives on each node. Could OpenMPI handle it? As far as I know, The application compiled using Intel MPI could run successfully under this situation. I just wonder if I could change some mca parameters to make the application compiled using OpenMPI also run successfully.  I'm not sure if I got your point of "The only situation where this is expected to work is if you would restrict the communicator used during MPI_File_open to have only processes on one node, or in the extreme case MPI_COMM_SELF". Do you mean I have to change the code?

**Comment by jsquyres** [comment]
@J-shel Per @edgargabriel's reply, I don't think that the MPI IO API is designed for the case you are describing.  It really assumes shared storage to all nodes.  Perhaps Intel MPI has a mechanism to handle your case, but it sounds like that is an extension to MPI on their part.

**Comment by J-shel** [comment]
@jsquyres @edgargabriel  Thank you very much for your reply. I'm glad to know OpenMPI could also deal with this situation, but please don't bother to re-introducing the mca parameter if you think it may be not that necessary. For me, it is also a rare scenario since our parallel storage system is under maintenance. We tried it just for emergency use. 

Anyway, thank you and good day!
