### ISSUE TITLE
v4.1.x: --with-pmix=external does not fail if no external PMIx found

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#8829]
Per https://www.mail-archive.com/devel@lists.open-mpi.org/msg21284.html, Paul Kapinos mentions that

```
$ ./configure --with-pmix=external ...
```

when there is no external PMIx to be found will _not_ actually cause `configure` to fail.  This seems unexpected.

See attached `config.log` (Paul linked to it from his email): [config.log.gz](https://github.com/open-mpi/ompi/files/6337692/config.log.gz)

I found the relevant bits by searching for `component pmix:`.

It might be a bit tricky to fix this; there's a bunch of different PMIx components; several of them are external.

**Comment by bwbarrett** [comment]
I'm going to close this ticket; it is highly unlikely that we will fix this issue in the 4.1 series.  The issue does not occur in the 5.0/main series, because of the rewrite of the PMIx configure logic there.
