### ISSUE TITLE
segfault when using MPI_File_get_byte_offset on a 0-sized file view

### ISSUE THREAD

**Issue by shanedsnyder** [open-mpi/ompi#8841]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.0.5

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

via Spack

### Please describe the system on which you are running

My laptop, but have also triggered the problem on Summit's Spectrum MPI using OMPIO backend

* Operating system/version: Ubuntu 20.04.02
* Computer hardware: Intel® Core™ i7-8650U CPU @ 1.90GHz
* Network type: 

-----------------------------

## Details of the problem

MPI codes that set a 0-sized file view and then call MPI_File_get_byte_offset can trigger a segfault in OpenMPI, ultimately caused by a divide by zero. Here's an example code snippet to trigger the problem:

```
#include <mpi.h>
#include <stdio.h>

#define CHECK(fn) {int errcode; errcode = (fn); if (errcode != MPI_SUCCESS) handle_error(errcode, NULL); }
static void handle_error(int errcode, char *str)
{
        char msg[MPI_MAX_ERROR_STRING];
        int resultlen;
        MPI_Error_string(errcode, msg, &resultlen);
        fprintf(stderr, "%s: %s\n", str, msg);
        MPI_Abort(MPI_COMM_WORLD, 1);
}

int main(int argc, char** argv)
{
    MPI_File fh;
    MPI_Datatype t;
    MPI_Aint lb, extent;
    MPI_Count size;
    MPI_Offset offset;

    MPI_Init(&argc, &argv);
    CHECK(MPI_File_open(MPI_COMM_WORLD, argv[1], MPI_MODE_CREATE|MPI_MODE_RDWR,
            MPI_INFO_NULL, &fh));


    CHECK(MPI_Type_contiguous(0, MPI_INT, &t));
    CHECK(MPI_Type_commit(&t));


    CHECK(MPI_Type_get_extent(t, &lb, &extent));
    CHECK(MPI_Type_size_x(t, &size));

    printf("type stats: lb: %ld extent %ld size %lld\n",
            lb, extent, size);


    CHECK(MPI_File_set_view(fh, 0, MPI_BYTE, t, "native", MPI_INFO_NULL));
    CHECK(MPI_File_get_byte_offset(fh, 100, &offset));

    MPI_File_close(&fh);
    MPI_Type_free(&t);
    MPI_Finalize();
}
```

Digging through the code, it looks like there aren't safety checks in the OMPIO `mca_io_ompio_file_get_byte_offset()` routine to protect against a 0-value for the `f_view_size` parameter (which is set to 0 as part of `MPI_File_set_view()`), allowing for an eventual divide by zero condition. 

The code in question runs fine using ROMIO backend.

**Comment by roblatham00** [comment]
This is a distilled test case from a more involved interaction among HDF5, Darshan, and OpenMPI-IO https://forum.hdfgroup.org/t/parallel-hdf5-write-with-irregular-size-in-one-dimension/8284

**Comment by edgargabriel** [comment]
@shanedsnyder @roblatham00 thank you for the bug report, I will have a look at it.

**Comment by awlauria** [comment]
All PR's merged to release branches, closing.
