### ISSUE TITLE
Static linking of apps broken for master/v5.0.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#8850]
It looks like the wrapper compiler data files are not getting a full list of all the needed static libraries when `--disable-shared --enable-static` is being used to configure Open MPI on master and v5.0.x.

Here's what shows up in my RHEL 6 build with GCC 10:

```
libs=-lmpi
libs_static= -lmpi -lopen-pal -lutil -lm -lrt
```

Here's what I had to change `libs_static` to in order to get `examples/hello_c.c` (and friends) to compile:

```
libs_static=-lmpi -lopen-pal -lutil -lm -lrt -lpmix -levent_core -levent_pthreads -lhwloc -lz -lpciaccess
```

I'm guessing it should be easy enough to find / add `-lpmix -levent_core -levent_pthreads -lhwloc` to `libs_static` (perhaps it's just some configury that is missing this right now?).  I'm not sure how to easily get the missing dependencies, though, such as `-lz` (dependency of pmix) and `-lpciaccess` (dependency of hwloc).

**Comment by gpaulsen** [comment]
@bwbarrett @jsquyres is this already fixed?

**Comment by jsquyres** [comment]
@gpaulsen Not yet, no.  I don't think there has been any progress yet.

**Comment by gpaulsen** [comment]
We will probably need some infrastructure in PMIx and PRRTE, that OMPI configure can lookup from OMPI.  We may just need pkgcfg files from those subcomponents.
