### ISSUE TITLE
Miles of pgcc atomic warnings in 4.1.x builds

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#8853]
I don't know if anyone cares, but there are miles of PGCC atomic warnings in 4.1.x builds.

For example, see https://gist.githubusercontent.com/ibm-ompi/a046771cac27b7a44faa970c3b4fbb06/raw/8eaa05a59398e1b369f55171efc84a8cb5a76ad5/output.txt (this is the IBM CI build from https://github.com/open-mpi/ompi/pull/8847).

Can these be fixed?  If not, feel free to close this issue as "wontfix".

**Comment by jjhursey** [comment]
Duplicate of https://github.com/open-mpi/ompi/issues/7686
We really should have Nvidia look into helping with this issue:
