### ISSUE TITLE
MPI_T_init/MPI_T_finalize prior to MPI_Init no longer works on master

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#8860]
This test case stopped working after we switched from dynamic loading of plugins to static
```c
/*
 * $HEADER$
 *
 * Purpose of test:
 *   - check that failures occur if attempt to lock when
 *     no_locks given
 */

#include <stdlib.h>
#include <mpi.h>

int
main(int argc, char *argv[])
{
    int provided;

    MPI_T_init_thread(MPI_THREAD_SINGLE, &provided);

    MPI_T_finalize();

    MPI_Init(&argc, &argv);

    MPI_Finalize();
    return 0;
}
```
The test segfaults in MPI_Init if OFI or UCX components are active.  This test simulates the ibm onesided/c_lock_illegal.  The test runs nominally if OMPI master is configured with --enable-mca-dso.

**Comment by gpaulsen** [comment]
Related to Issue #8850

**Comment by awlauria** [comment]
PR's merged, closing.
