### ISSUE TITLE
Formatting changes have mangled some copyright headers

### ISSUE THREAD

**Issue by awlauria** [open-mpi/ompi#8868]
This should get fixed before the official v5.0 release.

From @devreal , an example is [opal_progress.h](
https://github.com/open-mpi/ompi/blob/4c4d5206fa1369a185cd13ee0db548c475f43c9a/opal/runtime/opal_progress.h).

**Comment by devreal** [comment]
Here is an example:

https://github.com/open-mpi/ompi/blob/master/opal/runtime/opal_progress.h
