### ISSUE TITLE
run MPI_Send and MPI_Recv errors

### ISSUE THREAD

**Issue by Adahai** [open-mpi/ompi#8877]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Open MPI v4.1.1rc2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

from a source/distribution tarball

### Please describe the system on which you are running
* Operating system/version: Ubuntu 5.4.0-6ubuntu1~16.04.12
* Computer hardware: 96*Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz， 8* Tesla V100
* Network type: eth

-----------------------------

## Details of the problem
I wrote a program to send and recv data  that Data is passed through the MPI's interface, In fact, what I pass in the interface is the memory handle of the GPU,  follow
*****************************************************cuTest.h  begin********************************************************
```
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
void enableAccess(int GPU_Flag_SELF, int GPU_Flag_RMOT);
void disableAccess(int GPU_Flag_SELF, int GPU_Flag_RMOT);
void getCudaMemory(void *gpu_ptr, int len, int gpu_flag);
void copyDataToDevice(void *gpu_ptr, void *host_ptr, int len, int gpu_flag);
void copyDataFromDevice(void *host_ptr, void *gpu_ptr, int len, int gpu_flag);
void srcFree(void *ptr, int gpu_flag );
```
*****************************************************cuTest.h  end********************************************************

*****************************************************cuTest.cu  begin********************************************************
```
#include "cuTest.h"
#include <cuda_runtime.h>
#define cudaCheckError()\
{                                          \
        cudaError_t e=cudaGetLastError();                                 \
        if(e!=cudaSuccess) \
        {                                              \
            printf("Cuda failure %s:%d: '%s'\n",__FILE__,__LINE__,cudaGetErrorString(e));   \
            exit(EXIT_FAILURE);                                           \
        }                                                                 \
}


void enableAccess(int GPU_Flag_SELF, int GPU_Flag_RMOT)
{
    int access = 0;
    cudaSetDevice(GPU_Flag_SELF);
    cudaDeviceCanAccessPeer(&access, GPU_Flag_SELF, GPU_Flag_RMOT);
    if (access) 
    {
        cudaDeviceEnablePeerAccess(GPU_Flag_RMOT, 0 );
        cudaCheckError();
        cudaSetDevice(GPU_Flag_RMOT);
        cudaCheckError();
        cudaDeviceEnablePeerAccess(GPU_Flag_SELF, 0 );
        cudaCheckError();
        cudaSetDevice(GPU_Flag_SELF);
        cudaCheckError();
    }
        
}

void disableAccess(int GPU_Flag_SELF, int GPU_Flag_RMOT)
{
    
        cudaSetDevice(GPU_Flag_SELF);
        cudaCheckError();

        int access = 0;
        cudaDeviceCanAccessPeer(&access, GPU_Flag_SELF, GPU_Flag_RMOT);
        if (access) 
        {
            cudaDeviceDisablePeerAccess(GPU_Flag_RMOT);
            cudaCheckError();
            cudaSetDevice(GPU_Flag_RMOT);
            cudaCheckError();
            cudaDeviceDisablePeerAccess(GPU_Flag_SELF);
            cudaCheckError();
            cudaSetDevice(GPU_Flag_SELF);
            cudaCheckError();
        }
            
}

void getCudaMemory(void *gpu_ptr, int len, int gpu_flag)
{
    cudaSetDevice(gpu_flag);
    cudaCheckError();
    cudaMalloc((void**)(&gpu_ptr), len);
    cudaCheckError();
    cudaMemset(gpu_ptr, 0, len);
    cudaCheckError();
}

void copyDataToDevice(void *gpu_ptr, void *host_ptr, int len, int gpu_flag)
{
    cudaSetDevice(gpu_flag);
    cudaCheckError();
    cudaMemcpy(gpu_ptr, host_ptr, len, cudaMemcpyHostToDevice);
    cudaCheckError();
}

void copyDataFromDevice(void *host_ptr, void *gpu_ptr, int len, int gpu_flag)
{
    cudaSetDevice(gpu_flag);
    cudaCheckError();
    cudaMemcpy(host_ptr, gpu_ptr, len, cudaMemcpyDeviceToHost);
    cudaCheckError();
}

void srcFree(void *ptr, int gpu_flag )
{
    cudaSetDevice(gpu_flag);
    cudaCheckError();
    cudaFree(ptr);
    cudaCheckError();
}
```
*****************************************************cuTest.h  end********************************************************
*****************************************************mpiTest.cpp  end********************************************************
```
#include "mpi.h"
#include<iostream>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include "cuTest.h"

#define DATA_SIZE 1024 
int main( int argc, char *argv[])
{
    int myrank;
    MPI_Status status;
    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &myrank);
    if (myrank == 0) /* send data in process zero */
    {
        char  data[DATA_SIZE]="abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh";
        char *hostdata_send = NULL; 
        char *gpu_ptr_send = NULL;

        hostdata_send = (char*)malloc(DATA_SIZE);
        strncpy(hostdata_send, data, strlen(data)+1);
        enableAccess(0, 6);
        getCudaMemory(gpu_ptr_send, strlen(hostdata_send)+1, 0);
        copyDataToDevice(gpu_ptr_send, hostdata_send, strlen(hostdata_send)+1, 0);

        printf("start send!\n");
        MPI_Send(gpu_ptr_send, strlen(hostdata_send)+1, MPI_CHAR, 1, 99, MPI_COMM_WORLD);
        printf("send finished!\n");
        
        printf("hostdata_send=%s\n",hostdata_send);
        srcFree(gpu_ptr_send, 0);
        free(hostdata_send);
    }
    else if (myrank == 1) /* recv data in process process one */
    {
        char *hostdata_recv=NULL;
        char *gpu_ptr_recv = NULL;
        hostdata_recv = (char*)malloc(DATA_SIZE);
        int recvlen = 73;
        enableAccess(6, 0);
        getCudaMemory(gpu_ptr_recv, recvlen, 6);
        
        printf("start received!\n");
        MPI_Recv(gpu_ptr_recv, recvlen, MPI_CHAR, 0, 99, MPI_COMM_WORLD, &status);
        printf("end received!\n");
        copyDataFromDevice(gpu_ptr_recv, hostdata_recv, recvlen, 6);
        printf("hostdata_recv=%s\n",hostdata_recv);
        free(hostdata_recv);
        srcFree(gpu_ptr_recv, 6);
    }

    MPI_Finalize();   
    return 0;
}
```
*****************************************************mpiTest.cpp  end********************************************************
then i executed the following command
```
nvcc -ccbin=g++ -c cuTest.cu
mpic++ -c mpiTest.cpp
mpic++ -o mtest cuTest.o mpiTest.o -L/usr/local/cuda/lib64 -lcudart
mpirun -np 2 --allow-run-as-root  mtest
```
**The following error occurs:**
start received!
[d8e7a2df9d6e:02765] *** An error occurred in MPI_Recv
[d8e7a2df9d6e:02765] *** reported by process [1068892161,1]
[d8e7a2df9d6e:02765] *** on communicator MPI_COMM_WORLD
[d8e7a2df9d6e:02765] *** MPI_ERR_BUFFER: invalid buffer pointer
[d8e7a2df9d6e:02765] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[d8e7a2df9d6e:02765] ***    and potentially your MPI job)
Cuda failure cuTest.cu:71: 'invalid argument'

Oddly enough, the MPI interface apparently already supports data transfer between GPUs, why are there these errors？

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -np 2 ./hello_world
```

**Comment by bosilca** [comment]
The MI_Recv is correct, I don't think your application is doing what you think it is doing. Look specifically at getCudaMemory and print the value of the expected GPU memory pointer.

The way you use the & in this function will modify the temporary on the stack and not the variable in the caller. You would need to change the prototype to pass the address to the pointer (via **) instead.

**Comment by Adahai** [comment]
thank you very much, it works After fixing an error **!
