### ISSUE TITLE
ORTE does not know how to route a message to the specified daemon located on the indicated node

### ISSUE THREAD

**Issue by ealemany** [open-mpi/ompi#8893]
## Background information
OS: CentOS7
Scheduler: Moab/Torque 

1 headnode
15 nodes (14 nodes with 12cores Multithreaded, 1 node with 64cores multithreaded)

All users /home directories on headnode are shared (NFS)  to all users /home directories on the nodes.

### What version of Open MPI are you using?
OpenMPI-4.1.0

### Describe how Open MPI was installed 
From a source/distribution tarball. OpenMPI is installed in /opt on headnode which is mounted (NFS) on /opt on all nodes.

I have installed OpenMPI before and I was able to make it work. Moab/Torque is not the issue (at lease for now).

As I mentioned I installed OpenMPI from source.

```shell
/opt# gunzip -c openmpi-4.1.0.tar.gz | tar xf -

/opt# cd openmpi-4.1.0

./configure --prefix=/opt/openmpi-4.1.0 --with-tm --enable-orterun-prefix-by-default

Resource Managers
-----------------------
Cray Alps: no
Grid Engine: no
LSF: no
Moab: no
Slurm: yes
ssh/rsh: yes
Torque: yes
 
OMPIO File Systems
-----------------------
DDN Infinite Memory Engine: no
Generic Unix FS: yes
IBM Spectrum Scale/GPFS: no
Lustre: no
PVFS2/OrangeFS: no


:/opt/openmpi-4.1.0# make all install
```
I ran the install with --with-tm as per Adaptive Computing instructions - but again this is not the issue.

For each user on the headnode I edited their .bashrc file (on the headnode only since users' /home is NFS mounted on /home on all the nodes)
```shell
#OpenMPI_Environment
export PATH="$PATH:/opt/openmpi-4.1.0/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/openmpi-4.1.0/lib"
```

On all nodes i edited   /etc/environment 
```shell
PATH=“/opt/openmpi-4.1.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
LD_LIBRARY_PATH=“/opt/openmpi-4.1.0/lib"
```
I ran 
```shell
$ ompi_info |  grep tm
  Configure command line: '--prefix=/opt/openmpi-4.1.0' '--with-tm' '--enable-orterun-prefix-by-default'
                 MCA ess: tm (MCA v2.1.0, API v3.0.0, Component v4.1.0)
                 MCA plm: tm (MCA v2.1.0, API v2.0.0, Component v4.1.0)
                 MCA ras: tm (MCA v2.1.0, API v2.0.0, Component v4.1.0)
```
on all nodes successfully 

As well as 
```shell
$ which mpirun
/opt/openmpi-4.1.0/bin/mpirun
```
For each user from the headnode.

I also created a __hostfile__  in /opt
```shell
$ cat hostfile
radonc-phaser01 slots=12
radonc-phaser02 slots=12
radonc-phaser03 slots=12
radonc-phaser04 slots=12
radonc-phaser05 slots=12
radonc-phaser06 slots=12
radonc-phaser07 slots=12
radonc-phaser08 slots=12
radonc-phaser09 slots=12
radonc-phaser10 slots=12
radonc-phaser11 slots=12
radonc-phaser12 slots=12
tq1 slots=12
tq2 slots=12
onpoint slots=64
```
I also added all the nodes hostmane + IP address in /etc/hosts
```shell
cat /etc/hosts
10.112.0.7      radonc-phaser01.stanford.edu    radonc-phaser01
10.112.0.8      radonc-phaser02.stanford.edu    radonc-phaser02
10.112.0.9      radonc-phaser03.stanford.edu    radonc-phaser03
10.112.0.10     radonc-phaser04.stanford.edu    radonc-phaser04
10.112.0.11     radonc-phaser05.stanford.edu    radonc-phaser05
10.112.0.13     radonc-phaser06.stanford.edu    radonc-phaser06
10.112.0.15     radonc-phaser07.stanford.edu    radonc-phaser07
10.112.0.17     radonc-phaser08.stanford.edu    radonc-phaser08
10.112.0.18     radonc-phaser09.stanford.edu    radonc-phaser09
10.112.0.19     radonc-phaser10.stanford.edu    radonc-phaser10
10.112.0.20     radonc-phaser11.stanford.edu    radonc-phaser11
10.112.0.12     radonc-phaser12.stanford.edu    radonc-phaser12
10.112.0.24     phaser-manager.stanford.edu     phaser-manager
10.112.0.5	tq1.stanford.edu		tq1
10.112.0.6	tq2.stanford.edu                tq2
10.112.0.22	onpoint.stanford.edu	        onpoint
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

### Please describe the system on which you are running

* Operating system/version: CentOS7 
* Computer hardware: Dell
* Network type: TCP - NFS

-----------------------------

## Details of the problem

When I ran a simple test:
```shell
$ mpirun --hostfile /opt/hostfile -np 20 hostname
```
it hangs. I have to do  Ctrl+Z then the error message is:
```shell
mpirun: Forwarding signal 20 to job
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   phaser-manager
  target node:  radonc-phaser02

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
--------------------------------------------------------------------------
[phaser-manager.stanford.edu:18119] 12 more processes have sent help message help-errmgr-base.txt / no-path
[phaser-manager.stanford.edu:18119] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

Same thing when I run
```shell
mpirun --hostfile /opt/hostfile -np 20 --map-by node hostname
```
```shell
mpirun --hostfile /opt/hostfile -np 20 --map-by slot hostname
```

**Comment by rhc54** [comment]
Try adding `--mca plm_base_verbose 5` to your mpirun cmd line. It will show you what is going on when starting the daemons and hopefully give some idea of why you are hanging. It sounds like your TCP stack doesn't know how to send a message from `phaser-manager` to `radonc-phaser02`.

**Comment by ealemany** [comment]
Thank you @rhc54 for looking into this issue.

This is the result of the command you suggested. I do not know what to make of it but the output hanged again and i had to do Ctrl+Z


```shell
[eric@phaser-manager .ssh 06:15 PM]$ mpirun --hostfile /opt/hostfile -np 20 --mca plm_base_verbose 5 hostname
[phaser-manager.stanford.edu:03820] [[39676,0],0] plm:rsh: final template argv:
	/usr/bin/ssh <template>        PATH=/opt/openmpi-4.1.0/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/opt/openmpi-4.1.0/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/opt/openmpi-4.1.0/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /opt/openmpi-4.1.0/bin/orted -mca ess "env" -mca ess_base_jobid "2600206336" -mca ess_base_vpid "<template>" -mca ess_base_num_procs "16" -mca orte_node_regex "phaser-manager,radonc-phaser[2:1-12],tq[1:1-2],onpoint@0(16)" -mca orte_hnp_uri "2600206336.0;tcp://10.112.0.24:38363" --mca plm_base_verbose "5" -mca plm "rsh" --tree-spawn -mca routed "radix" -mca orte_parent_uri "2600206336.0;tcp://10.112.0.24:38363" -mca pmix "^s1,s2,cray,isolated"
```

**Comment by rhc54** [comment]
Hmmm...ok, the problem is that ssh doesn't know how to start a proc on your compute nodes. Try debugging `ssh radonc-phaser02 hostname` - if you can get that to work, you will probably be able to run `mpirun`. Could be a host resolution problem, a firewall in the way, needing a password, etc.

**Comment by ealemany** [comment]
Interesting! indeed it asked for a password.
```shell
[eric@phaser-manager .ssh 06:22 PM]$ ssh radonc-phaser02 hostname
eric@radonc-phaser02's password: 
radonc-phaser02.stanford.edu
```
interestingly enough I ran the command to ssh to several nodes and most of them asked for a password.
I am confused as I though that since all the users' /home directories are shared (NFS) on all compute nodes there was no need for password-less ssh. 
I am also not sure how to configure password-less ssh on a cluster sharing users' /home directories. I know how to do it in non-cluster environment.

**Comment by rhc54** [comment]
I'm not sure how you would do it blanket for everyone. We usually just have individual users set it up for themselves. Basically, you need to add the ssh key for each node to your .ssh/authorized_keys file in your home directory.

**Comment by ealemany** [comment]
Each user on the headnode has its own login directories shared on all the nodes. My initial thought (which apparently is wrong) is since users logging directories are shared among the nodes and the OpenMPI directory is also shared among all nodes and the OpenMPI path is the same for all users there was no need to establish passwordless ssh connections.
I see what you are saying that I need to add the ssh key of each node to my .ssh/authorized_keys in my home directory but for some reason I do not seem able to make it work.
I guess I need to ask someone for assistance.

._____________________________________________________________________________________________________

Eric F.  Alemany
System Administrator for Research
EXO - Extended Operations

Stanford Medicine - Technology & Digital Services


On Apr 29, 2021, at 21:17, Ralph Castain ***@***.***> wrote:

﻿

I'm not sure how you would do it blanket for everyone. We usually just have individual users set it up for themselves. Basically, you need to add the ssh key for each node to your .ssh/authorized_keys file in your home directory.

**Comment by ealemany** [comment]
I was able to configure password-less SSH connection between the headnodes and all the nodes. 
mpirun is running well.

Thank you
