### ISSUE TITLE
ompi_coll_base_alltoallv_intra_basic_linear can return success even if ompi_request_wait_all returns MPI_ERR_IN_STATUS

### ISSUE THREAD

**Issue by zhngaj** [open-mpi/ompi#8916]
* Open MPI version:
Open MPI v4.1.1rc4 from https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.1rc4.tar.bz2.

* Building command:
./configure --prefix=/fsx/openmpi-4.1.1rc4/install --with-sge --without-verbs --disable-builtin-atomics --with-libfabric=/fsx/libfabric/install --enable-debug

* Operating system/version: Amazon Linux 2 
* Network type: EFA

* Problem:

In function `ompi_coll_base_alltoallv_intra_basic_linear`, if `ompi_request_wait_all` encounters an error, it's supposed to find a real error code and return it. However, I observed that `ompi_coll_base_alltoallv_intra_basic_linear` returns success even if `ompi_request_wait_all` returns MPI_ERR_IN_STATUS. 

It can be reproduced with 32 c5n.18xlarge instances on EC2 and with EFA provider using the following command: `mpirun -n 1152 -N 36 -hostfile ~/hosts  osu_alltoallv -i 1 -x 0 -m 131072:131072`

If I understand correctly, we should 
either set `err` and break only if `reqs[i]->req_status.MPI_ERROR != 0` [here](https://github.com/open-mpi/ompi/blob/v4.1.1rc4/ompi/mca/coll/base/coll_base_alltoallv.c#L284),
or set `request->req_status.MPI_ERROR = MPI_ERR_PENDING` in the error handling part of fuction `ompi_request_default_wait_all` [here](https://github.com/open-mpi/ompi/blob/v4.1.1rc4/ompi/request/req_wait.c#L333-L342).

Please let me know if it makes sense or I'm missing something.

**Comment by zhngaj** [comment]
Since #8933 is merged, close this issue.

**Comment by bosilca** [comment]
I am really curious in which context you encountered this issue ?

**Comment by bwbarrett** [comment]
We had a bug in our Libfabric provider where sends were failing in very specific scenarios, like all to all collectives.  They looked like hangs, because we were returning MPI_SUCCESS instead of the error from the PML, as the error from the collective and therefore not aborting.
