### ISSUE TITLE
MPI apps hang when prrte daemon aborts

### ISSUE THREAD

**Issue by gpaulsen** [open-mpi/ompi#8925]
From @rhc54: It appears that on master and v5.0.x, MPI apps can no longer "suicide" when their local daemon aborts - PMIx generates the event indicating connection was lost, but the MPI errhandlers "block" and don't let the process actually abort. As a result, I'm getting reports of mpirun leaving lots of orphans laying around when someone rapidly hits us with "ctrl-c" after "ctrl-c" since we just die once we get several quick cmds like that (under the assumption that mpirun itself is jammed).  The root problem is in the MPI errhandlers blocking when trying to abort.

This appears to be related to the FT stuff - and since you can't turn that off (or so it appears), there is no way around that behavior.

**Comment by gpaulsen** [comment]
This looks similar to https://github.com/openpmix/prrte/issues/953, but I doubt they're the same ( I don't know PMIx events well enough)

**Comment by rhc54** [comment]
No, that issue has nothing to do with this problem.

**Comment by gpaulsen** [comment]
@abouteiller Could you please take a look to see if this was introduced with the fault-tollerant changes?

**Comment by gpaulsen** [comment]
@abouteiller Could you please take a look to see if this was introduced with the fault-tollerant changes?

**Comment by abouteiller** [comment]
Yes, do you have a replication recipe for the problem?

**Comment by awlauria** [comment]
Re-opening as Ralph now thinks that ompi should be calling exit, not pmix. He's going to back out  openpmix/openpmix#2219 .

**Comment by awlauria** [comment]
I believe this is done - closing.
