### ISSUE TITLE
Question on thread-safety in pml/ucx progress

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#8927]
While digging through the code in pml/ucx in current master, I stumbled across the progress function and noticed that it does not prevent multiple threads from progressing the pml's ucp_worker concurrently: https://github.com/open-mpi/ompi/blob/master/ompi/mca/pml/ucx/pml_ucx.c#L519

This might be problematic because UCX barks if progress is called concurrently on the same worker:
https://github.com/openucx/ucx/blob/master/src/ucp/core/ucp_worker.c#L2522

Since the `opal_progress` function does not provide any thread serialization (https://github.com/open-mpi/ompi/blob/master/opal/runtime/opal_progress.c#L216) I wonder whether the `mca_pml_ucx_progress` function should serialize calls to `ucp_worker_progress` on the `ompi_pml_ucx.ucp_worker`?

@open-mpi/ucx  any insights on this?

Note that I have not observed an issue with this so I'm just putting this out as a question. One possible way this could trigger is if multiple threads test on different requests, triggering the progress engine concurrently ending up in `mca_pml_ucx_progress`.

**Comment by yosefe** [comment]
please note https://github.com/openucx/ucx/blob/e64f087bdfca38ee920a6eb252b44df985af63c2/src/ucp/core/ucp_worker.c#L2519 which makes `ucp_worker_progress()` thread-safe (when enabled explicitly during worker create)

**Comment by devreal** [comment]
Thanks @yosefe, I didn't see that `UCP_PARAM_FIELD_MT_WORKERS_SHARED` was set. I've been running into this issue on the opal wpool implementation, where this flag is not set...
