### ISSUE TITLE
mpi4py spawn fails in multi-node environment with Mellanox adapters

### ISSUE THREAD

**Issue by njchoi** [open-mpi/ompi#8938]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

OpenMPI 4.0.4rc3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From source,

```
  Configure command line: 'FCFLAGS=-fPIC'
                          '--prefix=/proj/openmpi-4.0.4-nvfortran'
                          '--with-cuda=/usr/local/nvidia/hpc_sdk/Linux_x86_64/20.7/cuda'
                          '--with-ucx=/proj/ucx-1.8.1'
```

### Please describe the system on which you are running

* Operating system/version: Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-137-generic x86_64)
* Network type: Mellanox Technologies MT27500 Family [ConnectX-3]

-----------------------------

## Details of the problem

Dear all,

I'm testing mpi4py on a two-node server (inode0, inode1) connected by Mellanox Infiniband, and MPI.Intracomm.Spawn is failing if manager and worker processes are in different nodes.
If they are in the same node, it works fine.
I'm attaching the codes which fail in our environment, which are very simple.
I'm running the manager process in inode0 and spawning a worker process to inode1.

```
mpiexec -np 1 python Manager.py
```

Manager.py
```python
from mpi4py import MPI
import os
import sys

MPI_info = MPI.Info.Create()
MPI_info.Set("add-host", "inode1")

comm = MPI.COMM_SELF.Spawn(sys.executable, args=[os.getcwd() + '/Worker.py'], maxprocs=1, info=MPI_info)
```

Worker.py
```python
from mpi4py import MPI
comm = MPI.Comm.Get_parent()
print('Hello World!')
```

Error Message
```
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[17342,1],0]) is on host: node0
  Process 2 ([[17342,2],0]) is on host: unknown!
  BTLs attempted: openib tcp self

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
[node0:07833] [[17342,1],0] ORTE_ERROR_LOG: Unreachable in file dpm/dpm.c at line 493
Traceback (most recent call last):
  File "Manager.py", line 8, in <module>
    comm = MPI.COMM_SELF.Spawn(sys.executable, args=[os.getcwd() + '/Worker.py'], maxprocs=1, info=MPI_info)
  File "mpi4py/MPI/Comm.pyx", line 1534, in mpi4py.MPI.Intracomm.Spawn
mpi4py.MPI.Exception: MPI_ERR_INTERN: internal error
[node1:10571] [[17342,2],0] ORTE_ERROR_LOG: Unreachable in file dpm/dpm.c at line 493
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_dpm_dyn_init() failed
  --> Returned "Unreachable" (-12) instead of "Success" (0)
--------------------------------------------------------------------------
[node1:10571] *** An error occurred in MPI_Init_thread
[node1:10571] *** reported by process [1136525314,0]
[node1:10571] *** on a NULL communicator
[node1:10571] *** Unknown error
[node1:10571] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[node1:10571] ***    and potentially your MPI job)
[node0:07829] 1 more process has sent help message help-mca-bml-r2.txt / unreachable proc
[node0:07829] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

This seems to be a network connectivity issue, but we have been running normally other MPI applications that do not employ MPI spawn.

FYI, the relavent software versions are as follows:

Compiler : GCC 7.3.0
UCX : UCX 1.8.1 (installed from source)
mpi4py : 3.0.3 (installed by pip)
Python : 3.8.5 (installed by conda)
Mellanox driver : 4.6-1.0.1.1 (installed from binary)

If you need more information about our environment, I'm willing to provide.
Any guidance of what I should look for will be also appreciated.

Many thanks in advance!

**Comment by jsquyres** [comment]
@open-mpi/ucx Can you comment?

**Comment by njchoi** [comment]
Folks, thank you for your concern, but never mind.
We just decided to use sockets instead of MPI spawn.
It appears that the support for MPI spawn is too unstable and portability is not guaranteed.
