### ISSUE TITLE
--enable-mca-no-build is not being honored.

### ISSUE THREAD

**Issue by awlauria** [open-mpi/ompi#8996]
With recent configury rework this is a regression on master and v5.0.x.

I did a git bisect and it seems to have stopped working on this commit: https://github.com/open-mpi/ompi/commit/000f7e86e0f5ee294e26ed22293a3770d7e76596#diff-49b9a659b0c410cc6da95abe258b24ca007dddbe6b6203953fc6997f2275dfa7

**Comment by jsquyres** [comment]
See https://github.com/open-mpi/ompi/pull/8974

**Comment by jsquyres** [comment]
This is actually a dup of #8963.

**Comment by awlauria** [comment]
Ah, thanks @jsquyres
