### ISSUE TITLE
Make new MCA fw open call to open mandatory components

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#9]
In talks with various developers, it seems like we have several places in the code base that have ''required'' components.  For example:
- BTL: needs "self"
- Coll: needs "self" and "basic"
- RAS: needs "dash_host" and "localhost" (sorta)

We've also seen users screw this up -- most often in the btl or coll cases, where they do something like this:

```
shell$ mpirun --mca btl openib ...
```

And then get confused when they try to MPI send a message to themselves and have the PML/BTL barf because it has no BTL path to send to itself.  

One possible way to make this nicer is to either modify the existing mca_base_components_open() function to take another argument (or leave the mca_base_components_open() interface alone and make a new function, perhaps named mca_base_components_open_required() that is the same as mca_base_components_open() but has the new parameter).  This new argument can be a list of components that ''have'' to be opened, and are therefore excluded from the "--mca <framework> <value>" selection criteria.  

We can add error checking in there such that if someone runs:

```
shell$ mpirun --mca coll ^basic ...
```

and the coll base lists "basic" in the "required" list, a friendly error message can be printed, etc.  You get the idea.

The point is that this might help a bunch of the code base become simpler if it can be assumed that certain components are always available (it would simplify a bunch of the coll base, for example).  It would also allow the Law of Least Astonishment for users running:

```
shell$ mpirun --mca btl openib ...
```

This kind of scenario would then work as the user expects because the BTL base will silently be loading "self" in the background (note that this is up to the framework -- so in an MTL situation, we wouldn't be calling the btl_base_open(), so this mandatory loading of the BTL self component wouldn't apply, etc.).

**Comment by gpaulsen** [comment]
Closing as won't fix.
