### ISSUE TITLE
opal_common_ucx_devices MCA param not checked correctly

### ISSUE THREAD

**Issue by omor1** [open-mpi/ompi#9012]
## Background information

The MCA parameter `opal_common_ucx_devices` isn't checked correctly against the available devices.

### What version of Open MPI are you using?

Open MPI 4.1.1

### Describe how Open MPI was installed

From source using Spack

### Please describe the system on which you are running

* SDSC Expanse
* CentOS 8.1.1911
* UCX 1.10
* Mellanox ConnectX-6

-----------------------------

## Details of the problem

I am trying to use the MCA param `opal_common_ucx_devices` to specify what UCX device to use. SDSC Expanse has three devices matching `mlx*`: one ConnectX-6 used for InfiniBand and two ConnectX-5 used for what appears to be 40GbE and 10GbE. When using btl/openib I had run into issues allowing Open MPI to use any of them, so I opted to restrict it to the `mlx5_2` device (`mlx5_2:1` in UCX parlance).

The `opal_common_ucx_devices` parameter was introduced in 562c57ce97cd40fb3e3c795fcc65200c737fe7ca, but it seems to not work correctly. Specifically, the `opal_common_ucx_check_device` function seems to always return failure, even against devices that _should_ match. It also rejects attempts to use non-IB devices e.g. `memory`. (I don't know if bypassing btl/self and btl/vader in favor of UCX's shared memory communication facilities is supported or useful, but it was worth a try. Can btl/self or btl/vader even be used for p2p communication when pml/ob1 is disabled?)

Currently, specifying `opal_common_ucx_devices` leads to support level `OPAL_COMMON_UCX_SUPPORT_TRANSPORT` being used rather than `OPAL_COMMON_UCX_SUPPORT_DEVICE`.

**Comment by yosefe** [comment]
@omor1 can you pls describe the parameter you are passing, and what is expected behavior vs. actual behavior?

**Comment by omor1** [comment]
@yosefe I have tried passing both `OMPI_MCA_opal_common_ucx_devices="mlx5_2"` and `OMPI_MCA_opal_common_ucx_devices="mlx5_2:1"`. In both cases, with verbose output I get:
```console
[exp-4-19:88865] common_ucx.c:304 posix/memory: did not match transport list
[exp-4-19:88865] common_ucx.c:304 sysv/memory: did not match transport list
[exp-4-19:88865] common_ucx.c:191 readlink(/sys/class/infiniband/memory/device/driver) failed: No such file or directory
[exp-4-19:88865] common_ucx.c:299 self/memory: matched transport list but not device list
[exp-4-19:88865] common_ucx.c:304 tcp/eno33.450: did not match transport list
[exp-4-19:88865] common_ucx.c:304 tcp/ib0: did not match transport list
[exp-4-19:88865] common_ucx.c:304 tcp/eno33: did not match transport list
[exp-4-19:88865] common_ucx.c:304 tcp/lo: did not match transport list
[exp-4-19:88865] common_ucx.c:304 rc_verbs/mlx5_0:1: did not match transport list
[exp-4-19:88865] common_ucx.c:299 rc_mlx5/mlx5_0:1: matched transport list but not device list
[exp-4-19:88865] common_ucx.c:299 dc_mlx5/mlx5_0:1: matched transport list but not device list
[exp-4-19:88865] common_ucx.c:304 ud_verbs/mlx5_0:1: did not match transport list
[exp-4-19:88865] common_ucx.c:299 ud_mlx5/mlx5_0:1: matched transport list but not device list
[exp-4-19:88865] common_ucx.c:304 rc_verbs/mlx5_2:1: did not match transport list
[exp-4-19:88865] common_ucx.c:299 rc_mlx5/mlx5_2:1: matched transport list but not device list
[exp-4-19:88865] common_ucx.c:299 dc_mlx5/mlx5_2:1: matched transport list but not device list
[exp-4-19:88865] common_ucx.c:304 ud_verbs/mlx5_2:1: did not match transport list
[exp-4-19:88865] common_ucx.c:299 ud_mlx5/mlx5_2:1: matched transport list but not device list
[exp-4-19:88865] common_ucx.c:191 readlink(/sys/class/infiniband/memory/device/driver) failed: No such file or directory
[exp-4-19:88865] common_ucx.c:299 cma/memory: matched transport list but not device list
[exp-4-19:88865] common_ucx.c:191 readlink(/sys/class/infiniband/memory/device/driver) failed: No such file or directory
[exp-4-19:88865] common_ucx.c:299 knem/memory: matched transport list but not device list
[exp-4-19:88865] common_ucx.c:191 readlink(/sys/class/infiniband/memory/device/driver) failed: No such file or directory
[exp-4-19:88865] common_ucx.c:299 xpmem/memory: matched transport list but not device list
[exp-4-19:88865] common_ucx.c:311 support level is transports only
```

If I don't pass anything for the MCA parameter and use the default `"mlx*"` I instead get
```console
[exp-3-30:55793] common_ucx.c:304 posix/memory: did not match transport list
[exp-3-30:55793] common_ucx.c:304 sysv/memory: did not match transport list
[exp-3-30:55793] common_ucx.c:191 readlink(/sys/class/infiniband/memory/device/driver) failed: No such file or directory
[exp-3-30:55793] common_ucx.c:299 self/memory: matched transport list but not device list
[exp-3-30:55793] common_ucx.c:304 tcp/eno33: did not match transport list
[exp-3-30:55793] common_ucx.c:304 tcp/ib0: did not match transport list
[exp-3-30:55793] common_ucx.c:304 tcp/eno33.450: did not match transport list
[exp-3-30:55793] common_ucx.c:304 tcp/lo: did not match transport list
[exp-3-30:55793] common_ucx.c:304 rc_verbs/mlx5_0:1: did not match transport list
[exp-3-30:55793] common_ucx.c:199 driver '../../../../bus/pci/drivers/mlx5_core' matched by 'mlx*'
[exp-3-30:55793] common_ucx.c:295 rc_mlx5/mlx5_0:1: matched both transport and device list
[exp-3-30:55793] common_ucx.c:311 support level is transports and devices
```

Note that I'm trying to use the `mlx5_2` device. `mlx5_1` is entirely disconnected and `mlx5_0` is configured fora t 25GbE. I think that UCX is smart enough to actually use `mlx5_2` despite what Open MPI thinks is happening.

**Comment by omor1** [comment]
Expected behavior is that `rc_verbs/mlx5_2:1` and `ud_verbs/mlx5_2:1` don't match transport list, but that `rc_mlx5/mlx5_2:1`, `ud_mlx5/mlx5_2:1`, and `rc_mlx5/mlx5_2:1` match both transport and device lists. (I am passing `OMPI_MCA_opal_common_ucx_tls="rc_mlx5,ud_mlx5,dc_mlx5"`.

Additionally, if I pass `memory` as part of the device list and e.g. `posix,sysv,self,cma,knem,xpmem` as part of the transport list, I'd expect that those devices are used—assuming that this is a supported option in Open MPI.

**Comment by yosefe** [comment]
`OMPI_MCA_opal_common_ucx_devices` is NOT intended to specify "which devices UCX should use". The intent is "which devices need to be present so the UCX pml would be enabled". In order to configure which devices UCX should utilize, need to use UCX-level configuration, as documented in https://openucx.readthedocs.io/en/master/faq.html#selecting-networks-and-transports - and not OMPI-level configuration.

That being said, the variable `OMPI_MCA_opal_common_ucx_devices` should contain the names of **device drivers** (see [documentation](https://github.com/open-mpi/ompi/blob/master/opal/mca/common/ucx/common_ucx.c#L124)). 
The reason for doing so is that RDMA device name in the Verbs layer (e.g mlx5_1) does not always indicate its vendor. The code [here](https://github.com/open-mpi/ompi/blob/master/opal/mca/common/ucx/common_ucx.c#L215) is matching device name to driver name.,

**Comment by omor1** [comment]
Thanks for clarifying that @yosefe! I clearly didn't read the MCA parameter description closely enough—I thought it worked similarly to e.g. `btl` and `btl_openib_if_include`. I'll go ahead and close the issue—this is working as intended.
