### ISSUE TITLE
Using OPAL_PREFIX to relocate an install is broken

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#9014]
Per discussion in Slack:

> I bet that's (using OPAL prefix to relocate an installation) broken :disappointed:.  We could fairly easily have opal_prefix set the right environment variables for PMIx and PRRTE.  And hopefully stop packaging those in the future so we don’t have to think about it.  Some day…

> and when I say broken, I bet its broken for when we build 3rd party libraries.  It should work fine for when the 3rd party libraries are found externally.

v5.0 RMs: since this is a regression compared to v4.x, I marked this as a blocker.  Indeed, I know some 3rd party software packages that include their own Open MPI install and rely on this behavior.

**Comment by bwbarrett** [comment]
I'll investigate how big of a problem this is in PMIx and PRRTE tomorrow and update with next steps.

**Comment by rhc54** [comment]
@mike0042 for your tracking purposes

**Comment by gpaulsen** [comment]
@bwbarrett Did you discover anything specific about this yet?  Will this be rolled into general configury fixes?

**Comment by bwbarrett** [comment]
We have a plan, that is basically OMPI is going to provide a binary mpirun (rather than a symlink) that just handles OPAL_PREFIX and then calls into PRRTE.  We still have some work to do in OMPI to set the PRRTE and PMIx prefix environment variables properly.  This is on my todo list, still.

**Comment by jsquyres** [comment]
Fixed on master via #9108 and #9116.

**Comment by awlauria** [comment]
Fixed in v5.0.x via #9163. Closing.
