### ISSUE TITLE
OPAL_CONVERTOR_PREPARE - is this awful practice?

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#9053]
The OPAL_CONVERTOR_PREPARE calls return for various convertor cases.  This seems to be bad practice to do in a macro.
Indeed in the places where this macro is used, there has been additional code added below the call which may never be reached as return had been invoked in OPAL_CONVERTOR_PREPARE.

**Comment by devreal** [comment]
There is no reason for this to be a macro, it could as well be an inline function. I'd love to see us move from macros to inline functions for any macro that is not a type-generic function (C's way of C++ templates). Such returns are just one reason, parameter substitution issues and debugging capabilities are others. I don't think there would be any negative impact on performance if `OPAL_CONVERTER_PREPARE` was turned into a function call.

**Comment by bosilca** [comment]
That macro is well the way it is, a common part for the initialization of both pack and unpack convertor, that returns as soon as the convertor is completely initialized.

**Comment by awlauria** [comment]
It's my understanding that the usage of `'inline` does not guarantee that the function is inlined, as with a macro. Compilers are still free to do what it wants as it is merely an unbinding suggestion:

```
Since this meaning of the keyword inline is non-binding, compilers are free to use inline substitution for any function that's not marked inline, and are free to generate function calls to any function marked inline. Those optimization choices do not change the rules regarding multiple definitions and shared statics listed above.
```

Here: https://en.cppreference.com/w/cpp/language/inline

Not saying that this is a bad way to go, but it is something to consider.

**Comment by hppritcha** [comment]
we will just leave this macro like it is for now.
