### ISSUE TITLE
Error: cannot find '-lpmpi' when compiling app with OMPI v1.10.7

### ISSUE THREAD

**Issue by dcentella16** [open-mpi/ompi#9056]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

OpenMPI 1.10.7

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.) 

Installed using tarball. 

### Please describe the system on which you are running
RHEL 8 

-----------------------------

## Details of the problem

I am trying to run a Makefile for a Finite Element code "LS-DYNA" to compile the executable. The Makefile requires me to use OpenMPI 1.10.7 with Inter Fortran Compiler. The error I am getting is the following: 

ld: cannot find -lpmpi

I already exported the path and ld_library path and checked using echo command. I have been working on Linux OS for 2 weeks and I have no experience in this kind of work. Any guidance?

Thanks in advance

**Comment by ggouaillardet** [comment]
Open MPI 1.10.7 is quite legacy today, and is clearly no more supported.

Anyway, I do not think there is a `libpmpi.so` so I suggest you simply remove `-lpmpi` from your `Makefile` and see how it goes. I expect it to work since all `PMPI_*` symbols (if ever used by your application) are in `libmpi.so`.

**Comment by awlauria** [comment]
@dcentella16 if you can it's recommended to upgrade to the ompi v4 series. You can find the release tarballs here:

https://www.open-mpi.org/software/ompi/v4.1/

https://www.open-mpi.org/software/ompi/v4.0/

**Comment by jsquyres** [comment]
Piling on what @ggouaillardet and @awlauria stated: it's also worth noting that the MPI standard does not require that a library named `libpmpi` exists / that `-lpmpi` works.  It's probably worth following @ggouaillardet's advice: just drop the `-lpmpi` and probably everything will be ok.

Please feel free to re-open this issue if you have further questions about it.
