### ISSUE TITLE
Will openmpi support encrypted communication among processes?

### ISSUE THREAD

**Issue by henrysun007** [open-mpi/ompi#9057]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
The latest master.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
```
git submodule update --init --recursive
./autogen.pl
./configure
make -j
make install
```

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
 10b03e44c443d5115af66dc0ce62f98bc37ac740 3rd-party/openpmix (v1.1.3-2995-g10b03e44)
 923745679dc43219e82bd5808e928349bf92d31b 3rd-party/prrte (dev-31223-g923745679d)

### Please describe the system on which you are running

* Operating system/version: ubuntu 20.04 with 5.4.0-42-generic 
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.
### The problem I am having
The data transmitted among processes in different hosts needs to be protected from network eavesdropping. Do open-mpi support the underlying encrypted communication? Or do you have better solutions to achieve the data protection?

**Comment by ggouaillardet** [comment]
I do not think we have such a plan.

It you are communicating over TCP, then one "agnostic" solution is to use IPSec or other encryption method at the TCP level.

**Comment by jsquyres** [comment]
To add to what @ggouaillardet stated: the focus of MPI has traditionally been extreme speed and performance.  Adding encryption is somewhat counter to that focus.  That being said, encryption is getting offloaded to hardware these days.

We'd be happy to consider contributions that optionally add things like TLS encryption to the TCP BTL and/or other transports.  Especially if the encryption can be offloaded (although -- depending on the transport -- there may be challenges pipelining two different offloads [encryption and network] in an efficient manner).  I would assume that this would be an excellent field of research for someone to pursue; I've had a small number of random discussions about topics like this with people, but I don't know if anyone is actively pursuing it.

**Comment by bwbarrett** [comment]
@jsquyres summed up the TCP situation pretty well.  For high speed networks, that is really a detail best left to the hardware, and is probably situational dependent.  For example, the network of a Cray EX computer is probably best protected by putting a lock on the door and a guard out front.  On the other hand, AWS EFA does support transparent encryption of data in transit, because it is hard for a company to put a guard in front of their Cloud VPC :).  In both cases, Open MPI does not need to do anything; the details are all hidden in hardware and Open MPI only needs to use the provided communication interface.

**Comment by henrysun007** [comment]
I am closing this issue as I have got the thoughts of the community about MPI communication encryption. Thank you.
