### ISSUE TITLE
CM PML getting selected instead of OB1 PML + usNIC BTL in Open MPI v4.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#9099]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

All 4.x versions.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From distribution tarball.

### Please describe the system on which you are running

* Operating system/version: RHEL 7
* Computer hardware: x86_64
* Network type: usNIC

-----------------------------

## Details of the problem

As reported to me off-list by @roguephysicist, with a usNIC-enabled network (and no other HPC-class network interfaces) with Open MPI v4.1.1 built against libfabric 1.12.1, Open MPI is somehow choosing the CM PML instead of OB1 (and the usNIC BTL).

This ultimately leads to an error in CM's `add_procs()`, and the MPI process aborts.

**Correction:** This happens in all v4.x versions.

Perhaps something changed in the OFI MTL selection logic...?  I am investigating.

**Comment by jsquyres** [comment]
Fixed by #9101, #9102, #9103, #9104.

**Comment by hppritcha** [comment]
@jsquyres can this be closed now?
