### ISSUE TITLE
Support cross-compilation of OpenMPI with Fortran enabled

### ISSUE THREAD

**Issue by vchuravy** [open-mpi/ompi#9106]
IIUC currently OpenMPI can only be cross-compiled with Fortran bindings disabled. As an example see https://github.com/open-mpi/ompi/blob/6d237e85d730ed946c9f45fcd3e19b78a243203e/contrib/platform/lanl/darwin/mic-common#L20-L25 and https://github.com/JuliaPackaging/Yggdrasil/pull/3230

This is due since several of the scripts require running their compiled prgrams:
- https://github.com/open-mpi/ompi/blob/8820fd2b0473e4be3550c25e6cfb3ebf1a09668e/config/ompi_fortran_get_alignment.m4#L124
- https://github.com/open-mpi/ompi/blob/8820fd2b0473e4be3550c25e6cfb3ebf1a09668e/config/ompi_fortran_get_kind_value.m4#L63
- https://github.com/open-mpi/ompi/blob/8820fd2b0473e4be3550c25e6cfb3ebf1a09668e/config/ompi_fortran_get_sizeof.m4#L80
- https://github.com/open-mpi/ompi/blob/8820fd2b0473e4be3550c25e6cfb3ebf1a09668e/config/ompi_fortran_get_value_true.m4#L115

Is there any other way we could get this information? Or that I as a distributor of the bindings could set these options?

**Comment by kawashima-fj** [comment]
Hi @vchuravy,

Open MPI supports cross-compiling itself using the `--with-cross=FILE` option of `configure`.

You need to create a file like [aarch64-linux-gcc.txt](https://github.com/open-mpi/ompi/files/6737172/aarch64-linux-gcc.txt) and specify the path to `FILE`. The values (Autoconf cache values) in the file are dependent on your environment (CPU architecture, OS, compiler). If you have a corresponding native compiler on the target machine, you can collect the values from the `config.log` file created by building Open MPI on the target machine using the corresponding native compiler. I don't know how to automate this procedure.

Also, [this mail thread](https://www.mail-archive.com/users@lists.open-mpi.org/msg30165.html) may be helpful.

**Comment by vchuravy** [comment]
@kawashima-fj Thank you! That was the information I was looking for :)
