### ISSUE TITLE
Process 2 is on host: unknown!

### ISSUE THREAD

**Issue by JPGlaser** [open-mpi/ompi#9113]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
`OpenMP Official Release v3.1.6`

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Installed on Docker Container via the following:
```
RUN echo "Installing Open MPI" && \
    export OMPI_DIR=/opt/ompi && \
    export OMPI_VERSION=3.1.6 && \
    export OMPI_URL="https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-$OMPI_VERSION.tar.bz2" && \
    mkdir -p /tmp/ompi && \
    mkdir -p /opt && \
    cd /tmp/ompi && \
    wget -O openmpi-$OMPI_VERSION.tar.bz2 $OMPI_URL && \
    tar -xjf openmpi-$OMPI_VERSION.tar.bz2 && \
    cd /tmp/ompi/openmpi-$OMPI_VERSION && \
    ./configure --prefix=$OMPI_DIR && \
    make -j8 install
ENV PATH=/opt/ompi/bin:$PATH
ENV LD_LIBRARY_PATH=/opt/ompi/lib:$LD_LIBRARY_PATH
```

### Please describe the system on which you are running

* Operating system/version: Ubuntu 20 LTS
* Computer hardware: Docker Container running on Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
* Network type: Internal Only

-----------------------------

## Details of the problem

Currently, running on a JupyterHub Notebook environment inside of NANOPulse docker container (https://hub.docker.com/r/nanograv/nanopulse). OpenMPI and mpi4py are installed as normal (see above and `RUN env MPICC=/opt/ompi/bin/mpicc pip install mpi4py`). I compile the following test below to test to make sure everything is working fine.

```c
  GNU nano 4.8                                   /home/jovyan/work/helloworld.c
#include <mpi.h>
#include <stdio.h>

int main(int argc, char** argv) {
    // Initialize the MPI environment
    MPI_Init(NULL, NULL);

    // Get the number of processes
    int world_size;
    MPI_Comm_size(MPI_COMM_WORLD, &world_size);

    // Get the rank of the process
    int world_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

    // Get the name of the processor
    char processor_name[MPI_MAX_PROCESSOR_NAME];
    int name_len;
    MPI_Get_processor_name(processor_name, &name_len);

    // Print off a hello world message
    printf("Hello world from processor %s, rank %d out of %d processors\n",
           processor_name, world_rank, world_size);

    // Finalize the MPI environment.
    MPI_Finalize();
}
```
Running this returns:
```shell
mpirun -n 5 ~/work/helloworld
Hello world from processor c4cd802d7fc0, rank 2 out of 5 processors
Hello world from processor c4cd802d7fc0, rank 3 out of 5 processors
Hello world from processor c4cd802d7fc0, rank 4 out of 5 processors
Hello world from processor c4cd802d7fc0, rank 0 out of 5 processors
Hello world from processor c4cd802d7fc0, rank 1 out of 5 processors
```

However, after installing AMUSE (https://github.com/amusecode/amuse) via the usual `pip` install or from source and running a simple test script, we see the following error:
```shell
(base) jovyan@c4cd802d7fc0:~/work/shared/amuse$ ./amuse.sh examples/simple/massloss.py
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[11747,2],0]) is on host: c4cd802d7fc0
  Process 2 ([[11747,1],0]) is on host: unknown!
  BTLs attempted: self tcp

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_dpm_dyn_init() failed
  --> Returned "Unreachable" (-12) instead of "Success" (0)
--------------------------------------------------------------------------
[c4cd802d7fc0:23105] [[11747,1],0] ORTE_ERROR_LOG: Unreachable in file dpm/dpm.c at line 433
Traceback (most recent call last):
  File "examples/simple/massloss.py", line 40, in <module>
    instance = Hermite(convert_nbody)
  File "/home/jovyan/work/shared/amuse/src/amuse/community/hermite/interface.py", line 208, in __init__
    legacy_interface = self.__interface__(**options)
  File "/home/jovyan/work/shared/amuse/src/amuse/community/hermite/interface.py", line 23, in __init__
[c4cd802d7fc0:23114] *** An error occurred in MPI_Init_thread
[c4cd802d7fc0:23114] *** reported by process [769851394,0]
[c4cd802d7fc0:23114] *** on a NULL communicator
[c4cd802d7fc0:23114] *** Unknown error
[c4cd802d7fc0:23114] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[c4cd802d7fc0:23114] ***    and potentially your MPI job)
    CodeInterface.__init__(self, name_of_the_worker="hermite_worker",
  File "/home/jovyan/work/shared/amuse/src/amuse/rfi/core.py", line 752, in __init__
    self._start(name_of_the_worker = name_of_the_worker, **options)
  File "/home/jovyan/work/shared/amuse/src/amuse/rfi/core.py", line 780, in _start
    self.channel.start()
  File "/home/jovyan/work/shared/amuse/src/amuse/rfi/channel.py", line 1067, in start
    self.intercomm = MPI.COMM_SELF.Spawn(command, arguments, self.number_of_workers, info=self.info)
  File "mpi4py/MPI/Comm.pyx", line 1534, in mpi4py.MPI.Intracomm.Spawn
mpi4py.MPI.Exception: MPI_ERR_INTERN: internal error
[c4cd802d7fc0:23107] 1 more process has sent help message help-mca-bml-r2.txt / unreachable proc
[c4cd802d7fc0:23107] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

For some reason, it seems to be trying to allocate one of the worker process to not the main host's free CPUs, which seems quite incorrect. I assume there is some sort of a variable that isn't being set correctly. Opinions?

~ Joe G.

**Comment by jsquyres** [comment]
I'm afraid we don't know anything about AMUSE or how it uses Open MPI.  The issue you opened on the amuse repo might be your best bet.  ☹️

**Comment by JPGlaser** [comment]
Very possible, @jsquyres , but I am wondering if the OpenMPI community might still be able to shed some light on this issue. I think it might be related to how OpenMPI is installed on the Docker container. 

Does the community have a standardized container environment that I could test this on to see if the same thing occurs? I am wondering if it has to do with BTL trying to use tcp rather than self and erroring out because it doesn't realize there are 30+ processors free on the hardware.

~ Joe G.

**Comment by jsquyres** [comment]
It's hard to say without knowing what `/amuse.sh` is doing.  That being said, I see what looks like a Python call stack in there, and it looks like it's invoking MPI4Py's MPI interface to MPI_Comm_spawn.  With ancient Open MPI like that, it's possible that there's something broken in the spawn API.  You might want to try updating to Open MPI 4.1.1 (i.e., the latest) and see if that fixes the issue.

There are small portions of the MPI/HPC community who use containers, but it's not a common use case.  The vast majority of HPC apps are designed to run on bare metal.

**Comment by JPGlaser** [comment]
This issue was indeed solved by updating to OpenMPI 4+. It seems that mpi4py doesn't actually check its compatibility with the installed OpenMPI, which was causing the error when everything was installed freshly.

We're moving towards containers just for quicker dropping of Singularity images onto HPC clusters to ensure uniform runtime environments. 

Thanks for your insight on this, I didn't think 3 was that "ancient," but my PhD work I think schewed my idea of what was old software. XD

~ Joe G.
