### ISSUE TITLE
patch for NAG compiler uses a method present only in libtool 2.4.5 and newer

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#9124]
PR https://github.com/open-mpi/ompi/pull/6378 applied a patch to configure which makes use of ```func_cc_basename```, resulting in the generated libtool script invoking this function.  This function is only defined in libtool versions 2.4.5 and newer.  Consequently, if one is building OMPI master from a git checkout, i.e. running ```autogen.pl``` using libtool version 2.4.4 or older, the following message is emitted during portions of the build process relying on the libtool script:

```
  CCLD     libmca_psensor_file.la
../../../../libtool: line 9834: func_cc_basename: command not found
```
It isn't fatal but might be disconcerting to someone building OMPI master.

**Comment by jsquyres** [comment]
This is relevant because some distros ship with older versions of Libtool (e.g., RHEL 7.x ships with Libtool v2.4.2).

It *seems* like this warning message doesn't matter, but... it's icky.

**Comment by rhc54** [comment]
Looks like people wound up patching libtool (again) with something like:
```shell
# func_basename FILE
# ------------------
# Set func_basename_result to FILE with everything up to and including
# the last / stripped.
if test yes = "$_G_HAVE_XSI_OPS"; then
  # If this shell supports suffix pattern removal, then use it to avoid
  # forking. Hide the definitions single quotes in case the shell chokes
  # on unsupported syntax...
  _b='func_basename_result=${1##*/}'
  _d='case $1 in
        */*) func_dirname_result=${1%/*}$2 ;;
        *  ) func_dirname_result=$3        ;;
      esac'

else
  # ...otherwise fall back to using sed.
  _b='func_basename_result=`$ECHO "$1" |$SED "$sed_basename"`'
  _d='func_dirname_result=`$ECHO "$1"  |$SED "$sed_dirname"`
      if test "X$func_dirname_result" = "X$1"; then
        func_dirname_result=$3
      else
        func_append func_dirname_result "$2"
      fi'
fi

eval 'func_basename ()
{
    $debug_cmd

    '"$_b"'
}'
```

**Comment by wzamazon** [comment]
I hit this issue when trying to build master. So the error is harmless?

**Comment by rhc54** [comment]
Yep - just annoying.

**Comment by jsquyres** [comment]
I see RHEL 7.4 ships with Libtool 2.4.2, which is the current minimum we allow in autogen.pl.

Should we emit a warning somewhere -- either in autogen.pl, or should someone fix the patch from #6378 about this missing function?

**Comment by awlauria** [comment]
RHEL 7.4 support ends August 31st of this month. Since this is a master only issue right now, I wouldn't rush to fix it based on that.

https://access.redhat.com/support/policy/updates/errata

**Comment by wzamazon** [comment]
Amazon Linux 2 ship with libtool 2.4.2, which is the most used linux OS on AWS.

**Comment by hppritcha** [comment]
closing due to old age and newer libtools versions
