### ISSUE TITLE
OMPI v4.1.2a1 complains about not using UCX even when no UCX hardware is available.

### ISSUE THREAD

**Issue by mwheinz** [open-mpi/ompi#9132]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Tip of the v4.1.x branch, sha bbbb06dc2d3d55905197dd28cbe6f99fd03ee359

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

$ ./configure --prefix=/usr/mpi/gcc/openmpi-v4.1.x --with-hwloc=internal --with-libevent=internal --with-pmix=internal --with-ofi        --with-ucx=no --with-usnic=no --with-ugni=no --with-psm2=yes --with-verbs=no --with-psm=no

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

I don't think 4.1.x has submodules? (No 3rd-party directory)

## Details of the problem

After expressly building OMPI without UCX, I still get complaints about not using UCX:

```
+ /usr/mpi/gcc/openmpi-v4.1.x/bin/mpirun -np 2 -map-by node --allow-run-as-root -machinefile /home/mheinz/work/mpi_apps/mpi_hosts -mca plm_rsh_no_tree_spawn 1 osu-micro-benchmarks-3.8-July12/mpi/pt2pt/osu_bw
--------------------------------------------------------------------------
By default, for Open MPI 4.0 and later, infiniband ports on a device
are not used by default.  The intent is to use UCX for these devices.
You can override this policy by setting the btl_openib_allow_ib MCA parameter
to true.

  Local host:              awbp029
  Local adapter:           hfi1_0
  Local port:              1

--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   awbp029
  Local device: hfi1_0
--------------------------------------------------------------------------
```

**Comment by jsquyres** [comment]
FYI @open-mpi/ucx

**Comment by yosefe** [comment]
@jsquyres this issues does not seem to be related to UCX: It's openib BTL on OPA hardware
Anyway, I would expect OFI to be selected here and not openib

**Comment by jsquyres** [comment]
@yosefe You're right; I missed that.

**Comment by hjelmn** [comment]
Yup. This setup should be using mtl/ofi and btl/ofi and not btl/openib.

**Comment by jsquyres** [comment]
@mwheinz openib is unfortunately basically unmaintained in the 4.x series.  If there's a bug fix that's needed, you might be the most interested party... ☹️
