### ISSUE TITLE
orte: mpi processes are left behind when there is a timeout

### ISSUE THREAD

**Issue by AboorvaDevarajan** [open-mpi/ompi#9133]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
`v4.1.x`

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
`git clone`

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
`None`

### Please describe the system on which you are running

* Operating system/version: RH8.4
* Computer hardware: ppc64le
* Network type: IB

-----------------------------

## OMPI 

```
$ git clone -b v4.1.x --recursive https://github.com/open-mpi/ompi.git ompiv4
$ cd ompiv4
$ ./autogen.pl

$ ./configure --disable-man-pages --enable-mca-no-build=btl-uct --enable-mpi1-compatibility --prefix /installs/ompiv4-install --enable-debug --with-cuda=/usr/local/cuda --with-ucx=/installs/ucx-install/

$ make -j40 install

```

```

//launch osu_ialltoallv test with less timeout so that it fails fast.

$ /installs/ompiv4-install/bin/mpirun --timeout 20 --report-bindings   --mca backtrace_lwcore_enable t --get-stack-traces --report-state-on-timeout  --prefix /installs/ompiv4-install --mca osc ucx,sm --mca pml ucx --mca btl ^vader,tcp,openib,uct -x LD_LIBRARY_PATH --mca coll basic,inter,libnbc,self,cuda --host n02:40,n03:40  -np 80 ./osu_ialltoall 

//timeouts and prints stacktrace

```

Leaked MPI processes:

```
$ ps -ef | grep osu
    960058       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
    960059       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
    960060       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
    960061       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
    960062       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
    960063       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
    960064       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
    960065       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
    960066       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
    960067       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
    960068       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
    960069       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
    960070       1 98 01:36 pts/2    00:12:35 ./osu_ialltoall
   ..
   ..
```

So far I can only recreate this on `ppc64le` nodes.

**Comment by abouteiller** [comment]
Thank you for your report, we are working toward a resolution for a similar issue in master (see issue #8925); hopefully we will be able to back port the fix to 4.x.

**Comment by jjhursey** [comment]
May be a duplicate of Issue #9369
@AboorvaDevarajan can you review Issue #9369 and PR #9370 to see if they address the issue you saw on the v4 branches?

**Comment by AboorvaDevarajan** [comment]
@jjhursey Josh, I verified that with the patch (4d717db7268b45f30f5fa2082e6f2fb638c29ba9) reported issue is no longer seen. Thanks. Closing the issue.
