### ISSUE TITLE
Installing Open MPI 1.10.7 on RHEL 8.4

### ISSUE THREAD

**Issue by dcentella16** [open-mpi/ompi#9157]
## Background information

I'm currently trying to install Open MPI for compiling purposes

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Open MPI 1.10.7 (Specific version requested for the program that I want to compile)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Im trying to install the package from tarball.

### Please describe the system on which you are running

* Operating system/version:  RHEL 8.4
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem

I havent been able to install Open MPI 1.10.7 on my RHEL 8.4 machine. I downloaded the tarball for Open MPI 1.10.7 from the website.

After initializing the environment by running the setvars.sh script provided by Intel oneAPI Toolkit, I configured OpenMPI by:

$ ./configure -prefix=/usr/local/openmpi CXX=icpc CC=icc FC=ifort F77=ifort

Then I ran Make all. No problems faced up to this point. After running:

$sudo make all install

I get the following error:

ld: /opt/intel/oneapi/compiler/2021.3.0/linux/bin/intel64/../../bin/intel64/../../lib/icx-lto.so: error loading plugin: libimf.so: cannot open shared object file: No such file or directory 
make[2]: *** [Makefile:1779: libmpi_usempi_ignore_tkr.la] Error 1
make[2]: Leaving directory '/home/dylancentella/Downloads/openmpi-1.10.7/ompi/mpi/fortran/use-mpi-ignore-tkr'
make[1]: *** [Makefile:3261: all-recursive] Error 1
make[1]: Leaving directory '/home/dylancentella/Downloads/openmpi-1.10.7/ompi'
make: *** [Makefile:1777: all-recursive] Error 1

Thanks for your help

**Comment by jsquyres** [comment]
You should know that Open MPI v1.10.x is fairly ancient and is no longer supported.  YMMV on RHEL 8.4 with Open MPI v1.10.x.

That being said, your problem *may* be that your Intel compiler environment is not propagating into your `sudo` environment.  E.g., you may need to source your intel compiler environment setup script in the sudo environment before running `make install`.

**Comment by dcentella16** [comment]
Thanks much. Problem solved.
