### ISSUE TITLE
Unable to find environment variables

### ISSUE THREAD

**Issue by SpinTensor** [open-mpi/ompi#9167]
I need to determine the rank before MPI_Init is called.
So far I did it with `getenv("OMPI_COMM_WORLD_RANK")`. 
But with the current git version (revision: 30a561bc37e36f4cc8ec18f91680dfc0906082de), `getenv` returns a NULL pointer.
Checking with `mpirun -np 2 env | grep OMPI` confirms that mpirun does not seem to set any environment variables.
With my ubuntu installed OpenMPI 4.0.3 the same command shows the expected environment variables.

Interestingly a call to `MPI_Comm_rank` after `MPI_Init` produces the correct ranks. I wonder where it gets the info from.

**Comment by ggouaillardet** [comment]
@SpinTensor you can use the `PMIX_RANK` environment variable

**Comment by SpinTensor** [comment]
Thanks a lot. `PMIX_RANK` works. Do I see it correctly, that there is no `PMIX_` variable for the size, or total number of ranks?

**Comment by ggouaillardet** [comment]
I did not see them either, but I spotted `OMPI_WORLD_SIZE` and `OMPI_COMM_WORLD_SIZE`

@rhc54 is there a clean way to retrieve this information?
For example, is it possible to call `PMIx_Init()` **before** `MPI_Init()`?
if yes, can `PMIx_Finalize()` be invoked before `MPI_Init()`? or does it have to be called after `MPI_Init()` (or even `MPI_Finalize()`) ?

**Comment by rhc54** [comment]
Not sure what folks are seeing, but using today's git HEAD:
```
$ mpirun -n 1 env
.....
OMPI_UNIVERSE_SIZE=10
OMPI_COMM_WORLD_SIZE=1
OMPI_WORLD_SIZE=1
OMPI_MCA_num_procs=1
OMPI_COMM_WORLD_LOCAL_SIZE=1
OMPI_WORLD_LOCAL_SIZE=1
OMPI_NUM_APP_CTX=1
OMPI_FILE_LOCATION=/Users/rhc/tmp/prte.Ralphs-iMac-2.1000/dvm.76726/1/0
OMPI_MCA_initial_wdir=/Users/rhc/openmpi/v5.0.x
OMPI_COMMAND=env
OMPI_ARGV=
OMPI_MCA_cpu_type=x86_64
OMPI_COMM_WORLD_RANK=0
OMPI_COMM_WORLD_LOCAL_RANK=0
OMPI_COMM_WORLD_NODE_RANK=0
....
```

**Comment by rhc54** [comment]
> is there a clean way to retrieve this information?

To address these questions...

> For example, is it possible to call `PMIx_Init()` **before** `MPI_Init()`?

Sure - you can always do that. You then have access to _all_ the PMIx-provided info and capabilities - e.g., to discover what resources are available to you (GPUs, memory, storage, cores) - and can use that info to "steer" your computation.

> if yes, can `PMIx_Finalize()` be invoked before `MPI_Init()`? or does it have to be called after `MPI_Init()` (or even `MPI_Finalize()`) ?

Either way is fine. The library simply refcounts the init/finalize pairs and finalizes when they balance. It's safer and far more efficient to invoke it after you call `MPI_Init` as that means the library won't try to zero out all its stored information. My recommendation is to treat it like a wrapper - if you invoke `PMIx_Init` before `MPI_Init`, then invoke `PMIx_Finalize` _after_ calling `MPI_Finalize`.

**Comment by SpinTensor** [comment]
I'm a bit surprised that you cannot reproduce my findings. So here is what I did:
```
$ ~/software/ompi_src$ git pull
Already up to date.
$ ~/software/ompi_src$ git status
On branch master
Your branch is up to date with 'origin/master'.
````
Then I simply configured, and installed it:
```
$ ./ompi_src/configure --prefix=/home/fuhl/software/ompi/ --enable-mpi-fortran --disable-man-pages
$ make && make install
```
I set some paths:
```
$ export PATH=$HOME/software/ompi/bin:$PATH
$ export LD_LIBRARY_PATH=$HOME/software/ompi/lib/:$LD_LIBRARY_PATH
$ export C_INLUCDE_PATH=$HOME/software/ompi/include/:$C_INLUCDE_PATH
$ export MANPATH=${HOME}/software/ompi/share/man:$MANPATH
```
Checking that it is the correct executable:
```
$ which mpirun
/home/fuhl/software/ompi/bin/mpirun
```
Next checking the environment:
```
$ mpirun -np 1 env | grep OMPI
$ mpirun -np 1 env | grep PMIX
PMIX_NAMESPACE=prterun-thalia-117130@1
PMIX_RANK=0
PMIX_SERVER_URI41=prterun-thalia-117130@0.0;tcp4://192.168.0.174:37221
PMIX_SERVER_URI401=prterun-thalia-117130@0.0;tcp4://192.168.0.174:37221
PMIX_SERVER_URI4=prterun-thalia-117130@0.0;tcp4://192.168.0.174:37221
PMIX_SERVER_URI3=prterun-thalia-117130@0.0;tcp4://192.168.0.174:37221
PMIX_SERVER_URI2=prterun-thalia-117130@0.0;tcp4://192.168.0.174:37221
PMIX_SERVER_URI21=prterun-thalia-117130@0.0;tcp4://192.168.0.174:37221
PMIX_SECURITY_MODE=native
PMIX_BFROP_BUFFER_TYPE=PMIX_BFROP_BUFFER_NON_DESC
PMIX_GDS_MODULE=hash
PMIX_SERVER_TMPDIR=/tmp/prte.thalia.1000/dvm.117130
PMIX_SYSTEM_TMPDIR=/tmp
PMIX_HOSTNAME=thalia
PMIX_VERSION=4.1.0a1
```
So for some reason the OMPI variables do not get set on my machine. I tested it on a different system, but the result was the same.

**Comment by rhc54** [comment]
When you hit something that bizarre, it usually means there is something borked with your setup. There are a couple of things that can happen - e.g., stale libraries in the build target or the submodules being out-of-date.

Try getting a fresh clone and delete the install target directory (your `/home/fuhl/software/ompi`) and then rebuild.

**Comment by SpinTensor** [comment]
I got a fresh clone of the ompi repo. and the problem of the undefined `OMPI_*` variables persisted. Then I removed the build and install folder and I got a different error:
```
$ mpirun -np 1 env 
prterun executable could not be found - unable to run
```
I suspected the system preinstalled compiler, so I compiled the same gcc version myself (9.3.0) and the 10.3.0 just for good measure. Compiling openmpi with my self compiled gccs resolved the problem. I can see the OMPI variables. 

If you are interested in what the difference is here is an `ls` of the `bin` folder
system-gcc (9.3.0):
```
ls bin/
mpic++  mpicc  mpiCC  mpicxx  mpiexec  mpif77  mpif90  mpifort  mpirun  ompi_info  opal_wrapper  oshrun
```
self compiled gcc (9.3.0):
```
ls bin
mpic++  mpiCC   mpiexec  mpif90   mpirun     opal_wrapper  pcc   prted      prterun  pterm
mpicc   mpicxx  mpif77   mpifort  ompi_info  oshrun        prte  prte_info  prun
```
and the same for the self compiled 10.3.0 gcc.
So it seems to be a problem of ubuntu and their preinstalled compiler. So far I never had problems with the preinstalled compiler on these systems.

Thanks for your help. I will close this issue now.

**Comment by jsquyres** [comment]
@SpinTensor FWIW: without seeing the build logs, it's hard to know why this happened.

**Comment by rhc54** [comment]
@jsquyres Looks to me like PRRTE failed to build for some reason. Guess that leads to two notes:

* if PRRTE fails to build (for whatever reason), then OMPI shouldn't install `mpirun` or any of its namesakes (e.g., `mpiexec`)
* if the user does not specify `--without-prte` and PRRTE itself decides it cannot build, then configure should error out

Yes/no?

**Comment by jsquyres** [comment]
Possibly.  But I wanted to see the full build logs, because there is at least a small possibility that two different versions of Open MPI were accidentally built/installed.  Or there was an error in the config / build / install process.  🤷‍♂️   I'd like to see the logs to be able to get definitive answers.

**Comment by SpinTensor** [comment]
Sure, I can provide the build logs. If you can tell me where to find them and which files you need. The only log I see is the `config.log`.

**Comment by jsquyres** [comment]
@SpinTensor Check out https://www.open-mpi.org/community/help/.  Thanks!

**Comment by SpinTensor** [comment]
In order to get the build logs, I had to rebuild everything. I am absolutely certain that I repeated everything exactly as I did before, but now it works fine. I will try to reproduce it on my other machine tomorrow. I think I might have installed system updates on this one. sorry.

**Comment by SpinTensor** [comment]
Sorry, it seems like I am not able to reproduce it anymore.

**Comment by jsquyres** [comment]
No worries.  Let us know if it happens again.
