### ISSUE TITLE
Open MPI 4.x configure is confusing PMIx's configure

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#9170]
As reported by @eschnett in #9162, Open MPI x4.0.x and v4.1.x `configure` is doing something weird with external hwloc/libevent and PMIx.

Specifically, in the files attached to #9162, you can see that Open MPI was configured (via spack) with:

```
./configure \
...
  --with-libevent=/Users/eschnett/src/spack/opt/spack/darwin-bigsur-skylake/gcc-11.1.0/libevent-2.1.12-kmrptsjbl4ghvwa54yzyozt7xqusvjac \
  --with-hwloc=/Users/eschnett/src/spack/opt/spack/darwin-bigsur-skylake/gcc-11.1.0/hwloc-2.5.0-fdhuxgmzrrihnqfemkfgsnfvis6opoam \
...
```

Looking at the output from Open MPI's `configure`, however, you can see that it passes the following when it calls PMIx's `configure` (artificially word wrapped for clarity):

```
--- MCA component pmix:pmix3x (m4 configuration macro)
checking for MCA component pmix:pmix3x compile mode... static
checking if PMIx timing is enabled... no (disabled)
configure: OPAL configuring in opal/mca/pmix/pmix3x/pmix
configure: running /bin/sh '/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-openmpi-4.1.1-4rhxaejgvtzajqrvrs3ikl2z5lg7zyiw/spack-src/opal/mca/pmix/pmix3x/pmix/configure' --disable-man-pages \
...
--enable-embedded-libevent --with-libevent-header=\"opal/mca/event/external/external.h\" \
--enable-embedded-hwloc --with-hwloc-header=\"opal/mca/hwloc/external/extern\al.h\"  \
...
'--with-libevent=/Users/eschnett/src/spack/opt/spack/darwin-bigsur-skylake/gcc-11.1.0/libevent-2.1.12-kmrptsjbl4ghvwa54yzyozt7xqusvjac' \
'--with-hwloc=/Users/eschnett/src/spack/opt/spack/darwin-bigsur-skylake/gcc-11.1.0/hwloc-2.5.0-fdhuxgmzrrihnqfemkfgsnfvis6opoam' \
...
```

Meaning: Open MPI appears to be giving PMIx conflicting information (use both the embedded and external libevent/hwloc).  PMIx apparently chooses to follow the `--enable-embedded-*` directives:

```
PMIx configuration:
-----------------------
Version: 3.2.3
Debug build: no
Platform file: (none)

External Packages
-----------------------
HWLOC: yes (embedded)
Libevent: yes (embedded)
ZLIB: yes (/Users/eschnett/src/spack/opt/spack/darwin-bigsur-skylake/gcc-11.1.0/zlib-1.2.11-oll4m2dh7d3vjpdlfpncdmeihx562kjr)
...
```

Whereas Open MPI does what what was requested via its `configure` CLI params (i.e., use externals):

```
Open MPI configuration:
-----------------------
Version: 4.1.1
Build MPI C bindings: yes
Build MPI C++ bindings (deprecated): no
Build MPI Fortran bindings: mpif.h, use mpi, use mpi_f08
MPI Build Java bindings (experimental): no
Build Open SHMEM support: no (disabled)
Debug build: no
Platform file: (none)

Miscellaneous
-----------------------
CUDA support: no
HWLOC support: external
Libevent support: external
PMIx support: Internal
...
```

So there's probably two things to fix here:

1. PMIx should probably check for conflicting CLI params like this and abort.  This may or may not be worth fixing in the older version of PMIx.
2. Open MPI should not pass conflicting CLI params to PMIx's `configure`.

FYI @rhc for the PMIx references.

**Comment by rhc54** [comment]
Errr...that configure conflict isn't in PMIx, @jsquyres  -  it is in the pmix3x component in OMPI. PMIx itself has no `--enable-embedded-hwloc` or equivalent libevent configure flags.

**Comment by jsquyres** [comment]
@rhc54 Ya, I understand that it's the pmix3x OPAL component invoking that `configure` statement.  Somehow it's passing in extra `--enable-embedded-*` params, but if they're being ignored, ok -- cool.

But the output at the end of the PMIx `configure` output implies that it's using an embedded hwloc/libevent.  Is that not what's happening? 

```
PMIx configuration:
-----------------------
Version: 3.2.3
Debug build: no
Platform file: (none)

External Packages
-----------------------
HWLOC: yes (embedded)
Libevent: yes (embedded)
ZLIB: yes (/Users/eschnett/src/spack/opt/spack/darwin-bigsur-skylake/gcc-11.1.0/zlib-1.2.11-oll4m2dh7d3vjpdlfpncdmeihx562kjr)
...
```

**Comment by rhc54** [comment]
All that means is that OMPI passed down the ``--enable-embedded-mode` flag. So PMIx assumes that both hwloc and libevent are going to have their header locations directly provided to PMIx, we don't bother to check the libraries, etc. You still have to pass the `--with-foo-header` flag to tell us the path to the header, and you set the `--with-foo=cobuild` flag.

@bwbarrett wrote all this stuff, not me. Best to ask him if there are questions - sounds like maybe OMPI v4 isn't in sync with the corresponding PMIx configury?

**Comment by rhc54** [comment]
Guess there is some variation on the older PMIx versions (I described what's on master), but the basic elements are the same. They don't have the `--with-foo=cobuild` flag - you just provide the header and the `--enable-embedded-mode` options.

**Comment by jsquyres** [comment]
I think we're (mostly) violently agreeing.

In Open MPI v4.1.1, I don't see any `--enable-embedded-[hwloc|libevent]` options in the PMIx that is embedded in the opal/mca/pmix/pmix3x component.  Meaning: I agree -- the opal/mca/pmix/pmix3x component is incorrectly choosing the pass those flags to the PMIx 3.x `configure` script.  I assume it means that those flags are getting ignored.

Here's what I see in the PMIx 3.x `configure` script in the Open MPI v4.1.1 tarball:

```
$ pwd
/.../openmpi-4.1.1/opal/mca/pmix/pmix3x/pmix
$ ./configure --help |& grep embedded
  --enable-embedded-mode  Using --enable-embedded-mode causes PMIx to skip a
                          in embedded mode)
                          Link any embedded components/tools that require it
                          to the provided libtool lib (used in embedded mode)

$ ./configure --help |& grep hwloc   
  --with-hwloc-header=HEADER
                          include hwloc.h
  --with-hwloc=DIR        Search for hwloc headers and libraries in DIR
  --with-hwloc-libdir=DIR Search for hwloc libraries in DIR

$ ./configure --help |& grep libevent
  --with-libevent-header=HEADER
  --with-libevent=DIR     Search for libevent headers and libraries in DIR
  --with-libevent-libdir=DIR
                          Search for libevent libraries in DIR
```

So ya -- it has the `--with-[libevent|hwloc]*` flags, which opal/mca/pmix/pmix3x is passing it.

My question is: since Open MPI *is* passing in the `--with-[libevent|hwloc]*` flags, why does PMIX's `configure` report that it's using the embedded versions:

```
PMIx configuration:
-----------------------
Version: 3.2.3
Debug build: no
Platform file: (none)

External Packages
-----------------------
HWLOC: yes (embedded)
Libevent: yes (embedded)
ZLIB: yes (/Users/eschnett/src/spack/opt/spack/darwin-bigsur-skylake/gcc-11.1.0/zlib-1.2.11-oll4m2dh7d3vjpdlfpncdmeihx562kjr)
...
```

**Comment by jsquyres** [comment]
Looking through the output a bit more, it looks like this is an overload of the word "embedded".

Looking at the PMIx configure output:

```
External Packages
-----------------------
HWLOC: yes (embedded)
Libevent: yes (embedded)
```

I assumed that that meant that PMIx meant it was using embedded copies of hwloc and libevent (presumably from Open MPI).

But when PMIx says "(embedded)" next to hwloc and libevent, it's really referring to the fact that *PMIx itself is embedded* -- not that it is using an embedded hwloc or libevent.  PMIx is therefore assuming that the upper level (i.e., Open MPI) has setup access to hwloc and libevent somehow.

This is therefore just slightly ambiguous wording in PMIx's `configure` output -- it doesn't reflect any real problem.

**Comment by rhc54** [comment]
I assume because it was given the `--with-hwloc-header` (and friends) flag if it wasn't given `--enable-embedded-mode`. 🤷‍♂️  I don't recall if I wrote that stuff or not, but either way I haven't looked at it in a very long time. I'd just as soon you guys stopped embedding those things 😄
