### ISSUE TITLE
need to implement MPI_COMM_TYPE_HW_GUIDED/UNGUIDED for MPI 4.0

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#9197]
from the MPI 4.0 standard changelog:
```
10. Section 7.4.2 on page 327.
MPI_COMM_TYPE_HW_UNGUIDED was added as a new possible value for the split_type
parameter of the MPI_COMM_SPLIT_TYPE function.

11. Section 7.4.2 on page 327.
MPI_COMM_TYPE_HW_GUIDED was added as a new possible value for the
split_type parameter of the MPI_COMM_SPLIT_TYPE function, as well as a new info
key "mpi_hw_resource_type". A specic value associated with this new info key is also
dened: "mpi_shared_memory"
```

**Comment by dalcinl** [comment]
For the shake of MPI-4 completeness, some minimal support could be added first.

* `MPI_COMM_TYPE_HW_GUIDED`: Just support info key `"mpi_hw_resource_type"` with value `"mpi_shared_memory"`. The implementation is equivalent to `MPI_COMM_TYPE_SHARED`, so it should be trivial to implement.
* `MPI_COMM_TYPE_HW_UNGUIDED`: I'm not sure about this one, but returning `MPI_COMM_NULL` should be OK?

**Comment by jjhursey** [comment]
The basic implementation is in PR https://github.com/open-mpi/ompi/pull/10630

It recognizes but does not implement the `MPI_COMM_TYPE_HW_UNGUIDED` split type. It will return `MPI_COMM_NULL` unconditionally. I'll open an issue to improve that as a second effort.

**Comment by jjhursey** [comment]
See Issue #10635 for follow-on work for a better implementation of `MPI_COMM_TYPE_HW_UNGUIDED`
