### ISSUE TITLE
mca_pml_ob1_progress does not check pckt_pending

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#92]
The mca_pml_ob1_progress() function does not check mca_pml_ob1.pckt_pending.  Thus, packets on this list don't progress, leading to hangs.
## Details

For example, let's say one process sends a rendezvous message to another process.  It starts by sending a lead fragment.  The receiver receives this lead fragment and tries to send back a rendezvous acknowledgement to indicate readiness.  Assume, however, that the receiver is out of fragments.  Then, mca_pml_ob1_recv_request_ack_send() fails to send and queues this "rendezvous acknowledgement" on mca_pml_ob1.pckt_pending using  MCA_PML_OB1_ADD_ACK_TO_PENDING.  Then, the process spins without ever sending this packet.  For example, opal_progress() will call mca_pml_ob1_progress(), but that function only checks mca_pml_ob1.send_pending.  Items on mca_pml_ob1.pckt_pending languish.
## Example

An example is attached to this ticket.  Rank 0 sends a large message to rank 1.  After a short delay, rank 1 sends 64 short messages to rank 2 to exhaust its fragments.  Then, rank 1 posts a receive for the large message, but it is unable to send the rendezvous acknowledgement to rank 0 since it is out of fragments.  After another short delay, rank 2 receives all its messages, returning fragments to rank 1.  At this point, rank 1 has many fragments available.  Despite that, it does not send the rendezvous acknowledgement to rank 0 since that item has been "lost" on the pckt_pending list.
## Motivating Instance

The SPECmpi2007 benchmark has been observed to hang on the small mtest data set at np=128.  It appears to be due to this problem.  The code is somewhat unusual in that message traffic is highly unidirectional.  Rank 0 performs ''very many'' short broadcasts.  It also sends many point-to-point messages.  Thus, PML queues (such as unexpected messages) grow very long.  Ultimately, rank 0 attempts a long message (over the rendezvous limit) to a receiver who has no free fragments and is unable to allocate any.  The code hangs.

In this particular case, `-mca coll_sync_barrier_before 100` works around the problem, presumably by managing flow control of fragments.

**Comment by jsquyres** [comment]
Discussion at the June 2015 dev meeting...  @bosilca @hjelmn 

A simple way to fix this is for when OB1 puts something on the packet pending list, it should also queue up an event on libevent to just try to unconditionally progress the packet pending list. Additionally, if OB1 ever drains the packet pending list, this event should be removed from the libevent base.

For completeness, the same thing should be done with the packet send list.

**Comment by jsquyres** [comment]
@bosilca Any progress on this?

**Comment by jsquyres** [comment]
According to @hjelmn we have done mitigation of these code paths (in the BTLs), and it doesn't happen any more.

Keeping this open because it feels like it would be nice if OB1 handled this instead of the BTLs.  Moving it to the Future milestone.

**Comment by bosilca** [comment]
OB1 now takes care of the pending packets in `mca_pml_ob1_process_pending_packets`.
