### ISSUE TITLE
setting MPIEXEC_TIMEOUT caused prterun to segfault (Master branch)

### ISSUE THREAD

**Issue by wzamazon** [open-mpi/ompi#9238]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

master branch

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

compiled from source

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
```
 cf79874bd1be12bbae26aafd43c168e86885fb8a 3rd-party/openpmix (v1.1.3-3057-gcf79874b)
 91b235f3c0d9be9abde7d79de70e6996fb08adba 3rd-party/prrte (psrvr-v2.0.0rc1-3954-g91b235f3c0)
```

### Please describe the system on which you are running

* Operating system/version:  Amazon Linux2
* Computer hardware: Intel  Xeon(R) Platinum 8124M CPU @ 3.00GHz
* Network type:  EFA

-----------------------------

## Details of the problem

I noticed that simply setting the environment variable `MPIEXEC_TIMEOUT` will cause `prterun` to segfault on ompi master branch.

To reproduce:
```
export MPIEXEC_TIMEOUT=7200
mpirun -n 2 --map-by ppr:1:node --output tag  --hostfile 2instances osu_latency
```

I got:

```
Segmentation fault      (core dumped) mpirun ....

```

**Comment by wzamazon** [comment]
Will try to get the backtrace from core dump

**Comment by wzamazon** [comment]
Looks like a bug in prte. `free` is called on the return of `getenv` when MPIEXEC_TIMEOUT was set.

I opened a PR to fix it:
https://github.com/openpmix/prrte/pull/1068

**Comment by wzamazon** [comment]
https://github.com/openpmix/prrte/pull/1068 has been merged.

Will ompi automatically update submodule? or someone need to open PR to bump the submodule?

**Comment by awlauria** [comment]
@wzamazon the submodule pointer will need to be updated for both v5.0.x and master to pick up the fix.

**Comment by wzamazon** [comment]
https://github.com/open-mpi/ompi/pull/9244 update the point to master branch

**Comment by wzamazon** [comment]
5.0.x is bumped to. so all done.
