### ISSUE TITLE
README on main, 5.0.x make no mention of needing recursive clone

### ISSUE THREAD

**Issue by PeterGottesman** [open-mpi/ompi#9271]
It seems that main and 5.0.x need to either be cloned with `git clone --recursive` , but there is no mention of this until `autogen.pl` is run. Should some mention of this should be added in either the README or HACKING.md?

```
$ ./autogen.pl
Open MPI autogen (buckle up!)

1. Checking tool versions
<snip>

2. Checking for git submodules

=== Submodule: 3rd-party/openpmix
    ==> ERROR: Missing

The submodule "3rd-party/openpmix" is missing.

Perhaps you forgot to "git clone --recursive ...", or you need to
"git submodule update --init --recursive"...?
```

**Comment by awlauria** [comment]
master: https://github.com/open-mpi/ompi/pull/9428
v5.0.x: https://github.com/open-mpi/ompi/pull/9429

**Comment by awlauria** [comment]
PR's merged, closing.

@PeterGottesman thanks! If you want to adjust the wording or add anything comment here or feel free to open a PR.
