### ISSUE TITLE
MPI_Sendrecv_replace performance suffers with --mca btl openib

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#93]
The performance of MPI_Sendrecv_replace operations suffers when "-mca btl openib" is specified.

The problem is that in ompi/mpi/c/sendrecv_replace.c, when the operation is too long, a temporary buffer must be allocated.  This buffer is allocated with MPI_Alloc_mem.  When openib is turned on, this calls mca_mpool_base_alloc -> mca_mpool_rdma_alloc -> mca_mpool_rdma_register, which incurs large RDMA overheads.

It appears that performance is better when the temporary buffer is allocated with malloc().

Users should probably avoid Sendrecv_replace for performance reasons, but we seem to hand them an unnecessarily harsh penalty.

The matter comes up on the users alias:  http://www.open-mpi.org/community/lists/users/2010/01/11676.php

**Comment by rhc54** [comment]
Per Mellanox, this can be closed. Any further work will be done on a separate new ticket.
