### ISSUE TITLE
Output redirection to files broken in development branches

### ISSUE THREAD

**Issue by albandil** [open-mpi/ompi#9309]
I am using self-compiled development version of Open MPI on several version of openSUSE. The output redirection command line options `--output-filename` and `--output-directory` of `mpiexec` are broken in the current master branch as well as in the v5.0.x branch. No files or directories are created when using the commands

```
mpiexec --output-filename log hostname
mpiexec --output-directory logs hostname
```

Here follow some results from my investigation via git bisect:

#### master branch

  - Pull request #7162 introduced options `--output-filename` and `--output-directory` (both working well)
  - Pull request #7202 has broken `--output-directory` (output directory no longer produced)
  - Pull request #8998 has broken `--output-filename` (output files no longer produced)

#### v5.0.x branch

  - (Pull request #7162 common with master)
  - (Pull request #7202 common with master)
  - Pull request  #9026 has broken `--output-filename` (output files no longer produced)

I consider the per-rank output redirection a great added value of Open MPI compared to other implementations and would welcome if this functionality was fixed.

I am aware that there is also some additional option `--output`, but at least in v5.0.x (haven't tried master) I am not able to reproduce `--output-filename` with that switch either.

**Comment by rhc54** [comment]
It actually appears to be working fine in master:
```
$ mpirun --output file=log hostname
$ ls log*
log.prterun-rhc-node01-22901@1.01.err  log.prterun-rhc-node01-22901@1.06.err  log.prterun-rhc-node01-22901@1.12.out
log.prterun-rhc-node01-22901@1.01.out  log.prterun-rhc-node01-22901@1.06.out  log.prterun-rhc-node01-22901@1.13.out
log.prterun-rhc-node01-22901@1.02.err  log.prterun-rhc-node01-22901@1.07.err  log.prterun-rhc-node01-22901@1.14.out
log.prterun-rhc-node01-22901@1.02.out  log.prterun-rhc-node01-22901@1.07.out  log.prterun-rhc-node01-22901@1.15.out
log.prterun-rhc-node01-22901@1.03.err  log.prterun-rhc-node01-22901@1.08.err  log.prterun-rhc-node01-22901@1.16.out
log.prterun-rhc-node01-22901@1.03.out  log.prterun-rhc-node01-22901@1.08.out  log.prterun-rhc-node01-22901@1.17.out
log.prterun-rhc-node01-22901@1.04.err  log.prterun-rhc-node01-22901@1.09.err  log.prterun-rhc-node01-22901@1.18.out
log.prterun-rhc-node01-22901@1.04.out  log.prterun-rhc-node01-22901@1.09.out  log.prterun-rhc-node01-22901@1.19.out
log.prterun-rhc-node01-22901@1.05.err  log.prterun-rhc-node01-22901@1.10.out
log.prterun-rhc-node01-22901@1.05.out  log.prterun-rhc-node01-22901@1.11.out
```
I noticed that the output for the local procs isn't getting correctly stored, so I'll look into that bug. But the cmd line option appears to be working.

That said, you should have gotten a deprecation warning for the old options. I'll have to fix that as well.

**Comment by albandil** [comment]
I can confirm that `--output file=...` works well. I must have been using wrong keyword ("filename"?).

**Comment by rhc54** [comment]
`filename` should also have worked - we only check the "file" portion of the string.

**Comment by rhc54** [comment]
I'll update OMPI once the PRRTE fix has been committed.
