### ISSUE TITLE
Cygwin Windows 10 build fails

### ISSUE THREAD

**Issue by AntonC9018** [open-mpi/ompi#9342]
## Background information

I'm trying to compile OpenMPI on Windows 10, but the build fails with errors.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Latest version 4.1.1, tarball from the [downloads page](https://www.open-mpi.org/software/ompi/v4.1/).

### Please describe the system on which you are running

* Operating system/version: *Windows 10*
* Computer hardware: *Intel Core i5-2410M, 64-bit*
* Cygwin 3.2.0, GCC 11.2.0, GNU Make 4.3

-----------------------------

## Details of the problem

I downloaded the latest `tar.gz` archive from the downloads page, then followed the instructions in the readme of this repo.

I did `./configure --prefix=/cygdrive/e/build |& tee config.out` (As far as I know, Cygwin is built on top of a POSIX compatibility layer, that's why the path is so weird). The command took about 30 minutes and exited without errors. Here is the log file:

[config.log](https://github.com/open-mpi/ompi/files/7092346/config.log)
[config.out](https://github.com/open-mpi/ompi/files/7092385/config.txt)

Running the make command `make -j 8 |& tee make.out` generates errors:

[make.out](https://github.com/open-mpi/ompi/files/7092358/make.txt)

My theory is that `make` uses some other version of `gcc` than the config script detects, which is why it fails, but I cannot tell.

**Comment by jsquyres** [comment]
Sorry for the delay in replying.

@matzeri Do you have any insight on what could be happening here?  Additionally, how is the support of Cygwin going this days -- is it still active?  Or is it being replaced by WSL?

**Comment by jsquyres** [comment]
@AntonC9018 Were you able to try to v4.1.0 Cygwin link that @matzeri provided?

**Comment by AntonC9018** [comment]
@jsquyres I don't need the lib anymore. Thanks for the help anyway.
