### ISSUE TITLE
ompi master branch: add "--output tag" caused nothing from stdout to be printed.

### ISSUE THREAD

**Issue by wzamazon** [open-mpi/ompi#9365]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

github master branch

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone from source 

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

c63aa552eba1376ee2b2e18d5a341de6d8cdee14 3rd-party/openpmix (v1.1.3-3104-gc63aa552)
 e40735f86bc5927b62eda4e429a89d0490098325 3rd-party/prrte (psrvr-v2.0.0rc1-3991-ge40735f86b)

### Please describe the system on which you are running

* Operating system/version: amazon linux2
* Computer hardware: graviton 2 cpu
* Network type: efa

-----------------------------

## Details of the problem
Under the above setting, when adding ```--output tag``` to command line, stdout was NOT printed.

For example:

Without ```--output tag```, the following command

```
prterun --np 2 --map-by ppr:1:node --machinefile ../../2instances /fsx/ALinux2_arm/opt/omb-5.6.2-ompi-master/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency

```
works fine. I got the following output:

```
Warning: Permanently added 'compute-st-c6gn16xlarge-2,172.31.27.158' (ECDSA) to the list of known hosts.
Warning: Permanently added 'compute-st-c6gn16xlarge-1,172.31.30.136' (ECDSA) to the list of known hosts.
# OSU MPI Latency Test v5.6.2
# Size          Latency (us)
0                      14.87
1                      14.82
2                      14.79
4                      14.78
8                      14.83
16                     14.79
32                     14.81
64                     14.96
128                    14.98
256                    15.07
512                    15.21
1024                   15.49
2048                   16.11
4096                   17.42
8192                   19.14
16384                  19.25
32768                  20.99
65536                  24.53
131072                 68.69
262144                 95.61
524288                158.69
1048576               298.78
2097152               572.62
4194304              1106.01
```

However, after add  `--output tag` to command line, 

```
prterun --np 2 --map-by ppr:1:node --output tag  --machinefile ../../2instances /fsx/ALinux2_arm/opt/omb-5.6.2-ompi-master/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency
```
The output to stdout was not printed any more. I got the following
```
Warning: Permanently added 'compute-st-c6gn16xlarge-1,172.31.30.136' (ECDSA) to the list of known hosts.
Warning: Permanently added 'compute-st-c6gn16xlarge-2,172.31.27.158' (ECDSA) to the list of known hosts.
```

As far as we can tell, this started happening from Sep 3rd.

**Comment by jsquyres** [comment]
@wckzhang Does the same thing happen with non-MPI applications?  E.g., if you `prterun ... ls -l`?

@rhc54 This is uncomfortably close to when we were just mucking around in IOF.  Did something get broken, perchance?

**Comment by wzamazon** [comment]
```prterun ... ls -l``` has the same issue.

Without ```--output tag```, it works

```
prterun -n 1 ls -l
total 40999
drwxrwxrwx 7      500      500    33280 Jan 27  2021 ALinux1
drwxrwxr-x 8 ec2-user ec2-user    33280 Mar  7  2021 ALinux2
drwxrwxr-x 3 ec2-user ec2-user    33280 Sep  8 18:30 ALinux2_
drwxrwxr-x 7 ec2-user ec2-user    33280 Jan 23  2021 ALinux2_arm
drwxrwxr-x 4 ec2-user ec2-user    33280 Jun 23 19:39 Backup
drwxrwxr-x 3 ec2-user ec2-user    33280 Jul  2  2020 data
-rwxr-xr-x 1      500      500     3818 Feb  4  2020 mr_analyze.py
-rw-rw-r-- 1      500      500     2041 May 14  2020 nodelist
drwxrwxr-x 2 ec2-user ec2-user    33280 Jul  7  2020 script
drwxrwxrwx 5 ec2-user ec2-user    33280 Jan 17  2021 softwares
-rw-r--r-- 1 root     root     41465299 Jun  4  2020 SubspaceBenchmarks_0603.tar.gz
drwxrwxr-x 3 ec2-user ec2-user    33280 Aug  5 19:44 test
drwxrwxr-x 3      500      500    33280 Jun 19  2020 tmp
drwxrwxr-x 6 ec2-user ec2-user    33280 Jun 20  2020 Ubuntu1804

```

With ```--output tag```, no output:

```
 prterun -n 1 --output tag ls -l
<<<nothing>>>
```

**Comment by rhc54** [comment]
> Did something get broken, perchance?

Actually, no - we just exposed a use-case that wasn't being handled correctly. Pretty typical one, so a mod to the way we handle the default situation was the best solution.
