### ISSUE TITLE
Orphaned processes on launch node when --timeout is triggered

### ISSUE THREAD

**Issue by jjhursey** [open-mpi/ompi#9369]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

`v4.0.x` [HEAD](https://github.com/open-mpi/ompi/commit/14cc1897834a8c17ddcb949e7d8ddf4bdf54e968) and `v4.1.x` [HEAD](https://github.com/open-mpi/ompi/commit/02d6331a138db9e35e8e8fa5f76d9c231869f1c6) branches are impacted.

`v5.0.x` and `master` are not impacted.

Related tickets:
 * PR #9272
 * PR #9350

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Installed from git clone on ppc64le system with GNU compiler.

### Please describe the system on which you are running

* Operating system/version: RHEL 7.7
* Computer hardware: ppc64le
* Network type: Ethernet (`tcp,vader,self`)

-----------------------------

## Details of the problem

Using the `--timeout` option to `mpirun` will result in orphaned processes on the same node as `mpirun` if the timeout is triggered. The processes on the remote node were cleaned up correctly.

Originally we thought this was limited to non-MPI applications since the MPI application were terminating correctly. However, while root causing this issue we were able to determine that MPI applications are impacted, but are getting terminated differently when the PMIx connection drops.

Experimental setup:
 * 2 nodes - 2 processes per node
 * `mpirun --map-by ppr:2:node --host f7n01:2,f7n02:2 --timeout 2 <APP>`
 * Three applications used:
   1. `sleep 30` : System utility - Non-MPI application
   1. `hello_c` : C application that calls `sleep(30)` before exiting
   1. `hello_mpi` : C application that does an `MPI_Init` followed by `sleep(30)` followed by `MPI_Finalize`
 * Watched the system processes on both nodes to monitor if orphans were generated.

Running the following will orphan the processes on the `mpirun` node after `mpirun` completes.
```
mpirun --map-by ppr:2:node --host f7n01:2,f7n02:2 --timeout 2 sleep 30
mpirun --map-by ppr:2:node --host f7n01:2,f7n02:2 --timeout 2 hello_c
```

Running the following will not orphan the process:
```
mpirun --map-by ppr:2:node --host f7n01:2,f7n02:2 --timeout 2 hello_mpi
```

-----------------------------

## Root cause analysis

I attached to the `mpirun` process after application launch, but before the timeout was triggered. In all three cases (including the MPI case) `mpirun` was idling in the first loop in [this section of code](https://github.com/open-mpi/ompi/blob/02d6331a138db9e35e8e8fa5f76d9c231869f1c6/orte/tools/orterun/orterun.c#L176-L197) - waiting for the launch to complete, not waiting for the job to complete (second loop):
```
    // wait for response and unpack the status, jobid
    while (orte_event_base_active && launchst.active) {
        opal_event_loop(orte_event_base, OPAL_EVLOOP_ONCE);
    }
    ORTE_ACQUIRE_OBJECT(orte_event_base_active);
    if (orte_debug_flag) {
        opal_output(0, "Job %s has launched",
                   (NULL == launchst.jdata) ? "UNKNOWN" : ORTE_JOBID_PRINT(launchst.jdata->jobid));
    }
    if (!orte_event_base_active || ORTE_SUCCESS != launchst.status) {
        goto DONE;
    }


    while (orte_event_base_active && completest.active) {
        opal_event_loop(orte_event_base, OPAL_EVLOOP_ONCE);
    }
    ORTE_ACQUIRE_OBJECT(orte_event_base_active);


    if (ORTE_PROC_IS_HNP) {
        /* ensure all local procs are dead */
        orte_odls.kill_local_procs(NULL);
    }
```

At a high level, `mpirun` is waiting for the job launch to complete instead of moving on to the loop where it waits for the job to complete. I confirmed that the job launched successfully, and `mpirun` is aware of that since the job state `ORTE_JOB_STATE_RUNNING` was activated and [the associated](https://github.com/open-mpi/ompi/blob/02d6331a138db9e35e8e8fa5f76d9c231869f1c6/orte/mca/state/hnp/state_hnp.c#L87-L109) `orte_plm_base_post_launch` function was called. The problem was that that information was not propagated to the `mpirun` process so that it would move on to the next loop.

 * When the timeout is triggered the `orte_timeout_wakeup()` function is called which sets the state of [`ORTE_JOB_STATE_ALL_JOBS_COMPLETE `](https://github.com/open-mpi/ompi/blob/02d6331a138db9e35e8e8fa5f76d9c231869f1c6/orte/orted/orted_submit.c#L3228-L3231)
 * This actives the `orte_quit` functions from the [`state/hnp` component](https://github.com/open-mpi/ompi/blob/02d6331a138db9e35e8e8fa5f76d9c231869f1c6/orte/mca/state/hnp/state_hnp.c#L93-L114)
 * `orte_quit` will [break the event loop](https://github.com/open-mpi/ompi/blob/02d6331a138db9e35e8e8fa5f76d9c231869f1c6/orte/runtime/orte_quit.c#L140-L143)
 * This will cause `mpirun` to leave the first loop in the code section above and enter the `goto DONE` statement from the ` if (!orte_event_base_active || ORTE_SUCCESS != launchst.status) {` check
    - launchst.active = true
    - launchst.status = 0
    - orte_event_base_active = false
 * `mpirun` then jumps into the shutdown skipping over the `orte_odls.kill_local_procs(NULL);` thus orphaning local processes.
   * Why are MPI applications not orphaned? Because in `orte_finalize` we call `opal_pmix.server_finalize` (`PMIx_server_finalize`) which will eventually call `pmix_ptl_base_stop_listening` to drop the socket between the `mpirun` process and each local application process. The local (PMIx enabled) application processes will see the socket drop and shutdown. Without this mechanism we would have seen the MPI processes also be orphaned by `mpirun`.

-----------------------------

## Solution summary

The core problem is that `mpirun` is not transitioning to the "waiting for completion" after a successful launch.
To resolve this problem we need a call from `orte_plm_base_post_launch` (triggered when the job enters the state `ORTE_JOB_STATE_RUNNING`) to the `mpirun` process to tell it to move to the next phase.

There is a potential secondary problem where if the local launch is successful, but the remote launch fails then local orphans could still be generated since the `mpirun` process will then skip over the code to terminate the local processes.
Upon investigation, the `errmgr/default_hnp` component is actived in this state and end up in [this call](https://github.com/open-mpi/ompi/blob/02d6331a138db9e35e8e8fa5f76d9c231869f1c6/orte/mca/errmgr/default_hnp/errmgr_default_hnp.c#L858-L860) to `orte_plm.terminate_orteds`. This will eventually trigger `mpirun` to terminate the local processes.

We could add the code to `orte_odls.kill_local_procs(NULL);` if the launching loop fails in an abundance of caution, but it is not 100% necessary it seems.

**Comment by jjhursey** [comment]
I posted a fix in PR #9370 for the issue identified against `v4.0.x`. Once reviewed then I'll cherry-pick to `v4.1.x`

**Comment by jjhursey** [comment]
I found a scenario where the secondary problem can occur.

If the remote node is slow launching (possibly due to a file system issue) and the timeout triggers then this is not an abnormal failure, but a scenario where the timeout starts shutting down `mpirun` while it is waiting in the launch complete loop.

So we will need a fix to make sure that `mpirun` always cleans up its local children before exiting.

**Comment by jjhursey** [comment]
Per [this request](https://github.com/open-mpi/ompi/pull/9370#issuecomment-919314519) I took another look at Open MPI master with PRTE.

Issue 1 does not seem to occur with PRTE. It is idling [here](https://github.com/openpmix/prrte/blob/2a459fa5f4c46d90a37c5894740d04fe487a6147/src/prted/prte.c#L1234-L1237) when the timeout is triggered. So it moved from the 'waiting for launch' to the 'waiting for termination phase. This is because the `PMIx_Spawn_nb` call completed releasing it from the [first loop](https://github.com/openpmix/prrte/blob/2a459fa5f4c46d90a37c5894740d04fe487a6147/src/prted/prte.c#L1202-L1206)

However, Issue 2 is present and more problematic in PRTE. I added some code to odls_base_default_fns.c:1092:
```diff
diff --git a/src/mca/odls/base/odls_base_default_fns.c b/src/mca/odls/base/odls_base_default_fns.c
index 52a30fd3..b1425181 100644
--- a/src/mca/odls/base/odls_base_default_fns.c
+++ b/src/mca/odls/base/odls_base_default_fns.c
@@ -1089,6 +1089,10 @@ void prte_odls_base_spawn_proc(int fd, short sd, void *cbdata)
         goto errorout;
     }
 
+    if (!PRTE_PROC_IS_MASTER) {
+        sleep(30);
+    }
+
     PRTE_ACTIVATE_PROC_STATE(&child->name, PRTE_PROC_STATE_RUNNING);
     PRTE_RELEASE(cd);
     return;
```

Then ran with (either `mpirun` or `prterun` - so not an `ompi` personality issue it seems):
```
mpirun --map-by ppr:2:node --host f7n01:2,f7n02:2 --timeout 2 sleep 60
```

The timer is not triggered until the launch is complete. So it waits ~32 seconds before terminating instead of ~2 sec.
The `prterun` process is waiting in the  [first loop](https://github.com/openpmix/prrte/blob/2a459fa5f4c46d90a37c5894740d04fe487a6147/src/prted/prte.c#L1202-L1206) for `PMIx_Spawn_nb` to terminate.

From a quick read of the PRTE code the timer is set after the launch (instead of before it) during the `prte_plm_base_post_launch` function [here](https://github.com/openpmix/prrte/blob/2a459fa5f4c46d90a37c5894740d04fe487a6147/src/mca/plm/base/plm_base_launch_support.c#L992-L1006) which means that the timer doesn't start until the job successfully launches - which is problematic if one of the daemons encounters a very slow file system mount, for example.

**Comment by rhc54** [comment]
Hmmm...so are we interpreting "timeout" to be total time spent executing the job (including launch), or time spent executing the application (which excludes launch)? IIRC, there was some confusion over this point as a user might set a time limit on the latter (since they have some idea of how long their app might take to execute), but no control over how long it takes to launch the job.

Thus, on some systems that were slow to launch (e.g., slow file systems), users were unexpectedly timing out and questioning how to set "timeout" when you don't know launch time.

Perhaps we need to separate the two? A timeout for overall execution (or maybe just for launch?) and a separate timeout for app execution time?

**Comment by jjhursey** [comment]
Possibly. The behavior in the v4 series is a comprehensive timeout (inclusive of the launch time). This is pretty useful in testing where you don't want a hang in the launch sequence to hang your testing setup. I've seen folks use it as a hedge against slow ssh issues which can crop up depending on cluster config. I'd prefer to keep the behavior of `--timeout` consistent with total time taken for at least the testing case.

Having new `--timeout-app` that starts just after the launch is complete seems like it might be useful. I'm not sure.

**Comment by rhc54** [comment]
Okay, I think that makes sense. Looking at the code, I think PRRTE got caught between definitions - the timeout event got reused for the launch timeout, which can cause confusion. I'll separate the two.

**Comment by jjhursey** [comment]
That sounds good. Thanks!

**Comment by jjhursey** [comment]
Fixed references:
 * v4.0.x: https://github.com/open-mpi/ompi/pull/9370
 * v4.1.x: https://github.com/open-mpi/ompi/pull/9371
 * v5.0.x: https://github.com/open-mpi/ompi/pull/9383
 * master: https://github.com/open-mpi/ompi/pull/9382

This can now be closed since all active release branches and `master` have been fixed.
