### ISSUE TITLE
Improper cleanup/exit for rank with PID 0

### ISSUE THREAD

**Issue by rwespetal** [open-mpi/ompi#9389]
Thank you for taking the time to submit an issue!

## Background information
I'm encountering an error for unclean shutdown after a [LAMMPS benchmark](https://github.com/lammps/lammps/tree/master/bench) completes. The error message reports that the process is for PID 0 which is unexpected. When I'm able to get this to trigger, the error seems to persist for that node.

I'm hoping to gather some verbose logs soon to help with debug, but wanted to file an issue in advance in case there suggestions on what I should look for.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
Open MPI 4.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Distribution tarball

### Please describe the system on which you are running

* Operating system/version: Amazon Linux 2
* Computer hardware: Amazon EC2 c5n.18xlarge
* Network type: OFI MTL + Libfabric + EFA

-----------------------------

## Details of the problem

```
$ mpirun -n 4608 --map-by ppr:36:node lmp

LAMMPS (22 Aug 2018)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:87)
  using 1 OpenMP thread(s) per MPI task
Reading data file ...

<snip> 

Dangerous builds = 0
Total wall time: 0:00:25
--------------------------------------------------------------------------
mpirun has exited due to process rank 1297 with PID 0 on
node queue1-dy-c5n18xlarge-37 exiting improperly. There are three reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.

This may have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).

You can avoid this message by specifying -quiet on the mpirun command line.
--------------------------------------------------------------------------
```

**Comment by jsquyres** [comment]
@rwespetal Were you able to glean any further info on this issue?

**Comment by rhc54** [comment]
The zero value for the reported pid just means that the RTE either didn't get a chance to record it, or lost the entry when the proc failed. Either way, it is irrelevant to the problem.
