### ISSUE TITLE
Hang when running out of registered memory

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#94]
There appears to be a hang in OMPI in some cases when one process runs out of registered memory.

The U. New Hampshire !OpenFabrics validation guys are reporting to me that it ''looks'' like Open MPI hangs in IMB on machines with small amounts of memory.  Towards the end of the IMB alltoall tests, it ''looks'' like a receiver is failing to register memory (no more is available and nothing can be evicted), and that failure is not propagating back to the sender.  Since everything is waiting for this receive, the receiver never de-registers anything, hence, the receive never completes.  Therefore: hang.

It appears that setting the MCA param to limit the amount of registered memory works fine (mpool_rdma_rcache_size_limit).

I am creating this ticket and throwing it to the !OpenFabrics vendors to decide how to handle it...

**Comment by rhc54** [comment]
Per Mellanox, this can be closed. Any further work will be done on a separate new ticket.
