### ISSUE TITLE
./configure --help=recursive is not exposing options

### ISSUE THREAD

**Issue by cponder** [open-mpi/ompi#9419]
The OpenMPI 4.1.1 source file
```
./ompi/mca/op/avx/op_avx_functions.c
```
has this entry
```
58    #    error The configure step has detected possible support for AVX512 and/or AVX2 but the compiler flags during make are too restrictive. Please disable the AVX component by adding --enable-mca-no-build=op-avx to your configure step.
```
The ```./configure --help``` command describes the ```--enable-mca-no-build``` option, but the
```
./configure --help=recursive
```
doesn't go any deeper than that, so I wasn't aware that the option was available.
I'd expect the ```recursive``` option to expose this level of detail.
As it is, it doesn't add anything to the output, which seems redundant.

**Comment by bwbarrett** [comment]
I'm not sure I understand the issue.  I see the same help output with `./configure --help` and `./configure --help=recursive`:

```
  --enable-mca-no-build=LIST
                          Comma-separated list of <type>-<component> pairs
                          that will not be built. Example:
                          "--enable-mca-no-build=btl-portals,oob-ud" will
                          disable building the "portals" btl and the "ud" oob
                          components.
```

Are you seeing something other than that behavior?

**Comment by cponder** [comment]
My point is, that you *shouldn't* see the same output with both.
The ```=recursive``` option should give more details, otherwise there's no reason to have it.
I think it should be explaining the ```-enable-mca-no-build=op-avx``` setting, for example.

**Comment by bwbarrett** [comment]
That's not actually what the `--help=recursive` option does.  `--help=recursive` comes into play when a package (like Open MPI) includes packages with their own configure (like openpmix in the 5.0 branch).  `--help` will only show the top-level configure options, but `--help=recursive` will show the options of the sub-configures as well.  As a matter of fact, `--help=recursive` shows the short help message for options, meaning that in many situations it will show *less* information than plain `--help`.

As the `--enable-mca-no-build` help says, the option disables the building of certain components.  `--enable-mca-no-build=op-avx` will disable building the AVX OP component.  The OP framework provides the operators for operations like MPI_REDUCE and the AVX component implements those operations using AVX commands.

**Comment by cponder** [comment]
It doesn't document the ```op-avx``` setting. Can't you fix this? We shouldn't have to be reading the source files to find these.

**Comment by jsquyres** [comment]
@cponder I'm a little confused.  Doesn't the `#error The configure ...` message appear when it fails to compile?

**Comment by cponder** [comment]
No, it doesn't show up.
But, regardless, why shouldn't the ```--enable-mca-no-build=op-avx``` option be documented by the ```./configure --help``` command??

**Comment by jsquyres** [comment]
It *is* documented:

```
  --enable-mca-no-build=LIST
                          Comma-separated list of <type>-<component> pairs
                          that will not be built. Example:
                          "--enable-mca-no-build=btl-portals,oob-ud" will
                          disable building the "portals" btl and the "ud" oob
                          components.
```

There are many frameworks and many components -- op and avx are two of many.  We can't list them all in the help message.  The error message cites 2 examples already (btl-portals and oob-ud).

What is the exact problem that you are trying to solve?  I assumed something failed to compile, but I went back and re-read your initial message and it doesn't say that.  The `#error ...` message should show up if that particular case is the cause of the failure that you're trying to solve.  But apparently you're trying to solve something else...?

**Comment by cponder** [comment]
Here's the message
```
gcc-Info-Switch -Mvect -Mvect forces -O3
/usr/bin/ld: ./.libs/liblocal_ops_avx512.a(liblocal_ops_avx512_la-op_avx_functions.o):(.data+0x0): multiple definition of `ompi_op_avx_functions_avx2'; ./.libs/liblocal_ops_avx2.a(liblocal_ops_avx2_la-op_avx_functions.o):(.data+0x0): first defined here
/usr/bin/ld: ./.libs/liblocal_ops_avx512.a(liblocal_ops_avx512_la-op_avx_functions.o):(.data+0x1250): multiple definition of `ompi_op_avx_3buff_functions_avx2'; ./.libs/liblocal_ops_avx2.a(liblocal_ops_avx2_la-op_avx_functions.o):(.data+0x1250): first defined here
make[2]: Leaving directory '/usr/local/src/openmpi-4.1.1/ompi/mca/op/avx'
make[2]: *** [Makefile:1939: mca_op_avx.la] Error 2
make[1]: *** [Makefile:3555: install-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/openmpi-4.1.1/ompi'
make: *** [Makefile:1901: install-recursive] Error 1
```
It happens with the PGI 21.9 compiler but not the 21.7 compiler.
We're still trying to figure out why, but in the meantime I can make the problem go away by using the ```--enable-mca-no-build=op-avx``` option.

**Comment by cponder** [comment]
Is there another way to get a list of the ```no-build`` options?

**Comment by jsquyres** [comment]
Ah, so this is not the same situation that Open MPI's use of the `#error ...` directive was implemented for.

When you use `--enable-mca-no-build=LIST`, you're telling Open MPI not build each of the components in that LIST.  Hence, if there's a compiler / linker issue with one of those components, then yes, it "works", but it "works" because you have skipped building the problematic component.

As the help message says, the values in the LIST are `<type>-<component>` pairs.  The `<type>` is the framework type (e.g., `op` in this case), and the `<component>` is the name of the component (`avx`) in this case.  The names of frameworks are in the Open MPI source tree: `ls -d */mca/*`, and the names the components are one directory below that.  For example, `/usr/local/src/openmpi-4.1.1/ompi/mca/op/avx` is the directory of the `avx` component in the `op` framework.

**Comment by cponder** [comment]
Yeah, turning it off is the only option I have until we work this out  8-(
Looking at the directory-tree, I see
```
./opal/mca/btl/portals4
./orte/mca/oob
./orte/mca/rml/oob
```
but I don't see any of these
```
./opal/mca/btl/portals
./orte/mca/oob/ud
./orte/mca/rml/oob/ud
```
Is it because they weren't built, or do ```btl-portals``` & ```oob-ud``` refer to components that aren't there any more?

**Comment by jsquyres** [comment]
Yeah, it looks like the 2 examples in that help message got stale.  We can update those.
