### ISSUE TITLE
ORTE_ERROR_LOG and munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by YannChemin** [open-mpi/ompi#9433]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
Front end: 4.1.0-10ubuntu1
Nodes: 4.1.0-7ubuntu2

### Describe how Open MPI was installed 
Front end: Ubuntu Impish: 21.10
sudo apt install openmpi-bin
Nodes: Ubuntu Hirsute: 21.04
sudo apt install openmpi-bin

### Please describe the system on which you are running
* Operating system/version:  Front end Ubuntu Impish 21.10, Nodes Ubuntu Hirsute 21.04
* Computer hardware:  Front End Mac Book Pro 2014, Nodes: Celeron N3060,  Celeron J1900
* Network type: Switch 100mbit

-----------------------------

## Details of the problem
After upgrading my nodes from Ubuntu Groovy (20.10) to Ubuntu Hirsute (21.04), `ORTE_ERROR_LOG` appears along with a `munmap_chunk(): invalid pointer` (Discard the `No protocol specified` as I have submitted it to another thread). As a result, now `hello_world` fails.

```shell
shell$ mpirun --use-hwthread-cpus --hostfile /home/mpiuser/cloud/hostfile /home/mpiuser/cloud/hello
```
```shell
No protocol specified
No protocol specified
failed to open /dev/dri/renderD128: Permission denied
failed to open /dev/dri/renderD128: Permission denied
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[yann-MBP:37442] [[55582,0],0] ORTE_ERROR_LOG: Not found in file ../../../../../orte/mca/odls/base/odls_base_default_fns.c at line 292
munmap_chunk(): invalid pointer
run_hello.sh: line 11: 37442 Aborted                 (core dumped) mpirun --use-hwthread-cpus --hostfile /home/mpiuser/cloud/hostfile /home/mpiuser/cloud/hello
```

**Comment by jsquyres** [comment]
Hmm.  That's... odd.

Can you run non-MPI programs?  E.g., `hostname`?

**Comment by YannChemin** [comment]
yes all working properly

**Comment by jsquyres** [comment]
Sidenote: the `No protocol specified` message has been identified as coming from hwloc, which, in turn, is likely coming from OpenGL.  See https://github.com/open-mpi/hwloc/issues/483.

I notice in your original description that you are using two different versions of Open MPI.  Can you update the version of Open MPI to match across all your nodes?

**Comment by YannChemin** [comment]
i installed the nodes with Lubuntu 21.10 this morning, the front node is
Ubuntu 21.10. this bug is gone. on the aside, "No protocol" is still there.

**Comment by jsquyres** [comment]
@YannChemin Ok, good.  Let's chalk this up to version/package mismatch between the nodes, then.

The `No protocol...` message is being followed up in open-mpi/hwloc#483 and #7701.
