### ISSUE TITLE
ERROR: UNPACK-PAST-END

### ISSUE THREAD

**Issue by asesidaa** [open-mpi/ompi#9440]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
v4.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Using [spack](https://github.com/spack/spack)
Spec: openmpi@4.1.1%aocc@3.1.0  fabrics=ucx 

### Please describe the system on which you are running

* Operating system/version: 
```shell
$ uname -a
Linux epyc.node1 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
```
* Computer hardware: AMD EPYC 7742 64-Core Processor
* Network type: Infiniband

-----------------------------

## Details of the problem

When testing with a simple test prgram
```c++
include <mpi.h>
#include <stdio.h>

int main(int argc, char** argv) {
    // Initialize the MPI environment
    MPI_Init(NULL, NULL);

    // Get the number of processes
    int world_size;
    MPI_Comm_size(MPI_COMM_WORLD, &world_size);

    // Get the rank of the process
    int world_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

    // Get the name of the processor
    char processor_name[MPI_MAX_PROCESSOR_NAME];
    int name_len;
    MPI_Get_processor_name(processor_name, &name_len);

    // Print off a hello world message
    printf("Hello world from processor %s, rank %d out of %d processors\n",
           processor_name, world_rank, world_size);

    // Finalize the MPI environment.
    MPI_Finalize();
}
```
If I run on a single node, everything works fine. However, if I pass a hostfile and run on multiple nodes, in my case it's two nodes, I will encounter error
```
[epyc.node1:50515] PMIX ERROR: ERROR in file dstore_base.c at line 934
[epyc.node1:50515] PMIX ERROR: ERROR in file dstore_base.c at line 934
[epyc.node1:50515] PMIX ERROR: ERROR in file dstore_base.c at line 934
[epyc.node1:50515] PMIX ERROR: ERROR in file dstore_base.c at line 934
```
for the host node and error
```
[epyc.node2:248473] PMIX ERROR: UNPACK-PAST-END in file ../../../../../../../../../opal/mca/pmix/pmix3x/pmix/src/mca/bfrops/base/bfrop_base_unpack.c at line 1087
[epyc.node2:248473] PMIX ERROR: ERROR in file ../../../../../../../../../../opal/mca/pmix/pmix3x/pmix/src/mca/common/dstore/dstore_base.c at line 2691
[epyc.node2:248473] PMIX ERROR: ERROR in file ../../../../../../../../../opal/mca/pmix/pmix3x/pmix/src/mca/gds/base/gds_base_fns.c at line 181
[epyc.node2:248473] PMIX ERROR: ERROR in file ../../../../../../../../../../opal/mca/pmix/pmix3x/pmix/src/mca/common/dstore/dstore_base.c at line 2571
[epyc.node2:248473] PMIX ERROR: ERROR in file ../../../../../../../opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c at line 2462
```
for the remote node.

The test program can then run and output, but this error seems to prevent arm forge from profiling the program.
How can I resolve this error?
Thanks.

**Comment by jsquyres** [comment]
This type of error _usually_ occurs when Open MPI and/or PMIx are mis-matched between different peers.

Can you double check that your LD_LIBRARY_PATH for Open MPI and PMIx are set consistently for non-interactive logins across all nodes in your job?

**Comment by asesidaa** [comment]
Thank you for reply. It seems that somehow the environment variables are messed up, and I solved the issue by using the —prefix option to set the environment variables.
