### ISSUE TITLE
Can we pass custom HWLOC configuration flags if building --with-hwloc=internal?

### ISSUE THREAD

**Issue by mkre** [open-mpi/ompi#9453]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

5.0.0rc1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

compiled from source tarball

### Please describe the system on which you are running

* Operating system/version: Linux
* Computer hardware: N/A
* Network type: N/A

-----------------------------

## Details of the problem

Hi,

we want to minimize our external dependencies, so ideally, we would like to build Open MPI with internal HWLOC, and HWLOC configured with `--disable-libudev --disable-libxml2` to avoid a transitive dependency of `libmpi.so` on `libxml2.so` and `libudev.so` (which itself has some dependencies). Is there a way to specify these HWLOC configuration flags in the Open MPI configuration process? I only found `--disable-hwloc-pci` but that doesn't help in our case.

Thanks,
Moritz

**Comment by bwbarrett** [comment]
Yes; just specify them on the top-level configure and they will be passed to all sub-configures.

**Comment by mkre** [comment]
Yep, that works. Thanks! Looking back, it's pretty obvious, but I think I was a bit blind because it was not in the top-level configure's help message.
