### ISSUE TITLE
Is there a reason pcollreq is still an mpiext on v5.0.x?

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#9455]
While trying to cherry pick the recent Fortran mpi module fixes to v5.0.x (2798fd82e5 and 9865f3aec7), I ran into conflicts.

I discovered that `ompi/mpiext/pcollreq` still exists on the v5.0.x branch (it is gone from master, because it got turned into real MPI APIs -- not extensions).

I don't have time to chase down what commits are necessary to cherry pick to v5.0.x to convert the pcollreq extension to real MPI APIs.  But someone should probably identify them and bring them over.

After those are brought over, the following commits also need to be brought over to v5.0.x:

* 18bff7000ee6511b76d7bdd26b7911f4162b0dee.  This commit fixes a conflict for 2798fd82e5, but it runs into some conflicts of its own (due to the fact that pcollreq is different).  As such, this commit may actually be brought over to v5.0.x as part of converting pcollreq from an extension to a real MPI API.
* 2798fd82e5
* 9865f3aec7

**Comment by awlauria** [comment]
I think I got it all in the attached PR. Lmk if I missed anything.

**Comment by jsquyres** [comment]
Done!
