### ISSUE TITLE
Mac build help, permission denied

### ISSUE THREAD

**Issue by bensworth** [open-mpi/ompi#9468]
I am trying to install OpenMPI 4.1.1 on a MacBook Pro (16-inch, 2019) wit Big Sur (11.6). Open MPI 4.0.5 worked fine before I upgraded to Big Sur, then something with my compiler was broken after updating. I removed and reinstalled command line tools, upgraded all my homebrew recipes, and tried to reinstall. I downloaded the stable 4.1.1 tar.gz and called `./configure --prefix=/Users/<my_path>/install`, then called `make -j install`. It makes it part way through the installation, then fails:
```
Making install in hwloc
/Library/Developer/CommandLineTools/usr/bin/make  install-exec-hook
make[5]: /Library/Developer/CommandLineTools/usr/bin/make: Permission denied
make[5]: *** [install-exec-am] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [install-am] Error 2
make[3]: *** [install-recursive] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```
I am not installing this from an admin account, but my install prefix is in my User directory, so I do not know why there would be a permissions issue. The problem is likely a permissions issue on my side, but I don't really know where to look or what could be going wrong; something in `hwloc` seems to be the culprit. Any pointers are much appreciated.

**Comment by jsquyres** [comment]
Check out the `/Library/Developer/CommandLineTools/usr/bin/make` file -- it should be executable.  The error message implies that it is not.  E.g., look at `ls -l /Library/Developer/CommandLineTools/usr/bin/make`.

**Comment by bensworth** [comment]
Oops, I forgot to include that in my report. I tested this and think the permissions all seem fine:
`-rwxr-xr-x  1 root  wheel  436464 Jun  8 18:46 /Library/Developer/CommandLineTools/usr/bin/make
`
The only caveat being that I am not running as root user, but I don't see why that would be an issue. And, if I just call `/Library/Developer/CommandLineTools/usr/bin/make` from command line right where the error occurs, make runs fine (just probably not "making" what it should be in the install sequence).

**Comment by jsquyres** [comment]
That is a strange error, then.  The output from your original post pretty much directly states that `/Library/Developer/CommandLineTools/usr/bin/make` is not executable (you don't need to build Open MPI as root).  But your `ls -l` says that it is.

Is this a repeatable error?  I.e., if you do a top-level `make` in the Open MPI source tree, it fails in the same location with the same error?

If so, please post all the files here on the github issue described in https://www.open-mpi.org/community/help/.

**Comment by ggouaillardet** [comment]
Is there a white space in your prefix?

**Comment by bensworth** [comment]
So when running `make install` without the `-j` flag, I got more detailed info, the problem was not in `make`, but because some files in `hwloc201` were root permissions. 
```
openmpi-4.1.1$ ls -l ./opal/mca/hwloc/hwloc201/.libs/
total 648
-rw-r--r--  1 root  staff    1016 Oct  4 12:17 hwloc201_component.o
-rw-r--r--  1 root  staff  325528 Oct  4 12:17 libmca_hwloc_hwloc201.a
lrwxr-xr-x  1 root  staff      27 Oct  4 12:17 libmca_hwloc_hwloc201.la -> ../libmca_hwloc_hwloc201.la
```
I re-downloaded and configured OpenMPI and then ran just `make install` and everything worked. But, I learned this was unique to not using the `-j` flag. If I use `-j` I get permissions errors. I will close this issue now because I got OpenMPI installed, but if anyone has any thoughts on why `-j` is causing permission errors please let me know.
