### ISSUE TITLE
orte_rdma_dist_device: what kind of device?

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#953]
@miked-mellanox Can the help message for `orte_rdma_dist_device` be updated? https://github.com/open-mpi/ompi/blob/master/orte/mca/rmaps/base/rmaps_base_frame.c#L160-L166

It's not clear what kind of devices can be listed there.  E.g., can I list "eth0" there?  Or only verbs-based devices?  Or ...?

(I'm pinging @miked-mellanox because @elenash added this MCA param in 1e913c76c)

**Comment by miked-mellanox** [comment]
it can be any hwloc visible device.( @rhc54 - is that right?) 
@jsquyres - Could you please suggest a better wording?
@igor-ivanov - could you please apply it?

**Comment by jsquyres** [comment]
Perhaps:

> If specified, map processes near to this device.  Any device name that is identified by the "lstopo" hwloc utility can be used.  Typical examples include (but are not limited to): eth0, mlx4_0, etc.

**Comment by jsquyres** [comment]
Please also PR to v1.10 and v2.x.  Thanks!

**Comment by igor-ivanov** [comment]
I think that current logic is following:
user can set 'auto' value that allows to select openfabric devices but setting specific device a user can select ethernet or openfabrics.
See code:
1. 'auto' condition - https://github.com/open-mpi/ompi/blob/master/opal/mca/hwloc/base/hwloc_base_util.c#L2065-L2090
1.1. find_devices(HWLOC_OBJ_OSDEV_OPENFABRICS) - https://github.com/open-mpi/ompi/blob/master/opal/mca/hwloc/base/hwloc_base_util.c#L2023-L2035
1.2. sort_by_dist(HWLOC_OBJ_OSDEV_OPENFABRICS | HWLOC_OBJ_OSDEV_NETWORK) - https://github.com/open-mpi/ompi/blob/master/opal/mca/hwloc/base/hwloc_base_util.c#L1948-L1964
