### ISSUE TITLE
Remove stale/unused OPAL hwloc APIs

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#9537]
In master/v5.0.x, we should audit all the use of OPAL hwloc base APIs: delete the ones that are not being used.

We should search out those APIs and delete this now-unused code.

That being said, this needs to be done carefully such that we still have enough hwloc services available in a non-PRTE-launch scenario (e.g., direct launch).  E.g., ORTE used to mine some data from hwloc automatically (e.g., get the cache line size, etc.) and make that information available to the MPI layer.  This may not be happening in master/v5.0.x in a direct launch scenario (where PMIx is not involved -- e.g., old versions of SLURM).

Specifically: we have not been testing direct launch in a non-PMIx environment.

**Comment by bwbarrett** [comment]
@rhc54 and @jsquyres we don't support direct launch in a non-PMIx environment in v5.0, right?

Agree with the being careful and I'm not sure that we'll get some of the HWLOC data from PMIx today (I remember having trouble with that during the HWLOC repackage), but just want to make sure we've clearly defined the problem space.

**Comment by awlauria** [comment]
https://github.com/open-mpi/ompi/pull/9686 removes most, if not all of them.

**Comment by awlauria** [comment]
v5.0.x pr merged here: https://github.com/open-mpi/ompi/pull/9702

closing.
