### ISSUE TITLE
RMA - standard compliance and empty groups

### ISSUE THREAD

**Issue by thomasgillis** [open-mpi/ompi#9540]
- version: 4.1.0 and 4.5.0
- installation: easybuild
- OS: ubuntu and docker on macOS
- bug reproducers: https://github.com/thomasgillis/cori-mpi-rma

My issue (which is more a question) is twofold and originates from the small reproducer code `osc.cpp` that fails with OpenMPI.

1. I think it relates to the issue #8677 which has been solved and merge since then (cfr in the reproducers `empty.cpp`). Do you have any idea of the release timeline for 4.1.2 (which I guess will contain the merge)?

2. On some machines, the reproducer `osc.cpp` still fails with various MPI implementations while it goes through with others (like `pt2pt`). To me it raises the question of the compliance of the code with the MPI Standard. Would it be possible for a osc expert to take a look and confirm that the code complies to the standard? In particular to the type deletion right after the `MPI_Get` and a single rank that is at the same time target and origin of RMA calls.

Thank you very much for your time and your help!

**Comment by hppritcha** [comment]
I have a fix in the works.

**Comment by gpaulsen** [comment]
@devreal, Howard said he's working on a fix now

**Comment by hppritcha** [comment]
closed via #9556  and related PRs to release branches
