### ISSUE TITLE
Is partitioned communication going to v5.0?

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#9554]
Is the MPI-4.0 partitioned communication work heading to the v5.0 branch?

As @EmmanuelBRELLE pointed out in https://github.com/open-mpi/ompi/pull/9543#issuecomment-946606968, it looks like at least the following would need to be brought over to the v5.0.x branch:

* https://github.com/open-mpi/ompi/pull/8641
* At least part of https://github.com/open-mpi/ompi/pull/8882
* https://github.com/open-mpi/ompi/pull/9543
* The resolution to https://github.com/open-mpi/ompi/issues/9544

FYI @open-mpi/ompi-gatekeeper-5-0-x

**Comment by tkordenbrock** [comment]
@jsquyres #9593 has been merged so I think this can be closed.

**Comment by jsquyres** [comment]
See https://github.com/open-mpi/ompi/pull/9593#issuecomment-958113526.

**Comment by awlauria** [comment]
With the merging of #10077 I think v5.0.x has pulled in all of the partitioned communication pr's.
