### ISSUE TITLE
Configure breaks when using combinations of "--with-foo=external"

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#9576]
This applies to both OMPI master and v5.0. The problem is that the configure breaks when different combinations of `--with-foo=external` are used, and/or when the external package is not in a standard place such as `/usr` but _is_ pointed to by the usual flags (`CPPFLAGS`, `LDFLAGS`, etc) or is in the current `LD_LIBRARY_PATH`. I have fixed the problem for when PRRTE is the "external" package, so the following configure now works:
```text
--with-libevent=<path> --with-hwloc=<path> --with-pmix=<path> --with-prrte=external
```
where `PATH` includes the path to `prterun` and `CPPFLAGS` includes the path to the `prte_version.h` header.

However, I have not been able to get the `--with-pmix=external` case to work - i.e., the following will fail:
```text
--with-libevent=<path> --with-hwloc=<path> --with-pmix=external --with-prrte=<path>
```
This fails when OMPI tries to configure the _internal_ PRRTE code - unfortunately, the `--with-pmix=external` gets stripped but does not get replaced with the actual path to the PMIx installation. In addition, the `--with-prrte` option is retained, leaving us with the following output:
```text
*** Configuring PRRTE
with_prrte: /Users/rhc/pmix/build/prrte
opal_prrte_mode: external
checking if PMIx version is 4.0.0 or greater... yes
configure: ===== configuring 3rd-party/prrte =====
configure: running /bin/sh ./configure --disable-option-checking
'--prefix=/Users/rhc/openmpi/build/foobar' --enable-prte-ft
--with-proxy-version-string=5.1.0a1 --with-proxy-package-name="Open MPI"
--with-proxy-bugreport="https://www.open-mpi.org/community/help/"
--enable-prte-prefix-by-default --with-prte-extra-lib="" --with-prte-extra-ltlib=""
'--with-hwloc=/Users/rhc/hwloc/build/v2.2.0' '--with-libevent=/Users/rhc/libevent/build'
'--with-prrte=/Users/rhc/pmix/build/prrte'
'CFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
'LDFLAGS=-L/Users/rhc/pmix/build/clean/lib'
'CPPFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/Users/rhc/pmix/build/clean/include'
'CXXFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
--cache-file=/dev/null --srcdir=.
```
In this case, note that the external PMIx is pointed to by providing `LDFLAGS` and `CPPFLAGS` - it is _not_ in a standard location, nor is it even included on the PRRTE configure line. The `--with-prrte` option is of course not recognized, but that's a warning that gets ignored.

The internal PRRTE config subsequently fails when it cannot find PMIx:
```text
============================================================================
== Configure PMIx
============================================================================
checking --with-pmix value... not found
configure: WARNING: Directory /usr/include not found
configure: error: Cannot continue
configure: ===== done with 3rd-party/prrte configure =====
configure: error: PRRTE configuration failed.  Cannot continue.
```
I've spent some time trying to figure out a solution without any success. Somehow, we would need to point the internal PRRTE to where PMIx was actually found, but that is only a partial solution - the same problem exists for the `libevent=external` and `hwloc=external` cases as well, so we'd have to find a way to point the internal PRRTE (and the internal PMIx as well since it has the same problem) towards those too.

Or we could try to simplify things, perhaps not allowing the "external" keyword, or not supporting some of these combinations. I'm not sure of the right answer here - this has become a tangled web of inter-dependencies. Afraid I have to leave it to someone else to resolve.

Meantime, I can/will fix PRRTE's internal config so it can find PMIx when it is in the flags instead of only looking in `/usr`. That may help this situation, but likely isn't a solution for it. I'll at least give it a try once I get PRRTE updated.

**Comment by gpaulsen** [comment]
@awlauria can you please retest?

**Comment by awlauria** [comment]
I retested this on v5.0.x, and it got past configure, however I did run into some pkg-config errors and other things. That said I think the reported issue here is fixed.

My configure line:

```
./configure --prefix=`pwd`/exports --with-hwloc=/path/to/hwloc/exports --with-pmix=external --with-prrte=/path/to/prte/exports --disable-man-pages
```

PR to fix these issues: #9943

**Comment by awlauria** [comment]
Should be fixed on master with: https://github.com/open-mpi/ompi/pull/9955

**Comment by awlauria** [comment]
One potential bug with the above pr, when testing `--with-pmix=external`, where pmix is built into something like `/usr/local/lib`, I get a runtime error where it will fail to fine libpmix.so unless I set LD_LIBRARY_PATH to point to it. I don't think this is a problem with it installed in the general lib/lib64 dirs.

This could be fixed in OPAL_CHECK_PACKAGE to add the rpath to the LD_FLAGS. However, I don't know if that is something we want to do in this case or not.

**Comment by awlauria** [comment]
Closing this, as master and v5.0.x has been merged. I may open a new issue on the runtime error.
