### ISSUE TITLE
mpirun using srun is giving pmix_psec_base_open failed

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#9582]
Reported on PRRTE, which isn't in OMPI v4.1.2:

Thank you for taking the time to submit an issue!
Background information

This is with OMPI v4.1.2a1

When using slurm-20.11.7 compiled with pmix-3.2.3, and job is submitted like below :

srun -N 1 -c 2 --pty /bin/bash

on the allocated compute node, when I execute the below command, I get
the PMIX error with return value -46

mpirun -c 2 /bin/hostname

```
A requested component was not found, or was unable to be opened. This

means that this component is either not installed or is unable to be

used on your system (e.g., sometimes this means that shared libraries

that the component requires are unable to be found/loaded). Note that

PMIX stopped checking at the first component that it did not find.

Host: cnode9

Framework: psec

Component: munge

It looks like pmix_init failed for some reason; your parallel process is

likely to abort. There are many reasons that a parallel process can

fail during pmix_init; some of which are due to configuration or

environment problems. This failure appears to be an internal failure;

here's some additional information (which may only be relevant to an

PMIX developer):

pmix_psec_base_open failed

--> Returned value -46 instead of PMIX_SUCCESS

[cnode9:2708617] PMIX ERROR: NOT-FOUND in file server/pmix_server.c at
line 237
```

**Comment by rhc54** [comment]
@pankajd-57 reported this - referencing them here.

**Comment by ggouaillardet** [comment]
@rhc54 which PMIx is supposed to be used by `mpirun` here?
is this the (external) PMIx server spawned by SLURM?
or is this the (internal) PMIx server spawned by `mpirun` (or `orted` if there were multiple nodes).

@pankajd-57 is `munge` running on your compute nodes? you can
`echo | munge` to double check that
if success, the output should be something like that
`MUNGE:AwQDAAA1VImtMVNLu5wZC9gyGq9idQ48Qfx+CrJ9VC5y2Tb04f8V/O...`

**Comment by ggouaillardet** [comment]
OK, did you build Open MPI with the built-in PMIx or can you post your Open MPI `configure` command line?

If you do not know, can you check the existence of a `mca_psec_munge.so` file in both Open MPI and SLURM PMIx directories?
I am thinking the issue could be Open MPI was built with the internal PMIx but is using the external one at runtime (or the other way around)

can you also run
`env | grep ^MCA`
in your `srun` allocation?
