### ISSUE TITLE
osc-portals4: undefined variable error in minimum alignment info key lookup

### ISSUE THREAD

**Issue by tkordenbrock** [open-mpi/ompi#9586]

**Comment by gpaulsen** [comment]
@tkordenbrock, please add some more details?  What is this?  Where is the error?  how can we reproduce?  Is this really a blocker?  Can you just define the variable?

**Comment by tkordenbrock** [comment]
This is the issue for pull requests https://github.com/open-mpi/ompi/pull/9587 and https://github.com/open-mpi/ompi/pull/9597.  They are both merged so this can be closed.
