### ISSUE TITLE
Update man pages with f08

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/ompi#959]
The man pages in Open MPI currently show the mpif.h syntax. It should be great if someone would update them to include (probably replacing the mpif.h syntax) the new bindings.

This might be scriptable and could be part of the fortran scripting work.

**Comment by hjelmn** [comment]
Adding interested parties. @jsquyres @ggouaillardet

**Comment by hjelmn** [comment]
If anyone wants to do the work please self-assign. If I find someone I will assign them.

**Comment by ggouaillardet** [comment]
i did this some time ago but did not get any chance to commit it
will review and pr tomorrow

**Comment by jsquyres** [comment]
We probably don't want to get rid of the mpif.h syntax, because it's the same as the "use mpi" syntax. It would be great to add the mpi_f08 bindings, though.

@ggouaillardet Sweet!

**Comment by ggouaillardet** [comment]
this is what I did
as an option, I can sed the man pages to remove stuff that is not built
(such as c++ if bindings are not built, or f08 if the compiler does not support it)

**Comment by jsquyres** [comment]
Mmmm.  Interesting (i.e., snipping out parts of man pages for bindings that weren't built).

Do we really want that?

My $0.02: I think it might be ok to include the bindings for all interfaces.

I see other tokens like "F77 Notes" -- did you change that to "Fortran Notes"?

Also, `include 'mpif.h'` -- should we somehow indicate that `use mpi` is "preferred" these days, and `include 'mpif.h'` should only be used when absolutely necessary (E.g., when using an old gfortran that doesn't support ignore TKR)?

**Comment by jsquyres** [comment]
This was done long ago.  Huzzah!
