### ISSUE TITLE
MPI_Wait hangs after MPI_Cancel on a request from an MPI_Issend.

### ISSUE THREAD

**Issue by geligeli** [open-mpi/ompi#9626]
Thank you for taking the time to submit an issue!

## Background information

The following code hangs for me in MPI_Wait:

```
#include <mpi.h>

int main(int argc, char **argv) {
  MPI_Init(&argc, &argv);
  int rank;
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  if (rank == 0) {
    MPI_Request request;
    int val;
    MPI_Issend(&val, 1, MPI_INT, 0, 0, MPI_COMM_WORLD, &request);
    MPI_Cancel(&request);
    MPI_Status status;
    MPI_Wait(&request, &status); // <-- this hangs ??
  }
  MPI_Finalize();
  return 0;
}
```

From what I understand after MPI_Cancel and subsequent MPI_Wait should always return ( cf https://www.open-mpi.org/doc/v4.1/man3/MPI_Cancel.3.php )
Is this a bug or error on my  behalf?

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
v4.0.2

### Please describe the system on which you are running

* Operating system/version: Ubuntu 20.04
* Computer hardware: i9 9900k
* Network type: None

[edit: simplify example]

**Comment by bosilca** [comment]
You cannot cancel send requests, only receive requests.

**Comment by geligeli** [comment]
Actually the standard says that exactly this example should be correct: (cf https://www.mpi-forum.org/docs/mpi-4.0/mpi40-report.pdf pdf-page 536):

(Example 11.6 This program is correct. The cancel operation must succeed, since the send
cannot complete normally. The wait operation, after the call to MPI_Cancel, is local—no
matching MPI call is required on process 1. Cancelling a send request by calling
MPI_CANCEL is deprecated.
Process 0 
--------- 
MPI_Issend(dest=1); 
MPI_Cancel();
MPI_Wait();
MPI_Finalize();

Process 1
---------
MPI_Finalize();

**Comment by bosilca** [comment]
Not according to Section 3.8 page 84. 

> Cancelling a send request by calling MPI_CANCEL is deprecated. Cancelling a sendrecv request by calling MPI_CANCEL is not allowed.

**Comment by bosilca** [comment]
We missed this example in the MPI standard when we deprecated the send. I will provide a fix there, thanks for the report.

**Comment by geligeli** [comment]
Thanks so much!

**Comment by bosilca** [comment]
Here is the PR removing this inconsistency from the MPI standard (https://github.com/mpi-forum/mpi-standard/pull/635)

**Comment by geligeli** [comment]
Wait I don't understand: MPI_CANCEL on send is only deprecated not removed yet, no? So the example should still be correct according to the MPI 4.0 standard. Or does deprecated mean it's actually not part of the standard anymore?

**Comment by bwbarrett** [comment]
Deprecated means that you shouldn't use that feature.  Regardless of timing, very few MPI implementations have ever implemented MPI_CANCEL on sends in a way that works with the example.  Some have, with some transports.  Open MPI has never supported MPI_CANCEL of sends.  For most applications, the performance tradeoffs are the wrong call.

**Comment by hjelmn** [comment]
Also to note since this just got asked internally. That example also fails with Intel MPI. When multiple implementations don't work with something just don't do it!

**Comment by bosilca** [comment]
In addition to all these answers, I'm not really convinced the example is correct because MPI_Cancel being defined as a local operation it might not always succeed, so the status of the resulting MPI object is not binary, aka. the operation is either cancelled or will eventually complete. I would use MPI_Test_cancelled before the blocking wait to check if the operation was cancelled, and would skip the wait if the cancel failed.
