### ISSUE TITLE
Intermittent segfaults in btl smcuda in absence of GPUs

### ISSUE THREAD

**Issue by mkre** [open-mpi/ompi#9638]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.0.6

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Compiled from a source tarball

### Please describe the system on which you are running

* Operating system/version: CentOS 7.7/7.9
* Computer hardware: 2 nodes, each with Intel Xeon E5-4669 v4, **no GPUs**
* Network type: TCP

-----------------------------

## Details of the problem

We are seeing **intermittent** segfaults in the btl smcuda at [this location](https://github.com/open-mpi/ompi/blob/v4.0.6/opal/mca/btl/smcuda/btl_smcuda.c#L942). Here is some gdb output:
```c++
(gdb) c
Continuing.
[New Thread 0x7f60bfd89700 (LWP 10070)]

Thread 1 "star-ccm+" received signal SIGSEGV, Segmentation fault.
0x00007f60e5db5c42 in mca_btl_smcuda_sendi (btl=0x7f60e5fbd220 <mca_btl_smcuda>, endpoint=0xbb18c0, convertor=0x7ffe4f3627d0, header=0x7ffe4f362900, header_size=14, payload_size=4, order=255 '\377', flags=3, tag=65 'A', descriptor=0x0) at btl_smcuda.c:942
942     btl_smcuda.c: No such file or directory.
(gdb) dir ompi-4.0.6-src/opal/mca/btl/smcuda/
Source directories searched: /home/test/ompi-4.0.6-src/opal/mca/btl/smcuda:$cdir:$cwd
(gdb) list
937
938             /* allocate a fragment, giving up if we can't get one */
939             /* note that frag==NULL is equivalent to rc returning an error code */
940             MCA_BTL_SMCUDA_FRAG_ALLOC_EAGER(frag);
941             if( OPAL_UNLIKELY(NULL == frag) ) {
942                 *descriptor = NULL;
943                 return OPAL_ERR_OUT_OF_RESOURCE;
944             }
945
946             /* fill in fragment fields */
(gdb) info locals
length = 18
frag = 0x0
rc = 0
__PRETTY_FUNCTION__ = "mca_btl_smcuda_sendi"
(gdb) info args
btl = 0x7f60e5fbd220 <mca_btl_smcuda>
endpoint = 0xbb18c0
convertor = 0x7ffe4f3627d0
header = 0x7ffe4f362900
header_size = 14
payload_size = 4
order = 255 '\377'
flags = 3
tag = 65 'A'
descriptor = 0x0
```

We have configured Open MPI with CUDA support, but in this run we are not actually using it (we don't even have GPUs installed in the nodes). A couple of related questions:
1. Is it expected that the btl smcuda is still being used, even if there are no GPUs installed?
2. In general, do you have a recommendation about which components should be used for CUDA-aware MPI? Is the btl smcuda recommended, or should we restrict ourselves to using UCX if we want to have CUDA-aware MPI?

Thanks,
Moritz

**Comment by mkre** [comment]
Does anyone have an idea about this? Pinging @bosilca as you did the most recent work on smcuda.

**Comment by bosilca** [comment]
The smcuda should be there, but it should not be used if there are no GPU on the machine. But that is only part of the issue here. Can you please try the following patch
```diff
diff --git a/opal/mca/btl/smcuda/btl_smcuda.c b/opal/mca/btl/smcuda/btl_smcuda.c
index 5784e79bdd..22fc3b33dd 100644
--- a/opal/mca/btl/smcuda/btl_smcuda.c
+++ b/opal/mca/btl/smcuda/btl_smcuda.c
@@ -891,7 +891,6 @@ int mca_btl_smcuda_sendi(struct mca_btl_base_module_t *btl,
         /* note that frag==NULL is equivalent to rc returning an error code */
         MCA_BTL_SMCUDA_FRAG_ALLOC_EAGER(frag);
         if (OPAL_UNLIKELY(NULL == frag)) {
-            *descriptor = NULL;
             return OPAL_ERR_OUT_OF_RESOURCE;
         }
```
The rationale is that we don't need to set the returned descriptor to NULL, we already return an error code.

**Comment by mkre** [comment]
@bosilca, your suggested patch works to avoid the segfault.

> The smcuda should be there, but it should not be used if there are no GPU on the machine

Do you want me to run any follow-up tests regarding this one?

**Comment by bosilca** [comment]
Thanks for confirming this. Give me a day or two to look more in details on this and I'll get back to you. I will create a PR with the patch above and anything else I can find, and a second opinion/tester of that code would be great.

**Comment by mkre** [comment]
Ping @bosilca...

This is issue is not a blocker for us, since we have currently just disabled smcuda in favor of ucx. But I'm not sure if this is a good idea and it brings me back to my second question above:

> In general, do you have a recommendation about which components should be used for CUDA-aware MPI? Is the btl smcuda recommended, or should we restrict ourselves to using UCX if we want to have CUDA-aware MPI?

**Comment by mkre** [comment]
Just want to post a friendly reminder @bosilca...

**Comment by jsquyres** [comment]
Yo @bosilca -- we're looking to make a 4.1.x RC in a week or so.  Do you think you could look at the solution proposed on this issue before then?  #10031 also proposes a slightly different solution.
