### ISSUE TITLE
MPI_Bcast not receiving broadcast data

### ISSUE THREAD

**Issue by kmccall882** [open-mpi/ompi#9659]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

It was installed from a source/distribution tarball, using the configure command.   It was compiled with Nvidia's nvc++ 20.9-0 (LLVM 64-bit target on x86-64 Linux -tp haswell)

### Please describe the system on which you are running

* Operating system/version:  CentOS 7
* Computer hardware: Intel Xeon E5-2640
* Network type: Not sure, but it is nothing exotic.  Our filesystem is NFS.

-----------------------------

## Details of the problem

My MPI job consists of a single master process and a number manager processes, each connected individually with the master by 
inter-communicators.   The each manager is on its own node.

The master and managers call MPI_Bcast (on MPI_COMM_WORLD) to send a small amount of data from the master to all of the managers, but the managers are all receiving zeros, no data.   It is odd, because this code worked correctly under MPICH.  

(The only difference between the MPICH and the OpenMPI versions of my code is that the former uses host names
like "n001" in the "info" argument to MPI_Comm_spawn, while the latter uses "n001:20".   This should be irrelevant because the 
MPI_Bcast call doesn't use the inter-communicators created by MPI_Comm_spawn).

I don't have a small example that would duplicate the issue for you, but I can build one if necessary.  I'm hoping that this is a 
known issue...

**Comment by bosilca** [comment]
I understand you spawn your managers. Are they using a inter or intra communicator for the bcast ?

**Comment by ggouaillardet** [comment]
@kmccall882 if you start the single master process with `mpirun` and then spawn the managers with `MPI_Comm_spawn()`, then the master is alone in his own `MPI_COMM_WORLD`, and the managers are together (without the master) in their `MPI_COMM_WORLD`. So your description of the issue is a bit confusing.

There is a known issue with the `coll/tuned` component when matching but non identical signatures are used
(for example, you `MPI_Bcast()` many elements on the root rant, and a single derived datatype (made of many elements) on the other ranks.
There is also a known compiler bug with nvidia hpc compilers (from 20.3 iirc) but I am not sure it applies here.

You can give GNU compilers a try, and/or craft and post a simple reproducer.

**Comment by kmccall882** [comment]
Bosilca -- MPI_Bcast used the MPI_COMM_WORLD intra-communicator.

Sorry about my confusing description.   I only mentioned MPI_Comm_spawn because its info argument was the only difference 
between the MPICH and the OpenMPI versions of my code.    21 processes were launched by mpiexec, one became the master
and the rest became managers.   Since one became the master, a manager would be missing on the master's node, so MPI_Comm_spawn was called by the master to create a new single manager on that node.   It occurs to me that its MPI_COMM_WORLD might be different than the MPI_COMM_WORLD of the master and the 20 normal managers.   Could this be a problem?

I will give the GNU compilers a try.

**Comment by kmccall882** [comment]
I compiled OpenMPI with g++ 4.8.5 and got the same result:   MPI_Bcast on the managers is receiving all zeros.

**Comment by rhc54** [comment]
The manager that shares the node with the master will not be in the comm_world of the other managers, so it cannot receive the communication if you are bcasting on comm_world. The other managers should be receiving it - you might ensure you are checking their value and not just the one on the master's node.

**Comment by jsquyres** [comment]
Can you post a small reproducer code that shows the problem?

**Comment by kmccall882** [comment]
>> The other managers should be receiving it - you might ensure you are checking their value and not just the one on the master's node

All managers are reporting the same thing -- MPI_Bcast is receiving all zeros.   Would the call to MPI_Bcast on the 
manager that shares the node with the master be fouling things up, since there is no corresponding call in the master
on that manager's MPI_COMM_WORLD?

I'll try to create a small reproducer.

**Comment by kmccall882** [comment]
The problem turned out to be the fault of my code.   My MPI_Bcasts calls are now receiving the correct data.  I'm sorry to 
have wasted your time, but thanks for all of your quick responses.
