### ISSUE TITLE
Intermittent hangs with calling MPI_Comm_spawn()

### ISSUE THREAD

**Issue by gpaulsen** [open-mpi/ompi#9713]
On our weekly call, Nov 16th, George said he was seeing some (and perhaps some of our MTT timeouts were related to) intermittent hangs with MPI_Comm_spawn.  I'd recorded this in the context of the v4.1.x branch.

George can you please update this issue with the details that you've seen?  I opened this issue to track and not forget about this issue.

Thanks.

**Comment by bosilca** [comment]
@hppritcha already opened a similar issue (#8958)
