### ISSUE TITLE
CI updates wanted on v5.0.x?

### ISSUE THREAD

**Issue by awlauria** [open-mpi/ompi#9726]
https://github.com/open-mpi/ompi/pull/8702
https://github.com/open-mpi/ompi/pull/8986
https://github.com/open-mpi/ompi/pull/8960
https://github.com/open-mpi/ompi/pull/9100
https://github.com/open-mpi/ompi/pull/9380
https://github.com/open-mpi/ompi/pull/9500
https://github.com/open-mpi/ompi/pull/9517

All of these CI updates are on master but not v5.0.x. Just want to make sure they aren't needed/wanted on v5.0.x.
Creating this to not lose track.

**Comment by awlauria** [comment]
I brought #8959 over here: https://github.com/open-mpi/ompi/pull/9740

**Comment by hppritcha** [comment]
they can stay on master for now.  not sure how useful this will end up being.  there are pretty severe limitations trying to use gitlab to do CI on PRs to a github repo.

**Comment by awlauria** [comment]
Thanks - closing.
