### ISSUE TITLE
mpirun exits immediately with exit code 1

### ISSUE THREAD

**Issue by PhilipDeegan** [open-mpi/ompi#9729]
## Background information

Trying to spawn some tests via python subprocess inside a docker container
mpirun from cli works inside docker, but from python subprocess (inside docker), it exits without any error with exit code 1

sample python subprocess call would be like 

    mpirun -n $N python3 $ARG0 $ARG1

removing "mpirun -n $N"  and running the rest normally from python subprocess runs fine

### What version of Open MPI are you using? 
mpirun (Open MPI) 4.1.0

### Describe how Open MPI was installed
- dnf install openmpi openmpi-devel
- docker file https://github.com/PHARCHIVE/phare-teamcity-agent/blob/master/Dockerfile

### Please describe the system on which you are running

* Operating system/version:  Fedora 34
* Computer hardware:  AMD 3900
* Network type:  LAN / NA

-----------------------------

## Details of the problem
As described above.

Our setup isn't so trivial so I'm happy to troubleshoot whatever suggestions you might have.
I should add what I'm doing works as expected outside docker.

**Comment by jsquyres** [comment]
Can you update to the latest Open MPI v4.1.2?

**Comment by PhilipDeegan** [comment]
I will, testing 4.1.1 on fedora 35 is the same insofar as it exits without any message

**Comment by rhc54** [comment]
If you configure OMPI with `--enable-debug`, you can set `OMPI_MCA_state_base_verbose=5 OMPI_MCA_mca_base_component_show_load_errors=1` to watch `mpirun` load its libraries go thru its state machine. Should provide a little info. My guess is that you lose the `LD_LIBRARY_PATH` when you execute `mpirun` as a Python subprocess.

**Comment by PhilipDeegan** [comment]
> Can you update to the latest Open MPI v4.1.2?

4.1.2 is the same
I was mistaken earlier, it actually doesn't work outside docker, but it does work with MPICH in or out of docker

**Comment by rhc54** [comment]
Looks like it launched just fine - if that was all the output, then it looks like it is running. Does it complete - i.e., is there some output showing the proc exiting later on?

**Comment by PhilipDeegan** [comment]
I believe this is the output of the outer process, the one calling python subprocess, of the subprocess, there is no output, just an exit code of 1.

**Comment by rhc54** [comment]
Errr - wait a minute. Are you saying you use `mpirun` to start a python process that then tries to execute `mpirun` as a subprocess??? That definitely will not work - `mpirun` will detect that it is being called from within an `mpirun` job and abort.

**Comment by PhilipDeegan** [comment]
The outer process is not started via mpirun, but mpi might be being initialized within the outer process, I will check if this changes things, thanks

**Comment by PhilipDeegan** [comment]
> but mpi might be being initialized within the outer process...

it was this
