### ISSUE TITLE
Please port #8790 to v5.0.x

### ISSUE THREAD

**Issue by awlauria** [open-mpi/ompi#9747]
@shintaro-iwasaki can you please port https://github.com/open-mpi/ompi/pull/8790 to v5.0.x?

**Comment by awlauria** [comment]
I was able to do it here: https://github.com/open-mpi/ompi/pull/9731

**Comment by shintaro-iwasaki** [comment]
@awlauria Sorry for the late reply, but thank you very much for creating the PR!
