### ISSUE TITLE
Hcol library init failed, with explicity disabled ucx and hcol MCA

### ISSUE THREAD

**Issue by vasslavich** [open-mpi/ompi#9763]
Hello, everyone!

I'm compiling from sources and running a third-party library who uses Open MPI and have the own configuration options in **configure**.
My problem resemble the [post](https://github.com/open-mpi/ompi/issues/7388). I'm using the options ```--without-ucx``` and ```--without-hcol``` as in the post. But, I still got errors about **fault of Hcol library init**, when the third-party library was built and runned:

```
[LOG_CAT_ML] You must specify a valid HCA device by setting:
-x HCOLL_MAIN_IB=<dev_name:port> or -x UCX_NET_DEVICES=<dev_name:port>.
If no device was specified for HCOLL (or the calling library), automatic device detection will be run.
In case of unfounded HCA device please contact your system administrator.
[node1:3230196] Error: ../../../../../ompi/mca/coll/hcoll/coll_hcoll_module.c:310 - mca_coll_hcoll_comm_query() Hcol library init failed
```

The **configure** stage includes:
```
$ ../configure --prefix=/opt/openmpi-4.1.2 CC=nvc  CXX=nvc++ FC=nvfortran  CFLAGS="-O1 -fPIC" CXXFLAGS="-O1 -fPIC" FCFLAGS="-O1 -fPIC" LD=ld --enable-shared --without-tm --without-hcoll --without-ucx --enable-mpi-cxx --disable-wrapper-runpath --enable-mpirun-prefix-by-default --with-libevent=internal --without-libnl --enable-mca-no-build=op-avx --without-verbs --with-cuda=/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/cuda/11.4 --with-cuda-libdir=/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/cuda/11.4/lib64
```
Then ```make all install```.

I'm using OpenMPI version 4.1.2 from tarball. Also, already had been installed:
- Ubuntu 20.04. 
- NVIDIA HPC SDK 21.9 with CUDA 11.4. 
- Open UCX 1.11.2 (but, I disable it in the **configure** stage).

The **ompi_info** output:
```$ /opt/openmpi-4.1.2/bin/ompi_info | grep 'hcol'
  Configure command line: '--prefix=/opt/openmpi-4.1.1' 'CC=nvc' 'CXX=nvc++' 'FC=nvfortran' 'CFLAGS=-O1 -fPIC' 'CXXFLAGS=-O1 -fPIC' 'FCFLAGS=-O1 -fPIC' 'LD=ld' '--enable-shared' '--without-tm' '--without-hcoll' '--without-ucx' '--enable-mpi-cxx' '--disable-wrapper-runpath' '--enable-mpirun-prefix-by-default' '--with-libevent=internal' '--without-libnl' '--enable-mca-no-build=op-avx' '--without-verbs' '--with-cuda=/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/cuda/11.4' '--with-cuda-libdir=/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/cuda/11.4/lib64'
                MCA coll: hcoll (MCA v2.1.0, API v2.0.0, Component v4.1.2)
```

And, modules in the **prefix** folder:
```
$ ls -R /opt/openmpi-4.1.1/ | grep '*hcol*'
$
```

Thank for any advice!)

**Comment by ggouaillardet** [comment]
there is something inconsistent here.
your description is about Open MPI 4.1.2, but `ompi_info` output mentions the `/opt/openmpi-4.1.1` prefix, which is inconsitstent with your previous `configure` command line.

**Comment by vasslavich** [comment]
> there is something inconsistent here. your description is about Open MPI 4.1.2, but `ompi_info` output mentions the `/opt/openmpi-4.1.1` prefix, which is inconsitstent with your previous `configure` command line.

Thank you @ggouaillardet !
Yes, sorry, you're right! It's the confusion from me. But, actually, I tried install version 4.1.1 also and the error is the same. Simply, I accidentally took the output for ```ompi_info``` for 4.1.1. I'll correct the initial post.

**Comment by ggouaillardet** [comment]
make sure there is no old component left over (that would be `/opt/openmpi-4.1.2/lib/openmpi/mca_coll_hcoll.so`) from a previous install. If so, you can simple remove it and try again.

**Comment by vasslavich** [comment]
I found the library ```opt/openmpi-4.1.2/lib/openmpi/mca_coll_hcoll.so``` only into the NVIDIA HPC SDK pathes. But, I tried ```hcoll_info```, and got the result:

```
# $HPCX_HCOLL_DIR/bin/hcoll_info -all
[LOG_CAT_ML] You must specify a valid HCA device by setting:
-x HCOLL_MAIN_IB=<dev_name:port> or -x UCX_NET_DEVICES=<dev_name:port>.
If no device was specified for HCOLL (or the calling library), automatic device detection will be run.
In case of unfounded HCA device please contact your system administrator.
Hcoll initialization failed.
```
Can it be the reason of the ```Error ... Hcol library init failed``` from the initial post?
Сan I install it via an evironment variables only? 
Thanks!

**Comment by ggouaillardet** [comment]
If you want to skip the `coll/hcoll` component at runtime (I guess this is what you are asking), you have several options

 - `mpirun --mca coll ^hcoll ...`
 - `export OMPI_MCA_coll=^hcoll`
 - add `coll=^hcoll` in your `/.../etc/openmpi-mca-params.conf`

**Comment by vasslavich** [comment]
@ggouaillardet , thanks very much!

Via the environment variable is exactly what I need. Due to that a changing arguments in a third-party library is very problematic.

My respects!)

**Comment by ggouaillardet** [comment]
@vasslavich good to hear that!

By the way, what happens without the environment variable?
Does the MPI program abort? Or is this just an annoying message?
If the former, this is something we might want to change.

**Comment by vasslavich** [comment]
I assume the communication option should not affect the result correctness. I'm not sure yet that the third-party MPI program handles this case correctly, if ```coll/hcoll``` is not disabled explicity. It should be checked. The source code is very large and haves many scripts with invocations of ```mpirun```.
