### ISSUE TITLE
with SLURM

### ISSUE THREAD

**Issue by vasslavich** [open-mpi/ompi#9767]
Hello, dear colleagues!

I'm having the question.
I use NVIDIA HPC SDK 21.9 docker container with pre-installed OpenMPI 4.1.2. I need run my jobs via SLURM. Can I do it without a need reconfigure (+rebuild) OpenMPI (https://www.open-mpi.org/faq/?category=slurm)? For example, via environment variables or configuration files.

Thanks!

**Comment by rhc54** [comment]
You should ask them - it all depends on how they built OMPI.

**Comment by vasslavich** [comment]
Ok, thank you!
