### ISSUE TITLE
Compile: latest updates result in pmix being rejected with complaints about NVIDIA

### ISSUE THREAD

**Issue by tonycurtis** [open-mpi/ompi#9778]
Thank you for taking the time to submit an issue!

## Background information

Compiling latest HEAD, configure aborts with message as below.  System with no GPUs, have explicitly specified `--without-cuda` on ompi `configure` command-line to make sure.  UCX is indeed in location given with `--with-ucx=`.  Built OK 2 days ago.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

git master @ f500f8d56e6c4c98fcd7198e3ea3c46775bedfd4

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

```
$ git submodule status
 0afdd41215da9590e848aa25d738bc46871967f9 3rd-party/openpmix (v1.1.3-3315-g0afdd412)
 9f43d8e81534d88de3a0923095e17458328b8cb7 3rd-party/prrte (psrvr-v2.0.0rc1-4131-g9f43d8e815)
```

### Please describe the system on which you are running

* Operating system/version:  CentOS 8.1.1911
* Computer hardware: aarch64
* Network type: IBV

-----------------------------

## Details of the problem

```
--- MCA component pnet:nvd (m4 configuration macro)
checking for MCA component pnet:nvd compile mode... static
checking for header include/ucp/api/ucp.h in pmix_ucx_dir... no
checking for header include/ucp/api/ucp.h in pmix_ucx_dir/include... no
: error: NVIDIA support requested but UCX not found.  Aborting
configure: ===== done with 3rd-party/openpmix configure =====
configure: error: Could not find viable pmix build.
```

**Comment by rhc54** [comment]
Fix is coming: https://github.com/openpmix/openpmix/pull/2429
