### ISSUE TITLE
MIX ERROR: UNREACHABLE in file server/pmix_server.c

### ISSUE THREAD

**Issue by abhisheks1460** [open-mpi/ompi#9785]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

mpirun (Open MPI) 4.1.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

source/distribution tarball,

### Please describe the system on which you are running

* Operating system/version:  CentOS Linux release 7.6.1810 (Core)
* Computer hardware:  Bull Sequana xh2000 with Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
* Network type: private network

-----------------------------

## Details of the problem

I submitted a job and it run up to  some 90% and then it stops. 
with output error.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[cn007.24154] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2147
[cn007.24154] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2147
[cn007.24154] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2147
[cn007.24154] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2147
[cn007.24154] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2147
[cn007.24154] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2147
[cn007.24154] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2147
[cn007.24154] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2147
[cn007.24154] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2147
[cn007.24154] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2147
[cn007.24154] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2147
[cn007.24154] 266 more processes have sent help message help-mpi-api.txt / mpi-abort
[cn007.24154] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

real 304m0.888s
user 14505m34.166s
sys 30m36.621s
At line 498 of file tool/prg_ico2ll.f90 (unit = 9, file = '..//la_tg.rgn00015')

**Comment by rhc54** [comment]
Could you please tell us something about this job? How many processes, how many nodes, what is it doing, how was it launched, etc? All you've told us is that you ran something that didn't work.
