### ISSUE TITLE
question on alltoall collectives

### ISSUE THREAD

**Issue by Young768** [open-mpi/ompi#9791]
Hello, folks. Does MPI support CPU-GPU or GPU-CPU alltoall right now? I am working on deep learning workloads recently. I know that NCCL support GPU-GPU alltoall using GDR. But my input data is first on the CPU. I don't want to do the copy from CPU to GPU and call NCCL later, which introduces overhead on PCIe.

**Comment by bosilca** [comment]
I know this is a little late, but we've been running OMPI master with an FFT on a mixed setup and things work as expected. I will close this ticket.
