### ISSUE TITLE
pkg-config escapes "@{libdir}" when reading OpenPMIx Libs.private

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#9807]
I noticed yesterday that compiling `ompi_info` complained about an unknown escape sequence:

```
  CC       param.o
param.c: In function ‘ompi_info_do_config’:
param.c:618:23: warning: unknown escape sequence: '\{'
                       WRAPPER_EXTRA_LDFLAGS);
                       ^~~~~~~~~~~~~~~~~~~~~
param.c:618:23: warning: unknown escape sequence: '\}'
```

It took a little bit to track this back down to the root cause, but it's apparently that `pkg-config` (including the most recent version 0.29.2, which was released in 2017) takes this `pmix.pc` source file (artificially wrapped for easier reading):

```
$ grep Libs.private ~/bogus-extra/lib/pkgconfig/pmix.pc
Libs.private: -L/home/jsquyres/libevent-current/install/lib -L/home/jsquyres/bogus-extra/lib  \
    -Wl,-rpath -Wl,/home/jsquyres/libevent-current/install/lib \
    -Wl,-rpath -Wl,/home/jsquyres/bogus-extra/lib \
    -Wl,-rpath -Wl,@{libdir} \
    -Wl,--enable-new-dtags -levent_core -levent_pthreads -lhwloc
```

And emits it as this (artificially wrapped blah blah):

```
$ pkg-config --static --libs-only-L --libs-only-other pmix
-L/home/jsquyres/bogus-extra/lib -L/home/jsquyres/libevent-current/install/lib \
    -L/home/jsquyres/bogus-extra/lib \
    -Wl,-rpath -Wl,/home/jsquyres/libevent-current/install/lib \
    -Wl,-rpath -Wl,/home/jsquyres/bogus-extra/lib \
    -Wl,-rpath -Wl,@\{libdir\} \
    -Wl,--enable-new-dtags 
```

Specifically, there's a token `@{libdir}` in the `pmix.pc` file, but `pkg-config` chooses to emit it as `@\{libdir\}`.

This escaped value ultimately ends up in `$OMPI_WRAPPER_EXTRA_LDFLAGS` and `mpicc-wrapper-data.txt`.  Indeed, we actually end up with *2* copies of `@{libdir}` in `$OMPI_WRAPPER_EXTRA_LDFLAGS`: one that is escaped and one that is not (because the "uniq" code treated those two tokens as unique / different).  Artificially wrapped the output below for a little easier reading:

```
OMPI_WRAPPER_EXTRA_LDFLAGS='-L/opt/cisco/libfabric/lib -L/home/jsquyres/bogus/lib \
    -Wl,-rpath -Wl,@\{libdir\}  -Wl,-rpath -Wl,@{libdir}  \
    -Wl,-rpath -Wl,/opt/cisco/libfabric/lib -Wl,-rpath -Wl,/home/jsquyres/bogus/lib -Wl,--enable-new-dtags'
```

**Comment by jsquyres** [comment]
#9808 is a possible fix.

**Comment by bwbarrett** [comment]
Filed https://github.com/openpmix/openpmix/pull/2431 to fix this issue.

**Comment by jsquyres** [comment]
@bwbarrett Has this been brought into Open MPI's master branch yet, perchance?

**Comment by bwbarrett** [comment]
No; PRs posted in https://github.com/open-mpi/ompi/pull/9872 and https://github.com/open-mpi/ompi/pull/9873.

**Comment by jsquyres** [comment]
This is now moot.  Better PRs have been posted and merged.
