### ISSUE TITLE
Update to the latest stable hwloc

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#981]
Title says it all.

@bgoglin We (@jsquyres @bosilca) are waiting for a v1.11.1 release -- is that coming soon?

**Comment by bgoglin** [comment]
I can do a rc1 by the end of the week, and hopefully final 1.11.1 next week. What's your deadline?

**Comment by bosilca** [comment]
soon ... About 1 week away.

**Comment by jsquyres** [comment]
@bgoglin your timeline sounds good

**Comment by bgoglin** [comment]
rc1 is out :)

**Comment by bgoglin** [comment]
hwloc 1.11.1 is out, enjoy :)
