### ISSUE TITLE
Bring UCX PML and SPML in

### ISSUE THREAD

**Issue by bosilca** [open-mpi/ompi#982]
This is a placeholder for bringing in the UCX MTL before the 2.0 deadline. The deadline is tight so if we make good, otherwise @jsquyres will remove the blocker flag and move this issue to the next (v2.1) milestone.

@yosefe, @bosilca, @shamisp

**Comment by bosilca** [comment]
This operation is ongoing in open-mpi/ompi#1008.

**Comment by hppritcha** [comment]
I think this issue can be closed, no?
