### ISSUE TITLE
Fix MXM shutdown procedure in v1.10 series

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#985]
open-mpi/ompi-release#644 did not fix the MXM shutdown procedure; something isn't quite right in hcoll.

@miked-mellanox says they're working on a fix.  Opening this issue just to track it.

**Comment by bureddy** [comment]
submitted PR : https://github.com/open-mpi/ompi-release/pull/647

**Comment by jsquyres** [comment]
Commit fixed in v1.10 branch.
