### ISSUE TITLE
CUDA-awareness with Tegra chips

### ISSUE THREAD

**Issue by saulocpp** [open-mpi/ompi#9851]
I am working on a small cluster of Jetson Xavier NX modules and distributing the load with OMPI.
The library version is v2.1.1 and it comes as default with Ubuntu 18.04 in the JetPack 4.6. After querying the lib for cuda-awareness, it shows as negative so I decided to compile from source using --with-cuda.
After installing and fixing a few paths/symlinks so the compiler finds the proper headers, the test program says it is cuda-aware for compile-time (really just checking the presence of MPIX_CUDA_AWARE_SUPPORT == 1), but not for run-time (MPIX_Query_cuda_support() != 1).

After providing more detailed information at [nvidia forum](https://forums.developer.nvidia.com/t/jetpack-with-cuda-aware-ompi-could-be-default/199891), the moderator suggested that cuda-aware features are possibly meant to be used with discrete GPUs, and not Tegras (like gdrcopy). Is it really the case?

Thanks.

**Comment by jsquyres** [comment]
@janjust Can someone from NVIDIA answer?

**Comment by jsquyres** [comment]
@open-mpi/cuda Can someone from NVIDIA answer?

**Comment by saulocpp** [comment]
I have discussed this topic at NV's forum and both the moderator and I tried different things to test the cuda-awareness of OMPI on Tegra, but it looks like it is not yet supported (or not possible, I don't know).
In case anyone is interested in the discussion and the outcome, the thread is [this one](https://forums.developer.nvidia.com/t/jetpack-with-cuda-aware-ompi-could-be-default/199891).

I included a minimally "working" program that tries to send a bit of data from RAM in one Tegra to the GPU allocation of another Tegra, resulting in a bad address error when executing.
In case you don't have a couple of Jetsons handy and still want something tested, just let me know.

Thanks.

**Comment by janjust** [comment]
@Akshay-Venkatesh, when you get a chance could you look through the linked forum and its conclusion? I will close this issue for now due to discussion [here](https://forums.developer.nvidia.com/t/jetpack-with-cuda-aware-ompi-could-be-default/199891).
If this is a critical item, I suggest opening a feature request.

**Comment by saulocpp** [comment]
@janjust is it ok if I update the topic?
In the NV thread mentioned, the moderator made the cuda-aware data copy work on his Tegra setup and so did I, after fixing a few paths due to differences in installation. However, even with the copy working and the remote Tegra printing the right value to confirm the copy, I get the following message:

```
rank 1: receive
--------------------------------------------------------------------------
The call to cuMemHostRegister(0x7f8590ae28, 4, 0) failed.
  Host:  EVH5150
  cuMemHostRegister return value:  801
  Registration cache:  checkmem
--------------------------------------------------------------------------
rank 0: host->device and send
15.50000
```

EVH5150 is the host receiving the data copy in its GPU memory and printing the value 15.5 from the kernel function. Any idea on the circumstance this happens?
The program to reproduce is below, and it just prints the last element of an array previously filled in host 0 and transferred to host 1 GPU allocated memory:

```
#include <cstdio>
#include <mpi.h>
#include <cuda.h>
#include <cuda_runtime.h>

__global__ void print_val(float *data, const int LEN);

int main(int argc, char **argv)
{
	const int	LENGTH		= 32;
	int		mpi_rank	= 0,
			mpi_size	= 0;
	float		host_data[LENGTH],
			*dev_data;

	MPI_Init(&argc, &argv);

	MPI_Comm_rank(MPI_COMM_WORLD, &mpi_rank);
	MPI_Comm_size(MPI_COMM_WORLD, &mpi_size);

	if(mpi_rank == 0)
		for(int i = 0; i < LENGTH; i++)
			host_data[i] = (float) i * 0.5f;

	cudaMalloc((void **) &dev_data, LENGTH * sizeof(float));
	cudaMemset(&dev_data, LENGTH * sizeof(float), 0);

	if(mpi_rank == 0)
	{
		printf("rank 0: host->device and send\n");
		cudaMemcpy(dev_data, host_data, LENGTH * sizeof(float), cudaMemcpyHostToDevice);
		MPI_Send(dev_data, LENGTH, MPI_FLOAT, 1, 0, MPI_COMM_WORLD);
	}

	if(mpi_rank == 1)
	{
		printf("rank 1: receive\n");
		MPI_Recv(dev_data, LENGTH, MPI_FLOAT, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
		//cudaMemcpy(dev_data, host_data, LENGTH * sizeof(float), cudaMemcpyHostToDevice); // uncomment if receiving in host_data
		print_val <<< 1, 1 >>> (dev_data, LENGTH);
	}

	cudaFree(dev_data);

	MPI_Finalize();
	
	return 0;
	}

__global__ void print_val(float *data, const int LEN)
{
	printf("%.5f\n", data[LEN - 1]);
}
```
2 Tegras will be needed for that, so let me know if you need something tested on my side. I am updating both NV and OMPI topics as the information comes.
Thanks.

**Comment by janjust** [comment]
@saulocpp 
> is it ok if I update the topic?
Sure
@open-mpi/cuda fyi

**Comment by Akshay-Venkatesh** [comment]
@janjust @saulocpp 

I'll look into possible cumemhostregister limitations on tegra. Looking at the forum post and the output here, it doesn't look like ucx is being used.

@saulocpp in the past I had run openmpi(3.x) and ucx(1.8?) versions on a Jetson nano and my tests were working. I'll try and find the recipe and post here.

**Comment by saulocpp** [comment]
@Akshay-Venkatesh thanks for your time looking into this.
And just to complement with information you may want to know, both the moderator at NV forum and I are using the latest versions available from git, that is, ucx 1.11 and ompi 5.1 (if I'm not mistaken), compiled with ucx support on JetPack 4.6 and an existing ompi v2.1 installation from Ubuntu factory (this one built without cuda-awareness support, hence this endeavor).
If you need any action from my side, let me know.

**Comment by Akshay-Venkatesh** [comment]
@saulocpp Can you provide the output of ` cudaDeviceGetAttribute` with `cudaDevAttrHostRegisterSupported` attribute? It maybe the case that HostRegister is unsupported on your platform. Refer [I/O Coherency](https://docs.nvidia.com/cuda/cuda-for-tegra-appnote/index.html#io-coherency)

**Comment by saulocpp** [comment]
@Akshay-Venkatesh , first of all, thanks for your reply.
I think you nailed. This function returns 1 for this attribute on a Jetson Xavier NX (Volta) but 0 on a Jetson Nano (Maxwell), which is part of my cluster.
I will read the doc you referred to but already saw that "I/O coherency is supported on Tegra devices starting with Xavier SOC".

In this direction, if I am manually allocating pinned memory in host 1 and copying from host 0 GPU memory straight to host 1 GPU memory, OpenMPI is doing its own intermediate allocation for this copy to happen, thus making my allocation redundant/unnecessary?

**Comment by Akshay-Venkatesh** [comment]
>In this direction, if I am manually allocating pinned memory in host 1 and copying from host 0 GPU memory straight to host 1 GPU memory, OpenMPI is doing its own intermediate allocation for this copy to happen, thus making my allocation redundant/unnecessary?

As there isn't a way for UCX/OpenMPI to know about user allocated pinned memory, UCX would have to make its own allocation and use/reuse these buffers for staging over subsequent transfers. IIUC, you're right that you don't have to additionally allocate pinned host memory manually.

**Comment by saulocpp** [comment]
@Akshay-Venkatesh thanks for your input on all of this and ultimately pointing me to the issue.
Your last comment on the buffer and copy scratched the surface of UCX, which now prompts me to read some documentation to understand the persistence of its buffers, such as predicting a copy on the way back and avoiding a new allocation, and rethink my resource management policy.
I will update the topic at NV forum with the info obtained here and we are all done.
Thanks to all.

**Comment by janjust** [comment]
Closing, topic updated at the NV forum.
