### ISSUE TITLE
Add AlltoAll interface to HCOLL for 1.10.1 

### ISSUE THREAD

**Issue by jladd-mlnx** [open-mpi/ompi#986]
Adding a place holder.

**Comment by jladd-mlnx** [comment]
bot:milestone:v1.10.1

**Comment by jsquyres** [comment]
@jladd-mlnx What is the timing of this feature?

**Comment by jladd-mlnx** [comment]
@jsquyres We will have a PR in the next day.

**Comment by jladd-mlnx** [comment]
@jsquyres this is small change contained entirely within coll/hcoll.

**Comment by bureddy** [comment]
very minor change
PR: https://github.com/open-mpi/ompi-release/pull/650

**Comment by jsquyres** [comment]
Closed by open-mpi/ompi-release#650.
