### ISSUE TITLE
Add coll/hcoll level fix for hang in finalize on Orion at scale. 

### ISSUE THREAD

**Issue by jladd-mlnx** [open-mpi/ompi#987]
Adding a placeholder.

**Comment by jsquyres** [comment]
@jladd-mlnx How many features are you adding to 1.10.1 at the last second? :frowning:

**Comment by jladd-mlnx** [comment]
@jsquyres Sorry :innocent: - I think this is the last.

**Comment by jladd-mlnx** [comment]
@jsquyres FWIW - this is  a small change contained entirely in the coll/hcoll component.

**Comment by jsquyres** [comment]
K. Whew!

Coming soon?

**Comment by jladd-mlnx** [comment]
Yes. Very soon.

**Comment by jladd-mlnx** [comment]
Closing for now. Appears to be an issue in MXM teardown.
