### ISSUE TITLE
cannot use --enable-mca-dso when building OSHMEM with UCX

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#9875]
I was doing some experimenting with ```--enable-mca-dso``` again and noticed that master no longer appears to build with this configure option and with ```---with-ucx``` when trying to build the OSHMEM libraries:
```
Making install in mca/atomic/ucx
make[2]: Entering directory `/XXX/ompi/oshmem/mca/atomic/ucx'
  CC       atomic_ucx_module.lo
make[2]: *** No rule to make target `/XXX/ompi/opal/mca/common/ucx/open-palmca_common_ucx.la', needed by `mca_atomic_ucx.la'.  Stop.
```
If I don't use the ```--enable-mca-dso``` option the build completes nominally.

**Comment by hppritcha** [comment]
@open-mpi/ucx

**Comment by hoopoepg** [comment]
hi @hppritcha 

could you test https://github.com/open-mpi/ompi/pull/9877 ?
thank you

**Comment by hppritcha** [comment]
This fixes the issue.  thanks!
