### ISSUE TITLE
Need to add volatile to some globals to workaround gcc bug

### ISSUE THREAD

**Issue by rolfv** [open-mpi/ompi#988]
All the details are contained in this thread from the User's list. Looks like we planned on adding the workaround, but it never happened. I just had a second user run into this issue.
http://www.open-mpi.org/community/lists/users/2015/06/27039.php

I would like to make this a blocker for Open MPI 1.10.1.

**Comment by jsquyres** [comment]
Oy.  Things really crawl out of the walls when we announce we want to release in the Very Near Future!

Can you make a PR for this ASAP (e.g., by tomorrow)?

**Comment by jsquyres** [comment]
BTW, I assume you're going to read the history about this on #625.  Some solutions were proposed on there, IIRC.

**Comment by rolfv** [comment]
Yes, I read all the notes and both you and Dave Goodall already gave a thumbs up to the user of volatile. And the GCC guy also said to make it volatile. That is 3 yes votes! I will work on making it find its way through the 3 releases.

**Comment by rolfv** [comment]
I misread what you were pointing too. I was reading the email thread, not the thread from #625. I was not quite sure what your "softer" suggestion was.

**Comment by jsquyres** [comment]
See https://github.com/open-mpi/ompi/pull/625#issuecomment-110097661 and https://github.com/open-mpi/ompi/pull/625#issuecomment-110225915.

**Comment by rolfv** [comment]
Are suggesting making the whole structure volatile? Because then you are making things volatile that are unnecessary.  Or am I missing something.

**Comment by jsquyres** [comment]
I think we never resolved which of the two approaches was better.  :smile:

**Comment by jsquyres** [comment]
Whichever you do, please submit a PR *today*

**Comment by rolfv** [comment]
Right, I am just trying to implement your solution to see if it works but I am not exactly sure what you mean. I have shown the volatile fixes it with the 4.9.2 compiler. @jsquyres

**Comment by jsquyres** [comment]
I don't know which way is better -- e.g., are there side effects of making the whole struct volatile that could impact performance, etc.

**Comment by rolfv** [comment]
This is clearly not going to make it and I am mostly against these last minute things anyways, so I will remove the blocker from this.  Maybe 10.0.2......

**Comment by jsquyres** [comment]
@rolfv FWIW, we have no idea if there will ever be a 1.10.2.  So I think it would be ok to put in to 1.10.1.

**Comment by rolfv** [comment]
Well, miracles do happen and this has made it into master, 2.0.0, and 10.0.1.  Closing this bug.
