### ISSUE TITLE
MCA pml_ucx_tls has no effect

### ISSUE THREAD

**Issue by gkatev** [open-mpi/ompi#9889]
Hi, I'm under the impression that something like `--mca pml_ucx_tls tcp,self` will instruct UCX to only use these TLs -- is this correct? Instead, the parameter does not seem to have any effect.

Setup:
```
Open MPI v5.0.x (#9605bed)
UCX v1.12.0 (also used to happen on v1.11.2)
```
I would expect the following to fail, but it does not:
```
$(which mpirun) --host localhost:2 --mca coll libnbc,basic --mca pml ucx --mca pml_ucx_tls self osu_bcast
```
Or, there's no performance difference switching from `--mca pml_ucx_tls sm,self` to `--mca pml_ucx_tls tcp,self`.

If I instead set the `UCX_TLS` env var appropriately, the above scenarios do have the expected result (1st fails, 2nd has significant performance difference).

**Comment by brminich** [comment]
No, its meaning is to specify required transports support for UCX pml to be selected:
```
$ompi_info -all | grep -A 1 pml_ucx_tls
             MCA pml ucx: parameter "pml_ucx_tls" (current value: "any", data source: file (/hpc/local/benchmarks/daily/future/2022-01-19/hpcx-gcc-redhat7/ompi/etc/openmpi-mca-params.conf:64), level: 3 user/all, type: string, synonym of: opal_common_ucx_tls)
                          List of UCX transports which should be supported on the system, to enable selecting the UCX component. Special values: any (any available). A '^' prefix negates the list. For example, in order to exclude on shared memory and TCP transports, please set to '^posix,sysv,self,tcp,cma,knem,xpmem'.
```

**Comment by gkatev** [comment]
Ahh okay I see, thanks!
