### ISSUE TITLE
MPI_Comm_size always returns 1 (v5.0.0 only)

### ISSUE THREAD

**Issue by hatmer** [open-mpi/ompi#9902]
## Background information

I am trying out Open MPI v5.0.0 and have found a bug.

### What version of Open MPI are you using?

v5.0.0

### Describe how Open MPI was installed

tarball

### Please describe the system on which you are running

* Operating system/version: Linux 4.19.0-18-cloud-amd64

-----------------------------

## Details of the problem

When I run a simple MPI connectivity test program, Open MPI version 5.0.0 seems to have a bug where MPI_Comm_size is always 1. I ran the same program with Open MPI verions 4.1.2 and 5.0.0, and got different results. I understand that v5.0.0 is still a work in progress, I just thought I would submit a bug report if that is helpful.

```shell
$ ~/openmpi4/bin/mpirun --hostfile hosts -n 2 ./test.out
I am node A, 0 of 2
I am node B, 1 of 2
$ ~/openmpi5/bin/mpirun --hostfile hosts -n 2 ./test.out
I am node A, 0 of 1
I am node B, 0 of 1
```

test.cpp (on node A)
```c++
#include <stdio.h>
#include <stdlib.h> 
#include "mpi.h"

int main(int argc, char* argv[])
{
    int rank, size;
    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);
    printf("I am node A, %d of %d\n", rank, size);
    MPI_Barrier(MPI_COMM_WORLD);
    MPI_Finalize();
    return 0;
}
```

**Comment by jsquyres** [comment]
This type of error *usually* means a mismatch of libraries.

Your example implies that you're using the same `test.out` executable with both Open MPI v4.x's `mpirun` and Open MPI v5.x's `mpirun`.  Is that a correct assumption, or was your sample output abbreviated?

If you did use the same `test.out` in both cases, I'm not entirely surprised that an Open MPI v4.x-compiled `test.out` misbehaved with Open MPI v5.x's `mpirun` (I'm actually surprised that it nominally worked at all).

Can you verify that you have two different `test.out` executables, each compiled by their respective Open MPI installation?

**Comment by hatmer** [comment]
You are correct that I had not recompiled the test executable with the v5.0.0 mpic++. It works correctly now, thank you for your help.
