### ISSUE TITLE
mpirun fails when PRRTE is external

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#9917]
This is observed on both master and v5.0 branches. If you configure OMPI to use an external PRRTE installation, then there is no `prterun` installed in the OMPI prefix/bin location. Thus, if you attempt to execute `mpirun` using a path (absolute or relative - the key is to prefix a command with a path), then `mpirun` will attempt to fork/exec `prterun` using that same path. This fails with the error that `prterun` could not be found.

I had provided a patch that addressed this by prefixing `prterun` with the `--with-prrte=<foo>` path when that path was specified (and not "internal" or "external"), but people didn't seem enamored with it so I took it down. Something should probably be done, however, since external PRRTE is the way system installations installed via rpm will look - and anyone providing a path to `mpirun` will simply get errors. Might be as simple as creating a `prterun` symlink in the OMPI prefix/bin directory pointing back to the external executable.

**Comment by awlauria** [comment]
Opened https://github.com/open-mpi/ompi/pull/9959 to potentially address this in master.

**Comment by awlauria** [comment]
Master and v5.0.x PR's merged - closing.
