### ISSUE TITLE
Build error with 4.1.2

### ISSUE THREAD

**Issue by shefty** [open-mpi/ompi#9920]
I have a new download of 4.1.2.

```
 ./configure --prefix=/home/mshefty --enable-mpi-fortran=no --with-libfabric=/home/mshefty
make -j
```
which leads to several errors of this nature:
```
/mca/common'
Making all in mca/bfrops
make[5]: Entering directory `/home/mshefty/src/openmpi-4.1.2/opal/mca/pmix/pmix3x/pmix/src/mca/bfrops'
  CC       base/bfrop_base_frame.lo
  CC       base/bfrop_base_fns.lo
  CC       base/bfrop_base_select.lo
  CC       base/bfrop_base_copy.lo
  CC       base/bfrop_base_pack.lo
  CC       base/bfrop_base_print.lo
  CC       base/bfrop_base_stubs.lo
  CC       base/bfrop_base_unpack.lo
In file included from /home/mshefty/src/openmpi-4.1.2/opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.h:30:0,
                 from base/bfrop_base_copy.c:28:
/home/mshefty/src/openmpi-4.1.2/opal/mca/pmix/pmix3x/pmix/src/include/types.h:48:27: fatal error: opal/mca/event/libevent2022/libevent2022.h: No such file or directory
 #include PMIX_EVENT_HEADER
```
I also have a git clone, with the 4.1.2 release checked out (based on the tag).  It produces the same error.  (I can't build master because it wants pandoc which isn't installed on my system).

**Comment by awlauria** [comment]
Regarding master, for now there is a `--disable-man-pages` configure option that will allow it to build.

Can you paste share your configure output?

**Comment by shefty** [comment]
[config.txt](https://github.com/open-mpi/ompi/files/7935863/config.txt)

**Comment by shefty** [comment]
FWIW, I get the same build error with v4.0.7.  I'm trying to see how other developers in my group have successfully built openmpi.  If I copy the 'missing' file (it's there) into my include path, the error moves to the next 'missing' include file in line.  I've tried setting CFLAGS -I hoping that would force the pick-up of the include path, but that didn't work.

**Comment by j-xiong** [comment]
Have you tried "make V=1" to see the full compiler command line?

**Comment by shefty** [comment]
Quick update: Alexia logged into the same system using the same account as me and was able to build.  She used a github generated tarball, rather than the release tarball.  I tried to duplicate, and hit my same build issue.  So, we have that going for us.

**Comment by shefty** [comment]
This works on my system:
```
./configure --prefix=/home/mshefty/ompi --disable-oshmem --enable-mpi-fortran=no --with-libfabric=/home/mshefty
make -j
```
this does not:
```
./configure --prefix=/home/mshefty --disable-oshmem --enable-mpi-fortran=no --with-libfabric=/home/mshefty
```
why the prefix matters is beyond me, but that's where things landed.  My /home/mshefty directory is very boring.  (I'm on a system that I rarely use.)

**Comment by bwbarrett** [comment]
was the build directory inside /home/mshefty when you ran into trouble?  And was it inside /home/mshefty/ompi when it worked?  I have alarm bells going off that there's a known issue in the autotools when the build tree is inside $prefix, but I'd have to dig to remember the details.

**Comment by shefty** [comment]
I was building from /home/mshefty/src/ompi-4.1.2.  Alexia was building from a different location, but also using a different prefix (to avoid overwriting mine).  When I changed my prefix, the build worked.

**Comment by jsquyres** [comment]
On the surface, that makes no sense to me at all.  FWIW, I do this kind of thing all the time:

```
wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.2.tar.bz2
tar xf openmpi-4.1.2.tar.bz2
cd openmpi-4.1.2
./configure --prefix=`pwd`/install ...
make -j 32 install
```

I could see that there could well be problems if the prefix was the _same_ as the srcdir.  But I've not had problems embedding the prefix in a non-conflicting / non-pre-existing directory inside the srcdir.

For your original error:

```
...
  CC       base/bfrop_base_unpack.lo
In file included from /home/mshefty/src/openmpi-4.1.2/opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.h:30:0,
                 from base/bfrop_base_copy.c:28:
/home/mshefty/src/openmpi-4.1.2/opal/mca/pmix/pmix3x/pmix/src/include/types.h:48:27: fatal error: opal/mca/event/libevent2022/libevent2022.h: No such file or directory
 #include PMIX_EVENT_HEADER
```

We would need to see the output of `make V=1` to see the exact compile command that was being used -- e.g., see if if the appropriate `-I` somehow disappeared.

**Comment by shefty** [comment]
Here's the last section of make output after the 'bad' configure mentioned above.  Let me know if you want the full log:
```
Making all in mca/bfrops
make[5]: Entering directory `/home/mshefty/src/ompi-4.1.2/opal/mca/pmix/pmix3x/pmix/src/mca/bfrops'
depbase=`echo base/bfrop_base_frame.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../../../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../../../src/include -I../../../include   -iquote/home/mshefty/src/ompi-4.1.2/opal/mca/pmix/pmix3x/pmix -iquote/home/mshefty/src/ompi-4.1.2/opal/mca/pmix/pmix3x/pmix/src -I/home/mshefty/src/ompi-4.1.2/opal/mca/pmix/pmix3x/pmix/include -I/home/mshefty/include  -DNDEBUG -O3 -finline-functions -fno-strict-aliasing -mcx16 -pthread -MT base/bfrop_base_frame.lo -MD -MP -MF $depbase.Tpo -c -o base/bfrop_base_frame.lo base/bfrop_base_frame.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../../../src/include -I../../../include -iquote/home/mshefty/src/ompi-4.1.2/opal/mca/pmix/pmix3x/pmix -iquote/home/mshefty/src/ompi-4.1.2/opal/mca/pmix/pmix3x/pmix/src -I/home/mshefty/src/ompi-4.1.2/opal/mca/pmix/pmix3x/pmix/include -I/home/mshefty/include -DNDEBUG -O3 -finline-functions -fno-strict-aliasing -mcx16 -pthread -MT base/bfrop_base_frame.lo -MD -MP -MF base/.deps/bfrop_base_frame.Tpo -c base/bfrop_base_frame.c  -fPIC -DPIC -o base/.libs/bfrop_base_frame.o
In file included from /home/mshefty/src/ompi-4.1.2/opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.h:30:0,
                 from /home/mshefty/src/ompi-4.1.2/opal/mca/pmix/pmix3x/pmix/src/mca/bfrops/base/base.h:42,
                 from base/bfrop_base_frame.c:39:
/home/mshefty/src/ompi-4.1.2/opal/mca/pmix/pmix3x/pmix/src/include/types.h:48:27: fatal error: opal/mca/event/libevent2022/libevent2022.h: No such file or directory
 #include PMIX_EVENT_HEADER
                           ^
compilation terminated.
make[5]: *** [base/bfrop_base_frame.lo] Error 1
make[5]: Leaving directory `/home/mshefty/src/ompi-4.1.2/opal/mca/pmix/pmix3x/pmix/src/mca/bfrops'
```
/home/mshefty/include only contains the libfabric installed headers under rdma subdir.

**Comment by jsquyres** [comment]
Your output is from `./configure --prefix=/home/mshefty --enable-mpi-fortran=no --with-libfabric=/home/mshefty`, right?

Oddly, I get several more `-I`'s than Sean when I compile `bfrop_base_frame.c`.

* These are the same between Sean's build and my build:
    * `-I.`
    * `-I../../../src/include`
    * `-I../../../include`
    * `-iquote/SRCDIR/opal/mca/pmix/pmix3x/pmix`
    * `-iquote/SRCDIR/opal/mca/pmix/pmix3x/pmix/src`
    * `-I/SRCDIR/opal/mca/pmix/pmix3x/pmix/include`
* I have these, but @shefty does not:
    * `-I/SRCDIR`
    * `-I/SRCDIR/opal/include`
    * `-I/SRCDIR/opal/mca/event/libevent2022/libevent`
    * `-I/SRCDIR/opal/mca/event/libevent2022/libevent/include`
    * `-I/SRCDIR/opal/mca/hwloc/hwloc201/hwloc/include`
* Sean has this, but I do not:
    * `-IPREFIX/include` (possibly from `--with-libfabric`... but I don't know why that would be here in PMIx)

@shefty Can you send the `config.log` file and the full output from `make V=1`?

**Comment by shefty** [comment]
Attached should be output from:
```
./configure --prefix=/home/mshefty/ompi --disable-oshmem --enable-mpi-fortran=no --with-libfabric=/home/mshefty
make V=1 |& tee make.txt
```
[config.log](https://github.com/open-mpi/ompi/files/7953423/config.log)
[make.txt](https://github.com/open-mpi/ompi/files/7953426/make.txt)

**Comment by jsquyres** [comment]
This rabbit hole is getting deeper.  ☹️ 

Can you also send opal/mca/pmix/pmix3x/pmix/config.log?

**Comment by shefty** [comment]
config.log from pmix should be attached.  Unfortunately I don't have a way to grant someone external access to this system.

[pmix-config.log](https://github.com/open-mpi/ompi/files/7981124/pmix-config.log)

**Comment by gefei-qian-nih** [comment]
Are you on RHEL7/CentOS7?
The system installed gcc 4.8.5 may not be compatible with it. Try some newer gcc. Gcc version 10.2.9 will solve that particular problem, at least.

**Comment by ggouaillardet** [comment]
There is no gcc 10.2.9.
Also, I was able to build Open MPI 4.1.2 on my CentOS7 workstation with the stock gcc 4.8.5.

**Comment by ggouaillardet** [comment]
got it :-)

from  PMIx `config.log`

```
configure:2925: loading site script /home/mshefty/share/config.site
| CPPFLAGS=-I$HOME/include
| LDFLAGS=-L$HOME/lib
```

I suspect this overwrites `CPPFLAGS` (causing `-I/home/mshefty/src/ompi-4.1.2` to be removed and hence the failure).
This also explains why you do not have this error when you use a different prefix (that does not contain a `share/config.site`)

**Comment by shefty** [comment]
@ggouaillardet - That's it.  I don't know how that file got there (it's 5 years old), but that's overwriting those flags.

**Comment by gefei-qian-nih** [comment]
Confirmed. A clean centos7 does not have this problem. I may have other issues on my system.
