### ISSUE TITLE
V5.0.x / master: reports that cuda is not run-time loadable

### ISSUE THREAD

**Issue by bwbarrett** [open-mpi/ompi#9933]
In https://github.com/open-mpi/ompi/issues/9906 (which started out as a CUDA on 4.1.x problem), there is a discussion that on master (and therefore 5.0.x), it is no longer possible to build Open MPI with cuda support and run on platforms without cuda installed, due to deb37ac.  We need to verify this and fix any regressions in that configuration.

**Comment by wckzhang** [comment]
ACK, will work on this in February

**Comment by gpaulsen** [comment]
@wckzhang How is this going?

**Comment by artemry-nv** [comment]
Looks like we observed the similar issue with Open MPI from v5.0.x built on RHEL 7.x - libmpi.so depends on libcudart.so
Interesting that there's no such dependency on Ubuntu.

**Comment by awlauria** [comment]
@janjust can this be closed by: https://github.com/open-mpi/ompi/pull/10196

**Comment by janjust** [comment]
Closed with #10196
